Documentation: ssl_common/include/ssl_common/util.h File Reference
util.h File Reference
#include <math.h>
#include <string.h>
#include <algorithm>
Macros
#define __UTIL_H__
#define UnusedVar
#define MustUseResult
#define M_2PI 6.28318530717958647693
#define likely(x) (x)
#define unlikely(x) (x)
Functions
template<class num1 , class num2 >
num1 bound (num1 x, num2 low, num2 high)
template<class num1 , class num2 >
num1 abs_bound (num1 x, num2 range)
template<class num >
num abs_max (num a, num b)
template<class num >
num abs_min (num a, num b)
template<class num >
num max3 (num a, num b, num c)
template<class num >
num min3 (num a, num b, num c)
template<class num >
num max4 (num a, num b, num c, num d)
template<class num >
num min4 (num a, num b, num c, num d)
template<class num >
num max_abs (num a, num b)
template<class num >
num min_abs (num a, num b)
template<class data_t >
int max_idx (data_t *arr, int num)
template<class data_t >
int min_idx (data_t *arr, int num)
template<class num >
void sort (num &a, num &b, num &c)
template<class num >
bool take_min (num &base, num val)
template<class num >
bool take_max (num &base, num val)
template<class real >
real sq (real x)
template<class real >
real cube (real x)
template<class num >
num sign_nz (num x)
template<class num >
num sign_eq (num a, num b)
template<class num >
num sign (num x)
template<class bool_t >
void toggle (bool_t &b)
template<class num >
bool one_bit_set (num n)
template<class num >
num gcd (num x, num y)
template<class num >
num lcm (num x, num y)
template<class num >
num mod (num x, num m)
template<class real >
real fmodt (real x, real m)
template<class real >
real ramp (real x, real x0, real x1)
template<class real >
real ramp (real x, real x0, real y0, real x1, real y1)
template<class num , class num2 >
num bool_sat_count (num cnt, num2 min, num2 max, bool val)
template<class num1 , class num2 >
bool all_bits_set (num1 x, num2 m)
template<class num1 , class num2 >
bool any_bits_set (num1 x, num2 m)
template<class real >
real angle_mod (real angle)
template<class real >
real angle_long (real angle)
template<class real >
real angle_pos (real angle)
template<class real >
real angle_diff (real a, real b)
template<class real >
real angle_dist (real a, real b)
template<class real >
real avg_angle (real left, real right)
template<class real >
real abs_bound_angle (real bound_angle, real tolerance, real a)
template<class data >
int find_item (const data *arr, int num, data key)
template<class data , class num >
data * alloc_array (data *arr, num &size, num new_size)
template<class data , class num >
data * resize_array (data *arr, num &size, num new_size, num cur_used)
template<class data , class num >
void free_array (data *&arr, num &size)
template<class data , class num >
data * alloc_array2 (data *arr, num &w, num &h, int new_w, int new_h)
template<class data >
void set_range (data *arr, int start, int num, const data &val)
template<class data >
int mcopy (data *dest, data *src, int num)
template<class data >
data mset (data *dest, data val, int num)
template<class data >
void mzero (data &d)
template<class data >
void mzero (data *d, int n)
Macro Definition Documentation
#define __UTIL_H__
Definition at line 23 of file util.h.
#define likely (x) (x)
Definition at line 552 of file util.h.
#define M_2PI 6.28318530717958647693
Definition at line 42 of file util.h.
Referenced by angle_diff(), angle_long(), angle_mod(), and angle_pos().
#define MustUseResult
Definition at line 37 of file util.h.
Referenced by any_bits_set(), avg_angle(), bound(), find_item(), free_array(), sq(), and take_max().
#define unlikely (x) (x)
Definition at line 553 of file util.h.
#define UnusedVar
Definition at line 36 of file util.h.
Function Documentation
template<class num1 , class num2 > num1 abs_bound (num1 x, num2 range) inline
Definition at line 91 of file util.h.
 {
   if(x < -range) x = -range;
   if(x >  range) x =  range;
   return(x);
 }
template<class real > real abs_bound_angle (real bound_angle, real tolerance, real a)
Definition at line 422 of file util.h.
References abs_bound(), angle_mod(), and role._GoToPoint::x.
 {
   real x = angle_mod(a - bound_angle);
   x = abs_bound(x,tolerance);
   return(angle_mod(x + bound_angle));
 }
template<class num > num abs_max (num a, num b) inline
Definition at line 100 of file util.h.
 {
   return((fabs(a) > fabs(b))? a : b);
 }
template<class num > num abs_min (num a, num b) inline
Definition at line 106 of file util.h.
 {
   return((fabs(a) < fabs(b))? a : b);
 }
template<class num1 , class num2 > bool all_bits_set (num1 x, num2 m)
Definition at line 337 of file util.h.
 {
   return((x & m) == m);
 }
template<class data , class num > data* alloc_array (data * arr, num & size, num new_size)
Definition at line 443 of file util.h.
 {
   if((arr!=NULL && new_size==size) ||
      (arr==NULL && new_size==0)) return(arr);
   delete[](arr);
   arr = new data[new_size];
   size = (arr != NULL)? new_size : 0;
   return(arr);
 }
template<class data , class num > data* alloc_array2 (data * arr, num & w, num & h, int new_w, int new_h)
Definition at line 486 of file util.h.
 {
   int size = w * h;
   int new_size = new_w * new_h;
   if((arr!=NULL && new_size==size) ||
      (arr==NULL && new_size==0)) return(arr);
   delete[](arr);
   arr = new data[new_size];
   if(arr){
     w = new_w;
     h = new_h;
   }else{
     w = h = 0;
   }
   return(arr);
 }
template<class real > real angle_diff (real a, real b)
Definition at line 384 of file util.h.
References M_2PI.
 {
   real d;
   d = a - b;
   d -= M_2PI * rint(d / M_2PI);
   return(d);
 }
template<class real > real angle_dist (real a, real b)
Definition at line 396 of file util.h.
References angle_mod().
 {
   return(fabs(angle_mod(a-b)));
 }
template<class real > real angle_long (real angle)
Definition at line 366 of file util.h.
References M_2PI.
 {
   if (angle < 0.0) {
     return M_2PI + angle;
   } else {
     return -M_2PI + angle;
   }
 }
template<class real > real angle_mod (real angle)
Definition at line 357 of file util.h.
References M_2PI.
 {
   angle -= M_2PI * rint(angle / M_2PI);
   return(angle);
 }
template<class real > real angle_pos (real angle)
Definition at line 377 of file util.h.
References M_2PI.
 {
   return(fmod(angle+M_2PI,M_2PI));
 }
template<class num1 , class num2 > bool any_bits_set (num1 x, num2 m)
Definition at line 344 of file util.h.
References angle_mod(), and MustUseResult.
 {
   return((x & m) != 0);
 }
template<class real > real avg_angle (real left, real right)
Definition at line 404 of file util.h.
References abs_bound_angle(), and MustUseResult.
 {
   real result;
   if(left < right) left += 2*M_PI;
   result = (left + right)/2;
   if(result > M_PI) result -= 2*M_PI;
   return(result);
 }
template<class num , class num2 > num bool_sat_count (num cnt, num2 min, num2 max, bool val)
Definition at line 322 of file util.h.
 {
   if(val){
     return((cnt < max)? cnt+1 : max);
   }else{
     return((cnt > min)? cnt-1 : min);
   }
 }
template<class num1 , class num2 > num1 bound (num1 x, num2 low, num2 high) inline
Definition at line 80 of file util.h.
References abs_bound(), MustUseResult, and role._GoToPoint::x.
 {
   if(x < low ) x = low;
   if(x > high) x = high;
   return(x);
 }
template<class real > real cube (real x)
Definition at line 224 of file util.h.
 {
   return(x * x * x);
 }
template<class data > int find_item (const data * arr, int num, data key)
Definition at line 432 of file util.h.
References alloc_array(), velocity.pid_::i, and MustUseResult.
 {
   int i = 0;
   while(i<num && !(arr[i]==key)) i++;
   return(i);
 }
template<class real > real fmodt (real x, real m)
Definition at line 294 of file util.h.
 {
   return(x - floor(x / m)*m);
 }
template<class data , class num > void free_array (data *& arr, num & size)
Definition at line 474 of file util.h.
References alloc_array2(), and MustUseResult.
 {
   delete[](arr);
   arr = NULL;
   size = 0;
 }
template<class num > num gcd (num x, num y)
Definition at line 261 of file util.h.
References role._GoToPoint::x, and role._GoToPoint::y.
 {
   int w;
   while (y != 0) {
     w = x % y;
     x = y;
     y = w;
   }
   return x;
 }
template<class num > num lcm (num x, num y)
Definition at line 275 of file util.h.
References gcd().
 {
   num d = gcd(x,y);
   num r = (x / d) * (y / d);
   // num r = (x * y) / d; // faster but more likely to overflow
   return(r);
 }
template<class num > num max3 (num a, num b, num c) inline
Definition at line 112 of file util.h.
 {
   if(a > b){
     return((a > c)? a : c);
   }else{
     return((b > c)? b : c);
   }
 }
template<class num > num max4 (num a, num b, num c, num d) inline
Definition at line 132 of file util.h.
References GVector::max(), role._GoToPoint::x, and role._GoToPoint::y.
 {
   num x,y;
   x = max(a,b);
   y = max(c,d);
   return(max(x,y));
 }
template<class num > num max_abs (num a, num b) inline
Definition at line 150 of file util.h.
 {
   return((fabs(a) > fabs(b))? a : b);
 }
template<class data_t > int max_idx (data_t * arr, int num) inline
Definition at line 162 of file util.h.
References velocity.pid_::i.
 {
   int mi = 0;
   for(int i=1; i<num; i++){
     if(arr[i] > arr[mi]) mi = i;
   }
   return(mi);
 }
template<class data > int mcopy (data * dest, data * src, int num) inline
Definition at line 517 of file util.h.
References velocity.pid_::i.
 {
   int i;
   for(i=0; i<num; i++) dest[i] = src[i];
   return(num);
 }
template<class num > num min3 (num a, num b, num c) inline
Definition at line 122 of file util.h.
 {
   if(a < b){
     return((a < c)? a : c);
   }else{
     return((b < c)? b : c);
   }
 }
template<class num > num min4 (num a, num b, num c, num d) inline
Definition at line 141 of file util.h.
References GVector::min(), role._GoToPoint::x, and role._GoToPoint::y.
 {
   num x,y;
   x = min(a,b);
   y = min(c,d);
   return(min(x,y));
 }
template<class num > num min_abs (num a, num b) inline
Definition at line 156 of file util.h.
 {
   return((fabs(a) < fabs(b))? a : b);
 }
template<class data_t > int min_idx (data_t * arr, int num) inline
Definition at line 172 of file util.h.
References velocity.pid_::i.
 {
   int mi = 0;
   for(int i=1; i<num; i++){
     if(arr[i] < arr[mi]) mi = i;
   }
   return(mi);
 }
template<class num > num mod (num x, num m)
Definition at line 286 of file util.h.
 {
   return(((x % m) + m) % m);
 }
template<class data > data mset (data * dest, data val, int num) inline
Definition at line 527 of file util.h.
References velocity.pid_::i.
 {
   int i;
   for(i=0; i<num; i++) dest[i] = val;
   return(val);
 }
template<class data > void mzero (data & d) inline
Definition at line 537 of file util.h.
 {
   memset(&d,0,sizeof(d));
 }
template<class data > void mzero (data * d, int n) inline
Definition at line 543 of file util.h.
 {
   memset(d,0,sizeof(data)*n);
 }
template<class num > bool one_bit_set (num n)
Definition at line 254 of file util.h.
 {
   return(n!=0 && ((-n) & n) == n);
 }
template<class real > real ramp (real x, real x0, real x1)
Definition at line 302 of file util.h.
 {
   if(x < x0) return(0);
   if(x > x1) return(1);
   return((x - x0) / (x1 - x0));
 }
template<class real > real ramp (real x, real x0, real y0, real x1, real y1)
Definition at line 312 of file util.h.
 {
   if(x < x0) return(y0);
   if(x > x1) return(y1);
   return(y0 + (y1 - y0) * (x - x0) / (x1 - x0));
 }
template<class data , class num > data* resize_array (data * arr, num & size, num new_size, num cur_used)
Definition at line 455 of file util.h.
References velocity.pid_::i.
 {
   if((arr!=NULL && new_size==size) ||
      (arr==NULL && new_size==0)) return(arr);
   data *narr = new data[new_size];
   if(narr){
     // copy existing data
     for(num i=0; i<cur_used; i++) narr[i] = arr[i];
     delete[](arr);
     size = new_size;
     return(narr);
   }else{
     // could not resize
     return(arr);
   }
 }
template<class data > void set_range (data * arr, int start, int num, const data & val)
Definition at line 508 of file util.h.
References velocity.pid_::i.
 {
   num += start;
   for(int i=start; i<num; i++) arr[i] = val;
 }
template<class num > num sign (num x)
Definition at line 242 of file util.h.
 {
   return((x >= 0)? (x > 0) : -1);
 }
template<class num > num sign_eq (num a, num b)
Definition at line 236 of file util.h.
 {
   return((a >= 0) == (b >= 0));
 }
template<class num > num sign_nz (num x)
Definition at line 230 of file util.h.
 {
   return((x >= 0)? 1 : -1);
 }
template<class num > void sort (num & a, num & b, num & c) inline
Definition at line 182 of file util.h.
 {
   if(a > b) swap(a,b);
   if(b > c) swap(b,c);
   if(a > b) swap(a,b);
 }
template<class real > real sq (real x)
Definition at line 215 of file util.h.
References cube(), MustUseResult, and role._GoToPoint::x.
 {
   return(x * x);
 }
template<class num > bool take_max (num & base, num val) inline
Definition at line 201 of file util.h.
References MustUseResult, sq(), and role._GoToPoint::x.
 {
   if(val > base){
     base = val;
     return(true);
   }else{
     return(false);
   }
 }
template<class num > bool take_min (num & base, num val) inline
Definition at line 190 of file util.h.
 {
   if(val < base){
     base = val;
     return(true);
   }else{
     return(false);
   }
 }
template<class bool_t > void toggle (bool_t & b)
Definition at line 248 of file util.h.
 {
   b = !b;
 }