Documentation: NKDTree< state_t, num_t, dim, scaled, get_next > Class Template Reference
NKDTree< state_t, num_t, dim, scaled, get_next > Class Template Reference
#include <nkdtree.h>
Data Structures
struct BBox
struct Node
class PriorityQueue
struct QueryNode
Public Types
typedef Vec::NVector< num_t, dim > vec_t
Public Member Functions
NKDTree ()
~NKDTree ()
void add (state_t *s)
void build ()
void clear ()
void setScale (int dim_idx, num_t val)
void startQuery (const state_t &_query_point, double _query_max_dist)
void startQuery (const vec_t &_query_point, double _query_max_dist)
state_t * getNextNearest (double &dist)
void endQuery ()
state_t * getOnlyNearest (const state_t &s, double &max_dist)
bool isEmpty () const
void draw (int levels) const
Protected Types
typedef std::priority_queue< QueryNode > _PriorityQueue
Protected Member Functions
double distFromQuery (Node *p)
double distFromQuery (state_t *s)
void initBBox (BBox &b, state_t &s)
void updateBBox (BBox &b, state_t &s)
void calcBBox (BBox &b, state_t *s)
void calcBBox (BBox &b, BBox &c1, BBox &c2)
void freeTree (Node *p)
void add (Node **q, state_t *s, int level)
void split (Node *p, int level)
void addToSearchQueue (Node *p)
void addToSearchQueue (state_t *s)
state_t * getOnlyNearest (Node *t, state_t *nearest)
void draw (const Node *t, int levels) const
Protected Attributes
Node * root
int leaf_size
int max_depth
int is_built
vec_t query_point
double query_max_dist
vec_t scale
PriorityQueue queue
Detailed Description
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>>
class NKDTree< state_t, num_t, dim, scaled, get_next >
Definition at line 46 of file nkdtree.h.
Member Typedef Documentation
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> typedef std::priority_queue<QueryNode> NKDTree< state_t, num_t, dim, scaled, get_next >::_PriorityQueue protected
Definition at line 84 of file nkdtree.h.
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> typedef Vec::NVector<num_t,dim> NKDTree< state_t, num_t, dim, scaled, get_next >::vec_t
Definition at line 48 of file nkdtree.h.
Constructor & Destructor Documentation
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> NKDTree< state_t, num_t, dim, scaled, get_next >::NKDTree () inline
Definition at line 112 of file nkdtree.h.
 {root=NULL; leaf_size=16; max_depth=20; scale.set(1.0);}
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> NKDTree< state_t, num_t, dim, scaled, get_next >::~NKDTree () inline
Definition at line 113 of file nkdtree.h.
 {clear();}
Member Function Documentation
template<class state_t, typename num_t , int dim, bool scaled, class get_next > void NKDTree< state_t, num_t, dim, scaled, get_next >::add (Node ** q, state_t * s, int level) protected
Definition at line 227 of file nkdtree.h.
References NKDTree< state_t, num_t, dim, scaled, get_next >::Node::child, velocity.pid_::i, mzero(), NKD_TEM, NKDTree< state_t, num_t, dim, scaled, get_next >::Node::num_states, NKDTree< state_t, num_t, dim, scaled, get_next >::Node::split_dim, NKDTree< state_t, num_t, dim, scaled, get_next >::Node::states, and NKDTree< state_t, num_t, dim, scaled, get_next >::Node::threshold.
Referenced by PluginDetectRobots::buildRegionTree().
 {
   get_next next;
   Node *p = *q;
   // check if p is a leaf node
   if(!p || !p->child[0]){
     // we're at a leaf, so add state to this node
     // make a new node if none exists here
     if(!p){
       *q = p = new Node;
       mzero(*p);
       initBBox(*p,*s);
     }
     // add point
     next(s) = p->states;
     p->states = s;
     p->num_states++;
     updateBBox(*p,*s);
     // if tree has already been built, split leaf if necessary
     if(is_built) split(p,level);
   }else{
     // there is an existing tree and we're at an internal node, so
     // just update out bounding box and recurse through this node
     updateBBox(*p,*s);
     int i = (*s)[p->split_dim] > p->threshold;
     add(&p->child[i],s,level+1);
   }
 }
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> void NKDTree< state_t, num_t, dim, scaled, get_next >::add (state_t * s) inline
Definition at line 115 of file nkdtree.h.
Referenced by NKDTree< Region, float, 2, false, CMVision::RegionTreeGetNext >::add().
 {add(&root,s,0);}
template<class state_t , typename num_t , int dim, bool scaled, class get_next > void NKDTree< state_t, num_t, dim, scaled, get_next >::addToSearchQueue (Node * p) protected
Definition at line 335 of file nkdtree.h.
References NKDTree< state_t, num_t, dim, scaled, get_next >::QueryNode::dist, NKD_TEM, NKDTree< state_t, num_t, dim, scaled, get_next >::QueryNode::node, and NKDTree< state_t, num_t, dim, scaled, get_next >::QueryNode::state.
 {
   QueryNode qn;
   qn.dist = distFromQuery(p);
   if(qn.dist < query_max_dist){
     qn.node = p;
     qn.state = NULL;
     queue.push(qn);
   }
 }
template<class state_t, typename num_t , int dim, bool scaled, class get_next > void NKDTree< state_t, num_t, dim, scaled, get_next >::addToSearchQueue (state_t * s) protected
Definition at line 347 of file nkdtree.h.
References NKDTree< state_t, num_t, dim, scaled, get_next >::QueryNode::dist, NKD_TEM, NKDTree< state_t, num_t, dim, scaled, get_next >::QueryNode::node, and NKDTree< state_t, num_t, dim, scaled, get_next >::QueryNode::state.
 {
   QueryNode qn;
   qn.dist = distFromQuery(s);
   if(qn.dist < query_max_dist){
     qn.node = NULL;
     qn.state = s;
     queue.push(qn);
   }
 }
template<class state_t , typename num_t , int dim, bool scaled, class get_next > void NKDTree< state_t, num_t, dim, scaled, get_next >::build ()
Definition at line 308 of file nkdtree.h.
References NKD_TEM.
Referenced by PluginDetectRobots::buildRegionTree().
 {
   if(!is_built){
     if(root) split(root,0);
     is_built = true;
   }
 }
template<class state_t, typename num_t , int dim, bool scaled, class get_next > void NKDTree< state_t, num_t, dim, scaled, get_next >::calcBBox (BBox & b, state_t * s) protected
Definition at line 191 of file nkdtree.h.
References NKD_TEM.
 {
   get_next next;
   // set bbox equal to first state
   initBBox(*s);
   s = next(s);
   // enlarge using additional states
   while(s){
     updateBBox(*s);
     s = next(s);
   }
 }
template<class state_t, typename num_t , int dim, bool scaled, class get_next > void NKDTree< state_t, num_t, dim, scaled, get_next >::calcBBox (BBox & b, BBox & c1, BBox & c2) protected
Definition at line 209 of file nkdtree.h.
References NKDTree< state_t, num_t, dim, scaled, get_next >::BBox::max, Vec::NVector< num, dim >::max(), NKDTree< state_t, num_t, dim, scaled, get_next >::BBox::min, Vec::NVector< num, dim >::min(), and NKD_TEM.
 {
   b.min.min(c1.min, c2.min);
   b.max.max(c1.max, c2.max);
 }
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> void NKDTree< state_t, num_t, dim, scaled, get_next >::clear () inline
Definition at line 117 of file nkdtree.h.
Referenced by PluginDetectRobots::buildRegionTree().
 {freeTree(root); root=NULL; is_built=false;}
template<class state_t , typename num_t , int dim, bool scaled, class get_next > double NKDTree< state_t, num_t, dim, scaled, get_next >::distFromQuery (Node * p) protected
Definition at line 137 of file nkdtree.h.
References Vec::NVector< num, dim >::bound(), GVector::dist(), velocity.pid_::i, NKDTree< state_t, num_t, dim, scaled, get_next >::BBox::max, NKDTree< state_t, num_t, dim, scaled, get_next >::BBox::min, NKD_TEM, and sq().
 {
   vec_t near;
   near.bound(query_point, p->min, p->max);
   if(!scaled){
     return(dist(query_point, near));
   }else{
     double d = 0.0;
     for(int i=0; i<dim; i++){
       d += sq((query_point[i] - near[i]) * scale[i]);
     }
     return(sqrt(d));
   }
 }
template<class state_t, typename num_t , int dim, bool scaled, class get_next > double NKDTree< state_t, num_t, dim, scaled, get_next >::distFromQuery (state_t * s) protected
Definition at line 153 of file nkdtree.h.
References velocity.pid_::i, NKD_TEM, and sq().
 {
   int i;
   double d = 0.0;
   for(i=0; i<dim; i++){
     if(!scaled){
       d += sq(query_point[i] - (*s)[i]);
     }else{
       d += sq(query_point[i] - (*s)[i]) * scale[i];
     }
   }
   return(sqrt(d));
 }
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> void NKDTree< state_t, num_t, dim, scaled, get_next >::draw (const Node * t, int levels) const protected
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> void NKDTree< state_t, num_t, dim, scaled, get_next >::draw (int levels) const inline
Definition at line 132 of file nkdtree.h.
     {if(dim==2) draw(root,levels);}
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> void NKDTree< state_t, num_t, dim, scaled, get_next >::endQuery () inline
Definition at line 125 of file nkdtree.h.
Referenced by CMPattern::TeamDetector::findRobotsByModel().
 {queue.clear();}
template<class state_t , typename num_t , int dim, bool scaled, class get_next > void NKDTree< state_t, num_t, dim, scaled, get_next >::freeTree (Node * p) protected
Definition at line 217 of file nkdtree.h.
References NKDTree< state_t, num_t, dim, scaled, get_next >::Node::child, and NKD_TEM.
 {
   if(p){
     freeTree(p->child[0]); p->child[0]=NULL;
     freeTree(p->child[1]); p->child[1]=NULL;
     delete(p);
   }
 }
template<class state_t , typename num_t , int dim, bool scaled, class get_next > state_t * NKDTree< state_t, num_t, dim, scaled, get_next >::getNextNearest (double & dist)
Definition at line 359 of file nkdtree.h.
References NKDTree< state_t, num_t, dim, scaled, get_next >::Node::child, NKDTree< state_t, num_t, dim, scaled, get_next >::QueryNode::dist, NKD_TEM, NKDTree< state_t, num_t, dim, scaled, get_next >::QueryNode::node, NKDTree< state_t, num_t, dim, scaled, get_next >::QueryNode::state, and NKDTree< state_t, num_t, dim, scaled, get_next >::Node::states.
Referenced by CMPattern::TeamDetector::findRobotsByModel().
 {
   get_next next;
   QueryNode qn;
   state_t *s;
   while(queue.size() > 0){
     // get head of priority queue
     qn = queue.top();
     queue.pop();
     // if its a raw state, return it
     if(qn.state){
       dist = qn.dist;
       return(qn.state);
     }
     // otherwise it is a node, so we have to expand it
     // expand nodes
     if(qn.node->child[0]) addToSearchQueue(qn.node->child[0]);
     if(qn.node->child[1]) addToSearchQueue(qn.node->child[1]);
     // expand states
     s = qn.node->states;
     while(s){
       addToSearchQueue(s);
       s = next(s);
     }
   }
   // ran out of states
   return(NULL);
 }
template<class state_t, typename num_t , int dim, bool scaled, class get_next > state_t * NKDTree< state_t, num_t, dim, scaled, get_next >::getOnlyNearest (Node * t, state_t * nearest) protected
Definition at line 395 of file nkdtree.h.
References NKDTree< state_t, num_t, dim, scaled, get_next >::Node::child, velocity.pid_::i, NKD_TEM, NKDTree< state_t, num_t, dim, scaled, get_next >::Node::split_dim, NKDTree< state_t, num_t, dim, scaled, get_next >::Node::states, and NKDTree< state_t, num_t, dim, scaled, get_next >::Node::threshold.
 {
   get_next next;
   state_t *s;
   double d;
   // pruning
   if(t==NULL || distFromQuery(t)>query_max_dist) return(nearest);
   // we either store states (leaf) or are have children (interal node)
   if(t->states){
     // leaf node, check the states stored here to update the nearest
     s = t->states;
     while(s){
       d = distFromQuery(s);
       if(d < query_max_dist){
         nearest = s;
         query_max_dist = d;
       }
       s = next(s);
     }
   }else{
     // internal node, find out which side of the plane our query is on
     // and descend the tree on that side first, followed by the
     // further side.
     int i = query_point[t->split_dim] > t->threshold;
     nearest = getOnlyNearest(t->child[ i],nearest);
     nearest = getOnlyNearest(t->child[!i],nearest);
   }
   return(nearest);
 }
template<class state_t, typename num_t , int dim, bool scaled, class get_next > state_t * NKDTree< state_t, num_t, dim, scaled, get_next >::getOnlyNearest (const state_t & s, double & max_dist)
Definition at line 429 of file nkdtree.h.
References NKDTree< state_t, num_t, dim, scaled, get_next >::Node::child, velocity.pid_::i, NKDTree< state_t, num_t, dim, scaled, get_next >::BBox::max, NKDTree< state_t, num_t, dim, scaled, get_next >::BBox::min, NKD_TEM, GVector::vector2d< num >::set(), NKDTree< state_t, num_t, dim, scaled, get_next >::Node::states, and t.
 {
   state_t *sn;
   /*
   endQuery();
   startQuery(s,max_dist);
   sn = getNextNearest(max_dist);
   endQuery();
   */
   for(int i=0; i<dim; i++) query_point[i] = s[i];
   query_max_dist = max_dist;
   sn = getOnlyNearest(root,NULL);
   max_dist = query_max_dist;
   return(sn);
 }
template<class state_t, typename num_t , int dim, bool scaled, class get_next > void NKDTree< state_t, num_t, dim, scaled, get_next >::initBBox (BBox & b, state_t & s) protected
Definition at line 168 of file nkdtree.h.
References velocity.pid_::i, NKDTree< state_t, num_t, dim, scaled, get_next >::BBox::max, NKDTree< state_t, num_t, dim, scaled, get_next >::BBox::min, and NKD_TEM.
 {
   for(int i=0; i<dim; i++){
     b.min[i] = b.max[i] = s[i];
   }
 }
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> bool NKDTree< state_t, num_t, dim, scaled, get_next >::isEmpty () const inline
Definition at line 130 of file nkdtree.h.
     {return(!root || root->num_states==0);}
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> void NKDTree< state_t, num_t, dim, scaled, get_next >::setScale (int dim_idx, num_t val) inline
Definition at line 118 of file nkdtree.h.
     {scale[dim_idx]=val;}
template<class state_t , typename num_t , int dim, bool scaled, class get_next > void NKDTree< state_t, num_t, dim, scaled, get_next >::split (Node * p, int level) protected
Definition at line 261 of file nkdtree.h.
References NKDTree< state_t, num_t, dim, scaled, get_next >::Node::child, velocity.pid_::i, NKDTree< state_t, num_t, dim, scaled, get_next >::BBox::max, NKDTree< state_t, num_t, dim, scaled, get_next >::BBox::min, NKD_TEM, NKDTree< state_t, num_t, dim, scaled, get_next >::Node::num_states, NKDTree< state_t, num_t, dim, scaled, get_next >::Node::split_dim, GVector::sqdist(), NKDTree< state_t, num_t, dim, scaled, get_next >::Node::states, and NKDTree< state_t, num_t, dim, scaled, get_next >::Node::threshold.
 {
   get_next next;
   state_t *s,*sn;
   int sd;
   double sum;
   int i;
   // check if we actually want to split
   if(!p) return;
   if((p->num_states <= leaf_size) || (level >= max_depth)) return;
   if(sqdist(p->min,p->max) < 1E-9) return;
   // choose split dimension as round-robin
   p->split_dim = sd = level % dim;
   // calculate mean for split threshold
   sum = 0.0;
   s = p->states;
   while(s){
     sum += (*s)[sd];
     s = next(s);
   }
   p->threshold = sum / p->num_states;
   // split the points based on the plane
   s = p->states;
   while(s){
     sn = next(s);
     i = (*s)[sd] > p->threshold;
     add(&(p->child[i]),s,level+1);
     s = sn;
   }
   // this state no longer stores points
   p->states = 0;
   p->num_states = 0;
   if(!is_built){
     split(p->child[0],level+1);
     split(p->child[1],level+1);
   }
 }
template<class state_t, typename num_t , int dim, bool scaled, class get_next > void NKDTree< state_t, num_t, dim, scaled, get_next >::startQuery (const state_t & _query_point, double _query_max_dist)
Definition at line 317 of file nkdtree.h.
References velocity.pid_::i, and NKD_TEM.
Referenced by CMPattern::TeamDetector::findRobotsByModel().
 {
   endQuery();
   for(int i=0; i<dim; i++) query_point[i] = _query_point[i];
   query_max_dist = _query_max_dist;
   if(root) addToSearchQueue(root);
 }
template<class state_t, typename num_t , int dim, bool scaled, class get_next > void NKDTree< state_t, num_t, dim, scaled, get_next >::startQuery (const vec_t & _query_point, double _query_max_dist)
Definition at line 326 of file nkdtree.h.
References NKD_TEM.
 {
   endQuery();
   query_point = _query_point;
   query_max_dist = _query_max_dist;
   if(root) addToSearchQueue(root);
 }
template<class state_t, typename num_t , int dim, bool scaled, class get_next > void NKDTree< state_t, num_t, dim, scaled, get_next >::updateBBox (BBox & b, state_t & s) protected
Definition at line 177 of file nkdtree.h.
References velocity.pid_::i, NKDTree< state_t, num_t, dim, scaled, get_next >::BBox::max, NKDTree< state_t, num_t, dim, scaled, get_next >::BBox::min, NKD_TEM, and v.
 {
   int i;
   num_t v;
   for(i=0; i<dim; i++){
     v = s[i];
     if(v < b.min[i]) b.min[i] = v;
     if(v > b.max[i]) b.max[i] = v;
   }
 }
Field Documentation
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> int NKDTree< state_t, num_t, dim, scaled, get_next >::is_built protected
Definition at line 78 of file nkdtree.h.
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> int NKDTree< state_t, num_t, dim, scaled, get_next >::leaf_size protected
Definition at line 77 of file nkdtree.h.
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> int NKDTree< state_t, num_t, dim, scaled, get_next >::max_depth protected
Definition at line 77 of file nkdtree.h.
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> double NKDTree< state_t, num_t, dim, scaled, get_next >::query_max_dist protected
Definition at line 81 of file nkdtree.h.
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> vec_t NKDTree< state_t, num_t, dim, scaled, get_next >::query_point protected
Definition at line 80 of file nkdtree.h.
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> PriorityQueue NKDTree< state_t, num_t, dim, scaled, get_next >::queue protected
Definition at line 89 of file nkdtree.h.
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> Node* NKDTree< state_t, num_t, dim, scaled, get_next >::root protected
Definition at line 76 of file nkdtree.h.
template<class state_t, typename num_t, int dim, bool scaled = false, class get_next = NKDTreeGetNext<state_t>> vec_t NKDTree< state_t, num_t, dim, scaled, get_next >::scale protected
Definition at line 82 of file nkdtree.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/nkdtree.h