Documentation: Random Class Reference
Random Class Reference
A class implementing the Mersenne Twister RNG.
#include <random.h>
Public Member Functions
Random ()
void randomize ()
void seed (uint32_t s)
void seed (const uint32_t *init_key, int key_length)
unsigned uint32 ()
int int32 ()
int int31 ()
unsigned uint32 (unsigned max)
unsigned uint32 (int min, int max)
double sreal32 ()
double real32 ()
double real53 ()
double gaussian32 ()
Private Member Functions
void next_state ()
Private Attributes
uint32_t state [N]
uint32_t * next
int left
int gleft
double grand
Static Private Attributes
static const int N = 624
static const int M = 397
Detailed Description
A class implementing the Mersenne Twister RNG.
Definition at line 66 of file random.h.
Constructor & Destructor Documentation
Random::Random () inline
Definition at line 80 of file random.h.
References randomize(), seed(), and uint32().
 {left=-1;}
Member Function Documentation
double Random::gaussian32 ()
Definition at line 204 of file random.cpp.
References gleft, grand, real32(), role._GoToPoint::x, and role._GoToPoint::y.
Referenced by real53().
 {
   double x,y,l,f;
   if(gleft){
     gleft = 0;
     return(grand);
   }else{
     do{
       x = 2*real32()-1;
       y = 2*real32()-1;
       l = x*x + y*y;
     }while(l>=1.0 || l==0.0);
     f = sqrt(-2*log(l)/l);
     gleft = 1;
     grand = y*f;
     return(x*f);
   }
 }
int Random::int31 () inline
Definition at line 90 of file random.h.
References uint32().
     {return((int)(uint32()>>1));}
int Random::int32 () inline
Definition at line 88 of file random.h.
References uint32().
     {return((int)(uint32()));}
void Random::next_state () private
Definition at line 165 of file random.cpp.
References left, M, N, next, seed(), state, and TWIST.
Referenced by uint32().
 {
   uint32_t *p=state;
   int j;
   /* if seed() or randomize() has not been called, */
   /* a default initial seed is used         */
   if(left < 0) seed(5489UL);
   left = N;
   next = state;
   for(j=N-M+1; --j; p++){
     *p = p[M] ^ TWIST(p[0], p[1]);
   }
   for(j=M; --j; p++){
     *p = p[M-N] ^ TWIST(p[0], p[1]);
   }
   *p = p[M-N] ^ TWIST(p[0], state[0]);
 }
void Random::randomize ()
Definition at line 91 of file random.cpp.
References left, N, seed(), and state.
Referenced by GlobalRandom::GlobalRandom(), and Random().
 {
   timeval tv;
   uint32_t a[2];
   int fd;
   fd = open("/dev/urandom",O_RDONLY);
   if(fd >= 0){
     const size_t num_bytes = sizeof(uint32_t)*N;
     if (read(fd,state,num_bytes) != num_bytes) {
       fprintf(stderr, "WARNING: Unable to read sufficient seed bytes from "
               "/dev/urandom");
     }
     close(fd);
     left = 1;
   }else{
     #if WIN32
     //FIXME.
     seed(43);
     #else
     gettimeofday(&tv,NULL);
     a[0] = tv.tv_sec;
     a[1] = tv.tv_usec;
     seed(a,2);
     #endif
   }
 }
double Random::real32 () inline
Definition at line 100 of file random.h.
References uint32().
Referenced by gaussian32().
     {return((double)uint32() * (1.0/4294967296.0));}
double Random::real53 () inline
Definition at line 102 of file random.h.
References gaussian32(), and uint32().
     {unsigned a=uint32()>>5,b=uint32()>>6;
      return(a*67108864.0+b)*(1.0/9007199254740992.0);}
void Random::seed (uint32_t s)
Definition at line 120 of file random.cpp.
References left, N, and state.
Referenced by next_state(), Random(), randomize(), and seed().
 {
   int j;
   state[0]= s;
   for(j=1; j<N; j++){
     state[j] = (1812433253UL * (state[j-1] ^ (state[j-1] >> 30)) + j);
     /* See Knuth TAOCP Vol2. 3rd Ed. P.106 for multiplier. */
     /* In the previous versions, MSBs of the seed affect   */
     /* only MSBs of the array state[].                     */
     /* 2002/01/09 modified by Makoto Matsumoto             */
   }
   left = 1;
 }
void Random::seed (const uint32_t * init_key, int key_length)
Definition at line 139 of file random.cpp.
References velocity.pid_::i, k, left, N, seed(), and state.
 {
   int i,j,k;
   seed(19650218UL);
   i=1; j=0;
   k = (N>key_length ? N : key_length);
   for(; k; k--){
     state[i] = (state[i] ^ ((state[i-1] ^ (state[i-1] >> 30)) * 1664525UL))
       + init_key[j] + j; /* non linear */
     i++; j++;
     if(i>=N){ state[0] = state[N-1]; i=1; }
     if(j>=key_length) j=0;
   }
   for(k=N-1; k; k--){
     state[i] = (state[i] ^ ((state[i-1] ^ (state[i-1] >> 30)) * 1566083941UL))
       - i; /* non linear */
     i++;
     if(i>=N){ state[0] = state[N-1]; i=1; }
   }
   state[0] = 0x80000000UL; /* MSB is 1; assuring non-zero initial array */
   left = 1;
 }
double Random::sreal32 () inline
Definition at line 98 of file random.h.
References uint32().
     {return((double)uint32() * (2.0/4294967296.0) - 1.0);}
unsigned Random::uint32 ()
Definition at line 188 of file random.cpp.
References left, next, next_state(), and role._GoToPoint::y.
Referenced by int31(), int32(), Random(), real32(), real53(), sreal32(), and uint32().
 {
   unsigned y;
   if(--left <= 0) next_state();
   y = *next++;
   /* Tempering */
   y ^= (y >> 11);
   y ^= (y << 7) & 0x9d2c5680UL;
   y ^= (y << 15) & 0xefc60000UL;
   y ^= (y >> 18);
   return(y);
 }
unsigned Random::uint32 (unsigned max) inline
Definition at line 93 of file random.h.
References uint32().
     {return(uint32() % max);}
unsigned Random::uint32 (int min, int max) inline
Definition at line 95 of file random.h.
References uint32().
     {return(uint32() % (max-min) + min);}
Field Documentation
int Random::gleft private
Definition at line 75 of file random.h.
Referenced by gaussian32().
double Random::grand private
Definition at line 76 of file random.h.
Referenced by gaussian32().
int Random::left private
Definition at line 73 of file random.h.
Referenced by next_state(), randomize(), seed(), and uint32().
const int Random::M = 397 static private
Definition at line 68 of file random.h.
Referenced by next_state().
const int Random::N = 624 static private
Definition at line 67 of file random.h.
Referenced by next_state(), randomize(), and seed().
uint32_t* Random::next private
Definition at line 72 of file random.h.
Referenced by next_state(), and uint32().
uint32_t Random::state[N] private
Definition at line 71 of file random.h.
Referenced by fsm.StateMachine::corresponding_ancestor_state(), fsm.StateMachine::is_in_state(), next_state(), randomize(), seed(), fsm.StateMachine::spin(), and fsm.StateMachine::transition().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/util/random.h
ssl-vision/src/shared/util/random.cpp