Documentation: Protobuf.GrSimReplacement.grSim_Replacement Class Reference
Protobuf.GrSimReplacement.grSim_Replacement Class Reference
Data Structures
class Builder
Public Member Functions
grSim_Replacement getDefaultInstanceForType ()
boolean hasBall ()
GrSimReplacement.grSim_BallReplacement getBall ()
GrSimReplacement.grSim_BallReplacementOrBuilder getBallOrBuilder ()
java.util.List< GrSimReplacement.grSim_RobotReplacement > getRobotsList ()
java.util.List<?extends GrSimReplacement.grSim_RobotReplacementOrBuilder > getRobotsOrBuilderList ()
int getRobotsCount ()
GrSimReplacement.grSim_RobotReplacement getRobots (int index)
GrSimReplacement.grSim_RobotReplacementOrBuilder getRobotsOrBuilder (int index)
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static grSim_Replacement getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static GrSimReplacement.grSim_Replacement parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimReplacement.grSim_Replacement parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimReplacement.grSim_Replacement parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimReplacement.grSim_Replacement parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimReplacement.grSim_Replacement parseFrom (java.io.InputStream input) throws java.io.IOException
static GrSimReplacement.grSim_Replacement parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static GrSimReplacement.grSim_Replacement parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static GrSimReplacement.grSim_Replacement parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static GrSimReplacement.grSim_Replacement parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static GrSimReplacement.grSim_Replacement parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (GrSimReplacement.grSim_Replacement prototype)
Static Public Attributes
static final int BALL_FIELD_NUMBER = 1
static final int ROBOTS_FIELD_NUMBER = 2
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
grSim_Replacement (Builder builder)
grSim_Replacement (boolean noInit)
void initFields ()
Private Attributes
int bitField0_
GrSimReplacement.grSim_BallReplacement ball_
java.util.List< GrSimReplacement.grSim_RobotReplacement > robots_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final grSim_Replacement defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 1176 of file GrSimReplacement.java.
Constructor & Destructor Documentation
Protobuf.GrSimReplacement.grSim_Replacement.grSim_Replacement (Builder builder) inline private
Definition at line 1180 of file GrSimReplacement.java.
{
       super(builder);
     }
Protobuf.GrSimReplacement.grSim_Replacement.grSim_Replacement (boolean noInit) inline private
Definition at line 1183 of file GrSimReplacement.java.
 {}
Member Function Documentation
GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_Replacement.getBall () inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1211 of file GrSimReplacement.java.
{
       return ball_;
     }
GrSimReplacement.grSim_BallReplacementOrBuilder Protobuf.GrSimReplacement.grSim_Replacement.getBallOrBuilder () inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1214 of file GrSimReplacement.java.
{
       return ball_;
     }
static grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.getDefaultInstance () inline static
Definition at line 1186 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimPacket.grSim_Packet.Builder.clear(), Protobuf.GrSimPacket.grSim_Packet.Builder.clearReplacement(), Protobuf.GrSimReplacement.grSim_Replacement.Builder.getDefaultInstanceForType(), Protobuf.GrSimPacket.grSim_Packet.initFields(), Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeFrom(), and Protobuf.GrSimPacket.grSim_Packet.Builder.mergeReplacement().
{
       return defaultInstance;
     }
grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.getDefaultInstanceForType () inline
Definition at line 1190 of file GrSimReplacement.java.
{
       return defaultInstance;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimReplacement.grSim_Replacement.getDescriptor () inline static
Definition at line 1195 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.internal_static_grSim_Replacement_descriptor.
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.Builder.getDescriptorForType().
{
       return GrSimReplacement.internal_static_grSim_Replacement_descriptor;
     }
GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_Replacement.getRobots (int index) inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1231 of file GrSimReplacement.java.
{
       return robots_.get(index);
     }
int Protobuf.GrSimReplacement.grSim_Replacement.getRobotsCount () inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1228 of file GrSimReplacement.java.
{
       return robots_.size();
     }
java.util.List<GrSimReplacement.grSim_RobotReplacement> Protobuf.GrSimReplacement.grSim_Replacement.getRobotsList () inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1221 of file GrSimReplacement.java.
{
       return robots_;
     }
GrSimReplacement.grSim_RobotReplacementOrBuilder Protobuf.GrSimReplacement.grSim_Replacement.getRobotsOrBuilder (int index) inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1234 of file GrSimReplacement.java.
                    {
       return robots_.get(index);
     }
java.util.List<? extends GrSimReplacement.grSim_RobotReplacementOrBuilder> Protobuf.GrSimReplacement.grSim_Replacement.getRobotsOrBuilderList () inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1225 of file GrSimReplacement.java.
{
       return robots_;
     }
int Protobuf.GrSimReplacement.grSim_Replacement.getSerializedSize () inline
Definition at line 1277 of file GrSimReplacement.java.
References velocity.pid_.i.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(1, ball_);
       }
       for (int i = 0; i < robots_.size(); i++) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(2, robots_.get(i));
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
boolean Protobuf.GrSimReplacement.grSim_Replacement.hasBall () inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1208 of file GrSimReplacement.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
void Protobuf.GrSimReplacement.grSim_Replacement.initFields () inline private
Definition at line 1239 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.getDefaultInstance().
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.Builder.getRobotsFieldBuilder().
{
       ball_ = GrSimReplacement.grSim_BallReplacement.getDefaultInstance();
       robots_ = java.util.Collections.emptyList();
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.GrSimReplacement.grSim_Replacement.internalGetFieldAccessorTable () inline protected
Definition at line 1200 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.internal_static_grSim_Replacement_fieldAccessorTable.
{
       return GrSimReplacement.internal_static_grSim_Replacement_fieldAccessorTable;
     }
final boolean Protobuf.GrSimReplacement.grSim_Replacement.isInitialized () inline
Definition at line 1244 of file GrSimReplacement.java.
References velocity.pid_.i.
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (hasBall()) {
         if (!getBall().isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       for (int i = 0; i < getRobotsCount(); i++) {
         if (!getRobots(i).isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.GrSimReplacement.grSim_Replacement.newBuilder () inline static
Definition at line 1369 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_Replacement.Builder.create().
Referenced by Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom(), and Protobuf.GrSimPacket.grSim_Packet.Builder.mergeReplacement().
 { return Builder.create(); }
static Builder Protobuf.GrSimReplacement.grSim_Replacement.newBuilder (GrSimReplacement.grSim_Replacement prototype) inline static
Definition at line 1371 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.GrSimReplacement.grSim_Replacement.newBuilderForType () inline
Definition at line 1370 of file GrSimReplacement.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.GrSimReplacement.grSim_Replacement.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 1377 of file GrSimReplacement.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 1336 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_Replacement.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1345 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_Replacement.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1302 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1307 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1314 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1318 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 1325 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1329 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 1356 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1361 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.GrSimReplacement.grSim_Replacement.toBuilder () inline
Definition at line 1374 of file GrSimReplacement.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.GrSimReplacement.grSim_Replacement.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 1297 of file GrSimReplacement.java.
{
       return super.writeReplace();
     }
void Protobuf.GrSimReplacement.grSim_Replacement.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 1264 of file GrSimReplacement.java.
References velocity.pid_.i.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeMessage(1, ball_);
       }
       for (int i = 0; i < robots_.size(); i++) {
         output.writeMessage(2, robots_.get(i));
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_Replacement.ball_ private
Definition at line 1207 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.Builder.buildPartial().
final int Protobuf.GrSimReplacement.grSim_Replacement.BALL_FIELD_NUMBER = 1 static
Definition at line 1206 of file GrSimReplacement.java.
int Protobuf.GrSimReplacement.grSim_Replacement.bitField0_ private
Definition at line 1204 of file GrSimReplacement.java.
final grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.defaultInstance static private
Definition at line 1185 of file GrSimReplacement.java.
byte Protobuf.GrSimReplacement.grSim_Replacement.memoizedIsInitialized = -1 private
Definition at line 1243 of file GrSimReplacement.java.
int Protobuf.GrSimReplacement.grSim_Replacement.memoizedSerializedSize = -1 private
Definition at line 1276 of file GrSimReplacement.java.
java.util.List<GrSimReplacement.grSim_RobotReplacement> Protobuf.GrSimReplacement.grSim_Replacement.robots_ private
Definition at line 1220 of file GrSimReplacement.java.
final int Protobuf.GrSimReplacement.grSim_Replacement.ROBOTS_FIELD_NUMBER = 2 static
Definition at line 1219 of file GrSimReplacement.java.
final long Protobuf.GrSimReplacement.grSim_Replacement.serialVersionUID = 0L static private
Definition at line 1295 of file GrSimReplacement.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimReplacement.java