float64 packet_timestamp
uint32 stage
uint32 stage_time_left
uint32 command
uint32 command_counter
uint32 command_timestamp
string b_name
uint32 b_score
uint32 b_red_cards
uint32 b_yellow_cards
uint32 b_timeouts
uint32 b_timeout_time
uint32 b_goalie
string y_name
uint32 y_score
uint32 y_red_cards
uint32 y_yellow_cards
uint32 y_timeouts
uint32 y_timeout_time
uint32 y_goalie
uint32[] y_card_times
uint32[] b_card_times

	
