Documentation: LUT3D Class Reference
LUT3D Class Reference
A general 3D LUT class, allowing fast bit-wise lookup.
#include <lut3d.h>
Public Member Functions
LUT3D (unsigned int x_bits=7, unsigned int y_bits=7, unsigned int z_bits=7, string filename="3dlut.xml")
void lock ()
void unlock ()
VarList * getSettings ()
LUTChannel getChannel (unsigned int idx) const
void clearDerivedLUTs (bool unallocate_derived_memory=true)
int getDerivedLUTcount ()
LUT3D * getDerivedLUT (int idx)
void addDerivedLUT (LUT3D *lut)
LUT3D * getDerivedLUT (ColorSpace space)
void updateDerivedLUTs ()
virtual void deriveFromLUT (LUT3D *lut)
int getChannelID (const string &label) const
void setChannel (unsigned int idx, LUTChannel c)
int getChannelCount () const
int getSizeX () const
int getSizeY () const
int getSizeZ () const
int getMaxX () const
int getMaxY () const
int getMaxZ () const
virtual ~LUT3D ()
virtual ColorSpace getColorSpace () const
void reset ()
lut_mask_t * getTable () const
lut_mask_t * getPointer (unsigned char x, unsigned char y, unsigned char z) const
lut_mask_t * getPointerPreshrunk (unsigned char x, unsigned char y, unsigned char z) const
unsigned char norm2lutX (unsigned char x) const
unsigned char norm2lutY (unsigned char y) const
unsigned char norm2lutZ (unsigned char z) const
unsigned char lut2normX (unsigned char x) const
unsigned char lut2normY (unsigned char y) const
unsigned char lut2normZ (unsigned char z) const
void set (unsigned char x, unsigned char y, unsigned char z, lut_mask_t mask)
void set_preshrunk (unsigned char x, unsigned char y, unsigned char z, lut_mask_t mask)
lut_mask_t get (const unsigned char x, const unsigned char y, const unsigned char z)
lut_mask_t get_preshrunk (const unsigned char x, const unsigned char y, const unsigned char z)
void copyChannels (const LUT3D &other)
void loadRoboCupChannels (LUTChannelMode mode)
void loadBlackWhite (LUTChannelMode mode)
void maskFillYZ (unsigned char slice_x, unsigned char origin_y, unsigned char origin_z, lut_mask_t new_color, LUTChannelMode mode, bool remove=false, bool check_exact=true, bool write_exclusive=false)
Data Fields
unsigned int X_BITS
unsigned int Y_BITS
unsigned int Z_BITS
unsigned int X_SHIFT
unsigned int Y_SHIFT
unsigned int Z_SHIFT
unsigned int Y_SHIFT_PLUS_8
unsigned int Z_SHIFT_PLUS_16
unsigned int Z_AND_Y_BITS
unsigned int TOTAL_BITS
unsigned int LUT_SIZE
lut_mask_t * LUT
VarBlob * v_blob
VarList * v_settings
vector< LUTChannel > channels
vector< LUT3D * > derived_LUTs
QMutex mutex
Protected Slots
void slotVBlobChange ()
Detailed Description
A general 3D LUT class, allowing fast bit-wise lookup.
Author
Stefan Zickler
Definition at line 77 of file lut3d.h.
Constructor & Destructor Documentation
LUT3D::LUT3D (unsigned int x_bits = 7, unsigned int y_bits = 7, unsigned int z_bits = 7, string filename = "3dlut.xml") inline
Definition at line 109 of file lut3d.h.
References VarTypes::VarList::addChild(), and role._GoToPoint::reset().
{
       assert(x_bits <= 8 && y_bits <= 8 && z_bits <= 8);
       X_BITS = x_bits; // bits for each field, should be less or equal to 8
       Y_BITS = y_bits; // bits for each field, should be less or equal to 8
       Z_BITS = z_bits; // bits for each field, should be less or equal to 8
       //derived values:
       X_SHIFT=8-X_BITS;
       Y_SHIFT=8-Y_BITS;
       Z_SHIFT=8-Z_BITS;
       //Y_SHIFT_PLUS_8=Y_SHIFT + 8;
       //Z_SHIFT_PLUS_16=Z_SHIFT + 16;
       Z_AND_Y_BITS = Y_BITS+Z_BITS; // bits for each field
       TOTAL_BITS = X_BITS + Y_BITS + Z_BITS; // bits for each field
       //LUT_SIZE = (0x1 << (TOTAL_BITS+1)) - 0x01;
       LUT_SIZE = (0x01 << (TOTAL_BITS+1));// + 1;
       channels.resize(sizeof(lut_mask_t));
       LUT=new lut_mask_t[LUT_SIZE];
       if (filename=="") {
         v_settings=0;
         v_blob=0;
       } else {
         v_settings=new VarExternal(filename,"LUT 3D");
         v_settings->addChild(v_blob=new VarBlob((uint8_t *)LUT,(int)LUT_SIZE*sizeof(lut_mask_t),"LUT Data"));
         connect(v_blob,SIGNAL(XMLwasRead(VarType *)),this,SLOT(slotVBlobChange()));
       }
       reset();
     };
virtual LUT3D::~LUT3D () inline virtual
Definition at line 270 of file lut3d.h.
                      {
       channels.clear();
       clearDerivedLUTs(true);
       delete[] LUT;
       if (v_blob!=0) delete v_blob;
       if (v_settings!=0) delete v_settings;
     };
Member Function Documentation
void LUT3D::addDerivedLUT (LUT3D * lut) inline
Definition at line 184 of file lut3d.h.
Referenced by StackRoboCupSSL::StackRoboCupSSL().
{
       lock();
       if (lut!=0) {
         derived_LUTs.push_back(lut);
       }
       unlock();
     }
void LUT3D::clearDerivedLUTs (bool unallocate_derived_memory = true) inline
Definition at line 160 of file lut3d.h.
References velocity.pid_::i.
{
       lock();
         int n = derived_LUTs.size();
         if (unallocate_derived_memory) {
           for (int i = 0; i < n; i ++) {
             delete derived_LUTs[i];
           }
         }
         derived_LUTs.clear();
       unlock();
     }
void LUT3D::copyChannels (const LUT3D & other) inline
Definition at line 339 of file lut3d.h.
References getChannel(), getChannelCount(), and velocity.pid_::i.
Referenced by CMPattern::TeamDetector::init().
{
       lock();
       int n=other.getChannelCount();
       channels.clear();
       for (int i=0;i<n;i++) {
         channels.push_back(other.getChannel(i));
       }
       unlock();
     }
virtual void LUT3D::deriveFromLUT (LUT3D * lut) inline virtual
Reimplemented in YUVLUT, and RGBLUT.
Definition at line 216 of file lut3d.h.
References get(), role._GoToPoint::x, and role._GoToPoint::y.
{
       for (int x=0;x<=255;x++) {
         for (int y=0;y<=255;y++) {
           for (int z=0;z<=255;z++) {
             set((unsigned char)x,(unsigned char)y,(unsigned char)z,lut->get((unsigned char)x,(unsigned char)y,(unsigned char)z));
           }
         }
       }
     }
lut_mask_t LUT3D::get (const unsigned char x, const unsigned char y, const unsigned char z) inline
Definition at line 331 of file lut3d.h.
Referenced by deriveFromLUT(), RGBLUT::deriveFromLUT(), and YUVLUT::deriveFromLUT().
{
       return LUT[((x >> X_SHIFT) << Z_AND_Y_BITS) | ((y >> Y_SHIFT) << Z_BITS) | (z >> Z_SHIFT)];
     }
lut_mask_t LUT3D::get_preshrunk (const unsigned char x, const unsigned char y, const unsigned char z) inline
Definition at line 335 of file lut3d.h.
References role._GoToPoint::x, and role._GoToPoint::y.
Referenced by GLLUTWidget::drawSinglePixel(), and GLLUTWidget::drawSlice().
{
       return LUT[((x) << Z_AND_Y_BITS) | ((y) << Z_BITS) | (z)];
     }
LUTChannel LUT3D::getChannel (unsigned int idx) const inline
Definition at line 152 of file lut3d.h.
Referenced by CMVisionThreshold::colorizeImageFromThresholding(), copyChannels(), PluginVisualize::DrawBlobs(), and PluginVisualize::DrawThresholdedImage().
{
       if (idx >= channels.size()) {
         fprintf(stderr,"invalid channel selected in getChannel(...)\n");
       }
       return channels[idx];
     }
int LUT3D::getChannelCount () const inline
Definition at line 241 of file lut3d.h.
Referenced by copyChannels(), CMPattern::TeamDetector::init(), PluginDetectBalls::PluginDetectBalls(), and PluginFindBlobs::process().
{
       return channels.size();
     }
int LUT3D::getChannelID (const string & label) const inline
Definition at line 226 of file lut3d.h.
References velocity.pid_::i.
Referenced by CMPattern::MultiPatternModel::loadSinglePatternImage(), PluginDetectBalls::PluginDetectBalls(), PluginDetectRobots::PluginDetectRobots(), PluginDetectBalls::process(), and CMPattern::TeamDetector::TeamDetector().
{
       for (int i = 0; i < getChannelCount(); i++) {
         if (channels[i].label.compare(label)==0) return i;
       }
       return -1;
     }
virtual ColorSpace LUT3D::getColorSpace () const inline virtual
Reimplemented in YUVLUT, and RGBLUT.
Definition at line 278 of file lut3d.h.
References CSPACE_UNDEFINED.
Referenced by RGBLUT::deriveFromLUT(), YUVLUT::deriveFromLUT(), and GLLUTWidget::drawSlice().
{
       return CSPACE_UNDEFINED;
     }
LUT3D* LUT3D::getDerivedLUT (int idx) inline
Definition at line 176 of file lut3d.h.
Referenced by PluginColorThreshold::process().
{
       LUT3D * res=0;
       lock();
         res = derived_LUTs[idx];
       unlock();
       return res;
     }
LUT3D* LUT3D::getDerivedLUT (ColorSpace space) inline
Definition at line 192 of file lut3d.h.
References velocity.pid_::i.
{
      LUT3D * result=0;
      lock();
       int n = derived_LUTs.size();
       for (int i = 0; i < n; i ++) {
         if (derived_LUTs[i]->getColorSpace()==space) {
           result= derived_LUTs[i];
           break;
         }
       }
       unlock();
       return result;
     }
int LUT3D::getDerivedLUTcount () inline
Definition at line 172 of file lut3d.h.
{
       return derived_LUTs.size();
     }
int LUT3D::getMaxX () const inline
Definition at line 257 of file lut3d.h.
{
       return ((0x01 << (X_BITS)) - 0x01);
     }
int LUT3D::getMaxY () const inline
Definition at line 261 of file lut3d.h.
Referenced by GLLUTWidget::glPixel2LUTCoordinates().
{
       return ((0x01 << (Y_BITS)) - 0x01);
     }
int LUT3D::getMaxZ () const inline
Definition at line 265 of file lut3d.h.
Referenced by GLLUTWidget::glPixel2LUTCoordinates().
{
       return ((0x01 << (Z_BITS)) - 0x01);
     }
lut_mask_t* LUT3D::getPointer (unsigned char x, unsigned char y, unsigned char z) const inline
Definition at line 292 of file lut3d.h.
{
       return LUT + (((x >> X_SHIFT) << Z_AND_Y_BITS) | ((y >> Y_SHIFT) << Z_BITS) | (z >> Z_SHIFT));
     }
lut_mask_t* LUT3D::getPointerPreshrunk (unsigned char x, unsigned char y, unsigned char z) const inline
Definition at line 296 of file lut3d.h.
References role._GoToPoint::x, and role._GoToPoint::y.
Referenced by GLLUTWidget::UndoState::restore(), and GLLUTWidget::UndoState::UndoState().
{
       return LUT + (((x) << Z_AND_Y_BITS) | ((y) << Z_BITS) | (z));
     }
VarList* LUT3D::getSettings () inline
Definition at line 148 of file lut3d.h.
Referenced by StackRoboCupSSL::StackRoboCupSSL().
{
       return v_settings;
     }
int LUT3D::getSizeX () const inline
Definition at line 245 of file lut3d.h.
Referenced by GLLUTWidget::init().
{
       return ((0x01 << (X_BITS)));
     }
int LUT3D::getSizeY () const inline
Definition at line 249 of file lut3d.h.
Referenced by GLLUTWidget::drawSlice(), GLLUTWidget::glPixel2LUTCoordinates(), and GLLUTWidget::init().
{
       return ((0x01 << (Y_BITS)));
     }
int LUT3D::getSizeZ () const inline
Definition at line 253 of file lut3d.h.
Referenced by GLLUTWidget::drawSlice(), GLLUTWidget::glPixel2LUTCoordinates(), and GLLUTWidget::init().
{
       return ((0x01 << (Z_BITS)));
     }
lut_mask_t* LUT3D::getTable () const inline
Definition at line 288 of file lut3d.h.
Referenced by CMVisionThreshold::thresholdImageRGB(), CMVisionThreshold::thresholdImageYUV422_UYVY(), and CMVisionThreshold::thresholdImageYUV444().
{
       return LUT;
     }
void LUT3D::loadBlackWhite (LUTChannelMode mode) inline
Definition at line 365 of file lut3d.h.
References RGB::Black, LUTChannelMode_Numeric, and RGB::White.
{
       lock();
       channels.clear();
       if (mode==LUTChannelMode_Numeric) channels.push_back(LUTChannel("<Clear>",RGB::Black));
       channels.push_back(LUTChannel("White",RGB::White));
       channels.push_back(LUTChannel("Black",RGB::Black));
       unlock();
     }
void LUT3D::loadRoboCupChannels (LUTChannelMode mode) inline
Definition at line 349 of file lut3d.h.
References RGB::Black, RGB::Blue, RGB::Cyan, RGB::DarkGreen, RGB::Green, LUTChannelMode_Numeric, RGB::Orange, RGB::Pink, RGB::White, and RGB::Yellow.
Referenced by StackRoboCupSSL::StackRoboCupSSL().
{
       lock();
       channels.clear();
       if (mode==LUTChannelMode_Numeric) channels.push_back(LUTChannel("<Clear>",RGB::Black));
       channels.push_back(LUTChannel("Field Green",RGB::DarkGreen));
       channels.push_back(LUTChannel("Orange",RGB::Orange));
       channels.push_back(LUTChannel("Yellow",RGB::Yellow));
       channels.push_back(LUTChannel("Blue",RGB::Blue));
       channels.push_back(LUTChannel("Pink",RGB::Pink));
       channels.push_back(LUTChannel("Cyan",RGB::Cyan));
       channels.push_back(LUTChannel("Green",RGB::Green));
       channels.push_back(LUTChannel("White",RGB::White));
       channels.push_back(LUTChannel("Black",RGB::Black));
       unlock();
     }
void LUT3D::lock () inline
Definition at line 142 of file lut3d.h.
Referenced by GLLUTWidget::add_del_Pixel(), PluginNeuralColorCalib::CopyNeuraltoLUT(), GLLUTWidget::drawEvent(), CMVisionThreshold::thresholdImageYUV422_UYVY(), and CMVisionThreshold::thresholdImageYUV444().
                 {
       mutex.lock();
     }
unsigned char LUT3D::lut2normX (unsigned char x) const inline
Definition at line 309 of file lut3d.h.
Referenced by GLLUTWidget::drawSlice().
{
       return(x << X_SHIFT);
     }
unsigned char LUT3D::lut2normY (unsigned char y) const inline
Definition at line 312 of file lut3d.h.
Referenced by GLLUTWidget::drawSlice().
{
       return(y << Y_SHIFT);
     }
unsigned char LUT3D::lut2normZ (unsigned char z) const inline
Definition at line 315 of file lut3d.h.
Referenced by GLLUTWidget::drawSlice().
{
       return(z << Z_SHIFT);
     }
void LUT3D::maskFillYZ (unsigned char slice_x, unsigned char origin_y, unsigned char origin_z, lut_mask_t new_color, LUTChannelMode mode, bool remove = false, bool check_exact = true, bool write_exclusive = false) inline
This function fills an area in the y/z plane of an LUT for a given x-slice if check_exact is true then we only extend to pixels matching exactly the origin's mask if it's false then we extend to pixels matching any one of the origin's mask's channels if write_exclusive is true then we set the target pixel to be exactly the new_color if it's false then we OR the target pixel with the new_color the special case is where new_color is 0 in which we go into erase mode. in this case if write_exclusive is false, we will subtract the origins color's from the current pixel Note that the values of check_exact and write_exclusive only matter if mode is LUTChannelMode_Bitwise. They are ignored if mode is LUTChannelMode_Numeric.
Definition at line 375 of file lut3d.h.
References LUTChannelMode_Bitwise, LUTChannelMode_Numeric, LUTFILL_MAXDEPTH, LUTFILL_POP, LUTFILL_PUSH, and role._GoToPoint::x.
Referenced by GLLUTWidget::drawEvent().
     {
       if (mode==LUTChannelMode_Numeric) {
         check_exact=true;
         write_exclusive=true;
       }
       int x=origin_y;
       int y=origin_z;
       int left, x1, x2, dy;
       int x_max_index=getMaxY();
       int y_max_index=getMaxZ();
       lut_mask_t old_color=get_preshrunk(slice_x,x,y);
       //if (remove) old_color=old_color & new_color;
       LINESEGMENT stack[LUTFILL_MAXDEPTH], *sp = stack;
       if (remove==false) {
         //see if the origin is already colored with newcolor
         if ( check_exact ? (old_color == new_color) : ((old_color & new_color) != 0x00) ) return;
       }
       else {
         //see if the origin is already fully removed of newcolor
         if (mode==LUTChannelMode_Bitwise) {
           if ( (old_color & new_color) == 0x00 ) return;
         } else {
           if ( old_color==0x00 ) return;
         }
       }
       if( (x < 0) || (x > x_max_index) || (y < 0) || (y > y_max_index) ) return;
       LUTFILL_PUSH(x, x, y, 1);        /* needed in some cases */
       LUTFILL_PUSH(x, x, y+1, -1);    /* seed segment (popped 1st) */
       while( sp > stack ) {
         LUTFILL_POP(x1, x2, y, dy);
         //for( x = x1; x >= 0 && (check_exact ? (get_preshrunk(slice_x,x,y) == old_color) : ((get_preshrunk(slice_x,x,y) & old_color) != 0x00)); --x )
         for( x = x1; x >= 0 && (check_exact ? (get_preshrunk(slice_x,x,y) == old_color) : (((get_preshrunk(slice_x,x,y) & new_color) == 0x00) == (remove ? false : true)) ); --x )
           (remove ?
             ((mode==LUTChannelMode_Bitwise) ?
               (set_preshrunk(slice_x,x,y,get_preshrunk(slice_x,x,y) & (~new_color))) :
               (set_preshrunk(slice_x,x,y,0x00)))
               :
             (write_exclusive ?
               set_preshrunk(slice_x,x,y,new_color) :
               set_preshrunk(slice_x,x,y,get_preshrunk(slice_x,x,y) | (new_color))));
         if( x >= x1 ) goto SKIP;
         left = x+1;
         if( left < x1 )
           //BUG FIXED by S.Zickler
           //OLD CODE WAS: LUTFILL_PUSH(y, left, x1-1, -dy);    /* leak on left? */
           LUTFILL_PUSH(left, x1-1, y, -dy); /* leak on left? */
         x = x1+1;
         do {
           //for( ; x<=getMaxY() && (check_exact ? (get_preshrunk(slice_x,x,y) == old_color) : ((get_preshrunk(slice_x,x,y) & old_color) != 0x00)); ++x )
           for( ; x<=getMaxY() && (check_exact ? (get_preshrunk(slice_x,x,y) == old_color) : (((get_preshrunk(slice_x,x,y) & new_color) == 0x00) == (remove ? false : true))); ++x )
             (remove ?
               ((mode==LUTChannelMode_Bitwise) ?
               (set_preshrunk(slice_x,x,y,get_preshrunk(slice_x,x,y) & (~new_color))) :
               (set_preshrunk(slice_x,x,y,0x00)))
               :
               (write_exclusive ?
                 set_preshrunk(slice_x,x,y,new_color) :
                 set_preshrunk(slice_x,x,y,get_preshrunk(slice_x,x,y) | (new_color))));
           LUTFILL_PUSH(left, x-1, y, dy);
           if( x > x2+1 ) LUTFILL_PUSH(x2+1, x-1, y, -dy);    /* leak on right? */
         SKIP:
           for( ++x; x <= x2 && ((check_exact ? (get_preshrunk(slice_x,x,y) == old_color) : (((get_preshrunk(slice_x,x,y) & new_color) == 0x00) == (remove ? false : true)))==false); ++x ) {
             ;
           }
           left = x;
         } while( x<=x2 );
       }
     }
unsigned char LUT3D::norm2lutX (unsigned char x) const inline
Definition at line 300 of file lut3d.h.
Referenced by GLLUTWidget::add_del_Pixel(), GLLUTWidget::sampleImage(), and GLLUTWidget::samplePixel().
{
       return(x >> X_SHIFT);
     }
unsigned char LUT3D::norm2lutY (unsigned char y) const inline
Definition at line 303 of file lut3d.h.
Referenced by GLLUTWidget::add_del_Pixel(), GLLUTWidget::sampleImage(), and GLLUTWidget::samplePixel().
{
       return(y >> Y_SHIFT);
     }
unsigned char LUT3D::norm2lutZ (unsigned char z) const inline
Definition at line 306 of file lut3d.h.
Referenced by GLLUTWidget::add_del_Pixel(), GLLUTWidget::sampleImage(), and GLLUTWidget::samplePixel().
{
       return(z >> Z_SHIFT);
     }
void LUT3D::reset () inline
Definition at line 282 of file lut3d.h.
                  {
       lock();
       memset(LUT,0x00,LUT_SIZE*sizeof(lut_mask_t));
       unlock();
     };
void LUT3D::set (unsigned char x, unsigned char y, unsigned char z, lut_mask_t mask) inline
Definition at line 319 of file lut3d.h.
Referenced by PluginNeuralColorCalib::CopyNeuraltoLUT().
{
       LUT[((x >> X_SHIFT) << Z_AND_Y_BITS) | ((y >> Y_SHIFT) << Z_BITS) | (z >> Z_SHIFT)]=mask;
     }
void LUT3D::set_preshrunk (unsigned char x, unsigned char y, unsigned char z, lut_mask_t mask) inline
Definition at line 323 of file lut3d.h.
References role._GoToPoint::x, and role._GoToPoint::y.
Referenced by GLLUTWidget::drawSinglePixel().
{
       LUT[((x) << Z_AND_Y_BITS) | ((y) << Z_BITS) | (z)]=mask;
     }
void LUT3D::setChannel (unsigned int idx, LUTChannel c) inline
Definition at line 233 of file lut3d.h.
{
       if (idx < channels.size()) {
         channels[idx]=c;
       } else {
         fprintf(stderr,"invalid channel selected in getChannel(...)\n");
       }
     }
void LUT3D::slotVBlobChange () inline protected slot
Definition at line 104 of file lut3d.h.
{
       updateDerivedLUTs();
     }
void LUT3D::unlock () inline
Definition at line 145 of file lut3d.h.
Referenced by GLLUTWidget::add_del_Pixel(), PluginNeuralColorCalib::CopyNeuraltoLUT(), GLLUTWidget::drawEvent(), CMVisionThreshold::thresholdImageYUV422_UYVY(), and CMVisionThreshold::thresholdImageYUV444().
                   {
       mutex.unlock();
     }
void LUT3D::updateDerivedLUTs () inline
Definition at line 206 of file lut3d.h.
References velocity.pid_::i.
Referenced by GLLUTWidget::add_del_Pixel(), GLLUTWidget::editRedo(), GLLUTWidget::editUndo(), and GLLUTWidget::mouseReleaseEvent().
{
       lock();
       int n = derived_LUTs.size();
       for (int i = 0; i < n; i ++) {
         derived_LUTs[i]->copyChannels(*this);
         derived_LUTs[i]->deriveFromLUT(this);
       }
       unlock();
     }
Field Documentation
vector<LUTChannel> LUT3D::channels
Definition at line 100 of file lut3d.h.
Referenced by GLLUTWidget::maskToRGBA(), LUTWidget::updateList(), and NeuroWidget::updateList().
vector<LUT3D *> LUT3D::derived_LUTs
Definition at line 101 of file lut3d.h.
lut_mask_t* LUT3D::LUT
Definition at line 97 of file lut3d.h.
unsigned int LUT3D::LUT_SIZE
Definition at line 95 of file lut3d.h.
Referenced by GLLUTWidget::UndoState::restore(), and GLLUTWidget::UndoState::UndoState().
QMutex LUT3D::mutex
Definition at line 102 of file lut3d.h.
unsigned int LUT3D::TOTAL_BITS
Definition at line 94 of file lut3d.h.
VarBlob* LUT3D::v_blob
Definition at line 98 of file lut3d.h.
VarList* LUT3D::v_settings
Definition at line 99 of file lut3d.h.
unsigned int LUT3D::X_BITS
Definition at line 81 of file lut3d.h.
unsigned int LUT3D::X_SHIFT
Definition at line 86 of file lut3d.h.
Referenced by PluginNeuralColorCalib::CopyNeuraltoLUT(), CMVisionThreshold::thresholdImageRGB(), CMVisionThreshold::thresholdImageYUV422_UYVY(), and CMVisionThreshold::thresholdImageYUV444().
unsigned int LUT3D::Y_BITS
Definition at line 82 of file lut3d.h.
unsigned int LUT3D::Y_SHIFT
Definition at line 87 of file lut3d.h.
Referenced by PluginNeuralColorCalib::CopyNeuraltoLUT(), CMVisionThreshold::thresholdImageRGB(), CMVisionThreshold::thresholdImageYUV422_UYVY(), and CMVisionThreshold::thresholdImageYUV444().
unsigned int LUT3D::Y_SHIFT_PLUS_8
Definition at line 90 of file lut3d.h.
unsigned int LUT3D::Z_AND_Y_BITS
Definition at line 93 of file lut3d.h.
Referenced by CMVisionThreshold::thresholdImageRGB(), CMVisionThreshold::thresholdImageYUV422_UYVY(), and CMVisionThreshold::thresholdImageYUV444().
unsigned int LUT3D::Z_BITS
Definition at line 83 of file lut3d.h.
Referenced by CMVisionThreshold::thresholdImageRGB(), CMVisionThreshold::thresholdImageYUV422_UYVY(), and CMVisionThreshold::thresholdImageYUV444().
unsigned int LUT3D::Z_SHIFT
Definition at line 88 of file lut3d.h.
Referenced by PluginNeuralColorCalib::CopyNeuraltoLUT(), CMVisionThreshold::thresholdImageRGB(), CMVisionThreshold::thresholdImageYUV422_UYVY(), and CMVisionThreshold::thresholdImageYUV444().
unsigned int LUT3D::Z_SHIFT_PLUS_16
Definition at line 91 of file lut3d.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/lut3d.h