Documentation: PWorld Class Reference
PWorld Class Reference
#include <pworld.h>
Public Member Functions
PWorld (dReal dt, dReal gravity, CGraphics *graphics)
~PWorld ()
void setGravity (dReal gravity)
void addObject (PObject *o)
void initAllObjects ()
PSurface * createSurface (PObject *o1, PObject *o2)
PSurface * findSurface (PObject *o1, PObject *o2)
void step (dReal dt=-1)
void glinit ()
void draw ()
void handleCollisions (dGeomID o1, dGeomID o2)
Data Fields
dWorldID world
dSpaceID space
CGraphics * g
Private Attributes
dJointGroupID contactgroup
QVector< PObject * > objects
QVector< PSurface * > surfaces
dReal delta_time
int ** sur_matrix
int objects_count
Detailed Description
Definition at line 27 of file pworld.h.
Constructor & Destructor Documentation
PWorld::PWorld (dReal dt, dReal gravity, CGraphics * graphics)
Definition at line 39 of file pworld.cpp.
References velocity.pid::dt.
 {
     //dInitODE2(0);
     dInitODE();
     world = dWorldCreate();
     space = dHashSpaceCreate (0);
     contactgroup = dJointGroupCreate (0);
     dWorldSetGravity (world,0,0,-gravity);
     objects_count = 0;
     sur_matrix = NULL;
     //dAllocateODEDataForThread(dAllocateMaskAll);
     delta_time = dt;
     g = graphics;
 }
PWorld::~PWorld ()
Definition at line 54 of file pworld.cpp.
 {
   dJointGroupDestroy (contactgroup);
   dSpaceDestroy (space);
   dWorldDestroy (world);
   dCloseODE();
 }
Member Function Documentation
void PWorld::addObject (PObject * o)
Definition at line 107 of file pworld.cpp.
References PObject::g, PObject::geom, PObject::id, PObject::init(), PObject::space, and PObject::world.
Referenced by Robot::Kicker::Kicker(), Robot::Robot(), SSLWorld::SSLWorld(), and Robot::Wheel::Wheel().
 {
     int id = objects.count();
     o->id = id;
     if (o->world==NULL) o->world = world;
     if (o->space==NULL) o->space = space;
     o->g = g;
     o->init();
     dGeomSetData(o->geom,(void*)(&(o->id)));
     objects.append(o);
 }
PSurface * PWorld::createSurface (PObject * o1, PObject * o2)
Definition at line 146 of file pworld.cpp.
References PObject::geom, PObject::id, PSurface::id1, PSurface::id2, and PSurface::PSurface().
Referenced by SSLWorld::SSLWorld().
 {
     PSurface *s = new PSurface();
     s->id1 = o1->geom;
     s->id2 = o2->geom;
     surfaces.append(s);
     sur_matrix[o1->id][o2->id] =
     sur_matrix[o2->id][o1->id] = surfaces.count() - 1;
     return s;
 }
void PWorld::draw ()
Definition at line 179 of file pworld.cpp.
References velocity.pid_::i.
Referenced by SSLWorld::step().
 {
     for (int i=0;i<objects.count();i++)
         if (objects[i]->getVisibility()) objects[i]->draw();
 }
PSurface * PWorld::findSurface (PObject * o1, PObject * o2)
Definition at line 157 of file pworld.cpp.
References PObject::geom, velocity.pid_::i, and PSurface::isIt().
Referenced by MainWindow::changeBallGroundSurface().
 {
     for (int i=0;i<surfaces.count();i++)
     {
         if (surfaces[i]->isIt(o1->geom,o2->geom)) return (surfaces[i]);
     }
     return NULL;
 }
void PWorld::glinit ()
Definition at line 185 of file pworld.cpp.
References velocity.pid_::i.
Referenced by SSLWorld::glinit().
 {
     for (int i=0;i<objects.count();i++)
         objects[i]->glinit();
 }
void PWorld::handleCollisions (dGeomID o1, dGeomID o2)
Definition at line 67 of file pworld.cpp.
References PSurface::callback, PSurface::contactNormal, PSurface::contactPos, PSurface::fdir1, velocity.pid_::i, PSurface::surface, and PSurface::usefdir1.
 {
     PSurface* sur;
     int j=sur_matrix[*((int*)(dGeomGetData(o1)))][*((int*)(dGeomGetData(o2)))];
     if (j!=-1)
     {
         const int N = 10;
         dContact contact[N];
         int n = dCollide (o1,o2,N,&contact[0].geom,sizeof(dContact));
         if (n > 0) {
           sur = surfaces[j];
           sur->contactPos   [0] = contact[0].geom.pos[0];
           sur->contactPos   [1] = contact[0].geom.pos[1];
           sur->contactPos   [2] = contact[0].geom.pos[2];
           sur->contactNormal[0] = contact[0].geom.normal[0];
           sur->contactNormal[1] = contact[0].geom.normal[1];
           sur->contactNormal[2] = contact[0].geom.normal[2];
           bool flag=true;
           if (sur->callback!=NULL) flag = sur->callback(o1,o2,sur);
           if (flag)
           for (int i=0; i<n; i++) {
               contact[i].surface = sur->surface;
               if (sur->usefdir1)
               {
                   contact[i].fdir1[0] = sur->fdir1[0];
                   contact[i].fdir1[1] = sur->fdir1[1];
                   contact[i].fdir1[2] = sur->fdir1[2];
                   contact[i].fdir1[3] = sur->fdir1[3];
               }
               dJointID c = dJointCreateContact (world,contactgroup,&contact[i]);
               dJointAttach (c,
                             dGeomGetBody(contact[i].geom.g1),
                             dGeomGetBody(contact[i].geom.g2));
             }
         }
     }
 }
void PWorld::initAllObjects ()
Definition at line 119 of file pworld.cpp.
References velocity.pid_::i, PSurface::id1, and PSurface::id2.
Referenced by SSLWorld::SSLWorld().
 {
     objects_count = objects.count();
     int c = objects_count;
     bool flag = false;
     if (sur_matrix!=NULL)
     {
         for (int i=0;i<c;i++)
             delete sur_matrix[i];
         delete sur_matrix;
         flag = true;
     }
     sur_matrix = new int* [c];
     for (int i=0;i<c;i++)
     {
         sur_matrix[i] = new int [c];
         for (int j=0;j<c;j++)
             sur_matrix[i][j] = -1;
     }
     if (flag)
     {
         for (int i=0;i<surfaces.count();i++)
             sur_matrix[(*(int*)(dGeomGetData(surfaces[i]->id1)))][*((int*)(dGeomGetData(surfaces[i]->id2)))] =
             sur_matrix[(*(int*)(dGeomGetData(surfaces[i]->id2)))][*((int*)(dGeomGetData(surfaces[i]->id1)))] = i;
     }
 }
void PWorld::setGravity (dReal gravity)
Definition at line 62 of file pworld.cpp.
 {
     dWorldSetGravity (world,0,0,-gravity);
 }
void PWorld::step (dReal dt = -1)
Definition at line 166 of file pworld.cpp.
References nearCallback().
Referenced by SSLWorld::step().
 {
     try {
     dSpaceCollide (space,this,&nearCallback);
     dWorldStep (world,(dt<0) ? delta_time : dt);
     dJointGroupEmpty (contactgroup);
     }
     catch (...)
     {
         //qDebug() << "Some Error Happened;";
     }
 }
Field Documentation
dJointGroupID PWorld::contactgroup private
Definition at line 30 of file pworld.h.
dReal PWorld::delta_time private
Definition at line 33 of file pworld.h.
CGraphics* PWorld::g
Definition at line 50 of file pworld.h.
Referenced by Robot::drawLabel().
QVector<PObject*> PWorld::objects private
Definition at line 31 of file pworld.h.
int PWorld::objects_count private
Definition at line 35 of file pworld.h.
dSpaceID PWorld::space
Definition at line 49 of file pworld.h.
Referenced by Robot::Robot().
int** PWorld::sur_matrix private
Definition at line 34 of file pworld.h.
QVector<PSurface*> PWorld::surfaces private
Definition at line 32 of file pworld.h.
dWorldID PWorld::world
Definition at line 48 of file pworld.h.
Referenced by MainWindow::changeGravity(), Robot::Kicker::Kicker(), Robot::Robot(), and Robot::Wheel::Wheel().
The documentation for this class was generated from the following files:
grSim/include/physics/pworld.h
grSim/src/physics/pworld.cpp