Documentation: behavior.Behavior Class Reference
behavior.Behavior Class Reference
Behavior is an abstract superclass for Skill, Play, etc.
Data Structures
class State
These are the core states of the Behavior class Subclasses may extend this by adding substates of the following.
Public Member Functions
def __init__ (self)
def is_done_running (self)
Whether or not the Behavior is running Because we use hierarchial state machines, a behavior never be in the "running", but may be in a substate of it This is a convenience method to check whether or not the play is running.
def set_failed (self)
Set the behavior to failed if sub behaviors remains uncompleted.
def terminate (self)
Transitions the Behavior into a terminal state (either completed or cancelled)
def behavior_state (self)
returns a state in Behavior.State that represents what the behaviors is doing use this instead of the property if you want to avoid dealing with custom subclass substates
Public Member Functions inherited from fsm.StateMachine
def __init__ (self, start_state, end_state)
def start_state (self)
def restart (self)
def add_state (self, state, parent_state=None)
def spin (self)
def add_transition (self, from_state, to_state, condition, event_name)
def transition (self, new_state)
def is_in_state (self, state)
def state_is_substate (self, state, possible_parent)
def corresponding_ancestor_state (self, ancestors)
def ancestors_of_state (self, state)
def as_graphviz (self)
def write_diagram_png (self)
def state (self)
Detailed Description
Behavior is an abstract superclass for Skill, Play, etc.
Definition at line 7 of file behavior.py.
Constructor & Destructor Documentation
def behavior.Behavior.__init__ (self)
Definition at line 20 of file behavior.py.
References fsm.StateMachine.add_state().
     def __init__(self):
         # print "behav"
         super(Behavior, self).__init__(start_state=Behavior.State.start,end_state=Behavior.State.completed)
         # add base states for Behavior
         self.add_state(Behavior.State.start)
         self.add_state(Behavior.State.running)
         self.add_state(Behavior.State.completed)
         self.add_state(Behavior.State.failed)
         self.add_state(Behavior.State.cancelled)
         #self._is_continuous = continuous
Member Function Documentation
def behavior.Behavior.behavior_state (self)
returns a state in Behavior.State that represents what the behaviors is doing use this instead of the property if you want to avoid dealing with custom subclass substates
Definition at line 63 of file behavior.py.
References fsm.StateMachine.corresponding_ancestor_state().
     def behavior_state(self):
         return self.corresponding_ancestor_state(list(Behavior.State))
def behavior.Behavior.is_done_running (self)
Whether or not the Behavior is running Because we use hierarchial state machines, a behavior never be in the "running", but may be in a substate of it This is a convenience method to check whether or not the play is running.
Definition at line 39 of file behavior.py.
References fsm.StateMachine.is_in_state().
Referenced by behavior.Behavior.set_failed(), and behavior.Behavior.terminate().
     def is_done_running(self) :
         for state in [Behavior.State.completed, Behavior.State.failed,
                       Behavior.State.cancelled]:
             if self.is_in_state(state): return True
         return False
def behavior.Behavior.set_failed (self)
Set the behavior to failed if sub behaviors remains uncompleted.
Definition at line 47 of file behavior.py.
References behavior.Behavior.is_done_running(), and fsm.StateMachine.transition().
     def set_failed(self):
         if self.is_done_running():
             logging.warn("Attempt to set fail flag to a behavior that's already done running")
         else:
             self.transition(Behavior.State.failed)
def behavior.Behavior.terminate (self)
Transitions the Behavior into a terminal state (either completed or cancelled)
Definition at line 54 of file behavior.py.
References behavior.Behavior.is_done_running(), and fsm.StateMachine.transition().
     def terminate(self):
         if self.is_done_running():
             logging.warn("Attempt to terminate behavior that's already done running")
         else:
             self.transition(Behavior.State.cancelled)
The documentation for this class was generated from the following file:
behavior.py