Documentation: PluginColorThreshold Class Reference
PluginColorThreshold Class Reference
#include <plugin_colorthreshold.h>
Public Member Functions
PluginColorThreshold (FrameBuffer *_buffer, YUVLUT *_lut)
~PluginColorThreshold ()
virtual ProcessResult process (FrameData *data, RenderOptions *options)
virtual VarList * getSettings ()
virtual string getName ()
Public Member Functions inherited from VisionPlugin
VisionPlugin (FrameBuffer *_buffer)
virtual ~VisionPlugin ()
FrameBuffer * getFrameBuffer () const
this functions provides convenient access to the ring-buffer
void lock ()
void unlock ()
virtual bool isEnabled () const
virtual void setEnabled (bool enable)
virtual bool isVisualize () const
virtual void setVisualize (bool enable)
virtual bool isSharedAmongStacks () const
virtual void setSharedAmongStacks (bool enable)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual void postProcess (FrameData *data, RenderOptions *options)
virtual QWidget * getVisualizationWidget ()
virtual QWidget * getControlWidget ()
virtual void closeWidgets ()
virtual QList< QAction * > actions ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
void setTimeProcessing (double val)
void setTimePostProcessing (double val)
double getTimeProcessing ()
double getTimePostProcessing ()
Protected Attributes
YUVLUT * lut
Protected Attributes inherited from VisionPlugin
QMutex mutex
bool enabled
bool visualize
bool shared
FrameBuffer * buffer
double time_proc
double time_post
Additional Inherited Members
Public Slots inherited from VisionPlugin
void slotKeyPressEvent (QKeyEvent *event)
Detailed Description
Author
Stefan Zickler
Definition at line 31 of file plugin_colorthreshold.h.
Constructor & Destructor Documentation
PluginColorThreshold::PluginColorThreshold (FrameBuffer * _buffer, YUVLUT * _lut)
Definition at line 23 of file plugin_colorthreshold.cpp.
References lut.
  : VisionPlugin(_buffer)
 {
   lut=_lut;
 }
PluginColorThreshold::~PluginColorThreshold ()
Definition at line 30 of file plugin_colorthreshold.cpp.
 {
 }
Member Function Documentation
string PluginColorThreshold::getName () virtual
Reimplemented from VisionPlugin.
Definition at line 76 of file plugin_colorthreshold.cpp.
{
   return "Segmentation";
 }
VarList * PluginColorThreshold::getSettings () virtual
Reimplemented from VisionPlugin.
Definition at line 72 of file plugin_colorthreshold.cpp.
{
   return 0;
 }
ProcessResult PluginColorThreshold::process (FrameData * data, RenderOptions * options) virtual
Reimplemented from VisionPlugin.
Definition at line 36 of file plugin_colorthreshold.cpp.
References Image< PIXEL >::allocate(), COLOR_RGB8, COLOR_YUV422_UYVY, COLOR_YUV444, Colors::colorFormatToString(), CSPACE_RGB, FrameDataMap::get(), RawImage::getColorFormat(), LUT3D::getDerivedLUT(), RawImage::getHeight(), RawImage::getWidth(), FrameDataMap::insert(), lut, FrameData::map, ProcessingFailed, ProcessingOk, CMVisionThreshold::thresholdImageRGB(), CMVisionThreshold::thresholdImageYUV422_UYVY(), CMVisionThreshold::thresholdImageYUV444(), and FrameData::video.
{
   (void)options;
   Image<raw8> * img_thresholded;
   if ((img_thresholded=(Image<raw8> *)data->map.get("cmv_threshold")) == 0) {
     img_thresholded=(Image<raw8> *)data->map.insert("cmv_threshold",new Image<raw8>());
   }
   if (data->video.getColorFormat()==COLOR_YUV422_UYVY) {
     //make sure image is allocated:
     img_thresholded->allocate(data->video.getWidth(),data->video.getHeight());
     //directly apply YUV lut:
     CMVisionThreshold::thresholdImageYUV422_UYVY(img_thresholded,&(data->video),lut);
   } else if (data->video.getColorFormat()==COLOR_YUV444) {
     //make sure image is allocated:
     img_thresholded->allocate(data->video.getWidth(),data->video.getHeight());
     //directly apply YUV lut:
     CMVisionThreshold::thresholdImageYUV444(img_thresholded,&(data->video),lut);
   } else if (data->video.getColorFormat()==COLOR_RGB8) {
     //FIXME: check for changes in YUV LUT....if changed...copy things to RGB lut...
     RGBLUT * rgblut = (RGBLUT *) lut->getDerivedLUT(CSPACE_RGB);
     if (rgblut==0) {
       printf("WARNING: No RGB LUT has been defined. You need to create a derived RGB LUT by calling e.g. \"lut_yuv->addDerivedLUT(new RGBLUT(5,5,5,\"\"))\" in the stack constructor!\n");
     } else {
       img_thresholded->allocate(data->video.getWidth(),data->video.getHeight());
       CMVisionThreshold::thresholdImageRGB(img_thresholded,&(data->video),rgblut);
     }
   } else {
     fprintf(stderr,"ColorThresholding needs YUV422, YUV444, or RGB8 as input image, but found: %s\n",Colors::colorFormatToString(data->video.getColorFormat()).c_str());
     return ProcessingFailed;
   }
   return ProcessingOk;
 }
Field Documentation
YUVLUT* PluginColorThreshold::lut protected
Definition at line 34 of file plugin_colorthreshold.h.
Referenced by PluginColorThreshold(), and process().
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/plugin_colorthreshold.h
ssl-vision/src/app/plugins/plugin_colorthreshold.cpp