Documentation: ssl-vision/src/app/plugins/plugin_legacypublishgeometry.h File Reference
plugin_legacypublishgeometry.h File Reference
C++ Interface: plugin_legacypublishgeometry.
#include <visionplugin.h>
#include "robocup_ssl_server.h"
#include "camera_calibration.h"
#include "messages_robocup_ssl_geometry_legacy.pb.h"
#include "VarTypes.h"
Data Structures
class PluginLegacyPublishGeometry
Functions
const FieldLine * GetFieldLine (const string &line_name, const vector< FieldLine * > &field_lines)
const FieldCircularArc * GetFieldCircularArc (const string &arc_name, const vector< FieldCircularArc * > &field_arcs)
Detailed Description
C++ Interface: plugin_legacypublishgeometry.
Author
Joydeep Biswas, 2014
Definition in file plugin_legacypublishgeometry.h.
Function Documentation
const FieldCircularArc* GetFieldCircularArc (const string & arc_name, const vector< FieldCircularArc * > & field_arcs)
Definition at line 35 of file plugin_legacypublishgeometry.cpp.
References velocity.pid_::i.
Referenced by PluginLegacyPublishGeometry::GetFieldCircularArcRadius().
{
   for (size_t i = 0; i < field_arcs.size(); ++i) {
     if (arc_name.compare(field_arcs[i]->name->getString()) == 0) {
       return (field_arcs[i]);
     }
   }
   fprintf(stderr, "ERROR: Field Arc \"%s\" not found!\n", arc_name.c_str());
   return NULL;
 }
const FieldLine* GetFieldLine (const string & line_name, const vector< FieldLine * > & field_lines)
Definition at line 23 of file plugin_legacypublishgeometry.cpp.
References velocity.pid_::i.
Referenced by PluginLegacySSLNetworkOutput::DoubleSizeToSingleSize(), PluginLegacyPublishGeometry::GetFieldLineLength(), and PluginLegacyPublishGeometry::GetFieldLineThickness().
{
   for (size_t i = 0; i < field_lines.size(); ++i) {
     if (line_name.compare(field_lines[i]->name->getString()) == 0) {
       return (field_lines[i]);
     }
   }
   fprintf(stderr, "ERROR: Field Line \"%s\" not found!\n", line_name.c_str());
   return NULL;
 }