Documentation: Conversions Class Reference
Conversions Class Reference
#include <conversions.h>
Static Public Member Functions
static void yuv2rgb (int y, int u, int v, int &r, int &g, int &b)
static rgb yuv2rgb (yuv const &in)
static rgb rgba2rgb (rgb const &in)
static rgba rgb2rgba (rgb const &in, unsigned char alpha=0)
static void rgb2yuv (int r, int g, int b, int &y, int &u, int &v)
static yuv rgb2yuv (rgb const &in)
static void uyvy2rgb (unsigned char *src, unsigned char *dest, int width, int height)
static void yuyv2rgb (unsigned char *src, unsigned char *dest, int width, int height)
static void rgb2uyvy (unsigned char *src, unsigned char *dest, int width, int height)
static void rgb2yuyv (unsigned char *src, unsigned char *dest, int width, int height)
static void uyyvyy2rgb (unsigned char *src, unsigned char *dest, int width, int height)
static void y2rgb (unsigned char *src, unsigned char *dest, int width, int height)
static void bgr2rgb (unsigned char *src, unsigned char *dest, int width, int height)
static void rgb2bgr (unsigned char *src, unsigned char *dest, int width, int height)
static void rgb482rgb (unsigned char *src, unsigned char *dest, int width, int height)
static void uyv2rgb (unsigned char *src, unsigned char *dest, int width, int height)
static void uyvy2bgr (unsigned char *src, unsigned char *dest, int width, int height)
static void y162rgb (unsigned char *src, unsigned char *dest, int width, int height, int bits)
Detailed Description
Definition at line 40 of file conversions.h.
Member Function Documentation
void Conversions::bgr2rgb (unsigned char * src, unsigned char * dest, int width, int height) static
Definition at line 33 of file conversions.cpp.
References velocity.pid_::i.
Referenced by rgb2yuv().
{
   int NumPixels = width*height;
   for ( int i=0;i<NumPixels*3;i+=3 ) {
     dest[i]   = src[i+2];
     dest[i+1] = src[i+1];
     dest[i+2] = src[i];
   }
 }
void Conversions::rgb2bgr (unsigned char * src, unsigned char * dest, int width, int height) static
Definition at line 45 of file conversions.cpp.
References velocity.pid_::i.
Referenced by rgb2yuv().
{
   int NumPixels = width*height;
   for ( int i=0;i<NumPixels*3;i+=3 ) {
     dest[i]   = src[i+2];
     dest[i+1] = src[i+1];
     dest[i+2] = src[i];
   }
 }
static rgba Conversions::rgb2rgba (rgb const & in, unsigned char alpha = 0) inline static
Definition at line 73 of file conversions.h.
References ColorRGB< num, fmt >::b, ColorRGB< num, fmt >::g, ColorRGB< num, fmt >::r, and ColorRGBA< num, fmt >::set().
Referenced by GLLUTWidget::drawSlice(), and GLLUTWidget::maskToRGBA().
{
   rgba out;
   out.set(in.r,in.g,in.b,alpha);
   return out;
 }
void Conversions::rgb2uyvy (unsigned char * src, unsigned char * dest, int width, int height) static
Definition at line 169 of file conversions.cpp.
References velocity.pid_::i, and v.
Referenced by CaptureV4L::convertFrame(), and rgb2yuv().
 {
 #ifndef NO_DC1394_CONVERSIONS
     dc1394_convert_to_RGB8(src,dest, width, height, DC1394_BYTE_ORDER_UYVY,
                            DC1394_COLOR_CODING_RGB8, 8);
 #else
     int NumPixels = width*height;
     register int max_i = ( NumPixels << 1 )-1;
     //register int max_j = NumPixels + ( NumPixels << 1 ) -1;
     register int i = 0;
     register int j = 0;
     register int y0, y1, u, v;
     register int r, g, b;
     while ( i < max_i ) {
         r = ( unsigned char ) src[i++];
         g = ( unsigned char ) src[i++];
         b = ( unsigned char ) src[i++];
         rgb2yuv ( r, g, b, y0, u, v );
         r = ( unsigned char ) src[i++];
         g = ( unsigned char ) src[i++];
         b = ( unsigned char ) src[i++];
         rgb2yuv ( r, g, b, y1, u, v );
         dest[j++] = u+128;
         dest[j++] = y0;
         dest[j++] = v+128;
         dest[j++] = y1;
     }
 #endif
 }
static void Conversions::rgb2yuv (int r, int g, int b, int & y, int & u, int & v) inline static
Definition at line 79 of file conversions.h.
References GVector::bound().
Referenced by YUVLUT::computeLUTfromLabels(), Images::convert(), RGBLUT::deriveFromLUT(), PluginColorCalibration::mouseEvent(), PluginNeuralColorCalib::mouseEvent(), rgb2yuv(), and GLLUTWidget::sampleImage().
 {
   y = bound((306*r + 601*g + 117*b)  >> 10, 0, 255);
   u = bound(((-172*r - 340*g + 512*b) >> 10)  + 128, 0, 255);
   v = bound(((512*r - 429*g - 83*b) >> 10) + 128, 0, 255);
 }
static yuv Conversions::rgb2yuv (rgb const & in) inline static
Definition at line 85 of file conversions.h.
References ColorRGB< num, fmt >::b, bgr2rgb(), ColorRGB< num, fmt >::g, ColorRGB< num, fmt >::r, rgb2bgr(), rgb2uyvy(), rgb2yuv(), rgb2yuyv(), rgb482rgb(), ColorYUV< num, fmt >::u, uyv2rgb(), uyvy2bgr(), uyvy2rgb(), uyyvyy2rgb(), v, ColorYUV< num, fmt >::v, role._GoToPoint::y, ColorYUV< num, fmt >::y, y162rgb(), y2rgb(), and yuyv2rgb().
 {
   yuv col;
   int y, u, v;
   rgb2yuv((int) in.r, (int) in.g,
           (int) in.b, y, u, v);
   col.y = (unsigned char) y;
   col.u = (unsigned char) u;
   col.v = (unsigned char) v;
   return (col);
 }
void Conversions::rgb2yuyv (unsigned char * src, unsigned char * dest, int width, int height) static
Definition at line 203 of file conversions.cpp.
References velocity.pid_::i, v, and role._GoToPoint::y.
Referenced by CaptureV4L::convertFrame(), and rgb2yuv().
 {
 #ifndef NO_DC1394_CONVERSIONS
     dc1394_convert_to_RGB8(src,dest, width, height, DC1394_BYTE_ORDER_YUYV,
                            DC1394_COLOR_CODING_RGB8, 8);
 #else
     int NumPixels = width*height;
     register int max_i = ( NumPixels << 1 )-1;
     //register int max_j = NumPixels + ( NumPixels << 1 ) -1;
     register int i = 0;
     register int j = 0;
     register int y0, y1, u, v;
     register int r, g, b;
     rgb2yuv(int r, int g, int b, int & y, int & u, int & v
     while ( i < max_i ) {
         r = ( unsigned char ) src[i++];
         g = ( unsigned char ) src[i++];
         b = ( unsigned char ) src[i++];
         rgb2yuv ( r, g, b, y0, u, v );
         r = ( unsigned char ) src[i++];
         g = ( unsigned char ) src[i++];
         b = ( unsigned char ) src[i++];
         rgb2yuv ( r, g, b, y1, u, v );
         dest[j++] = y0;
         dest[j++] = u+128;
         dest[j++] = y1;
         dest[j++] = v+128;
     }
 #endif
 }
void Conversions::rgb482rgb (unsigned char * src, unsigned char * dest, int width, int height) static
Definition at line 57 of file conversions.cpp.
References velocity.pid_::i.
Referenced by rgb2yuv().
{
   int NumPixels = width*height;
   register int i = ( ( NumPixels + ( NumPixels << 1 ) ) << 1 )-1;
   register int j = NumPixels + ( NumPixels << 1 ) -1;
   while ( i > 0 ) {
     i--;
     dest[j--]=src[i--];
     i--;
     dest[j--]=src[i--];
     i--;
     dest[j--]=src[i--];
   }
 }
static rgb Conversions::rgba2rgb (rgb const & in) inline static
Definition at line 67 of file conversions.h.
References ColorRGB< num, fmt >::b, ColorRGB< num, fmt >::g, ColorRGB< num, fmt >::r, and ColorRGB< num, fmt >::set().
{
   rgb out;
   out.set(in.r,in.g,in.b);
   return out;
 }
void Conversions::uyv2rgb (unsigned char * src, unsigned char * dest, int width, int height) static
Definition at line 76 of file conversions.cpp.
References velocity.pid_::i, v, and role._GoToPoint::y.
Referenced by rgb2yuv().
{
   int NumPixels = width*height;
   register int i = NumPixels + ( NumPixels << 1 ) -1;
   register int j = NumPixels + ( NumPixels << 1 ) -1;
   register int y, u, v;
   int r, g, b;
   while ( i > 0 ) {
     v = ( unsigned char ) src[i--] - 128;
     y = ( unsigned char ) src[i--];
     u = ( unsigned char ) src[i--] - 128;
     yuv2rgb ( y, u, v, r, g, b );
     dest[j--] = b;
     dest[j--] = g;
     dest[j--] = r;
   }
 }
void Conversions::uyvy2bgr (unsigned char * src, unsigned char * dest, int width, int height) static
Definition at line 238 of file conversions.cpp.
References velocity.pid_::i, and v.
Referenced by rgb2yuv().
{
   int NumPixels = width*height;
   register int i = ( NumPixels << 1 )-1;
   register int j = NumPixels + ( NumPixels << 1 ) -1;
   register int y0, y1, u, v;
   int r, g, b;
   while ( i > 0 ) {
     y1 = ( unsigned char ) src[i--];
     v  = ( unsigned char ) src[i--] - 128;
     y0 = ( unsigned char ) src[i--];
     u  = ( unsigned char ) src[i--] - 128;
     yuv2rgb ( y1, u, v, r, g, b );
     dest[j--] = r;
     dest[j--] = g;
     dest[j--] = b;
     yuv2rgb ( y0, u, v, r, g, b );
     dest[j--] = r;
     dest[j--] = g;
     dest[j--] = b;
   }
 }
void Conversions::uyvy2rgb (unsigned char * src, unsigned char * dest, int width, int height) static
Definition at line 98 of file conversions.cpp.
References velocity.pid_::i, and v.
Referenced by PluginCameraCalibration::detectEdges(), PluginVisualize::DrawCameraImage(), rgb2yuv(), and PluginDVR::slotMovieSave().
{
   #ifndef NO_DC1394_CONVERSIONS
     dc1394_convert_to_RGB8(src,dest, width, height, DC1394_BYTE_ORDER_UYVY,
                        DC1394_COLOR_CODING_YUV422, 8);
   #else
   int NumPixels = width*height;
   register int max_i = ( NumPixels << 1 )-1;
   //register int max_j = NumPixels + ( NumPixels << 1 ) -1;
   register int i = 0;
   register int j = 0;
   register int y0, y1, u, v;
   register int r, g, b;
   while ( i < max_i ) {
     u  = ( unsigned char ) src[i++] - 128;
     y0 = ( unsigned char ) src[i++];
     v  = ( unsigned char ) src[i++] - 128;
     y1 = ( unsigned char ) src[i++];
     yuv2rgb ( y0, u, v, r, g, b );
     dest[j++] = r;
     dest[j++] = g;
     dest[j++] = b;
     yuv2rgb ( y1, u, v, r, g, b );
     dest[j++] = r;
     dest[j++] = g;
     dest[j++] = b;
   }
   #endif
 }
void Conversions::uyyvyy2rgb (unsigned char * src, unsigned char * dest, int width, int height) static
Definition at line 266 of file conversions.cpp.
References velocity.pid_::i, and v.
Referenced by rgb2yuv().
{
   int NumPixels = width*height;
   register int i = NumPixels + ( NumPixels >> 1 )-1;
   register int j = NumPixels + ( NumPixels << 1 )-1;
   register int y0, y1, y2, y3, u, v;
   int r, g, b;
   while ( i > 0 ) {
     y3 = ( unsigned char ) src[i--];
     y2 = ( unsigned char ) src[i--];
     v  = ( unsigned char ) src[i--] - 128;
     y1 = ( unsigned char ) src[i--];
     y0 = ( unsigned char ) src[i--];
     u  = ( unsigned char ) src[i--] - 128;
     yuv2rgb ( y3, u, v, r, g, b );
     dest[j--] = b;
     dest[j--] = g;
     dest[j--] = r;
     yuv2rgb ( y2, u, v, r, g, b );
     dest[j--] = b;
     dest[j--] = g;
     dest[j--] = r;
     yuv2rgb ( y1, u, v, r, g, b );
     dest[j--] = b;
     dest[j--] = g;
     dest[j--] = r;
     yuv2rgb ( y0, u, v, r, g, b );
     dest[j--] = b;
     dest[j--] = g;
     dest[j--] = r;
   }
 }
void Conversions::y162rgb (unsigned char * src, unsigned char * dest, int width, int height, int bits) static
Definition at line 320 of file conversions.cpp.
References velocity.pid_::i, and role._GoToPoint::y.
Referenced by rgb2yuv().
{
   int NumPixels = width*height;
   register int i = ( NumPixels << 1 )-1;
   register int j = NumPixels + ( NumPixels << 1 )-1;
   register int y;
   while ( i > 0 ) {
     y = src[i--];
     y = ( y + ( src[i--]<<8 ) ) >> ( bits-8 );
     dest[j--] = y;
     dest[j--] = y;
     dest[j--] = y;
   }
 }
void Conversions::y2rgb (unsigned char * src, unsigned char * dest, int width, int height) static
Definition at line 303 of file conversions.cpp.
References velocity.pid_::i, and role._GoToPoint::y.
Referenced by rgb2yuv().
{
   int NumPixels = width*height;
   register int i = NumPixels-1;
   register int j = NumPixels + ( NumPixels << 1 )-1;
   register int y;
   while ( i > 0 ) {
     y = ( unsigned char ) src[i--];
     dest[j--] = y;
     dest[j--] = y;
     dest[j--] = y;
   }
 }
static void Conversions::yuv2rgb (int y, int u, int v, int & r, int & g, int & b) inline static
Definition at line 44 of file conversions.h.
References GVector::bound().
Referenced by Images::convert(), YUVLUT::deriveFromLUT(), GLLUTWidget::drawSlice(), and yuv2rgb().
 {
   r = bound(y         + ((v*1436) >>10), 0, 255);
   g = bound(y - ((u*352 + v*731) >> 10), 0, 255);
   b = bound(y + ((u*1814) >> 10)       , 0, 255);
 }
static rgb Conversions::yuv2rgb (yuv const & in) inline static
Definition at line 51 of file conversions.h.
References ColorRGB< num, fmt >::b, ColorRGB< num, fmt >::g, ColorRGB< num, fmt >::r, ColorYUV< num, fmt >::u, v, ColorYUV< num, fmt >::v, role._GoToPoint::y, ColorYUV< num, fmt >::y, and yuv2rgb().
 {
   int r, g, b;
   int y, u, v;
   y = (int) in.y;
   u = (int) in.u-128;
   v = (int) in.v-128;
   yuv2rgb(y, u, v, r, g, b);
   rgb col;
   col.r   = (unsigned char) r;
   col.g = (unsigned char) g;
   col.b  = (unsigned char) b;
   return (col);
 }
void Conversions::yuyv2rgb (unsigned char * src, unsigned char * dest, int width, int height) static
Definition at line 133 of file conversions.cpp.
References velocity.pid_::i, and v.
Referenced by rgb2yuv().
{
 #ifndef NO_DC1394_CONVERSIONS
     dc1394_convert_to_RGB8(src,dest, width, height, DC1394_BYTE_ORDER_YUYV,
                            DC1394_COLOR_CODING_YUV422, 8);
 #else
     int NumPixels = width*height;
     register int max_i = ( NumPixels << 1 )-1;
     //register int max_j = NumPixels + ( NumPixels << 1 ) -1;
     register int i = 0;
     register int j = 0;
     register int y0, y1, u, v;
     register int r, g, b;
     while ( i < max_i ) {
         y0 = ( unsigned char ) src[i++];
         u  = ( unsigned char ) src[i++];
         y1 = ( unsigned char ) src[i++];
         v  = ( unsigned char ) src[i++];
         yuv2rgb ( y0, u, v, r, g, b );
         dest[j++] = r;
         dest[j++] = g;
         dest[j++] = b;
         yuv2rgb ( y1, u, v, r, g, b );
         dest[j++] = r;
         dest[j++] = g;
         dest[j++] = b;
     }
 #endif
 }
The documentation for this class was generated from the following files:
ssl-vision/src/shared/util/conversions.h
ssl-vision/src/shared/util/conversions.cpp