Documentation: test_GoToPoint Namespace Reference
test_GoToPoint Namespace Reference
Functions
def reset ()
def GUI_Callback (data)
def BS_callback (data)
Variables
shared = memcache.Client(['127.0.0.1:11211'], debug = False)
BOT_ID = int(sys.argv[1])
pub = rospy.Publisher('/grsim_data', gr_Commands, queue_size=1000)
GOAL_POINT = point_2d()
x
y
int REPLANNED = 0
homePos = None
awayPos = None
BState = shared.get('state')
kub = kubs.kubs(BOT_ID, BState, pub)
anonymous
start_time = rospy.Time.now()
BeliefState
BS_callback
queue_size
point_SF
GUI_Callback
Function Documentation
def test_GoToPoint.BS_callback (data)
Definition at line 39 of file test_GoToPoint.py.
References BS_callback, velocity.run.Get_Vel(), print(), and reset().
 def BS_callback(data):
     global homePos, REPLANNED
     global awayPos, start_time, BState, kub
     BState = data
     homePos = data.homePos
     awayPos = data.awayPos
     t = rospy.Time.now()
     t = t.secs + 1.0*t.nsecs/pow(10,9)
     print(" t - start = ",t-start_time)
     [vx, vy, vw, REPLANNED] = Get_Vel(start_time, t, BOT_ID, data.ballPos, homePos, awayPos)    #vx, vy, vw, replanned
     print("-------------------REPLANNED = ",REPLANNED)
     if(REPLANNED):
         reset()
     print("vx = ",vx)
     print("vy = ",vy)
     # print("kubs_id = ",kub.kubs_id)
     try:
         kub.move(vx, vy)
         kub.turn(vw)
         kub.execute()
     except Exception as e:
         print("In except",e)
         pass
def test_GoToPoint.GUI_Callback (data)
Definition at line 33 of file test_GoToPoint.py.
References GUI_Callback.
 def GUI_Callback(data):
     global BOT_ID, kub, BState, pub
     BOT_ID = data.bot_id
     print BOT_ID, "_____________________________"
     kub = kubs.kubs(BOT_ID, BState, pub)
def test_GoToPoint.reset ()
Definition at line 28 of file test_GoToPoint.py.
Referenced by BS_callback().
 def reset():
     global start_time
     start_time = rospy.Time.now()
     start_time = 1.0*start_time.secs + 1.0*start_time.nsecs/pow(10,9)
Variable Documentation
test_GoToPoint.anonymous
Definition at line 65 of file test_GoToPoint.py.
test_GoToPoint.awayPos = None
Definition at line 24 of file test_GoToPoint.py.
test_GoToPoint.BeliefState
Definition at line 69 of file test_GoToPoint.py.
test_GoToPoint.BOT_ID = int(sys.argv[1])
Definition at line 15 of file test_GoToPoint.py.
test_GoToPoint.BS_callback
Definition at line 69 of file test_GoToPoint.py.
Referenced by BS_callback().
test_GoToPoint.BState = shared.get('state')
Definition at line 25 of file test_GoToPoint.py.
test_GoToPoint.GOAL_POINT = point_2d()
Definition at line 19 of file test_GoToPoint.py.
test_GoToPoint.GUI_Callback
Definition at line 70 of file test_GoToPoint.py.
Referenced by GUI_Callback().
test_GoToPoint.homePos = None
Definition at line 23 of file test_GoToPoint.py.
test_GoToPoint.kub = kubs.kubs(BOT_ID, BState, pub)
Definition at line 26 of file test_GoToPoint.py.
test_GoToPoint.point_SF
Definition at line 70 of file test_GoToPoint.py.
Referenced by GUI.ompl_gui.MainWindow.goToBall(), GUI.ompl_gui.MainWindow.goToBallFsm(), and GUI.self_RRT.MainWindow.sendParams().
test_GoToPoint.pub = rospy.Publisher('/grsim_data', gr_Commands, queue_size=1000)
Definition at line 17 of file test_GoToPoint.py.
test_GoToPoint.queue_size
Definition at line 69 of file test_GoToPoint.py.
int test_GoToPoint.REPLANNED = 0
Definition at line 22 of file test_GoToPoint.py.
test_GoToPoint.shared = memcache.Client(['127.0.0.1:11211'], debug = False)
Definition at line 12 of file test_GoToPoint.py.
float test_GoToPoint.start_time = rospy.Time.now()
Definition at line 66 of file test_GoToPoint.py.
test_GoToPoint.x
Definition at line 20 of file test_GoToPoint.py.
test_GoToPoint.y
Definition at line 21 of file test_GoToPoint.py.