Documentation: ConfigWidget Class Reference
ConfigWidget Class Reference
#include <configwidget.h>
Public Slots
void loadRobotsSettings ()
Public Slots inherited from VarTypes::VarTreeView
void search (const QString &text)
void nextSearchResult ()
Public Member Functions
ConfigWidget ()
virtual ~ConfigWidget ()
double Field_Line_Width ()
double Field_Length ()
double Field_Width ()
double Field_Rad ()
double Field_Defense_Rad ()
double Field_Defense_Stretch ()
double Field_Free_Kick ()
double Field_Penalty_Rad ()
double Field_Penalty_Line ()
double Field_Penalty_Point ()
double Field_Margin ()
double Field_Referee_Margin ()
double Wall_Thickness ()
double Goal_Thickness ()
double Goal_Depth ()
double Goal_Width ()
double Goal_Height ()
std::string YellowTeam ()
std::string BlueTeam ()
double BallRadius ()
double BallMass ()
double BallFriction ()
double BallSlip ()
double BallBounce ()
double BallBounceVel ()
double BallLinearDamp ()
double BallAngularDamp ()
bool SyncWithGL ()
double DesiredFPS ()
double DeltaTime ()
int sendGeometryEvery ()
double Gravity ()
std::string VisionMulticastAddr ()
int VisionMulticastPort ()
int CommandListenPort ()
int BlueStatusSendPort ()
int YellowStatusSendPort ()
int sendDelay ()
bool noise ()
double noiseDeviation_x ()
double noiseDeviation_y ()
double noiseDeviation_angle ()
bool vanishing ()
double ball_vanishing ()
double blue_team_vanishing ()
double yellow_team_vanishing ()
std::string plotter_addr ()
int plotter_port ()
bool plotter ()
void loadRobotSettings (QString team)
Public Member Functions inherited from VarTypes::VarTreeView
void setModel (VarTreeModel *tmodel)
VarTreeView (VarTreeModel *tmodel=0)
virtual ~VarTreeView ()
void fitColumns ()
void expandAndFocus (VarType *search)
Data Fields
VarListPtr geo_vars
QSettings * robot_settings
RobotSettings robotSettings
RobotSettings blueSettings
RobotSettings yellowSettings
std::tr1::shared_ptr< VarTypes::VarDouble > v_Field_Line_Width
std::tr1::shared_ptr< VarTypes::VarDouble > v_Field_Length
std::tr1::shared_ptr< VarTypes::VarDouble > v_Field_Width
std::tr1::shared_ptr< VarTypes::VarDouble > v_Field_Rad
std::tr1::shared_ptr< VarTypes::VarDouble > v_Field_Defense_Rad
std::tr1::shared_ptr< VarTypes::VarDouble > v_Field_Defense_Stretch
std::tr1::shared_ptr< VarTypes::VarDouble > v_Field_Free_Kick
std::tr1::shared_ptr< VarTypes::VarDouble > v_Field_Penalty_Rad
std::tr1::shared_ptr< VarTypes::VarDouble > v_Field_Penalty_Line
std::tr1::shared_ptr< VarTypes::VarDouble > v_Field_Penalty_Point
std::tr1::shared_ptr< VarTypes::VarDouble > v_Field_Margin
std::tr1::shared_ptr< VarTypes::VarDouble > v_Field_Referee_Margin
std::tr1::shared_ptr< VarTypes::VarDouble > v_Wall_Thickness
std::tr1::shared_ptr< VarTypes::VarDouble > v_Goal_Thickness
std::tr1::shared_ptr< VarTypes::VarDouble > v_Goal_Depth
std::tr1::shared_ptr< VarTypes::VarDouble > v_Goal_Width
std::tr1::shared_ptr< VarTypes::VarDouble > v_Goal_Height
std::tr1::shared_ptr< VarTypes::VarStringEnum > v_YellowTeam
std::tr1::shared_ptr< VarTypes::VarStringEnum > v_BlueTeam
std::tr1::shared_ptr< VarTypes::VarDouble > v_BallRadius
std::tr1::shared_ptr< VarTypes::VarDouble > v_BallMass
std::tr1::shared_ptr< VarTypes::VarDouble > v_BallFriction
std::tr1::shared_ptr< VarTypes::VarDouble > v_BallSlip
std::tr1::shared_ptr< VarTypes::VarDouble > v_BallBounce
std::tr1::shared_ptr< VarTypes::VarDouble > v_BallBounceVel
std::tr1::shared_ptr< VarTypes::VarDouble > v_BallLinearDamp
std::tr1::shared_ptr< VarTypes::VarDouble > v_BallAngularDamp
std::tr1::shared_ptr< VarTypes::VarBool > v_SyncWithGL
std::tr1::shared_ptr< VarTypes::VarDouble > v_DesiredFPS
std::tr1::shared_ptr< VarTypes::VarDouble > v_DeltaTime
std::tr1::shared_ptr< VarTypes::VarInt > v_sendGeometryEvery
std::tr1::shared_ptr< VarTypes::VarDouble > v_Gravity
std::tr1::shared_ptr< VarTypes::VarString > v_VisionMulticastAddr
std::tr1::shared_ptr< VarTypes::VarInt > v_VisionMulticastPort
std::tr1::shared_ptr< VarTypes::VarInt > v_CommandListenPort
std::tr1::shared_ptr< VarTypes::VarInt > v_BlueStatusSendPort
std::tr1::shared_ptr< VarTypes::VarInt > v_YellowStatusSendPort
std::tr1::shared_ptr< VarTypes::VarInt > v_sendDelay
std::tr1::shared_ptr< VarTypes::VarBool > v_noise
std::tr1::shared_ptr< VarTypes::VarDouble > v_noiseDeviation_x
std::tr1::shared_ptr< VarTypes::VarDouble > v_noiseDeviation_y
std::tr1::shared_ptr< VarTypes::VarDouble > v_noiseDeviation_angle
std::tr1::shared_ptr< VarTypes::VarBool > v_vanishing
std::tr1::shared_ptr< VarTypes::VarDouble > v_ball_vanishing
std::tr1::shared_ptr< VarTypes::VarDouble > v_blue_team_vanishing
std::tr1::shared_ptr< VarTypes::VarDouble > v_yellow_team_vanishing
std::tr1::shared_ptr< VarTypes::VarString > v_plotter_addr
std::tr1::shared_ptr< VarTypes::VarInt > v_plotter_port
std::tr1::shared_ptr< VarTypes::VarBool > v_plotter
Protected Attributes
vector< VarPtr > world
VarTreeModel * tmodel
Protected Attributes inherited from VarTypes::VarTreeView
QList< VarItem * > search_result
int result_idx
QLineEdit * search_edit
QTreeView * tw
VarItemDelegate * delegate
VarTreeModel * model
QVBoxLayout * l
Additional Inherited Members
Protected Slots inherited from VarTypes::VarTreeView
void newItemChecksRows (const QModelIndex &parent, int start, int end)
void checkDataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
Detailed Description
Definition at line 112 of file configwidget.h.
Constructor & Destructor Documentation
ConfigWidget::ConfigWidget ()
Definition at line 48 of file configwidget.cpp.
References ADD_ENUM, ADD_TO_ENUM, ADD_VALUE, ball_vanishing(), BallAngularDamp(), BallBounce(), BallBounceVel(), BallFriction(), BallLinearDamp(), BallMass(), BallRadius(), BallSlip(), blue_team_vanishing(), BlueStatusSendPort(), BlueTeam(), CommandListenPort(), DeltaTime(), DesiredFPS(), END_ENUM, VarTypes::VarTreeView::expandAndFocus(), Field_Defense_Rad(), Field_Defense_Stretch(), Field_Free_Kick(), Field_Length(), Field_Line_Width(), Field_Margin(), Field_Penalty_Line(), Field_Penalty_Point(), Field_Penalty_Rad(), Field_Rad(), Field_Referee_Margin(), Field_Width(), VarTypes::VarTreeView::fitColumns(), geo_vars, Goal_Depth(), Goal_Height(), Goal_Thickness(), Goal_Width(), Gravity(), velocity.pid_::i, loadRobotsSettings(), noise(), noiseDeviation_angle(), noiseDeviation_x(), noiseDeviation_y(), robot_settings, sendDelay(), sendGeometryEvery(), VarTypes::VarTreeView::setModel(), VarTypes::VarTreeModel::setRootItems(), SyncWithGL(), tmodel, v_BlueTeam, v_YellowTeam, vanishing(), VisionMulticastAddr(), VisionMulticastPort(), Wall_Thickness(), world, yellow_team_vanishing(), YellowStatusSendPort(), and YellowTeam().
 {
   tmodel=new VarTreeModel();
   this->setModel(tmodel);
   geo_vars = VarListPtr(new VarList("Geometry"));
   world.push_back(geo_vars);
   robot_settings = new QSettings;
     VarListPtr field_vars(new VarList("Field"));
     geo_vars->addChild(field_vars);
         ADD_VALUE(field_vars,Double,Field_Line_Width,0.010,"Line Thickness")
         ADD_VALUE(field_vars,Double,Field_Length,9.000,"Length")
         ADD_VALUE(field_vars,Double,Field_Width,6.000,"Width")
         ADD_VALUE(field_vars,Double,Field_Rad,0.500,"Radius")
         ADD_VALUE(field_vars,Double,Field_Defense_Rad,1.000,"Defense Radius")
         ADD_VALUE(field_vars,Double,Field_Defense_Stretch,0.500,"Defense Stretch")
         ADD_VALUE(field_vars,Double,Field_Free_Kick,0.700,"Free Kick Distanse From Defense Area")
         ADD_VALUE(field_vars,Double,Field_Penalty_Rad,0.50,"Penalty radius")
         ADD_VALUE(field_vars,Double,Field_Penalty_Line,0.350,"Penalty line length")
         ADD_VALUE(field_vars,Double,Field_Penalty_Point,0.950,"Penalty point")
         ADD_VALUE(field_vars,Double,Field_Margin,0.250,"Margin")
         ADD_VALUE(field_vars,Double,Field_Referee_Margin,0.455,"Referee margin")
         ADD_VALUE(field_vars,Double,Wall_Thickness,0.050,"Wall thickness")
         ADD_VALUE(field_vars,Double,Goal_Thickness,0.020,"Goal thickness")
         ADD_VALUE(field_vars,Double,Goal_Depth,0.200,"Goal depth")
         ADD_VALUE(field_vars,Double,Goal_Width,1.000,"Goal width")
         ADD_VALUE(field_vars,Double,Goal_Height,0.160,"Goal height")
     ADD_ENUM(StringEnum,YellowTeam,"Parsian","Yellow Team");
     END_ENUM(geo_vars,YellowTeam)
     ADD_ENUM(StringEnum,BlueTeam,"Parsian","Blue Team");
     END_ENUM(geo_vars,BlueTeam)
     VarListPtr ballg_vars(new VarList("Ball"));
     geo_vars->addChild(ballg_vars);
         ADD_VALUE(ballg_vars,Double,BallRadius,0.0215,"Radius")
   VarListPtr phys_vars(new VarList("Physics"));
   world.push_back(phys_vars);
     VarListPtr worldp_vars(new VarList("World"));
     phys_vars->addChild(worldp_vars);
         ADD_VALUE(worldp_vars,Double,DesiredFPS,65,"Desired FPS")
         ADD_VALUE(worldp_vars,Bool,SyncWithGL,false,"Synchronize ODE with OpenGL")
         ADD_VALUE(worldp_vars,Double,DeltaTime,0.016,"ODE time step")
         ADD_VALUE(worldp_vars,Double,Gravity,9.8,"Gravity")
   VarListPtr ballp_vars(new VarList("Ball"));
     phys_vars->addChild(ballp_vars);
         ADD_VALUE(ballp_vars,Double,BallMass,0.043,"Ball mass");
         ADD_VALUE(ballp_vars,Double,BallFriction,0.05,"Ball-ground friction")
         ADD_VALUE(ballp_vars,Double,BallSlip,1,"Ball-ground slip")
         ADD_VALUE(ballp_vars,Double,BallBounce,0.5,"Ball-ground bounce factor")
         ADD_VALUE(ballp_vars,Double,BallBounceVel,0.1,"Ball-ground bounce min velocity")
         ADD_VALUE(ballp_vars,Double,BallLinearDamp,0.004,"Ball linear damping")
         ADD_VALUE(ballp_vars,Double,BallAngularDamp,0.004,"Ball angular damping")
   VarListPtr comm_vars(new VarList("Communication"));
   world.push_back(comm_vars);
     ADD_VALUE(comm_vars,String,VisionMulticastAddr,"224.5.23.2","Vision multicast address")  //SSL Vision: "224.5.23.2"
     ADD_VALUE(comm_vars,Int,VisionMulticastPort,10020,"Vision multicast port")
     ADD_VALUE(comm_vars,Int,CommandListenPort,20011,"Command listen port")
     ADD_VALUE(comm_vars,Int,BlueStatusSendPort,30011,"Blue Team status send port")
     ADD_VALUE(comm_vars,Int,YellowStatusSendPort,30012,"Yellow Team status send port")
     ADD_VALUE(comm_vars,Int,sendDelay,0,"Sending delay (milliseconds)")
     ADD_VALUE(comm_vars,Int,sendGeometryEvery,120,"Send geometry every X frames")
     VarListPtr gauss_vars(new VarList("Gaussian noise"));
         comm_vars->addChild(gauss_vars);
         ADD_VALUE(gauss_vars,Bool,noise,false,"Noise")
         ADD_VALUE(gauss_vars,Double,noiseDeviation_x,3,"Deviation for x values")
         ADD_VALUE(gauss_vars,Double,noiseDeviation_y,3,"Deviation for y values")
         ADD_VALUE(gauss_vars,Double,noiseDeviation_angle,2,"Deviation for angle values")
     VarListPtr vanishing_vars(new VarList("Vanishing probability"));
         comm_vars->addChild(vanishing_vars);
         ADD_VALUE(gauss_vars,Bool,vanishing,false,"Vanishing")
         ADD_VALUE(vanishing_vars,Double,blue_team_vanishing,0,"Blue team")
         ADD_VALUE(vanishing_vars,Double,yellow_team_vanishing,0,"Yellow team")
         ADD_VALUE(vanishing_vars,Double,ball_vanishing,0,"Ball")
     world=VarXML::read(world,(QDir::homePath() + QString("/.grsim.xml")).toStdString());
     QDir dir;
     std::string blueteam = v_BlueTeam->getString();
     geo_vars->removeChild(v_BlueTeam);
     std::string yellowteam = v_YellowTeam->getString();
     geo_vars->removeChild(v_YellowTeam);
     ADD_ENUM(StringEnum,BlueTeam,blueteam.c_str(),"Blue Team");
     ADD_ENUM(StringEnum,YellowTeam,yellowteam.c_str(),"Yellow Team");
     dir.setCurrent(qApp->applicationDirPath()+"/../config/");
     dir.setNameFilters(QStringList() << "*.ini");
     dir.setSorting(QDir::Size | QDir::Reversed);
     QFileInfoList list = dir.entryInfoList();
     for (int i = 0; i < list.size(); ++i) {
         QFileInfo fileInfo = list.at(i);
         QStringList s = fileInfo.fileName().split(".");
         QString str;
         if (s.count() > 0) str = s[0];
         ADD_TO_ENUM(BlueTeam,str.toStdString())
         ADD_TO_ENUM(YellowTeam,str.toStdString())
     }
     dir.setCurrent(qApp->applicationDirPath()+"/../share/grsim/config/");
     dir.setNameFilters(QStringList() << "*.ini");
     dir.setSorting(QDir::Size | QDir::Reversed);
     list = dir.entryInfoList();
     for (int i = 0; i < list.size(); ++i) {
         QFileInfo fileInfo = list.at(i);
         QStringList s = fileInfo.fileName().split(".");
         QString str;
         if (s.count() > 0) str = s[0];
         ADD_TO_ENUM(BlueTeam,str.toStdString())
         ADD_TO_ENUM(YellowTeam,str.toStdString())
     }
     END_ENUM(geo_vars,BlueTeam)
     END_ENUM(geo_vars,YellowTeam)
   v_BlueTeam->setString(blueteam);
   v_YellowTeam->setString(yellowteam);
   tmodel->setRootItems(world);
   this->expandAndFocus(geo_vars);
   this->expandAndFocus(phys_vars);
   this->expandAndFocus(comm_vars);
   this->fitColumns();
   resize(320,400);
   connect(v_BlueTeam.get(), SIGNAL(wasEdited(VarPtr)), this, SLOT(loadRobotsSettings()));
   connect(v_YellowTeam.get(), SIGNAL(wasEdited(VarPtr)), this, SLOT(loadRobotsSettings()));
   loadRobotsSettings();
 }
ConfigWidget::~ConfigWidget () virtual
Definition at line 179 of file configwidget.cpp.
References world.
{
    VarXML::write(world,(QDir::homePath() + QString("/.grsim.xml")).toStdString());
 }
Member Function Documentation
double ConfigWidget::ball_vanishing () inline
Definition at line 173 of file configwidget.h.
Referenced by ConfigWidget(), and SSLWorld::generatePacket().
double ConfigWidget::BallAngularDamp () inline
Definition at line 155 of file configwidget.h.
Referenced by MainWindow::changeBallDamping(), and ConfigWidget().
double ConfigWidget::BallBounce () inline
Definition at line 152 of file configwidget.h.
Referenced by MainWindow::changeBallGroundSurface(), ConfigWidget(), and SSLWorld::SSLWorld().
double ConfigWidget::BallBounceVel () inline
Definition at line 153 of file configwidget.h.
Referenced by MainWindow::changeBallGroundSurface(), ConfigWidget(), and SSLWorld::SSLWorld().
double ConfigWidget::BallFriction () inline
Definition at line 150 of file configwidget.h.
Referenced by ballCallBack(), MainWindow::changeBallGroundSurface(), ConfigWidget(), and SSLWorld::step().
double ConfigWidget::BallLinearDamp () inline
Definition at line 154 of file configwidget.h.
Referenced by MainWindow::changeBallDamping(), and ConfigWidget().
double ConfigWidget::BallMass () inline
Definition at line 149 of file configwidget.h.
Referenced by MainWindow::changeBallMass(), ConfigWidget(), SSLWorld::SSLWorld(), and SSLWorld::step().
double ConfigWidget::BallRadius () inline
Definition at line 148 of file configwidget.h.
Referenced by ConfigWidget(), Robot::Kicker::isTouchingBall(), GLWidget::keyPressEvent(), GLWidget::mousePressEvent(), GLWidget::moveBall(), GLWidget::moveBallHere(), SSLWorld::recvActions(), SSLWorld::SSLWorld(), and SSLWorld::step().
double ConfigWidget::BallSlip () inline
Definition at line 151 of file configwidget.h.
Referenced by MainWindow::changeBallGroundSurface(), and ConfigWidget().
double ConfigWidget::blue_team_vanishing () inline
Definition at line 174 of file configwidget.h.
Referenced by ConfigWidget(), and SSLWorld::generatePacket().
int ConfigWidget::BlueStatusSendPort () inline
Definition at line 165 of file configwidget.h.
Referenced by ConfigWidget(), MainWindow::reconnectBlueStatusSocket(), and SSLWorld::recvActions().
std::string ConfigWidget::BlueTeam () inline
Definition at line 147 of file configwidget.h.
Referenced by ConfigWidget(), and loadRobotsSettings().
int ConfigWidget::CommandListenPort () inline
Definition at line 164 of file configwidget.h.
Referenced by ConfigWidget(), and MainWindow::reconnectCommandSocket().
double ConfigWidget::DeltaTime () inline
Definition at line 159 of file configwidget.h.
Referenced by ConfigWidget(), GLWidget::step(), and MainWindow::update().
double ConfigWidget::DesiredFPS () inline
Definition at line 158 of file configwidget.h.
Referenced by ConfigWidget(), MainWindow::getInterval(), and GLWidget::step().
double ConfigWidget::Field_Defense_Rad () inline
Definition at line 133 of file configwidget.h.
Referenced by SSLWorld::addFieldLinesArcs(), ConfigWidget(), and SSLWorld::SSLWorld().
double ConfigWidget::Field_Defense_Stretch () inline
Definition at line 134 of file configwidget.h.
Referenced by SSLWorld::addFieldLinesArcs(), ConfigWidget(), and SSLWorld::SSLWorld().
double ConfigWidget::Field_Free_Kick () inline
Definition at line 135 of file configwidget.h.
Referenced by ConfigWidget().
double ConfigWidget::Field_Length () inline
Definition at line 130 of file configwidget.h.
Referenced by SSLWorld::addFieldLinesArcs(), MainWindow::ballMenuTriggered(), GLWidget::changeCameraMode(), ConfigWidget(), SSLWorld::generatePacket(), and SSLWorld::SSLWorld().
double ConfigWidget::Field_Line_Width () inline
Definition at line 129 of file configwidget.h.
Referenced by SSLWorld::addFieldLinesArcs(), ConfigWidget(), and SSLWorld::SSLWorld().
double ConfigWidget::Field_Margin () inline
Definition at line 139 of file configwidget.h.
Referenced by GLWidget::changeCameraMode(), ConfigWidget(), SSLWorld::generatePacket(), and SSLWorld::SSLWorld().
double ConfigWidget::Field_Penalty_Line () inline
Definition at line 137 of file configwidget.h.
Referenced by ConfigWidget(), and SSLWorld::SSLWorld().
double ConfigWidget::Field_Penalty_Point () inline
Definition at line 138 of file configwidget.h.
Referenced by MainWindow::ballMenuTriggered(), ConfigWidget(), and SSLWorld::SSLWorld().
double ConfigWidget::Field_Penalty_Rad () inline
Definition at line 136 of file configwidget.h.
Referenced by ConfigWidget(), and SSLWorld::SSLWorld().
double ConfigWidget::Field_Rad () inline
Definition at line 132 of file configwidget.h.
Referenced by SSLWorld::addFieldLinesArcs(), ConfigWidget(), and SSLWorld::SSLWorld().
double ConfigWidget::Field_Referee_Margin () inline
Definition at line 140 of file configwidget.h.
Referenced by SSLWorld::addFieldLinesArcs(), ConfigWidget(), and SSLWorld::SSLWorld().
double ConfigWidget::Field_Width () inline
Definition at line 131 of file configwidget.h.
Referenced by SSLWorld::addFieldLinesArcs(), MainWindow::ballMenuTriggered(), GLWidget::changeCameraMode(), ConfigWidget(), SSLWorld::generatePacket(), and SSLWorld::SSLWorld().
double ConfigWidget::Goal_Depth () inline
Definition at line 143 of file configwidget.h.
Referenced by SSLWorld::addFieldLinesArcs(), ConfigWidget(), SSLWorld::generatePacket(), and SSLWorld::SSLWorld().
double ConfigWidget::Goal_Height () inline
Definition at line 145 of file configwidget.h.
Referenced by ConfigWidget(), and SSLWorld::SSLWorld().
double ConfigWidget::Goal_Thickness () inline
Definition at line 142 of file configwidget.h.
Referenced by ConfigWidget(), and SSLWorld::SSLWorld().
double ConfigWidget::Goal_Width () inline
Definition at line 144 of file configwidget.h.
Referenced by SSLWorld::addFieldLinesArcs(), ConfigWidget(), SSLWorld::generatePacket(), and SSLWorld::SSLWorld().
double ConfigWidget::Gravity () inline
Definition at line 161 of file configwidget.h.
Referenced by MainWindow::changeGravity(), ConfigWidget(), and SSLWorld::step().
void ConfigWidget::loadRobotSettings (QString team)
Definition at line 203 of file configwidget.cpp.
References RobotSettings::BodyMass, RobotSettings::BottomHeight, RobotSettings::Kicker_Friction, RobotSettings::KickerDampFactor, RobotSettings::KickerHeight, RobotSettings::KickerMass, RobotSettings::KickerThickness, RobotSettings::KickerWidth, RobotSettings::KickerZ, robot_settings, RobotSettings::RobotCenterFromKicker, RobotSettings::RobotHeight, RobotSettings::RobotRadius, robotSettings, RobotSettings::RollerPerpendicularTorqueFactor, RobotSettings::RollerTorqueFactor, RobotSettings::Wheel1Angle, RobotSettings::Wheel2Angle, RobotSettings::Wheel3Angle, RobotSettings::Wheel4Angle, RobotSettings::Wheel_Motor_FMax, RobotSettings::WheelMass, RobotSettings::WheelPerpendicularFriction, RobotSettings::WheelRadius, RobotSettings::WheelTangentFriction, and RobotSettings::WheelThickness.
Referenced by loadRobotsSettings().
 {
     QString ss = qApp->applicationDirPath()+QString("/../config/")+QString("%1.ini").arg(team);
     robot_settings = new QSettings(ss, QSettings::IniFormat);
     robotSettings.RobotCenterFromKicker = robot_settings->value("Geometery/CenterFromKicker", 0.073).toDouble();
     robotSettings.RobotRadius = robot_settings->value("Geometery/Radius", 0.09).toDouble();
     robotSettings.RobotHeight = robot_settings->value("Geometery/Height", 0.13).toDouble();
     robotSettings.BottomHeight = robot_settings->value("Geometery/RobotBottomZValue", 0.02).toDouble();
     robotSettings.KickerZ = robot_settings->value("Geometery/KickerZValue", 0.005).toDouble();
     robotSettings.KickerThickness = robot_settings->value("Geometery/KickerThickness", 0.005).toDouble();
     robotSettings.KickerWidth = robot_settings->value("Geometery/KickerWidth", 0.08).toDouble();
     robotSettings.KickerHeight = robot_settings->value("Geometery/KickerHeight", 0.04).toDouble();
     robotSettings.WheelRadius = robot_settings->value("Geometery/WheelRadius", 0.0325).toDouble();
     robotSettings.WheelThickness = robot_settings->value("Geometery/WheelThickness", 0.005).toDouble();
     robotSettings.Wheel1Angle = robot_settings->value("Geometery/Wheel1Angle", 60).toDouble();
     robotSettings.Wheel2Angle = robot_settings->value("Geometery/Wheel2Angle", 135).toDouble();
     robotSettings.Wheel3Angle = robot_settings->value("Geometery/Wheel3Angle", 225).toDouble();
     robotSettings.Wheel4Angle = robot_settings->value("Geometery/Wheel4Angle", 300).toDouble();
     robotSettings.BodyMass  = robot_settings->value("Physics/BodyMass", 2).toDouble();
     robotSettings.WheelMass = robot_settings->value("Physics/WheelMass", 0.2).toDouble();
     robotSettings.KickerMass= robot_settings->value("Physics/KickerMass",0.02).toDouble();
     robotSettings.KickerDampFactor = robot_settings->value("Physics/KickerDampFactor", 0.2f).toDouble();
     robotSettings.RollerTorqueFactor = robot_settings->value("Physics/RollerTorqueFactor", 0.06f).toDouble();
     robotSettings.RollerPerpendicularTorqueFactor = robot_settings->value("Physics/RollerPerpendicularTorqueFactor", 0.005f).toDouble();
     robotSettings.Kicker_Friction = robot_settings->value("Physics/KickerFriction", 0.8f).toDouble();
     robotSettings.WheelTangentFriction = robot_settings->value("Physics/WheelTangentFriction", 0.8f).toDouble();
     robotSettings.WheelPerpendicularFriction = robot_settings->value("Physics/WheelPerpendicularFriction", 0.05f).toDouble();
     robotSettings.Wheel_Motor_FMax = robot_settings->value("Physics/WheelMotorMaximumApplyingTorque", 0.2f).toDouble();
 }
void ConfigWidget::loadRobotsSettings () slot
Definition at line 195 of file configwidget.cpp.
References blueSettings, BlueTeam(), loadRobotSettings(), robotSettings, yellowSettings, and YellowTeam().
Referenced by ConfigWidget().
 {
     loadRobotSettings(YellowTeam().c_str());
     yellowSettings = robotSettings;
     loadRobotSettings(BlueTeam().c_str());
     blueSettings = robotSettings;
 }
bool ConfigWidget::noise () inline
Definition at line 168 of file configwidget.h.
Referenced by ConfigWidget(), SSLWorld::generatePacket(), and MainWindow::update().
double ConfigWidget::noiseDeviation_angle () inline
Definition at line 171 of file configwidget.h.
Referenced by ConfigWidget(), and SSLWorld::generatePacket().
double ConfigWidget::noiseDeviation_x () inline
Definition at line 169 of file configwidget.h.
Referenced by ConfigWidget(), and SSLWorld::generatePacket().
double ConfigWidget::noiseDeviation_y () inline
Definition at line 170 of file configwidget.h.
Referenced by ConfigWidget(), and SSLWorld::generatePacket().
bool ConfigWidget::plotter () inline
Definition at line 178 of file configwidget.h.
 :
std::string ConfigWidget::plotter_addr () inline
Definition at line 176 of file configwidget.h.
 :
int ConfigWidget::plotter_port () inline
Definition at line 177 of file configwidget.h.
 :
int ConfigWidget::sendDelay () inline
Definition at line 167 of file configwidget.h.
Referenced by ConfigWidget(), and SSLWorld::sendVisionBuffer().
int ConfigWidget::sendGeometryEvery () inline
Definition at line 160 of file configwidget.h.
Referenced by ConfigWidget(), and SSLWorld::generatePacket().
bool ConfigWidget::SyncWithGL () inline
Definition at line 157 of file configwidget.h.
Referenced by ConfigWidget(), and GLWidget::step().
bool ConfigWidget::vanishing () inline
Definition at line 172 of file configwidget.h.
Referenced by ConfigWidget(), SSLWorld::generatePacket(), and MainWindow::update().
std::string ConfigWidget::VisionMulticastAddr () inline
Definition at line 162 of file configwidget.h.
Referenced by ConfigWidget(), and MainWindow::reconnectVisionSocket().
int ConfigWidget::VisionMulticastPort () inline
Definition at line 163 of file configwidget.h.
Referenced by ConfigWidget(), and MainWindow::reconnectVisionSocket().
double ConfigWidget::Wall_Thickness () inline
Definition at line 141 of file configwidget.h.
Referenced by ConfigWidget(), and SSLWorld::SSLWorld().
double ConfigWidget::yellow_team_vanishing () inline
Definition at line 175 of file configwidget.h.
Referenced by ConfigWidget(), and SSLWorld::generatePacket().
int ConfigWidget::YellowStatusSendPort () inline
Definition at line 166 of file configwidget.h.
Referenced by ConfigWidget(), MainWindow::reconnectYellowStatusSocket(), and SSLWorld::recvActions().
std::string ConfigWidget::YellowTeam () inline
Definition at line 146 of file configwidget.h.
Referenced by ConfigWidget(), and loadRobotsSettings().
Field Documentation
RobotSettings ConfigWidget::blueSettings
Definition at line 126 of file configwidget.h.
Referenced by loadRobotsSettings(), and SSLWorld::SSLWorld().
VarListPtr ConfigWidget::geo_vars
Definition at line 120 of file configwidget.h.
Referenced by ConfigWidget().
QSettings* ConfigWidget::robot_settings
Definition at line 124 of file configwidget.h.
Referenced by ConfigWidget(), and loadRobotSettings().
RobotSettings ConfigWidget::robotSettings
Definition at line 125 of file configwidget.h.
Referenced by Robot::drawLabel(), Robot::Kicker::isTouchingBall(), Robot::Kicker::kick(), Robot::Kicker::Kicker(), loadRobotSettings(), loadRobotsSettings(), GLWidget::moveCurrentRobot(), GLWidget::moveRobot(), Robot::Robot(), Robot::setSpeed(), SSLWorld::SSLWorld(), Robot::Wheel::step(), Robot::Kicker::step(), GLWidget::unselectRobot(), Robot::Wheel::Wheel(), and wheelCallBack().
VarTreeModel* ConfigWidget::tmodel protected
Definition at line 118 of file configwidget.h.
Referenced by ConfigWidget().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_ball_vanishing
Definition at line 173 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_BallAngularDamp
Definition at line 155 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_BallBounce
Definition at line 152 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_BallBounceVel
Definition at line 153 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_BallFriction
Definition at line 150 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_BallLinearDamp
Definition at line 154 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_BallMass
Definition at line 149 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_BallRadius
Definition at line 148 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_BallSlip
Definition at line 151 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_blue_team_vanishing
Definition at line 174 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarInt > ConfigWidget::v_BlueStatusSendPort
Definition at line 165 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarStringEnum> ConfigWidget::v_BlueTeam
Definition at line 147 of file configwidget.h.
Referenced by ConfigWidget(), and MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarInt > ConfigWidget::v_CommandListenPort
Definition at line 164 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_DeltaTime
Definition at line 159 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_DesiredFPS
Definition at line 158 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Field_Defense_Rad
Definition at line 133 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Field_Defense_Stretch
Definition at line 134 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Field_Free_Kick
Definition at line 135 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Field_Length
Definition at line 130 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Field_Line_Width
Definition at line 129 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Field_Margin
Definition at line 139 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Field_Penalty_Line
Definition at line 137 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Field_Penalty_Point
Definition at line 138 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Field_Penalty_Rad
Definition at line 136 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Field_Rad
Definition at line 132 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Field_Referee_Margin
Definition at line 140 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Field_Width
Definition at line 131 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Goal_Depth
Definition at line 143 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Goal_Height
Definition at line 145 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Goal_Thickness
Definition at line 142 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Goal_Width
Definition at line 144 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Gravity
Definition at line 161 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarBool > ConfigWidget::v_noise
Definition at line 168 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_noiseDeviation_angle
Definition at line 171 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_noiseDeviation_x
Definition at line 169 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_noiseDeviation_y
Definition at line 170 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarBool > ConfigWidget::v_plotter
Definition at line 178 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarString > ConfigWidget::v_plotter_addr
Definition at line 176 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarInt > ConfigWidget::v_plotter_port
Definition at line 177 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarInt > ConfigWidget::v_sendDelay
Definition at line 167 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarInt > ConfigWidget::v_sendGeometryEvery
Definition at line 160 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarBool > ConfigWidget::v_SyncWithGL
Definition at line 157 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarBool > ConfigWidget::v_vanishing
Definition at line 172 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarString > ConfigWidget::v_VisionMulticastAddr
Definition at line 162 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarInt > ConfigWidget::v_VisionMulticastPort
Definition at line 163 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_Wall_Thickness
Definition at line 141 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarDouble > ConfigWidget::v_yellow_team_vanishing
Definition at line 175 of file configwidget.h.
std::tr1::shared_ptr<VarTypes::VarInt > ConfigWidget::v_YellowStatusSendPort
Definition at line 166 of file configwidget.h.
Referenced by MainWindow::customFPS().
std::tr1::shared_ptr<VarTypes::VarStringEnum> ConfigWidget::v_YellowTeam
Definition at line 146 of file configwidget.h.
Referenced by ConfigWidget(), and MainWindow::customFPS().
vector<VarPtr> ConfigWidget::world protected
Definition at line 117 of file configwidget.h.
Referenced by ConfigWidget(), and ~ConfigWidget().
RobotSettings ConfigWidget::yellowSettings
Definition at line 127 of file configwidget.h.
Referenced by loadRobotsSettings(), and SSLWorld::SSLWorld().
The documentation for this class was generated from the following files:
grSim/include/configwidget.h
grSim/src/configwidget.cpp