Documentation: Planning Class Reference
Planning Class Reference
Class for planning.
#include <MotionPlanner.h>
Public Member Functions
Planning (std::vector< krssg_ssl_msgs::point_2d > &v, int n, krssg_ssl_msgs::point_SF gui_msgs, int BOT_ID)
Constructor for planning class.
void init (std::vector< krssg_ssl_msgs::point_2d > &v, int n, krssg_ssl_msgs::point_SF gui_msgs, int BOT_ID)
bool isStateValid (const ob::State *state) const
Determines if ompl state is valid.
void planSimple ()
Set Dimensions for ompl space.
bool plan (int start_row, int start_col, int goal_row, int goal_col)
Initialise ompl state with path.
vector< krssg_ssl_msgs::point_2d > recordSolution ()
Get vector of points on path.
Private Attributes
double * xc
double * yc
double * r
double xstart
double ystart
double xgoal
double ygoal
int numObstacles
double xLeft
Left coordinate of space.
double xRight
Right coordinate of space.
double yTop
Top coordinate of space.
double yBottom
Bottom coordinate of space.
int selector
Planner Selector.
int maxWidth_
Width of space.
int maxHeight_
Height of space.
og::SimpleSetupPtr ss_
Detailed Description
Class for planning.
Definition at line 64 of file MotionPlanner.h.
Constructor & Destructor Documentation
Planning::Planning (std::vector< krssg_ssl_msgs::point_2d > & v, int n, krssg_ssl_msgs::point_SF gui_msgs, int BOT_ID)
Constructor for planning class.
Parameters
v Position of all bots
[in] n Total Number of Bots
[in] gui_msgs msg from gui node
Definition at line 31 of file MotionPlanner.cpp.
References role._GoToPoint::init().
{
   init(v,n,gui_msgs, BOT_ID);
 }
Member Function Documentation
void Planning::init (std::vector< krssg_ssl_msgs::point_2d > & v, int n, krssg_ssl_msgs::point_SF gui_msgs, int BOT_ID)
Definition at line 35 of file MotionPlanner.cpp.
References HALF_FIELD_MAXX_OMPL, HALF_FIELD_MAXY_OMPL, and velocity.pid_::i.
 {
   // stepSize=gui_msgs.step_size;
   // Boundaries of the space
   xLeft=-HALF_FIELD_MAXX_OMPL;
   xRight=HALF_FIELD_MAXX_OMPL;
   yTop=HALF_FIELD_MAXY_OMPL;
   yBottom=-HALF_FIELD_MAXY_OMPL;
   selector=gui_msgs.max_iteration;
   n--;
   numObstacles = n;
   xc = new double[numObstacles];
   yc = new double[numObstacles];
   for(int i=0, j=0;i<n;i++, j++){
     if(j==BOT_ID)
     {
       i--;
       continue;
     }
     xc[i] = v[j].x;
     yc[i] = v[j].y;
   }
 }
bool Planning::isStateValid (const ob::State * state) const
Determines if ompl state is valid.
Parameters
[in] state ompl state
Check if obstacle is not on path
Returns
True if state valid 1, False otherwise.
Definition at line 155 of file MotionPlanner.cpp.
References velocity.pid_::i, GVector::min(), obs_radius, and self_radius.
{
   const int w = std::min((int)state->as<ob::RealVectorStateSpace::StateType>()->values[0], maxWidth_);
   const int h = std::min((int)state->as<ob::RealVectorStateSpace::StateType>()->values[1], maxHeight_);
   if(sqrt(pow((xstart-w),2)+pow((ystart-h),2))<=self_radius)
     return true;
   if(sqrt(pow((xgoal-w),2)+pow((ygoal-h),2))<=self_radius)
     return true;
   for (int i = 0; i < numObstacles; ++i){
     if (sqrt(pow((xc[i]-w),2)+pow((yc[i]-h),2))<=obs_radius){
       return false;
     }
   }
   return true;
 }
bool Planning::plan (int start_row, int start_col, int goal_row, int goal_col)
Initialise ompl state with path.
Parameters
[in] start_row start point coordinate
[in] start_col start point coordinate
[in] goal_row end point coordinate
[in] goal_col end point coordinate
Find path from start point to end point. Simplify Path
Returns
return True if path is found
Definition at line 67 of file MotionPlanner.cpp.
References velocity.pid_::i.
{
   if (!ss_)
     return false;
   ob::ScopedState<> start(ss_->getStateSpace());
   start[0] = start_row;
   xstart = start_row;
   ystart = start_col;
   xgoal = goal_row;
   ygoal = goal_col;
   start[1] = start_col;
   ob::ScopedState<> goal(ss_->getStateSpace());
   goal[0] = goal_row;
   goal[1] = goal_col;
   selector = 3;
   ss_->setStartAndGoalStates(start, goal);
   for (int i = 0 ; i < 1 ; ++i){
         if(selector == 1){
         ob::PlannerPtr planner(new og::PRM(ss_->getSpaceInformation()));
         ss_->setPlanner(planner);
       }else if(selector == 2){
         ob::PlannerPtr planner(new og::RRT(ss_->getSpaceInformation()));
         ss_->setPlanner(planner);
       }else if(selector == 3){
         ob::PlannerPtr planner(new og::RRTConnect(ss_->getSpaceInformation()));
         ss_->setPlanner(planner);
       }else if(selector == 4){
         ob::PlannerPtr planner(new og::RRTstar(ss_->getSpaceInformation()));
         ss_->setPlanner(planner);
       }else if(selector == 5){
         ob::PlannerPtr planner(new og::LBTRRT(ss_->getSpaceInformation()));
         ss_->setPlanner(planner);
       }else if(selector == 6){
         ob::PlannerPtr planner(new og::LazyRRT(ss_->getSpaceInformation()));
         ss_->setPlanner(planner);
       }else if(selector == 7){
         ob::PlannerPtr planner(new og::TRRT(ss_->getSpaceInformation()));
         ss_->setPlanner(planner);
       }else if(selector == 8){
         ob::PlannerPtr planner(new og::pRRT(ss_->getSpaceInformation()));
         ss_->setPlanner(planner);
       }else if(selector == 9){
         ob::PlannerPtr planner(new og::EST(ss_->getSpaceInformation()));
         ss_->setPlanner(planner);
       }
       else{
         ob::PlannerPtr planner(new og::RRTConnect(ss_->getSpaceInformation()));
         ss_->setPlanner(planner);
       }
     ss_->solve();
   }
   const std::size_t ns = ss_->getProblemDefinition()->getSolutionCount();
   if (ss_->haveSolutionPath()){
     cout<<"__HERE__\n"<<endl;
     ss_->simplifySolution();
     og::PathGeometric &p = ss_->getSolutionPath();
     ss_->getPathSimplifier()->simplifyMax(p);
     ss_->getPathSimplifier()->smoothBSpline(p);
     cout<<"__FUNC_END__"<<endl;
     return true;
   }
   return false ;
 }
void Planning::planSimple ()
Set Dimensions for ompl space.
Boundaries of space
xLeft, xRight for x Dimension
yLeft, yRight for y Dimension
Definition at line 176 of file MotionPlanner.cpp.
References run_goalie::state.
Referenced by path().
{
   //if throwing an error related to shared pointer conflict b/w boost and std, uncomment the follwing line and comment the 2nd one.
   // boost::shared_ptr<ob::RealVectorStateSpace> space(boost::make_shared<ob::RealVectorStateSpace>());
   auto space(std::make_shared<ob::RealVectorStateSpace>());
   space->addDimension(xLeft, xRight);
   space->addDimension(yBottom, yTop);
   maxWidth_ = xRight - xLeft;
   maxHeight_ = yTop - yBottom;
   // ss_ = make_shared_ptr(ss_);
   std::shared_ptr<og::SimpleSetup> std_ss_;
   //do the same here too.
   ss_ = std::make_shared<og::SimpleSetup>(space);
   ss_->setStateValidityChecker([this](const ob::State *state) {return isStateValid(state);});
   space->setup();
   ss_->getSpaceInformation()->setStateValidityCheckingResolution(1.0 / space->getMaximumExtent());
 }
vector< krssg_ssl_msgs::point_2d > Planning::recordSolution ()
Get vector of points on path.
Path after Interpolation
Returns
Vector of points on path
Definition at line 133 of file MotionPlanner.cpp.
References velocity.pid_::i, GVector::min(), and vect1.
{
   vect1.clear();
   cout<<"recordSolution start\n";
   if (!ss_ || !ss_->haveSolutionPath())
     {
       vect1.clear();
       return vect1;
     }
   og::PathGeometric &p = ss_->getSolutionPath();
   p.interpolate();
   for (std::size_t i = 0 ; i < p.getStateCount() ; ++i)
   {
     const int w = std::min(maxWidth_, (int)p.getState(i)->as<ob::RealVectorStateSpace::StateType>()->values[0]);
     const int h = std::min(maxHeight_, (int)p.getState(i)->as<ob::RealVectorStateSpace::StateType>()->values[1]);
    krssg_ssl_msgs::point_2d s;
     s.x=w;
     s.y=h;
     vect1.push_back(s);
   }
   return vect1;
 }
Field Documentation
int Planning::maxHeight_ private
Height of space.
See also
planSimple()
Definition at line 164 of file MotionPlanner.h.
int Planning::maxWidth_ private
Width of space.
Definition at line 159 of file MotionPlanner.h.
int Planning::numObstacles private
Number of obstacles in space
Definition at line 130 of file MotionPlanner.h.
double* Planning::r private
Definition at line 124 of file MotionPlanner.h.
int Planning::selector private
Planner Selector.
See also
planSimple()
Definition at line 154 of file MotionPlanner.h.
og::SimpleSetupPtr Planning::ss_ private
Ompl space ptr
See also
planSimple()
Definition at line 170 of file MotionPlanner.h.
double* Planning::xc private
Definition at line 122 of file MotionPlanner.h.
double Planning::xgoal private
Definition at line 125 of file MotionPlanner.h.
double Planning::xLeft private
Left coordinate of space.
Definition at line 134 of file MotionPlanner.h.
double Planning::xRight private
Right coordinate of space.
See also
planSimple()
Definition at line 139 of file MotionPlanner.h.
double Planning::xstart private
Definition at line 125 of file MotionPlanner.h.
double Planning::yBottom private
Bottom coordinate of space.
See also
planSimple()
Definition at line 149 of file MotionPlanner.h.
double* Planning::yc private
Definition at line 123 of file MotionPlanner.h.
double Planning::ygoal private
Definition at line 125 of file MotionPlanner.h.
double Planning::ystart private
Definition at line 125 of file MotionPlanner.h.
double Planning::yTop private
Top coordinate of space.
See also
planSimple()
Definition at line 144 of file MotionPlanner.h.
The documentation for this class was generated from the following files:
ompl_planner/include/MotionPlanner.h
ompl_planner/src/MotionPlanner.cpp