Documentation: FrameCounter Class Reference
FrameCounter Class Reference
A class for frame counting and frame-rate measurements.
#include <framecounter.h>
Public Member Functions
FrameCounter (int _interval=1000)
~FrameCounter ()
void reset (int _interval=1000)
void count ()
void count (long long val)
long long getTotal ()
double getFPS (bool &changed)
Protected Attributes
int interval
double fps
long long total
long long framecounter
QTime timer
QMutex mutex
Detailed Description
A class for frame counting and frame-rate measurements.
Definition at line 32 of file framecounter.h.
Constructor & Destructor Documentation
FrameCounter::FrameCounter (int _interval = 1000) inline
Definition at line 42 of file framecounter.h.
References reset().
{
         reset(_interval);
     }
FrameCounter::~FrameCounter () inline
Definition at line 45 of file framecounter.h.
 {}
Member Function Documentation
void FrameCounter::count () inline
Definition at line 55 of file framecounter.h.
Referenced by GLWidget::displayLoopEvent(), GLWidget::mainDraw(), GLLUTWidget::paintGL(), and CaptureThread::run().
                  {
         mutex.lock();
         framecounter++;
         total++;
         mutex.unlock();
     }
void FrameCounter::count (long long val) inline
Definition at line 61 of file framecounter.h.
{
         mutex.lock();
         framecounter+=val;
         total+=val;
         mutex.unlock();
     }
double FrameCounter::getFPS (bool & changed) inline
Definition at line 74 of file framecounter.h.
References fps.
Referenced by GLWidget::displayLoopEvent(), and CaptureThread::run().
{
         mutex.lock();
         if (timer.elapsed() > 1000) {
         double secs=((double)timer.restart())/1000.0;
       fps=((double)framecounter)/secs;
         framecounter=0;
         changed=true;
     } else {
         changed=false;
         }
         double res=fps;
         mutex.unlock();
     return res;
     }
long long FrameCounter::getTotal () inline
Definition at line 67 of file framecounter.h.
References total.
Referenced by CaptureThread::run().
{
         long long res;
         mutex.lock();
         res=total;
         mutex.unlock();
         return res;
     }
void FrameCounter::reset (int _interval = 1000) inline
Definition at line 46 of file framecounter.h.
Referenced by FrameCounter().
{
         mutex.lock();
         interval=_interval;
         framecounter=0;
         fps=0.0;
         total=0;
         timer.restart();
         mutex.unlock();
     }
Field Documentation
double FrameCounter::fps protected
Definition at line 36 of file framecounter.h.
Referenced by getFPS().
long long FrameCounter::framecounter protected
Definition at line 38 of file framecounter.h.
int FrameCounter::interval protected
Definition at line 34 of file framecounter.h.
QMutex FrameCounter::mutex protected
Definition at line 40 of file framecounter.h.
QTime FrameCounter::timer protected
Definition at line 39 of file framecounter.h.
long long FrameCounter::total protected
Definition at line 37 of file framecounter.h.
Referenced by getTotal().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/framecounter.h