Documentation: FunctionTimer Class Reference
FunctionTimer Class Reference
#include <timer.h>
Public Member Functions
FunctionTimer (const char *_fname)
~FunctionTimer ()
FunctionTimer (const char *_fname)
~FunctionTimer ()
Private Attributes
const char * fname
Timer timer
Detailed Description
Definition at line 230 of file timer.h.
Constructor & Destructor Documentation
FunctionTimer::FunctionTimer (const char * _fname) inline
Definition at line 234 of file timer.h.
References Timer::start().
     {fname=_fname; timer.start();}
FunctionTimer::~FunctionTimer () inline
Definition at line 236 of file timer.h.
References Timer::stop(), and Timer::timeMSec().
     {timer.stop(); printf("%s: %0.3f\n",fname,timer.timeMSec());}
FunctionTimer::FunctionTimer (const char * _fname) inline
Definition at line 234 of file timer.h.
References Timer::start().
     {fname=_fname; timer.start();}
FunctionTimer::~FunctionTimer () inline
Definition at line 236 of file timer.h.
References Timer::stop(), and Timer::timeMSec().
     {timer.stop(); printf("%s: %0.3f\n",fname,timer.timeMSec());}
Field Documentation
const char * FunctionTimer::fname private
Definition at line 231 of file timer.h.
Timer FunctionTimer::timer private
Definition at line 232 of file timer.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/timer.h