Documentation: VarTypes::VarIntVal Class Reference
VarTypes::VarIntVal Class Reference
A Vartype for storing integers.
#include <VarIntVal.h>
Public Member Functions
virtual bool setInt (int val)
set the value of this node to val.
VarIntVal (int default_val=0)
virtual ~VarIntVal ()
virtual void printdebug () const
virtual VarVal * clone () const
virtual VarTypeId getType () const
virtual string getString () const
virtual int getInt () const
virtual double getDouble () const
virtual int get () const
virtual bool getBool () const
virtual bool setString (const string &val)
virtual bool setDouble (double val)
virtual bool setBool (bool val)
virtual bool hasValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
Protected Attributes
int _val
Additional Inherited Members
Protected Member Functions inherited from VarTypes::VarVal
virtual void lock () const
virtual void unlock () const
virtual void changed ()
Detailed Description
A Vartype for storing integers.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 35 of file VarIntVal.h.
Constructor & Destructor Documentation
VarTypes::VarIntVal::VarIntVal (int default_val = 0) inline
Definition at line 57 of file VarIntVal.h.
References VarTypes::VarVal::changed(), and setInt().
Referenced by clone().
                                  : VarVal()
     {
       setInt(default_val);
       changed();
     }
virtual VarTypes::VarIntVal::~VarIntVal () inline virtual
Definition at line 63 of file VarIntVal.h.
 {}
Member Function Documentation
virtual VarVal* VarTypes::VarIntVal::clone () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 72 of file VarIntVal.h.
References getInt(), setInt(), and VarIntVal().
{
       VarIntVal * tmp = new VarIntVal();
       tmp->setInt(getInt());
       return tmp;
     }
virtual int VarTypes::VarIntVal::get () const inline virtual
Reimplemented in VarTypes::VarInt.
Definition at line 91 of file VarIntVal.h.
References getInt().
 { return getInt(); };
virtual bool VarTypes::VarIntVal::getBool () const inline virtual
Reimplemented in VarTypes::VarInt.
Definition at line 93 of file VarIntVal.h.
References getInt().
 { return (getInt() == 1 ? true : false); };
virtual double VarTypes::VarIntVal::getDouble () const inline virtual
Reimplemented in VarTypes::VarInt.
Definition at line 90 of file VarIntVal.h.
References getInt().
Referenced by getValue().
 { return (double)getInt(); };
virtual int VarTypes::VarIntVal::getInt () const inline virtual
Reimplemented in VarTypes::VarInt.
Definition at line 89 of file VarIntVal.h.
References _val, VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
Referenced by clone(), get(), getBool(), getDouble(), and getString().
 { int res; lock(); res=_val; unlock(); return res; };
virtual double VarTypes::VarIntVal::getMaxValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Reimplemented in VarTypes::VarInt.
Definition at line 104 of file VarIntVal.h.
 { return 1; }
virtual double VarTypes::VarIntVal::getMinValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Reimplemented in VarTypes::VarInt.
Definition at line 103 of file VarIntVal.h.
 { return 0; }
virtual string VarTypes::VarIntVal::getString () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 81 of file VarIntVal.h.
References getInt().
     {
       char result[255];
       result[0]=0;
       sprintf(result,"%d",getInt());
       return result;
     };
virtual VarTypeId VarTypes::VarIntVal::getType () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 79 of file VarIntVal.h.
References VarTypes::VARTYPE_ID_INT.
 { return VARTYPE_ID_INT; };
virtual double VarTypes::VarIntVal::getValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Reimplemented in VarTypes::VarInt.
Definition at line 105 of file VarIntVal.h.
References getDouble().
 { return getDouble(); }
virtual bool VarTypes::VarIntVal::hasMaxValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Reimplemented in VarTypes::VarInt.
Definition at line 101 of file VarIntVal.h.
 { return false; }
virtual bool VarTypes::VarIntVal::hasMinValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Reimplemented in VarTypes::VarInt.
Definition at line 102 of file VarIntVal.h.
 { return false; }
virtual bool VarTypes::VarIntVal::hasValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Reimplemented in VarTypes::VarInt.
Definition at line 100 of file VarIntVal.h.
 { return true; }
virtual void VarTypes::VarIntVal::printdebug () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 65 of file VarIntVal.h.
References VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
     {
       lock();
       printf("%d\n",_val);
       unlock();
     }
virtual bool VarTypes::VarIntVal::setBool (bool val) inline virtual
Reimplemented in VarTypes::VarInt.
Definition at line 97 of file VarIntVal.h.
References setInt().
 { return setInt(val ? 1 : 0);  };
virtual bool VarTypes::VarIntVal::setDouble (double val) inline virtual
Reimplemented in VarTypes::VarInt.
Definition at line 96 of file VarIntVal.h.
References setInt().
 { return setInt((int)val);  };
virtual bool VarTypes::VarIntVal::setInt (int val) inline virtual
set the value of this node to val.
Reimplemented in VarTypes::VarInt.
Definition at line 44 of file VarIntVal.h.
References VarTypes::VarVal::changed(), VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
Referenced by clone(), setBool(), setDouble(), VarTypes::VarInt::setInt(), setString(), and VarIntVal().
     {
       lock();
       if (_val!=val) {
         _val=val;
         unlock();
         changed();
         return true;
       }
       unlock();
       return false;
     };
virtual bool VarTypes::VarIntVal::setString (const string & val) inline virtual
Reimplemented from VarTypes::VarVal.
Reimplemented in VarTypes::VarInt.
Definition at line 95 of file VarIntVal.h.
References setInt().
 { int num=0; sscanf(val.c_str(),"%d",&num); return setInt(num); };
Field Documentation
int VarTypes::VarIntVal::_val protected
Definition at line 39 of file VarIntVal.h.
Referenced by getInt(), and VarTypes::VarInt::getInt().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/vartypes/primitives/VarIntVal.h