Documentation: GraphScene Class Reference
GraphScene Class Reference
#include <GraphScene.h>
Public Member Functions
void setDrawSmooth (bool val)
void setShadeArea (bool val)
GraphScene (QObject *parent=0)
void setTimeControl (TimeControl *tcontrol)
virtual ~GraphScene ()
void addVariable (VarType *tl)
void drawBackground (QPainter *painter, const QRectF &rect)
void drawForeground (QPainter *painter, const QRectF &rect)
void updateArea ()
void mouseMoveEvent (QGraphicsSceneMouseEvent *mouseEvent)
Protected Member Functions
QPainterPath makePath (TimeLine *l, int minidx, int maxidx, bool zero_edges)
Protected Attributes
TimeControl * control
bool draw_smooth
bool shade_area
Private Attributes
QList< TimeLine * > lines
Detailed Description
Definition at line 29 of file GraphScene.h.
Constructor & Destructor Documentation
GraphScene::GraphScene (QObject * parent = 0)
Definition at line 22 of file GraphScene.cpp.
References setDrawSmooth(), and setShadeArea().
Referenced by setShadeArea().
                                         : QGraphicsScene(parent)
 {
     setDrawSmooth(true);
     setShadeArea(true);
 }
GraphScene::~GraphScene () virtual
Definition at line 28 of file GraphScene.cpp.
Referenced by setTimeControl().
 {
 }
Member Function Documentation
void GraphScene::addVariable (VarType * tl)
Definition at line 78 of file GraphScene.cpp.
References control, and lines.
Referenced by setTimeControl().
{
     if (tl->getType()==DT_TIMELINE) {
         ((TimeLine *)tl)->setTimePointer(control->getTimePointer());
         lines.append((TimeLine *)tl);
     } else {
         qDebug("cannot append non-timeline datatype to graphscene");
     }
 }
void GraphScene::drawBackground (QPainter * painter, const QRectF & rect)
Definition at line 52 of file GraphScene.cpp.
References control.
Referenced by setTimeControl().
{
     //clear the background in dark grey
     painter->setRenderHints(QPainter::Antialiasing);
     painter->save();
         QBrush bg(QColor(20,20,20));
         painter->setBrush(bg);
         painter->drawRect(rect);
     painter->restore();
     painter->save();
         QPen linepen(QColor(200,200,200), 1, Qt::SolidLine);
         linepen.setCosmetic(true);
         painter->setPen(linepen);
         painter->drawLine(control->getFullRange()->getMin(),0,control->getFullRange()->getMax(),0);
     painter->restore();
     //draw slightly visible second time-marks depending on range
     //draw textual time-labels also depending on range
 }
void GraphScene::drawForeground (QPainter * painter, const QRectF & rect)
Definition at line 87 of file GraphScene.cpp.
References control, TimeLine::findIdx(), velocity.pid_::i, lines, makePath(), path(), shade_area, and TimeLine::size().
Referenced by setTimeControl().
{
     //draw all graphs
     for (int i=0;i < lines.size();i++) {
         TimeLine * l=lines.at(i);
         int minidx=l->findIdx(control->getVisibleRange()->getMin());
         if (minidx > 0) minidx--;
         int maxidx=l->findIdx(control->getVisibleRange()->getMax());
         if (maxidx < (l->size()-1)) maxidx++;
         if (minidx >= 0 && maxidx >= 0) {
             QPainterPath path;
             painter->save();
                 painter->setRenderHints(QPainter::Antialiasing);
                 QColor c(0,192,255);
                 if (shade_area) {
                     path = makePath(l,minidx,maxidx, true);
                     c.setAlpha(128);
                     painter->setBrush( QBrush(c) );
                     painter->setPen ( Qt::NoPen );
                     painter->drawPath(path);
                 }
                 c.setAlpha(255);
                 path = makePath(l,minidx,maxidx, false);
                 QPen graphpen(c, 2, Qt::SolidLine);
                 graphpen.setCosmetic(true);
                 painter->setBrush( Qt::NoBrush );
                 painter->setPen (graphpen);
                 painter->drawPath(path);
             painter->restore();
         }
     }
     //draw pointer
     painter->save();
         //painter->setCompositionMode(QPainter::CompositionMode_Overlay);
         QPen ppen (QColor(255,255,0,128),2,Qt::SolidLine);
         ppen.setCosmetic(true);
         painter->setPen (ppen);
         painter->drawLine(QPointF(control->getTimePointer()->get(),rect.y()),QPointF(control->getTimePointer()->get(),rect.height()));
     painter->restore();
     painter->save();
         painter->resetTransform();
         QPen tpen (QColor(255,255,255),1,Qt::SolidLine);
         tpen.setCosmetic(true);
         painter->setPen (tpen);
         painter->drawText(QPointF(0,10),"test");
     painter->restore();
     //draw pointer if needed
 }
QPainterPath GraphScene::makePath (TimeLine * l, int minidx, int maxidx, bool zero_edges) protected
Definition at line 142 of file GraphScene.cpp.
References TimeLine::at(), GVector::distance(), draw_smooth, TimeVar::getData(), and path().
Referenced by drawForeground().
{
         QPainterPath path;
         QPointF p1;
         QPointF p2;
         for (int j=minidx;j<=maxidx;j++) {
                     p2.setX(((TimeIndex*)l->at(j))->getTime());
                     p2.setY(l->at(j)->getData()->getValue());
                     if (zero_edges==true && j==minidx) {
                         path.moveTo(QPointF(p2.x(),0));
                     }
                 if (draw_smooth==false) {
                     if (j==minidx && zero_edges ==false) {
                         path.moveTo(p2);
                     } else {
                         path.lineTo(p2);
                     }
                 } else {
                     if (j==minidx) {
                         if (zero_edges) {
                             path.lineTo(p2);
                         } else {
                             path.moveTo(p2);
                         }
                     } else {
                         double distance = p2.x() - p1.x();
                         path.cubicTo(p1.x() + distance / 2, p1.y(),
                             p1.x() + distance / 2, p2.y(),
                             p2.x(), p2.y());
                     }
                 }
                     if (zero_edges==true && j==maxidx) {
                         path.lineTo(QPointF(p2.x(),0));
                     }
                     p1=p2;
                 }
         return path;
 }
void GraphScene::mouseMoveEvent (QGraphicsSceneMouseEvent * mouseEvent)
Definition at line 182 of file GraphScene.cpp.
References control.
Referenced by setTimeControl().
{
     if (e->buttons() & Qt::LeftButton) {
         control->getTimePointer()->set(e->scenePos().x());
         update();
     }
     //control->hasChanged();
 }
void GraphScene::setDrawSmooth (bool val) inline
Definition at line 39 of file GraphScene.h.
Referenced by GraphScene().
{
     draw_smooth=val;
   }
void GraphScene::setShadeArea (bool val) inline
Definition at line 43 of file GraphScene.h.
References GraphScene().
Referenced by GraphScene().
{
     shade_area=val;
   }
void GraphScene::setTimeControl (TimeControl * tcontrol) inline
Definition at line 48 of file GraphScene.h.
References addVariable(), drawBackground(), drawForeground(), velocity.pid_::i, mouseMoveEvent(), updateArea(), and ~GraphScene().
Referenced by TimeGraphContainer::addGraphScene().
{
     control=tcontrol;
     for (int i=0;i<lines.size();i++) {
       lines.at(i)->setTimePointer(control->getTimePointer());
     }
   }
void GraphScene::updateArea ()
Definition at line 34 of file GraphScene.cpp.
References control, velocity.pid_::i, and lines.
Referenced by TimeGraphContainer::redraw(), and setTimeControl().
{
     ValueRange limit_value(0,1.0);
     for (int i=0;i < lines.size();i++) {
         if (i==0) {
             limit_value=lines.at(i)->getValueRange();
         } else {
             ValueRange tmp_value=lines.at(i)->getValueRange();
             if (tmp_value.getMin() < limit_value.getMin()) limit_value.setMin(tmp_value.getMin());
             if (tmp_value.getMax() > limit_value.getMax()) limit_value.setMax(tmp_value.getMax());
         }
     }
     setSceneRect(control->getFullRange()->getMin(),limit_value.getMin(),control->getFullRange()->getLength(),limit_value.getLength());
     //setSceneRect(control->getFullRange()->getMin(),-10,control->getFullRange()->getLength(),20);
     qDebug("scene rect: %f %f %f %f\n",(double)control->getFullRange()->getMin(),(double)limit_value.getMin(),(double)control->getFullRange()->getLength(),(double)limit_value.getLength());
 }
Field Documentation
TimeControl* GraphScene::control protected
Definition at line 34 of file GraphScene.h.
Referenced by addVariable(), drawBackground(), drawForeground(), mouseMoveEvent(), and updateArea().
bool GraphScene::draw_smooth protected
Definition at line 35 of file GraphScene.h.
Referenced by makePath().
QList<TimeLine *> GraphScene::lines private
Definition at line 32 of file GraphScene.h.
Referenced by addVariable(), drawForeground(), and updateArea().
bool GraphScene::shade_area protected
Definition at line 36 of file GraphScene.h.
Referenced by drawForeground().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/gui/experimental/GraphScene.h
ssl-vision/src/shared/vartypes/gui/experimental/GraphScene.cpp