Documentation: Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder Interface Reference
Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder Interface Reference
Public Member Functions
boolean hasId ()
int getId ()
boolean hasKickspeedx ()
float getKickspeedx ()
boolean hasKickspeedz ()
float getKickspeedz ()
boolean hasVeltangent ()
float getVeltangent ()
boolean hasVelnormal ()
float getVelnormal ()
boolean hasVelangular ()
float getVelangular ()
boolean hasSpinner ()
boolean getSpinner ()
boolean hasWheelsspeed ()
boolean getWheelsspeed ()
boolean hasWheel1 ()
float getWheel1 ()
boolean hasWheel2 ()
float getWheel2 ()
boolean hasWheel3 ()
float getWheel3 ()
boolean hasWheel4 ()
float getWheel4 ()
Detailed Description
Definition at line 10 of file GrSimCommands.java.
Member Function Documentation
int Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.getId ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
float Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.getKickspeedx ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
float Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.getKickspeedz ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.getSpinner ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
float Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.getVelangular ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
float Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.getVelnormal ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
float Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.getVeltangent ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
float Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.getWheel1 ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
float Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.getWheel2 ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
float Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.getWheel3 ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
float Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.getWheel4 ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.getWheelsspeed ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasId ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.isInitialized(), and Protobuf.GrSimCommands.grSim_Robot_Command.Builder.isInitialized().
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasKickspeedx ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.isInitialized(), and Protobuf.GrSimCommands.grSim_Robot_Command.Builder.isInitialized().
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasKickspeedz ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.isInitialized(), and Protobuf.GrSimCommands.grSim_Robot_Command.Builder.isInitialized().
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasSpinner ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.isInitialized(), and Protobuf.GrSimCommands.grSim_Robot_Command.Builder.isInitialized().
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasVelangular ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.isInitialized(), and Protobuf.GrSimCommands.grSim_Robot_Command.Builder.isInitialized().
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasVelnormal ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.isInitialized(), and Protobuf.GrSimCommands.grSim_Robot_Command.Builder.isInitialized().
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasVeltangent ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.isInitialized(), and Protobuf.GrSimCommands.grSim_Robot_Command.Builder.isInitialized().
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasWheel1 ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasWheel2 ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasWheel3 ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasWheel4 ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
boolean Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasWheelsspeed ()
Implemented in Protobuf.GrSimCommands.grSim_Robot_Command.Builder, and Protobuf.GrSimCommands.grSim_Robot_Command.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.isInitialized(), and Protobuf.GrSimCommands.grSim_Robot_Command.Builder.isInitialized().
The documentation for this interface was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimCommands.java