Documentation: SSL_DetectionRobot Class Reference
SSL_DetectionRobot Class Reference
#include <messages_robocup_ssl_detection.pb.h>
Public Member Functions
SSL_DetectionRobot ()
virtual ~SSL_DetectionRobot ()
SSL_DetectionRobot (const SSL_DetectionRobot &from)
SSL_DetectionRobot & operator= (const SSL_DetectionRobot &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_DetectionRobot *other)
SSL_DetectionRobot * New () const PROTOBUF_FINAL
SSL_DetectionRobot * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_DetectionRobot &from)
void MergeFrom (const SSL_DetectionRobot &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_confidence () const
void clear_confidence ()
float confidence () const
void set_confidence (float value)
bool has_robot_id () const
void clear_robot_id ()
::google::protobuf::uint32 robot_id () const
void set_robot_id (::google::protobuf::uint32 value)
bool has_x () const
void clear_x ()
float x () const
void set_x (float value)
bool has_y () const
void clear_y ()
float y () const
void set_y (float value)
bool has_orientation () const
void clear_orientation ()
float orientation () const
void set_orientation (float value)
bool has_pixel_x () const
void clear_pixel_x ()
float pixel_x () const
void set_pixel_x (float value)
bool has_pixel_y () const
void clear_pixel_y ()
float pixel_y () const
void set_pixel_y (float value)
bool has_height () const
void clear_height ()
float height () const
void set_height (float value)
SSL_DetectionRobot ()
virtual ~SSL_DetectionRobot ()
SSL_DetectionRobot (const SSL_DetectionRobot &from)
SSL_DetectionRobot & operator= (const SSL_DetectionRobot &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_DetectionRobot *other)
SSL_DetectionRobot * New () const PROTOBUF_FINAL
SSL_DetectionRobot * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_DetectionRobot &from)
void MergeFrom (const SSL_DetectionRobot &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_confidence () const
void clear_confidence ()
float confidence () const
void set_confidence (float value)
bool has_robot_id () const
void clear_robot_id ()
::google::protobuf::uint32 robot_id () const
void set_robot_id (::google::protobuf::uint32 value)
bool has_x () const
void clear_x ()
float x () const
void set_x (float value)
bool has_y () const
void clear_y ()
float y () const
void set_y (float value)
bool has_orientation () const
void clear_orientation ()
float orientation () const
void set_orientation (float value)
bool has_pixel_x () const
void clear_pixel_x ()
float pixel_x () const
void set_pixel_x (float value)
bool has_pixel_y () const
void clear_pixel_y ()
float pixel_y () const
void set_pixel_y (float value)
bool has_height () const
void clear_height ()
float height () const
void set_height (float value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_DetectionRobot & default_instance ()
static const SSL_DetectionRobot * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_DetectionRobot & default_instance ()
static void InitAsDefaultInstance ()
static const SSL_DetectionRobot * internal_default_instance ()
Static Public Attributes
static const int kConfidenceFieldNumber = 1
static const int kRobotIdFieldNumber = 2
static const int kXFieldNumber = 3
static const int kYFieldNumber = 4
static const int kOrientationFieldNumber = 5
static const int kPixelXFieldNumber = 6
static const int kPixelYFieldNumber = 7
static const int kHeightFieldNumber = 8
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_DetectionRobot *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_confidence ()
void clear_has_confidence ()
void set_has_robot_id ()
void clear_has_robot_id ()
void set_has_x ()
void clear_has_x ()
void set_has_y ()
void clear_has_y ()
void set_has_orientation ()
void clear_has_orientation ()
void set_has_pixel_x ()
void clear_has_pixel_x ()
void set_has_pixel_y ()
void clear_has_pixel_y ()
void set_has_height ()
void clear_has_height ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5fdetection_2eproto ()
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_DetectionRobot *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_confidence ()
void clear_has_confidence ()
void set_has_robot_id ()
void clear_has_robot_id ()
void set_has_x ()
void clear_has_x ()
void set_has_y ()
void clear_has_y ()
void set_has_orientation ()
void clear_has_orientation ()
void set_has_pixel_x ()
void clear_has_pixel_x ()
void set_has_pixel_y ()
void clear_has_pixel_y ()
void set_has_height ()
void clear_has_height ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::InitDefaultsSSL_DetectionRobotImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
float confidence_
::google::protobuf::uint32 robot_id_
float x_
float y_
float orientation_
float pixel_x_
float pixel_y_
float height_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::TableStruct
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto_impl ()
void protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_impl ()
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fdetection_2eproto ()
void swap (SSL_DetectionRobot &a, SSL_DetectionRobot &b)
Detailed Description
Definition at line 208 of file messages_robocup_ssl_detection.pb.h.
Constructor & Destructor Documentation
SSL_DetectionRobot::SSL_DetectionRobot ()
virtual SSL_DetectionRobot::~SSL_DetectionRobot () virtual
SSL_DetectionRobot::SSL_DetectionRobot (const SSL_DetectionRobot & from)
SSL_DetectionRobot::SSL_DetectionRobot ()
virtual SSL_DetectionRobot::~SSL_DetectionRobot () virtual
SSL_DetectionRobot::SSL_DetectionRobot (const SSL_DetectionRobot & from)
Member Function Documentation
size_t SSL_DetectionRobot::ByteSizeLong () const
size_t SSL_DetectionRobot::ByteSizeLong () const
void SSL_DetectionRobot::Clear ()
Referenced by CMPattern::TeamDetector::addRobot().
void SSL_DetectionRobot::Clear ()
void SSL_DetectionRobot::clear_confidence () inline
Definition at line 737 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::clear_has_confidence(), and SSL_DetectionBall::confidence_.
{
   confidence_ = 0;
   clear_has_confidence();
 }
void SSL_DetectionRobot::clear_confidence ()
void SSL_DetectionRobot::clear_has_confidence () inline private
Definition at line 734 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void SSL_DetectionRobot::clear_has_confidence () private
void SSL_DetectionRobot::clear_has_height () inline private
Definition at line 902 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] &= ~0x00000080u;
 }
void SSL_DetectionRobot::clear_has_height () private
void SSL_DetectionRobot::clear_has_orientation () inline private
Definition at line 830 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] &= ~0x00000010u;
 }
void SSL_DetectionRobot::clear_has_orientation () private
void SSL_DetectionRobot::clear_has_pixel_x () inline private
Definition at line 854 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] &= ~0x00000020u;
 }
void SSL_DetectionRobot::clear_has_pixel_x () private
void SSL_DetectionRobot::clear_has_pixel_y () inline private
Definition at line 878 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] &= ~0x00000040u;
 }
void SSL_DetectionRobot::clear_has_pixel_y () private
void SSL_DetectionRobot::clear_has_robot_id () inline private
Definition at line 758 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] &= ~0x00000002u;
 }
void SSL_DetectionRobot::clear_has_robot_id () private
void SSL_DetectionRobot::clear_has_x () inline private
Definition at line 782 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] &= ~0x00000004u;
 }
void SSL_DetectionRobot::clear_has_x () private
void SSL_DetectionRobot::clear_has_y () inline private
Definition at line 806 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] &= ~0x00000008u;
 }
void SSL_DetectionRobot::clear_has_y () private
void SSL_DetectionRobot::clear_height () inline
Definition at line 905 of file messages_robocup_ssl_detection.pb.h.
{
   height_ = 0;
   clear_has_height();
 }
void SSL_DetectionRobot::clear_height ()
void SSL_DetectionRobot::clear_orientation () inline
Definition at line 833 of file messages_robocup_ssl_detection.pb.h.
{
   orientation_ = 0;
   clear_has_orientation();
 }
void SSL_DetectionRobot::clear_orientation ()
void SSL_DetectionRobot::clear_pixel_x () inline
Definition at line 857 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::clear_has_pixel_x(), and SSL_DetectionBall::pixel_x_.
{
   pixel_x_ = 0;
   clear_has_pixel_x();
 }
void SSL_DetectionRobot::clear_pixel_x ()
void SSL_DetectionRobot::clear_pixel_y () inline
Definition at line 881 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::clear_has_pixel_y(), and SSL_DetectionBall::pixel_y_.
{
   pixel_y_ = 0;
   clear_has_pixel_y();
 }
void SSL_DetectionRobot::clear_pixel_y ()
void SSL_DetectionRobot::clear_robot_id () inline
Definition at line 761 of file messages_robocup_ssl_detection.pb.h.
{
   robot_id_ = 0u;
   clear_has_robot_id();
 }
void SSL_DetectionRobot::clear_robot_id ()
void SSL_DetectionRobot::clear_x () inline
Definition at line 785 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::clear_has_x(), and SSL_DetectionBall::x_.
{
   x_ = 0;
   clear_has_x();
 }
void SSL_DetectionRobot::clear_x ()
void SSL_DetectionRobot::clear_y () inline
Definition at line 809 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::clear_has_y(), and SSL_DetectionBall::y_.
{
   y_ = 0;
   clear_has_y();
 }
void SSL_DetectionRobot::clear_y ()
float SSL_DetectionRobot::confidence () const inline
Definition at line 741 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::confidence_.
Referenced by main(), printRobotInfo(), PluginDetectBalls::process(), GLSoccerView::updateDetection(), and SoccerView::UpdateRobots().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionRobot.confidence)
   return confidence_;
 }
float SSL_DetectionRobot::confidence () const
void SSL_DetectionRobot::CopyFrom (const ::google::protobuf::Message & from)
void SSL_DetectionRobot::CopyFrom (const SSL_DetectionRobot & from)
void SSL_DetectionRobot::CopyFrom (const ::google::protobuf::Message & from)
void SSL_DetectionRobot::CopyFrom (const SSL_DetectionRobot & from)
static const SSL_DetectionRobot& SSL_DetectionRobot::default_instance () static
static const SSL_DetectionRobot& SSL_DetectionRobot::default_instance () static
static const ::google::protobuf::Descriptor* SSL_DetectionRobot::descriptor () static
static const ::google::protobuf::Descriptor* SSL_DetectionRobot::descriptor () static
inline ::google::protobuf::Arena* SSL_DetectionRobot::GetArenaNoVirtual () const inline private
Definition at line 268 of file messages_robocup_ssl_detection.pb.h.
{
     return NULL;
   }
inline ::google::protobuf::Arena* SSL_DetectionRobot::GetArenaNoVirtual () const inline private
Definition at line 317 of file messages_robocup_ssl_detection.pb.h.
{
     return NULL;
   }
int SSL_DetectionRobot::GetCachedSize () const inline
Definition at line 261 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_cached_size_, SSL_DetectionBall::InternalSwap(), SSL_DetectionBall::SetCachedSize(), SSL_DetectionBall::SharedCtor(), and SSL_DetectionBall::SharedDtor().
 { return _cached_size_; }
int SSL_DetectionRobot::GetCachedSize () const inline
Definition at line 310 of file messages_robocup_ssl_detection.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata SSL_DetectionRobot::GetMetadata () const
::google::protobuf::Metadata SSL_DetectionRobot::GetMetadata () const
bool SSL_DetectionRobot::has_confidence () const inline
Definition at line 728 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool SSL_DetectionRobot::has_confidence () const
bool SSL_DetectionRobot::has_height () const inline
Definition at line 896 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   return (_has_bits_[0] & 0x00000080u) != 0;
 }
bool SSL_DetectionRobot::has_height () const
bool SSL_DetectionRobot::has_orientation () const inline
Definition at line 824 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
Referenced by printRobotInfo(), GLSoccerView::updateDetection(), and SoccerView::UpdateRobots().
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
bool SSL_DetectionRobot::has_orientation () const
bool SSL_DetectionRobot::has_pixel_x () const inline
Definition at line 848 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   return (_has_bits_[0] & 0x00000020u) != 0;
 }
bool SSL_DetectionRobot::has_pixel_x () const
bool SSL_DetectionRobot::has_pixel_y () const inline
Definition at line 872 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   return (_has_bits_[0] & 0x00000040u) != 0;
 }
bool SSL_DetectionRobot::has_pixel_y () const
bool SSL_DetectionRobot::has_robot_id () const inline
Definition at line 752 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
Referenced by printRobotInfo(), GLSoccerView::updateDetection(), and SoccerView::UpdateRobots().
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool SSL_DetectionRobot::has_robot_id () const
bool SSL_DetectionRobot::has_x () const inline
Definition at line 776 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool SSL_DetectionRobot::has_x () const
bool SSL_DetectionRobot::has_y () const inline
Definition at line 800 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool SSL_DetectionRobot::has_y () const
float SSL_DetectionRobot::height () const inline
Definition at line 909 of file messages_robocup_ssl_detection.pb.h.
Referenced by main(), and printRobotInfo().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionRobot.height)
   return height_;
 }
float SSL_DetectionRobot::height () const
static void SSL_DetectionRobot::InitAsDefaultInstance () static
static const SSL_DetectionRobot* SSL_DetectionRobot::internal_default_instance () inline static
Definition at line 231 of file messages_robocup_ssl_detection.pb.h.
References _SSL_DetectionRobot_default_instance_, and SSL_DetectionBall::Swap().
{
     return reinterpret_cast<const SSL_DetectionRobot*>(
                &_SSL_DetectionRobot_default_instance_);
   }
static const SSL_DetectionRobot* SSL_DetectionRobot::internal_default_instance () inline static
Definition at line 279 of file messages_robocup_ssl_detection.pb.h.
References _SSL_DetectionRobot_default_instance_.
{
     return reinterpret_cast<const SSL_DetectionRobot*>(
                &_SSL_DetectionRobot_default_instance_);
   }
::google::protobuf::uint8* SSL_DetectionRobot::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
::google::protobuf::uint8* SSL_DetectionRobot::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void SSL_DetectionRobot::InternalSwap (SSL_DetectionRobot * other) private
void SSL_DetectionRobot::InternalSwap (SSL_DetectionRobot * other) private
bool SSL_DetectionRobot::IsInitialized () const
bool SSL_DetectionRobot::IsInitialized () const
void* SSL_DetectionRobot::MaybeArenaPtr () const inline private
Definition at line 271 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::clear_confidence(), SSL_DetectionBall::GetMetadata(), and SSL_DetectionBall::has_confidence().
{
     return NULL;
   }
void* SSL_DetectionRobot::MaybeArenaPtr () const inline private
Definition at line 320 of file messages_robocup_ssl_detection.pb.h.
References role._GoToPoint::x, and role._GoToPoint::y.
{
     return NULL;
   }
void SSL_DetectionRobot::MergeFrom (const ::google::protobuf::Message & from)
void SSL_DetectionRobot::MergeFrom (const SSL_DetectionRobot & from)
void SSL_DetectionRobot::MergeFrom (const ::google::protobuf::Message & from)
void SSL_DetectionRobot::MergeFrom (const SSL_DetectionRobot & from)
bool SSL_DetectionRobot::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
bool SSL_DetectionRobot::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
inline ::google::protobuf::UnknownFieldSet* SSL_DetectionRobot::mutable_unknown_fields () inline
Definition at line 224 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_internal_metadata_, SSL_DetectionBall::default_instance(), and SSL_DetectionBall::descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
inline ::google::protobuf::UnknownFieldSet* SSL_DetectionRobot::mutable_unknown_fields () inline
Definition at line 271 of file messages_robocup_ssl_detection.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
SSL_DetectionRobot* SSL_DetectionRobot::New () const inline
Definition at line 240 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::ByteSizeLong(), SSL_DetectionBall::Clear(), SSL_DetectionBall::CopyFrom(), SSL_DetectionBall::InternalSerializeWithCachedSizesToArray(), SSL_DetectionBall::IsInitialized(), SSL_DetectionBall::MergeFrom(), SSL_DetectionBall::MergePartialFromCodedStream(), SSL_DetectionBall::New(), New(), SSL_DetectionBall::SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_DetectionRobot* SSL_DetectionRobot::New (::google::protobuf::Arena * arena) const
SSL_DetectionRobot* SSL_DetectionRobot::New () const inline
Definition at line 293 of file messages_robocup_ssl_detection.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_DetectionRobot* SSL_DetectionRobot::New (::google::protobuf::Arena * arena) const
SSL_DetectionRobot& SSL_DetectionRobot::operator= (const SSL_DetectionRobot & from) inline
Definition at line 215 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
SSL_DetectionRobot& SSL_DetectionRobot::operator= (const SSL_DetectionRobot & from) inline
Definition at line 249 of file messages_robocup_ssl_detection.pb.h.
{
     CopyFrom(from);
     return *this;
   }
float SSL_DetectionRobot::orientation () const inline
Definition at line 837 of file messages_robocup_ssl_detection.pb.h.
Referenced by main(), printRobotInfo(), GLSoccerView::updateDetection(), and SoccerView::UpdateRobots().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionRobot.orientation)
   return orientation_;
 }
float SSL_DetectionRobot::orientation () const
float SSL_DetectionRobot::pixel_x () const inline
Definition at line 861 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::pixel_x_.
Referenced by main(), and printRobotInfo().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionRobot.pixel_x)
   return pixel_x_;
 }
float SSL_DetectionRobot::pixel_x () const
float SSL_DetectionRobot::pixel_y () const inline
Definition at line 885 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::pixel_y_.
Referenced by main(), and printRobotInfo().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionRobot.pixel_y)
   return pixel_y_;
 }
float SSL_DetectionRobot::pixel_y () const
friendconst ::google::protobuf::uint32* SSL_DetectionRobot::protobuf_Offsets_messages_5frobocup_5fssl_5fdetection_2eproto () private
size_t SSL_DetectionRobot::RequiredFieldsByteSizeFallback () const private
size_t SSL_DetectionRobot::RequiredFieldsByteSizeFallback () const private
google::protobuf::uint32 SSL_DetectionRobot::robot_id () const inline
Definition at line 765 of file messages_robocup_ssl_detection.pb.h.
Referenced by main(), printRobotInfo(), GLSoccerView::updateDetection(), and SoccerView::UpdateRobots().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionRobot.robot_id)
   return robot_id_;
 }
::google::protobuf::uint32 SSL_DetectionRobot::robot_id () const
void SSL_DetectionRobot::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void SSL_DetectionRobot::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* SSL_DetectionRobot::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 257 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void SSL_DetectionRobot::set_confidence (float value) inline
Definition at line 745 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::confidence_, and SSL_DetectionBall::set_has_confidence().
Referenced by CMPattern::TeamDetector::addRobot(), and SSLWorld::generatePacket().
{
   set_has_confidence();
   confidence_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionRobot.confidence)
 }
void SSL_DetectionRobot::set_confidence (float value)
void SSL_DetectionRobot::set_has_confidence () inline private
Definition at line 731 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] |= 0x00000001u;
 }
void SSL_DetectionRobot::set_has_confidence () private
void SSL_DetectionRobot::set_has_height () inline private
Definition at line 899 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] |= 0x00000080u;
 }
void SSL_DetectionRobot::set_has_height () private
void SSL_DetectionRobot::set_has_orientation () inline private
Definition at line 827 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] |= 0x00000010u;
 }
void SSL_DetectionRobot::set_has_orientation () private
void SSL_DetectionRobot::set_has_pixel_x () inline private
Definition at line 851 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] |= 0x00000020u;
 }
void SSL_DetectionRobot::set_has_pixel_x () private
void SSL_DetectionRobot::set_has_pixel_y () inline private
Definition at line 875 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] |= 0x00000040u;
 }
void SSL_DetectionRobot::set_has_pixel_y () private
void SSL_DetectionRobot::set_has_robot_id () inline private
Definition at line 755 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] |= 0x00000002u;
 }
void SSL_DetectionRobot::set_has_robot_id () private
void SSL_DetectionRobot::set_has_x () inline private
Definition at line 779 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] |= 0x00000004u;
 }
void SSL_DetectionRobot::set_has_x () private
void SSL_DetectionRobot::set_has_y () inline private
Definition at line 803 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] |= 0x00000008u;
 }
void SSL_DetectionRobot::set_has_y () private
void SSL_DetectionRobot::set_height (float value) inline
Definition at line 913 of file messages_robocup_ssl_detection.pb.h.
Referenced by CMPattern::TeamDetector::findRobotsByModel(), and CMPattern::TeamDetector::findRobotsByTeamMarkerOnly().
{
   set_has_height();
   height_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionRobot.height)
 }
void SSL_DetectionRobot::set_height (float value)
void SSL_DetectionRobot::set_orientation (float value) inline
Definition at line 841 of file messages_robocup_ssl_detection.pb.h.
Referenced by CMPattern::TeamDetector::findRobotsByModel(), and SSLWorld::generatePacket().
{
   set_has_orientation();
   orientation_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionRobot.orientation)
 }
void SSL_DetectionRobot::set_orientation (float value)
void SSL_DetectionRobot::set_pixel_x (float value) inline
Definition at line 865 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::pixel_x_, and SSL_DetectionBall::set_has_pixel_x().
Referenced by CMPattern::TeamDetector::findRobotsByModel(), CMPattern::TeamDetector::findRobotsByTeamMarkerOnly(), and SSLWorld::generatePacket().
{
   set_has_pixel_x();
   pixel_x_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionRobot.pixel_x)
 }
void SSL_DetectionRobot::set_pixel_x (float value)
void SSL_DetectionRobot::set_pixel_y (float value) inline
Definition at line 889 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::pixel_y_, and SSL_DetectionBall::set_has_pixel_y().
Referenced by CMPattern::TeamDetector::findRobotsByModel(), CMPattern::TeamDetector::findRobotsByTeamMarkerOnly(), and SSLWorld::generatePacket().
{
   set_has_pixel_y();
   pixel_y_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionRobot.pixel_y)
 }
void SSL_DetectionRobot::set_pixel_y (float value)
void SSL_DetectionRobot::set_robot_id (::google::protobuf::uint32 value) inline
Definition at line 769 of file messages_robocup_ssl_detection.pb.h.
Referenced by CMPattern::TeamDetector::findRobotsByModel(), and SSLWorld::generatePacket().
{
   set_has_robot_id();
   robot_id_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionRobot.robot_id)
 }
void SSL_DetectionRobot::set_robot_id (::google::protobuf::uint32 value)
void SSL_DetectionRobot::set_x (float value) inline
Definition at line 793 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::set_has_x(), and SSL_DetectionBall::x_.
Referenced by CMPattern::TeamDetector::findRobotsByModel(), CMPattern::TeamDetector::findRobotsByTeamMarkerOnly(), and SSLWorld::generatePacket().
{
   set_has_x();
   x_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionRobot.x)
 }
void SSL_DetectionRobot::set_x (float value)
void SSL_DetectionRobot::set_y (float value) inline
Definition at line 817 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::set_has_y(), and SSL_DetectionBall::y_.
Referenced by CMPattern::TeamDetector::findRobotsByModel(), CMPattern::TeamDetector::findRobotsByTeamMarkerOnly(), and SSLWorld::generatePacket().
{
   set_has_y();
   y_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionRobot.y)
 }
void SSL_DetectionRobot::set_y (float value)
void SSL_DetectionRobot::SetCachedSize (int size) const private
void SSL_DetectionRobot::SetCachedSize (int size) const private
void SSL_DetectionRobot::SharedCtor () private
void SSL_DetectionRobot::SharedCtor () private
void SSL_DetectionRobot::SharedDtor () private
void SSL_DetectionRobot::SharedDtor () private
void SSL_DetectionRobot::Swap (SSL_DetectionRobot * other)
void SSL_DetectionRobot::Swap (SSL_DetectionRobot * other)
const ::google::protobuf::UnknownFieldSet& SSL_DetectionRobot::unknown_fields () const inline
Definition at line 220 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
const ::google::protobuf::UnknownFieldSet& SSL_DetectionRobot::unknown_fields () const inline
Definition at line 268 of file messages_robocup_ssl_detection.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
SSL_DetectionRobot::void::protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::InitDefaultsSSL_DetectionRobotImpl () private
float SSL_DetectionRobot::x () const inline
Definition at line 789 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::x_.
Referenced by main(), printRobotInfo(), PluginDetectBalls::process(), GLSoccerView::updateDetection(), and SoccerView::UpdateRobots().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionRobot.x)
   return x_;
 }
float SSL_DetectionRobot::x () const
float SSL_DetectionRobot::y () const inline
Definition at line 813 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::y_.
Referenced by main(), printRobotInfo(), PluginDetectBalls::process(), GLSoccerView::updateDetection(), and SoccerView::UpdateRobots().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionRobot.y)
   return y_;
 }
float SSL_DetectionRobot::y () const
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::TableStruct friend
Definition at line 420 of file messages_robocup_ssl_detection.pb.h.
void protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_impl () friend
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto_impl () friend
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fdetection_2eproto () friend
void swap (SSL_DetectionRobot & a, SSL_DetectionRobot & b) friend
Definition at line 287 of file messages_robocup_ssl_detection.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int SSL_DetectionRobot::_cached_size_ mutable private
Definition at line 362 of file messages_robocup_ssl_detection.pb.h.
google::protobuf::internal::HasBits< 1 > SSL_DetectionRobot::_has_bits_ private
Definition at line 361 of file messages_robocup_ssl_detection.pb.h.
google::protobuf::internal::InternalMetadataWithArena SSL_DetectionRobot::_internal_metadata_ private
Definition at line 360 of file messages_robocup_ssl_detection.pb.h.
float SSL_DetectionRobot::confidence_ private
Definition at line 363 of file messages_robocup_ssl_detection.pb.h.
float SSL_DetectionRobot::height_ private
Definition at line 370 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionRobot::kConfidenceFieldNumber = 1 static
Definition at line 285 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionRobot::kHeightFieldNumber = 8 static
Definition at line 334 of file messages_robocup_ssl_detection.pb.h.
PROTOBUF_CONSTEXPR int const SSL_DetectionRobot::kIndexInFileMessages static
Initial value:
=
    1
Definition at line 283 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionRobot::kOrientationFieldNumber = 5 static
Definition at line 313 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionRobot::kPixelXFieldNumber = 6 static
Definition at line 320 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionRobot::kPixelYFieldNumber = 7 static
Definition at line 327 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionRobot::kRobotIdFieldNumber = 2 static
Definition at line 292 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionRobot::kXFieldNumber = 3 static
Definition at line 299 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionRobot::kYFieldNumber = 4 static
Definition at line 306 of file messages_robocup_ssl_detection.pb.h.
float SSL_DetectionRobot::orientation_ private
Definition at line 367 of file messages_robocup_ssl_detection.pb.h.
float SSL_DetectionRobot::pixel_x_ private
Definition at line 368 of file messages_robocup_ssl_detection.pb.h.
float SSL_DetectionRobot::pixel_y_ private
Definition at line 369 of file messages_robocup_ssl_detection.pb.h.
google::protobuf::uint32 SSL_DetectionRobot::robot_id_ private
Definition at line 364 of file messages_robocup_ssl_detection.pb.h.
float SSL_DetectionRobot::x_ private
Definition at line 365 of file messages_robocup_ssl_detection.pb.h.
float SSL_DetectionRobot::y_ private
Definition at line 366 of file messages_robocup_ssl_detection.pb.h.
The documentation for this class was generated from the following file:
grsim_comm/include/proto/messages_robocup_ssl_detection.pb.h