Documentation: triangle1 Namespace Reference
triangle1 Namespace Reference
Functions
def reset ()
def target_Callback (msg)
def BS_callback (data)
Variables
shared = memcache.Client(['127.0.0.1:11211'], debug = False)
int BOT_ID = 0
pub = rospy.Publisher('/grsim_data', gr_Commands, queue_size=1000)
GOAL_POINT = point_2d()
x
y
int REPLANNED = 0
homePos = None
awayPos = None
BState = shared.get('state')
kub = kubs.kubs(BOT_ID, BState, pub)
anonymous
start_time = rospy.Time.now()
BeliefState
BS_callback
queue_size
target_triangle
target_Callback
Function Documentation
def triangle1.BS_callback (data)
Definition at line 39 of file triangle1.py.
References BS_callback, velocity.run.Get_Vel(), print(), and reset().
 def BS_callback(data):
     global homePos, REPLANNED
     global awayPos, start_time, BState, kub, GOAL_POINT
     BState = data
     homePos = data.homePos
     awayPos = data.awayPos
     t = rospy.Time.now()
     t = t.secs + 1.0*t.nsecs/pow(10,9)
     # print(" t - start = ",t-start_time)
     [vx, vy, vw, REPLANNED] = Get_Vel(start_time, t, BOT_ID, GOAL_POINT, homePos, awayPos)  #vx, vy, vw, replanned
     # print("-------------------REPLANNED = ",REPLANNED)
     if(REPLANNED):
         reset()
     # print("vx = ",vx)
     # print("vy = ",vy)
     # print("kubs_id = ",kub.kubs_id)
     try:
         kub.move(vx, vy)
         kub.turn(vw)
         kub.execute()
     except Exception as e:
         print("In except",e)
         pass
def triangle1.reset ()
Definition at line 29 of file triangle1.py.
Referenced by BS_callback().
 def reset():
     global start_time
     start_time = rospy.Time.now()
     start_time = 1.0*start_time.secs + 1.0*start_time.nsecs/pow(10,9)
def triangle1.target_Callback (msg)
Definition at line 34 of file triangle1.py.
References target_Callback.
 def target_Callback(msg):
     global GOAL_POINT
     GOAL_POINT.x = msg.tx0
     GOAL_POINT.y = msg.ty0
Variable Documentation
triangle1.anonymous
Definition at line 65 of file triangle1.py.
triangle1.awayPos = None
Definition at line 25 of file triangle1.py.
triangle1.BeliefState
Definition at line 69 of file triangle1.py.
int triangle1.BOT_ID = 0
Definition at line 16 of file triangle1.py.
triangle1.BS_callback
Definition at line 69 of file triangle1.py.
Referenced by BS_callback().
triangle1.BState = shared.get('state')
Definition at line 26 of file triangle1.py.
triangle1.GOAL_POINT = point_2d()
Definition at line 20 of file triangle1.py.
triangle1.homePos = None
Definition at line 24 of file triangle1.py.
triangle1.kub = kubs.kubs(BOT_ID, BState, pub)
Definition at line 27 of file triangle1.py.
triangle1.pub = rospy.Publisher('/grsim_data', gr_Commands, queue_size=1000)
Definition at line 18 of file triangle1.py.
triangle1.queue_size
Definition at line 69 of file triangle1.py.
int triangle1.REPLANNED = 0
Definition at line 23 of file triangle1.py.
triangle1.shared = memcache.Client(['127.0.0.1:11211'], debug = False)
Definition at line 13 of file triangle1.py.
float triangle1.start_time = rospy.Time.now()
Definition at line 66 of file triangle1.py.
triangle1.target_Callback
Definition at line 70 of file triangle1.py.
Referenced by target_Callback().
triangle1.target_triangle
Definition at line 70 of file triangle1.py.
Referenced by test_Triangle.BS_callback().
triangle1.x
Definition at line 21 of file triangle1.py.
triangle1.y
Definition at line 22 of file triangle1.py.