Documentation: GLWidgetGraphicsView Class Reference
GLWidgetGraphicsView Class Reference
#include <glwidget.h>
Public Member Functions
GLWidgetGraphicsView (QGraphicsScene *scene, GLWidget *_glwidget)
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void wheelEvent (QWheelEvent *event)
void keyPressEvent (QKeyEvent *event)
void closeEvent (QCloseEvent *event)
Private Attributes
GLWidget * glwidget
Detailed Description
Definition at line 108 of file glwidget.h.
Constructor & Destructor Documentation
GLWidgetGraphicsView::GLWidgetGraphicsView (QGraphicsScene * scene, GLWidget * _glwidget)
Definition at line 591 of file glwidget.cpp.
References glwidget.
     : QGraphicsView(scene)
 {
     glwidget = _glwidget;
 }
Member Function Documentation
void GLWidgetGraphicsView::closeEvent (QCloseEvent * event) protected
Definition at line 602 of file glwidget.cpp.
 {} //{viewportEvent(event);}
void GLWidgetGraphicsView::keyPressEvent (QKeyEvent * event) protected
Definition at line 601 of file glwidget.cpp.
References glwidget, and GLWidget::keyPressEvent().
 {glwidget->keyPressEvent(event);}
void GLWidgetGraphicsView::mouseMoveEvent (QMouseEvent * event) protected
Definition at line 598 of file glwidget.cpp.
References glwidget, and GLWidget::mouseMoveEvent().
 {glwidget->mouseMoveEvent(event);}
void GLWidgetGraphicsView::mousePressEvent (QMouseEvent * event) protected
Definition at line 597 of file glwidget.cpp.
References glwidget, and GLWidget::mousePressEvent().
 {glwidget->mousePressEvent(event);}
void GLWidgetGraphicsView::mouseReleaseEvent (QMouseEvent * event) protected
Definition at line 599 of file glwidget.cpp.
References glwidget, and GLWidget::mouseReleaseEvent().
 {glwidget->mouseReleaseEvent(event);}
void GLWidgetGraphicsView::wheelEvent (QWheelEvent * event) protected
Definition at line 600 of file glwidget.cpp.
References glwidget, and GLWidget::wheelEvent().
 {glwidget->wheelEvent(event);}
Field Documentation
GLWidget* GLWidgetGraphicsView::glwidget private
Definition at line 111 of file glwidget.h.
Referenced by GLWidgetGraphicsView(), keyPressEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and wheelEvent().
The documentation for this class was generated from the following files:
grSim/include/glwidget.h
grSim/src/glwidget.cpp