Documentation: Net::Address Class Reference
Net::Address Class Reference
#include <netraw.h>
Public Member Functions
Address ()
Address (const Address &src)
~Address ()
bool setHost (const char *hostname, int port)
void setAny (int port=0)
bool operator== (const Address &a) const
void copy (const Address &src)
void reset ()
void clear ()
in_addr_t getInAddr () const
void print (FILE *out=stdout) const
Address ()
Address (const Address &src)
~Address ()
bool setHost (const char *hostname, int port)
void setAny (int port=0)
bool operator== (const Address &a) const
void copy (const Address &src)
void reset ()
void clear ()
in_addr_t getInAddr () const
void print (FILE *out=stdout) const
Private Attributes
sockaddr addr
socklen_t addr_len
Friends
class UDP
Detailed Description
Definition at line 19 of file netraw.h.
Constructor & Destructor Documentation
Net::Address::Address () inline
Definition at line 23 of file netraw.h.
     {memset(&addr,0,sizeof(addr)); addr_len=0;}
Net::Address::Address (const Address & src) inline
Definition at line 25 of file netraw.h.
References copy().
     {copy(src);}
Net::Address::~Address () inline
Definition at line 27 of file netraw.h.
References port(), reset(), setAny(), and setHost().
     {reset();}
Net::Address::Address () inline
Definition at line 23 of file netraw.h.
     {memset(&addr,0,sizeof(addr)); addr_len=0;}
Net::Address::Address (const Address & src) inline
Definition at line 25 of file netraw.h.
References copy().
     {copy(src);}
Net::Address::~Address () inline
Definition at line 27 of file netraw.h.
References port(), reset(), setAny(), and setHost().
     {reset();}
Member Function Documentation
void Net::Address::clear () inline
Definition at line 39 of file netraw.h.
References getInAddr(), print(), and reset().
     {reset();}
void Net::Address::clear () inline
Definition at line 39 of file netraw.h.
References getInAddr(), print(), and reset().
     {reset();}
void Net::Address::copy (const Address & src) inline
Definition at line 35 of file netraw.h.
     {memcpy(&addr,&src.addr,src.addr_len); addr_len=src.addr_len;}
void Net::Address::copy (const Address & src) inline
Definition at line 35 of file netraw.h.
References addr, and addr_len.
Referenced by Address().
     {memcpy(&addr,&src.addr,src.addr_len); addr_len=src.addr_len;}
in_addr_t Net::Address::getInAddr () const
Definition at line 53 of file netraw.cpp.
References addr.
Referenced by Net::UDP::addMulticast(), and clear().
 {
   const sockaddr_in *s = (sockaddr_in*)(&addr);
   return(s->sin_addr.s_addr);
 }
in_addr_t Net::Address::getInAddr () const
bool Net::Address::operator== (const Address & a) const inline
Definition at line 33 of file netraw.h.
References addr, and addr_len.
     {return(addr_len==a.addr_len && memcmp(&addr,&a.addr,addr_len)==0);}
bool Net::Address::operator== (const Address & a) const inline
Definition at line 33 of file netraw.h.
     {return(addr_len==a.addr_len && memcmp(&addr,&a.addr,addr_len)==0);}
void Net::Address::print (FILE * out = stdout) const
Definition at line 59 of file netraw.cpp.
References addr, and addr_len.
Referenced by clear(), and Net::UDP::wait().
 {
   if(!addr_len){
     printf("null");
     return;
   }
   sockaddr_in *sockname = (sockaddr_in*)(&addr);
   if(sockname->sin_family == AF_INET){
     unsigned a = ntohl(sockname->sin_addr.s_addr);
     unsigned short p = ntohs(sockname->sin_port);
     fprintf(out,"%d.%d.%d.%d:%d",
             (a>>24)&0xFF, (a>>16)&0xFF, (a>>8)&0xFF, a&0xFF, p);
   }else{
     fprintf(out,"?");
   }
 }
void Net::Address::print (FILE * out = stdout) const
void Net::Address::reset () inline
Definition at line 37 of file netraw.h.
Referenced by clear(), and ~Address().
     {memset(&addr,0,sizeof(addr)); addr_len=0;}
void Net::Address::reset () inline
Definition at line 37 of file netraw.h.
     {memset(&addr,0,sizeof(addr)); addr_len=0;}
void Net::Address::setAny (int port = 0)
void Net::Address::setAny (int port = 0)
Definition at line 44 of file netraw.cpp.
References addr, addr_len, and mzero().
Referenced by RoboCupSSLClient::open(), RoboCupSSLServer::open(), and ~Address().
 {
   mzero(addr);
   sockaddr_in *s = (sockaddr_in*)(&addr);
   s->sin_addr.s_addr = htonl(INADDR_ANY);
   s->sin_port = htons(port);
   addr_len = sizeof(sockaddr_in);
 }
bool Net::Address::setHost (const char * hostname, int port)
Definition at line 21 of file netraw.cpp.
References addr, addr_len, and mzero().
Referenced by RoboCupSSLClient::open(), RoboCupSSLServer::open(), RoboCupSSLServer::sendWrapperPacket(), Net::UDP::wait(), and ~Address().
 {
   // printf("%s %d\n",hostname,port);
   addrinfo *res = NULL;
   getaddrinfo(hostname,NULL,NULL,&res);
   if(!res) return(false);
   mzero(addr);
   addr_len = res->ai_addrlen;
   memcpy(&addr,res->ai_addr,addr_len);
   // set port for internet sockets
   sockaddr_in *sockname = (sockaddr_in*)(&addr);
   if(sockname->sin_family == AF_INET){
     sockname->sin_port = htons(port);
   }else{
     // TODO: any way to set port in general?
   }
   freeaddrinfo(res);
   return(true);
 }
bool Net::Address::setHost (const char * hostname, int port)
Friends And Related Function Documentation
UDP friend
Definition at line 46 of file netraw.h.
Field Documentation
sockaddr Net::Address::addr private
Definition at line 20 of file netraw.h.
Referenced by copy(), getInAddr(), operator==(), print(), Net::UDP::recv(), Net::UDP::send(), setAny(), setHost(), and Net::UDP::wait().
socklen_t Net::Address::addr_len private
Definition at line 21 of file netraw.h.
Referenced by copy(), operator==(), print(), Net::UDP::recv(), Net::UDP::send(), setAny(), and setHost().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/net/netraw.h
ssl-vision/src/shared/net/netraw.cpp