Documentation: TimeLine Class Reference
TimeLine Class Reference
#include <TimeLine.h>
Public Slots
void slotPointerChange ()
Public Member Functions
TimeLine (string name="", TimePointer *current=0)
TimeVar * at (int id) const
int size () const
ValueClosedRange getValueClosedRange () const
void append (TimeVar *value)
TimeClosedRange getTimeClosedRange () const
void setTimePointer (TimePointer *tp)
TimePointer * getTimePointer () const
TimeVar * find (TimeIndex t) const
int findIdx (TimeIndex idx) const
TimeVar * findCurrent () const
virtual string getString () const
virtual void resetToDefault ()
virtual void printdebug () const
virtual VarTypeId getType () const
virtual ~TimeLine ()
virtual void sort ()
virtual vector< VarType * > getChildren () const
Static Public Member Functions
static bool timePointerLessThan (const TimeVar *s1, const TimeVar *s2)
Protected Member Functions
virtual void readChildren (XMLNode &us)
virtual void updateChildren (XMLNode &us) const
Protected Attributes
TimePointer * cur
QList< TimeVar * > list
Detailed Description
Definition at line 32 of file TimeLine.h.
Constructor & Destructor Documentation
TimeLine::TimeLine (string name = "", TimePointer * current = 0) inline
Definition at line 43 of file TimeLine.h.
References setTimePointer().
                                                              : VarType ( name ) {
       setTimePointer ( current );
       //list.append(new type);
     };
virtual TimeLine::~TimeLine () inline virtual
Definition at line 153 of file TimeLine.h.
 {};
Member Function Documentation
void TimeLine::append (TimeVar * value) inline
Definition at line 74 of file TimeLine.h.
{
       list.append ( value );
       changed();
     }
TimeVar* TimeLine::at (int id) const inline
Definition at line 48 of file TimeLine.h.
Referenced by GraphScene::makePath().
{
       if ( id < 0 || id >= list.size() ) return 0;
       return list.at ( id );
     }
TimeVar* TimeLine::find (TimeIndex t) const inline
Definition at line 108 of file TimeLine.h.
References findIdx().
Referenced by findCurrent().
{
       int idx = findIdx ( t );
       if ( idx == ( -1 ) ) return 0;
       return ( list.at ( idx ) );
     }
TimeVar* TimeLine::findCurrent () const inline
Definition at line 139 of file TimeLine.h.
References find().
Referenced by getChildren().
{
       if ( cur == 0 ) {
         return find ( 0.0 );
       } else {
         return find ( cur->get() );
       }
     }
int TimeLine::findIdx (TimeIndex idx) const inline
Definition at line 114 of file TimeLine.h.
Referenced by GraphScene::drawForeground(), and find().
{
       //perform a binary search for the index
       int maxidx = list.size() - 1;
       int minidx = 0;
       int range;
       int split;
       if ( maxidx < 0 ) return -1;
       while ( true ) {
         range = maxidx - minidx;
         split = ( range / 2 ) + minidx;
         if ( range <= 1 ) return split;
         if ( * ( ( TimeIndex * ) ( list.at ( split ) ) ) == idx ) {
           return split;
         } else if ( * ( ( TimeIndex * ) ( list.at ( split ) ) ) < idx ) {
           minidx = split;
         } else {
           maxidx = split;
         }
       }
     }
virtual vector<VarType *> TimeLine::getChildren () const inline virtual
Definition at line 170 of file TimeLine.h.
References findCurrent(), and v.
{
       vector<VarType *> v;
       //findCurrent();
       VarType * tmp = ( VarType * ) findCurrent();
       if ( tmp != 0 ) {
         v.push_back ( tmp );
       }
       return v;
     }
virtual string TimeLine::getString () const inline virtual
Definition at line 148 of file TimeLine.h.
 { return ""; }
TimeClosedRange TimeLine::getTimeClosedRange () const inline
Definition at line 79 of file TimeLine.h.
References velocity.pid_::i.
{
       TimeClosedRange result;
       QListIterator<TimeVar *> i ( list );
       while ( i.hasNext() ) {
         TimeVar * val = ( TimeVar  * ) i.next();
         if ( val != 0 ) {
           if ( ( *val ) < result.getMin() ) result.setMin ( ( TimeIndex ) ( *val ) );
           if ( ( *val ) > result.getMax() ) result.setMax ( ( TimeIndex ) ( *val ) );
         }
       }
       return result;
     }
TimePointer* TimeLine::getTimePointer () const inline
Definition at line 104 of file TimeLine.h.
References cur.
{
       return cur;
     }
virtual VarTypeId TimeLine::getType () const inline virtual
Definition at line 152 of file TimeLine.h.
Referenced by readChildren().
 { return DT_TIMELINE; };
ValueClosedRange TimeLine::getValueClosedRange () const inline
Definition at line 57 of file TimeLine.h.
References TimeVar::getData(), and velocity.pid_::i.
{
       ValueClosedRange result;
       QListIterator<TimeVar *> i ( list );
       bool first = true;
       while ( i.hasNext() ) {
         TimeVar  * val = i.next();
         if ( val != 0 ) {
           //FIXME: TODO: use the provided hasValue hasMax getMaxValue...functions
           if ( first || ( val->getData()->getValue() < result.getMin() ) ) result.setMin ( val->getData()->getValue() );
           if ( first || ( val->getData()->getValue() > result.getMax() ) ) result.setMax ( val->getData()->getValue() );
           first = false;
         }
       }
       return result;
     }
virtual void TimeLine::printdebug () const inline virtual
Definition at line 150 of file TimeLine.h.
 { printf ( "TimeLine named %s containing %d element(s)\n", getName().c_str(), list.size() ); }
virtual void TimeLine::readChildren (XMLNode & us) inline protected virtual
Definition at line 182 of file TimeLine.h.
References getType(), velocity.pid_::i, sort(), and v.
{
       qDebug ( "updating children\n" );
       vector<VarType *> v;
       QListIterator<TimeVar *> i ( list );
       while ( i.hasNext() ) {
         v.push_back ( ( VarType * ) i.next() );
       }
       vector<VarType *> result;
       result = readChildrenHelper ( us, v, false, true );
       list.clear();
       for ( unsigned int i = 0;i < result.size();i++ ) {
         qDebug ( "found one\n" );
         if ( result[i]->getType() == DT_TIMEVAR ) {
           list.append ( ( TimeVar * ) result[i] );
         }
       }
       sort();
     }
virtual void TimeLine::resetToDefault () inline virtual
Definition at line 149 of file TimeLine.h.
 { list.clear(); };
void TimeLine::setTimePointer (TimePointer * tp) inline
Definition at line 94 of file TimeLine.h.
References slotPointerChange().
Referenced by TimeLine().
{
       if ( cur != 0 ) {
         disconnect ( tp, SIGNAL ( hasChanged(VarType *) ), this, SLOT ( slotPointerChange() ) );
       }
       qDebug ( "setup pointer\n" );
       cur = tp;
       connect ( tp, SIGNAL ( hasChanged(VarType *) ), this, SLOT ( slotPointerChange() ) );
       changed();
     }
int TimeLine::size () const inline
Definition at line 53 of file TimeLine.h.
Referenced by GraphScene::drawForeground().
                      {
       return list.size();
     }
void TimeLine::slotPointerChange () inline slot
Definition at line 38 of file TimeLine.h.
Referenced by setTimePointer().
{
       qDebug ( "TIME CHANGED\n" );
       changed();
     }
virtual void TimeLine::sort () inline virtual
Definition at line 165 of file TimeLine.h.
References timePointerLessThan().
Referenced by readChildren().
{
       qSort ( list.begin(), list.end(), timePointerLessThan );
       changed();
     }
static bool TimeLine::timePointerLessThan (const TimeVar * s1, const TimeVar * s2) inline static
Definition at line 156 of file TimeLine.h.
Referenced by sort().
{
       if ( s1 != 0 && s2 != 0 ) {
         return ( *s1 ) < ( *s2 );
       } else {
         return false;
       }
     }
virtual void TimeLine::updateChildren (XMLNode & us) const inline protected virtual
Definition at line 204 of file TimeLine.h.
References velocity.pid_::i.
{
       //wipe out all children of type var...
       //us.deleteNodeContent(1);
       deleteAllVarChildren ( us );
       QListIterator<TimeVar *> i ( list );
       while ( i.hasNext() ) {
         ( i.next() )->writeXML ( us, true );
       }
     }
Field Documentation
TimePointer* TimeLine::cur protected
Definition at line 35 of file TimeLine.h.
Referenced by getTimePointer().
QList<TimeVar *> TimeLine::list protected
Definition at line 36 of file TimeLine.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/vartypes/enhanced/TimeLine.h