Documentation: protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto Namespace Reference
protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto Namespace Reference
Data Structures
struct TableStruct
Functions
void AddDescriptors ()
void InitDefaultsLog_FrameImpl ()
void InitDefaultsLog_Frame ()
void InitDefaultsRefbox_LogImpl ()
void InitDefaultsRefbox_Log ()
void InitDefaults ()
Function Documentation
void protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::AddDescriptors ()
void protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::InitDefaults () inline
Definition at line 50 of file messages_robocup_ssl_refbox_log.pb.h.
References _Log_Frame_default_instance_, _Refbox_Log_default_instance_, InitDefaultsLog_Frame(), and InitDefaultsRefbox_Log().
{
   InitDefaultsLog_Frame();
   InitDefaultsRefbox_Log();
 }
void protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::InitDefaultsLog_Frame ()
Referenced by InitDefaults().
void protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::InitDefaultsLog_FrameImpl ()
void protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::InitDefaultsRefbox_Log ()
Referenced by InitDefaults().
void protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::InitDefaultsRefbox_LogImpl ()