Documentation: TimeControlWidget Class Reference
TimeControlWidget Class Reference
#include <TimeControlWidget.h>
Public Member Functions
TimeControl * getTimeControl ()
void redraw ()
TimeControlWidget (TimeControl *c=0)
virtual ~TimeControlWidget ()
Protected Attributes
QVBoxLayout l
TimeControl * control
TimeRange range_full
TimeRange range_visible
TimePointer time_current
Detailed Description
Definition at line 27 of file TimeControlWidget.h.
Constructor & Destructor Documentation
TimeControlWidget::TimeControlWidget (TimeControl * c = 0)
Definition at line 22 of file TimeControlWidget.cpp.
References control, and redraw().
Referenced by getTimeControl().
 {
     setupUi((QWidget *)this);
     if (c==0) c = new TimeControl();
     control=c;
     redraw();
 }
TimeControlWidget::~TimeControlWidget () virtual
Definition at line 31 of file TimeControlWidget.cpp.
Referenced by getTimeControl().
 {
 }
Member Function Documentation
TimeControl* TimeControlWidget::getTimeControl () inline
Definition at line 40 of file TimeControlWidget.h.
References control, redraw(), TimeControlWidget(), and ~TimeControlWidget().
Referenced by TimeGraphContainer::addGraphScene(), TimeGraphContainer::getTimeControl(), and TimeGraphContainer::redraw().
{
         return control;
     }
void TimeControlWidget::redraw ()
Definition at line 35 of file TimeControlWidget.cpp.
References range_full, and range_visible.
Referenced by getTimeControl(), and TimeControlWidget().
{
     scroller->setMinimum((int)range_full.getMin());
     scroller->setMaximum((int)(range_full.getMax()+1.0));
     scroller->setPageStep(range_visible.getLength());
     scroller->setSliderPosition(range_visible.getMin());
     label1->setText("Total [ " +
     QString::number(range_full.getMin()) +
     " , " +
     QString::number(range_full.getMax()) +
     " ] (Range: " +
     QString::number(range_full.getLength()) +
     ")"
     );
     label2->setText("Selected [ " +
     QString::number(range_visible.getMin()) +
     " , " +
     QString::number(range_visible.getMax()) +
     " ] (Range: " +
     QString::number(range_visible.getLength()) +
     ")"
     );
 }
Field Documentation
TimeControl* TimeControlWidget::control protected
Definition at line 32 of file TimeControlWidget.h.
Referenced by getTimeControl(), and TimeControlWidget().
QVBoxLayout TimeControlWidget::l protected
Definition at line 31 of file TimeControlWidget.h.
TimeRange TimeControlWidget::range_full protected
Definition at line 33 of file TimeControlWidget.h.
Referenced by redraw().
TimeRange TimeControlWidget::range_visible protected
Definition at line 34 of file TimeControlWidget.h.
Referenced by redraw().
TimePointer TimeControlWidget::time_current protected
Definition at line 35 of file TimeControlWidget.h.
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/gui/experimental/TimeControlWidget.h
ssl-vision/src/shared/vartypes/gui/experimental/TimeControlWidget.cpp