Documentation: CameraParameters Class Reference
CameraParameters Class Reference
Intrinsic and extrinsic camera parameters.
#include <camera_calibration.h>
Data Structures
class AdditionalCalibrationInformation
Some additional data used for calibration.
class CalibrationData
Additional structure for holding information about image points on line segments.
Public Types
enum {
FOCAL_LENGTH =0, PP_X, PP_Y, DIST,
Q_1, Q_2, Q_3, T_1,
T_2, T_3, STATE_SPACE_DIMENSION
}
enum { FOUR_POINT_INITIAL = 1, FULL_ESTIMATION = 2 }
Public Member Functions
CameraParameters (int camera_index_)
~CameraParameters ()
void addSettingsToList (VarList &list)
GVector::vector3d< double > getWorldLocation ()
void field2image (const GVector::vector3d< double > &p_f, GVector::vector2d< double > &p_i) const
void image2field (GVector::vector3d< double > &p_f, const GVector::vector2d< double > &p_i, double z) const
void calibrate (std::vector< GVector::vector3d< double > > &p_f, std::vector< GVector::vector2d< double > > &p_i, int cal_type)
double radialDistortion (double ru) const
double radialDistortionInv (double rd) const
void radialDistortionInv (GVector::vector2d< double > &pu, const GVector::vector2d< double > &pd) const
void radialDistortion (const GVector::vector2d< double > pu, GVector::vector2d< double > &pd) const
double radialDistortion (double ru, double dist) const
void radialDistortion (const GVector::vector2d< double > pu, GVector::vector2d< double > &pd, double dist) const
double calc_chisqr (std::vector< GVector::vector3d< double > > &p_f, std::vector< GVector::vector2d< double > > &p_i, Eigen::VectorXd &p, int)
void field2image (GVector::vector3d< double > &p_f, GVector::vector2d< double > &p_i, Eigen::VectorXd &p)
void toProtoBuffer (SSL_GeometryCameraCalibration &buffer, int camera_id) const
void fromProtoBuffer (const SSL_GeometryCameraCalibration &buffer)
void do_calibration (int cal_type)
void reset ()
Data Fields
const int camera_index
VarDouble * focal_length
VarDouble * principal_point_x
VarDouble * principal_point_y
VarDouble * distortion
VarDouble * q0
VarDouble * q1
VarDouble * q2
VarDouble * q3
VarDouble * tx
VarDouble * ty
VarDouble * tz
std::vector< CalibrationData > calibrationSegments
Eigen::VectorXd p_alpha
Quaternion< double > q_rotate180
AdditionalCalibrationInformation * additional_calibration_information
std::vector< int > p_to_est
Detailed Description
Intrinsic and extrinsic camera parameters.
Author
Tim Laue, (C) 2009
Definition at line 44 of file camera_calibration.h.
Member Enumeration Documentation
anonymous enum
Enumerator
FOCAL_LENGTH
PP_X
PP_Y
DIST
Q_1
Q_2
Q_3
T_1
T_2
T_3
STATE_SPACE_DIMENSION
Definition at line 99 of file camera_calibration.h.
   {
     FOCAL_LENGTH=0,
     PP_X,
     PP_Y,
     DIST,
     Q_1,
     Q_2,
     Q_3,
     T_1,
     T_2,
     T_3,
     STATE_SPACE_DIMENSION
   };
anonymous enum
Enumerator
FOUR_POINT_INITIAL
FULL_ESTIMATION
Definition at line 114 of file camera_calibration.h.
   {
     FOUR_POINT_INITIAL = 1,
     FULL_ESTIMATION = 2
     // ... = 4 etc.
   };
Constructor & Destructor Documentation
CameraParameters::CameraParameters (int camera_index_)
Definition at line 11 of file camera_calibration.cpp.
References VarTypes::VarType::addFlags(), additional_calibration_information, camera_index, distortion, focal_length, principal_point_x, principal_point_y, q0, q1, q2, q3, q_rotate180, tx, ty, tz, and VarTypes::VARTYPE_FLAG_NOLOAD_ATTRIBUTES.
                                                     :
     camera_index(camera_index_), p_alpha(Eigen::VectorXd(1)) {
   focal_length = new VarDouble("focal length", 500.0);
   principal_point_x = new VarDouble("principal point x", 390.0);
   principal_point_y = new VarDouble("principal point y", 290.0);
   distortion = new VarDouble("distortion", 0.0, 0.0, 2.0);
   //do not overwrite min/max ranges with values from config file
   distortion->addFlags(VARTYPE_FLAG_NOLOAD_ATTRIBUTES);
   q0 = new VarDouble("q0", 0.7);
   q1 = new VarDouble("q1", -0.7);
   q2 = new VarDouble("q2", .0);
   q3 = new VarDouble("q3", .0);
   tx = new VarDouble("tx", 0);
   ty = new VarDouble("ty", 1250);
   tz = new VarDouble("tz", 3500, 0, 5000);
   //do not overwrite min/max ranges with values from config file
   tz->addFlags(VARTYPE_FLAG_NOLOAD_ATTRIBUTES);
   additional_calibration_information =
       new AdditionalCalibrationInformation(camera_index);
   q_rotate180 = Quaternion<double>(0, 0, 1.0,0);
 }
CameraParameters::~CameraParameters ()
Definition at line 38 of file camera_calibration.cpp.
References additional_calibration_information, distortion, focal_length, principal_point_x, principal_point_y, q0, q1, q2, q3, tx, ty, and tz.
{
   delete focal_length;
   delete principal_point_x;
   delete principal_point_y;
   delete distortion;
   delete q0;
   delete q1;
   delete q2;
   delete q3;
   delete tx;
   delete ty;
   delete tz;
   delete additional_calibration_information;
 }
Member Function Documentation
void CameraParameters::addSettingsToList (VarList & list)
Definition at line 109 of file camera_calibration.cpp.
References VarTypes::VarList::addChild(), distortion, focal_length, principal_point_x, principal_point_y, q0, q1, q2, q3, tx, ty, and tz.
Referenced by PluginCameraCalibration::PluginCameraCalibration().
{
   list.addChild(focal_length);
   list.addChild(principal_point_x);
   list.addChild(principal_point_y);
   list.addChild(distortion);
   list.addChild(q0);
   list.addChild(q1);
   list.addChild(q2);
   list.addChild(q3);
   list.addChild(tx);
   list.addChild(ty);
   list.addChild(tz);
 }
double CameraParameters::calc_chisqr (std::vector< GVector::vector3d< double > > & p_f, std::vector< GVector::vector2d< double > > & p_i, Eigen::VectorXd & p, int cal_type)
Definition at line 276 of file camera_calibration.cpp.
References additional_calibration_information, calibrationSegments, CameraParameters::AdditionalCalibrationInformation::cov_corner_x, CameraParameters::AdditionalCalibrationInformation::cov_corner_y, CameraParameters::AdditionalCalibrationInformation::cov_ls_x, CameraParameters::AdditionalCalibrationInformation::cov_ls_y, field2image(), FULL_ESTIMATION, VarTypes::VarDoubleVal::getDouble(), velocity.pid_::i, p_alpha, STATE_SPACE_DIMENSION, bot_comm::theta, GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
Referenced by calibrate().
                   {
   assert(p_f.size() == p_i.size());
   double cov_cx_inv =
       1.0 / additional_calibration_information->cov_corner_x->getDouble();
   double cov_cy_inv =
       1.0 / additional_calibration_information->cov_corner_y->getDouble();
   double cov_lsx_inv =
       1.0 / additional_calibration_information->cov_ls_x->getDouble();
   double cov_lsy_inv =
       1.0 / additional_calibration_information->cov_ls_y->getDouble();
   double chisqr(0);
   // Iterate over manual points
   std::vector<GVector::vector3d<double> >::iterator it_p_f  = p_f.begin();
   std::vector<GVector::vector2d<double> >::iterator it_p_i  = p_i.begin();
   for (; it_p_f != p_f.end(); it_p_f++, it_p_i++)
   {
     GVector::vector2d<double> proj_p;
     field2image(*it_p_f, proj_p, p);
     chisqr += (proj_p.x - it_p_i->x) * (proj_p.x - it_p_i->x) * cov_cx_inv +
         (proj_p.y - it_p_i->y) * (proj_p.y - it_p_i->y) * cov_cy_inv;
   }
   // Iterate of line edge points, but only when performing a full estimation
   if (cal_type & FULL_ESTIMATION)
   {
     std::vector<CalibrationData>::iterator ls_it = calibrationSegments.begin();
     int i = 0;
     for (; ls_it != calibrationSegments.end(); ls_it++) {
       std::vector< std::pair<GVector::vector2d<double>,bool> >::iterator
           imgPts_it = (*ls_it).imgPts.begin();
       for (; imgPts_it != (*ls_it).imgPts.end(); imgPts_it++) {
         // Integrate only if a valid point on line
         if (imgPts_it->second) {
           GVector::vector2d<double> proj_p;
           double alpha = p_alpha(i) + p(STATE_SPACE_DIMENSION + i);
           // Calculate point on segment
           GVector::vector3d<double> alpha_point;
           if (ls_it->straightLine) {
             alpha_point = alpha * (*ls_it).p1 + (1.0 - alpha) * (*ls_it).p2;
           } else {
             double theta = alpha * (*ls_it).theta1 + (1.0 - alpha) * (*ls_it).theta2;
             alpha_point = ls_it->center +
                 ls_it->radius*GVector::vector3d<double>(
                     cos(theta),sin(theta),0.0);
           }
           // Project into image plane
           field2image(alpha_point, proj_p, p);
           chisqr += (proj_p.x-imgPts_it->first.x) *
               (proj_p.x-imgPts_it->first.x) * cov_lsx_inv +
               (proj_p.y - imgPts_it->first.y) *
               (proj_p.y - imgPts_it->first.y) * cov_lsy_inv;
           i++;
         }
       }
     }
   }
   return chisqr;
 }
void CameraParameters::calibrate (std::vector< GVector::vector3d< double > > & p_f, std::vector< GVector::vector2d< double > > & p_i, int cal_type)
Definition at line 380 of file camera_calibration.cpp.
References additional_calibration_information, CameraParameters::AdditionalCalibrationInformation::AdditionalCalibrationInformation(), calc_chisqr(), calibrationSegments, CameraParameters::AdditionalCalibrationInformation::convergence_timeout, CameraParameters::AdditionalCalibrationInformation::cov_corner_x, CameraParameters::AdditionalCalibrationInformation::cov_corner_y, CameraParameters::AdditionalCalibrationInformation::cov_ls_x, CameraParameters::AdditionalCalibrationInformation::cov_ls_y, DIST, distortion, field2image(), focal_length, FOCAL_LENGTH, FULL_ESTIMATION, VarTypes::VarDoubleVal::getDouble(), GetTimeSec(), velocity.pid_::i, image2field(), GVector::vector3d< num >::length(), GVector::vector3d< num >::norm(), Quaternion< num >::norm(), p_alpha, p_to_est, PP_X, PP_Y, principal_point_x, principal_point_y, q0, q1, q2, q3, Q_1, Q_2, Q_3, q_rotate180, Quaternion< num >::setAxis(), VarTypes::VarDouble::setDouble(), STATE_SPACE_DIMENSION, T_1, T_2, T_3, bot_comm::theta, tx, ty, tz, GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
Referenced by do_calibration().
{
   assert(p_f.size() == p_i.size());
   assert(cal_type != 0);
   p_to_est.clear();
   p_to_est.push_back(FOCAL_LENGTH);
   p_to_est.push_back(Q_1);
   p_to_est.push_back(Q_2);
   p_to_est.push_back(Q_3);
   p_to_est.push_back(T_1);
   p_to_est.push_back(T_2);
   int num_alpha(0);
   if (cal_type & FULL_ESTIMATION) {
     int count_alpha(0); //The number of well detected line segment points
     std::vector<CalibrationData>::iterator ls_it = calibrationSegments.begin();
     for (; ls_it != calibrationSegments.end(); ls_it++) {
       std::vector< std::pair<GVector::vector2d<double>,bool> >::iterator
           pts_it = (*ls_it).imgPts.begin();
       for (; pts_it != (*ls_it).imgPts.end(); pts_it++) {
         if (pts_it->second) count_alpha ++;
       }
     }
     if (count_alpha > 0) {
       p_alpha = Eigen::VectorXd(count_alpha);
       count_alpha = 0;
       ls_it = calibrationSegments.begin();
       for (; ls_it != calibrationSegments.end(); ls_it++) {
         std::vector< std::pair<GVector::vector2d<double>,bool> >::iterator
             pts_it = (*ls_it).imgPts.begin();
         std::vector< double >::iterator alphas_it = (*ls_it).alphas.begin();
         for (; pts_it != (*ls_it).imgPts.end() &&
             alphas_it != (*ls_it).alphas.end(); pts_it++, alphas_it++) {
           if (pts_it->second) {
             p_alpha(count_alpha++) = (*alphas_it);
           }
         }
       }
     }
     p_to_est.push_back(PP_X);
     p_to_est.push_back(PP_Y);
     p_to_est.push_back(DIST);
     num_alpha = count_alpha;
   }
   double lambda(0.01);
   Eigen::VectorXd p(STATE_SPACE_DIMENSION + num_alpha);
   p.setZero();
   // Calculate first chisqr for all points using the start parameters
   double old_chisqr = calc_chisqr(p_f, p_i, p, cal_type);
 #ifndef NDEBUG
   std::cerr << "Chi-square: "<< old_chisqr << std::endl;
 #endif
   // Create and fill corner measurement covariance matrix
   Eigen::Matrix2d cov_corner_inv;
   cov_corner_inv <<
       1 / additional_calibration_information->cov_corner_x->getDouble(), 0 , 0 ,
       1 / additional_calibration_information->cov_corner_y->getDouble();
   // Create and fill line segment measurement covariance matrix
   Eigen::Matrix2d cov_ls_inv;
   cov_ls_inv << 1 / additional_calibration_information->cov_ls_x->getDouble(),
       0 , 0 , 1 / additional_calibration_information->cov_ls_y->getDouble();
   // Matrices for A, b and the Jacobian J
   Eigen::MatrixXd alpha(STATE_SPACE_DIMENSION + num_alpha,
                         STATE_SPACE_DIMENSION + num_alpha);
   Eigen::VectorXd beta(STATE_SPACE_DIMENSION + num_alpha, 1);
   Eigen::MatrixXd J(2, STATE_SPACE_DIMENSION + num_alpha);
   bool stop_optimization(false);
   int convergence_counter(0);
   double t_start=GetTimeSec();
   while (!stop_optimization) {
     // Calculate Jacobi-Matrix, alpha and beta
     // Iterate over alle point pairs
     std::vector<GVector::vector3d<double> >::iterator it_p_f  = p_f.begin();
     std::vector<GVector::vector2d<double> >::iterator it_p_i  = p_i.begin();
     double epsilon = sqrt(std::numeric_limits<double>::epsilon());
     alpha.setZero();
     beta.setZero();
     for (; it_p_f != p_f.end(); it_p_f++, it_p_i++) {
       J.setZero();
       GVector::vector2d<double> proj_p;
       field2image(*it_p_f, proj_p, p);
       proj_p = proj_p - *it_p_i;
       std::vector<int>::iterator it = p_to_est.begin();
       for (; it != p_to_est.end(); it++) {
         int i = *it;
         Eigen::VectorXd p_diff = p;
         p_diff(i) = p_diff(i) + epsilon;
         GVector::vector2d<double> proj_p_diff;
         field2image(*it_p_f, proj_p_diff, p_diff);
         J(0,i) = ((proj_p_diff.x - (*it_p_i).x) - proj_p.x) / epsilon;
         J(1,i) = ((proj_p_diff.y - (*it_p_i).y) - proj_p.y) / epsilon;
       }
       alpha += J.transpose() * cov_corner_inv * J;
       beta += J.transpose() * cov_corner_inv *
           Eigen::Vector2d(proj_p.x, proj_p.y);
     }
     if (cal_type & FULL_ESTIMATION) {
       // First, calculate how many alpha we need to estimate
       std::vector<CalibrationData>::iterator ls_it =
           calibrationSegments.begin();
       int i = 0;
       for (; ls_it != calibrationSegments.end(); ls_it++) {
         std::vector< std::pair<GVector::vector2d<double>,bool> >::iterator
             pts_it = (*ls_it).imgPts.begin();
         for (; pts_it != (*ls_it).imgPts.end(); pts_it++) {
           if (pts_it->second) {
             GVector::vector2d<double> proj_p;
             GVector::vector3d<double >alpha_point;
             if (ls_it->straightLine) {
               alpha_point = p_alpha(i) * (*ls_it).p1 + (1 - p_alpha(i)) * (*ls_it).p2;
             } else {
               double theta = p_alpha(i) * (*ls_it).theta1 + (1.0 - p_alpha(i)) * (*ls_it).theta2;
               alpha_point = ls_it->center + ls_it->radius*GVector::vector3d<double>(cos(theta),sin(theta),0.0);
             }
             field2image(alpha_point, proj_p, p);
             proj_p = proj_p - (*pts_it).first;
             J.setZero();
             std::vector<int>::iterator it = p_to_est.begin();
             for (; it != p_to_est.end(); it++) {
               int j = *it;
               Eigen::VectorXd p_diff = p;
               p_diff(j) = p_diff(j) + epsilon;
               GVector::vector2d<double> proj_p_diff;
               field2image(alpha_point, proj_p_diff, p_diff);
               J(0,j) = ((proj_p_diff.x - (*pts_it).first.x) - proj_p.x) /
                   epsilon;
               J(1,j) = ((proj_p_diff.y - (*pts_it).first.y) - proj_p.y) /
                   epsilon;
             }
             double my_alpha = p_alpha(i) + epsilon;
             if (ls_it->straightLine) {
               alpha_point = my_alpha * (*ls_it).p1 + (1 - my_alpha) *
                   (*ls_it).p2;
             } else {
               double theta = my_alpha * (*ls_it).theta1 + (1.0 - my_alpha) *
                   (*ls_it).theta2;
               alpha_point = ls_it->center +
                   ls_it->radius*GVector::vector3d<double>(cos(theta),
                                                           sin(theta),0.0);
             }
             GVector::vector2d<double> proj_p_diff;
             field2image(alpha_point, proj_p_diff);
             J(0,STATE_SPACE_DIMENSION + i) =
                 ((proj_p_diff.x - (*pts_it).first.x) - proj_p.x) / epsilon;
             J(1,STATE_SPACE_DIMENSION + i) =
                 ((proj_p_diff.y - (*pts_it).first.y) - proj_p.y) / epsilon;
             alpha += J.transpose() * cov_ls_inv * J;
             beta += J.transpose() * cov_ls_inv *
                 Eigen::Vector2d(proj_p.x, proj_p.y);
             i++;
           }
         }
       }
     }
     // Augment alpha
     alpha += Eigen::MatrixXd::Identity(
         STATE_SPACE_DIMENSION + num_alpha, STATE_SPACE_DIMENSION + num_alpha)
         * lambda;
     // Solve for x
     Eigen::VectorXd new_p(STATE_SPACE_DIMENSION + num_alpha);
     // Due to an API change we need to check for
     // the right call at compile time
 #ifdef EIGEN_WORLD_VERSION
     // alpha.llt().solve(-beta, &new_p); -- modify 1/15/16
     //  -- move to Eigen3 structure -
     //  -- http://eigen.tuxfamily.org/dox/Eigen2ToEigen3.html
     new_p = alpha.llt().solve(-beta);
 #else
     Eigen::Cholesky<Eigen::MatrixXd> c(alpha);
     new_p = c.solve(-beta);
 #endif
     // Calculate chisqr again
     double chisqr = calc_chisqr(p_f, p_i, new_p, cal_type);
     if (chisqr < old_chisqr) {
       focal_length->setDouble(focal_length->getDouble() + new_p[FOCAL_LENGTH]);
       principal_point_x->setDouble(
           principal_point_x->getDouble() + new_p[PP_X]);
       principal_point_y->setDouble(
           principal_point_y->getDouble() + new_p[PP_Y]);
       distortion->setDouble(distortion->getDouble() + new_p[DIST]);
       tx->setDouble(tx->getDouble() + new_p[T_1]);
       ty->setDouble(ty->getDouble() + new_p[T_2]);
       tz->setDouble(tz->getDouble() + new_p[T_3]);
       Quaternion<double> q_diff;
       GVector::vector3d<double> aa_diff(new_p[Q_1], new_p[Q_2], new_p[Q_3]);
       q_diff.setAxis(aa_diff.norm(), aa_diff.length());
       Quaternion<double> q_field2cam = Quaternion<double>(
           q0->getDouble(),q1->getDouble(),q2->getDouble(),q3->getDouble());
       q_field2cam.norm();
       q_field2cam = q_diff * q_field2cam ;
       q0->setDouble(q_field2cam.x);
       q1->setDouble(q_field2cam.y);
       q2->setDouble(q_field2cam.z);
       q3->setDouble(q_field2cam.w);
       for (int i=0; i < num_alpha; i++)
         p_alpha[i] += new_p[STATE_SPACE_DIMENSION + i];
       // Normalize focal length an orientation when the optimization tends to go into the wrong
       // of both possible projections
       if (focal_length->getDouble() < 0) {
         focal_length->setDouble(-focal_length->getDouble());
         q_field2cam = q_rotate180 * q_field2cam;
         q0->setDouble(q_field2cam.x);
         q1->setDouble(q_field2cam.y);
         q2->setDouble(q_field2cam.z);
         q3->setDouble(q_field2cam.w);
       }
       if (old_chisqr - chisqr < 0.001) {
         stop_optimization = true;
       } else {
         lambda /= 10;
         convergence_counter = 0;
       }
       old_chisqr = chisqr;
 #ifndef NDEBUG
       std::cerr << "Chi-square: "<< old_chisqr << std::endl;
 #endif
     } else {
       lambda *= 10;
       if (convergence_counter++ > 10) stop_optimization = true;
     }
     if ((GetTimeSec() - t_start) >
         additional_calibration_information->convergence_timeout->getDouble()) {
       stop_optimization=true;
     }
   }
 // Debug output starts here
 #ifndef NDEBUG
   // Estimated parameters
   std::cerr << "Estimated parameters: " << std::endl;
   std::cerr << focal_length->getDouble() << " "
             << principal_point_x->getDouble() << " "
             << principal_point_y->getDouble() << " " << distortion->getDouble()
             << std::endl;
   std::cerr << q0->getDouble() << " " << q1->getDouble() << " "
             << q2->getDouble() << " " << q3->getDouble() << std::endl;
   std::cerr << tx->getDouble() << " " << ty->getDouble() << " "
             << tz->getDouble() <<  std::endl;
   std::cerr << "alphas: " << p_alpha << std::endl;
   // Testing calibration by projecting the four field points into the image
   // plane and calculate MSE
   std::vector<GVector::vector3d<double> >::iterator it_p_f  = p_f.begin();
   std::vector<GVector::vector2d<double> >::iterator it_p_i  = p_i.begin();
   double corner_x(0);
   double corner_y(0);
   for (; it_p_f != p_f.end(); it_p_f++, it_p_i++) {
     GVector::vector2d<double> proj_p;
     field2image(*it_p_f, proj_p);
     GVector::vector3d<double> some_point;
     image2field(some_point,proj_p, 150);
     std::cerr << "Point in world: ("<< it_p_f->x << "," << it_p_f->y << ","
               << it_p_f->z  << ")" << std::endl;
     std::cerr << "Point should be at (" << it_p_i->x << "," << it_p_i->y
               << ") and is projected at (" << proj_p.x << "," << proj_p.y <<")"
               << std::endl;
     corner_x += (proj_p.x - it_p_i->x) * (proj_p.x - it_p_i->x);
     corner_y += (proj_p.y - it_p_i->y) * (proj_p.y - it_p_i->y);
   }
   std::cerr << "RESIDUAL CORNER POINTS: " << sqrt(corner_x/4) << " "
             << sqrt(corner_y/4) << std::endl;
  if (cal_type & FULL_ESTIMATION) {
   // Testing calibration by projecting the points on the lines into the image
   // plane and calculate MSE
   double line_x(0);
   double line_y(0);
   std::vector<CalibrationData>::iterator ls_it = calibrationSegments.begin();
   int i = 0;
   for (; ls_it != calibrationSegments.end(); ls_it++) {
     std::vector< std::pair<GVector::vector2d<double>,bool> >::iterator pts_it =
         (*ls_it).imgPts.begin();
     for (; pts_it != (*ls_it).imgPts.end(); pts_it++) {
       if (pts_it->second) {
         GVector::vector2d<double> proj_p;
         double alpha = p_alpha(i);
         GVector::vector3d<double >alpha_point;
         if (ls_it->straightLine) {
           alpha_point = alpha * (*ls_it).p1 + (1 - alpha) * (*ls_it).p2;
         } else {
           double theta = alpha * (*ls_it).theta1 + (1.0 - alpha) *
               (*ls_it).theta2;
           alpha_point = ls_it->center +
               ls_it->radius*GVector::vector3d<double>(
                   cos(theta),sin(theta),0.0);
         }
         field2image(alpha_point, proj_p, p);
         line_x += (proj_p.x - pts_it->first.x) * (proj_p.x - pts_it->first.x);
         line_y += (proj_p.y - pts_it->first.y) * (proj_p.y - pts_it->first.y);
         i++;
       }
     }
   }
   if (i != 0) {
     std::cerr << "RESIDUAL LINE POINTS: " << sqrt(line_x/(double)i) << " "
               << sqrt(line_y/(double)i) << std::endl;
   }
  }
 #endif
 }
void CameraParameters::do_calibration (int cal_type)
Definition at line 347 of file camera_calibration.cpp.
References additional_calibration_information, calibrate(), CameraParameters::AdditionalCalibrationInformation::control_point_field_xs, CameraParameters::AdditionalCalibrationInformation::control_point_field_ys, CameraParameters::AdditionalCalibrationInformation::control_point_image_xs, CameraParameters::AdditionalCalibrationInformation::control_point_image_ys, VarTypes::VarDoubleVal::getDouble(), velocity.pid_::i, and CameraParameters::AdditionalCalibrationInformation::kNumControlPoints.
Referenced by CameraParameters::CalibrationData::CalibrationData(), CameraCalibrationWidget::is_clicked_full(), and CameraCalibrationWidget::is_clicked_initial().
{
   std::vector<GVector::vector3d<double> > p_f;
   std::vector<GVector::vector2d<double> > p_i;
   AdditionalCalibrationInformation* aci = additional_calibration_information;
   for (int i = 0; i < AdditionalCalibrationInformation::kNumControlPoints;
       ++i) {
     p_i.push_back(GVector::vector2d<double>(
       aci->control_point_image_xs[i]->getDouble(),
       aci->control_point_image_ys[i]->getDouble()));
     p_f.push_back(GVector::vector3d<double>(
       aci->control_point_field_xs[i]->getDouble(),
       aci->control_point_field_ys[i]->getDouble(), 0.0));
   }
   calibrate(p_f, p_i, cal_type);
 }
void CameraParameters::field2image (const GVector::vector3d< double > & p_f, GVector::vector2d< double > & p_i) const
Definition at line 174 of file camera_calibration.cpp.
References focal_length, VarTypes::VarDoubleVal::getDouble(), Quaternion< num >::norm(), principal_point_x, principal_point_y, q0, q1, q2, q3, radialDistortion(), Quaternion< num >::rotateVectorByQuaternion(), tx, ty, tz, GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
Referenced by calc_chisqr(), calibrate(), PluginCameraCalibration::detectEdgesOnSingleArc(), PluginCameraCalibration::detectEdgesOnSingleLine(), PluginVisualize::DrawEdgeTangent(), PluginVisualize::drawFieldArc(), and PluginVisualize::drawFieldLine().
{
   Quaternion<double> q_field2cam = Quaternion<double>(
       q0->getDouble(),q1->getDouble(),q2->getDouble(),q3->getDouble());
   q_field2cam.norm();
   GVector::vector3d<double> translation = GVector::vector3d<double>(
       tx->getDouble(),ty->getDouble(),tz->getDouble());
   // First transform the point from the field into the coordinate system of the
   // camera
   GVector::vector3d<double> p_c =
       q_field2cam.rotateVectorByQuaternion(p_f) + translation;
   GVector::vector2d<double> p_un =
       GVector::vector2d<double>(p_c.x/p_c.z, p_c.y/p_c.z);
   // Apply distortion
   GVector::vector2d<double> p_d;
   radialDistortion(p_un,p_d);
   // Then project from the camera coordinate system onto the image plane using
   // the instrinsic parameters
   p_i = focal_length->getDouble() * p_d +
       GVector::vector2d<double>(principal_point_x->getDouble(),
                                 principal_point_y->getDouble());
 }
void CameraParameters::field2image (GVector::vector3d< double > & p_f, GVector::vector2d< double > & p_i, Eigen::VectorXd & p)
Definition at line 201 of file camera_calibration.cpp.
References DIST, distortion, focal_length, FOCAL_LENGTH, VarTypes::VarDoubleVal::getDouble(), GVector::vector3d< num >::length(), GVector::vector3d< num >::norm(), Quaternion< num >::norm(), PP_X, PP_Y, principal_point_x, principal_point_y, q0, q1, q2, q3, Q_1, Q_2, Q_3, radialDistortion(), Quaternion< num >::setAxis(), T_1, T_2, T_3, tx, ty, tz, GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
                       {
   Quaternion<double> q_field2cam = Quaternion<double>(
       q0->getDouble(),q1->getDouble(),q2->getDouble(),q3->getDouble());
   q_field2cam.norm();
   GVector::vector3d<double> translation = GVector::vector3d<double>(
       tx->getDouble(),ty->getDouble(),tz->getDouble());
   GVector::vector3d<double> aa_diff(p[Q_1], p[Q_2], p[Q_3]);
   GVector::vector3d<double> t_diff(p[T_1], p[T_2], p[T_3]);
   // Create a quaternion out of the 3D rotational representation
   Quaternion<double> q_diff;
   q_diff.setAxis(aa_diff.norm(), aa_diff.length());
   // First transform the point from the field into the coordinate system of the
   // camera
   GVector::vector3d<double> p_c =
       (q_diff * q_field2cam ).rotateVectorByQuaternion(p_f) + translation +
       t_diff;
   GVector::vector2d<double> p_un =
       GVector::vector2d<double>(p_c.x/p_c.z, p_c.y/p_c.z);
   // Apply distortion
   GVector::vector2d<double> p_d;
   radialDistortion(p_un,p_d,distortion->getDouble() + p[DIST]);
   // Then project from the camera coordinate system onto the image plane using
   // the instrinsic parameters
   p_i = (focal_length->getDouble() + p[FOCAL_LENGTH]) * p_d +
       GVector::vector2d<double>(principal_point_x->getDouble() + p[PP_X],
                                 principal_point_y->getDouble() + p[PP_Y]);
 }
void CameraParameters::fromProtoBuffer (const SSL_GeometryCameraCalibration & buffer)
Definition at line 94 of file camera_calibration.cpp.
References distortion, focal_length, principal_point_x, principal_point_y, q0, q1, q2, q3, VarTypes::VarDouble::setDouble(), tx, ty, and tz.
{
   focal_length->setDouble(buffer.focal_length());
   principal_point_x->setDouble(buffer.principal_point_x());
   principal_point_y->setDouble(buffer.principal_point_y());
   distortion->setDouble(buffer.distortion());
   q0->setDouble(buffer.q0());
   q1->setDouble(buffer.q1());
   q2->setDouble(buffer.q2());
   q3->setDouble(buffer.q3());
   tx->setDouble(buffer.tx());
   ty->setDouble(buffer.ty());
   tz->setDouble(buffer.tz());
 }
GVector::vector3d< double > CameraParameters::getWorldLocation ()
Definition at line 84 of file camera_calibration.cpp.
References VarTypes::VarDoubleVal::getDouble(), Quaternion< num >::invert(), q0, q1, q2, q3, Quaternion< num >::rotateVectorByQuaternion(), Quaternion< num >::set(), tx, ty, and tz.
Referenced by PluginCameraCalibration::detectEdgesOnSingleArc(), and PluginCameraCalibration::detectEdgesOnSingleLine().
{
   Quaternion<double> q;
   q.set(q0->getDouble(),q1->getDouble(),q2->getDouble(),q3->getDouble());
   q.invert();
   GVector::vector3d<double> v_in(tx->getDouble(),ty->getDouble(),tz->getDouble());
   v_in = (-(v_in));
   GVector::vector3d<double> v_out = q.rotateVectorByQuaternion(v_in);
   return v_out;
 }
void CameraParameters::image2field (GVector::vector3d< double > & p_f, const GVector::vector2d< double > & p_i, double z) const
Definition at line 236 of file camera_calibration.cpp.
References focal_length, VarTypes::VarDoubleVal::getDouble(), GVector::vector3d< num >::norm(), Quaternion< num >::norm(), principal_point_x, principal_point_y, q0, q1, q2, q3, radialDistortionInv(), GVector::ray_plane_intersect(), t, tx, ty, tz, v, GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
Referenced by calibrate(), CMPattern::MultiPatternModel::findPattern(), CMPattern::TeamDetector::findRobotsByModel(), CMPattern::TeamDetector::findRobotsByTeamMarkerOnly(), CMPattern::TeamDetector::getRegionArea(), and PluginDetectBalls::process().
                     {
   // Undo scaling and offset
   GVector::vector2d<double> p_d(
       (p_i.x - principal_point_x->getDouble()) / focal_length->getDouble(),
       (p_i.y - principal_point_y->getDouble()) / focal_length->getDouble());
   // Compensate for distortion (undistort)
   GVector::vector2d<double> p_un;
   radialDistortionInv(p_un,p_d);
   // Now we got a ray on the z axis
   GVector::vector3d<double> v(p_un.x, p_un.y, 1);
   // Transform this ray into world coordinates
   Quaternion<double> q_field2cam = Quaternion<double>(
       q0->getDouble(),q1->getDouble(),q2->getDouble(),q3->getDouble());
   q_field2cam.norm();
   GVector::vector3d<double> translation =
     GVector::vector3d<double>(tx->getDouble(),ty->getDouble(),tz->getDouble());
   Quaternion<double> q_field2cam_inv = q_field2cam;
   q_field2cam_inv.invert();
   GVector::vector3d<double> v_in_w =
       q_field2cam_inv.rotateVectorByQuaternion(v);
   GVector::vector3d<double> zero_in_w =
       q_field2cam_inv.rotateVectorByQuaternion(
           GVector::vector3d<double>(0,0,0) - translation);
   // Compute the the point where the rays intersects the field
   double t = GVector::ray_plane_intersect(
       GVector::vector3d<double>(0,0,z), GVector::vector3d<double>(0,0,1).norm(),
       zero_in_w, v_in_w.norm());
   // Set p_f
   p_f = zero_in_w + v_in_w.norm() * t;
 }
double CameraParameters::radialDistortion (double ru) const
Definition at line 123 of file camera_calibration.cpp.
References distortion, and VarTypes::VarDoubleVal::getDouble().
Referenced by field2image(), and radialDistortion().
{
   if ((distortion->getDouble())<=DBL_MIN)
     return ru;
   double rd = 0;
   double a = distortion->getDouble();
   double b = -9.0*a*a*ru + a*sqrt(a*(12.0 + 81.0*a*ru*ru));
   b = (b < 0.0) ? (-pow(b, 1.0 / 3.0)) : pow(b, 1.0 / 3.0);
   rd = pow(2.0 / 3.0, 1.0 / 3.0) / b -
       b / (pow(2.0 * 3.0 * 3.0, 1.0 / 3.0) * a);
   return rd;
 }
void CameraParameters::radialDistortion (const GVector::vector2d< double > pu, GVector::vector2d< double > & pd) const
Definition at line 159 of file camera_calibration.cpp.
References GVector::vector2d< num >::length(), GVector::vector2d< num >::norm(), and radialDistortion().
{
   double rd = radialDistortion(pu.length());
   pd = pu;
   pd = pd.norm(rd);
 }
double CameraParameters::radialDistortion (double ru, double dist) const
Definition at line 135 of file camera_calibration.cpp.
References GVector::dist().
{
   if (dist<=DBL_MIN)
     return ru;
   double rd = 0;
   double a = dist;
   double b = -9.0*a*a*ru + a*sqrt(a*(12.0 + 81.0*a*ru*ru));
   b = (b < 0.0) ? (-pow(b, 1.0 / 3.0)) : pow(b, 1.0 / 3.0);
   rd = pow(2.0 / 3.0, 1.0 / 3.0) / b -
       b / (pow(2.0 * 3.0 * 3.0, 1.0 / 3.0) * a);
   return rd;
 }
void CameraParameters::radialDistortion (const GVector::vector2d< double > pu, GVector::vector2d< double > & pd, double dist) const
Definition at line 166 of file camera_calibration.cpp.
References GVector::dist(), GVector::vector2d< num >::length(), GVector::vector2d< num >::norm(), and radialDistortion().
{
   double rd = radialDistortion(pu.length(), dist);
   pd = pu;
   pd = pd.norm(rd);
 }
double CameraParameters::radialDistortionInv (double rd) const
Definition at line 147 of file camera_calibration.cpp.
References distortion, and VarTypes::VarDoubleVal::getDouble().
Referenced by image2field(), and radialDistortionInv().
{
   double ru = rd*(1.0+rd*rd*distortion->getDouble());
   return ru;
 }
void CameraParameters::radialDistortionInv (GVector::vector2d< double > & pu, const GVector::vector2d< double > & pd) const
Definition at line 152 of file camera_calibration.cpp.
References GVector::vector2d< num >::length(), GVector::vector2d< num >::norm(), and radialDistortionInv().
{
   double ru = radialDistortionInv(pd.length());
   pu = pd;
   pu = pu.norm(ru);
 }
void CameraParameters::reset ()
Definition at line 366 of file camera_calibration.cpp.
References distortion, focal_length, principal_point_x, principal_point_y, q0, q1, q2, q3, VarTypes::VarDouble::resetToDefault(), tx, ty, and tz.
Referenced by CameraParameters::CalibrationData::CalibrationData(), and CameraCalibrationWidget::is_clicked_reset().
{
   focal_length->resetToDefault();
   principal_point_x->resetToDefault();
   principal_point_y->resetToDefault();
   distortion->resetToDefault();
   tx->resetToDefault();
   ty->resetToDefault();
   tz->resetToDefault();
   q0->resetToDefault();
   q1->resetToDefault();
   q2->resetToDefault();
   q3->resetToDefault();
 }
void CameraParameters::toProtoBuffer (SSL_GeometryCameraCalibration & buffer, int camera_id) const
Definition at line 53 of file camera_calibration.cpp.
References distortion, focal_length, VarTypes::VarDoubleVal::getDouble(), Quaternion< num >::invert(), principal_point_x, principal_point_y, q0, q1, q2, q3, Quaternion< num >::rotateVectorByQuaternion(), Quaternion< num >::set(), tx, ty, tz, GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
{
   buffer.set_focal_length(focal_length->getDouble());
   buffer.set_principal_point_x(principal_point_x->getDouble());
   buffer.set_principal_point_y(principal_point_y->getDouble());
   buffer.set_distortion(distortion->getDouble());
   buffer.set_q0(q0->getDouble());
   buffer.set_q1(q1->getDouble());
   buffer.set_q2(q2->getDouble());
   buffer.set_q3(q3->getDouble());
   buffer.set_tx(tx->getDouble());
   buffer.set_ty(ty->getDouble());
   buffer.set_tz(tz->getDouble());
   buffer.set_camera_id(camera_id);
   //--Set derived parameters:
   //compute camera world coordinates:
   Quaternion<double> q;
   q.set(q0->getDouble(),q1->getDouble(),q2->getDouble(),q3->getDouble());
   q.invert();
   GVector::vector3d<double> v_in(tx->getDouble(),ty->getDouble(),tz->getDouble());
   v_in=(-(v_in));
   GVector::vector3d<double> v_out = q.rotateVectorByQuaternion(v_in);
   buffer.set_derived_camera_world_tx(v_out.x);
   buffer.set_derived_camera_world_ty(v_out.y);
   buffer.set_derived_camera_world_tz(v_out.z);
 }
Field Documentation
AdditionalCalibrationInformation* CameraParameters::additional_calibration_information
Definition at line 79 of file camera_calibration.h.
Referenced by calc_chisqr(), calibrate(), CameraCalibrationWidget::CameraCalibrationWidget(), CameraParameters(), PluginCameraCalibration::detectEdges(), PluginCameraCalibration::detectEdgesOnSingleArc(), PluginCameraCalibration::detectEdgesOnSingleLine(), do_calibration(), PluginVisualize::DrawCameraCalibration(), CameraCalibrationWidget::line_search_slider_changed(), PluginCameraCalibration::mousePressEvent(), PluginCameraCalibration::PluginCameraCalibration(), CameraCalibrationWidget::set_slider_from_vars(), and ~CameraParameters().
std::vector<CalibrationData> CameraParameters::calibrationSegments
Definition at line 71 of file camera_calibration.h.
Referenced by calc_chisqr(), calibrate(), PluginCameraCalibration::detectEdges(), PluginCameraCalibration::detectEdgesOnSingleArc(), PluginCameraCalibration::detectEdgesOnSingleLine(), and PluginVisualize::DrawDetectedEdges().
const int CameraParameters::camera_index
Definition at line 55 of file camera_calibration.h.
Referenced by CameraParameters().
VarDouble* CameraParameters::distortion
Definition at line 59 of file camera_calibration.h.
Referenced by addSettingsToList(), calibrate(), CameraCalibrationWidget::CameraCalibrationWidget(), CameraParameters(), CameraCalibrationWidget::distortion_slider_changed(), field2image(), fromProtoBuffer(), radialDistortion(), radialDistortionInv(), reset(), CameraCalibrationWidget::set_slider_from_vars(), toProtoBuffer(), and ~CameraParameters().
VarDouble* CameraParameters::focal_length
Definition at line 56 of file camera_calibration.h.
Referenced by addSettingsToList(), calibrate(), CameraParameters(), field2image(), fromProtoBuffer(), image2field(), reset(), toProtoBuffer(), and ~CameraParameters().
Eigen::VectorXd CameraParameters::p_alpha
Definition at line 73 of file camera_calibration.h.
Referenced by calc_chisqr(), and calibrate().
std::vector<int> CameraParameters::p_to_est
Definition at line 121 of file camera_calibration.h.
Referenced by calibrate().
VarDouble* CameraParameters::principal_point_x
Definition at line 57 of file camera_calibration.h.
Referenced by addSettingsToList(), calibrate(), CameraParameters(), PluginVisualize::DrawCameraCalibration(), field2image(), fromProtoBuffer(), image2field(), reset(), toProtoBuffer(), and ~CameraParameters().
VarDouble* CameraParameters::principal_point_y
Definition at line 58 of file camera_calibration.h.
Referenced by addSettingsToList(), calibrate(), CameraParameters(), PluginVisualize::DrawCameraCalibration(), field2image(), fromProtoBuffer(), image2field(), reset(), toProtoBuffer(), and ~CameraParameters().
VarDouble* CameraParameters::q0
Definition at line 62 of file camera_calibration.h.
Referenced by addSettingsToList(), calibrate(), CameraParameters(), field2image(), fromProtoBuffer(), getWorldLocation(), image2field(), reset(), toProtoBuffer(), and ~CameraParameters().
VarDouble* CameraParameters::q1
Definition at line 63 of file camera_calibration.h.
Referenced by addSettingsToList(), calibrate(), CameraParameters(), field2image(), fromProtoBuffer(), getWorldLocation(), image2field(), reset(), toProtoBuffer(), and ~CameraParameters().
VarDouble* CameraParameters::q2
Definition at line 64 of file camera_calibration.h.
Referenced by addSettingsToList(), calibrate(), CameraParameters(), field2image(), fromProtoBuffer(), getWorldLocation(), image2field(), reset(), toProtoBuffer(), and ~CameraParameters().
VarDouble* CameraParameters::q3
Definition at line 65 of file camera_calibration.h.
Referenced by addSettingsToList(), calibrate(), CameraParameters(), field2image(), fromProtoBuffer(), getWorldLocation(), image2field(), reset(), toProtoBuffer(), and ~CameraParameters().
Quaternion<double> CameraParameters::q_rotate180
Definition at line 74 of file camera_calibration.h.
Referenced by calibrate(), and CameraParameters().
VarDouble* CameraParameters::tx
Definition at line 67 of file camera_calibration.h.
Referenced by addSettingsToList(), calibrate(), CameraParameters(), field2image(), fromProtoBuffer(), getWorldLocation(), image2field(), reset(), toProtoBuffer(), and ~CameraParameters().
VarDouble* CameraParameters::ty
Definition at line 68 of file camera_calibration.h.
Referenced by addSettingsToList(), calibrate(), CameraParameters(), field2image(), fromProtoBuffer(), getWorldLocation(), image2field(), reset(), toProtoBuffer(), and ~CameraParameters().
VarDouble* CameraParameters::tz
Definition at line 69 of file camera_calibration.h.
Referenced by addSettingsToList(), calibrate(), CameraCalibrationWidget::CameraCalibrationWidget(), CameraCalibrationWidget::cameraheight_slider_changed(), CameraParameters(), field2image(), fromProtoBuffer(), getWorldLocation(), image2field(), reset(), CameraCalibrationWidget::set_slider_from_vars(), toProtoBuffer(), and ~CameraParameters().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/util/camera_calibration.h
ssl-vision/src/shared/util/camera_calibration.cpp