Documentation: grSim_Packet Class Reference
grSim_Packet Class Reference
#include <grSim_Packet.pb.h>
Public Member Functions
grSim_Packet ()
virtual ~grSim_Packet ()
grSim_Packet (const grSim_Packet &from)
grSim_Packet & operator= (const grSim_Packet &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (grSim_Packet *other)
grSim_Packet * New () const PROTOBUF_FINAL
grSim_Packet * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const grSim_Packet &from)
void MergeFrom (const grSim_Packet &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_commands () const
void clear_commands ()
const ::grSim_Commands & commands () const
::grSim_Commands * mutable_commands ()
::grSim_Commands * release_commands ()
void set_allocated_commands (::grSim_Commands *commands)
bool has_replacement () const
void clear_replacement ()
const ::grSim_Replacement & replacement () const
::grSim_Replacement * mutable_replacement ()
::grSim_Replacement * release_replacement ()
void set_allocated_replacement (::grSim_Replacement *replacement)
bool has_debuginfo () const
void clear_debuginfo ()
const ::sslDebug_Data & debuginfo () const
::sslDebug_Data * mutable_debuginfo ()
::sslDebug_Data * release_debuginfo ()
void set_allocated_debuginfo (::sslDebug_Data *debuginfo)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const grSim_Packet & default_instance ()
static const grSim_Packet * internal_default_instance ()
Static Public Attributes
static const int kCommandsFieldNumber = 1
static const int kReplacementFieldNumber = 2
static const int kDebuginfoFieldNumber = 3
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (grSim_Packet *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_commands ()
void clear_has_commands ()
void set_has_replacement ()
void clear_has_replacement ()
void set_has_debuginfo ()
void clear_has_debuginfo ()
friendconst::google::protobuf::uint32 * protobuf_Offsets_grSim_5fPacket_2eproto ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::grSim_Commands * commands_
::grSim_Replacement * replacement_
::sslDebug_Data * debuginfo_
Friends
void protobuf_InitDefaults_grSim_5fPacket_2eproto_impl ()
void protobuf_AddDesc_grSim_5fPacket_2eproto_impl ()
void protobuf_ShutdownFile_grSim_5fPacket_2eproto ()
Detailed Description
Definition at line 74 of file grSim_Packet.pb.h.
Constructor & Destructor Documentation
grSim_Packet::grSim_Packet ()
virtual grSim_Packet::~grSim_Packet () virtual
grSim_Packet::grSim_Packet (const grSim_Packet & from)
Member Function Documentation
size_t grSim_Packet::ByteSizeLong () const
Referenced by New().
void grSim_Packet::Clear ()
Referenced by New().
void grSim_Packet::clear_commands () inline
Definition at line 214 of file grSim_Packet.pb.h.
References clear_has_commands(), and commands_.
Referenced by MaybeArenaPtr().
{
   if (commands_ != NULL) commands_->::grSim_Commands::Clear();
   clear_has_commands();
 }
void grSim_Packet::clear_debuginfo () inline
Definition at line 304 of file grSim_Packet.pb.h.
References clear_has_debuginfo(), and debuginfo_.
{
   if (debuginfo_ != NULL) debuginfo_->::sslDebug_Data::Clear();
   clear_has_debuginfo();
 }
void grSim_Packet::clear_has_commands () inline private
Definition at line 211 of file grSim_Packet.pb.h.
References _has_bits_.
Referenced by clear_commands(), release_commands(), and set_allocated_commands().
{
   _has_bits_[0] &= ~0x00000001u;
 }
void grSim_Packet::clear_has_debuginfo () inline private
Definition at line 301 of file grSim_Packet.pb.h.
References _has_bits_.
Referenced by clear_debuginfo(), release_debuginfo(), and set_allocated_debuginfo().
{
   _has_bits_[0] &= ~0x00000004u;
 }
void grSim_Packet::clear_has_replacement () inline private
Definition at line 256 of file grSim_Packet.pb.h.
References _has_bits_.
Referenced by clear_replacement(), release_replacement(), and set_allocated_replacement().
{
   _has_bits_[0] &= ~0x00000002u;
 }
void grSim_Packet::clear_replacement () inline
Definition at line 259 of file grSim_Packet.pb.h.
References clear_has_replacement(), and replacement_.
{
   if (replacement_ != NULL) replacement_->::grSim_Replacement::Clear();
   clear_has_replacement();
 }
const ::grSim_Commands & grSim_Packet::commands () const inline
Definition at line 218 of file grSim_Packet.pb.h.
References commands_, and grSim_Commands::internal_default_instance().
Referenced by SSLWorld::recvActions(), and set_allocated_commands().
{
   // @@protoc_insertion_point(field_get:grSim_Packet.commands)
   return commands_ != NULL ? *commands_
                          : *::grSim_Commands::internal_default_instance();
 }
void grSim_Packet::CopyFrom (const ::google::protobuf::Message & from)
Referenced by New(), and operator=().
void grSim_Packet::CopyFrom (const grSim_Packet & from)
const ::sslDebug_Data & grSim_Packet::debuginfo () const inline
Definition at line 308 of file grSim_Packet.pb.h.
References debuginfo_, and sslDebug_Data::internal_default_instance().
Referenced by set_allocated_debuginfo().
{
   // @@protoc_insertion_point(field_get:grSim_Packet.debuginfo)
   return debuginfo_ != NULL ? *debuginfo_
                          : *::sslDebug_Data::internal_default_instance();
 }
static const grSim_Packet& grSim_Packet::default_instance () static
Referenced by mutable_unknown_fields().
static const ::google::protobuf::Descriptor* grSim_Packet::descriptor () static
Referenced by mutable_unknown_fields().
inline ::google::protobuf::Arena* grSim_Packet::GetArenaNoVirtual () const inline private
Definition at line 134 of file grSim_Packet.pb.h.
{
     return NULL;
   }
int grSim_Packet::GetCachedSize () const inline
Definition at line 127 of file grSim_Packet.pb.h.
References _cached_size_, InternalSwap(), SetCachedSize(), SharedCtor(), and SharedDtor().
 { return _cached_size_; }
::google::protobuf::Metadata grSim_Packet::GetMetadata () const
Referenced by MaybeArenaPtr().
bool grSim_Packet::has_commands () const inline
Definition at line 205 of file grSim_Packet.pb.h.
References _has_bits_.
Referenced by MaybeArenaPtr(), and SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool grSim_Packet::has_debuginfo () const inline
Definition at line 295 of file grSim_Packet.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool grSim_Packet::has_replacement () const inline
Definition at line 250 of file grSim_Packet.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
static const grSim_Packet* grSim_Packet::internal_default_instance () inline static
Definition at line 97 of file grSim_Packet.pb.h.
References _grSim_Packet_default_instance_, and Swap().
{
     return reinterpret_cast<const grSim_Packet*>(
                &_grSim_Packet_default_instance_);
   }
::google::protobuf::uint8* grSim_Packet::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
Referenced by New(), and SerializeWithCachedSizesToArray().
void grSim_Packet::InternalSwap (grSim_Packet * other) private
Referenced by GetCachedSize().
bool grSim_Packet::IsInitialized () const
Referenced by New().
void* grSim_Packet::MaybeArenaPtr () const inline private
Definition at line 137 of file grSim_Packet.pb.h.
References clear_commands(), GetMetadata(), and has_commands().
{
     return NULL;
   }
void grSim_Packet::MergeFrom (const ::google::protobuf::Message & from)
Referenced by New().
void grSim_Packet::MergeFrom (const grSim_Packet & from)
bool grSim_Packet::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Referenced by New().
grSim_Commands * grSim_Packet::mutable_commands () inline
Definition at line 223 of file grSim_Packet.pb.h.
References commands_, and set_has_commands().
Referenced by Callback(), CallbackCmd(), and MainWindow::sendPacket().
{
   set_has_commands();
   if (commands_ == NULL) {
     commands_ = new ::grSim_Commands;
   }
   // @@protoc_insertion_point(field_mutable:grSim_Packet.commands)
   return commands_;
 }
sslDebug_Data * grSim_Packet::mutable_debuginfo () inline
Definition at line 313 of file grSim_Packet.pb.h.
References debuginfo_, and set_has_debuginfo().
Referenced by Callback(), and CallbackDbg().
{
   set_has_debuginfo();
   if (debuginfo_ == NULL) {
     debuginfo_ = new ::sslDebug_Data;
   }
   // @@protoc_insertion_point(field_mutable:grSim_Packet.debuginfo)
   return debuginfo_;
 }
grSim_Replacement * grSim_Packet::mutable_replacement () inline
Definition at line 268 of file grSim_Packet.pb.h.
References replacement_, and set_has_replacement().
{
   set_has_replacement();
   if (replacement_ == NULL) {
     replacement_ = new ::grSim_Replacement;
   }
   // @@protoc_insertion_point(field_mutable:grSim_Packet.replacement)
   return replacement_;
 }
inline ::google::protobuf::UnknownFieldSet* grSim_Packet::mutable_unknown_fields () inline
Definition at line 90 of file grSim_Packet.pb.h.
References _internal_metadata_, default_instance(), and descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
grSim_Packet* grSim_Packet::New () const inline
Definition at line 106 of file grSim_Packet.pb.h.
References ByteSizeLong(), Clear(), CopyFrom(), InternalSerializeWithCachedSizesToArray(), IsInitialized(), MergeFrom(), MergePartialFromCodedStream(), New(), SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
grSim_Packet* grSim_Packet::New (::google::protobuf::Arena * arena) const
grSim_Packet& grSim_Packet::operator= (const grSim_Packet & from) inline
Definition at line 81 of file grSim_Packet.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* grSim_Packet::protobuf_Offsets_grSim_5fPacket_2eproto () private
grSim_Commands * grSim_Packet::release_commands () inline
Definition at line 231 of file grSim_Packet.pb.h.
References clear_has_commands(), and commands_.
{
   // @@protoc_insertion_point(field_release:grSim_Packet.commands)
   clear_has_commands();
   ::grSim_Commands* temp = commands_;
   commands_ = NULL;
   return temp;
 }
sslDebug_Data * grSim_Packet::release_debuginfo () inline
Definition at line 321 of file grSim_Packet.pb.h.
References clear_has_debuginfo(), and debuginfo_.
{
   // @@protoc_insertion_point(field_release:grSim_Packet.debuginfo)
   clear_has_debuginfo();
   ::sslDebug_Data* temp = debuginfo_;
   debuginfo_ = NULL;
   return temp;
 }
grSim_Replacement * grSim_Packet::release_replacement () inline
Definition at line 276 of file grSim_Packet.pb.h.
References clear_has_replacement(), and replacement_.
{
   // @@protoc_insertion_point(field_release:grSim_Packet.replacement)
   clear_has_replacement();
   ::grSim_Replacement* temp = replacement_;
   replacement_ = NULL;
   return temp;
 }
const ::grSim_Replacement & grSim_Packet::replacement () const inline
Definition at line 263 of file grSim_Packet.pb.h.
References grSim_Replacement::internal_default_instance(), and replacement_.
Referenced by SSLWorld::recvActions(), and set_allocated_replacement().
{
   // @@protoc_insertion_point(field_get:grSim_Packet.replacement)
   return replacement_ != NULL ? *replacement_
                          : *::grSim_Replacement::internal_default_instance();
 }
void grSim_Packet::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Referenced by New().
::google::protobuf::uint8* grSim_Packet::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 123 of file grSim_Packet.pb.h.
References InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void grSim_Packet::set_allocated_commands (::grSim_Commands * commands) inline
Definition at line 238 of file grSim_Packet.pb.h.
References clear_has_commands(), commands(), commands_, and set_has_commands().
{
   delete commands_;
   commands_ = commands;
   if (commands) {
     set_has_commands();
   } else {
     clear_has_commands();
   }
   // @@protoc_insertion_point(field_set_allocated:grSim_Packet.commands)
 }
void grSim_Packet::set_allocated_debuginfo (::sslDebug_Data * debuginfo) inline
Definition at line 328 of file grSim_Packet.pb.h.
References clear_has_debuginfo(), debuginfo(), debuginfo_, and set_has_debuginfo().
{
   delete debuginfo_;
   debuginfo_ = debuginfo;
   if (debuginfo) {
     set_has_debuginfo();
   } else {
     clear_has_debuginfo();
   }
   // @@protoc_insertion_point(field_set_allocated:grSim_Packet.debuginfo)
 }
void grSim_Packet::set_allocated_replacement (::grSim_Replacement * replacement) inline
Definition at line 283 of file grSim_Packet.pb.h.
References clear_has_replacement(), replacement(), replacement_, and set_has_replacement().
{
   delete replacement_;
   replacement_ = replacement;
   if (replacement) {
     set_has_replacement();
   } else {
     clear_has_replacement();
   }
   // @@protoc_insertion_point(field_set_allocated:grSim_Packet.replacement)
 }
void grSim_Packet::set_has_commands () inline private
Definition at line 208 of file grSim_Packet.pb.h.
References _has_bits_.
Referenced by mutable_commands(), and set_allocated_commands().
{
   _has_bits_[0] |= 0x00000001u;
 }
void grSim_Packet::set_has_debuginfo () inline private
Definition at line 298 of file grSim_Packet.pb.h.
References _has_bits_.
Referenced by mutable_debuginfo(), and set_allocated_debuginfo().
{
   _has_bits_[0] |= 0x00000004u;
 }
void grSim_Packet::set_has_replacement () inline private
Definition at line 253 of file grSim_Packet.pb.h.
References _has_bits_.
Referenced by mutable_replacement(), and set_allocated_replacement().
{
   _has_bits_[0] |= 0x00000002u;
 }
void grSim_Packet::SetCachedSize (int size) const private
Referenced by GetCachedSize().
void grSim_Packet::SharedCtor () private
Referenced by GetCachedSize().
void grSim_Packet::SharedDtor () private
Referenced by GetCachedSize().
void grSim_Packet::Swap (grSim_Packet * other)
Referenced by internal_default_instance().
const ::google::protobuf::UnknownFieldSet& grSim_Packet::unknown_fields () const inline
Definition at line 86 of file grSim_Packet.pb.h.
References _internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
Friends And Related Function Documentation
void protobuf_AddDesc_grSim_5fPacket_2eproto_impl () friend
void protobuf_InitDefaults_grSim_5fPacket_2eproto_impl () friend
void protobuf_ShutdownFile_grSim_5fPacket_2eproto () friend
Field Documentation
int grSim_Packet::_cached_size_ mutable private
Definition at line 186 of file grSim_Packet.pb.h.
Referenced by GetCachedSize().
::google::protobuf::internal::HasBits<1> grSim_Packet::_has_bits_ private
Definition at line 185 of file grSim_Packet.pb.h.
Referenced by clear_has_commands(), clear_has_debuginfo(), clear_has_replacement(), has_commands(), has_debuginfo(), has_replacement(), set_has_commands(), set_has_debuginfo(), and set_has_replacement().
::google::protobuf::internal::InternalMetadataWithArena grSim_Packet::_internal_metadata_ private
Definition at line 184 of file grSim_Packet.pb.h.
Referenced by mutable_unknown_fields(), and unknown_fields().
::grSim_Commands* grSim_Packet::commands_ private
Definition at line 187 of file grSim_Packet.pb.h.
Referenced by clear_commands(), commands(), mutable_commands(), release_commands(), and set_allocated_commands().
::sslDebug_Data* grSim_Packet::debuginfo_ private
Definition at line 189 of file grSim_Packet.pb.h.
Referenced by clear_debuginfo(), debuginfo(), mutable_debuginfo(), release_debuginfo(), and set_allocated_debuginfo().
const int grSim_Packet::kCommandsFieldNumber = 1 static
Definition at line 151 of file grSim_Packet.pb.h.
const int grSim_Packet::kDebuginfoFieldNumber = 3 static
Definition at line 169 of file grSim_Packet.pb.h.
const int grSim_Packet::kReplacementFieldNumber = 2 static
Definition at line 160 of file grSim_Packet.pb.h.
::grSim_Replacement* grSim_Packet::replacement_ private
Definition at line 188 of file grSim_Packet.pb.h.
Referenced by clear_replacement(), mutable_replacement(), release_replacement(), replacement(), and set_allocated_replacement().
The documentation for this class was generated from the following file:
grsim_comm/include/proto/grSim_Packet.pb.h