Documentation: Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder Class Reference
Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
GrSimReplacement.grSim_RobotReplacement getDefaultInstanceForType ()
GrSimReplacement.grSim_RobotReplacement build ()
GrSimReplacement.grSim_RobotReplacement buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (GrSimReplacement.grSim_RobotReplacement other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasX ()
double getX ()
Builder setX (double value)
Builder clearX ()
boolean hasY ()
double getY ()
Builder setY (double value)
Builder clearY ()
boolean hasDir ()
double getDir ()
Builder setDir (double value)
Builder clearDir ()
boolean hasId ()
int getId ()
Builder setId (int value)
Builder clearId ()
boolean hasYellowteam ()
boolean getYellowteam ()
Builder setYellowteam (boolean value)
Builder clearYellowteam ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
GrSimReplacement.grSim_RobotReplacement buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
double x_
double y_
double dir_
int id_
boolean yellowteam_
Detailed Description
Definition at line 288 of file GrSimReplacement.java.
Constructor & Destructor Documentation
Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.Builder () inline private
Definition at line 302 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.Builder (BuilderParent parent) inline private
Definition at line 306 of file GrSimReplacement.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.build () inline
Definition at line 346 of file GrSimReplacement.java.
{
         GrSimReplacement.grSim_RobotReplacement result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 354 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_RobotReplacement.parseDelimitedFrom().
{
         GrSimReplacement.grSim_RobotReplacement result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.buildPartial () inline
Definition at line 364 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.x_.
{
         GrSimReplacement.grSim_RobotReplacement result = new GrSimReplacement.grSim_RobotReplacement(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         result.x_ = x_;
         if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
           to_bitField0_ |= 0x00000002;
         }
         result.y_ = y_;
         if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
           to_bitField0_ |= 0x00000004;
         }
         result.dir_ = dir_;
         if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
           to_bitField0_ |= 0x00000008;
         }
         result.id_ = id_;
         if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
           to_bitField0_ |= 0x00000010;
         }
         result.yellowteam_ = yellowteam_;
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.clear () inline
Definition at line 318 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.clear().
Referenced by Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.clear().
{
         super.clear();
         x_ = 0D;
         bitField0_ = (bitField0_ & ~0x00000001);
         y_ = 0D;
         bitField0_ = (bitField0_ & ~0x00000002);
         dir_ = 0D;
         bitField0_ = (bitField0_ & ~0x00000004);
         id_ = 0;
         bitField0_ = (bitField0_ & ~0x00000008);
         yellowteam_ = false;
         bitField0_ = (bitField0_ & ~0x00000010);
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.clearDir () inline
Definition at line 557 of file GrSimReplacement.java.
{
         bitField0_ = (bitField0_ & ~0x00000004);
         dir_ = 0D;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.clearId () inline
Definition at line 578 of file GrSimReplacement.java.
{
         bitField0_ = (bitField0_ & ~0x00000008);
         id_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.clearX () inline
Definition at line 515 of file GrSimReplacement.java.
{
         bitField0_ = (bitField0_ & ~0x00000001);
         x_ = 0D;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.clearY () inline
Definition at line 536 of file GrSimReplacement.java.
{
         bitField0_ = (bitField0_ & ~0x00000002);
         y_ = 0D;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.clearYellowteam () inline
Definition at line 599 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.initFields().
{
         bitField0_ = (bitField0_ & ~0x00000010);
         yellowteam_ = false;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.clone () inline
Definition at line 333 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.create () inline static private
Definition at line 314 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_RobotReplacement.newBuilder().
{
         return new Builder();
       }
GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.getDefaultInstanceForType () inline
Definition at line 342 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.getDefaultInstance().
{
         return GrSimReplacement.grSim_RobotReplacement.getDefaultInstance();
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.getDescriptor () inline static
Definition at line 292 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.internal_static_grSim_RobotReplacement_descriptor.
{
         return GrSimReplacement.internal_static_grSim_RobotReplacement_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.getDescriptorForType () inline
Definition at line 338 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.getDescriptor().
{
         return GrSimReplacement.grSim_RobotReplacement.getDescriptor();
       }
double Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.getDir () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 548 of file GrSimReplacement.java.
{
         return dir_;
       }
int Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.getId () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 569 of file GrSimReplacement.java.
{
         return id_;
       }
double Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.getX () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 506 of file GrSimReplacement.java.
{
         return x_;
       }
double Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.getY () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 527 of file GrSimReplacement.java.
{
         return y_;
       }
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.getYellowteam () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 590 of file GrSimReplacement.java.
{
         return yellowteam_;
       }
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.hasDir () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 545 of file GrSimReplacement.java.
{
         return ((bitField0_ & 0x00000004) == 0x00000004);
       }
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.hasId () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 566 of file GrSimReplacement.java.
{
         return ((bitField0_ & 0x00000008) == 0x00000008);
       }
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.hasX () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 503 of file GrSimReplacement.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.hasY () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 524 of file GrSimReplacement.java.
{
         return ((bitField0_ & 0x00000002) == 0x00000002);
       }
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.hasYellowteam () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 587 of file GrSimReplacement.java.
{
         return ((bitField0_ & 0x00000010) == 0x00000010);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 297 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.internal_static_grSim_RobotReplacement_fieldAccessorTable.
{
         return GrSimReplacement.internal_static_grSim_RobotReplacement_fieldAccessorTable;
       }
final boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.isInitialized () inline
Definition at line 423 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasDir(), Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasId(), Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasX(), Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasY(), and Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasYellowteam().
{
         if (!hasX()) {
           return false;
         }
         if (!hasY()) {
           return false;
         }
         if (!hasDir()) {
           return false;
         }
         if (!hasId()) {
           return false;
         }
         if (!hasYellowteam()) {
           return false;
         }
         return true;
       }
void Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.maybeForceBuilderInitialization () inline private
Definition at line 310 of file GrSimReplacement.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
         }
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 393 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.clone(), and Protobuf.GrSimReplacement.grSim_RobotReplacement.newBuilder().
{
         if (other instanceof GrSimReplacement.grSim_RobotReplacement) {
           return mergeFrom((GrSimReplacement.grSim_RobotReplacement)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.mergeFrom (GrSimReplacement.grSim_RobotReplacement other) inline
Definition at line 402 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.getDefaultInstance().
{
         if (other == GrSimReplacement.grSim_RobotReplacement.getDefaultInstance()) return this;
         if (other.hasX()) {
           setX(other.getX());
         }
         if (other.hasY()) {
           setY(other.getY());
         }
         if (other.hasDir()) {
           setDir(other.getDir());
         }
         if (other.hasId()) {
           setId(other.getId());
         }
         if (other.hasYellowteam()) {
           setYellowteam(other.getYellowteam());
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 447 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.Builder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 9: {
               bitField0_ |= 0x00000001;
               x_ = input.readDouble();
               break;
             }
             case 17: {
               bitField0_ |= 0x00000002;
               y_ = input.readDouble();
               break;
             }
             case 25: {
               bitField0_ |= 0x00000004;
               dir_ = input.readDouble();
               break;
             }
             case 32: {
               bitField0_ |= 0x00000008;
               id_ = input.readUInt32();
               break;
             }
             case 40: {
               bitField0_ |= 0x00000010;
               yellowteam_ = input.readBool();
               break;
             }
           }
         }
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.setDir (double value) inline
Definition at line 551 of file GrSimReplacement.java.
{
         bitField0_ |= 0x00000004;
         dir_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.setId (int value) inline
Definition at line 572 of file GrSimReplacement.java.
{
         bitField0_ |= 0x00000008;
         id_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.setX (double value) inline
Definition at line 509 of file GrSimReplacement.java.
{
         bitField0_ |= 0x00000001;
         x_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.setY (double value) inline
Definition at line 530 of file GrSimReplacement.java.
{
         bitField0_ |= 0x00000002;
         y_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.setYellowteam (boolean value) inline
Definition at line 593 of file GrSimReplacement.java.
{
         bitField0_ |= 0x00000010;
         yellowteam_ = value;
         onChanged();
         return this;
       }
Field Documentation
int Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.bitField0_ private
Definition at line 499 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.dir_ private
Definition at line 544 of file GrSimReplacement.java.
int Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.id_ private
Definition at line 565 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.x_ private
Definition at line 502 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.y_ private
Definition at line 523 of file GrSimReplacement.java.
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.yellowteam_ private
Definition at line 586 of file GrSimReplacement.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimReplacement.java