Documentation: VarTypes::VarBoolVal Class Reference
VarTypes::VarBoolVal Class Reference
A Vartype for storing booleans.
#include <VarBoolVal.h>
Public Member Functions
VarBoolVal (bool default_val=false)
virtual ~VarBoolVal ()
virtual void printdebug () const
virtual VarVal * clone () const
virtual VarTypeId getType () const
virtual string getString () const
will return the string "true" if true, or "false" if false.
virtual double getDouble () const
will return 1.0 if true, 0.0 if false.
virtual int getInt () const
will return 1 if true, 0 if false
virtual bool getBool () const
return the boolean value
virtual bool setString (const string &val)
will set this to true if the string is "true" or false otherwise
virtual bool setDouble (double val)
will set this to true if the value is 1.0 or false otherwise
virtual bool setInt (int val)
will set this to true if the value is 1 or false otherwise
virtual bool setBool (bool val)
set this to a particular boolean value
virtual bool hasValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
Protected Attributes
bool _val
Additional Inherited Members
Protected Member Functions inherited from VarTypes::VarVal
virtual void lock () const
virtual void unlock () const
virtual void changed ()
Detailed Description
A Vartype for storing booleans.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 35 of file VarBoolVal.h.
Constructor & Destructor Documentation
VarTypes::VarBoolVal::VarBoolVal (bool default_val = false) inline
Definition at line 43 of file VarBoolVal.h.
References VarTypes::VarVal::changed(), VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
Referenced by clone().
                                        : VarVal()
     {
       lock();
       _val=default_val;
       unlock();
       changed();
     }
virtual VarTypes::VarBoolVal::~VarBoolVal () inline virtual
Definition at line 51 of file VarBoolVal.h.
 {}
Member Function Documentation
virtual VarVal* VarTypes::VarBoolVal::clone () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 60 of file VarBoolVal.h.
References getBool(), setBool(), and VarBoolVal().
{
       VarBoolVal * tmp = new VarBoolVal();
       tmp->setBool(getBool());
       return tmp;
     }
virtual bool VarTypes::VarBoolVal::getBool () const inline virtual
return the boolean value
Definition at line 75 of file VarBoolVal.h.
References _val, VarTypes::VarVal::lock(), VarTypes::VarVal::unlock(), and v.
Referenced by clone(), CaptureFlycap::copyAndConvertFrame(), CaptureDC1394v2::copyAndConvertFrame(), VarTypes::VarBool::createEditor(), PluginVisualize::DrawCameraImage(), getDouble(), CaptureGenerator::getFrame(), getInt(), getString(), CMPattern::TeamDetector::init(), PluginFindBlobs::process(), PluginPublishGeometry::process(), PluginLegacyPublishGeometry::process(), PluginVisualize::process(), PluginDetectBalls::process(), PluginDVR::process(), CaptureV4L::readParameterValues(), CaptureDC1394v2::readParameterValues(), CaptureThread::run(), VarTypes::VarBool::setEditorData(), CaptureDC1394v2::startCapture(), CaptureFlycap::writeParameterValues(), CaptureBlueFox2::writeParameterValues(), CaptureV4L::writeParameterValues(), and CaptureDC1394v2::writeParameterValues().
 { lock(); bool v=_val; unlock(); return v; };
virtual double VarTypes::VarBoolVal::getDouble () const inline virtual
will return 1.0 if true, 0.0 if false.
Definition at line 71 of file VarBoolVal.h.
References getBool().
Referenced by getValue().
 { return (getBool() ? 1.0 : 0.0); };
virtual int VarTypes::VarBoolVal::getInt () const inline virtual
will return 1 if true, 0 if false
Definition at line 73 of file VarBoolVal.h.
References getBool().
 { return (getBool() ? 1 : 0); };
virtual double VarTypes::VarBoolVal::getMaxValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 91 of file VarBoolVal.h.
 { return 1.0; }
virtual double VarTypes::VarBoolVal::getMinValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 90 of file VarBoolVal.h.
 { return 0.0; }
virtual string VarTypes::VarBoolVal::getString () const inline virtual
will return the string "true" if true, or "false" if false.
Reimplemented from VarTypes::VarVal.
Definition at line 69 of file VarBoolVal.h.
References getBool().
 { return (getBool() ? "true" : "false"); };
virtual VarTypeId VarTypes::VarBoolVal::getType () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 66 of file VarBoolVal.h.
References VarTypes::VARTYPE_ID_BOOL.
 { return VARTYPE_ID_BOOL; };
virtual double VarTypes::VarBoolVal::getValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 92 of file VarBoolVal.h.
References getDouble().
 { return getDouble(); }
virtual bool VarTypes::VarBoolVal::hasMaxValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 88 of file VarBoolVal.h.
 { return true; }
virtual bool VarTypes::VarBoolVal::hasMinValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 89 of file VarBoolVal.h.
 { return true; }
virtual bool VarTypes::VarBoolVal::hasValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 87 of file VarBoolVal.h.
 { return true; }
virtual void VarTypes::VarBoolVal::printdebug () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 53 of file VarBoolVal.h.
References VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
     {
       lock();
       printf("%s\n",(_val ? "true" : "false"));
       unlock();
     }
virtual bool VarTypes::VarBoolVal::setBool (bool val) inline virtual
set this to a particular boolean value
Definition at line 84 of file VarBoolVal.h.
References VarTypes::VarVal::changed(), VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
Referenced by clone(), PluginVisualize::PluginVisualize(), CaptureV4L::readParameterProperty(), CaptureDC1394v2::readParameterProperty(), CaptureV4L::readParameterValues(), CaptureDC1394v2::readParameterValues(), VarTypes::VarBool::resetToDefault(), setDouble(), setInt(), VarTypes::VarBool::setModelData(), setString(), and CaptureV4L::writeParameterValues().
 { lock(); if (val!=_val) { _val=val; unlock(); changed(); return true;} else { unlock(); return false; }; };
virtual bool VarTypes::VarBoolVal::setDouble (double val) inline virtual
will set this to true if the value is 1.0 or false otherwise
Definition at line 80 of file VarBoolVal.h.
References setBool().
 { return setBool(val==1.0); };
virtual bool VarTypes::VarBoolVal::setInt (int val) inline virtual
will set this to true if the value is 1 or false otherwise
Definition at line 82 of file VarBoolVal.h.
References setBool().
 { return setBool(val==1); };
virtual bool VarTypes::VarBoolVal::setString (const string & val) inline virtual
will set this to true if the string is "true" or false otherwise
Reimplemented from VarTypes::VarVal.
Definition at line 78 of file VarBoolVal.h.
References setBool().
 { return setBool(val=="true"); };
Field Documentation
bool VarTypes::VarBoolVal::_val protected
Definition at line 39 of file VarBoolVal.h.
Referenced by getBool().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/vartypes/primitives/VarBoolVal.h