Documentation: VarTypes::VarTrigger Class Reference
VarTypes::VarTrigger Class Reference
This is a Trigger-like VarType of the VarTypes system.
#include <VarTrigger.h>
Signals
void signalTriggered ()
Signals inherited from VarTypes::VarType
void hasChanged (VarType *)
void wasEdited (VarType *)
void XMLwasRead (VarType *)
This signal is triggered if data was written from an xml node.
void XMLwasWritten (VarType *)
This signal is triggered if data was written to an xml node.
Public Member Functions
VarTrigger (string _name="", string _label="")
virtual ~VarTrigger ()
virtual void resetToDefault ()
virtual int getAndResetCounter ()
get and reset the internal counter
virtual int getCounter ()
get the internal counter
virtual void resetCounter ()
reset the internal counter back to zero.
virtual void printdebug () const
virtual string getLabel () const
get the label of the button
virtual void setLabel (string _label)
set the label of the button
virtual VarTypeId getType () const
virtual QWidget * createEditor (const VarItemDelegate *delegate, QWidget *parent, const QStyleOptionViewItem &option)
virtual void setEditorData (const VarItemDelegate *delegate, QWidget *editor) const
virtual void setModelData (const VarItemDelegate *delegate, QWidget *editor)
Public Member Functions inherited from VarTypes::VarType
VarType (string name="")
virtual ~VarType ()
virtual vector< VarType * > getChildren () const
virtual void deleteAllChildren ()
virtual void setName (string name)
Set the string label of this node.
virtual string getName () const
Get the string label of this node.
virtual VarTypeFlag getFlags () const
virtual void setFlags (VarTypeFlag f)
virtual void addFlags (VarTypeFlag f)
virtual void removeFlags (VarTypeFlag f)
virtual bool areFlagsSet (VarTypeFlag f) const
VarType * findChild (string label) const
void writeXML (XMLNode &parent, bool blind_append=true)
Write the contents of this VarType node to an XMLNode.
void readXML (XMLNode &us)
Let this VarType node load the contents of an XMLNode.
virtual QSize sizeHint (const VarItemDelegate *delegate, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void paint (const VarItemDelegate *delegate, QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * clone () const
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual string getString () const
Get a human-readable string representation of this node's data.
virtual bool setString (const string &val)
Set this node's data to some string representation.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
virtual bool hasValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Protected Slots
void trigger ()
Protected Attributes
int _counter
string label
Protected Attributes inherited from VarTypes::VarType
QMutex * _mutex
VarTypeFlag _flags
string _name
Additional Inherited Members
Public Slots inherited from VarTypes::VarType
void mvcEditCompleted ()
A slot to receive signals from a model-view system that editing of this item was just completed.
Static Public Member Functions inherited from VarTypes::VarType
static void deleteAllVarChildren (XMLNode &node)
Clear an XMLNode's list of children.
static vector< VarType * > readChildrenHelper (XMLNode &parent, vector< VarType * > existing_children, bool only_update_existing, bool blind_append)
A helper function to read a list of children from XML and convert it to a vector of VarType nodes.
Protected Member Functions inherited from VarTypes::VarType
virtual void lock () const
virtual void unlock () const
virtual void changed ()
virtual void updateAttributes (XMLNode &us) const
virtual void updateText (XMLNode &us) const
virtual void updateChildren (XMLNode &us) const
virtual void readAttributes (XMLNode &us)
virtual void readText (XMLNode &us)
virtual void readChildren (XMLNode &us)
virtual void loadExternal ()
Static Protected Member Functions inherited from VarTypes::VarType
static string fixString (const char *cst)
static string intToString (int val)
static string doubleToString (double val)
static XMLNode findOrAppendChild (XMLNode &parent, string key, string val)
Detailed Description
This is a Trigger-like VarType of the VarTypes system.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
This vartype will be represented as a single button in the GUI. If clicked, the trigger() slot will be called and an internal counter will be incremented by one.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 40 of file VarTrigger.h.
Constructor & Destructor Documentation
VarTypes::VarTrigger::VarTrigger (string _name = "", string _label = "") inline
constructs a new VarTrigger
Parameters
_label The label of the button to be rendered in a GUI view.
Definition at line 62 of file VarTrigger.h.
References VarTypes::VarType::_flags, VarTypes::VarType::changed(), and VarTypes::VARTYPE_FLAG_PERSISTENT.
                                                   : VarType(_name)
     {
       label=_label;
       _counter=0;
       _flags |= VARTYPE_FLAG_PERSISTENT;
       changed();
     }
virtual VarTypes::VarTrigger::~VarTrigger () inline virtual
Definition at line 70 of file VarTrigger.h.
{
     }
Member Function Documentation
virtual QWidget* VarTypes::VarTrigger::createEditor (const VarItemDelegate * delegate, QWidget * parent, const QStyleOptionViewItem & option) inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 125 of file VarTrigger.h.
References trigger().
{
       (void)delegate;
       (void)option;
       QPushButton * tmp=new QPushButton(parent);
       tmp->setText(QString::fromStdString(label));
       connect(tmp,SIGNAL(clicked()),this,SLOT(trigger()));
       return tmp;
     }
virtual int VarTypes::VarTrigger::getAndResetCounter () inline virtual
get and reset the internal counter
Definition at line 78 of file VarTrigger.h.
References _counter, VarTypes::VarType::lock(), VarTypes::VarType::unlock(), and v.
{
       lock();
       int v=_counter;
       _counter=0;
       unlock();
       return v;
     }
virtual int VarTypes::VarTrigger::getCounter () inline virtual
get the internal counter
Definition at line 87 of file VarTrigger.h.
References _counter, VarTypes::VarType::lock(), VarTypes::VarType::unlock(), and v.
Referenced by CaptureDC1394v2::writeParameterValues().
{
       lock();
       int v=_counter;
       unlock();
       return v;
     }
virtual string VarTypes::VarTrigger::getLabel () const inline virtual
get the label of the button
Definition at line 106 of file VarTrigger.h.
References label, VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
{
       lock();
       string tmp=label;
       unlock();
       return tmp;
     }
virtual VarTypeId VarTypes::VarTrigger::getType () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 121 of file VarTrigger.h.
References VarTypes::VARTYPE_ID_TRIGGER.
 { return VARTYPE_ID_TRIGGER; };
virtual void VarTypes::VarTrigger::printdebug () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 101 of file VarTrigger.h.
     {
     }
virtual void VarTypes::VarTrigger::resetCounter () inline virtual
reset the internal counter back to zero.
Definition at line 95 of file VarTrigger.h.
References VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
Referenced by CaptureDC1394v2::writeParameterValues().
{
       lock();
       _counter=0;
       unlock();
     }
virtual void VarTypes::VarTrigger::resetToDefault () inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 73 of file VarTrigger.h.
     {
     }
virtual void VarTypes::VarTrigger::setEditorData (const VarItemDelegate * delegate, QWidget * editor) const inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 133 of file VarTrigger.h.
{
       (void)delegate;
       (void)editor;
     }
virtual void VarTypes::VarTrigger::setLabel (string _label) inline virtual
set the label of the button
Definition at line 114 of file VarTrigger.h.
References VarTypes::VarType::changed(), VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
{
       lock();
       label=_label;
       unlock();
       changed();
     }
virtual void VarTypes::VarTrigger::setModelData (const VarItemDelegate * delegate, QWidget * editor) inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 137 of file VarTrigger.h.
{
       (void)delegate;
       (void)editor;
     }
void VarTypes::VarTrigger::signalTriggered () signal
Definition at line 100 of file moc_VarTrigger.cxx.
Referenced by trigger().
 {
     QMetaObject::activate(this, &staticMetaObject, 0, 0);
 }
void VarTypes::VarTrigger::trigger () inline protected slot
Definition at line 49 of file VarTrigger.h.
References VarTypes::VarType::changed(), VarTypes::VarType::lock(), signalTriggered(), VarTypes::VarType::unlock(), and VarTypes::VarType::wasEdited().
Referenced by createEditor().
                    {
       lock();
       _counter++;
       emit(signalTriggered());
       unlock();
       changed();
       wasEdited((VarType*)this);
     }
Field Documentation
int VarTypes::VarTrigger::_counter protected
Definition at line 44 of file VarTrigger.h.
Referenced by getAndResetCounter(), and getCounter().
string VarTypes::VarTrigger::label protected
Definition at line 45 of file VarTrigger.h.
Referenced by getLabel().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/primitives/VarTrigger.h
ssl-vision/build/src/shared/vartypes/primitives/moc_VarTrigger.cxx