Documentation: VarTypes::VarDoubleVal Class Reference
VarTypes::VarDoubleVal Class Reference
#include <VarDoubleVal.h>
Public Member Functions
VarDoubleVal (double default_val=0)
virtual bool setDouble (double val)
set the value of this node to val.
virtual VarVal * clone () const
virtual void printdebug () const
virtual VarTypeId getType () const
virtual string getString () const
virtual double getDouble () const
get the value of this data-type
virtual int getInt () const
virtual bool getBool () const
will return true if the value is 1.0, or false otherwise
virtual bool setString (const string &val)
virtual bool setInt (int val)
virtual bool setBool (bool val)
virtual bool hasValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
Protected Attributes
double _val
Additional Inherited Members
Protected Member Functions inherited from VarTypes::VarVal
virtual void lock () const
virtual void unlock () const
virtual void changed ()
Detailed Description
Definition at line 35 of file VarDoubleVal.h.
Constructor & Destructor Documentation
VarTypes::VarDoubleVal::VarDoubleVal (double default_val = 0) inline
Definition at line 42 of file VarDoubleVal.h.
References VarTypes::VarVal::changed(), VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
Referenced by clone().
                                        : VarVal()
     {
       lock();
       _val=default_val;
       unlock();
       changed();
     }
Member Function Documentation
virtual VarVal* VarTypes::VarDoubleVal::clone () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 65 of file VarDoubleVal.h.
References getDouble(), setDouble(), and VarDoubleVal().
{
       VarDoubleVal * tmp = new VarDoubleVal();
       tmp->setDouble(getDouble());
       return tmp;
     }
virtual bool VarTypes::VarDoubleVal::getBool () const inline virtual
will return true if the value is 1.0, or false otherwise
Definition at line 97 of file VarDoubleVal.h.
References getDouble().
Referenced by CaptureDC1394v2::writeParameterValues().
 { return (getDouble() == 1.0 ? true : false); };
virtual double VarTypes::VarDoubleVal::getDouble () const inline virtual
get the value of this data-type
Definition at line 91 of file VarDoubleVal.h.
References _val, VarTypes::VarVal::lock(), VarTypes::VarVal::unlock(), and v.
Referenced by CameraParameters::calc_chisqr(), CameraParameters::calibrate(), CameraCalibrationWidget::CameraCalibrationWidget(), clone(), PluginCameraCalibration::detectEdges(), CameraParameters::do_calibration(), PluginLegacySSLNetworkOutput::DoubleSizeToSingleSize(), PluginVisualize::DrawCalibrationResult(), PluginVisualize::DrawCameraCalibration(), GLSoccerView::drawFieldLines(), PluginVisualize::DrawSearchCorridors(), CameraParameters::field2image(), getBool(), PluginLegacyPublishGeometry::GetFieldCircularArcRadius(), PluginLegacyPublishGeometry::GetFieldLineLength(), PluginLegacyPublishGeometry::GetFieldLineThickness(), getInt(), getString(), getValue(), CameraParameters::getWorldLocation(), CameraParameters::image2field(), CMPattern::TeamDetector::init(), PluginPublishGeometry::process(), PluginLegacyPublishGeometry::process(), PluginDetectBalls::process(), CameraParameters::radialDistortion(), CameraParameters::radialDistortionInv(), CameraCalibrationWidget::set_slider_from_vars(), VarTypes::VarDouble::setEditorData(), CaptureGenerator::startCapture(), CameraParameters::toProtoBuffer(), RoboCupField::toProtoBuffer(), FieldFilter::update(), CaptureFlycap::writeParameterValues(), CaptureBlueFox2::writeParameterValues(), and CaptureDC1394v2::writeParameterValues().
 { lock(); double v=_val; unlock(); return v; };
virtual int VarTypes::VarDoubleVal::getInt () const inline virtual
will typecast the value to an int and return it. Note, that this will not perform any rounding, but rather a standard typecast.
Definition at line 95 of file VarDoubleVal.h.
References getDouble().
 { return (int)getDouble(); };
virtual double VarTypes::VarDoubleVal::getMaxValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 110 of file VarDoubleVal.h.
 { return 1.0; }
virtual double VarTypes::VarDoubleVal::getMinValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 109 of file VarDoubleVal.h.
 { return 0.0; }
virtual string VarTypes::VarDoubleVal::getString () const inline virtual
get a maximum precision string representation of the current value Internally this uses sprintf with the lf argument
Reimplemented from VarTypes::VarVal.
Definition at line 82 of file VarDoubleVal.h.
References getDouble().
     {
       char result[255];
       result[0]=0;
       sprintf(result,"%lf",getDouble());
       return result;
     };
virtual VarTypeId VarTypes::VarDoubleVal::getType () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 78 of file VarDoubleVal.h.
References VarTypes::VARTYPE_ID_DOUBLE.
 { return VARTYPE_ID_DOUBLE; };
virtual double VarTypes::VarDoubleVal::getValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 111 of file VarDoubleVal.h.
References getDouble().
 { return getDouble(); }
virtual bool VarTypes::VarDoubleVal::hasMaxValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 107 of file VarDoubleVal.h.
 { return false; }
virtual bool VarTypes::VarDoubleVal::hasMinValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 108 of file VarDoubleVal.h.
 { return false; }
virtual bool VarTypes::VarDoubleVal::hasValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 106 of file VarDoubleVal.h.
 { return true; }
virtual void VarTypes::VarDoubleVal::printdebug () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 71 of file VarDoubleVal.h.
References VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
     {
       lock();
       printf("%f\n",_val);
       unlock();
     }
virtual bool VarTypes::VarDoubleVal::setBool (bool val) inline virtual
Definition at line 103 of file VarDoubleVal.h.
References setDouble().
 { return setDouble(val ? 1.0 : 0.0);  };
virtual bool VarTypes::VarDoubleVal::setDouble (double val) inline virtual
set the value of this node to val.
Reimplemented in VarTypes::VarDouble.
Definition at line 51 of file VarDoubleVal.h.
References VarTypes::VarVal::changed(), VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
Referenced by clone(), setBool(), VarTypes::VarDouble::setDouble(), setInt(), and setString().
     {
       lock();
       if (val!=_val) {
         _val=val;
         unlock();
         changed();
         return true;
       } else {
         unlock();
         return false;
       }
     };
virtual bool VarTypes::VarDoubleVal::setInt (int val) inline virtual
Definition at line 102 of file VarDoubleVal.h.
References setDouble().
 { return setDouble((double)val);  };
virtual bool VarTypes::VarDoubleVal::setString (const string & val) inline virtual
set this floating point value to some string value. internally, this uses sscanf with the lf argument.
Reimplemented from VarTypes::VarVal.
Definition at line 101 of file VarDoubleVal.h.
References setDouble().
 { double num=0; sscanf(val.c_str(),"%lf",&num); return setDouble(num); };
Field Documentation
double VarTypes::VarDoubleVal::_val protected
Definition at line 39 of file VarDoubleVal.h.
Referenced by getDouble().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/vartypes/primitives/VarDoubleVal.h