import numpy as np
import matplotlib.pyplot as plt

# k_0 = np.loadtxt("grsim_tuned/k=0x.txt")
# k_1 = np.loadtxt("grsim_tuned/k=1x.txt")
# k_2 = np.loadtxt("grsim_tuned/k=2x.txt")
# k_3 = np.loadtxt("grsim_tuned/k=3x.txt")
# k_4 = np.loadtxt("grsim_tuned/k=4x.txt")
# k_4d_00_5x = np.loadtxt("grsim_tuned/k=4d=0.005x.txt")
# k_4d_00_1x = np.loadtxt("grsim_tuned/k=4d=0.001x.txt")
# k_4d_000_1x = np.loadtxt("grsim_tuned/k=4d=0.0001x.txt")
# k_4d_000_3x = np.loadtxt("grsim_tuned/k=4d=0.0003x.txt")
# k_5 = np.loadtxt("grsim_tuned/k=5x.txt")
# k_8 = np.loadtxt("grsim_tuned/k=8x.txt")
# plt.plot(k_0,"r")
# plt.plot(k_1,"b")
# plt.plot(k_2,"g")
# plt.plot(k_3,"y")
# plt.plot(k_4,"r")
# k_0 = np.loadtxt("bot_tune/k=0x.txt")
# k_2 = np.loadtxt("bot_tune/k=2x.txt")
k_3 = np.loadtxt("bot_tune/k=3x.txt")
# k_3_5 = np.loadtxt("bot_tune/k=3_5x.txt")
k_3_5_d_0001 = np.loadtxt("bot_tune/k=3_5d=0001x.txt")
k_3_5_d_0003 = np.loadtxt("bot_tune/k=3_5d=0003x.txt")

# plt.plot(k_0,"r")
# plt.plot(k_2,"b")
# plt.plot(k_3,"g")
# plt.plot(k_3,"c")
plt.plot(k_3_5_d_0001,"r")
plt.plot(k_3_5_d_0003,"b")
plt.show()