Documentation: VarTypes::VarTypesInstance Class Reference
VarTypes::VarTypesInstance Class Reference
A singleton wrapper to VarTypesFactory.
#include <VarTypesInstance.h>
Static Public Member Functions
static VarTypesFactory * getFactory ()
static bool setFactory (VarTypesFactory *factory)
Protected Member Functions
VarTypesInstance ()
VarTypesInstance (const VarTypesInstance &)
VarTypesInstance & operator= (const VarTypesInstance &)
Private Attributes
VarTypesFactory * _factory
Static Private Attributes
static VarTypesInstance * pinstance = 0
Detailed Description
A singleton wrapper to VarTypesFactory.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
This is a singleton wrapper to the VarTypesFactory This allows global registration of a custom VarTypesFactory subclass, by calling VarTypesInstance::setFactory(customVarTypesFactorySubClass) before using any other vartypes functions. This in turn provides the simple ability to add additional types to the vartypes system without touching the core files. If setFactory is not called before getFactory() is used, then the VarTypes' default factory class "VarTypesFactory" will be auto-instanciated instead.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 38 of file VarTypesInstance.h.
Constructor & Destructor Documentation
VarTypes::VarTypesInstance::VarTypesInstance () protected
Definition at line 45 of file VarTypesInstance.cpp.
References _factory.
Referenced by getFactory(), and setFactory().
   {
     _factory = 0;
   }
VarTypes::VarTypesInstance::VarTypesInstance (const VarTypesInstance &) protected
Member Function Documentation
VarTypesFactory * VarTypes::VarTypesInstance::getFactory () static
Definition at line 17 of file VarTypesInstance.cpp.
References _factory, pinstance, and VarTypesInstance().
Referenced by VarTypes::VarVal::getTypeName(), and VarTypes::VarType::readChildrenHelper().
   {
     if (pinstance == 0)  // is it the first call?
     {
       pinstance = new VarTypesInstance(); // create sole instance
     }
     if (pinstance->_factory==0) {
       pinstance->_factory= new VarTypesFactory();
     }
     return pinstance->_factory; // address of sole instance
   }
VarTypesInstance& VarTypes::VarTypesInstance::operator= (const VarTypesInstance &) protected
bool VarTypes::VarTypesInstance::setFactory (VarTypesFactory * factory) static
Definition at line 29 of file VarTypesInstance.cpp.
References _factory, pinstance, and VarTypesInstance().
   {
     if (pinstance == 0)  // is it the first call?
     {
       pinstance = new VarTypesInstance(); // create sole instance
     }
     if (pinstance->_factory==0) {
       pinstance->_factory= factory;
       return true;
     } else {
       fprintf(stderr,"ERROR: Unable to set VarTypes factory with a VarTypesInstance::setFactory() call because getFactory() has already been called!\n");
       fprintf(stderr,"Please call VarTypesInstance::setFactory() before any other VarType usage (e.g. at the beginning of your program!)\n");
       return false;
     }
   }
Field Documentation
VarTypesFactory* VarTypes::VarTypesInstance::_factory private
Definition at line 49 of file VarTypesInstance.h.
Referenced by getFactory(), setFactory(), and VarTypesInstance().
VarTypesInstance * VarTypes::VarTypesInstance::pinstance = 0 static private
Definition at line 48 of file VarTypesInstance.h.
Referenced by getFactory(), and setFactory().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/VarTypesInstance.h
ssl-vision/src/shared/vartypes/VarTypesInstance.cpp