Documentation: grsim_comm/include/proto/messages_robocup_ssl_refbox_log.pb.cc File Reference
messages_robocup_ssl_refbox_log.pb.cc File Reference
#include "messages_robocup_ssl_refbox_log.pb.h"
#include <algorithm>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
Data Structures
class Log_FrameDefaultTypeInternal
class Refbox_LogDefaultTypeInternal
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5frefbox_5flog_2eproto
Namespaces
anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}
Macros
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Functions
const ::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5frefbox_5flog_2eproto () GOOGLE_ATTRIBUTE_COLD
void anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}::protobuf_AssignDescriptors ()
void anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}::protobuf_AssignDescriptorsOnce ()
void anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}::protobuf_RegisterTypes (const ::std::string &) GOOGLE_ATTRIBUTE_COLD
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5frefbox_5flog_2eproto ()
void protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl ()
void protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto ()
void protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl ()
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_once_)
void protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto ()
Variables
Log_FrameDefaultTypeInternal _Log_Frame_default_instance_
Refbox_LogDefaultTypeInternal _Refbox_Log_default_instance_
::google::protobuf::Metadata anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}::file_level_metadata [2]
static const ::google::protobuf::internal::MigrationSchema schemas []
static const ::google::protobuf::internal::DefaultInstanceData file_default_instances []
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5frefbox_5flog_2eproto static_descriptor_initializer_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_
Macro Definition Documentation
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Referenced by Log_Frame::MergePartialFromCodedStream(), and Refbox_Log::MergePartialFromCodedStream().
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
Definition at line 4 of file messages_robocup_ssl_refbox_log.pb.cc.
Function Documentation
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_once_)
Referenced by protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::AddDescriptors(), protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::InitDefaultsLog_Frame(), protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::InitDefaultsRefbox_Log(), protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl(), anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}::protobuf_AssignDescriptorsOnce(), protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::protobuf_AssignDescriptorsOnce(), and protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto().
void protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto ()
Definition at line 125 of file messages_robocup_ssl_refbox_log.pb.cc.
References protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl().
Referenced by anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}::protobuf_AssignDescriptors(), and StaticDescriptorInitializer_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::StaticDescriptorInitializer_messages_5frobocup_5fssl_5frefbox_5flog_2eproto().
{
   ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_once_,
                  &protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl);
 }
void protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl ()
Definition at line 107 of file messages_robocup_ssl_refbox_log.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto(), protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto(), protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::protobuf_RegisterTypes(), and protobuf_ShutdownFile_messages_5frobocup_5fssl_5frefbox_5flog_2eproto().
Referenced by protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto().
{
   protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto();
   static const char descriptor[] = {
       "\n%messages_robocup_ssl_refbox_log.proto\032"
       "$messages_robocup_ssl_detection.proto\"C\n"
       "\tLog_Frame\022\"\n\005frame\030\001 \002(\0132\023.SSL_Detectio"
       "nFrame\022\022\n\nrefbox_cmd\030\002 \002(\t\"%\n\nRefbox_Log"
       "\022\027\n\003log\030\001 \003(\0132\n.Log_Frame"
   };
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
       descriptor, 185);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "messages_robocup_ssl_refbox_log.proto", &protobuf_RegisterTypes);
   ::protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_messages_5frobocup_5fssl_5frefbox_5flog_2eproto);
 }
void protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto ()
Definition at line 103 of file messages_robocup_ssl_refbox_log.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), and protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl().
Referenced by Log_Frame::default_instance(), Refbox_Log::default_instance(), Log_Frame::Log_Frame(), protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl(), and Refbox_Log::Refbox_Log().
{
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
   ::google::protobuf::GoogleOnceInit(&once, &protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl);
 }
void protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl ()
Definition at line 92 of file messages_robocup_ssl_refbox_log.pb.cc.
References SSL_DetectionFrame::internal_default_instance(), and protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto().
Referenced by protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto().
{
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto();
   ::google::protobuf::internal::InitProtobufDefaults();
   _Log_Frame_default_instance_.DefaultConstruct();
   _Refbox_Log_default_instance_.DefaultConstruct();
   _Log_Frame_default_instance_.get_mutable()->frame_ = const_cast< ::SSL_DetectionFrame*>(
       ::SSL_DetectionFrame::internal_default_instance());
 }
const ::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5frefbox_5flog_2eproto ()
Definition at line 32 of file messages_robocup_ssl_refbox_log.pb.cc.
Referenced by anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}::protobuf_AssignDescriptors().
{
   static const ::google::protobuf::uint32 offsets[] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Log_Frame, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Log_Frame, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Log_Frame, frame_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Log_Frame, refbox_cmd_),
     1,
     0,
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Refbox_Log, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Refbox_Log, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Refbox_Log, log_),
     0,
   };
   return offsets;
 }
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5frefbox_5flog_2eproto ()
Definition at line 85 of file messages_robocup_ssl_refbox_log.pb.cc.
References protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::file_level_metadata.
Referenced by protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl().
{
   _Log_Frame_default_instance_.Shutdown();
   delete file_level_metadata[0].reflection;
   _Refbox_Log_default_instance_.Shutdown();
   delete file_level_metadata[1].reflection;
 }
Variable Documentation
Log_FrameDefaultTypeInternal _Log_Frame_default_instance_
Definition at line 20 of file messages_robocup_ssl_refbox_log.pb.cc.
Referenced by Log_Frame::InitAsDefaultInstance(), and protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::InitDefaultsLog_FrameImpl().
Refbox_LogDefaultTypeInternal _Refbox_Log_default_instance_
Definition at line 22 of file messages_robocup_ssl_refbox_log.pb.cc.
Referenced by protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::InitDefaultsRefbox_LogImpl().
const ::google::protobuf::internal::DefaultInstanceData file_default_instances[] static
Initial value:
= {
  {reinterpret_cast<const ::google::protobuf::Message*>(&_Log_Frame_default_instance_), NULL},
  {reinterpret_cast<const ::google::protobuf::Message*>(&_Refbox_Log_default_instance_), NULL},
}
Definition at line 57 of file messages_robocup_ssl_refbox_log.pb.cc.
Referenced by anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}::protobuf_AssignDescriptors().
const ::google::protobuf::internal::MigrationSchema schemas[] static
Initial value:
= {
  { 0, 6, sizeof(Log_Frame)},
  { 8, 13, sizeof(Refbox_Log)},
}
Definition at line 52 of file messages_robocup_ssl_refbox_log.pb.cc.
Referenced by anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}::protobuf_AssignDescriptors(), and protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::protobuf_AssignDescriptors().
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5frefbox_5flog_2eproto static_descriptor_initializer_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_
Referenced by StaticDescriptorInitializer_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::StaticDescriptorInitializer_messages_5frobocup_5fssl_5frefbox_5flog_2eproto().