Documentation: sslDebug_Data Class Reference
sslDebug_Data Class Reference
#include <sslDebug_Data.pb.h>
Public Member Functions
sslDebug_Data ()
virtual ~sslDebug_Data ()
sslDebug_Data (const sslDebug_Data &from)
sslDebug_Data & operator= (const sslDebug_Data &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (sslDebug_Data *other)
sslDebug_Data * New () const PROTOBUF_FINAL
sslDebug_Data * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const sslDebug_Data &from)
void MergeFrom (const sslDebug_Data &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_id () const
void clear_id ()
const ::std::string & id () const
void set_id (const ::std::string &value)
void set_id (const char *value)
void set_id (const char *value, size_t size)
::std::string * mutable_id ()
::std::string * release_id ()
void set_allocated_id (::std::string *id)
int circle_size () const
void clear_circle ()
const ::Debug_Circle & circle (int index) const
::Debug_Circle * mutable_circle (int index)
::Debug_Circle * add_circle ()
::google::protobuf::RepeatedPtrField< ::Debug_Circle > * mutable_circle ()
const ::google::protobuf::RepeatedPtrField< ::Debug_Circle > & circle () const
int line_size () const
void clear_line ()
const ::Debug_Line & line (int index) const
::Debug_Line * mutable_line (int index)
::Debug_Line * add_line ()
::google::protobuf::RepeatedPtrField< ::Debug_Line > * mutable_line ()
const ::google::protobuf::RepeatedPtrField< ::Debug_Line > & line () const
int botpos_size () const
void clear_botpos ()
const ::Debug_AdjustBot & botpos (int index) const
::Debug_AdjustBot * mutable_botpos (int index)
::Debug_AdjustBot * add_botpos ()
::google::protobuf::RepeatedPtrField< ::Debug_AdjustBot > * mutable_botpos ()
const ::google::protobuf::RepeatedPtrField< ::Debug_AdjustBot > & botpos () const
int ballpos_size () const
void clear_ballpos ()
const ::Debug_AdjustBall & ballpos (int index) const
::Debug_AdjustBall * mutable_ballpos (int index)
::Debug_AdjustBall * add_ballpos ()
::google::protobuf::RepeatedPtrField< ::Debug_AdjustBall > * mutable_ballpos ()
const ::google::protobuf::RepeatedPtrField< ::Debug_AdjustBall > & ballpos () const
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const sslDebug_Data & default_instance ()
static const sslDebug_Data * internal_default_instance ()
Static Public Attributes
static const int kIdFieldNumber = 1
static const int kCircleFieldNumber = 2
static const int kLineFieldNumber = 3
static const int kBotposFieldNumber = 4
static const int kBallposFieldNumber = 5
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (sslDebug_Data *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_id ()
void clear_has_id ()
friendconst::google::protobuf::uint32 * protobuf_Offsets_sslDebug_5fData_2eproto ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::RepeatedPtrField< ::Debug_Circle > circle_
::google::protobuf::RepeatedPtrField< ::Debug_Line > line_
::google::protobuf::RepeatedPtrField< ::Debug_AdjustBot > botpos_
::google::protobuf::RepeatedPtrField< ::Debug_AdjustBall > ballpos_
::google::protobuf::internal::ArenaStringPtr id_
Friends
void protobuf_InitDefaults_sslDebug_5fData_2eproto_impl ()
void protobuf_AddDesc_sslDebug_5fData_2eproto_impl ()
void protobuf_ShutdownFile_sslDebug_5fData_2eproto ()
Detailed Description
Definition at line 53 of file sslDebug_Data.pb.h.
Constructor & Destructor Documentation
sslDebug_Data::sslDebug_Data ()
virtual sslDebug_Data::~sslDebug_Data () virtual
sslDebug_Data::sslDebug_Data (const sslDebug_Data & from)
Member Function Documentation
Debug_AdjustBall * sslDebug_Data::add_ballpos () inline
Definition at line 968 of file sslDebug_Data.pb.h.
References ballpos_.
{
   // @@protoc_insertion_point(field_add:sslDebug_Data.ballpos)
   return ballpos_.Add();
 }
Debug_AdjustBot * sslDebug_Data::add_botpos () inline
Definition at line 938 of file sslDebug_Data.pb.h.
References botpos_.
{
   // @@protoc_insertion_point(field_add:sslDebug_Data.botpos)
   return botpos_.Add();
 }
Debug_Circle * sslDebug_Data::add_circle () inline
Definition at line 878 of file sslDebug_Data.pb.h.
References circle_.
Referenced by CallbackDbg(), and main().
{
   // @@protoc_insertion_point(field_add:sslDebug_Data.circle)
   return circle_.Add();
 }
Debug_Line * sslDebug_Data::add_line () inline
Definition at line 908 of file sslDebug_Data.pb.h.
References line_.
Referenced by Callback(), CallbackDbg(), CallbackGC(), and main().
{
   // @@protoc_insertion_point(field_add:sslDebug_Data.line)
   return line_.Add();
 }
const ::Debug_AdjustBall & sslDebug_Data::ballpos (int index) const inline
Definition at line 960 of file sslDebug_Data.pb.h.
References ballpos_.
{
   // @@protoc_insertion_point(field_get:sslDebug_Data.ballpos)
   return ballpos_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::Debug_AdjustBall > & sslDebug_Data::ballpos () const inline
Definition at line 978 of file sslDebug_Data.pb.h.
References ballpos_.
{
   // @@protoc_insertion_point(field_list:sslDebug_Data.ballpos)
   return ballpos_;
 }
int sslDebug_Data::ballpos_size () const inline
Definition at line 954 of file sslDebug_Data.pb.h.
References ballpos_.
{
   return ballpos_.size();
 }
const ::Debug_AdjustBot & sslDebug_Data::botpos (int index) const inline
Definition at line 930 of file sslDebug_Data.pb.h.
References botpos_.
{
   // @@protoc_insertion_point(field_get:sslDebug_Data.botpos)
   return botpos_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::Debug_AdjustBot > & sslDebug_Data::botpos () const inline
Definition at line 948 of file sslDebug_Data.pb.h.
References botpos_.
{
   // @@protoc_insertion_point(field_list:sslDebug_Data.botpos)
   return botpos_;
 }
int sslDebug_Data::botpos_size () const inline
Definition at line 924 of file sslDebug_Data.pb.h.
References botpos_.
{
   return botpos_.size();
 }
size_t sslDebug_Data::ByteSizeLong () const
Referenced by New(), Debug_Circle::New(), Debug_Line::New(), Debug_AdjustBot::New(), and Debug_AdjustBall::New().
const ::Debug_Circle & sslDebug_Data::circle (int index) const inline
Definition at line 870 of file sslDebug_Data.pb.h.
References circle_.
{
   // @@protoc_insertion_point(field_get:sslDebug_Data.circle)
   return circle_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::Debug_Circle > & sslDebug_Data::circle () const inline
Definition at line 888 of file sslDebug_Data.pb.h.
References circle_.
{
   // @@protoc_insertion_point(field_list:sslDebug_Data.circle)
   return circle_;
 }
int sslDebug_Data::circle_size () const inline
Definition at line 864 of file sslDebug_Data.pb.h.
References circle_.
{
   return circle_.size();
 }
void sslDebug_Data::Clear ()
Referenced by New(), Debug_Circle::New(), Debug_Line::New(), Debug_AdjustBot::New(), and Debug_AdjustBall::New().
void sslDebug_Data::clear_ballpos () inline
Definition at line 957 of file sslDebug_Data.pb.h.
References ballpos_.
{
   ballpos_.Clear();
 }
void sslDebug_Data::clear_botpos () inline
Definition at line 927 of file sslDebug_Data.pb.h.
References botpos_.
{
   botpos_.Clear();
 }
void sslDebug_Data::clear_circle () inline
Definition at line 867 of file sslDebug_Data.pb.h.
References circle_.
{
   circle_.Clear();
 }
void sslDebug_Data::clear_has_id () inline private
Definition at line 808 of file sslDebug_Data.pb.h.
References _has_bits_.
Referenced by clear_id(), Debug_AdjustBot::clear_id(), release_id(), and set_allocated_id().
{
   _has_bits_[0] &= ~0x00000001u;
 }
void sslDebug_Data::clear_id () inline
Definition at line 811 of file sslDebug_Data.pb.h.
References clear_has_id(), and id_.
Referenced by MaybeArenaPtr(), and Debug_AdjustBot::MaybeArenaPtr().
{
   id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   clear_has_id();
 }
void sslDebug_Data::clear_line () inline
Definition at line 897 of file sslDebug_Data.pb.h.
References line_.
{
   line_.Clear();
 }
void sslDebug_Data::CopyFrom (const ::google::protobuf::Message & from)
Referenced by New(), Debug_Circle::New(), Debug_Line::New(), Debug_AdjustBot::New(), Debug_AdjustBall::New(), operator=(), Debug_Circle::operator=(), Debug_Line::operator=(), Debug_AdjustBot::operator=(), and Debug_AdjustBall::operator=().
void sslDebug_Data::CopyFrom (const sslDebug_Data & from)
static const sslDebug_Data& sslDebug_Data::default_instance () static
Referenced by mutable_unknown_fields(), Debug_Circle::mutable_unknown_fields(), Debug_Line::mutable_unknown_fields(), Debug_AdjustBot::mutable_unknown_fields(), and Debug_AdjustBall::mutable_unknown_fields().
static const ::google::protobuf::Descriptor* sslDebug_Data::descriptor () static
Referenced by mutable_unknown_fields(), Debug_Circle::mutable_unknown_fields(), Debug_Line::mutable_unknown_fields(), Debug_AdjustBot::mutable_unknown_fields(), and Debug_AdjustBall::mutable_unknown_fields().
inline ::google::protobuf::Arena* sslDebug_Data::GetArenaNoVirtual () const inline private
Definition at line 113 of file sslDebug_Data.pb.h.
{
     return NULL;
   }
int sslDebug_Data::GetCachedSize () const inline
Definition at line 106 of file sslDebug_Data.pb.h.
References _cached_size_, InternalSwap(), SetCachedSize(), SharedCtor(), and SharedDtor().
 { return _cached_size_; }
::google::protobuf::Metadata sslDebug_Data::GetMetadata () const
Referenced by MaybeArenaPtr(), Debug_Circle::MaybeArenaPtr(), Debug_Line::MaybeArenaPtr(), Debug_AdjustBot::MaybeArenaPtr(), and Debug_AdjustBall::MaybeArenaPtr().
bool sslDebug_Data::has_id () const inline
Definition at line 802 of file sslDebug_Data.pb.h.
References _has_bits_.
Referenced by MaybeArenaPtr(), and Debug_AdjustBot::MaybeArenaPtr().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
const ::std::string & sslDebug_Data::id () const inline
Definition at line 815 of file sslDebug_Data.pb.h.
References id_.
{
   // @@protoc_insertion_point(field_get:sslDebug_Data.id)
   return id_.GetNoArena();
 }
static const sslDebug_Data* sslDebug_Data::internal_default_instance () inline static
Definition at line 76 of file sslDebug_Data.pb.h.
References _sslDebug_Data_default_instance_, and Swap().
Referenced by grSim_Packet::debuginfo().
{
     return reinterpret_cast<const sslDebug_Data*>(
                &_sslDebug_Data_default_instance_);
   }
::google::protobuf::uint8* sslDebug_Data::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
Referenced by New(), Debug_Circle::New(), Debug_Line::New(), Debug_AdjustBot::New(), Debug_AdjustBall::New(), SerializeWithCachedSizesToArray(), Debug_Circle::SerializeWithCachedSizesToArray(), Debug_Line::SerializeWithCachedSizesToArray(), Debug_AdjustBot::SerializeWithCachedSizesToArray(), and Debug_AdjustBall::SerializeWithCachedSizesToArray().
void sslDebug_Data::InternalSwap (sslDebug_Data * other) private
Referenced by GetCachedSize(), Debug_Circle::GetCachedSize(), Debug_Line::GetCachedSize(), Debug_AdjustBot::GetCachedSize(), and Debug_AdjustBall::GetCachedSize().
bool sslDebug_Data::IsInitialized () const
Referenced by New(), Debug_Circle::New(), Debug_Line::New(), Debug_AdjustBot::New(), and Debug_AdjustBall::New().
const ::Debug_Line & sslDebug_Data::line (int index) const inline
Definition at line 900 of file sslDebug_Data.pb.h.
References line_.
{
   // @@protoc_insertion_point(field_get:sslDebug_Data.line)
   return line_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::Debug_Line > & sslDebug_Data::line () const inline
Definition at line 918 of file sslDebug_Data.pb.h.
References line_.
{
   // @@protoc_insertion_point(field_list:sslDebug_Data.line)
   return line_;
 }
int sslDebug_Data::line_size () const inline
Definition at line 894 of file sslDebug_Data.pb.h.
References line_.
{
   return line_.size();
 }
void* sslDebug_Data::MaybeArenaPtr () const inline private
Definition at line 116 of file sslDebug_Data.pb.h.
References clear_id(), GetMetadata(), and has_id().
{
     return NULL;
   }
void sslDebug_Data::MergeFrom (const ::google::protobuf::Message & from)
Referenced by New(), Debug_Circle::New(), Debug_Line::New(), Debug_AdjustBot::New(), and Debug_AdjustBall::New().
void sslDebug_Data::MergeFrom (const sslDebug_Data & from)
bool sslDebug_Data::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Referenced by New(), Debug_Circle::New(), Debug_Line::New(), Debug_AdjustBot::New(), and Debug_AdjustBall::New().
Debug_AdjustBall * sslDebug_Data::mutable_ballpos (int index) inline
Definition at line 964 of file sslDebug_Data.pb.h.
References ballpos_.
{
   // @@protoc_insertion_point(field_mutable:sslDebug_Data.ballpos)
   return ballpos_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::Debug_AdjustBall > * sslDebug_Data::mutable_ballpos () inline
Definition at line 973 of file sslDebug_Data.pb.h.
References ballpos_.
{
   // @@protoc_insertion_point(field_mutable_list:sslDebug_Data.ballpos)
   return &ballpos_;
 }
Debug_AdjustBot * sslDebug_Data::mutable_botpos (int index) inline
Definition at line 934 of file sslDebug_Data.pb.h.
References botpos_.
{
   // @@protoc_insertion_point(field_mutable:sslDebug_Data.botpos)
   return botpos_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::Debug_AdjustBot > * sslDebug_Data::mutable_botpos () inline
Definition at line 943 of file sslDebug_Data.pb.h.
References botpos_.
{
   // @@protoc_insertion_point(field_mutable_list:sslDebug_Data.botpos)
   return &botpos_;
 }
Debug_Circle * sslDebug_Data::mutable_circle (int index) inline
Definition at line 874 of file sslDebug_Data.pb.h.
References circle_.
{
   // @@protoc_insertion_point(field_mutable:sslDebug_Data.circle)
   return circle_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::Debug_Circle > * sslDebug_Data::mutable_circle () inline
Definition at line 883 of file sslDebug_Data.pb.h.
References circle_.
{
   // @@protoc_insertion_point(field_mutable_list:sslDebug_Data.circle)
   return &circle_;
 }
std::string * sslDebug_Data::mutable_id () inline
Definition at line 843 of file sslDebug_Data.pb.h.
References id_, and set_has_id().
{
   set_has_id();
   // @@protoc_insertion_point(field_mutable:sslDebug_Data.id)
   return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
Debug_Line * sslDebug_Data::mutable_line (int index) inline
Definition at line 904 of file sslDebug_Data.pb.h.
References line_.
{
   // @@protoc_insertion_point(field_mutable:sslDebug_Data.line)
   return line_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::Debug_Line > * sslDebug_Data::mutable_line () inline
Definition at line 913 of file sslDebug_Data.pb.h.
References line_.
{
   // @@protoc_insertion_point(field_mutable_list:sslDebug_Data.line)
   return &line_;
 }
inline ::google::protobuf::UnknownFieldSet* sslDebug_Data::mutable_unknown_fields () inline
Definition at line 69 of file sslDebug_Data.pb.h.
References _internal_metadata_, default_instance(), and descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
sslDebug_Data* sslDebug_Data::New () const inline
Definition at line 85 of file sslDebug_Data.pb.h.
References ByteSizeLong(), Clear(), CopyFrom(), InternalSerializeWithCachedSizesToArray(), IsInitialized(), MergeFrom(), MergePartialFromCodedStream(), New(), SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New(), Debug_Circle::New(), Debug_Line::New(), Debug_AdjustBot::New(), and Debug_AdjustBall::New().
 { return New(NULL); }
sslDebug_Data* sslDebug_Data::New (::google::protobuf::Arena * arena) const
sslDebug_Data& sslDebug_Data::operator= (const sslDebug_Data & from) inline
Definition at line 60 of file sslDebug_Data.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* sslDebug_Data::protobuf_Offsets_sslDebug_5fData_2eproto () private
std::string * sslDebug_Data::release_id () inline
Definition at line 848 of file sslDebug_Data.pb.h.
References clear_has_id(), and id_.
{
   // @@protoc_insertion_point(field_release:sslDebug_Data.id)
   clear_has_id();
   return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void sslDebug_Data::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Referenced by New(), Debug_Circle::New(), Debug_Line::New(), Debug_AdjustBot::New(), and Debug_AdjustBall::New().
::google::protobuf::uint8* sslDebug_Data::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 102 of file sslDebug_Data.pb.h.
References InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void sslDebug_Data::set_allocated_id (::std::string * id) inline
Definition at line 853 of file sslDebug_Data.pb.h.
References clear_has_id(), id_, and set_has_id().
{
   if (id != NULL) {
     set_has_id();
   } else {
     clear_has_id();
   }
   id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
   // @@protoc_insertion_point(field_set_allocated:sslDebug_Data.id)
 }
void sslDebug_Data::set_has_id () inline private
Definition at line 805 of file sslDebug_Data.pb.h.
References _has_bits_.
Referenced by mutable_id(), set_allocated_id(), set_id(), and Debug_AdjustBot::set_id().
{
   _has_bits_[0] |= 0x00000001u;
 }
void sslDebug_Data::set_id (const ::std::string & value) inline
Definition at line 819 of file sslDebug_Data.pb.h.
References id_, and set_has_id().
Referenced by Callback(), CallbackDbg(), CallbackGC(), and main().
{
   set_has_id();
   id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
   // @@protoc_insertion_point(field_set:sslDebug_Data.id)
 }
void sslDebug_Data::set_id (const char * value) inline
Definition at line 832 of file sslDebug_Data.pb.h.
References id_, and set_has_id().
{
   set_has_id();
   id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
   // @@protoc_insertion_point(field_set_char:sslDebug_Data.id)
 }
void sslDebug_Data::set_id (const char * value, size_t size) inline
Definition at line 837 of file sslDebug_Data.pb.h.
References id_, and set_has_id().
{
   set_has_id();
   id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
       ::std::string(reinterpret_cast<const char*>(value), size));
   // @@protoc_insertion_point(field_set_pointer:sslDebug_Data.id)
 }
void sslDebug_Data::SetCachedSize (int size) const private
Referenced by GetCachedSize(), Debug_Circle::GetCachedSize(), Debug_Line::GetCachedSize(), Debug_AdjustBot::GetCachedSize(), and Debug_AdjustBall::GetCachedSize().
void sslDebug_Data::SharedCtor () private
Referenced by GetCachedSize(), Debug_Circle::GetCachedSize(), Debug_Line::GetCachedSize(), Debug_AdjustBot::GetCachedSize(), and Debug_AdjustBall::GetCachedSize().
void sslDebug_Data::SharedDtor () private
Referenced by GetCachedSize(), Debug_Circle::GetCachedSize(), Debug_Line::GetCachedSize(), Debug_AdjustBot::GetCachedSize(), and Debug_AdjustBall::GetCachedSize().
void sslDebug_Data::Swap (sslDebug_Data * other)
Referenced by internal_default_instance(), Debug_Circle::internal_default_instance(), Debug_Line::internal_default_instance(), Debug_AdjustBot::internal_default_instance(), and Debug_AdjustBall::internal_default_instance().
const ::google::protobuf::UnknownFieldSet& sslDebug_Data::unknown_fields () const inline
Definition at line 65 of file sslDebug_Data.pb.h.
References _internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
Friends And Related Function Documentation
void protobuf_AddDesc_sslDebug_5fData_2eproto_impl () friend
void protobuf_InitDefaults_sslDebug_5fData_2eproto_impl () friend
void protobuf_ShutdownFile_sslDebug_5fData_2eproto () friend
Field Documentation
int sslDebug_Data::_cached_size_ mutable private
Definition at line 197 of file sslDebug_Data.pb.h.
Referenced by GetCachedSize(), Debug_Circle::GetCachedSize(), Debug_Line::GetCachedSize(), Debug_AdjustBot::GetCachedSize(), and Debug_AdjustBall::GetCachedSize().
::google::protobuf::internal::HasBits<1> sslDebug_Data::_has_bits_ private
Definition at line 196 of file sslDebug_Data.pb.h.
Referenced by Debug_Circle::clear_has_color(), Debug_Line::clear_has_color(), Debug_AdjustBot::clear_has_dir(), clear_has_id(), Debug_AdjustBot::clear_has_id(), Debug_Circle::clear_has_radius(), Debug_AdjustBot::clear_has_team(), Debug_AdjustBot::clear_has_vx(), Debug_AdjustBall::clear_has_vx(), Debug_AdjustBot::clear_has_vy(), Debug_AdjustBall::clear_has_vy(), Debug_AdjustBot::clear_has_vz(), Debug_AdjustBall::clear_has_vz(), Debug_Circle::clear_has_x(), Debug_AdjustBot::clear_has_x(), Debug_AdjustBall::clear_has_x(), Debug_Line::clear_has_x1(), Debug_Line::clear_has_x2(), Debug_Circle::clear_has_y(), Debug_AdjustBot::clear_has_y(), Debug_AdjustBall::clear_has_y(), Debug_Line::clear_has_y1(), Debug_Line::clear_has_y2(), Debug_Circle::has_color(), Debug_Line::has_color(), Debug_AdjustBot::has_dir(), has_id(), Debug_AdjustBot::has_id(), Debug_Circle::has_radius(), Debug_AdjustBot::has_team(), Debug_AdjustBot::has_vx(), Debug_AdjustBall::has_vx(), Debug_AdjustBot::has_vy(), Debug_AdjustBall::has_vy(), Debug_AdjustBot::has_vz(), Debug_AdjustBall::has_vz(), Debug_Circle::has_x(), Debug_AdjustBot::has_x(), Debug_AdjustBall::has_x(), Debug_Line::has_x1(), Debug_Line::has_x2(), Debug_Circle::has_y(), Debug_AdjustBot::has_y(), Debug_AdjustBall::has_y(), Debug_Line::has_y1(), Debug_Line::has_y2(), Debug_Circle::set_has_color(), Debug_Line::set_has_color(), Debug_AdjustBot::set_has_dir(), set_has_id(), Debug_AdjustBot::set_has_id(), Debug_Circle::set_has_radius(), Debug_AdjustBot::set_has_team(), Debug_AdjustBot::set_has_vx(), Debug_AdjustBall::set_has_vx(), Debug_AdjustBot::set_has_vy(), Debug_AdjustBall::set_has_vy(), Debug_AdjustBot::set_has_vz(), Debug_AdjustBall::set_has_vz(), Debug_Circle::set_has_x(), Debug_AdjustBot::set_has_x(), Debug_AdjustBall::set_has_x(), Debug_Line::set_has_x1(), Debug_Line::set_has_x2(), Debug_Circle::set_has_y(), Debug_AdjustBot::set_has_y(), Debug_AdjustBall::set_has_y(), Debug_Line::set_has_y1(), and Debug_Line::set_has_y2().
::google::protobuf::internal::InternalMetadataWithArena sslDebug_Data::_internal_metadata_ private
Definition at line 195 of file sslDebug_Data.pb.h.
Referenced by mutable_unknown_fields(), Debug_Circle::mutable_unknown_fields(), Debug_Line::mutable_unknown_fields(), Debug_AdjustBot::mutable_unknown_fields(), Debug_AdjustBall::mutable_unknown_fields(), unknown_fields(), Debug_Circle::unknown_fields(), Debug_Line::unknown_fields(), Debug_AdjustBot::unknown_fields(), and Debug_AdjustBall::unknown_fields().
::google::protobuf::RepeatedPtrField< ::Debug_AdjustBall > sslDebug_Data::ballpos_ private
Definition at line 201 of file sslDebug_Data.pb.h.
Referenced by add_ballpos(), ballpos(), ballpos_size(), clear_ballpos(), and mutable_ballpos().
::google::protobuf::RepeatedPtrField< ::Debug_AdjustBot > sslDebug_Data::botpos_ private
Definition at line 200 of file sslDebug_Data.pb.h.
Referenced by add_botpos(), botpos(), botpos_size(), clear_botpos(), and mutable_botpos().
::google::protobuf::RepeatedPtrField< ::Debug_Circle > sslDebug_Data::circle_ private
Definition at line 198 of file sslDebug_Data.pb.h.
Referenced by add_circle(), circle(), circle_size(), clear_circle(), and mutable_circle().
::google::protobuf::internal::ArenaStringPtr sslDebug_Data::id_ private
Definition at line 202 of file sslDebug_Data.pb.h.
Referenced by clear_id(), Debug_AdjustBot::clear_id(), id(), Debug_AdjustBot::id(), mutable_id(), release_id(), set_allocated_id(), set_id(), and Debug_AdjustBot::set_id().
const int sslDebug_Data::kBallposFieldNumber = 5 static
Definition at line 181 of file sslDebug_Data.pb.h.
const int sslDebug_Data::kBotposFieldNumber = 4 static
Definition at line 169 of file sslDebug_Data.pb.h.
const int sslDebug_Data::kCircleFieldNumber = 2 static
Definition at line 145 of file sslDebug_Data.pb.h.
const int sslDebug_Data::kIdFieldNumber = 1 static
Definition at line 130 of file sslDebug_Data.pb.h.
const int sslDebug_Data::kLineFieldNumber = 3 static
Definition at line 157 of file sslDebug_Data.pb.h.
::google::protobuf::RepeatedPtrField< ::Debug_Line > sslDebug_Data::line_ private
Definition at line 199 of file sslDebug_Data.pb.h.
Referenced by add_line(), clear_line(), line(), line_size(), and mutable_line().
The documentation for this class was generated from the following file:
grsim_comm/include/proto/sslDebug_Data.pb.h