Documentation: CGraphics Class Reference
CGraphics Class Reference
#include <graphics.h>
Public Member Functions
CGraphics (QGLWidget *_owner)
~CGraphics ()
void disableGraphics ()
void enableGraphics ()
bool isGraphicsEnabled ()
int loadTexture (QImage *img)
int loadTextureSkyBox (QImage *img)
void setViewpoint (dReal xyz[3], dReal hpr[3])
void getViewpoint (dReal *xyz, dReal *hpr)
void getFrustum (dReal &right, dReal &bottom, dReal &vnear)
int getWidth ()
int getHeight ()
dReal renderDepth ()
void setRenderDepth (dReal depth)
void setViewpoint (dReal x, dReal y, dReal z, dReal h, dReal p, dReal r)
void cameraMotion (int mode, int deltax, int deltay)
void lookAt (dReal x, dReal y, dReal z)
void getCameraForward (dReal &x, dReal &y, dReal &z)
void getCameraRight (dReal &x, dReal &y, dReal &z)
void zoomCamera (dReal dz)
void setColor (dReal r, dReal g, dReal b, dReal alpha)
void setSphereQuality (int q)
void setShadow (bool state)
void useTexture (int tex_id)
void noTexture ()
void setTransform (const dReal pos[3], const dReal R[12])
void setTransformD (const double pos[3], const double R[12])
void initScene (int width, int height, dReal rc, dReal gc, dReal bc, bool fog=false, dReal fogr=0.6, dReal fogg=0.6, dReal fogb=0.6, dReal fogdensity=0.6)
void finalizeScene ()
void resetState ()
void drawSkybox (int t1, int t2, int t3, int t4, int t5, int t6)
void drawSky ()
void drawGround ()
void drawSSLGround (dReal SSL_FIELD_RAD, dReal SSL_FIELD_LENGTH, dReal SSL_FIELD_WIDTH, dReal SSL_FIELD_PENALTY_RADIUS, dReal SSL_FIELD_PENALTY_LINE, dReal SSL_FIELD_PENALTY_POINT, dReal SSL_FIELD_LINE_WIDTH, dReal SSL_FIELD_DEFENSE_STRETCH, dReal SSL_FIELD_DEFENSE_RADIUS, dReal epsilon)
void drawBox (const dReal pos[3], const dReal R[12], const dReal sides[3])
void drawSphere (const dReal pos[3], const dReal R[12], dReal radius)
void drawCylinder (const dReal pos[3], const dReal R[12], dReal length, dReal radius)
void drawCylinder_TopTextured (const dReal pos[3], const dReal R[12], dReal length, dReal radius, int tex_id, bool robot=false)
void drawCapsule (const dReal pos[3], const dReal R[12], dReal length, dReal radius)
void drawLine (const dReal pos1[3], const dReal pos2[3])
void drawCircle (dReal x0, dReal y0, dReal z0, dReal r)
Private Member Functions
void _drawBox (const dReal sides[3])
void _drawPatch (dReal p1[3], dReal p2[3], dReal p3[3], int level)
void _drawSphere ()
void _drawCapsule (dReal l, dReal r)
void _drawCylinder (dReal l, dReal r, dReal zoffset)
void _drawCylinder_TopTextured (dReal l, dReal r, dReal zoffset, int tex_id, bool robot=false)
void wrapCameraAngles ()
void setCamera (dReal x, dReal y, dReal z, dReal h, dReal p, dReal r)
Private Attributes
dReal view_xyz [3]
dReal view_hpr [3]
QVector< GLuint > tex_ids
dReal frustum_right
dReal frustum_bottom
dReal frustum_vnear
dReal m_renderDepth
int _width
int _height
QGLWidget * owner
int sphere_quality
bool graphicDisabled
Detailed Description
Definition at line 28 of file graphics.h.
Constructor & Destructor Documentation
CGraphics::CGraphics (QGLWidget * _owner)
Definition at line 42 of file graphics.cpp.
References graphicDisabled, m_renderDepth, owner, setViewpoint(), and sphere_quality.
 {
     owner = _owner;
     dReal xyz[3] = {0.8317f,-0.9817f,0.8000f};
     dReal hpr[3] = {121.0000f,-27.5000f,0.0000f};
     setViewpoint (xyz,hpr);
     sphere_quality = 1;
     m_renderDepth = 100;
     graphicDisabled = false;
 }
CGraphics::~CGraphics ()
Definition at line 53 of file graphics.cpp.
 {
 }
Member Function Documentation
void CGraphics::_drawBox (const dReal sides[3]) private
Definition at line 789 of file graphics.cpp.
References graphicDisabled.
Referenced by drawBox().
 {
     if (graphicDisabled) return;
     dReal lx = sides[0]*0.5f;
     dReal ly = sides[1]*0.5f;
     dReal lz = sides[2]*0.5f;
     // sides
     glBegin (GL_TRIANGLE_STRIP);
     glNormal3f (-1,0,0);
     glVertex3f (-lx,-ly,-lz);
     glVertex3f (-lx,-ly,lz);
     glVertex3f (-lx,ly,-lz);
     glVertex3f (-lx,ly,lz);
     glNormal3f (0,1,0);
     glVertex3f (lx,ly,-lz);
     glVertex3f (lx,ly,lz);
     glNormal3f (1,0,0);
     glVertex3f (lx,-ly,-lz);
     glVertex3f (lx,-ly,lz);
     glNormal3f (0,-1,0);
     glVertex3f (-lx,-ly,-lz);
     glVertex3f (-lx,-ly,lz);
     glEnd();
     // top face
     glBegin (GL_TRIANGLE_FAN);
     glNormal3f (0,0,1);
     glVertex3f (-lx,-ly,lz);
     glVertex3f (lx,-ly,lz);
     glVertex3f (lx,ly,lz);
     glVertex3f (-lx,ly,lz);
     glEnd();
     // bottom face
     glBegin (GL_TRIANGLE_FAN);
     glNormal3f (0,0,-1);
     glVertex3f (-lx,-ly,-lz);
     glVertex3f (-lx,ly,-lz);
     glVertex3f (lx,ly,-lz);
     glVertex3f (lx,-ly,-lz);
     glEnd();
 }
void CGraphics::_drawCapsule (dReal l, dReal r) private
Definition at line 953 of file graphics.cpp.
References capped_cylinder_quality, graphicDisabled, and velocity.pid_::i.
Referenced by drawCapsule().
 {
     if (graphicDisabled) return;
     int i,j;
     dReal tmp,nx,ny,nz,start_nx,start_ny,a,ca,sa;
     // number of sides to the cylinder (divisible by 4):
     const int n = capped_cylinder_quality*4;
     l *= 0.5;
     a = dReal(M_PI*2.0)/dReal(n);
     sa = (dReal) sin(a);
     ca = (dReal) cos(a);
     // draw cylinder body
     ny=1; nz=0;       // normal vector = (0,ny,nz)
     glBegin (GL_TRIANGLE_STRIP);
     for (i=0; i<=n; i++) {
         glNormal3d (ny,nz,0);
         glVertex3d (ny*r,nz*r,l);
         glNormal3d (ny,nz,0);
         glVertex3d (ny*r,nz*r,-l);
         // rotate ny,nz
         tmp = ca*ny - sa*nz;
         nz = sa*ny + ca*nz;
         ny = tmp;
     }
     glEnd();
     // draw first cylinder cap
     start_nx = 0;
     start_ny = 1;
     for (j=0; j<(n/4); j++) {
         // get start_n2 = rotated start_n
         dReal start_nx2 =  ca*start_nx + sa*start_ny;
         dReal start_ny2 = -sa*start_nx + ca*start_ny;
         // get n=start_n and n2=start_n2
         nx = start_nx; ny = start_ny; nz = 0;
         dReal nx2 = start_nx2, ny2 = start_ny2, nz2 = 0;
         glBegin (GL_TRIANGLE_STRIP);
         for (i=0; i<=n; i++) {
             glNormal3d (ny2,nz2,nx2);
             glVertex3d (ny2*r,nz2*r,l+nx2*r);
             glNormal3d (ny,nz,nx);
             glVertex3d (ny*r,nz*r,l+nx*r);
             // rotate n,n2
             tmp = ca*ny - sa*nz;
             nz = sa*ny + ca*nz;
             ny = tmp;
             tmp = ca*ny2- sa*nz2;
             nz2 = sa*ny2 + ca*nz2;
             ny2 = tmp;
         }
         glEnd();
         start_nx = start_nx2;
         start_ny = start_ny2;
     }
     // draw second cylinder cap
     start_nx = 0;
     start_ny = 1;
     for (j=0; j<(n/4); j++) {
         // get start_n2 = rotated start_n
         dReal start_nx2 = ca*start_nx - sa*start_ny;
         dReal start_ny2 = sa*start_nx + ca*start_ny;
         // get n=start_n and n2=start_n2
         nx = start_nx; ny = start_ny; nz = 0;
         dReal nx2 = start_nx2, ny2 = start_ny2, nz2 = 0;
         glBegin (GL_TRIANGLE_STRIP);
         for (i=0; i<=n; i++) {
             glNormal3d (ny,nz,nx);
             glVertex3d (ny*r,nz*r,-l+nx*r);
             glNormal3d (ny2,nz2,nx2);
             glVertex3d (ny2*r,nz2*r,-l+nx2*r);
             // rotate n,n2
             tmp = ca*ny - sa*nz;
             nz = sa*ny + ca*nz;
             ny = tmp;
             tmp = ca*ny2- sa*nz2;
             nz2 = sa*ny2 + ca*nz2;
             ny2 = tmp;
         }
         glEnd();
         start_nx = start_nx2;
         start_ny = start_ny2;
     }
 }
void CGraphics::_drawCylinder (dReal l, dReal r, dReal zoffset) private
Definition at line 1041 of file graphics.cpp.
References graphicDisabled, and velocity.pid_::i.
Referenced by drawCylinder().
 {
     if (graphicDisabled) return;
     int i;
     dReal tmp,ny,nz,a,ca,sa;
     const int n = 24;   // number of sides to the cylinder (divisible by 4)
     l *= 0.5;
     a = dReal(M_PI*2.0)/dReal(n);
     sa = (dReal) sin(a);
     ca = (dReal) cos(a);
     // draw cylinder body
     ny=1; nz=0;       // normal vector = (0,ny,nz)
     glBegin (GL_TRIANGLE_STRIP);
     for (i=0; i<=n; i++) {
         glNormal3d (ny,nz,0);
         glVertex3d (ny*r,nz*r,l+zoffset);
         glNormal3d (ny,nz,0);
         glVertex3d (ny*r,nz*r,-l+zoffset);
         // rotate ny,nz
         tmp = ca*ny - sa*nz;
         nz = sa*ny + ca*nz;
         ny = tmp;
     }
     glEnd();
     // draw top cap
     glShadeModel (GL_FLAT);
     ny=1; nz=0;       // normal vector = (0,ny,nz)
     glBegin (GL_TRIANGLE_FAN);
     glNormal3d (0,0,1);
     glVertex3d (0,0,l+zoffset);
     for (i=0; i<=n; i++) {
         glNormal3d (0,0,1);
         glVertex3d (ny*r,nz*r,l+zoffset);
         // rotate ny,nz
         tmp = ca*ny - sa*nz;
         nz = sa*ny + ca*nz;
         ny = tmp;
     }
     glEnd();
     // draw bottom cap
     ny=1; nz=0;       // normal vector = (0,ny,nz)
     glBegin (GL_TRIANGLE_FAN);
     glNormal3d (0,0,-1);
     glVertex3d (0,0,-l+zoffset);
     for (i=0; i<=n; i++) {
         glNormal3d (0,0,-1);
         glVertex3d (ny*r,nz*r,-l+zoffset);
         // rotate ny,nz
         tmp = ca*ny + sa*nz;
         nz = -sa*ny + ca*nz;
         ny = tmp;
     }
     glEnd();
 }
void CGraphics::_drawCylinder_TopTextured (dReal l, dReal r, dReal zoffset, int tex_id, bool robot = false) private
Definition at line 1100 of file graphics.cpp.
References graphicDisabled, velocity.pid_::i, noTexture(), and useTexture().
Referenced by drawCylinder_TopTextured().
 {
     //glEnable(GL_BLEND);
     //glBlendFunc(GL_SRC_COLOR,GL_ONE_MINUS_SRC_COLOR);
     if (graphicDisabled) return;
     int i;
     dReal tmp,ny,nz,a,ca,sa;
     const int n = 24;   // number of sides to the cylinder (divisible by 4)
     l *= 0.5;
     a = dReal(M_PI*2.0)/dReal(n);
     sa = (dReal) sin(a);
     ca = (dReal) cos(a);
     // draw cylinder body
     ny=1; nz=0;       // normal vector = (0,ny,nz)
     glBegin (GL_TRIANGLE_STRIP);
     for (i=0; i<=n; i++) {
         if ((i>2 && i<n-2) || (!robot)) {
             glNormal3d (ny,nz,0);
             glVertex3d (ny*r,nz*r,l+zoffset);
             glNormal3d (ny,nz,0);
             glVertex3d (ny*r,nz*r,-l+zoffset);
         }
         // rotate ny,nz
         tmp = ca*ny - sa*nz;
         nz = sa*ny + ca*nz;
         ny = tmp;
     }
     for (i=0;i<=1;i++) {
         tmp = ca*ny - sa*nz;
         nz = sa*ny + ca*nz;
         ny = tmp;
     }
     glNormal3d (ny,nz,0);
     glVertex3d (ny*r,nz*r,l+zoffset);
     glNormal3d (ny,nz,0);
     glVertex3d (ny*r,nz*r,-l+zoffset);
     glEnd();
     glDisable(GL_LIGHTING);
     useTexture(tex_id);
     // draw top cap
     glShadeModel (GL_FLAT);
     ny=1; nz=0;       // normal vector = (0,ny,nz)
     glBegin (GL_TRIANGLE_FAN);
     for (i=0; i<n; i++) {
         if ((i>2 && i<n-2)  || (!robot)) {
             glNormal3d (0,0,1);
             glTexCoord2f(-0.5*nz+0.5,0.5*ny+0.5);
             glVertex3d (ny*r,nz*r,l+zoffset);
         }
         // rotate ny,nz
         tmp = ca*ny - sa*nz;
         nz = sa*ny + ca*nz;
         ny = tmp;
     }
     glEnd();
     noTexture();
     glEnable(GL_LIGHTING);
     // draw bottom cap
     ny=1; nz=0;       // normal vector = (0,ny,nz)
     glBegin (GL_TRIANGLE_FAN);
     glNormal3d (0,0,-1);
     glVertex3d (0,0,-l+zoffset);
     for (i=0; i<=n; i++) {
         if ((i>=2 && i<n-2)  || (!robot)) {
             glNormal3d (0,0,-1);
             glVertex3d (ny*r,nz*r,-l+zoffset);
         }
         // rotate ny,nz
         tmp = ca*ny + sa*nz;
         nz = -sa*ny + ca*nz;
         ny = tmp;
     }
     glEnd();
     //glDisable(GL_BLEND);
 }
void CGraphics::_drawPatch (dReal p1[3], dReal p2[3], dReal p3[3], int level) private
Definition at line 839 of file graphics.cpp.
References velocity.pid_::i.
Referenced by _drawSphere().
 {
     int i;
     if (level > 0) {
         dReal q1[3],q2[3],q3[3];         // sub-vertices
         for (i=0; i<3; i++) {
             q1[i] = 0.5f*(p1[i]+p2[i]);
             q2[i] = 0.5f*(p2[i]+p3[i]);
             q3[i] = 0.5f*(p3[i]+p1[i]);
         }
         dReal length1 = (dReal)(1.0/sqrt(q1[0]*q1[0]+q1[1]*q1[1]+q1[2]*q1[2]));
         dReal length2 = (dReal)(1.0/sqrt(q2[0]*q2[0]+q2[1]*q2[1]+q2[2]*q2[2]));
         dReal length3 = (dReal)(1.0/sqrt(q3[0]*q3[0]+q3[1]*q3[1]+q3[2]*q3[2]));
         for (i=0; i<3; i++) {
             q1[i] *= length1;
             q2[i] *= length2;
             q3[i] *= length3;
         }
         _drawPatch (p1,q1,q3,level-1);
         _drawPatch (q1,p2,q2,level-1);
         _drawPatch (q1,q2,q3,level-1);
         _drawPatch (q3,q2,p3,level-1);
     }
     else {
         glNormal3f (p1[0],p1[1],p1[2]);
         glVertex3f (p1[0],p1[1],p1[2]);
         glNormal3f (p2[0],p2[1],p2[2]);
         glVertex3f (p2[0],p2[1],p2[2]);
         glNormal3f (p3[0],p3[1],p3[2]);
         glVertex3f (p3[0],p3[1],p3[2]);
     }
 }
void CGraphics::_drawSphere () private
Definition at line 903 of file graphics.cpp.
References _drawPatch(), graphicDisabled, velocity.pid_::i, idata, iindex, and sphere_quality.
Referenced by drawSphere().
 {
     if (graphicDisabled) return;
     static GLuint listnum = 0;
     if (listnum==0) {
         listnum = glGenLists (1);
         glNewList (listnum,GL_COMPILE);
         glBegin (GL_TRIANGLES);
         for (int i=0; i<20; i++) {
             _drawPatch (&idata[iindex[i][2]][0],&idata[iindex[i][1]][0],
                         &idata[iindex[i][0]][0],sphere_quality);
         }
         glEnd();
         glEndList();
     }
     glCallList (listnum);
 }
void CGraphics::cameraMotion (int mode, int deltax, int deltay)
Definition at line 184 of file graphics.cpp.
References graphicDisabled, view_hpr, view_xyz, and wrapCameraAngles().
Referenced by GLWidget::mouseMoveEvent().
 {
     if (graphicDisabled) return;
     dReal side = 0.01f * dReal(deltax);
     dReal fwd = (mode==4) ? (0.01f * dReal(deltay)) : 0.0f;
     dReal s = (dReal) sin (view_hpr[0]*M_PI/180.0f);
     dReal c = (dReal) cos (view_hpr[0]*M_PI/180.0f);
     if (mode==1) {
         view_hpr[0] += dReal (deltax) * 0.5f;
         view_hpr[1] += dReal (deltay) * 0.5f;
     }
     else {
         view_xyz[0] += -s*side + c*fwd;
         view_xyz[1] += c*side + s*fwd;
         if (mode==2 || mode==5) view_xyz[2] += 0.01f * dReal(deltay);
     }
     wrapCameraAngles();
 }
void CGraphics::disableGraphics ()
Definition at line 58 of file graphics.cpp.
References graphicDisabled.
Referenced by SSLWorld::step().
 {
     graphicDisabled = true;
 }
void CGraphics::drawBox (const dReal pos[3], const dReal R[12], const dReal sides[3])
Definition at line 1185 of file graphics.cpp.
References _drawBox(), graphicDisabled, and setTransform().
Referenced by PFixedBox::draw(), and PBox::draw().
 {
     if (graphicDisabled) return;
     glShadeModel (GL_FLAT);
     setTransform (pos,R);
     _drawBox (sides);
     glPopMatrix();
 }
void CGraphics::drawCapsule (const dReal pos[3], const dReal R[12], dReal length, dReal radius)
Definition at line 1231 of file graphics.cpp.
References _drawCapsule(), graphicDisabled, and setTransform().
 {
     if (graphicDisabled) return;
     glShadeModel (GL_SMOOTH);
     setTransform (pos,R);
     _drawCapsule (length,radius);
     glPopMatrix();
 }
void CGraphics::drawCircle (dReal x0, dReal y0, dReal z0, dReal r)
Definition at line 925 of file graphics.cpp.
References graphicDisabled, and velocity.pid_::i.
Referenced by SSLWorld::step().
 {
     if (graphicDisabled) return;
     int i;
     dReal tmp,ny,nz,a,ca,sa;
     const int n = 24;   // number of sides to the cylinder (divisible by 4)
     a = dReal(M_PI*2.0)/dReal(n);
     sa = (dReal) sin(a);
     ca = (dReal) cos(a);
     // draw top cap
     glShadeModel (GL_FLAT);
     ny=1; nz=0;       // normal vector = (0,ny,nz)
     glBegin (GL_TRIANGLE_FAN);
     glNormal3d (0,0,1);
     for (i=0; i<=n; i++) {
         glNormal3d (0,0,1);
         glVertex3d (ny*r+x0,nz*r+y0,z0);
         // rotate ny,nz
         tmp = ca*ny - sa*nz;
         nz = sa*ny + ca*nz;
         ny = tmp;
     }
     glEnd();
 }
void CGraphics::drawCylinder (const dReal pos[3], const dReal R[12], dReal length, dReal radius)
Definition at line 1211 of file graphics.cpp.
References _drawCylinder(), graphicDisabled, and setTransform().
Referenced by PCylinder::draw().
 {
     if (graphicDisabled) return;
     glShadeModel (GL_SMOOTH);
     setTransform (pos,R);
     _drawCylinder (length,radius,0);
     glPopMatrix();
 }
void CGraphics::drawCylinder_TopTextured (const dReal pos[3], const dReal R[12], dReal length, dReal radius, int tex_id, bool robot = false)
Definition at line 1221 of file graphics.cpp.
References _drawCylinder_TopTextured(), graphicDisabled, and setTransform().
Referenced by PCylinder::draw().
 {
     if (graphicDisabled) return;
     glShadeModel (GL_SMOOTH);
     setTransform (pos,R);
     _drawCylinder_TopTextured (length,radius,0,tex_id,robot);
     glPopMatrix();
 }
void CGraphics::drawGround ()
Definition at line 587 of file graphics.cpp.
References graphicDisabled, ground_ofsx, ground_ofsy, ground_scale, and resetState().
Referenced by PGround::draw().
 {
     if (graphicDisabled) return;
     glDisable (GL_LIGHTING);
     glShadeModel (GL_FLAT);
     glEnable (GL_DEPTH_TEST);
     glDepthFunc (GL_LESS);
     const dReal gsize = 100.0f;
     const dReal offset = 0;
     glBegin (GL_QUADS);
     glNormal3f (0,0,1);
     glTexCoord2f (-gsize*ground_scale + ground_ofsx,
                   -gsize*ground_scale + ground_ofsy);
     glVertex3f (-gsize,-gsize,offset);
     glTexCoord2f (gsize*ground_scale + ground_ofsx,
                   -gsize*ground_scale + ground_ofsy);
     glVertex3f (gsize,-gsize,offset);
     glTexCoord2f (gsize*ground_scale + ground_ofsx,
                   gsize*ground_scale + ground_ofsy);
     glVertex3f (gsize,gsize,offset);
     glTexCoord2f (-gsize*ground_scale + ground_ofsx,
                   gsize*ground_scale + ground_ofsy);
     glVertex3f (-gsize,gsize,offset);
     glEnd();
     resetState();
 }
void CGraphics::drawLine (const dReal pos1[3], const dReal pos2[3])
Definition at line 1243 of file graphics.cpp.
References graphicDisabled.
 {
     if (graphicDisabled) return;
     glDisable (GL_LIGHTING);
     glLineWidth (2);
     glShadeModel (GL_FLAT);
     glBegin (GL_LINES);
     glVertex3f (pos1[0],pos1[1],pos1[2]);
     glVertex3f (pos2[0],pos2[1],pos2[2]);
     glEnd();
 }
void CGraphics::drawSky ()
Definition at line 546 of file graphics.cpp.
References graphicDisabled, resetState(), sky_height, sky_scale, view_xyz, and role._GoToPoint::x.
 {
     if (graphicDisabled) return;
     const dReal ssize = 1000.0f;
     dReal offset = 0.0f;
     dReal x = ssize*sky_scale;
     dReal z = view_xyz[2] + sky_height;
     glBegin (GL_QUADS);
     glNormal3f (0,0,-1);
     glTexCoord2f (-x+offset,-x+offset);
     glVertex3f (-ssize+view_xyz[0],-ssize+view_xyz[1],z);
     glTexCoord2f (-x+offset,x+offset);
     glVertex3f (-ssize+view_xyz[0],ssize+view_xyz[1],z);
     glTexCoord2f (x+offset,x+offset);
     glVertex3f (ssize+view_xyz[0],ssize+view_xyz[1],z);
     glTexCoord2f (x+offset,-x+offset);
     glVertex3f (ssize+view_xyz[0],-ssize+view_xyz[1],z);
     glEnd();
     //if (offset > 1) offset -= 1;//never read
     glDepthFunc (GL_LESS);
     glDepthRange (0,1);
     resetState();
 }
void CGraphics::drawSkybox (int t1, int t2, int t3, int t4, int t5, int t6)
Definition at line 296 of file graphics.cpp.
References graphicDisabled, m_renderDepth, tex_ids, and view_hpr.
Referenced by SSLWorld::step().
 {
     if (graphicDisabled) return;
     // Store the current matrix
     glPushMatrix();
     glLoadIdentity();
     glRotatef (90, 0,0,1);
     glRotatef (90, 0,1,0);
     glRotatef (view_hpr[2], 1,0,0);
     glRotatef (view_hpr[1], 0,1,0);
     glRotatef (-view_hpr[0], 0,0,1);
     glScalef (m_renderDepth,m_renderDepth,m_renderDepth);
     // Enable/Disable features
     glPushAttrib(GL_ENABLE_BIT);
     glEnable(GL_TEXTURE_2D);
     glShadeModel (GL_FLAT);
     glDisable(GL_LIGHTING);
     glDisable(GL_LIGHT0);
     glDisable(GL_BLEND);
     glDisable(GL_CULL_FACE);
     // Just in case we set all vertices to white.
     glColor4f(1,1,1,1);
     const dReal r = 1.005f;  //to overcome borders problem
     // neg_x / right
     glBindTexture(GL_TEXTURE_2D, tex_ids[t1]);
     glBegin(GL_QUADS);
     glTexCoord2f(0, 0); glVertex3f( -0.5f, -0.5f*r, -0.5f*r);
     glTexCoord2f(1, 0); glVertex3f( -0.5f,  0.5f*r, -0.5f*r);
     glTexCoord2f(1, 1); glVertex3f( -0.5f,  0.5f*r,  0.5f*r);
     glTexCoord2f(0, 1); glVertex3f( -0.5f, -0.5f*r,  0.5f*r);
     glEnd();
     // pos_y / front
     glBindTexture(GL_TEXTURE_2D, tex_ids[t4]);
     glBegin(GL_QUADS);
     glTexCoord2f(0, 0); glVertex3f( -0.5f*r,  0.5f, -0.5f*r);
     glTexCoord2f(1, 0); glVertex3f(  0.5f*r,  0.5f, -0.5f*r);
     glTexCoord2f(1, 1); glVertex3f(  0.5f*r,  0.5f,  0.5f*r);
     glTexCoord2f(0, 1); glVertex3f( -0.5f*r,  0.5f,  0.5f*r);
     glEnd();
     // pos_x / left
     glBindTexture(GL_TEXTURE_2D, tex_ids[t2]);
     glBegin(GL_QUADS);
     glTexCoord2f(0, 0); glVertex3f(  0.5f,  0.5f*r, -0.5f*r);
     glTexCoord2f(1, 0); glVertex3f(  0.5f, -0.5f*r, -0.5f*r);
     glTexCoord2f(1, 1); glVertex3f(  0.5f, -0.5f*r,  0.5f*r);
     glTexCoord2f(0, 1); glVertex3f(  0.5f,  0.5f*r,  0.5f*r);
     glEnd();
     // neg_y / back
     glBindTexture(GL_TEXTURE_2D, tex_ids[t3]);
     glBegin(GL_QUADS);
     glTexCoord2f(0, 0); glVertex3f(  0.5f*r, -0.5f, -0.5f*r);
     glTexCoord2f(1, 0); glVertex3f( -0.5f*r, -0.5f, -0.5f*r);
     glTexCoord2f(1, 1); glVertex3f( -0.5f*r, -0.5f,  0.5f*r);
     glTexCoord2f(0, 1); glVertex3f(  0.5f*r, -0.5f,  0.5f*r);
     glEnd();
     // neg_z / down
     glBindTexture(GL_TEXTURE_2D, tex_ids[t5]);
     glBegin(GL_QUADS);
     glTexCoord2f(0, 0); glVertex3f( -0.5f*r, -0.5f*r, -0.5f);
     glTexCoord2f(1, 0); glVertex3f( -0.5f*r,  0.5f*r, -0.5f);
     glTexCoord2f(1, 1); glVertex3f(  0.5f*r,  0.5f*r, -0.5f);
     glTexCoord2f(0, 1); glVertex3f(  0.5f*r, -0.5f*r, -0.5f);
     glEnd();
     // pos_z / up
     glBindTexture(GL_TEXTURE_2D, tex_ids[t6]);
     glBegin(GL_QUADS);
     glTexCoord2f(0, 0); glVertex3f( -0.5f*r, -0.5f*r,  0.5f);
     glTexCoord2f(1, 0); glVertex3f( -0.5f*r,  0.5f*r,  0.5f);
     glTexCoord2f(1, 1); glVertex3f(  0.5f*r,  0.5f*r,  0.5f);
     glTexCoord2f(0, 1); glVertex3f(  0.5f*r, -0.5f*r,  0.5f);
     glEnd();
     // Restore enable bits and matrix
     glPopAttrib();
     glPopMatrix();
 }
void CGraphics::drawSphere (const dReal pos[3], const dReal R[12], dReal radius)
Definition at line 1197 of file graphics.cpp.
References _drawSphere(), graphicDisabled, and setTransform().
Referenced by PBall::draw().
 {
     if (graphicDisabled) return;
     glEnable (GL_NORMALIZE);
     glShadeModel (GL_SMOOTH);
     setTransform (pos,R);
     glScaled (radius,radius,radius);
     _drawSphere();
     glPopMatrix();
     glDisable (GL_NORMALIZE);
 }
void CGraphics::drawSSLGround (dReal SSL_FIELD_RAD, dReal SSL_FIELD_LENGTH, dReal SSL_FIELD_WIDTH, dReal SSL_FIELD_PENALTY_RADIUS, dReal SSL_FIELD_PENALTY_LINE, dReal SSL_FIELD_PENALTY_POINT, dReal SSL_FIELD_LINE_WIDTH, dReal SSL_FIELD_DEFENSE_STRETCH, dReal SSL_FIELD_DEFENSE_RADIUS, dReal epsilon)
Definition at line 617 of file graphics.cpp.
References graphicDisabled.
Referenced by PGround::draw().
 {
     if (graphicDisabled) return;
     dReal angle;
     dReal fw = SSL_FIELD_LENGTH / 2.0;
     dReal fh = SSL_FIELD_WIDTH / 2.0;
     dReal lw = SSL_FIELD_LINE_WIDTH;
     dReal rad = SSL_FIELD_RAD;
     dReal drad = SSL_FIELD_DEFENSE_RADIUS;
     dReal ds = SSL_FIELD_DEFENSE_STRETCH / 2.0;
     dReal penx = SSL_FIELD_PENALTY_POINT;
     glEnable(GL_DEPTH_TEST);
     glPushMatrix();
     glScaled(1.0, 1.0, 1);
     glColor3f(1.0f,1.0f,1.0f);
     //Field rectangle
     glBegin(GL_QUADS);
     glVertex3f( fw - lw,  fh     , epsilon);
     glVertex3f( fw - lw, -fh + lw, epsilon);
     glVertex3f( fw     , -fh + lw, epsilon);
     glVertex3f( fw     ,  fh     , epsilon);
     glEnd();
     glBegin(GL_QUADS);
     glVertex3f( fw     , -fh + lw, epsilon);
     glVertex3f(-fw + lw, -fh + lw, epsilon);
     glVertex3f(-fw + lw, -fh     , epsilon);
     glVertex3f( fw     , -fh     , epsilon);
     glEnd();
     glBegin(GL_QUADS);
     glVertex3f(-fw + lw, -fh     , epsilon);
     glVertex3f(-fw + lw,  fh - lw, epsilon);
     glVertex3f(-fw     ,  fh - lw, epsilon);
     glVertex3f(-fw     , -fh     , epsilon);
     glEnd();
     glBegin(GL_QUADS);
     glVertex3f( fw - lw,  fh - lw, epsilon);
     glVertex3f( fw - lw,  fh     , epsilon);
     glVertex3f(-fw     ,  fh     , epsilon);
     glVertex3f(-fw     ,  fh - lw, epsilon);
     glEnd();
     //Middle line
     glBegin(GL_QUADS);
     glVertex3f( lw / 2,  fh - lw, epsilon);
     glVertex3f(-lw / 2,  fh - lw, epsilon);
     glVertex3f(-lw / 2, -fh + lw, epsilon);
     glVertex3f( lw / 2, -fh + lw, epsilon);
     glEnd();
     //Middle circle
     const float anglestep = M_PI/20.f;
     float cos1, cos2, sin1, sin2;
     cos1 = cos(-anglestep);
     sin1 = sin(-anglestep);
     for(angle = 0.0f; angle <= 2 * M_PI; angle += anglestep) {
         cos2 = cos(angle);
         sin2 = sin(angle);
         glBegin(GL_QUADS);
         glVertex3f(cos1 * (rad - lw), sin1 * (rad - lw), epsilon);
         glVertex3f(cos1 * rad       , sin1 * rad       , epsilon);
         glVertex3f(cos2 * rad       , sin2 * rad       , epsilon);
         glVertex3f(cos2 * (rad - lw), sin2 * (rad - lw), epsilon);
         glEnd();
         cos1 = cos2;
         sin1 = sin2;
     }
     //Left defense area
     cos1 = 0.0f, sin1 = -1.0f;
     for(angle = -M_PI / 2.0 + anglestep; angle < anglestep; angle += anglestep) {
         cos2 = cos(angle);
         sin2 = sin(angle);
         glBegin(GL_QUADS);
         glVertex3f(-fw + cos1 * (drad - lw), -ds + sin1 * (drad - lw), epsilon);
         glVertex3f(-fw + cos1 * drad       , -ds + sin1 * drad       , epsilon);
         glVertex3f(-fw + cos2 * drad       , -ds + sin2 * drad       , epsilon);
         glVertex3f(-fw + cos2 * (drad - lw), -ds + sin2 * (drad - lw), epsilon);
         glEnd();
         cos1 = cos2;
         sin1 = sin2;
     }
     glBegin(GL_QUADS);
     glVertex3f(-fw + drad     ,  ds, epsilon);
     glVertex3f(-fw + drad - lw,  ds, epsilon);
     glVertex3f(-fw + drad - lw, -ds, epsilon);
     glVertex3f(-fw + drad     , -ds, epsilon);
     glEnd();
     for(; angle < M_PI / 2.0 + anglestep; angle += anglestep) {
         cos2 = cos(angle);
         sin2 = sin(angle);
         glBegin(GL_QUADS);
         glVertex3f(-fw + cos1 * (drad - lw), ds + sin1 * (drad - lw), epsilon);
         glVertex3f(-fw + cos1 * drad       , ds + sin1 * drad       , epsilon);
         glVertex3f(-fw + cos2 * drad       , ds + sin2 * drad       , epsilon);
         glVertex3f(-fw + cos2 * (drad - lw), ds + sin2 * (drad - lw), epsilon);
         glEnd();
         cos1 = cos2;
         sin1 = sin2;
     }
     //Right defense area
     for(; angle < M_PI + anglestep; angle += anglestep) {
         cos2 = cos(angle);
         sin2 = sin(angle);
         glBegin(GL_QUADS);
         glVertex3f(fw + cos1 * (drad - lw), ds + sin1 * (drad - lw), epsilon);
         glVertex3f(fw + cos1 * drad       , ds + sin1 * drad       , epsilon);
         glVertex3f(fw + cos2 * drad       , ds + sin2 * drad       , epsilon);
         glVertex3f(fw + cos2 * (drad - lw), ds + sin2 * (drad - lw), epsilon);
         glEnd();
         cos1 = cos2;
         sin1 = sin2;
     }
     glBegin(GL_QUADS);
     glVertex3f(fw - drad     , -ds, epsilon);
     glVertex3f(fw - drad + lw, -ds, epsilon);
     glVertex3f(fw - drad + lw,  ds, epsilon);
     glVertex3f(fw - drad     ,  ds, epsilon);
     glEnd();
     for(; angle < 1.5 * M_PI + anglestep; angle += anglestep) {
         cos2 = cos(angle);
         sin2 = sin(angle);
         glBegin(GL_QUADS);
         glVertex3f(fw + cos1 * (drad - lw), -ds + sin1 * (drad - lw), epsilon);
         glVertex3f(fw + cos1 * drad       , -ds + sin1 * drad       , epsilon);
         glVertex3f(fw + cos2 * drad       , -ds + sin2 * drad       , epsilon);
         glVertex3f(fw + cos2 * (drad - lw), -ds + sin2 * (drad - lw), epsilon);
         glEnd();
         cos1 = cos2;
         sin1 = sin2;
     }
     //Penalty spots
     glBegin(GL_POLYGON);
     for(angle=0.0f; angle <= 2.0 * M_PI; angle+=anglestep)
         glVertex3f(-fw + penx + cos(angle) * lw, 0.0f + sin(angle) * lw, epsilon);
     glEnd();
     glBegin(GL_POLYGON);
     for(angle=0.0f; angle <= 2.0 * M_PI; angle+=anglestep)
         glVertex3f(fw - penx + cos(angle) * lw, 0.0f + sin(angle) * lw, epsilon);
     glEnd();
     glPopMatrix();
 }
void CGraphics::enableGraphics ()
Definition at line 63 of file graphics.cpp.
References graphicDisabled.
Referenced by SSLWorld::step().
 {
     graphicDisabled = false;
 }
void CGraphics::finalizeScene ()
Definition at line 541 of file graphics.cpp.
Referenced by SSLWorld::step().
 {
     //owner->swapBuffers();
 }
void CGraphics::getCameraForward (dReal & x, dReal & y, dReal & z)
Definition at line 214 of file graphics.cpp.
References rotxy(), and view_hpr.
Referenced by Robot::drawLabel(), GLWidget::update3DCursor(), and zoomCamera().
 {
     dReal h = view_hpr[0]*M_PI/180.0f;
     dReal p = view_hpr[1]*M_PI/180.0f;
     dReal r = view_hpr[2]*M_PI/180.0f;
     x=-1; y=0; z=0;
     rotxy(y,z,r);
     rotxy(z,x,-p);
     rotxy(x,y,h);
 }
void CGraphics::getCameraRight (dReal & x, dReal & y, dReal & z)
Definition at line 240 of file graphics.cpp.
References rotxy(), and view_hpr.
Referenced by Robot::drawLabel(), and GLWidget::update3DCursor().
 {
     dReal h = view_hpr[0]*M_PI/180.0f;
     dReal p = view_hpr[1]*M_PI/180.0f;
     dReal r = view_hpr[2]*M_PI/180.0f;
     x=0; y=-1; z=0;
     rotxy(y,z,r);
     rotxy(z,x,-p);
     rotxy(x,y,h);
 }
void CGraphics::getFrustum (dReal & right, dReal & bottom, dReal & vnear)
Definition at line 133 of file graphics.cpp.
References frustum_bottom, frustum_right, and frustum_vnear.
Referenced by Robot::drawLabel(), and GLWidget::update3DCursor().
 {
     right = frustum_right;
     bottom= frustum_bottom;
     vnear = frustum_vnear;
 }
int CGraphics::getHeight ()
Definition at line 536 of file graphics.cpp.
References _height.
Referenced by Robot::drawLabel().
 {
     return _height;
 }
void CGraphics::getViewpoint (dReal * xyz, dReal * hpr)
Definition at line 122 of file graphics.cpp.
References graphicDisabled, view_hpr, and view_xyz.
Referenced by GLWidget::changeCameraMode(), Robot::drawLabel(), SSLWorld::step(), and GLWidget::update3DCursor().
 {
     if (graphicDisabled) return;
     xyz[0] = view_xyz[0];
     xyz[1] = view_xyz[1];
     xyz[2] = view_xyz[2];
     hpr[0] = view_hpr[0];
     hpr[1] = view_hpr[1];
     hpr[2] = view_hpr[2];
 }
int CGraphics::getWidth ()
Definition at line 531 of file graphics.cpp.
References _width.
Referenced by Robot::drawLabel().
 {
     return _width;
 }
void CGraphics::initScene (int width, int height, dReal rc, dReal gc, dReal bc, bool fog = false, dReal fogr = 0.6, dReal fogg = 0.6, dReal fogb = 0.6, dReal fogdensity = 0.6)
Definition at line 442 of file graphics.cpp.
References _height, _width, frustum_bottom, frustum_right, frustum_vnear, graphicDisabled, k, LIGHTX, LIGHTY, m_renderDepth, setCamera(), view_hpr, and view_xyz.
Referenced by SSLWorld::step().
 {
     if (graphicDisabled) return;
     _width = width;
     _height = height;
     //glEnable(GL_POLYGON_SMOOTH);
     //glEnable(GL_LINE_SMOOTH);
     //glEnable(GL_POINT_SMOOTH);
     //glHint(GL_POINT_SMOOTH_HINT,GL_NICEST);
     //glHint(GL_POLYGON_SMOOTH_HINT,GL_NICEST);
     //glHint(GL_LINE_SMOOTH_HINT,GL_NICEST);
     //glEnable(GL_MULTISAMPLE);
     // setup stuff
     glEnable (GL_LIGHTING);
     glEnable (GL_LIGHT0);
     glDisable (GL_TEXTURE_2D);
     glDisable (GL_TEXTURE_GEN_S);
     glDisable (GL_TEXTURE_GEN_T);
     glShadeModel (GL_FLAT);
     glEnable (GL_DEPTH_TEST);
     glDepthFunc (GL_LESS);
     glEnable (GL_CULL_FACE);
     glCullFace (GL_BACK);
     glFrontFace (GL_CCW);
     // setup viewport
     glViewport (0,0,width,height);
     glMatrixMode (GL_PROJECTION);
     glLoadIdentity();
     const dReal vnear = 0.1f;
     const dReal vfar = m_renderDepth;
     const dReal k = 0.8f;     // view scale, 1 = +/- 45 degrees
     frustum_vnear = vnear;
     if (width >= height) {
         dReal k2 = dReal(height)/dReal(width);
         frustum_right  = vnear*k;
         frustum_bottom = vnear*k*k2;
     }
     else {
         dReal k2 = dReal(width)/dReal(height);
         frustum_right  = vnear*k*k2;
         frustum_bottom = vnear*k;
     }
     glFrustum (-frustum_right,frustum_right,-frustum_bottom,frustum_bottom,vnear,vfar);
     // setup lights. it makes a difference whether this is done in the
     // GL_PROJECTION matrix mode (lights are scene relative) or the
     // GL_MODELVIEW matrix mode (lights are camera relative, bad!).
     static const GLfloat light_ambient[] = { 0.5, 0.5, 0.5, 1.0 };
     static const GLfloat light_diffuse[] = { 1.0, 1.0, 1.0, 1.0 };
     static const GLfloat light_specular[] = { 1.0, 1.0, 1.0, 1.0 };
     glLightfv (GL_LIGHT0, GL_AMBIENT, light_ambient);
     glLightfv (GL_LIGHT0, GL_DIFFUSE, light_diffuse);
     glLightfv (GL_LIGHT0, GL_SPECULAR, light_specular);
     glColor3f (1.0, 1.0, 1.0);
     // clear the window
     glClearColor (rc,gc,bc,1);
     glClear (GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     // snapshot camera position (in MS Windows it is changed by the GUI thread)
     dReal view2_xyz[3];
     dReal view2_hpr[3];
     memcpy (view2_xyz,view_xyz,sizeof(dReal)*3);
     memcpy (view2_hpr,view_hpr,sizeof(dReal)*3);
     // go to GL_MODELVIEW matrix mode and set the camera
     glMatrixMode (GL_MODELVIEW);
     glLoadIdentity();
     setCamera (view2_xyz[0],view2_xyz[1],view2_xyz[2],
                view2_hpr[0],view2_hpr[1],view2_hpr[2]);
     // set the light position (for some reason we have to do this in model view.
     static GLfloat light_position[] = { LIGHTX, LIGHTY, 1.0, 0.0 };
     glLightfv (GL_LIGHT0, GL_POSITION, light_position);
     if (fog) {
         GLfloat fogColor [4] = {fogr,fogg,fogb,1};
         glFogi (GL_FOG_MODE, GL_EXP2); //set the fog mode to GL_EXP2
         glFogf(GL_FOG_START,5);
         glFogf(GL_FOG_END,10);
         glFogfv (GL_FOG_COLOR, fogColor); //set the fog color to our color chosen above
         glFogf (GL_FOG_DENSITY, fogdensity); //set the density to the value above
         //glHint (GL_FOG_HINT, GL_NICEST); // set the fog to look the nicest, may slow down on older cards
     }
 }
bool CGraphics::isGraphicsEnabled ()
Definition at line 68 of file graphics.cpp.
References graphicDisabled.
Referenced by GLWidget::mouseMoveEvent(), GLWidget::mousePressEvent(), GLWidget::paintGL(), SSLWorld::step(), MainWindow::update(), GLWidget::update3DCursor(), and GLWidget::wheelEvent().
 {
     return !graphicDisabled;
 }
int CGraphics::loadTexture (QImage * img)
Definition at line 74 of file graphics.cpp.
References graphicDisabled, owner, and tex_ids.
Referenced by SSLWorld::glinit().
 {
     if (graphicDisabled) return -1;
     GLuint id;
     glEnable(GL_TEXTURE_2D);
     glGenTextures(1, &id);
     id = owner->bindTexture(*img);
     tex_ids.append(id);
     return tex_ids.size()-1;
 }
int CGraphics::loadTextureSkyBox (QImage * img)
Definition at line 86 of file graphics.cpp.
References graphicDisabled, velocity.pid_::i, and tex_ids.
 {
     if (graphicDisabled) return -1;
     GLuint id;
     glEnable(GL_TEXTURE_2D);
     glGenTextures(1, &id);
     glBindTexture(GL_TEXTURE_2D,id);
     glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_DECAL);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
     char* buffer=new char[img->width()*img->height()*4];
     int ofs = img->width()*4;
     for (int j=0;j<img->height();j++)
     {
         memcpy(buffer+j*ofs,img->scanLine(img->height()-1-j),ofs);
     }
     for (int j=0;j<img->height();j++)
     {
         for (int i=0;i<img->width();i++)
         {
             int p=j*ofs+i*4;
             char temp = buffer[p+2];
             buffer[p+2]=buffer[p];
             buffer[p]=temp;
         }
     }
     glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, img->width(), img->height(), 0, GL_RGBA,
                GL_UNSIGNED_BYTE, buffer);
     delete img;
     tex_ids.append(id);
     return tex_ids.size()-1;
 }
void CGraphics::lookAt (dReal x, dReal y, dReal z)
Definition at line 225 of file graphics.cpp.
References view_hpr, and view_xyz.
Referenced by GLWidget::paintGL().
 {
     dReal rx = x - view_xyz[0];
     dReal ry = y - view_xyz[1];
     dReal rz = z - view_xyz[2];
     dReal rr = sqrt(rx*rx + ry*ry + rz*rz);
     if (rr==0) return;
     dReal r = 0;
     dReal p = asin(rz/rr)*180.0/M_PI;
     dReal h = atan2(ry,rx)*180.0/M_PI;
     view_hpr[0] = h;
     view_hpr[1] = p;
     view_hpr[2] = r;
 }
void CGraphics::noTexture ()
Definition at line 388 of file graphics.cpp.
References graphicDisabled.
Referenced by _drawCylinder_TopTextured(), PGround::draw(), and Robot::drawLabel().
 {
     if (graphicDisabled) return;
     glDisable(GL_TEXTURE_2D);
 }
dReal CGraphics::renderDepth ()
Definition at line 145 of file graphics.cpp.
References m_renderDepth.
 {
     return m_renderDepth;
 }
void CGraphics::resetState ()
Definition at line 575 of file graphics.cpp.
References graphicDisabled, and setColor().
Referenced by drawGround(), and drawSky().
 {
     if (graphicDisabled) return;
     glEnable (GL_LIGHTING);
     glDisable (GL_TEXTURE_2D);
     glShadeModel (GL_FLAT);
     glEnable (GL_DEPTH_TEST);
     glDepthFunc (GL_LESS);
     glColor3f (1,1,1);
     setColor (1,1,1,1);
 }
void CGraphics::setCamera (dReal x, dReal y, dReal z, dReal h, dReal p, dReal r) private
Definition at line 260 of file graphics.cpp.
References graphicDisabled.
Referenced by initScene().
 {
     if (graphicDisabled) return;
     glMatrixMode (GL_MODELVIEW);
     glLoadIdentity();
     glRotatef(90, 0,0,1);
     glRotatef(90, 0,1,0);
     glRotatef( r, 1,0,0);
     glRotatef( p, 0,1,0);
     glRotatef(-h, 0,0,1);
     glTranslatef(-x,-y,-z);
 }
void CGraphics::setColor (dReal r, dReal g, dReal b, dReal alpha)
Definition at line 274 of file graphics.cpp.
References graphicDisabled.
Referenced by PObject::draw(), resetState(), and SSLWorld::step().
 {
     if (graphicDisabled) return;
     GLfloat light_ambient[4],light_diffuse[4],light_specular[4];
     light_ambient[0] = r*0.3f;
     light_ambient[1] = g*0.3f;
     light_ambient[2] = b*0.3f;
     light_ambient[3] = alpha;
     light_diffuse[0] = r*0.7f;
     light_diffuse[1] = g*0.7f;
     light_diffuse[2] = b*0.7f;
     light_diffuse[3] = alpha;
     light_specular[0] = r*0.2f;
     light_specular[1] = g*0.2f;
     light_specular[2] = b*0.2f;
     light_specular[3] = alpha;
     glMaterialfv (GL_FRONT_AND_BACK, GL_AMBIENT, light_ambient);
     glMaterialfv (GL_FRONT_AND_BACK, GL_DIFFUSE, light_diffuse);
     glMaterialfv (GL_FRONT_AND_BACK, GL_SPECULAR, light_specular);
     glMaterialf (GL_FRONT_AND_BACK, GL_SHININESS, 5.0f);
 }
void CGraphics::setRenderDepth (dReal depth)
Definition at line 140 of file graphics.cpp.
References m_renderDepth.
 {
     m_renderDepth = depth;
 }
void CGraphics::setShadow (bool state)
void CGraphics::setSphereQuality (int q)
Definition at line 73 of file graphics.cpp.
References sphere_quality.
Referenced by SSLWorld::SSLWorld().
 {sphere_quality = q;}
void CGraphics::setTransform (const dReal pos[3], const dReal R[12])
Definition at line 394 of file graphics.cpp.
References graphicDisabled.
Referenced by drawBox(), drawCapsule(), drawCylinder(), drawCylinder_TopTextured(), Robot::drawLabel(), and drawSphere().
 {
     if (graphicDisabled) return;
     GLfloat matrix[16];
     matrix[0]=R[0];
     matrix[1]=R[4];
     matrix[2]=R[8];
     matrix[3]=0;
     matrix[4]=R[1];
     matrix[5]=R[5];
     matrix[6]=R[9];
     matrix[7]=0;
     matrix[8]=R[2];
     matrix[9]=R[6];
     matrix[10]=R[10];
     matrix[11]=0;
     matrix[12]=pos[0];
     matrix[13]=pos[1];
     matrix[14]=pos[2];
     matrix[15]=1;
     glPushMatrix();
     glMultMatrixf (matrix);
 }
void CGraphics::setTransformD (const double pos[3], const double R[12])
Definition at line 418 of file graphics.cpp.
References graphicDisabled.
 {
     if (graphicDisabled) return;
     GLdouble matrix[16];
     matrix[0]=R[0];
     matrix[1]=R[4];
     matrix[2]=R[8];
     matrix[3]=0;
     matrix[4]=R[1];
     matrix[5]=R[5];
     matrix[6]=R[9];
     matrix[7]=0;
     matrix[8]=R[2];
     matrix[9]=R[6];
     matrix[10]=R[10];
     matrix[11]=0;
     matrix[12]=pos[0];
     matrix[13]=pos[1];
     matrix[14]=pos[2];
     matrix[15]=1;
     glPushMatrix();
     glMultMatrixd (matrix);
 }
void CGraphics::setViewpoint (dReal xyz[3], dReal hpr[3])
Definition at line 150 of file graphics.cpp.
References view_hpr, view_xyz, and wrapCameraAngles().
Referenced by CGraphics(), GLWidget::changeCameraMode(), GLWidget::paintGL(), and SSLWorld::SSLWorld().
 {
     if (xyz) {
         view_xyz[0] = xyz[0];
         view_xyz[1] = xyz[1];
         view_xyz[2] = xyz[2];
     }
     if (hpr) {
         view_hpr[0] = hpr[0];
         view_hpr[1] = hpr[1];
         view_hpr[2] = hpr[2];
         wrapCameraAngles();
     }
 }
void CGraphics::setViewpoint (dReal x, dReal y, dReal z, dReal h, dReal p, dReal r)
Definition at line 165 of file graphics.cpp.
References view_hpr, view_xyz, wrapCameraAngles(), role._GoToPoint::x, and role._GoToPoint::y.
 {
     view_xyz[0] = x;
     view_xyz[1] = y;
     view_xyz[2] = z;
     view_hpr[0] = h;
     view_hpr[1] = p;
     view_hpr[2] = r;
     wrapCameraAngles();
 }
void CGraphics::useTexture (int tex_id)
Definition at line 381 of file graphics.cpp.
References graphicDisabled, and tex_ids.
Referenced by _drawCylinder_TopTextured(), PGround::draw(), and Robot::drawLabel().
 {
     if (graphicDisabled) return;
     glEnable (GL_TEXTURE_2D);
     glBindTexture(GL_TEXTURE_2D, tex_ids[tex_id]);
 }
void CGraphics::wrapCameraAngles () private
Definition at line 176 of file graphics.cpp.
References velocity.pid_::i, and view_hpr.
Referenced by cameraMotion(), and setViewpoint().
 {
     for (int i=0; i<3; i++) {
         while (view_hpr[i] > 180) view_hpr[i] -= 360;
         while (view_hpr[i] < -180) view_hpr[i] += 360;
     }
 }
void CGraphics::zoomCamera (dReal dz)
Definition at line 251 of file graphics.cpp.
References getCameraForward(), and view_xyz.
Referenced by GLWidget::wheelEvent().
 {
     dReal xx,yy,zz;
     getCameraForward(xx,yy,zz);
     view_xyz[0] += xx*dz;
     view_xyz[1] += yy*dz;
     view_xyz[2] += zz*dz;
 }
Field Documentation
int CGraphics::_height private
Definition at line 34 of file graphics.h.
Referenced by getHeight(), and initScene().
int CGraphics::_width private
Definition at line 34 of file graphics.h.
Referenced by getWidth(), and initScene().
dReal CGraphics::frustum_bottom private
Definition at line 33 of file graphics.h.
Referenced by getFrustum(), and initScene().
dReal CGraphics::frustum_right private
Definition at line 33 of file graphics.h.
Referenced by getFrustum(), and initScene().
dReal CGraphics::frustum_vnear private
Definition at line 33 of file graphics.h.
Referenced by getFrustum(), and initScene().
bool CGraphics::graphicDisabled private
Definition at line 45 of file graphics.h.
Referenced by _drawBox(), _drawCapsule(), _drawCylinder(), _drawCylinder_TopTextured(), _drawSphere(), cameraMotion(), CGraphics(), disableGraphics(), drawBox(), drawCapsule(), drawCircle(), drawCylinder(), drawCylinder_TopTextured(), drawGround(), drawLine(), drawSky(), drawSkybox(), drawSphere(), drawSSLGround(), enableGraphics(), getViewpoint(), initScene(), isGraphicsEnabled(), loadTexture(), loadTextureSkyBox(), noTexture(), resetState(), setCamera(), setColor(), setTransform(), setTransformD(), and useTexture().
dReal CGraphics::m_renderDepth private
Definition at line 33 of file graphics.h.
Referenced by CGraphics(), drawSkybox(), initScene(), renderDepth(), and setRenderDepth().
QGLWidget* CGraphics::owner private
Definition at line 35 of file graphics.h.
Referenced by CGraphics(), and loadTexture().
int CGraphics::sphere_quality private
Definition at line 36 of file graphics.h.
Referenced by _drawSphere(), CGraphics(), and setSphereQuality().
QVector<GLuint> CGraphics::tex_ids private
Definition at line 32 of file graphics.h.
Referenced by drawSkybox(), loadTexture(), loadTextureSkyBox(), and useTexture().
dReal CGraphics::view_hpr[3] private
Definition at line 31 of file graphics.h.
Referenced by cameraMotion(), drawSkybox(), getCameraForward(), getCameraRight(), getViewpoint(), initScene(), lookAt(), setViewpoint(), and wrapCameraAngles().
dReal CGraphics::view_xyz[3] private
Definition at line 31 of file graphics.h.
Referenced by cameraMotion(), drawSky(), getViewpoint(), initScene(), lookAt(), setViewpoint(), and zoomCamera().
The documentation for this class was generated from the following files:
grSim/include/graphics.h
grSim/src/graphics.cpp