Documentation: VarTypes::VarStringVal Class Reference
VarTypes::VarStringVal Class Reference
This is the string VarTypeVal of the VarTypes system.
#include <VarStringVal.h>
Public Member Functions
VarStringVal (const string &default_val="")
virtual ~VarStringVal ()
virtual void printdebug () const
virtual VarTypeId getType () const
virtual string getString () const
virtual bool hasValue () const
virtual bool setString (const string &val)
virtual VarVal * clone () const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Protected Attributes
string _val
Additional Inherited Members
Protected Member Functions inherited from VarTypes::VarVal
virtual void lock () const
virtual void unlock () const
virtual void changed ()
Detailed Description
This is the string VarTypeVal of the VarTypes system.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 35 of file VarStringVal.h.
Constructor & Destructor Documentation
VarTypes::VarStringVal::VarStringVal (const string & default_val = "") inline
Definition at line 42 of file VarStringVal.h.
References VarTypes::VarVal::changed(), VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
Referenced by clone().
                                                 : VarVal()
     {
       lock();
       _val=default_val;
       unlock();
       changed();
     }
virtual VarTypes::VarStringVal::~VarStringVal () inline virtual
Definition at line 50 of file VarStringVal.h.
 {}
Member Function Documentation
virtual VarVal* VarTypes::VarStringVal::clone () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 64 of file VarStringVal.h.
References getString(), setString(), and VarStringVal().
{
       VarStringVal * tmp = new VarStringVal();
       tmp->setString(getString());
       return tmp;
     }
virtual string VarTypes::VarStringVal::getString () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 60 of file VarStringVal.h.
References _val, VarTypes::VarVal::lock(), VarTypes::VarVal::unlock(), and v.
Referenced by clone(), CMPattern::TeamDetector::init(), PluginDetectBalls::process(), MultiStackRoboCupSSL::RefreshLegacyNetworkOutput(), MultiStackRoboCupSSL::RefreshNetworkOutput(), FieldLine::Rename(), FieldCircularArc::Rename(), CMPattern::Team::slotTeamNameChanged(), CaptureFromFile::startCapture(), and RoboCupField::toProtoBuffer().
 { lock(); string v=_val; unlock(); return v;  };
virtual VarTypeId VarTypes::VarStringVal::getType () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 59 of file VarStringVal.h.
References VarTypes::VARTYPE_ID_STRING.
 { return VARTYPE_ID_STRING; };
virtual bool VarTypes::VarStringVal::hasValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 61 of file VarStringVal.h.
 { return false; };
virtual void VarTypes::VarStringVal::printdebug () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 52 of file VarStringVal.h.
References VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
     {
       lock();
       printf("%s\n",_val.c_str());
       unlock();
     }
virtual bool VarTypes::VarStringVal::setString (const string & val) inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 62 of file VarStringVal.h.
References VarTypes::VarVal::changed(), VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
Referenced by clone(), and VarTypes::VarString::resetToDefault().
 { lock(); if (_val!=val) {_val=val; unlock(); changed(); return true;} else { unlock(); return false;} };
Field Documentation
string VarTypes::VarStringVal::_val protected
Definition at line 39 of file VarStringVal.h.
Referenced by getString().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/vartypes/primitives/VarStringVal.h