Documentation: belief_state/src/bot_data.cpp File Reference
bot_data.cpp File Reference
#include <iostream>
#include "serial.h"
#include "ros/ros.h"
#include "std_msgs/"
Functions
const string port ("/dev/ttyUSB0")
int main (int argc, char **argv)
Variables
const int NUM_BYTES = 6
static unsigned char buf [NUM_BYTES]
HAL::Serial serial
Function Documentation
int main (int argc, char ** argv)
Definition at line 14 of file bot_data.cpp.
References buf, role._GoToPoint::init(), NUM_BYTES, HAL::Serial::Open(), port(), pub, and HAL::Serial::Read().
Referenced by Net::UDP::wait().
{
     if(!serial.Open(port.c_str(), baud_rate)) {
         cout << "Couldn't open the fucking port: " << port.c_str() << "\n";
     }
     ros::init(argc, argv, "bot_data");
     ros::NodeHandle nh;
     ros::Publisher pub = nh.advertise<>("/bot_IR_data", 10000);
     while (true) {
         serial.Read(buf, NUM_BYTES);
     }
 }
const string port ("/dev/ttyUSB0")
Referenced by RoboCupSSLServer::change_port(), RoboCupSSLClient::changePort(), main(), SSLWorld::recvActions(), RoboCupSSLClient::RoboCupSSLClient(), RoboCupSSLServer::RoboCupSSLServer(), MultiStackRoboCupSSL::UpdateServerSettings(), Net::UDP::wait(), Net::Address::~Address(), and Net::UDP::~UDP().
Variable Documentation
unsigned char buf[NUM_BYTES] static
Definition at line 9 of file bot_data.cpp.
Referenced by CallBack(), HAL::Serial::Close(), GLSoccerView::drawRobot(), main(), and VarTypes::XMLNode::parseFile().
const int NUM_BYTES = 6
Definition at line 7 of file bot_data.cpp.
Referenced by main().
HAL::Serial serial
Definition at line 11 of file bot_data.cpp.