Documentation: grSim_BallReplacement Class Reference
grSim_BallReplacement Class Reference
#include <grSim_Replacement.pb.h>
Public Member Functions
grSim_BallReplacement ()
virtual ~grSim_BallReplacement ()
grSim_BallReplacement (const grSim_BallReplacement &from)
grSim_BallReplacement & operator= (const grSim_BallReplacement &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (grSim_BallReplacement *other)
grSim_BallReplacement * New () const PROTOBUF_FINAL
grSim_BallReplacement * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const grSim_BallReplacement &from)
void MergeFrom (const grSim_BallReplacement &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_x () const
void clear_x ()
double x () const
void set_x (double value)
bool has_y () const
void clear_y ()
double y () const
void set_y (double value)
bool has_vx () const
void clear_vx ()
double vx () const
void set_vx (double value)
bool has_vy () const
void clear_vy ()
double vy () const
void set_vy (double value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const grSim_BallReplacement & default_instance ()
static const grSim_BallReplacement * internal_default_instance ()
Static Public Attributes
static const int kXFieldNumber = 1
static const int kYFieldNumber = 2
static const int kVxFieldNumber = 3
static const int kVyFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (grSim_BallReplacement *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_x ()
void clear_has_x ()
void set_has_y ()
void clear_has_y ()
void set_has_vx ()
void clear_has_vx ()
void set_has_vy ()
void clear_has_vy ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_grSim_5fReplacement_2eproto ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
double x_
double y_
double vx_
double vy_
Friends
void protobuf_InitDefaults_grSim_5fReplacement_2eproto_impl ()
void protobuf_AddDesc_grSim_5fReplacement_2eproto_impl ()
void protobuf_ShutdownFile_grSim_5fReplacement_2eproto ()
Detailed Description
Definition at line 188 of file grSim_Replacement.pb.h.
Constructor & Destructor Documentation
grSim_BallReplacement::grSim_BallReplacement ()
virtual grSim_BallReplacement::~grSim_BallReplacement () virtual
grSim_BallReplacement::grSim_BallReplacement (const grSim_BallReplacement & from)
Member Function Documentation
size_t grSim_BallReplacement::ByteSizeLong () const
void grSim_BallReplacement::Clear ()
void grSim_BallReplacement::clear_has_vx () inline private
Definition at line 617 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
{
   _has_bits_[0] &= ~0x00000004u;
 }
void grSim_BallReplacement::clear_has_vy () inline private
Definition at line 641 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
{
   _has_bits_[0] &= ~0x00000008u;
 }
void grSim_BallReplacement::clear_has_x () inline private
Definition at line 569 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void grSim_BallReplacement::clear_has_y () inline private
Definition at line 593 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
{
   _has_bits_[0] &= ~0x00000002u;
 }
void grSim_BallReplacement::clear_vx () inline
Definition at line 620 of file grSim_Replacement.pb.h.
{
   vx_ = 0;
   clear_has_vx();
 }
void grSim_BallReplacement::clear_vy () inline
Definition at line 644 of file grSim_Replacement.pb.h.
{
   vy_ = 0;
   clear_has_vy();
 }
void grSim_BallReplacement::clear_x () inline
Definition at line 572 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::clear_has_x(), and grSim_RobotReplacement::x_.
{
   x_ = 0;
   clear_has_x();
 }
void grSim_BallReplacement::clear_y () inline
Definition at line 596 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::clear_has_y(), and grSim_RobotReplacement::y_.
{
   y_ = 0;
   clear_has_y();
 }
void grSim_BallReplacement::CopyFrom (const ::google::protobuf::Message & from)
void grSim_BallReplacement::CopyFrom (const grSim_BallReplacement & from)
static const grSim_BallReplacement& grSim_BallReplacement::default_instance () static
static const ::google::protobuf::Descriptor* grSim_BallReplacement::descriptor () static
inline ::google::protobuf::Arena* grSim_BallReplacement::GetArenaNoVirtual () const inline private
Definition at line 248 of file grSim_Replacement.pb.h.
{
     return NULL;
   }
int grSim_BallReplacement::GetCachedSize () const inline
Definition at line 241 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_cached_size_, grSim_RobotReplacement::InternalSwap(), grSim_RobotReplacement::SetCachedSize(), grSim_RobotReplacement::SharedCtor(), and grSim_RobotReplacement::SharedDtor().
 { return _cached_size_; }
::google::protobuf::Metadata grSim_BallReplacement::GetMetadata () const
bool grSim_BallReplacement::has_vx () const inline
Definition at line 611 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool grSim_BallReplacement::has_vy () const inline
Definition at line 635 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool grSim_BallReplacement::has_x () const inline
Definition at line 563 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool grSim_BallReplacement::has_y () const inline
Definition at line 587 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
static const grSim_BallReplacement* grSim_BallReplacement::internal_default_instance () inline static
Definition at line 211 of file grSim_Replacement.pb.h.
References _grSim_BallReplacement_default_instance_, and grSim_RobotReplacement::Swap().
Referenced by grSim_Replacement::ball().
{
     return reinterpret_cast<const grSim_BallReplacement*>(
                &_grSim_BallReplacement_default_instance_);
   }
::google::protobuf::uint8* grSim_BallReplacement::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void grSim_BallReplacement::InternalSwap (grSim_BallReplacement * other) private
bool grSim_BallReplacement::IsInitialized () const
void* grSim_BallReplacement::MaybeArenaPtr () const inline private
Definition at line 251 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::clear_x(), grSim_RobotReplacement::GetMetadata(), and grSim_RobotReplacement::has_x().
{
     return NULL;
   }
void grSim_BallReplacement::MergeFrom (const ::google::protobuf::Message & from)
void grSim_BallReplacement::MergeFrom (const grSim_BallReplacement & from)
bool grSim_BallReplacement::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
inline ::google::protobuf::UnknownFieldSet* grSim_BallReplacement::mutable_unknown_fields () inline
Definition at line 204 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_internal_metadata_, grSim_RobotReplacement::default_instance(), and grSim_RobotReplacement::descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
grSim_BallReplacement* grSim_BallReplacement::New () const inline
Definition at line 220 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::ByteSizeLong(), grSim_RobotReplacement::Clear(), grSim_RobotReplacement::CopyFrom(), grSim_RobotReplacement::InternalSerializeWithCachedSizesToArray(), grSim_RobotReplacement::IsInitialized(), grSim_RobotReplacement::MergeFrom(), grSim_RobotReplacement::MergePartialFromCodedStream(), grSim_RobotReplacement::New(), New(), grSim_RobotReplacement::SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
grSim_BallReplacement* grSim_BallReplacement::New (::google::protobuf::Arena * arena) const
grSim_BallReplacement& grSim_BallReplacement::operator= (const grSim_BallReplacement & from) inline
Definition at line 195 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* grSim_BallReplacement::protobuf_Offsets_grSim_5fReplacement_2eproto () private
size_t grSim_BallReplacement::RequiredFieldsByteSizeFallback () const private
void grSim_BallReplacement::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* grSim_BallReplacement::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 237 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void grSim_BallReplacement::set_has_vx () inline private
Definition at line 614 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
{
   _has_bits_[0] |= 0x00000004u;
 }
void grSim_BallReplacement::set_has_vy () inline private
Definition at line 638 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
{
   _has_bits_[0] |= 0x00000008u;
 }
void grSim_BallReplacement::set_has_x () inline private
Definition at line 566 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
{
   _has_bits_[0] |= 0x00000001u;
 }
void grSim_BallReplacement::set_has_y () inline private
Definition at line 590 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
{
   _has_bits_[0] |= 0x00000002u;
 }
void grSim_BallReplacement::set_vx (double value) inline
Definition at line 628 of file grSim_Replacement.pb.h.
{
   set_has_vx();
   vx_ = value;
   // @@protoc_insertion_point(field_set:grSim_BallReplacement.vx)
 }
void grSim_BallReplacement::set_vy (double value) inline
Definition at line 652 of file grSim_Replacement.pb.h.
{
   set_has_vy();
   vy_ = value;
   // @@protoc_insertion_point(field_set:grSim_BallReplacement.vy)
 }
void grSim_BallReplacement::set_x (double value) inline
Definition at line 580 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::set_has_x(), and grSim_RobotReplacement::x_.
{
   set_has_x();
   x_ = value;
   // @@protoc_insertion_point(field_set:grSim_BallReplacement.x)
 }
void grSim_BallReplacement::set_y (double value) inline
Definition at line 604 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::set_has_y(), and grSim_RobotReplacement::y_.
{
   set_has_y();
   y_ = value;
   // @@protoc_insertion_point(field_set:grSim_BallReplacement.y)
 }
void grSim_BallReplacement::SetCachedSize (int size) const private
void grSim_BallReplacement::SharedCtor () private
void grSim_BallReplacement::SharedDtor () private
void grSim_BallReplacement::Swap (grSim_BallReplacement * other)
const ::google::protobuf::UnknownFieldSet& grSim_BallReplacement::unknown_fields () const inline
Definition at line 200 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
double grSim_BallReplacement::vx () const inline
Definition at line 624 of file grSim_Replacement.pb.h.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_BallReplacement.vx)
   return vx_;
 }
double grSim_BallReplacement::vy () const inline
Definition at line 648 of file grSim_Replacement.pb.h.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_BallReplacement.vy)
   return vy_;
 }
double grSim_BallReplacement::x () const inline
Definition at line 576 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::x_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_BallReplacement.x)
   return x_;
 }
double grSim_BallReplacement::y () const inline
Definition at line 600 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::y_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_BallReplacement.y)
   return y_;
 }
Friends And Related Function Documentation
void protobuf_AddDesc_grSim_5fReplacement_2eproto_impl () friend
void protobuf_InitDefaults_grSim_5fReplacement_2eproto_impl () friend
void protobuf_ShutdownFile_grSim_5fReplacement_2eproto () friend
Field Documentation
int grSim_BallReplacement::_cached_size_ mutable private
Definition at line 306 of file grSim_Replacement.pb.h.
::google::protobuf::internal::HasBits<1> grSim_BallReplacement::_has_bits_ private
Definition at line 305 of file grSim_Replacement.pb.h.
::google::protobuf::internal::InternalMetadataWithArena grSim_BallReplacement::_internal_metadata_ private
Definition at line 304 of file grSim_Replacement.pb.h.
const int grSim_BallReplacement::kVxFieldNumber = 3 static
Definition at line 279 of file grSim_Replacement.pb.h.
const int grSim_BallReplacement::kVyFieldNumber = 4 static
Definition at line 286 of file grSim_Replacement.pb.h.
const int grSim_BallReplacement::kXFieldNumber = 1 static
Definition at line 265 of file grSim_Replacement.pb.h.
const int grSim_BallReplacement::kYFieldNumber = 2 static
Definition at line 272 of file grSim_Replacement.pb.h.
double grSim_BallReplacement::vx_ private
Definition at line 309 of file grSim_Replacement.pb.h.
double grSim_BallReplacement::vy_ private
Definition at line 310 of file grSim_Replacement.pb.h.
double grSim_BallReplacement::x_ private
Definition at line 307 of file grSim_Replacement.pb.h.
double grSim_BallReplacement::y_ private
Definition at line 308 of file grSim_Replacement.pb.h.
The documentation for this class was generated from the following file:
grsim_comm/include/proto/grSim_Replacement.pb.h