Documentation: grSim_Replacement Class Reference
grSim_Replacement Class Reference
#include <grSim_Replacement.pb.h>
Public Member Functions
grSim_Replacement ()
virtual ~grSim_Replacement ()
grSim_Replacement (const grSim_Replacement &from)
grSim_Replacement & operator= (const grSim_Replacement &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (grSim_Replacement *other)
grSim_Replacement * New () const PROTOBUF_FINAL
grSim_Replacement * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const grSim_Replacement &from)
void MergeFrom (const grSim_Replacement &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_ball () const
void clear_ball ()
const ::grSim_BallReplacement & ball () const
::grSim_BallReplacement * mutable_ball ()
::grSim_BallReplacement * release_ball ()
void set_allocated_ball (::grSim_BallReplacement *ball)
int robots_size () const
void clear_robots ()
const ::grSim_RobotReplacement & robots (int index) const
::grSim_RobotReplacement * mutable_robots (int index)
::grSim_RobotReplacement * add_robots ()
::google::protobuf::RepeatedPtrField< ::grSim_RobotReplacement > * mutable_robots ()
const ::google::protobuf::RepeatedPtrField< ::grSim_RobotReplacement > & robots () const
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const grSim_Replacement & default_instance ()
static const grSim_Replacement * internal_default_instance ()
Static Public Attributes
static const int kBallFieldNumber = 1
static const int kRobotsFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (grSim_Replacement *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_ball ()
void clear_has_ball ()
friendconst::google::protobuf::uint32 * protobuf_Offsets_grSim_5fReplacement_2eproto ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::RepeatedPtrField< ::grSim_RobotReplacement > robots_
::grSim_BallReplacement * ball_
Friends
void protobuf_InitDefaults_grSim_5fReplacement_2eproto_impl ()
void protobuf_AddDesc_grSim_5fReplacement_2eproto_impl ()
void protobuf_ShutdownFile_grSim_5fReplacement_2eproto ()
Detailed Description
Definition at line 319 of file grSim_Replacement.pb.h.
Constructor & Destructor Documentation
grSim_Replacement::grSim_Replacement ()
virtual grSim_Replacement::~grSim_Replacement () virtual
grSim_Replacement::grSim_Replacement (const grSim_Replacement & from)
Member Function Documentation
grSim_RobotReplacement * grSim_Replacement::add_robots () inline
Definition at line 722 of file grSim_Replacement.pb.h.
{
   // @@protoc_insertion_point(field_add:grSim_Replacement.robots)
   return robots_.Add();
 }
const ::grSim_BallReplacement & grSim_Replacement::ball () const inline
Definition at line 676 of file grSim_Replacement.pb.h.
References grSim_BallReplacement::internal_default_instance().
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Replacement.ball)
   return ball_ != NULL ? *ball_
                          : *::grSim_BallReplacement::internal_default_instance();
 }
size_t grSim_Replacement::ByteSizeLong () const
void grSim_Replacement::Clear ()
void grSim_Replacement::clear_ball () inline
Definition at line 672 of file grSim_Replacement.pb.h.
{
   if (ball_ != NULL) ball_->::grSim_BallReplacement::Clear();
   clear_has_ball();
 }
void grSim_Replacement::clear_has_ball () inline private
Definition at line 669 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void grSim_Replacement::clear_robots () inline
Definition at line 711 of file grSim_Replacement.pb.h.
{
   robots_.Clear();
 }
void grSim_Replacement::CopyFrom (const ::google::protobuf::Message & from)
void grSim_Replacement::CopyFrom (const grSim_Replacement & from)
static const grSim_Replacement& grSim_Replacement::default_instance () static
static const ::google::protobuf::Descriptor* grSim_Replacement::descriptor () static
inline ::google::protobuf::Arena* grSim_Replacement::GetArenaNoVirtual () const inline private
Definition at line 379 of file grSim_Replacement.pb.h.
{
     return NULL;
   }
int grSim_Replacement::GetCachedSize () const inline
Definition at line 372 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_cached_size_, grSim_RobotReplacement::InternalSwap(), grSim_RobotReplacement::SetCachedSize(), grSim_RobotReplacement::SharedCtor(), and grSim_RobotReplacement::SharedDtor().
 { return _cached_size_; }
::google::protobuf::Metadata grSim_Replacement::GetMetadata () const
bool grSim_Replacement::has_ball () const inline
Definition at line 663 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
static const grSim_Replacement* grSim_Replacement::internal_default_instance () inline static
Definition at line 342 of file grSim_Replacement.pb.h.
References _grSim_Replacement_default_instance_, and grSim_RobotReplacement::Swap().
Referenced by grSim_Packet::replacement().
{
     return reinterpret_cast<const grSim_Replacement*>(
                &_grSim_Replacement_default_instance_);
   }
::google::protobuf::uint8* grSim_Replacement::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void grSim_Replacement::InternalSwap (grSim_Replacement * other) private
bool grSim_Replacement::IsInitialized () const
void* grSim_Replacement::MaybeArenaPtr () const inline private
Definition at line 382 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::GetMetadata().
{
     return NULL;
   }
void grSim_Replacement::MergeFrom (const ::google::protobuf::Message & from)
void grSim_Replacement::MergeFrom (const grSim_Replacement & from)
bool grSim_Replacement::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
grSim_BallReplacement * grSim_Replacement::mutable_ball () inline
Definition at line 681 of file grSim_Replacement.pb.h.
{
   set_has_ball();
   if (ball_ == NULL) {
     ball_ = new ::grSim_BallReplacement;
   }
   // @@protoc_insertion_point(field_mutable:grSim_Replacement.ball)
   return ball_;
 }
grSim_RobotReplacement * grSim_Replacement::mutable_robots (int index) inline
Definition at line 718 of file grSim_Replacement.pb.h.
{
   // @@protoc_insertion_point(field_mutable:grSim_Replacement.robots)
   return robots_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::grSim_RobotReplacement > * grSim_Replacement::mutable_robots () inline
Definition at line 727 of file grSim_Replacement.pb.h.
{
   // @@protoc_insertion_point(field_mutable_list:grSim_Replacement.robots)
   return &robots_;
 }
inline ::google::protobuf::UnknownFieldSet* grSim_Replacement::mutable_unknown_fields () inline
Definition at line 335 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_internal_metadata_, grSim_RobotReplacement::default_instance(), and grSim_RobotReplacement::descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
grSim_Replacement* grSim_Replacement::New () const inline
Definition at line 351 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::ByteSizeLong(), grSim_RobotReplacement::Clear(), grSim_RobotReplacement::CopyFrom(), grSim_RobotReplacement::InternalSerializeWithCachedSizesToArray(), grSim_RobotReplacement::IsInitialized(), grSim_RobotReplacement::MergeFrom(), grSim_RobotReplacement::MergePartialFromCodedStream(), grSim_RobotReplacement::New(), New(), grSim_RobotReplacement::SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
grSim_Replacement* grSim_Replacement::New (::google::protobuf::Arena * arena) const
grSim_Replacement& grSim_Replacement::operator= (const grSim_Replacement & from) inline
Definition at line 326 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* grSim_Replacement::protobuf_Offsets_grSim_5fReplacement_2eproto () private
grSim_BallReplacement * grSim_Replacement::release_ball () inline
Definition at line 689 of file grSim_Replacement.pb.h.
{
   // @@protoc_insertion_point(field_release:grSim_Replacement.ball)
   clear_has_ball();
   ::grSim_BallReplacement* temp = ball_;
   ball_ = NULL;
   return temp;
 }
const ::grSim_RobotReplacement & grSim_Replacement::robots (int index) const inline
Definition at line 714 of file grSim_Replacement.pb.h.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Replacement.robots)
   return robots_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::grSim_RobotReplacement > & grSim_Replacement::robots () const inline
Definition at line 732 of file grSim_Replacement.pb.h.
{
   // @@protoc_insertion_point(field_list:grSim_Replacement.robots)
   return robots_;
 }
int grSim_Replacement::robots_size () const inline
Definition at line 708 of file grSim_Replacement.pb.h.
Referenced by SSLWorld::recvActions().
{
   return robots_.size();
 }
void grSim_Replacement::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* grSim_Replacement::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 368 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void grSim_Replacement::set_allocated_ball (::grSim_BallReplacement * ball) inline
Definition at line 696 of file grSim_Replacement.pb.h.
{
   delete ball_;
   ball_ = ball;
   if (ball) {
     set_has_ball();
   } else {
     clear_has_ball();
   }
   // @@protoc_insertion_point(field_set_allocated:grSim_Replacement.ball)
 }
void grSim_Replacement::set_has_ball () inline private
Definition at line 666 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_has_bits_.
{
   _has_bits_[0] |= 0x00000001u;
 }
void grSim_Replacement::SetCachedSize (int size) const private
void grSim_Replacement::SharedCtor () private
void grSim_Replacement::SharedDtor () private
void grSim_Replacement::Swap (grSim_Replacement * other)
const ::google::protobuf::UnknownFieldSet& grSim_Replacement::unknown_fields () const inline
Definition at line 331 of file grSim_Replacement.pb.h.
References grSim_RobotReplacement::_internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
Friends And Related Function Documentation
void protobuf_AddDesc_grSim_5fReplacement_2eproto_impl () friend
void protobuf_InitDefaults_grSim_5fReplacement_2eproto_impl () friend
void protobuf_ShutdownFile_grSim_5fReplacement_2eproto () friend
Field Documentation
int grSim_Replacement::_cached_size_ mutable private
Definition at line 421 of file grSim_Replacement.pb.h.
::google::protobuf::internal::HasBits<1> grSim_Replacement::_has_bits_ private
Definition at line 420 of file grSim_Replacement.pb.h.
::google::protobuf::internal::InternalMetadataWithArena grSim_Replacement::_internal_metadata_ private
Definition at line 419 of file grSim_Replacement.pb.h.
::grSim_BallReplacement* grSim_Replacement::ball_ private
Definition at line 423 of file grSim_Replacement.pb.h.
const int grSim_Replacement::kBallFieldNumber = 1 static
Definition at line 396 of file grSim_Replacement.pb.h.
const int grSim_Replacement::kRobotsFieldNumber = 2 static
Definition at line 405 of file grSim_Replacement.pb.h.
::google::protobuf::RepeatedPtrField< ::grSim_RobotReplacement > grSim_Replacement::robots_ private
Definition at line 422 of file grSim_Replacement.pb.h.
The documentation for this class was generated from the following file:
grsim_comm/include/proto/grSim_Replacement.pb.h