Documentation: PCylinder Class Reference
PCylinder Class Reference
#include <pcylinder.h>
Public Member Functions
PCylinder (dReal x, dReal y, dReal z, dReal radius, dReal length, dReal mass, dReal red, dReal green, dReal blue, int tex_id=-1, bool robot=false)
virtual ~PCylinder ()
virtual void setMass (dReal mass)
virtual void init ()
virtual void draw ()
Public Member Functions inherited from PObject
PObject (dReal x, dReal y, dReal z, dReal red, dReal green, dReal blue, dReal mass)
virtual ~PObject ()
void setRotation (dReal x_axis, dReal y_axis, dReal z_axis, dReal ang)
void setBodyPosition (dReal x, dReal y, dReal z, bool local=false)
void setBodyRotation (dReal x_axis, dReal y_axis, dReal z_axis, dReal ang, bool local=false)
void getBodyPosition (dReal &x, dReal &y, dReal &z, bool local=false)
void getBodyDirection (dReal &x, dReal &y, dReal &z)
void getBodyRotation (dMatrix3 r, bool local=false)
void setVisibility (bool v)
void setColor (dReal r, dReal g, dReal b)
void getColor (dReal &r, dReal &g, dReal &b)
bool getVisibility ()
virtual void glinit ()
Private Attributes
dReal m_radius
dReal m_length
GLuint m_gllistid
int m_texid
bool m_robot
Additional Inherited Members
Data Fields inherited from PObject
dBodyID body
dGeomID geom
dWorldID world
dSpaceID space
CGraphics * g
int tag
int id
Protected Member Functions inherited from PObject
void initPosBody ()
void initPosGeom ()
Protected Attributes inherited from PObject
dReal m_x
dReal m_y
dReal m_z
dReal m_red
dReal m_green
dReal m_blue
dReal m_mass
dMatrix3 local_Rot
dVector3 local_Pos
dQuaternion q
bool visible
Detailed Description
Definition at line 24 of file pcylinder.h.
Constructor & Destructor Documentation
PCylinder::PCylinder (dReal x, dReal y, dReal z, dReal radius, dReal length, dReal mass, dReal red, dReal green, dReal blue, int tex_id = -1, bool robot = false)
Definition at line 21 of file pcylinder.cpp.
References m_length, m_radius, m_robot, m_texid, and radius.
           : PObject(x,y,z,red,green,blue,mass)
 {
     m_radius = radius;
     m_length = length;
     m_texid = texid;
     m_robot = robot;
 }
PCylinder::~PCylinder () virtual
Definition at line 30 of file pcylinder.cpp.
 {
 }
Member Function Documentation
void PCylinder::draw () virtual
Reimplemented from PObject.
Definition at line 138 of file pcylinder.cpp.
References PObject::body, PObject::draw(), CGraphics::drawCylinder(), CGraphics::drawCylinder_TopTextured(), PObject::g, m_length, m_radius, m_robot, and m_texid.
 {
     PObject::draw();
     if (m_texid==-1)
         g->drawCylinder(dBodyGetPosition(body),dBodyGetRotation(body),m_length,m_radius);
     else
         g->drawCylinder_TopTextured(dBodyGetPosition(body),dBodyGetRotation(body),m_length,m_radius,m_texid,m_robot);
 /*    glColor3f(1.0, 1.0, 1.0);
     glPushMatrix();
         g->setTransform(dBodyGetPosition(body),dBodyGetRotation(body));
            glScaled(m_radius, m_radius, m_radius);
            glColor3d(0.1, 0.1, 0.1);
            glRasterPos3f(-0.25, 1.5, 0.0);
            //glutStrokeCharacter(GLUT_STROKE_ROMAN, c);
            glutBitmapCharacter(GLUT_BITMAP_8_BY_13,c);
     glPopMatrix();*/
 }
void PCylinder::init () virtual
Implements PObject.
Definition at line 43 of file pcylinder.cpp.
References PObject::body, PObject::geom, PObject::initPosBody(), m_length, PObject::m_mass, m_radius, setMass(), PObject::space, and PObject::world.
 {
   body = dBodyCreate (world);
   initPosBody();
   setMass(m_mass);
 /*  if (m_texid!=-1)
   {
       dTriMeshDataID g = dGeomTriMeshDataCreate();
       const int vertexcount = 19*3+1;
       const int indexcount = 19*9;
       dVector3* vertices = new dVector3[vertexcount];
       dTriIndex* indices = new dTriIndex[indexcount];
       const int n = 24; // number of sides to the cylinder (divisible by 4)
       dReal l = m_length*0.5;
       dReal a = dReal(M_PI*2.0)/dReal(n);
       dReal sa = (dReal) sin(a);
       dReal ca = (dReal) cos(a);
       dReal r = m_radius;
       dReal ny=1,nz=0,tmp;
       int v=0,f=0;
       int i;
       for (i=0; i<=n; i++) {
           if (i>2 && i<n-2)
           {
               vertices[v][0] = ny*r;
               vertices[v][1] = nz*r;
               vertices[v][2] = l;v++;
               vertices[v][0] = ny*r;
               vertices[v][1] = nz*r;
               vertices[v][2] = -l;v++;
               indices[f] = v;f++;
               indices[f] = v-2;f++;
               indices[f] = v-1;f++;
               indices[f] = v-1;f++;
               indices[f] = v;f++;
               indices[f] = v+1;f++;
           }
         }
       //v=38;f=38*3
         // rotate ny,nz
         tmp = ca*ny - sa*nz;
         nz = sa*ny + ca*nz;
         ny = tmp;
       ny=1; nz=0;         // normal vector = (0,ny,nz)
       glBegin (GL_TRIANGLE_FAN);
       vertices[v][0] = 0;
       vertices[v][1] = 0;
       vertices[v][2] = l;v++;
       for (i=0; i<n; i++) {
           if (i>2 && i<n-2)
           {
             vertices[v][0] = ny*r;
             vertices[v][1] = nz*r;
             vertices[v][2] = l;v++;
             indices[f] = 38;f++;
             indices[f] = v;f++;
             indices[f] = v-1;f++;
           }
         // rotate ny,nz
         tmp = ca*ny - sa*nz;
         nz = sa*ny + ca*nz;
         ny = tmp;
       }
       // draw bottom cap
 //      ny=1; nz=0;       // normal vector = (0,ny,nz)
 //      glBegin (GL_TRIANGLE_FAN);
 //      glNormal3d (0,0,-1);
 //      glVertex3d (0,0,-l+zoffset);
 //      for (i=0; i<=n; i++) {
 //          if (i>=2 && i<n-2)
 //          {
 //
 //        glNormal3d (0,0,-1);
 //        glVertex3d (ny*r,nz*r,-l+zoffset);
 //    }
 //        // rotate ny,nz
 //        tmp = ca*ny + sa*nz;
 //        nz = -sa*ny + ca*nz;
 //        ny = tmp;
 //      }
       dGeomTriMeshDataBuildSimple(g, (dReal*) vertices, vertexcount, indices, indexcount);
       geom = dCreateTriMesh(0,g,NULL,NULL,NULL);
   }
   else */
   {
     geom = dCreateCylinder(0,m_radius,m_length);
   }
   dGeomSetBody (geom,body);
   dSpaceAdd (space,geom);
 }
void PCylinder::setMass (dReal mass) virtual
Reimplemented from PObject.
Definition at line 35 of file pcylinder.cpp.
References PObject::body, m_length, PObject::m_mass, and m_radius.
Referenced by init().
 {
   m_mass = mass;
   dMass m;
   dMassSetCylinderTotal (&m,m_mass,1,m_radius,m_length);
   dBodySetMass (body,&m);
 }
Field Documentation
GLuint PCylinder::m_gllistid private
Definition at line 28 of file pcylinder.h.
dReal PCylinder::m_length private
Definition at line 27 of file pcylinder.h.
Referenced by draw(), init(), PCylinder(), and setMass().
dReal PCylinder::m_radius private
Definition at line 27 of file pcylinder.h.
Referenced by draw(), init(), PCylinder(), and setMass().
bool PCylinder::m_robot private
Definition at line 30 of file pcylinder.h.
Referenced by draw(), and PCylinder().
int PCylinder::m_texid private
Definition at line 29 of file pcylinder.h.
Referenced by draw(), and PCylinder().
The documentation for this class was generated from the following files:
grSim/include/physics/pcylinder.h
grSim/src/physics/pcylinder.cpp