Documentation: VarTypes::VarXML Class Reference
VarTypes::VarXML Class Reference
XML helper functions of the VarType system.
#include <VarXML.h>
Public Member Functions
VarXML ()
virtual ~VarXML ()
Static Public Member Functions
static void write (VarType *rootVar, string filename)
write a VarType node (and all of its children) to an xml file
static void write (vector< VarType * > rootVars, string filename)
write a vector of VarType nodes (and all of their children) to an xml file
static vector< VarType * > read (vector< VarType * > existing_nodes, string filename)
Detailed Description
XML helper functions of the VarType system.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
This class provides static functions to parse or write an XML file representing a VarTypes tree.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 38 of file VarXML.h.
Constructor & Destructor Documentation
VarTypes::VarXML::VarXML ()
Definition at line 25 of file VarXML.cpp.
 {};
VarTypes::VarXML::~VarXML () virtual
Definition at line 26 of file VarXML.cpp.
 {};
Member Function Documentation
vector< VarType * > VarTypes::VarXML::read (vector< VarType * > existing_nodes, string filename) static
read a VarType-tree from an xml file and return its root nodes as a vector.
Parameters
existing_nodes represents any pre-defined vartypes tree and should be an empty vector if no tree pre-exists.
If a tree does pre-exist then the read function will update the data of any existing nodes, or create new nodes if they are missing in the existing tree.
Definition at line 48 of file VarXML.cpp.
References VarTypes::XMLNode::openFileHelper(), and VarTypes::VarType::readChildrenHelper().
   {
     XMLNode root = XMLNode::openFileHelper(filename.c_str(),"VarXML");
     return VarType::readChildrenHelper(root ,existing_nodes, false, false);
   }
void VarTypes::VarXML::write (VarType * rootVar, string filename) static
write a VarType node (and all of its children) to an xml file
Definition at line 28 of file VarXML.cpp.
References v.
   {
     vector<VarType *> v;
     v.push_back(rootVar);
     write(v,filename);
   }
void VarTypes::VarXML::write (vector< VarType * > rootVars, string filename) static
write a vector of VarType nodes (and all of their children) to an xml file
Definition at line 34 of file VarXML.cpp.
References VarTypes::VarType::deleteAllVarChildren(), VarTypes::eXMLErrorNone, velocity.pid_::i, VarTypes::XMLNode::openFileHelper(), and VarTypes::XMLNode::writeToFile().
   {
     XMLNode root = XMLNode::openFileHelper(filename.c_str(),"VarXML");
     VarType::deleteAllVarChildren(root);
     for (unsigned int i=0;i<rootVars.size();i++) {
       rootVars[i]->writeXML(root,true);
     }
     const VarTypes::XMLError error = root.writeToFile(filename.c_str());
     if (error != VarTypes::eXMLErrorNone) {
       fprintf(stderr, "Error saving XML: %d\n", error);
     }
   }
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/VarXML.h
ssl-vision/src/shared/vartypes/VarXML.cpp