Documentation: PluginDetectRobots Class Reference
PluginDetectRobots Class Reference
#include <plugin_detect_robots.h>
Public Member Functions
PluginDetectRobots (FrameBuffer *_buffer, LUT3D *lut, const CameraParameters &camera_params, const RoboCupField &field, CMPattern::TeamSelector *_global_team_selector_blue, CMPattern::TeamSelector *_global_team_selector_yellow)
~PluginDetectRobots ()
virtual ProcessResult process (FrameData *data, RenderOptions *options)
virtual VarList * getSettings ()
virtual string getName ()
Public Member Functions inherited from VisionPlugin
VisionPlugin (FrameBuffer *_buffer)
virtual ~VisionPlugin ()
FrameBuffer * getFrameBuffer () const
this functions provides convenient access to the ring-buffer
void lock ()
void unlock ()
virtual bool isEnabled () const
virtual void setEnabled (bool enable)
virtual bool isVisualize () const
virtual void setVisualize (bool enable)
virtual bool isSharedAmongStacks () const
virtual void setSharedAmongStacks (bool enable)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual void postProcess (FrameData *data, RenderOptions *options)
virtual QWidget * getVisualizationWidget ()
virtual QWidget * getControlWidget ()
virtual void closeWidgets ()
virtual QList< QAction * > actions ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
void setTimeProcessing (double val)
void setTimePostProcessing (double val)
double getTimeProcessing ()
double getTimePostProcessing ()
Protected Slots
void teamDataChange ()
Protected Member Functions
void buildRegionTree (CMVision::ColorRegionList *colorlist)
Protected Attributes
VarNotifier _notifier
LUT3D * _lut
VarList * _settings
VarString * _color_label
int color_id_yellow
int color_id_blue
int color_id_clear
int color_id_ball
int color_id_black
int color_id_field
CMVision::RegionTree reg_tree
CMPattern::TeamSelector * global_team_selector_blue
CMPattern::TeamSelector * global_team_selector_yellow
CMPattern::TeamDetector * team_detector_blue
CMPattern::TeamDetector * team_detector_yellow
const CameraParameters & camera_parameters
const RoboCupField & field
Protected Attributes inherited from VisionPlugin
QMutex mutex
bool enabled
bool visualize
bool shared
FrameBuffer * buffer
double time_proc
double time_post
Additional Inherited Members
Public Slots inherited from VisionPlugin
void slotKeyPressEvent (QKeyEvent *event)
Detailed Description
Author
Author Name
Definition at line 38 of file plugin_detect_robots.h.
Constructor & Destructor Documentation
PluginDetectRobots::PluginDetectRobots (FrameBuffer * _buffer, LUT3D * lut, const CameraParameters & camera_params, const RoboCupField & field, CMPattern::TeamSelector * _global_team_selector_blue, CMPattern::TeamSelector * _global_team_selector_yellow)
Definition at line 23 of file plugin_detect_robots.cpp.
References _lut, _notifier, _settings, VarTypes::VarNotifier::addRecursive(), color_id_ball, color_id_black, color_id_blue, color_id_clear, color_id_field, color_id_yellow, LUT3D::getChannelID(), global_team_selector_blue, global_team_selector_yellow, team_detector_blue, and team_detector_yellow.
  : VisionPlugin(_buffer), camera_parameters(camera_params), field(field)
 {
   _lut=lut;
   color_id_yellow = _lut->getChannelID("Yellow");
   if (color_id_yellow == -1) printf("WARNING color label 'Yellow' not defined in LUT!!!\n");
   color_id_blue = _lut->getChannelID("Blue");
   if (color_id_yellow == -1) printf("WARNING color label 'Blue' not defined in LUT!!!\n");
   color_id_clear = 0;
   color_id_ball = _lut->getChannelID("Orange");
   if (color_id_ball == -1) printf("WARNING color label 'Orange' not defined in LUT!!!\n");
   color_id_black = _lut->getChannelID("Black");
   if (color_id_black == -1) printf("WARNING color label 'Black' not defined in LUT!!!\n");
   color_id_field = _lut->getChannelID("Field Green");
   if (color_id_field == -1) printf("WARNING color label 'Field Green' not defined in LUT!!!\n");
   global_team_selector_blue=_global_team_selector_blue;
   global_team_selector_yellow=_global_team_selector_yellow;
   team_detector_blue=new CMPattern::TeamDetector(_lut,camera_params,field);
   team_detector_yellow=new CMPattern::TeamDetector(_lut,camera_params,field);
   _settings=new VarList("Robot Detection");
   _notifier.addRecursive(_settings);
   connect(_global_team_selector_blue,SIGNAL(signalTeamDataChanged()),&_notifier,SLOT(changeSlotOtherChange()));
   connect(_global_team_selector_yellow,SIGNAL(signalTeamDataChanged()),&_notifier,SLOT(changeSlotOtherChange()));
 }
PluginDetectRobots::~PluginDetectRobots ()
Definition at line 56 of file plugin_detect_robots.cpp.
 {
 }
Member Function Documentation
void PluginDetectRobots::buildRegionTree (CMVision::ColorRegionList * colorlist) protected
Definition at line 69 of file plugin_detect_robots.cpp.
References NKDTree< state_t, num_t, dim, scaled, get_next >::add(), NKDTree< state_t, num_t, dim, scaled, get_next >::build(), NKDTree< state_t, num_t, dim, scaled, get_next >::clear(), color_id_ball, color_id_black, color_id_clear, color_id_field, CMVision::RegionLinkedList::getInitialElement(), CMVision::ColorRegionList::getNumColorRegions(), CMVision::ColorRegionList::getRegionList(), CMVision::Region::next, and reg_tree.
Referenced by process().
{
   reg_tree.clear();
   int num_colors=colorlist->getNumColorRegions();
   for(int c=0;c<num_colors;c++) {
     //ONLY ADD ROBOT MARKER COLORS:
     if (c!= color_id_clear && c!=color_id_field && c!= color_id_ball && c!= color_id_black) {
       CMVision::Region *reg = colorlist->getRegionList(c).getInitialElement();
       while(reg!=0) {
         reg_tree.add(reg);
         reg = reg->next;
       }
     }
   }
   reg_tree.build();
 }
string PluginDetectRobots::getName () virtual
Reimplemented from VisionPlugin.
Definition at line 65 of file plugin_detect_robots.cpp.
{
   return "DetectRobots";
 }
VarList * PluginDetectRobots::getSettings () virtual
Reimplemented from VisionPlugin.
Definition at line 61 of file plugin_detect_robots.cpp.
References _settings.
{
   return _settings;
 }
ProcessResult PluginDetectRobots::process (FrameData * data, RenderOptions * options) virtual
Reimplemented from VisionPlugin.
Definition at line 85 of file plugin_detect_robots.cpp.
References _notifier, buildRegionTree(), VarTypes::VarNotifier::changeSlotOtherChange(), color_id_blue, color_id_yellow, FrameDataMap::get(), CMPattern::TeamSelector::getNumberRobots(), CMPattern::TeamSelector::getSelectedTeam(), global_team_selector_blue, global_team_selector_yellow, VarTypes::VarNotifier::hasChanged(), CMPattern::TeamDetector::init(), FrameDataMap::insert(), FrameData::map, ProcessingFailed, ProcessingOk, reg_tree, team_detector_blue, team_detector_yellow, and CMPattern::TeamDetector::update().
 {
   (void)options;
   if (data==0) return ProcessingFailed;
   SSL_DetectionFrame * detection_frame = 0;
   detection_frame=(SSL_DetectionFrame *)data->map.get("ssl_detection_frame");
   if (detection_frame == 0) detection_frame=(SSL_DetectionFrame *)data->map.insert("ssl_detection_frame",new SSL_DetectionFrame());
   //acquire orange region list from data-map:
   CMVision::ColorRegionList * colorlist;
   colorlist=(CMVision::ColorRegionList *)data->map.get("cmv_colorlist");
   if (colorlist==0) {
     printf("error in robot detection plugin: no region-lists were found!\n");
     return ProcessingFailed;
   }
   //acquire color-labeled image from data-map:
   const Image<raw8> * image = (Image<raw8> *)(data->map.get("cmv_threshold"));
   if (image==0) {
     printf("error in robot detection plugin: no color-thresholded image was found!\n");
     return ProcessingFailed;
   }
   CMPattern::Team * team=0;
   ::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot >* robotlist=0;
   int color_id;
   int num_robots;
   CMPattern::TeamDetector * detector;
   //TODO: lookup color label from LUT
   buildRegionTree(colorlist);
   bool need_reinit=_notifier.hasChanged();
   for (int team_i = 0; team_i < 2; team_i++) {
     //team_i: 0==blue, 1==yellow
     if (team_i==0) {
       color_id=color_id_blue;
       team=global_team_selector_blue->getSelectedTeam();
       num_robots=global_team_selector_blue->getNumberRobots();
       detection_frame->clear_robots_blue();
       robotlist=detection_frame->mutable_robots_blue();
       detector=team_detector_blue;
     } else {
       color_id=color_id_yellow;
       team=global_team_selector_yellow->getSelectedTeam();
       num_robots=global_team_selector_yellow->getNumberRobots();
       detection_frame->clear_robots_yellow();
       robotlist=detection_frame->mutable_robots_yellow();
       detector=team_detector_yellow;
     }
     if (team!=0) {
       if (need_reinit) {
         detector->init(team);
       }
       detector->update(robotlist, color_id,  num_robots, image, colorlist, reg_tree);
     } else {
       _notifier.changeSlotOtherChange();
     }
 //    printf("DETECTED %d robots on team %d\n",robotlist->size(),team_i);
 //    fflush(stdout);
   }
   return ProcessingOk;
 }
void PluginDetectRobots::teamDataChange () protected slot
Field Documentation
VarString* PluginDetectRobots::_color_label protected
Definition at line 45 of file plugin_detect_robots.h.
LUT3D* PluginDetectRobots::_lut protected
Definition at line 42 of file plugin_detect_robots.h.
Referenced by PluginDetectRobots().
VarNotifier PluginDetectRobots::_notifier protected
Definition at line 41 of file plugin_detect_robots.h.
Referenced by PluginDetectRobots(), and process().
VarList* PluginDetectRobots::_settings protected
Definition at line 43 of file plugin_detect_robots.h.
Referenced by getSettings(), and PluginDetectRobots().
const CameraParameters& PluginDetectRobots::camera_parameters protected
Definition at line 63 of file plugin_detect_robots.h.
int PluginDetectRobots::color_id_ball protected
Definition at line 50 of file plugin_detect_robots.h.
Referenced by buildRegionTree(), and PluginDetectRobots().
int PluginDetectRobots::color_id_black protected
Definition at line 51 of file plugin_detect_robots.h.
Referenced by buildRegionTree(), and PluginDetectRobots().
int PluginDetectRobots::color_id_blue protected
Definition at line 48 of file plugin_detect_robots.h.
Referenced by PluginDetectRobots(), and process().
int PluginDetectRobots::color_id_clear protected
Definition at line 49 of file plugin_detect_robots.h.
Referenced by buildRegionTree(), and PluginDetectRobots().
int PluginDetectRobots::color_id_field protected
Definition at line 52 of file plugin_detect_robots.h.
Referenced by buildRegionTree(), and PluginDetectRobots().
int PluginDetectRobots::color_id_yellow protected
Definition at line 47 of file plugin_detect_robots.h.
Referenced by PluginDetectRobots(), and process().
const RoboCupField& PluginDetectRobots::field protected
Definition at line 64 of file plugin_detect_robots.h.
CMPattern::TeamSelector* PluginDetectRobots::global_team_selector_blue protected
Definition at line 57 of file plugin_detect_robots.h.
Referenced by PluginDetectRobots(), and process().
CMPattern::TeamSelector* PluginDetectRobots::global_team_selector_yellow protected
Definition at line 58 of file plugin_detect_robots.h.
Referenced by PluginDetectRobots(), and process().
CMVision::RegionTree PluginDetectRobots::reg_tree protected
Definition at line 55 of file plugin_detect_robots.h.
Referenced by buildRegionTree(), and process().
CMPattern::TeamDetector* PluginDetectRobots::team_detector_blue protected
Definition at line 60 of file plugin_detect_robots.h.
Referenced by PluginDetectRobots(), and process().
CMPattern::TeamDetector* PluginDetectRobots::team_detector_yellow protected
Definition at line 61 of file plugin_detect_robots.h.
Referenced by PluginDetectRobots(), and process().
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/plugin_detect_robots.h
ssl-vision/src/app/plugins/plugin_detect_robots.cpp