Documentation: Protobuf.GrSimReplacement.grSim_BallReplacement.Builder Class Reference
Protobuf.GrSimReplacement.grSim_BallReplacement.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
GrSimReplacement.grSim_BallReplacement getDefaultInstanceForType ()
GrSimReplacement.grSim_BallReplacement build ()
GrSimReplacement.grSim_BallReplacement buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (GrSimReplacement.grSim_BallReplacement other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasX ()
double getX ()
Builder setX (double value)
Builder clearX ()
boolean hasY ()
double getY ()
Builder setY (double value)
Builder clearY ()
boolean hasVx ()
double getVx ()
Builder setVx (double value)
Builder clearVx ()
boolean hasVy ()
double getVy ()
Builder setVy (double value)
Builder clearVy ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
GrSimReplacement.grSim_BallReplacement buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
double x_
double y_
double vx_
double vy_
Detailed Description
Definition at line 868 of file GrSimReplacement.java.
Constructor & Destructor Documentation
Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.Builder () inline private
Definition at line 882 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.Builder (BuilderParent parent) inline private
Definition at line 886 of file GrSimReplacement.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.build () inline
Definition at line 924 of file GrSimReplacement.java.
{
         GrSimReplacement.grSim_BallReplacement result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 932 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_BallReplacement.parseDelimitedFrom().
{
         GrSimReplacement.grSim_BallReplacement result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.buildPartial () inline
Definition at line 942 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.x_.
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeBall().
{
         GrSimReplacement.grSim_BallReplacement result = new GrSimReplacement.grSim_BallReplacement(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         result.x_ = x_;
         if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
           to_bitField0_ |= 0x00000002;
         }
         result.y_ = y_;
         if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
           to_bitField0_ |= 0x00000004;
         }
         result.vx_ = vx_;
         if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
           to_bitField0_ |= 0x00000008;
         }
         result.vy_ = vy_;
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.clear () inline
Definition at line 898 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.clear().
Referenced by Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.clear().
{
         super.clear();
         x_ = 0D;
         bitField0_ = (bitField0_ & ~0x00000001);
         y_ = 0D;
         bitField0_ = (bitField0_ & ~0x00000002);
         vx_ = 0D;
         bitField0_ = (bitField0_ & ~0x00000004);
         vy_ = 0D;
         bitField0_ = (bitField0_ & ~0x00000008);
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.clearVx () inline
Definition at line 1119 of file GrSimReplacement.java.
{
         bitField0_ = (bitField0_ & ~0x00000004);
         vx_ = 0D;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.clearVy () inline
Definition at line 1140 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.initFields().
{
         bitField0_ = (bitField0_ & ~0x00000008);
         vy_ = 0D;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.clearX () inline
Definition at line 1077 of file GrSimReplacement.java.
{
         bitField0_ = (bitField0_ & ~0x00000001);
         x_ = 0D;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.clearY () inline
Definition at line 1098 of file GrSimReplacement.java.
{
         bitField0_ = (bitField0_ & ~0x00000002);
         y_ = 0D;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.clone () inline
Definition at line 911 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.create () inline static private
Definition at line 894 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_BallReplacement.newBuilder().
{
         return new Builder();
       }
GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.getDefaultInstanceForType () inline
Definition at line 920 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.getDefaultInstance().
{
         return GrSimReplacement.grSim_BallReplacement.getDefaultInstance();
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.getDescriptor () inline static
Definition at line 872 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.internal_static_grSim_BallReplacement_descriptor.
{
         return GrSimReplacement.internal_static_grSim_BallReplacement_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.getDescriptorForType () inline
Definition at line 916 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.getDescriptor().
{
         return GrSimReplacement.grSim_BallReplacement.getDescriptor();
       }
double Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.getVx () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 1110 of file GrSimReplacement.java.
{
         return vx_;
       }
double Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.getVy () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 1131 of file GrSimReplacement.java.
{
         return vy_;
       }
double Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.getX () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 1068 of file GrSimReplacement.java.
{
         return x_;
       }
double Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.getY () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 1089 of file GrSimReplacement.java.
{
         return y_;
       }
boolean Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.hasVx () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 1107 of file GrSimReplacement.java.
{
         return ((bitField0_ & 0x00000004) == 0x00000004);
       }
boolean Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.hasVy () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 1128 of file GrSimReplacement.java.
{
         return ((bitField0_ & 0x00000008) == 0x00000008);
       }
boolean Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.hasX () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 1065 of file GrSimReplacement.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
boolean Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.hasY () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 1086 of file GrSimReplacement.java.
{
         return ((bitField0_ & 0x00000002) == 0x00000002);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 877 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.internal_static_grSim_BallReplacement_fieldAccessorTable.
{
         return GrSimReplacement.internal_static_grSim_BallReplacement_fieldAccessorTable;
       }
final boolean Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.isInitialized () inline
Definition at line 994 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasX(), and Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasY().
{
         if (!hasX()) {
           return false;
         }
         if (!hasY()) {
           return false;
         }
         if (!hasVx()) {
           return false;
         }
         if (!hasVy()) {
           return false;
         }
         return true;
       }
void Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.maybeForceBuilderInitialization () inline private
Definition at line 890 of file GrSimReplacement.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
         }
       }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 967 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.clone(), Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeBall(), Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeFrom(), and Protobuf.GrSimReplacement.grSim_BallReplacement.newBuilder().
{
         if (other instanceof GrSimReplacement.grSim_BallReplacement) {
           return mergeFrom((GrSimReplacement.grSim_BallReplacement)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.mergeFrom (GrSimReplacement.grSim_BallReplacement other) inline
Definition at line 976 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.getDefaultInstance().
{
         if (other == GrSimReplacement.grSim_BallReplacement.getDefaultInstance()) return this;
         if (other.hasX()) {
           setX(other.getX());
         }
         if (other.hasY()) {
           setY(other.getY());
         }
         if (other.hasVx()) {
           setVx(other.getVx());
         }
         if (other.hasVy()) {
           setVy(other.getVy());
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 1014 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.Builder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 9: {
               bitField0_ |= 0x00000001;
               x_ = input.readDouble();
               break;
             }
             case 17: {
               bitField0_ |= 0x00000002;
               y_ = input.readDouble();
               break;
             }
             case 25: {
               bitField0_ |= 0x00000004;
               vx_ = input.readDouble();
               break;
             }
             case 33: {
               bitField0_ |= 0x00000008;
               vy_ = input.readDouble();
               break;
             }
           }
         }
       }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.setVx (double value) inline
Definition at line 1113 of file GrSimReplacement.java.
{
         bitField0_ |= 0x00000004;
         vx_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.setVy (double value) inline
Definition at line 1134 of file GrSimReplacement.java.
{
         bitField0_ |= 0x00000008;
         vy_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.setX (double value) inline
Definition at line 1071 of file GrSimReplacement.java.
{
         bitField0_ |= 0x00000001;
         x_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.setY (double value) inline
Definition at line 1092 of file GrSimReplacement.java.
{
         bitField0_ |= 0x00000002;
         y_ = value;
         onChanged();
         return this;
       }
Field Documentation
int Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.bitField0_ private
Definition at line 1061 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.vx_ private
Definition at line 1106 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.vy_ private
Definition at line 1127 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.x_ private
Definition at line 1064 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.y_ private
Definition at line 1085 of file GrSimReplacement.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimReplacement.java