Documentation: FrameLimiter Class Reference
FrameLimiter Class Reference
#include <framelimiter.h>
Public Member Functions
FrameLimiter ()
void init (double fps)
~FrameLimiter ()
void waitForNextFrame ()
Private Attributes
double TLastDraw
double TLastOverShoot
double desired_fps
bool was_init
Timer timer
Detailed Description
Definition at line 15 of file framelimiter.h.
Constructor & Destructor Documentation
FrameLimiter::FrameLimiter () inline
Definition at line 24 of file framelimiter.h.
                  {
     was_init=false;
   };
FrameLimiter::~FrameLimiter () inline
Definition at line 37 of file framelimiter.h.
 {};
Member Function Documentation
void FrameLimiter::init (double fps) inline
Definition at line 29 of file framelimiter.h.
References Timer::midtime(), and Timer::start().
Referenced by CaptureGenerator::startCapture().
{
     desired_fps=fps;
     TLastDraw=timer.midtime();
     TLastOverShoot=timer.midtime();
     timer.start();
     was_init=true;
   };
void FrameLimiter::waitForNextFrame () inline
Definition at line 40 of file framelimiter.h.
References desired_fps, Timer::midtime(), TLastDraw, and TLastOverShoot.
Referenced by CaptureGenerator::getFrame().
{
     if (was_init==false) {
       printf("Need to call init() first before waitForNextFrame()\n");
     }
     // Wait if we are ahead of the desired framerate
     double waiting=1.0 / desired_fps;
     double curtime=timer.midtime();
     double diff=waiting-(curtime-TLastDraw);
     if (diff > 0) {
     //Compensate for any previous sluggish Frames:
       if (TLastOverShoot > 0 && TLastOverShoot < diff) diff-=TLastOverShoot;
       if (diff > waiting) diff=waiting;
       usleep((unsigned long)(diff*1.0E6));
     }
     TLastDraw=timer.midtime();
     TLastOverShoot=(TLastDraw-curtime)-diff;
   };
Field Documentation
double FrameLimiter::desired_fps private
Definition at line 19 of file framelimiter.h.
Referenced by waitForNextFrame().
Timer FrameLimiter::timer private
Definition at line 21 of file framelimiter.h.
double FrameLimiter::TLastDraw private
Definition at line 17 of file framelimiter.h.
Referenced by waitForNextFrame().
double FrameLimiter::TLastOverShoot private
Definition at line 18 of file framelimiter.h.
Referenced by waitForNextFrame().
bool FrameLimiter::was_init private
Definition at line 20 of file framelimiter.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/framelimiter.h