Documentation: belief_state/src/svg.cpp File Reference
svg.cpp File Reference
#include <cstdio>
#include <cstddef>
#include <cmath>
#include <vector>
#include <bits/stdc++.h>
#include "ros/ros.h"
#include <krssg_ssl_msgs/BeliefState.h>
Data Structures
class float_mat
Macros
#define WINDOW_SIZE 2
#define LAST_FRAMES 6
#define POLY_DEG 3
Functions
void permute (float_mat &A, std::vector< int > &idx)
permute() orders the rows of A to match the integers in the index array.
static int partial_pivot (float_mat &A, const size_t row, const size_t col, std::deque< double > &scale, std::vector< int > &idx, double tol)
Implicit partial pivoting.
static void lu_backsubst (float_mat &A, float_mat &a, bool diag=false)
Perform backward substitution.
static void lu_forwsubst (float_mat &A, float_mat &a, bool diag=true)
Perform forward substitution.
static int lu_factorize (float_mat &A, std::vector< int > &idx, double tol=TINY_FLOAT)
Performs LU factorization in place.
static float_mat lin_solve (const float_mat &A, const float_mat &a, double tol=TINY_FLOAT)
Solve a system of linear equations. Solves the inhomogeneous matrix problem with lu-decomposition. Note that inversion may be accomplished by setting a to the identity_matrix.
static float_mat invert (const float_mat &A)
Returns the inverse of a matrix using LU-decomposition.
static float_mat transpose (const float_mat &a)
returns the transposed matrix.
float_mat operator* (const float_mat &a, const float_mat &b)
matrix multiplication.
static std::deque< double > sg_coeff (const std::deque< double > &b, const size_t deg)
calculate savitzky golay coefficients.
std::deque< double > sg_smooth (const std::deque< double > &v, const int width, const int deg)
savitzky golay smoothing.
static std::deque< double > lsqr_fprime (const std::deque< double > &b, const int deg)
std::deque< double > sg_derivative (const std::deque< double > &v, const int width, const int deg, const double h)
savitzky golay smoothed numerical derivative.
void bsCallback (const krssg_ssl_msgs::BeliefState &msg_org)
int main (int argc, char **argv)
Variables
static const double TINY_FLOAT = 1.0e-300
default convergence
ros::Publisher pub
std::deque< double > vect_ball_x
two dimensional floating point array
std::deque< double > vect_ball_y
std::deque< double > vect_ball_vel_x
std::deque< double > vect_home_Pos_x [6]
std::deque< double > vect_home_Pos_y [6]
std::deque< double > vect_away_Pos_x [6]
std::deque< double > vect_away_Pos_y [6]
Macro Definition Documentation
#define LAST_FRAMES 6
Definition at line 2 of file svg.cpp.
Referenced by bsCallback().
#define POLY_DEG 3
Definition at line 3 of file svg.cpp.
Referenced by bsCallback().
#define WINDOW_SIZE 2
Definition at line 1 of file svg.cpp.
Referenced by bsCallback().
Function Documentation
void bsCallback (const krssg_ssl_msgs::BeliefState & msg_org)
Definition at line 567 of file svg.cpp.
References test_fsm::BeliefState, velocity.pid_::i, LAST_FRAMES, POLY_DEG, pub, sg_smooth(), and WINDOW_SIZE.
Referenced by main().
 {
   // system("sleep 0.01s");
   krssg_ssl_msgs::BeliefState msg;
   msg.isteamyellow=msg_org.isteamyellow;
   msg.frame_number=msg_org.frame_number ;
   msg.t_capture=msg_org.t_capture  ;
   msg.t_sent=msg_org.t_sent   ;
   msg.ballPos=msg_org.ballPos  ;
   msg.ballVel=msg_org.ballVel  ;
   msg.awayPos=msg_org.awayPos ;
   msg.homePos=msg_org.homePos;
   msg.ballDetected=msg_org.ballDetected;
   msg.homeDetected=msg_org.homeDetected;
   msg.awayDetected=msg_org.awayDetected;
   msg.our_bot_closest_to_ball=msg_org.our_bot_closest_to_ball;
   msg.opp_bot_closest_to_ball=msg_org.opp_bot_closest_to_ball;
   msg.our_goalie=msg_org.our_goalie;
   msg.opp_goalie=msg_org.opp_goalie;
   msg.opp_bot_marking_our_attacker=msg_org.opp_bot_marking_our_attacker;
   msg.ball_at_corners=msg_org.ball_at_corners;
   msg.ball_in_our_half=msg_org.ball_in_our_half;
   msg.ball_in_our_possession=msg_org.ball_in_our_possession;
   float ball_x = msg.ballPos.x;
   float ball_y = msg.ballPos.y;
   vect_ball_x.push_back(ball_x);
   if (vect_ball_x.size()>LAST_FRAMES)
     vect_ball_x.pop_front();
   // std::cout<<"here1\n";
   vect_ball_x = sg_smooth(vect_ball_x,WINDOW_SIZE, POLY_DEG);
   // std::cout<<"here1.5\n"<<vect_ball_x.size()<<std::endl;
   // std::cout<<"size: "<<vect_ball_x.size()<<std::endl;
   msg.ballPos.x = vect_ball_x[vect_ball_x.size()-1];
   vect_ball_y.push_back(ball_y);
   if (vect_ball_y.size()>LAST_FRAMES)
     vect_ball_y.pop_front();
   vect_ball_y = sg_smooth(vect_ball_y,WINDOW_SIZE, POLY_DEG);
   // std::cout<<"here2\n";
   msg.ballPos.y = vect_ball_y[vect_ball_y.size()-1];
   // std::cout<<"here2\n";
   for (int i=0; i<6; i++)
   {
       float bot_x = msg.homePos[i].x;
       vect_home_Pos_x[i].push_back(bot_x);
       if (vect_home_Pos_x[i].size()>LAST_FRAMES)
         vect_home_Pos_x[i].pop_front();
       vect_home_Pos_x[i] = sg_smooth(vect_home_Pos_x[i],WINDOW_SIZE, POLY_DEG);
       msg.homePos[i].x = vect_home_Pos_x[i][vect_home_Pos_x[i].size()-1];
       float bot_y = msg.homePos[i].y;
       vect_home_Pos_y[i].push_back(bot_y);
       if (vect_home_Pos_y[i].size()>LAST_FRAMES)
         vect_home_Pos_y[i].pop_front();
       vect_home_Pos_y[i] = sg_smooth(vect_home_Pos_y[i],WINDOW_SIZE, POLY_DEG);
       msg.homePos[i].y = vect_home_Pos_y[i][vect_home_Pos_y[i].size()-1];
       // std::cout<<"here3\n";
   }
       // std::cout<<"here3\n";
     // std::cout<<"here4\n";
     // std::cout<<"here4\n";
   for (int i=0; i<6; i++)
   {
       float bot_x = msg.awayPos[i].x;
       vect_away_Pos_x[i].push_back(bot_x);
       if (vect_away_Pos_x[i].size()>LAST_FRAMES)
         vect_away_Pos_x[i].pop_front();
       vect_away_Pos_x[i] = sg_smooth(vect_away_Pos_x[i],WINDOW_SIZE, POLY_DEG);
       msg.awayPos[i].x = vect_away_Pos_x[i][vect_away_Pos_x[i].size()-1];
       float bot_y = msg.awayPos[i].y;
       vect_away_Pos_y[i].push_back(bot_y);
       if (vect_away_Pos_y[i].size()>LAST_FRAMES)
         vect_away_Pos_y[i].pop_front();
       vect_away_Pos_y[i] = sg_smooth(vect_away_Pos_y[i],WINDOW_SIZE, POLY_DEG);
       msg.awayPos[i].y = vect_away_Pos_y[i][vect_away_Pos_y[i].size()-1];
   }
   std::cout<<"Bot 0 Orig: "<<msg_org.homePos[0].x<<", "<<msg_org.homePos[0].y<<std::endl;
   std::cout<<"Bot 0 Now : "<<msg.homePos[0].x<<", "<<msg.homePos[0].y<<std::endl;
   std::cout<<"Ball org: "<<msg_org.homePos[0].x<<", "<<msg_org.homePos[0].y<<std::endl;
   std::cout<<"Ball now: "<<msg.homePos[0].x<<", "<<msg.homePos[0].y<<std::endl;
   pub.publish(msg);
   // ROS_INFO("I heard: [%s]", msg->data.c_str());
 }
static float_mat invert (const float_mat & A) static
Returns the inverse of a matrix using LU-decomposition.
Definition at line 325 of file svg.cpp.
References velocity.pid_::i, and lin_solve().
Referenced by lsqr_fprime(), and sg_coeff().
 {
     const int n = A.size();
     float_mat E(n, n, 0.0);
     float_mat B(A);
     int i;
     for (i = 0; i < n; ++i) {
         E[i][i] = 1.0;
     }
     return lin_solve(B, E);
 }
static float_mat lin_solve (const float_mat & A, const float_mat & a, double tol = TINY_FLOAT) static
Solve a system of linear equations. Solves the inhomogeneous matrix problem with lu-decomposition. Note that inversion may be accomplished by setting a to the identity_matrix.
Definition at line 302 of file svg.cpp.
References lu_backsubst(), lu_factorize(), lu_forwsubst(), float_mat::nr_rows(), and permute().
Referenced by invert().
 {
     float_mat B(A);
     float_mat b(a);
     std::vector<int> idx(B.nr_rows());
     int j;
     for (j = 0; j < B.nr_rows(); ++j) {
         idx[j] = j;  // init row swap label array
     }
     lu_factorize(B,idx,tol); // get the lu-decomp.
     permute(b,idx);          // sort the inhomogeneity to match the lu-decomp
     lu_forwsubst(B,b);       // solve the forward problem
     lu_backsubst(B,b);       // solve the backward problem
     return b;
 }
static std::deque<double> lsqr_fprime (const std::deque< double > & b, const int deg) static
least squares fit a polynome of degree 'deg' to data in 'b'. then calculate the first derivative and return it.
Definition at line 486 of file svg.cpp.
References velocity.pid_::i, invert(), and transpose().
Referenced by sg_derivative().
 {
     const int rows(b.size());
     const int cols(deg + 1);
     float_mat A(rows, cols);
     std::deque<double> res(rows);
     // generate input matrix for least squares fit
     int i,j;
     for (i = 0; i < rows; ++i) {
         for (j = 0; j < cols; ++j) {
             A[i][j] = pow(double(i), double(j));
         }
     }
     float_mat c(invert(transpose(A) * A) * (transpose(A) * transpose(b)));
     for (i = 0; i < b.size(); ++i) {
         res[i] = c[1][0];
         for (j = 1; j < deg; ++j) {
             res[i] += c[j + 1][0] * double(j+1)
                 * pow(double(i), double(j));
         }
     }
     return res;
 }
static void lu_backsubst (float_mat & A, float_mat & a, bool diag = false) static
Perform backward substitution.
Solves the system of equations A*b=a, ASSUMING that A is upper triangular. If diag==1, then the diagonal elements are additionally assumed to be 1. Note that the lower triangular elements are never checked, so this function is valid to use after a LU-decomposition in place. A is not modified, and the solution, b, is returned in a.
Definition at line 206 of file svg.cpp.
References k, float_mat::nr_cols(), and float_mat::nr_rows().
Referenced by lin_solve().
 {
     int r,c,k;
     for (r = (A.nr_rows() - 1); r >= 0; --r) {
         for (c = (A.nr_cols() - 1); c > r; --c) {
             for (k = 0; k < A.nr_cols(); ++k) {
                 a[r][k] -= A[r][c] * a[c][k];
             }
         }
         if(!diag) {
             for (k = 0; k < A.nr_cols(); ++k) {
                 a[r][k] /= A[r][r];
             }
         }
     }
 }
static int lu_factorize (float_mat & A, std::vector< int > & idx, double tol = TINY_FLOAT) static
Performs LU factorization in place.
This is Crout's algorithm (cf., Num. Rec. in C, Section 2.3). The map of swapped indeces is recorded in idx. The return value is +1 or -1 depending on whether the number of row swaps was even or odd respectively. idx must be preinitialized to a valid set of indices (e.g., {1,2, ... ,A.nr_rows()}).
Definition at line 255 of file svg.cpp.
References velocity.pid_::i, float_mat::nr_cols(), float_mat::nr_rows(), partial_pivot(), permute(), and TINY_FLOAT.
Referenced by lin_solve().
 {
     if ( tol <= 0.0)
         tol = TINY_FLOAT;
     if ((A.nr_rows() == 0) || (A.nr_rows() != A.nr_cols())) {
       //sgs_error("lu_factorize(): cannot handle empty "
       //           "or nonsquare matrices.\n");
         return 0;
     }
     std::deque<double> scale(A.nr_rows());  // implicit pivot scaling
     int i,j;
     for (i = 0; i < A.nr_rows(); ++i) {
         double maxval = 0.0;
         for (j = 0; j < A.nr_cols(); ++j) {
             if (fabs(A[i][j]) > maxval)
                 maxval = fabs(A[i][j]);
         }
         if (maxval == 0.0) {
       //sgs_error("lu_factorize(): zero pivot found.\n");
             return 0;
         }
         scale[i] = 1.0 / maxval;
     }
     int swapNum = 1;
     int c,r;
     for (c = 0; c < A.nr_cols() ; ++c) {            // loop over columns
         swapNum *= partial_pivot(A, c, c, scale, idx, tol); // bring pivot to diagonal
         for(r = 0; r < A.nr_rows(); ++r) {      //  loop over rows
             int lim = (r < c) ? r : c;
             for (j = 0; j < lim; ++j) {
                 A[idx[r]][c] -= A[idx[r]][j] * A[idx[j]][c];
             }
             if (r > c)
                 A[idx[r]][c] /= A[idx[c]][c];
         }
     }
     permute(A,idx);
     return swapNum;
 }
static void lu_forwsubst (float_mat & A, float_mat & a, bool diag = true) static
Perform forward substitution.
Solves the system of equations A*b=a, ASSUMING that A is lower triangular. If diag==1, then the diagonal elements are additionally assumed to be 1. Note that the upper triangular elements are never checked, so this function is valid to use after a LU-decomposition in place. A is not modified, and the solution, b, is returned in a.
Definition at line 231 of file svg.cpp.
References k, float_mat::nr_cols(), and float_mat::nr_rows().
Referenced by lin_solve().
 {
     int r,k,c;
     for (r = 0;r < A.nr_rows(); ++r) {
         for(c = 0; c < r; ++c) {
             for (k = 0; k < A.nr_cols(); ++k) {
                 a[r][k] -= A[r][c] * a[c][k];
             }
         }
         if(!diag) {
             for (k = 0; k < A.nr_cols(); ++k) {
                 a[r][k] /= A[r][r];
             }
         }
     }
 }
int main (int argc, char ** argv)
Definition at line 679 of file svg.cpp.
References test_fsm::BeliefState, bsCallback(), role._GoToPoint::init(), and pub.
 {
   ros::init(argc, argv, "filter");
   ros::NodeHandle n;
   ros::Subscriber sub = n.subscribe("vision", 1000, bsCallback);
   pub = n.advertise<krssg_ssl_msgs::BeliefState>("belief_state", 1000);
   ros::spin();
   return 0;
 }
float_mat operator* (const float_mat & a, const float_mat & b)
matrix multiplication.
Definition at line 354 of file svg.cpp.
References velocity.pid_::i, k, float_mat::nr_cols(), and float_mat::nr_rows().
 {
     float_mat res(a.nr_rows(), b.nr_cols());
     if (a.nr_cols() != b.nr_rows()) {
       //sgs_error("incompatible matrices in multiplication\n");
         return res;
     }
     int i,j,k;
     for (i = 0; i < a.nr_rows(); ++i) {
         for (j = 0; j < b.nr_cols(); ++j) {
             double sum(0.0);
             for (k = 0; k < a.nr_cols(); ++k) {
                 sum += a[i][k] * b[k][j];
             }
             res[i][j] = sum;
         }
     }
     return res;
 }
static int partial_pivot (float_mat & A, const size_t row, const size_t col, std::deque< double > & scale, std::vector< int > & idx, double tol) static
Implicit partial pivoting.
The function looks for pivot element only in rows below the current element, A[idx[row]][column], then swaps that row with the current one in the index map. The algorithm is for implicit pivoting (i.e., the pivot is chosen as if the max coefficient in each row is set to 1) based on the scaling information in the vector scale. The map of swapped indices is recorded in swp. The return value is +1 or -1 depending on whether the number of row swaps was even or odd respectively.
Definition at line 160 of file svg.cpp.
References float_mat::nr_rows(), and TINY_FLOAT.
Referenced by lu_factorize().
 {
     if (tol <= 0.0)
         tol = TINY_FLOAT;
     int swapNum = 1;
     // default pivot is the current position, [row,col]
     int pivot = row;
     double piv_elem = fabs(A[idx[row]][col]) * scale[idx[row]];
     // loop over possible pivots below current
     int j;
     for (j = row + 1; j < A.nr_rows(); ++j) {
         const double tmp = fabs(A[idx[j]][col]) * scale[idx[j]];
         // if this elem is larger, then it becomes the pivot
         if (tmp > piv_elem) {
             pivot = j;
             piv_elem = tmp;
         }
     }
 #if 0
     if(piv_elem < tol) {
       //sgs_error("partial_pivot(): Zero pivot encountered.\n")
 #endif
     if(pivot > row) {           // bring the pivot to the diagonal
         j = idx[row];           // reorder swap array
         idx[row] = idx[pivot];
         idx[pivot] = j;
         swapNum = -swapNum;     // keeping track of odd or even swap
     }
     return swapNum;
 }
void permute (float_mat & A, std::vector< int > & idx)
permute() orders the rows of A to match the integers in the index array.
Definition at line 125 of file svg.cpp.
References velocity.pid_::i, k, and float_mat::nr_rows().
Referenced by lin_solve(), and lu_factorize().
 {
     std::vector<int> i(idx.size());
     int j,k;
     for (j = 0; j < A.nr_rows(); ++j) {
         i[j] = j;
     }
     // loop over permuted indices
     for (j = 0; j < A.nr_rows(); ++j) {
         if (i[j] != idx[j]) {
             // search only the remaining indices
             for (k = j+1; k < A.nr_rows(); ++k) {
                 if (i[k] ==idx[j]) {
                     std::swap(A[j],A[k]); // swap the rows and
                     i[k] = i[j];     // the elements of
                     i[j] = idx[j];   // the ordered index.
                     break; // next j
                 }
             }
         }
     }
 }
static std::deque<double> sg_coeff (const std::deque< double > & b, const size_t deg) static
calculate savitzky golay coefficients.
Definition at line 378 of file svg.cpp.
References velocity.pid_::i, invert(), and transpose().
Referenced by sg_smooth().
 {
     const size_t rows(b.size());
     const size_t cols(deg + 1);
     float_mat A(rows, cols);
     std::deque<double> res(rows);
     // generate input matrix for least squares fit
     int i,j;
     for (i = 0; i < rows; ++i) {
         for (j = 0; j < cols; ++j) {
             A[i][j] = pow(double(i), double(j));
         }
     }
     float_mat c(invert(transpose(A) * A) * (transpose(A) * transpose(b)));
     for (i = 0; i < b.size(); ++i) {
         res[i] = c[0][0];
         for (j = 1; j <= deg; ++j) {
             res[i] += c[j][0] * pow(double(i), double(j));
         }
     }
     return res;
 }
std::deque<double> sg_derivative (const std::deque< double > & v, const int width, const int deg, const double h)
savitzky golay smoothed numerical derivative.
This method means fitting a polynomial of degree 'deg' to a sliding window of width 2w+1 throughout the data.
In contrast to the sg_smooth function we do a brute force attempt by always fitting the data to a polynome of degree 'deg' and using the result.
Definition at line 521 of file svg.cpp.
References velocity.pid_::i, lsqr_fprime(), and v.
 {
     std::deque<double> res(v.size(), 0.0);
     if ((width < 1) || (deg < 1) || (v.size() < (2 * width + 2))) {
       printf("sgsderiv: parameter error.\n");
         return v;
     }
     const int window = 2 * width + 1;
     // handle border cases first because we do not repeat the fit
     // lower part
     std::deque<double> b(window, 0.0);
     int i,j;
     for (i = 0; i < window; ++i) {
         b[i] = v[i] / h;
     }
     const std::deque<double> c(lsqr_fprime(b, deg));
     for (j = 0; j <= width; ++j) {
         res[j] = c[j];
     }
     // upper part. direction of fit is reversed
     for (i = 0; i < window; ++i) {
         b[i] = v[v.size() - 1 - i] / h;
     }
     const std::deque<double> d(lsqr_fprime(b, deg));
     for (i = 0; i <= width; ++i) {
         res[v.size() - 1 - i] = -d[i];
     }
     // now loop over rest of data. wasting a lot of least squares calcs
     // since we only use the middle value.
     #if defined(_OPENMP)
     #pragma omp parallel for private(i,j) schedule(static)
     #endif
     for (i = 1; i < (v.size() - window); ++i) {
         for (j = 0; j < window; ++j) {
             b[j] = v[i + j] / h;
         }
         res[i + width] = lsqr_fprime(b, deg)[width];
     }
     return res;
 }
std::deque<double> sg_smooth (const std::deque< double > & v, const int width, const int deg)
savitzky golay smoothing.
This method means fitting a polynome of degree 'deg' to a sliding window of width 2w+1 throughout the data. The needed coefficients are generated dynamically by doing a least squares fit on a "symmetric" unit vector of size 2w+1, e.g. for w=2 b=(0,0,1,0,0). evaluating the polynome yields the sg-coefficients. at the border non symmectric vectors b are used.
Definition at line 412 of file svg.cpp.
References velocity.pid_::i, sg_coeff(), and v.
Referenced by bsCallback().
 {
     std::deque<double> res(v.size(), 0.0);
     if ((width < 1) || (deg < 0) || (v.size() < (2 * width + 2))) {
       //sgs_error("sgsmooth: parameter error.\n");
         return v;
     }
     const int window = 2 * width + 1;
     const int endidx = v.size() - 1;
     // do a regular sliding window average
     int i,j;
     if (deg == 0) {
         // handle border cases first because we need different coefficients
 #if defined(_OPENMP)
 #pragma omp parallel for private(i,j) schedule(static)
 #endif
         for (i = 0; i < width; ++i) {
         const double scale = 1.0/double(i+1);
             const std::deque<double> c1(width, scale);
             for (j = 0; j <= i; ++j) {
                 res[i]          += c1[j] * v[j];
                 res[endidx - i] += c1[j] * v[endidx - j];
             }
         }
         // now loop over rest of data. reusing the "symmetric" coefficients.
     const double scale = 1.0/double(window);
         const  std::deque<double> c2(window, scale);
 #if defined(_OPENMP)
 #pragma omp parallel for private(i,j) schedule(static)
 #endif
         for (i = 0; i <= (v.size() - window); ++i) {
             for (j = 0; j < window; ++j) {
                 res[i + width] += c2[j] * v[i + j];
             }
         }
         return res;
     }
     // handle border cases first because we need different coefficients
 #if defined(_OPENMP)
 #pragma omp parallel for private(i,j) schedule(static)
 #endif
     for (i = 0; i < width; ++i) {
         std::deque<double> b1(window, 0.0);
         b1[i] = 1.0;
         const std::deque<double> c1(sg_coeff(b1, deg));
         for (j = 0; j < window; ++j) {
             res[i]          += c1[j] * v[j];
             res[endidx - i] += c1[j] * v[endidx - j];
         }
     }
     // now loop over rest of data. reusing the "symmetric" coefficients.
     std::deque<double> b2(window, 0.0);
     b2[width] = 1.0;
     const std::deque<double> c2(sg_coeff(b2, deg));
 #if defined(_OPENMP)
 #pragma omp parallel for private(i,j) schedule(static)
 #endif
     for (i = 0; i <= (v.size() - window); ++i) {
         for (j = 0; j < window; ++j) {
             res[i + width] += c2[j] * v[i + j];
         }
     }
     return res;
 }
static float_mat transpose (const float_mat & a) static
returns the transposed matrix.
Definition at line 340 of file svg.cpp.
References velocity.pid_::i, float_mat::nr_cols(), and float_mat::nr_rows().
Referenced by lsqr_fprime(), and sg_coeff().
 {
     float_mat res(a.nr_cols(), a.nr_rows());
     int i,j;
     for (i = 0; i < a.nr_rows(); ++i) {
         for (j = 0; j < a.nr_cols(); ++j) {
             res[j][i] = a[i][j];
         }
     }
     return res;
 }
Variable Documentation
ros::Publisher pub
Definition at line 34 of file svg.cpp.
Referenced by bsCallback(), and main().
const double TINY_FLOAT = 1.0e-300 static
default convergence
Definition at line 30 of file svg.cpp.
Referenced by lu_factorize(), and partial_pivot().
std::deque<double> vect_away_Pos_x[6]
Definition at line 52 of file svg.cpp.
std::deque<double> vect_away_Pos_y[6]
Definition at line 53 of file svg.cpp.
std::deque<double> vect_ball_vel_x
Definition at line 49 of file svg.cpp.
std::deque<double> vect_ball_x
two dimensional floating point array
matrix class.
This is a matrix class derived from a vector of std::deque<double>s. Note that the matrix elements indexed [row][column] with indices starting at 0 (c style). Also note that because of its design looping through rows should be faster than looping through columns.
Definition at line 47 of file svg.cpp.
std::deque<double> vect_ball_y
Definition at line 48 of file svg.cpp.
std::deque<double> vect_home_Pos_x[6]
Definition at line 50 of file svg.cpp.
std::deque<double> vect_home_Pos_y[6]
Definition at line 51 of file svg.cpp.