Documentation: Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder Class Reference
Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
MessagesRobocupSslDetection.SSL_DetectionBall getDefaultInstanceForType ()
MessagesRobocupSslDetection.SSL_DetectionBall build ()
MessagesRobocupSslDetection.SSL_DetectionBall buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (MessagesRobocupSslDetection.SSL_DetectionBall other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasConfidence ()
float getConfidence ()
Builder setConfidence (float value)
Builder clearConfidence ()
boolean hasArea ()
int getArea ()
Builder setArea (int value)
Builder clearArea ()
boolean hasX ()
float getX ()
Builder setX (float value)
Builder clearX ()
boolean hasY ()
float getY ()
Builder setY (float value)
Builder clearY ()
boolean hasZ ()
float getZ ()
Builder setZ (float value)
Builder clearZ ()
boolean hasPixelX ()
float getPixelX ()
Builder setPixelX (float value)
Builder clearPixelX ()
boolean hasPixelY ()
float getPixelY ()
Builder setPixelY (float value)
Builder clearPixelY ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
MessagesRobocupSslDetection.SSL_DetectionBall buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
float confidence_
int area_
float x_
float y_
float z_
float pixelX_
float pixelY_
Detailed Description
Definition at line 332 of file MessagesRobocupSslDetection.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.Builder () inline private
Definition at line 346 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.Builder (BuilderParent parent) inline private
Definition at line 350 of file MessagesRobocupSslDetection.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.build () inline
Definition at line 394 of file MessagesRobocupSslDetection.java.
{
         MessagesRobocupSslDetection.SSL_DetectionBall result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 402 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.parseDelimitedFrom().
{
         MessagesRobocupSslDetection.SSL_DetectionBall result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.buildPartial () inline
Definition at line 412 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.confidence_.
{
         MessagesRobocupSslDetection.SSL_DetectionBall result = new MessagesRobocupSslDetection.SSL_DetectionBall(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         result.confidence_ = confidence_;
         if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
           to_bitField0_ |= 0x00000002;
         }
         result.area_ = area_;
         if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
           to_bitField0_ |= 0x00000004;
         }
         result.x_ = x_;
         if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
           to_bitField0_ |= 0x00000008;
         }
         result.y_ = y_;
         if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
           to_bitField0_ |= 0x00000010;
         }
         result.z_ = z_;
         if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
           to_bitField0_ |= 0x00000020;
         }
         result.pixelX_ = pixelX_;
         if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
           to_bitField0_ |= 0x00000040;
         }
         result.pixelY_ = pixelY_;
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.clear () inline
Definition at line 362 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.clear().
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.clear().
{
         super.clear();
         confidence_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000001);
         area_ = 0;
         bitField0_ = (bitField0_ & ~0x00000002);
         x_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000004);
         y_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000008);
         z_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000010);
         pixelX_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000020);
         pixelY_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000040);
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.clearArea () inline
Definition at line 608 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000002);
         area_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.clearConfidence () inline
Definition at line 587 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000001);
         confidence_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.clearPixelX () inline
Definition at line 692 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000020);
         pixelX_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.clearPixelY () inline
Definition at line 713 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.initFields().
{
         bitField0_ = (bitField0_ & ~0x00000040);
         pixelY_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.clearX () inline
Definition at line 629 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000004);
         x_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.clearY () inline
Definition at line 650 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000008);
         y_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.clearZ () inline
Definition at line 671 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000010);
         z_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.clone () inline
Definition at line 381 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.create () inline static private
Definition at line 358 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.newBuilder().
{
         return new Builder();
       }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.getArea () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 599 of file MessagesRobocupSslDetection.java.
{
         return area_;
       }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.getConfidence () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 578 of file MessagesRobocupSslDetection.java.
{
         return confidence_;
       }
MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.getDefaultInstanceForType () inline
Definition at line 390 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getDefaultInstance().
{
         return MessagesRobocupSslDetection.SSL_DetectionBall.getDefaultInstance();
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.getDescriptor () inline static
Definition at line 336 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.internal_static_SSL_DetectionBall_descriptor.
{
         return MessagesRobocupSslDetection.internal_static_SSL_DetectionBall_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.getDescriptorForType () inline
Definition at line 386 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getDescriptor().
{
         return MessagesRobocupSslDetection.SSL_DetectionBall.getDescriptor();
       }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.getPixelX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 683 of file MessagesRobocupSslDetection.java.
{
         return pixelX_;
       }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.getPixelY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 704 of file MessagesRobocupSslDetection.java.
{
         return pixelY_;
       }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.getX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 620 of file MessagesRobocupSslDetection.java.
{
         return x_;
       }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.getY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 641 of file MessagesRobocupSslDetection.java.
{
         return y_;
       }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.getZ () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 662 of file MessagesRobocupSslDetection.java.
{
         return z_;
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.hasArea () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 596 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000002) == 0x00000002);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.hasConfidence () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 575 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.hasPixelX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 680 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000020) == 0x00000020);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.hasPixelY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 701 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000040) == 0x00000040);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.hasX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 617 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000004) == 0x00000004);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.hasY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 638 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000008) == 0x00000008);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.hasZ () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 659 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000010) == 0x00000010);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 341 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.internal_static_SSL_DetectionBall_fieldAccessorTable.
{
         return MessagesRobocupSslDetection.internal_static_SSL_DetectionBall_fieldAccessorTable;
       }
final boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.isInitialized () inline
Definition at line 485 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasConfidence(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasPixelX(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasPixelY(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasX(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasY().
{
         if (!hasConfidence()) {
           return false;
         }
         if (!hasX()) {
           return false;
         }
         if (!hasY()) {
           return false;
         }
         if (!hasPixelX()) {
           return false;
         }
         if (!hasPixelY()) {
           return false;
         }
         return true;
       }
void Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.maybeForceBuilderInitialization () inline private
Definition at line 354 of file MessagesRobocupSslDetection.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
         }
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 449 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.clone(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.newBuilder().
{
         if (other instanceof MessagesRobocupSslDetection.SSL_DetectionBall) {
           return mergeFrom((MessagesRobocupSslDetection.SSL_DetectionBall)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.mergeFrom (MessagesRobocupSslDetection.SSL_DetectionBall other) inline
Definition at line 458 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getDefaultInstance().
{
         if (other == MessagesRobocupSslDetection.SSL_DetectionBall.getDefaultInstance()) return this;
         if (other.hasConfidence()) {
           setConfidence(other.getConfidence());
         }
         if (other.hasArea()) {
           setArea(other.getArea());
         }
         if (other.hasX()) {
           setX(other.getX());
         }
         if (other.hasY()) {
           setY(other.getY());
         }
         if (other.hasZ()) {
           setZ(other.getZ());
         }
         if (other.hasPixelX()) {
           setPixelX(other.getPixelX());
         }
         if (other.hasPixelY()) {
           setPixelY(other.getPixelY());
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 509 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.Builder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 13: {
               bitField0_ |= 0x00000001;
               confidence_ = input.readFloat();
               break;
             }
             case 16: {
               bitField0_ |= 0x00000002;
               area_ = input.readUInt32();
               break;
             }
             case 29: {
               bitField0_ |= 0x00000004;
               x_ = input.readFloat();
               break;
             }
             case 37: {
               bitField0_ |= 0x00000008;
               y_ = input.readFloat();
               break;
             }
             case 45: {
               bitField0_ |= 0x00000010;
               z_ = input.readFloat();
               break;
             }
             case 53: {
               bitField0_ |= 0x00000020;
               pixelX_ = input.readFloat();
               break;
             }
             case 61: {
               bitField0_ |= 0x00000040;
               pixelY_ = input.readFloat();
               break;
             }
           }
         }
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.setArea (int value) inline
Definition at line 602 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000002;
         area_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.setConfidence (float value) inline
Definition at line 581 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000001;
         confidence_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.setPixelX (float value) inline
Definition at line 686 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000020;
         pixelX_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.setPixelY (float value) inline
Definition at line 707 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000040;
         pixelY_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.setX (float value) inline
Definition at line 623 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000004;
         x_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.setY (float value) inline
Definition at line 644 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000008;
         y_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.setZ (float value) inline
Definition at line 665 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000010;
         z_ = value;
         onChanged();
         return this;
       }
Field Documentation
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.area_ private
Definition at line 595 of file MessagesRobocupSslDetection.java.
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.bitField0_ private
Definition at line 571 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.confidence_ private
Definition at line 574 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.pixelX_ private
Definition at line 679 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.pixelY_ private
Definition at line 700 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.x_ private
Definition at line 616 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.y_ private
Definition at line 637 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.z_ private
Definition at line 658 of file MessagesRobocupSslDetection.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslDetection.java