Documentation: Protobuf.GrSimReplacement.grSim_Replacement.Builder Class Reference
Protobuf.GrSimReplacement.grSim_Replacement.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
GrSimReplacement.grSim_Replacement getDefaultInstanceForType ()
GrSimReplacement.grSim_Replacement build ()
GrSimReplacement.grSim_Replacement buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (GrSimReplacement.grSim_Replacement other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasBall ()
GrSimReplacement.grSim_BallReplacement getBall ()
Builder setBall (GrSimReplacement.grSim_BallReplacement value)
Builder setBall (GrSimReplacement.grSim_BallReplacement.Builder builderForValue)
Builder mergeBall (GrSimReplacement.grSim_BallReplacement value)
Builder clearBall ()
GrSimReplacement.grSim_BallReplacement.Builder getBallBuilder ()
GrSimReplacement.grSim_BallReplacementOrBuilder getBallOrBuilder ()
java.util.List< GrSimReplacement.grSim_RobotReplacement > getRobotsList ()
int getRobotsCount ()
GrSimReplacement.grSim_RobotReplacement getRobots (int index)
Builder setRobots (int index, GrSimReplacement.grSim_RobotReplacement value)
Builder setRobots (int index, GrSimReplacement.grSim_RobotReplacement.Builder builderForValue)
Builder addRobots (GrSimReplacement.grSim_RobotReplacement value)
Builder addRobots (int index, GrSimReplacement.grSim_RobotReplacement value)
Builder addRobots (GrSimReplacement.grSim_RobotReplacement.Builder builderForValue)
Builder addRobots (int index, GrSimReplacement.grSim_RobotReplacement.Builder builderForValue)
Builder addAllRobots (java.lang.Iterable<?extends GrSimReplacement.grSim_RobotReplacement > values)
Builder clearRobots ()
Builder removeRobots (int index)
GrSimReplacement.grSim_RobotReplacement.Builder getRobotsBuilder (int index)
GrSimReplacement.grSim_RobotReplacementOrBuilder getRobotsOrBuilder (int index)
java.util.List<?extends GrSimReplacement.grSim_RobotReplacementOrBuilder > getRobotsOrBuilderList ()
GrSimReplacement.grSim_RobotReplacement.Builder addRobotsBuilder ()
GrSimReplacement.grSim_RobotReplacement.Builder addRobotsBuilder (int index)
java.util.List< GrSimReplacement.grSim_RobotReplacement.Builder > getRobotsBuilderList ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
GrSimReplacement.grSim_Replacement buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
com.google.protobuf.SingleFieldBuilder< GrSimReplacement.grSim_BallReplacement, GrSimReplacement.grSim_BallReplacement.Builder, GrSimReplacement.grSim_BallReplacementOrBuilder > getBallFieldBuilder ()
void ensureRobotsIsMutable ()
com.google.protobuf.RepeatedFieldBuilder< GrSimReplacement.grSim_RobotReplacement, GrSimReplacement.grSim_RobotReplacement.Builder, GrSimReplacement.grSim_RobotReplacementOrBuilder > getRobotsFieldBuilder ()
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
GrSimReplacement.grSim_BallReplacement ball_ = GrSimReplacement.grSim_BallReplacement.getDefaultInstance()
com.google.protobuf.SingleFieldBuilder< GrSimReplacement.grSim_BallReplacement, GrSimReplacement.grSim_BallReplacement.Builder, GrSimReplacement.grSim_BallReplacementOrBuilder > ballBuilder_
java.util.List< GrSimReplacement.grSim_RobotReplacement > robots_
com.google.protobuf.RepeatedFieldBuilder< GrSimReplacement.grSim_RobotReplacement, GrSimReplacement.grSim_RobotReplacement.Builder, GrSimReplacement.grSim_RobotReplacementOrBuilder > robotsBuilder_
Detailed Description
Definition at line 1382 of file GrSimReplacement.java.
Constructor & Destructor Documentation
Protobuf.GrSimReplacement.grSim_Replacement.Builder.Builder () inline private
Definition at line 1396 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.GrSimReplacement.grSim_Replacement.Builder.Builder (BuilderParent parent) inline private
Definition at line 1400 of file GrSimReplacement.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.addAllRobots (java.lang.Iterable<?extends GrSimReplacement.grSim_RobotReplacement > values) inline
Definition at line 1790 of file GrSimReplacement.java.
{
         if (robotsBuilder_ == null) {
           ensureRobotsIsMutable();
           super.addAll(values, robots_);
           onChanged();
         } else {
           robotsBuilder_.addAllMessages(values);
         }
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.addRobots (GrSimReplacement.grSim_RobotReplacement value) inline
Definition at line 1741 of file GrSimReplacement.java.
{
         if (robotsBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureRobotsIsMutable();
           robots_.add(value);
           onChanged();
         } else {
           robotsBuilder_.addMessage(value);
         }
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.addRobots (int index, GrSimReplacement.grSim_RobotReplacement value) inline
Definition at line 1754 of file GrSimReplacement.java.
{
         if (robotsBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureRobotsIsMutable();
           robots_.add(index, value);
           onChanged();
         } else {
           robotsBuilder_.addMessage(index, value);
         }
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.addRobots (GrSimReplacement.grSim_RobotReplacement.Builder builderForValue) inline
Definition at line 1768 of file GrSimReplacement.java.
{
         if (robotsBuilder_ == null) {
           ensureRobotsIsMutable();
           robots_.add(builderForValue.build());
           onChanged();
         } else {
           robotsBuilder_.addMessage(builderForValue.build());
         }
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.addRobots (int index, GrSimReplacement.grSim_RobotReplacement.Builder builderForValue) inline
Definition at line 1779 of file GrSimReplacement.java.
{
         if (robotsBuilder_ == null) {
           ensureRobotsIsMutable();
           robots_.add(index, builderForValue.build());
           onChanged();
         } else {
           robotsBuilder_.addMessage(index, builderForValue.build());
         }
         return this;
       }
GrSimReplacement.grSim_RobotReplacement.Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.addRobotsBuilder () inline
Definition at line 1840 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.getDefaultInstance().
{
         return getRobotsFieldBuilder().addBuilder(
             GrSimReplacement.grSim_RobotReplacement.getDefaultInstance());
       }
GrSimReplacement.grSim_RobotReplacement.Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.addRobotsBuilder (int index) inline
Definition at line 1844 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.getDefaultInstance().
                      {
         return getRobotsFieldBuilder().addBuilder(
             index, GrSimReplacement.grSim_RobotReplacement.getDefaultInstance());
       }
GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.Builder.build () inline
Definition at line 1444 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.Builder.setBall().
{
         GrSimReplacement.grSim_Replacement result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 1452 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.parseDelimitedFrom().
{
         GrSimReplacement.grSim_Replacement result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.Builder.buildPartial () inline
Definition at line 1462 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_Replacement.ball_.
Referenced by Protobuf.GrSimPacket.grSim_Packet.Builder.mergeReplacement().
{
         GrSimReplacement.grSim_Replacement result = new GrSimReplacement.grSim_Replacement(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         if (ballBuilder_ == null) {
           result.ball_ = ball_;
         } else {
           result.ball_ = ballBuilder_.build();
         }
         if (robotsBuilder_ == null) {
           if (((bitField0_ & 0x00000002) == 0x00000002)) {
             robots_ = java.util.Collections.unmodifiableList(robots_);
             bitField0_ = (bitField0_ & ~0x00000002);
           }
           result.robots_ = robots_;
         } else {
           result.robots_ = robotsBuilder_.build();
         }
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.clear () inline
Definition at line 1414 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_Replacement.Builder.clear(), and Protobuf.GrSimReplacement.grSim_BallReplacement.getDefaultInstance().
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.Builder.clear().
{
         super.clear();
         if (ballBuilder_ == null) {
           ball_ = GrSimReplacement.grSim_BallReplacement.getDefaultInstance();
         } else {
           ballBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000001);
         if (robotsBuilder_ == null) {
           robots_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000002);
         } else {
           robotsBuilder_.clear();
         }
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.clearBall () inline
Definition at line 1646 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.getDefaultInstance().
{
         if (ballBuilder_ == null) {
           ball_ = GrSimReplacement.grSim_BallReplacement.getDefaultInstance();
           onChanged();
         } else {
           ballBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000001);
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.clearRobots () inline
Definition at line 1801 of file GrSimReplacement.java.
{
         if (robotsBuilder_ == null) {
           robots_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000002);
           onChanged();
         } else {
           robotsBuilder_.clear();
         }
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.clone () inline
Definition at line 1431 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.create () inline static private
Definition at line 1410 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.newBuilder().
{
         return new Builder();
       }
void Protobuf.GrSimReplacement.grSim_Replacement.Builder.ensureRobotsIsMutable () inline private
Definition at line 1685 of file GrSimReplacement.java.
{
         if (!((bitField0_ & 0x00000002) == 0x00000002)) {
           robots_ = new java.util.ArrayList<GrSimReplacement.grSim_RobotReplacement>(robots_);
           bitField0_ |= 0x00000002;
          }
       }
GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_Replacement.Builder.getBall () inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1599 of file GrSimReplacement.java.
{
         if (ballBuilder_ == null) {
           return ball_;
         } else {
           return ballBuilder_.getMessage();
         }
       }
GrSimReplacement.grSim_BallReplacement.Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.getBallBuilder () inline
Definition at line 1656 of file GrSimReplacement.java.
{
         bitField0_ |= 0x00000001;
         onChanged();
         return getBallFieldBuilder().getBuilder();
       }
com.google.protobuf.SingleFieldBuilder< GrSimReplacement.grSim_BallReplacement, GrSimReplacement.grSim_BallReplacement.Builder, GrSimReplacement.grSim_BallReplacementOrBuilder> Protobuf.GrSimReplacement.grSim_Replacement.Builder.getBallFieldBuilder () inline private
Definition at line 1670 of file GrSimReplacement.java.
{
         if (ballBuilder_ == null) {
           ballBuilder_ = new com.google.protobuf.SingleFieldBuilder<
               GrSimReplacement.grSim_BallReplacement, GrSimReplacement.grSim_BallReplacement.Builder, GrSimReplacement.grSim_BallReplacementOrBuilder>(
                   ball_,
                   getParentForChildren(),
                   isClean());
           ball_ = null;
         }
         return ballBuilder_;
       }
GrSimReplacement.grSim_BallReplacementOrBuilder Protobuf.GrSimReplacement.grSim_Replacement.Builder.getBallOrBuilder () inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1661 of file GrSimReplacement.java.
{
         if (ballBuilder_ != null) {
           return ballBuilder_.getMessageOrBuilder();
         } else {
           return ball_;
         }
       }
GrSimReplacement.grSim_Replacement Protobuf.GrSimReplacement.grSim_Replacement.Builder.getDefaultInstanceForType () inline
Definition at line 1440 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_Replacement.getDefaultInstance().
{
         return GrSimReplacement.grSim_Replacement.getDefaultInstance();
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimReplacement.grSim_Replacement.Builder.getDescriptor () inline static
Definition at line 1386 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.internal_static_grSim_Replacement_descriptor.
{
         return GrSimReplacement.internal_static_grSim_Replacement_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimReplacement.grSim_Replacement.Builder.getDescriptorForType () inline
Definition at line 1436 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_Replacement.getDescriptor().
{
         return GrSimReplacement.grSim_Replacement.getDescriptor();
       }
GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_Replacement.Builder.getRobots (int index) inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1709 of file GrSimReplacement.java.
{
         if (robotsBuilder_ == null) {
           return robots_.get(index);
         } else {
           return robotsBuilder_.getMessage(index);
         }
       }
GrSimReplacement.grSim_RobotReplacement.Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.getRobotsBuilder (int index) inline
Definition at line 1821 of file GrSimReplacement.java.
                      {
         return getRobotsFieldBuilder().getBuilder(index);
       }
java.util.List<GrSimReplacement.grSim_RobotReplacement.Builder> Protobuf.GrSimReplacement.grSim_Replacement.Builder.getRobotsBuilderList () inline
Definition at line 1850 of file GrSimReplacement.java.
{
         return getRobotsFieldBuilder().getBuilderList();
       }
int Protobuf.GrSimReplacement.grSim_Replacement.Builder.getRobotsCount () inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1702 of file GrSimReplacement.java.
{
         if (robotsBuilder_ == null) {
           return robots_.size();
         } else {
           return robotsBuilder_.getCount();
         }
       }
com.google.protobuf.RepeatedFieldBuilder< GrSimReplacement.grSim_RobotReplacement, GrSimReplacement.grSim_RobotReplacement.Builder, GrSimReplacement.grSim_RobotReplacementOrBuilder> Protobuf.GrSimReplacement.grSim_Replacement.Builder.getRobotsFieldBuilder () inline private
Definition at line 1855 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_Replacement.initFields().
{
         if (robotsBuilder_ == null) {
           robotsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
               GrSimReplacement.grSim_RobotReplacement, GrSimReplacement.grSim_RobotReplacement.Builder, GrSimReplacement.grSim_RobotReplacementOrBuilder>(
                   robots_,
                   ((bitField0_ & 0x00000002) == 0x00000002),
                   getParentForChildren(),
                   isClean());
           robots_ = null;
         }
         return robotsBuilder_;
       }
java.util.List<GrSimReplacement.grSim_RobotReplacement> Protobuf.GrSimReplacement.grSim_Replacement.Builder.getRobotsList () inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1695 of file GrSimReplacement.java.
{
         if (robotsBuilder_ == null) {
           return java.util.Collections.unmodifiableList(robots_);
         } else {
           return robotsBuilder_.getMessageList();
         }
       }
GrSimReplacement.grSim_RobotReplacementOrBuilder Protobuf.GrSimReplacement.grSim_Replacement.Builder.getRobotsOrBuilder (int index) inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1825 of file GrSimReplacement.java.
                      {
         if (robotsBuilder_ == null) {
           return robots_.get(index);  } else {
           return robotsBuilder_.getMessageOrBuilder(index);
         }
       }
java.util.List<? extends GrSimReplacement.grSim_RobotReplacementOrBuilder> Protobuf.GrSimReplacement.grSim_Replacement.Builder.getRobotsOrBuilderList () inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1833 of file GrSimReplacement.java.
{
         if (robotsBuilder_ != null) {
           return robotsBuilder_.getMessageOrBuilderList();
         } else {
           return java.util.Collections.unmodifiableList(robots_);
         }
       }
boolean Protobuf.GrSimReplacement.grSim_Replacement.Builder.hasBall () inline
Implements Protobuf.GrSimReplacement.grSim_ReplacementOrBuilder.
Definition at line 1596 of file GrSimReplacement.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.GrSimReplacement.grSim_Replacement.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 1391 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.internal_static_grSim_Replacement_fieldAccessorTable.
{
         return GrSimReplacement.internal_static_grSim_Replacement_fieldAccessorTable;
       }
final boolean Protobuf.GrSimReplacement.grSim_Replacement.Builder.isInitialized () inline
Definition at line 1532 of file GrSimReplacement.java.
References velocity.pid_.i.
{
         if (hasBall()) {
           if (!getBall().isInitialized()) {
             return false;
           }
         }
         for (int i = 0; i < getRobotsCount(); i++) {
           if (!getRobots(i).isInitialized()) {
             return false;
           }
         }
         return true;
       }
void Protobuf.GrSimReplacement.grSim_Replacement.Builder.maybeForceBuilderInitialization () inline private
Definition at line 1404 of file GrSimReplacement.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
           getBallFieldBuilder();
           getRobotsFieldBuilder();
         }
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeBall (GrSimReplacement.grSim_BallReplacement value) inline
Definition at line 1630 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.buildPartial(), Protobuf.GrSimReplacement.grSim_BallReplacement.getDefaultInstance(), Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.mergeFrom(), and Protobuf.GrSimReplacement.grSim_BallReplacement.newBuilder().
{
         if (ballBuilder_ == null) {
           if (((bitField0_ & 0x00000001) == 0x00000001) &&
               ball_ != GrSimReplacement.grSim_BallReplacement.getDefaultInstance()) {
             ball_ =
               GrSimReplacement.grSim_BallReplacement.newBuilder(ball_).mergeFrom(value).buildPartial();
           } else {
             ball_ = value;
           }
           onChanged();
         } else {
           ballBuilder_.mergeFrom(value);
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 1488 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.Builder.clone(), Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom(), Protobuf.GrSimPacket.grSim_Packet.Builder.mergeReplacement(), and Protobuf.GrSimReplacement.grSim_Replacement.newBuilder().
{
         if (other instanceof GrSimReplacement.grSim_Replacement) {
           return mergeFrom((GrSimReplacement.grSim_Replacement)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeFrom (GrSimReplacement.grSim_Replacement other) inline
Definition at line 1497 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_Replacement.getDefaultInstance(), and Protobuf.GrSimReplacement.grSim_Replacement.Builder.robots_.
{
         if (other == GrSimReplacement.grSim_Replacement.getDefaultInstance()) return this;
         if (other.hasBall()) {
           mergeBall(other.getBall());
         }
         if (robotsBuilder_ == null) {
           if (!other.robots_.isEmpty()) {
             if (robots_.isEmpty()) {
               robots_ = other.robots_;
               bitField0_ = (bitField0_ & ~0x00000002);
             } else {
               ensureRobotsIsMutable();
               robots_.addAll(other.robots_);
             }
             onChanged();
           }
         } else {
           if (!other.robots_.isEmpty()) {
             if (robotsBuilder_.isEmpty()) {
               robotsBuilder_.dispose();
               robotsBuilder_ = null;
               robots_ = other.robots_;
               bitField0_ = (bitField0_ & ~0x00000002);
               robotsBuilder_ =
                 com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                    getRobotsFieldBuilder() : null;
             } else {
               robotsBuilder_.addAllMessages(other.robots_);
             }
           }
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 1548 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_Replacement.Builder.Builder(), Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.mergeFrom(), Protobuf.GrSimReplacement.grSim_RobotReplacement.newBuilder(), and Protobuf.GrSimReplacement.grSim_BallReplacement.newBuilder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 10: {
               GrSimReplacement.grSim_BallReplacement.Builder subBuilder = GrSimReplacement.grSim_BallReplacement.newBuilder();
               if (hasBall()) {
                 subBuilder.mergeFrom(getBall());
               }
               input.readMessage(subBuilder, extensionRegistry);
               setBall(subBuilder.buildPartial());
               break;
             }
             case 18: {
               GrSimReplacement.grSim_RobotReplacement.Builder subBuilder = GrSimReplacement.grSim_RobotReplacement.newBuilder();
               input.readMessage(subBuilder, extensionRegistry);
               addRobots(subBuilder.buildPartial());
               break;
             }
           }
         }
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.removeRobots (int index) inline
Definition at line 1811 of file GrSimReplacement.java.
{
         if (robotsBuilder_ == null) {
           ensureRobotsIsMutable();
           robots_.remove(index);
           onChanged();
         } else {
           robotsBuilder_.remove(index);
         }
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.setBall (GrSimReplacement.grSim_BallReplacement value) inline
Definition at line 1606 of file GrSimReplacement.java.
{
         if (ballBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ball_ = value;
           onChanged();
         } else {
           ballBuilder_.setMessage(value);
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.setBall (GrSimReplacement.grSim_BallReplacement.Builder builderForValue) inline
Definition at line 1619 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_Replacement.Builder.build().
{
         if (ballBuilder_ == null) {
           ball_ = builderForValue.build();
           onChanged();
         } else {
           ballBuilder_.setMessage(builderForValue.build());
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.setRobots (int index, GrSimReplacement.grSim_RobotReplacement value) inline
Definition at line 1716 of file GrSimReplacement.java.
{
         if (robotsBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureRobotsIsMutable();
           robots_.set(index, value);
           onChanged();
         } else {
           robotsBuilder_.setMessage(index, value);
         }
         return this;
       }
Builder Protobuf.GrSimReplacement.grSim_Replacement.Builder.setRobots (int index, GrSimReplacement.grSim_RobotReplacement.Builder builderForValue) inline
Definition at line 1730 of file GrSimReplacement.java.
{
         if (robotsBuilder_ == null) {
           ensureRobotsIsMutable();
           robots_.set(index, builderForValue.build());
           onChanged();
         } else {
           robotsBuilder_.setMessage(index, builderForValue.build());
         }
         return this;
       }
Field Documentation
GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_Replacement.Builder.ball_ = GrSimReplacement.grSim_BallReplacement.getDefaultInstance() private
Definition at line 1593 of file GrSimReplacement.java.
com.google.protobuf.SingleFieldBuilder< GrSimReplacement.grSim_BallReplacement, GrSimReplacement.grSim_BallReplacement.Builder, GrSimReplacement.grSim_BallReplacementOrBuilder> Protobuf.GrSimReplacement.grSim_Replacement.Builder.ballBuilder_ private
Definition at line 1595 of file GrSimReplacement.java.
int Protobuf.GrSimReplacement.grSim_Replacement.Builder.bitField0_ private
Definition at line 1590 of file GrSimReplacement.java.
java.util.List<GrSimReplacement.grSim_RobotReplacement> Protobuf.GrSimReplacement.grSim_Replacement.Builder.robots_ private
Initial value:
=
        java.util.Collections.emptyList()
Definition at line 1683 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeFrom().
com.google.protobuf.RepeatedFieldBuilder< GrSimReplacement.grSim_RobotReplacement, GrSimReplacement.grSim_RobotReplacement.Builder, GrSimReplacement.grSim_RobotReplacementOrBuilder> Protobuf.GrSimReplacement.grSim_Replacement.Builder.robotsBuilder_ private
Definition at line 1693 of file GrSimReplacement.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimReplacement.java