Documentation: grSim/include/logger.h File Reference
logger.h File Reference
#include <QString>
#include <QColor>
Functions
void initLogger (void *)
void logStatus (QString s, QColor c)
Function Documentation
void initLogger (void *)
Definition at line 22 of file logger.cpp.
Referenced by MainWindow::customFPS().
 {
     printer = (CStatusPrinter*) v;
 }
void logStatus (QString s, QColor c)
Definition at line 27 of file logger.cpp.
References CStatusPrinter::textBuffer.
Referenced by MainWindow::customFPS(), GLWidget::keyPressEvent(), MainWindow::reconnectBlueStatusSocket(), MainWindow::reconnectCommandSocket(), MainWindow::reconnectVisionSocket(), MainWindow::reconnectYellowStatusSocket(), RoboCupSSLServer::send(), and MainWindow::setCurrentRobotPosition().
 {
     printer->textBuffer.enqueue(CStatusText(s,c));
 }