Documentation: grsim_comm/include/proto/messages_robocup_ssl_geometry.pb.cc File Reference
messages_robocup_ssl_geometry.pb.cc File Reference
#include "messages_robocup_ssl_geometry.pb.h"
#include <algorithm>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
Data Structures
class SSL_GeometryFieldSizeDefaultTypeInternal
class SSL_GeometryCameraCalibrationDefaultTypeInternal
class SSL_GeometryDataDefaultTypeInternal
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5fgeometry_2eproto
Namespaces
anonymous_namespace{messages_robocup_ssl_geometry.pb.cc}
Macros
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Functions
const ::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5fgeometry_2eproto () GOOGLE_ATTRIBUTE_COLD
void anonymous_namespace{messages_robocup_ssl_geometry.pb.cc}::protobuf_AssignDescriptors ()
void anonymous_namespace{messages_robocup_ssl_geometry.pb.cc}::protobuf_AssignDescriptorsOnce ()
void anonymous_namespace{messages_robocup_ssl_geometry.pb.cc}::protobuf_RegisterTypes (const ::std::string &) GOOGLE_ATTRIBUTE_COLD
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto ()
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto_impl ()
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto ()
void protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_impl ()
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_once_)
void protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto ()
Variables
SSL_GeometryFieldSizeDefaultTypeInternal _SSL_GeometryFieldSize_default_instance_
SSL_GeometryCameraCalibrationDefaultTypeInternal _SSL_GeometryCameraCalibration_default_instance_
SSL_GeometryDataDefaultTypeInternal _SSL_GeometryData_default_instance_
::google::protobuf::Metadata anonymous_namespace{messages_robocup_ssl_geometry.pb.cc}::file_level_metadata [3]
static const ::google::protobuf::internal::MigrationSchema schemas []
static const ::google::protobuf::internal::DefaultInstanceData file_default_instances []
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5fgeometry_2eproto static_descriptor_initializer_messages_5frobocup_5fssl_5fgeometry_2eproto_
Macro Definition Documentation
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Referenced by SSL_GeometryFieldSize::MergePartialFromCodedStream(), SSL_GeometryCameraCalibration::MergePartialFromCodedStream(), and SSL_GeometryData::MergePartialFromCodedStream().
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
Definition at line 4 of file messages_robocup_ssl_geometry.pb.cc.
Function Documentation
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_once_)
Referenced by protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::AddDescriptors(), protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_FieldCicularArc(), protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_FieldLineSegment(), protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryCameraCalibration(), protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryData(), protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryFieldSize(), protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsVector2f(), protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_impl(), anonymous_namespace{messages_robocup_ssl_geometry.pb.cc}::protobuf_AssignDescriptorsOnce(), protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::protobuf_AssignDescriptorsOnce(), and protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto().
void protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto ()
Definition at line 207 of file messages_robocup_ssl_geometry.pb.cc.
References protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_impl().
Referenced by protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_impl(), anonymous_namespace{messages_robocup_ssl_geometry.pb.cc}::protobuf_AssignDescriptors(), and StaticDescriptorInitializer_messages_5frobocup_5fssl_5fgeometry_2eproto::StaticDescriptorInitializer_messages_5frobocup_5fssl_5fgeometry_2eproto().
{
   ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_once_,
                  &protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_impl);
 }
void protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_impl ()
Definition at line 173 of file messages_robocup_ssl_geometry.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto(), protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::protobuf_RegisterTypes(), and protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto().
Referenced by protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto().
{
   protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto();
   static const char descriptor[] = {
       "\n#messages_robocup_ssl_geometry.proto\"\212\003"
       "\n\025SSL_GeometryFieldSize\022\022\n\nline_width\030\001 "
       "\002(\005\022\024\n\014field_length\030\002 \002(\005\022\023\n\013field_width"
       "\030\003 \002(\005\022\026\n\016boundary_width\030\004 \002(\005\022\025\n\rrefere"
       "e_width\030\005 \002(\005\022\022\n\ngoal_width\030\006 \002(\005\022\022\n\ngoa"
       "l_depth\030\007 \002(\005\022\027\n\017goal_wall_width\030\010 \002(\005\022\034"
       "\n\024center_circle_radius\030\t \002(\005\022\026\n\016defense_"
       "radius\030\n \002(\005\022\027\n\017defense_stretch\030\013 \002(\005\022#\n"
       "\033free_kick_from_defense_dist\030\014 \002(\005\022)\n!pe"
       "nalty_spot_from_field_line_dist\030\r \002(\005\022#\n"
       "\033penalty_line_from_spot_dist\030\016 \002(\005\"\311\002\n\035S"
       "SL_GeometryCameraCalibration\022\021\n\tcamera_i"
       "d\030\001 \002(\r\022\024\n\014focal_length\030\002 \002(\002\022\031\n\021princip"
       "al_point_x\030\003 \002(\002\022\031\n\021principal_point_y\030\004 "
       "\002(\002\022\022\n\ndistortion\030\005 \002(\002\022\n\n\002q0\030\006 \002(\002\022\n\n\002q"
       "1\030\007 \002(\002\022\n\n\002q2\030\010 \002(\002\022\n\n\002q3\030\t \002(\002\022\n\n\002tx\030\n "
       "\002(\002\022\n\n\002ty\030\013 \002(\002\022\n\n\002tz\030\014 \002(\002\022\037\n\027derived_c"
       "amera_world_tx\030\r \001(\002\022\037\n\027derived_camera_w"
       "orld_ty\030\016 \001(\002\022\037\n\027derived_camera_world_tz"
       "\030\017 \001(\002\"h\n\020SSL_GeometryData\022%\n\005field\030\001 \002("
       "\0132\026.SSL_GeometryFieldSize\022-\n\005calib\030\002 \003(\013"
       "2\036.SSL_GeometryCameraCalibration"
   };
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
       descriptor, 872);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "messages_robocup_ssl_geometry.proto", &protobuf_RegisterTypes);
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto);
 }
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto ()
Definition at line 169 of file messages_robocup_ssl_geometry.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), and protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto_impl().
Referenced by SSL_GeometryFieldSize::default_instance(), SSL_GeometryCameraCalibration::default_instance(), SSL_GeometryData::default_instance(), protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_impl(), protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto_impl(), SSL_GeometryCameraCalibration::SSL_GeometryCameraCalibration(), SSL_GeometryData::SSL_GeometryData(), and SSL_GeometryFieldSize::SSL_GeometryFieldSize().
{
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
   ::google::protobuf::GoogleOnceInit(&once, &protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto_impl);
 }
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto_impl ()
Definition at line 158 of file messages_robocup_ssl_geometry.pb.cc.
References SSL_GeometryFieldSize::internal_default_instance().
Referenced by protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto().
{
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::internal::InitProtobufDefaults();
   _SSL_GeometryFieldSize_default_instance_.DefaultConstruct();
   _SSL_GeometryCameraCalibration_default_instance_.DefaultConstruct();
   _SSL_GeometryData_default_instance_.DefaultConstruct();
   _SSL_GeometryData_default_instance_.get_mutable()->field_ = const_cast< ::SSL_GeometryFieldSize*>(
       ::SSL_GeometryFieldSize::internal_default_instance());
 }
const ::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5fgeometry_2eproto ()
Definition at line 34 of file messages_robocup_ssl_geometry.pb.cc.
Referenced by anonymous_namespace{messages_robocup_ssl_geometry.pb.cc}::protobuf_AssignDescriptors().
{
   static const ::google::protobuf::uint32 offsets[] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, line_width_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, field_length_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, field_width_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, boundary_width_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, referee_width_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, goal_width_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, goal_depth_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, goal_wall_width_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, center_circle_radius_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, defense_radius_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, defense_stretch_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, free_kick_from_defense_dist_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, penalty_spot_from_field_line_dist_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, penalty_line_from_spot_dist_),
     0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, camera_id_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, focal_length_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, principal_point_x_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, principal_point_y_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, distortion_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, q0_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, q1_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, q2_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, q3_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, tx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, ty_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, tz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, derived_camera_world_tx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, derived_camera_world_ty_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, derived_camera_world_tz_),
     0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryData, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryData, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryData, field_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryData, calib_),
     0,
     1,
   };
   return offsets;
 }
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto ()
Definition at line 149 of file messages_robocup_ssl_geometry.pb.cc.
References protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::file_level_metadata.
Referenced by protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_impl().
{
   _SSL_GeometryFieldSize_default_instance_.Shutdown();
   delete file_level_metadata[0].reflection;
   _SSL_GeometryCameraCalibration_default_instance_.Shutdown();
   delete file_level_metadata[1].reflection;
   _SSL_GeometryData_default_instance_.Shutdown();
   delete file_level_metadata[2].reflection;
 }
Variable Documentation
SSL_GeometryCameraCalibrationDefaultTypeInternal _SSL_GeometryCameraCalibration_default_instance_
Definition at line 22 of file messages_robocup_ssl_geometry.pb.cc.
Referenced by protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryCameraCalibrationImpl().
SSL_GeometryDataDefaultTypeInternal _SSL_GeometryData_default_instance_
Definition at line 24 of file messages_robocup_ssl_geometry.pb.cc.
Referenced by RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::geometry(), SSL_GeometryData::InitAsDefaultInstance(), protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryDataImpl(), and RoboCup2014Legacy::Geometry::SSL_GeometryData::internal_default_instance().
SSL_GeometryFieldSizeDefaultTypeInternal _SSL_GeometryFieldSize_default_instance_
Definition at line 20 of file messages_robocup_ssl_geometry.pb.cc.
Referenced by RoboCup2014Legacy::Geometry::SSL_GeometryData::field(), protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryFieldSizeImpl(), and RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::internal_default_instance().
const ::google::protobuf::internal::DefaultInstanceData file_default_instances[] static
Initial value:
= {
  {reinterpret_cast<const ::google::protobuf::Message*>(&_SSL_GeometryFieldSize_default_instance_), NULL},
  {reinterpret_cast<const ::google::protobuf::Message*>(&_SSL_GeometryCameraCalibration_default_instance_), NULL},
  {reinterpret_cast<const ::google::protobuf::Message*>(&_SSL_GeometryData_default_instance_), NULL},
}
Definition at line 120 of file messages_robocup_ssl_geometry.pb.cc.
Referenced by anonymous_namespace{messages_robocup_ssl_geometry.pb.cc}::protobuf_AssignDescriptors().
const ::google::protobuf::internal::MigrationSchema schemas[] static
Initial value:
= {
  { 0, 18, sizeof(SSL_GeometryFieldSize)},
  { 32, 51, sizeof(SSL_GeometryCameraCalibration)},
  { 66, 72, sizeof(SSL_GeometryData)},
}
Definition at line 114 of file messages_robocup_ssl_geometry.pb.cc.
Referenced by anonymous_namespace{messages_robocup_ssl_geometry.pb.cc}::protobuf_AssignDescriptors(), and protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::protobuf_AssignDescriptors().
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5fgeometry_2eproto static_descriptor_initializer_messages_5frobocup_5fssl_5fgeometry_2eproto_
Referenced by StaticDescriptorInitializer_messages_5frobocup_5fssl_5fgeometry_2eproto::StaticDescriptorInitializer_messages_5frobocup_5fssl_5fgeometry_2eproto().