Documentation: GUI.ompl_gui Namespace Reference
GUI.ompl_gui Namespace Reference
Data Structures
class MainWindow
Functions
def BS_TO_GUI (x, y)
def debug_path (msg)
def Callback_VelProfile (msg)
def Callback_BS (msg)
def main ()
Variables
int MAJOR_AXIS_FACTOR = 10
int MINOR_AXIS_FACTOR = 2
float PI = 3.141592653589793
int radius = 10
int VEL_ANGLE = 0
list points_home = []
list points_home_theta = []
list points_opp = []
FIELD_MAXX = HALF_FIELD_MAXX
FIELD_MAXY = HALF_FIELD_MAXY
BOT_ID = None
int GUI_X = 600
int GUI_Y = 400
int vel_theta = 0
int vel_mag = 0
list ballPos = [0,0]
BState = None
list curr_vel = [10,0]
int VEL_UNIT = 5
pub = rospy.Publisher('gui_params', point_SF)
kubs_pub = rospy.Publisher('/grsim_data',gr_Commands,queue_size=1000)
int path_received = 0
Function Documentation
def GUI.ompl_gui.BS_TO_GUI (x, y)
Definition at line 36 of file ompl_gui.py.
Referenced by GUI.ompl_gui.Callback_BS(), GUI.ompl_gui.debug_path(), and GUI.ompl_gui.MainWindow.drawBoundary().
 def BS_TO_GUI(x, y):
     #GUI -> 600X400
     x1 = (x + FIELD_MAXX)*GUI_X/(2*FIELD_MAXX)
     y1 = (y + FIELD_MAXY)*GUI_Y/(2*FIELD_MAXY)
     return [x1, y1]
 vrtx_0=[(200,200)]
 vrtx_1=[(200,200)]
 vrtx_2=[(200,200)]
 vrtx_3=[(200,200)]
 vrtx_4=[(200,200)]
 vrtx_5=[(200,200)]
def GUI.ompl_gui.Callback_BS (msg)
Definition at line 108 of file ompl_gui.py.
References GUI.ompl_gui.BS_TO_GUI().
 def Callback_BS(msg):
     global points_home, points_home_theta, points_opp, ballPos
     # print "777"
     BState = msg
     ballPos = BS_TO_GUI(msg.ballPos.x, msg.ballPos.y)
     points_home = []
     points_home_theta = []
     points_opp=[]
     # print(BS_TO_GUI(-HALF_FIELD_MAXX,0))
     for i in msg.homePos:
         points_home.append(BS_TO_GUI(i.x, i.y))
         points_home_theta.append(i.theta)
     for i in msg.awayPos:
         points_opp.append(BS_TO_GUI(i.x, i.y))
def GUI.ompl_gui.Callback_VelProfile (msg)
Definition at line 96 of file ompl_gui.py.
 def Callback_VelProfile(msg):
     global curr_vel, vel_mag, vel_theta
     msg = msg.robot_commands
     theta = float(points_home_theta[BOT_ID])
     vel_theta = atan2(-1*msg.velnormal, msg.veltangent) + theta
     vel_mag = msg.velnormal*msg.velnormal + msg.veltangent*msg.veltangent
     curr_vel = [vel_mag, vel_theta]
     if(vel_mag<0.01):
         VEL_ANGLE = 0
     else:
         VEL_ANGLE = vel_theta
def GUI.ompl_gui.debug_path (msg)
Definition at line 60 of file ompl_gui.py.
References GUI.ompl_gui.BS_TO_GUI(), and print().
 def debug_path(msg):
     global BOT_ID
     BOT_ID = msg.bot_id
     print("New Path Received: BOT_ID = ",BOT_ID)
     global path_received, VEL_ANGLE, vel_theta, vel_mag, vrtx_0, vrtx_1, vrtx_2, vrtx_3, vrtx_4, vrtx_5
     if(BOT_ID==0):
         vrtx_0=[]
         for v in msg.point_array:
             vrtx_0.append((BS_TO_GUI(v.x, v.y)))
     elif BOT_ID==1:
         vrtx_1=[]
         for v in msg.point_array:
             vrtx_1.append((BS_TO_GUI(v.x, v.y)))
     elif BOT_ID==2:
         vrtx_2=[]
         for v in msg.point_array:
             vrtx_2.append((BS_TO_GUI(v.x, v.y)))
     elif BOT_ID==3:
         vrtx_3=[]
         for v in msg.point_array:
             vrtx_3.append((BS_TO_GUI(v.x, v.y)))
     elif BOT_ID==4:
         vrtx_4=[]
         for v in msg.point_array:
             vrtx_4.append((BS_TO_GUI(v.x, v.y)))
     elif BOT_ID==5:
         vrtx_5=[]
         for v in msg.point_array:
             vrtx_5.append((BS_TO_GUI(v.x, v.y)))
     path_received = 1
     # if(vel_mag<0.01):
     #     VEL_ANGLE = atan2(vrtx[2][1]-vrtx[0][1], vrtx[2][0]-vrtx[0][0])
     # else:
     #     VEL_ANGLE = vel_theta
def GUI.ompl_gui.main ()
Definition at line 377 of file ompl_gui.py.
 def main():
     rospy.init_node('display1', anonymous=False)
     rospy.Subscriber("/belief_state", BeliefState , Callback_BS);
     rospy.Subscriber("/grsim_data", gr_Commands , Callback_VelProfile);
     rospy.Subscriber("/path_planner_ompl", planner_path, debug_path)
     w.show()
     app.exec_()
     import signal
     signal.signal(signal.SIGINT, signal.SIG_DFL)
     sys.exit(0)
Variable Documentation
list GUI.ompl_gui.ballPos = [0,0]
Definition at line 33 of file ompl_gui.py.
int GUI.ompl_gui.BOT_ID = None
Definition at line 28 of file ompl_gui.py.
Referenced by path().
GUI.ompl_gui.BState = None
Definition at line 34 of file ompl_gui.py.
list GUI.ompl_gui.curr_vel = [10,0]
Definition at line 51 of file ompl_gui.py.
GUI.ompl_gui.FIELD_MAXX = HALF_FIELD_MAXX
Definition at line 26 of file ompl_gui.py.
GUI.ompl_gui.FIELD_MAXY = HALF_FIELD_MAXY
Definition at line 27 of file ompl_gui.py.
int GUI.ompl_gui.GUI_X = 600
Definition at line 29 of file ompl_gui.py.
int GUI.ompl_gui.GUI_Y = 400
Definition at line 30 of file ompl_gui.py.
GUI.ompl_gui.kubs_pub = rospy.Publisher('/grsim_data',gr_Commands,queue_size=1000)
Definition at line 56 of file ompl_gui.py.
int GUI.ompl_gui.MAJOR_AXIS_FACTOR = 10
Definition at line 16 of file ompl_gui.py.
int GUI.ompl_gui.MINOR_AXIS_FACTOR = 2
Definition at line 17 of file ompl_gui.py.
int GUI.ompl_gui.path_received = 0
Definition at line 58 of file ompl_gui.py.
float GUI.ompl_gui.PI = 3.141592653589793
Definition at line 18 of file ompl_gui.py.
list GUI.ompl_gui.points_home = []
Definition at line 23 of file ompl_gui.py.
list GUI.ompl_gui.points_home_theta = []
Definition at line 24 of file ompl_gui.py.
list GUI.ompl_gui.points_opp = []
Definition at line 25 of file ompl_gui.py.
GUI.ompl_gui.pub = rospy.Publisher('gui_params', point_SF)
Definition at line 55 of file ompl_gui.py.
int GUI.ompl_gui.radius = 10
Definition at line 19 of file ompl_gui.py.
int GUI.ompl_gui.VEL_ANGLE = 0
Definition at line 20 of file ompl_gui.py.
int GUI.ompl_gui.vel_mag = 0
Definition at line 32 of file ompl_gui.py.
int GUI.ompl_gui.vel_theta = 0
Definition at line 31 of file ompl_gui.py.
int GUI.ompl_gui.VEL_UNIT = 5
Definition at line 52 of file ompl_gui.py.