Documentation: ImageIO Class Reference
ImageIO Class Reference
A class containing helper functions for reading and writing image data to/from files.
#include <image_io.h>
Static Public Member Functions
static unsigned char * readGrayscale (int &width, int &height, const char *filename)
static rgb * readRGB (int &width, int &height, const char *filename)
static rgba * readRGBA (int &width, int &height, const char *filename)
static bool writeRGB (rgb *imgbuf, int width, int height, const char *filename)
static bool writePPM (rgb *imgbuf, int width, int height, const char *filename)
Static Protected Member Functions
static void copyBGRAtoRGBA (rgba *dst, unsigned char *src, unsigned int size)
static void copyBGRtoRGB (rgb *dst, unsigned char *src, unsigned int size)
static void copyBGRtoRGBA (rgba *dst, unsigned char *src, unsigned int size)
static void copyRGBtoRGBA (rgba *dst, unsigned char *src, unsigned int size)
static void copyBGRAtoRGB (rgb *dst, unsigned char *src, unsigned int size)
static void copyQRGBtoRGB (rgb *dst, QRgb *src, unsigned int size)
static void copyQRGBtoRGBA (rgba *dst, QRgb *src, unsigned int size)
static void copyRGBtoQRGB (QRgb *dst, rgb *src, unsigned int size)
static void copyRGBAtoQRGB (QRgb *dst, rgba *src, unsigned int size)
static void copyARGBtoRGB (rgb *dst, unsigned char *src, unsigned int size)
static void copyARGBtoRGBA (rgba *dst, unsigned char *src, unsigned int size)
Detailed Description
A class containing helper functions for reading and writing image data to/from files.
This class relies on QT4's image i/o functions
Definition at line 40 of file image_io.h.
Member Function Documentation
void ImageIO::copyARGBtoRGB (rgb * dst, unsigned char * src, unsigned int size) static protected
Definition at line 76 of file image_io.cpp.
References ColorRGB< num, fmt >::b, ColorRGB< num, fmt >::g, velocity.pid_::i, and ColorRGB< num, fmt >::r.
{
   unsigned int i;
   for (i=0;i!=size;i++) {
     src++;
     dst->r=(*src);
     src++;
     dst->g=(*src);
     src++;
     dst->b=(*src);
     if (i != (size-1)) {
       src++;
       dst++;
     }
   }
 }
void ImageIO::copyARGBtoRGBA (rgba * dst, unsigned char * src, unsigned int size) static protected
Definition at line 92 of file image_io.cpp.
References ColorRGBA< num, fmt >::a, ColorRGBA< num, fmt >::b, ColorRGBA< num, fmt >::g, velocity.pid_::i, and ColorRGBA< num, fmt >::r.
{
   unsigned int i;
   for (i=0;i!=size;i++) {
     dst->a=(*src);
     src++;
     dst->r=(*src);
     src++;
     dst->g=(*src);
     src++;
     dst->b=(*src);
     if (i != (size-1)) {
       src++;
       dst++;
     }
   }
 }
void ImageIO::copyBGRAtoRGB (rgb * dst, unsigned char * src, unsigned int size) static protected
Definition at line 157 of file image_io.cpp.
References ColorRGB< num, fmt >::b, ColorRGB< num, fmt >::g, velocity.pid_::i, and ColorRGB< num, fmt >::r.
{
   unsigned int i;
   for (i=0;i!=size;i++) {
     dst->b=(*src);
     src++;
     dst->g=(*src);
     src++;
     dst->r=(*src);
     src++;
     if (i != (size-1)) {
       src++;
       dst++;
     }
   }
 }
void ImageIO::copyBGRAtoRGBA (rgba * dst, unsigned char * src, unsigned int size) static protected
Definition at line 109 of file image_io.cpp.
References ColorRGBA< num, fmt >::a, ColorRGBA< num, fmt >::b, ColorRGBA< num, fmt >::g, velocity.pid_::i, and ColorRGBA< num, fmt >::r.
{
   unsigned int i;
   for (i=0;i!=size;i++) {
     dst->b=(*src);
     src++;
     dst->g=(*src);
     src++;
     dst->r=(*src);
     src++;
     dst->a=(*src);
     if (i != (size-1)) {
       src++;
       dst++;
     }
   }
 }
void ImageIO::copyBGRtoRGB (rgb * dst, unsigned char * src, unsigned int size) static protected
Definition at line 126 of file image_io.cpp.
References ColorRGB< num, fmt >::b, ColorRGB< num, fmt >::g, velocity.pid_::i, and ColorRGB< num, fmt >::r.
{
   unsigned int i;
   for (i=0;i!=size;i++) {
     dst->b=(*src);
     src++;
     dst->g=(*src);
     src++;
     dst->r=(*src);
     if (i != (size-1)) {
       src++;
       dst++;
     }
   }
 }
void ImageIO::copyBGRtoRGBA (rgba * dst, unsigned char * src, unsigned int size) static protected
Definition at line 141 of file image_io.cpp.
References ColorRGBA< num, fmt >::a, ColorRGBA< num, fmt >::b, ColorRGBA< num, fmt >::g, velocity.pid_::i, and ColorRGBA< num, fmt >::r.
{
   unsigned int i;
   for (i=0;i!=size;i++) {
     dst->b=(*src);
     src++;
     dst->g=(*src);
     src++;
     dst->r=(*src);
     dst->a=0xFF;
     if (i != (size-1)) {
       src++;
       dst++;
     }
   }
 }
void ImageIO::copyQRGBtoRGB (rgb * dst, QRgb * src, unsigned int size) static protected
Definition at line 27 of file image_io.cpp.
References ColorRGB< num, fmt >::b, ColorRGB< num, fmt >::g, velocity.pid_::i, and ColorRGB< num, fmt >::r.
Referenced by readRGB().
{
   unsigned int i;
   for (i=0;i!=size;i++) {
     dst->r=qRed(*src);
     dst->g=qGreen(*src);
     dst->b=qBlue(*src);
     if (i != (size-1)) {
       src++;
       dst++;
     }
   }
 }
void ImageIO::copyQRGBtoRGBA (rgba * dst, QRgb * src, unsigned int size) static protected
Definition at line 40 of file image_io.cpp.
References ColorRGBA< num, fmt >::a, ColorRGBA< num, fmt >::b, ColorRGBA< num, fmt >::g, velocity.pid_::i, and ColorRGBA< num, fmt >::r.
Referenced by readRGBA().
{
   unsigned int i;
   for (i=0;i!=size;i++) {
     dst->r=qRed(*src);
     dst->g=qGreen(*src);
     dst->b=qBlue(*src);
     dst->a=qAlpha(*src);
     if (i != (size-1)) {
       src++;
       dst++;
     }
   }
 }
void ImageIO::copyRGBAtoQRGB (QRgb * dst, rgba * src, unsigned int size) static protected
Definition at line 65 of file image_io.cpp.
References ColorRGBA< num, fmt >::a, ColorRGBA< num, fmt >::b, ColorRGBA< num, fmt >::g, velocity.pid_::i, and ColorRGBA< num, fmt >::r.
{
   unsigned int i;
   for (i=0;i!=size;i++) {
     *dst = qRgba(src->r, src->g, src->b, src->a);
     if (i != (size-1)) {
       src++;
       dst++;
     }
   }
 }
void ImageIO::copyRGBtoQRGB (QRgb * dst, rgb * src, unsigned int size) static protected
Definition at line 54 of file image_io.cpp.
References ColorRGB< num, fmt >::b, ColorRGB< num, fmt >::g, velocity.pid_::i, and ColorRGB< num, fmt >::r.
Referenced by writeRGB().
{
   unsigned int i;
   for (i=0;i!=size;i++) {
     *dst = qRgb(src->r, src->g, src->b);
     if (i != (size-1)) {
       src++;
       dst++;
     }
   }
 }
void ImageIO::copyRGBtoRGBA (rgba * dst, unsigned char * src, unsigned int size) static protected
Definition at line 173 of file image_io.cpp.
References ColorRGBA< num, fmt >::a, ColorRGBA< num, fmt >::b, ColorRGBA< num, fmt >::g, velocity.pid_::i, and ColorRGBA< num, fmt >::r.
{
   unsigned int i;
   for (i=0;i!=size;i++) {
     dst->r=(*src);
     src++;
     dst->g=(*src);
     src++;
     dst->b=(*src);
     dst->a=0xFF;
     if (i != (size-1)) {
       src++;
       dst++;
     }
   }
 }
unsigned char * ImageIO::readGrayscale (int & width, int & height, const char * filename) static
Definition at line 189 of file image_io.cpp.
 {
   uchar *imgbuf = NULL;
   width = height = 0;
   // load image
   QImage *img = NULL;
   //Fl_RGB_Image *img = NULL;
   img = new QImage(filename);
   if (img==0) return NULL;
   if (img->isGrayscale()==false) {
     printf("IMAGE IS NOT GREYSCALE!\n");
   }
   /*if(strstr(filename,".jpg")){
     img = new Fl_JPEG_Image(filename);
   }else if(strstr(filename,".png")){
     img = new Fl_PNG_Image(filename);
   }else if(strstr(filename,".ppm")){
     img = new Fl_PNM_Image(filename);
   }else{
     return(NULL);
   }*/
   // make sure its the right format
   int sz = img->width() * img->height();
   if(!img->bits() || img->depth()!=8 || sz==0) goto end;
   // TODO: handle 2,3,4 channel images
   // allocate an image buffer
   imgbuf = new uchar[sz];
   if(!imgbuf) goto end;
   // copy the data
   width  = img->width();
   height = img->height();
   memcpy(imgbuf,img->bits(),width*height*sizeof(uchar));
  end:
   delete(img);
   return(imgbuf);
 }
rgb * ImageIO::readRGB (int & width, int & height, const char * filename) static
Definition at line 234 of file image_io.cpp.
References copyQRGBtoRGB().
Referenced by Image< rgb >::load(), and PluginDVR::slotMovieLoad().
 {
   QString qfilename(filename);
   QImageReader reader(qfilename);
   QImage image;
   if (reader.read(&image)) {
     width  = image.width();
     height = image.height();
     //convert qimage to rgb pointer:
     if (width > 0 && height > 0 && image.bits() != 0) {
       /*if (image.format() == QImage::Format_RGB888) {
         rgb *imgbuf = new rgb[width*height];
         memcpy(imgbuf,image.bits(),width*height*sizeof(rgb));
         return imgbuf;
       } else */
       if (image.format() == QImage::Format_RGB32 || image.format() == QImage::Format_ARGB32) {
         rgb *imgbuf = new rgb[width*height];
         copyQRGBtoRGB(imgbuf,(QRgb *)(image.bits()),width * height);
         return imgbuf;
       } else {
         printf("WRONG FORMAT RETURNED BY QIMAGE!!!!!!\n");
         return 0;
       }
     } else {
       return 0;
     }
   } else {
     return 0;
   }
   /*
   rgb *imgbuf = NULL;
   width = height = 0;
   QImage *img = NULL;
   //Fl_RGB_Image *img = NULL;
   img = new QImage(filename);
   if (img==0) return NULL;
   // make sure its the right format
   int sz = img->width() * img->height();
   if((img->bits()==0) || (img->depth()!=24 && img->depth()!=32) || sz==0) goto end;
   // allocate an image buffer
   imgbuf = new rgb[sz];
   if(!imgbuf) goto end;
   // copy the data
   width  = img->width();
   height = img->height();
   //memcpy(imgbuf,img->bits(),width*height*sizeof(rgb));
   if (img->depth()==24) {
     copyBGRtoRGB(imgbuf,img->bits(),width*height);
   } else if (img->depth()==32) {
     copyBGRAtoRGB(imgbuf,img->bits(),width*height);
   }
  end:
   delete(img);
   return(imgbuf);*/
 }
rgba * ImageIO::readRGBA (int & width, int & height, const char * filename) static
Definition at line 296 of file image_io.cpp.
References copyQRGBtoRGBA().
Referenced by Image< rgb >::load(), and CaptureFromFile::startCapture().
 {
   QString qfilename(filename);
   QImageReader reader(qfilename);
   QImage image;
   if (reader.read(&image)) {
     width  = image.width();
     height = image.height();
     //convert qimage to rgb pointer:
     if (width > 0 && height > 0 && image.bits() != 0) {
       /*if (image.format() == QImage::Format_RGB888) {
         rgba *imgbuf = new rgba[width*height];
         copyRGBtoRGBA(imgbuf,image.bits(),width * height);
         return imgbuf;
       } else */
       if (image.format() == QImage::Format_RGB32 || image.format() == QImage::Format_ARGB32) {
         rgba *imgbuf = new rgba[width*height];
         copyQRGBtoRGBA(imgbuf,(QRgb *)(image.bits()),width * height);
         return imgbuf;
       } else {
         printf("WRONG FORMAT RETURNED BY QIMAGE!!!!!!\n");
         return 0;
       }
     } else {
       return 0;
     }
   } else {
     return 0;
   }
   /*
   rgba *imgbuf = NULL;
   width = height = 0;
   QImage *img = NULL;
   //Fl_RGB_Image *img = NULL;
   img = new QImage(filename);
   if (img==0) return NULL;
   // make sure its the right format
   int sz = img->width() * img->height();
   if((img->bits()==0) || (img->depth()!=24 && img->depth()!=32) || sz==0) goto end;
   // allocate an image buffer
   imgbuf = new rgba[sz];
   if(!imgbuf) goto end;
   // copy the data
   width  = img->width();
   height = img->height();
   //memcpy(imgbuf,img->bits(),width*height*sizeof(rgba));
   if (img->depth()==24) {
     copyBGRtoRGBA(imgbuf,img->bits(),width*height);
   } else if (img->depth()==32) {
     copyBGRAtoRGBA(imgbuf,img->bits(),width*height);
   }
  end:
   delete(img);
   return(imgbuf);*/
 }
bool ImageIO::writePPM (rgb * imgbuf, int width, int height, const char * filename) static
Definition at line 355 of file image_io.cpp.
 {
   // open output file
   FILE *out = fopen(filename,"wb");
   if(!out) return(false);
   // write the image
   fprintf(out,"P6\n%d %d\n%d\n",width,height,255);
   int result=fwrite(imgbuf,3,width*height,out);
   (void)result; //get the compiler to shut up.
   return(fclose(out) == 0);
 }
bool ImageIO::writeRGB (rgb * imgbuf, int width, int height, const char * filename) static
Definition at line 382 of file image_io.cpp.
References COLOR_RGB8, COLOR_RGBA8, copyRGBtoQRGB(), velocity.pid_::i, and TRUE.
Referenced by Image< rgb >::save().
 {
   QImage img(width,height,QImage::Format_RGB32);
   copyRGBtoQRGB((QRgb *)(img.bits()),imgbuf,width*height);
   QImageWriter writer;
   QString qfilename(filename);
   writer.setFileName(qfilename);
   return writer.write(img);
 /*
   const char *ext = strrchr(filename,'.');
   if(strcmp(ext,".ppm") == 0) return(ImageIO::writePPM (imgbuf,width,height,filename));
   if(strcmp(ext,".jpg") == 0) return(ImageIO::writeJPEG(imgbuf,width,height,filename,90));
   if(strcmp(ext,".png") == 0) return(ImageIO::WritePNG(imgbuf,width,height,filename));
   printf("WriteRGB: Unknown extension \"%s\"\n",ext);
   return(false);*/
 }
The documentation for this class was generated from the following files:
ssl-vision/src/shared/util/image_io.h
ssl-vision/src/shared/util/image_io.cpp