Documentation: GlobalV4LinstanceManager Class Reference
GlobalV4LinstanceManager Class Reference
A static instance manager to provide global singleton access to GlobalV4Linstance.
#include <capturev4l.h>
Static Public Member Functions
static GlobalV4Linstance * obtainInstance (int iDevice)
static int enumerateInstances (int *id_list, int max_id=4)
static bool removeInstance (GlobalV4Linstance *pDevice)
static bool removeInstance (int iDevice)
Protected Member Functions
GlobalV4LinstanceManager ()
~GlobalV4LinstanceManager ()
GlobalV4LinstanceManager (const GlobalV4LinstanceManager &)
GlobalV4LinstanceManager & operator= (const GlobalV4LinstanceManager &)
Private Types
typedef std::map< int, GlobalV4Linstance * > t_map_v4l
Private Attributes
t_map_v4l map_instance
Static Private Attributes
static GlobalV4LinstanceManager * pinstance = NULL
Detailed Description
A static instance manager to provide global singleton access to GlobalV4Linstance.
Author
Eric Zavesky, (C) 2016
Definition at line 181 of file capturev4l.h.
Member Typedef Documentation
typedef std::map<int, GlobalV4Linstance*> GlobalV4LinstanceManager::t_map_v4l private
Definition at line 195 of file capturev4l.h.
Constructor & Destructor Documentation
GlobalV4LinstanceManager::GlobalV4LinstanceManager () protected
Definition at line 93 of file capturev4l.cpp.
Referenced by obtainInstance().
{
     //instance=new GlobalV4Linstance();
 }
GlobalV4LinstanceManager::~GlobalV4LinstanceManager () protected
Definition at line 96 of file capturev4l.cpp.
References map_instance, and pinstance.
{
     for (t_map_v4l::iterator it=pinstance->map_instance.begin();
          it!=pinstance->map_instance.end(); it++) {
         delete it->second;
     }
     map_instance.clear();
 }
GlobalV4LinstanceManager::GlobalV4LinstanceManager (const GlobalV4LinstanceManager &) protected
Member Function Documentation
int GlobalV4LinstanceManager::enumerateInstances (int * id_list, int max_id = 4) static
Definition at line 104 of file capturev4l.cpp.
References obtainInstance(), and removeInstance().
Referenced by CaptureV4L::CaptureV4L(), and CaptureV4L::resetBus().
 {
     int iFoundDevices = 0;
     for (int cam_id=0; cam_id < max_id; cam_id++) {
         GlobalV4Linstance *pDevice = GlobalV4LinstanceManager::obtainInstance(cam_id);
         if (pDevice) {
             id_list[iFoundDevices++] = cam_id;
             GlobalV4LinstanceManager::removeInstance(pDevice);
         }
     }
     return iFoundDevices;
 }
GlobalV4Linstance * GlobalV4LinstanceManager::obtainInstance (int iDevice) static
Definition at line 68 of file capturev4l.cpp.
References GlobalV4LinstanceManager(), map_instance, and pinstance.
Referenced by CaptureV4L::CaptureV4L(), enumerateInstances(), GlobalV4Linstance::obtainInstance(), and CaptureV4L::startCapture().
{
     if (!pinstance) pinstance=new GlobalV4LinstanceManager();
     if (pinstance->map_instance.find(iDevice)==pinstance->map_instance.end()) {
         pinstance->map_instance[iDevice] = new GlobalV4Linstance();
     }
     if (!pinstance->map_instance[iDevice]->obtainInstance(iDevice)) return NULL;
     return pinstance->map_instance[iDevice];
 }
GlobalV4LinstanceManager& GlobalV4LinstanceManager::operator= (const GlobalV4LinstanceManager &) protected
bool GlobalV4LinstanceManager::removeInstance (GlobalV4Linstance * pDevice) static
Definition at line 76 of file capturev4l.cpp.
References map_instance, pinstance, and GlobalV4Linstance::removeInstance().
Referenced by enumerateInstances(), GlobalV4Linstance::obtainInstance(), removeInstance(), CaptureV4L::startCapture(), and CaptureV4L::~CaptureV4L().
{
     for (t_map_v4l::iterator it=pinstance->map_instance.begin();
          it!=pinstance->map_instance.end(); it++) {
         if (it->second == pDevice) {
             if (pDevice->removeInstance()) {
                 delete pDevice;
             }
             pinstance->map_instance.erase(it);
             return true;
         }
     }
     return false;       // didn't find it
 }
bool GlobalV4LinstanceManager::removeInstance (int iDevice) static
Definition at line 89 of file capturev4l.cpp.
References map_instance, pinstance, and removeInstance().
{
     if (pinstance->map_instance.find(iDevice)!=pinstance->map_instance.end()) return false;
     return removeInstance(pinstance->map_instance[iDevice]);
 }
Field Documentation
t_map_v4l GlobalV4LinstanceManager::map_instance private
Definition at line 196 of file capturev4l.h.
Referenced by obtainInstance(), removeInstance(), and ~GlobalV4LinstanceManager().
GlobalV4LinstanceManager * GlobalV4LinstanceManager::pinstance = NULL static private
Definition at line 194 of file capturev4l.h.
Referenced by obtainInstance(), removeInstance(), and ~GlobalV4LinstanceManager().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/capture/capturev4l.h
ssl-vision/src/shared/capture/capturev4l.cpp