Documentation: Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Class Reference
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Class Reference
Data Structures
class Builder
Public Member Functions
SSL_GeometryCameraCalibration getDefaultInstanceForType ()
boolean hasCameraId ()
int getCameraId ()
boolean hasFocalLength ()
float getFocalLength ()
boolean hasPrincipalPointX ()
float getPrincipalPointX ()
boolean hasPrincipalPointY ()
float getPrincipalPointY ()
boolean hasDistortion ()
float getDistortion ()
boolean hasQ0 ()
float getQ0 ()
boolean hasQ1 ()
float getQ1 ()
boolean hasQ2 ()
float getQ2 ()
boolean hasQ3 ()
float getQ3 ()
boolean hasTx ()
float getTx ()
boolean hasTy ()
float getTy ()
boolean hasTz ()
float getTz ()
boolean hasDerivedCameraWorldTx ()
float getDerivedCameraWorldTx ()
boolean hasDerivedCameraWorldTy ()
float getDerivedCameraWorldTy ()
boolean hasDerivedCameraWorldTz ()
float getDerivedCameraWorldTz ()
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static SSL_GeometryCameraCalibration getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration parseFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration prototype)
Static Public Attributes
static final int CAMERA_ID_FIELD_NUMBER = 1
static final int FOCAL_LENGTH_FIELD_NUMBER = 2
static final int PRINCIPAL_POINT_X_FIELD_NUMBER = 3
static final int PRINCIPAL_POINT_Y_FIELD_NUMBER = 4
static final int DISTORTION_FIELD_NUMBER = 5
static final int Q0_FIELD_NUMBER = 6
static final int Q1_FIELD_NUMBER = 7
static final int Q2_FIELD_NUMBER = 8
static final int Q3_FIELD_NUMBER = 9
static final int TX_FIELD_NUMBER = 10
static final int TY_FIELD_NUMBER = 11
static final int TZ_FIELD_NUMBER = 12
static final int DERIVED_CAMERA_WORLD_TX_FIELD_NUMBER = 13
static final int DERIVED_CAMERA_WORLD_TY_FIELD_NUMBER = 14
static final int DERIVED_CAMERA_WORLD_TZ_FIELD_NUMBER = 15
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
SSL_GeometryCameraCalibration (Builder builder)
SSL_GeometryCameraCalibration (boolean noInit)
void initFields ()
Private Attributes
int bitField0_
int cameraId_
float focalLength_
float principalPointX_
float principalPointY_
float distortion_
float q0_
float q1_
float q2_
float q3_
float tx_
float ty_
float tz_
float derivedCameraWorldTx_
float derivedCameraWorldTy_
float derivedCameraWorldTz_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final SSL_GeometryCameraCalibration defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 1265 of file MessagesRobocupSslGeometry.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.SSL_GeometryCameraCalibration (Builder builder) inline private
Definition at line 1269 of file MessagesRobocupSslGeometry.java.
{
       super(builder);
     }
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.SSL_GeometryCameraCalibration (boolean noInit) inline private
Definition at line 1272 of file MessagesRobocupSslGeometry.java.
 {}
Member Function Documentation
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getCameraId () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1300 of file MessagesRobocupSslGeometry.java.
{
       return cameraId_;
     }
static SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDefaultInstance () inline static
Definition at line 1275 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.addCalibBuilder(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getDefaultInstanceForType(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.mergeFrom().
{
       return defaultInstance;
     }
SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDefaultInstanceForType () inline
Definition at line 1279 of file MessagesRobocupSslGeometry.java.
{
       return defaultInstance;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDerivedCameraWorldTx () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1420 of file MessagesRobocupSslGeometry.java.
{
       return derivedCameraWorldTx_;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDerivedCameraWorldTy () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1430 of file MessagesRobocupSslGeometry.java.
{
       return derivedCameraWorldTy_;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDerivedCameraWorldTz () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1440 of file MessagesRobocupSslGeometry.java.
{
       return derivedCameraWorldTz_;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDescriptor () inline static
Definition at line 1284 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.internal_static_SSL_GeometryCameraCalibration_descriptor.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getDescriptorForType().
{
       return MessagesRobocupSslGeometry.internal_static_SSL_GeometryCameraCalibration_descriptor;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDistortion () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1340 of file MessagesRobocupSslGeometry.java.
{
       return distortion_;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getFocalLength () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1310 of file MessagesRobocupSslGeometry.java.
{
       return focalLength_;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getPrincipalPointX () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1320 of file MessagesRobocupSslGeometry.java.
{
       return principalPointX_;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getPrincipalPointY () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1330 of file MessagesRobocupSslGeometry.java.
{
       return principalPointY_;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getQ0 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1350 of file MessagesRobocupSslGeometry.java.
{
       return q0_;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getQ1 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1360 of file MessagesRobocupSslGeometry.java.
{
       return q1_;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getQ2 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1370 of file MessagesRobocupSslGeometry.java.
{
       return q2_;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getQ3 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1380 of file MessagesRobocupSslGeometry.java.
{
       return q3_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getSerializedSize () inline
Definition at line 1570 of file MessagesRobocupSslGeometry.java.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeUInt32Size(1, cameraId_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(2, focalLength_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(3, principalPointX_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(4, principalPointY_);
       }
       if (((bitField0_ & 0x00000010) == 0x00000010)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(5, distortion_);
       }
       if (((bitField0_ & 0x00000020) == 0x00000020)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(6, q0_);
       }
       if (((bitField0_ & 0x00000040) == 0x00000040)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(7, q1_);
       }
       if (((bitField0_ & 0x00000080) == 0x00000080)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(8, q2_);
       }
       if (((bitField0_ & 0x00000100) == 0x00000100)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(9, q3_);
       }
       if (((bitField0_ & 0x00000200) == 0x00000200)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(10, tx_);
       }
       if (((bitField0_ & 0x00000400) == 0x00000400)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(11, ty_);
       }
       if (((bitField0_ & 0x00000800) == 0x00000800)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(12, tz_);
       }
       if (((bitField0_ & 0x00001000) == 0x00001000)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(13, derivedCameraWorldTx_);
       }
       if (((bitField0_ & 0x00002000) == 0x00002000)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(14, derivedCameraWorldTy_);
       }
       if (((bitField0_ & 0x00004000) == 0x00004000)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(15, derivedCameraWorldTz_);
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getTx () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1390 of file MessagesRobocupSslGeometry.java.
{
       return tx_;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getTy () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1400 of file MessagesRobocupSslGeometry.java.
{
       return ty_;
     }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getTz () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1410 of file MessagesRobocupSslGeometry.java.
{
       return tz_;
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasCameraId () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1297 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasDerivedCameraWorldTx () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1417 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00001000) == 0x00001000);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasDerivedCameraWorldTy () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1427 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00002000) == 0x00002000);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasDerivedCameraWorldTz () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1437 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00004000) == 0x00004000);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasDistortion () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1337 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000010) == 0x00000010);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasFocalLength () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1307 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000002) == 0x00000002);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasPrincipalPointX () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1317 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000004) == 0x00000004);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasPrincipalPointY () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1327 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000008) == 0x00000008);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasQ0 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1347 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000020) == 0x00000020);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasQ1 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1357 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000040) == 0x00000040);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasQ2 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1367 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000080) == 0x00000080);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasQ3 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1377 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000100) == 0x00000100);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasTx () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1387 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000200) == 0x00000200);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasTy () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1397 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000400) == 0x00000400);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.hasTz () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 1407 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000800) == 0x00000800);
     }
void Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.initFields () inline private
Definition at line 1444 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearDerivedCameraWorldTz().
{
       cameraId_ = 0;
       focalLength_ = 0F;
       principalPointX_ = 0F;
       principalPointY_ = 0F;
       distortion_ = 0F;
       q0_ = 0F;
       q1_ = 0F;
       q2_ = 0F;
       q3_ = 0F;
       tx_ = 0F;
       ty_ = 0F;
       tz_ = 0F;
       derivedCameraWorldTx_ = 0F;
       derivedCameraWorldTy_ = 0F;
       derivedCameraWorldTz_ = 0F;
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.internalGetFieldAccessorTable () inline protected
Definition at line 1289 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.internal_static_SSL_GeometryCameraCalibration_fieldAccessorTable.
{
       return MessagesRobocupSslGeometry.internal_static_SSL_GeometryCameraCalibration_fieldAccessorTable;
     }
final boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.isInitialized () inline
Definition at line 1462 of file MessagesRobocupSslGeometry.java.
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (!hasCameraId()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasFocalLength()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasPrincipalPointX()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasPrincipalPointY()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasDistortion()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasQ0()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasQ1()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasQ2()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasQ3()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasTx()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasTy()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasTz()) {
         memoizedIsInitialized = 0;
         return false;
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.newBuilder () inline static
Definition at line 1714 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.create().
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeFrom().
 { return Builder.create(); }
static Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.newBuilder (MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration prototype) inline static
Definition at line 1716 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.newBuilderForType () inline
Definition at line 1715 of file MessagesRobocupSslGeometry.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 1722 of file MessagesRobocupSslGeometry.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 1681 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1690 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1647 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1652 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1659 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1663 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 1670 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1674 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 1701 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1706 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.toBuilder () inline
Definition at line 1719 of file MessagesRobocupSslGeometry.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 1642 of file MessagesRobocupSslGeometry.java.
{
       return super.writeReplace();
     }
void Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 1518 of file MessagesRobocupSslGeometry.java.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeUInt32(1, cameraId_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         output.writeFloat(2, focalLength_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         output.writeFloat(3, principalPointX_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         output.writeFloat(4, principalPointY_);
       }
       if (((bitField0_ & 0x00000010) == 0x00000010)) {
         output.writeFloat(5, distortion_);
       }
       if (((bitField0_ & 0x00000020) == 0x00000020)) {
         output.writeFloat(6, q0_);
       }
       if (((bitField0_ & 0x00000040) == 0x00000040)) {
         output.writeFloat(7, q1_);
       }
       if (((bitField0_ & 0x00000080) == 0x00000080)) {
         output.writeFloat(8, q2_);
       }
       if (((bitField0_ & 0x00000100) == 0x00000100)) {
         output.writeFloat(9, q3_);
       }
       if (((bitField0_ & 0x00000200) == 0x00000200)) {
         output.writeFloat(10, tx_);
       }
       if (((bitField0_ & 0x00000400) == 0x00000400)) {
         output.writeFloat(11, ty_);
       }
       if (((bitField0_ & 0x00000800) == 0x00000800)) {
         output.writeFloat(12, tz_);
       }
       if (((bitField0_ & 0x00001000) == 0x00001000)) {
         output.writeFloat(13, derivedCameraWorldTx_);
       }
       if (((bitField0_ & 0x00002000) == 0x00002000)) {
         output.writeFloat(14, derivedCameraWorldTy_);
       }
       if (((bitField0_ & 0x00004000) == 0x00004000)) {
         output.writeFloat(15, derivedCameraWorldTz_);
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.bitField0_ private
Definition at line 1293 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.CAMERA_ID_FIELD_NUMBER = 1 static
Definition at line 1295 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.cameraId_ private
Definition at line 1296 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.buildPartial().
final SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.defaultInstance static private
Definition at line 1274 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.DERIVED_CAMERA_WORLD_TX_FIELD_NUMBER = 13 static
Definition at line 1415 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.DERIVED_CAMERA_WORLD_TY_FIELD_NUMBER = 14 static
Definition at line 1425 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.DERIVED_CAMERA_WORLD_TZ_FIELD_NUMBER = 15 static
Definition at line 1435 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.derivedCameraWorldTx_ private
Definition at line 1416 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.derivedCameraWorldTy_ private
Definition at line 1426 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.derivedCameraWorldTz_ private
Definition at line 1436 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.distortion_ private
Definition at line 1336 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.DISTORTION_FIELD_NUMBER = 5 static
Definition at line 1335 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.FOCAL_LENGTH_FIELD_NUMBER = 2 static
Definition at line 1305 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.focalLength_ private
Definition at line 1306 of file MessagesRobocupSslGeometry.java.
byte Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.memoizedIsInitialized = -1 private
Definition at line 1461 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.memoizedSerializedSize = -1 private
Definition at line 1569 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.PRINCIPAL_POINT_X_FIELD_NUMBER = 3 static
Definition at line 1315 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.PRINCIPAL_POINT_Y_FIELD_NUMBER = 4 static
Definition at line 1325 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.principalPointX_ private
Definition at line 1316 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.principalPointY_ private
Definition at line 1326 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.q0_ private
Definition at line 1346 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Q0_FIELD_NUMBER = 6 static
Definition at line 1345 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.q1_ private
Definition at line 1356 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Q1_FIELD_NUMBER = 7 static
Definition at line 1355 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.q2_ private
Definition at line 1366 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Q2_FIELD_NUMBER = 8 static
Definition at line 1365 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.q3_ private
Definition at line 1376 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Q3_FIELD_NUMBER = 9 static
Definition at line 1375 of file MessagesRobocupSslGeometry.java.
final long Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.serialVersionUID = 0L static private
Definition at line 1640 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.tx_ private
Definition at line 1386 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.TX_FIELD_NUMBER = 10 static
Definition at line 1385 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.ty_ private
Definition at line 1396 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.TY_FIELD_NUMBER = 11 static
Definition at line 1395 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.tz_ private
Definition at line 1406 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.TZ_FIELD_NUMBER = 12 static
Definition at line 1405 of file MessagesRobocupSslGeometry.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslGeometry.java