Documentation: BBox::BBox3D< vector, num > Struct Template Reference
BBox::BBox3D< vector, num > Struct Template Reference
#include <bbox.h>
Public Member Functions
bool check (const BBox3D &b) const
bool inside (const vector &p) const
void zero ()
void set (const vector &_cen, const vector &_rad)
void set (const vector &_cen, num _rad)
void set (const vector &p0, const vector &p1, num _rad)
void expand (num amt)
void add (const BBox3D &b)
void add (vector cen, num rad)
void merge (const BBox3D &a, const BBox3D &b)
Data Fields
vector cen
vector rad
Detailed Description
template<class vector, class num>
struct BBox::BBox3D< vector, num >
Definition at line 32 of file bbox.h.
Member Function Documentation
template<class vector , class num > void BBox::BBox3D< vector, num >::add (const BBox3D< vector, num > & b)
Definition at line 88 of file bbox.h.
References BBOX_TEM, BBox::BBox3D< vector, num >::cen, GVector::max(), GVector::min(), and BBox::BBox3D< vector, num >::rad.
Referenced by BBox::BBox3D< vector, num >::set(), and BBox::BBox2D< vector, num >::set().
 {
   vector p0 = min(cen-rad, b.cen-b.rad);
   vector p1 = max(cen+rad, b.cen+b.rad);
   cen = (p1 + p0)*0.5;
   rad = (p1 - p0)*0.5;
 }
template<class vector , class num > void BBox::BBox3D< vector, num >::add (vector cen, num rad)
Definition at line 98 of file bbox.h.
References BBOX_TEM, BBox::BBox3D< vector, num >::cen, GVector::max(), GVector::min(), and BBox::BBox3D< vector, num >::rad.
 {
   vector rv(radius,radius,radius);
   vector p0 = min(cen-rad, center-rv);
   vector p1 = max(cen+rad, center+rv);
   cen = (p1 + p0)*0.5;
   rad = (p1 - p0)*0.5;
 }
template<class vector , class num > bool BBox::BBox3D< vector, num >::check (const BBox3D< vector, num > & b) const
Definition at line 64 of file bbox.h.
References BBOX_TEM, BBox::BBox3D< vector, num >::cen, and BBox::BBox3D< vector, num >::rad.
 {
   return(fabs(b.cen.x - cen.x) > (b.rad.x + rad.x) ||
          fabs(b.cen.y - cen.y) > (b.rad.y + rad.y) ||
          fabs(b.cen.z - cen.z) > (b.rad.z + rad.z));
 }
template<class vector , class num > void BBox::BBox3D< vector, num >::expand (num amt)
Definition at line 80 of file bbox.h.
References BBOX_TEM, and BBox::BBox3D< vector, num >::rad.
Referenced by BBox::BBox3D< vector, num >::set(), and BBox::BBox2D< vector, num >::set().
 {
   rad.x += amt;
   rad.y += amt;
   rad.z += amt;
 }
template<class vector , class num > bool BBox::BBox3D< vector, num >::inside (const vector & p) const
Definition at line 72 of file bbox.h.
References BBOX_TEM, BBox::BBox3D< vector, num >::cen, and BBox::BBox3D< vector, num >::rad.
 {
   return(fabs(p.x - cen.x) < rad.x &&
          fabs(p.y - cen.y) < rad.y &&
          fabs(p.z - cen.z) < rad.z);
 }
template<class vector , class num > void BBox::BBox3D< vector, num >::merge (const BBox3D< vector, num > & a, const BBox3D< vector, num > & b)
Definition at line 109 of file bbox.h.
References BBox::BBox3D< vector, num >::cen, GVector::max(), GVector::min(), and BBox::BBox3D< vector, num >::rad.
Referenced by BBox::BBox3D< vector, num >::set(), and BBox::BBox2D< vector, num >::set().
 {
   vector p0 = min(a.cen-a.rad, b.cen-b.rad);
   vector p1 = max(a.cen+a.rad, b.cen+b.rad);
   cen = (p1 + p0)*0.5;
   rad = (p1 - p0)*0.5;
 }
template<class vector , class num > void BBox::BBox3D< vector, num >::set (const vector & _cen, const vector & _rad) inline
Definition at line 42 of file bbox.h.
     {cen=_cen; rad=_rad;}
template<class vector , class num > void BBox::BBox3D< vector, num >::set (const vector & _cen, num _rad) inline
Definition at line 44 of file bbox.h.
References BBox::BBox3D< vector, num >::add(), BBOX_TEM, BBox::BBox3D< vector, num >::expand(), and BBox::BBox3D< vector, num >::merge().
     {cen=_cen; rad.set(_rad,_rad,_rad);}
template<class vector , class num > void BBox::BBox3D< vector, num >::set (const vector & p0, const vector & p1, num _rad)
Definition at line 55 of file bbox.h.
References BBOX_TEM, BBox::BBox3D< vector, num >::cen, and BBox::BBox3D< vector, num >::rad.
 {
   cen = (p0 + p1)*0.5;
   rad.set(fabs(p1.x - p0.x)*0.5 + _rad,
           fabs(p1.y - p0.y)*0.5 + _rad,
           fabs(p1.z - p0.z)*0.5 + _rad);
 }
template<class vector , class num > void BBox::BBox3D< vector, num >::zero () inline
Definition at line 40 of file bbox.h.
     {cen.zero(); rad.zero();}
Field Documentation
template<class vector , class num > vector BBox::BBox3D< vector, num >::cen
Definition at line 34 of file bbox.h.
Referenced by BBox::BBox3D< vector, num >::add(), BBox::BBox2D< vector, num >::add(), BBox::BBox3D< vector, num >::check(), BBox::BBox2D< vector, num >::check(), BBox::BBox3D< vector, num >::inside(), BBox::BBox2D< vector, num >::inside(), BBox::BBox3D< vector, num >::merge(), BBox::BBox2D< vector, num >::merge(), BBox::BBox3D< vector, num >::set(), and BBox::BBox2D< vector, num >::set().
template<class vector , class num > vector BBox::BBox3D< vector, num >::rad
Definition at line 35 of file bbox.h.
Referenced by BBox::BBox3D< vector, num >::add(), BBox::BBox2D< vector, num >::add(), BBox::BBox3D< vector, num >::check(), BBox::BBox2D< vector, num >::check(), BBox::BBox3D< vector, num >::expand(), BBox::BBox2D< vector, num >::expand(), BBox::BBox3D< vector, num >::inside(), BBox::BBox2D< vector, num >::inside(), BBox::BBox3D< vector, num >::merge(), BBox::BBox2D< vector, num >::merge(), BBox::BBox3D< vector, num >::set(), and BBox::BBox2D< vector, num >::set().
The documentation for this struct was generated from the following file:
ssl-vision/src/shared/util/bbox.h