Documentation: Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder Class Reference
Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
MessagesRobocupSslDetection.SSL_DetectionFrame getDefaultInstanceForType ()
MessagesRobocupSslDetection.SSL_DetectionFrame build ()
MessagesRobocupSslDetection.SSL_DetectionFrame buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (MessagesRobocupSslDetection.SSL_DetectionFrame other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasFrameNumber ()
int getFrameNumber ()
Builder setFrameNumber (int value)
Builder clearFrameNumber ()
boolean hasTCapture ()
double getTCapture ()
Builder setTCapture (double value)
Builder clearTCapture ()
boolean hasTSent ()
double getTSent ()
Builder setTSent (double value)
Builder clearTSent ()
boolean hasCameraId ()
int getCameraId ()
Builder setCameraId (int value)
Builder clearCameraId ()
java.util.List< MessagesRobocupSslDetection.SSL_DetectionBall > getBallsList ()
int getBallsCount ()
MessagesRobocupSslDetection.SSL_DetectionBall getBalls (int index)
Builder setBalls (int index, MessagesRobocupSslDetection.SSL_DetectionBall value)
Builder setBalls (int index, MessagesRobocupSslDetection.SSL_DetectionBall.Builder builderForValue)
Builder addBalls (MessagesRobocupSslDetection.SSL_DetectionBall value)
Builder addBalls (int index, MessagesRobocupSslDetection.SSL_DetectionBall value)
Builder addBalls (MessagesRobocupSslDetection.SSL_DetectionBall.Builder builderForValue)
Builder addBalls (int index, MessagesRobocupSslDetection.SSL_DetectionBall.Builder builderForValue)
Builder addAllBalls (java.lang.Iterable<?extends MessagesRobocupSslDetection.SSL_DetectionBall > values)
Builder clearBalls ()
Builder removeBalls (int index)
MessagesRobocupSslDetection.SSL_DetectionBall.Builder getBallsBuilder (int index)
MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder getBallsOrBuilder (int index)
java.util.List<?extends MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder > getBallsOrBuilderList ()
MessagesRobocupSslDetection.SSL_DetectionBall.Builder addBallsBuilder ()
MessagesRobocupSslDetection.SSL_DetectionBall.Builder addBallsBuilder (int index)
java.util.List< MessagesRobocupSslDetection.SSL_DetectionBall.Builder > getBallsBuilderList ()
java.util.List< MessagesRobocupSslDetection.SSL_DetectionRobot > getRobotsYellowList ()
int getRobotsYellowCount ()
MessagesRobocupSslDetection.SSL_DetectionRobot getRobotsYellow (int index)
Builder setRobotsYellow (int index, MessagesRobocupSslDetection.SSL_DetectionRobot value)
Builder setRobotsYellow (int index, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder builderForValue)
Builder addRobotsYellow (MessagesRobocupSslDetection.SSL_DetectionRobot value)
Builder addRobotsYellow (int index, MessagesRobocupSslDetection.SSL_DetectionRobot value)
Builder addRobotsYellow (MessagesRobocupSslDetection.SSL_DetectionRobot.Builder builderForValue)
Builder addRobotsYellow (int index, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder builderForValue)
Builder addAllRobotsYellow (java.lang.Iterable<?extends MessagesRobocupSslDetection.SSL_DetectionRobot > values)
Builder clearRobotsYellow ()
Builder removeRobotsYellow (int index)
MessagesRobocupSslDetection.SSL_DetectionRobot.Builder getRobotsYellowBuilder (int index)
MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder getRobotsYellowOrBuilder (int index)
java.util.List<?extends MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder > getRobotsYellowOrBuilderList ()
MessagesRobocupSslDetection.SSL_DetectionRobot.Builder addRobotsYellowBuilder ()
MessagesRobocupSslDetection.SSL_DetectionRobot.Builder addRobotsYellowBuilder (int index)
java.util.List< MessagesRobocupSslDetection.SSL_DetectionRobot.Builder > getRobotsYellowBuilderList ()
java.util.List< MessagesRobocupSslDetection.SSL_DetectionRobot > getRobotsBlueList ()
int getRobotsBlueCount ()
MessagesRobocupSslDetection.SSL_DetectionRobot getRobotsBlue (int index)
Builder setRobotsBlue (int index, MessagesRobocupSslDetection.SSL_DetectionRobot value)
Builder setRobotsBlue (int index, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder builderForValue)
Builder addRobotsBlue (MessagesRobocupSslDetection.SSL_DetectionRobot value)
Builder addRobotsBlue (int index, MessagesRobocupSslDetection.SSL_DetectionRobot value)
Builder addRobotsBlue (MessagesRobocupSslDetection.SSL_DetectionRobot.Builder builderForValue)
Builder addRobotsBlue (int index, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder builderForValue)
Builder addAllRobotsBlue (java.lang.Iterable<?extends MessagesRobocupSslDetection.SSL_DetectionRobot > values)
Builder clearRobotsBlue ()
Builder removeRobotsBlue (int index)
MessagesRobocupSslDetection.SSL_DetectionRobot.Builder getRobotsBlueBuilder (int index)
MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder getRobotsBlueOrBuilder (int index)
java.util.List<?extends MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder > getRobotsBlueOrBuilderList ()
MessagesRobocupSslDetection.SSL_DetectionRobot.Builder addRobotsBlueBuilder ()
MessagesRobocupSslDetection.SSL_DetectionRobot.Builder addRobotsBlueBuilder (int index)
java.util.List< MessagesRobocupSslDetection.SSL_DetectionRobot.Builder > getRobotsBlueBuilderList ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
MessagesRobocupSslDetection.SSL_DetectionFrame buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
void ensureBallsIsMutable ()
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionBall, MessagesRobocupSslDetection.SSL_DetectionBall.Builder, MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder > getBallsFieldBuilder ()
void ensureRobotsYellowIsMutable ()
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionRobot, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder, MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder > getRobotsYellowFieldBuilder ()
void ensureRobotsBlueIsMutable ()
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionRobot, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder, MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder > getRobotsBlueFieldBuilder ()
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
int frameNumber_
double tCapture_
double tSent_
int cameraId_
java.util.List< MessagesRobocupSslDetection.SSL_DetectionBall > balls_
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionBall, MessagesRobocupSslDetection.SSL_DetectionBall.Builder, MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder > ballsBuilder_
java.util.List< MessagesRobocupSslDetection.SSL_DetectionRobot > robotsYellow_
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionRobot, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder, MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder > robotsYellowBuilder_
java.util.List< MessagesRobocupSslDetection.SSL_DetectionRobot > robotsBlue_
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionRobot, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder, MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder > robotsBlueBuilder_
Detailed Description
Definition at line 1894 of file MessagesRobocupSslDetection.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.Builder () inline private
Definition at line 1908 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.Builder (BuilderParent parent) inline private
Definition at line 1912 of file MessagesRobocupSslDetection.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addAllBalls (java.lang.Iterable<?extends MessagesRobocupSslDetection.SSL_DetectionBall > values) inline
Definition at line 2443 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ == null) {
           ensureBallsIsMutable();
           super.addAll(values, balls_);
           onChanged();
         } else {
           ballsBuilder_.addAllMessages(values);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addAllRobotsBlue (java.lang.Iterable<?extends MessagesRobocupSslDetection.SSL_DetectionRobot > values) inline
Definition at line 2815 of file MessagesRobocupSslDetection.java.
{
         if (robotsBlueBuilder_ == null) {
           ensureRobotsBlueIsMutable();
           super.addAll(values, robotsBlue_);
           onChanged();
         } else {
           robotsBlueBuilder_.addAllMessages(values);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addAllRobotsYellow (java.lang.Iterable<?extends MessagesRobocupSslDetection.SSL_DetectionRobot > values) inline
Definition at line 2629 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ == null) {
           ensureRobotsYellowIsMutable();
           super.addAll(values, robotsYellow_);
           onChanged();
         } else {
           robotsYellowBuilder_.addAllMessages(values);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addBalls (MessagesRobocupSslDetection.SSL_DetectionBall value) inline
Definition at line 2394 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureBallsIsMutable();
           balls_.add(value);
           onChanged();
         } else {
           ballsBuilder_.addMessage(value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addBalls (int index, MessagesRobocupSslDetection.SSL_DetectionBall value) inline
Definition at line 2407 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureBallsIsMutable();
           balls_.add(index, value);
           onChanged();
         } else {
           ballsBuilder_.addMessage(index, value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addBalls (MessagesRobocupSslDetection.SSL_DetectionBall.Builder builderForValue) inline
Definition at line 2421 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ == null) {
           ensureBallsIsMutable();
           balls_.add(builderForValue.build());
           onChanged();
         } else {
           ballsBuilder_.addMessage(builderForValue.build());
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addBalls (int index, MessagesRobocupSslDetection.SSL_DetectionBall.Builder builderForValue) inline
Definition at line 2432 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ == null) {
           ensureBallsIsMutable();
           balls_.add(index, builderForValue.build());
           onChanged();
         } else {
           ballsBuilder_.addMessage(index, builderForValue.build());
         }
         return this;
       }
MessagesRobocupSslDetection.SSL_DetectionBall.Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addBallsBuilder () inline
Definition at line 2493 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getDefaultInstance().
{
         return getBallsFieldBuilder().addBuilder(
             MessagesRobocupSslDetection.SSL_DetectionBall.getDefaultInstance());
       }
MessagesRobocupSslDetection.SSL_DetectionBall.Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addBallsBuilder (int index) inline
Definition at line 2497 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getDefaultInstance().
                      {
         return getBallsFieldBuilder().addBuilder(
             index, MessagesRobocupSslDetection.SSL_DetectionBall.getDefaultInstance());
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsBlue (MessagesRobocupSslDetection.SSL_DetectionRobot value) inline
Definition at line 2766 of file MessagesRobocupSslDetection.java.
{
         if (robotsBlueBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureRobotsBlueIsMutable();
           robotsBlue_.add(value);
           onChanged();
         } else {
           robotsBlueBuilder_.addMessage(value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsBlue (int index, MessagesRobocupSslDetection.SSL_DetectionRobot value) inline
Definition at line 2779 of file MessagesRobocupSslDetection.java.
{
         if (robotsBlueBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureRobotsBlueIsMutable();
           robotsBlue_.add(index, value);
           onChanged();
         } else {
           robotsBlueBuilder_.addMessage(index, value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsBlue (MessagesRobocupSslDetection.SSL_DetectionRobot.Builder builderForValue) inline
Definition at line 2793 of file MessagesRobocupSslDetection.java.
{
         if (robotsBlueBuilder_ == null) {
           ensureRobotsBlueIsMutable();
           robotsBlue_.add(builderForValue.build());
           onChanged();
         } else {
           robotsBlueBuilder_.addMessage(builderForValue.build());
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsBlue (int index, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder builderForValue) inline
Definition at line 2804 of file MessagesRobocupSslDetection.java.
{
         if (robotsBlueBuilder_ == null) {
           ensureRobotsBlueIsMutable();
           robotsBlue_.add(index, builderForValue.build());
           onChanged();
         } else {
           robotsBlueBuilder_.addMessage(index, builderForValue.build());
         }
         return this;
       }
MessagesRobocupSslDetection.SSL_DetectionRobot.Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsBlueBuilder () inline
Definition at line 2865 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstance().
{
         return getRobotsBlueFieldBuilder().addBuilder(
             MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstance());
       }
MessagesRobocupSslDetection.SSL_DetectionRobot.Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsBlueBuilder (int index) inline
Definition at line 2869 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstance().
                      {
         return getRobotsBlueFieldBuilder().addBuilder(
             index, MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstance());
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsYellow (MessagesRobocupSslDetection.SSL_DetectionRobot value) inline
Definition at line 2580 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureRobotsYellowIsMutable();
           robotsYellow_.add(value);
           onChanged();
         } else {
           robotsYellowBuilder_.addMessage(value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsYellow (int index, MessagesRobocupSslDetection.SSL_DetectionRobot value) inline
Definition at line 2593 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureRobotsYellowIsMutable();
           robotsYellow_.add(index, value);
           onChanged();
         } else {
           robotsYellowBuilder_.addMessage(index, value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsYellow (MessagesRobocupSslDetection.SSL_DetectionRobot.Builder builderForValue) inline
Definition at line 2607 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ == null) {
           ensureRobotsYellowIsMutable();
           robotsYellow_.add(builderForValue.build());
           onChanged();
         } else {
           robotsYellowBuilder_.addMessage(builderForValue.build());
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsYellow (int index, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder builderForValue) inline
Definition at line 2618 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ == null) {
           ensureRobotsYellowIsMutable();
           robotsYellow_.add(index, builderForValue.build());
           onChanged();
         } else {
           robotsYellowBuilder_.addMessage(index, builderForValue.build());
         }
         return this;
       }
MessagesRobocupSslDetection.SSL_DetectionRobot.Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsYellowBuilder () inline
Definition at line 2679 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstance().
{
         return getRobotsYellowFieldBuilder().addBuilder(
             MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstance());
       }
MessagesRobocupSslDetection.SSL_DetectionRobot.Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsYellowBuilder (int index) inline
Definition at line 2683 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstance().
                      {
         return getRobotsYellowFieldBuilder().addBuilder(
             index, MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstance());
       }
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.build () inline
Definition at line 1971 of file MessagesRobocupSslDetection.java.
{
         MessagesRobocupSslDetection.SSL_DetectionFrame result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 1979 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.parseDelimitedFrom().
{
         MessagesRobocupSslDetection.SSL_DetectionFrame result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.buildPartial () inline
Definition at line 1989 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.frameNumber_.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeDetection(), and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrame().
{
         MessagesRobocupSslDetection.SSL_DetectionFrame result = new MessagesRobocupSslDetection.SSL_DetectionFrame(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         result.frameNumber_ = frameNumber_;
         if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
           to_bitField0_ |= 0x00000002;
         }
         result.tCapture_ = tCapture_;
         if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
           to_bitField0_ |= 0x00000004;
         }
         result.tSent_ = tSent_;
         if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
           to_bitField0_ |= 0x00000008;
         }
         result.cameraId_ = cameraId_;
         if (ballsBuilder_ == null) {
           if (((bitField0_ & 0x00000010) == 0x00000010)) {
             balls_ = java.util.Collections.unmodifiableList(balls_);
             bitField0_ = (bitField0_ & ~0x00000010);
           }
           result.balls_ = balls_;
         } else {
           result.balls_ = ballsBuilder_.build();
         }
         if (robotsYellowBuilder_ == null) {
           if (((bitField0_ & 0x00000020) == 0x00000020)) {
             robotsYellow_ = java.util.Collections.unmodifiableList(robotsYellow_);
             bitField0_ = (bitField0_ & ~0x00000020);
           }
           result.robotsYellow_ = robotsYellow_;
         } else {
           result.robotsYellow_ = robotsYellowBuilder_.build();
         }
         if (robotsBlueBuilder_ == null) {
           if (((bitField0_ & 0x00000040) == 0x00000040)) {
             robotsBlue_ = java.util.Collections.unmodifiableList(robotsBlue_);
             bitField0_ = (bitField0_ & ~0x00000040);
           }
           result.robotsBlue_ = robotsBlue_;
         } else {
           result.robotsBlue_ = robotsBlueBuilder_.build();
         }
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.clear () inline
Definition at line 1927 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.clear().
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.clear().
{
         super.clear();
         frameNumber_ = 0;
         bitField0_ = (bitField0_ & ~0x00000001);
         tCapture_ = 0D;
         bitField0_ = (bitField0_ & ~0x00000002);
         tSent_ = 0D;
         bitField0_ = (bitField0_ & ~0x00000004);
         cameraId_ = 0;
         bitField0_ = (bitField0_ & ~0x00000008);
         if (ballsBuilder_ == null) {
           balls_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000010);
         } else {
           ballsBuilder_.clear();
         }
         if (robotsYellowBuilder_ == null) {
           robotsYellow_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000020);
         } else {
           robotsYellowBuilder_.clear();
         }
         if (robotsBlueBuilder_ == null) {
           robotsBlue_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000040);
         } else {
           robotsBlueBuilder_.clear();
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.clearBalls () inline
Definition at line 2454 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ == null) {
           balls_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000010);
           onChanged();
         } else {
           ballsBuilder_.clear();
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.clearCameraId () inline
Definition at line 2328 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000008);
         cameraId_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.clearFrameNumber () inline
Definition at line 2265 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000001);
         frameNumber_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.clearRobotsBlue () inline
Definition at line 2826 of file MessagesRobocupSslDetection.java.
{
         if (robotsBlueBuilder_ == null) {
           robotsBlue_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000040);
           onChanged();
         } else {
           robotsBlueBuilder_.clear();
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.clearRobotsYellow () inline
Definition at line 2640 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ == null) {
           robotsYellow_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000020);
           onChanged();
         } else {
           robotsYellowBuilder_.clear();
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.clearTCapture () inline
Definition at line 2286 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000002);
         tCapture_ = 0D;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.clearTSent () inline
Definition at line 2307 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000004);
         tSent_ = 0D;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.clone () inline
Definition at line 1958 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.create () inline static private
Definition at line 1923 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder().
{
         return new Builder();
       }
void Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.ensureBallsIsMutable () inline private
Definition at line 2338 of file MessagesRobocupSslDetection.java.
{
         if (!((bitField0_ & 0x00000010) == 0x00000010)) {
           balls_ = new java.util.ArrayList<MessagesRobocupSslDetection.SSL_DetectionBall>(balls_);
           bitField0_ |= 0x00000010;
          }
       }
void Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.ensureRobotsBlueIsMutable () inline private
Definition at line 2710 of file MessagesRobocupSslDetection.java.
{
         if (!((bitField0_ & 0x00000040) == 0x00000040)) {
           robotsBlue_ = new java.util.ArrayList<MessagesRobocupSslDetection.SSL_DetectionRobot>(robotsBlue_);
           bitField0_ |= 0x00000040;
          }
       }
void Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.ensureRobotsYellowIsMutable () inline private
Definition at line 2524 of file MessagesRobocupSslDetection.java.
{
         if (!((bitField0_ & 0x00000020) == 0x00000020)) {
           robotsYellow_ = new java.util.ArrayList<MessagesRobocupSslDetection.SSL_DetectionRobot>(robotsYellow_);
           bitField0_ |= 0x00000020;
          }
       }
MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getBalls (int index) inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2362 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ == null) {
           return balls_.get(index);
         } else {
           return ballsBuilder_.getMessage(index);
         }
       }
MessagesRobocupSslDetection.SSL_DetectionBall.Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getBallsBuilder (int index) inline
Definition at line 2474 of file MessagesRobocupSslDetection.java.
                      {
         return getBallsFieldBuilder().getBuilder(index);
       }
java.util.List<MessagesRobocupSslDetection.SSL_DetectionBall.Builder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getBallsBuilderList () inline
Definition at line 2503 of file MessagesRobocupSslDetection.java.
{
         return getBallsFieldBuilder().getBuilderList();
       }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getBallsCount () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2355 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ == null) {
           return balls_.size();
         } else {
           return ballsBuilder_.getCount();
         }
       }
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionBall, MessagesRobocupSslDetection.SSL_DetectionBall.Builder, MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getBallsFieldBuilder () inline private
Definition at line 2508 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ == null) {
           ballsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
               MessagesRobocupSslDetection.SSL_DetectionBall, MessagesRobocupSslDetection.SSL_DetectionBall.Builder, MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder>(
                   balls_,
                   ((bitField0_ & 0x00000010) == 0x00000010),
                   getParentForChildren(),
                   isClean());
           balls_ = null;
         }
         return ballsBuilder_;
       }
java.util.List<MessagesRobocupSslDetection.SSL_DetectionBall> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getBallsList () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2348 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ == null) {
           return java.util.Collections.unmodifiableList(balls_);
         } else {
           return ballsBuilder_.getMessageList();
         }
       }
MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getBallsOrBuilder (int index) inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2478 of file MessagesRobocupSslDetection.java.
                      {
         if (ballsBuilder_ == null) {
           return balls_.get(index);  } else {
           return ballsBuilder_.getMessageOrBuilder(index);
         }
       }
java.util.List<? extends MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getBallsOrBuilderList () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2486 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ != null) {
           return ballsBuilder_.getMessageOrBuilderList();
         } else {
           return java.util.Collections.unmodifiableList(balls_);
         }
       }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getCameraId () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2319 of file MessagesRobocupSslDetection.java.
{
         return cameraId_;
       }
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getDefaultInstanceForType () inline
Definition at line 1967 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance().
{
         return MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getDescriptor () inline static
Definition at line 1898 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.internal_static_SSL_DetectionFrame_descriptor.
{
         return MessagesRobocupSslDetection.internal_static_SSL_DetectionFrame_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getDescriptorForType () inline
Definition at line 1963 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDescriptor().
{
         return MessagesRobocupSslDetection.SSL_DetectionFrame.getDescriptor();
       }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getFrameNumber () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2256 of file MessagesRobocupSslDetection.java.
{
         return frameNumber_;
       }
MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsBlue (int index) inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2734 of file MessagesRobocupSslDetection.java.
{
         if (robotsBlueBuilder_ == null) {
           return robotsBlue_.get(index);
         } else {
           return robotsBlueBuilder_.getMessage(index);
         }
       }
MessagesRobocupSslDetection.SSL_DetectionRobot.Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsBlueBuilder (int index) inline
Definition at line 2846 of file MessagesRobocupSslDetection.java.
                      {
         return getRobotsBlueFieldBuilder().getBuilder(index);
       }
java.util.List<MessagesRobocupSslDetection.SSL_DetectionRobot.Builder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsBlueBuilderList () inline
Definition at line 2875 of file MessagesRobocupSslDetection.java.
{
         return getRobotsBlueFieldBuilder().getBuilderList();
       }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsBlueCount () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2727 of file MessagesRobocupSslDetection.java.
{
         if (robotsBlueBuilder_ == null) {
           return robotsBlue_.size();
         } else {
           return robotsBlueBuilder_.getCount();
         }
       }
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionRobot, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder, MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsBlueFieldBuilder () inline private
Definition at line 2880 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.initFields().
{
         if (robotsBlueBuilder_ == null) {
           robotsBlueBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
               MessagesRobocupSslDetection.SSL_DetectionRobot, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder, MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder>(
                   robotsBlue_,
                   ((bitField0_ & 0x00000040) == 0x00000040),
                   getParentForChildren(),
                   isClean());
           robotsBlue_ = null;
         }
         return robotsBlueBuilder_;
       }
java.util.List<MessagesRobocupSslDetection.SSL_DetectionRobot> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsBlueList () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2720 of file MessagesRobocupSslDetection.java.
{
         if (robotsBlueBuilder_ == null) {
           return java.util.Collections.unmodifiableList(robotsBlue_);
         } else {
           return robotsBlueBuilder_.getMessageList();
         }
       }
MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsBlueOrBuilder (int index) inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2850 of file MessagesRobocupSslDetection.java.
                      {
         if (robotsBlueBuilder_ == null) {
           return robotsBlue_.get(index);  } else {
           return robotsBlueBuilder_.getMessageOrBuilder(index);
         }
       }
java.util.List<? extends MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsBlueOrBuilderList () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2858 of file MessagesRobocupSslDetection.java.
{
         if (robotsBlueBuilder_ != null) {
           return robotsBlueBuilder_.getMessageOrBuilderList();
         } else {
           return java.util.Collections.unmodifiableList(robotsBlue_);
         }
       }
MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsYellow (int index) inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2548 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ == null) {
           return robotsYellow_.get(index);
         } else {
           return robotsYellowBuilder_.getMessage(index);
         }
       }
MessagesRobocupSslDetection.SSL_DetectionRobot.Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsYellowBuilder (int index) inline
Definition at line 2660 of file MessagesRobocupSslDetection.java.
                      {
         return getRobotsYellowFieldBuilder().getBuilder(index);
       }
java.util.List<MessagesRobocupSslDetection.SSL_DetectionRobot.Builder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsYellowBuilderList () inline
Definition at line 2689 of file MessagesRobocupSslDetection.java.
{
         return getRobotsYellowFieldBuilder().getBuilderList();
       }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsYellowCount () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2541 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ == null) {
           return robotsYellow_.size();
         } else {
           return robotsYellowBuilder_.getCount();
         }
       }
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionRobot, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder, MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsYellowFieldBuilder () inline private
Definition at line 2694 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ == null) {
           robotsYellowBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
               MessagesRobocupSslDetection.SSL_DetectionRobot, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder, MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder>(
                   robotsYellow_,
                   ((bitField0_ & 0x00000020) == 0x00000020),
                   getParentForChildren(),
                   isClean());
           robotsYellow_ = null;
         }
         return robotsYellowBuilder_;
       }
java.util.List<MessagesRobocupSslDetection.SSL_DetectionRobot> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsYellowList () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2534 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ == null) {
           return java.util.Collections.unmodifiableList(robotsYellow_);
         } else {
           return robotsYellowBuilder_.getMessageList();
         }
       }
MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsYellowOrBuilder (int index) inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2664 of file MessagesRobocupSslDetection.java.
                      {
         if (robotsYellowBuilder_ == null) {
           return robotsYellow_.get(index);  } else {
           return robotsYellowBuilder_.getMessageOrBuilder(index);
         }
       }
java.util.List<? extends MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsYellowOrBuilderList () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2672 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ != null) {
           return robotsYellowBuilder_.getMessageOrBuilderList();
         } else {
           return java.util.Collections.unmodifiableList(robotsYellow_);
         }
       }
double Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getTCapture () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2277 of file MessagesRobocupSslDetection.java.
{
         return tCapture_;
       }
double Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getTSent () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2298 of file MessagesRobocupSslDetection.java.
{
         return tSent_;
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.hasCameraId () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2316 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000008) == 0x00000008);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.hasFrameNumber () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2253 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.hasTCapture () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2274 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000002) == 0x00000002);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.hasTSent () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 2295 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000004) == 0x00000004);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 1903 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.internal_static_SSL_DetectionFrame_fieldAccessorTable.
{
         return MessagesRobocupSslDetection.internal_static_SSL_DetectionFrame_fieldAccessorTable;
       }
final boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.isInitialized () inline
Definition at line 2146 of file MessagesRobocupSslDetection.java.
References velocity.pid_.i.
{
         if (!hasFrameNumber()) {
           return false;
         }
         if (!hasTCapture()) {
           return false;
         }
         if (!hasTSent()) {
           return false;
         }
         if (!hasCameraId()) {
           return false;
         }
         for (int i = 0; i < getBallsCount(); i++) {
           if (!getBalls(i).isInitialized()) {
             return false;
           }
         }
         for (int i = 0; i < getRobotsYellowCount(); i++) {
           if (!getRobotsYellow(i).isInitialized()) {
             return false;
           }
         }
         for (int i = 0; i < getRobotsBlueCount(); i++) {
           if (!getRobotsBlue(i).isInitialized()) {
             return false;
           }
         }
         return true;
       }
void Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.maybeForceBuilderInitialization () inline private
Definition at line 1916 of file MessagesRobocupSslDetection.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
           getBallsFieldBuilder();
           getRobotsYellowFieldBuilder();
           getRobotsBlueFieldBuilder();
         }
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 2041 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.clone(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeDetection(), Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrame(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom(), Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrom(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder().
{
         if (other instanceof MessagesRobocupSslDetection.SSL_DetectionFrame) {
           return mergeFrom((MessagesRobocupSslDetection.SSL_DetectionFrame)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom (MessagesRobocupSslDetection.SSL_DetectionFrame other) inline
Definition at line 2050 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.balls_, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance().
{
         if (other == MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance()) return this;
         if (other.hasFrameNumber()) {
           setFrameNumber(other.getFrameNumber());
         }
         if (other.hasTCapture()) {
           setTCapture(other.getTCapture());
         }
         if (other.hasTSent()) {
           setTSent(other.getTSent());
         }
         if (other.hasCameraId()) {
           setCameraId(other.getCameraId());
         }
         if (ballsBuilder_ == null) {
           if (!other.balls_.isEmpty()) {
             if (balls_.isEmpty()) {
               balls_ = other.balls_;
               bitField0_ = (bitField0_ & ~0x00000010);
             } else {
               ensureBallsIsMutable();
               balls_.addAll(other.balls_);
             }
             onChanged();
           }
         } else {
           if (!other.balls_.isEmpty()) {
             if (ballsBuilder_.isEmpty()) {
               ballsBuilder_.dispose();
               ballsBuilder_ = null;
               balls_ = other.balls_;
               bitField0_ = (bitField0_ & ~0x00000010);
               ballsBuilder_ =
                 com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                    getBallsFieldBuilder() : null;
             } else {
               ballsBuilder_.addAllMessages(other.balls_);
             }
           }
         }
         if (robotsYellowBuilder_ == null) {
           if (!other.robotsYellow_.isEmpty()) {
             if (robotsYellow_.isEmpty()) {
               robotsYellow_ = other.robotsYellow_;
               bitField0_ = (bitField0_ & ~0x00000020);
             } else {
               ensureRobotsYellowIsMutable();
               robotsYellow_.addAll(other.robotsYellow_);
             }
             onChanged();
           }
         } else {
           if (!other.robotsYellow_.isEmpty()) {
             if (robotsYellowBuilder_.isEmpty()) {
               robotsYellowBuilder_.dispose();
               robotsYellowBuilder_ = null;
               robotsYellow_ = other.robotsYellow_;
               bitField0_ = (bitField0_ & ~0x00000020);
               robotsYellowBuilder_ =
                 com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                    getRobotsYellowFieldBuilder() : null;
             } else {
               robotsYellowBuilder_.addAllMessages(other.robotsYellow_);
             }
           }
         }
         if (robotsBlueBuilder_ == null) {
           if (!other.robotsBlue_.isEmpty()) {
             if (robotsBlue_.isEmpty()) {
               robotsBlue_ = other.robotsBlue_;
               bitField0_ = (bitField0_ & ~0x00000040);
             } else {
               ensureRobotsBlueIsMutable();
               robotsBlue_.addAll(other.robotsBlue_);
             }
             onChanged();
           }
         } else {
           if (!other.robotsBlue_.isEmpty()) {
             if (robotsBlueBuilder_.isEmpty()) {
               robotsBlueBuilder_.dispose();
               robotsBlueBuilder_ = null;
               robotsBlue_ = other.robotsBlue_;
               bitField0_ = (bitField0_ & ~0x00000040);
               robotsBlueBuilder_ =
                 com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                    getRobotsBlueFieldBuilder() : null;
             } else {
               robotsBlueBuilder_.addAllMessages(other.robotsBlue_);
             }
           }
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 2184 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.Builder(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.newBuilder(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.newBuilder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 8: {
               bitField0_ |= 0x00000001;
               frameNumber_ = input.readUInt32();
               break;
             }
             case 17: {
               bitField0_ |= 0x00000002;
               tCapture_ = input.readDouble();
               break;
             }
             case 25: {
               bitField0_ |= 0x00000004;
               tSent_ = input.readDouble();
               break;
             }
             case 32: {
               bitField0_ |= 0x00000008;
               cameraId_ = input.readUInt32();
               break;
             }
             case 42: {
               MessagesRobocupSslDetection.SSL_DetectionBall.Builder subBuilder = MessagesRobocupSslDetection.SSL_DetectionBall.newBuilder();
               input.readMessage(subBuilder, extensionRegistry);
               addBalls(subBuilder.buildPartial());
               break;
             }
             case 50: {
               MessagesRobocupSslDetection.SSL_DetectionRobot.Builder subBuilder = MessagesRobocupSslDetection.SSL_DetectionRobot.newBuilder();
               input.readMessage(subBuilder, extensionRegistry);
               addRobotsYellow(subBuilder.buildPartial());
               break;
             }
             case 58: {
               MessagesRobocupSslDetection.SSL_DetectionRobot.Builder subBuilder = MessagesRobocupSslDetection.SSL_DetectionRobot.newBuilder();
               input.readMessage(subBuilder, extensionRegistry);
               addRobotsBlue(subBuilder.buildPartial());
               break;
             }
           }
         }
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.removeBalls (int index) inline
Definition at line 2464 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ == null) {
           ensureBallsIsMutable();
           balls_.remove(index);
           onChanged();
         } else {
           ballsBuilder_.remove(index);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.removeRobotsBlue (int index) inline
Definition at line 2836 of file MessagesRobocupSslDetection.java.
{
         if (robotsBlueBuilder_ == null) {
           ensureRobotsBlueIsMutable();
           robotsBlue_.remove(index);
           onChanged();
         } else {
           robotsBlueBuilder_.remove(index);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.removeRobotsYellow (int index) inline
Definition at line 2650 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ == null) {
           ensureRobotsYellowIsMutable();
           robotsYellow_.remove(index);
           onChanged();
         } else {
           robotsYellowBuilder_.remove(index);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.setBalls (int index, MessagesRobocupSslDetection.SSL_DetectionBall value) inline
Definition at line 2369 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureBallsIsMutable();
           balls_.set(index, value);
           onChanged();
         } else {
           ballsBuilder_.setMessage(index, value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.setBalls (int index, MessagesRobocupSslDetection.SSL_DetectionBall.Builder builderForValue) inline
Definition at line 2383 of file MessagesRobocupSslDetection.java.
{
         if (ballsBuilder_ == null) {
           ensureBallsIsMutable();
           balls_.set(index, builderForValue.build());
           onChanged();
         } else {
           ballsBuilder_.setMessage(index, builderForValue.build());
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.setCameraId (int value) inline
Definition at line 2322 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000008;
         cameraId_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.setFrameNumber (int value) inline
Definition at line 2259 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000001;
         frameNumber_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.setRobotsBlue (int index, MessagesRobocupSslDetection.SSL_DetectionRobot value) inline
Definition at line 2741 of file MessagesRobocupSslDetection.java.
{
         if (robotsBlueBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureRobotsBlueIsMutable();
           robotsBlue_.set(index, value);
           onChanged();
         } else {
           robotsBlueBuilder_.setMessage(index, value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.setRobotsBlue (int index, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder builderForValue) inline
Definition at line 2755 of file MessagesRobocupSslDetection.java.
{
         if (robotsBlueBuilder_ == null) {
           ensureRobotsBlueIsMutable();
           robotsBlue_.set(index, builderForValue.build());
           onChanged();
         } else {
           robotsBlueBuilder_.setMessage(index, builderForValue.build());
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.setRobotsYellow (int index, MessagesRobocupSslDetection.SSL_DetectionRobot value) inline
Definition at line 2555 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureRobotsYellowIsMutable();
           robotsYellow_.set(index, value);
           onChanged();
         } else {
           robotsYellowBuilder_.setMessage(index, value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.setRobotsYellow (int index, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder builderForValue) inline
Definition at line 2569 of file MessagesRobocupSslDetection.java.
{
         if (robotsYellowBuilder_ == null) {
           ensureRobotsYellowIsMutable();
           robotsYellow_.set(index, builderForValue.build());
           onChanged();
         } else {
           robotsYellowBuilder_.setMessage(index, builderForValue.build());
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.setTCapture (double value) inline
Definition at line 2280 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000002;
         tCapture_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.setTSent (double value) inline
Definition at line 2301 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000004;
         tSent_ = value;
         onChanged();
         return this;
       }
Field Documentation
java.util.List<MessagesRobocupSslDetection.SSL_DetectionBall> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.balls_ private
Initial value:
=
        java.util.Collections.emptyList()
Definition at line 2336 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom().
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionBall, MessagesRobocupSslDetection.SSL_DetectionBall.Builder, MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.ballsBuilder_ private
Definition at line 2346 of file MessagesRobocupSslDetection.java.
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.bitField0_ private
Definition at line 2249 of file MessagesRobocupSslDetection.java.
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.cameraId_ private
Definition at line 2315 of file MessagesRobocupSslDetection.java.
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.frameNumber_ private
Definition at line 2252 of file MessagesRobocupSslDetection.java.
java.util.List<MessagesRobocupSslDetection.SSL_DetectionRobot> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.robotsBlue_ private
Initial value:
=
        java.util.Collections.emptyList()
Definition at line 2708 of file MessagesRobocupSslDetection.java.
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionRobot, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder, MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.robotsBlueBuilder_ private
Definition at line 2718 of file MessagesRobocupSslDetection.java.
java.util.List<MessagesRobocupSslDetection.SSL_DetectionRobot> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.robotsYellow_ private
Initial value:
=
        java.util.Collections.emptyList()
Definition at line 2522 of file MessagesRobocupSslDetection.java.
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionRobot, MessagesRobocupSslDetection.SSL_DetectionRobot.Builder, MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.robotsYellowBuilder_ private
Definition at line 2532 of file MessagesRobocupSslDetection.java.
double Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.tCapture_ private
Definition at line 2273 of file MessagesRobocupSslDetection.java.
double Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.tSent_ private
Definition at line 2294 of file MessagesRobocupSslDetection.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslDetection.java