Documentation: VarTypes::XMLParserBase64Tool Class Reference
VarTypes::XMLParserBase64Tool Class Reference
#include <xmlParser.h>
Static Public Member Functions
static int encodeLength (int inBufLen, char formatted=0)
static void encode (unsigned char *inData, unsigned int inDataLen, std::string &outString, char formatted=0)
static void encode (const std::string &inString, std::string &outString, char formatted=0)
static unsigned int decodeSize (const char *inString, XMLError *xe=NULL)
static bool decode (const std::string &inString, std::string &outString, XMLError *xe=NULL)
static bool decode (const std::string &inString, unsigned char *outByteBuf, int inMaxByteOutBuflen, XMLError *xe=NULL)
Detailed Description
Definition at line 530 of file xmlParser.h.
Member Function Documentation
bool VarTypes::XMLParserBase64Tool::decode (const std::string & inString, std::string & outString, XMLError * xe = NULL) static
Definition at line 2599 of file xmlParser.cpp.
References VarTypes::eXMLErrorNone.
Referenced by VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::setSerialString(), and VarTypes::VarBlob::setSerialString().
   {
     if (xe) *xe=eXMLErrorNone;
     unsigned int len=decodeSize(inString.c_str(),xe);
     if (!len) return false;
     outString.resize(len+1,0);
     return decode(inString,(unsigned char *)outString.data(),len,xe);
   }
bool VarTypes::XMLParserBase64Tool::decode (const std::string & inString, unsigned char * outByteBuf, int inMaxByteOutBuflen, XMLError * xe = NULL) static
Definition at line 2538 of file xmlParser.cpp.
References BASE64DECODE_READ_NEXT_CHAR, VarTypes::XMLNode::d, VarTypes::eXMLErrorBase64DecodeBufferTooSmall, VarTypes::eXMLErrorBase64DecodeTruncatedData, VarTypes::eXMLErrorNone, velocity.pid_::i, and XMLCSTR.
   {
       XMLCSTR data=inString.c_str();
       if (xe) *xe=eXMLErrorNone;
       int i=0,p=0;
       unsigned char d,c;
       for(;;)
       {
   #ifdef _XMLUNICODE
   #define BASE64DECODE_READ_NEXT_CHAR(c)                                              \
           do {                                                                        \
               if (data[i]>255){ c=98; break; }                                        \
               c=base64DecodeTable[(unsigned char)data[i++]];                       \
           }while (c==97);                                                             \
           if(c==98){ if(xe)*xe=eXMLErrorBase64DecodeIllegalCharacter; return false; }
   #else
   #define BASE64DECODE_READ_NEXT_CHAR(c)                                           \
           do { c=base64DecodeTable[(unsigned char)data[i++]]; }while (c==97);   \
           if(c==98){ if(xe)*xe=eXMLErrorBase64DecodeIllegalCharacter; return false; }
   #endif
           BASE64DECODE_READ_NEXT_CHAR(c)
           if (c==99) { return true; }
           if (c==96)
           {
               if (p==(int)len) return true;
               if (xe) *xe=eXMLErrorBase64DecodeTruncatedData;
               return true;
           }
           BASE64DECODE_READ_NEXT_CHAR(d)
           if ((d==99)||(d==96)) { if (xe) *xe=eXMLErrorBase64DecodeTruncatedData;  return true; }
           if (p==(int)len) {      if (xe) *xe=eXMLErrorBase64DecodeBufferTooSmall; return false; }
           buf[p++]=(c<<2)|((d>>4)&0x3);
           BASE64DECODE_READ_NEXT_CHAR(c)
           if (c==99) { if (xe) *xe=eXMLErrorBase64DecodeTruncatedData;  return true; }
           if (p==(int)len)
           {
               if (c==96) return true;
               if (xe) *xe=eXMLErrorBase64DecodeBufferTooSmall;
               return false;
           }
           if (c==96) { if (xe) *xe=eXMLErrorBase64DecodeTruncatedData;  return true; }
           buf[p++]=((d<<4)&0xf0)|((c>>2)&0xf);
           BASE64DECODE_READ_NEXT_CHAR(d)
           if (d==99 ) { if (xe) *xe=eXMLErrorBase64DecodeTruncatedData;  return true; }
           if (p==(int)len)
           {
               if (d==96) return true;
               if (xe) *xe=eXMLErrorBase64DecodeBufferTooSmall;
               return false;
           }
           if (d==96) { if (xe) *xe=eXMLErrorBase64DecodeTruncatedData;  return true; }
           buf[p++]=((c<<6)&0xc0)|d;
       }
   }
unsigned int VarTypes::XMLParserBase64Tool::decodeSize (const char * inString, XMLError * xe = NULL) static
Definition at line 2516 of file xmlParser.cpp.
References VarTypes::eXMLErrorBase64DataSizeIsNotMultipleOf4, VarTypes::eXMLErrorBase64DecodeIllegalCharacter, and VarTypes::eXMLErrorNone.
   {
       if (xe) *xe=eXMLErrorNone;
       int size=0;
       unsigned char c;
       //skip any extra characters (e.g. newlines or spaces)
       while (*data)
       {
   #ifdef _XMLUNICODE
           if (*data>255) { if (xe) *xe=eXMLErrorBase64DecodeIllegalCharacter; return 0; }
   #endif
           c=base64DecodeTable[(unsigned char)(*data)];
           if (c<97) size++;
           else if (c==98) { if (xe) *xe=eXMLErrorBase64DecodeIllegalCharacter; return 0; }
           data++;
       }
       if (xe&&(size%4!=0)) *xe=eXMLErrorBase64DataSizeIsNotMultipleOf4;
       if (size==0) return 0;
       do { data--; size--; } while(*data==base64Fillchar); size++;
       return (unsigned int)((size*3)/4);
   }
void VarTypes::XMLParserBase64Tool::encode (unsigned char * inData, unsigned int inDataLen, std::string & outString, char formatted = 0) static
Definition at line 2481 of file xmlParser.cpp.
References _T, velocity.pid_::i, k, and XMLSTR.
Referenced by VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::getSerialString(), and VarTypes::VarBlob::getSerialString().
{
       int i=encodeLength(inlen,formatted),k=17,eLen=inlen/3,j;
       outString.resize(i,0);
       XMLSTR curr=(XMLSTR)outString.data();
 //       alloc(i*sizeof(XMLCHAR));
 //       XMLSTR curr=(XMLSTR)buf;
       for(i=0;i<eLen;i++)
       {
           // Copy next three bytes into lower 24 bits of int, paying attention to sign.
           j=(inbuf[0]<<16)|(inbuf[1]<<8)|inbuf[2]; inbuf+=3;
           // Encode the int into four chars
           *(curr++)=base64EncodeTable[ j>>18      ];
           *(curr++)=base64EncodeTable[(j>>12)&0x3f];
           *(curr++)=base64EncodeTable[(j>> 6)&0x3f];
           *(curr++)=base64EncodeTable[(j    )&0x3f];
           if (formatted) { if (!k) { *(curr++)=_T('\n'); k=18; } k--; }
       }
       eLen=inlen-eLen*3; // 0 - 2.
       if (eLen==1)
       {
           *(curr++)=base64EncodeTable[ inbuf[0]>>2      ];
           *(curr++)=base64EncodeTable[(inbuf[0]<<4)&0x3F];
           *(curr++)=base64Fillchar;
           *(curr++)=base64Fillchar;
       } else if (eLen==2)
       {
           j=(inbuf[0]<<8)|inbuf[1];
           *(curr++)=base64EncodeTable[ j>>10      ];
           *(curr++)=base64EncodeTable[(j>> 4)&0x3f];
           *(curr++)=base64EncodeTable[(j<< 2)&0x3f];
           *(curr++)=base64Fillchar;
       }
       *(curr++)=0;
   }
void VarTypes::XMLParserBase64Tool::encode (const std::string & inString, std::string & outString, char formatted = 0) static
Definition at line 2474 of file xmlParser.cpp.
   {
       unsigned char *inbuf = (unsigned char*)inString.data();
       unsigned int inlen   = inString.length();
       encode(inbuf,inlen,outString,formatted);
   }
int VarTypes::XMLParserBase64Tool::encodeLength (int inBufLen, char formatted = 0) static
Definition at line 2467 of file xmlParser.cpp.
References velocity.pid_::i.
   {
       unsigned int i=((inlen-1)/3*4+4+1);
       if (formatted) i+=inlen/54;
       return i;
   }
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/xml/xmlParser.h
ssl-vision/src/shared/vartypes/xml/xmlParser.cpp