Documentation: PluginSSLNetworkOutput Class Reference
PluginSSLNetworkOutput Class Reference
#include <plugin_sslnetworkoutput.h>
Public Member Functions
PluginSSLNetworkOutput (FrameBuffer *_fb, RoboCupSSLServer *udp_server, const CameraParameters &camera_params, const RoboCupField &field)
~PluginSSLNetworkOutput ()
virtual ProcessResult process (FrameData *data, RenderOptions *options)
virtual string getName ()
Public Member Functions inherited from VisionPlugin
VisionPlugin (FrameBuffer *_buffer)
virtual ~VisionPlugin ()
FrameBuffer * getFrameBuffer () const
this functions provides convenient access to the ring-buffer
void lock ()
void unlock ()
virtual bool isEnabled () const
virtual void setEnabled (bool enable)
virtual bool isVisualize () const
virtual void setVisualize (bool enable)
virtual bool isSharedAmongStacks () const
virtual void setSharedAmongStacks (bool enable)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual VarList * getSettings ()
virtual void postProcess (FrameData *data, RenderOptions *options)
virtual QWidget * getVisualizationWidget ()
virtual QWidget * getControlWidget ()
virtual void closeWidgets ()
virtual QList< QAction * > actions ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
void setTimeProcessing (double val)
void setTimePostProcessing (double val)
double getTimeProcessing ()
double getTimePostProcessing ()
Protected Attributes
const CameraParameters & _camera_params
const RoboCupField & _field
RoboCupSSLServer * _udp_server
Protected Attributes inherited from VisionPlugin
QMutex mutex
bool enabled
bool visualize
bool shared
FrameBuffer * buffer
double time_proc
double time_post
Additional Inherited Members
Public Slots inherited from VisionPlugin
void slotKeyPressEvent (QKeyEvent *event)
Detailed Description
Author
Stefan Zickler
Definition at line 33 of file plugin_sslnetworkoutput.h.
Constructor & Destructor Documentation
PluginSSLNetworkOutput::PluginSSLNetworkOutput (FrameBuffer * _fb, RoboCupSSLServer * udp_server, const CameraParameters & camera_params, const RoboCupField & field)
Definition at line 23 of file plugin_sslnetworkoutput.cpp.
References _udp_server.
  : VisionPlugin(_fb), _camera_params(camera_params), _field(field)
 {
   _udp_server=udp_server;
 }
PluginSSLNetworkOutput::~PluginSSLNetworkOutput ()
Definition at line 29 of file plugin_sslnetworkoutput.cpp.
 {
 }
Member Function Documentation
string PluginSSLNetworkOutput::getName () virtual
Reimplemented from VisionPlugin.
Definition at line 53 of file plugin_sslnetworkoutput.cpp.
{
   return "Network Output";
 }
ProcessResult PluginSSLNetworkOutput::process (FrameData * data, RenderOptions * options) virtual
Reimplemented from VisionPlugin.
Definition at line 35 of file plugin_sslnetworkoutput.cpp.
References _udp_server, FrameData::cam_id, FrameDataMap::get(), GetTimeSec(), FrameData::map, FrameData::number, ProcessingFailed, ProcessingOk, RoboCupSSLServer::send(), and FrameData::time.
 {
   (void)options;
   if (data==0) return ProcessingFailed;
   SSL_DetectionFrame * detection_frame = 0;
   detection_frame=(SSL_DetectionFrame *)data->map.get("ssl_detection_frame");
   if (detection_frame != 0) {
     detection_frame->set_t_capture(data->time);
     detection_frame->set_frame_number(data->number);
     detection_frame->set_camera_id(data->cam_id);
     detection_frame->set_t_sent(GetTimeSec());
     _udp_server->send(*detection_frame);
   }
   return ProcessingOk;
 }
Field Documentation
const CameraParameters& PluginSSLNetworkOutput::_camera_params protected
Definition at line 36 of file plugin_sslnetworkoutput.h.
const RoboCupField& PluginSSLNetworkOutput::_field protected
Definition at line 37 of file plugin_sslnetworkoutput.h.
RoboCupSSLServer* PluginSSLNetworkOutput::_udp_server protected
Definition at line 38 of file plugin_sslnetworkoutput.h.
Referenced by PluginSSLNetworkOutput(), and process().
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/plugin_sslnetworkoutput.h
ssl-vision/src/app/plugins/plugin_sslnetworkoutput.cpp