Documentation: float_mat Class Reference
float_mat Class Reference
Public Member Functions
float_mat (const size_t rows, const size_t cols, const double def=0.0)
constructor with sizes
float_mat (const float_mat &m)
copy constructor for matrix
float_mat (const std::deque< double > &v)
copy constructor for vector
size_t nr_rows (void) const
use default destructor
size_t nr_cols (void) const
get size
Private Member Functions
float_mat ()
disable the default constructor
float_mat & operator= (const float_mat &)
disable assignment operator until it is implemented.
Detailed Description
Definition at line 57 of file svg.cpp.
Constructor & Destructor Documentation
float_mat::float_mat () inline explicit private
disable the default constructor
Definition at line 60 of file svg.cpp.
Referenced by operator=().
 {};
float_mat::float_mat (const size_t rows, const size_t cols, const double def = 0.0)
constructor with sizes
Definition at line 83 of file svg.cpp.
References velocity.pid_::i.
         : std::vector<std::deque<double> >(rows) {
     int i;
     for (i = 0; i < rows; ++i) {
         (*this)[i].resize(cols, defval);
     }
     if ((rows < 1) || (cols < 1)) {
         char buffer[1024];
         sprintf(buffer, "cannot build matrix with %d rows and %d columns\n",
                 rows, cols);
         //sgs_error(buffer);
     }
 }
float_mat::float_mat (const float_mat & m)
copy constructor for matrix
Definition at line 99 of file svg.cpp.
                                        : std::vector<std::deque<double> >(m.size()) {
     float_mat::iterator inew = begin();
     float_mat::const_iterator iold = m.begin();
     for (/* empty */; iold < m.end(); ++inew, ++iold) {
         const size_t oldsz = iold->size();
         inew->resize(oldsz);
         const std::deque<double> oldvec(*iold);
         *inew = oldvec;
     }
 }
float_mat::float_mat (const std::deque< double > & v)
copy constructor for vector
Definition at line 112 of file svg.cpp.
References v.
         : std::vector<std::deque<double> >(1) {
     const size_t oldsz = v.size();
     front().resize(oldsz);
     front() = v;
 }
Member Function Documentation
size_t float_mat::nr_cols (void) const inline
get size
Definition at line 77 of file svg.cpp.
Referenced by lu_backsubst(), lu_factorize(), lu_forwsubst(), operator*(), and transpose().
 { return front().size(); };
size_t float_mat::nr_rows (void) const inline
use default destructor
get size
Definition at line 75 of file svg.cpp.
Referenced by lin_solve(), lu_backsubst(), lu_factorize(), lu_forwsubst(), operator*(), partial_pivot(), permute(), and transpose().
 { return size(); };
float_mat& float_mat::operator= (const float_mat &) inline private
disable assignment operator until it is implemented.
Definition at line 62 of file svg.cpp.
References float_mat(), and v.
 { return *this; };
The documentation for this class was generated from the following file:
belief_state/src/svg.cpp