Documentation: Colors Class Reference
Colors Class Reference
#include <colors.h>
Static Public Member Functions
static ColorFormat stringToColorFormat (const char *s)
static string colorFormatToString (ColorFormat f)
Detailed Description
Definition at line 58 of file colors.h.
Member Function Documentation
static string Colors::colorFormatToString (ColorFormat f) inline static
Definition at line 92 of file colors.h.
References COLOR_MONO16, COLOR_MONO8, COLOR_RAW16, COLOR_RAW32, COLOR_RAW8, COLOR_RGB16, COLOR_RGB8, COLOR_RGBA8, COLOR_UNDEFINED, COLOR_YUV411, COLOR_YUV422_UYVY, COLOR_YUV422_YUYV, and COLOR_YUV444.
Referenced by CaptureBlueFox2::CaptureBlueFox2(), CaptureDC1394v2::CaptureDC1394v2(), CaptureFlycap::CaptureFlycap(), CaptureFromFile::CaptureFromFile(), CaptureGenerator::CaptureGenerator(), CaptureV4L::CaptureV4L(), CaptureFlycap::convertFrame(), CaptureV4L::convertFrame(), CaptureDC1394v2::convertFrame(), CaptureGenerator::copyAndConvertFrame(), CaptureFromFile::copyAndConvertFrame(), PluginCameraCalibration::detectEdges(), PluginVisualize::DrawCameraImage(), PluginColorCalibration::mouseEvent(), PluginNeuralColorCalib::mouseEvent(), PluginColorThreshold::process(), GLLUTWidget::sampleImage(), CMVisionThreshold::thresholdImageRGB(), CMVisionThreshold::thresholdImageYUV422_UYVY(), and CMVisionThreshold::thresholdImageYUV444().
   {
     if (f==COLOR_RGB8) {
       return ("rgb");
     } else if (f==COLOR_RGBA8) {
       return ("rgba");
     } else if (f==COLOR_YUV411) {
       return ("yuv411");
     } else if (f==COLOR_YUV422_UYVY) {
       return ("yuv422_uyvy");
     } else if (f==COLOR_YUV422_YUYV) {
       return ("yuv422_yuyv");
     } else if (f==COLOR_YUV444) {
       return ("yuv444");
     } else if (f==COLOR_MONO16) {
       return ("mono16");
     } else if (f==COLOR_MONO8) {
       return ("mono8");
     } else if (f==COLOR_RAW8) {
       return ("raw8");
     } else if (f==COLOR_RAW16) {
       return ("raw16");
     } else if (f==COLOR_RAW32) {
       return ("raw32");
     } else if (f==COLOR_RGB16) {
       return ("rgb16");
     } else if (f==COLOR_UNDEFINED) {
       return ("undefined");
     } else {
       return ("unknown");
     }
   }
static ColorFormat Colors::stringToColorFormat (const char * s) inline static
Definition at line 61 of file colors.h.
References COLOR_MONO16, COLOR_MONO8, COLOR_RAW16, COLOR_RAW32, COLOR_RAW8, COLOR_RGB16, COLOR_RGB8, COLOR_RGBA8, COLOR_UNDEFINED, COLOR_YUV411, COLOR_YUV422_UYVY, COLOR_YUV422_YUYV, and COLOR_YUV444.
Referenced by CaptureGenerator::copyAndConvertFrame(), CaptureFromFile::copyAndConvertFrame(), CaptureFlycap::copyAndConvertFrame(), CaptureV4L::copyAndConvertFrame(), CaptureDC1394v2::copyAndConvertFrame(), CaptureBlueFox2::getFrame(), CaptureBlueFox2::startCapture(), CaptureV4L::startCapture(), CaptureDC1394v2::startCapture(), and CaptureFlycap::writeParameterValues().
   {
     if (strcmp(s,"rgb")==0) {
       return COLOR_RGB8;
     } else if (strcmp(s,"rgba")==0) {
       return COLOR_RGBA8;
     } else if (strcmp(s,"yuv411")==0) {
       return COLOR_YUV411;
     } else if (strcmp(s,"yuv422_uyvy")==0) {
       return COLOR_YUV422_UYVY;
     } else if (strcmp(s,"yuv422_yuyv")==0) {
       return COLOR_YUV422_YUYV;
     } else if (strcmp(s,"yuv444")==0) {
       return COLOR_YUV444;
     } else if (strcmp(s,"mono16")==0) {
       return COLOR_MONO16;
     } else if (strcmp(s,"mono8")==0) {
       return COLOR_MONO8;
     } else if (strcmp(s,"raw8")==0) {
       return COLOR_RAW8;
     } else if (strcmp(s,"raw16")==0) {
       return COLOR_RAW16;
     } else if (strcmp(s,"raw32")==0) {
       return COLOR_RAW32;
     } else if (strcmp(s,"rgb16")==0) {
       return COLOR_RGB16;
     } else {
       return COLOR_UNDEFINED;
     }
   }
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/colors.h