Documentation: RoboCup2014Legacy::Wrapper::SSL_WrapperPacket Class Reference
RoboCup2014Legacy::Wrapper::SSL_WrapperPacket Class Reference
#include <messages_robocup_ssl_wrapper_legacy.pb.h>
Public Member Functions
SSL_WrapperPacket ()
virtual ~SSL_WrapperPacket ()
SSL_WrapperPacket (const SSL_WrapperPacket &from)
SSL_WrapperPacket & operator= (const SSL_WrapperPacket &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_WrapperPacket *other)
SSL_WrapperPacket * New () const PROTOBUF_FINAL
SSL_WrapperPacket * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_WrapperPacket &from)
void MergeFrom (const SSL_WrapperPacket &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_detection () const
void clear_detection ()
const ::SSL_DetectionFrame & detection () const
::SSL_DetectionFrame * release_detection ()
::SSL_DetectionFrame * mutable_detection ()
void set_allocated_detection (::SSL_DetectionFrame *detection)
bool has_geometry () const
void clear_geometry ()
const ::RoboCup2014Legacy::Geometry::SSL_GeometryData & geometry () const
::RoboCup2014Legacy::Geometry::SSL_GeometryData * release_geometry ()
::RoboCup2014Legacy::Geometry::SSL_GeometryData * mutable_geometry ()
void set_allocated_geometry (::RoboCup2014Legacy::Geometry::SSL_GeometryData *geometry)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_WrapperPacket & default_instance ()
static void InitAsDefaultInstance ()
static const SSL_WrapperPacket * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kDetectionFieldNumber = 1
static const int kGeometryFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_WrapperPacket *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_detection ()
void clear_has_detection ()
void set_has_geometry ()
void clear_has_geometry ()
friend void::protobuf_messages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto::InitDefaultsSSL_WrapperPacketImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::SSL_DetectionFrame * detection_
::RoboCup2014Legacy::Geometry::SSL_GeometryData * geometry_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto::TableStruct
void swap (SSL_WrapperPacket &a, SSL_WrapperPacket &b)
Detailed Description
Definition at line 65 of file messages_robocup_ssl_wrapper_legacy.pb.h.
Constructor & Destructor Documentation
RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::SSL_WrapperPacket ()
virtual RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::~SSL_WrapperPacket () virtual
RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::SSL_WrapperPacket (const SSL_WrapperPacket & from)
Member Function Documentation
size_t RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::ByteSizeLong () const
void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::Clear ()
void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::clear_detection ()
void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::clear_geometry ()
void SSL_WrapperPacket::clear_has_detection () inline private
Definition at line 205 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void SSL_WrapperPacket::clear_has_geometry () inline private
Definition at line 255 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000002u;
 }
void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::CopyFrom (const ::google::protobuf::Message & from)
void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::CopyFrom (const SSL_WrapperPacket & from)
static const SSL_WrapperPacket& RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::default_instance () static
static const ::google::protobuf::Descriptor* RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::descriptor () static
const ::SSL_DetectionFrame & SSL_WrapperPacket::detection () const inline
Definition at line 208 of file messages_robocup_ssl_wrapper_legacy.pb.h.
References _SSL_DetectionFrame_default_instance_.
{
   const ::SSL_DetectionFrame* p = detection_;
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.detection)
   return p != NULL ? *p : *reinterpret_cast<const ::SSL_DetectionFrame*>(
       &::_SSL_DetectionFrame_default_instance_);
 }
const ::RoboCup2014Legacy::Geometry::SSL_GeometryData & SSL_WrapperPacket::geometry () const inline
Definition at line 258 of file messages_robocup_ssl_wrapper_legacy.pb.h.
References _SSL_GeometryData_default_instance_.
{
   const ::RoboCup2014Legacy::Geometry::SSL_GeometryData* p = geometry_;
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.geometry)
   return p != NULL ? *p : *reinterpret_cast<const ::RoboCup2014Legacy::Geometry::SSL_GeometryData*>(
       &::RoboCup2014Legacy::Geometry::_SSL_GeometryData_default_instance_);
 }
inline ::google::protobuf::Arena* RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::GetArenaNoVirtual () const inline private
Definition at line 140 of file messages_robocup_ssl_wrapper_legacy.pb.h.
Referenced by operator=().
{
     return NULL;
   }
int RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::GetCachedSize () const inline
Definition at line 133 of file messages_robocup_ssl_wrapper_legacy.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::GetMetadata () const
bool SSL_WrapperPacket::has_detection () const inline
Definition at line 199 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool SSL_WrapperPacket::has_geometry () const inline
Definition at line 249 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
static void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::InitAsDefaultInstance () static
static const SSL_WrapperPacket* RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::internal_default_instance () inline static
Definition at line 102 of file messages_robocup_ssl_wrapper_legacy.pb.h.
References RoboCup2014Legacy::Wrapper::_SSL_WrapperPacket_default_instance_.
{
     return reinterpret_cast<const SSL_WrapperPacket*>(
                &_SSL_WrapperPacket_default_instance_);
   }
::google::protobuf::uint8* RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::InternalSwap (SSL_WrapperPacket * other) private
bool RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::IsInitialized () const
void* RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::MaybeArenaPtr () const inline private
Definition at line 143 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
     return NULL;
   }
void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::MergeFrom (const ::google::protobuf::Message & from)
void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::MergeFrom (const SSL_WrapperPacket & from)
bool RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
SSL_DetectionFrame * SSL_WrapperPacket::mutable_detection () inline
Definition at line 221 of file messages_robocup_ssl_wrapper_legacy.pb.h.
Referenced by RoboCupSSLServer::sendLegacyMessage().
{
   set_has_detection();
   if (detection_ == NULL) {
     detection_ = new ::SSL_DetectionFrame;
   }
   // @@protoc_insertion_point(field_mutable:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.detection)
   return detection_;
 }
RoboCup2014Legacy::Geometry::SSL_GeometryData * SSL_WrapperPacket::mutable_geometry () inline
Definition at line 271 of file messages_robocup_ssl_wrapper_legacy.pb.h.
Referenced by RoboCupSSLServer::sendLegacyMessage().
{
   set_has_geometry();
   if (geometry_ == NULL) {
     geometry_ = new ::RoboCup2014Legacy::Geometry::SSL_GeometryData;
   }
   // @@protoc_insertion_point(field_mutable:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.geometry)
   return geometry_;
 }
inline ::google::protobuf::UnknownFieldSet* RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::mutable_unknown_fields () inline
Definition at line 94 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
SSL_WrapperPacket* RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::New () const inline
Definition at line 116 of file messages_robocup_ssl_wrapper_legacy.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_WrapperPacket* RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::New (::google::protobuf::Arena * arena) const
SSL_WrapperPacket& RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::operator= (const SSL_WrapperPacket & from) inline
Definition at line 72 of file messages_robocup_ssl_wrapper_legacy.pb.h.
References GetArenaNoVirtual().
{
     CopyFrom(from);
     return *this;
   }
SSL_DetectionFrame * SSL_WrapperPacket::release_detection () inline
Definition at line 214 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
   // @@protoc_insertion_point(field_release:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.detection)
   clear_has_detection();
   ::SSL_DetectionFrame* temp = detection_;
   detection_ = NULL;
   return temp;
 }
RoboCup2014Legacy::Geometry::SSL_GeometryData * SSL_WrapperPacket::release_geometry () inline
Definition at line 264 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
   // @@protoc_insertion_point(field_release:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.geometry)
   clear_has_geometry();
   ::RoboCup2014Legacy::Geometry::SSL_GeometryData* temp = geometry_;
   geometry_ = NULL;
   return temp;
 }
void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void SSL_WrapperPacket::set_allocated_detection (::SSL_DetectionFrame * detection) inline
Definition at line 229 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
   ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
   if (message_arena == NULL) {
     delete reinterpret_cast< ::google::protobuf::MessageLite*>(detection_);
   }
   if (detection) {
     ::google::protobuf::Arena* submessage_arena = NULL;
     if (message_arena != submessage_arena) {
       detection = ::google::protobuf::internal::GetOwnedMessage(
           message_arena, detection, submessage_arena);
     }
     set_has_detection();
   } else {
     clear_has_detection();
   }
   detection_ = detection;
   // @@protoc_insertion_point(field_set_allocated:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.detection)
 }
void SSL_WrapperPacket::set_allocated_geometry (::RoboCup2014Legacy::Geometry::SSL_GeometryData * geometry) inline
Definition at line 279 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
   ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
   if (message_arena == NULL) {
     delete reinterpret_cast< ::google::protobuf::MessageLite*>(geometry_);
   }
   if (geometry) {
     ::google::protobuf::Arena* submessage_arena = NULL;
     if (message_arena != submessage_arena) {
       geometry = ::google::protobuf::internal::GetOwnedMessage(
           message_arena, geometry, submessage_arena);
     }
     set_has_geometry();
   } else {
     clear_has_geometry();
   }
   geometry_ = geometry;
   // @@protoc_insertion_point(field_set_allocated:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.geometry)
 }
void SSL_WrapperPacket::set_has_detection () inline private
Definition at line 202 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000001u;
 }
void SSL_WrapperPacket::set_has_geometry () inline private
Definition at line 252 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000002u;
 }
void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::SetCachedSize (int size) const private
void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::SharedCtor () private
void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::SharedDtor () private
void RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::Swap (SSL_WrapperPacket * other)
const ::google::protobuf::UnknownFieldSet& RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::unknown_fields () const inline
Definition at line 91 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::void::protobuf_messages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto::InitDefaultsSSL_WrapperPacketImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto::TableStruct friend
Definition at line 184 of file messages_robocup_ssl_wrapper_legacy.pb.h.
void swap (SSL_WrapperPacket & a, SSL_WrapperPacket & b) friend
Definition at line 110 of file messages_robocup_ssl_wrapper_legacy.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::_cached_size_ mutable private
Definition at line 181 of file messages_robocup_ssl_wrapper_legacy.pb.h.
::google::protobuf::internal::HasBits<1> RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::_has_bits_ private
Definition at line 180 of file messages_robocup_ssl_wrapper_legacy.pb.h.
::google::protobuf::internal::InternalMetadataWithArena RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::_internal_metadata_ private
Definition at line 179 of file messages_robocup_ssl_wrapper_legacy.pb.h.
::SSL_DetectionFrame* RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::detection_ private
Definition at line 182 of file messages_robocup_ssl_wrapper_legacy.pb.h.
::RoboCup2014Legacy::Geometry::SSL_GeometryData* RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::geometry_ private
Definition at line 183 of file messages_robocup_ssl_wrapper_legacy.pb.h.
const int RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::kDetectionFieldNumber = 1 static
Definition at line 157 of file messages_robocup_ssl_wrapper_legacy.pb.h.
const int RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::kGeometryFieldNumber = 2 static
Definition at line 166 of file messages_robocup_ssl_wrapper_legacy.pb.h.
PROTOBUF_CONSTEXPR int const RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::kIndexInFileMessages static
Initial value:
=
    0
Definition at line 106 of file messages_robocup_ssl_wrapper_legacy.pb.h.
The documentation for this class was generated from the following file:
ssl-vision/build/messages_robocup_ssl_wrapper_legacy.pb.h