Documentation: Zoom Class Reference
Zoom Class Reference
A class for computation of 2D zoom + pan operations.
#include <zoom.h>
Public Member Functions
double getZoom ()
double getPanX ()
double getPanY ()
void reset ()
void setup (int img_width, int img_height, int surface_width, int surface_height, bool center_origin=false)
void setCustomImageCenter (double x, double y)
void setDefaultImageCenter ()
bool getFlipX ()
bool getFlipY ()
double getFlipXval ()
double getFlipYval ()
void setFlipX (bool val)
void setFlipY (bool val)
void zoomToFit ()
void setZoom (double val)
void setPan (double valX, double valY)
void panLeft (double distance=0.01)
void panRight (double distance=0.01)
void panUp (double distance=0.01)
void panDown (double distance=0.01)
void zoomIn (double factor=1.25)
void zoomOut (double factor=1.25)
Zoom ()
virtual ~Zoom ()
QTransform getQTransform (bool center_origin)
pixelloc zoom (int x, int y)
pixelloc invZoom (int x, int y, bool disable_center_origin=false)
Protected Attributes
double IMAGE_WIDTH
double IMAGE_HEIGHT
double SURFACE_WIDTH
double SURFACE_HEIGHT
bool CENTER_ORIGIN
double flipX
double flipY
double img_center_x
double img_center_y
double zoomFactor
double zoomCenterX
double zoomCenterY
Detailed Description
A class for computation of 2D zoom + pan operations.
Author
Stefan Zickler, (C) 2008
Definition at line 39 of file zoom.h.
Constructor & Destructor Documentation
Zoom::Zoom () inline
Definition at line 156 of file zoom.h.
References reset(), and setup().
            {
       CENTER_ORIGIN=false;
       setup ( 320,240,320,240 );
       reset();
     }
virtual Zoom::~Zoom () inline virtual
Definition at line 162 of file zoom.h.
                     {
     }
Member Function Documentation
bool Zoom::getFlipX () inline
Definition at line 92 of file zoom.h.
                     {
       return ( flipX < 0 );
     }
double Zoom::getFlipXval () inline
Definition at line 98 of file zoom.h.
References flipX.
Referenced by GLWidget::mouseAction(), and GLWidget::myGLdraw().
{
       return flipX;
     }
bool Zoom::getFlipY () inline
Definition at line 95 of file zoom.h.
Referenced by invZoom().
                     {
       return ( flipY < 0 );
     }
double Zoom::getFlipYval () inline
Definition at line 101 of file zoom.h.
References flipY.
Referenced by GLWidget::mouseAction(), and GLWidget::myGLdraw().
{
       return flipY;
     }
double Zoom::getPanX () inline
Definition at line 56 of file zoom.h.
References zoomCenterX.
Referenced by GLWidget::mouseAction(), panDown(), panLeft(), panRight(), and panUp().
                      {
       return zoomCenterX;
     }
double Zoom::getPanY () inline
Definition at line 59 of file zoom.h.
References zoomCenterY.
Referenced by GLWidget::mouseAction(), panDown(), panLeft(), panRight(), and panUp().
                      {
       return zoomCenterY;
     }
QTransform Zoom::getQTransform (bool center_origin) inline
Definition at line 166 of file zoom.h.
References t.
Referenced by GLWidget::mainDraw().
{
       if ( center_origin ) {
         QTransform t ( zoomFactor * flipX, 0.0,0.0,zoomFactor * flipY,
                        ( ( - img_center_x )   + ( zoomCenterX * SURFACE_WIDTH ) ) * ( zoomFactor * flipX ) ,
                        ( ( - img_center_y )   + ( zoomCenterY * SURFACE_HEIGHT ) ) * ( zoomFactor * flipY ) );
         return t;
       } else {
               QTransform t ( zoomFactor * flipX, 0.0,0.0,zoomFactor * flipY,
                        ( ( - img_center_x )   + ( zoomCenterX * SURFACE_WIDTH ) ) * ( zoomFactor * flipX ) + SURFACE_WIDTH / 2.0,
                        ( ( - img_center_y )   + ( zoomCenterY * SURFACE_HEIGHT ) ) * ( zoomFactor * flipY ) + SURFACE_HEIGHT / 2.0 );
         return t;
       }
     }
double Zoom::getZoom () inline
Definition at line 53 of file zoom.h.
References zoomFactor.
Referenced by GLWidget::mouseAction(), GLWidget::myGLdraw(), zoomIn(), and zoomOut().
                      {
       return zoomFactor;
     }
pixelloc Zoom::invZoom (int x, int y, bool disable_center_origin = false) inline
Definition at line 200 of file zoom.h.
References flipX, flipY, getFlipY(), SURFACE_HEIGHT, SURFACE_WIDTH, pixelloc::x, and pixelloc::y.
Referenced by GLWidget::mouseAction(), and GLWidget::resizeGL().
{
       pixelloc result;
       double tx= ( double ) x;
       double ty= ( double ) y;
       if ( CENTER_ORIGIN==false || disable_center_origin ) {
         tx-= ( double ) SURFACE_WIDTH/2.0;
         ty-= ( double ) SURFACE_HEIGHT/2.0;
       }
       result.x = ( int ) ( ( ( ( double ) tx / ( zoomFactor * flipX ) ) - ( zoomCenterX * SURFACE_WIDTH ) + ( img_center_x ) ) - ( 0.0 ) );
       result.y = ( int ) ( ( ( ( double ) ty / ( zoomFactor * flipY ) ) - ( zoomCenterY * SURFACE_HEIGHT ) + ( img_center_y ) ) - ( getFlipY() ? 0.0 : 0.5 ) );
       return result;
     }
void Zoom::panDown (double distance = 0.01) inline
Definition at line 147 of file zoom.h.
References GVector::distance(), getPanX(), getPanY(), and setPan().
Referenced by GLWidget::callHelp().
{
       setPan ( getPanX(),getPanY() + ( distance*flipY ) );
     }
void Zoom::panLeft (double distance = 0.01) inline
Definition at line 138 of file zoom.h.
References GVector::distance(), getPanX(), getPanY(), and setPan().
Referenced by GLWidget::callHelp().
{
       setPan ( getPanX()- ( distance*flipX ),getPanY() );
     }
void Zoom::panRight (double distance = 0.01) inline
Definition at line 141 of file zoom.h.
References GVector::distance(), getPanX(), getPanY(), and setPan().
Referenced by GLWidget::callHelp().
{
       setPan ( getPanX() + ( distance*flipX ),getPanY() );
     }
void Zoom::panUp (double distance = 0.01) inline
Definition at line 144 of file zoom.h.
References GVector::distance(), getPanX(), getPanY(), and setPan().
Referenced by GLWidget::callHelp().
{
       setPan ( getPanX(),getPanY()- ( distance*flipY ) );
     }
void Zoom::reset () inline
Definition at line 62 of file zoom.h.
Referenced by Zoom().
                  {
       flipX=1.0;
       flipY=1.0;
       zoomFactor=1.0;
       zoomCenterX=0.0;
       zoomCenterY=0.0;
     }
void Zoom::setCustomImageCenter (double x, double y) inline
Definition at line 82 of file zoom.h.
References role._GoToPoint::x, and role._GoToPoint::y.
{
       img_center_x=x;
       img_center_y=y;
     }
void Zoom::setDefaultImageCenter () inline
Definition at line 87 of file zoom.h.
{
       img_center_x=IMAGE_WIDTH/2.0;
       img_center_y=IMAGE_HEIGHT/2.0;
     }
void Zoom::setFlipX (bool val) inline
Definition at line 104 of file zoom.h.
Referenced by GLWidget::flipImage().
{
       if ( val ) {
         flipX= ( -1.0 );
       } else {
         flipX=1.0;
       }
     }
void Zoom::setFlipY (bool val) inline
Definition at line 112 of file zoom.h.
Referenced by GLWidget::flipImage().
{
       if ( val ) {
         flipY= ( -1.0 );
       } else {
         flipY=1.0;
       }
     }
void Zoom::setPan (double valX, double valY) inline
Definition at line 130 of file zoom.h.
References MAX_PAN, and MIN_PAN.
Referenced by GLWidget::callZoomFit(), GLWidget::callZoomNormal(), GLWidget::mouseAction(), panDown(), panLeft(), panRight(), and panUp().
{
       if ( valX < MIN_PAN ) valX=MIN_PAN;
       if ( valX > MAX_PAN ) valX=MAX_PAN;
       if ( valY < MIN_PAN ) valY=MIN_PAN;
       if ( valY > MAX_PAN ) valY=MAX_PAN;
       zoomCenterX=valX;
       zoomCenterY=valY;
     }
void Zoom::setup (int img_width, int img_height, int surface_width, int surface_height, bool center_origin = false) inline
Definition at line 69 of file zoom.h.
Referenced by GLWidget::myGLdraw(), and Zoom().
{
       //if center_origin is true then it is assumed that pixel coordinate 0,0 is in the
       //center of the viewport (after loading glLoadIdentity() in ortho mode this is usually the case)
       //if it's false then its assumes that the origin is in the corner of the viewport
       CENTER_ORIGIN=center_origin;
       IMAGE_WIDTH=img_width;
       IMAGE_HEIGHT=img_height;
       img_center_x=IMAGE_WIDTH/2.0;
       img_center_y=IMAGE_HEIGHT/2.0;
       SURFACE_WIDTH=surface_width;
       SURFACE_HEIGHT=surface_height;
     }
void Zoom::setZoom (double val) inline
Definition at line 124 of file zoom.h.
References MAX_ZOOM, and MIN_ZOOM.
Referenced by GLWidget::callZoomNormal(), zoomIn(), zoomOut(), and zoomToFit().
{
       if ( val < MIN_ZOOM ) val=MIN_ZOOM;
       if ( val > MAX_ZOOM ) val=MAX_ZOOM;
       zoomFactor=val;
     }
pixelloc Zoom::zoom (int x, int y) inline
Definition at line 184 of file zoom.h.
References flipX, flipY, SURFACE_HEIGHT, SURFACE_WIDTH, role._GoToPoint::x, pixelloc::x, role._GoToPoint::y, and pixelloc::y.
Referenced by GLWidget::myGLdraw().
{
       pixelloc result;
       double tx,ty;
       tx= x;
       ty= y;
       if ( CENTER_ORIGIN ) {
         result.x= ( int ) ( ( tx - ( img_center_x )   + ( zoomCenterX * SURFACE_WIDTH ) ) * ( zoomFactor * flipX ) );
         result.y= ( int ) ( ( ty - ( img_center_y )  + ( zoomCenterY * SURFACE_HEIGHT ) ) * ( zoomFactor * flipY ) );
       } else {
         result.x= ( int ) ( ( ( tx - ( img_center_x )   + ( zoomCenterX * SURFACE_WIDTH ) ) * ( zoomFactor * flipX ) ) + SURFACE_WIDTH/2.0 ) ;
         result.y= ( int ) ( ( ( ty - ( img_center_y )  + ( zoomCenterY * SURFACE_HEIGHT ) ) * ( zoomFactor * flipY ) ) + SURFACE_HEIGHT/2.0 ) ;
       }
       return ( result );
     }
void Zoom::zoomIn (double factor = 1.25) inline
Definition at line 150 of file zoom.h.
References getZoom(), and setZoom().
Referenced by GLWidget::callHelp(), and GLWidget::resizeGL().
{
       setZoom ( getZoom() *factor );
     }
void Zoom::zoomOut (double factor = 1.25) inline
Definition at line 153 of file zoom.h.
References getZoom(), and setZoom().
Referenced by GLWidget::callHelp(), and GLWidget::resizeGL().
{
       setZoom ( getZoom() /factor );
     }
void Zoom::zoomToFit () inline
Definition at line 120 of file zoom.h.
References GVector::min(), and setZoom().
Referenced by GLWidget::callZoomFit().
                      {
       setZoom ( min ( ( double ) SURFACE_WIDTH/ ( double ) IMAGE_WIDTH, ( double ) SURFACE_HEIGHT/ ( double ) IMAGE_HEIGHT ) );
     }
Field Documentation
bool Zoom::CENTER_ORIGIN protected
Definition at line 45 of file zoom.h.
double Zoom::flipX protected
Definition at line 46 of file zoom.h.
Referenced by getFlipXval(), invZoom(), and zoom().
double Zoom::flipY protected
Definition at line 47 of file zoom.h.
Referenced by getFlipYval(), invZoom(), and zoom().
double Zoom::IMAGE_HEIGHT protected
Definition at line 42 of file zoom.h.
double Zoom::IMAGE_WIDTH protected
Definition at line 41 of file zoom.h.
double Zoom::img_center_x protected
Definition at line 48 of file zoom.h.
double Zoom::img_center_y protected
Definition at line 49 of file zoom.h.
double Zoom::SURFACE_HEIGHT protected
Definition at line 44 of file zoom.h.
Referenced by invZoom(), and zoom().
double Zoom::SURFACE_WIDTH protected
Definition at line 43 of file zoom.h.
Referenced by invZoom(), and zoom().
double Zoom::zoomCenterX protected
Definition at line 51 of file zoom.h.
Referenced by getPanX().
double Zoom::zoomCenterY protected
Definition at line 51 of file zoom.h.
Referenced by getPanY().
double Zoom::zoomFactor protected
Definition at line 50 of file zoom.h.
Referenced by getZoom().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/zoom.h