Documentation: grsim_comm/include/proto/grSim_Packet.pb.cc File Reference
grSim_Packet.pb.cc File Reference
#include "grSim_Packet.pb.h"
#include <algorithm>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
Data Structures
class grSim_PacketDefaultTypeInternal
struct StaticDescriptorInitializer_grSim_5fPacket_2eproto
Namespaces
anonymous_namespace{grSim_Packet.pb.cc}
Macros
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Functions
const ::google::protobuf::uint32 * protobuf_Offsets_grSim_5fPacket_2eproto () GOOGLE_ATTRIBUTE_COLD
void anonymous_namespace{grSim_Packet.pb.cc}::protobuf_AssignDescriptors ()
void anonymous_namespace{grSim_Packet.pb.cc}::protobuf_AssignDescriptorsOnce ()
void anonymous_namespace{grSim_Packet.pb.cc}::protobuf_RegisterTypes (const ::std::string &) GOOGLE_ATTRIBUTE_COLD
void protobuf_ShutdownFile_grSim_5fPacket_2eproto ()
void protobuf_InitDefaults_grSim_5fPacket_2eproto_impl ()
void protobuf_InitDefaults_grSim_5fPacket_2eproto ()
void protobuf_AddDesc_grSim_5fPacket_2eproto_impl ()
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_grSim_5fPacket_2eproto_once_)
void protobuf_AddDesc_grSim_5fPacket_2eproto ()
Variables
grSim_PacketDefaultTypeInternal _grSim_Packet_default_instance_
::google::protobuf::Metadata anonymous_namespace{grSim_Packet.pb.cc}::file_level_metadata [1]
static const ::google::protobuf::internal::MigrationSchema schemas []
static const ::google::protobuf::internal::DefaultInstanceData file_default_instances []
struct StaticDescriptorInitializer_grSim_5fPacket_2eproto static_descriptor_initializer_grSim_5fPacket_2eproto_
Macro Definition Documentation
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Referenced by grSim_Packet::MergePartialFromCodedStream().
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
Definition at line 4 of file grSim_Packet.pb.cc.
Function Documentation
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_grSim_5fPacket_2eproto_once_)
Referenced by protobuf_AddDesc_grSim_5fPacket_2eproto_impl(), anonymous_namespace{grSim_Packet.pb.cc}::protobuf_AssignDescriptorsOnce(), and protobuf_InitDefaults_grSim_5fPacket_2eproto().
void protobuf_AddDesc_grSim_5fPacket_2eproto ()
Definition at line 123 of file grSim_Packet.pb.cc.
References protobuf_AddDesc_grSim_5fPacket_2eproto_impl().
Referenced by anonymous_namespace{grSim_Packet.pb.cc}::protobuf_AssignDescriptors(), and StaticDescriptorInitializer_grSim_5fPacket_2eproto::StaticDescriptorInitializer_grSim_5fPacket_2eproto().
{
   ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_grSim_5fPacket_2eproto_once_,
                  &protobuf_AddDesc_grSim_5fPacket_2eproto_impl);
 }
void protobuf_AddDesc_grSim_5fPacket_2eproto_impl ()
Definition at line 102 of file grSim_Packet.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), protobuf_AddDesc_grSim_5fCommands_2eproto(), protobuf_AddDesc_grSim_5fReplacement_2eproto(), protobuf_AddDesc_sslDebug_5fData_2eproto(), protobuf_InitDefaults_grSim_5fPacket_2eproto(), anonymous_namespace{grSim_Packet.pb.cc}::protobuf_RegisterTypes(), and protobuf_ShutdownFile_grSim_5fPacket_2eproto().
Referenced by protobuf_AddDesc_grSim_5fPacket_2eproto().
{
   protobuf_InitDefaults_grSim_5fPacket_2eproto();
   static const char descriptor[] = {
       "\n\022grSim_Packet.proto\032\024grSim_Commands.pro"
       "to\032\027grSim_Replacement.proto\032\023sslDebug_Da"
       "ta.proto\"}\n\014grSim_Packet\022!\n\010commands\030\001 \001"
       "(\0132\017.grSim_Commands\022\'\n\013replacement\030\002 \001(\013"
       "2\022.grSim_Replacement\022!\n\tdebuginfo\030\003 \001(\0132"
       "\016.sslDebug_Data"
   };
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
       descriptor, 215);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "grSim_Packet.proto", &protobuf_RegisterTypes);
   ::protobuf_AddDesc_grSim_5fCommands_2eproto();
   ::protobuf_AddDesc_grSim_5fReplacement_2eproto();
   ::protobuf_AddDesc_sslDebug_5fData_2eproto();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_grSim_5fPacket_2eproto);
 }
void protobuf_InitDefaults_grSim_5fPacket_2eproto ()
Definition at line 98 of file grSim_Packet.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), and protobuf_InitDefaults_grSim_5fPacket_2eproto_impl().
Referenced by grSim_Packet::default_instance(), grSim_Packet::grSim_Packet(), and protobuf_AddDesc_grSim_5fPacket_2eproto_impl().
{
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
   ::google::protobuf::GoogleOnceInit(&once, &protobuf_InitDefaults_grSim_5fPacket_2eproto_impl);
 }
void protobuf_InitDefaults_grSim_5fPacket_2eproto_impl ()
Definition at line 82 of file grSim_Packet.pb.cc.
References sslDebug_Data::internal_default_instance(), grSim_Commands::internal_default_instance(), grSim_Replacement::internal_default_instance(), protobuf_InitDefaults_grSim_5fCommands_2eproto(), protobuf_InitDefaults_grSim_5fReplacement_2eproto(), and protobuf_InitDefaults_sslDebug_5fData_2eproto().
Referenced by protobuf_InitDefaults_grSim_5fPacket_2eproto().
{
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::protobuf_InitDefaults_grSim_5fCommands_2eproto();
   ::protobuf_InitDefaults_grSim_5fReplacement_2eproto();
   ::protobuf_InitDefaults_sslDebug_5fData_2eproto();
   ::google::protobuf::internal::InitProtobufDefaults();
   _grSim_Packet_default_instance_.DefaultConstruct();
   _grSim_Packet_default_instance_.get_mutable()->commands_ = const_cast< ::grSim_Commands*>(
       ::grSim_Commands::internal_default_instance());
   _grSim_Packet_default_instance_.get_mutable()->replacement_ = const_cast< ::grSim_Replacement*>(
       ::grSim_Replacement::internal_default_instance());
   _grSim_Packet_default_instance_.get_mutable()->debuginfo_ = const_cast< ::sslDebug_Data*>(
       ::sslDebug_Data::internal_default_instance());
 }
const ::google::protobuf::uint32 * protobuf_Offsets_grSim_5fPacket_2eproto ()
Definition at line 30 of file grSim_Packet.pb.cc.
Referenced by anonymous_namespace{grSim_Packet.pb.cc}::protobuf_AssignDescriptors().
{
   static const ::google::protobuf::uint32 offsets[] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Packet, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Packet, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Packet, commands_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Packet, replacement_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Packet, debuginfo_),
     0,
     1,
     2,
   };
   return offsets;
 }
void protobuf_ShutdownFile_grSim_5fPacket_2eproto ()
Definition at line 77 of file grSim_Packet.pb.cc.
References anonymous_namespace{grSim_Packet.pb.cc}::file_level_metadata.
Referenced by protobuf_AddDesc_grSim_5fPacket_2eproto_impl().
{
   _grSim_Packet_default_instance_.Shutdown();
   delete file_level_metadata[0].reflection;
 }
Variable Documentation
grSim_PacketDefaultTypeInternal _grSim_Packet_default_instance_
Definition at line 20 of file grSim_Packet.pb.cc.
Referenced by grSim_Packet::internal_default_instance().
const ::google::protobuf::internal::DefaultInstanceData file_default_instances[] static
Initial value:
= {
  {reinterpret_cast<const ::google::protobuf::Message*>(&_grSim_Packet_default_instance_), NULL},
}
Definition at line 50 of file grSim_Packet.pb.cc.
Referenced by anonymous_namespace{grSim_Packet.pb.cc}::protobuf_AssignDescriptors().
const ::google::protobuf::internal::MigrationSchema schemas[] static
Initial value:
= {
  { 0, 7, sizeof(grSim_Packet)},
}
Definition at line 46 of file grSim_Packet.pb.cc.
Referenced by anonymous_namespace{grSim_Packet.pb.cc}::protobuf_AssignDescriptors().
struct StaticDescriptorInitializer_grSim_5fPacket_2eproto static_descriptor_initializer_grSim_5fPacket_2eproto_
Referenced by StaticDescriptorInitializer_grSim_5fPacket_2eproto::StaticDescriptorInitializer_grSim_5fPacket_2eproto().