Documentation: PluginCameraCalibration Class Reference
PluginCameraCalibration Class Reference
#include <plugin_cameracalib.h>
Public Member Functions
PluginCameraCalibration (FrameBuffer *_buffer, CameraParameters &camera_params, RoboCupField &_field)
~PluginCameraCalibration ()
virtual ProcessResult process (FrameData *data, RenderOptions *options)
virtual VarList * getSettings ()
virtual std::string getName ()
virtual QWidget * getControlWidget ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
Public Member Functions inherited from VisionPlugin
VisionPlugin (FrameBuffer *_buffer)
virtual ~VisionPlugin ()
FrameBuffer * getFrameBuffer () const
this functions provides convenient access to the ring-buffer
void lock ()
void unlock ()
virtual bool isEnabled () const
virtual void setEnabled (bool enable)
virtual bool isVisualize () const
virtual void setVisualize (bool enable)
virtual bool isSharedAmongStacks () const
virtual void setSharedAmongStacks (bool enable)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual void postProcess (FrameData *data, RenderOptions *options)
virtual QWidget * getVisualizationWidget ()
virtual void closeWidgets ()
virtual QList< QAction * > actions ()
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
void setTimeProcessing (double val)
void setTimePostProcessing (double val)
double getTimeProcessing ()
double getTimePostProcessing ()
Protected Member Functions
void mouseEvent (QMouseEvent *event, pixelloc loc)
void sanitizeSobel (greyImage *img, GVector::vector2d< double > &val, int sobel_border=1)
void detectEdges (FrameData *data)
void detectEdgesOnSingleLine (const GVector::vector3d< double > &p1, const GVector::vector3d< double > &p2, double thickness, double point_separation)
void detectEdgesOnSingleArc (const GVector::vector3d< double > &center, double radius, double theta1, double theta2, double thickness, double point_separation)
Protected Attributes
VarList * settings
VarList * camera_settings
VarList * calibration_settings
CameraParameters & camera_parameters
RoboCupField & field
CameraCalibrationWidget * ccw
greyImage * grey_image
rgbImage * rgb_image
int video_width
int video_height
bool doing_drag
VarDouble * drag_x
VarDouble * drag_y
Protected Attributes inherited from VisionPlugin
QMutex mutex
bool enabled
bool visualize
bool shared
FrameBuffer * buffer
double time_proc
double time_post
Additional Inherited Members
Public Slots inherited from VisionPlugin
void slotKeyPressEvent (QKeyEvent *event)
Detailed Description
Author
Tim Laue Tim.L.nosp@m.aue@.nosp@m.dfki..nosp@m.de
Definition at line 35 of file plugin_cameracalib.h.
Constructor & Destructor Documentation
PluginCameraCalibration::PluginCameraCalibration (FrameBuffer * _buffer, CameraParameters & camera_params, RoboCupField & _field)
Definition at line 31 of file plugin_cameracalib.cpp.
References VarTypes::VarList::addChild(), CameraParameters::additional_calibration_information, CameraParameters::addSettingsToList(), CameraParameters::AdditionalCalibrationInformation::addSettingsToList(), calibration_settings, camera_parameters, camera_settings, settings, video_height, and video_width.
                           :
     VisionPlugin(_buffer), camera_parameters(camera_params),
     field(_field),
     ccw(0), grey_image(0), rgb_image(0), doing_drag(false), drag_x(0),
     drag_y(0) {
   video_width=video_height=0;
   settings=new VarList("Camera Calibrator");
   settings->addChild(camera_settings = new VarList("Camera Parameters"));
   camera_params.addSettingsToList(*camera_settings);
   settings->addChild(calibration_settings =
       new VarList("Calibration Parameters"));
   camera_parameters.additional_calibration_information->addSettingsToList(
       *calibration_settings);
 }
PluginCameraCalibration::~PluginCameraCalibration ()
Definition at line 48 of file plugin_cameracalib.cpp.
References calibration_settings, camera_settings, grey_image, and rgb_image.
{
   delete camera_settings;
   delete calibration_settings;
   if(grey_image)
     delete grey_image;
   if(rgb_image)
     delete rgb_image;
 }
Member Function Documentation
void PluginCameraCalibration::detectEdges (FrameData * data) protected
Definition at line 57 of file plugin_cameracalib.cpp.
References FieldCircularArc::a1, FieldCircularArc::a2, CameraParameters::additional_calibration_information, CameraParameters::calibrationSegments, camera_parameters, FieldCircularArc::center_x, FieldCircularArc::center_y, COLOR_RGB8, COLOR_YUV422_UYVY, Colors::colorFormatToString(), Images::convert(), detectEdgesOnSingleArc(), detectEdgesOnSingleLine(), field, RoboCupField::field_arcs, RoboCupField::field_lines, RoboCupField::field_markings_mutex, RawImage::getColorFormat(), RawImage::getData(), VarTypes::VarDoubleVal::getDouble(), RawImage::getHeight(), RawImage::getWidth(), grey_image, velocity.pid_::i, FieldLine::p1_x, FieldLine::p1_y, FieldLine::p2_x, FieldLine::p2_y, FieldCircularArc::radius, rgb_image, FieldLine::thickness, FieldCircularArc::thickness, Conversions::uyvy2rgb(), and FrameData::video.
Referenced by process().
{
   double point_separation(camera_parameters.additional_calibration_information->
       pointSeparation->getDouble());
   // Reset list:
   camera_parameters.calibrationSegments.clear();
   // Get a greyscale image:
   if(grey_image == 0) {
     grey_image = new greyImage(data->video.getWidth(),data->video.getHeight());
     rgb_image = new rgbImage(data->video.getWidth(),data->video.getHeight());
   }
   if (data->video.getColorFormat()==COLOR_YUV422_UYVY) {
     Conversions::uyvy2rgb(
         data->video.getData(),
         reinterpret_cast<unsigned char*>(rgb_image->getData()),
         data->video.getWidth(),data->video.getHeight());
     Images::convert(*rgb_image, *grey_image);
   } else if (data->video.getColorFormat()==COLOR_RGB8) {
     Images::convert(data->video, *grey_image);
   } else {
     fprintf(stderr, "ColorThresholding needs YUV422 or RGB8 as input image, "
             "but found: %s\n",
             Colors::colorFormatToString(data->video.getColorFormat()).c_str());
     return;
   }
   field.field_markings_mutex.lockForRead();
   for (size_t i = 0; i < field.field_lines.size(); ++i) {
     const FieldLine& line = *(field.field_lines[i]);
     const GVector::vector3d<double> p1(
         line.p1_x->getDouble(), line.p1_y->getDouble(), 0.0);
     const GVector::vector3d<double> p2(
         line.p2_x->getDouble(), line.p2_y->getDouble(), 0.0);
     detectEdgesOnSingleLine(
         p1, p2, line.thickness->getDouble(), point_separation);
   }
   for (size_t i = 0; i < field.field_arcs.size(); ++i) {
     const FieldCircularArc& arc = *(field.field_arcs[i]);
     const GVector::vector3d<double> center(
         arc.center_x->getDouble(), arc.center_y->getDouble(), 0.0);
     detectEdgesOnSingleArc(center, arc.radius->getDouble(), arc.a1->getDouble(),
         arc.a2->getDouble(), arc.thickness->getDouble(), point_separation);
   }
   field.field_markings_mutex.unlock();
 }
void PluginCameraCalibration::detectEdgesOnSingleArc (const GVector::vector3d< double > & center, double radius, double theta1, double theta2, double thickness, double point_separation) protected
Definition at line 206 of file plugin_cameracalib.cpp.
References CameraParameters::additional_calibration_information, CameraParameters::CalibrationData::alphas, CameraParameters::calibrationSegments, camera_parameters, CameraParameters::CalibrationData::center, Sobel::centerOfLine(), CameraParameters::field2image(), CameraParameters::getWorldLocation(), grey_image, velocity.pid_::i, CameraParameters::CalibrationData::imgPts, radius, CameraParameters::CalibrationData::radius, sanitizeSobel(), CameraParameters::CalibrationData::straightLine, bot_comm::theta, CameraParameters::CalibrationData::theta1, CameraParameters::CalibrationData::theta2, GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
Referenced by detectEdges().
{
   static const int kSobelThreshold = 20;
   const double search_distance =
       camera_parameters.additional_calibration_information->
       line_search_corridor_width->getDouble() / 2.0;
   const double image_boundary =
       camera_parameters.additional_calibration_information->
       image_boundary->getDouble();
   const double max_feature_distance =
       camera_parameters.additional_calibration_information->
       max_feature_distance->getDouble();
   CameraParameters::CalibrationData calibration_data;
   calibration_data.straightLine = false;
   calibration_data.radius = radius;
   calibration_data.center = center;
   calibration_data.theta1 = theta1;
   calibration_data.theta2 = theta2;
   const int num_points =
       floor((theta2 - theta1) * radius / point_separation - 1.0);
   for (int i = 1; i <= num_points; ++i) {
     const double alpha =
         1.0 - static_cast<double>(i) / (static_cast<double>(num_points) + 1.0);
     const double theta = alpha * theta1 + (1.0 - alpha) * theta2;
     const GVector::vector3d<double> radius_vector(cos(theta), sin(theta), 0.0);
     const GVector::vector3d<double> p_world = center + radius * radius_vector;
     GVector::vector2d<double> p_image(0.0, 0.0);
     camera_parameters.field2image(p_world, p_image);
     if (p_image.x < image_boundary ||
         p_image.x > grey_image->getWidth() - image_boundary ||
         p_image.y < image_boundary ||
         p_image.y > grey_image->getHeight() - image_boundary) {
       // This edge feature is outside the image boundary, so ignore it since
       // the edge detection might not be accurate.
       continue;
     }
     if ((p_world - camera_parameters.getWorldLocation()).length() >
        max_feature_distance) {
       // This edge feature too far away from the camera, so ignore it since the
       // line feature is likely to be too small to detect accurately.
       continue;
     }
     const GVector::vector3d<double> start_world =
         center + (radius - 0.5 * thickness - search_distance) * radius_vector;
     const GVector::vector3d<double> end_world =
         center + (radius + 0.5 * thickness + search_distance) * radius_vector;
     GVector::vector2d<double> start_image(0.0, 0.0), end_image(0.0, 0.0);
     camera_parameters.field2image(start_world, start_image);
     camera_parameters.field2image(end_world, end_image);
     sanitizeSobel(grey_image, start_image);
     sanitizeSobel(grey_image, end_image);
     GVector::vector2d<double> point_image;
     bool center_found = false;
     Sobel::centerOfLine(
         *grey_image, start_image.x, end_image.x, start_image.y,
         end_image.y, point_image, center_found, kSobelThreshold);
     calibration_data.imgPts.push_back(std::make_pair(point_image,center_found));
     calibration_data.alphas.push_back(alpha);
   }
   if (calibration_data.imgPts.size() > 3) {
     // Need at least three points to uniquely define a circular arc.
     camera_parameters.calibrationSegments.push_back(calibration_data);
   }
 }
void PluginCameraCalibration::detectEdgesOnSingleLine (const GVector::vector3d< double > & p1, const GVector::vector3d< double > & p2, double thickness, double point_separation) protected
Definition at line 140 of file plugin_cameracalib.cpp.
References CameraParameters::additional_calibration_information, CameraParameters::CalibrationData::alphas, CameraParameters::calibrationSegments, camera_parameters, Sobel::centerOfLine(), CameraParameters::field2image(), CameraParameters::getWorldLocation(), grey_image, velocity.pid_::i, CameraParameters::CalibrationData::imgPts, CameraParameters::CalibrationData::p1, CameraParameters::CalibrationData::p2, sanitizeSobel(), CameraParameters::CalibrationData::straightLine, GVector::vector3d< num >::x, and GVector::vector3d< num >::y.
Referenced by detectEdges().
{
   static const int kSobelThreshold = 20;
   const double search_distance =
       camera_parameters.additional_calibration_information->
       line_search_corridor_width->getDouble() / 2.0;
   const double image_boundary =
       camera_parameters.additional_calibration_information->
       image_boundary->getDouble();
   const double max_feature_distance =
       camera_parameters.additional_calibration_information->
       max_feature_distance->getDouble();
   CameraParameters::CalibrationData calibration_data;
   calibration_data.straightLine = true;
   calibration_data.p1 = p1;
   calibration_data.p2 = p2;
   const double line_length = (p2 - p1).length();
   const GVector::vector3d<double> line_dir = (p2 - p1) / line_length;
   const GVector::vector3d<double> line_perp(-line_dir.y, line_dir.x, 0.0);
   const int num_points = floor(line_length / point_separation - 1.0);
   for (int i = 1; i <= num_points; ++i) {
     const double alpha =
         1.0 - static_cast<double>(i) / (static_cast<double>(num_points) + 1.0);
     const GVector::vector3d<double> p_world = alpha * p1 + (1.0 - alpha) * p2;
     GVector::vector2d<double> p_image(0.0, 0.0);
         camera_parameters.field2image(p_world, p_image);
     if (p_image.x < image_boundary ||
         p_image.x > grey_image->getWidth() - image_boundary ||
         p_image.y < image_boundary ||
         p_image.y > grey_image->getHeight() - image_boundary) {
       // This edge feature is outside the image boundary, so ignore it since
       // the edge detection might not be accurate.
       continue;
     }
     if ((p_world - camera_parameters.getWorldLocation()).length() >
        max_feature_distance) {
       // This edge feature too far away from the camera, so ignore it since the
       // line feature is likely to be too small to detect accurately.
       continue;
     }
     const GVector::vector3d<double> start_world =
         p_world + line_perp * (0.5 * thickness + search_distance);
     const GVector::vector3d<double> end_world =
         p_world - line_perp * (0.5 * thickness + search_distance);
     GVector::vector2d<double> start_image(0.0, 0.0), end_image(0.0, 0.0);
     camera_parameters.field2image(start_world, start_image);
     camera_parameters.field2image(end_world, end_image);
     sanitizeSobel(grey_image, start_image);
     sanitizeSobel(grey_image, end_image);
     GVector::vector2d<double> point_image;
     bool center_found = false;
     Sobel::centerOfLine(
         *grey_image, start_image.x, end_image.x, start_image.y,
         end_image.y, point_image, center_found, kSobelThreshold);
     calibration_data.imgPts.push_back(std::make_pair(point_image,center_found));
     calibration_data.alphas.push_back(alpha);
   }
   if (calibration_data.imgPts.size() > 2) {
     // Need at least two points to uniquely define a line segment.
     camera_parameters.calibrationSegments.push_back(calibration_data);
   }
 }
QWidget * PluginCameraCalibration::getControlWidget () virtual
Reimplemented from VisionPlugin.
Definition at line 127 of file plugin_cameracalib.cpp.
References camera_parameters, and ccw.
{
   if (ccw==0)
     ccw = new CameraCalibrationWidget(camera_parameters);
   return (QWidget *)ccw;
 }
string PluginCameraCalibration::getName () virtual
Reimplemented from VisionPlugin.
Definition at line 123 of file plugin_cameracalib.cpp.
{
   return "Camera Calibration";
 }
VarList * PluginCameraCalibration::getSettings () virtual
Reimplemented from VisionPlugin.
Definition at line 119 of file plugin_cameracalib.cpp.
References settings.
{
   return settings;
 }
void PluginCameraCalibration::keyPressEvent (QKeyEvent * event) virtual
Reimplemented from VisionPlugin.
Definition at line 279 of file plugin_cameracalib.cpp.
 {
   (void) event;
 }
void PluginCameraCalibration::mouseEvent (QMouseEvent * event, pixelloc loc) protected
Definition at line 273 of file plugin_cameracalib.cpp.
 {
   (void) event;
   (void) loc;
 }
void PluginCameraCalibration::mouseMoveEvent (QMouseEvent * event, pixelloc loc) virtual
Reimplemented from VisionPlugin.
Definition at line 334 of file plugin_cameracalib.cpp.
References ccw, doing_drag, drag_x, drag_y, VarTypes::VarDouble::setDouble(), video_height, video_width, pixelloc::x, and pixelloc::y.
 {
   QTabWidget* tabw = (QTabWidget*) ccw->parentWidget()->parentWidget();
   if (doing_drag && tabw->currentWidget() == ccw && (event->buttons() & Qt::LeftButton)!=0)
   {
     if (loc.x < 0) loc.x=0;
     if (loc.y < 0) loc.y=0;
     if (video_width > 0 && loc.x >= video_width) loc.x=video_width-1;
     if (video_height > 0 && loc.y >= video_height) loc.y=video_height-1;
     drag_x->setDouble(loc.x);
     drag_y->setDouble(loc.y);
     event->accept();
   }
   else
     event->ignore();
 }
void PluginCameraCalibration::mousePressEvent (QMouseEvent * event, pixelloc loc) virtual
Reimplemented from VisionPlugin.
Definition at line 284 of file plugin_cameracalib.cpp.
References CameraParameters::additional_calibration_information, camera_parameters, ccw, doing_drag, drag_x, drag_y, velocity.pid_::i, CameraParameters::AdditionalCalibrationInformation::kNumControlPoints, pixelloc::x, and pixelloc::y.
 {
   QTabWidget* tabw = (QTabWidget*) ccw->parentWidget()->parentWidget();
   double drag_threshold = 20; //in px
   if (tabw->currentWidget() == ccw && (event->buttons() & Qt::LeftButton)!=0) {
     drag_x = 0;
     drag_y = 0;
     for (int i = 0;
         i < CameraParameters::AdditionalCalibrationInformation::kNumControlPoints;
         ++i) {
       const double x_diff =
           camera_parameters.additional_calibration_information->
               control_point_image_xs[i]->getDouble() - loc.x;
       const double y_diff =
           camera_parameters.additional_calibration_information->
               control_point_image_ys[i]->getDouble() - loc.y;
       if (sqrt(x_diff*x_diff + y_diff*y_diff) < drag_threshold) {
         drag_x = camera_parameters.additional_calibration_information->
             control_point_image_xs[i];
         drag_y = camera_parameters.additional_calibration_information->
             control_point_image_ys[i];
         break;
       }
     }
     if (drag_x != 0 && drag_y != 0)
     {
       event->accept();
       doing_drag = true;
     }
     else
       event->ignore();
   } else {
     event->ignore();
   }
 }
void PluginCameraCalibration::mouseReleaseEvent (QMouseEvent * event, pixelloc loc) virtual
Reimplemented from VisionPlugin.
Definition at line 321 of file plugin_cameracalib.cpp.
References ccw, and doing_drag.
 {
   (void)loc;
   QTabWidget* tabw = (QTabWidget*) ccw->parentWidget()->parentWidget();
   if (tabw->currentWidget() == ccw)
   {
     doing_drag =false;
     event->accept();
   }
   else
     event->ignore();
 }
ProcessResult PluginCameraCalibration::process (FrameData * data, RenderOptions * options) virtual
Reimplemented from VisionPlugin.
Definition at line 103 of file plugin_cameracalib.cpp.
References ccw, detectEdges(), CameraCalibrationWidget::getDetectEdges(), RawImage::getHeight(), RawImage::getWidth(), ProcessingOk, CameraCalibrationWidget::resetDetectEdges(), CameraCalibrationWidget::set_slider_from_vars(), FrameData::video, video_height, and video_width.
{
   video_width=data->video.getWidth();
   video_height=data->video.getHeight();
   (void)options;
   if(ccw) {
     if(ccw->getDetectEdges()) {
       detectEdges(data);
       // detectEdges2(data);
       ccw->resetDetectEdges();
     }
     ccw->set_slider_from_vars();
   }
   return ProcessingOk;
 }
void PluginCameraCalibration::sanitizeSobel (greyImage * img, GVector::vector2d< double > & val, int sobel_border = 1) protected
Definition at line 134 of file plugin_cameracalib.cpp.
References GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
Referenced by detectEdgesOnSingleArc(), and detectEdgesOnSingleLine().
{
   val.x = bound<double>(val.x, sobel_border, img->getWidth() - sobel_border);
   val.y = bound<double>(val.y, sobel_border, img->getHeight() - sobel_border);
 }
Field Documentation
VarList* PluginCameraCalibration::calibration_settings protected
Definition at line 40 of file plugin_cameracalib.h.
Referenced by PluginCameraCalibration(), and ~PluginCameraCalibration().
CameraParameters& PluginCameraCalibration::camera_parameters protected
Definition at line 41 of file plugin_cameracalib.h.
Referenced by detectEdges(), detectEdgesOnSingleArc(), detectEdgesOnSingleLine(), getControlWidget(), mousePressEvent(), and PluginCameraCalibration().
VarList* PluginCameraCalibration::camera_settings protected
Definition at line 39 of file plugin_cameracalib.h.
Referenced by PluginCameraCalibration(), and ~PluginCameraCalibration().
CameraCalibrationWidget* PluginCameraCalibration::ccw protected
Definition at line 43 of file plugin_cameracalib.h.
Referenced by getControlWidget(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and process().
bool PluginCameraCalibration::doing_drag protected
Definition at line 50 of file plugin_cameracalib.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
VarDouble* PluginCameraCalibration::drag_x protected
Definition at line 51 of file plugin_cameracalib.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
VarDouble* PluginCameraCalibration::drag_y protected
Definition at line 52 of file plugin_cameracalib.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
RoboCupField& PluginCameraCalibration::field protected
Definition at line 42 of file plugin_cameracalib.h.
Referenced by detectEdges().
greyImage* PluginCameraCalibration::grey_image protected
Definition at line 44 of file plugin_cameracalib.h.
Referenced by detectEdges(), detectEdgesOnSingleArc(), detectEdgesOnSingleLine(), and ~PluginCameraCalibration().
rgbImage* PluginCameraCalibration::rgb_image protected
Definition at line 45 of file plugin_cameracalib.h.
Referenced by detectEdges(), and ~PluginCameraCalibration().
VarList* PluginCameraCalibration::settings protected
Definition at line 38 of file plugin_cameracalib.h.
Referenced by getSettings(), and PluginCameraCalibration().
int PluginCameraCalibration::video_height protected
Definition at line 47 of file plugin_cameracalib.h.
Referenced by mouseMoveEvent(), PluginCameraCalibration(), and process().
int PluginCameraCalibration::video_width protected
Definition at line 46 of file plugin_cameracalib.h.
Referenced by mouseMoveEvent(), PluginCameraCalibration(), and process().
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/plugin_cameracalib.h
ssl-vision/src/app/plugins/plugin_cameracalib.cpp