Documentation: ImageInterface Class Reference
ImageInterface Class Reference abstract
#include <image_interface.h>
Public Member Functions
virtual int getWidth () const =0
virtual int getHeight () const =0
virtual ColorFormat getColorFormat () const =0
virtual unsigned char * getData () const =0
virtual int getNumBytes () const =0
virtual int getNumPixels () const =0
virtual ~ImageInterface ()
Detailed Description
Definition at line 25 of file image_interface.h.
Constructor & Destructor Documentation
virtual ImageInterface::~ImageInterface () inline virtual
Definition at line 34 of file image_interface.h.
 {};
Member Function Documentation
virtual ColorFormat ImageInterface::getColorFormat () const pure virtual
Implemented in Image< PIXEL >, Image< ColorGrey< uint8_t, COLOR_RAW8 > >, Image< rgb >, and RawImage.
Referenced by CMVisionThreshold::thresholdImageRGB(), and CMVisionThreshold::thresholdImageYUV444().
virtual unsigned char* ImageInterface::getData () const pure virtual
Implemented in Image< PIXEL >, Image< ColorGrey< uint8_t, COLOR_RAW8 > >, Image< rgb >, and RawImage.
Referenced by CMVisionThreshold::thresholdImageRGB(), and CMVisionThreshold::thresholdImageYUV444().
virtual int ImageInterface::getHeight () const pure virtual
Implemented in Image< PIXEL >, Image< ColorGrey< uint8_t, COLOR_RAW8 > >, Image< rgb >, and RawImage.
Referenced by CMVision::ImageProcessor::processYUV444(), CMVisionThreshold::thresholdImageRGB(), and CMVisionThreshold::thresholdImageYUV444().
virtual int ImageInterface::getNumBytes () const pure virtual
Implemented in Image< PIXEL >, Image< ColorGrey< uint8_t, COLOR_RAW8 > >, Image< rgb >, and RawImage.
virtual int ImageInterface::getNumPixels () const pure virtual
Implemented in Image< PIXEL >, Image< ColorGrey< uint8_t, COLOR_RAW8 > >, Image< rgb >, and RawImage.
Referenced by CMVisionThreshold::thresholdImageRGB(), and CMVisionThreshold::thresholdImageYUV444().
virtual int ImageInterface::getWidth () const pure virtual
Implemented in Image< PIXEL >, Image< ColorGrey< uint8_t, COLOR_RAW8 > >, Image< rgb >, and RawImage.
Referenced by CMVision::ImageProcessor::processYUV444(), CMVisionThreshold::thresholdImageRGB(), and CMVisionThreshold::thresholdImageYUV444().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/image_interface.h