Documentation: grSim_Robot_Command Class Reference
grSim_Robot_Command Class Reference
#include <grSim_Commands.pb.h>
Public Member Functions
grSim_Robot_Command ()
virtual ~grSim_Robot_Command ()
grSim_Robot_Command (const grSim_Robot_Command &from)
grSim_Robot_Command & operator= (const grSim_Robot_Command &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (grSim_Robot_Command *other)
grSim_Robot_Command * New () const PROTOBUF_FINAL
grSim_Robot_Command * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const grSim_Robot_Command &from)
void MergeFrom (const grSim_Robot_Command &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_id () const
void clear_id ()
::google::protobuf::uint32 id () const
void set_id (::google::protobuf::uint32 value)
bool has_kickspeedx () const
void clear_kickspeedx ()
float kickspeedx () const
void set_kickspeedx (float value)
bool has_kickspeedz () const
void clear_kickspeedz ()
float kickspeedz () const
void set_kickspeedz (float value)
bool has_veltangent () const
void clear_veltangent ()
float veltangent () const
void set_veltangent (float value)
bool has_velnormal () const
void clear_velnormal ()
float velnormal () const
void set_velnormal (float value)
bool has_velangular () const
void clear_velangular ()
float velangular () const
void set_velangular (float value)
bool has_spinner () const
void clear_spinner ()
bool spinner () const
void set_spinner (bool value)
bool has_wheelsspeed () const
void clear_wheelsspeed ()
bool wheelsspeed () const
void set_wheelsspeed (bool value)
bool has_wheel1 () const
void clear_wheel1 ()
float wheel1 () const
void set_wheel1 (float value)
bool has_wheel2 () const
void clear_wheel2 ()
float wheel2 () const
void set_wheel2 (float value)
bool has_wheel3 () const
void clear_wheel3 ()
float wheel3 () const
void set_wheel3 (float value)
bool has_wheel4 () const
void clear_wheel4 ()
float wheel4 () const
void set_wheel4 (float value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const grSim_Robot_Command & default_instance ()
static const grSim_Robot_Command * internal_default_instance ()
Static Public Attributes
static const int kIdFieldNumber = 1
static const int kKickspeedxFieldNumber = 2
static const int kKickspeedzFieldNumber = 3
static const int kVeltangentFieldNumber = 4
static const int kVelnormalFieldNumber = 5
static const int kVelangularFieldNumber = 6
static const int kSpinnerFieldNumber = 7
static const int kWheelsspeedFieldNumber = 8
static const int kWheel1FieldNumber = 9
static const int kWheel2FieldNumber = 10
static const int kWheel3FieldNumber = 11
static const int kWheel4FieldNumber = 12
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (grSim_Robot_Command *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_id ()
void clear_has_id ()
void set_has_kickspeedx ()
void clear_has_kickspeedx ()
void set_has_kickspeedz ()
void clear_has_kickspeedz ()
void set_has_veltangent ()
void clear_has_veltangent ()
void set_has_velnormal ()
void clear_has_velnormal ()
void set_has_velangular ()
void clear_has_velangular ()
void set_has_spinner ()
void clear_has_spinner ()
void set_has_wheelsspeed ()
void clear_has_wheelsspeed ()
void set_has_wheel1 ()
void clear_has_wheel1 ()
void set_has_wheel2 ()
void clear_has_wheel2 ()
void set_has_wheel3 ()
void clear_has_wheel3 ()
void set_has_wheel4 ()
void clear_has_wheel4 ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_grSim_5fCommands_2eproto ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::uint32 id_
float kickspeedx_
float kickspeedz_
float veltangent_
float velnormal_
float velangular_
bool spinner_
bool wheelsspeed_
float wheel1_
float wheel2_
float wheel3_
float wheel4_
Friends
void protobuf_InitDefaults_grSim_5fCommands_2eproto_impl ()
void protobuf_AddDesc_grSim_5fCommands_2eproto_impl ()
void protobuf_ShutdownFile_grSim_5fCommands_2eproto ()
Detailed Description
Definition at line 44 of file grSim_Commands.pb.h.
Constructor & Destructor Documentation
grSim_Robot_Command::grSim_Robot_Command ()
virtual grSim_Robot_Command::~grSim_Robot_Command () virtual
grSim_Robot_Command::grSim_Robot_Command (const grSim_Robot_Command & from)
Member Function Documentation
size_t grSim_Robot_Command::ByteSizeLong () const
Referenced by New(), and grSim_Commands::New().
void grSim_Robot_Command::Clear ()
Referenced by New(), and grSim_Commands::New().
void grSim_Robot_Command::clear_has_id () inline private
Definition at line 392 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by clear_id().
{
   _has_bits_[0] &= ~0x00000001u;
 }
void grSim_Robot_Command::clear_has_kickspeedx () inline private
Definition at line 416 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by clear_kickspeedx().
{
   _has_bits_[0] &= ~0x00000002u;
 }
void grSim_Robot_Command::clear_has_kickspeedz () inline private
Definition at line 440 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by clear_kickspeedz().
{
   _has_bits_[0] &= ~0x00000004u;
 }
void grSim_Robot_Command::clear_has_spinner () inline private
Definition at line 536 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by clear_spinner().
{
   _has_bits_[0] &= ~0x00000040u;
 }
void grSim_Robot_Command::clear_has_velangular () inline private
Definition at line 512 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by clear_velangular().
{
   _has_bits_[0] &= ~0x00000020u;
 }
void grSim_Robot_Command::clear_has_velnormal () inline private
Definition at line 488 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by clear_velnormal().
{
   _has_bits_[0] &= ~0x00000010u;
 }
void grSim_Robot_Command::clear_has_veltangent () inline private
Definition at line 464 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by clear_veltangent().
{
   _has_bits_[0] &= ~0x00000008u;
 }
void grSim_Robot_Command::clear_has_wheel1 () inline private
Definition at line 584 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by clear_wheel1().
{
   _has_bits_[0] &= ~0x00000100u;
 }
void grSim_Robot_Command::clear_has_wheel2 () inline private
Definition at line 608 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by clear_wheel2().
{
   _has_bits_[0] &= ~0x00000200u;
 }
void grSim_Robot_Command::clear_has_wheel3 () inline private
Definition at line 632 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by clear_wheel3().
{
   _has_bits_[0] &= ~0x00000400u;
 }
void grSim_Robot_Command::clear_has_wheel4 () inline private
Definition at line 656 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by clear_wheel4().
{
   _has_bits_[0] &= ~0x00000800u;
 }
void grSim_Robot_Command::clear_has_wheelsspeed () inline private
Definition at line 560 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by clear_wheelsspeed().
{
   _has_bits_[0] &= ~0x00000080u;
 }
void grSim_Robot_Command::clear_id () inline
Definition at line 395 of file grSim_Commands.pb.h.
References clear_has_id(), and id_.
Referenced by MaybeArenaPtr().
{
   id_ = 0u;
   clear_has_id();
 }
void grSim_Robot_Command::clear_kickspeedx () inline
Definition at line 419 of file grSim_Commands.pb.h.
References clear_has_kickspeedx(), and kickspeedx_.
{
   kickspeedx_ = 0;
   clear_has_kickspeedx();
 }
void grSim_Robot_Command::clear_kickspeedz () inline
Definition at line 443 of file grSim_Commands.pb.h.
References clear_has_kickspeedz(), and kickspeedz_.
{
   kickspeedz_ = 0;
   clear_has_kickspeedz();
 }
void grSim_Robot_Command::clear_spinner () inline
Definition at line 539 of file grSim_Commands.pb.h.
References clear_has_spinner(), and spinner_.
{
   spinner_ = false;
   clear_has_spinner();
 }
void grSim_Robot_Command::clear_velangular () inline
Definition at line 515 of file grSim_Commands.pb.h.
References clear_has_velangular(), and velangular_.
{
   velangular_ = 0;
   clear_has_velangular();
 }
void grSim_Robot_Command::clear_velnormal () inline
Definition at line 491 of file grSim_Commands.pb.h.
References clear_has_velnormal(), and velnormal_.
{
   velnormal_ = 0;
   clear_has_velnormal();
 }
void grSim_Robot_Command::clear_veltangent () inline
Definition at line 467 of file grSim_Commands.pb.h.
References clear_has_veltangent(), and veltangent_.
{
   veltangent_ = 0;
   clear_has_veltangent();
 }
void grSim_Robot_Command::clear_wheel1 () inline
Definition at line 587 of file grSim_Commands.pb.h.
References clear_has_wheel1(), and wheel1_.
{
   wheel1_ = 0;
   clear_has_wheel1();
 }
void grSim_Robot_Command::clear_wheel2 () inline
Definition at line 611 of file grSim_Commands.pb.h.
References clear_has_wheel2(), and wheel2_.
{
   wheel2_ = 0;
   clear_has_wheel2();
 }
void grSim_Robot_Command::clear_wheel3 () inline
Definition at line 635 of file grSim_Commands.pb.h.
References clear_has_wheel3(), and wheel3_.
{
   wheel3_ = 0;
   clear_has_wheel3();
 }
void grSim_Robot_Command::clear_wheel4 () inline
Definition at line 659 of file grSim_Commands.pb.h.
References clear_has_wheel4(), and wheel4_.
{
   wheel4_ = 0;
   clear_has_wheel4();
 }
void grSim_Robot_Command::clear_wheelsspeed () inline
Definition at line 563 of file grSim_Commands.pb.h.
References clear_has_wheelsspeed(), and wheelsspeed_.
{
   wheelsspeed_ = false;
   clear_has_wheelsspeed();
 }
void grSim_Robot_Command::CopyFrom (const ::google::protobuf::Message & from)
Referenced by New(), grSim_Commands::New(), operator=(), and grSim_Commands::operator=().
void grSim_Robot_Command::CopyFrom (const grSim_Robot_Command & from)
static const grSim_Robot_Command& grSim_Robot_Command::default_instance () static
Referenced by mutable_unknown_fields(), and grSim_Commands::mutable_unknown_fields().
static const ::google::protobuf::Descriptor* grSim_Robot_Command::descriptor () static
Referenced by mutable_unknown_fields(), and grSim_Commands::mutable_unknown_fields().
inline ::google::protobuf::Arena* grSim_Robot_Command::GetArenaNoVirtual () const inline private
Definition at line 104 of file grSim_Commands.pb.h.
{
     return NULL;
   }
int grSim_Robot_Command::GetCachedSize () const inline
Definition at line 97 of file grSim_Commands.pb.h.
References _cached_size_, InternalSwap(), SetCachedSize(), SharedCtor(), and SharedDtor().
 { return _cached_size_; }
::google::protobuf::Metadata grSim_Robot_Command::GetMetadata () const
Referenced by MaybeArenaPtr(), and grSim_Commands::MaybeArenaPtr().
bool grSim_Robot_Command::has_id () const inline
Definition at line 386 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by MaybeArenaPtr(), and SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool grSim_Robot_Command::has_kickspeedx () const inline
Definition at line 410 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool grSim_Robot_Command::has_kickspeedz () const inline
Definition at line 434 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool grSim_Robot_Command::has_spinner () const inline
Definition at line 530 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000040u) != 0;
 }
bool grSim_Robot_Command::has_velangular () const inline
Definition at line 506 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000020u) != 0;
 }
bool grSim_Robot_Command::has_velnormal () const inline
Definition at line 482 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
bool grSim_Robot_Command::has_veltangent () const inline
Definition at line 458 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool grSim_Robot_Command::has_wheel1 () const inline
Definition at line 578 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000100u) != 0;
 }
bool grSim_Robot_Command::has_wheel2 () const inline
Definition at line 602 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000200u) != 0;
 }
bool grSim_Robot_Command::has_wheel3 () const inline
Definition at line 626 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000400u) != 0;
 }
bool grSim_Robot_Command::has_wheel4 () const inline
Definition at line 650 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000800u) != 0;
 }
bool grSim_Robot_Command::has_wheelsspeed () const inline
Definition at line 554 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000080u) != 0;
 }
google::protobuf::uint32 grSim_Robot_Command::id () const inline
Definition at line 399 of file grSim_Commands.pb.h.
References id_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Robot_Command.id)
   return id_;
 }
static const grSim_Robot_Command* grSim_Robot_Command::internal_default_instance () inline static
Definition at line 67 of file grSim_Commands.pb.h.
References _grSim_Robot_Command_default_instance_, and Swap().
{
     return reinterpret_cast<const grSim_Robot_Command*>(
                &_grSim_Robot_Command_default_instance_);
   }
::google::protobuf::uint8* grSim_Robot_Command::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
Referenced by New(), grSim_Commands::New(), SerializeWithCachedSizesToArray(), and grSim_Commands::SerializeWithCachedSizesToArray().
void grSim_Robot_Command::InternalSwap (grSim_Robot_Command * other) private
Referenced by GetCachedSize(), and grSim_Commands::GetCachedSize().
bool grSim_Robot_Command::IsInitialized () const
Referenced by New(), and grSim_Commands::New().
float grSim_Robot_Command::kickspeedx () const inline
Definition at line 423 of file grSim_Commands.pb.h.
References kickspeedx_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Robot_Command.kickspeedx)
   return kickspeedx_;
 }
float grSim_Robot_Command::kickspeedz () const inline
Definition at line 447 of file grSim_Commands.pb.h.
References kickspeedz_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Robot_Command.kickspeedz)
   return kickspeedz_;
 }
void* grSim_Robot_Command::MaybeArenaPtr () const inline private
Definition at line 107 of file grSim_Commands.pb.h.
References clear_id(), GetMetadata(), and has_id().
{
     return NULL;
   }
void grSim_Robot_Command::MergeFrom (const ::google::protobuf::Message & from)
Referenced by New(), and grSim_Commands::New().
void grSim_Robot_Command::MergeFrom (const grSim_Robot_Command & from)
bool grSim_Robot_Command::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Referenced by New(), and grSim_Commands::New().
inline ::google::protobuf::UnknownFieldSet* grSim_Robot_Command::mutable_unknown_fields () inline
Definition at line 60 of file grSim_Commands.pb.h.
References _internal_metadata_, default_instance(), and descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
grSim_Robot_Command* grSim_Robot_Command::New () const inline
Definition at line 76 of file grSim_Commands.pb.h.
References ByteSizeLong(), Clear(), CopyFrom(), InternalSerializeWithCachedSizesToArray(), IsInitialized(), MergeFrom(), MergePartialFromCodedStream(), New(), SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New(), and grSim_Commands::New().
 { return New(NULL); }
grSim_Robot_Command* grSim_Robot_Command::New (::google::protobuf::Arena * arena) const
grSim_Robot_Command& grSim_Robot_Command::operator= (const grSim_Robot_Command & from) inline
Definition at line 51 of file grSim_Commands.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* grSim_Robot_Command::protobuf_Offsets_grSim_5fCommands_2eproto () private
size_t grSim_Robot_Command::RequiredFieldsByteSizeFallback () const private
void grSim_Robot_Command::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Referenced by New(), and grSim_Commands::New().
::google::protobuf::uint8* grSim_Robot_Command::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 93 of file grSim_Commands.pb.h.
References InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void grSim_Robot_Command::set_has_id () inline private
Definition at line 389 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by set_id().
{
   _has_bits_[0] |= 0x00000001u;
 }
void grSim_Robot_Command::set_has_kickspeedx () inline private
Definition at line 413 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by set_kickspeedx().
{
   _has_bits_[0] |= 0x00000002u;
 }
void grSim_Robot_Command::set_has_kickspeedz () inline private
Definition at line 437 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by set_kickspeedz().
{
   _has_bits_[0] |= 0x00000004u;
 }
void grSim_Robot_Command::set_has_spinner () inline private
Definition at line 533 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by set_spinner().
{
   _has_bits_[0] |= 0x00000040u;
 }
void grSim_Robot_Command::set_has_velangular () inline private
Definition at line 509 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by set_velangular().
{
   _has_bits_[0] |= 0x00000020u;
 }
void grSim_Robot_Command::set_has_velnormal () inline private
Definition at line 485 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by set_velnormal().
{
   _has_bits_[0] |= 0x00000010u;
 }
void grSim_Robot_Command::set_has_veltangent () inline private
Definition at line 461 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by set_veltangent().
{
   _has_bits_[0] |= 0x00000008u;
 }
void grSim_Robot_Command::set_has_wheel1 () inline private
Definition at line 581 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by set_wheel1().
{
   _has_bits_[0] |= 0x00000100u;
 }
void grSim_Robot_Command::set_has_wheel2 () inline private
Definition at line 605 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by set_wheel2().
{
   _has_bits_[0] |= 0x00000200u;
 }
void grSim_Robot_Command::set_has_wheel3 () inline private
Definition at line 629 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by set_wheel3().
{
   _has_bits_[0] |= 0x00000400u;
 }
void grSim_Robot_Command::set_has_wheel4 () inline private
Definition at line 653 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by set_wheel4().
{
   _has_bits_[0] |= 0x00000800u;
 }
void grSim_Robot_Command::set_has_wheelsspeed () inline private
Definition at line 557 of file grSim_Commands.pb.h.
References _has_bits_.
Referenced by set_wheelsspeed().
{
   _has_bits_[0] |= 0x00000080u;
 }
void grSim_Robot_Command::set_id (::google::protobuf::uint32 value) inline
Definition at line 403 of file grSim_Commands.pb.h.
References id_, and set_has_id().
Referenced by Callback(), CallbackCmd(), and MainWindow::sendPacket().
{
   set_has_id();
   id_ = value;
   // @@protoc_insertion_point(field_set:grSim_Robot_Command.id)
 }
void grSim_Robot_Command::set_kickspeedx (float value) inline
Definition at line 427 of file grSim_Commands.pb.h.
References kickspeedx_, and set_has_kickspeedx().
Referenced by Callback(), CallbackCmd(), and MainWindow::sendPacket().
{
   set_has_kickspeedx();
   kickspeedx_ = value;
   // @@protoc_insertion_point(field_set:grSim_Robot_Command.kickspeedx)
 }
void grSim_Robot_Command::set_kickspeedz (float value) inline
Definition at line 451 of file grSim_Commands.pb.h.
References kickspeedz_, and set_has_kickspeedz().
Referenced by Callback(), CallbackCmd(), and MainWindow::sendPacket().
{
   set_has_kickspeedz();
   kickspeedz_ = value;
   // @@protoc_insertion_point(field_set:grSim_Robot_Command.kickspeedz)
 }
void grSim_Robot_Command::set_spinner (bool value) inline
Definition at line 547 of file grSim_Commands.pb.h.
References set_has_spinner(), and spinner_.
Referenced by Callback(), CallbackCmd(), and MainWindow::sendPacket().
{
   set_has_spinner();
   spinner_ = value;
   // @@protoc_insertion_point(field_set:grSim_Robot_Command.spinner)
 }
void grSim_Robot_Command::set_velangular (float value) inline
Definition at line 523 of file grSim_Commands.pb.h.
References set_has_velangular(), and velangular_.
Referenced by Callback(), CallbackCmd(), and MainWindow::sendPacket().
{
   set_has_velangular();
   velangular_ = value;
   // @@protoc_insertion_point(field_set:grSim_Robot_Command.velangular)
 }
void grSim_Robot_Command::set_velnormal (float value) inline
Definition at line 499 of file grSim_Commands.pb.h.
References set_has_velnormal(), and velnormal_.
Referenced by Callback(), CallbackCmd(), and MainWindow::sendPacket().
{
   set_has_velnormal();
   velnormal_ = value;
   // @@protoc_insertion_point(field_set:grSim_Robot_Command.velnormal)
 }
void grSim_Robot_Command::set_veltangent (float value) inline
Definition at line 475 of file grSim_Commands.pb.h.
References set_has_veltangent(), and veltangent_.
Referenced by Callback(), CallbackCmd(), and MainWindow::sendPacket().
{
   set_has_veltangent();
   veltangent_ = value;
   // @@protoc_insertion_point(field_set:grSim_Robot_Command.veltangent)
 }
void grSim_Robot_Command::set_wheel1 (float value) inline
Definition at line 595 of file grSim_Commands.pb.h.
References set_has_wheel1(), and wheel1_.
Referenced by Callback(), and MainWindow::sendPacket().
{
   set_has_wheel1();
   wheel1_ = value;
   // @@protoc_insertion_point(field_set:grSim_Robot_Command.wheel1)
 }
void grSim_Robot_Command::set_wheel2 (float value) inline
Definition at line 619 of file grSim_Commands.pb.h.
References set_has_wheel2(), and wheel2_.
Referenced by Callback(), and MainWindow::sendPacket().
{
   set_has_wheel2();
   wheel2_ = value;
   // @@protoc_insertion_point(field_set:grSim_Robot_Command.wheel2)
 }
void grSim_Robot_Command::set_wheel3 (float value) inline
Definition at line 643 of file grSim_Commands.pb.h.
References set_has_wheel3(), and wheel3_.
Referenced by Callback(), and MainWindow::sendPacket().
{
   set_has_wheel3();
   wheel3_ = value;
   // @@protoc_insertion_point(field_set:grSim_Robot_Command.wheel3)
 }
void grSim_Robot_Command::set_wheel4 (float value) inline
Definition at line 667 of file grSim_Commands.pb.h.
References set_has_wheel4(), and wheel4_.
Referenced by Callback(), and MainWindow::sendPacket().
{
   set_has_wheel4();
   wheel4_ = value;
   // @@protoc_insertion_point(field_set:grSim_Robot_Command.wheel4)
 }
void grSim_Robot_Command::set_wheelsspeed (bool value) inline
Definition at line 571 of file grSim_Commands.pb.h.
References set_has_wheelsspeed(), and wheelsspeed_.
Referenced by Callback(), CallbackCmd(), and MainWindow::sendPacket().
{
   set_has_wheelsspeed();
   wheelsspeed_ = value;
   // @@protoc_insertion_point(field_set:grSim_Robot_Command.wheelsspeed)
 }
void grSim_Robot_Command::SetCachedSize (int size) const private
Referenced by GetCachedSize(), and grSim_Commands::GetCachedSize().
void grSim_Robot_Command::SharedCtor () private
Referenced by GetCachedSize(), and grSim_Commands::GetCachedSize().
void grSim_Robot_Command::SharedDtor () private
Referenced by GetCachedSize(), and grSim_Commands::GetCachedSize().
bool grSim_Robot_Command::spinner () const inline
Definition at line 543 of file grSim_Commands.pb.h.
References spinner_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Robot_Command.spinner)
   return spinner_;
 }
void grSim_Robot_Command::Swap (grSim_Robot_Command * other)
Referenced by internal_default_instance(), and grSim_Commands::internal_default_instance().
const ::google::protobuf::UnknownFieldSet& grSim_Robot_Command::unknown_fields () const inline
Definition at line 56 of file grSim_Commands.pb.h.
References _internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
float grSim_Robot_Command::velangular () const inline
Definition at line 519 of file grSim_Commands.pb.h.
References velangular_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Robot_Command.velangular)
   return velangular_;
 }
float grSim_Robot_Command::velnormal () const inline
Definition at line 495 of file grSim_Commands.pb.h.
References velnormal_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Robot_Command.velnormal)
   return velnormal_;
 }
float grSim_Robot_Command::veltangent () const inline
Definition at line 471 of file grSim_Commands.pb.h.
References veltangent_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Robot_Command.veltangent)
   return veltangent_;
 }
float grSim_Robot_Command::wheel1 () const inline
Definition at line 591 of file grSim_Commands.pb.h.
References wheel1_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Robot_Command.wheel1)
   return wheel1_;
 }
float grSim_Robot_Command::wheel2 () const inline
Definition at line 615 of file grSim_Commands.pb.h.
References wheel2_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Robot_Command.wheel2)
   return wheel2_;
 }
float grSim_Robot_Command::wheel3 () const inline
Definition at line 639 of file grSim_Commands.pb.h.
References wheel3_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Robot_Command.wheel3)
   return wheel3_;
 }
float grSim_Robot_Command::wheel4 () const inline
Definition at line 663 of file grSim_Commands.pb.h.
References wheel4_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Robot_Command.wheel4)
   return wheel4_;
 }
bool grSim_Robot_Command::wheelsspeed () const inline
Definition at line 567 of file grSim_Commands.pb.h.
References wheelsspeed_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Robot_Command.wheelsspeed)
   return wheelsspeed_;
 }
Friends And Related Function Documentation
void protobuf_AddDesc_grSim_5fCommands_2eproto_impl () friend
void protobuf_InitDefaults_grSim_5fCommands_2eproto_impl () friend
void protobuf_ShutdownFile_grSim_5fCommands_2eproto () friend
Field Documentation
int grSim_Robot_Command::_cached_size_ mutable private
Definition at line 234 of file grSim_Commands.pb.h.
Referenced by GetCachedSize(), and grSim_Commands::GetCachedSize().
::google::protobuf::internal::HasBits<1> grSim_Robot_Command::_has_bits_ private
Definition at line 233 of file grSim_Commands.pb.h.
Referenced by clear_has_id(), grSim_Commands::clear_has_isteamyellow(), clear_has_kickspeedx(), clear_has_kickspeedz(), clear_has_spinner(), grSim_Commands::clear_has_timestamp(), clear_has_velangular(), clear_has_velnormal(), clear_has_veltangent(), clear_has_wheel1(), clear_has_wheel2(), clear_has_wheel3(), clear_has_wheel4(), clear_has_wheelsspeed(), has_id(), grSim_Commands::has_isteamyellow(), has_kickspeedx(), has_kickspeedz(), has_spinner(), grSim_Commands::has_timestamp(), has_velangular(), has_velnormal(), has_veltangent(), has_wheel1(), has_wheel2(), has_wheel3(), has_wheel4(), has_wheelsspeed(), set_has_id(), grSim_Commands::set_has_isteamyellow(), set_has_kickspeedx(), set_has_kickspeedz(), set_has_spinner(), grSim_Commands::set_has_timestamp(), set_has_velangular(), set_has_velnormal(), set_has_veltangent(), set_has_wheel1(), set_has_wheel2(), set_has_wheel3(), set_has_wheel4(), and set_has_wheelsspeed().
::google::protobuf::internal::InternalMetadataWithArena grSim_Robot_Command::_internal_metadata_ private
Definition at line 232 of file grSim_Commands.pb.h.
Referenced by mutable_unknown_fields(), grSim_Commands::mutable_unknown_fields(), unknown_fields(), and grSim_Commands::unknown_fields().
::google::protobuf::uint32 grSim_Robot_Command::id_ private
Definition at line 235 of file grSim_Commands.pb.h.
Referenced by clear_id(), id(), and set_id().
float grSim_Robot_Command::kickspeedx_ private
Definition at line 236 of file grSim_Commands.pb.h.
Referenced by clear_kickspeedx(), kickspeedx(), and set_kickspeedx().
float grSim_Robot_Command::kickspeedz_ private
Definition at line 237 of file grSim_Commands.pb.h.
Referenced by clear_kickspeedz(), kickspeedz(), and set_kickspeedz().
const int grSim_Robot_Command::kIdFieldNumber = 1 static
Definition at line 121 of file grSim_Commands.pb.h.
const int grSim_Robot_Command::kKickspeedxFieldNumber = 2 static
Definition at line 128 of file grSim_Commands.pb.h.
const int grSim_Robot_Command::kKickspeedzFieldNumber = 3 static
Definition at line 135 of file grSim_Commands.pb.h.
const int grSim_Robot_Command::kSpinnerFieldNumber = 7 static
Definition at line 163 of file grSim_Commands.pb.h.
const int grSim_Robot_Command::kVelangularFieldNumber = 6 static
Definition at line 156 of file grSim_Commands.pb.h.
const int grSim_Robot_Command::kVelnormalFieldNumber = 5 static
Definition at line 149 of file grSim_Commands.pb.h.
const int grSim_Robot_Command::kVeltangentFieldNumber = 4 static
Definition at line 142 of file grSim_Commands.pb.h.
const int grSim_Robot_Command::kWheel1FieldNumber = 9 static
Definition at line 177 of file grSim_Commands.pb.h.
const int grSim_Robot_Command::kWheel2FieldNumber = 10 static
Definition at line 184 of file grSim_Commands.pb.h.
const int grSim_Robot_Command::kWheel3FieldNumber = 11 static
Definition at line 191 of file grSim_Commands.pb.h.
const int grSim_Robot_Command::kWheel4FieldNumber = 12 static
Definition at line 198 of file grSim_Commands.pb.h.
const int grSim_Robot_Command::kWheelsspeedFieldNumber = 8 static
Definition at line 170 of file grSim_Commands.pb.h.
bool grSim_Robot_Command::spinner_ private
Definition at line 241 of file grSim_Commands.pb.h.
Referenced by clear_spinner(), set_spinner(), and spinner().
float grSim_Robot_Command::velangular_ private
Definition at line 240 of file grSim_Commands.pb.h.
Referenced by clear_velangular(), set_velangular(), and velangular().
float grSim_Robot_Command::velnormal_ private
Definition at line 239 of file grSim_Commands.pb.h.
Referenced by clear_velnormal(), set_velnormal(), and velnormal().
float grSim_Robot_Command::veltangent_ private
Definition at line 238 of file grSim_Commands.pb.h.
Referenced by clear_veltangent(), set_veltangent(), and veltangent().
float grSim_Robot_Command::wheel1_ private
Definition at line 243 of file grSim_Commands.pb.h.
Referenced by clear_wheel1(), set_wheel1(), and wheel1().
float grSim_Robot_Command::wheel2_ private
Definition at line 244 of file grSim_Commands.pb.h.
Referenced by clear_wheel2(), set_wheel2(), and wheel2().
float grSim_Robot_Command::wheel3_ private
Definition at line 245 of file grSim_Commands.pb.h.
Referenced by clear_wheel3(), set_wheel3(), and wheel3().
float grSim_Robot_Command::wheel4_ private
Definition at line 246 of file grSim_Commands.pb.h.
Referenced by clear_wheel4(), set_wheel4(), and wheel4().
bool grSim_Robot_Command::wheelsspeed_ private
Definition at line 242 of file grSim_Commands.pb.h.
Referenced by clear_wheelsspeed(), set_wheelsspeed(), and wheelsspeed().
The documentation for this class was generated from the following file:
grsim_comm/include/proto/grSim_Commands.pb.h