Documentation: Debug_AdjustBot Class Reference
Debug_AdjustBot Class Reference
#include <sslDebug_Data.pb.h>
Public Member Functions
Debug_AdjustBot ()
virtual ~Debug_AdjustBot ()
Debug_AdjustBot (const Debug_AdjustBot &from)
Debug_AdjustBot & operator= (const Debug_AdjustBot &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Debug_AdjustBot *other)
Debug_AdjustBot * New () const PROTOBUF_FINAL
Debug_AdjustBot * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const Debug_AdjustBot &from)
void MergeFrom (const Debug_AdjustBot &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_id () const
void clear_id ()
::google::protobuf::uint32 id () const
void set_id (::google::protobuf::uint32 value)
bool has_x () const
void clear_x ()
::google::protobuf::int32 x () const
void set_x (::google::protobuf::int32 value)
bool has_y () const
void clear_y ()
::google::protobuf::int32 y () const
void set_y (::google::protobuf::int32 value)
bool has_dir () const
void clear_dir ()
float dir () const
void set_dir (float value)
bool has_vx () const
void clear_vx ()
::google::protobuf::int32 vx () const
void set_vx (::google::protobuf::int32 value)
bool has_vy () const
void clear_vy ()
::google::protobuf::int32 vy () const
void set_vy (::google::protobuf::int32 value)
bool has_vz () const
void clear_vz ()
::google::protobuf::int32 vz () const
void set_vz (::google::protobuf::int32 value)
bool has_team () const
void clear_team ()
::google::protobuf::uint32 team () const
void set_team (::google::protobuf::uint32 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Debug_AdjustBot & default_instance ()
static const Debug_AdjustBot * internal_default_instance ()
Static Public Attributes
static const int kIdFieldNumber = 1
static const int kXFieldNumber = 2
static const int kYFieldNumber = 3
static const int kDirFieldNumber = 4
static const int kVxFieldNumber = 5
static const int kVyFieldNumber = 6
static const int kVzFieldNumber = 7
static const int kTeamFieldNumber = 8
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (Debug_AdjustBot *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_id ()
void clear_has_id ()
void set_has_x ()
void clear_has_x ()
void set_has_y ()
void clear_has_y ()
void set_has_dir ()
void clear_has_dir ()
void set_has_vx ()
void clear_has_vx ()
void set_has_vy ()
void clear_has_vy ()
void set_has_vz ()
void clear_has_vz ()
void set_has_team ()
void clear_has_team ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_sslDebug_5fData_2eproto ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::uint32 id_
::google::protobuf::int32 x_
::google::protobuf::int32 y_
float dir_
::google::protobuf::int32 vx_
::google::protobuf::int32 vy_
::google::protobuf::int32 vz_
::google::protobuf::uint32 team_
Friends
void protobuf_InitDefaults_sslDebug_5fData_2eproto_impl ()
void protobuf_AddDesc_sslDebug_5fData_2eproto_impl ()
void protobuf_ShutdownFile_sslDebug_5fData_2eproto ()
Detailed Description
Definition at line 483 of file sslDebug_Data.pb.h.
Constructor & Destructor Documentation
Debug_AdjustBot::Debug_AdjustBot ()
virtual Debug_AdjustBot::~Debug_AdjustBot () virtual
Debug_AdjustBot::Debug_AdjustBot (const Debug_AdjustBot & from)
Member Function Documentation
size_t Debug_AdjustBot::ByteSizeLong () const
void Debug_AdjustBot::Clear ()
void Debug_AdjustBot::clear_dir () inline
Definition at line 1293 of file sslDebug_Data.pb.h.
{
   dir_ = 0;
   clear_has_dir();
 }
void Debug_AdjustBot::clear_has_dir () inline private
Definition at line 1290 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000008u;
 }
void Debug_AdjustBot::clear_has_id () inline private
Definition at line 1218 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void Debug_AdjustBot::clear_has_team () inline private
Definition at line 1386 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000080u;
 }
void Debug_AdjustBot::clear_has_vx () inline private
Definition at line 1314 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000010u;
 }
void Debug_AdjustBot::clear_has_vy () inline private
Definition at line 1338 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000020u;
 }
void Debug_AdjustBot::clear_has_vz () inline private
Definition at line 1362 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000040u;
 }
void Debug_AdjustBot::clear_has_x () inline private
Definition at line 1242 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000002u;
 }
void Debug_AdjustBot::clear_has_y () inline private
Definition at line 1266 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000004u;
 }
void Debug_AdjustBot::clear_id () inline
Definition at line 1221 of file sslDebug_Data.pb.h.
References sslDebug_Data::clear_has_id(), and sslDebug_Data::id_.
{
   id_ = 0u;
   clear_has_id();
 }
void Debug_AdjustBot::clear_team () inline
Definition at line 1389 of file sslDebug_Data.pb.h.
{
   team_ = 0u;
   clear_has_team();
 }
void Debug_AdjustBot::clear_vx () inline
Definition at line 1317 of file sslDebug_Data.pb.h.
{
   vx_ = 0;
   clear_has_vx();
 }
void Debug_AdjustBot::clear_vy () inline
Definition at line 1341 of file sslDebug_Data.pb.h.
{
   vy_ = 0;
   clear_has_vy();
 }
void Debug_AdjustBot::clear_vz () inline
Definition at line 1365 of file sslDebug_Data.pb.h.
{
   vz_ = 0;
   clear_has_vz();
 }
void Debug_AdjustBot::clear_x () inline
Definition at line 1245 of file sslDebug_Data.pb.h.
{
   x_ = 0;
   clear_has_x();
 }
void Debug_AdjustBot::clear_y () inline
Definition at line 1269 of file sslDebug_Data.pb.h.
{
   y_ = 0;
   clear_has_y();
 }
void Debug_AdjustBot::CopyFrom (const ::google::protobuf::Message & from)
void Debug_AdjustBot::CopyFrom (const Debug_AdjustBot & from)
static const Debug_AdjustBot& Debug_AdjustBot::default_instance () static
static const ::google::protobuf::Descriptor* Debug_AdjustBot::descriptor () static
float Debug_AdjustBot::dir () const inline
Definition at line 1297 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_AdjustBot.dir)
   return dir_;
 }
inline ::google::protobuf::Arena* Debug_AdjustBot::GetArenaNoVirtual () const inline private
Definition at line 543 of file sslDebug_Data.pb.h.
{
     return NULL;
   }
int Debug_AdjustBot::GetCachedSize () const inline
Definition at line 536 of file sslDebug_Data.pb.h.
References sslDebug_Data::_cached_size_, sslDebug_Data::InternalSwap(), sslDebug_Data::SetCachedSize(), sslDebug_Data::SharedCtor(), and sslDebug_Data::SharedDtor().
 { return _cached_size_; }
::google::protobuf::Metadata Debug_AdjustBot::GetMetadata () const
bool Debug_AdjustBot::has_dir () const inline
Definition at line 1284 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool Debug_AdjustBot::has_id () const inline
Definition at line 1212 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool Debug_AdjustBot::has_team () const inline
Definition at line 1380 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000080u) != 0;
 }
bool Debug_AdjustBot::has_vx () const inline
Definition at line 1308 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
bool Debug_AdjustBot::has_vy () const inline
Definition at line 1332 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000020u) != 0;
 }
bool Debug_AdjustBot::has_vz () const inline
Definition at line 1356 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000040u) != 0;
 }
bool Debug_AdjustBot::has_x () const inline
Definition at line 1236 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool Debug_AdjustBot::has_y () const inline
Definition at line 1260 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
google::protobuf::uint32 Debug_AdjustBot::id () const inline
Definition at line 1225 of file sslDebug_Data.pb.h.
References sslDebug_Data::id_.
{
   // @@protoc_insertion_point(field_get:Debug_AdjustBot.id)
   return id_;
 }
static const Debug_AdjustBot* Debug_AdjustBot::internal_default_instance () inline static
Definition at line 506 of file sslDebug_Data.pb.h.
References _Debug_AdjustBot_default_instance_, and sslDebug_Data::Swap().
{
     return reinterpret_cast<const Debug_AdjustBot*>(
                &_Debug_AdjustBot_default_instance_);
   }
::google::protobuf::uint8* Debug_AdjustBot::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void Debug_AdjustBot::InternalSwap (Debug_AdjustBot * other) private
bool Debug_AdjustBot::IsInitialized () const
void* Debug_AdjustBot::MaybeArenaPtr () const inline private
Definition at line 546 of file sslDebug_Data.pb.h.
References sslDebug_Data::clear_id(), sslDebug_Data::GetMetadata(), and sslDebug_Data::has_id().
{
     return NULL;
   }
void Debug_AdjustBot::MergeFrom (const ::google::protobuf::Message & from)
void Debug_AdjustBot::MergeFrom (const Debug_AdjustBot & from)
bool Debug_AdjustBot::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
inline ::google::protobuf::UnknownFieldSet* Debug_AdjustBot::mutable_unknown_fields () inline
Definition at line 499 of file sslDebug_Data.pb.h.
References sslDebug_Data::_internal_metadata_, sslDebug_Data::default_instance(), and sslDebug_Data::descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
Debug_AdjustBot* Debug_AdjustBot::New () const inline
Definition at line 515 of file sslDebug_Data.pb.h.
References sslDebug_Data::ByteSizeLong(), sslDebug_Data::Clear(), sslDebug_Data::CopyFrom(), sslDebug_Data::InternalSerializeWithCachedSizesToArray(), sslDebug_Data::IsInitialized(), sslDebug_Data::MergeFrom(), sslDebug_Data::MergePartialFromCodedStream(), sslDebug_Data::New(), New(), sslDebug_Data::SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
Debug_AdjustBot* Debug_AdjustBot::New (::google::protobuf::Arena * arena) const
Debug_AdjustBot& Debug_AdjustBot::operator= (const Debug_AdjustBot & from) inline
Definition at line 490 of file sslDebug_Data.pb.h.
References sslDebug_Data::CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* Debug_AdjustBot::protobuf_Offsets_sslDebug_5fData_2eproto () private
size_t Debug_AdjustBot::RequiredFieldsByteSizeFallback () const private
void Debug_AdjustBot::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* Debug_AdjustBot::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 532 of file sslDebug_Data.pb.h.
References sslDebug_Data::InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void Debug_AdjustBot::set_dir (float value) inline
Definition at line 1301 of file sslDebug_Data.pb.h.
{
   set_has_dir();
   dir_ = value;
   // @@protoc_insertion_point(field_set:Debug_AdjustBot.dir)
 }
void Debug_AdjustBot::set_has_dir () inline private
Definition at line 1287 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000008u;
 }
void Debug_AdjustBot::set_has_id () inline private
Definition at line 1215 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000001u;
 }
void Debug_AdjustBot::set_has_team () inline private
Definition at line 1383 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000080u;
 }
void Debug_AdjustBot::set_has_vx () inline private
Definition at line 1311 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000010u;
 }
void Debug_AdjustBot::set_has_vy () inline private
Definition at line 1335 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000020u;
 }
void Debug_AdjustBot::set_has_vz () inline private
Definition at line 1359 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000040u;
 }
void Debug_AdjustBot::set_has_x () inline private
Definition at line 1239 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000002u;
 }
void Debug_AdjustBot::set_has_y () inline private
Definition at line 1263 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000004u;
 }
void Debug_AdjustBot::set_id (::google::protobuf::uint32 value) inline
Definition at line 1229 of file sslDebug_Data.pb.h.
References sslDebug_Data::id_, and sslDebug_Data::set_has_id().
{
   set_has_id();
   id_ = value;
   // @@protoc_insertion_point(field_set:Debug_AdjustBot.id)
 }
void Debug_AdjustBot::set_team (::google::protobuf::uint32 value) inline
Definition at line 1397 of file sslDebug_Data.pb.h.
{
   set_has_team();
   team_ = value;
   // @@protoc_insertion_point(field_set:Debug_AdjustBot.team)
 }
void Debug_AdjustBot::set_vx (::google::protobuf::int32 value) inline
Definition at line 1325 of file sslDebug_Data.pb.h.
{
   set_has_vx();
   vx_ = value;
   // @@protoc_insertion_point(field_set:Debug_AdjustBot.vx)
 }
void Debug_AdjustBot::set_vy (::google::protobuf::int32 value) inline
Definition at line 1349 of file sslDebug_Data.pb.h.
{
   set_has_vy();
   vy_ = value;
   // @@protoc_insertion_point(field_set:Debug_AdjustBot.vy)
 }
void Debug_AdjustBot::set_vz (::google::protobuf::int32 value) inline
Definition at line 1373 of file sslDebug_Data.pb.h.
{
   set_has_vz();
   vz_ = value;
   // @@protoc_insertion_point(field_set:Debug_AdjustBot.vz)
 }
void Debug_AdjustBot::set_x (::google::protobuf::int32 value) inline
Definition at line 1253 of file sslDebug_Data.pb.h.
{
   set_has_x();
   x_ = value;
   // @@protoc_insertion_point(field_set:Debug_AdjustBot.x)
 }
void Debug_AdjustBot::set_y (::google::protobuf::int32 value) inline
Definition at line 1277 of file sslDebug_Data.pb.h.
{
   set_has_y();
   y_ = value;
   // @@protoc_insertion_point(field_set:Debug_AdjustBot.y)
 }
void Debug_AdjustBot::SetCachedSize (int size) const private
void Debug_AdjustBot::SharedCtor () private
void Debug_AdjustBot::SharedDtor () private
void Debug_AdjustBot::Swap (Debug_AdjustBot * other)
google::protobuf::uint32 Debug_AdjustBot::team () const inline
Definition at line 1393 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_AdjustBot.team)
   return team_;
 }
const ::google::protobuf::UnknownFieldSet& Debug_AdjustBot::unknown_fields () const inline
Definition at line 495 of file sslDebug_Data.pb.h.
References sslDebug_Data::_internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
google::protobuf::int32 Debug_AdjustBot::vx () const inline
Definition at line 1321 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_AdjustBot.vx)
   return vx_;
 }
google::protobuf::int32 Debug_AdjustBot::vy () const inline
Definition at line 1345 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_AdjustBot.vy)
   return vy_;
 }
google::protobuf::int32 Debug_AdjustBot::vz () const inline
Definition at line 1369 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_AdjustBot.vz)
   return vz_;
 }
google::protobuf::int32 Debug_AdjustBot::x () const inline
Definition at line 1249 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_AdjustBot.x)
   return x_;
 }
google::protobuf::int32 Debug_AdjustBot::y () const inline
Definition at line 1273 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_AdjustBot.y)
   return y_;
 }
Friends And Related Function Documentation
void protobuf_AddDesc_sslDebug_5fData_2eproto_impl () friend
void protobuf_InitDefaults_sslDebug_5fData_2eproto_impl () friend
void protobuf_ShutdownFile_sslDebug_5fData_2eproto () friend
Field Documentation
int Debug_AdjustBot::_cached_size_ mutable private
Definition at line 637 of file sslDebug_Data.pb.h.
::google::protobuf::internal::HasBits<1> Debug_AdjustBot::_has_bits_ private
Definition at line 636 of file sslDebug_Data.pb.h.
::google::protobuf::internal::InternalMetadataWithArena Debug_AdjustBot::_internal_metadata_ private
Definition at line 635 of file sslDebug_Data.pb.h.
float Debug_AdjustBot::dir_ private
Definition at line 641 of file sslDebug_Data.pb.h.
::google::protobuf::uint32 Debug_AdjustBot::id_ private
Definition at line 638 of file sslDebug_Data.pb.h.
const int Debug_AdjustBot::kDirFieldNumber = 4 static
Definition at line 581 of file sslDebug_Data.pb.h.
const int Debug_AdjustBot::kIdFieldNumber = 1 static
Definition at line 560 of file sslDebug_Data.pb.h.
const int Debug_AdjustBot::kTeamFieldNumber = 8 static
Definition at line 609 of file sslDebug_Data.pb.h.
const int Debug_AdjustBot::kVxFieldNumber = 5 static
Definition at line 588 of file sslDebug_Data.pb.h.
const int Debug_AdjustBot::kVyFieldNumber = 6 static
Definition at line 595 of file sslDebug_Data.pb.h.
const int Debug_AdjustBot::kVzFieldNumber = 7 static
Definition at line 602 of file sslDebug_Data.pb.h.
const int Debug_AdjustBot::kXFieldNumber = 2 static
Definition at line 567 of file sslDebug_Data.pb.h.
const int Debug_AdjustBot::kYFieldNumber = 3 static
Definition at line 574 of file sslDebug_Data.pb.h.
::google::protobuf::uint32 Debug_AdjustBot::team_ private
Definition at line 645 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_AdjustBot::vx_ private
Definition at line 642 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_AdjustBot::vy_ private
Definition at line 643 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_AdjustBot::vz_ private
Definition at line 644 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_AdjustBot::x_ private
Definition at line 639 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_AdjustBot::y_ private
Definition at line 640 of file sslDebug_Data.pb.h.
The documentation for this class was generated from the following file:
grsim_comm/include/proto/sslDebug_Data.pb.h