Documentation: Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder Interface Reference
Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder Interface Reference
Public Member Functions
boolean hasX ()
double getX ()
boolean hasY ()
double getY ()
boolean hasDir ()
double getDir ()
boolean hasId ()
int getId ()
boolean hasYellowteam ()
boolean getYellowteam ()
Detailed Description
Definition at line 11 of file GrSimReplacement.java.
Member Function Documentation
double Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.getDir ()
Implemented in Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder, and Protobuf.GrSimReplacement.grSim_RobotReplacement.
int Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.getId ()
Implemented in Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder, and Protobuf.GrSimReplacement.grSim_RobotReplacement.
double Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.getX ()
Implemented in Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder, and Protobuf.GrSimReplacement.grSim_RobotReplacement.
double Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.getY ()
Implemented in Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder, and Protobuf.GrSimReplacement.grSim_RobotReplacement.
boolean Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.getYellowteam ()
Implemented in Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder, and Protobuf.GrSimReplacement.grSim_RobotReplacement.
boolean Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasDir ()
Implemented in Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder, and Protobuf.GrSimReplacement.grSim_RobotReplacement.
Referenced by Protobuf.GrSimReplacement.grSim_RobotReplacement.isInitialized(), and Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.isInitialized().
boolean Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasId ()
Implemented in Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder, and Protobuf.GrSimReplacement.grSim_RobotReplacement.
Referenced by Protobuf.GrSimReplacement.grSim_RobotReplacement.isInitialized(), and Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.isInitialized().
boolean Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasX ()
Implemented in Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder, and Protobuf.GrSimReplacement.grSim_RobotReplacement.
Referenced by Protobuf.GrSimReplacement.grSim_RobotReplacement.isInitialized(), Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.isInitialized(), Protobuf.GrSimReplacement.grSim_BallReplacement.isInitialized(), and Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.isInitialized().
boolean Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasY ()
Implemented in Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder, and Protobuf.GrSimReplacement.grSim_RobotReplacement.
Referenced by Protobuf.GrSimReplacement.grSim_RobotReplacement.isInitialized(), Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.isInitialized(), Protobuf.GrSimReplacement.grSim_BallReplacement.isInitialized(), and Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.isInitialized().
boolean Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasYellowteam ()
Implemented in Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder, and Protobuf.GrSimReplacement.grSim_RobotReplacement.
Referenced by Protobuf.GrSimReplacement.grSim_RobotReplacement.isInitialized(), and Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.isInitialized().
The documentation for this interface was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimReplacement.java