Documentation: SSL_GeometryFieldSize Class Reference
SSL_GeometryFieldSize Class Reference
#include <messages_robocup_ssl_geometry.pb.h>
Public Member Functions
SSL_GeometryFieldSize ()
virtual ~SSL_GeometryFieldSize ()
SSL_GeometryFieldSize (const SSL_GeometryFieldSize &from)
SSL_GeometryFieldSize & operator= (const SSL_GeometryFieldSize &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_GeometryFieldSize *other)
SSL_GeometryFieldSize * New () const PROTOBUF_FINAL
SSL_GeometryFieldSize * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_GeometryFieldSize &from)
void MergeFrom (const SSL_GeometryFieldSize &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_line_width () const
void clear_line_width ()
::google::protobuf::int32 line_width () const
void set_line_width (::google::protobuf::int32 value)
bool has_field_length () const
void clear_field_length ()
::google::protobuf::int32 field_length () const
void set_field_length (::google::protobuf::int32 value)
bool has_field_width () const
void clear_field_width ()
::google::protobuf::int32 field_width () const
void set_field_width (::google::protobuf::int32 value)
bool has_boundary_width () const
void clear_boundary_width ()
::google::protobuf::int32 boundary_width () const
void set_boundary_width (::google::protobuf::int32 value)
bool has_referee_width () const
void clear_referee_width ()
::google::protobuf::int32 referee_width () const
void set_referee_width (::google::protobuf::int32 value)
bool has_goal_width () const
void clear_goal_width ()
::google::protobuf::int32 goal_width () const
void set_goal_width (::google::protobuf::int32 value)
bool has_goal_depth () const
void clear_goal_depth ()
::google::protobuf::int32 goal_depth () const
void set_goal_depth (::google::protobuf::int32 value)
bool has_goal_wall_width () const
void clear_goal_wall_width ()
::google::protobuf::int32 goal_wall_width () const
void set_goal_wall_width (::google::protobuf::int32 value)
bool has_center_circle_radius () const
void clear_center_circle_radius ()
::google::protobuf::int32 center_circle_radius () const
void set_center_circle_radius (::google::protobuf::int32 value)
bool has_defense_radius () const
void clear_defense_radius ()
::google::protobuf::int32 defense_radius () const
void set_defense_radius (::google::protobuf::int32 value)
bool has_defense_stretch () const
void clear_defense_stretch ()
::google::protobuf::int32 defense_stretch () const
void set_defense_stretch (::google::protobuf::int32 value)
bool has_free_kick_from_defense_dist () const
void clear_free_kick_from_defense_dist ()
::google::protobuf::int32 free_kick_from_defense_dist () const
void set_free_kick_from_defense_dist (::google::protobuf::int32 value)
bool has_penalty_spot_from_field_line_dist () const
void clear_penalty_spot_from_field_line_dist ()
::google::protobuf::int32 penalty_spot_from_field_line_dist () const
void set_penalty_spot_from_field_line_dist (::google::protobuf::int32 value)
bool has_penalty_line_from_spot_dist () const
void clear_penalty_line_from_spot_dist ()
::google::protobuf::int32 penalty_line_from_spot_dist () const
void set_penalty_line_from_spot_dist (::google::protobuf::int32 value)
SSL_GeometryFieldSize ()
virtual ~SSL_GeometryFieldSize ()
SSL_GeometryFieldSize (const SSL_GeometryFieldSize &from)
SSL_GeometryFieldSize & operator= (const SSL_GeometryFieldSize &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_GeometryFieldSize *other)
SSL_GeometryFieldSize * New () const PROTOBUF_FINAL
SSL_GeometryFieldSize * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_GeometryFieldSize &from)
void MergeFrom (const SSL_GeometryFieldSize &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
int field_lines_size () const
void clear_field_lines ()
const ::SSL_FieldLineSegment & field_lines (int index) const
::SSL_FieldLineSegment * mutable_field_lines (int index)
::SSL_FieldLineSegment * add_field_lines ()
::google::protobuf::RepeatedPtrField< ::SSL_FieldLineSegment > * mutable_field_lines ()
const ::google::protobuf::RepeatedPtrField< ::SSL_FieldLineSegment > & field_lines () const
int field_arcs_size () const
void clear_field_arcs ()
const ::SSL_FieldCicularArc & field_arcs (int index) const
::SSL_FieldCicularArc * mutable_field_arcs (int index)
::SSL_FieldCicularArc * add_field_arcs ()
::google::protobuf::RepeatedPtrField< ::SSL_FieldCicularArc > * mutable_field_arcs ()
const ::google::protobuf::RepeatedPtrField< ::SSL_FieldCicularArc > & field_arcs () const
bool has_field_length () const
void clear_field_length ()
::google::protobuf::int32 field_length () const
void set_field_length (::google::protobuf::int32 value)
bool has_field_width () const
void clear_field_width ()
::google::protobuf::int32 field_width () const
void set_field_width (::google::protobuf::int32 value)
bool has_goal_width () const
void clear_goal_width ()
::google::protobuf::int32 goal_width () const
void set_goal_width (::google::protobuf::int32 value)
bool has_goal_depth () const
void clear_goal_depth ()
::google::protobuf::int32 goal_depth () const
void set_goal_depth (::google::protobuf::int32 value)
bool has_boundary_width () const
void clear_boundary_width ()
::google::protobuf::int32 boundary_width () const
void set_boundary_width (::google::protobuf::int32 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_GeometryFieldSize & default_instance ()
static const SSL_GeometryFieldSize * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_GeometryFieldSize & default_instance ()
static void InitAsDefaultInstance ()
static const SSL_GeometryFieldSize * internal_default_instance ()
Static Public Attributes
static const int kLineWidthFieldNumber = 1
static const int kFieldLengthFieldNumber = 2
static const int kFieldWidthFieldNumber = 3
static const int kBoundaryWidthFieldNumber = 4
static const int kRefereeWidthFieldNumber = 5
static const int kGoalWidthFieldNumber = 6
static const int kGoalDepthFieldNumber = 7
static const int kGoalWallWidthFieldNumber = 8
static const int kCenterCircleRadiusFieldNumber = 9
static const int kDefenseRadiusFieldNumber = 10
static const int kDefenseStretchFieldNumber = 11
static const int kFreeKickFromDefenseDistFieldNumber = 12
static const int kPenaltySpotFromFieldLineDistFieldNumber = 13
static const int kPenaltyLineFromSpotDistFieldNumber = 14
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kFieldLinesFieldNumber = 6
static const int kFieldArcsFieldNumber = 7
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_GeometryFieldSize *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_line_width ()
void clear_has_line_width ()
void set_has_field_length ()
void clear_has_field_length ()
void set_has_field_width ()
void clear_has_field_width ()
void set_has_boundary_width ()
void clear_has_boundary_width ()
void set_has_referee_width ()
void clear_has_referee_width ()
void set_has_goal_width ()
void clear_has_goal_width ()
void set_has_goal_depth ()
void clear_has_goal_depth ()
void set_has_goal_wall_width ()
void clear_has_goal_wall_width ()
void set_has_center_circle_radius ()
void clear_has_center_circle_radius ()
void set_has_defense_radius ()
void clear_has_defense_radius ()
void set_has_defense_stretch ()
void clear_has_defense_stretch ()
void set_has_free_kick_from_defense_dist ()
void clear_has_free_kick_from_defense_dist ()
void set_has_penalty_spot_from_field_line_dist ()
void clear_has_penalty_spot_from_field_line_dist ()
void set_has_penalty_line_from_spot_dist ()
void clear_has_penalty_line_from_spot_dist ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5fgeometry_2eproto ()
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_GeometryFieldSize *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_field_length ()
void clear_has_field_length ()
void set_has_field_width ()
void clear_has_field_width ()
void set_has_goal_width ()
void clear_has_goal_width ()
void set_has_goal_depth ()
void clear_has_goal_depth ()
void set_has_boundary_width ()
void clear_has_boundary_width ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryFieldSizeImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::int32 line_width_
::google::protobuf::int32 field_length_
::google::protobuf::int32 field_width_
::google::protobuf::int32 boundary_width_
::google::protobuf::int32 referee_width_
::google::protobuf::int32 goal_width_
::google::protobuf::int32 goal_depth_
::google::protobuf::int32 goal_wall_width_
::google::protobuf::int32 center_circle_radius_
::google::protobuf::int32 defense_radius_
::google::protobuf::int32 defense_stretch_
::google::protobuf::int32 free_kick_from_defense_dist_
::google::protobuf::int32 penalty_spot_from_field_line_dist_
::google::protobuf::int32 penalty_line_from_spot_dist_
::google::protobuf::RepeatedPtrField< ::SSL_FieldLineSegment > field_lines_
::google::protobuf::RepeatedPtrField< ::SSL_FieldCicularArc > field_arcs_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::TableStruct
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto_impl ()
void protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_impl ()
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto ()
void swap (SSL_GeometryFieldSize &a, SSL_GeometryFieldSize &b)
Detailed Description
Definition at line 47 of file messages_robocup_ssl_geometry.pb.h.
Constructor & Destructor Documentation
SSL_GeometryFieldSize::SSL_GeometryFieldSize ()
virtual SSL_GeometryFieldSize::~SSL_GeometryFieldSize () virtual
SSL_GeometryFieldSize::SSL_GeometryFieldSize (const SSL_GeometryFieldSize & from)
SSL_GeometryFieldSize::SSL_GeometryFieldSize ()
virtual SSL_GeometryFieldSize::~SSL_GeometryFieldSize () virtual
SSL_GeometryFieldSize::SSL_GeometryFieldSize (const SSL_GeometryFieldSize & from)
Member Function Documentation
SSL_FieldCicularArc * SSL_GeometryFieldSize::add_field_arcs () inline
Definition at line 1737 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSLWorld::addFieldArc(), and RoboCupField::toProtoBuffer().
{
   // @@protoc_insertion_point(field_add:SSL_GeometryFieldSize.field_arcs)
   return field_arcs_.Add();
 }
SSL_FieldLineSegment * SSL_GeometryFieldSize::add_field_lines () inline
Definition at line 1707 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSLWorld::addFieldLine(), and RoboCupField::toProtoBuffer().
{
   // @@protoc_insertion_point(field_add:SSL_GeometryFieldSize.field_lines)
   return field_lines_.Add();
 }
google::protobuf::int32 SSL_GeometryFieldSize::boundary_width () const inline
Definition at line 724 of file messages_robocup_ssl_geometry.pb.h.
References boundary_width_.
Referenced by main(), PluginLegacyPublishGeometry::sendGeometry(), and SSL_FieldCicularArc::set_thickness().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.boundary_width)
   return boundary_width_;
 }
::google::protobuf::int32 SSL_GeometryFieldSize::boundary_width () const
size_t SSL_GeometryFieldSize::ByteSizeLong () const
Referenced by New(), SSL_GeometryCameraCalibration::New(), and SSL_GeometryData::New().
size_t SSL_GeometryFieldSize::ByteSizeLong () const
google::protobuf::int32 SSL_GeometryFieldSize::center_circle_radius () const inline
Definition at line 844 of file messages_robocup_ssl_geometry.pb.h.
References center_circle_radius_.
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.center_circle_radius)
   return center_circle_radius_;
 }
void SSL_GeometryFieldSize::Clear ()
Referenced by New(), SSL_GeometryCameraCalibration::New(), SSL_GeometryData::New(), and RoboCupField::toProtoBuffer().
void SSL_GeometryFieldSize::Clear ()
void SSL_GeometryFieldSize::clear_boundary_width () inline
Definition at line 720 of file messages_robocup_ssl_geometry.pb.h.
References boundary_width_, and clear_has_boundary_width().
Referenced by SSL_FieldCicularArc::set_thickness().
{
   boundary_width_ = 0;
   clear_has_boundary_width();
 }
void SSL_GeometryFieldSize::clear_boundary_width ()
void SSL_GeometryFieldSize::clear_center_circle_radius () inline
Definition at line 840 of file messages_robocup_ssl_geometry.pb.h.
References center_circle_radius_, and clear_has_center_circle_radius().
{
   center_circle_radius_ = 0;
   clear_has_center_circle_radius();
 }
void SSL_GeometryFieldSize::clear_defense_radius () inline
Definition at line 864 of file messages_robocup_ssl_geometry.pb.h.
References clear_has_defense_radius(), and defense_radius_.
{
   defense_radius_ = 0;
   clear_has_defense_radius();
 }
void SSL_GeometryFieldSize::clear_defense_stretch () inline
Definition at line 888 of file messages_robocup_ssl_geometry.pb.h.
References clear_has_defense_stretch(), and defense_stretch_.
{
   defense_stretch_ = 0;
   clear_has_defense_stretch();
 }
void SSL_GeometryFieldSize::clear_field_arcs () inline
Definition at line 1726 of file messages_robocup_ssl_geometry.pb.h.
{
   field_arcs_.Clear();
 }
void SSL_GeometryFieldSize::clear_field_length () inline
Definition at line 672 of file messages_robocup_ssl_geometry.pb.h.
References clear_has_field_length(), and field_length_.
Referenced by SSL_FieldCicularArc::set_thickness().
{
   field_length_ = 0;
   clear_has_field_length();
 }
void SSL_GeometryFieldSize::clear_field_length ()
void SSL_GeometryFieldSize::clear_field_lines () inline
Definition at line 1696 of file messages_robocup_ssl_geometry.pb.h.
{
   field_lines_.Clear();
 }
void SSL_GeometryFieldSize::clear_field_width () inline
Definition at line 696 of file messages_robocup_ssl_geometry.pb.h.
References clear_has_field_width(), and field_width_.
Referenced by SSL_FieldCicularArc::set_thickness().
{
   field_width_ = 0;
   clear_has_field_width();
 }
void SSL_GeometryFieldSize::clear_field_width ()
void SSL_GeometryFieldSize::clear_free_kick_from_defense_dist () inline
Definition at line 912 of file messages_robocup_ssl_geometry.pb.h.
References clear_has_free_kick_from_defense_dist(), and free_kick_from_defense_dist_.
{
   free_kick_from_defense_dist_ = 0;
   clear_has_free_kick_from_defense_dist();
 }
void SSL_GeometryFieldSize::clear_goal_depth () inline
Definition at line 792 of file messages_robocup_ssl_geometry.pb.h.
References clear_has_goal_depth(), and goal_depth_.
Referenced by SSL_FieldCicularArc::set_thickness().
{
   goal_depth_ = 0;
   clear_has_goal_depth();
 }
void SSL_GeometryFieldSize::clear_goal_depth ()
void SSL_GeometryFieldSize::clear_goal_wall_width () inline
Definition at line 816 of file messages_robocup_ssl_geometry.pb.h.
References clear_has_goal_wall_width(), and goal_wall_width_.
{
   goal_wall_width_ = 0;
   clear_has_goal_wall_width();
 }
void SSL_GeometryFieldSize::clear_goal_width () inline
Definition at line 768 of file messages_robocup_ssl_geometry.pb.h.
References clear_has_goal_width(), and goal_width_.
Referenced by SSL_FieldCicularArc::set_thickness().
{
   goal_width_ = 0;
   clear_has_goal_width();
 }
void SSL_GeometryFieldSize::clear_goal_width ()
void SSL_GeometryFieldSize::clear_has_boundary_width () inline private
Definition at line 717 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_boundary_width(), and SSL_FieldCicularArc::set_thickness().
{
   _has_bits_[0] &= ~0x00000008u;
 }
void SSL_GeometryFieldSize::clear_has_boundary_width () private
void SSL_GeometryFieldSize::clear_has_center_circle_radius () inline private
Definition at line 837 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_center_circle_radius().
{
   _has_bits_[0] &= ~0x00000100u;
 }
void SSL_GeometryFieldSize::clear_has_defense_radius () inline private
Definition at line 861 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_defense_radius().
{
   _has_bits_[0] &= ~0x00000200u;
 }
void SSL_GeometryFieldSize::clear_has_defense_stretch () inline private
Definition at line 885 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_defense_stretch().
{
   _has_bits_[0] &= ~0x00000400u;
 }
void SSL_GeometryFieldSize::clear_has_field_length () inline private
Definition at line 669 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_field_length(), and SSL_FieldCicularArc::set_thickness().
{
   _has_bits_[0] &= ~0x00000002u;
 }
void SSL_GeometryFieldSize::clear_has_field_length () private
void SSL_GeometryFieldSize::clear_has_field_width () inline private
Definition at line 693 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_field_width(), and SSL_FieldCicularArc::set_thickness().
{
   _has_bits_[0] &= ~0x00000004u;
 }
void SSL_GeometryFieldSize::clear_has_field_width () private
void SSL_GeometryFieldSize::clear_has_free_kick_from_defense_dist () inline private
Definition at line 909 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_free_kick_from_defense_dist().
{
   _has_bits_[0] &= ~0x00000800u;
 }
void SSL_GeometryFieldSize::clear_has_goal_depth () inline private
Definition at line 789 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_goal_depth(), and SSL_FieldCicularArc::set_thickness().
{
   _has_bits_[0] &= ~0x00000040u;
 }
void SSL_GeometryFieldSize::clear_has_goal_depth () private
void SSL_GeometryFieldSize::clear_has_goal_wall_width () inline private
Definition at line 813 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_goal_wall_width().
{
   _has_bits_[0] &= ~0x00000080u;
 }
void SSL_GeometryFieldSize::clear_has_goal_width () inline private
Definition at line 765 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_goal_width(), and SSL_FieldCicularArc::set_thickness().
{
   _has_bits_[0] &= ~0x00000020u;
 }
void SSL_GeometryFieldSize::clear_has_goal_width () private
void SSL_GeometryFieldSize::clear_has_line_width () inline private
Definition at line 645 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_line_width().
{
   _has_bits_[0] &= ~0x00000001u;
 }
void SSL_GeometryFieldSize::clear_has_penalty_line_from_spot_dist () inline private
Definition at line 957 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_penalty_line_from_spot_dist().
{
   _has_bits_[0] &= ~0x00002000u;
 }
void SSL_GeometryFieldSize::clear_has_penalty_spot_from_field_line_dist () inline private
Definition at line 933 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_penalty_spot_from_field_line_dist().
{
   _has_bits_[0] &= ~0x00001000u;
 }
void SSL_GeometryFieldSize::clear_has_referee_width () inline private
Definition at line 741 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by clear_referee_width().
{
   _has_bits_[0] &= ~0x00000010u;
 }
void SSL_GeometryFieldSize::clear_line_width () inline
Definition at line 648 of file messages_robocup_ssl_geometry.pb.h.
References clear_has_line_width(), and line_width_.
Referenced by MaybeArenaPtr().
{
   line_width_ = 0;
   clear_has_line_width();
 }
void SSL_GeometryFieldSize::clear_penalty_line_from_spot_dist () inline
Definition at line 960 of file messages_robocup_ssl_geometry.pb.h.
References clear_has_penalty_line_from_spot_dist(), and penalty_line_from_spot_dist_.
{
   penalty_line_from_spot_dist_ = 0;
   clear_has_penalty_line_from_spot_dist();
 }
void SSL_GeometryFieldSize::clear_penalty_spot_from_field_line_dist () inline
Definition at line 936 of file messages_robocup_ssl_geometry.pb.h.
References clear_has_penalty_spot_from_field_line_dist(), and penalty_spot_from_field_line_dist_.
{
   penalty_spot_from_field_line_dist_ = 0;
   clear_has_penalty_spot_from_field_line_dist();
 }
void SSL_GeometryFieldSize::clear_referee_width () inline
Definition at line 744 of file messages_robocup_ssl_geometry.pb.h.
References clear_has_referee_width(), and referee_width_.
{
   referee_width_ = 0;
   clear_has_referee_width();
 }
void SSL_GeometryFieldSize::CopyFrom (const ::google::protobuf::Message & from)
Referenced by New(), SSL_GeometryCameraCalibration::New(), SSL_GeometryData::New(), operator=(), SSL_GeometryCameraCalibration::operator=(), and SSL_GeometryData::operator=().
void SSL_GeometryFieldSize::CopyFrom (const SSL_GeometryFieldSize & from)
void SSL_GeometryFieldSize::CopyFrom (const ::google::protobuf::Message & from)
void SSL_GeometryFieldSize::CopyFrom (const SSL_GeometryFieldSize & from)
static const SSL_GeometryFieldSize& SSL_GeometryFieldSize::default_instance () static
Referenced by mutable_unknown_fields(), SSL_GeometryCameraCalibration::mutable_unknown_fields(), and SSL_GeometryData::mutable_unknown_fields().
static const SSL_GeometryFieldSize& SSL_GeometryFieldSize::default_instance () static
google::protobuf::int32 SSL_GeometryFieldSize::defense_radius () const inline
Definition at line 868 of file messages_robocup_ssl_geometry.pb.h.
References defense_radius_.
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.defense_radius)
   return defense_radius_;
 }
google::protobuf::int32 SSL_GeometryFieldSize::defense_stretch () const inline
Definition at line 892 of file messages_robocup_ssl_geometry.pb.h.
References defense_stretch_.
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.defense_stretch)
   return defense_stretch_;
 }
static const ::google::protobuf::Descriptor* SSL_GeometryFieldSize::descriptor () static
Referenced by mutable_unknown_fields(), SSL_GeometryCameraCalibration::mutable_unknown_fields(), and SSL_GeometryData::mutable_unknown_fields().
static const ::google::protobuf::Descriptor* SSL_GeometryFieldSize::descriptor () static
const ::SSL_FieldCicularArc & SSL_GeometryFieldSize::field_arcs (int index) const inline
Definition at line 1729 of file messages_robocup_ssl_geometry.pb.h.
Referenced by GLSoccerView::updateFieldGeometry().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.field_arcs)
   return field_arcs_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::SSL_FieldCicularArc > & SSL_GeometryFieldSize::field_arcs () const inline
Definition at line 1747 of file messages_robocup_ssl_geometry.pb.h.
References _SSL_GeometryFieldSize_default_instance_, SSL_GeometryData::add_calib(), SSL_GeometryData::calib(), SSL_GeometryData::calib_size(), SSL_GeometryCameraCalibration::camera_id(), SSL_GeometryData::clear_calib(), SSL_GeometryCameraCalibration::clear_camera_id(), SSL_GeometryCameraCalibration::clear_derived_camera_world_tx(), SSL_GeometryCameraCalibration::clear_derived_camera_world_ty(), SSL_GeometryCameraCalibration::clear_derived_camera_world_tz(), SSL_GeometryCameraCalibration::clear_distortion(), SSL_GeometryData::clear_field(), SSL_GeometryCameraCalibration::clear_focal_length(), SSL_GeometryCameraCalibration::clear_has_camera_id(), SSL_GeometryCameraCalibration::clear_has_derived_camera_world_tx(), SSL_GeometryCameraCalibration::clear_has_derived_camera_world_ty(), SSL_GeometryCameraCalibration::clear_has_derived_camera_world_tz(), SSL_GeometryCameraCalibration::clear_has_distortion(), SSL_GeometryData::clear_has_field(), SSL_GeometryCameraCalibration::clear_has_focal_length(), SSL_GeometryCameraCalibration::clear_has_principal_point_x(), SSL_GeometryCameraCalibration::clear_has_principal_point_y(), SSL_GeometryCameraCalibration::clear_has_q0(), SSL_GeometryCameraCalibration::clear_has_q1(), SSL_GeometryCameraCalibration::clear_has_q2(), SSL_GeometryCameraCalibration::clear_has_q3(), SSL_GeometryCameraCalibration::clear_has_tx(), SSL_GeometryCameraCalibration::clear_has_ty(), SSL_GeometryCameraCalibration::clear_has_tz(), SSL_GeometryCameraCalibration::clear_principal_point_x(), SSL_GeometryCameraCalibration::clear_principal_point_y(), SSL_GeometryCameraCalibration::clear_q0(), SSL_GeometryCameraCalibration::clear_q1(), SSL_GeometryCameraCalibration::clear_q2(), SSL_GeometryCameraCalibration::clear_q3(), SSL_GeometryCameraCalibration::clear_tx(), SSL_GeometryCameraCalibration::clear_ty(), SSL_GeometryCameraCalibration::clear_tz(), SSL_GeometryCameraCalibration::derived_camera_world_tx(), SSL_GeometryCameraCalibration::derived_camera_world_ty(), SSL_GeometryCameraCalibration::derived_camera_world_tz(), SSL_GeometryCameraCalibration::distortion(), SSL_GeometryData::field(), SSL_GeometryCameraCalibration::focal_length(), SSL_GeometryCameraCalibration::has_camera_id(), SSL_GeometryCameraCalibration::has_derived_camera_world_tx(), SSL_GeometryCameraCalibration::has_derived_camera_world_ty(), SSL_GeometryCameraCalibration::has_derived_camera_world_tz(), SSL_GeometryCameraCalibration::has_distortion(), SSL_GeometryData::has_field(), SSL_GeometryCameraCalibration::has_focal_length(), SSL_GeometryCameraCalibration::has_principal_point_x(), SSL_GeometryCameraCalibration::has_principal_point_y(), SSL_GeometryCameraCalibration::has_q0(), SSL_GeometryCameraCalibration::has_q1(), SSL_GeometryCameraCalibration::has_q2(), SSL_GeometryCameraCalibration::has_q3(), SSL_GeometryCameraCalibration::has_tx(), SSL_GeometryCameraCalibration::has_ty(), SSL_GeometryCameraCalibration::has_tz(), SSL_GeometryData::mutable_calib(), SSL_GeometryData::mutable_field(), SSL_GeometryCameraCalibration::principal_point_x(), SSL_GeometryCameraCalibration::principal_point_y(), SSL_GeometryCameraCalibration::q0(), SSL_GeometryCameraCalibration::q1(), SSL_GeometryCameraCalibration::q2(), SSL_GeometryCameraCalibration::q3(), SSL_GeometryData::release_field(), SSL_GeometryData::set_allocated_field(), SSL_GeometryCameraCalibration::set_camera_id(), SSL_GeometryCameraCalibration::set_derived_camera_world_tx(), SSL_GeometryCameraCalibration::set_derived_camera_world_ty(), SSL_GeometryCameraCalibration::set_derived_camera_world_tz(), SSL_GeometryCameraCalibration::set_distortion(), SSL_GeometryCameraCalibration::set_focal_length(), SSL_GeometryCameraCalibration::set_has_camera_id(), SSL_GeometryCameraCalibration::set_has_derived_camera_world_tx(), SSL_GeometryCameraCalibration::set_has_derived_camera_world_ty(), SSL_GeometryCameraCalibration::set_has_derived_camera_world_tz(), SSL_GeometryCameraCalibration::set_has_distortion(), SSL_GeometryData::set_has_field(), SSL_GeometryCameraCalibration::set_has_focal_length(), SSL_GeometryCameraCalibration::set_has_principal_point_x(), SSL_GeometryCameraCalibration::set_has_principal_point_y(), SSL_GeometryCameraCalibration::set_has_q0(), SSL_GeometryCameraCalibration::set_has_q1(), SSL_GeometryCameraCalibration::set_has_q2(), SSL_GeometryCameraCalibration::set_has_q3(), SSL_GeometryCameraCalibration::set_has_tx(), SSL_GeometryCameraCalibration::set_has_ty(), SSL_GeometryCameraCalibration::set_has_tz(), SSL_GeometryCameraCalibration::set_principal_point_x(), SSL_GeometryCameraCalibration::set_principal_point_y(), SSL_GeometryCameraCalibration::set_q0(), SSL_GeometryCameraCalibration::set_q1(), SSL_GeometryCameraCalibration::set_q2(), SSL_GeometryCameraCalibration::set_q3(), SSL_GeometryCameraCalibration::set_tx(), SSL_GeometryCameraCalibration::set_ty(), SSL_GeometryCameraCalibration::set_tz(), SSL_GeometryCameraCalibration::tx(), SSL_GeometryCameraCalibration::ty(), and SSL_GeometryCameraCalibration::tz().
{
   // @@protoc_insertion_point(field_list:SSL_GeometryFieldSize.field_arcs)
   return field_arcs_;
 }
int SSL_GeometryFieldSize::field_arcs_size () const inline
Definition at line 1723 of file messages_robocup_ssl_geometry.pb.h.
Referenced by main(), and GLSoccerView::updateFieldGeometry().
{
   return field_arcs_.size();
 }
google::protobuf::int32 SSL_GeometryFieldSize::field_length () const inline
Definition at line 676 of file messages_robocup_ssl_geometry.pb.h.
References field_length_.
Referenced by main(), PluginLegacyPublishGeometry::sendGeometry(), and SSL_FieldCicularArc::set_thickness().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.field_length)
   return field_length_;
 }
::google::protobuf::int32 SSL_GeometryFieldSize::field_length () const
const ::SSL_FieldLineSegment & SSL_GeometryFieldSize::field_lines (int index) const inline
Definition at line 1699 of file messages_robocup_ssl_geometry.pb.h.
Referenced by GLSoccerView::updateFieldGeometry().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.field_lines)
   return field_lines_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::SSL_FieldLineSegment > & SSL_GeometryFieldSize::field_lines () const inline
Definition at line 1717 of file messages_robocup_ssl_geometry.pb.h.
{
   // @@protoc_insertion_point(field_list:SSL_GeometryFieldSize.field_lines)
   return field_lines_;
 }
int SSL_GeometryFieldSize::field_lines_size () const inline
Definition at line 1693 of file messages_robocup_ssl_geometry.pb.h.
Referenced by main(), and GLSoccerView::updateFieldGeometry().
{
   return field_lines_.size();
 }
google::protobuf::int32 SSL_GeometryFieldSize::field_width () const inline
Definition at line 700 of file messages_robocup_ssl_geometry.pb.h.
References field_width_.
Referenced by main(), PluginLegacyPublishGeometry::sendGeometry(), and SSL_FieldCicularArc::set_thickness().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.field_width)
   return field_width_;
 }
::google::protobuf::int32 SSL_GeometryFieldSize::field_width () const
google::protobuf::int32 SSL_GeometryFieldSize::free_kick_from_defense_dist () const inline
Definition at line 916 of file messages_robocup_ssl_geometry.pb.h.
References free_kick_from_defense_dist_.
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.free_kick_from_defense_dist)
   return free_kick_from_defense_dist_;
 }
inline ::google::protobuf::Arena* SSL_GeometryFieldSize::GetArenaNoVirtual () const inline private
Definition at line 107 of file messages_robocup_ssl_geometry.pb.h.
{
     return NULL;
   }
inline ::google::protobuf::Arena* SSL_GeometryFieldSize::GetArenaNoVirtual () const inline private
Definition at line 613 of file messages_robocup_ssl_geometry.pb.h.
{
     return NULL;
   }
int SSL_GeometryFieldSize::GetCachedSize () const inline
Definition at line 100 of file messages_robocup_ssl_geometry.pb.h.
References _cached_size_, InternalSwap(), SetCachedSize(), SharedCtor(), and SharedDtor().
 { return _cached_size_; }
int SSL_GeometryFieldSize::GetCachedSize () const inline
Definition at line 606 of file messages_robocup_ssl_geometry.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata SSL_GeometryFieldSize::GetMetadata () const
Referenced by MaybeArenaPtr(), SSL_GeometryCameraCalibration::MaybeArenaPtr(), and SSL_GeometryData::MaybeArenaPtr().
::google::protobuf::Metadata SSL_GeometryFieldSize::GetMetadata () const
google::protobuf::int32 SSL_GeometryFieldSize::goal_depth () const inline
Definition at line 796 of file messages_robocup_ssl_geometry.pb.h.
References goal_depth_.
Referenced by main(), PluginLegacyPublishGeometry::sendGeometry(), and SSL_FieldCicularArc::set_thickness().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.goal_depth)
   return goal_depth_;
 }
::google::protobuf::int32 SSL_GeometryFieldSize::goal_depth () const
google::protobuf::int32 SSL_GeometryFieldSize::goal_wall_width () const inline
Definition at line 820 of file messages_robocup_ssl_geometry.pb.h.
References goal_wall_width_.
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.goal_wall_width)
   return goal_wall_width_;
 }
google::protobuf::int32 SSL_GeometryFieldSize::goal_width () const inline
Definition at line 772 of file messages_robocup_ssl_geometry.pb.h.
References goal_width_.
Referenced by main(), PluginLegacyPublishGeometry::sendGeometry(), and SSL_FieldCicularArc::set_thickness().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.goal_width)
   return goal_width_;
 }
::google::protobuf::int32 SSL_GeometryFieldSize::goal_width () const
bool SSL_GeometryFieldSize::has_boundary_width () const inline
Definition at line 711 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by SSL_FieldCicularArc::set_thickness().
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool SSL_GeometryFieldSize::has_boundary_width () const
bool SSL_GeometryFieldSize::has_center_circle_radius () const inline
Definition at line 831 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00000100u) != 0;
 }
bool SSL_GeometryFieldSize::has_defense_radius () const inline
Definition at line 855 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00000200u) != 0;
 }
bool SSL_GeometryFieldSize::has_defense_stretch () const inline
Definition at line 879 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00000400u) != 0;
 }
bool SSL_GeometryFieldSize::has_field_length () const inline
Definition at line 663 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by SSL_FieldCicularArc::set_thickness().
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool SSL_GeometryFieldSize::has_field_length () const
bool SSL_GeometryFieldSize::has_field_width () const inline
Definition at line 687 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by SSL_FieldCicularArc::set_thickness().
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool SSL_GeometryFieldSize::has_field_width () const
bool SSL_GeometryFieldSize::has_free_kick_from_defense_dist () const inline
Definition at line 903 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00000800u) != 0;
 }
bool SSL_GeometryFieldSize::has_goal_depth () const inline
Definition at line 783 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by SSL_FieldCicularArc::set_thickness().
{
   return (_has_bits_[0] & 0x00000040u) != 0;
 }
bool SSL_GeometryFieldSize::has_goal_depth () const
bool SSL_GeometryFieldSize::has_goal_wall_width () const inline
Definition at line 807 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00000080u) != 0;
 }
bool SSL_GeometryFieldSize::has_goal_width () const inline
Definition at line 759 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by SSL_FieldCicularArc::set_thickness().
{
   return (_has_bits_[0] & 0x00000020u) != 0;
 }
bool SSL_GeometryFieldSize::has_goal_width () const
bool SSL_GeometryFieldSize::has_line_width () const inline
Definition at line 639 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by MaybeArenaPtr().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool SSL_GeometryFieldSize::has_penalty_line_from_spot_dist () const inline
Definition at line 951 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00002000u) != 0;
 }
bool SSL_GeometryFieldSize::has_penalty_spot_from_field_line_dist () const inline
Definition at line 927 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00001000u) != 0;
 }
bool SSL_GeometryFieldSize::has_referee_width () const inline
Definition at line 735 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
static void SSL_GeometryFieldSize::InitAsDefaultInstance () static
static const SSL_GeometryFieldSize* SSL_GeometryFieldSize::internal_default_instance () inline static
Definition at line 70 of file messages_robocup_ssl_geometry.pb.h.
References _SSL_GeometryFieldSize_default_instance_, and Swap().
Referenced by SSL_GeometryData::field().
{
     return reinterpret_cast<const SSL_GeometryFieldSize*>(
                &_SSL_GeometryFieldSize_default_instance_);
   }
static const SSL_GeometryFieldSize* SSL_GeometryFieldSize::internal_default_instance () inline static
Definition at line 575 of file messages_robocup_ssl_geometry.pb.h.
References _SSL_GeometryFieldSize_default_instance_.
{
     return reinterpret_cast<const SSL_GeometryFieldSize*>(
                &_SSL_GeometryFieldSize_default_instance_);
   }
::google::protobuf::uint8* SSL_GeometryFieldSize::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
Referenced by New(), SSL_GeometryCameraCalibration::New(), SSL_GeometryData::New(), SerializeWithCachedSizesToArray(), SSL_GeometryCameraCalibration::SerializeWithCachedSizesToArray(), and SSL_GeometryData::SerializeWithCachedSizesToArray().
::google::protobuf::uint8* SSL_GeometryFieldSize::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void SSL_GeometryFieldSize::InternalSwap (SSL_GeometryFieldSize * other) private
Referenced by GetCachedSize(), SSL_GeometryCameraCalibration::GetCachedSize(), and SSL_GeometryData::GetCachedSize().
void SSL_GeometryFieldSize::InternalSwap (SSL_GeometryFieldSize * other) private
bool SSL_GeometryFieldSize::IsInitialized () const
Referenced by New(), SSL_GeometryCameraCalibration::New(), and SSL_GeometryData::New().
bool SSL_GeometryFieldSize::IsInitialized () const
google::protobuf::int32 SSL_GeometryFieldSize::line_width () const inline
Definition at line 652 of file messages_robocup_ssl_geometry.pb.h.
References line_width_.
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.line_width)
   return line_width_;
 }
void* SSL_GeometryFieldSize::MaybeArenaPtr () const inline private
Definition at line 110 of file messages_robocup_ssl_geometry.pb.h.
References clear_line_width(), GetMetadata(), and has_line_width().
{
     return NULL;
   }
void* SSL_GeometryFieldSize::MaybeArenaPtr () const inline private
Definition at line 616 of file messages_robocup_ssl_geometry.pb.h.
{
     return NULL;
   }
void SSL_GeometryFieldSize::MergeFrom (const ::google::protobuf::Message & from)
Referenced by New(), SSL_GeometryCameraCalibration::New(), and SSL_GeometryData::New().
void SSL_GeometryFieldSize::MergeFrom (const SSL_GeometryFieldSize & from)
void SSL_GeometryFieldSize::MergeFrom (const ::google::protobuf::Message & from)
void SSL_GeometryFieldSize::MergeFrom (const SSL_GeometryFieldSize & from)
bool SSL_GeometryFieldSize::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Referenced by New(), SSL_GeometryCameraCalibration::New(), and SSL_GeometryData::New().
bool SSL_GeometryFieldSize::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
SSL_FieldCicularArc * SSL_GeometryFieldSize::mutable_field_arcs (int index) inline
Definition at line 1733 of file messages_robocup_ssl_geometry.pb.h.
{
   // @@protoc_insertion_point(field_mutable:SSL_GeometryFieldSize.field_arcs)
   return field_arcs_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::SSL_FieldCicularArc > * SSL_GeometryFieldSize::mutable_field_arcs () inline
Definition at line 1742 of file messages_robocup_ssl_geometry.pb.h.
{
   // @@protoc_insertion_point(field_mutable_list:SSL_GeometryFieldSize.field_arcs)
   return &field_arcs_;
 }
SSL_FieldLineSegment * SSL_GeometryFieldSize::mutable_field_lines (int index) inline
Definition at line 1703 of file messages_robocup_ssl_geometry.pb.h.
{
   // @@protoc_insertion_point(field_mutable:SSL_GeometryFieldSize.field_lines)
   return field_lines_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::SSL_FieldLineSegment > * SSL_GeometryFieldSize::mutable_field_lines () inline
Definition at line 1712 of file messages_robocup_ssl_geometry.pb.h.
{
   // @@protoc_insertion_point(field_mutable_list:SSL_GeometryFieldSize.field_lines)
   return &field_lines_;
 }
inline ::google::protobuf::UnknownFieldSet* SSL_GeometryFieldSize::mutable_unknown_fields () inline
Definition at line 63 of file messages_robocup_ssl_geometry.pb.h.
References _internal_metadata_, default_instance(), and descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
inline ::google::protobuf::UnknownFieldSet* SSL_GeometryFieldSize::mutable_unknown_fields () inline
Definition at line 567 of file messages_robocup_ssl_geometry.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
SSL_GeometryFieldSize* SSL_GeometryFieldSize::New () const inline
Definition at line 79 of file messages_robocup_ssl_geometry.pb.h.
References ByteSizeLong(), Clear(), CopyFrom(), InternalSerializeWithCachedSizesToArray(), IsInitialized(), MergeFrom(), MergePartialFromCodedStream(), New(), SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New(), SSL_GeometryCameraCalibration::New(), and SSL_GeometryData::New().
 { return New(NULL); }
SSL_GeometryFieldSize* SSL_GeometryFieldSize::New (::google::protobuf::Arena * arena) const
SSL_GeometryFieldSize* SSL_GeometryFieldSize::New () const inline
Definition at line 589 of file messages_robocup_ssl_geometry.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_GeometryFieldSize* SSL_GeometryFieldSize::New (::google::protobuf::Arena * arena) const
SSL_GeometryFieldSize& SSL_GeometryFieldSize::operator= (const SSL_GeometryFieldSize & from) inline
Definition at line 54 of file messages_robocup_ssl_geometry.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
SSL_GeometryFieldSize& SSL_GeometryFieldSize::operator= (const SSL_GeometryFieldSize & from) inline
Definition at line 545 of file messages_robocup_ssl_geometry.pb.h.
{
     CopyFrom(from);
     return *this;
   }
google::protobuf::int32 SSL_GeometryFieldSize::penalty_line_from_spot_dist () const inline
Definition at line 964 of file messages_robocup_ssl_geometry.pb.h.
References penalty_line_from_spot_dist_.
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.penalty_line_from_spot_dist)
   return penalty_line_from_spot_dist_;
 }
google::protobuf::int32 SSL_GeometryFieldSize::penalty_spot_from_field_line_dist () const inline
Definition at line 940 of file messages_robocup_ssl_geometry.pb.h.
References penalty_spot_from_field_line_dist_.
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.penalty_spot_from_field_line_dist)
   return penalty_spot_from_field_line_dist_;
 }
friendconst ::google::protobuf::uint32* SSL_GeometryFieldSize::protobuf_Offsets_messages_5frobocup_5fssl_5fgeometry_2eproto () private
google::protobuf::int32 SSL_GeometryFieldSize::referee_width () const inline
Definition at line 748 of file messages_robocup_ssl_geometry.pb.h.
References referee_width_.
{
   // @@protoc_insertion_point(field_get:SSL_GeometryFieldSize.referee_width)
   return referee_width_;
 }
size_t SSL_GeometryFieldSize::RequiredFieldsByteSizeFallback () const private
size_t SSL_GeometryFieldSize::RequiredFieldsByteSizeFallback () const private
void SSL_GeometryFieldSize::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Referenced by New(), SSL_GeometryCameraCalibration::New(), and SSL_GeometryData::New().
void SSL_GeometryFieldSize::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* SSL_GeometryFieldSize::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 96 of file messages_robocup_ssl_geometry.pb.h.
References InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void SSL_GeometryFieldSize::set_boundary_width (::google::protobuf::int32 value) inline
Definition at line 728 of file messages_robocup_ssl_geometry.pb.h.
References boundary_width_, and set_has_boundary_width().
Referenced by SSLWorld::generatePacket(), SSL_FieldCicularArc::set_thickness(), and RoboCupField::toProtoBuffer().
{
   set_has_boundary_width();
   boundary_width_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.boundary_width)
 }
void SSL_GeometryFieldSize::set_boundary_width (::google::protobuf::int32 value)
void SSL_GeometryFieldSize::set_center_circle_radius (::google::protobuf::int32 value) inline
Definition at line 848 of file messages_robocup_ssl_geometry.pb.h.
References center_circle_radius_, and set_has_center_circle_radius().
{
   set_has_center_circle_radius();
   center_circle_radius_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.center_circle_radius)
 }
void SSL_GeometryFieldSize::set_defense_radius (::google::protobuf::int32 value) inline
Definition at line 872 of file messages_robocup_ssl_geometry.pb.h.
References defense_radius_, and set_has_defense_radius().
{
   set_has_defense_radius();
   defense_radius_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.defense_radius)
 }
void SSL_GeometryFieldSize::set_defense_stretch (::google::protobuf::int32 value) inline
Definition at line 896 of file messages_robocup_ssl_geometry.pb.h.
References defense_stretch_, and set_has_defense_stretch().
{
   set_has_defense_stretch();
   defense_stretch_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.defense_stretch)
 }
void SSL_GeometryFieldSize::set_field_length (::google::protobuf::int32 value) inline
Definition at line 680 of file messages_robocup_ssl_geometry.pb.h.
References field_length_, and set_has_field_length().
Referenced by SSLWorld::generatePacket(), SSL_FieldCicularArc::set_thickness(), and RoboCupField::toProtoBuffer().
{
   set_has_field_length();
   field_length_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.field_length)
 }
void SSL_GeometryFieldSize::set_field_length (::google::protobuf::int32 value)
void SSL_GeometryFieldSize::set_field_width (::google::protobuf::int32 value) inline
Definition at line 704 of file messages_robocup_ssl_geometry.pb.h.
References field_width_, and set_has_field_width().
Referenced by SSLWorld::generatePacket(), SSL_FieldCicularArc::set_thickness(), and RoboCupField::toProtoBuffer().
{
   set_has_field_width();
   field_width_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.field_width)
 }
void SSL_GeometryFieldSize::set_field_width (::google::protobuf::int32 value)
void SSL_GeometryFieldSize::set_free_kick_from_defense_dist (::google::protobuf::int32 value) inline
Definition at line 920 of file messages_robocup_ssl_geometry.pb.h.
References free_kick_from_defense_dist_, and set_has_free_kick_from_defense_dist().
{
   set_has_free_kick_from_defense_dist();
   free_kick_from_defense_dist_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.free_kick_from_defense_dist)
 }
void SSL_GeometryFieldSize::set_goal_depth (::google::protobuf::int32 value) inline
Definition at line 800 of file messages_robocup_ssl_geometry.pb.h.
References goal_depth_, and set_has_goal_depth().
Referenced by SSLWorld::generatePacket(), SSL_FieldCicularArc::set_thickness(), and RoboCupField::toProtoBuffer().
{
   set_has_goal_depth();
   goal_depth_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.goal_depth)
 }
void SSL_GeometryFieldSize::set_goal_depth (::google::protobuf::int32 value)
void SSL_GeometryFieldSize::set_goal_wall_width (::google::protobuf::int32 value) inline
Definition at line 824 of file messages_robocup_ssl_geometry.pb.h.
References goal_wall_width_, and set_has_goal_wall_width().
{
   set_has_goal_wall_width();
   goal_wall_width_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.goal_wall_width)
 }
void SSL_GeometryFieldSize::set_goal_width (::google::protobuf::int32 value) inline
Definition at line 776 of file messages_robocup_ssl_geometry.pb.h.
References goal_width_, and set_has_goal_width().
Referenced by SSLWorld::generatePacket(), SSL_FieldCicularArc::set_thickness(), and RoboCupField::toProtoBuffer().
{
   set_has_goal_width();
   goal_width_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.goal_width)
 }
void SSL_GeometryFieldSize::set_goal_width (::google::protobuf::int32 value)
void SSL_GeometryFieldSize::set_has_boundary_width () inline private
Definition at line 714 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_boundary_width(), and SSL_FieldCicularArc::set_thickness().
{
   _has_bits_[0] |= 0x00000008u;
 }
void SSL_GeometryFieldSize::set_has_boundary_width () private
void SSL_GeometryFieldSize::set_has_center_circle_radius () inline private
Definition at line 834 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_center_circle_radius().
{
   _has_bits_[0] |= 0x00000100u;
 }
void SSL_GeometryFieldSize::set_has_defense_radius () inline private
Definition at line 858 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_defense_radius().
{
   _has_bits_[0] |= 0x00000200u;
 }
void SSL_GeometryFieldSize::set_has_defense_stretch () inline private
Definition at line 882 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_defense_stretch().
{
   _has_bits_[0] |= 0x00000400u;
 }
void SSL_GeometryFieldSize::set_has_field_length () inline private
Definition at line 666 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_field_length(), and SSL_FieldCicularArc::set_thickness().
{
   _has_bits_[0] |= 0x00000002u;
 }
void SSL_GeometryFieldSize::set_has_field_length () private
void SSL_GeometryFieldSize::set_has_field_width () inline private
Definition at line 690 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_field_width(), and SSL_FieldCicularArc::set_thickness().
{
   _has_bits_[0] |= 0x00000004u;
 }
void SSL_GeometryFieldSize::set_has_field_width () private
void SSL_GeometryFieldSize::set_has_free_kick_from_defense_dist () inline private
Definition at line 906 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_free_kick_from_defense_dist().
{
   _has_bits_[0] |= 0x00000800u;
 }
void SSL_GeometryFieldSize::set_has_goal_depth () inline private
Definition at line 786 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_goal_depth(), and SSL_FieldCicularArc::set_thickness().
{
   _has_bits_[0] |= 0x00000040u;
 }
void SSL_GeometryFieldSize::set_has_goal_depth () private
void SSL_GeometryFieldSize::set_has_goal_wall_width () inline private
Definition at line 810 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_goal_wall_width().
{
   _has_bits_[0] |= 0x00000080u;
 }
void SSL_GeometryFieldSize::set_has_goal_width () inline private
Definition at line 762 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_goal_width(), and SSL_FieldCicularArc::set_thickness().
{
   _has_bits_[0] |= 0x00000020u;
 }
void SSL_GeometryFieldSize::set_has_goal_width () private
void SSL_GeometryFieldSize::set_has_line_width () inline private
Definition at line 642 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_line_width().
{
   _has_bits_[0] |= 0x00000001u;
 }
void SSL_GeometryFieldSize::set_has_penalty_line_from_spot_dist () inline private
Definition at line 954 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_penalty_line_from_spot_dist().
{
   _has_bits_[0] |= 0x00002000u;
 }
void SSL_GeometryFieldSize::set_has_penalty_spot_from_field_line_dist () inline private
Definition at line 930 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_penalty_spot_from_field_line_dist().
{
   _has_bits_[0] |= 0x00001000u;
 }
void SSL_GeometryFieldSize::set_has_referee_width () inline private
Definition at line 738 of file messages_robocup_ssl_geometry.pb.h.
References _has_bits_.
Referenced by set_referee_width().
{
   _has_bits_[0] |= 0x00000010u;
 }
void SSL_GeometryFieldSize::set_line_width (::google::protobuf::int32 value) inline
Definition at line 656 of file messages_robocup_ssl_geometry.pb.h.
References line_width_, and set_has_line_width().
{
   set_has_line_width();
   line_width_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.line_width)
 }
void SSL_GeometryFieldSize::set_penalty_line_from_spot_dist (::google::protobuf::int32 value) inline
Definition at line 968 of file messages_robocup_ssl_geometry.pb.h.
References penalty_line_from_spot_dist_, and set_has_penalty_line_from_spot_dist().
{
   set_has_penalty_line_from_spot_dist();
   penalty_line_from_spot_dist_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.penalty_line_from_spot_dist)
 }
void SSL_GeometryFieldSize::set_penalty_spot_from_field_line_dist (::google::protobuf::int32 value) inline
Definition at line 944 of file messages_robocup_ssl_geometry.pb.h.
References penalty_spot_from_field_line_dist_, and set_has_penalty_spot_from_field_line_dist().
{
   set_has_penalty_spot_from_field_line_dist();
   penalty_spot_from_field_line_dist_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.penalty_spot_from_field_line_dist)
 }
void SSL_GeometryFieldSize::set_referee_width (::google::protobuf::int32 value) inline
Definition at line 752 of file messages_robocup_ssl_geometry.pb.h.
References referee_width_, and set_has_referee_width().
{
   set_has_referee_width();
   referee_width_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryFieldSize.referee_width)
 }
void SSL_GeometryFieldSize::SetCachedSize (int size) const private
Referenced by GetCachedSize(), SSL_GeometryCameraCalibration::GetCachedSize(), and SSL_GeometryData::GetCachedSize().
void SSL_GeometryFieldSize::SetCachedSize (int size) const private
void SSL_GeometryFieldSize::SharedCtor () private
Referenced by GetCachedSize(), SSL_GeometryCameraCalibration::GetCachedSize(), and SSL_GeometryData::GetCachedSize().
void SSL_GeometryFieldSize::SharedCtor () private
void SSL_GeometryFieldSize::SharedDtor () private
Referenced by GetCachedSize(), SSL_GeometryCameraCalibration::GetCachedSize(), and SSL_GeometryData::GetCachedSize().
void SSL_GeometryFieldSize::SharedDtor () private
void SSL_GeometryFieldSize::Swap (SSL_GeometryFieldSize * other)
Referenced by internal_default_instance(), SSL_GeometryCameraCalibration::internal_default_instance(), and SSL_GeometryData::internal_default_instance().
void SSL_GeometryFieldSize::Swap (SSL_GeometryFieldSize * other)
const ::google::protobuf::UnknownFieldSet& SSL_GeometryFieldSize::unknown_fields () const inline
Definition at line 59 of file messages_robocup_ssl_geometry.pb.h.
References _internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
const ::google::protobuf::UnknownFieldSet& SSL_GeometryFieldSize::unknown_fields () const inline
Definition at line 564 of file messages_robocup_ssl_geometry.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
SSL_GeometryFieldSize::void::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryFieldSizeImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::TableStruct friend
Definition at line 712 of file messages_robocup_ssl_geometry.pb.h.
void protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_impl () friend
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto_impl () friend
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto () friend
void swap (SSL_GeometryFieldSize & a, SSL_GeometryFieldSize & b) friend
Definition at line 583 of file messages_robocup_ssl_geometry.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int SSL_GeometryFieldSize::_cached_size_ mutable private
Definition at line 255 of file messages_robocup_ssl_geometry.pb.h.
Referenced by GetCachedSize(), SSL_GeometryCameraCalibration::GetCachedSize(), and SSL_GeometryData::GetCachedSize().
google::protobuf::internal::HasBits< 1 > SSL_GeometryFieldSize::_has_bits_ private
Definition at line 254 of file messages_robocup_ssl_geometry.pb.h.
Referenced by clear_has_boundary_width(), SSL_GeometryCameraCalibration::clear_has_camera_id(), clear_has_center_circle_radius(), clear_has_defense_radius(), clear_has_defense_stretch(), SSL_GeometryCameraCalibration::clear_has_derived_camera_world_tx(), SSL_GeometryCameraCalibration::clear_has_derived_camera_world_ty(), SSL_GeometryCameraCalibration::clear_has_derived_camera_world_tz(), SSL_GeometryCameraCalibration::clear_has_distortion(), SSL_GeometryData::clear_has_field(), clear_has_field_length(), clear_has_field_width(), SSL_GeometryCameraCalibration::clear_has_focal_length(), clear_has_free_kick_from_defense_dist(), clear_has_goal_depth(), clear_has_goal_wall_width(), clear_has_goal_width(), clear_has_line_width(), clear_has_penalty_line_from_spot_dist(), clear_has_penalty_spot_from_field_line_dist(), SSL_GeometryCameraCalibration::clear_has_principal_point_x(), SSL_GeometryCameraCalibration::clear_has_principal_point_y(), SSL_GeometryCameraCalibration::clear_has_q0(), SSL_GeometryCameraCalibration::clear_has_q1(), SSL_GeometryCameraCalibration::clear_has_q2(), SSL_GeometryCameraCalibration::clear_has_q3(), clear_has_referee_width(), SSL_GeometryCameraCalibration::clear_has_tx(), SSL_GeometryCameraCalibration::clear_has_ty(), SSL_GeometryCameraCalibration::clear_has_tz(), has_boundary_width(), SSL_GeometryCameraCalibration::has_camera_id(), has_center_circle_radius(), has_defense_radius(), has_defense_stretch(), SSL_GeometryCameraCalibration::has_derived_camera_world_tx(), SSL_GeometryCameraCalibration::has_derived_camera_world_ty(), SSL_GeometryCameraCalibration::has_derived_camera_world_tz(), SSL_GeometryCameraCalibration::has_distortion(), SSL_GeometryData::has_field(), has_field_length(), has_field_width(), SSL_GeometryCameraCalibration::has_focal_length(), has_free_kick_from_defense_dist(), has_goal_depth(), has_goal_wall_width(), has_goal_width(), has_line_width(), has_penalty_line_from_spot_dist(), has_penalty_spot_from_field_line_dist(), SSL_GeometryCameraCalibration::has_principal_point_x(), SSL_GeometryCameraCalibration::has_principal_point_y(), SSL_GeometryCameraCalibration::has_q0(), SSL_GeometryCameraCalibration::has_q1(), SSL_GeometryCameraCalibration::has_q2(), SSL_GeometryCameraCalibration::has_q3(), has_referee_width(), SSL_GeometryCameraCalibration::has_tx(), SSL_GeometryCameraCalibration::has_ty(), SSL_GeometryCameraCalibration::has_tz(), set_has_boundary_width(), SSL_GeometryCameraCalibration::set_has_camera_id(), set_has_center_circle_radius(), set_has_defense_radius(), set_has_defense_stretch(), SSL_GeometryCameraCalibration::set_has_derived_camera_world_tx(), SSL_GeometryCameraCalibration::set_has_derived_camera_world_ty(), SSL_GeometryCameraCalibration::set_has_derived_camera_world_tz(), SSL_GeometryCameraCalibration::set_has_distortion(), SSL_GeometryData::set_has_field(), set_has_field_length(), set_has_field_width(), SSL_GeometryCameraCalibration::set_has_focal_length(), set_has_free_kick_from_defense_dist(), set_has_goal_depth(), set_has_goal_wall_width(), set_has_goal_width(), set_has_line_width(), set_has_penalty_line_from_spot_dist(), set_has_penalty_spot_from_field_line_dist(), SSL_GeometryCameraCalibration::set_has_principal_point_x(), SSL_GeometryCameraCalibration::set_has_principal_point_y(), SSL_GeometryCameraCalibration::set_has_q0(), SSL_GeometryCameraCalibration::set_has_q1(), SSL_GeometryCameraCalibration::set_has_q2(), SSL_GeometryCameraCalibration::set_has_q3(), set_has_referee_width(), SSL_GeometryCameraCalibration::set_has_tx(), SSL_GeometryCameraCalibration::set_has_ty(), and SSL_GeometryCameraCalibration::set_has_tz().
google::protobuf::internal::InternalMetadataWithArena SSL_GeometryFieldSize::_internal_metadata_ private
Definition at line 253 of file messages_robocup_ssl_geometry.pb.h.
Referenced by mutable_unknown_fields(), SSL_GeometryCameraCalibration::mutable_unknown_fields(), SSL_GeometryData::mutable_unknown_fields(), unknown_fields(), SSL_GeometryCameraCalibration::unknown_fields(), and SSL_GeometryData::unknown_fields().
google::protobuf::int32 SSL_GeometryFieldSize::boundary_width_ private
Definition at line 259 of file messages_robocup_ssl_geometry.pb.h.
Referenced by boundary_width(), clear_boundary_width(), and set_boundary_width().
::google::protobuf::int32 SSL_GeometryFieldSize::center_circle_radius_ private
Definition at line 264 of file messages_robocup_ssl_geometry.pb.h.
Referenced by center_circle_radius(), clear_center_circle_radius(), and set_center_circle_radius().
::google::protobuf::int32 SSL_GeometryFieldSize::defense_radius_ private
Definition at line 265 of file messages_robocup_ssl_geometry.pb.h.
Referenced by clear_defense_radius(), defense_radius(), and set_defense_radius().
::google::protobuf::int32 SSL_GeometryFieldSize::defense_stretch_ private
Definition at line 266 of file messages_robocup_ssl_geometry.pb.h.
Referenced by clear_defense_stretch(), defense_stretch(), and set_defense_stretch().
::google::protobuf::RepeatedPtrField< ::SSL_FieldCicularArc > SSL_GeometryFieldSize::field_arcs_ private
Definition at line 706 of file messages_robocup_ssl_geometry.pb.h.
google::protobuf::int32 SSL_GeometryFieldSize::field_length_ private
Definition at line 257 of file messages_robocup_ssl_geometry.pb.h.
Referenced by clear_field_length(), field_length(), and set_field_length().
::google::protobuf::RepeatedPtrField< ::SSL_FieldLineSegment > SSL_GeometryFieldSize::field_lines_ private
Definition at line 705 of file messages_robocup_ssl_geometry.pb.h.
google::protobuf::int32 SSL_GeometryFieldSize::field_width_ private
Definition at line 258 of file messages_robocup_ssl_geometry.pb.h.
Referenced by clear_field_width(), field_width(), and set_field_width().
::google::protobuf::int32 SSL_GeometryFieldSize::free_kick_from_defense_dist_ private
Definition at line 267 of file messages_robocup_ssl_geometry.pb.h.
Referenced by clear_free_kick_from_defense_dist(), free_kick_from_defense_dist(), and set_free_kick_from_defense_dist().
google::protobuf::int32 SSL_GeometryFieldSize::goal_depth_ private
Definition at line 262 of file messages_robocup_ssl_geometry.pb.h.
Referenced by clear_goal_depth(), goal_depth(), and set_goal_depth().
::google::protobuf::int32 SSL_GeometryFieldSize::goal_wall_width_ private
Definition at line 263 of file messages_robocup_ssl_geometry.pb.h.
Referenced by clear_goal_wall_width(), goal_wall_width(), and set_goal_wall_width().
google::protobuf::int32 SSL_GeometryFieldSize::goal_width_ private
Definition at line 261 of file messages_robocup_ssl_geometry.pb.h.
Referenced by clear_goal_width(), goal_width(), and set_goal_width().
static const int SSL_GeometryFieldSize::kBoundaryWidthFieldNumber = 4 static
Definition at line 145 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_GeometryFieldSize::kCenterCircleRadiusFieldNumber = 9 static
Definition at line 180 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_GeometryFieldSize::kDefenseRadiusFieldNumber = 10 static
Definition at line 187 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_GeometryFieldSize::kDefenseStretchFieldNumber = 11 static
Definition at line 194 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_GeometryFieldSize::kFieldArcsFieldNumber = 7 static
Definition at line 642 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryFieldSize::kFieldLengthFieldNumber = 2 static
Definition at line 131 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_GeometryFieldSize::kFieldLinesFieldNumber = 6 static
Definition at line 630 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryFieldSize::kFieldWidthFieldNumber = 3 static
Definition at line 138 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_GeometryFieldSize::kFreeKickFromDefenseDistFieldNumber = 12 static
Definition at line 201 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryFieldSize::kGoalDepthFieldNumber = 7 static
Definition at line 166 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_GeometryFieldSize::kGoalWallWidthFieldNumber = 8 static
Definition at line 173 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryFieldSize::kGoalWidthFieldNumber = 6 static
Definition at line 159 of file messages_robocup_ssl_geometry.pb.h.
PROTOBUF_CONSTEXPR int const SSL_GeometryFieldSize::kIndexInFileMessages static
Initial value:
=
    3
Definition at line 579 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_GeometryFieldSize::kLineWidthFieldNumber = 1 static
Definition at line 124 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_GeometryFieldSize::kPenaltyLineFromSpotDistFieldNumber = 14 static
Definition at line 215 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_GeometryFieldSize::kPenaltySpotFromFieldLineDistFieldNumber = 13 static
Definition at line 208 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_GeometryFieldSize::kRefereeWidthFieldNumber = 5 static
Definition at line 152 of file messages_robocup_ssl_geometry.pb.h.
::google::protobuf::int32 SSL_GeometryFieldSize::line_width_ private
Definition at line 256 of file messages_robocup_ssl_geometry.pb.h.
Referenced by clear_line_width(), line_width(), and set_line_width().
::google::protobuf::int32 SSL_GeometryFieldSize::penalty_line_from_spot_dist_ private
Definition at line 269 of file messages_robocup_ssl_geometry.pb.h.
Referenced by clear_penalty_line_from_spot_dist(), penalty_line_from_spot_dist(), and set_penalty_line_from_spot_dist().
::google::protobuf::int32 SSL_GeometryFieldSize::penalty_spot_from_field_line_dist_ private
Definition at line 268 of file messages_robocup_ssl_geometry.pb.h.
Referenced by clear_penalty_spot_from_field_line_dist(), penalty_spot_from_field_line_dist(), and set_penalty_spot_from_field_line_dist().
::google::protobuf::int32 SSL_GeometryFieldSize::referee_width_ private
Definition at line 260 of file messages_robocup_ssl_geometry.pb.h.
Referenced by clear_referee_width(), referee_width(), and set_referee_width().
The documentation for this class was generated from the following file:
grsim_comm/include/proto/messages_robocup_ssl_geometry.pb.h