Documentation: VarTypes::VarBlob Class Reference
VarTypes::VarBlob Class Reference
A Vartype for storing binary data.
#include <VarBlob.h>
Public Member Functions
VarBlob (uint8_t *external_pointer, int maxsize, string name="")
VarBlob (int maxsize=0, string name="")
virtual ~VarBlob ()
virtual uint8_t * getDataPointer () const
virtual long getDataSize () const
virtual void allocate (int size)
virtual void clearData ()
virtual void setDataPointer (uint8_t *pointer, int size)
virtual void printdebug () const
virtual void getSerialString (string &val) const
virtual void setSerialString (const string &val)
virtual void getBinarySerialString (string &val) const
virtual void setBinarySerialString (const string &val)
virtual VarTypeId getType () const
virtual string getString () const
virtual bool hasValue () const
virtual bool setString (const string &val)
virtual QWidget * createEditor (const VarItemDelegate *delegate, QWidget *parent, const QStyleOptionViewItem &option)
Public Member Functions inherited from VarTypes::VarType
VarType (string name="")
virtual ~VarType ()
virtual vector< VarType * > getChildren () const
virtual void deleteAllChildren ()
virtual void setName (string name)
Set the string label of this node.
virtual string getName () const
Get the string label of this node.
virtual void resetToDefault ()
Reset the values of this node to default.
virtual VarTypeFlag getFlags () const
virtual void setFlags (VarTypeFlag f)
virtual void addFlags (VarTypeFlag f)
virtual void removeFlags (VarTypeFlag f)
virtual bool areFlagsSet (VarTypeFlag f) const
VarType * findChild (string label) const
void writeXML (XMLNode &parent, bool blind_append=true)
Write the contents of this VarType node to an XMLNode.
void readXML (XMLNode &us)
Let this VarType node load the contents of an XMLNode.
virtual void setEditorData (const VarItemDelegate *delegate, QWidget *editor) const
virtual void setModelData (const VarItemDelegate *delegate, QWidget *editor)
virtual QSize sizeHint (const VarItemDelegate *delegate, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void paint (const VarItemDelegate *delegate, QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * clone () const
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
string getBinarySerialString () const
string getSerialString () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Protected Attributes
long _dsize
uint8_t * _dpointer
bool _dsize_limited
Protected Attributes inherited from VarTypes::VarType
QMutex * _mutex
VarTypeFlag _flags
string _name
Additional Inherited Members
Public Slots inherited from VarTypes::VarType
void mvcEditCompleted ()
A slot to receive signals from a model-view system that editing of this item was just completed.
Signals inherited from VarTypes::VarType
void hasChanged (VarType *)
void wasEdited (VarType *)
void XMLwasRead (VarType *)
This signal is triggered if data was written from an xml node.
void XMLwasWritten (VarType *)
This signal is triggered if data was written to an xml node.
Static Public Member Functions inherited from VarTypes::VarType
static void deleteAllVarChildren (XMLNode &node)
Clear an XMLNode's list of children.
static vector< VarType * > readChildrenHelper (XMLNode &parent, vector< VarType * > existing_children, bool only_update_existing, bool blind_append)
A helper function to read a list of children from XML and convert it to a vector of VarType nodes.
Protected Member Functions inherited from VarTypes::VarType
virtual void lock () const
virtual void unlock () const
virtual void changed ()
virtual void updateAttributes (XMLNode &us) const
virtual void updateText (XMLNode &us) const
virtual void updateChildren (XMLNode &us) const
virtual void readAttributes (XMLNode &us)
virtual void readText (XMLNode &us)
virtual void readChildren (XMLNode &us)
virtual void loadExternal ()
Static Protected Member Functions inherited from VarTypes::VarType
static string fixString (const char *cst)
static string intToString (int val)
static string doubleToString (double val)
static XMLNode findOrAppendChild (XMLNode &parent, string key, string val)
Detailed Description
A Vartype for storing binary data.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
The VarBlob Vartype allows for storage of any continuous binary string. It will automatically ensure that the data will be converted to/from base64 when storing/loading to/from XML.
Note, that to use this VarType, you will first have to manually allocate a data-block and supply that data-pointer and a max-size as arguments to the VarBlob.
Alternatively, you can use its allocate(size) function to construct the data-block
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 47 of file VarBlob.h.
Constructor & Destructor Documentation
VarTypes::VarBlob::VarBlob (uint8_t * external_pointer, int maxsize, string name = "") inline
Definition at line 56 of file VarBlob.h.
References VarTypes::VarType::changed().
                                                                      : VarType(name)
     {
       if (external_pointer==0 || maxsize<=0) {
         _dpointer=external_pointer;
         _dsize=maxsize;
         _dsize_limited=false;
       } else {
         _dpointer=external_pointer;
         _dsize=maxsize;
         _dsize_limited=true;
       }
       changed();
     }
VarTypes::VarBlob::VarBlob (int maxsize = 0, string name = "") inline
Definition at line 70 of file VarBlob.h.
References allocate().
                                            : VarType(name)
     {
       if (maxsize > 0) {
         _dsize_limited=true;
       } else {
         _dsize_limited=false;
       }
       _dpointer=0;
       _dsize=0;
       allocate(maxsize);
     }
virtual VarTypes::VarBlob::~VarBlob () inline virtual
Definition at line 82 of file VarBlob.h.
 {}
Member Function Documentation
virtual void VarTypes::VarBlob::allocate (int size) inline virtual
Definition at line 87 of file VarBlob.h.
References _dpointer, and VarTypes::VarType::changed().
Referenced by VarBlob().
{
       if (_dpointer != 0) delete[] _dpointer;
       if (size<=0) {
         _dsize=0;
         _dpointer=0;
       } else {
         _dsize=size;
         _dpointer=new uint8_t[size];
       }
       changed();
     }
virtual void VarTypes::VarBlob::clearData () inline virtual
Definition at line 99 of file VarBlob.h.
References _dpointer, and VarTypes::VarType::changed().
{
       if (_dpointer != 0) delete _dpointer;
       _dsize=0;
       changed();
     }
virtual QWidget* VarTypes::VarBlob::createEditor (const VarItemDelegate * delegate, QWidget * parent, const QStyleOptionViewItem & option) inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 145 of file VarBlob.h.
{
       (void)delegate;
       (void)option;
       (void)parent;
       return 0;
     }
virtual void VarTypes::VarBlob::getBinarySerialString (string & val) const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 125 of file VarBlob.h.
References getDataPointer(), and getDataSize().
{
       val.assign((const char*)getDataPointer(),getDataSize());
     }
virtual uint8_t* VarTypes::VarBlob::getDataPointer () const inline virtual
Definition at line 84 of file VarBlob.h.
References _dpointer.
Referenced by getBinarySerialString(), getSerialString(), setBinarySerialString(), and setSerialString().
 { return _dpointer; };
virtual long VarTypes::VarBlob::getDataSize () const inline virtual
Definition at line 85 of file VarBlob.h.
References _dsize.
Referenced by getBinarySerialString(), getSerialString(), setBinarySerialString(), and setSerialString().
 { return _dsize; } ;
virtual void VarTypes::VarBlob::getSerialString (string & val) const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 116 of file VarBlob.h.
References VarTypes::XMLParserBase64Tool::encode(), getDataPointer(), getDataSize(), and VarTypes::VarBase64::getTool().
{
       VarBase64::getTool()->encode(getDataPointer(),getDataSize(), val,1);
     }
virtual string VarTypes::VarBlob::getString () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 139 of file VarBlob.h.
 { return "Pointer";  };
virtual VarTypeId VarTypes::VarBlob::getType () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 138 of file VarBlob.h.
References VarTypes::VARTYPE_ID_BLOB.
 { return VARTYPE_ID_BLOB; };
virtual bool VarTypes::VarBlob::hasValue () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 140 of file VarBlob.h.
 { return false; };
virtual void VarTypes::VarBlob::printdebug () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 111 of file VarBlob.h.
     {
       printf("Data Blob pointer %p , size: %d\n",_dpointer,(int)_dsize);
     }
virtual void VarTypes::VarBlob::setBinarySerialString (const string & val) inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 129 of file VarBlob.h.
References VarTypes::VarType::changed(), getDataPointer(), and getDataSize().
{
       long len = val.length();
       long maxlen = getDataSize();
       if (len > maxlen) len=maxlen;
       memcpy(getDataPointer(),val.data(), len);
       changed();
     }
virtual void VarTypes::VarBlob::setDataPointer (uint8_t * pointer, int size) inline virtual
Definition at line 105 of file VarBlob.h.
References VarTypes::VarType::changed().
{
       _dpointer=pointer;
       _dsize=size;
       changed();
     }
virtual void VarTypes::VarBlob::setSerialString (const string & val) inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 120 of file VarBlob.h.
References VarTypes::VarType::changed(), VarTypes::XMLParserBase64Tool::decode(), getDataPointer(), getDataSize(), and VarTypes::VarBase64::getTool().
{
       VarBase64::getTool()->decode(val,getDataPointer(),getDataSize());
       changed();
     }
virtual bool VarTypes::VarBlob::setString (const string & val) inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 141 of file VarBlob.h.
 { (void)val; return false; };
Field Documentation
uint8_t* VarTypes::VarBlob::_dpointer protected
Definition at line 52 of file VarBlob.h.
Referenced by allocate(), clearData(), and getDataPointer().
long VarTypes::VarBlob::_dsize protected
Definition at line 51 of file VarBlob.h.
Referenced by getDataSize().
bool VarTypes::VarBlob::_dsize_limited protected
Definition at line 53 of file VarBlob.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/vartypes/primitives/VarBlob.h