Documentation: grsim_comm/include/proto/grSim_Replacement.pb.cc File Reference
grSim_Replacement.pb.cc File Reference
#include "grSim_Replacement.pb.h"
#include <algorithm>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
Data Structures
class grSim_RobotReplacementDefaultTypeInternal
class grSim_BallReplacementDefaultTypeInternal
class grSim_ReplacementDefaultTypeInternal
struct StaticDescriptorInitializer_grSim_5fReplacement_2eproto
Namespaces
anonymous_namespace{grSim_Replacement.pb.cc}
Macros
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Functions
const ::google::protobuf::uint32 * protobuf_Offsets_grSim_5fReplacement_2eproto () GOOGLE_ATTRIBUTE_COLD
void anonymous_namespace{grSim_Replacement.pb.cc}::protobuf_AssignDescriptors ()
void anonymous_namespace{grSim_Replacement.pb.cc}::protobuf_AssignDescriptorsOnce ()
void anonymous_namespace{grSim_Replacement.pb.cc}::protobuf_RegisterTypes (const ::std::string &) GOOGLE_ATTRIBUTE_COLD
void protobuf_ShutdownFile_grSim_5fReplacement_2eproto ()
void protobuf_InitDefaults_grSim_5fReplacement_2eproto_impl ()
void protobuf_InitDefaults_grSim_5fReplacement_2eproto ()
void protobuf_AddDesc_grSim_5fReplacement_2eproto_impl ()
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_grSim_5fReplacement_2eproto_once_)
void protobuf_AddDesc_grSim_5fReplacement_2eproto ()
Variables
grSim_RobotReplacementDefaultTypeInternal _grSim_RobotReplacement_default_instance_
grSim_BallReplacementDefaultTypeInternal _grSim_BallReplacement_default_instance_
grSim_ReplacementDefaultTypeInternal _grSim_Replacement_default_instance_
::google::protobuf::Metadata anonymous_namespace{grSim_Replacement.pb.cc}::file_level_metadata [3]
static const ::google::protobuf::internal::MigrationSchema schemas []
static const ::google::protobuf::internal::DefaultInstanceData file_default_instances []
struct StaticDescriptorInitializer_grSim_5fReplacement_2eproto static_descriptor_initializer_grSim_5fReplacement_2eproto_
Macro Definition Documentation
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Referenced by grSim_RobotReplacement::MergePartialFromCodedStream(), grSim_BallReplacement::MergePartialFromCodedStream(), and grSim_Replacement::MergePartialFromCodedStream().
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
Definition at line 4 of file grSim_Replacement.pb.cc.
Function Documentation
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_grSim_5fReplacement_2eproto_once_)
Referenced by protobuf_AddDesc_grSim_5fReplacement_2eproto_impl(), anonymous_namespace{grSim_Replacement.pb.cc}::protobuf_AssignDescriptorsOnce(), and protobuf_InitDefaults_grSim_5fReplacement_2eproto().
void protobuf_AddDesc_grSim_5fReplacement_2eproto ()
Definition at line 153 of file grSim_Replacement.pb.cc.
References protobuf_AddDesc_grSim_5fReplacement_2eproto_impl().
Referenced by protobuf_AddDesc_grSim_5fPacket_2eproto_impl(), anonymous_namespace{grSim_Replacement.pb.cc}::protobuf_AssignDescriptors(), and StaticDescriptorInitializer_grSim_5fReplacement_2eproto::StaticDescriptorInitializer_grSim_5fReplacement_2eproto().
{
   ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_grSim_5fReplacement_2eproto_once_,
                  &protobuf_AddDesc_grSim_5fReplacement_2eproto_impl);
 }
void protobuf_AddDesc_grSim_5fReplacement_2eproto_impl ()
Definition at line 133 of file grSim_Replacement.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), protobuf_InitDefaults_grSim_5fReplacement_2eproto(), anonymous_namespace{grSim_Replacement.pb.cc}::protobuf_RegisterTypes(), and protobuf_ShutdownFile_grSim_5fReplacement_2eproto().
Referenced by protobuf_AddDesc_grSim_5fReplacement_2eproto().
{
   protobuf_InitDefaults_grSim_5fReplacement_2eproto();
   static const char descriptor[] = {
       "\n\027grSim_Replacement.proto\"[\n\026grSim_Robot"
       "Replacement\022\t\n\001x\030\001 \002(\001\022\t\n\001y\030\002 \002(\001\022\013\n\003dir"
       "\030\003 \002(\001\022\n\n\002id\030\004 \002(\r\022\022\n\nyellowteam\030\005 \002(\010\"E"
       "\n\025grSim_BallReplacement\022\t\n\001x\030\001 \002(\001\022\t\n\001y\030"
       "\002 \002(\001\022\n\n\002vx\030\003 \002(\001\022\n\n\002vy\030\004 \002(\001\"b\n\021grSim_R"
       "eplacement\022$\n\004ball\030\001 \001(\0132\026.grSim_BallRep"
       "lacement\022\'\n\006robots\030\002 \003(\0132\027.grSim_RobotRe"
       "placement"
   };
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
       descriptor, 289);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "grSim_Replacement.proto", &protobuf_RegisterTypes);
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_grSim_5fReplacement_2eproto);
 }
void protobuf_InitDefaults_grSim_5fReplacement_2eproto ()
Definition at line 129 of file grSim_Replacement.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), and protobuf_InitDefaults_grSim_5fReplacement_2eproto_impl().
Referenced by grSim_RobotReplacement::default_instance(), grSim_BallReplacement::default_instance(), grSim_Replacement::default_instance(), grSim_BallReplacement::grSim_BallReplacement(), grSim_Replacement::grSim_Replacement(), grSim_RobotReplacement::grSim_RobotReplacement(), protobuf_AddDesc_grSim_5fReplacement_2eproto_impl(), and protobuf_InitDefaults_grSim_5fPacket_2eproto_impl().
{
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
   ::google::protobuf::GoogleOnceInit(&once, &protobuf_InitDefaults_grSim_5fReplacement_2eproto_impl);
 }
void protobuf_InitDefaults_grSim_5fReplacement_2eproto_impl ()
Definition at line 118 of file grSim_Replacement.pb.cc.
References grSim_BallReplacement::internal_default_instance().
Referenced by protobuf_InitDefaults_grSim_5fReplacement_2eproto().
{
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::internal::InitProtobufDefaults();
   _grSim_RobotReplacement_default_instance_.DefaultConstruct();
   _grSim_BallReplacement_default_instance_.DefaultConstruct();
   _grSim_Replacement_default_instance_.DefaultConstruct();
   _grSim_Replacement_default_instance_.get_mutable()->ball_ = const_cast< ::grSim_BallReplacement*>(
       ::grSim_BallReplacement::internal_default_instance());
 }
const ::google::protobuf::uint32 * protobuf_Offsets_grSim_5fReplacement_2eproto ()
Definition at line 34 of file grSim_Replacement.pb.cc.
Referenced by anonymous_namespace{grSim_Replacement.pb.cc}::protobuf_AssignDescriptors().
{
   static const ::google::protobuf::uint32 offsets[] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_RobotReplacement, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_RobotReplacement, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_RobotReplacement, x_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_RobotReplacement, y_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_RobotReplacement, dir_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_RobotReplacement, id_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_RobotReplacement, yellowteam_),
     0,
     1,
     2,
     3,
     4,
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_BallReplacement, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_BallReplacement, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_BallReplacement, x_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_BallReplacement, y_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_BallReplacement, vx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_BallReplacement, vy_),
     0,
     1,
     2,
     3,
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Replacement, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Replacement, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Replacement, ball_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Replacement, robots_),
     0,
     1,
   };
   return offsets;
 }
void protobuf_ShutdownFile_grSim_5fReplacement_2eproto ()
Definition at line 109 of file grSim_Replacement.pb.cc.
References anonymous_namespace{grSim_Replacement.pb.cc}::file_level_metadata.
Referenced by protobuf_AddDesc_grSim_5fReplacement_2eproto_impl().
{
   _grSim_RobotReplacement_default_instance_.Shutdown();
   delete file_level_metadata[0].reflection;
   _grSim_BallReplacement_default_instance_.Shutdown();
   delete file_level_metadata[1].reflection;
   _grSim_Replacement_default_instance_.Shutdown();
   delete file_level_metadata[2].reflection;
 }
Variable Documentation
grSim_BallReplacementDefaultTypeInternal _grSim_BallReplacement_default_instance_
Definition at line 22 of file grSim_Replacement.pb.cc.
Referenced by grSim_BallReplacement::internal_default_instance().
grSim_ReplacementDefaultTypeInternal _grSim_Replacement_default_instance_
Definition at line 24 of file grSim_Replacement.pb.cc.
Referenced by grSim_Replacement::internal_default_instance().
grSim_RobotReplacementDefaultTypeInternal _grSim_RobotReplacement_default_instance_
Definition at line 20 of file grSim_Replacement.pb.cc.
Referenced by grSim_RobotReplacement::internal_default_instance().
const ::google::protobuf::internal::DefaultInstanceData file_default_instances[] static
Initial value:
= {
  {reinterpret_cast<const ::google::protobuf::Message*>(&_grSim_RobotReplacement_default_instance_), NULL},
  {reinterpret_cast<const ::google::protobuf::Message*>(&_grSim_BallReplacement_default_instance_), NULL},
  {reinterpret_cast<const ::google::protobuf::Message*>(&_grSim_Replacement_default_instance_), NULL},
}
Definition at line 80 of file grSim_Replacement.pb.cc.
Referenced by anonymous_namespace{grSim_Replacement.pb.cc}::protobuf_AssignDescriptors().
const ::google::protobuf::internal::MigrationSchema schemas[] static
Initial value:
= {
  { 0, 9, sizeof(grSim_RobotReplacement)},
  { 14, 22, sizeof(grSim_BallReplacement)},
  { 26, 32, sizeof(grSim_Replacement)},
}
Definition at line 74 of file grSim_Replacement.pb.cc.
Referenced by anonymous_namespace{grSim_Replacement.pb.cc}::protobuf_AssignDescriptors().
struct StaticDescriptorInitializer_grSim_5fReplacement_2eproto static_descriptor_initializer_grSim_5fReplacement_2eproto_
Referenced by StaticDescriptorInitializer_grSim_5fReplacement_2eproto::StaticDescriptorInitializer_grSim_5fReplacement_2eproto().