Documentation: GLCamera Class Reference
GLCamera Class Reference
An OpenGL camera class.
#include <glcamera.h>
Public Types
enum GLCAM_PAN_MODE_ENUM { GLCAM_PAN_POSITION_CENTRIC, GLCAM_PAN_FREE_FLY }
Public Member Functions
quat getQuaternion ()
GLCamera ()
~GLCamera ()
void reset ()
virtual void apply ()
virtual void setState (const GLCamera &cam)
GLCAM_PAN_MODE_ENUM getPanMode ()
void setPanMode (GLCAM_PAN_MODE_ENUM mode)
void setDistance (double distance, bool allow_negative=false)
double getDistance ()
vector3d getLensPosition ()
void freeLookAt (const vector3d &point)
void lookAt (const vector3d &point)
void setEuler (double pitch, double yaw, double roll)
void setRoll (double roll)
void setPitch (double pitch)
void setYaw (double yaw)
void getEuler (double &pitch, double &yaw, double &roll)
double getRoll ()
double getPitch ()
double getYaw ()
void wheelEvent (QWheelEvent *event)
void keyPressEvent (QKeyEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
Public Member Functions inherited from GLObject
GLObject ()
virtual ~GLObject ()
void reset ()
Data Fields
vector3d forward
Data Fields inherited from GLObject
vector3d scale
vector3d pos
quat rot
Protected Member Functions
virtual void preRender ()
virtual void postRender ()
virtual void render ()
void mouseAction (QMouseEvent *event)
Protected Attributes
GLCAM_PAN_MODE_ENUM pan_mode
QPoint mouseStart_rotate
QPoint mouseStart_pan
double p_start
double y_start
double r_start
double pan_start_x
double pan_start_y
vector3d pan_start_pos
Detailed Description
An OpenGL camera class.
Author
Stefan Zickler
Definition at line 40 of file glcamera.h.
Member Enumeration Documentation
enum GLCamera::GLCAM_PAN_MODE_ENUM
Enumerator
GLCAM_PAN_POSITION_CENTRIC
GLCAM_PAN_FREE_FLY
Definition at line 42 of file glcamera.h.
{
   GLCAM_PAN_POSITION_CENTRIC,
   GLCAM_PAN_FREE_FLY,
 };
Constructor & Destructor Documentation
GLCamera::GLCamera ()
Definition at line 24 of file glcamera.cpp.
References GLCAM_PAN_POSITION_CENTRIC, pan_mode, and reset().
 {
   reset();
   pan_mode=GLCAM_PAN_POSITION_CENTRIC;
 }
GLCamera::~GLCamera ()
Definition at line 93 of file glcamera.cpp.
 {
 }
Member Function Documentation
void GLCamera::apply () virtual
Reimplemented from GLObject.
Definition at line 84 of file glcamera.cpp.
References postRender(), preRender(), and render().
Referenced by GLLUTWidget::paintGL().
                      {
   //since this is a camera transformation that should affect
   //the entire scene we do not want QGLObject's standard apply implementation
   //because it would restore the old matrix when finished
   preRender();
   render();
   postRender();
 }
void GLCamera::freeLookAt (const vector3d & point)
Definition at line 97 of file glcamera.cpp.
References Quaternion< num >::invert(), GLObject::pos, GLObject::rot, and shortestArc().
Referenced by setState().
{
   rot = shortestArc((vector3d(0.0,0.0,1.0)).norm(),(pos-point).norm());
   rot.invert();
 }
double GLCamera::getDistance ()
Definition at line 49 of file glcamera.cpp.
References forward, and GVector::vector3d< num >::z.
Referenced by mouseAction(), setState(), and wheelEvent().
{
   return forward.z;
 }
void GLCamera::getEuler (double & pitch, double & yaw, double & roll)
Definition at line 136 of file glcamera.cpp.
References Quaternion< num >::getEuler(), and GLObject::rot.
Referenced by mousePressEvent(), and setState().
{
   rot.getEuler(pitch,yaw,roll);
 }
vector3d GLCamera::getLensPosition ()
Definition at line 68 of file glcamera.cpp.
References forward, GLObject::pos, GLObject::rot, Quaternion< num >::rotateVectorByQuaternion(), and GVector::vector3d< num >::sqlength().
Referenced by setState().
{
   vector3d result=pos;
   if (forward.sqlength() > 0.0) {
     result+=rot.rotateVectorByQuaternion(forward);
   }
   return (result);
 }
GLCamera::GLCAM_PAN_MODE_ENUM GLCamera::getPanMode ()
Definition at line 36 of file glcamera.cpp.
References pan_mode.
Referenced by setState().
{
   return pan_mode;
 }
double GLCamera::getPitch ()
Definition at line 145 of file glcamera.cpp.
References Quaternion< num >::getPitch(), and GLObject::rot.
Referenced by setState().
{
   return rot.getPitch();
 }
quat GLCamera::getQuaternion ()
Definition at line 53 of file glcamera.cpp.
References GLObject::rot.
{
   return (rot);
 }
double GLCamera::getRoll ()
Definition at line 140 of file glcamera.cpp.
References Quaternion< num >::getRoll(), and GLObject::rot.
Referenced by setState().
{
   return rot.getRoll();
 }
double GLCamera::getYaw ()
Definition at line 149 of file glcamera.cpp.
References Quaternion< num >::getYaw(), and GLObject::rot.
Referenced by setState().
{
   return rot.getYaw();
 }
void GLCamera::keyPressEvent (QKeyEvent * event)
Definition at line 168 of file glcamera.cpp.
{
   (void)event;
 }
void GLCamera::lookAt (const vector3d & point)
Definition at line 103 of file glcamera.cpp.
References GLObject::pos, GLObject::rot, Quaternion< num >::setEuler(), GVector::shortest_angle(), GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
Referenced by setState().
{
   //1st compute yaw:
   vector3d diff=(pos-point);
   vector3d diff_flat(diff.x,0.0,diff.z);
   double yaw=atan2(diff.x,diff.z);
   double pitch=shortest_angle(diff,diff_flat);
   if (diff.y > 0.0) pitch*=(-1.0);
   rot.setEuler(pitch,yaw,0.0);
 }
void GLCamera::mouseAction (QMouseEvent * event) protected
Definition at line 172 of file glcamera.cpp.
References forward, getDistance(), GLCAM_PAN_FREE_FLY, GLCAM_PAN_POSITION_CENTRIC, GVector::max(), mouseStart_pan, mouseStart_rotate, p_start, pan_mode, pan_start_pos, pan_start_x, pan_start_y, GLObject::pos, r_start, GLObject::rot, Quaternion< num >::rotateVectorByQuaternion(), setEuler(), GVector::vector3d< num >::x, GVector::vector3d< num >::y, y_start, and GVector::vector3d< num >::z.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
{
   if ((event->buttons() & Qt::RightButton) != 0) {
     QPoint offset=mouseStart_pan-event->pos();
     if (pan_mode==GLCAM_PAN_POSITION_CENTRIC) {
       forward.x=(pan_start_x+(double)offset.x()*max(getDistance(),1.0)/700.0);
       forward.y=(pan_start_y-(double)offset.y()*max(getDistance(),1.0)/700.0);
     } else if (pan_mode==GLCAM_PAN_FREE_FLY) {
       vector3d trans;
       trans.x=((double)offset.x()/10.0);
       trans.y=(-(double)offset.y()/10.0);
       trans.z=0.0;
       trans=rot.rotateVectorByQuaternion(trans);
       pos=pan_start_pos+trans;
     }
   }
   if ((event->buttons() & Qt::LeftButton) != 0) {
     QPoint offset=mouseStart_rotate-event->pos();
     setEuler(p_start+(double)offset.y()/100.0,y_start+(double)offset.x()/100.0,r_start);
   }
 }
void GLCamera::mouseMoveEvent (QMouseEvent * event)
Definition at line 213 of file glcamera.cpp.
References mouseAction().
Referenced by GLLUTWidget::mouseMoveEvent().
{
   mouseAction(event);
 }
void GLCamera::mousePressEvent (QMouseEvent * event)
Definition at line 193 of file glcamera.cpp.
References forward, getEuler(), GLCAM_PAN_FREE_FLY, GLCAM_PAN_POSITION_CENTRIC, mouseAction(), mouseStart_pan, mouseStart_rotate, p_start, pan_mode, pan_start_pos, pan_start_x, pan_start_y, GLObject::pos, r_start, GVector::vector3d< num >::x, GVector::vector3d< num >::y, and y_start.
Referenced by GLLUTWidget::mousePressEvent().
{
   if (event->button()==Qt::RightButton) {
     mouseStart_pan=event->pos();
     if (pan_mode==GLCAM_PAN_POSITION_CENTRIC) {
       pan_start_x=forward.x;
       pan_start_y=forward.y;
     } else if (pan_mode==GLCAM_PAN_FREE_FLY) {
       pan_start_pos=pos;
     }
   } else if (event->button()==Qt::LeftButton) {
     getEuler(p_start,y_start,r_start);
     mouseStart_rotate=event->pos();
   }
   mouseAction(event);
 }
void GLCamera::mouseReleaseEvent (QMouseEvent * event)
Definition at line 210 of file glcamera.cpp.
References mouseAction().
Referenced by GLLUTWidget::mouseReleaseEvent().
{
   mouseAction(event);
 }
void GLCamera::postRender () protected virtual
Reimplemented from GLObject.
Definition at line 76 of file glcamera.cpp.
References GLObject::pos, GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
Referenced by apply(), and setState().
{
   glTranslatef(-pos.x,-pos.y,-pos.z);
 }
void GLCamera::preRender () protected virtual
Reimplemented from GLObject.
Definition at line 57 of file glcamera.cpp.
References forward, Quaternion< num >::getMatrix(), GLObject::rot, GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
Referenced by apply(), and setState().
{
   double m[16];
   rot.getMatrix(m);
   //this pans in camera coordinates (centered around camera):
   //glTranslatef(0.0,0.0,-forward.z);
   glTranslated(-forward.x,-forward.y,-forward.z);
   glMultMatrixd(m);
 }
void GLCamera::render () protected virtual
Reimplemented from GLObject.
Definition at line 80 of file glcamera.cpp.
Referenced by apply(), and setState().
                       {
 }
void GLCamera::reset ()
Definition at line 30 of file glcamera.cpp.
References Quaternion< num >::clear(), forward, GLObject::reset(), GLObject::rot, and GVector::vector3d< num >::set().
Referenced by GLLUTWidget::callZoomFit(), GLLUTWidget::callZoomNormal(), GLCamera(), and GLLUTWidget::GLLUTWidget().
                      {
   GLObject::reset();
   forward.set(0.0,0.0,1.0);
   rot.clear();
 }
void GLCamera::setDistance (double distance, bool allow_negative = false)
Definition at line 44 of file glcamera.cpp.
References GVector::distance(), forward, and GVector::vector3d< num >::z.
Referenced by GLLUTWidget::callZoomFit(), GLLUTWidget::callZoomNormal(), GLLUTWidget::GLLUTWidget(), setState(), and wheelEvent().
{
   if (distance < 0.0 && allow_negative==false) distance=0.0;
   forward.z=distance;
 }
void GLCamera::setEuler (double pitch, double yaw, double roll)
Definition at line 118 of file glcamera.cpp.
References M_PI_HALF, GLObject::rot, and Quaternion< num >::setEuler().
Referenced by mouseAction(), setPitch(), setRoll(), setState(), and setYaw().
{
   if (pitch > M_PI_HALF) pitch=M_PI_HALF;
   if (pitch < -M_PI_HALF) pitch=-M_PI_HALF;
   rot.setEuler(pitch,yaw,roll);
 }
void GLCamera::setPanMode (GLCamera::GLCAM_PAN_MODE_ENUM mode)
Definition at line 40 of file glcamera.cpp.
References pan_mode.
Referenced by setState().
{
   pan_mode=mode;
 }
void GLCamera::setPitch (double pitch)
Definition at line 128 of file glcamera.cpp.
References Quaternion< num >::getRoll(), Quaternion< num >::getYaw(), GLObject::rot, and setEuler().
Referenced by GLLUTWidget::callZoomFit(), GLLUTWidget::callZoomNormal(), GLLUTWidget::GLLUTWidget(), and setState().
{
   setEuler(pitch,rot.getYaw(),rot.getRoll());
 }
void GLCamera::setRoll (double roll)
Definition at line 124 of file glcamera.cpp.
References Quaternion< num >::getPitch(), Quaternion< num >::getYaw(), roll(), GLObject::rot, and setEuler().
Referenced by setState().
{
   setEuler(rot.getPitch(),rot.getYaw(),roll);
 }
virtual void GLCamera::setState (const GLCamera & cam) inline virtual
Definition at line 62 of file glcamera.h.
References GVector::distance(), forward, freeLookAt(), getDistance(), getEuler(), getLensPosition(), getPanMode(), getPitch(), getRoll(), getYaw(), lookAt(), GLObject::pos, postRender(), preRender(), render(), roll(), GLObject::rot, GLObject::scale, setDistance(), setEuler(), setPanMode(), setPitch(), setRoll(), and setYaw().
{
       forward=cam.forward;
       pos=cam.pos;
       scale=cam.scale;
       rot=cam.rot;
     }
void GLCamera::setYaw (double yaw)
Definition at line 132 of file glcamera.cpp.
References Quaternion< num >::getPitch(), Quaternion< num >::getRoll(), GLObject::rot, and setEuler().
Referenced by GLLUTWidget::callZoomFit(), GLLUTWidget::callZoomNormal(), GLLUTWidget::GLLUTWidget(), and setState().
{
   setEuler(rot.getPitch(),yaw,rot.getRoll());
 }
void GLCamera::wheelEvent (QWheelEvent * event)
Definition at line 157 of file glcamera.cpp.
References getDistance(), GVector::max(), GVector::min(), and setDistance().
Referenced by GLLUTWidget::wheelEvent().
{
   int delta=event->delta();
   if (delta < 0) {
     setDistance(max(getDistance() + 0.05,getDistance()*1.15));
     //this->zoom.zoomIn();
   } else {
     setDistance(max(0.0,min(getDistance() - 0.05, getDistance()/1.15)));
     //this->zoom.zoomOut();
   }
   event->accept();
 }
Field Documentation
vector3d GLCamera::forward
Definition at line 52 of file glcamera.h.
Referenced by getDistance(), getLensPosition(), mouseAction(), mousePressEvent(), preRender(), reset(), setDistance(), setState(), and GLSmoothCamera::step().
QPoint GLCamera::mouseStart_pan protected
Definition at line 99 of file glcamera.h.
Referenced by mouseAction(), and mousePressEvent().
QPoint GLCamera::mouseStart_rotate protected
Definition at line 98 of file glcamera.h.
Referenced by mouseAction(), and mousePressEvent().
double GLCamera::p_start protected
Definition at line 100 of file glcamera.h.
Referenced by mouseAction(), and mousePressEvent().
GLCAM_PAN_MODE_ENUM GLCamera::pan_mode protected
Definition at line 48 of file glcamera.h.
Referenced by getPanMode(), GLCamera(), mouseAction(), mousePressEvent(), and setPanMode().
vector3d GLCamera::pan_start_pos protected
Definition at line 102 of file glcamera.h.
Referenced by mouseAction(), and mousePressEvent().
double GLCamera::pan_start_x protected
Definition at line 101 of file glcamera.h.
Referenced by mouseAction(), and mousePressEvent().
double GLCamera::pan_start_y protected
Definition at line 101 of file glcamera.h.
Referenced by mouseAction(), and mousePressEvent().
double GLCamera::r_start protected
Definition at line 100 of file glcamera.h.
Referenced by mouseAction(), and mousePressEvent().
double GLCamera::y_start protected
Definition at line 100 of file glcamera.h.
Referenced by mouseAction(), and mousePressEvent().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/gl/glcamera.h
ssl-vision/src/shared/gl/glcamera.cpp