Documentation: VarTypes::VarList Class Reference
VarTypes::VarList Class Reference
This is the list type of the VarTypes system.
#include <VarList.h>
Signals
void childAdded (VarType *child)
void childRemoved (VarType *child)
Signals inherited from VarTypes::VarType
void hasChanged (VarType *)
void wasEdited (VarType *)
void XMLwasRead (VarType *)
This signal is triggered if data was written from an xml node.
void XMLwasWritten (VarType *)
This signal is triggered if data was written to an xml node.
Public Member Functions
VarList (string _name="")
Creates an empty VarList.
virtual ~VarList ()
virtual string getString () const
this will always return the empty string ""
virtual void resetToDefault ()
this will clear the list
virtual void printdebug () const
prints the label and number of elements
int addChild (VarType *child)
adds a VarType item to the end of the list.
bool removeChild (VarType *child)
virtual VarTypeId getType () const
virtual int getChildrenCount () const
returns the number of children of this list
virtual void deleteAllChildren ()
virtual vector< VarType * > getChildren () const
returns a vector of all children in the order that they occur in internally
VarType * findChildOrReplace (VarType *other)
template<class VCLASS >
VCLASS * findChildOrReplace (VCLASS *other)
virtual QWidget * createEditor (const VarItemDelegate *delegate, QWidget *parent, const QStyleOptionViewItem &option)
Public Member Functions inherited from VarTypes::VarType
VarType (string name="")
virtual ~VarType ()
virtual void setName (string name)
Set the string label of this node.
virtual string getName () const
Get the string label of this node.
virtual VarTypeFlag getFlags () const
virtual void setFlags (VarTypeFlag f)
virtual void addFlags (VarTypeFlag f)
virtual void removeFlags (VarTypeFlag f)
virtual bool areFlagsSet (VarTypeFlag f) const
VarType * findChild (string label) const
void writeXML (XMLNode &parent, bool blind_append=true)
Write the contents of this VarType node to an XMLNode.
void readXML (XMLNode &us)
Let this VarType node load the contents of an XMLNode.
virtual void setEditorData (const VarItemDelegate *delegate, QWidget *editor) const
virtual void setModelData (const VarItemDelegate *delegate, QWidget *editor)
virtual QSize sizeHint (const VarItemDelegate *delegate, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void paint (const VarItemDelegate *delegate, QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * clone () const
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual bool setString (const string &val)
Set this node's data to some string representation.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
virtual bool hasValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Protected Member Functions
virtual void readChildren (XMLNode &us)
Protected Member Functions inherited from VarTypes::VarType
virtual void lock () const
virtual void unlock () const
virtual void changed ()
virtual void updateAttributes (XMLNode &us) const
virtual void updateText (XMLNode &us) const
virtual void updateChildren (XMLNode &us) const
virtual void readAttributes (XMLNode &us)
virtual void readText (XMLNode &us)
virtual void loadExternal ()
Protected Attributes
vector< VarType * > list
Protected Attributes inherited from VarTypes::VarType
QMutex * _mutex
VarTypeFlag _flags
string _name
Additional Inherited Members
Public Slots inherited from VarTypes::VarType
void mvcEditCompleted ()
A slot to receive signals from a model-view system that editing of this item was just completed.
Static Public Member Functions inherited from VarTypes::VarType
static void deleteAllVarChildren (XMLNode &node)
Clear an XMLNode's list of children.
static vector< VarType * > readChildrenHelper (XMLNode &parent, vector< VarType * > existing_children, bool only_update_existing, bool blind_append)
A helper function to read a list of children from XML and convert it to a vector of VarType nodes.
Static Protected Member Functions inherited from VarTypes::VarType
static string fixString (const char *cst)
static string intToString (int val)
static string doubleToString (double val)
static XMLNode findOrAppendChild (XMLNode &parent, string key, string val)
Detailed Description
This is the list type of the VarTypes system.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
VarList allows the storage of an ordered list of children nodes.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 39 of file VarList.h.
Constructor & Destructor Documentation
VarTypes::VarList::VarList (string _name = "") inline
Creates an empty VarList.
Definition at line 51 of file VarList.h.
                              : VarType(_name) {
     };
virtual VarTypes::VarList::~VarList () inline virtual
Definition at line 53 of file VarList.h.
{
     };
Member Function Documentation
int VarTypes::VarList::addChild (VarType * child) inline
adds a VarType item to the end of the list.
Definition at line 68 of file VarList.h.
Referenced by CameraParameters::AdditionalCalibrationInformation::AdditionalCalibrationInformation(), CameraParameters::addSettingsToList(), CameraParameters::AdditionalCalibrationInformation::addSettingsToList(), CaptureBlueFox2::CaptureBlueFox2(), CaptureDC1394v2::CaptureDC1394v2(), CaptureFlycap::CaptureFlycap(), CaptureFromFile::CaptureFromFile(), CaptureGenerator::CaptureGenerator(), CaptureThread::CaptureThread(), CaptureV4L::CaptureV4L(), FieldCircularArc::FieldCircularArc(), FieldLine::FieldLine(), LUT3D::LUT3D(), MainWindow::MainWindow(), MultiStackRoboCupSSL::MultiStackRoboCupSSL(), PluginCameraCalibration::PluginCameraCalibration(), PluginDetectBallsSettings::PluginDetectBallsSettings(), PluginDVR::PluginDVR(), PluginFindBlobs::PluginFindBlobs(), PluginLegacyPublishGeometry::PluginLegacyPublishGeometry(), PluginPublishGeometry::PluginPublishGeometry(), PluginVisualize::PluginVisualize(), CMPattern::TeamDetectorSettings::slotAddPressed(), StackRoboCupSSL::StackRoboCupSSL(), CMPattern::TeamDetectorSettings::TeamDetectorSettings(), and CMPattern::TeamSelector::TeamSelector().
 { lock(); list.push_back(child); emit(childAdded(child)); unlock(); changed(); return (list.size()-1);}
void VarTypes::VarList::childAdded (VarType * child) signal
Definition at line 97 of file moc_VarList.cxx.
Referenced by VarTypes::VarExternal::loadExternal().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 0, _a);
 }
void VarTypes::VarList::childRemoved (VarType * child) signal
Definition at line 104 of file moc_VarList.cxx.
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 1, _a);
 }
virtual QWidget* VarTypes::VarList::createEditor (const VarItemDelegate * delegate, QWidget * parent, const QStyleOptionViewItem & option) inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 179 of file VarList.h.
{
     (void)delegate;
     (void)option;
     (void)parent;
     return 0;
   }
virtual void VarTypes::VarList::deleteAllChildren () inline virtual
removes all children, by actually deleting them in memory note that this is recursive. use it to un-allocate entire hierarchies from memory
Reimplemented from VarTypes::VarType.
Definition at line 107 of file VarList.h.
References velocity.pid_::i.
Referenced by CaptureBlueFox2::~CaptureBlueFox2().
{
       lock();
       int n = list.size();
       for (int i = 0; i < n ; i++) {
         if (list[i]!=0) {
           list[i]->deleteAllChildren();
           delete list[i];
         }
       }
       list.clear();
       unlock();
     }
VarType* VarTypes::VarList::findChildOrReplace (VarType * other) inline
Finds a child based on the label of 'other' If the child is not found then other is returned However, if the child is found then other will be deleted and the child will be returned!
Definition at line 132 of file VarList.h.
References VarTypes::VarType::getName().
Referenced by CMPattern::Team::Team().
{
       VarType * data = findChild(other->getName());
       if (data!=0) {
         delete other;
         return data;
       } else {
         addChild(other);
         return other;
       }
     }
template<class VCLASS > VCLASS* VarTypes::VarList::findChildOrReplace (VCLASS * other) inline
Finds a child based on the label of 'other' If the child is not found then other is returned However, if the child is found then other will be deleted and the child will be returned!
Definition at line 147 of file VarList.h.
{
       VCLASS * data = (VCLASS *)findChild(other->getName());
       if (data!=0) {
         delete other;
         return data;
       } else {
         addChild(other);
         return other;
       }
     }
virtual vector<VarType *> VarTypes::VarList::getChildren () const inline virtual
returns a vector of all children in the order that they occur in internally
Reimplemented from VarTypes::VarType.
Definition at line 121 of file VarList.h.
Referenced by CaptureDC1394v2::CaptureDC1394v2(), CaptureV4L::CaptureV4L(), FieldLine::FromVarList(), FieldCircularArc::FromVarList(), CaptureFlycap::mvc_connect(), CaptureBlueFox2::mvc_connect(), CaptureV4L::mvc_connect(), CaptureDC1394v2::mvc_connect(), CaptureV4L::readAllParameterProperties(), CaptureDC1394v2::readAllParameterProperties(), CaptureFlycap::readAllParameterValues(), CaptureV4L::readAllParameterValues(), CaptureDC1394v2::readAllParameterValues(), CaptureV4L::readParameterProperty(), CaptureDC1394v2::readParameterProperty(), CaptureV4L::readParameterValues(), CaptureDC1394v2::readParameterValues(), CaptureBlueFox2::startCapture(), CaptureV4L::startCapture(), CaptureDC1394v2::startCapture(), CaptureBlueFox2::stopCapture(), CaptureV4L::stopCapture(), CaptureDC1394v2::stopCapture(), VarTypes::VarExternal::VarExternal(), CaptureFlycap::writeAllParameterValues(), CaptureV4L::writeAllParameterValues(), CaptureDC1394v2::writeAllParameterValues(), CaptureFlycap::writeParameterValues(), CaptureV4L::writeParameterValues(), and CaptureDC1394v2::writeParameterValues().
     {
       lock();
       vector<VarType *> l = list;
       unlock();
       return l;
     }
virtual int VarTypes::VarList::getChildrenCount () const inline virtual
returns the number of children of this list
Definition at line 95 of file VarList.h.
Referenced by CMPattern::TeamDetectorSettings::slotAddPressed().
     {
       int res;
       lock();
       res = list.size();
       unlock();
       return res;
     }
virtual string VarTypes::VarList::getString () const inline virtual
this will always return the empty string ""
Reimplemented from VarTypes::VarVal.
Definition at line 59 of file VarList.h.
 { return ""; }
virtual VarTypeId VarTypes::VarList::getType () const inline virtual
Reimplemented from VarTypes::VarVal.
Reimplemented in VarTypes::VarExternal.
Definition at line 92 of file VarList.h.
References VarTypes::VARTYPE_ID_LIST.
 { return VARTYPE_ID_LIST; } ;
virtual void VarTypes::VarList::printdebug () const inline virtual
prints the label and number of elements
Reimplemented from VarTypes::VarVal.
Definition at line 65 of file VarList.h.
 { printf("VarList named %s containing %zu element(s)\n",getName().c_str(), list.size()); }
virtual void VarTypes::VarList::readChildren (XMLNode & us) inline protected virtual
Reimplemented from VarTypes::VarType.
Reimplemented in VarTypes::VarExternal.
Definition at line 161 of file VarList.h.
References velocity.pid_::i.
     {
       lock();
       int before=list.size();
       list=readChildrenHelper(us, list, false, false);
       int after=list.size();
       if (after > before) {
         for (int i=before; i < after; i++) {
           emit(childAdded(list[i]));
         }
       }
       unlock();
       changed();
     }
bool VarTypes::VarList::removeChild (VarType * child) inline
Definition at line 69 of file VarList.h.
References velocity.pid_::i.
Referenced by FieldCircularArc::~FieldCircularArc(), and FieldLine::~FieldLine().
{
       lock();
       vector<VarType *> newlist;
       unsigned int n=list.size();
       bool found=false;
       for (unsigned int i=0;i<n;i++) {
         if (list[i]!=child) {
           newlist.push_back(list[i]);
         } else {
           found=true;
         }
       }
       if (found) {
         list=newlist;
       }
       unlock();
       if (found) {
         emit(childRemoved(child));
         changed();
       }
       return found;
     };
virtual void VarTypes::VarList::resetToDefault () inline virtual
this will clear the list
Reimplemented from VarTypes::VarType.
Definition at line 62 of file VarList.h.
References velocity.pid_::i.
 {lock(); for (unsigned int i=0;i<list.size();i++) { emit(childRemoved(list[i])); } list.clear();  unlock(); };
Field Documentation
vector<VarType *> VarTypes::VarList::list protected
Definition at line 45 of file VarList.h.
Referenced by VarTypes::VarExternal::loadExternal(), and VarTypes::VarExternal::VarExternal().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/primitives/VarList.h
ssl-vision/build/src/shared/vartypes/primitives/moc_VarList.cxx