Documentation: CMVision::Histogram Class Reference
CMVision::Histogram Class Reference
#include <cmvision_histogram.h>
Public Member Functions
Histogram (int _max_channels)
~Histogram ()
int addBox (const Image< raw8 > *image, int x1, int y1, int x2, int y2)
int getChannel (int channel)
void setChannel (int channel, int value)
void clear ()
Protected Attributes
int * channels
int max_channels
Detailed Description
Definition at line 27 of file cmvision_histogram.h.
Constructor & Destructor Documentation
CMVision::Histogram::Histogram (int _max_channels)
Definition at line 25 of file cmvision_histogram.cpp.
References channels, and max_channels.
 {
   if (_max_channels < 1) _max_channels=1;
   max_channels=_max_channels;
   channels=new int[max_channels];
 }
CMVision::Histogram::~Histogram ()
Definition at line 65 of file cmvision_histogram.cpp.
References channels.
 {
   delete[] channels;
 }
Member Function Documentation
int CMVision::Histogram::addBox (const Image< raw8 > * image, int x1, int y1, int x2, int y2)
Definition at line 38 of file cmvision_histogram.cpp.
References GVector::bound(), channels, Image< PIXEL >::getHeight(), Image< PIXEL >::getPixelData(), Image< PIXEL >::getWidth(), ColorGrey< num, fmt >::v, role._GoToPoint::x, and role._GoToPoint::y.
Referenced by PluginDetectBalls::checkHistogram(), and CMPattern::TeamDetector::checkHistogram().
{
   raw8 * data = image->getPixelData();
   int image_width = image->getWidth();
   int image_height = image->getHeight();
   x1 = bound(x1,0,image_width-1);
   y1 = bound(y1,0,image_height-1);
   x2 = bound(x2,0,image_width-1);
   y2 = bound(y2,0,image_height-1);
   for(int y=y1; y<=y2; y++){
     for(int x=x1; x<=x2; x++){
       channels[data[y*image_width+x].v]++;
     }
   }
   return((x2 - x1 + 1) * (y2 - y1 + 1));
 }
void CMVision::Histogram::clear ()
Definition at line 32 of file cmvision_histogram.cpp.
References channels, velocity.pid_::i, and max_channels.
Referenced by PluginDetectBalls::checkHistogram(), and CMPattern::TeamDetector::checkHistogram().
                       {
   for (int i=0;i<max_channels;i++) {
     channels[i]=0;
   }
 }
int CMVision::Histogram::getChannel (int channel)
Definition at line 57 of file cmvision_histogram.cpp.
References channels.
Referenced by PluginDetectBalls::checkHistogram(), and CMPattern::TeamDetector::checkHistogram().
{
   return channels[channel];
 }
void CMVision::Histogram::setChannel (int channel, int value)
Definition at line 61 of file cmvision_histogram.cpp.
References channels.
{
   channels[channel]=value;
 }
Field Documentation
int* CMVision::Histogram::channels protected
Definition at line 29 of file cmvision_histogram.h.
Referenced by addBox(), clear(), getChannel(), Histogram(), setChannel(), and ~Histogram().
int CMVision::Histogram::max_channels protected
Definition at line 30 of file cmvision_histogram.h.
Referenced by clear(), and Histogram().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/cmvision/cmvision_histogram.h
ssl-vision/src/shared/cmvision/cmvision_histogram.cpp