Documentation: grSim_Commands Class Reference
grSim_Commands Class Reference
#include <grSim_Commands.pb.h>
Public Member Functions
grSim_Commands ()
virtual ~grSim_Commands ()
grSim_Commands (const grSim_Commands &from)
grSim_Commands & operator= (const grSim_Commands &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (grSim_Commands *other)
grSim_Commands * New () const PROTOBUF_FINAL
grSim_Commands * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const grSim_Commands &from)
void MergeFrom (const grSim_Commands &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_timestamp () const
void clear_timestamp ()
double timestamp () const
void set_timestamp (double value)
bool has_isteamyellow () const
void clear_isteamyellow ()
bool isteamyellow () const
void set_isteamyellow (bool value)
int robot_commands_size () const
void clear_robot_commands ()
const ::grSim_Robot_Command & robot_commands (int index) const
::grSim_Robot_Command * mutable_robot_commands (int index)
::grSim_Robot_Command * add_robot_commands ()
::google::protobuf::RepeatedPtrField< ::grSim_Robot_Command > * mutable_robot_commands ()
const ::google::protobuf::RepeatedPtrField< ::grSim_Robot_Command > & robot_commands () const
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const grSim_Commands & default_instance ()
static const grSim_Commands * internal_default_instance ()
Static Public Attributes
static const int kTimestampFieldNumber = 1
static const int kIsteamyellowFieldNumber = 2
static const int kRobotCommandsFieldNumber = 3
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (grSim_Commands *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_timestamp ()
void clear_has_timestamp ()
void set_has_isteamyellow ()
void clear_has_isteamyellow ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_grSim_5fCommands_2eproto ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::RepeatedPtrField< ::grSim_Robot_Command > robot_commands_
double timestamp_
bool isteamyellow_
Friends
void protobuf_InitDefaults_grSim_5fCommands_2eproto_impl ()
void protobuf_AddDesc_grSim_5fCommands_2eproto_impl ()
void protobuf_ShutdownFile_grSim_5fCommands_2eproto ()
Detailed Description
Definition at line 255 of file grSim_Commands.pb.h.
Constructor & Destructor Documentation
grSim_Commands::grSim_Commands ()
virtual grSim_Commands::~grSim_Commands () virtual
grSim_Commands::grSim_Commands (const grSim_Commands & from)
Member Function Documentation
grSim_Robot_Command * grSim_Commands::add_robot_commands () inline
Definition at line 740 of file grSim_Commands.pb.h.
Referenced by Callback(), CallbackCmd(), and MainWindow::sendPacket().
{
   // @@protoc_insertion_point(field_add:grSim_Commands.robot_commands)
   return robot_commands_.Add();
 }
size_t grSim_Commands::ByteSizeLong () const
void grSim_Commands::Clear ()
void grSim_Commands::clear_has_isteamyellow () inline private
Definition at line 708 of file grSim_Commands.pb.h.
References grSim_Robot_Command::_has_bits_.
{
   _has_bits_[0] &= ~0x00000002u;
 }
void grSim_Commands::clear_has_timestamp () inline private
Definition at line 684 of file grSim_Commands.pb.h.
References grSim_Robot_Command::_has_bits_.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void grSim_Commands::clear_isteamyellow () inline
Definition at line 711 of file grSim_Commands.pb.h.
{
   isteamyellow_ = false;
   clear_has_isteamyellow();
 }
void grSim_Commands::clear_robot_commands () inline
Definition at line 729 of file grSim_Commands.pb.h.
{
   robot_commands_.Clear();
 }
void grSim_Commands::clear_timestamp () inline
Definition at line 687 of file grSim_Commands.pb.h.
{
   timestamp_ = 0;
   clear_has_timestamp();
 }
void grSim_Commands::CopyFrom (const ::google::protobuf::Message & from)
void grSim_Commands::CopyFrom (const grSim_Commands & from)
static const grSim_Commands& grSim_Commands::default_instance () static
static const ::google::protobuf::Descriptor* grSim_Commands::descriptor () static
inline ::google::protobuf::Arena* grSim_Commands::GetArenaNoVirtual () const inline private
Definition at line 315 of file grSim_Commands.pb.h.
{
     return NULL;
   }
int grSim_Commands::GetCachedSize () const inline
Definition at line 308 of file grSim_Commands.pb.h.
References grSim_Robot_Command::_cached_size_, grSim_Robot_Command::InternalSwap(), grSim_Robot_Command::SetCachedSize(), grSim_Robot_Command::SharedCtor(), and grSim_Robot_Command::SharedDtor().
 { return _cached_size_; }
::google::protobuf::Metadata grSim_Commands::GetMetadata () const
bool grSim_Commands::has_isteamyellow () const inline
Definition at line 702 of file grSim_Commands.pb.h.
References grSim_Robot_Command::_has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool grSim_Commands::has_timestamp () const inline
Definition at line 678 of file grSim_Commands.pb.h.
References grSim_Robot_Command::_has_bits_.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
static const grSim_Commands* grSim_Commands::internal_default_instance () inline static
Definition at line 278 of file grSim_Commands.pb.h.
References _grSim_Commands_default_instance_, and grSim_Robot_Command::Swap().
Referenced by grSim_Packet::commands().
{
     return reinterpret_cast<const grSim_Commands*>(
                &_grSim_Commands_default_instance_);
   }
::google::protobuf::uint8* grSim_Commands::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void grSim_Commands::InternalSwap (grSim_Commands * other) private
bool grSim_Commands::IsInitialized () const
bool grSim_Commands::isteamyellow () const inline
Definition at line 715 of file grSim_Commands.pb.h.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Commands.isteamyellow)
   return isteamyellow_;
 }
void* grSim_Commands::MaybeArenaPtr () const inline private
Definition at line 318 of file grSim_Commands.pb.h.
References grSim_Robot_Command::GetMetadata().
{
     return NULL;
   }
void grSim_Commands::MergeFrom (const ::google::protobuf::Message & from)
void grSim_Commands::MergeFrom (const grSim_Commands & from)
bool grSim_Commands::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
grSim_Robot_Command * grSim_Commands::mutable_robot_commands (int index) inline
Definition at line 736 of file grSim_Commands.pb.h.
{
   // @@protoc_insertion_point(field_mutable:grSim_Commands.robot_commands)
   return robot_commands_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::grSim_Robot_Command > * grSim_Commands::mutable_robot_commands () inline
Definition at line 745 of file grSim_Commands.pb.h.
{
   // @@protoc_insertion_point(field_mutable_list:grSim_Commands.robot_commands)
   return &robot_commands_;
 }
inline ::google::protobuf::UnknownFieldSet* grSim_Commands::mutable_unknown_fields () inline
Definition at line 271 of file grSim_Commands.pb.h.
References grSim_Robot_Command::_internal_metadata_, grSim_Robot_Command::default_instance(), and grSim_Robot_Command::descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
grSim_Commands* grSim_Commands::New () const inline
Definition at line 287 of file grSim_Commands.pb.h.
References grSim_Robot_Command::ByteSizeLong(), grSim_Robot_Command::Clear(), grSim_Robot_Command::CopyFrom(), grSim_Robot_Command::InternalSerializeWithCachedSizesToArray(), grSim_Robot_Command::IsInitialized(), grSim_Robot_Command::MergeFrom(), grSim_Robot_Command::MergePartialFromCodedStream(), grSim_Robot_Command::New(), New(), grSim_Robot_Command::SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
grSim_Commands* grSim_Commands::New (::google::protobuf::Arena * arena) const
grSim_Commands& grSim_Commands::operator= (const grSim_Commands & from) inline
Definition at line 262 of file grSim_Commands.pb.h.
References grSim_Robot_Command::CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* grSim_Commands::protobuf_Offsets_grSim_5fCommands_2eproto () private
size_t grSim_Commands::RequiredFieldsByteSizeFallback () const private
const ::grSim_Robot_Command & grSim_Commands::robot_commands (int index) const inline
Definition at line 732 of file grSim_Commands.pb.h.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_Commands.robot_commands)
   return robot_commands_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::grSim_Robot_Command > & grSim_Commands::robot_commands () const inline
Definition at line 750 of file grSim_Commands.pb.h.
{
   // @@protoc_insertion_point(field_list:grSim_Commands.robot_commands)
   return robot_commands_;
 }
int grSim_Commands::robot_commands_size () const inline
Definition at line 726 of file grSim_Commands.pb.h.
Referenced by SSLWorld::recvActions().
{
   return robot_commands_.size();
 }
void grSim_Commands::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* grSim_Commands::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 304 of file grSim_Commands.pb.h.
References grSim_Robot_Command::InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void grSim_Commands::set_has_isteamyellow () inline private
Definition at line 705 of file grSim_Commands.pb.h.
References grSim_Robot_Command::_has_bits_.
{
   _has_bits_[0] |= 0x00000002u;
 }
void grSim_Commands::set_has_timestamp () inline private
Definition at line 681 of file grSim_Commands.pb.h.
References grSim_Robot_Command::_has_bits_.
{
   _has_bits_[0] |= 0x00000001u;
 }
void grSim_Commands::set_isteamyellow (bool value) inline
Definition at line 719 of file grSim_Commands.pb.h.
Referenced by Callback(), CallbackCmd(), and MainWindow::sendPacket().
{
   set_has_isteamyellow();
   isteamyellow_ = value;
   // @@protoc_insertion_point(field_set:grSim_Commands.isteamyellow)
 }
void grSim_Commands::set_timestamp (double value) inline
Definition at line 695 of file grSim_Commands.pb.h.
Referenced by Callback(), CallbackCmd(), and MainWindow::sendPacket().
{
   set_has_timestamp();
   timestamp_ = value;
   // @@protoc_insertion_point(field_set:grSim_Commands.timestamp)
 }
void grSim_Commands::SetCachedSize (int size) const private
void grSim_Commands::SharedCtor () private
void grSim_Commands::SharedDtor () private
void grSim_Commands::Swap (grSim_Commands * other)
double grSim_Commands::timestamp () const inline
Definition at line 691 of file grSim_Commands.pb.h.
{
   // @@protoc_insertion_point(field_get:grSim_Commands.timestamp)
   return timestamp_;
 }
const ::google::protobuf::UnknownFieldSet& grSim_Commands::unknown_fields () const inline
Definition at line 267 of file grSim_Commands.pb.h.
References grSim_Robot_Command::_internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
Friends And Related Function Documentation
void protobuf_AddDesc_grSim_5fCommands_2eproto_impl () friend
void protobuf_InitDefaults_grSim_5fCommands_2eproto_impl () friend
void protobuf_ShutdownFile_grSim_5fCommands_2eproto () friend
Field Documentation
int grSim_Commands::_cached_size_ mutable private
Definition at line 367 of file grSim_Commands.pb.h.
::google::protobuf::internal::HasBits<1> grSim_Commands::_has_bits_ private
Definition at line 366 of file grSim_Commands.pb.h.
::google::protobuf::internal::InternalMetadataWithArena grSim_Commands::_internal_metadata_ private
Definition at line 365 of file grSim_Commands.pb.h.
bool grSim_Commands::isteamyellow_ private
Definition at line 370 of file grSim_Commands.pb.h.
const int grSim_Commands::kIsteamyellowFieldNumber = 2 static
Definition at line 339 of file grSim_Commands.pb.h.
const int grSim_Commands::kRobotCommandsFieldNumber = 3 static
Definition at line 346 of file grSim_Commands.pb.h.
const int grSim_Commands::kTimestampFieldNumber = 1 static
Definition at line 332 of file grSim_Commands.pb.h.
::google::protobuf::RepeatedPtrField< ::grSim_Robot_Command > grSim_Commands::robot_commands_ private
Definition at line 368 of file grSim_Commands.pb.h.
double grSim_Commands::timestamp_ private
Definition at line 369 of file grSim_Commands.pb.h.
The documentation for this class was generated from the following file:
grsim_comm/include/proto/grSim_Commands.pb.h