Documentation: VarTypes Namespace Reference
VarTypes Namespace Reference
Data Structures
struct ALLXMLClearTag
struct NextToken
class SafeVarVal
class VarBase64
A singleton wrapper to XMLParserBase64Tool.
class VarBlob
A Vartype for storing binary data.
class VarBool
A Vartype for storing booleans.
class VarBoolVal
A Vartype for storing booleans.
class VarDouble
A Vartype for storing double precision floating points.
class VarDoubleVal
class VarExternal
A list of VarTypes to be stored in an separate XML file.
class VarInt
A Vartype for storing integers.
class VarIntVal
A Vartype for storing integers.
class VarItem
The 'item' inheriting QStandardItem for displaying VarTypes in the QT4 Item-Model.
class VarItemDelegate
The 'item-delegate' inheriting QItemDelegate for displaying VarTypes in the QT4 Item-Model.
class VarList
This is the list type of the VarTypes system.
class VarNotifier
A helper class which accumulates the occurence of VarType changes.
class VarProtoBuffer
A Vartype for storing integers.
class VarProtoBufferVal
A Vartype that wraps around google protocol buffers.
class VarQWidget
An Vartype for embedding QWidgets into the Var-tree.
class VarSelection
This is the multi-selection VarType of the VarTypes system.
class VarString
This is the string VarType of the VarTypes system.
class VarStringEnum
This is the string enumeration VarType of the VarTypes system.
class VarStringVal
This is the string VarTypeVal of the VarTypes system.
class VarTreeModel
The 'item-model' inheriting QStandardItemModel for displaying VarTypes in the QT4 Item-Model.
class VarTreeView
The 'view' using a QTreeView for displaying VarTypes in the QT4 Item-Model.
class VarTreeViewOptions
An internal set of rendering parameters used by the VarTypes view-model.
class VarTrigger
This is a Trigger-like VarType of the VarTypes system.
class VarType
The base class of the VarTypes system.
class VarTypesFactory
class VarTypesInstance
A singleton wrapper to VarTypesFactory.
class VarTypeTemplate
class VarVal
class VarXML
XML helper functions of the VarType system.
struct XML
struct XMLAttribute
struct XMLCharacterEntity
struct XMLClear
struct XMLNode
struct XMLNodeContents
class XMLParserBase64Tool
struct XMLResults
Typedefs
typedef int GuiColumnFlag
typedef int VarTypeFlag
typedef uint8_t VarTypeId
typedef enum VarTypes::XMLTokenTypeTag XMLTokenType
typedef struct VarTypes::XML XML
typedef enum VarTypes::Attrib Attrib
typedef enum VarTypes::Status Status
typedef enum VarTypes::XMLError XMLError
typedef enum VarTypes::XMLElementType XMLElementType
typedef struct VarTypes::XMLResults XMLResults
typedef struct VarTypes::XMLNode XMLNode
typedef struct VarTypes::XMLNodeContents XMLNodeContents
Enumerations
enum GuiColumnFlagEnum {
GUI_COLUMN_FLAG_NONE =0x00, GUI_COLUMN_FLAG_TREE_NODE =0x01 << 0, GUI_COLUMN_FLAG_TEXT_LABEL =0x01 << 1, GUI_COLUMN_FLAG_ICON =0x01 << 2,
GUI_COLUMN_FLAG_TEXT_VALUE =0x01 << 3, GUI_COLUMN_FLAG_EDITABLE =0x01 << 4, GUI_COLUMN_FLAG_RANGEBARS =0x01 << 5
}
enum VarTypeFlagEnum {
VARTYPE_FLAG_NONE = 0x00, VARTYPE_FLAG_READONLY = 0x01 << 0, VARTYPE_FLAG_HIDDEN = 0x01 << 1, VARTYPE_FLAG_AUTO_EXPAND = 0x01 << 2,
VARTYPE_FLAG_AUTO_EXPAND_TREE = 0x01 << 3, VARTYPE_FLAG_NOSAVE = 0x01 << 4, VARTYPE_FLAG_NOLOAD = 0x01 << 5, VARTYPE_FLAG_PERSISTENT = 0x01 << 6,
VARTYPE_FLAG_HIDE_CHILDREN = 0x01 << 7, VARTYPE_FLAG_NOLOAD_ENUM_CHILDREN = 0x01 << 8, VARTYPE_FLAG_NOLOAD_ATTRIBUTES = 0x01 << 9, VARTYPE_FLAG_ENUM_COUNT = 0x01 << 10,
VARTYPE_FLAG_NOSTORE = VARTYPE_FLAG_NOSAVE | VARTYPE_FLAG_NOLOAD
}
enum VarTypeIdEnum {
VARTYPE_ID_UNDEFINED =0, VARTYPE_ID_BOOL, VARTYPE_ID_INT, VARTYPE_ID_DOUBLE,
VARTYPE_ID_STRING, VARTYPE_ID_BLOB, VARTYPE_ID_EXTERNAL, VARTYPE_ID_VECTOR2D,
VARTYPE_ID_VECTOR3D, VARTYPE_ID_TIMEVAR, VARTYPE_ID_TIMELINE, VARTYPE_ID_LIST,
VARTYPE_ID_STRINGENUM, VARTYPE_ID_SELECTION, VARTYPE_ID_TRIGGER, VARTYPE_ID_QWIDGET,
VARTYPE_ID_COUNT, VARTYPE_ID_MIN_USERTYPE =128
}
enum XMLTokenTypeTag {
eTokenText = 0, eTokenQuotedText, eTokenTagStart, eTokenTagEnd,
eTokenCloseTag, eTokenEquals, eTokenDeclaration, eTokenShortHandClose,
eTokenClear, eTokenError
}
enum Attrib { eAttribName = 0, eAttribEquals, eAttribValue }
enum Status { eInsideTag = 0, eOutsideTag }
enum XMLError {
eXMLErrorNone = 0, eXMLErrorMissingEndTag, eXMLErrorEmpty, eXMLErrorFirstNotStartTag,
eXMLErrorMissingTagName, eXMLErrorMissingEndTagName, eXMLErrorNoMatchingQuote, eXMLErrorUnmatchedEndTag,
eXMLErrorUnmatchedEndClearTag, eXMLErrorUnexpectedToken, eXMLErrorInvalidTag, eXMLErrorNoElements,
eXMLErrorFileNotFound, eXMLErrorFirstTagNotFound, eXMLErrorUnknownCharacterEntity, eXMLErrorCharConversionError,
eXMLErrorCannotOpenWriteFile, eXMLErrorCannotWriteFile, eXMLErrorBase64DataSizeIsNotMultipleOf4, eXMLErrorBase64DecodeIllegalCharacter,
eXMLErrorBase64DecodeTruncatedData, eXMLErrorBase64DecodeBufferTooSmall
}
enum XMLElementType {
eNodeChild =0, eNodeAttribute =1, eNodeText =2, eNodeClear =3,
eNodeNULL =4
}
Functions
void free_XMLDLL (void *t)
int mmin (const int t1, const int t2)
char myIsTextUnicode (const void *b, int len)
char * myWideCharToMultiByte (const wchar_t *s, int l)
FILE * _tfopen (const char *filename, const char *mode)
int _tcslen (const char *c)
int _tcsnicmp (const char *c1, const char *c2, int l)
int _tcsicmp (const char *c1, const char *c2)
char * _tcsstr (const char *c1, const char *c2)
char * _tcscpy (char *c1, const char *c2)
int _strnicmp (const char *c1, const char *c2, int l)
char * stringDup (const char *lpszData, int cbData)
char * toXMLString (char *dest, const char *source)
int lengthXMLString (const char *source)
char * toXMLString (const char *source)
char * toXMLStringFast (char **dest, int *destSz, const char *source)
char * fromXMLString (const char *s, int lo, XML *pXML)
char myTagCompare (const char *cclose, const char *copen)
static char getNextChar (XML *pXML)
static NextToken GetNextToken (XML *pXML, int *pcbToken, enum XMLTokenTypeTag *pType)
static void * myRealloc (void *p, int newsize, int memInc, int sizeofElem)
static void CountLinesAndColumns (const char *lpXML, int nUpto, XMLResults *pResults)
static void charmemset (char *dest, char c, int l)
Variables
static char strictUTF8Parsing =1
static char guessUnicodeChars =1
static char dropWhiteSpace =1
static ALLXMLClearTag XMLClearTags []
static XMLCharacterEntity XMLEntities []
static const char XML_utf8ByteTable [256]
static const char XML_asciiByteTable [256]
static const char * XML_ByteTable =(const char *)XML_utf8ByteTable
static const char base64Fillchar = '='
const char * base64EncodeTable = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
const unsigned char base64DecodeTable []
Detailed Description
Author
Stefan Zickler szick.nosp@m.ler@.nosp@m.cs.cm.nosp@m.u.ed.nosp@m.u
Typedef Documentation
typedef enum VarTypes::Attrib VarTypes::Attrib
typedef int VarTypes::GuiColumnFlag
Definition at line 35 of file VarTreeViewOptions.h.
typedef enum VarTypes::Status VarTypes::Status
typedef int VarTypes::VarTypeFlag
Definition at line 81 of file VarType.h.
typedef uint8_t VarTypes::VarTypeId
Definition at line 29 of file VarVal.h.
typedef struct VarTypes::XML VarTypes::XML
typedef enum VarTypes::XMLElementType VarTypes::XMLElementType
typedef enum VarTypes::XMLError VarTypes::XMLError
typedef struct VarTypes::XMLNode VarTypes::XMLNode
typedef struct VarTypes::XMLNodeContents VarTypes::XMLNodeContents
typedef struct VarTypes::XMLResults VarTypes::XMLResults
typedef enum VarTypes::XMLTokenTypeTag VarTypes::XMLTokenType
Enumeration Type Documentation
enum VarTypes::Attrib
Enumerator
eAttribName
eAttribEquals
eAttribValue
Definition at line 517 of file xmlParser.cpp.
   {
       eAttribName = 0,
       eAttribEquals,
       eAttribValue
   } Attrib;
enum VarTypes::GuiColumnFlagEnum
Enumerator
GUI_COLUMN_FLAG_NONE
GUI_COLUMN_FLAG_TREE_NODE
GUI_COLUMN_FLAG_TEXT_LABEL
GUI_COLUMN_FLAG_ICON
GUI_COLUMN_FLAG_TEXT_VALUE
GUI_COLUMN_FLAG_EDITABLE
GUI_COLUMN_FLAG_RANGEBARS
Definition at line 25 of file VarTreeViewOptions.h.
{
     GUI_COLUMN_FLAG_NONE=0x00,
     GUI_COLUMN_FLAG_TREE_NODE=0x01 << 0,
     GUI_COLUMN_FLAG_TEXT_LABEL=0x01 << 1,
     GUI_COLUMN_FLAG_ICON=0x01 << 2,
     GUI_COLUMN_FLAG_TEXT_VALUE=0x01 << 3,
     GUI_COLUMN_FLAG_EDITABLE=0x01 << 4,
     GUI_COLUMN_FLAG_RANGEBARS=0x01 << 5,
   };
enum VarTypes::Status
Enumerator
eInsideTag
eOutsideTag
Definition at line 526 of file xmlParser.cpp.
   {
       eInsideTag = 0,
       eOutsideTag
   } Status;
enum VarTypes::VarTypeFlagEnum
Enumerator
VARTYPE_FLAG_NONE
VARTYPE_FLAG_READONLY
no special properties
VARTYPE_FLAG_HIDDEN
this vartype is not editable in the GUI
VARTYPE_FLAG_AUTO_EXPAND
this vartype will be hidden in the GUI
VARTYPE_FLAG_AUTO_EXPAND_TREE
whether to expand this node by default
VARTYPE_FLAG_NOSAVE
whether to expand this node and all of its sub-nodes by default
VARTYPE_FLAG_NOLOAD
don't store this subtree to XML
VARTYPE_FLAG_PERSISTENT
don't load this subtree from XML
VARTYPE_FLAG_HIDE_CHILDREN
make the item editor be persistent (always open, not just when clicked on it)
VARTYPE_FLAG_NOLOAD_ENUM_CHILDREN
hide the entire subtree (but not node itself)
VARTYPE_FLAG_NOLOAD_ATTRIBUTES
don't load this subtree from XML
VARTYPE_FLAG_ENUM_COUNT
only load the value, but do not load the attributes, like min/max ranges.
VARTYPE_FLAG_NOSTORE
Definition at line 65 of file VarType.h.
{
     VARTYPE_FLAG_NONE = 0x00,
     VARTYPE_FLAG_READONLY= 0x01 << 0,
     VARTYPE_FLAG_HIDDEN  = 0x01 << 1,
     VARTYPE_FLAG_AUTO_EXPAND = 0x01 << 2,
     VARTYPE_FLAG_AUTO_EXPAND_TREE = 0x01 << 3,
     VARTYPE_FLAG_NOSAVE = 0x01 << 4,
     VARTYPE_FLAG_NOLOAD = 0x01 << 5,
     VARTYPE_FLAG_PERSISTENT = 0x01 << 6,
     VARTYPE_FLAG_HIDE_CHILDREN = 0x01 << 7,
     VARTYPE_FLAG_NOLOAD_ENUM_CHILDREN = 0x01 << 8,
     VARTYPE_FLAG_NOLOAD_ATTRIBUTES = 0x01 << 9,
     VARTYPE_FLAG_ENUM_COUNT = 0x01 << 10,
     VARTYPE_FLAG_NOSTORE = VARTYPE_FLAG_NOSAVE | VARTYPE_FLAG_NOLOAD
   };
enum VarTypes::VarTypeIdEnum
Enumerator
VARTYPE_ID_UNDEFINED
VARTYPE_ID_BOOL
VARTYPE_ID_INT
VARTYPE_ID_DOUBLE
VARTYPE_ID_STRING
VARTYPE_ID_BLOB
VARTYPE_ID_EXTERNAL
VARTYPE_ID_VECTOR2D
VARTYPE_ID_VECTOR3D
VARTYPE_ID_TIMEVAR
VARTYPE_ID_TIMELINE
VARTYPE_ID_LIST
VARTYPE_ID_STRINGENUM
VARTYPE_ID_SELECTION
VARTYPE_ID_TRIGGER
VARTYPE_ID_QWIDGET
VARTYPE_ID_COUNT
VARTYPE_ID_MIN_USERTYPE
Definition at line 30 of file VarVal.h.
                      {
     VARTYPE_ID_UNDEFINED=0,
     VARTYPE_ID_BOOL,
     VARTYPE_ID_INT,
     VARTYPE_ID_DOUBLE,
     VARTYPE_ID_STRING,
     VARTYPE_ID_BLOB,
     VARTYPE_ID_EXTERNAL,
     VARTYPE_ID_VECTOR2D,
     VARTYPE_ID_VECTOR3D,
     VARTYPE_ID_TIMEVAR,
     VARTYPE_ID_TIMELINE,
     VARTYPE_ID_LIST,
     VARTYPE_ID_STRINGENUM,
     VARTYPE_ID_SELECTION,
     VARTYPE_ID_TRIGGER,
     VARTYPE_ID_QWIDGET,
     VARTYPE_ID_COUNT,
     VARTYPE_ID_MIN_USERTYPE=128
   };
enum VarTypes::XMLElementType
Enumerator
eNodeChild
eNodeAttribute
eNodeText
eNodeClear
eNodeNULL
Definition at line 144 of file xmlParser.h.
 {
     eNodeChild=0,
     eNodeAttribute=1,
     eNodeText=2,
     eNodeClear=3,
     eNodeNULL=4
 } XMLElementType;
enum VarTypes::XMLError
Enumerator
eXMLErrorNone
eXMLErrorMissingEndTag
eXMLErrorEmpty
eXMLErrorFirstNotStartTag
eXMLErrorMissingTagName
eXMLErrorMissingEndTagName
eXMLErrorNoMatchingQuote
eXMLErrorUnmatchedEndTag
eXMLErrorUnmatchedEndClearTag
eXMLErrorUnexpectedToken
eXMLErrorInvalidTag
eXMLErrorNoElements
eXMLErrorFileNotFound
eXMLErrorFirstTagNotFound
eXMLErrorUnknownCharacterEntity
eXMLErrorCharConversionError
eXMLErrorCannotOpenWriteFile
eXMLErrorCannotWriteFile
eXMLErrorBase64DataSizeIsNotMultipleOf4
eXMLErrorBase64DecodeIllegalCharacter
eXMLErrorBase64DecodeTruncatedData
eXMLErrorBase64DecodeBufferTooSmall
Definition at line 116 of file xmlParser.h.
 {
     eXMLErrorNone = 0,
     eXMLErrorMissingEndTag,
     eXMLErrorEmpty,
     eXMLErrorFirstNotStartTag,
     eXMLErrorMissingTagName,
     eXMLErrorMissingEndTagName,
     eXMLErrorNoMatchingQuote,
     eXMLErrorUnmatchedEndTag,
     eXMLErrorUnmatchedEndClearTag,
     eXMLErrorUnexpectedToken,
     eXMLErrorInvalidTag,
     eXMLErrorNoElements,
     eXMLErrorFileNotFound,
     eXMLErrorFirstTagNotFound,
     eXMLErrorUnknownCharacterEntity,
     eXMLErrorCharConversionError,
     eXMLErrorCannotOpenWriteFile,
     eXMLErrorCannotWriteFile,
     eXMLErrorBase64DataSizeIsNotMultipleOf4,
     eXMLErrorBase64DecodeIllegalCharacter,
     eXMLErrorBase64DecodeTruncatedData,
     eXMLErrorBase64DecodeBufferTooSmall
 } XMLError;
enum VarTypes::XMLTokenTypeTag
Enumerator
eTokenText
eTokenQuotedText
eTokenTagStart
eTokenTagEnd
eTokenCloseTag
eTokenEquals
eTokenDeclaration
eTokenShortHandClose
eTokenClear
eTokenError
Definition at line 482 of file xmlParser.cpp.
   {
       eTokenText = 0,
       eTokenQuotedText,
       eTokenTagStart,         /* "<"            */
       eTokenTagEnd,           /* "</"           */
       eTokenCloseTag,         /* ">"            */
       eTokenEquals,           /* "="            */
       eTokenDeclaration,      /* "<?"           */
       eTokenShortHandClose,   /* "/>"           */
       eTokenClear,
       eTokenError
   } XMLTokenType;
Function Documentation
int VarTypes::_strnicmp (const char * c1, const char * c2, int l)
Definition at line 330 of file xmlParser.cpp.
Referenced by VarTypes::XMLNode::guessUTF8ParsingParameterValue(), myIsTextUnicode(), and myWideCharToMultiByte().
 { return strncasecmp(c1,c2,l);}
char* VarTypes::_tcscpy (char * c1, const char * c2)
Definition at line 325 of file xmlParser.cpp.
References XMLSTR.
Referenced by VarTypes::XMLNode::CreateXMLStringR(), myWideCharToMultiByte(), and toXMLString().
 { return (XMLSTR)strcpy(c1,c2); }
int VarTypes::_tcsicmp (const char * c1, const char * c2)
Definition at line 323 of file xmlParser.cpp.
Referenced by VarTypes::XMLNode::getAttribute(), VarTypes::XMLNode::getChildNode(), VarTypes::XMLNode::getChildNodeWithAttribute(), VarTypes::XMLNode::isAttributeSet(), myWideCharToMultiByte(), VarTypes::XMLNode::nChildNode(), and VarTypes::XMLNode::parseString().
 { return strcasecmp(c1,c2); }
int VarTypes::_tcslen (const char * c)
Definition at line 321 of file xmlParser.cpp.
Referenced by myTagCompare(), myWideCharToMultiByte(), VarTypes::XMLNode::parseClearTag(), VarTypes::XMLNode::parseString(), and stringDup().
 { return strlen(c); }
int VarTypes::_tcsnicmp (const char * c1, const char * c2, int l)
Definition at line 322 of file xmlParser.cpp.
Referenced by fromXMLString(), GetNextToken(), myTagCompare(), and myWideCharToMultiByte().
 { return strncasecmp(c1,c2,l);}
char* VarTypes::_tcsstr (const char * c1, const char * c2)
Definition at line 324 of file xmlParser.cpp.
References XMLSTR.
Referenced by myWideCharToMultiByte(), and VarTypes::XMLNode::parseClearTag().
 { return (XMLSTR)strstr(c1,c2); }
FILE* VarTypes::_tfopen (const char * filename, const char * mode)
Definition at line 320 of file xmlParser.cpp.
Referenced by myWideCharToMultiByte(), VarTypes::XMLNode::openFileHelper(), VarTypes::XMLNode::parseFile(), and VarTypes::XMLNode::writeToFile().
 { return fopen(filename,mode); }
static void VarTypes::charmemset (char * dest, char c, int l) inline static
Definition at line 1684 of file xmlParser.cpp.
Referenced by VarTypes::XMLNode::CreateXMLStringR().
 { while (l--) *(dest++)=c; }
static void VarTypes::CountLinesAndColumns (const char * lpXML, int nUpto, XMLResults * pResults) static
Definition at line 1540 of file xmlParser.cpp.
References _T, eXMLErrorNone, getNextChar(), VarTypes::XMLResults::nColumn, VarTypes::XML::nIndex, VarTypes::XMLResults::nLine, TRUE, and XMLCHAR.
Referenced by VarTypes::XMLNode::parseString().
   {
       XMLCHAR ch;
       assert(lpXML);
       assert(pResults);
       struct XML xml={ lpXML,lpXML, 0, 0, eXMLErrorNone, NULL, 0, NULL, 0, TRUE };
       pResults->nLine = 1;
       pResults->nColumn = 1;
       while (xml.nIndex<nUpto)
       {
           ch = getNextChar(&xml);
           if (ch != _T('\n')) pResults->nColumn++;
           else
           {
               pResults->nLine++;
               pResults->nColumn=1;
           }
       }
   }
void VarTypes::free_XMLDLL (void * t)
Definition at line 97 of file xmlParser.cpp.
 {free(t);}
char* VarTypes::fromXMLString (const char * s, int lo, XML * pXML)
Definition at line 603 of file xmlParser.cpp.
References _T, _tcsnicmp(), VarTypes::XMLCharacterEntity::c, VarTypes::XMLNode::d, VarTypes::XML::error, eXMLErrorUnknownCharacterEntity, VarTypes::XMLCharacterEntity::l, VarTypes::XMLCharacterEntity::s, XMLCHAR, XMLCSTR, XMLEntities, and XMLSTR.
Referenced by VarTypes::XMLNode::maybeAddTxT(), and VarTypes::XMLNode::ParseXMLElement().
   {
       // This function is the opposite of the function "toXMLString". It decodes the escape
       // sequences &amp;, &quot;, &apos;, &lt;, &gt; and replace them by the characters
       // &,",',<,>. This function is used internally by the XML Parser. All the calls to
       // the XML library will always gives you back "decoded" strings.
       //
       // in: string (s) and length (lo) of string
       // out:  new allocated string converted from xml
       if (!s) return NULL;
       int ll=0,j;
       XMLSTR d;
       XMLCSTR ss=s;
       XMLCharacterEntity *entity;
       while ((lo>0)&&(*s))
       {
           if (*s==_T('&'))
           {
               if ((lo>2)&&(s[1]==_T('#')))
               {
                   s+=2; lo-=2;
                   if ((*s==_T('X'))||(*s==_T('x'))) { s++; lo--; }
                   while ((*s)&&(*s!=_T(';'))&&((lo--)>0)) s++;
                   if (*s!=_T(';'))
                   {
                       pXML->error=eXMLErrorUnknownCharacterEntity;
                       return NULL;
                   }
                   s++; lo--;
               } else
               {
                   entity=XMLEntities;
                   do
                   {
                       if ((lo>=entity->l)&&(_tcsnicmp(s,entity->s,entity->l)==0)) { s+=entity->l; lo-=entity->l; break; }
                       entity++;
                   } while(entity->s);
                   if (!entity->s)
                   {
                       pXML->error=eXMLErrorUnknownCharacterEntity;
                       return NULL;
                   }
               }
           } else
           {
   #ifdef _XMLUNICODE
               s++; lo--;
   #else
               j=XML_ByteTable[(unsigned char)*s]; s+=j; lo-=j; ll+=j-1;
   #endif
           }
           ll++;
       }
       d=(XMLSTR)malloc((ll+1)*sizeof(XMLCHAR));
       s=d;
       while (ll-->0)
       {
           if (*ss==_T('&'))
           {
               if (ss[1]==_T('#'))
               {
                   ss+=2; j=0;
                   if ((*ss==_T('X'))||(*ss==_T('x')))
                   {
                       ss++;
                       while (*ss!=_T(';'))
                       {
                           if ((*ss>=_T('0'))&&(*ss<=_T('9'))) j=(j<<4)+*ss-_T('0');
                           else if ((*ss>=_T('A'))&&(*ss<=_T('F'))) j=(j<<4)+*ss-_T('A')+10;
                           else if ((*ss>=_T('a'))&&(*ss<=_T('f'))) j=(j<<4)+*ss-_T('a')+10;
                           else { free((void*)s); pXML->error=eXMLErrorUnknownCharacterEntity;return NULL;}
                           ss++;
                       }
                   } else
                   {
                       while (*ss!=_T(';'))
                       {
                           if ((*ss>=_T('0'))&&(*ss<=_T('9'))) j=(j*10)+*ss-_T('0');
                           else { free((void*)s); pXML->error=eXMLErrorUnknownCharacterEntity;return NULL;}
                           ss++;
                       }
                   }
                   (*d++)=(XMLCHAR)j; ss++;
               } else
               {
                   entity=XMLEntities;
                   do
                   {
                       if (_tcsnicmp(ss,entity->s,entity->l)==0) { *(d++)=entity->c; ss+=entity->l; break; }
                       entity++;
                   } while(entity->s);
               }
           } else
           {
   #ifdef _XMLUNICODE
               *(d++)=*(ss++);
   #else
               switch(XML_ByteTable[(unsigned char)*ss])
               {
               case 4: *(d++)=*(ss++); ll--;
               case 3: *(d++)=*(ss++); ll--;
               case 2: *(d++)=*(ss++); ll--;
               case 1: *(d++)=*(ss++);
               }
   #endif
           }
       }
       *d=0;
       return (XMLSTR)s;
   }
static char VarTypes::getNextChar (XML * pXML) inline static
Definition at line 737 of file xmlParser.cpp.
References VarTypes::XML::lpXML, VarTypes::XML::nIndex, and XMLCHAR.
Referenced by CountLinesAndColumns(), and GetNextToken().
   {
       XMLCHAR ch = pXML->lpXML[pXML->nIndex];
   #ifdef _XMLUNICODE
       if (ch!=0) pXML->nIndex++;
   #else
       pXML->nIndex+=XML_ByteTable[(unsigned char)ch];
   #endif
       return ch;
   }
static NextToken VarTypes::GetNextToken (XML * pXML, int * pcbToken, enum XMLTokenTypeTag * pType) static
Definition at line 750 of file xmlParser.cpp.
References _T, _tcsnicmp(), eTokenClear, eTokenCloseTag, eTokenDeclaration, eTokenEquals, eTokenError, eTokenQuotedText, eTokenShortHandClose, eTokenTagEnd, eTokenTagStart, eTokenText, FALSE, getNextChar(), VarTypes::ALLXMLClearTag::lpszOpen, VarTypes::XML::lpXML, VarTypes::XML::nIndex, VarTypes::ALLXMLClearTag::openTagLen, VarTypes::NextToken::pClr, VarTypes::NextToken::pStr, TRUE, XML_isSPACECHAR, XMLCHAR, and XMLClearTags.
Referenced by VarTypes::XMLNode::ParseXMLElement().
   {
       NextToken        result;
       XMLCHAR            ch;
       XMLCHAR            chTemp;
       int              indexStart,nFoundMatch,nIsText=FALSE;
       result.pClr=NULL; // prevent warning
       // Find next non-white space character
       do { indexStart=pXML->nIndex; ch=getNextChar(pXML); } while XML_isSPACECHAR(ch);
       if (ch)
       {
           // Cache the current string pointer
           result.pStr = &pXML->lpXML[indexStart];
           // First check whether the token is in the clear tag list (meaning it
           // does not need formatting).
           ALLXMLClearTag *ctag=XMLClearTags;
           do
           {
               if (_tcsnicmp(ctag->lpszOpen, result.pStr, ctag->openTagLen)==0)
               {
                   result.pClr=ctag;
                   pXML->nIndex+=ctag->openTagLen-1;
                   *pType=eTokenClear;
                   return result;
               }
               ctag++;
           } while(ctag->lpszOpen);
           // If we didn't find a clear tag then check for standard tokens
           switch(ch)
           {
           // Check for quotes
           case _T('\''):
           case _T('\"'):
               // Type of token
               *pType = eTokenQuotedText;
               chTemp = ch;
               // Set the size
               nFoundMatch = FALSE;
               // Search through the string to find a matching quote
               while((ch = getNextChar(pXML)))
               {
                   if (ch==chTemp) { nFoundMatch = TRUE; break; }
                   if (ch==_T('<')) break;
               }
               // If we failed to find a matching quote
               if (nFoundMatch == FALSE)
               {
                   pXML->nIndex=indexStart+1;
                   nIsText=TRUE;
                   break;
               }
   //  4.02.2002
   //            if (FindNonWhiteSpace(pXML)) pXML->nIndex--;
               break;
           // Equals (used with attribute values)
           case _T('='):
               *pType = eTokenEquals;
               break;
           // Close tag
           case _T('>'):
               *pType = eTokenCloseTag;
               break;
           // Check for tag start and tag end
           case _T('<'):
               // Peek at the next character to see if we have an end tag '</',
               // or an xml declaration '<?'
               chTemp = pXML->lpXML[pXML->nIndex];
               // If we have a tag end...
               if (chTemp == _T('/'))
               {
                   // Set the type and ensure we point at the next character
                   getNextChar(pXML);
                   *pType = eTokenTagEnd;
               }
               // If we have an XML declaration tag
               else if (chTemp == _T('?'))
               {
                   // Set the type and ensure we point at the next character
                   getNextChar(pXML);
                   *pType = eTokenDeclaration;
               }
               // Otherwise we must have a start tag
               else
               {
                   *pType = eTokenTagStart;
               }
               break;
           // Check to see if we have a short hand type end tag ('/>').
           case _T('/'):
               // Peek at the next character to see if we have a short end tag '/>'
               chTemp = pXML->lpXML[pXML->nIndex];
               // If we have a short hand end tag...
               if (chTemp == _T('>'))
               {
                   // Set the type and ensure we point at the next character
                   getNextChar(pXML);
                   *pType = eTokenShortHandClose;
                   break;
               }
               // If we haven't found a short hand closing tag then drop into the
               // text process
           // Other characters
           default:
               nIsText = TRUE;
           }
           // If this is a TEXT node
           if (nIsText)
           {
               // Indicate we are dealing with text
               *pType = eTokenText;
               while((ch = getNextChar(pXML)))
               {
                   if XML_isSPACECHAR(ch)
                   {
                       indexStart++; break;
                   } else if (ch==_T('/'))
                   {
                       // If we find a slash then this maybe text or a short hand end tag
                       // Peek at the next character to see it we have short hand end tag
                       ch=pXML->lpXML[pXML->nIndex];
                       // If we found a short hand end tag then we need to exit the loop
                       if (ch==_T('>')) { pXML->nIndex--; break; }
                   } else if ((ch==_T('<'))||(ch==_T('>'))||(ch==_T('=')))
                   {
                       pXML->nIndex--; break;
                   }
               }
           }
           *pcbToken = pXML->nIndex-indexStart;
       } else
       {
           // If we failed to obtain a valid character
           *pcbToken = 0;
           *pType = eTokenError;
           result.pStr=NULL;
       }
       return result;
   }
int VarTypes::lengthXMLString (const char * source)
Definition at line 565 of file xmlParser.cpp.
References VarTypes::XMLCharacterEntity::c, VarTypes::XMLCharacterEntity::l, VarTypes::XMLCharacterEntity::s, XMLCHAR, and XMLEntities.
Referenced by VarTypes::XMLNode::CreateXMLStringR(), toXMLString(), and toXMLStringFast().
   {
       int r=0;
       XMLCharacterEntity *entity;
       XMLCHAR ch;
       while ((ch=*source))
       {
           entity=XMLEntities;
           do
           {
               if (ch==entity->c) { r+=entity->l; source++; goto out_of_loop1; }
               entity++;
           } while(entity->s);
   #ifdef _XMLUNICODE
           r++; source++;
   #else
           ch=XML_ByteTable[(unsigned char)ch]; r+=ch; source+=ch;
   #endif
   out_of_loop1:
           ;
       }
       return r;
   }
int VarTypes::mmin (const int t1, const int t2) inline
Definition at line 101 of file xmlParser.cpp.
Referenced by VarTypes::XMLNode::guessUTF8ParsingParameterValue(), and myIsTextUnicode().
 { return t1 < t2 ? t1 : t2; }
char VarTypes::myIsTextUnicode (const void * b, int len)
Definition at line 177 of file xmlParser.cpp.
References _strnicmp(), VarTypes::XMLNode::d, FALSE, velocity.pid_::i, mmin(), myWideCharToMultiByte(), TRUE, and XMLCHAR.
Referenced by VarTypes::XMLNode::guessUTF8ParsingParameterValue(), and VarTypes::XMLNode::parseFile().
 { (void)b; (void)len; return FALSE; }
static void* VarTypes::myRealloc (void * p, int newsize, int memInc, int sizeofElem) inline static
Definition at line 952 of file xmlParser.cpp.
Referenced by VarTypes::XMLNode::addAttribute_priv(), and VarTypes::XMLNode::addToOrder().
   {
       if (p==NULL) { if (memInc) return malloc(memInc*sizeofElem); return malloc(sizeofElem); }
       if ((memInc==0)||((newsize%memInc)==0)) p=realloc(p,(newsize+memInc)*sizeofElem);
   //    if (!p)
   //    {
   //        printf("XMLParser Error: Not enough memory! Aborting...\n"); exit(220);
   //    }
       return p;
   }
char VarTypes::myTagCompare (const char * cclose, const char * copen)
Definition at line 719 of file xmlParser.cpp.
References _T, _tcslen(), _tcsnicmp(), XML_isSPACECHAR, and XMLCHAR.
Referenced by VarTypes::XMLNode::ParseXMLElement().
   {
       if (!cclose) return 1;
       int l=(int)_tcslen(cclose);
       if (_tcsnicmp(cclose, copen, l)!=0) return 1;
       const XMLCHAR c=copen[l];
       if (XML_isSPACECHAR(c)||
           (c==_T('/' ))||
           (c==_T('<' ))||
           (c==_T('>' ))||
           (c==_T('=' ))) return 0;
       return 1;
   }
char* VarTypes::myWideCharToMultiByte (const wchar_t * s, int l)
Definition at line 265 of file xmlParser.cpp.
References _strnicmp(), _T, _tcscpy(), _tcsicmp(), _tcslen(), _tcsnicmp(), _tcsstr(), _tfopen(), VarTypes::XMLNode::d, velocity.pid_::i, XMLCSTR, and XMLSTR.
Referenced by myIsTextUnicode(), and VarTypes::XMLNode::parseFile().
 { (void)s; (void)l; return NULL; }
char * VarTypes::stringDup (const char * lpszData, int cbData)
Definition at line 462 of file xmlParser.cpp.
References _tcslen(), VarTypes::XMLNode::emptyXMLAttribute, VarTypes::XMLNode::emptyXMLClear, VarTypes::XMLNode::emptyXMLNode, XMLCHAR, and XMLSTR.
Referenced by VarTypes::XMLNode::addAttribute(), VarTypes::XMLNode::addChild(), VarTypes::XMLNode::addClear(), VarTypes::XMLNode::addText(), VarTypes::XMLNode::createXMLTopNode(), VarTypes::XMLNode::parseClearTag(), VarTypes::XMLNode::ParseXMLElement(), VarTypes::XMLNode::updateAttribute(), VarTypes::XMLNode::updateAttribute_WOSD(), VarTypes::XMLNode::updateClear(), VarTypes::XMLNode::updateName(), and VarTypes::XMLNode::updateText().
   {
       if (lpszData==NULL) return NULL;
       XMLSTR lpszNew;
       if (cbData==0) cbData=(int)_tcslen(lpszData);
       lpszNew = (XMLSTR)malloc((cbData+1) * sizeof(XMLCHAR));
       if (lpszNew)
       {
           memcpy(lpszNew, lpszData, (cbData) * sizeof(XMLCHAR));
           lpszNew[cbData] = (XMLCHAR)NULL;
       }
       return lpszNew;
   }
char * VarTypes::toXMLString (char * dest, const char * source)
Definition at line 533 of file xmlParser.cpp.
References _tcscpy(), VarTypes::XMLCharacterEntity::c, VarTypes::XMLCharacterEntity::l, VarTypes::XMLCharacterEntity::s, XMLCHAR, XMLEntities, and XMLSTR.
Referenced by VarTypes::XMLNode::CreateXMLStringR(), toXMLString(), and toXMLStringFast().
   {
       XMLSTR dd=dest;
       XMLCHAR ch;
       XMLCharacterEntity *entity;
       while ((ch=*source))
       {
           entity=XMLEntities;
           do
           {
               if (ch==entity->c) {_tcscpy(dest,entity->s); dest+=entity->l; source++; goto out_of_loop1; }
               entity++;
           } while(entity->s);
   #ifdef _XMLUNICODE
           *(dest++)=*(source++);
   #else
           switch(XML_ByteTable[(unsigned char)ch])
           {
           case 4: *(dest++)=*(source++);
           case 3: *(dest++)=*(source++);
           case 2: *(dest++)=*(source++);
           case 1: *(dest++)=*(source++);
           }
   #endif
   out_of_loop1:
           ;
       }
       *dest=0;
       return dd;
   }
char * VarTypes::toXMLString (const char * source)
Definition at line 589 of file xmlParser.cpp.
References lengthXMLString(), toXMLString(), XMLCHAR, and XMLSTR.
   {
       XMLSTR dest=(XMLSTR)malloc((lengthXMLString(source)+1)*sizeof(XMLCHAR));
       return toXMLString(dest,source);
   }
char * VarTypes::toXMLStringFast (char ** dest, int * destSz, const char * source)
Definition at line 595 of file xmlParser.cpp.
References lengthXMLString(), toXMLString(), XMLCHAR, and XMLSTR.
   {
       int l=lengthXMLString(source)+1;
       if (l>*destSz) { *destSz=l; *dest=(XMLSTR)realloc(*dest,l*sizeof(XMLCHAR)); }
       return toXMLString(*dest,source);
   }
Variable Documentation
const unsigned char VarTypes::base64DecodeTable[]
Initial value:
= {
      99,98,98,98,98,98,98,98,98,97,  97,98,98,97,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
      98,98,97,98,98,98,98,98,98,98,  98,98,98,62,98,98,98,63,52,53,  54,55,56,57,58,59,60,61,98,98,
      98,96,98,98,98, 0, 1, 2, 3, 4,   5, 6, 7, 8, 9,10,11,12,13,14,  15,16,17,18,19,20,21,22,23,24,
      25,98,98,98,98,98,98,26,27,28,  29,30,31,32,33,34,35,36,37,38,  39,40,41,42,43,44,45,46,47,48,
      49,50,51,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
      98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
      98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
      98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
      98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98
  }
Definition at line 2455 of file xmlParser.cpp.
const char* VarTypes::base64EncodeTable = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
Definition at line 2451 of file xmlParser.cpp.
const char VarTypes::base64Fillchar = '=' static
Definition at line 2448 of file xmlParser.cpp.
char VarTypes::dropWhiteSpace =1 static
Definition at line 99 of file xmlParser.cpp.
Referenced by VarTypes::XMLNode::createXMLString(), VarTypes::XMLNode::maybeAddTxT(), VarTypes::XMLNode::openFileHelper(), and VarTypes::XMLNode::setGlobalOptions().
char VarTypes::guessUnicodeChars =1 static
Definition at line 99 of file xmlParser.cpp.
Referenced by VarTypes::XMLNode::openFileHelper(), VarTypes::XMLNode::parseFile(), and VarTypes::XMLNode::setGlobalOptions().
char VarTypes::strictUTF8Parsing =1 static
Definition at line 99 of file xmlParser.cpp.
const char VarTypes::XML_asciiByteTable[256] static
Initial value:
=
  {
      0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
  }
Definition at line 409 of file xmlParser.cpp.
Referenced by VarTypes::XMLNode::setGlobalOptions().
const char* VarTypes::XML_ByteTable =(const char *)XML_utf8ByteTable static
Definition at line 418 of file xmlParser.cpp.
const char VarTypes::XML_utf8ByteTable[256] static
Initial value:
=
  {
      0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
      2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
      3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
      4,4,4,4,4,1,1,1,1,1,1,1,1,1,1,1
  }
Definition at line 389 of file xmlParser.cpp.
Referenced by VarTypes::XMLNode::setGlobalOptions().
ALLXMLClearTag VarTypes::XMLClearTags[] static
Initial value:
=
  {
      {     "<![CDATA[" ,9,   "]]>"       },
      {     "<!DOCTYPE" ,9,   ">"         },
      {     "<PRE>"     ,5,   "</PRE>"    },
      {     "<Script>"  ,8,   "</Script>" },
      {     "<!--"      ,4,   "-->"       },
      {    NULL           ,0,  NULL           }
  }
Definition at line 107 of file xmlParser.cpp.
Referenced by VarTypes::XMLNode::getClearTagTable(), and GetNextToken().
XMLCharacterEntity VarTypes::XMLEntities[] static
Initial value:
=
  {
      {  "&amp;" , 5,  '&' },
      {  "&lt;" , 4,  '<' },
      {  "&gt;" , 4,  '>' },
      {  "&quot;" , 6,  '\"' },
      {  "&apos;" , 6,  '\'' },
      { NULL        , 0, '\0'    }
  }
Definition at line 123 of file xmlParser.cpp.
Referenced by fromXMLString(), lengthXMLString(), and toXMLString().