Documentation: RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize Class Reference
RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize Class Reference
#include <messages_robocup_ssl_geometry_legacy.pb.h>
Public Member Functions
SSL_GeometryFieldSize ()
virtual ~SSL_GeometryFieldSize ()
SSL_GeometryFieldSize (const SSL_GeometryFieldSize &from)
SSL_GeometryFieldSize & operator= (const SSL_GeometryFieldSize &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_GeometryFieldSize *other)
SSL_GeometryFieldSize * New () const PROTOBUF_FINAL
SSL_GeometryFieldSize * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_GeometryFieldSize &from)
void MergeFrom (const SSL_GeometryFieldSize &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_line_width () const
void clear_line_width ()
::google::protobuf::int32 line_width () const
void set_line_width (::google::protobuf::int32 value)
bool has_field_length () const
void clear_field_length ()
::google::protobuf::int32 field_length () const
void set_field_length (::google::protobuf::int32 value)
bool has_field_width () const
void clear_field_width ()
::google::protobuf::int32 field_width () const
void set_field_width (::google::protobuf::int32 value)
bool has_boundary_width () const
void clear_boundary_width ()
::google::protobuf::int32 boundary_width () const
void set_boundary_width (::google::protobuf::int32 value)
bool has_referee_width () const
void clear_referee_width ()
::google::protobuf::int32 referee_width () const
void set_referee_width (::google::protobuf::int32 value)
bool has_goal_width () const
void clear_goal_width ()
::google::protobuf::int32 goal_width () const
void set_goal_width (::google::protobuf::int32 value)
bool has_goal_depth () const
void clear_goal_depth ()
::google::protobuf::int32 goal_depth () const
void set_goal_depth (::google::protobuf::int32 value)
bool has_goal_wall_width () const
void clear_goal_wall_width ()
::google::protobuf::int32 goal_wall_width () const
void set_goal_wall_width (::google::protobuf::int32 value)
bool has_center_circle_radius () const
void clear_center_circle_radius ()
::google::protobuf::int32 center_circle_radius () const
void set_center_circle_radius (::google::protobuf::int32 value)
bool has_defense_radius () const
void clear_defense_radius ()
::google::protobuf::int32 defense_radius () const
void set_defense_radius (::google::protobuf::int32 value)
bool has_defense_stretch () const
void clear_defense_stretch ()
::google::protobuf::int32 defense_stretch () const
void set_defense_stretch (::google::protobuf::int32 value)
bool has_free_kick_from_defense_dist () const
void clear_free_kick_from_defense_dist ()
::google::protobuf::int32 free_kick_from_defense_dist () const
void set_free_kick_from_defense_dist (::google::protobuf::int32 value)
bool has_penalty_spot_from_field_line_dist () const
void clear_penalty_spot_from_field_line_dist ()
::google::protobuf::int32 penalty_spot_from_field_line_dist () const
void set_penalty_spot_from_field_line_dist (::google::protobuf::int32 value)
bool has_penalty_line_from_spot_dist () const
void clear_penalty_line_from_spot_dist ()
::google::protobuf::int32 penalty_line_from_spot_dist () const
void set_penalty_line_from_spot_dist (::google::protobuf::int32 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_GeometryFieldSize & default_instance ()
static void InitAsDefaultInstance ()
static const SSL_GeometryFieldSize * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kLineWidthFieldNumber = 1
static const int kFieldLengthFieldNumber = 2
static const int kFieldWidthFieldNumber = 3
static const int kBoundaryWidthFieldNumber = 4
static const int kRefereeWidthFieldNumber = 5
static const int kGoalWidthFieldNumber = 6
static const int kGoalDepthFieldNumber = 7
static const int kGoalWallWidthFieldNumber = 8
static const int kCenterCircleRadiusFieldNumber = 9
static const int kDefenseRadiusFieldNumber = 10
static const int kDefenseStretchFieldNumber = 11
static const int kFreeKickFromDefenseDistFieldNumber = 12
static const int kPenaltySpotFromFieldLineDistFieldNumber = 13
static const int kPenaltyLineFromSpotDistFieldNumber = 14
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_GeometryFieldSize *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_line_width ()
void clear_has_line_width ()
void set_has_field_length ()
void clear_has_field_length ()
void set_has_field_width ()
void clear_has_field_width ()
void set_has_boundary_width ()
void clear_has_boundary_width ()
void set_has_referee_width ()
void clear_has_referee_width ()
void set_has_goal_width ()
void clear_has_goal_width ()
void set_has_goal_depth ()
void clear_has_goal_depth ()
void set_has_goal_wall_width ()
void clear_has_goal_wall_width ()
void set_has_center_circle_radius ()
void clear_has_center_circle_radius ()
void set_has_defense_radius ()
void clear_has_defense_radius ()
void set_has_defense_stretch ()
void clear_has_defense_stretch ()
void set_has_free_kick_from_defense_dist ()
void clear_has_free_kick_from_defense_dist ()
void set_has_penalty_spot_from_field_line_dist ()
void clear_has_penalty_spot_from_field_line_dist ()
void set_has_penalty_line_from_spot_dist ()
void clear_has_penalty_line_from_spot_dist ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto::InitDefaultsSSL_GeometryFieldSizeImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::int32 line_width_
::google::protobuf::int32 field_length_
::google::protobuf::int32 field_width_
::google::protobuf::int32 boundary_width_
::google::protobuf::int32 referee_width_
::google::protobuf::int32 goal_width_
::google::protobuf::int32 goal_depth_
::google::protobuf::int32 goal_wall_width_
::google::protobuf::int32 center_circle_radius_
::google::protobuf::int32 defense_radius_
::google::protobuf::int32 defense_stretch_
::google::protobuf::int32 free_kick_from_defense_dist_
::google::protobuf::int32 penalty_spot_from_field_line_dist_
::google::protobuf::int32 penalty_line_from_spot_dist_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto::TableStruct
void swap (SSL_GeometryFieldSize &a, SSL_GeometryFieldSize &b)
Detailed Description
Definition at line 70 of file messages_robocup_ssl_geometry_legacy.pb.h.
Constructor & Destructor Documentation
RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::SSL_GeometryFieldSize ()
virtual RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::~SSL_GeometryFieldSize () virtual
RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::SSL_GeometryFieldSize (const SSL_GeometryFieldSize & from)
Member Function Documentation
google::protobuf::int32 SSL_GeometryFieldSize::boundary_width () const inline
Definition at line 533 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.boundary_width)
   return boundary_width_;
 }
size_t RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::ByteSizeLong () const
google::protobuf::int32 SSL_GeometryFieldSize::center_circle_radius () const inline
Definition at line 653 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.center_circle_radius)
   return center_circle_radius_;
 }
void RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::Clear ()
void SSL_GeometryFieldSize::clear_boundary_width () inline
Definition at line 529 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   boundary_width_ = 0;
   clear_has_boundary_width();
 }
void SSL_GeometryFieldSize::clear_center_circle_radius () inline
Definition at line 649 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   center_circle_radius_ = 0;
   clear_has_center_circle_radius();
 }
void SSL_GeometryFieldSize::clear_defense_radius () inline
Definition at line 673 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   defense_radius_ = 0;
   clear_has_defense_radius();
 }
void SSL_GeometryFieldSize::clear_defense_stretch () inline
Definition at line 697 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   defense_stretch_ = 0;
   clear_has_defense_stretch();
 }
void SSL_GeometryFieldSize::clear_field_length () inline
Definition at line 481 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   field_length_ = 0;
   clear_has_field_length();
 }
void SSL_GeometryFieldSize::clear_field_width () inline
Definition at line 505 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   field_width_ = 0;
   clear_has_field_width();
 }
void SSL_GeometryFieldSize::clear_free_kick_from_defense_dist () inline
Definition at line 721 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   free_kick_from_defense_dist_ = 0;
   clear_has_free_kick_from_defense_dist();
 }
void SSL_GeometryFieldSize::clear_goal_depth () inline
Definition at line 601 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   goal_depth_ = 0;
   clear_has_goal_depth();
 }
void SSL_GeometryFieldSize::clear_goal_wall_width () inline
Definition at line 625 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   goal_wall_width_ = 0;
   clear_has_goal_wall_width();
 }
void SSL_GeometryFieldSize::clear_goal_width () inline
Definition at line 577 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   goal_width_ = 0;
   clear_has_goal_width();
 }
void SSL_GeometryFieldSize::clear_has_boundary_width () inline private
Definition at line 526 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000008u;
 }
void SSL_GeometryFieldSize::clear_has_center_circle_radius () inline private
Definition at line 646 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000100u;
 }
void SSL_GeometryFieldSize::clear_has_defense_radius () inline private
Definition at line 670 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000200u;
 }
void SSL_GeometryFieldSize::clear_has_defense_stretch () inline private
Definition at line 694 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000400u;
 }
void SSL_GeometryFieldSize::clear_has_field_length () inline private
Definition at line 478 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000002u;
 }
void SSL_GeometryFieldSize::clear_has_field_width () inline private
Definition at line 502 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000004u;
 }
void SSL_GeometryFieldSize::clear_has_free_kick_from_defense_dist () inline private
Definition at line 718 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000800u;
 }
void SSL_GeometryFieldSize::clear_has_goal_depth () inline private
Definition at line 598 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000040u;
 }
void SSL_GeometryFieldSize::clear_has_goal_wall_width () inline private
Definition at line 622 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000080u;
 }
void SSL_GeometryFieldSize::clear_has_goal_width () inline private
Definition at line 574 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000020u;
 }
void SSL_GeometryFieldSize::clear_has_line_width () inline private
Definition at line 454 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void SSL_GeometryFieldSize::clear_has_penalty_line_from_spot_dist () inline private
Definition at line 766 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00002000u;
 }
void SSL_GeometryFieldSize::clear_has_penalty_spot_from_field_line_dist () inline private
Definition at line 742 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00001000u;
 }
void SSL_GeometryFieldSize::clear_has_referee_width () inline private
Definition at line 550 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000010u;
 }
void SSL_GeometryFieldSize::clear_line_width () inline
Definition at line 457 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   line_width_ = 0;
   clear_has_line_width();
 }
void SSL_GeometryFieldSize::clear_penalty_line_from_spot_dist () inline
Definition at line 769 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   penalty_line_from_spot_dist_ = 0;
   clear_has_penalty_line_from_spot_dist();
 }
void SSL_GeometryFieldSize::clear_penalty_spot_from_field_line_dist () inline
Definition at line 745 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   penalty_spot_from_field_line_dist_ = 0;
   clear_has_penalty_spot_from_field_line_dist();
 }
void SSL_GeometryFieldSize::clear_referee_width () inline
Definition at line 553 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   referee_width_ = 0;
   clear_has_referee_width();
 }
void RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::CopyFrom (const ::google::protobuf::Message & from)
void RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::CopyFrom (const SSL_GeometryFieldSize & from)
static const SSL_GeometryFieldSize& RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::default_instance () static
google::protobuf::int32 SSL_GeometryFieldSize::defense_radius () const inline
Definition at line 677 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.defense_radius)
   return defense_radius_;
 }
google::protobuf::int32 SSL_GeometryFieldSize::defense_stretch () const inline
Definition at line 701 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.defense_stretch)
   return defense_stretch_;
 }
static const ::google::protobuf::Descriptor* RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::descriptor () static
google::protobuf::int32 SSL_GeometryFieldSize::field_length () const inline
Definition at line 485 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.field_length)
   return field_length_;
 }
google::protobuf::int32 SSL_GeometryFieldSize::field_width () const inline
Definition at line 509 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.field_width)
   return field_width_;
 }
google::protobuf::int32 SSL_GeometryFieldSize::free_kick_from_defense_dist () const inline
Definition at line 725 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.free_kick_from_defense_dist)
   return free_kick_from_defense_dist_;
 }
inline ::google::protobuf::Arena* RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::GetArenaNoVirtual () const inline private
Definition at line 145 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by operator=().
{
     return NULL;
   }
int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::GetCachedSize () const inline
Definition at line 138 of file messages_robocup_ssl_geometry_legacy.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::GetMetadata () const
google::protobuf::int32 SSL_GeometryFieldSize::goal_depth () const inline
Definition at line 605 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.goal_depth)
   return goal_depth_;
 }
google::protobuf::int32 SSL_GeometryFieldSize::goal_wall_width () const inline
Definition at line 629 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.goal_wall_width)
   return goal_wall_width_;
 }
google::protobuf::int32 SSL_GeometryFieldSize::goal_width () const inline
Definition at line 581 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.goal_width)
   return goal_width_;
 }
bool SSL_GeometryFieldSize::has_boundary_width () const inline
Definition at line 520 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool SSL_GeometryFieldSize::has_center_circle_radius () const inline
Definition at line 640 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000100u) != 0;
 }
bool SSL_GeometryFieldSize::has_defense_radius () const inline
Definition at line 664 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000200u) != 0;
 }
bool SSL_GeometryFieldSize::has_defense_stretch () const inline
Definition at line 688 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000400u) != 0;
 }
bool SSL_GeometryFieldSize::has_field_length () const inline
Definition at line 472 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool SSL_GeometryFieldSize::has_field_width () const inline
Definition at line 496 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool SSL_GeometryFieldSize::has_free_kick_from_defense_dist () const inline
Definition at line 712 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000800u) != 0;
 }
bool SSL_GeometryFieldSize::has_goal_depth () const inline
Definition at line 592 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000040u) != 0;
 }
bool SSL_GeometryFieldSize::has_goal_wall_width () const inline
Definition at line 616 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000080u) != 0;
 }
bool SSL_GeometryFieldSize::has_goal_width () const inline
Definition at line 568 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000020u) != 0;
 }
bool SSL_GeometryFieldSize::has_line_width () const inline
Definition at line 448 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool SSL_GeometryFieldSize::has_penalty_line_from_spot_dist () const inline
Definition at line 760 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00002000u) != 0;
 }
bool SSL_GeometryFieldSize::has_penalty_spot_from_field_line_dist () const inline
Definition at line 736 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00001000u) != 0;
 }
bool SSL_GeometryFieldSize::has_referee_width () const inline
Definition at line 544 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
static void RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::InitAsDefaultInstance () static
static const SSL_GeometryFieldSize* RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::internal_default_instance () inline static
Definition at line 107 of file messages_robocup_ssl_geometry_legacy.pb.h.
References RoboCup2014Legacy::Geometry::_SSL_GeometryFieldSize_default_instance_.
{
     return reinterpret_cast<const SSL_GeometryFieldSize*>(
                &_SSL_GeometryFieldSize_default_instance_);
   }
::google::protobuf::uint8* RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::InternalSwap (SSL_GeometryFieldSize * other) private
bool RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::IsInitialized () const
google::protobuf::int32 SSL_GeometryFieldSize::line_width () const inline
Definition at line 461 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.line_width)
   return line_width_;
 }
void* RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::MaybeArenaPtr () const inline private
Definition at line 148 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
     return NULL;
   }
void RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::MergeFrom (const ::google::protobuf::Message & from)
void RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::MergeFrom (const SSL_GeometryFieldSize & from)
bool RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
inline ::google::protobuf::UnknownFieldSet* RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::mutable_unknown_fields () inline
Definition at line 99 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
SSL_GeometryFieldSize* RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::New () const inline
Definition at line 121 of file messages_robocup_ssl_geometry_legacy.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_GeometryFieldSize* RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::New (::google::protobuf::Arena * arena) const
SSL_GeometryFieldSize& RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::operator= (const SSL_GeometryFieldSize & from) inline
Definition at line 77 of file messages_robocup_ssl_geometry_legacy.pb.h.
References GetArenaNoVirtual().
{
     CopyFrom(from);
     return *this;
   }
google::protobuf::int32 SSL_GeometryFieldSize::penalty_line_from_spot_dist () const inline
Definition at line 773 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.penalty_line_from_spot_dist)
   return penalty_line_from_spot_dist_;
 }
google::protobuf::int32 SSL_GeometryFieldSize::penalty_spot_from_field_line_dist () const inline
Definition at line 749 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.penalty_spot_from_field_line_dist)
   return penalty_spot_from_field_line_dist_;
 }
google::protobuf::int32 SSL_GeometryFieldSize::referee_width () const inline
Definition at line 557 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.referee_width)
   return referee_width_;
 }
size_t RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::RequiredFieldsByteSizeFallback () const private
void RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void SSL_GeometryFieldSize::set_boundary_width (::google::protobuf::int32 value) inline
Definition at line 537 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_boundary_width();
   boundary_width_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.boundary_width)
 }
void SSL_GeometryFieldSize::set_center_circle_radius (::google::protobuf::int32 value) inline
Definition at line 657 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_center_circle_radius();
   center_circle_radius_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.center_circle_radius)
 }
void SSL_GeometryFieldSize::set_defense_radius (::google::protobuf::int32 value) inline
Definition at line 681 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_defense_radius();
   defense_radius_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.defense_radius)
 }
void SSL_GeometryFieldSize::set_defense_stretch (::google::protobuf::int32 value) inline
Definition at line 705 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_defense_stretch();
   defense_stretch_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.defense_stretch)
 }
void SSL_GeometryFieldSize::set_field_length (::google::protobuf::int32 value) inline
Definition at line 489 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_field_length();
   field_length_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.field_length)
 }
void SSL_GeometryFieldSize::set_field_width (::google::protobuf::int32 value) inline
Definition at line 513 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_field_width();
   field_width_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.field_width)
 }
void SSL_GeometryFieldSize::set_free_kick_from_defense_dist (::google::protobuf::int32 value) inline
Definition at line 729 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_free_kick_from_defense_dist();
   free_kick_from_defense_dist_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.free_kick_from_defense_dist)
 }
void SSL_GeometryFieldSize::set_goal_depth (::google::protobuf::int32 value) inline
Definition at line 609 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_goal_depth();
   goal_depth_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.goal_depth)
 }
void SSL_GeometryFieldSize::set_goal_wall_width (::google::protobuf::int32 value) inline
Definition at line 633 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_goal_wall_width();
   goal_wall_width_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.goal_wall_width)
 }
void SSL_GeometryFieldSize::set_goal_width (::google::protobuf::int32 value) inline
Definition at line 585 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_goal_width();
   goal_width_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.goal_width)
 }
void SSL_GeometryFieldSize::set_has_boundary_width () inline private
Definition at line 523 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000008u;
 }
void SSL_GeometryFieldSize::set_has_center_circle_radius () inline private
Definition at line 643 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000100u;
 }
void SSL_GeometryFieldSize::set_has_defense_radius () inline private
Definition at line 667 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000200u;
 }
void SSL_GeometryFieldSize::set_has_defense_stretch () inline private
Definition at line 691 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000400u;
 }
void SSL_GeometryFieldSize::set_has_field_length () inline private
Definition at line 475 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000002u;
 }
void SSL_GeometryFieldSize::set_has_field_width () inline private
Definition at line 499 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000004u;
 }
void SSL_GeometryFieldSize::set_has_free_kick_from_defense_dist () inline private
Definition at line 715 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000800u;
 }
void SSL_GeometryFieldSize::set_has_goal_depth () inline private
Definition at line 595 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000040u;
 }
void SSL_GeometryFieldSize::set_has_goal_wall_width () inline private
Definition at line 619 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000080u;
 }
void SSL_GeometryFieldSize::set_has_goal_width () inline private
Definition at line 571 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000020u;
 }
void SSL_GeometryFieldSize::set_has_line_width () inline private
Definition at line 451 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000001u;
 }
void SSL_GeometryFieldSize::set_has_penalty_line_from_spot_dist () inline private
Definition at line 763 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00002000u;
 }
void SSL_GeometryFieldSize::set_has_penalty_spot_from_field_line_dist () inline private
Definition at line 739 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00001000u;
 }
void SSL_GeometryFieldSize::set_has_referee_width () inline private
Definition at line 547 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000010u;
 }
void SSL_GeometryFieldSize::set_line_width (::google::protobuf::int32 value) inline
Definition at line 465 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_line_width();
   line_width_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.line_width)
 }
void SSL_GeometryFieldSize::set_penalty_line_from_spot_dist (::google::protobuf::int32 value) inline
Definition at line 777 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_penalty_line_from_spot_dist();
   penalty_line_from_spot_dist_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.penalty_line_from_spot_dist)
 }
void SSL_GeometryFieldSize::set_penalty_spot_from_field_line_dist (::google::protobuf::int32 value) inline
Definition at line 753 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_penalty_spot_from_field_line_dist();
   penalty_spot_from_field_line_dist_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.penalty_spot_from_field_line_dist)
 }
void SSL_GeometryFieldSize::set_referee_width (::google::protobuf::int32 value) inline
Definition at line 561 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_referee_width();
   referee_width_ = value;
   // @@protoc_insertion_point(field_set:RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.referee_width)
 }
void RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::SetCachedSize (int size) const private
void RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::SharedCtor () private
void RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::SharedDtor () private
void RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::Swap (SSL_GeometryFieldSize * other)
const ::google::protobuf::UnknownFieldSet& RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::unknown_fields () const inline
Definition at line 96 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::void::protobuf_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto::InitDefaultsSSL_GeometryFieldSizeImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto::TableStruct friend
Definition at line 308 of file messages_robocup_ssl_geometry_legacy.pb.h.
void swap (SSL_GeometryFieldSize & a, SSL_GeometryFieldSize & b) friend
Definition at line 115 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::_cached_size_ mutable private
Definition at line 293 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::internal::HasBits<1> RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::_has_bits_ private
Definition at line 292 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::internal::InternalMetadataWithArena RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::_internal_metadata_ private
Definition at line 291 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::boundary_width_ private
Definition at line 297 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::center_circle_radius_ private
Definition at line 302 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::defense_radius_ private
Definition at line 303 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::defense_stretch_ private
Definition at line 304 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::field_length_ private
Definition at line 295 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::field_width_ private
Definition at line 296 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::free_kick_from_defense_dist_ private
Definition at line 305 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::goal_depth_ private
Definition at line 300 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::goal_wall_width_ private
Definition at line 301 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::goal_width_ private
Definition at line 299 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kBoundaryWidthFieldNumber = 4 static
Definition at line 183 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kCenterCircleRadiusFieldNumber = 9 static
Definition at line 218 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kDefenseRadiusFieldNumber = 10 static
Definition at line 225 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kDefenseStretchFieldNumber = 11 static
Definition at line 232 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kFieldLengthFieldNumber = 2 static
Definition at line 169 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kFieldWidthFieldNumber = 3 static
Definition at line 176 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kFreeKickFromDefenseDistFieldNumber = 12 static
Definition at line 239 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kGoalDepthFieldNumber = 7 static
Definition at line 204 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kGoalWallWidthFieldNumber = 8 static
Definition at line 211 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kGoalWidthFieldNumber = 6 static
Definition at line 197 of file messages_robocup_ssl_geometry_legacy.pb.h.
PROTOBUF_CONSTEXPR int const RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kIndexInFileMessages static
Initial value:
=
    0
Definition at line 111 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kLineWidthFieldNumber = 1 static
Definition at line 162 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kPenaltyLineFromSpotDistFieldNumber = 14 static
Definition at line 253 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kPenaltySpotFromFieldLineDistFieldNumber = 13 static
Definition at line 246 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::kRefereeWidthFieldNumber = 5 static
Definition at line 190 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::line_width_ private
Definition at line 294 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::penalty_line_from_spot_dist_ private
Definition at line 307 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::penalty_spot_from_field_line_dist_ private
Definition at line 306 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::int32 RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize::referee_width_ private
Definition at line 298 of file messages_robocup_ssl_geometry_legacy.pb.h.
The documentation for this class was generated from the following file:
ssl-vision/build/messages_robocup_ssl_geometry_legacy.pb.h