Documentation: Image< PIXEL > Class Template Reference
Image< PIXEL > Class Template Reference
A template-based 2D raster-image class.
#include <image.h>
Public Member Functions
void fromRawImage (const RawImage &img)
void copyToRawImage (RawImage &img)
void fromImage (const Image< PIXEL > &img)
void allocate (int w, int h)
void clear ()
Image (const RawImage &ri)
Image ()
Image (int w, int h)
~Image ()
ColorFormat getColorFormat () const
int getWidth () const
int getHeight () const
int getNumPixels () const
int getNumBytes () const
void fillBlack ()
void fillColor (const PIXEL &color)
PIXEL * getPixelData () const
unsigned char * getData () const
PIXEL getPixel (int number) const
PIXEL getPixel (int x, int y) const
PIXEL * getPixelPointer (int x, int y) const
void setPixel (int x, int y, PIXEL val)
void drawLine (int x0, int y0, int x1, int y1, PIXEL val)
void drawFatLine (int x0, int y0, int x1, int y1, PIXEL val)
void drawBox (int x, int y, int width, int height, PIXEL val)
void drawFatBox (int x, int y, int width, int height, PIXEL val)
bool load (string filename)
bool save (string filename)
void copy (const Image &source, bool allow_external=false)
void copyFromRectArea (const Image &source, int x, int y, int w, int h, bool allow_external=false)
void subtract (const Image &source)
void convertToIntensity ()
void binarizeGreyImage (unsigned int threshold)
void binarizeChanneledImage (unsigned int threshold_r, unsigned int threshold_g, unsigned int threshold_b)
void drawChar (int x, int y, char c, PIXEL val)
void drawString (int x, int y, std::string s, PIXEL val)
Public Member Functions inherited from ImageInterface
virtual ~ImageInterface ()
Data Fields
bool _external
int width
int height
PIXEL * data
Detailed Description
template<class PIXEL>
class Image< PIXEL >
A template-based 2D raster-image class.
Definition at line 43 of file image.h.
Constructor & Destructor Documentation
template<class PIXEL> Image< PIXEL >::Image (const RawImage< PIXEL > & ri) inline
Definition at line 109 of file image.h.
{
     data=0;
     _external=false;
     allocate(0,0);
     fromRawImage(ri);
   }
template<class PIXEL> Image< PIXEL >::Image () inline
Definition at line 116 of file image.h.
   {
     data=0;
     _external=false;
     allocate(0,0);
   }
template<class PIXEL> Image< PIXEL >::Image (int w, int h) inline
Definition at line 123 of file image.h.
   {
     data=0;
     _external=false;
     allocate(w,h);
   }
template<class PIXEL> Image< PIXEL >::~Image () inline
Definition at line 130 of file image.h.
   {
     if (data!=0 && _external==false) {
       delete[] data;
     }
   }
Member Function Documentation
template<class PIXEL> void Image< PIXEL >::allocate (int w, int h) inline
Definition at line 88 of file image.h.
Referenced by Image< rgb >::clear(), Image< rgb >::copy(), Image< rgb >::copyFromRectArea(), Image< rgb >::Image(), and PluginColorThreshold::process().
   {
     //if (width==w && height==h && _external==false && data!=0) return;
     assert(w >= 0 && h >= 0);
     if (data!=0 && _external==false) {
       if (width==w && height==h) return;
       delete[] data;
     }
     if (w==0 && h==0) {
       data=0;
     } else {
       data=new PIXEL[w*h];
     }
     _external=false;
     width=w;
     height=h;
   }
template<class PIXEL> void Image< PIXEL >::binarizeChanneledImage (unsigned int threshold_r, unsigned int threshold_g, unsigned int threshold_b) inline
Definition at line 441 of file image.h.
{
       register PIXEL * a=getPixelData();
       register unsigned int i;
       register unsigned int pixelCount=getNumPixels();
       for (i=0;i<pixelCount;i++) {
         if (a->r > threshold_r) {a->r = 255; } else {a->r=0; };
         if (a->g > threshold_g) {a->g = 255; } else {a->g=0; };
         if (a->b > threshold_b) {a->b = 255; } else {a->b=0; };
         a++;
       }
   }
template<class PIXEL> void Image< PIXEL >::binarizeGreyImage (unsigned int threshold) inline
Definition at line 429 of file image.h.
{
       register PIXEL * a=getPixelData();
       register unsigned int i;
       register unsigned int pixelCount=getNumPixels();
       for (i=0;i<pixelCount;i++) {
         if (a->r > threshold) {a->r = 255; } else {a->r=0; };
         a->g=a->b=a->r;
         a++;
       }
   }
template<class PIXEL> void Image< PIXEL >::clear () inline
Definition at line 105 of file image.h.
Referenced by Image< rgb >::fromImage(), Image< rgb >::fromRawImage(), and Image< rgb >::load().
                {
     allocate(0,0);
   };
template<class PIXEL> void Image< PIXEL >::convertToIntensity () inline
Definition at line 419 of file image.h.
{
       register PIXEL * a=getPixelData();
       register unsigned int i;
       register unsigned int pixelCount=getNumPixels();
       for (i=0;i<pixelCount;i++) {
         a->r = a->g = a->b = a->getIntensity();
         a++;
       }
   }
template<class PIXEL> void Image< PIXEL >::copy (const Image< PIXEL > & source, bool allow_external = false) inline
Definition at line 374 of file image.h.
{
     if (!(allow_external && source.getWidth()==getWidth() && source.getHeight() == getHeight())) {
       allocate(source.getWidth(),source.getHeight());
     }
     memcpy(data,source.getData(),source.getNumBytes());
   }
template<class PIXEL> void Image< PIXEL >::copyFromRectArea (const Image< PIXEL > & source, int x, int y, int w, int h, bool allow_external = false) inline
Definition at line 381 of file image.h.
{
     if (x < 0) x=0;
     if (y < 0) y=0;
     if (w < 0) w=0;
     if (h < 0) h=0;
     if ((x+w) >= source.getWidth()) w = source.getWidth() - x;
     if ((y+h) >= source.getHeight()) h = source.getHeight() - y;
     if (w<=0 || h <=0) w=h=0;
     if (!(allow_external && w==getWidth() && h == getHeight())) {
       allocate(w,h);
     }
     if (w==0||h==0) return;
     //TODO: add rect copy from source:
     int my=y+h;
     PIXEL * src_ptr = source.getPixelPointer(x,y);
     PIXEL * tgt_ptr = getPixelData();
     for (int i = y ; i < my; i++) {
       memcpy(tgt_ptr, src_ptr ,sizeof(PIXEL) * w);
       src_ptr+=source.getWidth();
       tgt_ptr+=w;
     }
   }
template<class PIXEL> void Image< PIXEL >::copyToRawImage (RawImage< PIXEL > & img) inline
Definition at line 66 of file image.h.
{
     if (PIXEL::getColorFormat() == img.getColorFormat() && img.getNumBytes() == getNumBytes()) {
       memcpy(img.getData(),getData(),getNumBytes());
       img.setWidth( getWidth());
       img.setHeight( getHeight());
     } else {
       fprintf(stderr,"cannot copy image to rawimage. colortypes and/or size do not match\n");
     }
   }
template<class PIXEL> void Image< PIXEL >::drawBox (int x, int y, int width, int height, PIXEL val) inline
Definition at line 322 of file image.h.
   {
     drawLine(x, y, x+width, y, val);
     drawLine(x+width, y, x+width, y+height, val);
     drawLine(x+width, y+height, x, y+height, val);
     drawLine(x, y+height, x, y, val);
   }
template<class PIXEL> void Image< PIXEL >::drawChar (int x, int y, char c, PIXEL val) inline
Definition at line 453 of file image.h.
Referenced by Image< rgb >::drawString().
   {
     int charWidth(8), charHeight(8), charSize(8);
     int x0=x;
     unsigned char* charpos(gfxPrimitivesFontdata + (unsigned char) c * charSize);
     unsigned char patt(0);
     for (int iy = 0; iy < charHeight; iy++) {
       unsigned char mask = 0x00;
       x=x0;
       for (int ix = 0; ix < charWidth; ix++) {
         if (!(mask >>= 1)) {
           patt = *charpos++;
           mask = 0x80;
         }
         if (patt & mask) setPixel(x,y,val);
         x++;
       }
       y++;
     }
   }
template<class PIXEL> void Image< PIXEL >::drawFatBox (int x, int y, int width, int height, PIXEL val) inline
Definition at line 330 of file image.h.
   {
     drawFatLine(x, y, x+width, y, val);
     drawFatLine(x+width, y, x+width, y+height, val);
     drawFatLine(x+width, y+height, x, y+height, val);
     drawFatLine(x, y+height, x, y, val);
   }
template<class PIXEL> void Image< PIXEL >::drawFatLine (int x0, int y0, int x1, int y1, PIXEL val) inline
Definition at line 265 of file image.h.
Referenced by Image< rgb >::drawFatBox().
 {
   int x, y, dx, dy, sx, sy, ax, ay, decy, decx;
   x = x0;
   y = y0;
   dx = x1 - x0;
   dy = y1 - y0;
   if ( dx > 0 ) {
     sx = 1;
   } else {
     if ( dx < 0 ) {
       sx = -1;
       dx = -dx;
     } else {
       sx = 0;
     }
   }
   if ( dy > 0 ) {
     sy = 1;
   } else {
     if ( dy < 0 ) {
       sy = -1;
       dy = -dy;
     } else {
       sy = 0;
     }
   }
   ax = 2 * dx;
   ay = 2 * dy;
   if ( dy <= dx ) {
     for ( decy = ay - ax; ; x = x + sx, decy = decy + ay ) {
       setPixel(x,y,val);setPixel(x+1,y,val);setPixel(x-1,y,val);
       setPixel(x,y-1,val);setPixel(x+1,y-1,val);setPixel(x-1,y-1,val);
       setPixel(x,y+1,val);setPixel(x+1,y+1,val);setPixel(x-1,y+1,val);
       //TABLE [_curstep] [ x ][ y ] = color;
       if ( x == x1 ) break;
       if ( decy >= 0 ) {
         decy = decy - ax;
         y = y + sy;
       }
     }
   } else {
     for ( decx = ax - ay; ; y = y + sy, decx = decx + ax ) {
       setPixel(x,y,val);setPixel(x+1,y,val);setPixel(x-1,y,val);
       setPixel(x,y-1,val);setPixel(x+1,y-1,val);setPixel(x-1,y-1,val);
       setPixel(x,y+1,val);setPixel(x+1,y+1,val);setPixel(x-1,y+1,val);
       if ( y == y1 ) break;
       if ( decx >= 0 ) {
         decx = decx - ay;
         x = x + sx;
       }
     }
   }
 }
template<class PIXEL> void Image< PIXEL >::drawLine (int x0, int y0, int x1, int y1, PIXEL val) inline
Definition at line 211 of file image.h.
Referenced by Image< rgb >::drawBox().
   {
   int x, y, dx, dy, sx, sy, ax, ay, decy, decx;
   x = x0;
   y = y0;
   dx = x1 - x0;
   dy = y1 - y0;
   if ( dx > 0 ) {
     sx = 1;
   } else {
     if ( dx < 0 ) {
       sx = -1;
       dx = -dx;
     } else {
       sx = 0;
     }
   }
   if ( dy > 0 ) {
     sy = 1;
   } else {
     if ( dy < 0 ) {
       sy = -1;
       dy = -dy;
     } else {
       sy = 0;
     }
   }
   ax = 2 * dx;
   ay = 2 * dy;
   if ( dy <= dx ) {
     for ( decy = ay - ax; ; x = x + sx, decy = decy + ay ) {
       setPixel(x,y,val);
       //TABLE [_curstep] [ x ][ y ] = color;
       if ( x == x1 ) break;
       if ( decy >= 0 ) {
         decy = decy - ax;
         y = y + sy;
       }
     }
   } else {
     for ( decx = ax - ay; ; y = y + sy, decx = decx + ax ) {
       setPixel(x,y,val);
       if ( y == y1 ) break;
       if ( decx >= 0 ) {
         decx = decx - ay;
         x = x + sx;
       }
     }
   }
 }
template<class PIXEL> void Image< PIXEL >::drawString (int x, int y, std::string s, PIXEL val) inline
Definition at line 476 of file image.h.
   {
     for (unsigned int i=0; i < s.length(); i++)
       drawChar(x+8*i, y, s[i], val);
   }
template<class PIXEL> void Image< PIXEL >::fillBlack () inline
Definition at line 162 of file image.h.
                    {
     memset(data,0,getNumBytes());
   }
template<class PIXEL> void Image< PIXEL >::fillColor (const PIXEL & color) inline
Definition at line 166 of file image.h.
{
     int count=getNumPixels();
     PIXEL * p=getPixelData();
     for (int i=0;i<count;i++) {
       (*p)=color;
       p++;
     }
   }
template<class PIXEL> void Image< PIXEL >::fromImage (const Image< PIXEL > & img) inline
Definition at line 79 of file image.h.
   {
     clear();
     _external=true;
     data=img.getData();
     width=img.getWidth();
     height=img.getHeight();
   }
template<class PIXEL> void Image< PIXEL >::fromRawImage (const RawImage< PIXEL > & img) inline
Definition at line 53 of file image.h.
Referenced by Image< rgb >::Image().
   {
     if (PIXEL::getColorFormat() == img.getColorFormat()) {
       clear();
       _external=true;
       data=(PIXEL *)img.getData();
       width=img.getWidth();
       height=img.getHeight();
     } else {
       fprintf(stderr,"cannot create image from rawimage. colortypes do not match\n");
     }
   }
template<class PIXEL> ColorFormat Image< PIXEL >::getColorFormat () const inline virtual
Implements ImageInterface.
Definition at line 137 of file image.h.
   {
     return PIXEL::getColorFormat();
   }
template<class PIXEL> unsigned char* Image< PIXEL >::getData () const inline virtual
Implements ImageInterface.
Definition at line 180 of file image.h.
Referenced by Image< rgb >::copy(), Image< rgb >::copyToRawImage(), Image< rgb >::fromImage(), and Image< rgb >::subtract().
   {
     return (unsigned char *) data;
   }
template<class PIXEL> int Image< PIXEL >::getHeight () const inline virtual
Implements ImageInterface.
Definition at line 147 of file image.h.
Referenced by CMVision::Histogram::addBox(), CMVisionThreshold::colorizeImageFromThresholding(), Image< rgb >::copy(), Image< rgb >::copyFromRectArea(), Image< rgb >::copyToRawImage(), CMVision::RegionProcessing::encodeRuns(), Image< rgb >::fromImage(), Image< rgb >::save(), CMVisionThreshold::thresholdImageRGB(), CMVisionThreshold::thresholdImageYUV422_UYVY(), and CMVisionThreshold::thresholdImageYUV444().
   {
     return height;
   };
template<class PIXEL> int Image< PIXEL >::getNumBytes () const inline virtual
Implements ImageInterface.
Definition at line 157 of file image.h.
Referenced by Image< rgb >::copy(), Image< rgb >::copyToRawImage(), and Image< rgb >::fillBlack().
   {
     return width*height*sizeof(PIXEL);
   }
template<class PIXEL> int Image< PIXEL >::getNumPixels () const inline virtual
Implements ImageInterface.
Definition at line 152 of file image.h.
Referenced by Image< rgb >::binarizeChanneledImage(), Image< rgb >::binarizeGreyImage(), CMVisionThreshold::colorizeImageFromThresholding(), Image< rgb >::convertToIntensity(), PluginVisualize::DrawThresholdedImage(), Image< rgb >::fillColor(), Image< rgb >::subtract(), CMVisionThreshold::thresholdImageRGB(), CMVisionThreshold::thresholdImageYUV422_UYVY(), and CMVisionThreshold::thresholdImageYUV444().
   {
     return width*height;
   }
template<class PIXEL> PIXEL Image< PIXEL >::getPixel (int number) const inline
Definition at line 185 of file image.h.
   {
     assert(number >= 0 && number < (width*height));
     return(*(data+number));
   }
template<class PIXEL> PIXEL Image< PIXEL >::getPixel (int x, int y) const inline
Definition at line 191 of file image.h.
   {
     assert(x >= 0 && y >=0 && x<width && y<height);
     return(*(data+(width*y)+x));
   }
template<class PIXEL> PIXEL* Image< PIXEL >::getPixelData () const inline
Definition at line 175 of file image.h.
Referenced by CMVision::Histogram::addBox(), Image< rgb >::binarizeChanneledImage(), Image< rgb >::binarizeGreyImage(), CMVisionThreshold::colorizeImageFromThresholding(), Image< rgb >::convertToIntensity(), Image< rgb >::copyFromRectArea(), PluginVisualize::DrawThresholdedImage(), CMVision::RegionProcessing::encodeRuns(), Image< rgb >::fillColor(), Image< rgb >::save(), Image< rgb >::subtract(), CMVisionThreshold::thresholdImageRGB(), CMVisionThreshold::thresholdImageYUV422_UYVY(), and CMVisionThreshold::thresholdImageYUV444().
   {
     return data;
   };
template<class PIXEL> PIXEL* Image< PIXEL >::getPixelPointer (int x, int y) const inline
Definition at line 197 of file image.h.
Referenced by Image< rgb >::copyFromRectArea().
   {
     assert(x >= 0 && y >=0 && x<width && y<height);
     return((data+(width*y)+x));
   }
template<class PIXEL> int Image< PIXEL >::getWidth () const inline virtual
Implements ImageInterface.
Definition at line 142 of file image.h.
Referenced by CMVision::Histogram::addBox(), CMVisionThreshold::colorizeImageFromThresholding(), Image< rgb >::copy(), Image< rgb >::copyFromRectArea(), Image< rgb >::copyToRawImage(), CMVision::RegionProcessing::encodeRuns(), Image< rgb >::fromImage(), Image< rgb >::save(), CMVisionThreshold::thresholdImageRGB(), CMVisionThreshold::thresholdImageYUV422_UYVY(), and CMVisionThreshold::thresholdImageYUV444().
   {
     return width;
   };
template<class PIXEL> bool Image< PIXEL >::load (string filename) inline
Definition at line 338 of file image.h.
{
   (void)filename;
    if ((PIXEL::getColorFormat()==COLOR_RGB8) || (PIXEL::getColorFormat()==COLOR_RGBA8)) {
       clear();
       int w,h;
       w=0;
       h=0;
       if (PIXEL::getColorFormat()==COLOR_RGB8) {
         data=(PIXEL *)(ImageIO::readRGB(w,h,filename.c_str()));
       } else {
         data=(PIXEL *)(ImageIO::readRGBA(w,h,filename.c_str()));
       }
       if (data!=0) {
         width=w;
         height=h;
         return true;
       } else {
         return false;
       }
    } else {
     //TODO: loading of formats other than pure RGB
     //      is not yet supported
     return false;
    }
   }
template<class PIXEL> bool Image< PIXEL >::save (string filename) inline
Definition at line 364 of file image.h.
{
    if (PIXEL::getColorFormat()==COLOR_RGB8) {
      return ImageIO::writeRGB(getPixelData(), getWidth() , getHeight() ,filename.c_str());
    } else {
     //TODO: saving of formats other than pure RGB
     //      is not yet supported
     return false;
    }
   }
template<class PIXEL> void Image< PIXEL >::setPixel (int x, int y, PIXEL val) inline
Definition at line 203 of file image.h.
Referenced by Image< rgb >::drawChar(), Image< rgb >::drawFatLine(), and Image< rgb >::drawLine().
   {
     if (x >= 0 && y >=0 && x<width && y<height) {
       (*(data+(width*y)+x))=val;
     }
   }
template<class PIXEL> void Image< PIXEL >::subtract (const Image< PIXEL > & source) inline
Definition at line 405 of file image.h.
{
     if (source.getNumPixels()==getNumPixels()) {
       register PIXEL * a=getPixelData();
       register PIXEL * b=source.getData();
       register unsigned int i;
       register unsigned int pixelCount=getNumPixels();
       for (i=0;i<pixelCount;i++) {
         (*a)-=(*b);
         a++;
         b++;
       }
     }
   }
Field Documentation
template<class PIXEL> bool Image< PIXEL >::_external
Definition at line 47 of file image.h.
template<class PIXEL> PIXEL* Image< PIXEL >::data
Definition at line 50 of file image.h.
Referenced by Image< rgb >::allocate(), Image< rgb >::getData(), Image< rgb >::getPixelData(), and Image< rgb >::~Image().
template<class PIXEL> int Image< PIXEL >::height
Definition at line 49 of file image.h.
Referenced by Image< rgb >::getHeight(), and Image< rgb >::getNumPixels().
template<class PIXEL> int Image< PIXEL >::width
Definition at line 48 of file image.h.
Referenced by Image< rgb >::getWidth().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/image.h