# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1224, 762)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 771, 501))
        self.graphicsView.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 0);\n"
"background-color: rgb(0, 85, 0);"))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(840, 310, 171, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("cmr10"))
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.playStartButton = QtGui.QPushButton(self.centralwidget)
        self.playStartButton.setGeometry(QtCore.QRect(660, 610, 151, 41))
        self.playStartButton.setObjectName(_fromUtf8("playStartButton"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(840, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("cmr10"))
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.skillStartButton = QtGui.QPushButton(self.centralwidget)
        self.skillStartButton.setGeometry(QtCore.QRect(850, 440, 151, 41))
        self.skillStartButton.setObjectName(_fromUtf8("skillStartButton"))
        self.skillResetButton = QtGui.QPushButton(self.centralwidget)
        self.skillResetButton.setGeometry(QtCore.QRect(1010, 440, 151, 41))
        self.skillResetButton.setObjectName(_fromUtf8("skillResetButton"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(840, 340, 331, 91))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelSkill = QtGui.QLabel(self.layoutWidget)
        self.labelSkill.setObjectName(_fromUtf8("labelSkill"))
        self.verticalLayout_4.addWidget(self.labelSkill)
        self.labelSkillBot = QtGui.QLabel(self.layoutWidget)
        self.labelSkillBot.setObjectName(_fromUtf8("labelSkillBot"))
        self.verticalLayout_4.addWidget(self.labelSkillBot)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.skillOptions = QtGui.QComboBox(self.layoutWidget)
        self.skillOptions.setObjectName(_fromUtf8("skillOptions"))
        self.skillOptions.addItem(_fromUtf8(""))
        self.skillOptions.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.skillOptions)
        self.botOptions = QtGui.QComboBox(self.layoutWidget)
        self.botOptions.setObjectName(_fromUtf8("botOptions"))
        self.botOptions.addItem(_fromUtf8(""))
        self.botOptions.addItem(_fromUtf8(""))
        self.botOptions.addItem(_fromUtf8(""))
        self.botOptions.addItem(_fromUtf8(""))
        self.botOptions.addItem(_fromUtf8(""))
        self.botOptions.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.botOptions)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.playResetButton = QtGui.QPushButton(self.centralwidget)
        self.playResetButton.setGeometry(QtCore.QRect(940, 240, 151, 41))
        self.playResetButton.setObjectName(_fromUtf8("playResetButton"))
        self.exitButton = QtGui.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(1078, 656, 121, 41))
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.labelPlay = QtGui.QLabel(self.centralwidget)
        self.labelPlay.setGeometry(QtCore.QRect(690, 560, 134, 17))
        self.labelPlay.setObjectName(_fromUtf8("labelPlay"))
        self.playOptions = QtGui.QComboBox(self.centralwidget)
        self.playOptions.setGeometry(QtCore.QRect(820, 550, 117, 27))
        self.playOptions.setObjectName(_fromUtf8("playOptions"))
        self.playOptions.addItem(_fromUtf8(""))
        self.playOptions.addItem(_fromUtf8(""))
        self.playOptions.addItem(_fromUtf8(""))
        self.startPlaySelectorButton = QtGui.QPushButton(self.centralwidget)
        self.startPlaySelectorButton.setGeometry(QtCore.QRect(10, 560, 191, 51))
        self.startPlaySelectorButton.setObjectName(_fromUtf8("startPlaySelectorButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 560, 171, 51))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(841, 41, 341, 171))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelPath = QtGui.QLabel(self.layoutWidget1)
        self.labelPath.setObjectName(_fromUtf8("labelPath"))
        self.verticalLayout_2.addWidget(self.labelPath)
        self.labelInitialPosition = QtGui.QLabel(self.layoutWidget1)
        self.labelInitialPosition.setObjectName(_fromUtf8("labelInitialPosition"))
        self.verticalLayout_2.addWidget(self.labelInitialPosition)
        self.labelTeam = QtGui.QLabel(self.layoutWidget1)
        self.labelTeam.setObjectName(_fromUtf8("labelTeam"))
        self.verticalLayout_2.addWidget(self.labelTeam)
        self.labelGoalie = QtGui.QLabel(self.layoutWidget1)
        self.labelGoalie.setObjectName(_fromUtf8("labelGoalie"))
        self.verticalLayout_2.addWidget(self.labelGoalie)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pathOptions = QtGui.QComboBox(self.layoutWidget1)
        self.pathOptions.setObjectName(_fromUtf8("pathOptions"))
        self.pathOptions.addItem(_fromUtf8(""))
        self.pathOptions.addItem(_fromUtf8(""))
        self.pathOptions.addItem(_fromUtf8(""))
        self.pathOptions.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.pathOptions)
        self.initialPositionOptions = QtGui.QComboBox(self.layoutWidget1)
        self.initialPositionOptions.setObjectName(_fromUtf8("initialPositionOptions"))
        self.initialPositionOptions.addItem(_fromUtf8(""))
        self.initialPositionOptions.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.initialPositionOptions)
        self.teamOptions = QtGui.QComboBox(self.layoutWidget1)
        self.teamOptions.setObjectName(_fromUtf8("teamOptions"))
        self.teamOptions.addItem(_fromUtf8(""))
        self.teamOptions.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.teamOptions)
        self.goalieOptions = QtGui.QComboBox(self.layoutWidget1)
        self.goalieOptions.setObjectName(_fromUtf8("goalieOptions"))
        self.goalieOptions.addItem(_fromUtf8(""))
        self.goalieOptions.addItem(_fromUtf8(""))
        self.goalieOptions.addItem(_fromUtf8(""))
        self.goalieOptions.addItem(_fromUtf8(""))
        self.goalieOptions.addItem(_fromUtf8(""))
        self.goalieOptions.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.goalieOptions)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1224, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_7.setText(_translate("MainWindow", "Skill Testing", None))
        self.playStartButton.setText(_translate("MainWindow", "Start Play", None))
        self.label_8.setText(_translate("MainWindow", "Initial Conditions", None))
        self.skillStartButton.setText(_translate("MainWindow", "Start Skill", None))
        self.skillResetButton.setText(_translate("MainWindow", "Reset", None))
        self.labelSkill.setText(_translate("MainWindow", "Select Skill", None))
        self.labelSkillBot.setText(_translate("MainWindow", "Select Bot", None))
        self.skillOptions.setItemText(0, _translate("MainWindow", "goToBall", None))
        self.skillOptions.setItemText(1, _translate("MainWindow", "goToPoint", None))
        self.botOptions.setItemText(0, _translate("MainWindow", "0", None))
        self.botOptions.setItemText(1, _translate("MainWindow", "1", None))
        self.botOptions.setItemText(2, _translate("MainWindow", "2", None))
        self.botOptions.setItemText(3, _translate("MainWindow", "3", None))
        self.botOptions.setItemText(4, _translate("MainWindow", "4", None))
        self.botOptions.setItemText(5, _translate("MainWindow", "5", None))
        self.playResetButton.setText(_translate("MainWindow", "Reset", None))
        self.exitButton.setText(_translate("MainWindow", "EXIT", None))
        self.labelPlay.setText(_translate("MainWindow", "Select Play", None))
        self.playOptions.setItemText(0, _translate("MainWindow", "Offensive", None))
        self.playOptions.setItemText(1, _translate("MainWindow", "Defensive", None))
        self.playOptions.setItemText(2, _translate("MainWindow", "Stall", None))
        self.startPlaySelectorButton.setText(_translate("MainWindow", "Start Play Selector", None))
        self.pushButton_2.setText(_translate("MainWindow", "Kill", None))
        self.labelPath.setText(_translate("MainWindow", "Select Path Planner", None))
        self.labelInitialPosition.setText(_translate("MainWindow", "Set Initial Position", None))
        self.labelTeam.setText(_translate("MainWindow", "Select Team", None))
        self.labelGoalie.setText(_translate("MainWindow", "Select Goalie", None))
        self.pathOptions.setItemText(0, _translate("MainWindow", "RRT", None))
        self.pathOptions.setItemText(1, _translate("MainWindow", "RRTStar", None))
        self.pathOptions.setItemText(2, _translate("MainWindow", "RRTConnect", None))
        self.pathOptions.setItemText(3, _translate("MainWindow", "LazyRRT", None))
        self.initialPositionOptions.setItemText(0, _translate("MainWindow", "Position 1", None))
        self.initialPositionOptions.setItemText(1, _translate("MainWindow", "Position2", None))
        self.teamOptions.setItemText(0, _translate("MainWindow", "Team Yellow", None))
        self.teamOptions.setItemText(1, _translate("MainWindow", "Team  Blue", None))
        self.goalieOptions.setItemText(0, _translate("MainWindow", "0", None))
        self.goalieOptions.setItemText(1, _translate("MainWindow", "1", None))
        self.goalieOptions.setItemText(2, _translate("MainWindow", "2", None))
        self.goalieOptions.setItemText(3, _translate("MainWindow", "3", None))
        self.goalieOptions.setItemText(4, _translate("MainWindow", "4", None))
        self.goalieOptions.setItemText(5, _translate("MainWindow", "5", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

