Documentation: Vec::NVector< num, dim > Class Template Reference
Vec::NVector< num, dim > Class Template Reference
#include <nvector.h>
Public Member Functions
num & operator[] (int i)
const num & operator[] (int i) const
int size ()
template<class num2 >
void set (num2 val)
void copy (const NVector< num, dim > &a)
void zero ()
void unit (int dir)
num sqlength ()
num length ()
void add (const NVector< num, dim > &a)
void sub (const NVector< num, dim > &a)
void mul (const NVector< num, dim > &a)
void div (const NVector< num, dim > &a)
void add (const NVector< num, dim > &a, const NVector< num, dim > &b)
void sub (const NVector< num, dim > &a, const NVector< num, dim > &b)
void mul (const NVector< num, dim > &a, const NVector< num, dim > &b)
void div (const NVector< num, dim > &a, const NVector< num, dim > &b)
template<class num2 >
void mul (const NVector< num, dim > &a, num2 s)
template<class num2 >
void div (const NVector< num, dim > &a, num2 s)
template<class num2 >
void mul (num2 s)
template<class num2 >
void div (num2 s)
void neg (const NVector< num, dim > &a)
void neg ()
void norm (const NVector< num, dim > &a)
void norm ()
void min (const NVector< num, dim > &a, const NVector< num, dim > &b)
void max (const NVector< num, dim > &a, const NVector< num, dim > &b)
void abs_bound (const NVector< num, dim > &a, const NVector< num, dim > &b)
void bound (const NVector &a, const NVector &b, const NVector &c)
Data Fields
num v [dim]
Detailed Description
template<class num, const int dim>
class Vec::NVector< num, dim >
Definition at line 31 of file nvector.h.
Member Function Documentation
template<class num, const int dim> void Vec::NVector< num, dim >::abs_bound (const NVector< num, dim > & a, const NVector< num, dim > & b)
Definition at line 262 of file nvector.h.
Referenced by Vec::NVector< num_t, dim >::norm().
template<class num, const int dim> void Vec::NVector< num, dim >::add (const NVector< num, dim > & a)
Definition at line 166 of file nvector.h.
Referenced by Vec::NVector< num_t, dim >::length().
template<class num, const int dim> void Vec::NVector< num, dim >::add (const NVector< num, dim > & a, const NVector< num, dim > & b)
Definition at line 191 of file nvector.h.
template<class num , const int dim> void Vec::NVector< num, dim >::bound (const NVector< num, dim > & a, const NVector< num, dim > & b, const NVector< num, dim > & c)
Definition at line 284 of file nvector.h.
Referenced by NKDTree< state_t, num_t, dim, scaled, get_next >::distFromQuery(), and Vec::NVector< num_t, dim >::norm().
 {
template<class num, const int dim> void Vec::NVector< num, dim >::copy (const NVector< num, dim > & a)
Definition at line 100 of file nvector.h.
References velocity.pid_::i, and Vec::NVector< num, dim >::v.
Referenced by Vec::NVector< num_t, dim >::size().
 {
   switch(dim){
     case 4: v[3] = a.v[3];
     case 3: v[2] = a.v[2];
     case 2: v[1] = a.v[1];
     case 1: v[0] = a.v[0];
       break;
     default:
       for(int i=0; i<dim; i++){
         v[i] = a.v[i];
       }
   }
 }
template<class num, const int dim> void Vec::NVector< num, dim >::div (const NVector< num, dim > & a)
Definition at line 169 of file nvector.h.
Referenced by Vec::NVector< num_t, dim >::length().
template<class num, const int dim> void Vec::NVector< num, dim >::div (const NVector< num, dim > & a, const NVector< num, dim > & b)
Definition at line 194 of file nvector.h.
template<class num, const int dim> template<class num2 > void Vec::NVector< num, dim >::div (const NVector< num, dim > & a, num2 s)
Definition at line 217 of file nvector.h.
template<class num, const int dim> template<class num2 > void Vec::NVector< num, dim >::div (num2 s)
Definition at line 238 of file nvector.h.
template<class num, const int dim> num Vec::NVector< num, dim >::length () inline
Definition at line 49 of file nvector.h.
Referenced by Vec::NVector< num_t, dim >::norm().
 {return(sqrt(sqlength()));}
template<class num, const int dim> void Vec::NVector< num, dim >::max (const NVector< num, dim > & a, const NVector< num, dim > & b)
Definition at line 261 of file nvector.h.
Referenced by NKDTree< state_t, num_t, dim, scaled, get_next >::calcBBox(), and Vec::NVector< num_t, dim >::norm().
template<class num, const int dim> void Vec::NVector< num, dim >::min (const NVector< num, dim > & a, const NVector< num, dim > & b)
Definition at line 260 of file nvector.h.
Referenced by NKDTree< state_t, num_t, dim, scaled, get_next >::calcBBox(), and Vec::NVector< num_t, dim >::norm().
template<class num, const int dim> void Vec::NVector< num, dim >::mul (const NVector< num, dim > & a)
Definition at line 168 of file nvector.h.
Referenced by Vec::NVector< num_t, dim >::length(), Vec::NVector< num_t, dim >::neg(), and Vec::NVector< num_t, dim >::norm().
template<class num, const int dim> void Vec::NVector< num, dim >::mul (const NVector< num, dim > & a, const NVector< num, dim > & b)
Definition at line 193 of file nvector.h.
template<class num, const int dim> template<class num2 > void Vec::NVector< num, dim >::mul (const NVector< num, dim > & a, num2 s)
Definition at line 216 of file nvector.h.
template<class num, const int dim> template<class num2 > void Vec::NVector< num, dim >::mul (num2 s)
Definition at line 237 of file nvector.h.
template<class num, const int dim> void Vec::NVector< num, dim >::neg (const NVector< num, dim > & a) inline
Definition at line 71 of file nvector.h.
 {mul(a,-1);}
template<class num, const int dim> void Vec::NVector< num, dim >::neg () inline
Definition at line 72 of file nvector.h.
 {mul(-1);}
template<class num, const int dim> void Vec::NVector< num, dim >::norm (const NVector< num, dim > & a) inline
Definition at line 73 of file nvector.h.
 {mul(a,1/a.length());}
template<class num, const int dim> void Vec::NVector< num, dim >::norm () inline
Definition at line 74 of file nvector.h.
 {mul(1/length());}
template<class num, const int dim> num& Vec::NVector< num, dim >::operator[] (int i) inline
Definition at line 35 of file nvector.h.
     {return(v[i]);}
template<class num, const int dim> const num& Vec::NVector< num, dim >::operator[] (int i) const inline
Definition at line 37 of file nvector.h.
     {return(v[i]);}
template<class num , const int dim> template<class num2 > void Vec::NVector< num, dim >::set (num2 val)
Definition at line 84 of file nvector.h.
References velocity.pid_::i, and Vec::NVector< num, dim >::v.
Referenced by NKDTree< Region, float, 2, false, CMVision::RegionTreeGetNext >::NKDTree().
 {
   switch(dim){
     case 4: v[3] = val;
     case 3: v[2] = val;
     case 2: v[1] = val;
     case 1: v[0] = val;
       break;
     default:
       for(int i=0; i<dim; i++){
         v[i] = val;
       }
   }
 }
template<class num, const int dim> int Vec::NVector< num, dim >::size () inline
Definition at line 40 of file nvector.h.
 {return(dim);}
template<class num , const int dim> num Vec::NVector< num, dim >::sqlength ()
Definition at line 132 of file nvector.h.
References velocity.pid_::i, and Vec::NVector< num, dim >::v.
Referenced by Vec::NVector< num_t, dim >::length(), and Vec::NVector< num_t, dim >::zero().
 {
   num sum = 0;
   switch(dim){
     case 4: sum += v[3] * v[3];
     case 3: sum += v[2] * v[2];
     case 2: sum += v[1] * v[1];
     case 1: sum += v[0] * v[0];
       break;
     default:
       for(int i=0; i<dim; i++){
         sum += v[i] * v[i];
       }
   }
   return(sum);
 }
template<class num, const int dim> void Vec::NVector< num, dim >::sub (const NVector< num, dim > & a)
Definition at line 167 of file nvector.h.
Referenced by Vec::NVector< num_t, dim >::length().
template<class num, const int dim> void Vec::NVector< num, dim >::sub (const NVector< num, dim > & a, const NVector< num, dim > & b)
Definition at line 192 of file nvector.h.
template<class num , const int dim> void Vec::NVector< num, dim >::unit (int dir)
Definition at line 116 of file nvector.h.
References velocity.pid_::i, and Vec::NVector< num, dim >::v.
Referenced by Vec::NVector< num_t, dim >::zero().
 {
   switch(dim){
     case 4: v[3] = (dir == 3);
     case 3: v[2] = (dir == 2);
     case 2: v[1] = (dir == 1);
     case 1: v[0] = (dir == 0);
       break;
     default:
       for(int i=0; i<dim; i++){
         v[i] = (dir == i);
       }
   }
 }
template<class num, const int dim> void Vec::NVector< num, dim >::zero () inline
Definition at line 46 of file nvector.h.
 {set(0);}
Field Documentation
template<class num, const int dim> num Vec::NVector< num, dim >::v[dim]
Definition at line 33 of file nvector.h.
Referenced by Vec::NVector< num, dim >::copy(), Vec::dot(), Vec::NVector< num, dim >::set(), Vec::NVector< num, dim >::sqlength(), and Vec::NVector< num, dim >::unit().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/nvector.h