Documentation: TimeVar Class Reference
TimeVar Class Reference
#include <TimeVar.h>
Public Member Functions
TimeVar (string _name="", TimeIndex idx=0.0, VarType *vdt=0)
VarType * getData () const
void setData (VarType *vdt)
virtual ~TimeVar ()
virtual VarTypeId getType () const
virtual string getTypeName () const
virtual string getString () const
virtual void setString (string val)
virtual void resetToDefault ()
virtual void printdebug () const
virtual void setDouble (double val)
virtual double getDouble () const
virtual bool hasValue () const
virtual double getValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual vector< VarType * > getChildren () const
virtual void setSerialString (string val)
virtual string getSerialString () const
Protected Member Functions
virtual void readChildren (XMLNode &us)
virtual void readAttributes (XMLNode &us)
virtual void updateAttributes (XMLNode &us) const
Protected Attributes
VarType * data
Detailed Description
Definition at line 26 of file TimeVar.h.
Constructor & Destructor Documentation
TimeVar::TimeVar (string _name = "", TimeIndex idx = 0.0, VarType * vdt = 0) inline
Definition at line 31 of file TimeVar.h.
References setData().
                                                                           : VarType ( _name ), TimeIndex ( idx ) {
       setData ( vdt );
     };
virtual TimeVar::~TimeVar () inline virtual
Definition at line 40 of file TimeVar.h.
 {};
Member Function Documentation
virtual vector<VarType *> TimeVar::getChildren () const inline virtual
Definition at line 70 of file TimeVar.h.
References v.
{
       vector<VarType *> v;
       v.push_back ( data );
       return v;
     }
VarType* TimeVar::getData () const inline
Definition at line 34 of file TimeVar.h.
References data.
Referenced by TimeLine::getValueClosedRange(), and GraphScene::makePath().
{
       return data;
     }
virtual double TimeVar::getDouble () const inline virtual
Definition at line 63 of file TimeVar.h.
 { return getTime(); }
virtual string TimeVar::getSerialString () const inline virtual
Definition at line 80 of file TimeVar.h.
{
       return "";
     }
virtual string TimeVar::getString () const inline virtual
Definition at line 43 of file TimeVar.h.
{
       char result[255];
       result[0] = 0;
       sprintf ( result, "%lf", getTime() );
       return result;
     };
virtual VarTypeId TimeVar::getType () const inline virtual
Definition at line 41 of file TimeVar.h.
Referenced by getTypeName().
 { return DT_TIMEVAR; };
virtual string TimeVar::getTypeName () const inline virtual
Definition at line 42 of file TimeVar.h.
References getType().
 { return typeToString ( getType() ); };
virtual double TimeVar::getValue () const inline virtual
Definition at line 66 of file TimeVar.h.
 { return getTime(); }
virtual bool TimeVar::hasMaxValue () const inline virtual
Definition at line 67 of file TimeVar.h.
 { return false; }
virtual bool TimeVar::hasMinValue () const inline virtual
Definition at line 68 of file TimeVar.h.
 { return false; }
virtual bool TimeVar::hasValue () const inline virtual
Definition at line 65 of file TimeVar.h.
 { return true; }
virtual void TimeVar::printdebug () const inline virtual
Definition at line 56 of file TimeVar.h.
{
       printf ( "Time Index : %f\n", getTime() );
     }
virtual void TimeVar::readAttributes (XMLNode & us) inline protected virtual
Definition at line 100 of file TimeVar.h.
{
       string s = fixString ( us.getAttribute ( "time" ) );
       if ( s == "" ) {
         setTime ( 0.0 );
       } else {
         double num = 0; sscanf ( s.c_str(), "%lf", &num );
         setTime ( num );
       }
       changed();
     }
virtual void TimeVar::readChildren (XMLNode & us) inline protected virtual
Definition at line 88 of file TimeVar.h.
References v.
{
       vector<VarType *> v;
       v = readChildrenHelper ( us, v, false, true );
       if ( v.size() > 0 ) {
         data = v[0];
       } else {
         data = 0;
       }
       changed();
     }
virtual void TimeVar::resetToDefault () inline virtual
Definition at line 52 of file TimeVar.h.
{
       setTime ( 0.0 );
       changed();
     }
void TimeVar::setData (VarType * vdt) inline
Definition at line 37 of file TimeVar.h.
Referenced by TimeVar().
{
       data = vdt;
     }
virtual void TimeVar::setDouble (double val) inline virtual
Definition at line 60 of file TimeVar.h.
 { setTime ( val ); changed(); };
virtual void TimeVar::setSerialString (string val) inline virtual
Definition at line 76 of file TimeVar.h.
{
     }
virtual void TimeVar::setString (string val) inline virtual
Definition at line 49 of file TimeVar.h.
 { double num = 0; sscanf ( val.c_str(), "%lf", &num ); setTime ( num ); };
virtual void TimeVar::updateAttributes (XMLNode & us) const inline protected virtual
Definition at line 111 of file TimeVar.h.
{
       us.updateAttribute ( doubleToString ( getTime() ).c_str(), "time", "time" );
     }
Field Documentation
VarType* TimeVar::data protected
Definition at line 29 of file TimeVar.h.
Referenced by getData().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/vartypes/enhanced/TimeVar.h