Documentation: GlobalV4Linstance Class Reference
GlobalV4Linstance Class Reference
A singleton provider of a v4l lib context used for capturing with multiple threads.
#include <capturev4l.h>
Data Structures
struct image_t
struct rgb
struct yuv
struct yuyv
Public Types
enum private_control_t { V4L2_FEATURE_PRIVATE = V4L2_CID_PRIVATE_BASE, V4L2_FEATURE_FRAME_RATE }
Public Member Functions
bool getControl (int ctrl_id, long &s)
bool setControl (int ctrl_id, long s)
bool checkControl (int ctrl_id, bool *bEnabled=NULL, bool *bReadOnly=NULL, long *lDefault=NULL, long *lMin=NULL, long *lMax=NULL)
bool startStreaming (int iWidth_, int iHeight_, int iInput=0)
bool stopStreaming ()
void captureWarm (int iMaxSpin=1)
bool captureFrame (RawImage *pImage, int iMaxSpin=1)
const image_t * captureFrame (int iMaxSpin=1)
bool releaseFrame (const image_t *_img)
Static Public Member Functions
static bool writeYuyvPPM (GlobalV4Linstance::yuyv *pSrc, int width, int height, const char *filename)
static bool writeRgbPPM (GlobalV4Linstance::rgb *imgbuf, int width, int height, const char *filename)
Protected Member Functions
GlobalV4Linstance ()
~GlobalV4Linstance ()
Protected Attributes
QMutex mutex
Private Member Functions
bool enqueueBuffer (v4l2_buffer &buf)
bool dequeueBuffer (v4l2_buffer &buf)
bool waitForFrame (int max_msec=500)
bool obtainInstance (int iDevice)
bool obtainInstance (char *szDevice)
bool removeInstance (bool bRelock=true)
bool xioctl (int request, void *data, const char *error_str)
void lock ()
void unlock ()
Static Private Member Functions
static int xioctl (int fd, int request, void *data, const char *error_str)
static bool getImageRgb (GlobalV4Linstance::yuyv *pSrc, int width, int height, GlobalV4Linstance::rgb **rgbbuf)
static GlobalV4Linstance::rgb yuv2rgb (GlobalV4Linstance::yuv p)
Private Attributes
pollfd pollset
char counter
char szDevice [128]
struct v4l2_buffer tempbuf
image_t img [3]
Friends
class GlobalV4LinstanceManager
Detailed Description
A singleton provider of a v4l lib context used for capturing with multiple threads.
Author
Eric Zavesky, (C) 2016 (derived from DC1394 interface)
Definition at line 71 of file capturev4l.h.
Member Enumeration Documentation
enum GlobalV4Linstance::private_control_t
Enumerator
V4L2_FEATURE_PRIVATE
V4L2_FEATURE_FRAME_RATE
Definition at line 82 of file capturev4l.h.
                            {    //custom control codes that must be individually caught...
         V4L2_FEATURE_PRIVATE = V4L2_CID_PRIVATE_BASE,
         V4L2_FEATURE_FRAME_RATE
     };
Constructor & Destructor Documentation
GlobalV4Linstance::GlobalV4Linstance () inline protected
Definition at line 87 of file capturev4l.h.
References counter, img, mutex, mzero(), pollset, szDevice, and V4L_STREAMBUFS.
{
 #ifndef VDATA_NO_QT
 #else
         pthread_mutex_init (&mutex);
 #endif
         counter=0;
         pollset.fd=-1;
         mzero(img, V4L_STREAMBUFS);
         memset(szDevice, 0, sizeof(char)*128);
     }
GlobalV4Linstance::~GlobalV4Linstance () inline protected
Definition at line 97 of file capturev4l.h.
References counter, mutex, and removeInstance().
{
         while (counter) removeInstance();       //if iterating, release control first
 #ifndef VDATA_NO_QT
 #else
         pthread_mutex_destroy (&mutex);
 #endif
     }
Member Function Documentation
bool GlobalV4Linstance::captureFrame (RawImage * pImage, int iMaxSpin = 1)
Definition at line 237 of file capturev4l.cpp.
References GlobalV4Linstance::image_t::data, RawImage::getData(), RawImage::getHeight(), RawImage::getWidth(), RawImage::setTime(), and GlobalV4Linstance::image_t::timestamp.
Referenced by CaptureV4L::getFrame().
 {
     const image_t *_img = captureFrame(iMaxSpin);       //low-level fetch
     if (!_img || _img->data==NULL) return false;
     bool bSuccess = false;
     if (_img) {
         if (pImage) {                                       //allow null to stoke the capture
             unsigned char *pDest = pImage->getData();
             if (!pDest) {                                   //we don't want low-level to reallocate!
                 fprintf(stderr,"GlobalV4Linstance: RawImage not pre-allocated in captureFrame in device '%s'\n",
                         szDevice);
             }
             lock();
             //mid-level copy to RGB
             if (_img->data &&
                     getImageRgb(reinterpret_cast<GlobalV4Linstance::yuyv *>(_img->data),
                              pImage->getWidth(), pImage->getHeight(),
                              reinterpret_cast<GlobalV4Linstance::rgb **>(&pDest)) )
             {
                 // just copy timestamp from v4l buffer
                 // http://www.linuxtv.org/downloads/v4l-dvb-apis/buffer.html
                 // http://linux.die.net/man/2/gettimeofday
                 /*
                 timeval tv;
                 pImage->setTime(0.0);
                 //TODO: we could copy the timestamp from the tempbuf/image itself
                 gettimeofday(&tv,NULL);
                 pImage->setTime((double)tv.tv_sec + tv.tv_usec*(1.0E-6));
                 */
                 pImage->setTime((double)_img->timestamp.tv_sec + _img->timestamp.tv_usec*(1.0E-6));
                 bSuccess = true;
             }
             unlock();
         }
         if ( !releaseFrame(_img))                            //maybe we shouldn't return an error?
             return false;
     }
     return bSuccess;
 }
const GlobalV4Linstance::image_t * GlobalV4Linstance::captureFrame (int iMaxSpin = 1)
Definition at line 281 of file capturev4l.cpp.
References velocity.pid_::i.
 {
     if(!waitForFrame(300)) {
         fprintf(stderr,"GlobalV4Linstance: error waiting for frame '%s'\n", szDevice);
         return(NULL);
     }
     do {
         // get the frame
         dequeueBuffer(tempbuf);
         // poll to see if a another frame is already available
         // if so, break out now
         if(!waitForFrame(0)) break;
         // otherwise, drop this frame
         enqueueBuffer(tempbuf);
     }
     while(iMaxSpin--);
     int i = tempbuf.index;
     img[i].timestamp = tempbuf.timestamp;
     img[i].field = (tempbuf.field == V4L2_FIELD_BOTTOM);
     return(&(img[i]));
 }
void GlobalV4Linstance::captureWarm (int iMaxSpin = 1)
Definition at line 316 of file capturev4l.cpp.
References GlobalV4Linstance::image_t::data.
Referenced by CaptureV4L::startCapture().
 {
     const GlobalV4Linstance::image_t *_img = NULL;
     while (!_img) {
         _img = captureFrame(iMaxSpin);
     }
     if (_img->data)
         releaseFrame(_img);
 }
bool GlobalV4Linstance::checkControl (int ctrl_id, bool * bEnabled = NULL, bool * bReadOnly = NULL, long * lDefault = NULL, long * lMin = NULL, long * lMax = NULL)
Definition at line 447 of file capturev4l.cpp.
References mzero().
Referenced by CaptureV4L::readParameterProperty(), and CaptureV4L::readParameterValues().
{
     v4l2_queryctrl queryctrl;
     mzero(queryctrl);
     queryctrl.id = ctrl_id;
     if(xioctl(VIDIOC_QUERYCTRL, &queryctrl, "CheckControl")) {
         if (bEnabled) (*bEnabled) = !(queryctrl.flags & V4L2_CTRL_FLAG_DISABLED);
         if (bReadOnly) (*bReadOnly) = queryctrl.flags & V4L2_CTRL_FLAG_READ_ONLY;
         if (lMin) (*lMin) = queryctrl.minimum;
         if (lMax) (*lMax) = queryctrl.maximum;
         if (lDefault) (*lDefault) = queryctrl.default_value;
         return true;
     }
     return false;
 }
bool GlobalV4Linstance::dequeueBuffer (v4l2_buffer & buf) private
Definition at line 442 of file capturev4l.cpp.
 {
     return xioctl(VIDIOC_DQBUF, &buf, "DequeueBuffer");
 }
bool GlobalV4Linstance::enqueueBuffer (v4l2_buffer & buf) private
Definition at line 437 of file capturev4l.cpp.
 {
     return xioctl(VIDIOC_QBUF, &buf, "EnqueueBuffer");
 }
bool GlobalV4Linstance::getControl (int ctrl_id, long & s)
Definition at line 465 of file capturev4l.cpp.
References mzero().
Referenced by CaptureV4L::readParameterProperty(), and CaptureV4L::readParameterValues().
 {
     v4l2_control ctrl;
     mzero(ctrl);
     ctrl.id = ctrl_id;
     if(xioctl(VIDIOC_G_CTRL, &ctrl, "GetControl")) {
         s = ctrl.value;
         return(true);
     }else{
         return(false);
     }
 }
bool GlobalV4Linstance::getImageRgb (GlobalV4Linstance::yuyv * pSrc, int width, int height, GlobalV4Linstance::rgb ** rgbbuf) static private
Definition at line 519 of file capturev4l.cpp.
References GlobalV4Linstance::yuyv::u, GlobalV4Linstance::yuv::u, GlobalV4Linstance::yuyv::v, GlobalV4Linstance::yuv::v, GlobalV4Linstance::yuv::y, GlobalV4Linstance::yuyv::y1, and GlobalV4Linstance::yuyv::y2.
 {
     if (!rgbbuf) return false;
     if ((*rgbbuf)==NULL)
         (*rgbbuf) = new rgb[width * height];
     int size = width*height;
     GlobalV4Linstance::rgb *pDest = (*rgbbuf);
     GlobalV4Linstance::yuv pxCopy;
     for (int iP=0; iP<size; iP++) {
         pxCopy.y = (iP&1)? pSrc->y2 : pSrc->y1;
         pxCopy.u = pSrc->u;
         pxCopy.v = pSrc->v;
         (*pDest) = yuv2rgb(pxCopy);
         pDest++;                //advance destination always
         if (iP&1) pSrc++;       //avoid odd field advancement
     }
     return true;
 }
void GlobalV4Linstance::lock () inline private
Definition at line 141 of file capturev4l.h.
                 {
 #ifndef VDATA_NO_QT
         mutex.lock();
 #else
         pthread_mutex_lock();
 #endif
     }
bool GlobalV4Linstance::obtainInstance (int iDevice) private
Definition at line 120 of file capturev4l.cpp.
References GlobalV4LinstanceManager::obtainInstance().
 {
     char szDeviceLocal[128];
     snprintf(szDeviceLocal, 128, "/dev/video%d", iDevice);
     return obtainInstance(szDeviceLocal);
 }
bool GlobalV4Linstance::obtainInstance (char * szDevice) private
Definition at line 127 of file capturev4l.cpp.
References mzero(), and GlobalV4LinstanceManager::removeInstance().
 {
     lock();
     bool bSuccess = (pollset.fd > -1);
     //fprintf(stderr,"WARNING: obtainInstance ENTER : counter : %d!\n", counter);
     if (counter == 0) {
         if (pollset.fd < 0) {
             counter = 1;
             removeInstance(false);
         }
         pollset.fd = open(szDevice_, O_RDWR|O_NONBLOCK);
         if(pollset.fd > -1) bSuccess = true;
         if (bSuccess) {
             pollset.events = POLLIN;
             // test capture capabilities
             v4l2_capability cap;
             if(xioctl(pollset.fd, VIDIOC_QUERYCAP, &cap, "VideoQueryCap") == 0){
                 if(!(cap.capabilities & V4L2_CAP_VIDEO_CAPTURE) ||
                    !(cap.capabilities & V4L2_CAP_STREAMING)){
                     bSuccess = false;
                 }
             }else{
                 bSuccess = false;
             }
         }
         // set cropping to default (no effect if not supported)
         if(bSuccess && false){
             v4l2_cropcap cropcap;
             v4l2_crop crop;
             mzero(cropcap);
             mzero(crop);
             cropcap.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
             xioctl(pollset.fd, VIDIOC_CROPCAP, &cropcap, "CropCap");
             crop.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
             crop.c = cropcap.defrect;
             xioctl(pollset.fd, VIDIOC_S_CROP, &crop, "SetCrop");
         }
         if (!bSuccess ) {
             if(pollset.fd > -1) close(pollset.fd);
             pollset.fd = -1;
         }
         else {
             strncpy(szDevice, szDevice_, 128);
         }
     }
     if (bSuccess)
         counter++;
     //fprintf(stderr,"WARNING: obtainInstance EXIT : counter : %d!\n", counter);
     unlock();
     return bSuccess;
 }
bool GlobalV4Linstance::releaseFrame (const image_t * _img)
Definition at line 307 of file capturev4l.cpp.
References GlobalV4Linstance::image_t::index.
Referenced by CaptureV4L::getV4LfeatureEnum().
 {
     if(!_img) return(false);
     tempbuf.index = _img->index;
     return(enqueueBuffer(tempbuf));
 }
bool GlobalV4Linstance::removeInstance (bool bRelock = true) private
Definition at line 185 of file capturev4l.cpp.
Referenced by GlobalV4LinstanceManager::removeInstance(), and ~GlobalV4Linstance().
 {
     if (bRelock) lock();
     counter--;
     bool was_last=false;
     if (counter == 0) {
         if(pollset.fd >= 0) {
             stopStreaming();
             close(pollset.fd);
         }
         pollset.fd = -1;
         memset(szDevice, 0, sizeof(char)*128);
         was_last=true;
     }
     if (counter < 0) {
         fprintf(stderr,"WARNING: Attempting to remove more instances than have been created!\n");
         fflush(stderr);
         counter = 0;
     }
     if (bRelock) unlock();
     return was_last;
 }
bool GlobalV4Linstance::setControl (int ctrl_id, long s)
Definition at line 479 of file capturev4l.cpp.
References mzero().
Referenced by CaptureV4L::writeParameterValues().
 {
     v4l2_control ctrl;
     mzero(ctrl);
     ctrl.id = ctrl_id;
     ctrl.value = s;
     if(xioctl(VIDIOC_S_CTRL, &ctrl, "SetControl")){
         return(true);
     }else{
         return(false);
     }
 }
bool GlobalV4Linstance::startStreaming (int iWidth_, int iHeight_, int iInput = 0)
Definition at line 333 of file capturev4l.cpp.
References velocity.pid_::i, mzero(), and V4L_STREAMBUFS.
Referenced by CaptureV4L::startCapture().
 {
     struct v4l2_requestbuffers req;
     // Set video format
     v4l2_format fmt;
     mzero(fmt);
     fmt.fmt.pix.width       = iWidth_;
     fmt.fmt.pix.height      = iHeight_;
     fmt.fmt.pix.pixelformat = V4L2_PIX_FMT_YUYV;        //see note at top of file
     fmt.fmt.pix.field       = V4L2_FIELD_ALTERNATE;
     fmt.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
     if (!xioctl(VIDIOC_S_FMT, &fmt, "SetFormat")) {
         printf("Warning: Could not set format, '%s'; was device previously started?\n", szDevice);
  //       return(false);
     }
     // Set Input and Controls (for more advanced v4l as well)
     // http://www.linuxtv.org/downloads/v4l-dvb-apis/vidioc-g-input.html
     // vid.setInput(0); // main capture (cable or camera video)
     // vid.setInput(1); // Component video
     // vid.setInput(2); // S-video
     xioctl(VIDIOC_S_INPUT,&iInputIdx,"SetInput");
     /*
     v4l2_std_id id = V4L2_STD_NTSC_M;               //TODO: modify/detect for other cameras
     xioctl(VIDIOC_S_STD,&id,"SetStandard");
     long lControlVal = static_cast<long>(0.5f*(1 << 16));
     setControl(V4L2_CID_BRIGHTNESS, lControlVal);
     setControl(V4L2_CID_HUE, lControlVal);
     setControl(V4L2_CID_CONTRAST, lControlVal);
     lControlVal = static_cast<long>(0.9f*(1 << 16));
     setControl(V4L2_CID_SATURATION, lControlVal);
      */
     // Request mmap-able capture buffers
     mzero(req);
     req.count  = V4L_STREAMBUFS;
     req.type   = V4L2_BUF_TYPE_VIDEO_CAPTURE;
     req.memory = V4L2_MEMORY_MMAP;
     if(!xioctl(VIDIOC_REQBUFS, &req, "Request Buffers") || req.count != V4L_STREAMBUFS) {
         printf("REQBUFS returned error, count %d\n", req.count);
         return(false);
     }
     // set up individual buffers
     mzero(img,V4L_STREAMBUFS);
     mzero(tempbuf);
     tempbuf.type   = V4L2_BUF_TYPE_VIDEO_CAPTURE;
     tempbuf.memory = V4L2_MEMORY_MMAP;
     for(unsigned i=0; i<req.count; i++){
         tempbuf.index = i;
         if(!xioctl(VIDIOC_QUERYBUF, &tempbuf, "Allocate query buffer")) {
             printf("QUERYBUF returned error, '%s'\n", szDevice);
             return(false);
         }
         img[i].index = i;
         img[i].length = tempbuf.length;
         img[i].data = static_cast<unsigned char*>(
               mmap(NULL, tempbuf.length, PROT_READ | PROT_WRITE, MAP_SHARED,
                    pollset.fd, tempbuf.m.offset));
         if(img[i].data == MAP_FAILED){
             printf("mmap() returned error %d (%s)\n",errno,strerror(errno));
             return(false);
         }
     }
     //enqueue buffer that we just memmapped/allocated
     for(unsigned i=0; i<req.count; i++){
         tempbuf.index = i;
         if(!enqueueBuffer(tempbuf)){
             printf("Error queueing initial buffers, '%s'\n", szDevice);
             return(false);
         }
     }
     //start actual stream
     v4l2_buf_type type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
     return xioctl(VIDIOC_STREAMON, &type, "StreamOn");
 }
bool GlobalV4Linstance::stopStreaming ()
Definition at line 416 of file capturev4l.cpp.
References velocity.pid_::i, and V4L_STREAMBUFS.
Referenced by CaptureV4L::cleanup(), and CaptureV4L::startCapture().
 {
     bool bSuccess = false;
     if(pollset.fd != -1){
         v4l2_buf_type type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
         bSuccess = xioctl(VIDIOC_STREAMOFF, &type, NULL);
         for(int i=0; i<V4L_STREAMBUFS; i++){
             if(img[i].data){
                 munmap(img[i].data, img[i].length);
                 img[i].data = NULL;
                 img[i].length = 0;
             }
         }
     }
     //don't close the stream just yet
     return bSuccess;
 }
void GlobalV4Linstance::unlock () inline private
Definition at line 148 of file capturev4l.h.
                   {
 #ifndef VDATA_NO_QT
         mutex.unlock();
 #else
         pthread_mutex_unlock();
 #endif
     }
bool GlobalV4Linstance::waitForFrame (int max_msec = 500) private
Definition at line 326 of file capturev4l.cpp.
 {
     if (pollset.fd==-1) return false;
     int n = poll(&pollset,1,max_msec);
     return(n==1 && (pollset.revents & POLLIN)!=0);
 }
bool GlobalV4Linstance::writeRgbPPM (GlobalV4Linstance::rgb * imgbuf, int width, int height, const char * filename) static
Definition at line 505 of file capturev4l.cpp.
Referenced by CaptureV4L::getFrame().
 {
     // open output file
     FILE *out = fopen(filename,"wb");
     if(!out) return(false);
     // write the image
     fprintf(out,"P6\n%d %d\n%d\n",width,height,255);
     int result=fwrite(imgbuf,3,width*height,out);
     (void)result; //get the compiler to shut up.
     return(fclose(out) == 0);
 }
bool GlobalV4Linstance::writeYuyvPPM (GlobalV4Linstance::yuyv * pSrc, int width, int height, const char * filename) static
Definition at line 494 of file capturev4l.cpp.
 {
     GlobalV4Linstance::rgb *bufrgb = NULL;
     if (!getImageRgb(pSrc, width,height,&bufrgb)) return false;
     int wrote;
     wrote = writeRgbPPM(bufrgb,width,height,filename);
     delete[](bufrgb);
     return(wrote > 0);
 }
int GlobalV4Linstance::xioctl (int fd, int request, void * data, const char * error_str) static private
Definition at line 214 of file capturev4l.cpp.
 {
     // try the ioctl, which should succeed in the common case
     int ret = ioctl(fd,request,data);
     if(ret >= 0) return(ret);
     // retry if we were interrupted (up to a few times)
     int n=0;
     while(ret!=0 && errno==EINTR && n<8){
         ret = ioctl(fd,request,data);
         n++;
     }
     // report error
     if(ret != 0 && error_str) {
         fprintf(stderr,"GlobalV4Linstance: %s returned %d (%s)\n",
                 error_str,ret,strerror(errno));
     }
     return(ret);
 }
bool GlobalV4Linstance::xioctl (int request, void * data, const char * error_str) private
Definition at line 208 of file capturev4l.cpp.
 {
     int ret = xioctl(pollset.fd,request,data, error_str);
     return (ret == 0);
 }
GlobalV4Linstance::rgb GlobalV4Linstance::yuv2rgb (GlobalV4Linstance::yuv p) static private
Definition at line 539 of file capturev4l.cpp.
References GlobalV4Linstance::rgb::blue, GVector::bound(), GlobalV4Linstance::rgb::green, GlobalV4Linstance::rgb::red, GlobalV4Linstance::yuv::u, v, GlobalV4Linstance::yuv::v, role._GoToPoint::y, and GlobalV4Linstance::yuv::y.
 {
     GlobalV4Linstance::rgb r;
     int y,u,v;
     y = p.y;
     u = p.v*2 - 255;
     v = p.u*2 - 255;
     r.red   = bound(y + u                     ,0,255);
     r.green = bound((int)(y - 0.51*u - 0.19*v),0,255);
     r.blue  = bound(y + v                     ,0,255);
     return(r);
 }
Friends And Related Function Documentation
friend class GlobalV4LinstanceManager friend
Definition at line 73 of file capturev4l.h.
Field Documentation
char GlobalV4Linstance::counter private
Definition at line 111 of file capturev4l.h.
Referenced by GlobalV4Linstance(), and ~GlobalV4Linstance().
image_t GlobalV4Linstance::img[3] private
Definition at line 114 of file capturev4l.h.
Referenced by GlobalV4Linstance().
QMutex GlobalV4Linstance::mutex protected
Definition at line 105 of file capturev4l.h.
Referenced by GlobalV4Linstance(), and ~GlobalV4Linstance().
pollfd GlobalV4Linstance::pollset private
Definition at line 110 of file capturev4l.h.
Referenced by GlobalV4Linstance().
char GlobalV4Linstance::szDevice[128] private
Definition at line 112 of file capturev4l.h.
Referenced by GlobalV4Linstance().
struct v4l2_buffer GlobalV4Linstance::tempbuf private
Definition at line 113 of file capturev4l.h.
The documentation for this class was generated from the following files:
ssl-vision/src/shared/capture/capturev4l.h
ssl-vision/src/shared/capture/capturev4l.cpp