Documentation: Debug_Circle Class Reference
Debug_Circle Class Reference
#include <sslDebug_Data.pb.h>
Public Member Functions
Debug_Circle ()
virtual ~Debug_Circle ()
Debug_Circle (const Debug_Circle &from)
Debug_Circle & operator= (const Debug_Circle &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Debug_Circle *other)
Debug_Circle * New () const PROTOBUF_FINAL
Debug_Circle * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const Debug_Circle &from)
void MergeFrom (const Debug_Circle &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_x () const
void clear_x ()
::google::protobuf::int32 x () const
void set_x (::google::protobuf::int32 value)
bool has_y () const
void clear_y ()
::google::protobuf::int32 y () const
void set_y (::google::protobuf::int32 value)
bool has_radius () const
void clear_radius ()
::google::protobuf::int32 radius () const
void set_radius (::google::protobuf::int32 value)
bool has_color () const
void clear_color ()
float color () const
void set_color (float value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Debug_Circle & default_instance ()
static const Debug_Circle * internal_default_instance ()
Static Public Attributes
static const int kXFieldNumber = 1
static const int kYFieldNumber = 2
static const int kRadiusFieldNumber = 3
static const int kColorFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (Debug_Circle *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_x ()
void clear_has_x ()
void set_has_y ()
void clear_has_y ()
void set_has_radius ()
void clear_has_radius ()
void set_has_color ()
void clear_has_color ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_sslDebug_5fData_2eproto ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::int32 x_
::google::protobuf::int32 y_
::google::protobuf::int32 radius_
float color_
Friends
void protobuf_InitDefaults_sslDebug_5fData_2eproto_impl ()
void protobuf_AddDesc_sslDebug_5fData_2eproto_impl ()
void protobuf_ShutdownFile_sslDebug_5fData_2eproto ()
Detailed Description
Definition at line 211 of file sslDebug_Data.pb.h.
Constructor & Destructor Documentation
Debug_Circle::Debug_Circle ()
virtual Debug_Circle::~Debug_Circle () virtual
Debug_Circle::Debug_Circle (const Debug_Circle & from)
Member Function Documentation
size_t Debug_Circle::ByteSizeLong () const
void Debug_Circle::Clear ()
void Debug_Circle::clear_color () inline
Definition at line 1069 of file sslDebug_Data.pb.h.
{
   color_ = 0;
   clear_has_color();
 }
void Debug_Circle::clear_has_color () inline private
Definition at line 1066 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000008u;
 }
void Debug_Circle::clear_has_radius () inline private
Definition at line 1042 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000004u;
 }
void Debug_Circle::clear_has_x () inline private
Definition at line 994 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void Debug_Circle::clear_has_y () inline private
Definition at line 1018 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000002u;
 }
void Debug_Circle::clear_radius () inline
Definition at line 1045 of file sslDebug_Data.pb.h.
{
   radius_ = 0;
   clear_has_radius();
 }
void Debug_Circle::clear_x () inline
Definition at line 997 of file sslDebug_Data.pb.h.
{
   x_ = 0;
   clear_has_x();
 }
void Debug_Circle::clear_y () inline
Definition at line 1021 of file sslDebug_Data.pb.h.
{
   y_ = 0;
   clear_has_y();
 }
float Debug_Circle::color () const inline
Definition at line 1073 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_Circle.color)
   return color_;
 }
void Debug_Circle::CopyFrom (const ::google::protobuf::Message & from)
void Debug_Circle::CopyFrom (const Debug_Circle & from)
static const Debug_Circle& Debug_Circle::default_instance () static
static const ::google::protobuf::Descriptor* Debug_Circle::descriptor () static
inline ::google::protobuf::Arena* Debug_Circle::GetArenaNoVirtual () const inline private
Definition at line 271 of file sslDebug_Data.pb.h.
{
     return NULL;
   }
int Debug_Circle::GetCachedSize () const inline
Definition at line 264 of file sslDebug_Data.pb.h.
References sslDebug_Data::_cached_size_, sslDebug_Data::InternalSwap(), sslDebug_Data::SetCachedSize(), sslDebug_Data::SharedCtor(), and sslDebug_Data::SharedDtor().
 { return _cached_size_; }
::google::protobuf::Metadata Debug_Circle::GetMetadata () const
bool Debug_Circle::has_color () const inline
Definition at line 1060 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool Debug_Circle::has_radius () const inline
Definition at line 1036 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool Debug_Circle::has_x () const inline
Definition at line 988 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool Debug_Circle::has_y () const inline
Definition at line 1012 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
static const Debug_Circle* Debug_Circle::internal_default_instance () inline static
Definition at line 234 of file sslDebug_Data.pb.h.
References _Debug_Circle_default_instance_, and sslDebug_Data::Swap().
{
     return reinterpret_cast<const Debug_Circle*>(
                &_Debug_Circle_default_instance_);
   }
::google::protobuf::uint8* Debug_Circle::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void Debug_Circle::InternalSwap (Debug_Circle * other) private
bool Debug_Circle::IsInitialized () const
void* Debug_Circle::MaybeArenaPtr () const inline private
Definition at line 274 of file sslDebug_Data.pb.h.
References sslDebug_Data::GetMetadata().
{
     return NULL;
   }
void Debug_Circle::MergeFrom (const ::google::protobuf::Message & from)
void Debug_Circle::MergeFrom (const Debug_Circle & from)
bool Debug_Circle::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
inline ::google::protobuf::UnknownFieldSet* Debug_Circle::mutable_unknown_fields () inline
Definition at line 227 of file sslDebug_Data.pb.h.
References sslDebug_Data::_internal_metadata_, sslDebug_Data::default_instance(), and sslDebug_Data::descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
Debug_Circle* Debug_Circle::New () const inline
Definition at line 243 of file sslDebug_Data.pb.h.
References sslDebug_Data::ByteSizeLong(), sslDebug_Data::Clear(), sslDebug_Data::CopyFrom(), sslDebug_Data::InternalSerializeWithCachedSizesToArray(), sslDebug_Data::IsInitialized(), sslDebug_Data::MergeFrom(), sslDebug_Data::MergePartialFromCodedStream(), sslDebug_Data::New(), New(), sslDebug_Data::SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
Debug_Circle* Debug_Circle::New (::google::protobuf::Arena * arena) const
Debug_Circle& Debug_Circle::operator= (const Debug_Circle & from) inline
Definition at line 218 of file sslDebug_Data.pb.h.
References sslDebug_Data::CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* Debug_Circle::protobuf_Offsets_sslDebug_5fData_2eproto () private
google::protobuf::int32 Debug_Circle::radius () const inline
Definition at line 1049 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_Circle.radius)
   return radius_;
 }
size_t Debug_Circle::RequiredFieldsByteSizeFallback () const private
void Debug_Circle::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* Debug_Circle::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 260 of file sslDebug_Data.pb.h.
References sslDebug_Data::InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void Debug_Circle::set_color (float value) inline
Definition at line 1077 of file sslDebug_Data.pb.h.
Referenced by CallbackDbg(), and main().
{
   set_has_color();
   color_ = value;
   // @@protoc_insertion_point(field_set:Debug_Circle.color)
 }
void Debug_Circle::set_has_color () inline private
Definition at line 1063 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000008u;
 }
void Debug_Circle::set_has_radius () inline private
Definition at line 1039 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000004u;
 }
void Debug_Circle::set_has_x () inline private
Definition at line 991 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000001u;
 }
void Debug_Circle::set_has_y () inline private
Definition at line 1015 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000002u;
 }
void Debug_Circle::set_radius (::google::protobuf::int32 value) inline
Definition at line 1053 of file sslDebug_Data.pb.h.
Referenced by CallbackDbg(), and main().
{
   set_has_radius();
   radius_ = value;
   // @@protoc_insertion_point(field_set:Debug_Circle.radius)
 }
void Debug_Circle::set_x (::google::protobuf::int32 value) inline
Definition at line 1005 of file sslDebug_Data.pb.h.
Referenced by CallbackDbg(), and main().
{
   set_has_x();
   x_ = value;
   // @@protoc_insertion_point(field_set:Debug_Circle.x)
 }
void Debug_Circle::set_y (::google::protobuf::int32 value) inline
Definition at line 1029 of file sslDebug_Data.pb.h.
Referenced by CallbackDbg(), and main().
{
   set_has_y();
   y_ = value;
   // @@protoc_insertion_point(field_set:Debug_Circle.y)
 }
void Debug_Circle::SetCachedSize (int size) const private
void Debug_Circle::SharedCtor () private
void Debug_Circle::SharedDtor () private
void Debug_Circle::Swap (Debug_Circle * other)
const ::google::protobuf::UnknownFieldSet& Debug_Circle::unknown_fields () const inline
Definition at line 223 of file sslDebug_Data.pb.h.
References sslDebug_Data::_internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
google::protobuf::int32 Debug_Circle::x () const inline
Definition at line 1001 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_Circle.x)
   return x_;
 }
google::protobuf::int32 Debug_Circle::y () const inline
Definition at line 1025 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_Circle.y)
   return y_;
 }
Friends And Related Function Documentation
void protobuf_AddDesc_sslDebug_5fData_2eproto_impl () friend
void protobuf_InitDefaults_sslDebug_5fData_2eproto_impl () friend
void protobuf_ShutdownFile_sslDebug_5fData_2eproto () friend
Field Documentation
int Debug_Circle::_cached_size_ mutable private
Definition at line 329 of file sslDebug_Data.pb.h.
::google::protobuf::internal::HasBits<1> Debug_Circle::_has_bits_ private
Definition at line 328 of file sslDebug_Data.pb.h.
::google::protobuf::internal::InternalMetadataWithArena Debug_Circle::_internal_metadata_ private
Definition at line 327 of file sslDebug_Data.pb.h.
float Debug_Circle::color_ private
Definition at line 333 of file sslDebug_Data.pb.h.
const int Debug_Circle::kColorFieldNumber = 4 static
Definition at line 309 of file sslDebug_Data.pb.h.
const int Debug_Circle::kRadiusFieldNumber = 3 static
Definition at line 302 of file sslDebug_Data.pb.h.
const int Debug_Circle::kXFieldNumber = 1 static
Definition at line 288 of file sslDebug_Data.pb.h.
const int Debug_Circle::kYFieldNumber = 2 static
Definition at line 295 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_Circle::radius_ private
Definition at line 332 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_Circle::x_ private
Definition at line 330 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_Circle::y_ private
Definition at line 331 of file sslDebug_Data.pb.h.
The documentation for this class was generated from the following file:
grsim_comm/include/proto/sslDebug_Data.pb.h