Documentation: CMVision::ColorRegionList Class Reference
CMVision::ColorRegionList Class Reference
#include <cmvision_region.h>
Public Member Functions
ColorRegionList (int _num_color_regions)
~ColorRegionList ()
const RegionLinkedList & getRegionList (int idx) const
RegionLinkedList * getColorRegionArrayPointer () const
int getNumColorRegions () const
Private Attributes
RegionLinkedList * color_regions
int num_color_regions
Detailed Description
Definition at line 158 of file cmvision_region.h.
Constructor & Destructor Documentation
CMVision::ColorRegionList::ColorRegionList (int _num_color_regions) inline
Definition at line 163 of file cmvision_region.h.
{
     color_regions=new RegionLinkedList[_num_color_regions];
     num_color_regions=_num_color_regions;
   }
CMVision::ColorRegionList::~ColorRegionList () inline
Definition at line 167 of file cmvision_region.h.
                      {
     delete[] color_regions;
   }
Member Function Documentation
RegionLinkedList* CMVision::ColorRegionList::getColorRegionArrayPointer () const inline
Definition at line 174 of file cmvision_region.h.
Referenced by PluginVisualize::DrawBlobs(), PluginFindBlobs::process(), CMVision::RegionProcessing::separateRegions(), and CMVision::RegionProcessing::sortRegions().
{
     return color_regions;
   }
int CMVision::ColorRegionList::getNumColorRegions () const inline
Definition at line 177 of file cmvision_region.h.
Referenced by PluginDetectRobots::buildRegionTree(), PluginVisualize::DrawBlobs(), PluginFindBlobs::process(), CMVision::RegionProcessing::separateRegions(), and CMVision::RegionProcessing::sortRegions().
{
     return num_color_regions;
   }
const RegionLinkedList& CMVision::ColorRegionList::getRegionList (int idx) const inline
Definition at line 171 of file cmvision_region.h.
Referenced by PluginDetectRobots::buildRegionTree(), CMPattern::TeamDetector::findRobotsByModel(), CMPattern::TeamDetector::findRobotsByTeamMarkerOnly(), CMPattern::MultiPatternModel::loadSinglePatternImage(), and PluginDetectBalls::process().
{
     return color_regions[idx];
   }
Field Documentation
RegionLinkedList* CMVision::ColorRegionList::color_regions private
Definition at line 160 of file cmvision_region.h.
int CMVision::ColorRegionList::num_color_regions private
Definition at line 161 of file cmvision_region.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/cmvision/cmvision_region.h