Documentation: VarTypes::VarQWidget Class Reference
VarTypes::VarQWidget Class Reference
An Vartype for embedding QWidgets into the Var-tree.
#include <VarQWidget.h>
Public Member Functions
VarQWidget (string _name="", QWidget *default_val=0)
virtual ~VarQWidget ()
virtual void resetToDefault ()
virtual void printdebug () const
virtual VarTypeId getType () const
virtual QWidget * getQWidget () const
virtual bool setQWidget (QWidget *val)
virtual QWidget * createEditor (const VarItemDelegate *delegate, QWidget *parent, const QStyleOptionViewItem &option)
virtual void setEditorData (const VarItemDelegate *delegate, QWidget *editor) const
virtual void setModelData (const VarItemDelegate *delegate, QWidget *editor)
Public Member Functions inherited from VarTypes::VarType
VarType (string name="")
virtual ~VarType ()
virtual vector< VarType * > getChildren () const
virtual void deleteAllChildren ()
virtual void setName (string name)
Set the string label of this node.
virtual string getName () const
Get the string label of this node.
virtual VarTypeFlag getFlags () const
virtual void setFlags (VarTypeFlag f)
virtual void addFlags (VarTypeFlag f)
virtual void removeFlags (VarTypeFlag f)
virtual bool areFlagsSet (VarTypeFlag f) const
VarType * findChild (string label) const
void writeXML (XMLNode &parent, bool blind_append=true)
Write the contents of this VarType node to an XMLNode.
void readXML (XMLNode &us)
Let this VarType node load the contents of an XMLNode.
virtual QSize sizeHint (const VarItemDelegate *delegate, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void paint (const VarItemDelegate *delegate, QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * clone () const
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual string getString () const
Get a human-readable string representation of this node's data.
virtual bool setString (const string &val)
Set this node's data to some string representation.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
virtual bool hasValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Protected Attributes
QWidget * _val
Protected Attributes inherited from VarTypes::VarType
QMutex * _mutex
VarTypeFlag _flags
string _name
Additional Inherited Members
Public Slots inherited from VarTypes::VarType
void mvcEditCompleted ()
A slot to receive signals from a model-view system that editing of this item was just completed.
Signals inherited from VarTypes::VarType
void hasChanged (VarType *)
void wasEdited (VarType *)
void XMLwasRead (VarType *)
This signal is triggered if data was written from an xml node.
void XMLwasWritten (VarType *)
This signal is triggered if data was written to an xml node.
Static Public Member Functions inherited from VarTypes::VarType
static void deleteAllVarChildren (XMLNode &node)
Clear an XMLNode's list of children.
static vector< VarType * > readChildrenHelper (XMLNode &parent, vector< VarType * > existing_children, bool only_update_existing, bool blind_append)
A helper function to read a list of children from XML and convert it to a vector of VarType nodes.
Protected Member Functions inherited from VarTypes::VarType
virtual void lock () const
virtual void unlock () const
virtual void changed ()
virtual void updateAttributes (XMLNode &us) const
virtual void updateText (XMLNode &us) const
virtual void updateChildren (XMLNode &us) const
virtual void readAttributes (XMLNode &us)
virtual void readText (XMLNode &us)
virtual void readChildren (XMLNode &us)
virtual void loadExternal ()
Static Protected Member Functions inherited from VarTypes::VarType
static string fixString (const char *cst)
static string intToString (int val)
static string doubleToString (double val)
static XMLNode findOrAppendChild (XMLNode &parent, string key, string val)
Detailed Description
An Vartype for embedding QWidgets into the Var-tree.
Author
Stefan Zickler, (C) 2008
See also
VarQWidget
VarTypes.h
Note, that this class breaks the model/view paradigm as it will construct a single qwidget which will be shared between viewers and not separate instances for each viewer. This is fine if you only have a single viewer, but will likely create problems if you have multiple ones.
To avoid these issues, it is better to simply inherit VarType and create a qwidget factory by reimplementing VarType's createEditor(...);
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 52 of file VarQWidget.h.
Constructor & Destructor Documentation
VarTypes::VarQWidget::VarQWidget (string _name = "", QWidget * default_val = 0) inline
Definition at line 60 of file VarQWidget.h.
References VarTypes::VarType::_flags, VarTypes::VarType::changed(), and VarTypes::VARTYPE_FLAG_PERSISTENT.
                                                          : VarType (_name)
     {
       _val=default_val;
       _flags |= VARTYPE_FLAG_PERSISTENT;
       changed();
     }
virtual VarTypes::VarQWidget::~VarQWidget () inline virtual
Definition at line 67 of file VarQWidget.h.
References _val.
{
       if (_val!=0) delete _val;
     }
Member Function Documentation
virtual QWidget* VarTypes::VarQWidget::createEditor (const VarItemDelegate * delegate, QWidget * parent, const QStyleOptionViewItem & option) inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 91 of file VarQWidget.h.
References getQWidget().
{
       (void)delegate;
       (void)parent;
       (void)option;
       QWidget * w=getQWidget();
       if (w!=0) w->setParent(parent);
       return w;
     };
virtual QWidget* VarTypes::VarQWidget::getQWidget () const inline virtual
Definition at line 82 of file VarQWidget.h.
References _val.
Referenced by createEditor().
{
       return _val;
     };
virtual VarTypeId VarTypes::VarQWidget::getType () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 80 of file VarQWidget.h.
References VarTypes::VARTYPE_ID_QWIDGET.
 { return VARTYPE_ID_QWIDGET; };
virtual void VarTypes::VarQWidget::printdebug () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 75 of file VarQWidget.h.
     {
       printf("QWidget pointer: %p\n",_val);
     }
virtual void VarTypes::VarQWidget::resetToDefault () inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 71 of file VarQWidget.h.
     {
     }
virtual void VarTypes::VarQWidget::setEditorData (const VarItemDelegate * delegate, QWidget * editor) const inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 99 of file VarQWidget.h.
{
       (void)delegate;
       (void)editor;
     };
virtual void VarTypes::VarQWidget::setModelData (const VarItemDelegate * delegate, QWidget * editor) inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 103 of file VarQWidget.h.
{
       (void)delegate;
       (void)editor;
     }
virtual bool VarTypes::VarQWidget::setQWidget (QWidget * val) inline virtual
Definition at line 86 of file VarQWidget.h.
References VarTypes::VarType::changed().
 { if (val!=_val) { _val=val; changed(); return true;} else { return false; }; };
Field Documentation
QWidget* VarTypes::VarQWidget::_val protected
Definition at line 57 of file VarQWidget.h.
Referenced by getQWidget(), and ~VarQWidget().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/vartypes/primitives/VarQWidget.h