Documentation: PluginNeuralColorCalib Class Reference
PluginNeuralColorCalib Class Reference
#include <plugin_neuralcolorcalib.h>
Public Member Functions
PluginNeuralColorCalib (FrameBuffer *_buffer, YUVLUT *_lut, LUTChannelMode _mode=LUTChannelMode_Numeric)
~PluginNeuralColorCalib ()
ProcessResult process (FrameData *data, RenderOptions *options)
int TrainNeuralopenCV ()
int RunNeuralopenCV (double *input)
void Clear ()
virtual VarList * getSettings ()
virtual string getName ()
virtual QWidget * getControlWidget ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
Public Member Functions inherited from VisionPlugin
VisionPlugin (FrameBuffer *_buffer)
virtual ~VisionPlugin ()
FrameBuffer * getFrameBuffer () const
this functions provides convenient access to the ring-buffer
void lock ()
void unlock ()
virtual bool isEnabled () const
virtual void setEnabled (bool enable)
virtual bool isVisualize () const
virtual void setVisualize (bool enable)
virtual bool isSharedAmongStacks () const
virtual void setSharedAmongStacks (bool enable)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual void postProcess (FrameData *data, RenderOptions *options)
virtual QWidget * getVisualizationWidget ()
virtual void closeWidgets ()
virtual QList< QAction * > actions ()
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
void setTimeProcessing (double val)
void setTimePostProcessing (double val)
double getTimeProcessing ()
double getTimePostProcessing ()
Data Fields
bool isNetSet
int n_samples
int epochs
Protected Member Functions
void mouseEvent (QMouseEvent *event, pixelloc loc)
void CopyNeuraltoLUT ()
Protected Attributes
YUVLUT * lut
VarList * settings
NeuroWidget * lutw
LUTChannelMode mode
bool continuing_undo
CvANN_MLP * neuronet
CvMat * realinput
CvMat * netout
std::vector< double > * neuro_trainingset
std::vector< double > * neuro_targset
Protected Attributes inherited from VisionPlugin
QMutex mutex
bool enabled
bool visualize
bool shared
FrameBuffer * buffer
double time_proc
double time_post
Additional Inherited Members
Public Slots inherited from VisionPlugin
void slotKeyPressEvent (QKeyEvent *event)
Detailed Description
Definition at line 34 of file plugin_neuralcolorcalib.h.
Constructor & Destructor Documentation
PluginNeuralColorCalib::PluginNeuralColorCalib (FrameBuffer * _buffer, YUVLUT * _lut, LUTChannelMode _mode = LUTChannelMode_Numeric)
Definition at line 87 of file plugin_neuralcolorcalib.cpp.
References continuing_undo, isNetSet, lut, lutw, mode, n_samples, netout, neuro_targset, neuro_trainingset, neuronet, realinput, settings, sizeHidLayer, sizeInputLayer, and sizeOutLayer.
                                                                                                          : VisionPlugin(_buffer)
 {
     mode=_mode;
     lut=_lut;
     lutw=0;
     settings=new VarList("Neural Calibrator");
     continuing_undo = false;
     int layersinfo[sizeInputLayer]={sizeInputLayer,sizeHidLayer,sizeOutLayer};
     CvMat layer_sizes= cvMat(1,3,CV_32SC1,layersinfo);
     neuronet = new CvANN_MLP(&layer_sizes,CvANN_MLP::SIGMOID_SYM,1,1);
     //variables used by OpenCV algorithm RunNeuralopenCV
     realinput = cvCreateMat(1,3,CV_64F);
     netout = cvCreateMat(1,sizeOutLayer,CV_64F);
     //
     isNetSet=false;
     n_samples=0;
     neuro_trainingset = new std::vector<double>;
     neuro_targset = new std::vector<double>;
 }
PluginNeuralColorCalib::~PluginNeuralColorCalib ()
Definition at line 146 of file plugin_neuralcolorcalib.cpp.
References settings.
 {
     delete settings;
 }
Member Function Documentation
void PluginNeuralColorCalib::Clear ()
Definition at line 246 of file plugin_neuralcolorcalib.cpp.
References isNetSet, n_samples, neuro_targset, and neuro_trainingset.
Referenced by process().
{
     n_samples=0;
     neuro_trainingset->resize(0);
     neuro_targset->resize(0);
     isNetSet=false;
 }
void PluginNeuralColorCalib::CopyNeuraltoLUT () protected
Definition at line 221 of file plugin_neuralcolorcalib.cpp.
References isNetSet, LUT3D::lock(), lut, RunNeuralopenCV(), LUT3D::set(), LUT3D::unlock(), v, LUT3D::X_SHIFT, role._GoToPoint::y, LUT3D::Y_SHIFT, and LUT3D::Z_SHIFT.
Referenced by process().
{
     double input[3];
     int output;
     if (isNetSet)
     {
         lut->lock();
         for (int y = 0; y <= 255; y+= (0x1 << lut->X_SHIFT)) {
             for (int u = 0; u <= 255; u+= (0x1 << lut->Y_SHIFT)) {
                 for (int v = 0; v <= 255; v+= (0x1 << lut->Z_SHIFT)) {
                     input[0]= (double)y;
                     input[1]= (double)u;
                     input[2]= (double)v;
                     output = RunNeuralopenCV(input);
                     if (output== -1)
                         output = 0;
                     lut->set(y,u,v,output); //Writes values to the camera's LUT table
                 }
             }
         }
         lut->unlock();
     }
 }
QWidget * PluginNeuralColorCalib::getControlWidget () virtual
Reimplemented from VisionPlugin.
Definition at line 151 of file plugin_neuralcolorcalib.cpp.
References lut, lutw, and mode.
{
     if (lutw==0) {
         lutw=new NeuroWidget(lut,mode);
     //    connect(lutw->getGLLUTWidget(),SIGNAL(signalKeyPressEvent(QKeyEvent *)),this, SLOT(slotKeyPressEvent(QKeyEvent *)));
     }
     return (QWidget *)lutw;
 }
string PluginNeuralColorCalib::getName () virtual
Reimplemented from VisionPlugin.
Definition at line 142 of file plugin_neuralcolorcalib.cpp.
{
     return "Neural Calib";
 }
VarList * PluginNeuralColorCalib::getSettings () virtual
Reimplemented from VisionPlugin.
Definition at line 138 of file plugin_neuralcolorcalib.cpp.
References settings.
{
     return settings;
 }
void PluginNeuralColorCalib::keyPressEvent (QKeyEvent * event) virtual
Reimplemented from VisionPlugin.
Definition at line 253 of file plugin_neuralcolorcalib.cpp.
{
     event->accept();
 }
void PluginNeuralColorCalib::mouseEvent (QMouseEvent * event, pixelloc loc) protected
Definition at line 159 of file plugin_neuralcolorcalib.cpp.
References kalman_filter::color, COLOR_RGB8, COLOR_YUV422_UYVY, COLOR_YUV444, Colors::colorFormatToString(), bot_comm::frame, RawImage::getColorFormat(), RawImage::getData(), VisionPlugin::getFrameBuffer(), RawImage::getHeight(), NeuroWidget::getStateChannel(), RawImage::getWidth(), lutw, n_samples, neuro_targset, neuro_trainingset, Conversions::rgb2yuv(), NeuroWidget::setSamplesLabel(), sizeOutLayer, ColorYUV< num, fmt >::u, ColorUYVY< num, fmt >::u, ColorYUV< num, fmt >::v, ColorUYVY< num, fmt >::v, FrameData::video, pixelloc::x, pixelloc::y, ColorYUV< num, fmt >::y, ColorUYVY< num, fmt >::y1, and ColorUYVY< num, fmt >::y2.
Referenced by mousePressEvent().
{
     QTabWidget* tabw = (QTabWidget*) lutw->parentWidget()->parentWidget();
     if (tabw->currentWidget() == lutw) {
         if (event->buttons()==Qt::LeftButton && lutw->getStateChannel() != -1) {
             FrameBuffer * rb=getFrameBuffer();
             if (rb!=0) {
                 rb->lockRead();
                 int idx=rb->curRead();
                 FrameData * frame = rb->getPointer(idx);
                 if (loc.x < frame->video.getWidth() && loc.y < frame->video.getHeight() && loc.x >=0 && loc.y >=0) {
                     if (frame->video.getWidth() > 1 && frame->video.getHeight() > 1) {
                         yuv color;
                         //if converting entire image then blanking is not needed
                         ColorFormat source_format=frame->video.getColorFormat();
                         if (source_format==COLOR_RGB8) {
                             //plain copy of data
                             rgbImage img(frame->video);
                             color=Conversions::rgb2yuv(img.getPixel(loc.x,loc.y));
                         } else if (source_format==COLOR_YUV444) {
                             yuvImage img(frame->video);
                             color=img.getPixel(loc.x,loc.y);
                         } else if (source_format==COLOR_YUV422_UYVY) {
                             uyvy color2 = *((uyvy*)(frame->video.getData() + (sizeof(uyvy) * (((loc.y * (frame->video.getWidth())) + loc.x) / 2))));
                             color.u=color2.u;
                             color.v=color2.v;
                             if ((loc.x % 2)==0) {
                                 color.y=color2.y1;
                             } else {
                                 color.y=color2.y2;
                             }
                         } else {
                             //blank it:
                             fprintf(stderr,"Unable to pick color from frame of format: %s\n",Colors::colorFormatToString(source_format).c_str());
                             fprintf(stderr,"Currently supported are rgb8, yuv444, and yuv422 (UYVY).\n");
                             fprintf(stderr,"(Feel free to add more conversions to plugin_neuralcolorcalib.cpp).\n");
                         }
                         neuro_trainingset->push_back( (double)color.y );
                         neuro_trainingset->push_back( (double)color.u );
                         neuro_trainingset->push_back( (double)color.v );
                         for (int j=0; j < sizeOutLayer; j++){
                             if (lutw->getStateChannel() == j)
                                 neuro_targset->push_back( lutw->getStateChannel() );
                             else
                                 neuro_targset->push_back( 0 );
                         }
                         this->n_samples++;
                         lutw->setSamplesLabel(this->n_samples);
                     }
                 }
                 rb->unlockRead();
             }
             event->accept();
         }
     }
     else
         event->ignore();
 }
void PluginNeuralColorCalib::mouseMoveEvent (QMouseEvent * event, pixelloc loc) virtual
Reimplemented from VisionPlugin.
Definition at line 267 of file plugin_neuralcolorcalib.cpp.
{
     event->ignore();
 }
void PluginNeuralColorCalib::mousePressEvent (QMouseEvent * event, pixelloc loc) virtual
Reimplemented from VisionPlugin.
Definition at line 257 of file plugin_neuralcolorcalib.cpp.
References mouseEvent().
{
     mouseEvent(event,loc);
 }
void PluginNeuralColorCalib::mouseReleaseEvent (QMouseEvent * event, pixelloc loc) virtual
Reimplemented from VisionPlugin.
Definition at line 261 of file plugin_neuralcolorcalib.cpp.
{
     event->accept();
     //continuing_undo = false;
     //mouseEvent(event,loc);
 }
ProcessResult PluginNeuralColorCalib::process (FrameData * data, RenderOptions * options) virtual
Reimplemented from VisionPlugin.
Definition at line 111 of file plugin_neuralcolorcalib.cpp.
References Clear(), CopyNeuraltoLUT(), epochs, isNetSet, lutw, n_samples, NeuroWidget::pending_clear, NeuroWidget::pending_loadnn, NeuroWidget::pending_train, ProcessingOk, NeuroWidget::setSamplesLabel(), NeuroWidget::setStatusLabel(), and TrainNeuralopenCV().
{
     if (lutw->pending_loadnn){
         if (isNetSet){
             this->CopyNeuraltoLUT();
             lutw->setStatusLabel("LUT Updated");
         }
         lutw->pending_loadnn = false;
     }else if(lutw->pending_train){
         if (n_samples > 0){
             this->epochs = this->TrainNeuralopenCV();
             lutw->setStatusLabel("NN trained in "+ QString::number(epochs)+" epochs");
         }else{
             lutw->setStatusLabel("Please capture samples.");
         }
         lutw->pending_train = false;
     }else if(lutw->pending_clear){
         this->Clear();
         lutw->setSamplesLabel(this->n_samples);
         lutw->setStatusLabel("NN training data cleared");
         lutw->pending_clear = false;
     }
     return ProcessingOk;
 }
int PluginNeuralColorCalib::RunNeuralopenCV (double * input)
Definition at line 64 of file plugin_neuralcolorcalib.cpp.
References isNetSet, netout, neuronet, realinput, and sizeOutLayer.
Referenced by CopyNeuraltoLUT().
{
     double tmpout=0,maxout=0;
     int noutput=0;
     if (isNetSet){ //if network is not trained do nothing
             cvSetData(realinput,input,sizeof(double)*3); //inserts the input into the OpenCV matrix format
             neuronet->predict (realinput,netout); //call prediction (ask the output) of the object for a given input.
             for (int j=0; j<sizeOutLayer; j++){ //inserts the output in an output array
                 tmpout=CV_MAT_ELEM(*netout,double,0,j);
                 if  (tmpout > maxout){
                     noutput=j;
                     maxout=tmpout;
                 }
             }
             return noutput;
     }
     else
         return -1;
 }
int PluginNeuralColorCalib::TrainNeuralopenCV ()
Definition at line 32 of file plugin_neuralcolorcalib.cpp.
References isNetSet, n_samples, neuro_targset, neuro_trainingset, neuronet, sizeInputLayer, sizeOutLayer, and role._GoToPoint::target.
Referenced by process().
{
     CvANN_MLP_TrainParams netparams;
     CvTermCriteria term_crit;
     double * training;
     training= new double [n_samples * sizeInputLayer * sizeInputLayer];
     double * target;
     target= new double [n_samples * sizeOutLayer * sizeOutLayer];
     CvMat trainin;
     CvMat trainout;
     int interactions_ran=0;
     term_crit.max_iter =1000; //maximum number of epochs to train
     term_crit.epsilon  = 1e-5; //maximum tolerance to errors of the network during training
     term_crit.type = CV_TERMCRIT_ITER + CV_TERMCRIT_EPS; //indicates training stops either when performance or max. epochs is reached
     netparams=CvANN_MLP_TrainParams(term_crit, CvANN_MLP_TrainParams::BACKPROP,0.1,0.1); //specifies learning algorithm, learning rate and momentum
     for (unsigned int n=0; n<neuro_trainingset->size(); n++){
         training[n] = neuro_trainingset->at(n);
     }
     for (unsigned int n=0; n<neuro_targset->size(); n++){
         target[n] = neuro_targset->at(n);
     }
     trainin = cvMat(n_samples,3,CV_64F,training);
     trainout = cvMat(n_samples,sizeOutLayer,CV_64F,target);
     interactions_ran = neuronet->train (&trainin, &trainout,0,0,netparams,0); //call training functions of the object
     isNetSet=true;
     return interactions_ran;
 }
Field Documentation
bool PluginNeuralColorCalib::continuing_undo protected
Definition at line 40 of file plugin_neuralcolorcalib.h.
Referenced by PluginNeuralColorCalib().
int PluginNeuralColorCalib::epochs
Definition at line 56 of file plugin_neuralcolorcalib.h.
Referenced by process().
bool PluginNeuralColorCalib::isNetSet
Definition at line 54 of file plugin_neuralcolorcalib.h.
Referenced by Clear(), CopyNeuraltoLUT(), PluginNeuralColorCalib(), process(), RunNeuralopenCV(), and TrainNeuralopenCV().
YUVLUT* PluginNeuralColorCalib::lut protected
Definition at line 36 of file plugin_neuralcolorcalib.h.
Referenced by CopyNeuraltoLUT(), getControlWidget(), and PluginNeuralColorCalib().
NeuroWidget* PluginNeuralColorCalib::lutw protected
Definition at line 38 of file plugin_neuralcolorcalib.h.
Referenced by getControlWidget(), mouseEvent(), PluginNeuralColorCalib(), and process().
LUTChannelMode PluginNeuralColorCalib::mode protected
Definition at line 39 of file plugin_neuralcolorcalib.h.
Referenced by getControlWidget(), and PluginNeuralColorCalib().
int PluginNeuralColorCalib::n_samples
Definition at line 55 of file plugin_neuralcolorcalib.h.
Referenced by Clear(), mouseEvent(), PluginNeuralColorCalib(), process(), and TrainNeuralopenCV().
CvMat* PluginNeuralColorCalib::netout protected
Definition at line 45 of file plugin_neuralcolorcalib.h.
Referenced by PluginNeuralColorCalib(), and RunNeuralopenCV().
std::vector<double>* PluginNeuralColorCalib::neuro_targset protected
Definition at line 47 of file plugin_neuralcolorcalib.h.
Referenced by Clear(), mouseEvent(), PluginNeuralColorCalib(), and TrainNeuralopenCV().
std::vector<double>* PluginNeuralColorCalib::neuro_trainingset protected
Definition at line 46 of file plugin_neuralcolorcalib.h.
Referenced by Clear(), mouseEvent(), PluginNeuralColorCalib(), and TrainNeuralopenCV().
CvANN_MLP* PluginNeuralColorCalib::neuronet protected
Definition at line 42 of file plugin_neuralcolorcalib.h.
Referenced by PluginNeuralColorCalib(), RunNeuralopenCV(), and TrainNeuralopenCV().
CvMat* PluginNeuralColorCalib::realinput protected
Definition at line 44 of file plugin_neuralcolorcalib.h.
Referenced by PluginNeuralColorCalib(), and RunNeuralopenCV().
VarList* PluginNeuralColorCalib::settings protected
Definition at line 37 of file plugin_neuralcolorcalib.h.
Referenced by getSettings(), PluginNeuralColorCalib(), and ~PluginNeuralColorCalib().
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/plugin_neuralcolorcalib.h
ssl-vision/src/app/plugins/plugin_neuralcolorcalib.cpp