Documentation: Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame Class Reference
Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame Class Reference
Data Structures
class Builder
Public Member Functions
SSL_DetectionFrame getDefaultInstanceForType ()
boolean hasFrameNumber ()
int getFrameNumber ()
boolean hasTCapture ()
double getTCapture ()
boolean hasTSent ()
double getTSent ()
boolean hasCameraId ()
int getCameraId ()
java.util.List< MessagesRobocupSslDetection.SSL_DetectionBall > getBallsList ()
java.util.List<?extends MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder > getBallsOrBuilderList ()
int getBallsCount ()
MessagesRobocupSslDetection.SSL_DetectionBall getBalls (int index)
MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder getBallsOrBuilder (int index)
java.util.List< MessagesRobocupSslDetection.SSL_DetectionRobot > getRobotsYellowList ()
java.util.List<?extends MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder > getRobotsYellowOrBuilderList ()
int getRobotsYellowCount ()
MessagesRobocupSslDetection.SSL_DetectionRobot getRobotsYellow (int index)
MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder getRobotsYellowOrBuilder (int index)
java.util.List< MessagesRobocupSslDetection.SSL_DetectionRobot > getRobotsBlueList ()
java.util.List<?extends MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder > getRobotsBlueOrBuilderList ()
int getRobotsBlueCount ()
MessagesRobocupSslDetection.SSL_DetectionRobot getRobotsBlue (int index)
MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder getRobotsBlueOrBuilder (int index)
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static SSL_DetectionFrame getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static MessagesRobocupSslDetection.SSL_DetectionFrame parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslDetection.SSL_DetectionFrame parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslDetection.SSL_DetectionFrame parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslDetection.SSL_DetectionFrame parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslDetection.SSL_DetectionFrame parseFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionFrame parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionFrame parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionFrame parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionFrame parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionFrame parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (MessagesRobocupSslDetection.SSL_DetectionFrame prototype)
Static Public Attributes
static final int FRAME_NUMBER_FIELD_NUMBER = 1
static final int T_CAPTURE_FIELD_NUMBER = 2
static final int T_SENT_FIELD_NUMBER = 3
static final int CAMERA_ID_FIELD_NUMBER = 4
static final int BALLS_FIELD_NUMBER = 5
static final int ROBOTS_YELLOW_FIELD_NUMBER = 6
static final int ROBOTS_BLUE_FIELD_NUMBER = 7
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
SSL_DetectionFrame (Builder builder)
SSL_DetectionFrame (boolean noInit)
void initFields ()
Private Attributes
int bitField0_
int frameNumber_
double tCapture_
double tSent_
int cameraId_
java.util.List< MessagesRobocupSslDetection.SSL_DetectionBall > balls_
java.util.List< MessagesRobocupSslDetection.SSL_DetectionRobot > robotsYellow_
java.util.List< MessagesRobocupSslDetection.SSL_DetectionRobot > robotsBlue_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final SSL_DetectionFrame defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 1557 of file MessagesRobocupSslDetection.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.SSL_DetectionFrame (Builder builder) inline private
Definition at line 1561 of file MessagesRobocupSslDetection.java.
{
       super(builder);
     }
Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.SSL_DetectionFrame (boolean noInit) inline private
Definition at line 1564 of file MessagesRobocupSslDetection.java.
 {}
Member Function Documentation
MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getBalls (int index) inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1639 of file MessagesRobocupSslDetection.java.
{
       return balls_.get(index);
     }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getBallsCount () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1636 of file MessagesRobocupSslDetection.java.
{
       return balls_.size();
     }
java.util.List<MessagesRobocupSslDetection.SSL_DetectionBall> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getBallsList () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1629 of file MessagesRobocupSslDetection.java.
{
       return balls_;
     }
MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getBallsOrBuilder (int index) inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1642 of file MessagesRobocupSslDetection.java.
                    {
       return balls_.get(index);
     }
java.util.List<? extends MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getBallsOrBuilderList () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1633 of file MessagesRobocupSslDetection.java.
{
       return balls_;
     }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getCameraId () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1622 of file MessagesRobocupSslDetection.java.
{
       return cameraId_;
     }
static SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance () inline static
Definition at line 1567 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.clear(), Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.clear(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.clearDetection(), Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.clearFrame(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getDefaultInstanceForType(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.initFields(), Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.initFields(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeDetection(), Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrame(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom().
{
       return defaultInstance;
     }
SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstanceForType () inline
Definition at line 1571 of file MessagesRobocupSslDetection.java.
{
       return defaultInstance;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDescriptor () inline static
Definition at line 1576 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.internal_static_SSL_DetectionFrame_descriptor.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getDescriptorForType().
{
       return MessagesRobocupSslDetection.internal_static_SSL_DetectionFrame_descriptor;
     }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getFrameNumber () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1592 of file MessagesRobocupSslDetection.java.
{
       return frameNumber_;
     }
MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getRobotsBlue (int index) inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1681 of file MessagesRobocupSslDetection.java.
{
       return robotsBlue_.get(index);
     }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getRobotsBlueCount () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1678 of file MessagesRobocupSslDetection.java.
{
       return robotsBlue_.size();
     }
java.util.List<MessagesRobocupSslDetection.SSL_DetectionRobot> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getRobotsBlueList () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1671 of file MessagesRobocupSslDetection.java.
{
       return robotsBlue_;
     }
MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getRobotsBlueOrBuilder (int index) inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1684 of file MessagesRobocupSslDetection.java.
                    {
       return robotsBlue_.get(index);
     }
java.util.List<? extends MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getRobotsBlueOrBuilderList () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1675 of file MessagesRobocupSslDetection.java.
{
       return robotsBlue_;
     }
MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getRobotsYellow (int index) inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1660 of file MessagesRobocupSslDetection.java.
{
       return robotsYellow_.get(index);
     }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getRobotsYellowCount () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1657 of file MessagesRobocupSslDetection.java.
{
       return robotsYellow_.size();
     }
java.util.List<MessagesRobocupSslDetection.SSL_DetectionRobot> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getRobotsYellowList () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1650 of file MessagesRobocupSslDetection.java.
{
       return robotsYellow_;
     }
MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getRobotsYellowOrBuilder (int index) inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1663 of file MessagesRobocupSslDetection.java.
                    {
       return robotsYellow_.get(index);
     }
java.util.List<? extends MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getRobotsYellowOrBuilderList () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1654 of file MessagesRobocupSslDetection.java.
{
       return robotsYellow_;
     }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getSerializedSize () inline
Definition at line 1769 of file MessagesRobocupSslDetection.java.
References velocity.pid_.i.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeUInt32Size(1, frameNumber_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         size += com.google.protobuf.CodedOutputStream
           .computeDoubleSize(2, tCapture_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         size += com.google.protobuf.CodedOutputStream
           .computeDoubleSize(3, tSent_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         size += com.google.protobuf.CodedOutputStream
           .computeUInt32Size(4, cameraId_);
       }
       for (int i = 0; i < balls_.size(); i++) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(5, balls_.get(i));
       }
       for (int i = 0; i < robotsYellow_.size(); i++) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(6, robotsYellow_.get(i));
       }
       for (int i = 0; i < robotsBlue_.size(); i++) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(7, robotsBlue_.get(i));
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
double Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getTCapture () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1602 of file MessagesRobocupSslDetection.java.
{
       return tCapture_;
     }
double Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getTSent () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1612 of file MessagesRobocupSslDetection.java.
{
       return tSent_;
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.hasCameraId () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1619 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000008) == 0x00000008);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.hasFrameNumber () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1589 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.hasTCapture () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1599 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000002) == 0x00000002);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.hasTSent () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder.
Definition at line 1609 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000004) == 0x00000004);
     }
void Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.initFields () inline private
Definition at line 1689 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.getRobotsBlueFieldBuilder().
{
       frameNumber_ = 0;
       tCapture_ = 0D;
       tSent_ = 0D;
       cameraId_ = 0;
       balls_ = java.util.Collections.emptyList();
       robotsYellow_ = java.util.Collections.emptyList();
       robotsBlue_ = java.util.Collections.emptyList();
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.internalGetFieldAccessorTable () inline protected
Definition at line 1581 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.internal_static_SSL_DetectionFrame_fieldAccessorTable.
{
       return MessagesRobocupSslDetection.internal_static_SSL_DetectionFrame_fieldAccessorTable;
     }
final boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.isInitialized () inline
Definition at line 1699 of file MessagesRobocupSslDetection.java.
References velocity.pid_.i.
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (!hasFrameNumber()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasTCapture()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasTSent()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasCameraId()) {
         memoizedIsInitialized = 0;
         return false;
       }
       for (int i = 0; i < getBallsCount(); i++) {
         if (!getBalls(i).isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       for (int i = 0; i < getRobotsYellowCount(); i++) {
         if (!getRobotsYellow(i).isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       for (int i = 0; i < getRobotsBlueCount(); i++) {
         if (!getRobotsBlue(i).isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder () inline static
Definition at line 1881 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.create().
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeDetection(), Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrame(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom(), and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrom().
 { return Builder.create(); }
static Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder (MessagesRobocupSslDetection.SSL_DetectionFrame prototype) inline static
Definition at line 1883 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilderForType () inline
Definition at line 1882 of file MessagesRobocupSslDetection.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 1889 of file MessagesRobocupSslDetection.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 1848 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1857 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1814 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1819 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1826 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1830 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 1837 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1841 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 1868 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1873 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.toBuilder () inline
Definition at line 1886 of file MessagesRobocupSslDetection.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 1809 of file MessagesRobocupSslDetection.java.
{
       return super.writeReplace();
     }
void Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 1741 of file MessagesRobocupSslDetection.java.
References velocity.pid_.i.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeUInt32(1, frameNumber_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         output.writeDouble(2, tCapture_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         output.writeDouble(3, tSent_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         output.writeUInt32(4, cameraId_);
       }
       for (int i = 0; i < balls_.size(); i++) {
         output.writeMessage(5, balls_.get(i));
       }
       for (int i = 0; i < robotsYellow_.size(); i++) {
         output.writeMessage(6, robotsYellow_.get(i));
       }
       for (int i = 0; i < robotsBlue_.size(); i++) {
         output.writeMessage(7, robotsBlue_.get(i));
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
java.util.List<MessagesRobocupSslDetection.SSL_DetectionBall> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.balls_ private
Definition at line 1628 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.BALLS_FIELD_NUMBER = 5 static
Definition at line 1627 of file MessagesRobocupSslDetection.java.
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.bitField0_ private
Definition at line 1585 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.CAMERA_ID_FIELD_NUMBER = 4 static
Definition at line 1617 of file MessagesRobocupSslDetection.java.
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.cameraId_ private
Definition at line 1618 of file MessagesRobocupSslDetection.java.
final SSL_DetectionFrame Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.defaultInstance static private
Definition at line 1566 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.FRAME_NUMBER_FIELD_NUMBER = 1 static
Definition at line 1587 of file MessagesRobocupSslDetection.java.
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.frameNumber_ private
Definition at line 1588 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.buildPartial().
byte Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.memoizedIsInitialized = -1 private
Definition at line 1698 of file MessagesRobocupSslDetection.java.
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.memoizedSerializedSize = -1 private
Definition at line 1768 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.ROBOTS_BLUE_FIELD_NUMBER = 7 static
Definition at line 1669 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.ROBOTS_YELLOW_FIELD_NUMBER = 6 static
Definition at line 1648 of file MessagesRobocupSslDetection.java.
java.util.List<MessagesRobocupSslDetection.SSL_DetectionRobot> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.robotsBlue_ private
Definition at line 1670 of file MessagesRobocupSslDetection.java.
java.util.List<MessagesRobocupSslDetection.SSL_DetectionRobot> Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.robotsYellow_ private
Definition at line 1649 of file MessagesRobocupSslDetection.java.
final long Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.serialVersionUID = 0L static private
Definition at line 1807 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.T_CAPTURE_FIELD_NUMBER = 2 static
Definition at line 1597 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.T_SENT_FIELD_NUMBER = 3 static
Definition at line 1607 of file MessagesRobocupSslDetection.java.
double Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.tCapture_ private
Definition at line 1598 of file MessagesRobocupSslDetection.java.
double Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.tSent_ private
Definition at line 1608 of file MessagesRobocupSslDetection.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslDetection.java