Documentation: SSL_DetectionFrame Class Reference
SSL_DetectionFrame Class Reference
#include <messages_robocup_ssl_detection.pb.h>
Public Member Functions
SSL_DetectionFrame ()
virtual ~SSL_DetectionFrame ()
SSL_DetectionFrame (const SSL_DetectionFrame &from)
SSL_DetectionFrame & operator= (const SSL_DetectionFrame &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_DetectionFrame *other)
SSL_DetectionFrame * New () const PROTOBUF_FINAL
SSL_DetectionFrame * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_DetectionFrame &from)
void MergeFrom (const SSL_DetectionFrame &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_frame_number () const
void clear_frame_number ()
::google::protobuf::uint32 frame_number () const
void set_frame_number (::google::protobuf::uint32 value)
bool has_t_capture () const
void clear_t_capture ()
double t_capture () const
void set_t_capture (double value)
bool has_t_sent () const
void clear_t_sent ()
double t_sent () const
void set_t_sent (double value)
bool has_camera_id () const
void clear_camera_id ()
::google::protobuf::uint32 camera_id () const
void set_camera_id (::google::protobuf::uint32 value)
int balls_size () const
void clear_balls ()
const ::SSL_DetectionBall & balls (int index) const
::SSL_DetectionBall * mutable_balls (int index)
::SSL_DetectionBall * add_balls ()
::google::protobuf::RepeatedPtrField< ::SSL_DetectionBall > * mutable_balls ()
const ::google::protobuf::RepeatedPtrField< ::SSL_DetectionBall > & balls () const
int robots_yellow_size () const
void clear_robots_yellow ()
const ::SSL_DetectionRobot & robots_yellow (int index) const
::SSL_DetectionRobot * mutable_robots_yellow (int index)
::SSL_DetectionRobot * add_robots_yellow ()
::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot > * mutable_robots_yellow ()
const ::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot > & robots_yellow () const
int robots_blue_size () const
void clear_robots_blue ()
const ::SSL_DetectionRobot & robots_blue (int index) const
::SSL_DetectionRobot * mutable_robots_blue (int index)
::SSL_DetectionRobot * add_robots_blue ()
::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot > * mutable_robots_blue ()
const ::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot > & robots_blue () const
SSL_DetectionFrame ()
virtual ~SSL_DetectionFrame ()
SSL_DetectionFrame (const SSL_DetectionFrame &from)
SSL_DetectionFrame & operator= (const SSL_DetectionFrame &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_DetectionFrame *other)
SSL_DetectionFrame * New () const PROTOBUF_FINAL
SSL_DetectionFrame * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_DetectionFrame &from)
void MergeFrom (const SSL_DetectionFrame &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
int balls_size () const
void clear_balls ()
const ::SSL_DetectionBall & balls (int index) const
::SSL_DetectionBall * mutable_balls (int index)
::SSL_DetectionBall * add_balls ()
::google::protobuf::RepeatedPtrField< ::SSL_DetectionBall > * mutable_balls ()
const ::google::protobuf::RepeatedPtrField< ::SSL_DetectionBall > & balls () const
int robots_yellow_size () const
void clear_robots_yellow ()
const ::SSL_DetectionRobot & robots_yellow (int index) const
::SSL_DetectionRobot * mutable_robots_yellow (int index)
::SSL_DetectionRobot * add_robots_yellow ()
::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot > * mutable_robots_yellow ()
const ::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot > & robots_yellow () const
int robots_blue_size () const
void clear_robots_blue ()
const ::SSL_DetectionRobot & robots_blue (int index) const
::SSL_DetectionRobot * mutable_robots_blue (int index)
::SSL_DetectionRobot * add_robots_blue ()
::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot > * mutable_robots_blue ()
const ::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot > & robots_blue () const
bool has_t_capture () const
void clear_t_capture ()
double t_capture () const
void set_t_capture (double value)
bool has_frame_number () const
void clear_frame_number ()
::google::protobuf::uint32 frame_number () const
void set_frame_number (::google::protobuf::uint32 value)
bool has_camera_id () const
void clear_camera_id ()
::google::protobuf::uint32 camera_id () const
void set_camera_id (::google::protobuf::uint32 value)
bool has_t_sent () const
void clear_t_sent ()
double t_sent () const
void set_t_sent (double value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_DetectionFrame & default_instance ()
static const SSL_DetectionFrame * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_DetectionFrame & default_instance ()
static void InitAsDefaultInstance ()
static const SSL_DetectionFrame * internal_default_instance ()
Static Public Attributes
static const int kFrameNumberFieldNumber = 1
static const int kTCaptureFieldNumber = 2
static const int kTSentFieldNumber = 3
static const int kCameraIdFieldNumber = 4
static const int kBallsFieldNumber = 5
static const int kRobotsYellowFieldNumber = 6
static const int kRobotsBlueFieldNumber = 7
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_DetectionFrame *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_frame_number ()
void clear_has_frame_number ()
void set_has_t_capture ()
void clear_has_t_capture ()
void set_has_t_sent ()
void clear_has_t_sent ()
void set_has_camera_id ()
void clear_has_camera_id ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5fdetection_2eproto ()
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_DetectionFrame *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_frame_number ()
void clear_has_frame_number ()
void set_has_t_capture ()
void clear_has_t_capture ()
void set_has_t_sent ()
void clear_has_t_sent ()
void set_has_camera_id ()
void clear_has_camera_id ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::InitDefaultsSSL_DetectionFrameImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::RepeatedPtrField< ::SSL_DetectionBall > balls_
::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot > robots_yellow_
::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot > robots_blue_
double t_capture_
::google::protobuf::uint32 frame_number_
::google::protobuf::uint32 camera_id_
double t_sent_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::TableStruct
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto_impl ()
void protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_impl ()
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fdetection_2eproto ()
void swap (SSL_DetectionFrame &a, SSL_DetectionFrame &b)
Detailed Description
Definition at line 379 of file messages_robocup_ssl_detection.pb.h.
Constructor & Destructor Documentation
SSL_DetectionFrame::SSL_DetectionFrame ()
virtual SSL_DetectionFrame::~SSL_DetectionFrame () virtual
SSL_DetectionFrame::SSL_DetectionFrame (const SSL_DetectionFrame & from)
SSL_DetectionFrame::SSL_DetectionFrame ()
virtual SSL_DetectionFrame::~SSL_DetectionFrame () virtual
SSL_DetectionFrame::SSL_DetectionFrame (const SSL_DetectionFrame & from)
Member Function Documentation
SSL_DetectionBall * SSL_DetectionFrame::add_balls () inline
Definition at line 1034 of file messages_robocup_ssl_detection.pb.h.
Referenced by SSLWorld::generatePacket(), and PluginDetectBalls::process().
{
   // @@protoc_insertion_point(field_add:SSL_DetectionFrame.balls)
   return balls_.Add();
 }
::SSL_DetectionBall* SSL_DetectionFrame::add_balls ()
SSL_DetectionRobot * SSL_DetectionFrame::add_robots_blue () inline
Definition at line 1094 of file messages_robocup_ssl_detection.pb.h.
Referenced by SSLWorld::generatePacket().
{
   // @@protoc_insertion_point(field_add:SSL_DetectionFrame.robots_blue)
   return robots_blue_.Add();
 }
::SSL_DetectionRobot* SSL_DetectionFrame::add_robots_blue ()
SSL_DetectionRobot * SSL_DetectionFrame::add_robots_yellow () inline
Definition at line 1064 of file messages_robocup_ssl_detection.pb.h.
Referenced by SSLWorld::generatePacket().
{
   // @@protoc_insertion_point(field_add:SSL_DetectionFrame.robots_yellow)
   return robots_yellow_.Add();
 }
::SSL_DetectionRobot* SSL_DetectionFrame::add_robots_yellow ()
const ::SSL_DetectionBall & SSL_DetectionFrame::balls (int index) const inline
Definition at line 1026 of file messages_robocup_ssl_detection.pb.h.
Referenced by ViewUpdateThread::execute(), main(), and GLSoccerView::updateDetection().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionFrame.balls)
   return balls_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::SSL_DetectionBall > & SSL_DetectionFrame::balls () const inline
Definition at line 1044 of file messages_robocup_ssl_detection.pb.h.
{
   // @@protoc_insertion_point(field_list:SSL_DetectionFrame.balls)
   return balls_;
 }
const ::SSL_DetectionBall& SSL_DetectionFrame::balls (int index) const
const ::google::protobuf::RepeatedPtrField< ::SSL_DetectionBall >& SSL_DetectionFrame::balls () const
int SSL_DetectionFrame::balls_size () const inline
Definition at line 1020 of file messages_robocup_ssl_detection.pb.h.
Referenced by ViewUpdateThread::execute(), main(), and GLSoccerView::updateDetection().
{
   return balls_.size();
 }
int SSL_DetectionFrame::balls_size () const
size_t SSL_DetectionFrame::ByteSizeLong () const
size_t SSL_DetectionFrame::ByteSizeLong () const
google::protobuf::uint32 SSL_DetectionFrame::camera_id () const inline
Definition at line 1009 of file messages_robocup_ssl_detection.pb.h.
Referenced by ViewUpdateThread::execute(), main(), GLSoccerView::updateDetection(), and SoccerView::UpdateRobots().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionFrame.camera_id)
   return camera_id_;
 }
::google::protobuf::uint32 SSL_DetectionFrame::camera_id () const
void SSL_DetectionFrame::Clear ()
void SSL_DetectionFrame::Clear ()
void SSL_DetectionFrame::clear_balls () inline
Definition at line 1023 of file messages_robocup_ssl_detection.pb.h.
Referenced by PluginDetectBalls::process().
{
   balls_.Clear();
 }
void SSL_DetectionFrame::clear_balls ()
void SSL_DetectionFrame::clear_camera_id () inline
Definition at line 1005 of file messages_robocup_ssl_detection.pb.h.
{
   camera_id_ = 0u;
   clear_has_camera_id();
 }
void SSL_DetectionFrame::clear_camera_id ()
void SSL_DetectionFrame::clear_frame_number () inline
Definition at line 933 of file messages_robocup_ssl_detection.pb.h.
{
   frame_number_ = 0u;
   clear_has_frame_number();
 }
void SSL_DetectionFrame::clear_frame_number ()
void SSL_DetectionFrame::clear_has_camera_id () inline private
Definition at line 1002 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] &= ~0x00000004u;
 }
void SSL_DetectionFrame::clear_has_camera_id () private
void SSL_DetectionFrame::clear_has_frame_number () inline private
Definition at line 930 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] &= ~0x00000002u;
 }
void SSL_DetectionFrame::clear_has_frame_number () private
void SSL_DetectionFrame::clear_has_t_capture () inline private
Definition at line 954 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void SSL_DetectionFrame::clear_has_t_capture () private
void SSL_DetectionFrame::clear_has_t_sent () inline private
Definition at line 978 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] &= ~0x00000008u;
 }
void SSL_DetectionFrame::clear_has_t_sent () private
void SSL_DetectionFrame::clear_robots_blue () inline
Definition at line 1083 of file messages_robocup_ssl_detection.pb.h.
Referenced by PluginDetectRobots::process().
{
   robots_blue_.Clear();
 }
void SSL_DetectionFrame::clear_robots_blue ()
void SSL_DetectionFrame::clear_robots_yellow () inline
Definition at line 1053 of file messages_robocup_ssl_detection.pb.h.
Referenced by PluginDetectRobots::process().
{
   robots_yellow_.Clear();
 }
void SSL_DetectionFrame::clear_robots_yellow ()
void SSL_DetectionFrame::clear_t_capture () inline
Definition at line 957 of file messages_robocup_ssl_detection.pb.h.
{
   t_capture_ = 0;
   clear_has_t_capture();
 }
void SSL_DetectionFrame::clear_t_capture ()
void SSL_DetectionFrame::clear_t_sent () inline
Definition at line 981 of file messages_robocup_ssl_detection.pb.h.
{
   t_sent_ = 0;
   clear_has_t_sent();
 }
void SSL_DetectionFrame::clear_t_sent ()
void SSL_DetectionFrame::CopyFrom (const ::google::protobuf::Message & from)
Referenced by RoboCupSSLServer::open(), RoboCupSSLServer::send(), and RoboCupSSLServer::sendLegacyMessage().
void SSL_DetectionFrame::CopyFrom (const SSL_DetectionFrame & from)
void SSL_DetectionFrame::CopyFrom (const ::google::protobuf::Message & from)
void SSL_DetectionFrame::CopyFrom (const SSL_DetectionFrame & from)
static const SSL_DetectionFrame& SSL_DetectionFrame::default_instance () static
static const SSL_DetectionFrame& SSL_DetectionFrame::default_instance () static
static const ::google::protobuf::Descriptor* SSL_DetectionFrame::descriptor () static
static const ::google::protobuf::Descriptor* SSL_DetectionFrame::descriptor () static
google::protobuf::uint32 SSL_DetectionFrame::frame_number () const inline
Definition at line 937 of file messages_robocup_ssl_detection.pb.h.
Referenced by main().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionFrame.frame_number)
   return frame_number_;
 }
::google::protobuf::uint32 SSL_DetectionFrame::frame_number () const
inline ::google::protobuf::Arena* SSL_DetectionFrame::GetArenaNoVirtual () const inline private
Definition at line 439 of file messages_robocup_ssl_detection.pb.h.
{
     return NULL;
   }
inline ::google::protobuf::Arena* SSL_DetectionFrame::GetArenaNoVirtual () const inline private
Definition at line 500 of file messages_robocup_ssl_detection.pb.h.
{
     return NULL;
   }
int SSL_DetectionFrame::GetCachedSize () const inline
Definition at line 432 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_cached_size_, SSL_DetectionBall::InternalSwap(), SSL_DetectionBall::SetCachedSize(), SSL_DetectionBall::SharedCtor(), and SSL_DetectionBall::SharedDtor().
 { return _cached_size_; }
int SSL_DetectionFrame::GetCachedSize () const inline
Definition at line 493 of file messages_robocup_ssl_detection.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata SSL_DetectionFrame::GetMetadata () const
::google::protobuf::Metadata SSL_DetectionFrame::GetMetadata () const
bool SSL_DetectionFrame::has_camera_id () const inline
Definition at line 996 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool SSL_DetectionFrame::has_camera_id () const
bool SSL_DetectionFrame::has_frame_number () const inline
Definition at line 924 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool SSL_DetectionFrame::has_frame_number () const
bool SSL_DetectionFrame::has_t_capture () const inline
Definition at line 948 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool SSL_DetectionFrame::has_t_capture () const
bool SSL_DetectionFrame::has_t_sent () const inline
Definition at line 972 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool SSL_DetectionFrame::has_t_sent () const
static void SSL_DetectionFrame::InitAsDefaultInstance () static
static const SSL_DetectionFrame* SSL_DetectionFrame::internal_default_instance () inline static
Definition at line 402 of file messages_robocup_ssl_detection.pb.h.
References _SSL_DetectionFrame_default_instance_, and SSL_DetectionBall::Swap().
Referenced by SSL_WrapperPacket::detection(), and Log_Frame::frame().
{
     return reinterpret_cast<const SSL_DetectionFrame*>(
                &_SSL_DetectionFrame_default_instance_);
   }
static const SSL_DetectionFrame* SSL_DetectionFrame::internal_default_instance () inline static
Definition at line 462 of file messages_robocup_ssl_detection.pb.h.
References _SSL_DetectionFrame_default_instance_.
{
     return reinterpret_cast<const SSL_DetectionFrame*>(
                &_SSL_DetectionFrame_default_instance_);
   }
::google::protobuf::uint8* SSL_DetectionFrame::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
::google::protobuf::uint8* SSL_DetectionFrame::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void SSL_DetectionFrame::InternalSwap (SSL_DetectionFrame * other) private
void SSL_DetectionFrame::InternalSwap (SSL_DetectionFrame * other) private
bool SSL_DetectionFrame::IsInitialized () const
bool SSL_DetectionFrame::IsInitialized () const
void* SSL_DetectionFrame::MaybeArenaPtr () const inline private
Definition at line 442 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::GetMetadata().
{
     return NULL;
   }
void* SSL_DetectionFrame::MaybeArenaPtr () const inline private
Definition at line 503 of file messages_robocup_ssl_detection.pb.h.
{
     return NULL;
   }
void SSL_DetectionFrame::MergeFrom (const ::google::protobuf::Message & from)
void SSL_DetectionFrame::MergeFrom (const SSL_DetectionFrame & from)
void SSL_DetectionFrame::MergeFrom (const ::google::protobuf::Message & from)
void SSL_DetectionFrame::MergeFrom (const SSL_DetectionFrame & from)
bool SSL_DetectionFrame::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
bool SSL_DetectionFrame::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
SSL_DetectionBall * SSL_DetectionFrame::mutable_balls (int index) inline
Definition at line 1030 of file messages_robocup_ssl_detection.pb.h.
{
   // @@protoc_insertion_point(field_mutable:SSL_DetectionFrame.balls)
   return balls_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::SSL_DetectionBall > * SSL_DetectionFrame::mutable_balls () inline
Definition at line 1039 of file messages_robocup_ssl_detection.pb.h.
{
   // @@protoc_insertion_point(field_mutable_list:SSL_DetectionFrame.balls)
   return &balls_;
 }
::SSL_DetectionBall* SSL_DetectionFrame::mutable_balls (int index)
::google::protobuf::RepeatedPtrField< ::SSL_DetectionBall >* SSL_DetectionFrame::mutable_balls ()
SSL_DetectionRobot * SSL_DetectionFrame::mutable_robots_blue (int index) inline
Definition at line 1090 of file messages_robocup_ssl_detection.pb.h.
Referenced by PluginDetectRobots::process(), and PluginDetectBalls::process().
{
   // @@protoc_insertion_point(field_mutable:SSL_DetectionFrame.robots_blue)
   return robots_blue_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::SSL_DetectionRobot > * SSL_DetectionFrame::mutable_robots_blue () inline
Definition at line 1099 of file messages_robocup_ssl_detection.pb.h.
{
   // @@protoc_insertion_point(field_mutable_list:SSL_DetectionFrame.robots_blue)
   return &robots_blue_;
 }
::SSL_DetectionRobot* SSL_DetectionFrame::mutable_robots_blue (int index)
::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot >* SSL_DetectionFrame::mutable_robots_blue ()
SSL_DetectionRobot * SSL_DetectionFrame::mutable_robots_yellow (int index) inline
Definition at line 1060 of file messages_robocup_ssl_detection.pb.h.
Referenced by PluginDetectRobots::process(), and PluginDetectBalls::process().
{
   // @@protoc_insertion_point(field_mutable:SSL_DetectionFrame.robots_yellow)
   return robots_yellow_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::SSL_DetectionRobot > * SSL_DetectionFrame::mutable_robots_yellow () inline
Definition at line 1069 of file messages_robocup_ssl_detection.pb.h.
{
   // @@protoc_insertion_point(field_mutable_list:SSL_DetectionFrame.robots_yellow)
   return &robots_yellow_;
 }
::SSL_DetectionRobot* SSL_DetectionFrame::mutable_robots_yellow (int index)
::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot >* SSL_DetectionFrame::mutable_robots_yellow ()
inline ::google::protobuf::UnknownFieldSet* SSL_DetectionFrame::mutable_unknown_fields () inline
Definition at line 395 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_internal_metadata_, SSL_DetectionBall::default_instance(), and SSL_DetectionBall::descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
inline ::google::protobuf::UnknownFieldSet* SSL_DetectionFrame::mutable_unknown_fields () inline
Definition at line 454 of file messages_robocup_ssl_detection.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
SSL_DetectionFrame* SSL_DetectionFrame::New () const inline
Definition at line 411 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::ByteSizeLong(), SSL_DetectionBall::Clear(), SSL_DetectionBall::CopyFrom(), SSL_DetectionBall::InternalSerializeWithCachedSizesToArray(), SSL_DetectionBall::IsInitialized(), SSL_DetectionBall::MergeFrom(), SSL_DetectionBall::MergePartialFromCodedStream(), SSL_DetectionBall::New(), New(), SSL_DetectionBall::SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_DetectionFrame* SSL_DetectionFrame::New (::google::protobuf::Arena * arena) const
SSL_DetectionFrame* SSL_DetectionFrame::New () const inline
Definition at line 476 of file messages_robocup_ssl_detection.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_DetectionFrame* SSL_DetectionFrame::New (::google::protobuf::Arena * arena) const
SSL_DetectionFrame& SSL_DetectionFrame::operator= (const SSL_DetectionFrame & from) inline
Definition at line 386 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
SSL_DetectionFrame& SSL_DetectionFrame::operator= (const SSL_DetectionFrame & from) inline
Definition at line 432 of file messages_robocup_ssl_detection.pb.h.
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* SSL_DetectionFrame::protobuf_Offsets_messages_5frobocup_5fssl_5fdetection_2eproto () private
size_t SSL_DetectionFrame::RequiredFieldsByteSizeFallback () const private
size_t SSL_DetectionFrame::RequiredFieldsByteSizeFallback () const private
const ::SSL_DetectionRobot & SSL_DetectionFrame::robots_blue (int index) const inline
Definition at line 1086 of file messages_robocup_ssl_detection.pb.h.
Referenced by main(), GLSoccerView::updateDetection(), and SoccerView::UpdateRobots().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionFrame.robots_blue)
   return robots_blue_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::SSL_DetectionRobot > & SSL_DetectionFrame::robots_blue () const inline
Definition at line 1104 of file messages_robocup_ssl_detection.pb.h.
{
   // @@protoc_insertion_point(field_list:SSL_DetectionFrame.robots_blue)
   return robots_blue_;
 }
const ::SSL_DetectionRobot& SSL_DetectionFrame::robots_blue (int index) const
const ::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot >& SSL_DetectionFrame::robots_blue () const
int SSL_DetectionFrame::robots_blue_size () const inline
Definition at line 1080 of file messages_robocup_ssl_detection.pb.h.
Referenced by main(), PluginDetectBalls::process(), GLSoccerView::updateDetection(), and SoccerView::UpdateRobots().
{
   return robots_blue_.size();
 }
int SSL_DetectionFrame::robots_blue_size () const
const ::SSL_DetectionRobot & SSL_DetectionFrame::robots_yellow (int index) const inline
Definition at line 1056 of file messages_robocup_ssl_detection.pb.h.
Referenced by main(), GLSoccerView::updateDetection(), and SoccerView::UpdateRobots().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionFrame.robots_yellow)
   return robots_yellow_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::SSL_DetectionRobot > & SSL_DetectionFrame::robots_yellow () const inline
Definition at line 1074 of file messages_robocup_ssl_detection.pb.h.
{
   // @@protoc_insertion_point(field_list:SSL_DetectionFrame.robots_yellow)
   return robots_yellow_;
 }
const ::SSL_DetectionRobot& SSL_DetectionFrame::robots_yellow (int index) const
const ::google::protobuf::RepeatedPtrField< ::SSL_DetectionRobot >& SSL_DetectionFrame::robots_yellow () const
int SSL_DetectionFrame::robots_yellow_size () const inline
Definition at line 1050 of file messages_robocup_ssl_detection.pb.h.
Referenced by main(), PluginDetectBalls::process(), GLSoccerView::updateDetection(), and SoccerView::UpdateRobots().
{
   return robots_yellow_.size();
 }
int SSL_DetectionFrame::robots_yellow_size () const
void SSL_DetectionFrame::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void SSL_DetectionFrame::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* SSL_DetectionFrame::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 428 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void SSL_DetectionFrame::set_camera_id (::google::protobuf::uint32 value) inline
Definition at line 1013 of file messages_robocup_ssl_detection.pb.h.
Referenced by SSLWorld::generatePacket(), PluginSSLNetworkOutput::process(), and PluginLegacySSLNetworkOutput::process().
{
   set_has_camera_id();
   camera_id_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionFrame.camera_id)
 }
void SSL_DetectionFrame::set_camera_id (::google::protobuf::uint32 value)
void SSL_DetectionFrame::set_frame_number (::google::protobuf::uint32 value) inline
Definition at line 941 of file messages_robocup_ssl_detection.pb.h.
Referenced by SSLWorld::generatePacket(), PluginSSLNetworkOutput::process(), and PluginLegacySSLNetworkOutput::process().
{
   set_has_frame_number();
   frame_number_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionFrame.frame_number)
 }
void SSL_DetectionFrame::set_frame_number (::google::protobuf::uint32 value)
void SSL_DetectionFrame::set_has_camera_id () inline private
Definition at line 999 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] |= 0x00000004u;
 }
void SSL_DetectionFrame::set_has_camera_id () private
void SSL_DetectionFrame::set_has_frame_number () inline private
Definition at line 927 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] |= 0x00000002u;
 }
void SSL_DetectionFrame::set_has_frame_number () private
void SSL_DetectionFrame::set_has_t_capture () inline private
Definition at line 951 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] |= 0x00000001u;
 }
void SSL_DetectionFrame::set_has_t_capture () private
void SSL_DetectionFrame::set_has_t_sent () inline private
Definition at line 975 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_has_bits_.
{
   _has_bits_[0] |= 0x00000008u;
 }
void SSL_DetectionFrame::set_has_t_sent () private
void SSL_DetectionFrame::set_t_capture (double value) inline
Definition at line 965 of file messages_robocup_ssl_detection.pb.h.
Referenced by SSLWorld::generatePacket(), PluginSSLNetworkOutput::process(), and PluginLegacySSLNetworkOutput::process().
{
   set_has_t_capture();
   t_capture_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionFrame.t_capture)
 }
void SSL_DetectionFrame::set_t_capture (double value)
void SSL_DetectionFrame::set_t_sent (double value) inline
Definition at line 989 of file messages_robocup_ssl_detection.pb.h.
Referenced by SSLWorld::generatePacket(), RoboCupSSLServer::open(), PluginSSLNetworkOutput::process(), PluginLegacySSLNetworkOutput::process(), and RoboCupSSLServer::sendLegacyMessage().
{
   set_has_t_sent();
   t_sent_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionFrame.t_sent)
 }
void SSL_DetectionFrame::set_t_sent (double value)
void SSL_DetectionFrame::SetCachedSize (int size) const private
void SSL_DetectionFrame::SetCachedSize (int size) const private
void SSL_DetectionFrame::SharedCtor () private
void SSL_DetectionFrame::SharedCtor () private
void SSL_DetectionFrame::SharedDtor () private
void SSL_DetectionFrame::SharedDtor () private
void SSL_DetectionFrame::Swap (SSL_DetectionFrame * other)
void SSL_DetectionFrame::Swap (SSL_DetectionFrame * other)
double SSL_DetectionFrame::t_capture () const inline
Definition at line 961 of file messages_robocup_ssl_detection.pb.h.
Referenced by ViewUpdateThread::execute(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionFrame.t_capture)
   return t_capture_;
 }
double SSL_DetectionFrame::t_capture () const
double SSL_DetectionFrame::t_sent () const inline
Definition at line 985 of file messages_robocup_ssl_detection.pb.h.
Referenced by main().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionFrame.t_sent)
   return t_sent_;
 }
double SSL_DetectionFrame::t_sent () const
const ::google::protobuf::UnknownFieldSet& SSL_DetectionFrame::unknown_fields () const inline
Definition at line 391 of file messages_robocup_ssl_detection.pb.h.
References SSL_DetectionBall::_internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
const ::google::protobuf::UnknownFieldSet& SSL_DetectionFrame::unknown_fields () const inline
Definition at line 451 of file messages_robocup_ssl_detection.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
SSL_DetectionFrame::void::protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::InitDefaultsSSL_DetectionFrameImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::TableStruct friend
Definition at line 602 of file messages_robocup_ssl_detection.pb.h.
void protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_impl () friend
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto_impl () friend
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fdetection_2eproto () friend
void swap (SSL_DetectionFrame & a, SSL_DetectionFrame & b) friend
Definition at line 470 of file messages_robocup_ssl_detection.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int SSL_DetectionFrame::_cached_size_ mutable private
Definition at line 533 of file messages_robocup_ssl_detection.pb.h.
google::protobuf::internal::HasBits< 1 > SSL_DetectionFrame::_has_bits_ private
Definition at line 532 of file messages_robocup_ssl_detection.pb.h.
google::protobuf::internal::InternalMetadataWithArena SSL_DetectionFrame::_internal_metadata_ private
Definition at line 531 of file messages_robocup_ssl_detection.pb.h.
google::protobuf::RepeatedPtrField<::SSL_DetectionBall > SSL_DetectionFrame::balls_ private
Definition at line 534 of file messages_robocup_ssl_detection.pb.h.
google::protobuf::uint32 SSL_DetectionFrame::camera_id_ private
Definition at line 539 of file messages_robocup_ssl_detection.pb.h.
google::protobuf::uint32 SSL_DetectionFrame::frame_number_ private
Definition at line 538 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionFrame::kBallsFieldNumber = 5 static
Definition at line 484 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionFrame::kCameraIdFieldNumber = 4 static
Definition at line 477 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionFrame::kFrameNumberFieldNumber = 1 static
Definition at line 456 of file messages_robocup_ssl_detection.pb.h.
PROTOBUF_CONSTEXPR int const SSL_DetectionFrame::kIndexInFileMessages static
Initial value:
=
    2
Definition at line 466 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionFrame::kRobotsBlueFieldNumber = 7 static
Definition at line 508 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionFrame::kRobotsYellowFieldNumber = 6 static
Definition at line 496 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionFrame::kTCaptureFieldNumber = 2 static
Definition at line 463 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionFrame::kTSentFieldNumber = 3 static
Definition at line 470 of file messages_robocup_ssl_detection.pb.h.
google::protobuf::RepeatedPtrField<::SSL_DetectionRobot > SSL_DetectionFrame::robots_blue_ private
Definition at line 536 of file messages_robocup_ssl_detection.pb.h.
google::protobuf::RepeatedPtrField<::SSL_DetectionRobot > SSL_DetectionFrame::robots_yellow_ private
Definition at line 535 of file messages_robocup_ssl_detection.pb.h.
double SSL_DetectionFrame::t_capture_ private
Definition at line 537 of file messages_robocup_ssl_detection.pb.h.
double SSL_DetectionFrame::t_sent_ private
Definition at line 540 of file messages_robocup_ssl_detection.pb.h.
The documentation for this class was generated from the following file:
grsim_comm/include/proto/messages_robocup_ssl_detection.pb.h