Documentation: PluginColorCalibration Class Reference
PluginColorCalibration Class Reference
#include <plugin_colorcalib.h>
Public Member Functions
PluginColorCalibration (FrameBuffer *_buffer, YUVLUT *_lut, LUTChannelMode _mode=LUTChannelMode_Numeric)
virtual VarList * getSettings ()
virtual string getName ()
~PluginColorCalibration ()
virtual QWidget * getControlWidget ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
Public Member Functions inherited from VisionPlugin
VisionPlugin (FrameBuffer *_buffer)
virtual ~VisionPlugin ()
FrameBuffer * getFrameBuffer () const
this functions provides convenient access to the ring-buffer
void lock ()
void unlock ()
virtual bool isEnabled () const
virtual void setEnabled (bool enable)
virtual bool isVisualize () const
virtual void setVisualize (bool enable)
virtual bool isSharedAmongStacks () const
virtual void setSharedAmongStacks (bool enable)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual ProcessResult process (FrameData *data, RenderOptions *options)
virtual void postProcess (FrameData *data, RenderOptions *options)
virtual QWidget * getVisualizationWidget ()
virtual void closeWidgets ()
virtual QList< QAction * > actions ()
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
void setTimeProcessing (double val)
void setTimePostProcessing (double val)
double getTimeProcessing ()
double getTimePostProcessing ()
Protected Member Functions
void mouseEvent (QMouseEvent *event, pixelloc loc)
Protected Attributes
YUVLUT * lut
VarList * settings
LUTWidget * lutw
LUTChannelMode mode
bool continuing_undo
Protected Attributes inherited from VisionPlugin
QMutex mutex
bool enabled
bool visualize
bool shared
FrameBuffer * buffer
double time_proc
double time_post
Additional Inherited Members
Public Slots inherited from VisionPlugin
void slotKeyPressEvent (QKeyEvent *event)
Detailed Description
Author
Stefan Zickler szick.nosp@m.ler@.nosp@m.cs.cm.nosp@m.u.ed.nosp@m.u
Definition at line 33 of file plugin_colorcalib.h.
Constructor & Destructor Documentation
PluginColorCalibration::PluginColorCalibration (FrameBuffer * _buffer, YUVLUT * _lut, LUTChannelMode _mode = LUTChannelMode_Numeric)
Definition at line 24 of file plugin_colorcalib.cpp.
References continuing_undo, lut, lutw, mode, and settings.
                                                                                                          : VisionPlugin(_buffer)
 {
   mode=_mode;
   lut=_lut;
   lutw=0;
   settings=new VarList("YUV Calibrator");
   continuing_undo = false;
 }
PluginColorCalibration::~PluginColorCalibration ()
Definition at line 41 of file plugin_colorcalib.cpp.
References settings.
 {
   delete settings;
 }
Member Function Documentation
QWidget * PluginColorCalibration::getControlWidget () virtual
Reimplemented from VisionPlugin.
Definition at line 46 of file plugin_colorcalib.cpp.
References LUTWidget::getGLLUTWidget(), lut, lutw, mode, and VisionPlugin::slotKeyPressEvent().
{
   if (lutw==0) {
     lutw=new LUTWidget(lut,mode);
     connect(lutw->getGLLUTWidget(),SIGNAL(signalKeyPressEvent(QKeyEvent *)),this, SLOT(slotKeyPressEvent(QKeyEvent *)));
   }
   return (QWidget *)lutw;
 }
string PluginColorCalibration::getName () virtual
Reimplemented from VisionPlugin.
Definition at line 37 of file plugin_colorcalib.cpp.
{
   return "YUV Calibration";
 }
VarList * PluginColorCalibration::getSettings () virtual
Reimplemented from VisionPlugin.
Definition at line 33 of file plugin_colorcalib.cpp.
References settings.
{
   return settings;
 }
void PluginColorCalibration::keyPressEvent (QKeyEvent * event) virtual
Reimplemented from VisionPlugin.
Definition at line 114 of file plugin_colorcalib.cpp.
References GLLUTWidget::clearSampler(), bot_comm::frame, VisionPlugin::getFrameBuffer(), LUTWidget::getGLLUTWidget(), lutw, LUTWidget::sampleImage(), and FrameData::video.
{
   if (event->key()==Qt::Key_I) {
     FrameBuffer * rb=getFrameBuffer();
     if (rb!=0) {
       rb->lockRead();
       int idx=rb->curRead();
       FrameData * frame = rb->getPointer(idx);
       lutw->sampleImage(frame->video);
       rb->unlockRead();
     }
     event->accept();
   } else if (event->key()==Qt::Key_C) {
     lutw->getGLLUTWidget()->clearSampler();
     event->accept();
   }
 }
void PluginColorCalibration::mouseEvent (QMouseEvent * event, pixelloc loc) protected
Definition at line 54 of file plugin_colorcalib.cpp.
References LUTWidget::add_del_Pixel(), kalman_filter::color, COLOR_RGB8, COLOR_YUV422_UYVY, COLOR_YUV444, Colors::colorFormatToString(), continuing_undo, bot_comm::frame, RawImage::getColorFormat(), RawImage::getData(), VisionPlugin::getFrameBuffer(), RawImage::getHeight(), RawImage::getWidth(), lutw, Conversions::rgb2yuv(), LUTWidget::samplePixel(), ColorYUV< num, fmt >::u, ColorUYVY< num, fmt >::u, ColorYUV< num, fmt >::v, ColorUYVY< num, fmt >::v, FrameData::video, pixelloc::x, pixelloc::y, ColorYUV< num, fmt >::y, ColorUYVY< num, fmt >::y1, and ColorUYVY< num, fmt >::y2.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
{
   QTabWidget* tabw = (QTabWidget*) lutw->parentWidget()->parentWidget();
   if (tabw->currentWidget() == lutw) {
     if (event->buttons()==Qt::LeftButton) {
       FrameBuffer * rb=getFrameBuffer();
       if (rb!=0) {
         rb->lockRead();
         int idx=rb->curRead();
         FrameData * frame = rb->getPointer(idx);
         if (loc.x < frame->video.getWidth() && loc.y < frame->video.getHeight() && loc.x >=0 && loc.y >=0) {
           if (frame->video.getWidth() > 1 && frame->video.getHeight() > 1) {
             yuv color;
             //if converting entire image then blanking is not needed
             ColorFormat source_format=frame->video.getColorFormat();
             if (source_format==COLOR_RGB8) {
               //plain copy of data
                 rgbImage img(frame->video);
               color=Conversions::rgb2yuv(img.getPixel(loc.x,loc.y));
             } else if (source_format==COLOR_YUV444) {
               yuvImage img(frame->video);
               color=img.getPixel(loc.x,loc.y);
             } else if (source_format==COLOR_YUV422_UYVY) {
               uyvy color2 = *((uyvy*)(frame->video.getData() + (sizeof(uyvy) * (((loc.y * (frame->video.getWidth())) + loc.x) / 2))));
               color.u=color2.u;
               color.v=color2.v;
               if ((loc.x % 2)==0) {
                 color.y=color2.y1;
               } else {
                 color.y=color2.y2;
               }
             } else {
               //blank it:
               fprintf(stderr,"Unable to pick color from frame of format: %s\n",Colors::colorFormatToString(source_format).c_str());
               fprintf(stderr,"Currently supported are rgb8, yuv444, and yuv422 (UYVY).\n");
               fprintf(stderr,"(Feel free to add more conversions to plugin_colorcalib.cpp).\n");
             }
             lutw->samplePixel(color);
             //img.setPixel(loc.x,loc.y,rgb(255,0,0));
             if (event->modifiers()!=Qt::NoModifier) {
               if(event->modifiers() & Qt::ShiftModifier) {          //modified 2/1/16, 'control' alone consumed
                 if(event->modifiers() & Qt::ControlModifier)        // by QT framework to move a window
                   lutw->add_del_Pixel(color, true, continuing_undo);
                 else
                   lutw->add_del_Pixel(color, false, continuing_undo);
               }
               continuing_undo = true;
             }
           }
         }
         rb->unlockRead();
       }
       event->accept();
     }
   }
   else
     event->ignore();
 }
void PluginColorCalibration::mouseMoveEvent (QMouseEvent * event, pixelloc loc) virtual
Reimplemented from VisionPlugin.
Definition at line 140 of file plugin_colorcalib.cpp.
References mouseEvent().
{
   mouseEvent(event,loc);
 }
void PluginColorCalibration::mousePressEvent (QMouseEvent * event, pixelloc loc) virtual
Reimplemented from VisionPlugin.
Definition at line 131 of file plugin_colorcalib.cpp.
References mouseEvent().
{
   mouseEvent(event,loc);
 }
void PluginColorCalibration::mouseReleaseEvent (QMouseEvent * event, pixelloc loc) virtual
Reimplemented from VisionPlugin.
Definition at line 135 of file plugin_colorcalib.cpp.
References continuing_undo, and mouseEvent().
{
   continuing_undo = false;
   mouseEvent(event,loc);
 }
Field Documentation
bool PluginColorCalibration::continuing_undo protected
Definition at line 39 of file plugin_colorcalib.h.
Referenced by mouseEvent(), mouseReleaseEvent(), and PluginColorCalibration().
YUVLUT* PluginColorCalibration::lut protected
Definition at line 35 of file plugin_colorcalib.h.
Referenced by getControlWidget(), and PluginColorCalibration().
LUTWidget* PluginColorCalibration::lutw protected
Definition at line 37 of file plugin_colorcalib.h.
Referenced by getControlWidget(), keyPressEvent(), mouseEvent(), and PluginColorCalibration().
LUTChannelMode PluginColorCalibration::mode protected
Definition at line 38 of file plugin_colorcalib.h.
Referenced by getControlWidget(), and PluginColorCalibration().
VarList* PluginColorCalibration::settings protected
Definition at line 36 of file plugin_colorcalib.h.
Referenced by getSettings(), PluginColorCalibration(), and ~PluginColorCalibration().
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/plugin_colorcalib.h
ssl-vision/src/app/plugins/plugin_colorcalib.cpp