Documentation: ssltest Namespace Reference
ssltest Namespace Reference
Functions
def vel_convert (vel_3_wheel)
def gr_Commands_CB (msg)
Variables
int frame = 1
ti = time.time()
ser = None
prev_time = time.time()
now_time = time.time()
string file = ''
int Team_ID = 127
list theta = [30.0,150.0,225.0,315.0]
float bot_radius = 0.087
float bot_wheel_radius = 0.025
float max_vel_wheel = 5000.0
int buf = [None]*32
int FACTOR_T = 40
int FACTOR_N = 40
int FACTOR_W = 90
list v_4_wheel = [None, None, None, None]
string ch_buff = ''
Function Documentation
def ssltest.gr_Commands_CB (msg)
Definition at line 68 of file ssltest.py.
References print(), and vel_convert().
 def gr_Commands_CB(msg):
     global buf, prev_time, now_time
     #print("Command received for bot_id : ",msg.robot_commands.id)
     # vel_xyw = [None]*3
     # vel_xyw[0] = int(msg.robot_commands.velnormal * FACTOR_T)
     # vel_xyw[1] = -1*int(msg.robot_commands.veltangent * FACTOR_N)
     # vel_xyw[2] =int(msg.robot_commands.velangular * FACTOR_W)
     # v_4_wheel = vel_convert(vel_xyw)
     # global frame,ti
     # # print(frame, ti,"  ", time.time())
     # # print("Frame Rate  ",frame*1.0/(time.time()-ti))
     # frame += 1
     # start = 1 + msg.robot_commands.id*5
     # for i in range(4):
     #     buf[i+start] = int(v_4_wheel[i])
     # if msg.robot_commands.spinner and msg.robot_commands.kickspeedx :
     #     buf[start+4] = 3
     # elif msg.robot_commands.spinner :
     #     buf[start+4] = 2
     # elif msg.robot_commands.kickspeedx :
     #     buf[start+4] = 1
     # else:
     #     buf[start+4] = 0
     # print(msg.robot_commands.spinner, msg.robot_commands.kickspeedx,"dribbler test")
     #ser.flush()
     #buf = bytearray(buf)
     buff = ''
     for i in xrange(1,32):
         buf[i] = 0
     for i in range(0,6):
         # pass
         buf[5*i+1],   buf[5*i+2],  buf[5*i+3],  buf[5*i+4] = vel_convert([0,-60,0])
     # buf[1],   buf[2],  buf[3],  buf[4] = vel_convert([0,-50,0])
     now_time = time.time()
     # print now_time- prev_time
     if(now_time- prev_time>1):
         prev_time = now_time
         buf[31] = 1
         print("SENDING_RESET"*20)
     for i in xrange(11,15):
         buf[i] = int(buf[i])
     for i in xrange(1,5):
         buf[i] = int(buf[i])
     for i in xrange(32):
         #print("f#ck off ",i)
         buff += chr(int(buf[i])%256)
     #print(buff)
     #print("2 fucked ",buf)
     # time.sleep(0.5)
     # statinfo = stat(file)
     # print(statinfo.st_size,file)
     #ser.flushInput()
     print(buf)
     ser.write(buff)
     # print(,"data return ")
     #print(size_buf_file(file),file)
     # print("Data sent :")
 # rospy.init_node('bot_comm_nrf',anonymous=False)
 # rospy.Subscriber('/grsim_data',gr_Commands,gr_Commands_CB)
 # time.sleep(0.5)
 while(1):
     # os.system("sleep 0.01s")
     gr_Commands_CB("")
     print "gfsgh"
 # rospy.spin()
 # msg=gr_Commands()
 # msg.robot_commands.id=0
 # msg.robot_commands.veltangent=0
 # msg.robot_commands.velnormal=50
 # msg.robot_commands.velangular=0
 # for i in range(32*69):
 #   time.sleep(1)
 #   msg.robot_commands.veltangent=(i%3)*20
 #   msg.robot_commands.velnormal=0
 #   msg.robot_commands.velangular=0
 #   print("itera   ", i)
 #   gr_Commands_CB(msg)
def ssltest.vel_convert (vel_3_wheel)
Definition at line 53 of file ssltest.py.
References print().
Referenced by gr_Commands_CB().
 def vel_convert(vel_3_wheel):
     vx = vel_3_wheel[0]
     vy = vel_3_wheel[1]
     vw = -vel_3_wheel[2]
     print("vx",vx,"vy",vy,"vw",vw)
     for i in range(4):
         v_4_wheel[i] = ((bot_radius*vw) - (vx*math.sin(theta[i]*math.pi/180.0)) + (vy*math.cos(theta[i]*math.pi/180.0)))/(bot_wheel_radius * math.pi)
     for i in range(4):
         if v_4_wheel[i] > 0 :
             v_4_wheel[i] = int(126 + ((v_4_wheel[i]-max_vel_wheel)*126.0) / max_vel_wheel)
         else :
             v_4_wheel[i] = int(256 - (v_4_wheel[i]*(129.0-256.0)) / max_vel_wheel)
     return v_4_wheel
Variable Documentation
float ssltest.bot_radius = 0.087
Definition at line 37 of file ssltest.py.
float ssltest.bot_wheel_radius = 0.025
Definition at line 38 of file ssltest.py.
int ssltest.buf = [None]*32
Definition at line 41 of file ssltest.py.
string ssltest.ch_buff = ''
Definition at line 49 of file ssltest.py.
int ssltest.FACTOR_N = 40
Definition at line 46 of file ssltest.py.
int ssltest.FACTOR_T = 40
Definition at line 45 of file ssltest.py.
int ssltest.FACTOR_W = 90
Definition at line 47 of file ssltest.py.
string ssltest.file = ''
Definition at line 18 of file ssltest.py.
int ssltest.frame = 1
Definition at line 9 of file ssltest.py.
float ssltest.max_vel_wheel = 5000.0
Definition at line 39 of file ssltest.py.
ssltest.now_time = time.time()
Definition at line 15 of file ssltest.py.
ssltest.prev_time = time.time()
Definition at line 14 of file ssltest.py.
ssltest.ser = None
Definition at line 13 of file ssltest.py.
int ssltest.Team_ID = 127
Definition at line 35 of file ssltest.py.
list ssltest.theta = [30.0,150.0,225.0,315.0]
Definition at line 36 of file ssltest.py.
ssltest.ti = time.time()
Definition at line 10 of file ssltest.py.
list ssltest.v_4_wheel = [None, None, None, None]
Definition at line 48 of file ssltest.py.