Documentation: VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id > Class Template Reference
VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id > Class Template Reference
A Vartype that wraps around google protocol buffers.
#include <VarProtoBufferVal.h>
Public Member Functions
VarProtoBufferVal (CLASS_VARVAL_TYPE *default_val=0)
virtual ~VarProtoBufferVal ()
virtual void printdebug () const
virtual void getSerialString (string &val) const
virtual void setSerialString (const string &val)
virtual void getBinarySerialString (string &val) const
virtual void setBinarySerialString (const string &val)
virtual VarVal * clone () const
virtual VarTypeId getType () const
virtual string getString () const
virtual CLASS_VARVAL_TYPE * get () const
virtual bool set (CLASS_VARVAL_TYPE *val)
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual bool setString (const string &val)
Set this node's data to some string representation.
string getBinarySerialString () const
string getSerialString () const
virtual bool hasValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Protected Attributes
CLASS_VARVAL_TYPE * _val
Additional Inherited Members
Protected Member Functions inherited from VarTypes::VarVal
virtual void lock () const
virtual void unlock () const
virtual void changed ()
Detailed Description
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id>
class VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >
A Vartype that wraps around google protocol buffers.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
The VarProtoBufferVal Vartype allows wrapping of Google Protocol Buffer Messages. It will automatically ensure that the data will be converted to/from base64 when storing/loading to/from XML.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 43 of file VarProtoBufferVal.h.
Constructor & Destructor Documentation
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id> VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::VarProtoBufferVal (CLASS_VARVAL_TYPE * default_val = 0) inline
Definition at line 51 of file VarProtoBufferVal.h.
References VarTypes::VarVal::changed().
                                                          : VarVal()
     {
       if (default_val==0) {
         default_val = new CLASS_VARVAL_TYPE();
       }
       set(default_val);
       changed();
     }
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id> virtual VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::~VarProtoBufferVal () inline virtual
Definition at line 60 of file VarProtoBufferVal.h.
References VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::_val.
{
       if (_val!=0) delete _val;
     }
Member Function Documentation
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id> virtual VarVal* VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::clone () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 106 of file VarProtoBufferVal.h.
References VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::set().
{
       VarProtoBufferVal<CLASS_VARVAL_TYPE, TPL_vartype_id> * tmp = new VarProtoBufferVal<CLASS_VARVAL_TYPE, TPL_vartype_id>();
       tmp->set(get());
       return tmp;
     }
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id> virtual CLASS_VARVAL_TYPE* VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::get () const inline virtual
Definition at line 122 of file VarProtoBufferVal.h.
References VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::_val, VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
{
       CLASS_VARVAL_TYPE * res=0;
       lock();
       res=_val;
       unlock();
       return res;
     };
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id> virtual void VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::getBinarySerialString (string & val) const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 93 of file VarProtoBufferVal.h.
References VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
{
       lock();
       if (_val!=0) _val->SerializeToString(&val);
       unlock();
     }
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id> virtual void VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::getSerialString (string & val) const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 72 of file VarProtoBufferVal.h.
References VarTypes::XMLParserBase64Tool::encode(), VarTypes::VarBase64::getTool(), VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
{
       lock();
       string temp;
       if (_val!=0) {
         _val->SerializeToString(&temp);
       }
       VarBase64::getTool()->encode(temp, val,1);
       unlock();
     }
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id> virtual string VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::getString () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 114 of file VarProtoBufferVal.h.
     {
       CLASS_VARVAL_TYPE * tmp = get();
       char blah[255];
       sprintf(blah,"Pointer: %p",tmp);
       return blah;
     };
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id> virtual VarTypeId VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::getType () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 112 of file VarProtoBufferVal.h.
 { return TPL_vartype_id; };
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id> virtual void VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::printdebug () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 64 of file VarProtoBufferVal.h.
References VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
     {
       lock();
       printf("Pointer %p\n",_val);
       unlock();
     }
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id> virtual bool VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::set (CLASS_VARVAL_TYPE * val) inline virtual
Definition at line 130 of file VarProtoBufferVal.h.
References VarTypes::VarVal::changed(), VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
Referenced by VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::clone().
{
       lock();
       if (_val!=val) {
         _val=val;
         unlock();
         changed();
         return true;
       } else {
         unlock();
         return false;
       }
     };
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id> virtual void VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::setBinarySerialString (const string & val) inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 99 of file VarProtoBufferVal.h.
References VarTypes::VarVal::changed(), VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
{
       lock();
       if (_val!=0) _val->ParseFromString(val);
       unlock();
       changed();
     }
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id> virtual void VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::setSerialString (const string & val) inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 82 of file VarProtoBufferVal.h.
References VarTypes::VarVal::changed(), VarTypes::XMLParserBase64Tool::decode(), VarTypes::VarBase64::getTool(), VarTypes::VarVal::lock(), and VarTypes::VarVal::unlock().
{
       lock();
       string temp;
       if (_val!=0) {
         VarBase64::getTool()->decode(val,temp);
         _val->ParseFromString(temp);
       }
       unlock();
       changed();
     }
Field Documentation
template<class CLASS_VARVAL_TYPE, VarTypeId TPL_vartype_id> CLASS_VARVAL_TYPE* VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::_val protected
Definition at line 47 of file VarProtoBufferVal.h.
Referenced by VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::get(), and VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::~VarProtoBufferVal().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/vartypes/primitives/VarProtoBufferVal.h