Documentation: PluginPublishGeometry Class Reference
PluginPublishGeometry Class Reference
#include <plugin_publishgeometry.h>
Public Member Functions
PluginPublishGeometry (FrameBuffer *fb, RoboCupSSLServer *server, const RoboCupField &field)
void addCameraParameters (CameraParameters *param)
virtual VarList * getSettings ()
virtual ~PluginPublishGeometry ()
virtual string getName ()
virtual ProcessResult process (FrameData *data, RenderOptions *options)
Public Member Functions inherited from VisionPlugin
VisionPlugin (FrameBuffer *_buffer)
virtual ~VisionPlugin ()
FrameBuffer * getFrameBuffer () const
this functions provides convenient access to the ring-buffer
void lock ()
void unlock ()
virtual bool isEnabled () const
virtual void setEnabled (bool enable)
virtual bool isVisualize () const
virtual void setVisualize (bool enable)
virtual bool isSharedAmongStacks () const
virtual void setSharedAmongStacks (bool enable)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual void postProcess (FrameData *data, RenderOptions *options)
virtual QWidget * getVisualizationWidget ()
virtual QWidget * getControlWidget ()
virtual void closeWidgets ()
virtual QList< QAction * > actions ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
void setTimeProcessing (double val)
void setTimePostProcessing (double val)
double getTimeProcessing ()
double getTimePostProcessing ()
Protected Slots
void slotPublishTriggered ()
Protected Member Functions
void sendGeometry ()
Protected Attributes
RoboCupSSLServer * _server
const RoboCupField & _field
vector< CameraParameters * > params
VarList * _settings
VarTrigger * _pub
VarBool * _pub_auto_enable
VarDouble * _pub_auto_interval
VarList * _pub_auto
QMutex mutex
double last_t
Protected Attributes inherited from VisionPlugin
QMutex mutex
bool enabled
bool visualize
bool shared
FrameBuffer * buffer
double time_proc
double time_post
Additional Inherited Members
Public Slots inherited from VisionPlugin
void slotKeyPressEvent (QKeyEvent *event)
Detailed Description
Author
Author Name
Definition at line 33 of file plugin_publishgeometry.h.
Constructor & Destructor Documentation
PluginPublishGeometry::PluginPublishGeometry (FrameBuffer * fb, RoboCupSSLServer * server, const RoboCupField & field)
Definition at line 23 of file plugin_publishgeometry.cpp.
References _pub, _pub_auto, _pub_auto_enable, _pub_auto_interval, _server, _settings, VarTypes::VarList::addChild(), last_t, VisionPlugin::setSharedAmongStacks(), and slotPublishTriggered().
  : VisionPlugin(fb), _field(field)
 {
   _server=server;
   setSharedAmongStacks(true);
   _settings=new VarList("Publish Geometry");
   _settings->addChild(_pub=new VarTrigger("Publish","Publish!"));
   _settings->addChild(_pub_auto=new VarList("Auto Publish"));
   _pub_auto->addChild(_pub_auto_enable=new VarBool("Enable",true));
   _pub_auto->addChild(_pub_auto_interval=new VarDouble("Interval (seconds)",3.0));
   last_t=0;
   connect(_pub,SIGNAL(signalTriggered()),this,SLOT(slotPublishTriggered()));
 }
PluginPublishGeometry::~PluginPublishGeometry () virtual
Definition at line 43 of file plugin_publishgeometry.cpp.
References _pub, and _settings.
 {
   delete _settings;
   delete _pub;
 }
Member Function Documentation
void PluginPublishGeometry::addCameraParameters (CameraParameters * param)
Definition at line 37 of file plugin_publishgeometry.cpp.
References VisionPlugin::lock(), params, and VisionPlugin::unlock().
Referenced by StackRoboCupSSL::StackRoboCupSSL().
{
   lock();
   params.push_back(param);
   unlock();
 }
string PluginPublishGeometry::getName () virtual
Reimplemented from VisionPlugin.
Definition at line 53 of file plugin_publishgeometry.cpp.
{
   return "Publish Geometry";
 }
VarList * PluginPublishGeometry::getSettings () virtual
Reimplemented from VisionPlugin.
Definition at line 49 of file plugin_publishgeometry.cpp.
References _settings.
{
   return _settings;
 }
ProcessResult PluginPublishGeometry::process (FrameData * data, RenderOptions * options) virtual
Reimplemented from VisionPlugin.
Definition at line 74 of file plugin_publishgeometry.cpp.
References _pub_auto_enable, _pub_auto_interval, VarTypes::VarBoolVal::getBool(), VarTypes::VarDoubleVal::getDouble(), last_t, ProcessingOk, sendGeometry(), t, and FrameData::time.
{
   (void)data;
   (void)options;
   //TODO: check client requests in server process
   //      if requested, call sendGeometry();
   if (_pub_auto_enable->getBool()==true) {
     double t = data->time - last_t;
     if (t > _pub_auto_interval->getDouble()) {
       sendGeometry();
       last_t=data->time;
     }
   }
   return ProcessingOk;
 }
void PluginPublishGeometry::sendGeometry () protected
Definition at line 57 of file plugin_publishgeometry.cpp.
References _field, _server, velocity.pid_::i, params, RoboCupSSLServer::send(), and RoboCupField::toProtoBuffer().
Referenced by process(), and slotPublishTriggered().
{
   SSL_GeometryData geodata;
   SSL_GeometryFieldSize * gfield = geodata.mutable_field();
   _field.toProtoBuffer(*gfield);
   for (unsigned int i = 0; i < params.size(); i++) {
     SSL_GeometryCameraCalibration * calib = geodata.add_calib();
     params[i]->toProtoBuffer(*calib,i);
   }
   _server->send(geodata);
 }
void PluginPublishGeometry::slotPublishTriggered () protected slot
Definition at line 68 of file plugin_publishgeometry.cpp.
References VisionPlugin::lock(), sendGeometry(), and VisionPlugin::unlock().
Referenced by PluginPublishGeometry().
{
   lock();
     sendGeometry();
   unlock();
 }
Field Documentation
const RoboCupField& PluginPublishGeometry::_field protected
Definition at line 38 of file plugin_publishgeometry.h.
Referenced by sendGeometry().
VarTrigger* PluginPublishGeometry::_pub protected
Definition at line 41 of file plugin_publishgeometry.h.
Referenced by PluginPublishGeometry(), and ~PluginPublishGeometry().
VarList* PluginPublishGeometry::_pub_auto protected
Definition at line 44 of file plugin_publishgeometry.h.
Referenced by PluginPublishGeometry().
VarBool* PluginPublishGeometry::_pub_auto_enable protected
Definition at line 42 of file plugin_publishgeometry.h.
Referenced by PluginPublishGeometry(), and process().
VarDouble* PluginPublishGeometry::_pub_auto_interval protected
Definition at line 43 of file plugin_publishgeometry.h.
Referenced by PluginPublishGeometry(), and process().
RoboCupSSLServer* PluginPublishGeometry::_server protected
Definition at line 37 of file plugin_publishgeometry.h.
Referenced by PluginPublishGeometry(), and sendGeometry().
VarList* PluginPublishGeometry::_settings protected
Definition at line 40 of file plugin_publishgeometry.h.
Referenced by getSettings(), PluginPublishGeometry(), and ~PluginPublishGeometry().
double PluginPublishGeometry::last_t protected
Definition at line 47 of file plugin_publishgeometry.h.
Referenced by PluginPublishGeometry(), and process().
QMutex PluginPublishGeometry::mutex protected
Definition at line 45 of file plugin_publishgeometry.h.
vector<CameraParameters *> PluginPublishGeometry::params protected
Definition at line 39 of file plugin_publishgeometry.h.
Referenced by addCameraParameters(), and sendGeometry().
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/plugin_publishgeometry.h
ssl-vision/src/app/plugins/plugin_publishgeometry.cpp