Documentation: Utils::RandomSampler< T > Class Template Reference
Utils::RandomSampler< T > Class Template Reference
#include <Random_sampling.hpp>
Public Member Functions
RandomSampler ()
RandomSampler (double alpha, double beta)
Point< T > & LineTo (Point< T > &goal, Point< T > &closest)
Point< T > & Uniform ()
Point< T > & Ellipsis (Point< T > &start, Point< T > &goal)
Private Attributes
double alpha
double beta
Detailed Description
template<class T>
class Utils::RandomSampler< T >
Definition at line 8 of file Random_sampling.hpp.
Constructor & Destructor Documentation
template<class T > Utils::RandomSampler< T >::RandomSampler () inline
Definition at line 13 of file Random_sampling.hpp.
 : alpha(0.1), beta(0.2) {}
template<class T > Utils::RandomSampler< T >::RandomSampler (double alpha, double beta) inline
Definition at line 14 of file Random_sampling.hpp.
References Utils::RandomSampler< T >::alpha, Utils::RandomSampler< T >::beta, Utils::RandomSampler< T >::Ellipsis(), Utils::RandomSampler< T >::LineTo(), and Utils::RandomSampler< T >::Uniform().
{
       this->alpha = alpha;
       this->beta = beta;
     }
Member Function Documentation
template<class T > Point< T > & Utils::RandomSampler< T >::Ellipsis (Point< T > & start, Point< T > & goal)
Definition at line 16 of file Random_sampling.cpp.
Referenced by Utils::RandomSampler< T >::RandomSampler().
                     {
   }
template<class T > Point< T > & Utils::RandomSampler< T >::LineTo (Point< T > & goal, Point< T > & closest)
Definition at line 5 of file Random_sampling.cpp.
Referenced by Utils::RandomSampler< T >::RandomSampler().
{
   }
template<class T > Point< T > & Utils::RandomSampler< T >::Uniform ()
Definition at line 11 of file Random_sampling.cpp.
Referenced by Utils::RandomSampler< T >::RandomSampler().
{
   }
Field Documentation
template<class T > double Utils::RandomSampler< T >::alpha private
Definition at line 10 of file Random_sampling.hpp.
Referenced by Utils::RandomSampler< T >::RandomSampler().
template<class T > double Utils::RandomSampler< T >::beta private
Definition at line 11 of file Random_sampling.hpp.
Referenced by Utils::RandomSampler< T >::RandomSampler().
The documentation for this class was generated from the following files:
RRT/include/Random_sampling.hpp
RRT/src/Random_sampling.cpp