Documentation: LUTWidget Class Reference
LUTWidget Class Reference
#include <lutwidget.h>
Public Member Functions
GLLUTWidget * getGLLUTWidget ()
void samplePixel (const yuv &color)
void add_del_Pixel (yuv color, bool add, bool continuing_undo)
void sampleImage (const RawImage &img)
void focusInEvent (QFocusEvent *event)
LUTWidget (LUT3D *lut, LUTChannelMode mode)
~LUTWidget ()
Protected Slots
void selectChannel (int c)
Protected Member Functions
void updateList (LUT3D *lut)
Protected Attributes
QBoxLayout * vbox
QBoxLayout * hbox
QListWidget * list
QLabel * label
GLLUTWidget * gllut
QToolBar * toolbar
LUTChannelMode _mode
Detailed Description
Definition at line 36 of file lutwidget.h.
Constructor & Destructor Documentation
LUTWidget::LUTWidget (LUT3D * lut, LUTChannelMode mode)
Definition at line 25 of file lutwidget.cpp.
References _mode, gllut, hbox, label, list, selectChannel(), GLLUTWidget::setLUT(), toolbar, updateList(), and vbox.
 {
   _mode=mode;
   toolbar=new QToolBar();
   vbox=new QBoxLayout(QBoxLayout::TopToBottom);
   hbox=new QBoxLayout(QBoxLayout::LeftToRight);
   list=new QListWidget();
   label=new QLabel();
   gllut=new GLLUTWidget(mode,this);
   gllut->setLUT(lut);
   updateList(lut);
   connect(list,SIGNAL(currentRowChanged(int)),this, SLOT(selectChannel(int)));
   list->setFixedWidth(list->sizeHintForColumn ( 0 ) + 5 );
   list->setSizePolicy ( QSizePolicy::Preferred, QSizePolicy::Preferred );
   list->setFocusPolicy(Qt::NoFocus);
   setFocusPolicy(Qt::StrongFocus);
   gllut->setSizePolicy ( QSizePolicy::Expanding, QSizePolicy::Expanding );
   label->setSizePolicy( QSizePolicy::Preferred, QSizePolicy::Preferred );
   toolbar->setIconSize(QSize(16,16));
   toolbar->setSizePolicy( QSizePolicy::Preferred, QSizePolicy::Preferred );
   vbox->setSpacing(2);
   vbox->setMargin(0);
   hbox->setSpacing(2);
   hbox->setMargin(0);
   hbox->addWidget(gllut);
   hbox->addWidget(list);
   vbox->addWidget(toolbar);
   vbox->addLayout(hbox);
   vbox->addWidget(label);
   this->setLayout(vbox);
   addActions(gllut->actions());
   toolbar->addActions(actions());
   //toolbar->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
                 //QList<QAction *> toolactions=gllut->actions();
                 //reverse the list so the icons appear in the right order:
                 // (qt really needs a list.reverse() function....)
                 /*for (int i=0;i<toolactions.size()/2;i++) {
                         toolactions.swap(i,toolactions.size()-(i+1));
                 }*/
                 //add the actions to the toolbar
 }
LUTWidget::~LUTWidget ()
Definition at line 105 of file lutwidget.cpp.
References gllut, hbox, label, list, toolbar, and vbox.
 {
   delete gllut;
   delete label;
   delete list;
   delete hbox;
   delete vbox;
   delete toolbar;
 }
Member Function Documentation
void LUTWidget::add_del_Pixel (yuv color, bool add, bool continuing_undo)
Definition at line 97 of file lutwidget.cpp.
References GLLUTWidget::add_del_Pixel(), and gllut.
Referenced by PluginColorCalibration::mouseEvent().
{
   gllut->add_del_Pixel(color, add, continuing_undo);
 }
void LUTWidget::focusInEvent (QFocusEvent * event)
Definition at line 115 of file lutwidget.cpp.
References gllut.
{
   (void)event;
   //forward the focus to the actual widget that we contain
   gllut->setFocus(Qt::OtherFocusReason);
 }
GLLUTWidget * LUTWidget::getGLLUTWidget ()
Definition at line 121 of file lutwidget.cpp.
References gllut.
Referenced by PluginColorCalibration::getControlWidget(), and PluginColorCalibration::keyPressEvent().
{
   return gllut;
 }
void LUTWidget::sampleImage (const RawImage & img)
Definition at line 101 of file lutwidget.cpp.
References gllut, and GLLUTWidget::sampleImage().
Referenced by PluginColorCalibration::keyPressEvent().
{
   gllut->sampleImage( img );
 }
void LUTWidget::samplePixel (const yuv & color)
Definition at line 93 of file lutwidget.cpp.
References gllut, and GLLUTWidget::samplePixel().
Referenced by PluginColorCalibration::mouseEvent().
{
   gllut->samplePixel( color );
 }
void LUTWidget::selectChannel (int c) protected slot
Definition at line 72 of file lutwidget.cpp.
References gllut, and GLLUTWidget::setChannel().
Referenced by LUTWidget().
{
   if (c!=(-1)) {
     gllut->setChannel(c);
   }
 }
void LUTWidget::updateList (LUT3D * lut) protected
Definition at line 78 of file lutwidget.cpp.
References LUT3D::channels, velocity.pid_::i, and list.
Referenced by LUTWidget().
{
   QListWidgetItem * item;
   for (unsigned int i=0;i<lut->channels.size();i++) {
     item=new QListWidgetItem(QString::fromStdString(lut->channels[i].label));
     QPixmap p(16,16);
     p.fill(QColor(lut->channels[i].draw_color.r,lut->channels[i].draw_color.g,lut->channels[i].draw_color.b));
     QPainter painter(&p);
     painter.setPen(QPen(QColor(0,0,0),1));
     painter.drawRect(0,0,15,15);
     item->setIcon(p);
     list->addItem(item);
   }
 }
Field Documentation
LUTChannelMode LUTWidget::_mode protected
Definition at line 46 of file lutwidget.h.
Referenced by LUTWidget().
GLLUTWidget* LUTWidget::gllut protected
Definition at line 43 of file lutwidget.h.
Referenced by add_del_Pixel(), focusInEvent(), getGLLUTWidget(), LUTWidget(), sampleImage(), samplePixel(), selectChannel(), and ~LUTWidget().
QBoxLayout* LUTWidget::hbox protected
Definition at line 40 of file lutwidget.h.
Referenced by LUTWidget(), and ~LUTWidget().
QLabel* LUTWidget::label protected
Definition at line 42 of file lutwidget.h.
Referenced by LUTWidget(), and ~LUTWidget().
QListWidget* LUTWidget::list protected
Definition at line 41 of file lutwidget.h.
Referenced by LUTWidget(), updateList(), and ~LUTWidget().
QToolBar* LUTWidget::toolbar protected
Definition at line 44 of file lutwidget.h.
Referenced by LUTWidget(), and ~LUTWidget().
QBoxLayout* LUTWidget::vbox protected
Definition at line 39 of file lutwidget.h.
Referenced by LUTWidget(), and ~LUTWidget().
The documentation for this class was generated from the following files:
ssl-vision/src/app/gui/lutwidget.h
ssl-vision/src/app/gui/lutwidget.cpp