Documentation: CMPattern::TeamSelector Class Reference
CMPattern::TeamSelector Class Reference
#include <cmpattern_teamdetector.h>
Signals
void signalTeamDataChanged ()
Public Member Functions
TeamSelector (string label, TeamDetectorSettings *detector_settings)
VarList * getSettings ()
Team * getSelectedTeam ()
int getNumberRobots ()
~TeamSelector ()
Protected Slots
void slotTeamInfoChanged ()
void slotTeamDataChanged ()
Protected Member Functions
void update ()
Protected Attributes
TeamDetectorSettings * _detector_settings
VarList * _settings
VarStringEnum * _selector
VarInt * _num_robots
Team * current_team
Detailed Description
Definition at line 72 of file cmpattern_teamdetector.h.
Constructor & Destructor Documentation
CMPattern::TeamSelector::TeamSelector (string label, TeamDetectorSettings * detector_settings) inline
Definition at line 119 of file cmpattern_teamdetector.h.
References VarTypes::VarList::addChild(), VarTypes::VarType::addFlags(), and VarTypes::VARTYPE_FLAG_NOLOAD_ENUM_CHILDREN.
{
     _detector_settings=detector_settings;
     connect(_detector_settings,SIGNAL(teamInfoChanged()),this,SLOT(slotTeamInfoChanged()));
     current_team=0;
     _settings= new VarList(label);
     _settings->addChild(_selector = new VarStringEnum("Team",""));
     _selector->addFlags(VARTYPE_FLAG_NOLOAD_ENUM_CHILDREN);
     _settings->addChild(_num_robots = new VarInt("Max Robots",6));
     update();
   }
CMPattern::TeamSelector::~TeamSelector () inline
Definition at line 143 of file cmpattern_teamdetector.h.
                   {
     delete _settings;
   }
Member Function Documentation
int CMPattern::TeamSelector::getNumberRobots () inline
Definition at line 140 of file cmpattern_teamdetector.h.
References VarTypes::VarInt::getInt().
Referenced by PluginDetectRobots::process().
{
     return _num_robots->getInt();
   }
Team* CMPattern::TeamSelector::getSelectedTeam () inline
Definition at line 132 of file cmpattern_teamdetector.h.
References VarTypes::VarStringEnum::getIndex(), and CMPattern::TeamDetectorSettings::getTeam().
Referenced by PluginDetectRobots::process().
{
     if (_selector->getIndex() == -1) {
       update();
     } else if (current_team!=_detector_settings->getTeam(_selector->getIndex())) {
       update();
     }
     return current_team;
   }
VarList* CMPattern::TeamSelector::getSettings () inline
Definition at line 129 of file cmpattern_teamdetector.h.
Referenced by MultiStackRoboCupSSL::MultiStackRoboCupSSL().
{
     return _settings;
   }
void CMPattern::TeamSelector::signalTeamDataChanged () signal
Definition at line 191 of file moc_cmpattern_teamdetector.cxx.
 {
     QMetaObject::activate(this, &staticMetaObject, 0, 0);
 }
void CMPattern::TeamSelector::slotTeamDataChanged () inline protected slot
Definition at line 115 of file cmpattern_teamdetector.h.
{
     emit(signalTeamDataChanged());
   }
void CMPattern::TeamSelector::slotTeamInfoChanged () inline protected slot
Definition at line 112 of file cmpattern_teamdetector.h.
{
     update();
   }
void CMPattern::TeamSelector::update () inline protected
Definition at line 82 of file cmpattern_teamdetector.h.
References VarTypes::VarStringEnum::getIndex(), CMPattern::TeamDetectorSettings::getTeam(), CMPattern::TeamDetectorSettings::getTeams(), velocity.pid_::i, VarTypes::VarStringEnum::selectIndex(), VarTypes::VarStringEnum::setLabel(), and VarTypes::VarStringEnum::setSize().
                 {
     vector<Team *> teams = _detector_settings->getTeams();
     _selector->setSize(teams.size(), "");
     int old_select_index = _selector->getIndex();
     for (unsigned int i=0;i<teams.size();i++) {
       _selector->setLabel(i,teams[i]-> _team_name->getString());
     }
     Team * new_team=0;
     if (teams.size() > 0) {
       if (old_select_index >= 0 && old_select_index < (int)teams.size()) {
          _selector->selectIndex(old_select_index);
       } else {
          _selector->selectIndex(0);
       }
       new_team=_detector_settings->getTeam(_selector->getIndex());
     } else {
       new_team=0;
     }
     if (new_team!=current_team) {
       if (current_team!=0) {
         disconnect(current_team,SIGNAL(signalChangeOccured(VarType*)),this,SLOT(slotTeamDataChanged()));
       }
       if (new_team!=0) {
         connect(new_team,SIGNAL(signalChangeOccured(VarType*)),this,SLOT(slotTeamDataChanged()));
       }
       current_team=new_team;
     }
     emit(signalTeamDataChanged());
   }
Field Documentation
TeamDetectorSettings* CMPattern::TeamSelector::_detector_settings protected
Definition at line 77 of file cmpattern_teamdetector.h.
VarInt* CMPattern::TeamSelector::_num_robots protected
Definition at line 80 of file cmpattern_teamdetector.h.
VarStringEnum* CMPattern::TeamSelector::_selector protected
Definition at line 79 of file cmpattern_teamdetector.h.
VarList* CMPattern::TeamSelector::_settings protected
Definition at line 78 of file cmpattern_teamdetector.h.
Team* CMPattern::TeamSelector::current_team protected
Definition at line 81 of file cmpattern_teamdetector.h.
The documentation for this class was generated from the following files:
ssl-vision/src/shared/cmpattern/cmpattern_teamdetector.h
ssl-vision/build/src/shared/cmpattern/moc_cmpattern_teamdetector.cxx