Documentation: VarTypes::VarItem Class Reference
VarTypes::VarItem Class Reference
The 'item' inheriting QStandardItem for displaying VarTypes in the QT4 Item-Model.
#include <VarItem.h>
Public Slots
void changeUpdate ()
Public Member Functions
GuiColumnFlag getColFlags () const
const VarTreeViewOptions * getViewOptions () const
VarType * getVarType ()
VarItem (VarType *_dt, const VarTreeViewOptions *_opts, GuiColumnFlag myflags)
virtual ~VarItem ()
void update (VarType *_dt, const VarTreeViewOptions *_opts, GuiColumnFlag myflags)
virtual int type () const
Static Public Attributes
static int const VarItemTypeNumber = (QStandardItem::UserType + 1)
Static Protected Member Functions
static bool areColFlagsSet (GuiColumnFlag _flags, GuiColumnFlag f)
static void searchTree (QStandardItem *node, const VarType *search, QList< VarItem * > &result)
static void updateTree (QStandardItem *node, const vector< VarType * > &children, const VarTreeViewOptions *_opts, bool recurse)
Protected Attributes
vector< GuiColumnFlag > * cols
VarType * dt
GuiColumnFlag colflags
const VarTreeViewOptions * opts
Friends
class VarTreeModel
Detailed Description
The 'item' inheriting QStandardItem for displaying VarTypes in the QT4 Item-Model.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
This file is part of the QT4 Item-Model for VarTypes. It is used when you want to edit/visualize VarTypes using QT4's model/view system.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 41 of file VarItem.h.
Constructor & Destructor Documentation
VarTypes::VarItem::VarItem (VarType * _dt, const VarTreeViewOptions * _opts, GuiColumnFlag myflags)
Definition at line 24 of file VarItem.cpp.
References dt, and update().
Referenced by updateTree().
{
     dt=0;
     update(_dt, opts, myflags);
   }
VarTypes::VarItem::~VarItem () virtual
Definition at line 29 of file VarItem.cpp.
                     {
   }
Member Function Documentation
static bool VarTypes::VarItem::areColFlagsSet (GuiColumnFlag _flags, GuiColumnFlag f) inline static protected
Definition at line 47 of file VarItem.h.
Referenced by changeUpdate(), and update().
{
     return ((_flags & f) == f);
   }
void VarTypes::VarItem::changeUpdate () slot
Definition at line 33 of file VarItem.cpp.
References areColFlagsSet(), VarTypes::VarType::areFlagsSet(), colflags, dt, VarTypes::VarVal::getType(), VarTypes::GUI_COLUMN_FLAG_TREE_NODE, opts, update(), updateTree(), VarTypes::VARTYPE_FLAG_HIDE_CHILDREN, VarTypes::VARTYPE_ID_EXTERNAL, and VarTypes::VARTYPE_ID_LIST.
Referenced by update().
{
     update(dt,opts,colflags);
     vector<VarType *> vd;
     if (dt!=0) {
       //update tree structure if it's a list item.
       if (areColFlagsSet(colflags,GUI_COLUMN_FLAG_TREE_NODE)) {
         if (dt->getType()==VARTYPE_ID_LIST || dt->getType()==VARTYPE_ID_EXTERNAL) {
           if (dt->areFlagsSet(VARTYPE_FLAG_HIDE_CHILDREN)==false) {
             vd=((VarList*)dt)->getChildren();
           }
           updateTree(this,vd,opts,true);
         }
       }
     }
   }
GuiColumnFlag VarTypes::VarItem::getColFlags () const
Definition at line 137 of file VarItem.cpp.
References colflags.
Referenced by VarTypes::VarItemDelegate::paint().
{
     return colflags;
   }
VarType * VarTypes::VarItem::getVarType ()
Definition at line 133 of file VarItem.cpp.
References dt.
Referenced by VarTypes::VarTreeView::checkDataChanged(), VarTypes::VarItemDelegate::createEditor(), VarTypes::VarItemDelegate::paint(), searchTree(), VarTypes::VarItemDelegate::setEditorData(), and VarTypes::VarItemDelegate::setModelData().
{
     return dt;
   }
const VarTreeViewOptions * VarTypes::VarItem::getViewOptions () const
Definition at line 141 of file VarItem.cpp.
References opts.
{
     return opts;
   }
void VarTypes::VarItem::searchTree (QStandardItem * node, const VarType * search, QList< VarItem * > & result) static protected
Definition at line 88 of file VarItem.cpp.
References getVarType(), and velocity.pid_::i.
Referenced by VarTypes::VarTreeModel::findItems().
{
     int n=node->rowCount();
     QStandardItem * tmp;
     for (int i=0;i<n;i++) {
       tmp=node->child(i);
       if (((VarItem *)tmp)->getVarType()==search) result.append((VarItem *)tmp);
       searchTree(tmp,search,result);
     }
   }
int VarTypes::VarItem::type () const virtual
Definition at line 49 of file VarItem.cpp.
{
     return QStandardItem::UserType + 1;
   }
void VarTypes::VarItem::update (VarType * _dt, const VarTreeViewOptions * _opts, GuiColumnFlag myflags)
Definition at line 52 of file VarItem.cpp.
References areColFlagsSet(), VarTypes::VarType::areFlagsSet(), changeUpdate(), colflags, dt, VarTypes::VarType::getFlags(), VarTypes::VarType::getName(), VarTypes::VarVal::getString(), VarTypes::VarVal::getType(), VarTypes::VarVal::getTypeName(), VarTypes::GUI_COLUMN_FLAG_EDITABLE, VarTypes::GUI_COLUMN_FLAG_TEXT_VALUE, VarTypes::GUI_COLUMN_FLAG_TREE_NODE, opts, VarTypes::VARTYPE_FLAG_PERSISTENT, VarTypes::VARTYPE_FLAG_READONLY, VarTypes::VARTYPE_ID_EXTERNAL, VarTypes::VARTYPE_ID_LIST, and VarTypes::VARTYPE_ID_TIMELINE.
Referenced by changeUpdate(), updateTree(), and VarItem().
{
     opts=_opts;
     colflags=myflags;
     setEditable(areColFlagsSet( colflags,GUI_COLUMN_FLAG_EDITABLE) && (_dt->getType() != VARTYPE_ID_LIST && _dt->getType() != VARTYPE_ID_EXTERNAL ));
     if (_dt!=dt && _dt!=0) {
       if (dt != 0) {
         disconnect(dt,SIGNAL(hasChanged(VarType *)),this,SLOT(changeUpdate()));
       }
       connect(_dt,SIGNAL(hasChanged(VarType *)),this,SLOT(changeUpdate()));
       dt=_dt;
     }
     if (dt!=0) {
     setEnabled(! dt->areFlagsSet(VARTYPE_FLAG_READONLY));
       if (areColFlagsSet(colflags,GUI_COLUMN_FLAG_TREE_NODE)) {
         setText(QString::fromStdString(dt->getName()));
         setToolTip(QString::fromStdString(dt->getName()) + " (" + QString::fromStdString(dt->getTypeName()) + ")");
         if (dt->getType() == VARTYPE_ID_LIST) {
           setIcon(QIcon(":/icons/vartypes/list.png"));
         } else if (dt->getType() == VARTYPE_ID_EXTERNAL) {
           setIcon(QIcon(":/icons/vartypes/external.png"));
         } else if (dt->getType() == VARTYPE_ID_TIMELINE) {
           setIcon(QIcon(":/icons/vartypes/time.png"));
           //setCheckState(1,Qt::Unchecked);
         } else {
           setIcon(QIcon(":/icons/vartypes/node.png"));
         }
       } else if (areColFlagsSet(colflags,GUI_COLUMN_FLAG_TEXT_VALUE)) {
         if ((dt->getFlags() & VARTYPE_FLAG_PERSISTENT) != 0x00) {
           setText("");
         } else {
           setText(QString::fromStdString(dt->getString()));
         }
       }
     }
   }
void VarTypes::VarItem::updateTree (QStandardItem * node, const vector< VarType * > & children, const VarTreeViewOptions * _opts, bool recurse) static protected
Definition at line 98 of file VarItem.cpp.
References VarTypes::VarType::areFlagsSet(), VarTypes::VarTreeViewOptions::getColumns(), velocity.pid_::i, update(), VarItem(), VarTypes::VARTYPE_FLAG_HIDDEN, and VarTypes::VARTYPE_FLAG_HIDE_CHILDREN.
Referenced by changeUpdate(), and VarTypes::VarTreeModel::setRootItems().
{
     //FIRST OF ALL filter out child_list that are invisible to the user or that are null-pointers
     vector<VarType *> child_list;
     for (unsigned int i=0;i<children.size();i++) {
       VarType * d = children[i];
       if (d!=0 && d->areFlagsSet(VARTYPE_FLAG_HIDDEN)==false) {
         child_list.push_back(d);
       }
     }
     vector<GuiColumnFlag> columns=_opts->getColumns();
     //Now display visible child_list:
     node->setColumnCount(columns.size());
     node->setRowCount(child_list.size());
     for (unsigned int i=0;i<child_list.size();i++) {
       for (unsigned int j=0;j<columns.size();j++) {
         VarItem * item=(VarItem *)node->child(i,j);
         //printf("i: %d   j: %d\n",i,j);
         if (item==0) {
           item=new VarItem(child_list[i],_opts,columns[j]);
           node->setChild(i,j,item);
         } else {
           item->update(child_list[i],_opts,columns[j]);
         }
         if (recurse && j==0) {
           if (child_list[i]->areFlagsSet(VARTYPE_FLAG_HIDE_CHILDREN)==false) {
             updateTree(item,child_list[i]->getChildren(),_opts,recurse);
           }
         }
       }
     }
   }
Friends And Related Function Documentation
friend class VarTreeModel friend
Definition at line 64 of file VarItem.h.
Field Documentation
GuiColumnFlag VarTypes::VarItem::colflags protected
Definition at line 52 of file VarItem.h.
Referenced by changeUpdate(), getColFlags(), and update().
vector<GuiColumnFlag>* VarTypes::VarItem::cols protected
Definition at line 50 of file VarItem.h.
VarType* VarTypes::VarItem::dt protected
Definition at line 51 of file VarItem.h.
Referenced by changeUpdate(), getVarType(), update(), and VarItem().
const VarTreeViewOptions* VarTypes::VarItem::opts protected
Definition at line 53 of file VarItem.h.
Referenced by changeUpdate(), getViewOptions(), and update().
int const VarTypes::VarItem::VarItemTypeNumber = (QStandardItem::UserType + 1) static
Definition at line 45 of file VarItem.h.
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/gui/VarItem.h
ssl-vision/src/shared/vartypes/gui/VarItem.cpp