Documentation: TimeGraphContainer Class Reference
TimeGraphContainer Class Reference
#include <TimeGraphContainer.h>
Public Member Functions
void addGraphScene (GraphScene *widget)
TimeControl * getTimeControl ()
TimeGraphContainer ()
virtual ~TimeGraphContainer ()
void redraw ()
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
QList< QGraphicsView * > list
QVBoxLayout * outer_layout
QVBoxLayout * inner_layout
TimeControlWidget * time_widget
Detailed Description
Definition at line 28 of file TimeGraphContainer.h.
Constructor & Destructor Documentation
TimeGraphContainer::TimeGraphContainer ()
Definition at line 22 of file TimeGraphContainer.cpp.
References inner_layout, outer_layout, and time_widget.
Referenced by getTimeControl().
 {
     time_widget = new TimeControlWidget();
     outer_layout = new QVBoxLayout();
     inner_layout = new QVBoxLayout();
     outer_layout->addLayout(inner_layout);
     outer_layout->addWidget(time_widget);
     inner_layout->setMargin(0);
     inner_layout->setSpacing(0);
     outer_layout->setMargin(0);
     outer_layout->setSpacing(0);
     setLayout(outer_layout);
 }
TimeGraphContainer::~TimeGraphContainer () virtual
Definition at line 38 of file TimeGraphContainer.cpp.
Referenced by getTimeControl().
 {
 }
Member Function Documentation
void TimeGraphContainer::addGraphScene (GraphScene * widget)
Definition at line 43 of file TimeGraphContainer.cpp.
References TimeControlWidget::getTimeControl(), inner_layout, list, GraphScene::setTimeControl(), time_widget, and v.
{
     scene->setTimeControl(time_widget->getTimeControl());
     QGraphicsView * v = new QGraphicsView();
     v->scale(1.0,-1.0);
     v->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
     v->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
     list.append(v);
     v->setScene(scene);
     inner_layout->addWidget(v);
 }
TimeControl* TimeGraphContainer::getTimeControl () inline
Definition at line 38 of file TimeGraphContainer.h.
References TimeControlWidget::getTimeControl(), paintEvent(), redraw(), TimeGraphContainer(), and ~TimeGraphContainer().
{
         return time_widget->getTimeControl();
     }
void TimeGraphContainer::paintEvent (QPaintEvent * event) virtual
Definition at line 56 of file TimeGraphContainer.cpp.
References redraw().
Referenced by getTimeControl().
{
     redraw();
     QWidget::paintEvent(event);
 }
void TimeGraphContainer::redraw ()
Definition at line 63 of file TimeGraphContainer.cpp.
References TimeControlWidget::getTimeControl(), velocity.pid_::i, list, time_widget, GraphScene::updateArea(), and v.
Referenced by getTimeControl(), and paintEvent().
{
     //redraw it all:
     QGraphicsView * v;
     GraphScene * gs;
     for (int i=0;i<list.size();i++) {
         v=list.at(i);
         gs=(GraphScene *)v->scene();
         gs->updateArea();
         //v->fitInView ( 0,-10,3,20);
         v->fitInView ( (double)time_widget->getTimeControl()->getVisibleRange()->getMin() ,
                                      (double)gs->sceneRect().y(),
                                      (double)time_widget->getTimeControl()->getVisibleRange()->getLength(),
                                       (double)gs->sceneRect().height(),
                                       //20,
                                       Qt::IgnoreAspectRatio );
         qDebug("fit %f, %f, %f, %f\n",(double)time_widget->getTimeControl()->getVisibleRange()->getMin() ,
                                      (double)gs->sceneRect().y(),
                                      (double)time_widget->getTimeControl()->getVisibleRange()->getLength(),
                                       (double)gs->sceneRect().height());
     }
 }
Field Documentation
QVBoxLayout* TimeGraphContainer::inner_layout protected
Definition at line 34 of file TimeGraphContainer.h.
Referenced by addGraphScene(), and TimeGraphContainer().
QList<QGraphicsView *> TimeGraphContainer::list protected
Definition at line 32 of file TimeGraphContainer.h.
Referenced by addGraphScene(), and redraw().
QVBoxLayout* TimeGraphContainer::outer_layout protected
Definition at line 33 of file TimeGraphContainer.h.
Referenced by TimeGraphContainer().
TimeControlWidget* TimeGraphContainer::time_widget protected
Definition at line 35 of file TimeGraphContainer.h.
Referenced by addGraphScene(), redraw(), and TimeGraphContainer().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/gui/experimental/TimeGraphContainer.h
ssl-vision/src/shared/vartypes/gui/experimental/TimeGraphContainer.cpp