Documentation: VideoWidget Class Reference
VideoWidget Class Reference
A QT widget container that allows detaching, and fullscreen mode.
#include <videowidget.h>
Public Slots
void processVideoStats (VideoStats stats)
void toggleOn (bool val)
void toggleWindow (bool val)
void toggleFullScreen (bool val)
Public Member Functions
VideoWidget (QString title="Unnamed", QWidget *vis=0)
virtual ~VideoWidget ()
Public Member Functions inherited from Ui_VideoWidget
void setupUi (QWidget *VideoWidget)
void retranslateUi (QWidget *VideoWidget)
Protected Member Functions
void closeEvent (QCloseEvent *event)
void focusInEvent (QFocusEvent *event)
Protected Attributes
QWidget * parent_backup
QAction * actionWindow
QAction * actionFullscreen
QWidget * _vis
Additional Inherited Members
Data Fields inherited from Ui_VideoWidget
QAction * actionWindow
QAction * actionFullscreen
QAction * actionFlipV
QAction * actionFlipH
QAction * actionOn
QVBoxLayout * vboxLayout
QFrame * bigframe
QVBoxLayout * vboxLayout1
QFrame * videoframe
QVBoxLayout * vboxLayout2
QLabel * titleLabel
QLabel * statLabel
Detailed Description
A QT widget container that allows detaching, and fullscreen mode.
Author
Stefan Zickler, (C) 2008
Definition at line 38 of file videowidget.h.
Constructor & Destructor Documentation
VideoWidget::VideoWidget (QString title = "Unnamed", QWidget * vis = 0)
Definition at line 24 of file videowidget.cpp.
References _vis, actionFullscreen, actionWindow, Ui_VideoWidget::bigframe, velocity.pid_::i, parent_backup, processVideoStats(), Ui_VideoWidget::setupUi(), Ui_VideoWidget::titleLabel, toggleFullScreen(), toggleWindow(), and Ui_VideoWidget::videoframe.
 {
   setupUi(this);
   this->setWindowTitle(title);
   titleLabel->setText(title);
   _vis=vis;
   //create a toolbar and add all the actions:
   QToolBar * toolbar=new QToolBar();
   actionWindow = new QAction(this);
   actionWindow->setObjectName("actionWindow");
   actionWindow->setCheckable(true);
   actionWindow->setIcon(QIcon(":/icons/window-new.png"));
   actionWindow->setShortcut(QKeySequence("Ctrl+w"));
   actionWindow->setToolTip("Toggle separate window (Ctrl-w)");
   actionWindow->setShortcutContext(Qt::WidgetShortcut);
   if (vis!=0)
     vis->addAction(actionWindow);
   connect(actionWindow, SIGNAL(triggered(bool)), this, SLOT(toggleWindow(bool)));
   actionFullscreen = new QAction(this);
   actionFullscreen->setObjectName("actionFullscreen");
   actionFullscreen->setCheckable(true);
   actionFullscreen->setIcon(QIcon(":/icons/view-fullscreen.png"));
   actionFullscreen->setShortcut(QKeySequence("Ctrl+f"));
   actionFullscreen->setToolTip("Toggle Fullscreen (Ctrl-f)");
   actionFullscreen->setShortcutContext(Qt::WidgetShortcut);
   if (vis!=0)
     vis->addAction(actionFullscreen);
   connect(actionFullscreen, SIGNAL(triggered(bool)), this, SLOT(toggleFullScreen(bool)));
   toolbar->setIconSize(QSize(16,16));
   toolbar->setSizePolicy( QSizePolicy::Preferred, QSizePolicy::Minimum );
   if (vis!=0) {
     //there is a sub-widget.
     //let's get its actions:
     QList<QAction *> toolactions=vis->actions();
     //reverse the list so the icons appear in the right order:
     // (qt really needs a list.reverse() function....)
     for (int i=0;i<toolactions.size()/2;i++) {
       toolactions.swap(i,toolactions.size()-(i+1));
     }
     //add the actions to the toolbar
     toolbar->addActions(toolactions);
     //add the widget itself and set it up:
     ((QVBoxLayout *)videoframe->layout())->insertWidget(1,vis);
     vis->setFocusPolicy(Qt::StrongFocus);
     vis->setSizePolicy( QSizePolicy::Preferred, QSizePolicy::Expanding );
     connect(vis, SIGNAL(updateVideoStats(VideoStats)), this, SLOT(processVideoStats(VideoStats)));
   }
   videoframe->setSizePolicy( QSizePolicy::Preferred, QSizePolicy::Expanding );
   this->bigframe->layout()->addWidget(toolbar);
   parent_backup=0;
 }
VideoWidget::~VideoWidget () virtual
Definition at line 123 of file videowidget.cpp.
 {}
Member Function Documentation
void VideoWidget::closeEvent (QCloseEvent * event) protected
Definition at line 177 of file videowidget.cpp.
References actionWindow.
 {
   //if this window is closed...simply re-integrate it into the parent
   actionWindow->trigger();
   event->ignore();
 }
void VideoWidget::focusInEvent (QFocusEvent * event) protected
Definition at line 169 of file videowidget.cpp.
References _vis.
 {
   (void)event;
   //forward the focus to the actual widget that we contain
   if (_vis!=0)
     _vis->setFocus(Qt::OtherFocusReason);
 }
void VideoWidget::processVideoStats (VideoStats stats) slot
Definition at line 184 of file videowidget.cpp.
References VideoStats::capture_stats, CaptureStats::fps_capture, VideoStats::fps_draw, VideoStats::fps_loop, and Ui_VideoWidget::statLabel.
Referenced by VideoWidget().
 {
   //our display-widget as thrown us a stat-update event
   //let's display it
   statLabel->setText(
     "Capture: "+ QString::number(stats.capture_stats.fps_capture,'f',2)  + " fps | Display: " + QString::number(stats.fps_draw,'f',2) + " fps | "
     + QString::number(stats.fps_loop,'f',2) + " its/s");
 }
void VideoWidget::toggleFullScreen (bool val) slot
Definition at line 89 of file videowidget.cpp.
References actionWindow, and parent_backup.
Referenced by VideoWidget().
 {
   //this function takes care of fullscreening this widget
   //it will automatically do the nasties such as
   //reparenting etc...
   QWidget * op=this;
   if (val) {
     if (op->parentWidget()!=NULL) {
       parent_backup=op->parentWidget();
       op->setParent(NULL, Qt::Window);
     }
     op->showFullScreen();
     actionWindow->setChecked(false);
   } else {
     if (op->parentWidget()==NULL) {
       if (actionWindow->isChecked()==true) {
         op->showNormal();
       } else {
         if (parent_backup!=NULL) {
           QSplitter * sp = qobject_cast<QSplitter *>(parent_backup);
           if (sp!=0) {
             sp->addWidget(op);
           } else {
             if (parent_backup->layout()!=0) {
               parent_backup->layout()->addWidget(op);
             }
           }
         }
       }
     }
   }
   op->setFocus(Qt::OtherFocusReason);
 }
void VideoWidget::toggleOn (bool val) slot
Definition at line 126 of file videowidget.cpp.
 {
   (void) val;
 }
void VideoWidget::toggleWindow (bool val) slot
Definition at line 131 of file videowidget.cpp.
References actionFullscreen, and parent_backup.
Referenced by VideoWidget().
 {
   (void) val;
   //this function takes care of detaching/attaching this widget
   //to become a separate window
   //it will automatically do the nasties such as
   //reparenting etc...
   QWidget * op=this;
   if (val) {
     QPoint pos = this->mapToGlobal(QPoint(0,0));
     if (op->parentWidget()!=NULL) {
       parent_backup=op->parentWidget();
       op->setParent(NULL, Qt::Window);
     }
     //op->setGeometry(,480);
     op->move(pos.x(),pos.y());
     op->showNormal();
   } else {
     if (op->parentWidget()==NULL) {
       if (parent_backup!=NULL) {
         QSplitter * sp = qobject_cast<QSplitter *>(parent_backup);
         if (sp!=0) {
           sp->addWidget(op);
         } else {
           if (parent_backup->layout()!=0) {
             parent_backup->layout()->addWidget(op);
           }
         }
       }
     }
   }
   actionFullscreen->setChecked(false);
   op->setFocus(Qt::OtherFocusReason);
 }
Field Documentation
QWidget* VideoWidget::_vis protected
Definition at line 44 of file videowidget.h.
Referenced by focusInEvent(), and VideoWidget().
QAction* VideoWidget::actionFullscreen protected
Definition at line 43 of file videowidget.h.
Referenced by toggleWindow(), and VideoWidget().
QAction* VideoWidget::actionWindow protected
Definition at line 42 of file videowidget.h.
Referenced by closeEvent(), toggleFullScreen(), and VideoWidget().
QWidget* VideoWidget::parent_backup protected
Definition at line 41 of file videowidget.h.
Referenced by toggleFullScreen(), toggleWindow(), and VideoWidget().
The documentation for this class was generated from the following files:
ssl-vision/src/app/gui/videowidget.h
ssl-vision/src/app/gui/videowidget.cpp