Documentation: Debug_Line Class Reference
Debug_Line Class Reference
#include <sslDebug_Data.pb.h>
Public Member Functions
Debug_Line ()
virtual ~Debug_Line ()
Debug_Line (const Debug_Line &from)
Debug_Line & operator= (const Debug_Line &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Debug_Line *other)
Debug_Line * New () const PROTOBUF_FINAL
Debug_Line * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const Debug_Line &from)
void MergeFrom (const Debug_Line &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_x1 () const
void clear_x1 ()
::google::protobuf::int32 x1 () const
void set_x1 (::google::protobuf::int32 value)
bool has_y1 () const
void clear_y1 ()
::google::protobuf::int32 y1 () const
void set_y1 (::google::protobuf::int32 value)
bool has_x2 () const
void clear_x2 ()
::google::protobuf::int32 x2 () const
void set_x2 (::google::protobuf::int32 value)
bool has_y2 () const
void clear_y2 ()
::google::protobuf::int32 y2 () const
void set_y2 (::google::protobuf::int32 value)
bool has_color () const
void clear_color ()
float color () const
void set_color (float value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Debug_Line & default_instance ()
static const Debug_Line * internal_default_instance ()
Static Public Attributes
static const int kX1FieldNumber = 1
static const int kY1FieldNumber = 2
static const int kX2FieldNumber = 3
static const int kY2FieldNumber = 4
static const int kColorFieldNumber = 5
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (Debug_Line *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_x1 ()
void clear_has_x1 ()
void set_has_y1 ()
void clear_has_y1 ()
void set_has_x2 ()
void clear_has_x2 ()
void set_has_y2 ()
void clear_has_y2 ()
void set_has_color ()
void clear_has_color ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_sslDebug_5fData_2eproto ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::int32 x1_
::google::protobuf::int32 y1_
::google::protobuf::int32 x2_
::google::protobuf::int32 y2_
float color_
Friends
void protobuf_InitDefaults_sslDebug_5fData_2eproto_impl ()
void protobuf_AddDesc_sslDebug_5fData_2eproto_impl ()
void protobuf_ShutdownFile_sslDebug_5fData_2eproto ()
Detailed Description
Definition at line 342 of file sslDebug_Data.pb.h.
Constructor & Destructor Documentation
Debug_Line::Debug_Line ()
virtual Debug_Line::~Debug_Line () virtual
Debug_Line::Debug_Line (const Debug_Line & from)
Member Function Documentation
size_t Debug_Line::ByteSizeLong () const
void Debug_Line::Clear ()
void Debug_Line::clear_color () inline
Definition at line 1193 of file sslDebug_Data.pb.h.
{
   color_ = 0;
   clear_has_color();
 }
void Debug_Line::clear_has_color () inline private
Definition at line 1190 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000010u;
 }
void Debug_Line::clear_has_x1 () inline private
Definition at line 1094 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void Debug_Line::clear_has_x2 () inline private
Definition at line 1142 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000004u;
 }
void Debug_Line::clear_has_y1 () inline private
Definition at line 1118 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000002u;
 }
void Debug_Line::clear_has_y2 () inline private
Definition at line 1166 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000008u;
 }
void Debug_Line::clear_x1 () inline
Definition at line 1097 of file sslDebug_Data.pb.h.
{
   x1_ = 0;
   clear_has_x1();
 }
void Debug_Line::clear_x2 () inline
Definition at line 1145 of file sslDebug_Data.pb.h.
{
   x2_ = 0;
   clear_has_x2();
 }
void Debug_Line::clear_y1 () inline
Definition at line 1121 of file sslDebug_Data.pb.h.
{
   y1_ = 0;
   clear_has_y1();
 }
void Debug_Line::clear_y2 () inline
Definition at line 1169 of file sslDebug_Data.pb.h.
{
   y2_ = 0;
   clear_has_y2();
 }
float Debug_Line::color () const inline
Definition at line 1197 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_Line.color)
   return color_;
 }
void Debug_Line::CopyFrom (const ::google::protobuf::Message & from)
void Debug_Line::CopyFrom (const Debug_Line & from)
static const Debug_Line& Debug_Line::default_instance () static
static const ::google::protobuf::Descriptor* Debug_Line::descriptor () static
inline ::google::protobuf::Arena* Debug_Line::GetArenaNoVirtual () const inline private
Definition at line 402 of file sslDebug_Data.pb.h.
{
     return NULL;
   }
int Debug_Line::GetCachedSize () const inline
Definition at line 395 of file sslDebug_Data.pb.h.
References sslDebug_Data::_cached_size_, sslDebug_Data::InternalSwap(), sslDebug_Data::SetCachedSize(), sslDebug_Data::SharedCtor(), and sslDebug_Data::SharedDtor().
 { return _cached_size_; }
::google::protobuf::Metadata Debug_Line::GetMetadata () const
bool Debug_Line::has_color () const inline
Definition at line 1184 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
bool Debug_Line::has_x1 () const inline
Definition at line 1088 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool Debug_Line::has_x2 () const inline
Definition at line 1136 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool Debug_Line::has_y1 () const inline
Definition at line 1112 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool Debug_Line::has_y2 () const inline
Definition at line 1160 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
static const Debug_Line* Debug_Line::internal_default_instance () inline static
Definition at line 365 of file sslDebug_Data.pb.h.
References _Debug_Line_default_instance_, and sslDebug_Data::Swap().
{
     return reinterpret_cast<const Debug_Line*>(
                &_Debug_Line_default_instance_);
   }
::google::protobuf::uint8* Debug_Line::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void Debug_Line::InternalSwap (Debug_Line * other) private
bool Debug_Line::IsInitialized () const
void* Debug_Line::MaybeArenaPtr () const inline private
Definition at line 405 of file sslDebug_Data.pb.h.
References sslDebug_Data::GetMetadata().
{
     return NULL;
   }
void Debug_Line::MergeFrom (const ::google::protobuf::Message & from)
void Debug_Line::MergeFrom (const Debug_Line & from)
bool Debug_Line::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
inline ::google::protobuf::UnknownFieldSet* Debug_Line::mutable_unknown_fields () inline
Definition at line 358 of file sslDebug_Data.pb.h.
References sslDebug_Data::_internal_metadata_, sslDebug_Data::default_instance(), and sslDebug_Data::descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
Debug_Line* Debug_Line::New () const inline
Definition at line 374 of file sslDebug_Data.pb.h.
References sslDebug_Data::ByteSizeLong(), sslDebug_Data::Clear(), sslDebug_Data::CopyFrom(), sslDebug_Data::InternalSerializeWithCachedSizesToArray(), sslDebug_Data::IsInitialized(), sslDebug_Data::MergeFrom(), sslDebug_Data::MergePartialFromCodedStream(), sslDebug_Data::New(), New(), sslDebug_Data::SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
Debug_Line* Debug_Line::New (::google::protobuf::Arena * arena) const
Debug_Line& Debug_Line::operator= (const Debug_Line & from) inline
Definition at line 349 of file sslDebug_Data.pb.h.
References sslDebug_Data::CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* Debug_Line::protobuf_Offsets_sslDebug_5fData_2eproto () private
size_t Debug_Line::RequiredFieldsByteSizeFallback () const private
void Debug_Line::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* Debug_Line::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 391 of file sslDebug_Data.pb.h.
References sslDebug_Data::InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void Debug_Line::set_color (float value) inline
Definition at line 1201 of file sslDebug_Data.pb.h.
Referenced by Callback(), CallbackDbg(), CallbackGC(), and main().
{
   set_has_color();
   color_ = value;
   // @@protoc_insertion_point(field_set:Debug_Line.color)
 }
void Debug_Line::set_has_color () inline private
Definition at line 1187 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000010u;
 }
void Debug_Line::set_has_x1 () inline private
Definition at line 1091 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000001u;
 }
void Debug_Line::set_has_x2 () inline private
Definition at line 1139 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000004u;
 }
void Debug_Line::set_has_y1 () inline private
Definition at line 1115 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000002u;
 }
void Debug_Line::set_has_y2 () inline private
Definition at line 1163 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000008u;
 }
void Debug_Line::set_x1 (::google::protobuf::int32 value) inline
Definition at line 1105 of file sslDebug_Data.pb.h.
Referenced by Callback(), CallbackDbg(), CallbackGC(), and main().
{
   set_has_x1();
   x1_ = value;
   // @@protoc_insertion_point(field_set:Debug_Line.x1)
 }
void Debug_Line::set_x2 (::google::protobuf::int32 value) inline
Definition at line 1153 of file sslDebug_Data.pb.h.
Referenced by Callback(), CallbackDbg(), CallbackGC(), and main().
{
   set_has_x2();
   x2_ = value;
   // @@protoc_insertion_point(field_set:Debug_Line.x2)
 }
void Debug_Line::set_y1 (::google::protobuf::int32 value) inline
Definition at line 1129 of file sslDebug_Data.pb.h.
Referenced by Callback(), CallbackDbg(), CallbackGC(), and main().
{
   set_has_y1();
   y1_ = value;
   // @@protoc_insertion_point(field_set:Debug_Line.y1)
 }
void Debug_Line::set_y2 (::google::protobuf::int32 value) inline
Definition at line 1177 of file sslDebug_Data.pb.h.
Referenced by Callback(), CallbackDbg(), CallbackGC(), and main().
{
   set_has_y2();
   y2_ = value;
   // @@protoc_insertion_point(field_set:Debug_Line.y2)
 }
void Debug_Line::SetCachedSize (int size) const private
void Debug_Line::SharedCtor () private
void Debug_Line::SharedDtor () private
void Debug_Line::Swap (Debug_Line * other)
const ::google::protobuf::UnknownFieldSet& Debug_Line::unknown_fields () const inline
Definition at line 354 of file sslDebug_Data.pb.h.
References sslDebug_Data::_internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
google::protobuf::int32 Debug_Line::x1 () const inline
Definition at line 1101 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_Line.x1)
   return x1_;
 }
google::protobuf::int32 Debug_Line::x2 () const inline
Definition at line 1149 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_Line.x2)
   return x2_;
 }
google::protobuf::int32 Debug_Line::y1 () const inline
Definition at line 1125 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_Line.y1)
   return y1_;
 }
google::protobuf::int32 Debug_Line::y2 () const inline
Definition at line 1173 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_Line.y2)
   return y2_;
 }
Friends And Related Function Documentation
void protobuf_AddDesc_sslDebug_5fData_2eproto_impl () friend
void protobuf_InitDefaults_sslDebug_5fData_2eproto_impl () friend
void protobuf_ShutdownFile_sslDebug_5fData_2eproto () friend
Field Documentation
int Debug_Line::_cached_size_ mutable private
Definition at line 469 of file sslDebug_Data.pb.h.
::google::protobuf::internal::HasBits<1> Debug_Line::_has_bits_ private
Definition at line 468 of file sslDebug_Data.pb.h.
::google::protobuf::internal::InternalMetadataWithArena Debug_Line::_internal_metadata_ private
Definition at line 467 of file sslDebug_Data.pb.h.
float Debug_Line::color_ private
Definition at line 474 of file sslDebug_Data.pb.h.
const int Debug_Line::kColorFieldNumber = 5 static
Definition at line 447 of file sslDebug_Data.pb.h.
const int Debug_Line::kX1FieldNumber = 1 static
Definition at line 419 of file sslDebug_Data.pb.h.
const int Debug_Line::kX2FieldNumber = 3 static
Definition at line 433 of file sslDebug_Data.pb.h.
const int Debug_Line::kY1FieldNumber = 2 static
Definition at line 426 of file sslDebug_Data.pb.h.
const int Debug_Line::kY2FieldNumber = 4 static
Definition at line 440 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_Line::x1_ private
Definition at line 470 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_Line::x2_ private
Definition at line 472 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_Line::y1_ private
Definition at line 471 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_Line::y2_ private
Definition at line 473 of file sslDebug_Data.pb.h.
The documentation for this class was generated from the following file:
grsim_comm/include/proto/sslDebug_Data.pb.h