Documentation: Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder Class Reference
Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
MessagesRobocupSslWrapper.SSL_WrapperPacket getDefaultInstanceForType ()
MessagesRobocupSslWrapper.SSL_WrapperPacket build ()
MessagesRobocupSslWrapper.SSL_WrapperPacket buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (MessagesRobocupSslWrapper.SSL_WrapperPacket other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasDetection ()
MessagesRobocupSslDetection.SSL_DetectionFrame getDetection ()
Builder setDetection (MessagesRobocupSslDetection.SSL_DetectionFrame value)
Builder setDetection (MessagesRobocupSslDetection.SSL_DetectionFrame.Builder builderForValue)
Builder mergeDetection (MessagesRobocupSslDetection.SSL_DetectionFrame value)
Builder clearDetection ()
MessagesRobocupSslDetection.SSL_DetectionFrame.Builder getDetectionBuilder ()
MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getDetectionOrBuilder ()
boolean hasGeometry ()
MessagesRobocupSslGeometry.SSL_GeometryData getGeometry ()
Builder setGeometry (MessagesRobocupSslGeometry.SSL_GeometryData value)
Builder setGeometry (MessagesRobocupSslGeometry.SSL_GeometryData.Builder builderForValue)
Builder mergeGeometry (MessagesRobocupSslGeometry.SSL_GeometryData value)
Builder clearGeometry ()
MessagesRobocupSslGeometry.SSL_GeometryData.Builder getGeometryBuilder ()
MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder getGeometryOrBuilder ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
MessagesRobocupSslWrapper.SSL_WrapperPacket buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionFrame, MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder > getDetectionFieldBuilder ()
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslGeometry.SSL_GeometryData, MessagesRobocupSslGeometry.SSL_GeometryData.Builder, MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder > getGeometryFieldBuilder ()
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
MessagesRobocupSslDetection.SSL_DetectionFrame detection_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance()
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionFrame, MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder > detectionBuilder_
MessagesRobocupSslGeometry.SSL_GeometryData geometry_ = MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance()
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslGeometry.SSL_GeometryData, MessagesRobocupSslGeometry.SSL_GeometryData.Builder, MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder > geometryBuilder_
Detailed Description
Definition at line 222 of file MessagesRobocupSslWrapper.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.Builder () inline private
Definition at line 236 of file MessagesRobocupSslWrapper.java.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.Builder (BuilderParent parent) inline private
Definition at line 240 of file MessagesRobocupSslWrapper.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.build () inline
Definition at line 284 of file MessagesRobocupSslWrapper.java.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.setDetection(), and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.setGeometry().
{
         MessagesRobocupSslWrapper.SSL_WrapperPacket result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 292 of file MessagesRobocupSslWrapper.java.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.parseDelimitedFrom().
{
         MessagesRobocupSslWrapper.SSL_WrapperPacket result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.buildPartial () inline
Definition at line 302 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.detection_.
{
         MessagesRobocupSslWrapper.SSL_WrapperPacket result = new MessagesRobocupSslWrapper.SSL_WrapperPacket(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         if (detectionBuilder_ == null) {
           result.detection_ = detection_;
         } else {
           result.detection_ = detectionBuilder_.build();
         }
         if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
           to_bitField0_ |= 0x00000002;
         }
         if (geometryBuilder_ == null) {
           result.geometry_ = geometry_;
         } else {
           result.geometry_ = geometryBuilder_.build();
         }
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.clear () inline
Definition at line 254 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.clear(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance().
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.clear().
{
         super.clear();
         if (detectionBuilder_ == null) {
           detection_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
         } else {
           detectionBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000001);
         if (geometryBuilder_ == null) {
           geometry_ = MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance();
         } else {
           geometryBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000002);
         return this;
       }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.clearDetection () inline
Definition at line 465 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance().
{
         if (detectionBuilder_ == null) {
           detection_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
           onChanged();
         } else {
           detectionBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000001);
         return this;
       }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.clearGeometry () inline
Definition at line 555 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance().
{
         if (geometryBuilder_ == null) {
           geometry_ = MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance();
           onChanged();
         } else {
           geometryBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000002);
         return this;
       }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.clone () inline
Definition at line 271 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.create () inline static private
Definition at line 250 of file MessagesRobocupSslWrapper.java.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.newBuilder().
{
         return new Builder();
       }
MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getDefaultInstanceForType () inline
Definition at line 280 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.getDefaultInstance().
{
         return MessagesRobocupSslWrapper.SSL_WrapperPacket.getDefaultInstance();
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getDescriptor () inline static
Definition at line 226 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_descriptor.
{
         return MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getDescriptorForType () inline
Definition at line 276 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.getDescriptor().
{
         return MessagesRobocupSslWrapper.SSL_WrapperPacket.getDescriptor();
       }
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getDetection () inline
Implements Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.
Definition at line 418 of file MessagesRobocupSslWrapper.java.
{
         if (detectionBuilder_ == null) {
           return detection_;
         } else {
           return detectionBuilder_.getMessage();
         }
       }
MessagesRobocupSslDetection.SSL_DetectionFrame.Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getDetectionBuilder () inline
Definition at line 475 of file MessagesRobocupSslWrapper.java.
{
         bitField0_ |= 0x00000001;
         onChanged();
         return getDetectionFieldBuilder().getBuilder();
       }
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionFrame, MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder> Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getDetectionFieldBuilder () inline private
Definition at line 489 of file MessagesRobocupSslWrapper.java.
{
         if (detectionBuilder_ == null) {
           detectionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
               MessagesRobocupSslDetection.SSL_DetectionFrame, MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder>(
                   detection_,
                   getParentForChildren(),
                   isClean());
           detection_ = null;
         }
         return detectionBuilder_;
       }
MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getDetectionOrBuilder () inline
Implements Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.
Definition at line 480 of file MessagesRobocupSslWrapper.java.
{
         if (detectionBuilder_ != null) {
           return detectionBuilder_.getMessageOrBuilder();
         } else {
           return detection_;
         }
       }
MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getGeometry () inline
Implements Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.
Definition at line 508 of file MessagesRobocupSslWrapper.java.
{
         if (geometryBuilder_ == null) {
           return geometry_;
         } else {
           return geometryBuilder_.getMessage();
         }
       }
MessagesRobocupSslGeometry.SSL_GeometryData.Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getGeometryBuilder () inline
Definition at line 565 of file MessagesRobocupSslWrapper.java.
{
         bitField0_ |= 0x00000002;
         onChanged();
         return getGeometryFieldBuilder().getBuilder();
       }
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslGeometry.SSL_GeometryData, MessagesRobocupSslGeometry.SSL_GeometryData.Builder, MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder> Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getGeometryFieldBuilder () inline private
Definition at line 579 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.initFields().
{
         if (geometryBuilder_ == null) {
           geometryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
               MessagesRobocupSslGeometry.SSL_GeometryData, MessagesRobocupSslGeometry.SSL_GeometryData.Builder, MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder>(
                   geometry_,
                   getParentForChildren(),
                   isClean());
           geometry_ = null;
         }
         return geometryBuilder_;
       }
MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getGeometryOrBuilder () inline
Implements Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.
Definition at line 570 of file MessagesRobocupSslWrapper.java.
{
         if (geometryBuilder_ != null) {
           return geometryBuilder_.getMessageOrBuilder();
         } else {
           return geometry_;
         }
       }
boolean Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.hasDetection () inline
Implements Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.
Definition at line 415 of file MessagesRobocupSslWrapper.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
boolean Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.hasGeometry () inline
Implements Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.
Definition at line 505 of file MessagesRobocupSslWrapper.java.
{
         return ((bitField0_ & 0x00000002) == 0x00000002);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 231 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_fieldAccessorTable.
{
         return MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_fieldAccessorTable;
       }
final boolean Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.isInitialized () inline
Definition at line 348 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.getDetection(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.getGeometry(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.hasDetection(), and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.hasGeometry().
{
         if (hasDetection()) {
           if (!getDetection().isInitialized()) {
             return false;
           }
         }
         if (hasGeometry()) {
           if (!getGeometry().isInitialized()) {
             return false;
           }
         }
         return true;
       }
void Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.maybeForceBuilderInitialization () inline private
Definition at line 244 of file MessagesRobocupSslWrapper.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
           getDetectionFieldBuilder();
           getGeometryFieldBuilder();
         }
       }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeDetection (MessagesRobocupSslDetection.SSL_DetectionFrame value) inline
Definition at line 449 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.buildPartial(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder().
{
         if (detectionBuilder_ == null) {
           if (((bitField0_ & 0x00000001) == 0x00000001) &&
               detection_ != MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance()) {
             detection_ =
               MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder(detection_).mergeFrom(value).buildPartial();
           } else {
             detection_ = value;
           }
           onChanged();
         } else {
           detectionBuilder_.mergeFrom(value);
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 327 of file MessagesRobocupSslWrapper.java.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.clone(), and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.newBuilder().
{
         if (other instanceof MessagesRobocupSslWrapper.SSL_WrapperPacket) {
           return mergeFrom((MessagesRobocupSslWrapper.SSL_WrapperPacket)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom (MessagesRobocupSslWrapper.SSL_WrapperPacket other) inline
Definition at line 336 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.getDefaultInstance().
{
         if (other == MessagesRobocupSslWrapper.SSL_WrapperPacket.getDefaultInstance()) return this;
         if (other.hasDetection()) {
           mergeDetection(other.getDetection());
         }
         if (other.hasGeometry()) {
           mergeGeometry(other.getGeometry());
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 364 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.Builder(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.getDetection(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.getGeometry(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.hasDetection(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.hasGeometry(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeFrom(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.newBuilder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 10: {
               MessagesRobocupSslDetection.SSL_DetectionFrame.Builder subBuilder = MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder();
               if (hasDetection()) {
                 subBuilder.mergeFrom(getDetection());
               }
               input.readMessage(subBuilder, extensionRegistry);
               setDetection(subBuilder.buildPartial());
               break;
             }
             case 18: {
               MessagesRobocupSslGeometry.SSL_GeometryData.Builder subBuilder = MessagesRobocupSslGeometry.SSL_GeometryData.newBuilder();
               if (hasGeometry()) {
                 subBuilder.mergeFrom(getGeometry());
               }
               input.readMessage(subBuilder, extensionRegistry);
               setGeometry(subBuilder.buildPartial());
               break;
             }
           }
         }
       }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeGeometry (MessagesRobocupSslGeometry.SSL_GeometryData value) inline
Definition at line 539 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.buildPartial(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeFrom(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.newBuilder().
{
         if (geometryBuilder_ == null) {
           if (((bitField0_ & 0x00000002) == 0x00000002) &&
               geometry_ != MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance()) {
             geometry_ =
               MessagesRobocupSslGeometry.SSL_GeometryData.newBuilder(geometry_).mergeFrom(value).buildPartial();
           } else {
             geometry_ = value;
           }
           onChanged();
         } else {
           geometryBuilder_.mergeFrom(value);
         }
         bitField0_ |= 0x00000002;
         return this;
       }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.setDetection (MessagesRobocupSslDetection.SSL_DetectionFrame value) inline
Definition at line 425 of file MessagesRobocupSslWrapper.java.
{
         if (detectionBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           detection_ = value;
           onChanged();
         } else {
           detectionBuilder_.setMessage(value);
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.setDetection (MessagesRobocupSslDetection.SSL_DetectionFrame.Builder builderForValue) inline
Definition at line 438 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.build().
{
         if (detectionBuilder_ == null) {
           detection_ = builderForValue.build();
           onChanged();
         } else {
           detectionBuilder_.setMessage(builderForValue.build());
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.setGeometry (MessagesRobocupSslGeometry.SSL_GeometryData value) inline
Definition at line 515 of file MessagesRobocupSslWrapper.java.
{
         if (geometryBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           geometry_ = value;
           onChanged();
         } else {
           geometryBuilder_.setMessage(value);
         }
         bitField0_ |= 0x00000002;
         return this;
       }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.setGeometry (MessagesRobocupSslGeometry.SSL_GeometryData.Builder builderForValue) inline
Definition at line 528 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.build().
{
         if (geometryBuilder_ == null) {
           geometry_ = builderForValue.build();
           onChanged();
         } else {
           geometryBuilder_.setMessage(builderForValue.build());
         }
         bitField0_ |= 0x00000002;
         return this;
       }
Field Documentation
int Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.bitField0_ private
Definition at line 409 of file MessagesRobocupSslWrapper.java.
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.detection_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance() private
Definition at line 412 of file MessagesRobocupSslWrapper.java.
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionFrame, MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder> Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.detectionBuilder_ private
Definition at line 414 of file MessagesRobocupSslWrapper.java.
MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.geometry_ = MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance() private
Definition at line 502 of file MessagesRobocupSslWrapper.java.
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslGeometry.SSL_GeometryData, MessagesRobocupSslGeometry.SSL_GeometryData.Builder, MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder> Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.geometryBuilder_ private
Definition at line 504 of file MessagesRobocupSslWrapper.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslWrapper.java