Documentation: CaptureGenerator Class Reference
CaptureGenerator Class Reference
#include <capture_generator.h>
Public Member Functions
CaptureGenerator (VarList *_settings, QObject *parent=0)
void mvc_connect (VarList *group)
~CaptureGenerator ()
virtual bool startCapture ()
virtual bool stopCapture ()
virtual bool isCapturing ()
virtual RawImage getFrame ()
virtual void releaseFrame ()
void cleanup ()
virtual bool copyAndConvertFrame (const RawImage &src, RawImage &target)
virtual string getCaptureMethodName () const
Public Member Functions inherited from CaptureInterface
CaptureInterface (VarList *_settings=0)
virtual ~CaptureInterface ()
virtual bool resetBus ()
virtual void readAllParameterValues ()
Protected Attributes
QMutex mutex
bool is_capturing
RawImage result
FrameLimiter limit
VarStringEnum * v_colorout
VarList * capture_settings
VarList * conversion_settings
VarInt * v_width
VarInt * v_height
VarDouble * v_framerate
VarBool * v_test_image
Additional Inherited Members
Data Fields inherited from CaptureInterface
VarList * settings
Detailed Description
Definition at line 41 of file capture_generator.h.
Constructor & Destructor Documentation
CaptureGenerator::CaptureGenerator (VarList * _settings, QObject * parent = 0)
Definition at line 27 of file capture_generator.cpp.
References VarTypes::VarList::addChild(), VarTypes::VarStringEnum::addItem(), capture_settings, COLOR_RGB8, COLOR_YUV422_UYVY, Colors::colorFormatToString(), conversion_settings, is_capturing, CaptureInterface::settings, v_colorout, v_framerate, v_height, v_test_image, and v_width.
                                                                            : QObject ( parent ), CaptureInterface ( _settings )
 #else
 CaptureGenerator::CaptureGenerator ( VarList * _settings ) : CaptureInterface ( _settings )
 #endif
 {
   is_capturing=false;
   settings->addChild ( conversion_settings = new VarList ( "Conversion Settings" ) );
   settings->addChild ( capture_settings = new VarList ( "Capture Settings" ) );
   //=======================CONVERSION SETTINGS=======================
   conversion_settings->addChild ( v_colorout=new VarStringEnum ( "convert to mode",Colors::colorFormatToString ( COLOR_YUV422_UYVY ) ) );
   v_colorout->addItem ( Colors::colorFormatToString ( COLOR_RGB8 ) );
   v_colorout->addItem ( Colors::colorFormatToString ( COLOR_YUV422_UYVY ) );
   //=======================CAPTURE SETTINGS==========================
   capture_settings->addChild ( v_framerate = new VarDouble ( "Framerate (FPS)", 60.0 ) );
   capture_settings->addChild ( v_width = new VarInt ( "Width (pixels)", 780 ) );
   capture_settings->addChild ( v_height = new VarInt ( "Height (pixels)", 580 ) );
   capture_settings->addChild ( v_test_image = new VarBool ( "Generate Color Test Image", false ) );
 }
CaptureGenerator::~CaptureGenerator ()
Definition at line 49 of file capture_generator.cpp.
 {
 }
Member Function Documentation
void CaptureGenerator::cleanup ()
Definition at line 59 of file capture_generator.cpp.
References is_capturing, and mutex.
Referenced by isCapturing(), and stopCapture().
 {
 #ifndef VDATA_NO_QT
   mutex.lock();
 #endif
   is_capturing=false;
 #ifndef VDATA_NO_QT
   mutex.unlock();
 #endif
 }
bool CaptureGenerator::copyAndConvertFrame (const RawImage & src, RawImage & target) virtual
Reimplemented from CaptureInterface.
Definition at line 85 of file capture_generator.cpp.
References RawImage::allocate(), COLOR_RGB8, COLOR_YUV422_UYVY, Colors::colorFormatToString(), RawImage::ensure_allocation(), RawImage::getColorFormat(), RawImage::getData(), RawImage::getHeight(), RawImage::getNumBytes(), VarTypes::VarStringEnum::getSelection(), RawImage::getTime(), RawImage::getWidth(), mutex, RawImage::setTime(), Colors::stringToColorFormat(), and v_colorout.
Referenced by isCapturing().
 {
 #ifndef VDATA_NO_QT
   mutex.lock();
 #endif
   ColorFormat output_fmt = Colors::stringToColorFormat ( v_colorout->getSelection().c_str() );
   ColorFormat src_fmt=src.getColorFormat();
   if ( target.getData() ==0 ) {
     target.allocate ( output_fmt, src.getWidth(), src.getHeight() );
   } else {
     target.ensure_allocation ( output_fmt, src.getWidth(), src.getHeight() );
   }
   target.setTime ( src.getTime() );
   if ( output_fmt == src_fmt ) {
     if ( src.getData() != 0 ) memcpy ( target.getData(),src.getData(),src.getNumBytes() );
   } else if ( src_fmt == COLOR_RGB8 && output_fmt == COLOR_YUV422_UYVY ) {
     if ( src.getData() != 0 ) {
       dc1394_convert_to_YUV422 ( src.getData(), target.getData(), src.getWidth(), src.getHeight(),
                                  DC1394_BYTE_ORDER_UYVY, DC1394_COLOR_CODING_RGB8, 8 );
     }
   } else {
     fprintf ( stderr,"Cannot copy and convert frame...unknown conversion selected from: %s to %s\n",
               Colors::colorFormatToString ( src_fmt ).c_str(),
               Colors::colorFormatToString ( output_fmt ).c_str() );
 #ifndef VDATA_NO_QT
     mutex.unlock();
 #endif
     return false;
   }
 #ifndef VDATA_NO_QT
   mutex.unlock();
 #endif
   return true;
 }
string CaptureGenerator::getCaptureMethodName () const virtual
Implements CaptureInterface.
Definition at line 189 of file capture_generator.cpp.
Referenced by isCapturing().
 {
   return "Image Generator";
 }
RawImage CaptureGenerator::getFrame () virtual
Implements CaptureInterface.
Definition at line 122 of file capture_generator.cpp.
References RawImage::allocate(), ColorRGB< num, fmt >::b, RGB::Black, RGB::Blue, kalman_filter::color, COLOR_RGB8, RGB::Cyan, ColorRGB< num, fmt >::g, VarTypes::VarBoolVal::getBool(), RawImage::getHeight(), VarTypes::VarInt::getInt(), GetTimeSec(), RawImage::getWidth(), RGB::Green, limit, GVector::max(), GVector::min(), mutex, RGB::Pink, ColorRGB< num, fmt >::r, RGB::Red, result, RawImage::setColorFormat(), RawImage::setTime(), v_height, v_test_image, v_width, FrameLimiter::waitForNextFrame(), RGB::White, role._GoToPoint::x, role._GoToPoint::y, and RGB::Yellow.
Referenced by isCapturing().
 {
 #ifndef VDATA_NO_QT
   mutex.lock();
 #endif
   limit.waitForNextFrame();
   result.setColorFormat ( COLOR_RGB8 );
   result.setTime ( GetTimeSec() );
   result.allocate ( COLOR_RGB8,v_width->getInt(),v_height->getInt() );
   rgbImage img;
   img.fromRawImage(result);
   if (v_test_image->getBool()) {
     int w = result.getWidth();
     int h = result.getHeight();
     int n_colors = 8;
     int slice_width = w/n_colors;
     rgb color=RGB::Black;
     rgb color2;
     for (int x = 0 ; x < w; x++) {
       int c_idx= x/slice_width;
       if (c_idx==0) {
         color=RGB::White;
       } else if (c_idx==1) {
         color=RGB::Red;
       } else if (c_idx==2) {
         color=RGB::Green;
       } else if (c_idx==3) {
         color=RGB::Blue;
       } else if (c_idx==4) {
         color=RGB::Cyan;
       } else if (c_idx==5) {
         color=RGB::Pink;
       } else if (c_idx==6) {
         color=RGB::Yellow;
       } else if (c_idx==7) {
         color=RGB::Black;
       }
       for (int y = 0 ; y < h; y++) {
         color2.r= max(0,min(255,((int)color.r * (h-1-y))/h));
         color2.g= max(0,min(255,((int)color.g * (h-1-y))/h));
         color2.b= max(0,min(255,((int)color.b * (h-1-y))/h));
         img.setPixel(x,y,color2);
       }
     }
   } else {
     img.fillBlack();
   }
 #ifndef VDATA_NO_QT
   mutex.unlock();
 #endif
   return result;
 }
virtual bool CaptureGenerator::isCapturing () inline virtual
Implements CaptureInterface.
Definition at line 81 of file capture_generator.h.
References cleanup(), copyAndConvertFrame(), getCaptureMethodName(), getFrame(), is_capturing, releaseFrame(), and role._GoToPoint::target.
 { return is_capturing; };
void CaptureGenerator::mvc_connect (VarList * group)
void CaptureGenerator::releaseFrame () virtual
Implements CaptureInterface.
Definition at line 178 of file capture_generator.cpp.
References mutex.
Referenced by isCapturing().
 {
 #ifndef VDATA_NO_QT
   mutex.lock();
 #endif
 #ifndef VDATA_NO_QT
   mutex.unlock();
 #endif
 }
bool CaptureGenerator::startCapture () virtual
Implements CaptureInterface.
Definition at line 70 of file capture_generator.cpp.
References VarTypes::VarDoubleVal::getDouble(), FrameLimiter::init(), is_capturing, limit, mutex, and v_framerate.
 {
 #ifndef VDATA_NO_QT
   mutex.lock();
 #endif
   limit.init ( v_framerate->getDouble() );
   is_capturing=true;
 #ifndef VDATA_NO_QT
   mutex.unlock();
 #endif
   return true;
 }
bool CaptureGenerator::stopCapture () virtual
Implements CaptureInterface.
Definition at line 53 of file capture_generator.cpp.
References cleanup().
 {
   cleanup();
   return true;
 }
Field Documentation
VarList* CaptureGenerator::capture_settings protected
Definition at line 62 of file capture_generator.h.
Referenced by CaptureGenerator().
VarList* CaptureGenerator::conversion_settings protected
Definition at line 63 of file capture_generator.h.
Referenced by CaptureGenerator().
bool CaptureGenerator::is_capturing protected
Definition at line 56 of file capture_generator.h.
Referenced by CaptureGenerator(), cleanup(), isCapturing(), and startCapture().
FrameLimiter CaptureGenerator::limit protected
Definition at line 58 of file capture_generator.h.
Referenced by getFrame(), and startCapture().
QMutex CaptureGenerator::mutex protected
Definition at line 51 of file capture_generator.h.
Referenced by cleanup(), copyAndConvertFrame(), getFrame(), releaseFrame(), and startCapture().
RawImage CaptureGenerator::result protected
Definition at line 57 of file capture_generator.h.
Referenced by getFrame().
VarStringEnum* CaptureGenerator::v_colorout protected
Definition at line 60 of file capture_generator.h.
Referenced by CaptureGenerator(), and copyAndConvertFrame().
VarDouble* CaptureGenerator::v_framerate protected
Definition at line 67 of file capture_generator.h.
Referenced by CaptureGenerator(), and startCapture().
VarInt* CaptureGenerator::v_height protected
Definition at line 66 of file capture_generator.h.
Referenced by CaptureGenerator(), and getFrame().
VarBool* CaptureGenerator::v_test_image protected
Definition at line 68 of file capture_generator.h.
Referenced by CaptureGenerator(), and getFrame().
VarInt* CaptureGenerator::v_width protected
Definition at line 65 of file capture_generator.h.
Referenced by CaptureGenerator(), and getFrame().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/capture/capture_generator.h
ssl-vision/src/shared/capture/capture_generator.cpp