Documentation: Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder Class Reference
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
MessagesRobocupSslGeometry.SSL_GeometryFieldSize getDefaultInstanceForType ()
MessagesRobocupSslGeometry.SSL_GeometryFieldSize build ()
MessagesRobocupSslGeometry.SSL_GeometryFieldSize buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (MessagesRobocupSslGeometry.SSL_GeometryFieldSize other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasLineWidth ()
int getLineWidth ()
Builder setLineWidth (int value)
Builder clearLineWidth ()
boolean hasFieldLength ()
int getFieldLength ()
Builder setFieldLength (int value)
Builder clearFieldLength ()
boolean hasFieldWidth ()
int getFieldWidth ()
Builder setFieldWidth (int value)
Builder clearFieldWidth ()
boolean hasBoundaryWidth ()
int getBoundaryWidth ()
Builder setBoundaryWidth (int value)
Builder clearBoundaryWidth ()
boolean hasRefereeWidth ()
int getRefereeWidth ()
Builder setRefereeWidth (int value)
Builder clearRefereeWidth ()
boolean hasGoalWidth ()
int getGoalWidth ()
Builder setGoalWidth (int value)
Builder clearGoalWidth ()
boolean hasGoalDepth ()
int getGoalDepth ()
Builder setGoalDepth (int value)
Builder clearGoalDepth ()
boolean hasGoalWallWidth ()
int getGoalWallWidth ()
Builder setGoalWallWidth (int value)
Builder clearGoalWallWidth ()
boolean hasCenterCircleRadius ()
int getCenterCircleRadius ()
Builder setCenterCircleRadius (int value)
Builder clearCenterCircleRadius ()
boolean hasDefenseRadius ()
int getDefenseRadius ()
Builder setDefenseRadius (int value)
Builder clearDefenseRadius ()
boolean hasDefenseStretch ()
int getDefenseStretch ()
Builder setDefenseStretch (int value)
Builder clearDefenseStretch ()
boolean hasFreeKickFromDefenseDist ()
int getFreeKickFromDefenseDist ()
Builder setFreeKickFromDefenseDist (int value)
Builder clearFreeKickFromDefenseDist ()
boolean hasPenaltySpotFromFieldLineDist ()
int getPenaltySpotFromFieldLineDist ()
Builder setPenaltySpotFromFieldLineDist (int value)
Builder clearPenaltySpotFromFieldLineDist ()
boolean hasPenaltyLineFromSpotDist ()
int getPenaltyLineFromSpotDist ()
Builder setPenaltyLineFromSpotDist (int value)
Builder clearPenaltyLineFromSpotDist ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
MessagesRobocupSslGeometry.SSL_GeometryFieldSize buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
int lineWidth_
int fieldLength_
int fieldWidth_
int boundaryWidth_
int refereeWidth_
int goalWidth_
int goalDepth_
int goalWallWidth_
int centerCircleRadius_
int defenseRadius_
int defenseStretch_
int freeKickFromDefenseDist_
int penaltySpotFromFieldLineDist_
int penaltyLineFromSpotDist_
Detailed Description
Definition at line 522 of file MessagesRobocupSslGeometry.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.Builder () inline private
Definition at line 536 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.Builder (BuilderParent parent) inline private
Definition at line 540 of file MessagesRobocupSslGeometry.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.build () inline
Definition at line 598 of file MessagesRobocupSslGeometry.java.
{
         MessagesRobocupSslGeometry.SSL_GeometryFieldSize result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 606 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.parseDelimitedFrom().
{
         MessagesRobocupSslGeometry.SSL_GeometryFieldSize result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.buildPartial () inline
Definition at line 616 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.lineWidth_.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeField().
{
         MessagesRobocupSslGeometry.SSL_GeometryFieldSize result = new MessagesRobocupSslGeometry.SSL_GeometryFieldSize(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         result.lineWidth_ = lineWidth_;
         if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
           to_bitField0_ |= 0x00000002;
         }
         result.fieldLength_ = fieldLength_;
         if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
           to_bitField0_ |= 0x00000004;
         }
         result.fieldWidth_ = fieldWidth_;
         if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
           to_bitField0_ |= 0x00000008;
         }
         result.boundaryWidth_ = boundaryWidth_;
         if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
           to_bitField0_ |= 0x00000010;
         }
         result.refereeWidth_ = refereeWidth_;
         if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
           to_bitField0_ |= 0x00000020;
         }
         result.goalWidth_ = goalWidth_;
         if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
           to_bitField0_ |= 0x00000040;
         }
         result.goalDepth_ = goalDepth_;
         if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
           to_bitField0_ |= 0x00000080;
         }
         result.goalWallWidth_ = goalWallWidth_;
         if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
           to_bitField0_ |= 0x00000100;
         }
         result.centerCircleRadius_ = centerCircleRadius_;
         if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
           to_bitField0_ |= 0x00000200;
         }
         result.defenseRadius_ = defenseRadius_;
         if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
           to_bitField0_ |= 0x00000400;
         }
         result.defenseStretch_ = defenseStretch_;
         if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
           to_bitField0_ |= 0x00000800;
         }
         result.freeKickFromDefenseDist_ = freeKickFromDefenseDist_;
         if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
           to_bitField0_ |= 0x00001000;
         }
         result.penaltySpotFromFieldLineDist_ = penaltySpotFromFieldLineDist_;
         if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
           to_bitField0_ |= 0x00002000;
         }
         result.penaltyLineFromSpotDist_ = penaltyLineFromSpotDist_;
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clear () inline
Definition at line 552 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clear().
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clear().
{
         super.clear();
         lineWidth_ = 0;
         bitField0_ = (bitField0_ & ~0x00000001);
         fieldLength_ = 0;
         bitField0_ = (bitField0_ & ~0x00000002);
         fieldWidth_ = 0;
         bitField0_ = (bitField0_ & ~0x00000004);
         boundaryWidth_ = 0;
         bitField0_ = (bitField0_ & ~0x00000008);
         refereeWidth_ = 0;
         bitField0_ = (bitField0_ & ~0x00000010);
         goalWidth_ = 0;
         bitField0_ = (bitField0_ & ~0x00000020);
         goalDepth_ = 0;
         bitField0_ = (bitField0_ & ~0x00000040);
         goalWallWidth_ = 0;
         bitField0_ = (bitField0_ & ~0x00000080);
         centerCircleRadius_ = 0;
         bitField0_ = (bitField0_ & ~0x00000100);
         defenseRadius_ = 0;
         bitField0_ = (bitField0_ & ~0x00000200);
         defenseStretch_ = 0;
         bitField0_ = (bitField0_ & ~0x00000400);
         freeKickFromDefenseDist_ = 0;
         bitField0_ = (bitField0_ & ~0x00000800);
         penaltySpotFromFieldLineDist_ = 0;
         bitField0_ = (bitField0_ & ~0x00001000);
         penaltyLineFromSpotDist_ = 0;
         bitField0_ = (bitField0_ & ~0x00002000);
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearBoundaryWidth () inline
Definition at line 974 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000008);
         boundaryWidth_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearCenterCircleRadius () inline
Definition at line 1079 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000100);
         centerCircleRadius_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearDefenseRadius () inline
Definition at line 1100 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000200);
         defenseRadius_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearDefenseStretch () inline
Definition at line 1121 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000400);
         defenseStretch_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearFieldLength () inline
Definition at line 932 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000002);
         fieldLength_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearFieldWidth () inline
Definition at line 953 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000004);
         fieldWidth_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearFreeKickFromDefenseDist () inline
Definition at line 1142 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000800);
         freeKickFromDefenseDist_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearGoalDepth () inline
Definition at line 1037 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000040);
         goalDepth_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearGoalWallWidth () inline
Definition at line 1058 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000080);
         goalWallWidth_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearGoalWidth () inline
Definition at line 1016 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000020);
         goalWidth_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearLineWidth () inline
Definition at line 911 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000001);
         lineWidth_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearPenaltyLineFromSpotDist () inline
Definition at line 1184 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.initFields().
{
         bitField0_ = (bitField0_ & ~0x00002000);
         penaltyLineFromSpotDist_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearPenaltySpotFromFieldLineDist () inline
Definition at line 1163 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00001000);
         penaltySpotFromFieldLineDist_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearRefereeWidth () inline
Definition at line 995 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000010);
         refereeWidth_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clone () inline
Definition at line 585 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.create () inline static private
Definition at line 548 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.newBuilder().
{
         return new Builder();
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getBoundaryWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 965 of file MessagesRobocupSslGeometry.java.
{
         return boundaryWidth_;
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getCenterCircleRadius () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1070 of file MessagesRobocupSslGeometry.java.
{
         return centerCircleRadius_;
       }
MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getDefaultInstanceForType () inline
Definition at line 594 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance().
{
         return MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance();
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getDefenseRadius () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1091 of file MessagesRobocupSslGeometry.java.
{
         return defenseRadius_;
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getDefenseStretch () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1112 of file MessagesRobocupSslGeometry.java.
{
         return defenseStretch_;
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getDescriptor () inline static
Definition at line 526 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.internal_static_SSL_GeometryFieldSize_descriptor.
{
         return MessagesRobocupSslGeometry.internal_static_SSL_GeometryFieldSize_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getDescriptorForType () inline
Definition at line 590 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDescriptor().
{
         return MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDescriptor();
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getFieldLength () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 923 of file MessagesRobocupSslGeometry.java.
{
         return fieldLength_;
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getFieldWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 944 of file MessagesRobocupSslGeometry.java.
{
         return fieldWidth_;
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getFreeKickFromDefenseDist () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1133 of file MessagesRobocupSslGeometry.java.
{
         return freeKickFromDefenseDist_;
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getGoalDepth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1028 of file MessagesRobocupSslGeometry.java.
{
         return goalDepth_;
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getGoalWallWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1049 of file MessagesRobocupSslGeometry.java.
{
         return goalWallWidth_;
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getGoalWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1007 of file MessagesRobocupSslGeometry.java.
{
         return goalWidth_;
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getLineWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 902 of file MessagesRobocupSslGeometry.java.
{
         return lineWidth_;
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getPenaltyLineFromSpotDist () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1175 of file MessagesRobocupSslGeometry.java.
{
         return penaltyLineFromSpotDist_;
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getPenaltySpotFromFieldLineDist () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1154 of file MessagesRobocupSslGeometry.java.
{
         return penaltySpotFromFieldLineDist_;
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getRefereeWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 986 of file MessagesRobocupSslGeometry.java.
{
         return refereeWidth_;
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasBoundaryWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 962 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000008) == 0x00000008);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasCenterCircleRadius () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1067 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000100) == 0x00000100);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasDefenseRadius () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1088 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000200) == 0x00000200);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasDefenseStretch () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1109 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000400) == 0x00000400);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasFieldLength () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 920 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000002) == 0x00000002);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasFieldWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 941 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000004) == 0x00000004);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasFreeKickFromDefenseDist () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1130 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000800) == 0x00000800);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasGoalDepth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1025 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000040) == 0x00000040);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasGoalWallWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1046 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000080) == 0x00000080);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasGoalWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1004 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000020) == 0x00000020);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasLineWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 899 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasPenaltyLineFromSpotDist () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1172 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00002000) == 0x00002000);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasPenaltySpotFromFieldLineDist () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 1151 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00001000) == 0x00001000);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.hasRefereeWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 983 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000010) == 0x00000010);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 531 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.internal_static_SSL_GeometryFieldSize_fieldAccessorTable.
{
         return MessagesRobocupSslGeometry.internal_static_SSL_GeometryFieldSize_fieldAccessorTable;
       }
final boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized () inline
Definition at line 738 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasBoundaryWidth(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasCenterCircleRadius(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasDefenseRadius(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasDefenseStretch(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasFieldLength(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasFieldWidth(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasFreeKickFromDefenseDist(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasGoalDepth(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasGoalWallWidth(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasGoalWidth(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasLineWidth(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasPenaltyLineFromSpotDist(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasPenaltySpotFromFieldLineDist(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasRefereeWidth().
{
         if (!hasLineWidth()) {
           return false;
         }
         if (!hasFieldLength()) {
           return false;
         }
         if (!hasFieldWidth()) {
           return false;
         }
         if (!hasBoundaryWidth()) {
           return false;
         }
         if (!hasRefereeWidth()) {
           return false;
         }
         if (!hasGoalWidth()) {
           return false;
         }
         if (!hasGoalDepth()) {
           return false;
         }
         if (!hasGoalWallWidth()) {
           return false;
         }
         if (!hasCenterCircleRadius()) {
           return false;
         }
         if (!hasDefenseRadius()) {
           return false;
         }
         if (!hasDefenseStretch()) {
           return false;
         }
         if (!hasFreeKickFromDefenseDist()) {
           return false;
         }
         if (!hasPenaltySpotFromFieldLineDist()) {
           return false;
         }
         if (!hasPenaltyLineFromSpotDist()) {
           return false;
         }
         return true;
       }
void Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.maybeForceBuilderInitialization () inline private
Definition at line 544 of file MessagesRobocupSslGeometry.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
         }
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 681 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clone(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeField(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeFrom(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.newBuilder().
{
         if (other instanceof MessagesRobocupSslGeometry.SSL_GeometryFieldSize) {
           return mergeFrom((MessagesRobocupSslGeometry.SSL_GeometryFieldSize)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.mergeFrom (MessagesRobocupSslGeometry.SSL_GeometryFieldSize other) inline
Definition at line 690 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance().
{
         if (other == MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance()) return this;
         if (other.hasLineWidth()) {
           setLineWidth(other.getLineWidth());
         }
         if (other.hasFieldLength()) {
           setFieldLength(other.getFieldLength());
         }
         if (other.hasFieldWidth()) {
           setFieldWidth(other.getFieldWidth());
         }
         if (other.hasBoundaryWidth()) {
           setBoundaryWidth(other.getBoundaryWidth());
         }
         if (other.hasRefereeWidth()) {
           setRefereeWidth(other.getRefereeWidth());
         }
         if (other.hasGoalWidth()) {
           setGoalWidth(other.getGoalWidth());
         }
         if (other.hasGoalDepth()) {
           setGoalDepth(other.getGoalDepth());
         }
         if (other.hasGoalWallWidth()) {
           setGoalWallWidth(other.getGoalWallWidth());
         }
         if (other.hasCenterCircleRadius()) {
           setCenterCircleRadius(other.getCenterCircleRadius());
         }
         if (other.hasDefenseRadius()) {
           setDefenseRadius(other.getDefenseRadius());
         }
         if (other.hasDefenseStretch()) {
           setDefenseStretch(other.getDefenseStretch());
         }
         if (other.hasFreeKickFromDefenseDist()) {
           setFreeKickFromDefenseDist(other.getFreeKickFromDefenseDist());
         }
         if (other.hasPenaltySpotFromFieldLineDist()) {
           setPenaltySpotFromFieldLineDist(other.getPenaltySpotFromFieldLineDist());
         }
         if (other.hasPenaltyLineFromSpotDist()) {
           setPenaltyLineFromSpotDist(other.getPenaltyLineFromSpotDist());
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 798 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.Builder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 8: {
               bitField0_ |= 0x00000001;
               lineWidth_ = input.readInt32();
               break;
             }
             case 16: {
               bitField0_ |= 0x00000002;
               fieldLength_ = input.readInt32();
               break;
             }
             case 24: {
               bitField0_ |= 0x00000004;
               fieldWidth_ = input.readInt32();
               break;
             }
             case 32: {
               bitField0_ |= 0x00000008;
               boundaryWidth_ = input.readInt32();
               break;
             }
             case 40: {
               bitField0_ |= 0x00000010;
               refereeWidth_ = input.readInt32();
               break;
             }
             case 48: {
               bitField0_ |= 0x00000020;
               goalWidth_ = input.readInt32();
               break;
             }
             case 56: {
               bitField0_ |= 0x00000040;
               goalDepth_ = input.readInt32();
               break;
             }
             case 64: {
               bitField0_ |= 0x00000080;
               goalWallWidth_ = input.readInt32();
               break;
             }
             case 72: {
               bitField0_ |= 0x00000100;
               centerCircleRadius_ = input.readInt32();
               break;
             }
             case 80: {
               bitField0_ |= 0x00000200;
               defenseRadius_ = input.readInt32();
               break;
             }
             case 88: {
               bitField0_ |= 0x00000400;
               defenseStretch_ = input.readInt32();
               break;
             }
             case 96: {
               bitField0_ |= 0x00000800;
               freeKickFromDefenseDist_ = input.readInt32();
               break;
             }
             case 104: {
               bitField0_ |= 0x00001000;
               penaltySpotFromFieldLineDist_ = input.readInt32();
               break;
             }
             case 112: {
               bitField0_ |= 0x00002000;
               penaltyLineFromSpotDist_ = input.readInt32();
               break;
             }
           }
         }
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setBoundaryWidth (int value) inline
Definition at line 968 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000008;
         boundaryWidth_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setCenterCircleRadius (int value) inline
Definition at line 1073 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000100;
         centerCircleRadius_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setDefenseRadius (int value) inline
Definition at line 1094 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000200;
         defenseRadius_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setDefenseStretch (int value) inline
Definition at line 1115 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000400;
         defenseStretch_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setFieldLength (int value) inline
Definition at line 926 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000002;
         fieldLength_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setFieldWidth (int value) inline
Definition at line 947 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000004;
         fieldWidth_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setFreeKickFromDefenseDist (int value) inline
Definition at line 1136 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000800;
         freeKickFromDefenseDist_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setGoalDepth (int value) inline
Definition at line 1031 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000040;
         goalDepth_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setGoalWallWidth (int value) inline
Definition at line 1052 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000080;
         goalWallWidth_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setGoalWidth (int value) inline
Definition at line 1010 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000020;
         goalWidth_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setLineWidth (int value) inline
Definition at line 905 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000001;
         lineWidth_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setPenaltyLineFromSpotDist (int value) inline
Definition at line 1178 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00002000;
         penaltyLineFromSpotDist_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setPenaltySpotFromFieldLineDist (int value) inline
Definition at line 1157 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00001000;
         penaltySpotFromFieldLineDist_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.setRefereeWidth (int value) inline
Definition at line 989 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000010;
         refereeWidth_ = value;
         onChanged();
         return this;
       }
Field Documentation
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.bitField0_ private
Definition at line 895 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.boundaryWidth_ private
Definition at line 961 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.centerCircleRadius_ private
Definition at line 1066 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.defenseRadius_ private
Definition at line 1087 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.defenseStretch_ private
Definition at line 1108 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.fieldLength_ private
Definition at line 919 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.fieldWidth_ private
Definition at line 940 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.freeKickFromDefenseDist_ private
Definition at line 1129 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.goalDepth_ private
Definition at line 1024 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.goalWallWidth_ private
Definition at line 1045 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.goalWidth_ private
Definition at line 1003 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.lineWidth_ private
Definition at line 898 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.penaltyLineFromSpotDist_ private
Definition at line 1171 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.penaltySpotFromFieldLineDist_ private
Definition at line 1150 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.refereeWidth_ private
Definition at line 982 of file MessagesRobocupSslGeometry.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslGeometry.java