Documentation: MultiStackRoboCupSSL Class Reference
MultiStackRoboCupSSL Class Reference
The multi-camera vision processing stack used for the RoboCup SSL vision system.
#include <multistack_robocup_ssl.h>
Public Slots
void RefreshNetworkOutput ()
void RefreshLegacyNetworkOutput ()
Public Member Functions
MultiStackRoboCupSSL (RenderOptions *_opts, int cameras)
virtual string getSettingsFileName ()
virtual ~MultiStackRoboCupSSL ()
Public Member Functions inherited from MultiVisionStack
MultiVisionStack (string _name, RenderOptions *_opts)
virtual ~MultiVisionStack ()
VarList * getSettings ()
virtual string getName ()
void start ()
void stop ()
Protected Attributes
RoboCupField * global_field
PluginDetectBallsSettings * global_ball_settings
PluginPublishGeometry * global_plugin_publish_geometry
PluginLegacyPublishGeometry * legacy_plugin_publish_geometry
CMPattern::TeamDetectorSettings * global_team_settings
CMPattern::TeamSelector * global_team_selector_blue
CMPattern::TeamSelector * global_team_selector_yellow
PluginSSLNetworkOutputSettings * global_network_output_settings
PluginLegacySSLNetworkOutputSettings * legacy_network_output_settings
RoboCupSSLServer * ds_udp_server_new
RoboCupSSLServer * ds_udp_server_old
Private Member Functions
void UpdateServerSettings (const int port, const string &address, const string &interface, const string &server_name, RoboCupSSLServer *server)
Additional Inherited Members
Data Fields inherited from MultiVisionStack
string name
RenderOptions * opts
VarList * settings
vector< CaptureThread * > threads
Protected Member Functions inherited from MultiVisionStack
void createThreads (int number)
Detailed Description
The multi-camera vision processing stack used for the RoboCup SSL vision system.
Author
Stefan Zickler, (C) 2008
Definition at line 39 of file multistack_robocup_ssl.h.
Constructor & Destructor Documentation
MultiStackRoboCupSSL::MultiStackRoboCupSSL (RenderOptions * _opts, int cameras)
Definition at line 23 of file multistack_robocup_ssl.cpp.
References VarTypes::VarList::addChild(), MultiVisionStack::createThreads(), PluginLegacySSLNetworkOutputSettings::ds_multicast_port_old, ds_udp_server_new, ds_udp_server_old, PluginSSLNetworkOutputSettings::getSettings(), CMPattern::TeamDetectorSettings::getSettings(), PluginLegacySSLNetworkOutputSettings::getSettings(), PluginDetectBallsSettings::getSettings(), CMPattern::TeamSelector::getSettings(), RoboCupField::getSettings(), global_ball_settings, global_field, global_network_output_settings, global_plugin_publish_geometry, global_team_selector_blue, global_team_selector_yellow, global_team_settings, velocity.pid_::i, legacy_network_output_settings, legacy_plugin_publish_geometry, PluginSSLNetworkOutputSettings::multicast_address, PluginLegacySSLNetworkOutputSettings::multicast_address, PluginSSLNetworkOutputSettings::multicast_interface, PluginLegacySSLNetworkOutputSettings::multicast_interface, PluginSSLNetworkOutputSettings::multicast_port, RefreshLegacyNetworkOutput(), RefreshNetworkOutput(), MultiVisionStack::settings, and MultiVisionStack::threads.
                                                                              :
     MultiVisionStack("RoboCup SSL Multi-Cam",_opts),
     ds_udp_server_new(NULL),
     ds_udp_server_old(NULL) {
   //add global field calibration parameter
   global_field = new RoboCupField();
   settings->addChild(global_field->getSettings());
   global_ball_settings = new PluginDetectBallsSettings();
   settings->addChild(global_ball_settings->getSettings());
   global_team_settings = new CMPattern::TeamDetectorSettings("robocup-ssl-teams.xml");
   settings->addChild(global_team_settings->getSettings());
   global_team_selector_blue = new CMPattern::TeamSelector("Blue Team", global_team_settings);
   settings->addChild(global_team_selector_blue->getSettings());
   global_team_selector_yellow = new CMPattern::TeamSelector("Yellow Team", global_team_settings);
   settings->addChild(global_team_selector_yellow->getSettings());
   global_network_output_settings = new PluginSSLNetworkOutputSettings();
   settings->addChild(global_network_output_settings->getSettings());
   connect(global_network_output_settings->multicast_port,
           SIGNAL(wasEdited(VarType *)),
           this,
           SLOT(RefreshNetworkOutput()));
   connect(global_network_output_settings->multicast_address,
           SIGNAL(wasEdited(VarType *)),
           this,
           SLOT(RefreshNetworkOutput()));
   connect(global_network_output_settings->multicast_interface,
           SIGNAL(wasEdited(VarType *)),
           this,
           SLOT(RefreshNetworkOutput()));
   legacy_network_output_settings = new PluginLegacySSLNetworkOutputSettings();
   settings->addChild(legacy_network_output_settings->getSettings());
   connect(legacy_network_output_settings->ds_multicast_port_old,
           SIGNAL(wasEdited(VarType *)),
           this,
           SLOT(RefreshLegacyNetworkOutput()));
   connect(legacy_network_output_settings->multicast_address,
           SIGNAL(wasEdited(VarType *)),
           this,
           SLOT(RefreshLegacyNetworkOutput()));
   connect(legacy_network_output_settings->multicast_interface,
           SIGNAL(wasEdited(VarType *)),
           this,
           SLOT(RefreshLegacyNetworkOutput()));
   ds_udp_server_new = new RoboCupSSLServer(10006, "224.5.23.2");
   ds_udp_server_old = new RoboCupSSLServer(10005, "224.5.23.2");
   global_plugin_publish_geometry = new  PluginPublishGeometry(
       0,
       ds_udp_server_new,
       *global_field);
   legacy_plugin_publish_geometry = new  PluginLegacyPublishGeometry(
       0,
       ds_udp_server_old,
       *global_field);
   //add parameter for number of cameras
   createThreads(cameras);
   unsigned int n = threads.size();
   for (unsigned int i = 0; i < n;i++) {
     threads[i]->setFrameBuffer(new FrameBuffer(5));
     threads[i]->setStack(
         new StackRoboCupSSL(
             _opts,threads[i]->getFrameBuffer(),
             i,
             global_field,
             global_ball_settings,
             global_plugin_publish_geometry,
             legacy_plugin_publish_geometry,
             global_team_selector_blue,
             global_team_selector_yellow,
             ds_udp_server_new,
             ds_udp_server_old,
             "robocup-ssl-cam-" + QString::number(i).toStdString()));
   }
   //TODO: make LUT widgets aware of each other for easy data-sharing
 }
MultiStackRoboCupSSL::~MultiStackRoboCupSSL () virtual
Definition at line 112 of file multistack_robocup_ssl.cpp.
References ds_udp_server_new, ds_udp_server_old, global_ball_settings, global_field, global_plugin_publish_geometry, and MultiVisionStack::stop().
{
   stop();
   delete ds_udp_server_new;
   delete ds_udp_server_old;
   delete global_plugin_publish_geometry;
   delete global_field;
   delete global_ball_settings;
 }
Member Function Documentation
string MultiStackRoboCupSSL::getSettingsFileName () virtual
Reimplemented from MultiVisionStack.
Definition at line 108 of file multistack_robocup_ssl.cpp.
{
   return "robocup-ssl";
 }
void MultiStackRoboCupSSL::RefreshLegacyNetworkOutput () slot
Definition at line 140 of file multistack_robocup_ssl.cpp.
References PluginLegacySSLNetworkOutputSettings::ds_multicast_port_old, ds_udp_server_old, VarTypes::VarInt::getInt(), VarTypes::VarStringVal::getString(), legacy_network_output_settings, PluginLegacySSLNetworkOutputSettings::multicast_address, and UpdateServerSettings().
Referenced by MultiStackRoboCupSSL().
{
   const string address =
       legacy_network_output_settings->multicast_address->getString();
   const string interface =
       legacy_network_output_settings->multicast_interface->getString();
   UpdateServerSettings(
       legacy_network_output_settings->ds_multicast_port_old->getInt(),
       address,
       interface,
       "DOUBLE-SIZE FIELD (OLD FORMAT)",
       ds_udp_server_old
   );
 }
void MultiStackRoboCupSSL::RefreshNetworkOutput () slot
Definition at line 154 of file multistack_robocup_ssl.cpp.
References ds_udp_server_new, VarTypes::VarInt::getInt(), VarTypes::VarStringVal::getString(), global_network_output_settings, PluginSSLNetworkOutputSettings::multicast_address, PluginSSLNetworkOutputSettings::multicast_interface, PluginSSLNetworkOutputSettings::multicast_port, and UpdateServerSettings().
Referenced by MultiStackRoboCupSSL().
 {
   UpdateServerSettings(
       global_network_output_settings->multicast_port->getInt(),
       global_network_output_settings->multicast_address->getString(),
       global_network_output_settings->multicast_interface->getString(),
       "DOUBLE-SIZE FIELD (NEW FORMAT)",
       ds_udp_server_new
   );
 }
void MultiStackRoboCupSSL::UpdateServerSettings (const int port, const string & address, const string & interface, const string & server_name, RoboCupSSLServer * server) private
Definition at line 121 of file multistack_robocup_ssl.cpp.
References RoboCupSSLServer::_net_address, RoboCupSSLServer::_net_interface, RoboCupSSLServer::_port, RoboCupSSLServer::close(), RoboCupSSLServer::mutex, RoboCupSSLServer::open(), and port().
Referenced by RefreshLegacyNetworkOutput(), and RefreshNetworkOutput().
{
   server->mutex.lock();
   server->close();
   server->_port = port;
   server->_net_address = address;
   server->_net_interface = interface;
   if (server->open()==false) {
     fprintf(stderr,
             "ERROR WHEN TRYING TO OPEN UDP NETWORK SERVER FOR %s!\n",
             server_name.c_str());
     fflush(stderr);
   }
   server->mutex.unlock();
 }
Field Documentation
RoboCupSSLServer* MultiStackRoboCupSSL::ds_udp_server_new protected
Definition at line 53 of file multistack_robocup_ssl.h.
Referenced by MultiStackRoboCupSSL(), RefreshNetworkOutput(), and ~MultiStackRoboCupSSL().
RoboCupSSLServer* MultiStackRoboCupSSL::ds_udp_server_old protected
Definition at line 55 of file multistack_robocup_ssl.h.
Referenced by MultiStackRoboCupSSL(), RefreshLegacyNetworkOutput(), and ~MultiStackRoboCupSSL().
PluginDetectBallsSettings* MultiStackRoboCupSSL::global_ball_settings protected
Definition at line 43 of file multistack_robocup_ssl.h.
Referenced by MultiStackRoboCupSSL(), and ~MultiStackRoboCupSSL().
RoboCupField* MultiStackRoboCupSSL::global_field protected
Definition at line 42 of file multistack_robocup_ssl.h.
Referenced by MultiStackRoboCupSSL(), and ~MultiStackRoboCupSSL().
PluginSSLNetworkOutputSettings* MultiStackRoboCupSSL::global_network_output_settings protected
Definition at line 49 of file multistack_robocup_ssl.h.
Referenced by MultiStackRoboCupSSL(), and RefreshNetworkOutput().
PluginPublishGeometry* MultiStackRoboCupSSL::global_plugin_publish_geometry protected
Definition at line 44 of file multistack_robocup_ssl.h.
Referenced by MultiStackRoboCupSSL(), and ~MultiStackRoboCupSSL().
CMPattern::TeamSelector* MultiStackRoboCupSSL::global_team_selector_blue protected
Definition at line 47 of file multistack_robocup_ssl.h.
Referenced by MultiStackRoboCupSSL().
CMPattern::TeamSelector* MultiStackRoboCupSSL::global_team_selector_yellow protected
Definition at line 48 of file multistack_robocup_ssl.h.
Referenced by MultiStackRoboCupSSL().
CMPattern::TeamDetectorSettings* MultiStackRoboCupSSL::global_team_settings protected
Definition at line 46 of file multistack_robocup_ssl.h.
Referenced by MultiStackRoboCupSSL().
PluginLegacySSLNetworkOutputSettings* MultiStackRoboCupSSL::legacy_network_output_settings protected
Definition at line 50 of file multistack_robocup_ssl.h.
Referenced by MultiStackRoboCupSSL(), and RefreshLegacyNetworkOutput().
PluginLegacyPublishGeometry* MultiStackRoboCupSSL::legacy_plugin_publish_geometry protected
Definition at line 45 of file multistack_robocup_ssl.h.
Referenced by MultiStackRoboCupSSL().
The documentation for this class was generated from the following files:
ssl-vision/src/app/stacks/multistack_robocup_ssl.h
ssl-vision/src/app/stacks/multistack_robocup_ssl.cpp