Documentation: ssl-vision/src/shared/util/quaternion.h File Reference
quaternion.h File Reference
A Quaternion class.
#include <iostream>
#include <cmath>
#include "gvector.h"
Data Structures
class Quaternion< num >
A Quaternion class.
Macros
#define PIOVER180 0.01745329251994329576923690768488612713442871888541725456097191440171
Functions
template<class num >
static Quaternion< num > operator* (const Quaternion< num > &q, const Quaternion< num > &r)
template<class num >
static Quaternion< num > shortestArc (const GVector::vector3d< num > &from, const GVector::vector3d< num > &to)
Detailed Description
A Quaternion class.
Author
Stefan Zickler, (C) 2007
Definition in file quaternion.h.
Macro Definition Documentation
#define PIOVER180 0.01745329251994329576923690768488612713442871888541725456097191440171
Definition at line 40 of file quaternion.h.
Function Documentation
template<class num > static Quaternion<num> operator* (const Quaternion< num > & q, const Quaternion< num > & r) static
Definition at line 346 of file quaternion.h.
References Quaternion< num >::w, Quaternion< num >::x, Quaternion< num >::y, and Quaternion< num >::z.
 {
   return Quaternion<num>(
            r.w * q.x + r.x * q.w + r.y * q.z - r.z * q.y,
            r.w * q.y - r.x * q.z + r.y * q.w + r.z * q.x,
            r.w * q.z + r.x * q.y - r.y * q.x + r.z * q.w,
            r.w * q.w - r.x * q.x - r.y * q.y - r.z * q.z
          );
 }
template<class num > static Quaternion<num> shortestArc (const GVector::vector3d< num > & from, const GVector::vector3d< num > & to) static
Definition at line 357 of file quaternion.h.
References GVector::vector3d< num >::cross(), GVector::cross(), GVector::vector3d< num >::dot(), GVector::dot(), GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
Referenced by GLCamera::freeLookAt().
 {
   GVector::vector3d<num> cross = from.cross(to); //Compute vector cross product
   num dot = from.dot(to) ;      //Compute dot product
   dot = (num) sqrt( 2*(dot+1) ) ; //We will use this equation twice
   cross /= dot ; //Get the x, y, z components
   if (std::isnan(cross.x) || std::isnan(cross.y) || std::isnan(cross.z) || std::isnan(-dot/2)) {
     printf("ERROR x: %f   y:%f   z: %f   w: %f\n",cross.x,cross.y,cross.z,-dot/2);
     fflush(stdout);
     exit(0);
   }
   //Return with the w component (Note that w is inverted because 3D has
   // left-handed rotations )
   return Quaternion<num>( cross.x, cross.y, cross.z, -dot/2 ) ;
 }