Documentation: NeuroWidget Class Reference
NeuroWidget Class Reference
#include <neurowidget.h>
Public Member Functions
int getStateChannel ()
GLLUTWidget * getGLLUTWidget ()
void samplePixel (const yuv &color)
void add_del_Pixel (yuv color, bool add, bool continuing_undo)
void sampleImage (const RawImage &img)
void focusInEvent (QFocusEvent *event)
void setStatusLabel (const QString &str_input)
void setSamplesLabel (int samples)
NeuroWidget (LUT3D *lut, LUTChannelMode mode)
~NeuroWidget ()
Data Fields
bool pending_loadnn
bool pending_train
bool pending_clear
int samples_captured
Protected Slots
void selectChannel (int c)
void is_clicked_btn_loadnn ()
void is_clicked_btn_train ()
void is_clicked_btn_clear ()
Protected Member Functions
void updateList (LUT3D *lut)
Protected Attributes
QBoxLayout * vbox
QBoxLayout * hbox
QListWidget * list
GLLUTWidget * gllut
QToolBar * toolbar
LUTChannelMode _mode
int currentChannel
Detailed Description
Definition at line 39 of file neurowidget.h.
Constructor & Destructor Documentation
NeuroWidget::NeuroWidget (LUT3D * lut, LUTChannelMode mode)
Definition at line 25 of file neurowidget.cpp.
References _mode, currentChannel, is_clicked_btn_clear(), is_clicked_btn_loadnn(), is_clicked_btn_train(), list, pending_loadnn, pending_train, selectChannel(), and updateList().
 {
   setupUi((QWidget*)this);
   _mode=mode;
   currentChannel = -1;
   pending_loadnn = false;
   pending_train = false;
   pending_train = false;
   //toolbar=new QToolBar();
   //vbox=new QBoxLayout(QBoxLayout::TopToBottom);
   //hbox=new QBoxLayout(QBoxLayout::LeftToRight);
   //btn_train = new QPushButton(tr("Train Neural Network"));
   connect(btn_train, SIGNAL(clicked()), SLOT(is_clicked_btn_train()));
   //btn_loadnn = new QPushButton(tr("Load Neural to LUT"));
   connect(btn_loadnn, SIGNAL(clicked()), SLOT(is_clicked_btn_loadnn()));
   //btn_clear = new QPushButton(tr("Clear Training Set"));
   connect(btn_clear, SIGNAL(clicked()), SLOT(is_clicked_btn_clear()));
   //gllut=new GLLUTWidget(mode,this);
   //gllut->setLUT(lut);
   list=new QListWidget(this);
   list->setGeometry(QRect(50,40,120,200));
   updateList(lut);
   connect(list,SIGNAL(currentRowChanged(int)),this, SLOT(selectChannel(int)));
   list->setFixedWidth(list->sizeHintForColumn ( 0 ) + 5 );
   list->setSizePolicy ( QSizePolicy::Preferred, QSizePolicy::Preferred );
   list->setFocusPolicy(Qt::NoFocus);
   setFocusPolicy(Qt::StrongFocus);
   //gllut->setSizePolicy ( QSizePolicy::Expanding, QSizePolicy::Expanding );
   //label->setSizePolicy( QSizePolicy::Preferred, QSizePolicy::Preferred );
   //toolbar->setIconSize(QSize(16,16));
   //toolbar->setSizePolicy( QSizePolicy::Preferred, QSizePolicy::Preferred );
   //vbox->setSpacing(2);
   //vbox->setMargin(0);
   //hbox->setSpacing(2);
   //hbox->setMargin(0);
   //hbox->addWidget(list);
   //vbox->addWidget(toolbar);
   //vbox->addLayout(hbox);
   //vbox->addWidget(label);
   //vbox->addWidget(btn_train);
   //vbox->addWidget(btn_loadnn);
   //vbox->addWidget(btn_clear);
   //this->setLayout(vbox);
   //addActions(gllut->actions());
   //toolbar->addActions(actions());
   //toolbar->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
                 //QList<QAction *> toolactions=gllut->actions();
                 //reverse the list so the icons appear in the right order:
                 // (qt really needs a list.reverse() function....)
                 /*for (int i=0;i<toolactions.size()/2;i++) {
                         toolactions.swap(i,toolactions.size()-(i+1));
                 }*/
                 //add the actions to the toolbar
 }
NeuroWidget::~NeuroWidget ()
Definition at line 111 of file neurowidget.cpp.
References gllut, hbox, list, toolbar, and vbox.
 {
   delete gllut;
   delete label;
   delete list;
   delete hbox;
   delete vbox;
   delete toolbar;
 }
Member Function Documentation
void NeuroWidget::add_del_Pixel (yuv color, bool add, bool continuing_undo)
void NeuroWidget::focusInEvent (QFocusEvent * event)
Definition at line 121 of file neurowidget.cpp.
{
   (void)event;
   //forward the focus to the actual widget that we contain
   //gllut->setFocus(Qt::OtherFocusReason);
 }
GLLUTWidget* NeuroWidget::getGLLUTWidget ()
int NeuroWidget::getStateChannel ()
Definition at line 128 of file neurowidget.cpp.
References currentChannel.
Referenced by PluginNeuralColorCalib::mouseEvent().
{
   return currentChannel;
 }
void NeuroWidget::is_clicked_btn_clear () protected slot
Definition at line 139 of file neurowidget.cpp.
References pending_clear.
Referenced by NeuroWidget().
{
     pending_clear = true;
 }
void NeuroWidget::is_clicked_btn_loadnn () protected slot
Definition at line 132 of file neurowidget.cpp.
References pending_loadnn.
Referenced by NeuroWidget().
{
     pending_loadnn = true;
 }
void NeuroWidget::is_clicked_btn_train () protected slot
Definition at line 136 of file neurowidget.cpp.
References pending_train.
Referenced by NeuroWidget().
{
     pending_train = true;
 }
void NeuroWidget::sampleImage (const RawImage & img)
void NeuroWidget::samplePixel (const yuv & color)
void NeuroWidget::selectChannel (int c) protected slot
Definition at line 90 of file neurowidget.cpp.
References currentChannel.
Referenced by NeuroWidget().
{
   if (c!=(-1)) {
     currentChannel = c;
   }
 }
void NeuroWidget::setSamplesLabel (int samples)
Definition at line 147 of file neurowidget.cpp.
Referenced by PluginNeuralColorCalib::mouseEvent(), and PluginNeuralColorCalib::process().
{
     this->lbl_sample->setText("Samples Captured: "+QString::number(samples));
 }
void NeuroWidget::setStatusLabel (const QString & str_input)
Definition at line 143 of file neurowidget.cpp.
Referenced by PluginNeuralColorCalib::process().
{
     this->label->setText(str_input);
 }
void NeuroWidget::updateList (LUT3D * lut) protected
Definition at line 96 of file neurowidget.cpp.
References LUT3D::channels, velocity.pid_::i, and list.
Referenced by NeuroWidget().
{
   QListWidgetItem * item;
   for (unsigned int i=0;i<lut->channels.size();i++) {
     item=new QListWidgetItem(QString::fromStdString(lut->channels[i].label));
     QPixmap p(16,16);
     p.fill(QColor(lut->channels[i].draw_color.r,lut->channels[i].draw_color.g,lut->channels[i].draw_color.b));
     QPainter painter(&p);
     painter.setPen(QPen(QColor(0,0,0),1));
     painter.drawRect(0,0,15,15);
     item->setIcon(p);
     list->addItem(item);
   }
 }
Field Documentation
LUTChannelMode NeuroWidget::_mode protected
Definition at line 54 of file neurowidget.h.
Referenced by NeuroWidget().
int NeuroWidget::currentChannel protected
Definition at line 55 of file neurowidget.h.
Referenced by getStateChannel(), NeuroWidget(), and selectChannel().
GLLUTWidget* NeuroWidget::gllut protected
Definition at line 51 of file neurowidget.h.
Referenced by ~NeuroWidget().
QBoxLayout* NeuroWidget::hbox protected
Definition at line 47 of file neurowidget.h.
Referenced by ~NeuroWidget().
QListWidget* NeuroWidget::list protected
Definition at line 48 of file neurowidget.h.
Referenced by NeuroWidget(), updateList(), and ~NeuroWidget().
bool NeuroWidget::pending_clear
Definition at line 64 of file neurowidget.h.
Referenced by is_clicked_btn_clear(), and PluginNeuralColorCalib::process().
bool NeuroWidget::pending_loadnn
Definition at line 62 of file neurowidget.h.
Referenced by is_clicked_btn_loadnn(), NeuroWidget(), and PluginNeuralColorCalib::process().
bool NeuroWidget::pending_train
Definition at line 63 of file neurowidget.h.
Referenced by is_clicked_btn_train(), NeuroWidget(), and PluginNeuralColorCalib::process().
int NeuroWidget::samples_captured
Definition at line 65 of file neurowidget.h.
QToolBar* NeuroWidget::toolbar protected
Definition at line 52 of file neurowidget.h.
Referenced by ~NeuroWidget().
QBoxLayout* NeuroWidget::vbox protected
Definition at line 46 of file neurowidget.h.
Referenced by ~NeuroWidget().
The documentation for this class was generated from the following files:
ssl-vision/src/app/gui/neurowidget.h
ssl-vision/src/app/gui/neurowidget.cpp