Documentation: vision_comm/include/timer.h File Reference
timer.h File Reference
#include <sys/types.h>
#include <signal.h>
#include <unistd.h>
#include <stdint.h>
#include <stdio.h>
#include <sys/time.h>
#include <time.h>
Data Structures
class Timer
a basic timer class
class AccumulativeTimer
a basic timer class
class CycleTimer
class StageCycleTimer< num >
class FunctionTimer
class FunctionCycleTimer
Typedefs
typedef uint32_t cycle_t
typedef uint64_t cycle64_t
Functions
unsigned GetTimeUSec ()
double GetTimeSec ()
void GetDate (struct tm &date)
double GetCPUClockRateMHz ()
double GetCPUClockPeriod ()
void Sleep (double sec)
Typedef Documentation
typedef uint64_t cycle64_t
Definition at line 114 of file timer.h.
typedef uint32_t cycle_t
Definition at line 113 of file timer.h.
Function Documentation
double GetCPUClockPeriod ()
double GetCPUClockRateMHz ()
void GetDate (struct tm & date) inline
Definition at line 170 of file timer.h.
References GetCPUClockPeriod(), GetCPUClockRateMHz(), t, and Timer::time().
 {
   time_t t = time(NULL);
   localtime_r(&t,&date);
 }
double GetTimeSec () inline
Definition at line 157 of file timer.h.
 {
 #ifdef Apertos
   struct SystemTime time;
   GetSystemTime(&time);
   return((double)time.seconds + time.useconds*(1.0E-6));
 #else
   timeval tv;
   gettimeofday(&tv,NULL);
   return((double)tv.tv_sec + tv.tv_usec*(1.0E-6));
 #endif
 }
unsigned GetTimeUSec () inline
Definition at line 144 of file timer.h.
 {
 #ifdef Apertos
   struct SystemTime time;
   GetSystemTime(&time);
   return(time.seconds*1000000 + time.useconds);
 #else
   timeval tv;
   gettimeofday(&tv,NULL);
   return(tv.tv_sec*1000000 + tv.tv_usec);
 #endif
 }
void Sleep (double sec) inline
Definition at line 225 of file timer.h.
 {
   usleep((int)(sec * 1E6));
 }