Documentation: SSL_GeometryData Class Reference
SSL_GeometryData Class Reference
#include <messages_robocup_ssl_geometry.pb.h>
Public Member Functions
SSL_GeometryData ()
virtual ~SSL_GeometryData ()
SSL_GeometryData (const SSL_GeometryData &from)
SSL_GeometryData & operator= (const SSL_GeometryData &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_GeometryData *other)
SSL_GeometryData * New () const PROTOBUF_FINAL
SSL_GeometryData * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_GeometryData &from)
void MergeFrom (const SSL_GeometryData &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_field () const
void clear_field ()
const ::SSL_GeometryFieldSize & field () const
::SSL_GeometryFieldSize * mutable_field ()
::SSL_GeometryFieldSize * release_field ()
void set_allocated_field (::SSL_GeometryFieldSize *field)
int calib_size () const
void clear_calib ()
const ::SSL_GeometryCameraCalibration & calib (int index) const
::SSL_GeometryCameraCalibration * mutable_calib (int index)
::SSL_GeometryCameraCalibration * add_calib ()
::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration > * mutable_calib ()
const ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration > & calib () const
SSL_GeometryData ()
virtual ~SSL_GeometryData ()
SSL_GeometryData (const SSL_GeometryData &from)
SSL_GeometryData & operator= (const SSL_GeometryData &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_GeometryData *other)
SSL_GeometryData * New () const PROTOBUF_FINAL
SSL_GeometryData * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_GeometryData &from)
void MergeFrom (const SSL_GeometryData &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
int calib_size () const
void clear_calib ()
const ::SSL_GeometryCameraCalibration & calib (int index) const
::SSL_GeometryCameraCalibration * mutable_calib (int index)
::SSL_GeometryCameraCalibration * add_calib ()
::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration > * mutable_calib ()
const ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration > & calib () const
bool has_field () const
void clear_field ()
const ::SSL_GeometryFieldSize & field () const
::SSL_GeometryFieldSize * release_field ()
::SSL_GeometryFieldSize * mutable_field ()
void set_allocated_field (::SSL_GeometryFieldSize *field)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_GeometryData & default_instance ()
static const SSL_GeometryData * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_GeometryData & default_instance ()
static void InitAsDefaultInstance ()
static const SSL_GeometryData * internal_default_instance ()
Static Public Attributes
static const int kFieldFieldNumber = 1
static const int kCalibFieldNumber = 2
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_GeometryData *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_field ()
void clear_has_field ()
friendconst::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5fgeometry_2eproto ()
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_GeometryData *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_field ()
void clear_has_field ()
friend void::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryDataImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration > calib_
::SSL_GeometryFieldSize * field_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::TableStruct
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto_impl ()
void protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_impl ()
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto ()
void swap (SSL_GeometryData &a, SSL_GeometryData &b)
Detailed Description
Definition at line 519 of file messages_robocup_ssl_geometry.pb.h.
Constructor & Destructor Documentation
SSL_GeometryData::SSL_GeometryData ()
virtual SSL_GeometryData::~SSL_GeometryData () virtual
SSL_GeometryData::SSL_GeometryData (const SSL_GeometryData & from)
SSL_GeometryData::SSL_GeometryData ()
virtual SSL_GeometryData::~SSL_GeometryData () virtual
SSL_GeometryData::SSL_GeometryData (const SSL_GeometryData & from)
Member Function Documentation
SSL_GeometryCameraCalibration * SSL_GeometryData::add_calib () inline
Definition at line 1402 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and PluginPublishGeometry::sendGeometry().
{
   // @@protoc_insertion_point(field_add:SSL_GeometryData.calib)
   return calib_.Add();
 }
::SSL_GeometryCameraCalibration* SSL_GeometryData::add_calib ()
size_t SSL_GeometryData::ByteSizeLong () const
size_t SSL_GeometryData::ByteSizeLong () const
const ::SSL_GeometryCameraCalibration & SSL_GeometryData::calib (int index) const inline
Definition at line 1394 of file messages_robocup_ssl_geometry.pb.h.
Referenced by main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryData.calib)
   return calib_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::SSL_GeometryCameraCalibration > & SSL_GeometryData::calib () const inline
Definition at line 1412 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   // @@protoc_insertion_point(field_list:SSL_GeometryData.calib)
   return calib_;
 }
const ::SSL_GeometryCameraCalibration& SSL_GeometryData::calib (int index) const
const ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration >& SSL_GeometryData::calib () const
int SSL_GeometryData::calib_size () const inline
Definition at line 1388 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and main().
{
   return calib_.size();
 }
int SSL_GeometryData::calib_size () const
void SSL_GeometryData::Clear ()
void SSL_GeometryData::Clear ()
void SSL_GeometryData::clear_calib () inline
Definition at line 1391 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   calib_.Clear();
 }
void SSL_GeometryData::clear_calib ()
void SSL_GeometryData::clear_field () inline
Definition at line 1352 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   if (field_ != NULL) field_->::SSL_GeometryFieldSize::Clear();
   clear_has_field();
 }
void SSL_GeometryData::clear_field ()
void SSL_GeometryData::clear_has_field () inline private
Definition at line 1349 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00000001u;
 }
void SSL_GeometryData::clear_has_field () private
void SSL_GeometryData::CopyFrom (const ::google::protobuf::Message & from)
Referenced by RoboCupSSLServer::open(), and RoboCupSSLServer::send().
void SSL_GeometryData::CopyFrom (const SSL_GeometryData & from)
void SSL_GeometryData::CopyFrom (const ::google::protobuf::Message & from)
void SSL_GeometryData::CopyFrom (const SSL_GeometryData & from)
static const SSL_GeometryData& SSL_GeometryData::default_instance () static
static const SSL_GeometryData& SSL_GeometryData::default_instance () static
static const ::google::protobuf::Descriptor* SSL_GeometryData::descriptor () static
static const ::google::protobuf::Descriptor* SSL_GeometryData::descriptor () static
const ::SSL_GeometryFieldSize & SSL_GeometryData::field () const inline
Definition at line 1356 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::internal_default_instance().
Referenced by ViewUpdateThread::execute(), SSL_GeometryFieldSize::field_arcs(), main(), and MyThread::run().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryData.field)
   return field_ != NULL ? *field_
                          : *::SSL_GeometryFieldSize::internal_default_instance();
 }
const ::SSL_GeometryFieldSize& SSL_GeometryData::field () const
inline ::google::protobuf::Arena* SSL_GeometryData::GetArenaNoVirtual () const inline private
Definition at line 579 of file messages_robocup_ssl_geometry.pb.h.
{
     return NULL;
   }
inline ::google::protobuf::Arena* SSL_GeometryData::GetArenaNoVirtual () const inline private
Definition at line 1045 of file messages_robocup_ssl_geometry.pb.h.
{
     return NULL;
   }
int SSL_GeometryData::GetCachedSize () const inline
Definition at line 572 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_cached_size_, SSL_GeometryFieldSize::InternalSwap(), SSL_GeometryFieldSize::SetCachedSize(), SSL_GeometryFieldSize::SharedCtor(), and SSL_GeometryFieldSize::SharedDtor().
 { return _cached_size_; }
int SSL_GeometryData::GetCachedSize () const inline
Definition at line 1038 of file messages_robocup_ssl_geometry.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata SSL_GeometryData::GetMetadata () const
::google::protobuf::Metadata SSL_GeometryData::GetMetadata () const
bool SSL_GeometryData::has_field () const inline
Definition at line 1343 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool SSL_GeometryData::has_field () const
static void SSL_GeometryData::InitAsDefaultInstance () static
static const SSL_GeometryData* SSL_GeometryData::internal_default_instance () inline static
Definition at line 542 of file messages_robocup_ssl_geometry.pb.h.
References _SSL_GeometryData_default_instance_, and SSL_GeometryFieldSize::Swap().
Referenced by SSL_WrapperPacket::geometry().
{
     return reinterpret_cast<const SSL_GeometryData*>(
                &_SSL_GeometryData_default_instance_);
   }
static const SSL_GeometryData* SSL_GeometryData::internal_default_instance () inline static
Definition at line 1007 of file messages_robocup_ssl_geometry.pb.h.
References _SSL_GeometryData_default_instance_.
{
     return reinterpret_cast<const SSL_GeometryData*>(
                &_SSL_GeometryData_default_instance_);
   }
::google::protobuf::uint8* SSL_GeometryData::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
::google::protobuf::uint8* SSL_GeometryData::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void SSL_GeometryData::InternalSwap (SSL_GeometryData * other) private
void SSL_GeometryData::InternalSwap (SSL_GeometryData * other) private
bool SSL_GeometryData::IsInitialized () const
bool SSL_GeometryData::IsInitialized () const
void* SSL_GeometryData::MaybeArenaPtr () const inline private
Definition at line 582 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::GetMetadata().
{
     return NULL;
   }
void* SSL_GeometryData::MaybeArenaPtr () const inline private
Definition at line 1048 of file messages_robocup_ssl_geometry.pb.h.
{
     return NULL;
   }
void SSL_GeometryData::MergeFrom (const ::google::protobuf::Message & from)
void SSL_GeometryData::MergeFrom (const SSL_GeometryData & from)
void SSL_GeometryData::MergeFrom (const ::google::protobuf::Message & from)
void SSL_GeometryData::MergeFrom (const SSL_GeometryData & from)
bool SSL_GeometryData::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
bool SSL_GeometryData::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
SSL_GeometryCameraCalibration * SSL_GeometryData::mutable_calib (int index) inline
Definition at line 1398 of file messages_robocup_ssl_geometry.pb.h.
{
   // @@protoc_insertion_point(field_mutable:SSL_GeometryData.calib)
   return calib_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::SSL_GeometryCameraCalibration > * SSL_GeometryData::mutable_calib () inline
Definition at line 1407 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   // @@protoc_insertion_point(field_mutable_list:SSL_GeometryData.calib)
   return &calib_;
 }
::SSL_GeometryCameraCalibration* SSL_GeometryData::mutable_calib (int index)
::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration >* SSL_GeometryData::mutable_calib ()
SSL_GeometryFieldSize * SSL_GeometryData::mutable_field () inline
Definition at line 1361 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), SSLWorld::generatePacket(), and PluginPublishGeometry::sendGeometry().
{
   set_has_field();
   if (field_ == NULL) {
     field_ = new ::SSL_GeometryFieldSize;
   }
   // @@protoc_insertion_point(field_mutable:SSL_GeometryData.field)
   return field_;
 }
::SSL_GeometryFieldSize* SSL_GeometryData::mutable_field ()
inline ::google::protobuf::UnknownFieldSet* SSL_GeometryData::mutable_unknown_fields () inline
Definition at line 535 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_internal_metadata_, SSL_GeometryFieldSize::default_instance(), and SSL_GeometryFieldSize::descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
inline ::google::protobuf::UnknownFieldSet* SSL_GeometryData::mutable_unknown_fields () inline
Definition at line 999 of file messages_robocup_ssl_geometry.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
SSL_GeometryData* SSL_GeometryData::New () const inline
Definition at line 551 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::ByteSizeLong(), SSL_GeometryFieldSize::Clear(), SSL_GeometryFieldSize::CopyFrom(), SSL_GeometryFieldSize::InternalSerializeWithCachedSizesToArray(), SSL_GeometryFieldSize::IsInitialized(), SSL_GeometryFieldSize::MergeFrom(), SSL_GeometryFieldSize::MergePartialFromCodedStream(), SSL_GeometryFieldSize::New(), New(), SSL_GeometryFieldSize::SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_GeometryData* SSL_GeometryData::New (::google::protobuf::Arena * arena) const
SSL_GeometryData* SSL_GeometryData::New () const inline
Definition at line 1021 of file messages_robocup_ssl_geometry.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_GeometryData* SSL_GeometryData::New (::google::protobuf::Arena * arena) const
SSL_GeometryData& SSL_GeometryData::operator= (const SSL_GeometryData & from) inline
Definition at line 526 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
SSL_GeometryData& SSL_GeometryData::operator= (const SSL_GeometryData & from) inline
Definition at line 977 of file messages_robocup_ssl_geometry.pb.h.
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* SSL_GeometryData::protobuf_Offsets_messages_5frobocup_5fssl_5fgeometry_2eproto () private
SSL_GeometryFieldSize * SSL_GeometryData::release_field () inline
Definition at line 1369 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   // @@protoc_insertion_point(field_release:SSL_GeometryData.field)
   clear_has_field();
   ::SSL_GeometryFieldSize* temp = field_;
   field_ = NULL;
   return temp;
 }
::SSL_GeometryFieldSize* SSL_GeometryData::release_field ()
void SSL_GeometryData::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void SSL_GeometryData::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* SSL_GeometryData::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 568 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void SSL_GeometryData::set_allocated_field (::SSL_GeometryFieldSize * field) inline
Definition at line 1376 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   delete field_;
   field_ = field;
   if (field) {
     set_has_field();
   } else {
     clear_has_field();
   }
   // @@protoc_insertion_point(field_set_allocated:SSL_GeometryData.field)
 }
void SSL_GeometryData::set_allocated_field (::SSL_GeometryFieldSize * field)
void SSL_GeometryData::set_has_field () inline private
Definition at line 1346 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00000001u;
 }
void SSL_GeometryData::set_has_field () private
void SSL_GeometryData::SetCachedSize (int size) const private
void SSL_GeometryData::SetCachedSize (int size) const private
void SSL_GeometryData::SharedCtor () private
void SSL_GeometryData::SharedCtor () private
void SSL_GeometryData::SharedDtor () private
void SSL_GeometryData::SharedDtor () private
void SSL_GeometryData::Swap (SSL_GeometryData * other)
void SSL_GeometryData::Swap (SSL_GeometryData * other)
const ::google::protobuf::UnknownFieldSet& SSL_GeometryData::unknown_fields () const inline
Definition at line 531 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
const ::google::protobuf::UnknownFieldSet& SSL_GeometryData::unknown_fields () const inline
Definition at line 996 of file messages_robocup_ssl_geometry.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
SSL_GeometryData::void::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryDataImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::TableStruct friend
Definition at line 1090 of file messages_robocup_ssl_geometry.pb.h.
void protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_impl () friend
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto_impl () friend
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto () friend
void swap (SSL_GeometryData & a, SSL_GeometryData & b) friend
Definition at line 1015 of file messages_robocup_ssl_geometry.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int SSL_GeometryData::_cached_size_ mutable private
Definition at line 621 of file messages_robocup_ssl_geometry.pb.h.
google::protobuf::internal::HasBits< 1 > SSL_GeometryData::_has_bits_ private
Definition at line 620 of file messages_robocup_ssl_geometry.pb.h.
google::protobuf::internal::InternalMetadataWithArena SSL_GeometryData::_internal_metadata_ private
Definition at line 619 of file messages_robocup_ssl_geometry.pb.h.
google::protobuf::RepeatedPtrField<::SSL_GeometryCameraCalibration > SSL_GeometryData::calib_ private
Definition at line 622 of file messages_robocup_ssl_geometry.pb.h.
SSL_GeometryFieldSize * SSL_GeometryData::field_ private
Definition at line 623 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryData::kCalibFieldNumber = 2 static
Definition at line 605 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryData::kFieldFieldNumber = 1 static
Definition at line 596 of file messages_robocup_ssl_geometry.pb.h.
PROTOBUF_CONSTEXPR int const SSL_GeometryData::kIndexInFileMessages static
Initial value:
=
    5
Definition at line 1011 of file messages_robocup_ssl_geometry.pb.h.
The documentation for this class was generated from the following file:
grsim_comm/include/proto/messages_robocup_ssl_geometry.pb.h