Documentation: grSim_RobotReplacement Class Reference
grSim_RobotReplacement Class Reference
#include <grSim_Replacement.pb.h>
Public Member Functions
grSim_RobotReplacement ()
virtual ~grSim_RobotReplacement ()
grSim_RobotReplacement (const grSim_RobotReplacement &from)
grSim_RobotReplacement & operator= (const grSim_RobotReplacement &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (grSim_RobotReplacement *other)
grSim_RobotReplacement * New () const PROTOBUF_FINAL
grSim_RobotReplacement * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const grSim_RobotReplacement &from)
void MergeFrom (const grSim_RobotReplacement &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_x () const
void clear_x ()
double x () const
void set_x (double value)
bool has_y () const
void clear_y ()
double y () const
void set_y (double value)
bool has_dir () const
void clear_dir ()
double dir () const
void set_dir (double value)
bool has_id () const
void clear_id ()
::google::protobuf::uint32 id () const
void set_id (::google::protobuf::uint32 value)
bool has_yellowteam () const
void clear_yellowteam ()
bool yellowteam () const
void set_yellowteam (bool value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const grSim_RobotReplacement & default_instance ()
static const grSim_RobotReplacement * internal_default_instance ()
Static Public Attributes
static const int kXFieldNumber = 1
static const int kYFieldNumber = 2
static const int kDirFieldNumber = 3
static const int kIdFieldNumber = 4
static const int kYellowteamFieldNumber = 5
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (grSim_RobotReplacement *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_x ()
void clear_has_x ()
void set_has_y ()
void clear_has_y ()
void set_has_dir ()
void clear_has_dir ()
void set_has_id ()
void clear_has_id ()
void set_has_yellowteam ()
void clear_has_yellowteam ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_grSim_5fReplacement_2eproto ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
double x_
double y_
double dir_
::google::protobuf::uint32 id_
bool yellowteam_
Friends
void protobuf_InitDefaults_grSim_5fReplacement_2eproto_impl ()
void protobuf_AddDesc_grSim_5fReplacement_2eproto_impl ()
void protobuf_ShutdownFile_grSim_5fReplacement_2eproto ()
Detailed Description
Definition at line 47 of file grSim_Replacement.pb.h.
Constructor & Destructor Documentation
grSim_RobotReplacement::grSim_RobotReplacement ()
virtual grSim_RobotReplacement::~grSim_RobotReplacement () virtual
grSim_RobotReplacement::grSim_RobotReplacement (const grSim_RobotReplacement & from)
Member Function Documentation
size_t grSim_RobotReplacement::ByteSizeLong () const
Referenced by New(), grSim_BallReplacement::New(), and grSim_Replacement::New().
void grSim_RobotReplacement::Clear ()
Referenced by New(), grSim_BallReplacement::New(), and grSim_Replacement::New().
void grSim_RobotReplacement::clear_dir () inline
Definition at line 496 of file grSim_Replacement.pb.h.
References clear_has_dir(), and dir_.
{
   dir_ = 0;
   clear_has_dir();
 }
void grSim_RobotReplacement::clear_has_dir () inline private
Definition at line 493 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by clear_dir().
{
   _has_bits_[0] &= ~0x00000004u;
 }
void grSim_RobotReplacement::clear_has_id () inline private
Definition at line 517 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by clear_id().
{
   _has_bits_[0] &= ~0x00000008u;
 }
void grSim_RobotReplacement::clear_has_x () inline private
Definition at line 445 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by clear_x(), and grSim_BallReplacement::clear_x().
{
   _has_bits_[0] &= ~0x00000001u;
 }
void grSim_RobotReplacement::clear_has_y () inline private
Definition at line 469 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by clear_y(), and grSim_BallReplacement::clear_y().
{
   _has_bits_[0] &= ~0x00000002u;
 }
void grSim_RobotReplacement::clear_has_yellowteam () inline private
Definition at line 541 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by clear_yellowteam().
{
   _has_bits_[0] &= ~0x00000010u;
 }
void grSim_RobotReplacement::clear_id () inline
Definition at line 520 of file grSim_Replacement.pb.h.
References clear_has_id(), and id_.
{
   id_ = 0u;
   clear_has_id();
 }
void grSim_RobotReplacement::clear_x () inline
Definition at line 448 of file grSim_Replacement.pb.h.
References clear_has_x(), and x_.
Referenced by MaybeArenaPtr(), and grSim_BallReplacement::MaybeArenaPtr().
{
   x_ = 0;
   clear_has_x();
 }
void grSim_RobotReplacement::clear_y () inline
Definition at line 472 of file grSim_Replacement.pb.h.
References clear_has_y(), and y_.
{
   y_ = 0;
   clear_has_y();
 }
void grSim_RobotReplacement::clear_yellowteam () inline
Definition at line 544 of file grSim_Replacement.pb.h.
References clear_has_yellowteam(), and yellowteam_.
{
   yellowteam_ = false;
   clear_has_yellowteam();
 }
void grSim_RobotReplacement::CopyFrom (const ::google::protobuf::Message & from)
Referenced by New(), grSim_BallReplacement::New(), grSim_Replacement::New(), operator=(), grSim_BallReplacement::operator=(), and grSim_Replacement::operator=().
void grSim_RobotReplacement::CopyFrom (const grSim_RobotReplacement & from)
static const grSim_RobotReplacement& grSim_RobotReplacement::default_instance () static
Referenced by mutable_unknown_fields(), grSim_BallReplacement::mutable_unknown_fields(), and grSim_Replacement::mutable_unknown_fields().
static const ::google::protobuf::Descriptor* grSim_RobotReplacement::descriptor () static
Referenced by mutable_unknown_fields(), grSim_BallReplacement::mutable_unknown_fields(), and grSim_Replacement::mutable_unknown_fields().
double grSim_RobotReplacement::dir () const inline
Definition at line 500 of file grSim_Replacement.pb.h.
References dir_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_RobotReplacement.dir)
   return dir_;
 }
inline ::google::protobuf::Arena* grSim_RobotReplacement::GetArenaNoVirtual () const inline private
Definition at line 107 of file grSim_Replacement.pb.h.
{
     return NULL;
   }
int grSim_RobotReplacement::GetCachedSize () const inline
Definition at line 100 of file grSim_Replacement.pb.h.
References _cached_size_, InternalSwap(), SetCachedSize(), SharedCtor(), and SharedDtor().
 { return _cached_size_; }
::google::protobuf::Metadata grSim_RobotReplacement::GetMetadata () const
Referenced by MaybeArenaPtr(), grSim_BallReplacement::MaybeArenaPtr(), and grSim_Replacement::MaybeArenaPtr().
bool grSim_RobotReplacement::has_dir () const inline
Definition at line 487 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool grSim_RobotReplacement::has_id () const inline
Definition at line 511 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool grSim_RobotReplacement::has_x () const inline
Definition at line 439 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by MaybeArenaPtr(), grSim_BallReplacement::MaybeArenaPtr(), and SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool grSim_RobotReplacement::has_y () const inline
Definition at line 463 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool grSim_RobotReplacement::has_yellowteam () const inline
Definition at line 535 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by SSLWorld::recvActions().
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
google::protobuf::uint32 grSim_RobotReplacement::id () const inline
Definition at line 524 of file grSim_Replacement.pb.h.
References id_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_RobotReplacement.id)
   return id_;
 }
static const grSim_RobotReplacement* grSim_RobotReplacement::internal_default_instance () inline static
Definition at line 70 of file grSim_Replacement.pb.h.
References _grSim_RobotReplacement_default_instance_, and Swap().
{
     return reinterpret_cast<const grSim_RobotReplacement*>(
                &_grSim_RobotReplacement_default_instance_);
   }
::google::protobuf::uint8* grSim_RobotReplacement::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
Referenced by New(), grSim_BallReplacement::New(), grSim_Replacement::New(), SerializeWithCachedSizesToArray(), grSim_BallReplacement::SerializeWithCachedSizesToArray(), and grSim_Replacement::SerializeWithCachedSizesToArray().
void grSim_RobotReplacement::InternalSwap (grSim_RobotReplacement * other) private
Referenced by GetCachedSize(), grSim_BallReplacement::GetCachedSize(), and grSim_Replacement::GetCachedSize().
bool grSim_RobotReplacement::IsInitialized () const
Referenced by New(), grSim_BallReplacement::New(), and grSim_Replacement::New().
void* grSim_RobotReplacement::MaybeArenaPtr () const inline private
Definition at line 110 of file grSim_Replacement.pb.h.
References clear_x(), GetMetadata(), and has_x().
{
     return NULL;
   }
void grSim_RobotReplacement::MergeFrom (const ::google::protobuf::Message & from)
Referenced by New(), grSim_BallReplacement::New(), and grSim_Replacement::New().
void grSim_RobotReplacement::MergeFrom (const grSim_RobotReplacement & from)
bool grSim_RobotReplacement::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Referenced by New(), grSim_BallReplacement::New(), and grSim_Replacement::New().
inline ::google::protobuf::UnknownFieldSet* grSim_RobotReplacement::mutable_unknown_fields () inline
Definition at line 63 of file grSim_Replacement.pb.h.
References _internal_metadata_, default_instance(), and descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
grSim_RobotReplacement* grSim_RobotReplacement::New () const inline
Definition at line 79 of file grSim_Replacement.pb.h.
References ByteSizeLong(), Clear(), CopyFrom(), InternalSerializeWithCachedSizesToArray(), IsInitialized(), MergeFrom(), MergePartialFromCodedStream(), New(), SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New(), grSim_BallReplacement::New(), and grSim_Replacement::New().
 { return New(NULL); }
grSim_RobotReplacement* grSim_RobotReplacement::New (::google::protobuf::Arena * arena) const
grSim_RobotReplacement& grSim_RobotReplacement::operator= (const grSim_RobotReplacement & from) inline
Definition at line 54 of file grSim_Replacement.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* grSim_RobotReplacement::protobuf_Offsets_grSim_5fReplacement_2eproto () private
size_t grSim_RobotReplacement::RequiredFieldsByteSizeFallback () const private
void grSim_RobotReplacement::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Referenced by New(), grSim_BallReplacement::New(), and grSim_Replacement::New().
::google::protobuf::uint8* grSim_RobotReplacement::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 96 of file grSim_Replacement.pb.h.
References InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void grSim_RobotReplacement::set_dir (double value) inline
Definition at line 504 of file grSim_Replacement.pb.h.
References dir_, and set_has_dir().
{
   set_has_dir();
   dir_ = value;
   // @@protoc_insertion_point(field_set:grSim_RobotReplacement.dir)
 }
void grSim_RobotReplacement::set_has_dir () inline private
Definition at line 490 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by set_dir().
{
   _has_bits_[0] |= 0x00000004u;
 }
void grSim_RobotReplacement::set_has_id () inline private
Definition at line 514 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by set_id().
{
   _has_bits_[0] |= 0x00000008u;
 }
void grSim_RobotReplacement::set_has_x () inline private
Definition at line 442 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by set_x(), and grSim_BallReplacement::set_x().
{
   _has_bits_[0] |= 0x00000001u;
 }
void grSim_RobotReplacement::set_has_y () inline private
Definition at line 466 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by set_y(), and grSim_BallReplacement::set_y().
{
   _has_bits_[0] |= 0x00000002u;
 }
void grSim_RobotReplacement::set_has_yellowteam () inline private
Definition at line 538 of file grSim_Replacement.pb.h.
References _has_bits_.
Referenced by set_yellowteam().
{
   _has_bits_[0] |= 0x00000010u;
 }
void grSim_RobotReplacement::set_id (::google::protobuf::uint32 value) inline
Definition at line 528 of file grSim_Replacement.pb.h.
References id_, and set_has_id().
{
   set_has_id();
   id_ = value;
   // @@protoc_insertion_point(field_set:grSim_RobotReplacement.id)
 }
void grSim_RobotReplacement::set_x (double value) inline
Definition at line 456 of file grSim_Replacement.pb.h.
References set_has_x(), and x_.
{
   set_has_x();
   x_ = value;
   // @@protoc_insertion_point(field_set:grSim_RobotReplacement.x)
 }
void grSim_RobotReplacement::set_y (double value) inline
Definition at line 480 of file grSim_Replacement.pb.h.
References set_has_y(), and y_.
{
   set_has_y();
   y_ = value;
   // @@protoc_insertion_point(field_set:grSim_RobotReplacement.y)
 }
void grSim_RobotReplacement::set_yellowteam (bool value) inline
Definition at line 552 of file grSim_Replacement.pb.h.
References set_has_yellowteam(), and yellowteam_.
{
   set_has_yellowteam();
   yellowteam_ = value;
   // @@protoc_insertion_point(field_set:grSim_RobotReplacement.yellowteam)
 }
void grSim_RobotReplacement::SetCachedSize (int size) const private
Referenced by GetCachedSize(), grSim_BallReplacement::GetCachedSize(), and grSim_Replacement::GetCachedSize().
void grSim_RobotReplacement::SharedCtor () private
Referenced by GetCachedSize(), grSim_BallReplacement::GetCachedSize(), and grSim_Replacement::GetCachedSize().
void grSim_RobotReplacement::SharedDtor () private
Referenced by GetCachedSize(), grSim_BallReplacement::GetCachedSize(), and grSim_Replacement::GetCachedSize().
void grSim_RobotReplacement::Swap (grSim_RobotReplacement * other)
Referenced by internal_default_instance(), grSim_BallReplacement::internal_default_instance(), and grSim_Replacement::internal_default_instance().
const ::google::protobuf::UnknownFieldSet& grSim_RobotReplacement::unknown_fields () const inline
Definition at line 59 of file grSim_Replacement.pb.h.
References _internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
double grSim_RobotReplacement::x () const inline
Definition at line 452 of file grSim_Replacement.pb.h.
References x_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_RobotReplacement.x)
   return x_;
 }
double grSim_RobotReplacement::y () const inline
Definition at line 476 of file grSim_Replacement.pb.h.
References y_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_RobotReplacement.y)
   return y_;
 }
bool grSim_RobotReplacement::yellowteam () const inline
Definition at line 548 of file grSim_Replacement.pb.h.
References yellowteam_.
Referenced by SSLWorld::recvActions().
{
   // @@protoc_insertion_point(field_get:grSim_RobotReplacement.yellowteam)
   return yellowteam_;
 }
Friends And Related Function Documentation
void protobuf_AddDesc_grSim_5fReplacement_2eproto_impl () friend
void protobuf_InitDefaults_grSim_5fReplacement_2eproto_impl () friend
void protobuf_ShutdownFile_grSim_5fReplacement_2eproto () friend
Field Documentation
int grSim_RobotReplacement::_cached_size_ mutable private
Definition at line 174 of file grSim_Replacement.pb.h.
Referenced by GetCachedSize(), grSim_BallReplacement::GetCachedSize(), and grSim_Replacement::GetCachedSize().
::google::protobuf::internal::HasBits<1> grSim_RobotReplacement::_has_bits_ private
Definition at line 173 of file grSim_Replacement.pb.h.
Referenced by grSim_Replacement::clear_has_ball(), clear_has_dir(), clear_has_id(), grSim_BallReplacement::clear_has_vx(), grSim_BallReplacement::clear_has_vy(), clear_has_x(), grSim_BallReplacement::clear_has_x(), clear_has_y(), grSim_BallReplacement::clear_has_y(), clear_has_yellowteam(), grSim_Replacement::has_ball(), has_dir(), has_id(), grSim_BallReplacement::has_vx(), grSim_BallReplacement::has_vy(), has_x(), grSim_BallReplacement::has_x(), has_y(), grSim_BallReplacement::has_y(), has_yellowteam(), grSim_Replacement::set_has_ball(), set_has_dir(), set_has_id(), grSim_BallReplacement::set_has_vx(), grSim_BallReplacement::set_has_vy(), set_has_x(), grSim_BallReplacement::set_has_x(), set_has_y(), grSim_BallReplacement::set_has_y(), and set_has_yellowteam().
::google::protobuf::internal::InternalMetadataWithArena grSim_RobotReplacement::_internal_metadata_ private
Definition at line 172 of file grSim_Replacement.pb.h.
Referenced by mutable_unknown_fields(), grSim_BallReplacement::mutable_unknown_fields(), grSim_Replacement::mutable_unknown_fields(), unknown_fields(), grSim_BallReplacement::unknown_fields(), and grSim_Replacement::unknown_fields().
double grSim_RobotReplacement::dir_ private
Definition at line 177 of file grSim_Replacement.pb.h.
Referenced by clear_dir(), dir(), and set_dir().
::google::protobuf::uint32 grSim_RobotReplacement::id_ private
Definition at line 178 of file grSim_Replacement.pb.h.
Referenced by clear_id(), id(), and set_id().
const int grSim_RobotReplacement::kDirFieldNumber = 3 static
Definition at line 138 of file grSim_Replacement.pb.h.
const int grSim_RobotReplacement::kIdFieldNumber = 4 static
Definition at line 145 of file grSim_Replacement.pb.h.
const int grSim_RobotReplacement::kXFieldNumber = 1 static
Definition at line 124 of file grSim_Replacement.pb.h.
const int grSim_RobotReplacement::kYellowteamFieldNumber = 5 static
Definition at line 152 of file grSim_Replacement.pb.h.
const int grSim_RobotReplacement::kYFieldNumber = 2 static
Definition at line 131 of file grSim_Replacement.pb.h.
double grSim_RobotReplacement::x_ private
Definition at line 175 of file grSim_Replacement.pb.h.
Referenced by clear_x(), grSim_BallReplacement::clear_x(), set_x(), grSim_BallReplacement::set_x(), x(), and grSim_BallReplacement::x().
double grSim_RobotReplacement::y_ private
Definition at line 176 of file grSim_Replacement.pb.h.
Referenced by clear_y(), grSim_BallReplacement::clear_y(), set_y(), grSim_BallReplacement::set_y(), y(), and grSim_BallReplacement::y().
bool grSim_RobotReplacement::yellowteam_ private
Definition at line 179 of file grSim_Replacement.pb.h.
Referenced by clear_yellowteam(), set_yellowteam(), and yellowteam().
The documentation for this class was generated from the following file:
grsim_comm/include/proto/grSim_Replacement.pb.h