Documentation: VarTypes::VarVal Class Reference
VarTypes::VarVal Class Reference
#include <VarVal.h>
Public Member Functions
VarVal ()
virtual ~VarVal ()
virtual VarVal * clone () const
virtual VarVal * deepClone () const
virtual VarTypeId getType () const
Get the type of this VarType node.
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual void printdebug () const
virtual string getString () const
Get a human-readable string representation of this node's data.
virtual bool setString (const string &val)
Set this node's data to some string representation.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
virtual bool hasValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Protected Member Functions
virtual void lock () const
virtual void unlock () const
virtual void changed ()
Detailed Description
Author
Stefan Zickler szick.nosp@m.ler@.nosp@m.cs.cm.nosp@m.u.ed.nosp@m.u
Definition at line 55 of file VarVal.h.
Constructor & Destructor Documentation
VarTypes::VarVal::VarVal ()
Definition at line 15 of file VarVal.cpp.
Referenced by clone().
   {
   }
VarTypes::VarVal::~VarVal () virtual
Definition at line 19 of file VarVal.cpp.
   {
   }
Member Function Documentation
virtual void VarTypes::VarVal::changed () inline protected virtual
Reimplemented in VarTypes::VarType, and VarTypes::VarProtoBuffer< CLASS_VARVAL_TYPE, TPL_vartype_id >.
Definition at line 62 of file VarVal.h.
Referenced by VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::set(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::setBinarySerialString(), VarTypes::VarBoolVal::setBool(), VarTypes::VarDoubleVal::setDouble(), VarTypes::VarIntVal::setInt(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::setSerialString(), VarTypes::VarStringVal::setString(), VarTypes::VarBoolVal::VarBoolVal(), VarTypes::VarDoubleVal::VarDoubleVal(), VarTypes::VarIntVal::VarIntVal(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::VarProtoBufferVal(), and VarTypes::VarStringVal::VarStringVal().
 {};
VarVal * VarTypes::VarVal::clone () const virtual
Creates a clone of the item. Note, that for containers that include VarType pointers (e.g. a list consisting of child-elements), this will perform a SHALLOW-COPY (e.g. the pointer values will be copied, but not the actual children references by them.), To perform a fully recursive deep-copy clone, run "deepClone()".
Reimplemented in VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >, VarTypes::VarIntVal, VarTypes::VarDoubleVal, VarTypes::VarStringVal, and VarTypes::VarBoolVal.
Definition at line 23 of file VarVal.cpp.
References VarVal().
Referenced by deepClone().
{
     return new VarVal();
   }
VarVal * VarTypes::VarVal::deepClone () const virtual
Creates a clone of this item (similar to clone()), except that this will produce a DEEP-COPY, which recursively clones the entire data-hierarchy.
Definition at line 27 of file VarVal.cpp.
References clone().
{
     return clone();
   }
void VarTypes::VarVal::getBinarySerialString (string & val) const virtual
Get a full canonical binary representation of this node. This will be used to store the node to XML.
Reimplemented in VarTypes::VarBlob, and VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >.
Definition at line 69 of file VarVal.cpp.
References getSerialString().
{
     getSerialString(val);
   };
string VarTypes::VarVal::getBinarySerialString () const
and its less efficient, deprecated non-virtual wrapper: DO NOT OVERLOAD THIS:
Definition at line 74 of file VarVal.cpp.
   {
     string result;
     getBinarySerialString(result);
     return result;
   }
double VarTypes::VarVal::getMaxValue () const virtual
This function returns the pre-specified maximum of this node's value range. To first check whether this node has such a maximum, please see hasMaxValue() .
See also
hasMaxValue()
Reimplemented in VarTypes::VarInt, VarTypes::VarDoubleVal, VarTypes::VarIntVal, and VarTypes::VarBoolVal.
Definition at line 107 of file VarVal.cpp.
Referenced by VarTypes::VarItemDelegate::drawBar().
   {
     return 1.0;
   }
double VarTypes::VarVal::getMinValue () const virtual
This function returns the pre-specified minimum of this node's value range. To first check whether this node has such a minimum, please see hasMinValue() .
See also
hasMinValue()
Reimplemented in VarTypes::VarInt, VarTypes::VarDoubleVal, VarTypes::VarIntVal, and VarTypes::VarBoolVal.
Definition at line 102 of file VarVal.cpp.
Referenced by VarTypes::VarItemDelegate::drawBar().
   {
     return 0.0;
   }
void VarTypes::VarVal::getSerialString (string & val) const virtual
Get a full canonical binary representation of this node. This will be used to store the node to XML.
Reimplemented in VarTypes::VarBlob, and VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >.
Definition at line 51 of file VarVal.cpp.
References getString().
   {
     val=getString();
   }
string VarTypes::VarVal::getSerialString () const
and its less efficient, deprecated non-virtual wrapper: DO NOT OVERLOAD THIS:
Definition at line 57 of file VarVal.cpp.
Referenced by getBinarySerialString(), and VarTypes::VarType::updateText().
   {
     string result;
     getSerialString(result);
     return result;
   }
string VarTypes::VarVal::getString () const virtual
Get a human-readable string representation of this node's data.
Reimplemented in VarTypes::VarBlob, VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >, VarTypes::VarDoubleVal, VarTypes::VarIntVal, VarTypes::VarBoolVal, VarTypes::VarStringEnum, VarTypes::VarStringVal, VarTypes::VarList, and VarTypes::VarSelection.
Definition at line 40 of file VarVal.cpp.
Referenced by getSerialString(), VarTypes::VarType::setEditorData(), and VarTypes::VarItem::update().
{
     return "";
   };
VarTypeId VarTypes::VarVal::getType () const virtual
Get the type of this VarType node.
Reimplemented in VarTypes::VarStringEnum, VarTypes::VarSelection, VarTypes::VarBlob, VarTypes::VarTrigger, VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >, VarTypes::VarList, VarTypes::VarQWidget, VarTypes::VarIntVal, VarTypes::VarDoubleVal, VarTypes::VarBoolVal, VarTypes::VarStringVal, and VarTypes::VarExternal.
Definition at line 32 of file VarVal.cpp.
References VarTypes::VARTYPE_ID_UNDEFINED.
Referenced by CaptureFlycap::changed(), CaptureBlueFox2::changed(), CaptureDC1394v2::changed(), CaptureV4L::changed(), VarTypes::VarItem::changeUpdate(), VarTypes::VarItemDelegate::drawBar(), getTypeName(), VarTypes::VarType::readChildrenHelper(), and VarTypes::VarItem::update().
 { return VARTYPE_ID_UNDEFINED; };
string VarTypes::VarVal::getTypeName () const virtual
Get the string label of the type of this VarType node.
Definition at line 35 of file VarVal.cpp.
References VarTypes::VarTypesInstance::getFactory(), getType(), and VarTypes::VarTypesFactory::typeToString().
Referenced by VarTypes::VarItem::update(), and VarTypes::VarType::writeXML().
 { return VarTypesInstance::getFactory()->typeToString(getType()) ;};
double VarTypes::VarVal::getValue () const virtual
Returns a single, numeric value of this node. To first check whether this node has a numeric value, please see hasValue() .
See also
hasValue()
Reimplemented in VarTypes::VarInt, VarTypes::VarDoubleVal, VarTypes::VarIntVal, and VarTypes::VarBoolVal.
Definition at line 112 of file VarVal.cpp.
Referenced by VarTypes::VarItemDelegate::drawBar().
   {
     return 0.0;
   }
bool VarTypes::VarVal::hasMaxValue () const virtual
This function indicates whether this node's value range has a pre-specified maximum This is useful for plotting.
See also
getMaxValue()
Reimplemented in VarTypes::VarInt, VarTypes::VarDoubleVal, VarTypes::VarIntVal, and VarTypes::VarBoolVal.
Definition at line 92 of file VarVal.cpp.
Referenced by VarTypes::VarItemDelegate::drawBar().
   {
     return false;
   }
bool VarTypes::VarVal::hasMinValue () const virtual
This function indicates whether this node's value range has a pre-specified minimum. This is useful for plotting.
See also
getMinValue()
Reimplemented in VarTypes::VarInt, VarTypes::VarDoubleVal, VarTypes::VarIntVal, and VarTypes::VarBoolVal.
Definition at line 97 of file VarVal.cpp.
Referenced by VarTypes::VarItemDelegate::drawBar().
   {
     return false;
   }
bool VarTypes::VarVal::hasValue () const virtual
This function indicates whether this nodes represents a numeric value. This is useful for e.g. determining whether this item is plottable. (e.g. whether this node has some kind of y-value)
Reimplemented in VarTypes::VarBlob, VarTypes::VarInt, VarTypes::VarDoubleVal, VarTypes::VarIntVal, VarTypes::VarBoolVal, and VarTypes::VarStringVal.
Definition at line 87 of file VarVal.cpp.
Referenced by VarTypes::VarItemDelegate::drawBar().
   {
     return false;
   }
virtual void VarTypes::VarVal::lock () const inline protected virtual
Reimplemented in VarTypes::SafeVarVal< VarTypes::VarDoubleVal >, VarTypes::SafeVarVal< VarTypes::VarIntVal >, VarTypes::SafeVarVal< VarTypes::VarStringVal >, VarTypes::SafeVarVal< VarTypes::VarBoolVal >, and VarTypes::VarType.
Definition at line 58 of file VarVal.h.
Referenced by VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::get(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::getBinarySerialString(), VarTypes::VarBoolVal::getBool(), VarTypes::VarDoubleVal::getDouble(), VarTypes::VarIntVal::getInt(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::getSerialString(), VarTypes::VarStringVal::getString(), VarTypes::VarStringVal::printdebug(), VarTypes::VarBoolVal::printdebug(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::printdebug(), VarTypes::VarIntVal::printdebug(), VarTypes::VarDoubleVal::printdebug(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::set(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::setBinarySerialString(), VarTypes::VarBoolVal::setBool(), VarTypes::VarDoubleVal::setDouble(), VarTypes::VarIntVal::setInt(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::setSerialString(), VarTypes::VarStringVal::setString(), VarTypes::VarBoolVal::VarBoolVal(), VarTypes::VarDoubleVal::VarDoubleVal(), and VarTypes::VarStringVal::VarStringVal().
 {};
void VarTypes::VarVal::printdebug () const virtual
Print out debugging information of this node to console. Usually this means the actually data of the node will be printed.
Reimplemented in VarTypes::VarBlob, VarTypes::VarTrigger, VarTypes::VarQWidget, VarTypes::VarDoubleVal, VarTypes::VarSelection, VarTypes::VarIntVal, VarTypes::VarList, VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >, VarTypes::VarStringEnum, VarTypes::VarBoolVal, and VarTypes::VarStringVal.
Definition at line 37 of file VarVal.cpp.
{
   };
void VarTypes::VarVal::setBinarySerialString (const string & val) virtual
Set the node to some full canonical binary representation. This will be used to load the node from XML.
Reimplemented in VarTypes::VarBlob, and VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >.
Definition at line 81 of file VarVal.cpp.
References setSerialString().
{
     setSerialString(val);
   }
void VarTypes::VarVal::setSerialString (const string & val) virtual
Set the node to some full canonical string representation. This will be used to load the node from XML.
Reimplemented in VarTypes::VarBlob, and VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >.
Definition at line 64 of file VarVal.cpp.
References setString().
Referenced by VarTypes::VarType::readText(), and setBinarySerialString().
   {
     setString(val);
   }
bool VarTypes::VarVal::setString (const string & val) virtual
Set this node's data to some string representation.
Reimplemented in VarTypes::VarBlob, VarTypes::VarInt, VarTypes::VarDoubleVal, VarTypes::VarIntVal, VarTypes::VarBoolVal, VarTypes::VarStringEnum, and VarTypes::VarStringVal.
Definition at line 44 of file VarVal.cpp.
Referenced by VarTypes::VarType::setModelData(), and setSerialString().
{
     (void)val;
     return false;
   };
virtual void VarTypes::VarVal::unlock () const inline protected virtual
Reimplemented in VarTypes::SafeVarVal< VarTypes::VarDoubleVal >, VarTypes::SafeVarVal< VarTypes::VarIntVal >, VarTypes::SafeVarVal< VarTypes::VarStringVal >, VarTypes::SafeVarVal< VarTypes::VarBoolVal >, and VarTypes::VarType.
Definition at line 60 of file VarVal.h.
Referenced by VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::get(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::getBinarySerialString(), VarTypes::VarBoolVal::getBool(), VarTypes::VarDoubleVal::getDouble(), VarTypes::VarIntVal::getInt(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::getSerialString(), VarTypes::VarStringVal::getString(), VarTypes::VarStringVal::printdebug(), VarTypes::VarBoolVal::printdebug(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::printdebug(), VarTypes::VarIntVal::printdebug(), VarTypes::VarDoubleVal::printdebug(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::set(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::setBinarySerialString(), VarTypes::VarBoolVal::setBool(), VarTypes::VarDoubleVal::setDouble(), VarTypes::VarIntVal::setInt(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::setSerialString(), VarTypes::VarStringVal::setString(), VarTypes::VarBoolVal::VarBoolVal(), VarTypes::VarDoubleVal::VarDoubleVal(), and VarTypes::VarStringVal::VarStringVal().
 {};
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/primitives/VarVal.h
ssl-vision/src/shared/vartypes/primitives/VarVal.cpp