Documentation: SSL_GeometryCameraCalibration Class Reference
SSL_GeometryCameraCalibration Class Reference
#include <messages_robocup_ssl_geometry.pb.h>
Public Member Functions
SSL_GeometryCameraCalibration ()
virtual ~SSL_GeometryCameraCalibration ()
SSL_GeometryCameraCalibration (const SSL_GeometryCameraCalibration &from)
SSL_GeometryCameraCalibration & operator= (const SSL_GeometryCameraCalibration &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_GeometryCameraCalibration *other)
SSL_GeometryCameraCalibration * New () const PROTOBUF_FINAL
SSL_GeometryCameraCalibration * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_GeometryCameraCalibration &from)
void MergeFrom (const SSL_GeometryCameraCalibration &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_camera_id () const
void clear_camera_id ()
::google::protobuf::uint32 camera_id () const
void set_camera_id (::google::protobuf::uint32 value)
bool has_focal_length () const
void clear_focal_length ()
float focal_length () const
void set_focal_length (float value)
bool has_principal_point_x () const
void clear_principal_point_x ()
float principal_point_x () const
void set_principal_point_x (float value)
bool has_principal_point_y () const
void clear_principal_point_y ()
float principal_point_y () const
void set_principal_point_y (float value)
bool has_distortion () const
void clear_distortion ()
float distortion () const
void set_distortion (float value)
bool has_q0 () const
void clear_q0 ()
float q0 () const
void set_q0 (float value)
bool has_q1 () const
void clear_q1 ()
float q1 () const
void set_q1 (float value)
bool has_q2 () const
void clear_q2 ()
float q2 () const
void set_q2 (float value)
bool has_q3 () const
void clear_q3 ()
float q3 () const
void set_q3 (float value)
bool has_tx () const
void clear_tx ()
float tx () const
void set_tx (float value)
bool has_ty () const
void clear_ty ()
float ty () const
void set_ty (float value)
bool has_tz () const
void clear_tz ()
float tz () const
void set_tz (float value)
bool has_derived_camera_world_tx () const
void clear_derived_camera_world_tx ()
float derived_camera_world_tx () const
void set_derived_camera_world_tx (float value)
bool has_derived_camera_world_ty () const
void clear_derived_camera_world_ty ()
float derived_camera_world_ty () const
void set_derived_camera_world_ty (float value)
bool has_derived_camera_world_tz () const
void clear_derived_camera_world_tz ()
float derived_camera_world_tz () const
void set_derived_camera_world_tz (float value)
SSL_GeometryCameraCalibration ()
virtual ~SSL_GeometryCameraCalibration ()
SSL_GeometryCameraCalibration (const SSL_GeometryCameraCalibration &from)
SSL_GeometryCameraCalibration & operator= (const SSL_GeometryCameraCalibration &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_GeometryCameraCalibration *other)
SSL_GeometryCameraCalibration * New () const PROTOBUF_FINAL
SSL_GeometryCameraCalibration * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_GeometryCameraCalibration &from)
void MergeFrom (const SSL_GeometryCameraCalibration &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_camera_id () const
void clear_camera_id ()
::google::protobuf::uint32 camera_id () const
void set_camera_id (::google::protobuf::uint32 value)
bool has_focal_length () const
void clear_focal_length ()
float focal_length () const
void set_focal_length (float value)
bool has_principal_point_x () const
void clear_principal_point_x ()
float principal_point_x () const
void set_principal_point_x (float value)
bool has_principal_point_y () const
void clear_principal_point_y ()
float principal_point_y () const
void set_principal_point_y (float value)
bool has_distortion () const
void clear_distortion ()
float distortion () const
void set_distortion (float value)
bool has_q0 () const
void clear_q0 ()
float q0 () const
void set_q0 (float value)
bool has_q1 () const
void clear_q1 ()
float q1 () const
void set_q1 (float value)
bool has_q2 () const
void clear_q2 ()
float q2 () const
void set_q2 (float value)
bool has_q3 () const
void clear_q3 ()
float q3 () const
void set_q3 (float value)
bool has_tx () const
void clear_tx ()
float tx () const
void set_tx (float value)
bool has_ty () const
void clear_ty ()
float ty () const
void set_ty (float value)
bool has_tz () const
void clear_tz ()
float tz () const
void set_tz (float value)
bool has_derived_camera_world_tx () const
void clear_derived_camera_world_tx ()
float derived_camera_world_tx () const
void set_derived_camera_world_tx (float value)
bool has_derived_camera_world_ty () const
void clear_derived_camera_world_ty ()
float derived_camera_world_ty () const
void set_derived_camera_world_ty (float value)
bool has_derived_camera_world_tz () const
void clear_derived_camera_world_tz ()
float derived_camera_world_tz () const
void set_derived_camera_world_tz (float value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_GeometryCameraCalibration & default_instance ()
static const SSL_GeometryCameraCalibration * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_GeometryCameraCalibration & default_instance ()
static void InitAsDefaultInstance ()
static const SSL_GeometryCameraCalibration * internal_default_instance ()
Static Public Attributes
static const int kCameraIdFieldNumber = 1
static const int kFocalLengthFieldNumber = 2
static const int kPrincipalPointXFieldNumber = 3
static const int kPrincipalPointYFieldNumber = 4
static const int kDistortionFieldNumber = 5
static const int kQ0FieldNumber = 6
static const int kQ1FieldNumber = 7
static const int kQ2FieldNumber = 8
static const int kQ3FieldNumber = 9
static const int kTxFieldNumber = 10
static const int kTyFieldNumber = 11
static const int kTzFieldNumber = 12
static const int kDerivedCameraWorldTxFieldNumber = 13
static const int kDerivedCameraWorldTyFieldNumber = 14
static const int kDerivedCameraWorldTzFieldNumber = 15
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_GeometryCameraCalibration *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_camera_id ()
void clear_has_camera_id ()
void set_has_focal_length ()
void clear_has_focal_length ()
void set_has_principal_point_x ()
void clear_has_principal_point_x ()
void set_has_principal_point_y ()
void clear_has_principal_point_y ()
void set_has_distortion ()
void clear_has_distortion ()
void set_has_q0 ()
void clear_has_q0 ()
void set_has_q1 ()
void clear_has_q1 ()
void set_has_q2 ()
void clear_has_q2 ()
void set_has_q3 ()
void clear_has_q3 ()
void set_has_tx ()
void clear_has_tx ()
void set_has_ty ()
void clear_has_ty ()
void set_has_tz ()
void clear_has_tz ()
void set_has_derived_camera_world_tx ()
void clear_has_derived_camera_world_tx ()
void set_has_derived_camera_world_ty ()
void clear_has_derived_camera_world_ty ()
void set_has_derived_camera_world_tz ()
void clear_has_derived_camera_world_tz ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5fgeometry_2eproto ()
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_GeometryCameraCalibration *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_camera_id ()
void clear_has_camera_id ()
void set_has_focal_length ()
void clear_has_focal_length ()
void set_has_principal_point_x ()
void clear_has_principal_point_x ()
void set_has_principal_point_y ()
void clear_has_principal_point_y ()
void set_has_distortion ()
void clear_has_distortion ()
void set_has_q0 ()
void clear_has_q0 ()
void set_has_q1 ()
void clear_has_q1 ()
void set_has_q2 ()
void clear_has_q2 ()
void set_has_q3 ()
void clear_has_q3 ()
void set_has_tx ()
void clear_has_tx ()
void set_has_ty ()
void clear_has_ty ()
void set_has_tz ()
void clear_has_tz ()
void set_has_derived_camera_world_tx ()
void clear_has_derived_camera_world_tx ()
void set_has_derived_camera_world_ty ()
void clear_has_derived_camera_world_ty ()
void set_has_derived_camera_world_tz ()
void clear_has_derived_camera_world_tz ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryCameraCalibrationImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::uint32 camera_id_
float focal_length_
float principal_point_x_
float principal_point_y_
float distortion_
float q0_
float q1_
float q2_
float q3_
float tx_
float ty_
float tz_
float derived_camera_world_tx_
float derived_camera_world_ty_
float derived_camera_world_tz_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::TableStruct
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto_impl ()
void protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_impl ()
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto ()
void swap (SSL_GeometryCameraCalibration &a, SSL_GeometryCameraCalibration &b)
Detailed Description
Definition at line 278 of file messages_robocup_ssl_geometry.pb.h.
Constructor & Destructor Documentation
SSL_GeometryCameraCalibration::SSL_GeometryCameraCalibration ()
virtual SSL_GeometryCameraCalibration::~SSL_GeometryCameraCalibration () virtual
SSL_GeometryCameraCalibration::SSL_GeometryCameraCalibration (const SSL_GeometryCameraCalibration & from)
SSL_GeometryCameraCalibration::SSL_GeometryCameraCalibration ()
virtual SSL_GeometryCameraCalibration::~SSL_GeometryCameraCalibration () virtual
SSL_GeometryCameraCalibration::SSL_GeometryCameraCalibration (const SSL_GeometryCameraCalibration & from)
Member Function Documentation
size_t SSL_GeometryCameraCalibration::ByteSizeLong () const
size_t SSL_GeometryCameraCalibration::ByteSizeLong () const
google::protobuf::uint32 SSL_GeometryCameraCalibration::camera_id () const inline
Definition at line 992 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.camera_id)
   return camera_id_;
 }
::google::protobuf::uint32 SSL_GeometryCameraCalibration::camera_id () const
void SSL_GeometryCameraCalibration::Clear ()
void SSL_GeometryCameraCalibration::Clear ()
void SSL_GeometryCameraCalibration::clear_camera_id () inline
Definition at line 988 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   camera_id_ = 0u;
   clear_has_camera_id();
 }
void SSL_GeometryCameraCalibration::clear_camera_id ()
void SSL_GeometryCameraCalibration::clear_derived_camera_world_tx () inline
Definition at line 1276 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   derived_camera_world_tx_ = 0;
   clear_has_derived_camera_world_tx();
 }
void SSL_GeometryCameraCalibration::clear_derived_camera_world_tx ()
void SSL_GeometryCameraCalibration::clear_derived_camera_world_ty () inline
Definition at line 1300 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   derived_camera_world_ty_ = 0;
   clear_has_derived_camera_world_ty();
 }
void SSL_GeometryCameraCalibration::clear_derived_camera_world_ty ()
void SSL_GeometryCameraCalibration::clear_derived_camera_world_tz () inline
Definition at line 1324 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   derived_camera_world_tz_ = 0;
   clear_has_derived_camera_world_tz();
 }
void SSL_GeometryCameraCalibration::clear_derived_camera_world_tz ()
void SSL_GeometryCameraCalibration::clear_distortion () inline
Definition at line 1084 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   distortion_ = 0;
   clear_has_distortion();
 }
void SSL_GeometryCameraCalibration::clear_distortion ()
void SSL_GeometryCameraCalibration::clear_focal_length () inline
Definition at line 1012 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   focal_length_ = 0;
   clear_has_focal_length();
 }
void SSL_GeometryCameraCalibration::clear_focal_length ()
void SSL_GeometryCameraCalibration::clear_has_camera_id () inline private
Definition at line 985 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00000001u;
 }
void SSL_GeometryCameraCalibration::clear_has_camera_id () private
void SSL_GeometryCameraCalibration::clear_has_derived_camera_world_tx () inline private
Definition at line 1273 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00001000u;
 }
void SSL_GeometryCameraCalibration::clear_has_derived_camera_world_tx () private
void SSL_GeometryCameraCalibration::clear_has_derived_camera_world_ty () inline private
Definition at line 1297 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00002000u;
 }
void SSL_GeometryCameraCalibration::clear_has_derived_camera_world_ty () private
void SSL_GeometryCameraCalibration::clear_has_derived_camera_world_tz () inline private
Definition at line 1321 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00004000u;
 }
void SSL_GeometryCameraCalibration::clear_has_derived_camera_world_tz () private
void SSL_GeometryCameraCalibration::clear_has_distortion () inline private
Definition at line 1081 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00000010u;
 }
void SSL_GeometryCameraCalibration::clear_has_distortion () private
void SSL_GeometryCameraCalibration::clear_has_focal_length () inline private
Definition at line 1009 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00000002u;
 }
void SSL_GeometryCameraCalibration::clear_has_focal_length () private
void SSL_GeometryCameraCalibration::clear_has_principal_point_x () inline private
Definition at line 1033 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00000004u;
 }
void SSL_GeometryCameraCalibration::clear_has_principal_point_x () private
void SSL_GeometryCameraCalibration::clear_has_principal_point_y () inline private
Definition at line 1057 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00000008u;
 }
void SSL_GeometryCameraCalibration::clear_has_principal_point_y () private
void SSL_GeometryCameraCalibration::clear_has_q0 () inline private
Definition at line 1105 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00000020u;
 }
void SSL_GeometryCameraCalibration::clear_has_q0 () private
void SSL_GeometryCameraCalibration::clear_has_q1 () inline private
Definition at line 1129 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00000040u;
 }
void SSL_GeometryCameraCalibration::clear_has_q1 () private
void SSL_GeometryCameraCalibration::clear_has_q2 () inline private
Definition at line 1153 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00000080u;
 }
void SSL_GeometryCameraCalibration::clear_has_q2 () private
void SSL_GeometryCameraCalibration::clear_has_q3 () inline private
Definition at line 1177 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00000100u;
 }
void SSL_GeometryCameraCalibration::clear_has_q3 () private
void SSL_GeometryCameraCalibration::clear_has_tx () inline private
Definition at line 1201 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00000200u;
 }
void SSL_GeometryCameraCalibration::clear_has_tx () private
void SSL_GeometryCameraCalibration::clear_has_ty () inline private
Definition at line 1225 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00000400u;
 }
void SSL_GeometryCameraCalibration::clear_has_ty () private
void SSL_GeometryCameraCalibration::clear_has_tz () inline private
Definition at line 1249 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] &= ~0x00000800u;
 }
void SSL_GeometryCameraCalibration::clear_has_tz () private
void SSL_GeometryCameraCalibration::clear_principal_point_x () inline
Definition at line 1036 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   principal_point_x_ = 0;
   clear_has_principal_point_x();
 }
void SSL_GeometryCameraCalibration::clear_principal_point_x ()
void SSL_GeometryCameraCalibration::clear_principal_point_y () inline
Definition at line 1060 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   principal_point_y_ = 0;
   clear_has_principal_point_y();
 }
void SSL_GeometryCameraCalibration::clear_principal_point_y ()
void SSL_GeometryCameraCalibration::clear_q0 () inline
Definition at line 1108 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   q0_ = 0;
   clear_has_q0();
 }
void SSL_GeometryCameraCalibration::clear_q0 ()
void SSL_GeometryCameraCalibration::clear_q1 () inline
Definition at line 1132 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   q1_ = 0;
   clear_has_q1();
 }
void SSL_GeometryCameraCalibration::clear_q1 ()
void SSL_GeometryCameraCalibration::clear_q2 () inline
Definition at line 1156 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   q2_ = 0;
   clear_has_q2();
 }
void SSL_GeometryCameraCalibration::clear_q2 ()
void SSL_GeometryCameraCalibration::clear_q3 () inline
Definition at line 1180 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   q3_ = 0;
   clear_has_q3();
 }
void SSL_GeometryCameraCalibration::clear_q3 ()
void SSL_GeometryCameraCalibration::clear_tx () inline
Definition at line 1204 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   tx_ = 0;
   clear_has_tx();
 }
void SSL_GeometryCameraCalibration::clear_tx ()
void SSL_GeometryCameraCalibration::clear_ty () inline
Definition at line 1228 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   ty_ = 0;
   clear_has_ty();
 }
void SSL_GeometryCameraCalibration::clear_ty ()
void SSL_GeometryCameraCalibration::clear_tz () inline
Definition at line 1252 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   tz_ = 0;
   clear_has_tz();
 }
void SSL_GeometryCameraCalibration::clear_tz ()
void SSL_GeometryCameraCalibration::CopyFrom (const ::google::protobuf::Message & from)
void SSL_GeometryCameraCalibration::CopyFrom (const SSL_GeometryCameraCalibration & from)
void SSL_GeometryCameraCalibration::CopyFrom (const ::google::protobuf::Message & from)
void SSL_GeometryCameraCalibration::CopyFrom (const SSL_GeometryCameraCalibration & from)
static const SSL_GeometryCameraCalibration& SSL_GeometryCameraCalibration::default_instance () static
static const SSL_GeometryCameraCalibration& SSL_GeometryCameraCalibration::default_instance () static
float SSL_GeometryCameraCalibration::derived_camera_world_tx () const inline
Definition at line 1280 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.derived_camera_world_tx)
   return derived_camera_world_tx_;
 }
float SSL_GeometryCameraCalibration::derived_camera_world_tx () const
float SSL_GeometryCameraCalibration::derived_camera_world_ty () const inline
Definition at line 1304 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.derived_camera_world_ty)
   return derived_camera_world_ty_;
 }
float SSL_GeometryCameraCalibration::derived_camera_world_ty () const
float SSL_GeometryCameraCalibration::derived_camera_world_tz () const inline
Definition at line 1328 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.derived_camera_world_tz)
   return derived_camera_world_tz_;
 }
float SSL_GeometryCameraCalibration::derived_camera_world_tz () const
static const ::google::protobuf::Descriptor* SSL_GeometryCameraCalibration::descriptor () static
static const ::google::protobuf::Descriptor* SSL_GeometryCameraCalibration::descriptor () static
float SSL_GeometryCameraCalibration::distortion () const inline
Definition at line 1088 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), CameraParameters::fromProtoBuffer(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.distortion)
   return distortion_;
 }
float SSL_GeometryCameraCalibration::distortion () const
float SSL_GeometryCameraCalibration::focal_length () const inline
Definition at line 1016 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), CameraParameters::fromProtoBuffer(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.focal_length)
   return focal_length_;
 }
float SSL_GeometryCameraCalibration::focal_length () const
inline ::google::protobuf::Arena* SSL_GeometryCameraCalibration::GetArenaNoVirtual () const inline private
Definition at line 338 of file messages_robocup_ssl_geometry.pb.h.
{
     return NULL;
   }
inline ::google::protobuf::Arena* SSL_GeometryCameraCalibration::GetArenaNoVirtual () const inline private
Definition at line 792 of file messages_robocup_ssl_geometry.pb.h.
{
     return NULL;
   }
int SSL_GeometryCameraCalibration::GetCachedSize () const inline
Definition at line 331 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_cached_size_, SSL_GeometryFieldSize::InternalSwap(), SSL_GeometryFieldSize::SetCachedSize(), SSL_GeometryFieldSize::SharedCtor(), and SSL_GeometryFieldSize::SharedDtor().
 { return _cached_size_; }
int SSL_GeometryCameraCalibration::GetCachedSize () const inline
Definition at line 785 of file messages_robocup_ssl_geometry.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata SSL_GeometryCameraCalibration::GetMetadata () const
::google::protobuf::Metadata SSL_GeometryCameraCalibration::GetMetadata () const
bool SSL_GeometryCameraCalibration::has_camera_id () const inline
Definition at line 979 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_camera_id () const
bool SSL_GeometryCameraCalibration::has_derived_camera_world_tx () const inline
Definition at line 1267 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs(), and main().
{
   return (_has_bits_[0] & 0x00001000u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_derived_camera_world_tx () const
bool SSL_GeometryCameraCalibration::has_derived_camera_world_ty () const inline
Definition at line 1291 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs(), and main().
{
   return (_has_bits_[0] & 0x00002000u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_derived_camera_world_ty () const
bool SSL_GeometryCameraCalibration::has_derived_camera_world_tz () const inline
Definition at line 1315 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs(), and main().
{
   return (_has_bits_[0] & 0x00004000u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_derived_camera_world_tz () const
bool SSL_GeometryCameraCalibration::has_distortion () const inline
Definition at line 1075 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_distortion () const
bool SSL_GeometryCameraCalibration::has_focal_length () const inline
Definition at line 1003 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_focal_length () const
bool SSL_GeometryCameraCalibration::has_principal_point_x () const inline
Definition at line 1027 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_principal_point_x () const
bool SSL_GeometryCameraCalibration::has_principal_point_y () const inline
Definition at line 1051 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_principal_point_y () const
bool SSL_GeometryCameraCalibration::has_q0 () const inline
Definition at line 1099 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   return (_has_bits_[0] & 0x00000020u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_q0 () const
bool SSL_GeometryCameraCalibration::has_q1 () const inline
Definition at line 1123 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   return (_has_bits_[0] & 0x00000040u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_q1 () const
bool SSL_GeometryCameraCalibration::has_q2 () const inline
Definition at line 1147 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   return (_has_bits_[0] & 0x00000080u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_q2 () const
bool SSL_GeometryCameraCalibration::has_q3 () const inline
Definition at line 1171 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   return (_has_bits_[0] & 0x00000100u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_q3 () const
bool SSL_GeometryCameraCalibration::has_tx () const inline
Definition at line 1195 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   return (_has_bits_[0] & 0x00000200u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_tx () const
bool SSL_GeometryCameraCalibration::has_ty () const inline
Definition at line 1219 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   return (_has_bits_[0] & 0x00000400u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_ty () const
bool SSL_GeometryCameraCalibration::has_tz () const inline
Definition at line 1243 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   return (_has_bits_[0] & 0x00000800u) != 0;
 }
bool SSL_GeometryCameraCalibration::has_tz () const
static void SSL_GeometryCameraCalibration::InitAsDefaultInstance () static
static const SSL_GeometryCameraCalibration* SSL_GeometryCameraCalibration::internal_default_instance () inline static
Definition at line 301 of file messages_robocup_ssl_geometry.pb.h.
References _SSL_GeometryCameraCalibration_default_instance_, and SSL_GeometryFieldSize::Swap().
{
     return reinterpret_cast<const SSL_GeometryCameraCalibration*>(
                &_SSL_GeometryCameraCalibration_default_instance_);
   }
static const SSL_GeometryCameraCalibration* SSL_GeometryCameraCalibration::internal_default_instance () inline static
Definition at line 754 of file messages_robocup_ssl_geometry.pb.h.
References _SSL_GeometryCameraCalibration_default_instance_.
{
     return reinterpret_cast<const SSL_GeometryCameraCalibration*>(
                &_SSL_GeometryCameraCalibration_default_instance_);
   }
::google::protobuf::uint8* SSL_GeometryCameraCalibration::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
::google::protobuf::uint8* SSL_GeometryCameraCalibration::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void SSL_GeometryCameraCalibration::InternalSwap (SSL_GeometryCameraCalibration * other) private
void SSL_GeometryCameraCalibration::InternalSwap (SSL_GeometryCameraCalibration * other) private
bool SSL_GeometryCameraCalibration::IsInitialized () const
bool SSL_GeometryCameraCalibration::IsInitialized () const
void* SSL_GeometryCameraCalibration::MaybeArenaPtr () const inline private
Definition at line 341 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::GetMetadata().
{
     return NULL;
   }
void* SSL_GeometryCameraCalibration::MaybeArenaPtr () const inline private
Definition at line 795 of file messages_robocup_ssl_geometry.pb.h.
{
     return NULL;
   }
void SSL_GeometryCameraCalibration::MergeFrom (const ::google::protobuf::Message & from)
void SSL_GeometryCameraCalibration::MergeFrom (const SSL_GeometryCameraCalibration & from)
void SSL_GeometryCameraCalibration::MergeFrom (const ::google::protobuf::Message & from)
void SSL_GeometryCameraCalibration::MergeFrom (const SSL_GeometryCameraCalibration & from)
bool SSL_GeometryCameraCalibration::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
bool SSL_GeometryCameraCalibration::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
inline ::google::protobuf::UnknownFieldSet* SSL_GeometryCameraCalibration::mutable_unknown_fields () inline
Definition at line 294 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_internal_metadata_, SSL_GeometryFieldSize::default_instance(), and SSL_GeometryFieldSize::descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
inline ::google::protobuf::UnknownFieldSet* SSL_GeometryCameraCalibration::mutable_unknown_fields () inline
Definition at line 746 of file messages_robocup_ssl_geometry.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
SSL_GeometryCameraCalibration* SSL_GeometryCameraCalibration::New () const inline
Definition at line 310 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::ByteSizeLong(), SSL_GeometryFieldSize::Clear(), SSL_GeometryFieldSize::CopyFrom(), SSL_GeometryFieldSize::InternalSerializeWithCachedSizesToArray(), SSL_GeometryFieldSize::IsInitialized(), SSL_GeometryFieldSize::MergeFrom(), SSL_GeometryFieldSize::MergePartialFromCodedStream(), SSL_GeometryFieldSize::New(), New(), SSL_GeometryFieldSize::SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_GeometryCameraCalibration* SSL_GeometryCameraCalibration::New (::google::protobuf::Arena * arena) const
SSL_GeometryCameraCalibration* SSL_GeometryCameraCalibration::New () const inline
Definition at line 768 of file messages_robocup_ssl_geometry.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_GeometryCameraCalibration* SSL_GeometryCameraCalibration::New (::google::protobuf::Arena * arena) const
SSL_GeometryCameraCalibration& SSL_GeometryCameraCalibration::operator= (const SSL_GeometryCameraCalibration & from) inline
Definition at line 285 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
SSL_GeometryCameraCalibration& SSL_GeometryCameraCalibration::operator= (const SSL_GeometryCameraCalibration & from) inline
Definition at line 724 of file messages_robocup_ssl_geometry.pb.h.
{
     CopyFrom(from);
     return *this;
   }
float SSL_GeometryCameraCalibration::principal_point_x () const inline
Definition at line 1040 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), CameraParameters::fromProtoBuffer(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.principal_point_x)
   return principal_point_x_;
 }
float SSL_GeometryCameraCalibration::principal_point_x () const
float SSL_GeometryCameraCalibration::principal_point_y () const inline
Definition at line 1064 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), CameraParameters::fromProtoBuffer(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.principal_point_y)
   return principal_point_y_;
 }
float SSL_GeometryCameraCalibration::principal_point_y () const
friendconst ::google::protobuf::uint32* SSL_GeometryCameraCalibration::protobuf_Offsets_messages_5frobocup_5fssl_5fgeometry_2eproto () private
float SSL_GeometryCameraCalibration::q0 () const inline
Definition at line 1112 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), CameraParameters::fromProtoBuffer(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.q0)
   return q0_;
 }
float SSL_GeometryCameraCalibration::q0 () const
float SSL_GeometryCameraCalibration::q1 () const inline
Definition at line 1136 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), CameraParameters::fromProtoBuffer(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.q1)
   return q1_;
 }
float SSL_GeometryCameraCalibration::q1 () const
float SSL_GeometryCameraCalibration::q2 () const inline
Definition at line 1160 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), CameraParameters::fromProtoBuffer(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.q2)
   return q2_;
 }
float SSL_GeometryCameraCalibration::q2 () const
float SSL_GeometryCameraCalibration::q3 () const inline
Definition at line 1184 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), CameraParameters::fromProtoBuffer(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.q3)
   return q3_;
 }
float SSL_GeometryCameraCalibration::q3 () const
size_t SSL_GeometryCameraCalibration::RequiredFieldsByteSizeFallback () const private
size_t SSL_GeometryCameraCalibration::RequiredFieldsByteSizeFallback () const private
void SSL_GeometryCameraCalibration::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void SSL_GeometryCameraCalibration::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* SSL_GeometryCameraCalibration::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 327 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void SSL_GeometryCameraCalibration::set_camera_id (::google::protobuf::uint32 value) inline
Definition at line 996 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_camera_id();
   camera_id_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.camera_id)
 }
void SSL_GeometryCameraCalibration::set_camera_id (::google::protobuf::uint32 value)
void SSL_GeometryCameraCalibration::set_derived_camera_world_tx (float value) inline
Definition at line 1284 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_derived_camera_world_tx();
   derived_camera_world_tx_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.derived_camera_world_tx)
 }
void SSL_GeometryCameraCalibration::set_derived_camera_world_tx (float value)
void SSL_GeometryCameraCalibration::set_derived_camera_world_ty (float value) inline
Definition at line 1308 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_derived_camera_world_ty();
   derived_camera_world_ty_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.derived_camera_world_ty)
 }
void SSL_GeometryCameraCalibration::set_derived_camera_world_ty (float value)
void SSL_GeometryCameraCalibration::set_derived_camera_world_tz (float value) inline
Definition at line 1332 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_derived_camera_world_tz();
   derived_camera_world_tz_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.derived_camera_world_tz)
 }
void SSL_GeometryCameraCalibration::set_derived_camera_world_tz (float value)
void SSL_GeometryCameraCalibration::set_distortion (float value) inline
Definition at line 1092 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_distortion();
   distortion_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.distortion)
 }
void SSL_GeometryCameraCalibration::set_distortion (float value)
void SSL_GeometryCameraCalibration::set_focal_length (float value) inline
Definition at line 1020 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_focal_length();
   focal_length_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.focal_length)
 }
void SSL_GeometryCameraCalibration::set_focal_length (float value)
void SSL_GeometryCameraCalibration::set_has_camera_id () inline private
Definition at line 982 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00000001u;
 }
void SSL_GeometryCameraCalibration::set_has_camera_id () private
void SSL_GeometryCameraCalibration::set_has_derived_camera_world_tx () inline private
Definition at line 1270 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00001000u;
 }
void SSL_GeometryCameraCalibration::set_has_derived_camera_world_tx () private
void SSL_GeometryCameraCalibration::set_has_derived_camera_world_ty () inline private
Definition at line 1294 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00002000u;
 }
void SSL_GeometryCameraCalibration::set_has_derived_camera_world_ty () private
void SSL_GeometryCameraCalibration::set_has_derived_camera_world_tz () inline private
Definition at line 1318 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00004000u;
 }
void SSL_GeometryCameraCalibration::set_has_derived_camera_world_tz () private
void SSL_GeometryCameraCalibration::set_has_distortion () inline private
Definition at line 1078 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00000010u;
 }
void SSL_GeometryCameraCalibration::set_has_distortion () private
void SSL_GeometryCameraCalibration::set_has_focal_length () inline private
Definition at line 1006 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00000002u;
 }
void SSL_GeometryCameraCalibration::set_has_focal_length () private
void SSL_GeometryCameraCalibration::set_has_principal_point_x () inline private
Definition at line 1030 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00000004u;
 }
void SSL_GeometryCameraCalibration::set_has_principal_point_x () private
void SSL_GeometryCameraCalibration::set_has_principal_point_y () inline private
Definition at line 1054 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00000008u;
 }
void SSL_GeometryCameraCalibration::set_has_principal_point_y () private
void SSL_GeometryCameraCalibration::set_has_q0 () inline private
Definition at line 1102 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00000020u;
 }
void SSL_GeometryCameraCalibration::set_has_q0 () private
void SSL_GeometryCameraCalibration::set_has_q1 () inline private
Definition at line 1126 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00000040u;
 }
void SSL_GeometryCameraCalibration::set_has_q1 () private
void SSL_GeometryCameraCalibration::set_has_q2 () inline private
Definition at line 1150 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00000080u;
 }
void SSL_GeometryCameraCalibration::set_has_q2 () private
void SSL_GeometryCameraCalibration::set_has_q3 () inline private
Definition at line 1174 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00000100u;
 }
void SSL_GeometryCameraCalibration::set_has_q3 () private
void SSL_GeometryCameraCalibration::set_has_tx () inline private
Definition at line 1198 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00000200u;
 }
void SSL_GeometryCameraCalibration::set_has_tx () private
void SSL_GeometryCameraCalibration::set_has_ty () inline private
Definition at line 1222 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00000400u;
 }
void SSL_GeometryCameraCalibration::set_has_ty () private
void SSL_GeometryCameraCalibration::set_has_tz () inline private
Definition at line 1246 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_has_bits_.
Referenced by SSL_GeometryFieldSize::field_arcs().
{
   _has_bits_[0] |= 0x00000800u;
 }
void SSL_GeometryCameraCalibration::set_has_tz () private
void SSL_GeometryCameraCalibration::set_principal_point_x (float value) inline
Definition at line 1044 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_principal_point_x();
   principal_point_x_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.principal_point_x)
 }
void SSL_GeometryCameraCalibration::set_principal_point_x (float value)
void SSL_GeometryCameraCalibration::set_principal_point_y (float value) inline
Definition at line 1068 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_principal_point_y();
   principal_point_y_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.principal_point_y)
 }
void SSL_GeometryCameraCalibration::set_principal_point_y (float value)
void SSL_GeometryCameraCalibration::set_q0 (float value) inline
Definition at line 1116 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_q0();
   q0_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.q0)
 }
void SSL_GeometryCameraCalibration::set_q0 (float value)
void SSL_GeometryCameraCalibration::set_q1 (float value) inline
Definition at line 1140 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_q1();
   q1_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.q1)
 }
void SSL_GeometryCameraCalibration::set_q1 (float value)
void SSL_GeometryCameraCalibration::set_q2 (float value) inline
Definition at line 1164 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_q2();
   q2_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.q2)
 }
void SSL_GeometryCameraCalibration::set_q2 (float value)
void SSL_GeometryCameraCalibration::set_q3 (float value) inline
Definition at line 1188 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_q3();
   q3_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.q3)
 }
void SSL_GeometryCameraCalibration::set_q3 (float value)
void SSL_GeometryCameraCalibration::set_tx (float value) inline
Definition at line 1212 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_tx();
   tx_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.tx)
 }
void SSL_GeometryCameraCalibration::set_tx (float value)
void SSL_GeometryCameraCalibration::set_ty (float value) inline
Definition at line 1236 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_ty();
   ty_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.ty)
 }
void SSL_GeometryCameraCalibration::set_ty (float value)
void SSL_GeometryCameraCalibration::set_tz (float value) inline
Definition at line 1260 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), and CameraParameters::toProtoBuffer().
{
   set_has_tz();
   tz_ = value;
   // @@protoc_insertion_point(field_set:SSL_GeometryCameraCalibration.tz)
 }
void SSL_GeometryCameraCalibration::set_tz (float value)
void SSL_GeometryCameraCalibration::SetCachedSize (int size) const private
void SSL_GeometryCameraCalibration::SetCachedSize (int size) const private
void SSL_GeometryCameraCalibration::SharedCtor () private
void SSL_GeometryCameraCalibration::SharedCtor () private
void SSL_GeometryCameraCalibration::SharedDtor () private
void SSL_GeometryCameraCalibration::SharedDtor () private
void SSL_GeometryCameraCalibration::Swap (SSL_GeometryCameraCalibration * other)
void SSL_GeometryCameraCalibration::Swap (SSL_GeometryCameraCalibration * other)
float SSL_GeometryCameraCalibration::tx () const inline
Definition at line 1208 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), CameraParameters::fromProtoBuffer(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.tx)
   return tx_;
 }
float SSL_GeometryCameraCalibration::tx () const
float SSL_GeometryCameraCalibration::ty () const inline
Definition at line 1232 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), CameraParameters::fromProtoBuffer(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.ty)
   return ty_;
 }
float SSL_GeometryCameraCalibration::ty () const
float SSL_GeometryCameraCalibration::tz () const inline
Definition at line 1256 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSL_GeometryFieldSize::field_arcs(), CameraParameters::fromProtoBuffer(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_GeometryCameraCalibration.tz)
   return tz_;
 }
float SSL_GeometryCameraCalibration::tz () const
const ::google::protobuf::UnknownFieldSet& SSL_GeometryCameraCalibration::unknown_fields () const inline
Definition at line 290 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::_internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
const ::google::protobuf::UnknownFieldSet& SSL_GeometryCameraCalibration::unknown_fields () const inline
Definition at line 743 of file messages_robocup_ssl_geometry.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
SSL_GeometryCameraCalibration::void::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryCameraCalibrationImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::TableStruct friend
Definition at line 965 of file messages_robocup_ssl_geometry.pb.h.
void protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_impl () friend
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto_impl () friend
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto () friend
void swap (SSL_GeometryCameraCalibration & a, SSL_GeometryCameraCalibration & b) friend
Definition at line 762 of file messages_robocup_ssl_geometry.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int SSL_GeometryCameraCalibration::_cached_size_ mutable private
Definition at line 495 of file messages_robocup_ssl_geometry.pb.h.
google::protobuf::internal::HasBits< 1 > SSL_GeometryCameraCalibration::_has_bits_ private
Definition at line 494 of file messages_robocup_ssl_geometry.pb.h.
google::protobuf::internal::InternalMetadataWithArena SSL_GeometryCameraCalibration::_internal_metadata_ private
Definition at line 493 of file messages_robocup_ssl_geometry.pb.h.
google::protobuf::uint32 SSL_GeometryCameraCalibration::camera_id_ private
Definition at line 496 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::derived_camera_world_tx_ private
Definition at line 508 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::derived_camera_world_ty_ private
Definition at line 509 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::derived_camera_world_tz_ private
Definition at line 510 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::distortion_ private
Definition at line 500 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::focal_length_ private
Definition at line 497 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kCameraIdFieldNumber = 1 static
Definition at line 355 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kDerivedCameraWorldTxFieldNumber = 13 static
Definition at line 439 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kDerivedCameraWorldTyFieldNumber = 14 static
Definition at line 446 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kDerivedCameraWorldTzFieldNumber = 15 static
Definition at line 453 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kDistortionFieldNumber = 5 static
Definition at line 383 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kFocalLengthFieldNumber = 2 static
Definition at line 362 of file messages_robocup_ssl_geometry.pb.h.
PROTOBUF_CONSTEXPR int const SSL_GeometryCameraCalibration::kIndexInFileMessages static
Initial value:
=
    4
Definition at line 758 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kPrincipalPointXFieldNumber = 3 static
Definition at line 369 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kPrincipalPointYFieldNumber = 4 static
Definition at line 376 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kQ0FieldNumber = 6 static
Definition at line 390 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kQ1FieldNumber = 7 static
Definition at line 397 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kQ2FieldNumber = 8 static
Definition at line 404 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kQ3FieldNumber = 9 static
Definition at line 411 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kTxFieldNumber = 10 static
Definition at line 418 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kTyFieldNumber = 11 static
Definition at line 425 of file messages_robocup_ssl_geometry.pb.h.
static const int SSL_GeometryCameraCalibration::kTzFieldNumber = 12 static
Definition at line 432 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::principal_point_x_ private
Definition at line 498 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::principal_point_y_ private
Definition at line 499 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::q0_ private
Definition at line 501 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::q1_ private
Definition at line 502 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::q2_ private
Definition at line 503 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::q3_ private
Definition at line 504 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::tx_ private
Definition at line 505 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::ty_ private
Definition at line 506 of file messages_robocup_ssl_geometry.pb.h.
float SSL_GeometryCameraCalibration::tz_ private
Definition at line 507 of file messages_robocup_ssl_geometry.pb.h.
The documentation for this class was generated from the following file:
grsim_comm/include/proto/messages_robocup_ssl_geometry.pb.h