Documentation: VarTypes::VarTypesFactory Class Reference
VarTypes::VarTypesFactory Class Reference
#include <VarTypesFactory.h>
Public Member Functions
VarTypesFactory ()
virtual ~VarTypesFactory ()
VarType * newVarType (VarTypeId t)
VarVal * newVarVal (VarTypeId t)
VarTypeId stringToType (const string &s)
string typeToString (VarTypeId t)
Protected Member Functions
virtual VarType * newUserVarType (VarTypeId t)
virtual VarVal * newUserVarVal (VarTypeId t)
virtual VarTypeId stringToUserType (const string &s)
virtual string userTypeToString (VarTypeId t)
Detailed Description
Author
Stefan Zickler szick.nosp@m.ler@.nosp@m.cs.cm.nosp@m.u.ed.nosp@m.u
Definition at line 42 of file VarTypesFactory.h.
Constructor & Destructor Documentation
VarTypes::VarTypesFactory::VarTypesFactory ()
Definition at line 15 of file VarTypesFactory.cpp.
   {
   }
VarTypes::VarTypesFactory::~VarTypesFactory () virtual
Definition at line 19 of file VarTypesFactory.cpp.
   {
   }
Member Function Documentation
VarType * VarTypes::VarTypesFactory::newUserVarType (VarTypeId t) protected virtual
Definition at line 23 of file VarTypesFactory.cpp.
Referenced by newVarType().
{
     (void)t;
     return 0;
   }
VarVal * VarTypes::VarTypesFactory::newUserVarVal (VarTypeId t) protected virtual
Definition at line 28 of file VarTypesFactory.cpp.
{
     (void)t;
     return 0;
   }
VarType * VarTypes::VarTypesFactory::newVarType (VarTypeId t)
Definition at line 43 of file VarTypesFactory.cpp.
References newUserVarType(), typeToString(), v, VarTypes::VARTYPE_ID_BLOB, VarTypes::VARTYPE_ID_BOOL, VarTypes::VARTYPE_ID_DOUBLE, VarTypes::VARTYPE_ID_EXTERNAL, VarTypes::VARTYPE_ID_INT, VarTypes::VARTYPE_ID_LIST, VarTypes::VARTYPE_ID_MIN_USERTYPE, VarTypes::VARTYPE_ID_QWIDGET, VarTypes::VARTYPE_ID_SELECTION, VarTypes::VARTYPE_ID_STRING, VarTypes::VARTYPE_ID_STRINGENUM, and VarTypes::VARTYPE_ID_TRIGGER.
Referenced by VarTypes::VarType::readChildrenHelper().
{
     if (t==VARTYPE_ID_BOOL) {
       return new VarBool();
     } else if (t==VARTYPE_ID_INT) {
       return new VarInt();
     } else if (t==VARTYPE_ID_DOUBLE) {
       return new VarDouble();
     } else if (t==VARTYPE_ID_STRING) {
       return new VarString();
     } else if (t==VARTYPE_ID_BLOB) {
       return new VarBlob();
     } else if (t==VARTYPE_ID_EXTERNAL) {
       return new VarExternal();
     } else if (t==VARTYPE_ID_LIST) {
       return new VarList();
     } else if (t==VARTYPE_ID_STRINGENUM) {
       return new VarStringEnum();
     } else if (t==VARTYPE_ID_SELECTION) {
       return new VarSelection();
     //} else if (t==VARTYPE_ID_PROTO_BUFFER) {
     //  return new VarProtoBuffer();
     } else if (t==VARTYPE_ID_QWIDGET) {
       return new VarQWidget();
     } else if (t==VARTYPE_ID_TRIGGER) {
       return new VarTrigger();
     } else {
       if (t >= VARTYPE_ID_MIN_USERTYPE) {
         VarType * v = newUserVarType(t);
         if (v==0) {
           fprintf(stderr,"Error: failed to construct unknown user-defined VarType with VarTypeId: %d (type name: %s).\n",t,typeToString(t).c_str());
           fprintf(stderr,"Note, if you were trying to define your own VarType, you need to overload the newUserVarType(...) function from the VarTypesFactory class.\n");
         }
         return v;
       } else {
         fprintf(stderr,"Error: failed to construct unknown VarType with VarTypeId: %d (type name: %s).\n",t,typeToString(t).c_str());
         fprintf(stderr,"Note if you were trying to define your own VarType, you need to ensure ");
         fprintf(stderr,"that your VarTypeId is greater than %d, as all other values are reserved ",VARTYPE_ID_MIN_USERTYPE);
         fprintf(stderr,"for future native types.\n");
         fprintf(stderr,"Otherwise, this error could have been caused if you are trying to load a VarTypes file that was created with a newer version, containing types that were not yet implemented in this version.\n");
         return 0;
       }
     }
   }
VarVal * VarTypes::VarTypesFactory::newVarVal (VarTypeId t)
Definition at line 87 of file VarTypesFactory.cpp.
{
     //TODO: add VarVal creation.
     (void)t;
     return 0;
   }
VarTypeId VarTypes::VarTypesFactory::stringToType (const string & s)
Definition at line 93 of file VarTypesFactory.cpp.
References stringToUserType(), v, VarTypes::VARTYPE_ID_BLOB, VarTypes::VARTYPE_ID_BOOL, VarTypes::VARTYPE_ID_DOUBLE, VarTypes::VARTYPE_ID_EXTERNAL, VarTypes::VARTYPE_ID_INT, VarTypes::VARTYPE_ID_LIST, VarTypes::VARTYPE_ID_MIN_USERTYPE, VarTypes::VARTYPE_ID_QWIDGET, VarTypes::VARTYPE_ID_SELECTION, VarTypes::VARTYPE_ID_STRING, VarTypes::VARTYPE_ID_STRINGENUM, VarTypes::VARTYPE_ID_TIMELINE, VarTypes::VARTYPE_ID_TIMEVAR, VarTypes::VARTYPE_ID_TRIGGER, VarTypes::VARTYPE_ID_UNDEFINED, VarTypes::VARTYPE_ID_VECTOR2D, and VarTypes::VARTYPE_ID_VECTOR3D.
Referenced by VarTypes::VarType::readChildrenHelper().
{
     if (s=="bool") {
       return VARTYPE_ID_BOOL;
     } else if (s=="double") {
       return VARTYPE_ID_DOUBLE;
     } else if (s=="int") {
       return VARTYPE_ID_INT;
     } else if (s=="string") {
       return VARTYPE_ID_STRING;
     } else if (s=="blob") {
       return VARTYPE_ID_BLOB;
     } else if (s=="external") {
       return VARTYPE_ID_EXTERNAL;
     } else if (s=="vector2d") {
       return VARTYPE_ID_VECTOR2D;
     } else if (s=="vector3d") {
       return VARTYPE_ID_VECTOR3D;
     } else if (s=="timeline") {
       return VARTYPE_ID_TIMELINE;
     } else if (s=="timevar") {
       return VARTYPE_ID_TIMEVAR;
     } else if (s=="list") {
       return VARTYPE_ID_LIST;
     } else if (s=="stringenum") {
       return VARTYPE_ID_STRINGENUM;
     } else if (s=="selection") {
       return VARTYPE_ID_SELECTION;
     } else if (s=="trigger") {
       return VARTYPE_ID_TRIGGER;
     } else if (s=="qwidget") {
       return VARTYPE_ID_QWIDGET;
     } else {
       VarTypeId v=stringToUserType(s);
       if (v==VARTYPE_ID_UNDEFINED) return v;
       if (v < VARTYPE_ID_MIN_USERTYPE) {
         fprintf(stderr,"Warning! stringToUserType needs to return a typeId greater or equal than %d (was %d for label '%s')\n",VARTYPE_ID_MIN_USERTYPE ,v, s.c_str());
         return VARTYPE_ID_UNDEFINED;
       } else {
         return v;
       }
     }
   }
VarTypeId VarTypes::VarTypesFactory::stringToUserType (const string & s) protected virtual
Definition at line 33 of file VarTypesFactory.cpp.
References VarTypes::VARTYPE_ID_UNDEFINED.
Referenced by stringToType().
{
     (void)s;
     return VARTYPE_ID_UNDEFINED;
   }
string VarTypes::VarTypesFactory::typeToString (VarTypeId t)
Definition at line 136 of file VarTypesFactory.cpp.
References userTypeToString(), VarTypes::VARTYPE_ID_BLOB, VarTypes::VARTYPE_ID_BOOL, VarTypes::VARTYPE_ID_DOUBLE, VarTypes::VARTYPE_ID_EXTERNAL, VarTypes::VARTYPE_ID_INT, VarTypes::VARTYPE_ID_LIST, VarTypes::VARTYPE_ID_QWIDGET, VarTypes::VARTYPE_ID_SELECTION, VarTypes::VARTYPE_ID_STRING, VarTypes::VARTYPE_ID_STRINGENUM, VarTypes::VARTYPE_ID_TIMELINE, VarTypes::VARTYPE_ID_TIMEVAR, VarTypes::VARTYPE_ID_TRIGGER, VarTypes::VARTYPE_ID_VECTOR2D, and VarTypes::VARTYPE_ID_VECTOR3D.
Referenced by VarTypes::VarVal::getTypeName(), and newVarType().
   {
     if (vt==VARTYPE_ID_BOOL) {
       return "bool";
     } else if (vt==VARTYPE_ID_DOUBLE) {
       return "double";
     } else if (vt==VARTYPE_ID_INT) {
       return "int";
     } else if (vt==VARTYPE_ID_STRING) {
       return "string";
     } else if (vt==VARTYPE_ID_EXTERNAL) {
       return "external";
     } else if (vt==VARTYPE_ID_BLOB) {
       return "blob";
     } else if (vt==VARTYPE_ID_VECTOR2D) {
       return "vector2d";
     } else if (vt==VARTYPE_ID_VECTOR3D) {
       return "vector3d";
     } else if (vt==VARTYPE_ID_TIMEVAR) {
       return "timevar";
     } else if (vt==VARTYPE_ID_TIMELINE) {
       return "timeline";
     } else if (vt==VARTYPE_ID_LIST) {
       return "list";
     } else if (vt==VARTYPE_ID_STRINGENUM) {
       return "stringenum";
     } else if (vt==VARTYPE_ID_SELECTION) {
       return "selection";
     } else if (vt==VARTYPE_ID_TRIGGER) {
       return "trigger";
     } else if (vt==VARTYPE_ID_QWIDGET) {
       return "qwidget";
     } else {
       string s = userTypeToString(vt);
       if (s=="" || s=="undefined") {
         printf("warning: unknown vartype: %d\n",vt);
         return "undefined";
       }
       return s;
     }
   }
string VarTypes::VarTypesFactory::userTypeToString (VarTypeId t) protected virtual
Definition at line 38 of file VarTypesFactory.cpp.
Referenced by typeToString().
{
     (void)t;
     return "undefined";
   }
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/VarTypesFactory.h
ssl-vision/src/shared/vartypes/VarTypesFactory.cpp