Documentation: SSL_FieldCicularArc Class Reference
SSL_FieldCicularArc Class Reference
#include <messages_robocup_ssl_geometry.pb.h>
Public Member Functions
SSL_FieldCicularArc ()
virtual ~SSL_FieldCicularArc ()
SSL_FieldCicularArc (const SSL_FieldCicularArc &from)
SSL_FieldCicularArc & operator= (const SSL_FieldCicularArc &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_FieldCicularArc *other)
SSL_FieldCicularArc * New () const PROTOBUF_FINAL
SSL_FieldCicularArc * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_FieldCicularArc &from)
void MergeFrom (const SSL_FieldCicularArc &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_name () const
void clear_name ()
const ::std::string & name () const
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
::std::string * mutable_name ()
::std::string * release_name ()
void set_allocated_name (::std::string *name)
bool has_center () const
void clear_center ()
const ::Vector2f & center () const
::Vector2f * release_center ()
::Vector2f * mutable_center ()
void set_allocated_center (::Vector2f *center)
bool has_radius () const
void clear_radius ()
float radius () const
void set_radius (float value)
bool has_a1 () const
void clear_a1 ()
float a1 () const
void set_a1 (float value)
bool has_a2 () const
void clear_a2 ()
float a2 () const
void set_a2 (float value)
bool has_thickness () const
void clear_thickness ()
float thickness () const
void set_thickness (float value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_FieldCicularArc & default_instance ()
static void InitAsDefaultInstance ()
static const SSL_FieldCicularArc * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kNameFieldNumber = 1
static const int kCenterFieldNumber = 2
static const int kRadiusFieldNumber = 3
static const int kA1FieldNumber = 4
static const int kA2FieldNumber = 5
static const int kThicknessFieldNumber = 6
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_FieldCicularArc *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_name ()
void clear_has_name ()
void set_has_center ()
void clear_has_center ()
void set_has_radius ()
void clear_has_radius ()
void set_has_a1 ()
void clear_has_a1 ()
void set_has_a2 ()
void clear_has_a2 ()
void set_has_thickness ()
void clear_has_thickness ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_FieldCicularArcImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::internal::ArenaStringPtr name_
::Vector2f * center_
float radius_
float a1_
float a2_
float thickness_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::TableStruct
void swap (SSL_FieldCicularArc &a, SSL_FieldCicularArc &b)
Detailed Description
Definition at line 365 of file messages_robocup_ssl_geometry.pb.h.
Constructor & Destructor Documentation
SSL_FieldCicularArc::SSL_FieldCicularArc ()
virtual SSL_FieldCicularArc::~SSL_FieldCicularArc () virtual
SSL_FieldCicularArc::SSL_FieldCicularArc (const SSL_FieldCicularArc & from)
Member Function Documentation
float SSL_FieldCicularArc::a1 () const inline
Definition at line 1510 of file messages_robocup_ssl_geometry.pb.h.
Referenced by GLSoccerView::updateFieldGeometry().
{
   // @@protoc_insertion_point(field_get:SSL_FieldCicularArc.a1)
   return a1_;
 }
float SSL_FieldCicularArc::a2 () const inline
Definition at line 1534 of file messages_robocup_ssl_geometry.pb.h.
Referenced by GLSoccerView::updateFieldGeometry().
{
   // @@protoc_insertion_point(field_get:SSL_FieldCicularArc.a2)
   return a2_;
 }
size_t SSL_FieldCicularArc::ByteSizeLong () const
const ::Vector2f & SSL_FieldCicularArc::center () const inline
Definition at line 1432 of file messages_robocup_ssl_geometry.pb.h.
References _Vector2f_default_instance_.
Referenced by GLSoccerView::updateFieldGeometry().
{
   const ::Vector2f* p = center_;
   // @@protoc_insertion_point(field_get:SSL_FieldCicularArc.center)
   return p != NULL ? *p : *reinterpret_cast<const ::Vector2f*>(
       &::_Vector2f_default_instance_);
 }
void SSL_FieldCicularArc::Clear ()
void SSL_FieldCicularArc::clear_a1 () inline
Definition at line 1506 of file messages_robocup_ssl_geometry.pb.h.
{
   a1_ = 0;
   clear_has_a1();
 }
void SSL_FieldCicularArc::clear_a2 () inline
Definition at line 1530 of file messages_robocup_ssl_geometry.pb.h.
{
   a2_ = 0;
   clear_has_a2();
 }
void SSL_FieldCicularArc::clear_center () inline
Definition at line 1428 of file messages_robocup_ssl_geometry.pb.h.
{
   if (center_ != NULL) center_->Clear();
   clear_has_center();
 }
void SSL_FieldCicularArc::clear_has_a1 () inline private
Definition at line 1503 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] &= ~0x00000008u;
 }
void SSL_FieldCicularArc::clear_has_a2 () inline private
Definition at line 1527 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] &= ~0x00000010u;
 }
void SSL_FieldCicularArc::clear_has_center () inline private
Definition at line 1425 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] &= ~0x00000002u;
 }
void SSL_FieldCicularArc::clear_has_name () inline private
Definition at line 1362 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void SSL_FieldCicularArc::clear_has_radius () inline private
Definition at line 1479 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] &= ~0x00000004u;
 }
void SSL_FieldCicularArc::clear_has_thickness () inline private
Definition at line 1551 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] &= ~0x00000020u;
 }
void SSL_FieldCicularArc::clear_name () inline
Definition at line 1365 of file messages_robocup_ssl_geometry.pb.h.
{
   name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   clear_has_name();
 }
void SSL_FieldCicularArc::clear_radius () inline
Definition at line 1482 of file messages_robocup_ssl_geometry.pb.h.
{
   radius_ = 0;
   clear_has_radius();
 }
void SSL_FieldCicularArc::clear_thickness () inline
Definition at line 1554 of file messages_robocup_ssl_geometry.pb.h.
{
   thickness_ = 0;
   clear_has_thickness();
 }
void SSL_FieldCicularArc::CopyFrom (const ::google::protobuf::Message & from)
void SSL_FieldCicularArc::CopyFrom (const SSL_FieldCicularArc & from)
static const SSL_FieldCicularArc& SSL_FieldCicularArc::default_instance () static
static const ::google::protobuf::Descriptor* SSL_FieldCicularArc::descriptor () static
inline ::google::protobuf::Arena* SSL_FieldCicularArc::GetArenaNoVirtual () const inline private
Definition at line 440 of file messages_robocup_ssl_geometry.pb.h.
Referenced by operator=().
{
     return NULL;
   }
int SSL_FieldCicularArc::GetCachedSize () const inline
Definition at line 433 of file messages_robocup_ssl_geometry.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata SSL_FieldCicularArc::GetMetadata () const
bool SSL_FieldCicularArc::has_a1 () const inline
Definition at line 1497 of file messages_robocup_ssl_geometry.pb.h.
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool SSL_FieldCicularArc::has_a2 () const inline
Definition at line 1521 of file messages_robocup_ssl_geometry.pb.h.
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
bool SSL_FieldCicularArc::has_center () const inline
Definition at line 1419 of file messages_robocup_ssl_geometry.pb.h.
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool SSL_FieldCicularArc::has_name () const inline
Definition at line 1356 of file messages_robocup_ssl_geometry.pb.h.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool SSL_FieldCicularArc::has_radius () const inline
Definition at line 1473 of file messages_robocup_ssl_geometry.pb.h.
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool SSL_FieldCicularArc::has_thickness () const inline
Definition at line 1545 of file messages_robocup_ssl_geometry.pb.h.
{
   return (_has_bits_[0] & 0x00000020u) != 0;
 }
static void SSL_FieldCicularArc::InitAsDefaultInstance () static
static const SSL_FieldCicularArc* SSL_FieldCicularArc::internal_default_instance () inline static
Definition at line 402 of file messages_robocup_ssl_geometry.pb.h.
References _SSL_FieldCicularArc_default_instance_.
{
     return reinterpret_cast<const SSL_FieldCicularArc*>(
                &_SSL_FieldCicularArc_default_instance_);
   }
::google::protobuf::uint8* SSL_FieldCicularArc::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void SSL_FieldCicularArc::InternalSwap (SSL_FieldCicularArc * other) private
bool SSL_FieldCicularArc::IsInitialized () const
void* SSL_FieldCicularArc::MaybeArenaPtr () const inline private
Definition at line 443 of file messages_robocup_ssl_geometry.pb.h.
{
     return NULL;
   }
void SSL_FieldCicularArc::MergeFrom (const ::google::protobuf::Message & from)
void SSL_FieldCicularArc::MergeFrom (const SSL_FieldCicularArc & from)
bool SSL_FieldCicularArc::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Vector2f * SSL_FieldCicularArc::mutable_center () inline
Definition at line 1445 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSLWorld::addFieldArc(), and RoboCupField::toProtoBuffer().
{
   set_has_center();
   if (center_ == NULL) {
     center_ = new ::Vector2f;
   }
   // @@protoc_insertion_point(field_mutable:SSL_FieldCicularArc.center)
   return center_;
 }
std::string * SSL_FieldCicularArc::mutable_name () inline
Definition at line 1398 of file messages_robocup_ssl_geometry.pb.h.
{
   set_has_name();
   // @@protoc_insertion_point(field_mutable:SSL_FieldCicularArc.name)
   return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
inline ::google::protobuf::UnknownFieldSet* SSL_FieldCicularArc::mutable_unknown_fields () inline
Definition at line 394 of file messages_robocup_ssl_geometry.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
const ::std::string & SSL_FieldCicularArc::name () const inline
Definition at line 1369 of file messages_robocup_ssl_geometry.pb.h.
Referenced by GLSoccerView::updateFieldGeometry().
{
   // @@protoc_insertion_point(field_get:SSL_FieldCicularArc.name)
   return name_.GetNoArena();
 }
SSL_FieldCicularArc* SSL_FieldCicularArc::New () const inline
Definition at line 416 of file messages_robocup_ssl_geometry.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_FieldCicularArc* SSL_FieldCicularArc::New (::google::protobuf::Arena * arena) const
SSL_FieldCicularArc& SSL_FieldCicularArc::operator= (const SSL_FieldCicularArc & from) inline
Definition at line 372 of file messages_robocup_ssl_geometry.pb.h.
References GetArenaNoVirtual().
{
     CopyFrom(from);
     return *this;
   }
float SSL_FieldCicularArc::radius () const inline
Definition at line 1486 of file messages_robocup_ssl_geometry.pb.h.
Referenced by GLSoccerView::updateFieldGeometry().
{
   // @@protoc_insertion_point(field_get:SSL_FieldCicularArc.radius)
   return radius_;
 }
Vector2f * SSL_FieldCicularArc::release_center () inline
Definition at line 1438 of file messages_robocup_ssl_geometry.pb.h.
{
   // @@protoc_insertion_point(field_release:SSL_FieldCicularArc.center)
   clear_has_center();
   ::Vector2f* temp = center_;
   center_ = NULL;
   return temp;
 }
std::string * SSL_FieldCicularArc::release_name () inline
Definition at line 1403 of file messages_robocup_ssl_geometry.pb.h.
{
   // @@protoc_insertion_point(field_release:SSL_FieldCicularArc.name)
   clear_has_name();
   return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
size_t SSL_FieldCicularArc::RequiredFieldsByteSizeFallback () const private
void SSL_FieldCicularArc::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void SSL_FieldCicularArc::set_a1 (float value) inline
Definition at line 1514 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSLWorld::addFieldArc(), and RoboCupField::toProtoBuffer().
{
   set_has_a1();
   a1_ = value;
   // @@protoc_insertion_point(field_set:SSL_FieldCicularArc.a1)
 }
void SSL_FieldCicularArc::set_a2 (float value) inline
Definition at line 1538 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSLWorld::addFieldArc(), and RoboCupField::toProtoBuffer().
{
   set_has_a2();
   a2_ = value;
   // @@protoc_insertion_point(field_set:SSL_FieldCicularArc.a2)
 }
void SSL_FieldCicularArc::set_allocated_center (::Vector2f * center) inline
Definition at line 1453 of file messages_robocup_ssl_geometry.pb.h.
{
   ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
   if (message_arena == NULL) {
     delete center_;
   }
   if (center) {
     ::google::protobuf::Arena* submessage_arena = NULL;
     if (message_arena != submessage_arena) {
       center = ::google::protobuf::internal::GetOwnedMessage(
           message_arena, center, submessage_arena);
     }
     set_has_center();
   } else {
     clear_has_center();
   }
   center_ = center;
   // @@protoc_insertion_point(field_set_allocated:SSL_FieldCicularArc.center)
 }
void SSL_FieldCicularArc::set_allocated_name (::std::string * name) inline
Definition at line 1408 of file messages_robocup_ssl_geometry.pb.h.
{
   if (name != NULL) {
     set_has_name();
   } else {
     clear_has_name();
   }
   name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
   // @@protoc_insertion_point(field_set_allocated:SSL_FieldCicularArc.name)
 }
void SSL_FieldCicularArc::set_has_a1 () inline private
Definition at line 1500 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] |= 0x00000008u;
 }
void SSL_FieldCicularArc::set_has_a2 () inline private
Definition at line 1524 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] |= 0x00000010u;
 }
void SSL_FieldCicularArc::set_has_center () inline private
Definition at line 1422 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] |= 0x00000002u;
 }
void SSL_FieldCicularArc::set_has_name () inline private
Definition at line 1359 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] |= 0x00000001u;
 }
void SSL_FieldCicularArc::set_has_radius () inline private
Definition at line 1476 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] |= 0x00000004u;
 }
void SSL_FieldCicularArc::set_has_thickness () inline private
Definition at line 1548 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] |= 0x00000020u;
 }
void SSL_FieldCicularArc::set_name (const ::std::string & value) inline
Definition at line 1373 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSLWorld::addFieldArc(), and RoboCupField::toProtoBuffer().
{
   set_has_name();
   name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
   // @@protoc_insertion_point(field_set:SSL_FieldCicularArc.name)
 }
void SSL_FieldCicularArc::set_name (const char * value) inline
Definition at line 1386 of file messages_robocup_ssl_geometry.pb.h.
{
   GOOGLE_DCHECK(value != NULL);
   set_has_name();
   name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
   // @@protoc_insertion_point(field_set_char:SSL_FieldCicularArc.name)
 }
void SSL_FieldCicularArc::set_name (const char * value, size_t size) inline
Definition at line 1392 of file messages_robocup_ssl_geometry.pb.h.
{
   set_has_name();
   name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
       ::std::string(reinterpret_cast<const char*>(value), size));
   // @@protoc_insertion_point(field_set_pointer:SSL_FieldCicularArc.name)
 }
void SSL_FieldCicularArc::set_radius (float value) inline
Definition at line 1490 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSLWorld::addFieldArc(), and RoboCupField::toProtoBuffer().
{
   set_has_radius();
   radius_ = value;
   // @@protoc_insertion_point(field_set:SSL_FieldCicularArc.radius)
 }
void SSL_FieldCicularArc::set_thickness (float value) inline
Definition at line 1562 of file messages_robocup_ssl_geometry.pb.h.
References SSL_GeometryFieldSize::boundary_width(), SSL_GeometryFieldSize::clear_boundary_width(), SSL_GeometryFieldSize::clear_field_length(), SSL_GeometryFieldSize::clear_field_width(), SSL_GeometryFieldSize::clear_goal_depth(), SSL_GeometryFieldSize::clear_goal_width(), SSL_GeometryFieldSize::clear_has_boundary_width(), SSL_GeometryFieldSize::clear_has_field_length(), SSL_GeometryFieldSize::clear_has_field_width(), SSL_GeometryFieldSize::clear_has_goal_depth(), SSL_GeometryFieldSize::clear_has_goal_width(), SSL_GeometryFieldSize::field_length(), SSL_GeometryFieldSize::field_width(), SSL_GeometryFieldSize::goal_depth(), SSL_GeometryFieldSize::goal_width(), SSL_GeometryFieldSize::has_boundary_width(), SSL_GeometryFieldSize::has_field_length(), SSL_GeometryFieldSize::has_field_width(), SSL_GeometryFieldSize::has_goal_depth(), SSL_GeometryFieldSize::has_goal_width(), SSL_GeometryFieldSize::set_boundary_width(), SSL_GeometryFieldSize::set_field_length(), SSL_GeometryFieldSize::set_field_width(), SSL_GeometryFieldSize::set_goal_depth(), SSL_GeometryFieldSize::set_goal_width(), SSL_GeometryFieldSize::set_has_boundary_width(), SSL_GeometryFieldSize::set_has_field_length(), SSL_GeometryFieldSize::set_has_field_width(), SSL_GeometryFieldSize::set_has_goal_depth(), and SSL_GeometryFieldSize::set_has_goal_width().
Referenced by SSLWorld::addFieldArc(), and RoboCupField::toProtoBuffer().
{
   set_has_thickness();
   thickness_ = value;
   // @@protoc_insertion_point(field_set:SSL_FieldCicularArc.thickness)
 }
void SSL_FieldCicularArc::SetCachedSize (int size) const private
void SSL_FieldCicularArc::SharedCtor () private
void SSL_FieldCicularArc::SharedDtor () private
void SSL_FieldCicularArc::Swap (SSL_FieldCicularArc * other)
float SSL_FieldCicularArc::thickness () const inline
Definition at line 1558 of file messages_robocup_ssl_geometry.pb.h.
Referenced by GLSoccerView::updateFieldGeometry().
{
   // @@protoc_insertion_point(field_get:SSL_FieldCicularArc.thickness)
   return thickness_;
 }
const ::google::protobuf::UnknownFieldSet& SSL_FieldCicularArc::unknown_fields () const inline
Definition at line 391 of file messages_robocup_ssl_geometry.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
SSL_FieldCicularArc::void::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_FieldCicularArcImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::TableStruct friend
Definition at line 533 of file messages_robocup_ssl_geometry.pb.h.
void swap (SSL_FieldCicularArc & a, SSL_FieldCicularArc & b) friend
Definition at line 410 of file messages_robocup_ssl_geometry.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int SSL_FieldCicularArc::_cached_size_ mutable private
Definition at line 526 of file messages_robocup_ssl_geometry.pb.h.
::google::protobuf::internal::HasBits<1> SSL_FieldCicularArc::_has_bits_ private
Definition at line 525 of file messages_robocup_ssl_geometry.pb.h.
::google::protobuf::internal::InternalMetadataWithArena SSL_FieldCicularArc::_internal_metadata_ private
Definition at line 524 of file messages_robocup_ssl_geometry.pb.h.
float SSL_FieldCicularArc::a1_ private
Definition at line 530 of file messages_robocup_ssl_geometry.pb.h.
float SSL_FieldCicularArc::a2_ private
Definition at line 531 of file messages_robocup_ssl_geometry.pb.h.
::Vector2f* SSL_FieldCicularArc::center_ private
Definition at line 528 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_FieldCicularArc::kA1FieldNumber = 4 static
Definition at line 488 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_FieldCicularArc::kA2FieldNumber = 5 static
Definition at line 495 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_FieldCicularArc::kCenterFieldNumber = 2 static
Definition at line 472 of file messages_robocup_ssl_geometry.pb.h.
PROTOBUF_CONSTEXPR int const SSL_FieldCicularArc::kIndexInFileMessages static
Initial value:
=
    2
Definition at line 406 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_FieldCicularArc::kNameFieldNumber = 1 static
Definition at line 457 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_FieldCicularArc::kRadiusFieldNumber = 3 static
Definition at line 481 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_FieldCicularArc::kThicknessFieldNumber = 6 static
Definition at line 502 of file messages_robocup_ssl_geometry.pb.h.
::google::protobuf::internal::ArenaStringPtr SSL_FieldCicularArc::name_ private
Definition at line 527 of file messages_robocup_ssl_geometry.pb.h.
float SSL_FieldCicularArc::radius_ private
Definition at line 529 of file messages_robocup_ssl_geometry.pb.h.
float SSL_FieldCicularArc::thickness_ private
Definition at line 532 of file messages_robocup_ssl_geometry.pb.h.
The documentation for this class was generated from the following file:
ssl-vision/build/messages_robocup_ssl_geometry.pb.h