Documentation: VarTypes::VarInt Class Reference
VarTypes::VarInt Class Reference
A Vartype for storing integers.
#include <VarInt.h>
Public Member Functions
virtual int getMin () const
virtual int getMax () const
virtual bool hasMin () const
virtual bool hasMax () const
virtual void setMin (int minval)
virtual void setMax (int maxval)
virtual void unsetMin ()
virtual void unsetMax ()
virtual bool setInt (int val)
set the value of this node to val.
virtual void setDefault (int val)
VarInt (string name="", int default_val=0, int min_val=INT_MIN, int max_val=INT_MAX)
virtual ~VarInt ()
virtual void resetToDefault ()
virtual int getInt () const
virtual double getDouble () const
virtual int get () const
virtual bool getBool () const
virtual bool setString (const string &val)
virtual bool setDouble (double val)
virtual bool setBool (bool val)
virtual bool hasValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
virtual QWidget * createEditor (const VarItemDelegate *delegate, QWidget *parent, const QStyleOptionViewItem &option)
virtual void setEditorData (const VarItemDelegate *delegate, QWidget *editor) const
virtual void setModelData (const VarItemDelegate *delegate, QWidget *editor)
Public Member Functions inherited from VarTypes::VarTypeTemplate< VarIntVal >
VarTypeTemplate (string name="")
Public Member Functions inherited from VarTypes::VarType
VarType (string name="")
virtual ~VarType ()
virtual vector< VarType * > getChildren () const
virtual void deleteAllChildren ()
virtual void setName (string name)
Set the string label of this node.
virtual string getName () const
Get the string label of this node.
virtual VarTypeFlag getFlags () const
virtual void setFlags (VarTypeFlag f)
virtual void addFlags (VarTypeFlag f)
virtual void removeFlags (VarTypeFlag f)
virtual bool areFlagsSet (VarTypeFlag f) const
VarType * findChild (string label) const
void writeXML (XMLNode &parent, bool blind_append=true)
Write the contents of this VarType node to an XMLNode.
void readXML (XMLNode &us)
Let this VarType node load the contents of an XMLNode.
virtual QSize sizeHint (const VarItemDelegate *delegate, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void paint (const VarItemDelegate *delegate, QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
Public Member Functions inherited from VarTypes::VarIntVal
VarIntVal (int default_val=0)
virtual ~VarIntVal ()
virtual void printdebug () const
virtual VarVal * clone () const
virtual VarTypeId getType () const
virtual string getString () const
Protected Member Functions
virtual void updateAttributes (XMLNode &us) const
virtual void readAttributes (XMLNode &us)
Protected Member Functions inherited from VarTypes::VarType
virtual void lock () const
virtual void unlock () const
virtual void changed ()
virtual void updateText (XMLNode &us) const
virtual void updateChildren (XMLNode &us) const
virtual void readText (XMLNode &us)
virtual void readChildren (XMLNode &us)
virtual void loadExternal ()
Protected Attributes
SafeVarVal< VarIntVal > _def
int _min
int _max
Protected Attributes inherited from VarTypes::VarType
QMutex * _mutex
VarTypeFlag _flags
string _name
Protected Attributes inherited from VarTypes::VarIntVal
int _val
Additional Inherited Members
Public Slots inherited from VarTypes::VarType
void mvcEditCompleted ()
A slot to receive signals from a model-view system that editing of this item was just completed.
Signals inherited from VarTypes::VarType
void hasChanged (VarType *)
void wasEdited (VarType *)
void XMLwasRead (VarType *)
This signal is triggered if data was written from an xml node.
void XMLwasWritten (VarType *)
This signal is triggered if data was written to an xml node.
Static Public Member Functions inherited from VarTypes::VarType
static void deleteAllVarChildren (XMLNode &node)
Clear an XMLNode's list of children.
static vector< VarType * > readChildrenHelper (XMLNode &parent, vector< VarType * > existing_children, bool only_update_existing, bool blind_append)
A helper function to read a list of children from XML and convert it to a vector of VarType nodes.
Static Protected Member Functions inherited from VarTypes::VarType
static string fixString (const char *cst)
static string intToString (int val)
static string doubleToString (double val)
static XMLNode findOrAppendChild (XMLNode &parent, string key, string val)
Detailed Description
A Vartype for storing integers.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 36 of file VarInt.h.
Constructor & Destructor Documentation
VarTypes::VarInt::VarInt (string name = "", int default_val = 0, int min_val = INT_MIN, int max_val = INT_MAX) inline
Definition at line 114 of file VarInt.h.
References VarTypes::VarType::changed(), setDefault(), setMax(), and setMin().
                                                                                         : VarIntVal(default_val), VarTypeTemplate<VarIntVal>(name)
     {
       setMin(min_val);
       setMax(max_val);
       setDefault(default_val);
       changed();
     }
virtual VarTypes::VarInt::~VarInt () inline virtual
Definition at line 122 of file VarInt.h.
 {}
Member Function Documentation
virtual QWidget* VarTypes::VarInt::createEditor (const VarItemDelegate * delegate, QWidget * parent, const QStyleOptionViewItem & option) inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 187 of file VarInt.h.
{
       //TODO: hookup editor changes on press-enter and on spin:
       (void)delegate;
       (void)parent;
       (void)option;
       QSpinBox * w = new QSpinBox(parent);
       //connect((const QObject *)w,SIGNAL(editingFinished ( int )),(const QObject *)delegate,SLOT(editorChangeEvent()));
       //uncomment the following line for instantaneous updates:
       //connect((const QObject *)w,SIGNAL(valueChanged ( int )),(const QObject *)delegate,SLOT(editorChangeEvent()));
       return w;
     }
virtual int VarTypes::VarInt::get () const inline virtual
Reimplemented from VarTypes::VarIntVal.
Definition at line 131 of file VarInt.h.
References getInt().
 { return getInt(); };
virtual bool VarTypes::VarInt::getBool () const inline virtual
Reimplemented from VarTypes::VarIntVal.
Definition at line 133 of file VarInt.h.
References getInt().
 { return (getInt() == 1 ? true : false); };
virtual double VarTypes::VarInt::getDouble () const inline virtual
Reimplemented from VarTypes::VarIntVal.
Definition at line 130 of file VarInt.h.
References getInt().
Referenced by getValue(), and CMPattern::TeamDetector::init().
 { return (double)getInt(); };
virtual int VarTypes::VarInt::getInt () const inline virtual
Reimplemented from VarTypes::VarIntVal.
Definition at line 129 of file VarInt.h.
References VarTypes::VarIntVal::_val, VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
Referenced by CaptureFlycap::CaptureFlycap(), CaptureFlycap::convertFrame(), CaptureFlycap::copyAndConvertFrame(), CaptureDC1394v2::copyAndConvertFrame(), get(), getBool(), getDouble(), CaptureGenerator::getFrame(), CMPattern::TeamSelector::getNumberRobots(), CMPattern::TeamDetector::init(), PluginFindBlobs::process(), PluginDetectBalls::process(), PluginDVR::process(), MultiStackRoboCupSSL::RefreshLegacyNetworkOutput(), MultiStackRoboCupSSL::RefreshNetworkOutput(), setEditorData(), CaptureFlycap::startCapture(), CaptureBlueFox2::startCapture(), CaptureV4L::startCapture(), CaptureDC1394v2::startCapture(), CaptureFlycap::writeParameterValues(), CaptureBlueFox2::writeParameterValues(), CaptureV4L::writeParameterValues(), and CaptureDC1394v2::writeParameterValues().
 { int res; lock(); res=_val; unlock(); return res; };
virtual int VarTypes::VarInt::getMax () const inline virtual
get the maximum accepted value if this data-type has a limited range
See also
setMax(...)
hasMax()
unsetMax()
Definition at line 56 of file VarInt.h.
References _max, VarTypes::VarType::lock(), VarTypes::VarType::unlock(), and v.
Referenced by getMaxValue(), setEditorData(), setInt(), and updateAttributes().
 { lock(); int v=_max; unlock(); return v; }
virtual double VarTypes::VarInt::getMaxValue () const inline virtual
Reimplemented from VarTypes::VarIntVal.
Definition at line 144 of file VarInt.h.
References getMax().
 { return (double)getMax(); }
virtual int VarTypes::VarInt::getMin () const inline virtual
get the minimum accepted value if this data-type has a limited range
See also
setMin(...)
hasMin()
unsetMin()
Definition at line 50 of file VarInt.h.
References _min, VarTypes::VarType::lock(), VarTypes::VarType::unlock(), and v.
Referenced by getMinValue(), setEditorData(), setInt(), and updateAttributes().
 { lock(); int v=_min; unlock(); return v; }
virtual double VarTypes::VarInt::getMinValue () const inline virtual
Reimplemented from VarTypes::VarIntVal.
Definition at line 143 of file VarInt.h.
References getMin().
 { return (double)getMin(); }
virtual double VarTypes::VarInt::getValue () const inline virtual
Reimplemented from VarTypes::VarIntVal.
Definition at line 145 of file VarInt.h.
References getDouble().
 { return getDouble(); }
virtual bool VarTypes::VarInt::hasMax () const inline virtual
check whether this data type has a limited maximum value
See also
getMax(...)
setMax(...)
unsetMax()
Definition at line 68 of file VarInt.h.
References VarTypes::VarType::lock(), VarTypes::VarType::unlock(), and v.
Referenced by hasMaxValue(), setInt(), and updateAttributes().
 { lock(); bool v= (_max != INT_MAX); unlock(); return v; }
virtual bool VarTypes::VarInt::hasMaxValue () const inline virtual
Reimplemented from VarTypes::VarIntVal.
Definition at line 141 of file VarInt.h.
References hasMax().
 { return hasMax(); }
virtual bool VarTypes::VarInt::hasMin () const inline virtual
check whether this data type has a limited minimum value
See also
getMin(...)
setMin(...)
unsetMin()
Definition at line 62 of file VarInt.h.
References VarTypes::VarType::lock(), VarTypes::VarType::unlock(), and v.
Referenced by hasMinValue(), setInt(), and updateAttributes().
 { lock(); bool v= (_min != INT_MIN); unlock(); return v; }
virtual bool VarTypes::VarInt::hasMinValue () const inline virtual
Reimplemented from VarTypes::VarIntVal.
Definition at line 142 of file VarInt.h.
References hasMin().
 { return hasMin(); }
virtual bool VarTypes::VarInt::hasValue () const inline virtual
Reimplemented from VarTypes::VarIntVal.
Definition at line 140 of file VarInt.h.
 { return true; }
virtual void VarTypes::VarInt::readAttributes (XMLNode & us) inline protected virtual
Reimplemented from VarTypes::VarType.
Definition at line 164 of file VarInt.h.
References VarTypes::VarType::fixString(), VarTypes::XMLNode::getAttribute(), setMax(), setMin(), unsetMax(), and unsetMin().
     {
       string s = fixString(us.getAttribute("minval"));
       if (s=="") {
         unsetMin();
       } else {
         int num=0; sscanf(s.c_str(),"%d",&num);
         setMin(num);
       }
       s = fixString(us.getAttribute("maxval"));
       if (s=="") {
         unsetMax();
       } else {
         int num=0; sscanf(s.c_str(),"%d",&num);
         setMax(num);
       }
     }
virtual void VarTypes::VarInt::resetToDefault () inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 124 of file VarInt.h.
References setInt().
Referenced by CaptureV4L::writeParameterValues().
     {
       setInt(_def.getInt());
     }
virtual bool VarTypes::VarInt::setBool (bool val) inline virtual
Reimplemented from VarTypes::VarIntVal.
Definition at line 137 of file VarInt.h.
References setInt().
 { return setInt(val ? 1 : 0);  };
virtual void VarTypes::VarInt::setDefault (int val) inline virtual
Definition at line 108 of file VarInt.h.
References VarTypes::VarType::changed().
Referenced by CaptureV4L::readParameterProperty(), and VarInt().
     {
       _def.setInt(val);
       changed();
     }
virtual bool VarTypes::VarInt::setDouble (double val) inline virtual
Reimplemented from VarTypes::VarIntVal.
Definition at line 136 of file VarInt.h.
References setInt().
 { return setInt((int)val);  };
virtual void VarTypes::VarInt::setEditorData (const VarItemDelegate * delegate, QWidget * editor) const inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 199 of file VarInt.h.
References getInt(), getMax(), and getMin().
{
       (void)delegate;
       QSpinBox * spin=(QSpinBox *) editor;
       spin->setRange(getMin(),getMax() );
       spin->setValue(getInt());
     }
virtual bool VarTypes::VarInt::setInt (int val) inline virtual
set the value of this node to val.
Reimplemented from VarTypes::VarIntVal.
Definition at line 95 of file VarInt.h.
References _max, _min, getMax(), getMin(), hasMax(), hasMin(), and VarTypes::VarIntVal::setInt().
Referenced by CaptureV4L::readParameterValues(), CaptureDC1394v2::readParameterValues(), resetToDefault(), setBool(), setDouble(), setModelData(), and setString().
     {
       int tmp;
       if (hasMin() && val < getMin()) {
         tmp=_min;
       } else if (hasMax() && val > getMax()) {
         tmp=_max;
       } else {
         tmp=val;
       }
       return VarIntVal::setInt(tmp);
     };
virtual void VarTypes::VarInt::setMax (int maxval) inline virtual
limit the maximum value of this parameter to a pre-set value
See also
getMax(...)
hasMax()
unsetMax()
Definition at line 80 of file VarInt.h.
References VarTypes::VarType::changed(), VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
Referenced by readAttributes(), CaptureV4L::readParameterProperty(), CaptureDC1394v2::readParameterProperty(), and VarInt().
 { lock(); _max=maxval; unlock(); changed(); }
virtual void VarTypes::VarInt::setMin (int minval) inline virtual
limit the minumum value of this parameter to a pre-set value
See also
getMin(...)
hasMin()
unsetMin()
Definition at line 74 of file VarInt.h.
References VarTypes::VarType::changed(), VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
Referenced by PluginDVR::PluginDVR(), readAttributes(), CaptureV4L::readParameterProperty(), CaptureDC1394v2::readParameterProperty(), and VarInt().
 { lock(); _min=minval; unlock(); changed(); }
virtual void VarTypes::VarInt::setModelData (const VarItemDelegate * delegate, QWidget * editor) inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 206 of file VarInt.h.
References VarTypes::VarType::mvcEditCompleted(), and setInt().
{
       (void)delegate;
       QSpinBox * spin=(QSpinBox *) editor;
       if (setInt(spin->value()) ) mvcEditCompleted();
     }
virtual bool VarTypes::VarInt::setString (const string & val) inline virtual
Reimplemented from VarTypes::VarIntVal.
Definition at line 135 of file VarInt.h.
References setInt().
 { int num=0; sscanf(val.c_str(),"%d",&num); return setInt(num); };
virtual void VarTypes::VarInt::unsetMax () inline virtual
unset any previous limit of maximum value of this parameter
See also
getMax(...)
setMax(...)
hasMax()
Definition at line 92 of file VarInt.h.
References VarTypes::VarType::changed(), VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
Referenced by readAttributes().
 { lock(); _max=INT_MAX; unlock(); changed(); }
virtual void VarTypes::VarInt::unsetMin () inline virtual
unset any previous limit of minimum value of this parameter
See also
getMin(...)
setMin(...)
hasMin()
Definition at line 86 of file VarInt.h.
References VarTypes::VarType::changed(), VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
Referenced by readAttributes().
 { lock(); _min=INT_MIN; unlock(); changed(); }
virtual void VarTypes::VarInt::updateAttributes (XMLNode & us) const inline protected virtual
Reimplemented from VarTypes::VarType.
Definition at line 150 of file VarInt.h.
References getMax(), getMin(), hasMax(), hasMin(), VarTypes::VarType::intToString(), and VarTypes::XMLNode::updateAttribute().
     {
       if (hasMin()) {
         us.updateAttribute(intToString(getMin()).c_str(),"minval","minval");
       } else {
         us.updateAttribute("","minval","minval");
       }
       if (hasMax()) {
         us.updateAttribute(intToString(getMax()).c_str(),"maxval","maxval");
       } else {
         us.updateAttribute("","maxval","maxval");
       }
     }
Field Documentation
SafeVarVal<VarIntVal> VarTypes::VarInt::_def protected
Definition at line 41 of file VarInt.h.
int VarTypes::VarInt::_max protected
Definition at line 43 of file VarInt.h.
Referenced by getMax(), and setInt().
int VarTypes::VarInt::_min protected
Definition at line 42 of file VarInt.h.
Referenced by getMin(), and setInt().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/vartypes/primitives/VarInt.h