Documentation: Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder Class Reference
Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
MessagesRobocupSslDetection.SSL_DetectionRobot getDefaultInstanceForType ()
MessagesRobocupSslDetection.SSL_DetectionRobot build ()
MessagesRobocupSslDetection.SSL_DetectionRobot buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (MessagesRobocupSslDetection.SSL_DetectionRobot other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasConfidence ()
float getConfidence ()
Builder setConfidence (float value)
Builder clearConfidence ()
boolean hasRobotId ()
int getRobotId ()
Builder setRobotId (int value)
Builder clearRobotId ()
boolean hasX ()
float getX ()
Builder setX (float value)
Builder clearX ()
boolean hasY ()
float getY ()
Builder setY (float value)
Builder clearY ()
boolean hasOrientation ()
float getOrientation ()
Builder setOrientation (float value)
Builder clearOrientation ()
boolean hasPixelX ()
float getPixelX ()
Builder setPixelX (float value)
Builder clearPixelX ()
boolean hasPixelY ()
float getPixelY ()
Builder setPixelY (float value)
Builder clearPixelY ()
boolean hasHeight ()
float getHeight ()
Builder setHeight (float value)
Builder clearHeight ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
MessagesRobocupSslDetection.SSL_DetectionRobot buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
float confidence_
int robotId_
float x_
float y_
float orientation_
float pixelX_
float pixelY_
float height_
Detailed Description
Definition at line 1074 of file MessagesRobocupSslDetection.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.Builder () inline private
Definition at line 1088 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.Builder (BuilderParent parent) inline private
Definition at line 1092 of file MessagesRobocupSslDetection.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.build () inline
Definition at line 1138 of file MessagesRobocupSslDetection.java.
{
         MessagesRobocupSslDetection.SSL_DetectionRobot result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 1146 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.parseDelimitedFrom().
{
         MessagesRobocupSslDetection.SSL_DetectionRobot result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.buildPartial () inline
Definition at line 1156 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.confidence_.
{
         MessagesRobocupSslDetection.SSL_DetectionRobot result = new MessagesRobocupSslDetection.SSL_DetectionRobot(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         result.confidence_ = confidence_;
         if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
           to_bitField0_ |= 0x00000002;
         }
         result.robotId_ = robotId_;
         if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
           to_bitField0_ |= 0x00000004;
         }
         result.x_ = x_;
         if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
           to_bitField0_ |= 0x00000008;
         }
         result.y_ = y_;
         if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
           to_bitField0_ |= 0x00000010;
         }
         result.orientation_ = orientation_;
         if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
           to_bitField0_ |= 0x00000020;
         }
         result.pixelX_ = pixelX_;
         if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
           to_bitField0_ |= 0x00000040;
         }
         result.pixelY_ = pixelY_;
         if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
           to_bitField0_ |= 0x00000080;
         }
         result.height_ = height_;
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clear () inline
Definition at line 1104 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clear().
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clear().
{
         super.clear();
         confidence_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000001);
         robotId_ = 0;
         bitField0_ = (bitField0_ & ~0x00000002);
         x_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000004);
         y_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000008);
         orientation_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000010);
         pixelX_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000020);
         pixelY_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000040);
         height_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000080);
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clearConfidence () inline
Definition at line 1343 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000001);
         confidence_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clearHeight () inline
Definition at line 1490 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.initFields().
{
         bitField0_ = (bitField0_ & ~0x00000080);
         height_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clearOrientation () inline
Definition at line 1427 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000010);
         orientation_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clearPixelX () inline
Definition at line 1448 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000020);
         pixelX_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clearPixelY () inline
Definition at line 1469 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000040);
         pixelY_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clearRobotId () inline
Definition at line 1364 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000002);
         robotId_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clearX () inline
Definition at line 1385 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000004);
         x_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clearY () inline
Definition at line 1406 of file MessagesRobocupSslDetection.java.
{
         bitField0_ = (bitField0_ & ~0x00000008);
         y_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clone () inline
Definition at line 1125 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.create () inline static private
Definition at line 1100 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.newBuilder().
{
         return new Builder();
       }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.getConfidence () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1334 of file MessagesRobocupSslDetection.java.
{
         return confidence_;
       }
MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.getDefaultInstanceForType () inline
Definition at line 1134 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstance().
{
         return MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstance();
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.getDescriptor () inline static
Definition at line 1078 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.internal_static_SSL_DetectionRobot_descriptor.
{
         return MessagesRobocupSslDetection.internal_static_SSL_DetectionRobot_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.getDescriptorForType () inline
Definition at line 1130 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getDescriptor().
{
         return MessagesRobocupSslDetection.SSL_DetectionRobot.getDescriptor();
       }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.getHeight () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1481 of file MessagesRobocupSslDetection.java.
{
         return height_;
       }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.getOrientation () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1418 of file MessagesRobocupSslDetection.java.
{
         return orientation_;
       }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.getPixelX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1439 of file MessagesRobocupSslDetection.java.
{
         return pixelX_;
       }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.getPixelY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1460 of file MessagesRobocupSslDetection.java.
{
         return pixelY_;
       }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.getRobotId () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1355 of file MessagesRobocupSslDetection.java.
{
         return robotId_;
       }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.getX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1376 of file MessagesRobocupSslDetection.java.
{
         return x_;
       }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.getY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1397 of file MessagesRobocupSslDetection.java.
{
         return y_;
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.hasConfidence () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1331 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.hasHeight () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1478 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000080) == 0x00000080);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.hasOrientation () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1415 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000010) == 0x00000010);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.hasPixelX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1436 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000020) == 0x00000020);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.hasPixelY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1457 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000040) == 0x00000040);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.hasRobotId () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1352 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000002) == 0x00000002);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.hasX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1373 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000004) == 0x00000004);
       }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.hasY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 1394 of file MessagesRobocupSslDetection.java.
{
         return ((bitField0_ & 0x00000008) == 0x00000008);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 1083 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.internal_static_SSL_DetectionRobot_fieldAccessorTable.
{
         return MessagesRobocupSslDetection.internal_static_SSL_DetectionRobot_fieldAccessorTable;
       }
final boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.isInitialized () inline
Definition at line 1236 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasConfidence(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasPixelX(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasPixelY(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasX(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasY().
{
         if (!hasConfidence()) {
           return false;
         }
         if (!hasX()) {
           return false;
         }
         if (!hasY()) {
           return false;
         }
         if (!hasPixelX()) {
           return false;
         }
         if (!hasPixelY()) {
           return false;
         }
         return true;
       }
void Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.maybeForceBuilderInitialization () inline private
Definition at line 1096 of file MessagesRobocupSslDetection.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
         }
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 1197 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clone(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.newBuilder().
{
         if (other instanceof MessagesRobocupSslDetection.SSL_DetectionRobot) {
           return mergeFrom((MessagesRobocupSslDetection.SSL_DetectionRobot)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.mergeFrom (MessagesRobocupSslDetection.SSL_DetectionRobot other) inline
Definition at line 1206 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstance().
{
         if (other == MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstance()) return this;
         if (other.hasConfidence()) {
           setConfidence(other.getConfidence());
         }
         if (other.hasRobotId()) {
           setRobotId(other.getRobotId());
         }
         if (other.hasX()) {
           setX(other.getX());
         }
         if (other.hasY()) {
           setY(other.getY());
         }
         if (other.hasOrientation()) {
           setOrientation(other.getOrientation());
         }
         if (other.hasPixelX()) {
           setPixelX(other.getPixelX());
         }
         if (other.hasPixelY()) {
           setPixelY(other.getPixelY());
         }
         if (other.hasHeight()) {
           setHeight(other.getHeight());
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 1260 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.Builder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 13: {
               bitField0_ |= 0x00000001;
               confidence_ = input.readFloat();
               break;
             }
             case 16: {
               bitField0_ |= 0x00000002;
               robotId_ = input.readUInt32();
               break;
             }
             case 29: {
               bitField0_ |= 0x00000004;
               x_ = input.readFloat();
               break;
             }
             case 37: {
               bitField0_ |= 0x00000008;
               y_ = input.readFloat();
               break;
             }
             case 45: {
               bitField0_ |= 0x00000010;
               orientation_ = input.readFloat();
               break;
             }
             case 53: {
               bitField0_ |= 0x00000020;
               pixelX_ = input.readFloat();
               break;
             }
             case 61: {
               bitField0_ |= 0x00000040;
               pixelY_ = input.readFloat();
               break;
             }
             case 69: {
               bitField0_ |= 0x00000080;
               height_ = input.readFloat();
               break;
             }
           }
         }
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.setConfidence (float value) inline
Definition at line 1337 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000001;
         confidence_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.setHeight (float value) inline
Definition at line 1484 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000080;
         height_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.setOrientation (float value) inline
Definition at line 1421 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000010;
         orientation_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.setPixelX (float value) inline
Definition at line 1442 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000020;
         pixelX_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.setPixelY (float value) inline
Definition at line 1463 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000040;
         pixelY_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.setRobotId (int value) inline
Definition at line 1358 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000002;
         robotId_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.setX (float value) inline
Definition at line 1379 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000004;
         x_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.setY (float value) inline
Definition at line 1400 of file MessagesRobocupSslDetection.java.
{
         bitField0_ |= 0x00000008;
         y_ = value;
         onChanged();
         return this;
       }
Field Documentation
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.bitField0_ private
Definition at line 1327 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.confidence_ private
Definition at line 1330 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.height_ private
Definition at line 1477 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.orientation_ private
Definition at line 1414 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.pixelX_ private
Definition at line 1435 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.pixelY_ private
Definition at line 1456 of file MessagesRobocupSslDetection.java.
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.robotId_ private
Definition at line 1351 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.x_ private
Definition at line 1372 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.y_ private
Definition at line 1393 of file MessagesRobocupSslDetection.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslDetection.java