Documentation: role._GoToPoint_ Namespace Reference
role._GoToPoint_ Namespace Reference
Functions
def init (_kub, target, theta)
def reset ()
def execute (startTime, DIST_THRESH, avoid_ball=False)
Variables
run
shared = memcache.Client(BS_ADDRESS,debug=0)
kub = None
start_time = None
GOAL_POINT = None
bool FLAG_move = False
bool FLAG_turn = False
int rotate = 0
bool FIRST_CALL = True
prev_state = shared.get('state')
Function Documentation
def role._GoToPoint_.execute (startTime, DIST_THRESH, avoid_ball = False)
Definition at line 52 of file _GoToPoint_.py.
References GVector.abs(), GVector.dist(), velocity.run_w.Get_Omega(), velocity.run.Get_Vel(), utils.functions.normalize_angle(), print(), and role._GoToPoint_.reset().
 def execute(startTime,DIST_THRESH,avoid_ball=False):
     global GOAL_POINT, start_time,FIRST_CALL,FLAG_turn,FLAG_move,kub,prev_state
     # print DIST_THRESH
     if FIRST_CALL:
         print("First call of _gotopoint_")
         start_time = startTime
         FIRST_CALL = False
         vx_end,vy_end = 0,0
     while not (FLAG_move and FLAG_turn):
         kub.state = shared.get('state')
         if not(prev_state == kub.state):
             prev_state = kub.state
             t = rospy.Time.now()
             t = t.secs + 1.0*t.nsecs/pow(10,9)
             [vx, vy, vw, REPLANNED] = velocity.run.Get_Vel(start_time, t, kub.kubs_id, GOAL_POINT, kub.state.homePos, kub.state.awayPos, avoid_ball)
             velocity_magnitude = Vector2D(vx,vy).abs(Vector2D(vx,vy))
             if velocity_magnitude > MAX_BOT_SPEED:
                 angle_movement = math.atan2(vy,vx)
                 print("_____________Velocity Changed____________")
                 vy = MAX_BOT_SPEED*math.sin(angle_movement)
                 vx = MAX_BOT_SPEED*math.cos(angle_movement)
                 # pass
             # vy = min(vy,MIN_BOT_SPEED)
             vw = Get_Omega(kub.kubs_id,rotate,kub.state.homePos)
             if not vw:
                 vw = 0
             if(REPLANNED):
                 reset()
             if not vx and not vy:
                 vx,vy = vx_end,vy_end
             else:
                 vx_end,vy_end = vx,vy
             if abs(normalize_angle(kub.state.homePos[kub.kubs_id].theta-rotate))<ROTATION_FACTOR:
                 kub.turn(0)
                 print("Angle completed")
                 FLAG_turn = True
             else:
                 kub.turn(vw)
             # print("Distance ______",dist(kub.state.homePos[kub.kubs_id], GOAL_POINT))
             if dist(kub.state.homePos[kub.kubs_id], GOAL_POINT)<0 :
                 kub.move(0,0)
                 print("Distance completed")
                 FLAG_move = True
             else:
                 print("Sending velocity",vx,vy)
                 kub.move(vx, vy)
             kub.execute()
             yield kub,GOAL_POINT
         # else:
         #     print "_______False loop__________"
     kub.execute()
     # kub.execute()
     yield kub,GOAL_POINT
def role._GoToPoint_.init (_kub, target, theta)
Definition at line 35 of file _GoToPoint_.py.
 def init(_kub,target,theta):
     global kub,GOAL_POINT,rotate,FLAG_turn,FLAG_move,FIRST_CALL
     kub = _kub
     GOAL_POINT = point_2d()
     rotate = theta
     GOAL_POINT.x = target.x
     GOAL_POINT.y = target.y
     FLAG_move = False
     FLAG_turn = False
     FIRST_CALL = True
def role._GoToPoint_.reset ()
Definition at line 47 of file _GoToPoint_.py.
Referenced by role._GoToPoint_.execute().
 def reset():
     global start_time
     start_time = rospy.Time.now()
     start_time = 1.0*start_time.secs + 1.0*start_time.nsecs/pow(10,9)
Variable Documentation
bool role._GoToPoint_.FIRST_CALL = True
Definition at line 32 of file _GoToPoint_.py.
bool role._GoToPoint_.FLAG_move = False
Definition at line 27 of file _GoToPoint_.py.
bool role._GoToPoint_.FLAG_turn = False
Definition at line 28 of file _GoToPoint_.py.
role._GoToPoint_.GOAL_POINT = None
Definition at line 26 of file _GoToPoint_.py.
role._GoToPoint_.kub = None
Definition at line 24 of file _GoToPoint_.py.
role._GoToPoint_.prev_state = shared.get('state')
Definition at line 34 of file _GoToPoint_.py.
Referenced by BeliefState.update_frame().
int role._GoToPoint_.rotate = 0
Definition at line 29 of file _GoToPoint_.py.
Referenced by GVector.intersection().
role._GoToPoint_.run
Definition at line 5 of file _GoToPoint_.py.
Referenced by Client.Interface.main().
role._GoToPoint_.shared = memcache.Client(BS_ADDRESS,debug=0)
Definition at line 22 of file _GoToPoint_.py.
role._GoToPoint_.start_time = None
Definition at line 25 of file _GoToPoint_.py.