Documentation: VarTypes::VarBase64 Class Reference
VarTypes::VarBase64 Class Reference
A singleton wrapper to XMLParserBase64Tool.
#include <VarBase64.h>
Static Public Member Functions
static VarTypes::XMLParserBase64Tool * getTool ()
Protected Member Functions
VarBase64 ()
VarBase64 (const VarBase64 &)
VarBase64 & operator= (const VarBase64 &)
Private Attributes
VarTypes::XMLParserBase64Tool * tool
Static Private Attributes
static VarBase64 * pinstance = 0
Detailed Description
A singleton wrapper to XMLParserBase64Tool.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
This is a singleton wrapper to the XMLParserBase64Tool It is used for the en/decoding of binary data to/from xml using the Base64 ascii format.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 41 of file VarBase64.h.
Constructor & Destructor Documentation
VarTypes::VarBase64::VarBase64 () protected
Definition at line 36 of file VarBase64.cpp.
References tool.
Referenced by getTool().
   {
     tool = new XMLParserBase64Tool();
   }
VarTypes::VarBase64::VarBase64 (const VarBase64 &) protected
Member Function Documentation
XMLParserBase64Tool * VarTypes::VarBase64::getTool () static
Definition at line 27 of file VarBase64.cpp.
References pinstance, tool, and VarBase64().
Referenced by VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::getSerialString(), VarTypes::VarBlob::getSerialString(), VarTypes::VarProtoBufferVal< CLASS_VARVAL_TYPE, TPL_vartype_id >::setSerialString(), and VarTypes::VarBlob::setSerialString().
   {
     if (pinstance == 0)  // is it the first call?
     {
       pinstance = new VarBase64; // create sole instance
     }
     return pinstance->tool; // address of sole instance
   }
VarBase64& VarTypes::VarBase64::operator= (const VarBase64 &) protected
Field Documentation
VarBase64 * VarTypes::VarBase64::pinstance = 0 static private
Definition at line 50 of file VarBase64.h.
Referenced by getTool().
VarTypes::XMLParserBase64Tool* VarTypes::VarBase64::tool private
Definition at line 51 of file VarBase64.h.
Referenced by getTool(), and VarBase64().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/VarBase64.h
ssl-vision/src/shared/vartypes/VarBase64.cpp