Documentation: Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder Class Reference
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
MessagesRobocupSslGeometry.SSL_GeometryData getDefaultInstanceForType ()
MessagesRobocupSslGeometry.SSL_GeometryData build ()
MessagesRobocupSslGeometry.SSL_GeometryData buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (MessagesRobocupSslGeometry.SSL_GeometryData other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasField ()
MessagesRobocupSslGeometry.SSL_GeometryFieldSize getField ()
Builder setField (MessagesRobocupSslGeometry.SSL_GeometryFieldSize value)
Builder setField (MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder builderForValue)
Builder mergeField (MessagesRobocupSslGeometry.SSL_GeometryFieldSize value)
Builder clearField ()
MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder getFieldBuilder ()
MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder getFieldOrBuilder ()
java.util.List< MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration > getCalibList ()
int getCalibCount ()
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration getCalib (int index)
Builder setCalib (int index, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration value)
Builder setCalib (int index, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder builderForValue)
Builder addCalib (MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration value)
Builder addCalib (int index, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration value)
Builder addCalib (MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder builderForValue)
Builder addCalib (int index, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder builderForValue)
Builder addAllCalib (java.lang.Iterable<?extends MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration > values)
Builder clearCalib ()
Builder removeCalib (int index)
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder getCalibBuilder (int index)
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder getCalibOrBuilder (int index)
java.util.List<?extends MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder > getCalibOrBuilderList ()
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder addCalibBuilder ()
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder addCalibBuilder (int index)
java.util.List< MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder > getCalibBuilderList ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
MessagesRobocupSslGeometry.SSL_GeometryData buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslGeometry.SSL_GeometryFieldSize, MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder > getFieldFieldBuilder ()
void ensureCalibIsMutable ()
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder > getCalibFieldBuilder ()
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
MessagesRobocupSslGeometry.SSL_GeometryFieldSize field_ = MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance()
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslGeometry.SSL_GeometryFieldSize, MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder > fieldBuilder_
java.util.List< MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration > calib_
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder > calibBuilder_
Detailed Description
Definition at line 2660 of file MessagesRobocupSslGeometry.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.Builder () inline private
Definition at line 2674 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.Builder (BuilderParent parent) inline private
Definition at line 2678 of file MessagesRobocupSslGeometry.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.addAllCalib (java.lang.Iterable<?extends MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration > values) inline
Definition at line 3070 of file MessagesRobocupSslGeometry.java.
{
         if (calibBuilder_ == null) {
           ensureCalibIsMutable();
           super.addAll(values, calib_);
           onChanged();
         } else {
           calibBuilder_.addAllMessages(values);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.addCalib (MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration value) inline
Definition at line 3021 of file MessagesRobocupSslGeometry.java.
{
         if (calibBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureCalibIsMutable();
           calib_.add(value);
           onChanged();
         } else {
           calibBuilder_.addMessage(value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.addCalib (int index, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration value) inline
Definition at line 3034 of file MessagesRobocupSslGeometry.java.
{
         if (calibBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureCalibIsMutable();
           calib_.add(index, value);
           onChanged();
         } else {
           calibBuilder_.addMessage(index, value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.addCalib (MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder builderForValue) inline
Definition at line 3048 of file MessagesRobocupSslGeometry.java.
{
         if (calibBuilder_ == null) {
           ensureCalibIsMutable();
           calib_.add(builderForValue.build());
           onChanged();
         } else {
           calibBuilder_.addMessage(builderForValue.build());
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.addCalib (int index, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder builderForValue) inline
Definition at line 3059 of file MessagesRobocupSslGeometry.java.
{
         if (calibBuilder_ == null) {
           ensureCalibIsMutable();
           calib_.add(index, builderForValue.build());
           onChanged();
         } else {
           calibBuilder_.addMessage(index, builderForValue.build());
         }
         return this;
       }
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.addCalibBuilder () inline
Definition at line 3120 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDefaultInstance().
{
         return getCalibFieldBuilder().addBuilder(
             MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDefaultInstance());
       }
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.addCalibBuilder (int index) inline
Definition at line 3124 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDefaultInstance().
                      {
         return getCalibFieldBuilder().addBuilder(
             index, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDefaultInstance());
       }
MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.build () inline
Definition at line 2722 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.setField().
{
         MessagesRobocupSslGeometry.SSL_GeometryData result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 2730 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.parseDelimitedFrom().
{
         MessagesRobocupSslGeometry.SSL_GeometryData result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.buildPartial () inline
Definition at line 2740 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.field_.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeGeometry().
{
         MessagesRobocupSslGeometry.SSL_GeometryData result = new MessagesRobocupSslGeometry.SSL_GeometryData(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         if (fieldBuilder_ == null) {
           result.field_ = field_;
         } else {
           result.field_ = fieldBuilder_.build();
         }
         if (calibBuilder_ == null) {
           if (((bitField0_ & 0x00000002) == 0x00000002)) {
             calib_ = java.util.Collections.unmodifiableList(calib_);
             bitField0_ = (bitField0_ & ~0x00000002);
           }
           result.calib_ = calib_;
         } else {
           result.calib_ = calibBuilder_.build();
         }
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.clear () inline
Definition at line 2692 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.clear(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance().
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.clear().
{
         super.clear();
         if (fieldBuilder_ == null) {
           field_ = MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance();
         } else {
           fieldBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000001);
         if (calibBuilder_ == null) {
           calib_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000002);
         } else {
           calibBuilder_.clear();
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.clearCalib () inline
Definition at line 3081 of file MessagesRobocupSslGeometry.java.
{
         if (calibBuilder_ == null) {
           calib_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000002);
           onChanged();
         } else {
           calibBuilder_.clear();
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.clearField () inline
Definition at line 2926 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance().
{
         if (fieldBuilder_ == null) {
           field_ = MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance();
           onChanged();
         } else {
           fieldBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000001);
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.clone () inline
Definition at line 2709 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.create () inline static private
Definition at line 2688 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.newBuilder().
{
         return new Builder();
       }
void Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.ensureCalibIsMutable () inline private
Definition at line 2965 of file MessagesRobocupSslGeometry.java.
{
         if (!((bitField0_ & 0x00000002) == 0x00000002)) {
           calib_ = new java.util.ArrayList<MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration>(calib_);
           bitField0_ |= 0x00000002;
          }
       }
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getCalib (int index) inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2989 of file MessagesRobocupSslGeometry.java.
{
         if (calibBuilder_ == null) {
           return calib_.get(index);
         } else {
           return calibBuilder_.getMessage(index);
         }
       }
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getCalibBuilder (int index) inline
Definition at line 3101 of file MessagesRobocupSslGeometry.java.
                      {
         return getCalibFieldBuilder().getBuilder(index);
       }
java.util.List<MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder> Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getCalibBuilderList () inline
Definition at line 3130 of file MessagesRobocupSslGeometry.java.
{
         return getCalibFieldBuilder().getBuilderList();
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getCalibCount () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2982 of file MessagesRobocupSslGeometry.java.
{
         if (calibBuilder_ == null) {
           return calib_.size();
         } else {
           return calibBuilder_.getCount();
         }
       }
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder> Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getCalibFieldBuilder () inline private
Definition at line 3135 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.initFields().
{
         if (calibBuilder_ == null) {
           calibBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
               MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder>(
                   calib_,
                   ((bitField0_ & 0x00000002) == 0x00000002),
                   getParentForChildren(),
                   isClean());
           calib_ = null;
         }
         return calibBuilder_;
       }
java.util.List<MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration> Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getCalibList () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2975 of file MessagesRobocupSslGeometry.java.
{
         if (calibBuilder_ == null) {
           return java.util.Collections.unmodifiableList(calib_);
         } else {
           return calibBuilder_.getMessageList();
         }
       }
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getCalibOrBuilder (int index) inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 3105 of file MessagesRobocupSslGeometry.java.
                      {
         if (calibBuilder_ == null) {
           return calib_.get(index);  } else {
           return calibBuilder_.getMessageOrBuilder(index);
         }
       }
java.util.List<? extends MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder> Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getCalibOrBuilderList () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 3113 of file MessagesRobocupSslGeometry.java.
{
         if (calibBuilder_ != null) {
           return calibBuilder_.getMessageOrBuilderList();
         } else {
           return java.util.Collections.unmodifiableList(calib_);
         }
       }
MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getDefaultInstanceForType () inline
Definition at line 2718 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance().
{
         return MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance();
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getDescriptor () inline static
Definition at line 2664 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.internal_static_SSL_GeometryData_descriptor.
{
         return MessagesRobocupSslGeometry.internal_static_SSL_GeometryData_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getDescriptorForType () inline
Definition at line 2714 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getDescriptor().
{
         return MessagesRobocupSslGeometry.SSL_GeometryData.getDescriptor();
       }
MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getField () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2879 of file MessagesRobocupSslGeometry.java.
{
         if (fieldBuilder_ == null) {
           return field_;
         } else {
           return fieldBuilder_.getMessage();
         }
       }
MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getFieldBuilder () inline
Definition at line 2936 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000001;
         onChanged();
         return getFieldFieldBuilder().getBuilder();
       }
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslGeometry.SSL_GeometryFieldSize, MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder> Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getFieldFieldBuilder () inline private
Definition at line 2950 of file MessagesRobocupSslGeometry.java.
{
         if (fieldBuilder_ == null) {
           fieldBuilder_ = new com.google.protobuf.SingleFieldBuilder<
               MessagesRobocupSslGeometry.SSL_GeometryFieldSize, MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder>(
                   field_,
                   getParentForChildren(),
                   isClean());
           field_ = null;
         }
         return fieldBuilder_;
       }
MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getFieldOrBuilder () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2941 of file MessagesRobocupSslGeometry.java.
{
         if (fieldBuilder_ != null) {
           return fieldBuilder_.getMessageOrBuilder();
         } else {
           return field_;
         }
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.hasField () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2876 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 2669 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.internal_static_SSL_GeometryData_fieldAccessorTable.
{
         return MessagesRobocupSslGeometry.internal_static_SSL_GeometryData_fieldAccessorTable;
       }
final boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.isInitialized () inline
Definition at line 2810 of file MessagesRobocupSslGeometry.java.
References velocity.pid_.i.
{
         if (!hasField()) {
           return false;
         }
         if (!getField().isInitialized()) {
           return false;
         }
         for (int i = 0; i < getCalibCount(); i++) {
           if (!getCalib(i).isInitialized()) {
             return false;
           }
         }
         return true;
       }
void Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.maybeForceBuilderInitialization () inline private
Definition at line 2682 of file MessagesRobocupSslGeometry.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
           getFieldFieldBuilder();
           getCalibFieldBuilder();
         }
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeField (MessagesRobocupSslGeometry.SSL_GeometryFieldSize value) inline
Definition at line 2910 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.buildPartial(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.mergeFrom(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.newBuilder().
{
         if (fieldBuilder_ == null) {
           if (((bitField0_ & 0x00000001) == 0x00000001) &&
               field_ != MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance()) {
             field_ =
               MessagesRobocupSslGeometry.SSL_GeometryFieldSize.newBuilder(field_).mergeFrom(value).buildPartial();
           } else {
             field_ = value;
           }
           onChanged();
         } else {
           fieldBuilder_.mergeFrom(value);
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 2766 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.clone(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeGeometry(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.newBuilder().
{
         if (other instanceof MessagesRobocupSslGeometry.SSL_GeometryData) {
           return mergeFrom((MessagesRobocupSslGeometry.SSL_GeometryData)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeFrom (MessagesRobocupSslGeometry.SSL_GeometryData other) inline
Definition at line 2775 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.calib_, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance().
{
         if (other == MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance()) return this;
         if (other.hasField()) {
           mergeField(other.getField());
         }
         if (calibBuilder_ == null) {
           if (!other.calib_.isEmpty()) {
             if (calib_.isEmpty()) {
               calib_ = other.calib_;
               bitField0_ = (bitField0_ & ~0x00000002);
             } else {
               ensureCalibIsMutable();
               calib_.addAll(other.calib_);
             }
             onChanged();
           }
         } else {
           if (!other.calib_.isEmpty()) {
             if (calibBuilder_.isEmpty()) {
               calibBuilder_.dispose();
               calibBuilder_ = null;
               calib_ = other.calib_;
               bitField0_ = (bitField0_ & ~0x00000002);
               calibBuilder_ =
                 com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                    getCalibFieldBuilder() : null;
             } else {
               calibBuilder_.addAllMessages(other.calib_);
             }
           }
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 2828 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.Builder(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.mergeFrom(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.newBuilder(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.newBuilder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 10: {
               MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder subBuilder = MessagesRobocupSslGeometry.SSL_GeometryFieldSize.newBuilder();
               if (hasField()) {
                 subBuilder.mergeFrom(getField());
               }
               input.readMessage(subBuilder, extensionRegistry);
               setField(subBuilder.buildPartial());
               break;
             }
             case 18: {
               MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder subBuilder = MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.newBuilder();
               input.readMessage(subBuilder, extensionRegistry);
               addCalib(subBuilder.buildPartial());
               break;
             }
           }
         }
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.removeCalib (int index) inline
Definition at line 3091 of file MessagesRobocupSslGeometry.java.
{
         if (calibBuilder_ == null) {
           ensureCalibIsMutable();
           calib_.remove(index);
           onChanged();
         } else {
           calibBuilder_.remove(index);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.setCalib (int index, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration value) inline
Definition at line 2996 of file MessagesRobocupSslGeometry.java.
{
         if (calibBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureCalibIsMutable();
           calib_.set(index, value);
           onChanged();
         } else {
           calibBuilder_.setMessage(index, value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.setCalib (int index, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder builderForValue) inline
Definition at line 3010 of file MessagesRobocupSslGeometry.java.
{
         if (calibBuilder_ == null) {
           ensureCalibIsMutable();
           calib_.set(index, builderForValue.build());
           onChanged();
         } else {
           calibBuilder_.setMessage(index, builderForValue.build());
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.setField (MessagesRobocupSslGeometry.SSL_GeometryFieldSize value) inline
Definition at line 2886 of file MessagesRobocupSslGeometry.java.
{
         if (fieldBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           field_ = value;
           onChanged();
         } else {
           fieldBuilder_.setMessage(value);
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.setField (MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder builderForValue) inline
Definition at line 2899 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.build().
{
         if (fieldBuilder_ == null) {
           field_ = builderForValue.build();
           onChanged();
         } else {
           fieldBuilder_.setMessage(builderForValue.build());
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Field Documentation
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.bitField0_ private
Definition at line 2870 of file MessagesRobocupSslGeometry.java.
java.util.List<MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration> Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.calib_ private
Initial value:
=
        java.util.Collections.emptyList()
Definition at line 2963 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeFrom().
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder, MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder> Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.calibBuilder_ private
Definition at line 2973 of file MessagesRobocupSslGeometry.java.
MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.field_ = MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance() private
Definition at line 2873 of file MessagesRobocupSslGeometry.java.
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslGeometry.SSL_GeometryFieldSize, MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder> Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.fieldBuilder_ private
Definition at line 2875 of file MessagesRobocupSslGeometry.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslGeometry.java