Documentation: VisionPlugin Class Reference
VisionPlugin Class Reference
A base class for general vision processing plugin.
#include <visionplugin.h>
Public Slots
void slotKeyPressEvent (QKeyEvent *event)
Public Member Functions
VisionPlugin (FrameBuffer *_buffer)
virtual ~VisionPlugin ()
virtual string getName ()
you should overload this one to return the name of your plugin
FrameBuffer * getFrameBuffer () const
this functions provides convenient access to the ring-buffer
void lock ()
void unlock ()
virtual bool isEnabled () const
virtual void setEnabled (bool enable)
virtual bool isVisualize () const
virtual void setVisualize (bool enable)
virtual bool isSharedAmongStacks () const
virtual void setSharedAmongStacks (bool enable)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual ProcessResult process (FrameData *data, RenderOptions *options)
virtual VarList * getSettings ()
virtual void postProcess (FrameData *data, RenderOptions *options)
virtual QWidget * getVisualizationWidget ()
virtual QWidget * getControlWidget ()
virtual void closeWidgets ()
virtual QList< QAction * > actions ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
void setTimeProcessing (double val)
void setTimePostProcessing (double val)
double getTimeProcessing ()
double getTimePostProcessing ()
Protected Attributes
QMutex mutex
bool enabled
bool visualize
bool shared
FrameBuffer * buffer
double time_proc
double time_post
Detailed Description
A base class for general vision processing plugin.
Author
Stefan Zickler, (C) 2008
This is the class that should be extended when adding vision processing functions to the system. A VisionPlugin can be added to any part of a VisionStack
Definition at line 51 of file visionplugin.h.
Constructor & Destructor Documentation
VisionPlugin::VisionPlugin (FrameBuffer * _buffer)
Definition at line 24 of file visionplugin.cpp.
References buffer, enabled, setTimePostProcessing(), setTimeProcessing(), shared, and visualize.
 {
   buffer=_buffer;
   enabled=true;
   shared=false;
   visualize=true;
   setTimeProcessing(0.0);
   setTimePostProcessing(0.0);
 }
VisionPlugin::~VisionPlugin () virtual
Definition at line 34 of file visionplugin.cpp.
References closeWidgets().
 {
   closeWidgets();
 }
Member Function Documentation
QList< QAction * > VisionPlugin::actions () virtual
any QActions that should be displayed in a toolbar should be returned here
Definition at line 111 of file visionplugin.cpp.
{
   QList<QAction *> a;
   return a;
 }
void VisionPlugin::closeWidgets () virtual
this function will be called when the plugin's widgets are being closed it is up to the plugin whether to delete them from memory or not. If your plugin decides to delete them from memory (which is recommended if they are memory hogs, you just need to make sure to correctly reload them when one of the getControlWidget(...) or getVisualizationWidget(...) functions is called.
Definition at line 108 of file visionplugin.cpp.
Referenced by ~VisionPlugin().
{
 }
void VisionPlugin::displayLoopEvent (bool frame_changed, RenderOptions * opts) virtual
this function will be called about many times/s on your plugin in most cases you might want to only trigger a render if frame_changed==true which should occur with the same frequency as your camera input
Definition at line 79 of file visionplugin.cpp.
{
   (void)frame_changed;
   (void)opts;
 }
QWidget * VisionPlugin::getControlWidget () virtual
if this plugin has a control-widget (other than getSettings()) it should be returned here:
Reimplemented in PluginDVR, PluginCameraCalibration, PluginNeuralColorCalib, and PluginColorCalibration.
Definition at line 104 of file visionplugin.cpp.
Referenced by MainWindow::MainWindow().
{
   return 0;
 }
FrameBuffer * VisionPlugin::getFrameBuffer () const
this functions provides convenient access to the ring-buffer
Definition at line 43 of file visionplugin.cpp.
References buffer.
Referenced by PluginColorCalibration::keyPressEvent(), PluginColorCalibration::mouseEvent(), and PluginNeuralColorCalib::mouseEvent().
{
   return buffer;
 }
string VisionPlugin::getName () virtual
you should overload this one to return the name of your plugin
Reimplemented in PluginDVR, PluginDetectBalls, PluginVisualize, PluginDetectRobots, PluginCameraCalibration, PluginNeuralColorCalib, PluginLegacyPublishGeometry, PluginPublishGeometry, PluginFindBlobs, PluginLegacySSLNetworkOutput, PluginColorCalibration, PluginSSLNetworkOutput, PluginColorThreshold, and PluginRunlengthEncode.
Definition at line 39 of file visionplugin.cpp.
Referenced by MainWindow::MainWindow(), and VisionStack::process().
{
   return "Unnamed";
 }
VarList * VisionPlugin::getSettings () virtual
any settings of your plugin should be returned here this will ensure a nice integration with the systems data-tree and automatic XML settings saving
Reimplemented in PluginDVR, PluginDetectBalls, PluginVisualize, PluginDetectRobots, PluginCameraCalibration, PluginNeuralColorCalib, PluginLegacyPublishGeometry, PluginPublishGeometry, PluginFindBlobs, PluginColorCalibration, PluginColorThreshold, and PluginRunlengthEncode.
Definition at line 84 of file visionplugin.cpp.
Referenced by MainWindow::MainWindow().
{
   return 0;
 }
double VisionPlugin::getTimePostProcessing ()
Definition at line 152 of file visionplugin.cpp.
References time_post.
{
   return time_post;
 }
double VisionPlugin::getTimeProcessing ()
Definition at line 148 of file visionplugin.cpp.
References time_proc.
Referenced by VisionStack::process().
{
   return time_proc;
 }
QWidget * VisionPlugin::getVisualizationWidget () virtual
renderOverlay(...) on the other hand is used to visualize anything that goes beyond just modifying the existing output buffer. It should be used if we need to draw additional stuff using OpenGL or a QPainter: renderOverlay will be called after all postProcess(...) have been called if this plugin uses an extra widget to visualize data output it should be returned here: this is useful if visualization neeeds to go beyond the two above functions
Definition at line 100 of file visionplugin.cpp.
Referenced by MainWindow::MainWindow().
{
   return 0;
 }
bool VisionPlugin::isEnabled () const virtual
indicates whether this plugin will be used (e.g. whether process() will be called on it)
Definition at line 55 of file visionplugin.cpp.
References enabled.
{
   return enabled;
 }
bool VisionPlugin::isSharedAmongStacks () const virtual
indicates whether this plugin instance is used by multiple different stacks. if so, its control panels will be shown on the global pane, instead of the usual independent camera pane.
Definition at line 71 of file visionplugin.cpp.
References shared.
Referenced by MainWindow::MainWindow().
{
   return shared;
 }
bool VisionPlugin::isVisualize () const virtual
indicates whether this plugin's visualization functions will be called (postProcess(...) and renderOverlay(...))
Definition at line 63 of file visionplugin.cpp.
References visualize.
{
   return visualize;
 }
void VisionPlugin::keyPressEvent (QKeyEvent * event) virtual
These are event handlers that were called on the visualization window these events should provide a locked (meaning thread-safe) context. That is, they will never get triggered during a processing function. IMPORTANT, you should call event->accept() if you choose to handle it because non-accepted events will be forwarded to the next plugin and multiple plugins might be listening to the same events.
Reimplemented in PluginCameraCalibration, PluginNeuralColorCalib, and PluginColorCalibration.
Definition at line 116 of file visionplugin.cpp.
Referenced by VisionStack::keyPressEvent(), and slotKeyPressEvent().
{
   (void)event;
 }
void VisionPlugin::lock ()
these functions are called automatically by the parent-stack to ensure thread-safety you should NOT need to touch them
Definition at line 47 of file visionplugin.cpp.
References mutex.
Referenced by PluginPublishGeometry::addCameraParameters(), PluginLegacyPublishGeometry::addCameraParameters(), VisionStack::keyPressEvent(), VisionStack::mouseMoveEvent(), VisionStack::mousePressEvent(), VisionStack::mouseReleaseEvent(), VisionStack::postProcess(), VisionStack::process(), PluginPublishGeometry::slotPublishTriggered(), PluginLegacyPublishGeometry::slotPublishTriggered(), and VisionStack::wheelEvent().
{
   mutex.lock();
 }
void VisionPlugin::mouseMoveEvent (QMouseEvent * event, pixelloc loc) virtual
Reimplemented in PluginCameraCalibration, PluginNeuralColorCalib, and PluginColorCalibration.
Definition at line 130 of file visionplugin.cpp.
Referenced by VisionStack::mouseMoveEvent().
{
   (void)event;
   (void)loc;
 }
void VisionPlugin::mousePressEvent (QMouseEvent * event, pixelloc loc) virtual
Reimplemented in PluginCameraCalibration, PluginNeuralColorCalib, and PluginColorCalibration.
Definition at line 120 of file visionplugin.cpp.
Referenced by VisionStack::mousePressEvent().
{
   (void)event;
   (void)loc;
 }
void VisionPlugin::mouseReleaseEvent (QMouseEvent * event, pixelloc loc) virtual
Reimplemented in PluginCameraCalibration, PluginNeuralColorCalib, and PluginColorCalibration.
Definition at line 125 of file visionplugin.cpp.
Referenced by VisionStack::mouseReleaseEvent().
{
   (void)event;
   (void)loc;
 }
void VisionPlugin::postProcess (FrameData * data, RenderOptions * options) virtual
the following two functions should be used to visualize data postProcess(...) is used to modify the data in the FrameData buffer before it will hit the end of the rendering pipe this is useful if the only rendering we need to do can be done by directly modifying the output image (e.g. color some image-regions)
Note that this will be called after all the processing of all modules has happened, so it should not affect processing, only visualization
Definition at line 95 of file visionplugin.cpp.
Referenced by VisionStack::postProcess().
{
   (void)data;
   (void)options;
 }
ProcessResult VisionPlugin::process (FrameData * data, RenderOptions * options) virtual
this is the main-processing function. It allows your plugin to operate on the current frame-data
Reimplemented in PluginDVR, PluginDetectBalls, PluginVisualize, PluginDetectRobots, PluginCameraCalibration, PluginLegacyPublishGeometry, PluginNeuralColorCalib, PluginPublishGeometry, PluginLegacySSLNetworkOutput, PluginFindBlobs, PluginSSLNetworkOutput, PluginColorThreshold, and PluginRunlengthEncode.
Definition at line 88 of file visionplugin.cpp.
References ProcessingOk.
Referenced by VisionStack::process().
{
   (void)data;
   (void)options;
   return ProcessingOk;
 }
void VisionPlugin::setEnabled (bool enable) virtual
Definition at line 59 of file visionplugin.cpp.
References enabled.
{
   enabled=enable;
 }
void VisionPlugin::setSharedAmongStacks (bool enable) virtual
Definition at line 75 of file visionplugin.cpp.
References shared.
Referenced by PluginLegacyPublishGeometry::PluginLegacyPublishGeometry(), and PluginPublishGeometry::PluginPublishGeometry().
{
   shared=enable;
 }
void VisionPlugin::setTimePostProcessing (double val)
Definition at line 144 of file visionplugin.cpp.
References time_post.
Referenced by VisionStack::postProcess(), and VisionPlugin().
{
   time_post=val;
 }
void VisionPlugin::setTimeProcessing (double val)
Definition at line 140 of file visionplugin.cpp.
References time_proc.
Referenced by VisionStack::process(), and VisionPlugin().
{
   time_proc=val;
 }
void VisionPlugin::setVisualize (bool enable) virtual
Definition at line 67 of file visionplugin.cpp.
References visualize.
{
   visualize=enable;
 }
void VisionPlugin::slotKeyPressEvent (QKeyEvent * event) slot
Definition at line 156 of file visionplugin.cpp.
References keyPressEvent().
Referenced by PluginColorCalibration::getControlWidget().
{
   keyPressEvent(event);
 }
void VisionPlugin::unlock ()
Definition at line 51 of file visionplugin.cpp.
References mutex.
Referenced by PluginPublishGeometry::addCameraParameters(), PluginLegacyPublishGeometry::addCameraParameters(), VisionStack::keyPressEvent(), VisionStack::mouseMoveEvent(), VisionStack::mousePressEvent(), VisionStack::mouseReleaseEvent(), VisionStack::postProcess(), VisionStack::process(), PluginPublishGeometry::slotPublishTriggered(), PluginLegacyPublishGeometry::slotPublishTriggered(), and VisionStack::wheelEvent().
{
   mutex.unlock();
 }
void VisionPlugin::wheelEvent (QWheelEvent * event, pixelloc loc) virtual
Definition at line 135 of file visionplugin.cpp.
Referenced by VisionStack::wheelEvent().
{
   (void)event;
   (void)loc;
 }
Field Documentation
FrameBuffer* VisionPlugin::buffer protected
Definition at line 58 of file visionplugin.h.
Referenced by getFrameBuffer(), and VisionPlugin().
bool VisionPlugin::enabled protected
Definition at line 55 of file visionplugin.h.
Referenced by isEnabled(), setEnabled(), and VisionPlugin().
QMutex VisionPlugin::mutex protected
Definition at line 54 of file visionplugin.h.
Referenced by lock(), and unlock().
bool VisionPlugin::shared protected
Definition at line 57 of file visionplugin.h.
Referenced by isSharedAmongStacks(), setSharedAmongStacks(), and VisionPlugin().
double VisionPlugin::time_post protected
Definition at line 60 of file visionplugin.h.
Referenced by getTimePostProcessing(), and setTimePostProcessing().
double VisionPlugin::time_proc protected
Definition at line 59 of file visionplugin.h.
Referenced by getTimeProcessing(), and setTimeProcessing().
bool VisionPlugin::visualize protected
Definition at line 56 of file visionplugin.h.
Referenced by isVisualize(), setVisualize(), and VisionPlugin().
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/visionplugin.h
ssl-vision/src/app/plugins/visionplugin.cpp