Documentation: Vector2f Class Reference
Vector2f Class Reference
#include <messages_robocup_ssl_geometry.pb.h>
Public Member Functions
Vector2f ()
virtual ~Vector2f ()
Vector2f (const Vector2f &from)
Vector2f & operator= (const Vector2f &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Vector2f *other)
Vector2f * New () const PROTOBUF_FINAL
Vector2f * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const Vector2f &from)
void MergeFrom (const Vector2f &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_x () const
void clear_x ()
float x () const
void set_x (float value)
bool has_y () const
void clear_y ()
float y () const
void set_y (float value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Vector2f & default_instance ()
static void InitAsDefaultInstance ()
static const Vector2f * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kXFieldNumber = 1
static const int kYFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (Vector2f *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_x ()
void clear_has_x ()
void set_has_y ()
void clear_has_y ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsVector2fImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
float x_
float y_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::TableStruct
void swap (Vector2f &a, Vector2f &b)
Detailed Description
Definition at line 87 of file messages_robocup_ssl_geometry.pb.h.
Constructor & Destructor Documentation
Vector2f::Vector2f ()
virtual Vector2f::~Vector2f () virtual
Vector2f::Vector2f (const Vector2f & from)
Member Function Documentation
size_t Vector2f::ByteSizeLong () const
void Vector2f::Clear ()
void Vector2f::clear_has_x () inline private
Definition at line 1111 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void Vector2f::clear_has_y () inline private
Definition at line 1135 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] &= ~0x00000002u;
 }
void Vector2f::clear_x () inline
Definition at line 1114 of file messages_robocup_ssl_geometry.pb.h.
{
   x_ = 0;
   clear_has_x();
 }
void Vector2f::clear_y () inline
Definition at line 1138 of file messages_robocup_ssl_geometry.pb.h.
{
   y_ = 0;
   clear_has_y();
 }
void Vector2f::CopyFrom (const ::google::protobuf::Message & from)
void Vector2f::CopyFrom (const Vector2f & from)
static const Vector2f& Vector2f::default_instance () static
static const ::google::protobuf::Descriptor* Vector2f::descriptor () static
inline ::google::protobuf::Arena* Vector2f::GetArenaNoVirtual () const inline private
Definition at line 162 of file messages_robocup_ssl_geometry.pb.h.
Referenced by operator=().
{
     return NULL;
   }
int Vector2f::GetCachedSize () const inline
Definition at line 155 of file messages_robocup_ssl_geometry.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata Vector2f::GetMetadata () const
bool Vector2f::has_x () const inline
Definition at line 1105 of file messages_robocup_ssl_geometry.pb.h.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool Vector2f::has_y () const inline
Definition at line 1129 of file messages_robocup_ssl_geometry.pb.h.
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
static void Vector2f::InitAsDefaultInstance () static
static const Vector2f* Vector2f::internal_default_instance () inline static
Definition at line 124 of file messages_robocup_ssl_geometry.pb.h.
References _Vector2f_default_instance_.
{
     return reinterpret_cast<const Vector2f*>(
                &_Vector2f_default_instance_);
   }
::google::protobuf::uint8* Vector2f::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void Vector2f::InternalSwap (Vector2f * other) private
bool Vector2f::IsInitialized () const
void* Vector2f::MaybeArenaPtr () const inline private
Definition at line 165 of file messages_robocup_ssl_geometry.pb.h.
{
     return NULL;
   }
void Vector2f::MergeFrom (const ::google::protobuf::Message & from)
void Vector2f::MergeFrom (const Vector2f & from)
bool Vector2f::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
inline ::google::protobuf::UnknownFieldSet* Vector2f::mutable_unknown_fields () inline
Definition at line 116 of file messages_robocup_ssl_geometry.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
Vector2f* Vector2f::New () const inline
Definition at line 138 of file messages_robocup_ssl_geometry.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
Vector2f* Vector2f::New (::google::protobuf::Arena * arena) const
Vector2f& Vector2f::operator= (const Vector2f & from) inline
Definition at line 94 of file messages_robocup_ssl_geometry.pb.h.
References GetArenaNoVirtual().
{
     CopyFrom(from);
     return *this;
   }
size_t Vector2f::RequiredFieldsByteSizeFallback () const private
void Vector2f::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void Vector2f::set_has_x () inline private
Definition at line 1108 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] |= 0x00000001u;
 }
void Vector2f::set_has_y () inline private
Definition at line 1132 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] |= 0x00000002u;
 }
void Vector2f::set_x (float value) inline
Definition at line 1122 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSLWorld::addFieldArc(), SSLWorld::addFieldLine(), SSLWorld::allocVector(), and RoboCupField::toProtoBuffer().
{
   set_has_x();
   x_ = value;
   // @@protoc_insertion_point(field_set:Vector2f.x)
 }
void Vector2f::set_y (float value) inline
Definition at line 1146 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSLWorld::addFieldArc(), SSLWorld::addFieldLine(), SSLWorld::allocVector(), and RoboCupField::toProtoBuffer().
{
   set_has_y();
   y_ = value;
   // @@protoc_insertion_point(field_set:Vector2f.y)
 }
void Vector2f::SetCachedSize (int size) const private
void Vector2f::SharedCtor () private
void Vector2f::SharedDtor () private
void Vector2f::Swap (Vector2f * other)
const ::google::protobuf::UnknownFieldSet& Vector2f::unknown_fields () const inline
Definition at line 113 of file messages_robocup_ssl_geometry.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
Vector2f::void::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsVector2fImpl () private
float Vector2f::x () const inline
Definition at line 1118 of file messages_robocup_ssl_geometry.pb.h.
Referenced by GLSoccerView::updateFieldGeometry().
{
   // @@protoc_insertion_point(field_get:Vector2f.x)
   return x_;
 }
float Vector2f::y () const inline
Definition at line 1142 of file messages_robocup_ssl_geometry.pb.h.
Referenced by GLSoccerView::updateFieldGeometry().
{
   // @@protoc_insertion_point(field_get:Vector2f.y)
   return y_;
 }
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::TableStruct friend
Definition at line 205 of file messages_robocup_ssl_geometry.pb.h.
void swap (Vector2f & a, Vector2f & b) friend
Definition at line 132 of file messages_robocup_ssl_geometry.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int Vector2f::_cached_size_ mutable private
Definition at line 202 of file messages_robocup_ssl_geometry.pb.h.
::google::protobuf::internal::HasBits<1> Vector2f::_has_bits_ private
Definition at line 201 of file messages_robocup_ssl_geometry.pb.h.
::google::protobuf::internal::InternalMetadataWithArena Vector2f::_internal_metadata_ private
Definition at line 200 of file messages_robocup_ssl_geometry.pb.h.
PROTOBUF_CONSTEXPR int const Vector2f::kIndexInFileMessages static
Initial value:
=
    0
Definition at line 128 of file messages_robocup_ssl_geometry.pb.h.
const int Vector2f::kXFieldNumber = 1 static
Definition at line 179 of file messages_robocup_ssl_geometry.pb.h.
const int Vector2f::kYFieldNumber = 2 static
Definition at line 186 of file messages_robocup_ssl_geometry.pb.h.
float Vector2f::x_ private
Definition at line 203 of file messages_robocup_ssl_geometry.pb.h.
float Vector2f::y_ private
Definition at line 204 of file messages_robocup_ssl_geometry.pb.h.
The documentation for this class was generated from the following file:
ssl-vision/build/messages_robocup_ssl_geometry.pb.h