Documentation: grsim_comm/include/proto/messages_robocup_ssl_detection.pb.cc File Reference
messages_robocup_ssl_detection.pb.cc File Reference
#include "messages_robocup_ssl_detection.pb.h"
#include <algorithm>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
Data Structures
class SSL_DetectionBallDefaultTypeInternal
class SSL_DetectionRobotDefaultTypeInternal
class SSL_DetectionFrameDefaultTypeInternal
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5fdetection_2eproto
Namespaces
anonymous_namespace{messages_robocup_ssl_detection.pb.cc}
Macros
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Functions
const ::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5fdetection_2eproto () GOOGLE_ATTRIBUTE_COLD
void anonymous_namespace{messages_robocup_ssl_detection.pb.cc}::protobuf_AssignDescriptors ()
void anonymous_namespace{messages_robocup_ssl_detection.pb.cc}::protobuf_AssignDescriptorsOnce ()
void anonymous_namespace{messages_robocup_ssl_detection.pb.cc}::protobuf_RegisterTypes (const ::std::string &) GOOGLE_ATTRIBUTE_COLD
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fdetection_2eproto ()
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto_impl ()
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto ()
void protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_impl ()
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_once_)
void protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto ()
Variables
SSL_DetectionBallDefaultTypeInternal _SSL_DetectionBall_default_instance_
SSL_DetectionRobotDefaultTypeInternal _SSL_DetectionRobot_default_instance_
SSL_DetectionFrameDefaultTypeInternal _SSL_DetectionFrame_default_instance_
::google::protobuf::Metadata anonymous_namespace{messages_robocup_ssl_detection.pb.cc}::file_level_metadata [3]
static const ::google::protobuf::internal::MigrationSchema schemas []
static const ::google::protobuf::internal::DefaultInstanceData file_default_instances []
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5fdetection_2eproto static_descriptor_initializer_messages_5frobocup_5fssl_5fdetection_2eproto_
Macro Definition Documentation
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Referenced by SSL_DetectionBall::MergePartialFromCodedStream(), SSL_DetectionRobot::MergePartialFromCodedStream(), and SSL_DetectionFrame::MergePartialFromCodedStream().
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
Definition at line 4 of file messages_robocup_ssl_detection.pb.cc.
Function Documentation
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_once_)
Referenced by protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::AddDescriptors(), protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::InitDefaultsSSL_DetectionBall(), protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::InitDefaultsSSL_DetectionFrame(), protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::InitDefaultsSSL_DetectionRobot(), protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_impl(), anonymous_namespace{messages_robocup_ssl_detection.pb.cc}::protobuf_AssignDescriptorsOnce(), protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::protobuf_AssignDescriptorsOnce(), and protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto().
void protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto ()
Definition at line 179 of file messages_robocup_ssl_detection.pb.cc.
References protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_impl().
Referenced by protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl(), protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_impl(), anonymous_namespace{messages_robocup_ssl_detection.pb.cc}::protobuf_AssignDescriptors(), and StaticDescriptorInitializer_messages_5frobocup_5fssl_5fdetection_2eproto::StaticDescriptorInitializer_messages_5frobocup_5fssl_5fdetection_2eproto().
{
   ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_once_,
                  &protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_impl);
 }
void protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_impl ()
Definition at line 153 of file messages_robocup_ssl_detection.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto(), protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::protobuf_RegisterTypes(), and protobuf_ShutdownFile_messages_5frobocup_5fssl_5fdetection_2eproto().
Referenced by protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto().
{
   protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto();
   static const char descriptor[] = {
       "\n$messages_robocup_ssl_detection.proto\"x"
       "\n\021SSL_DetectionBall\022\022\n\nconfidence\030\001 \002(\002\022"
       "\014\n\004area\030\002 \001(\r\022\t\n\001x\030\003 \002(\002\022\t\n\001y\030\004 \002(\002\022\t\n\001z"
       "\030\005 \001(\002\022\017\n\007pixel_x\030\006 \002(\002\022\017\n\007pixel_y\030\007 \002(\002"
       "\"\227\001\n\022SSL_DetectionRobot\022\022\n\nconfidence\030\001 "
       "\002(\002\022\020\n\010robot_id\030\002 \001(\r\022\t\n\001x\030\003 \002(\002\022\t\n\001y\030\004 "
       "\002(\002\022\023\n\013orientation\030\005 \001(\002\022\017\n\007pixel_x\030\006 \002("
       "\002\022\017\n\007pixel_y\030\007 \002(\002\022\016\n\006height\030\010 \001(\002\"\331\001\n\022S"
       "SL_DetectionFrame\022\024\n\014frame_number\030\001 \002(\r\022"
       "\021\n\tt_capture\030\002 \002(\001\022\016\n\006t_sent\030\003 \002(\001\022\021\n\tca"
       "mera_id\030\004 \002(\r\022!\n\005balls\030\005 \003(\0132\022.SSL_Detec"
       "tionBall\022*\n\rrobots_yellow\030\006 \003(\0132\023.SSL_De"
       "tectionRobot\022(\n\013robots_blue\030\007 \003(\0132\023.SSL_"
       "DetectionRobot"
   };
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
       descriptor, 534);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "messages_robocup_ssl_detection.proto", &protobuf_RegisterTypes);
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_messages_5frobocup_5fssl_5fdetection_2eproto);
 }
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto ()
Definition at line 149 of file messages_robocup_ssl_detection.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), and protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto_impl().
Referenced by SSL_DetectionBall::default_instance(), SSL_DetectionRobot::default_instance(), SSL_DetectionFrame::default_instance(), protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_impl(), protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl(), protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto_impl(), SSL_DetectionBall::SSL_DetectionBall(), SSL_DetectionFrame::SSL_DetectionFrame(), and SSL_DetectionRobot::SSL_DetectionRobot().
{
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
   ::google::protobuf::GoogleOnceInit(&once, &protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto_impl);
 }
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto_impl ()
Definition at line 140 of file messages_robocup_ssl_detection.pb.cc.
Referenced by protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto().
{
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::internal::InitProtobufDefaults();
   _SSL_DetectionBall_default_instance_.DefaultConstruct();
   _SSL_DetectionRobot_default_instance_.DefaultConstruct();
   _SSL_DetectionFrame_default_instance_.DefaultConstruct();
 }
const ::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5fdetection_2eproto ()
Definition at line 34 of file messages_robocup_ssl_detection.pb.cc.
Referenced by anonymous_namespace{messages_robocup_ssl_detection.pb.cc}::protobuf_AssignDescriptors().
{
   static const ::google::protobuf::uint32 offsets[] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, confidence_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, area_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, x_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, y_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, z_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, pixel_x_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, pixel_y_),
     0,
     1,
     2,
     3,
     4,
     5,
     6,
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, confidence_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, robot_id_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, x_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, y_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, orientation_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, pixel_x_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, pixel_y_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, height_),
     0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, frame_number_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, t_capture_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, t_sent_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, camera_id_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, balls_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, robots_yellow_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, robots_blue_),
     1,
     0,
     3,
     2,
     4,
     5,
     6,
   };
   return offsets;
 }
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fdetection_2eproto ()
Definition at line 131 of file messages_robocup_ssl_detection.pb.cc.
References protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::file_level_metadata.
Referenced by protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_impl().
{
   _SSL_DetectionBall_default_instance_.Shutdown();
   delete file_level_metadata[0].reflection;
   _SSL_DetectionRobot_default_instance_.Shutdown();
   delete file_level_metadata[1].reflection;
   _SSL_DetectionFrame_default_instance_.Shutdown();
   delete file_level_metadata[2].reflection;
 }
Variable Documentation
SSL_DetectionBallDefaultTypeInternal _SSL_DetectionBall_default_instance_
Definition at line 20 of file messages_robocup_ssl_detection.pb.cc.
Referenced by protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::InitDefaultsSSL_DetectionBallImpl().
SSL_DetectionFrameDefaultTypeInternal _SSL_DetectionFrame_default_instance_
Definition at line 24 of file messages_robocup_ssl_detection.pb.cc.
Referenced by RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::detection(), and protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::InitDefaultsSSL_DetectionFrameImpl().
SSL_DetectionRobotDefaultTypeInternal _SSL_DetectionRobot_default_instance_
Definition at line 22 of file messages_robocup_ssl_detection.pb.cc.
Referenced by protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::InitDefaultsSSL_DetectionRobotImpl().
const ::google::protobuf::internal::DefaultInstanceData file_default_instances[] static
Initial value:
= {
  {reinterpret_cast<const ::google::protobuf::Message*>(&_SSL_DetectionBall_default_instance_), NULL},
  {reinterpret_cast<const ::google::protobuf::Message*>(&_SSL_DetectionRobot_default_instance_), NULL},
  {reinterpret_cast<const ::google::protobuf::Message*>(&_SSL_DetectionFrame_default_instance_), NULL},
}
Definition at line 102 of file messages_robocup_ssl_detection.pb.cc.
Referenced by anonymous_namespace{messages_robocup_ssl_detection.pb.cc}::protobuf_AssignDescriptors().
const ::google::protobuf::internal::MigrationSchema schemas[] static
Initial value:
= {
  { 0, 11, sizeof(SSL_DetectionBall)},
  { 18, 30, sizeof(SSL_DetectionRobot)},
  { 38, 49, sizeof(SSL_DetectionFrame)},
}
Definition at line 96 of file messages_robocup_ssl_detection.pb.cc.
Referenced by anonymous_namespace{messages_robocup_ssl_detection.pb.cc}::protobuf_AssignDescriptors(), and protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::protobuf_AssignDescriptors().
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5fdetection_2eproto static_descriptor_initializer_messages_5frobocup_5fssl_5fdetection_2eproto_
Referenced by StaticDescriptorInitializer_messages_5frobocup_5fssl_5fdetection_2eproto::StaticDescriptorInitializer_messages_5frobocup_5fssl_5fdetection_2eproto().