Documentation: MyThread Class Reference
MyThread Class Reference
Public Member Functions
MyThread (QObject *parent=0)
~MyThread ()
Protected Member Functions
void run ()
Detailed Description
Definition at line 32 of file main.cpp.
Constructor & Destructor Documentation
MyThread::MyThread (QObject * parent = 0) inline
Definition at line 56 of file main.cpp.
 {}
MyThread::~MyThread () inline
Definition at line 57 of file main.cpp.
 {}
Member Function Documentation
void MyThread::run () inline protected
Definition at line 35 of file main.cpp.
References RoboCupSSLClient::open(), RoboCupSSLClient::receive(), runApp, Sleep(), GLSoccerView::updateDetection(), and GLSoccerView::updateFieldGeometry().
   {
     static const double minDuration = 0.01; //100FPS
     RoboCupSSLClient client;
     client.open(false);
     SSL_WrapperPacket packet;
     while(runApp) {
       while (client.receive(packet)) {
         if (packet.has_detection()) {
           SSL_DetectionFrame detection = packet.detection();
           view->updateDetection(detection);
         }
         if (packet.has_geometry()) {
           view->updateFieldGeometry(packet.geometry().field());
         }
       }
       Sleep(minDuration);
     }
   }
The documentation for this class was generated from the following file:
ssl-vision/src/graphicalClient/main.cpp