Documentation: grSim/clients/qt/CMakeLists.txt File Reference
grSim/clients/qt/CMakeLists.txt File Reference
Functions
cmake_minimum_required (VERSION 2.8) set(CMAKE_AUTOMOC ON) set(CMAKE_INCLUDE_CURRENT_DIR ON) set(libs) set(QT_USE_QTNETWORK TRUE) find_package(Qt REQUIRED) include($
list (APPEND libs ${QT_LIBRARIES}) find_package(Protobuf REQUIRED) include_directories($
list (APPEND libs ${PROTOBUF_LIBRARIES}) protobuf_generate_cpp(PROTO_CPP PROTO_H../../src/proto/grSim_Replacement.proto../../src/proto/grSim_Commands.proto../../src/proto/grSim_Packet.proto) set(app client) add_executable($
Function Documentation
cmake_minimum_required (VERSION 2. 8)
Definition at line 1 of file CMakeLists.txt.
          {QT_USE_FILE})
list (APPEND libs ${QT_LIBRARIES})
Definition at line 12 of file CMakeLists.txt.
Referenced by behavior.Behavior::behavior_state(), ConfigWidget::ConfigWidget(), VarTypes::VarList::getChildren(), VarTypes::VarStringEnum::getChildren(), if(), RobotsFomation::loadFromFile(), CMVision::RegionProcessing::rangeSumSq(), composite_behavior.CompositeBehavior::remove_all_subbehaviors(), PluginDVR::slotMovieLoad(), CMVision::RegionProcessing::sortRegionListByArea(), and composite_behavior.CompositeBehavior::spin_cb().
                   {QT_LIBRARIES})
 find_package(Protobuf REQUIRED)
 include_directories(${PROTOBUF_INCLUDE_DIRS})
list (APPEND libs ${PROTOBUF_LIBRARIES})
Definition at line 16 of file CMakeLists.txt.
References app, and main().
                   {PROTOBUF_LIBRARIES})
 protobuf_generate_cpp(PROTO_CPP PROTO_H
     ../../src/proto/grSim_Replacement.proto
     ../../src/proto/grSim_Commands.proto
     ../../src/proto/grSim_Packet.proto
 )
 set(app client)
 add_executable(${app} MACOSX_BUNDLE