Documentation: CycleTimer Class Reference
CycleTimer Class Reference
#include <timer.h>
Public Member Functions
CycleTimer ()
void start ()
void stop ()
void end ()
unsigned cycles ()
double time ()
double timeMSec ()
double timeUSec ()
CycleTimer ()
void start ()
void stop ()
void end ()
unsigned cycles ()
double time ()
double timeMSec ()
double timeUSec ()
Private Attributes
cycle_t c1
cycle_t c2
Static Private Attributes
static double cpu_period
Detailed Description
Definition at line 183 of file timer.h.
Constructor & Destructor Documentation
CycleTimer::CycleTimer () inline
Definition at line 187 of file timer.h.
References GetCPUClockPeriod().
 {cpu_period=GetCPUClockPeriod();}
CycleTimer::CycleTimer () inline
Definition at line 187 of file timer.h.
References GetCPUClockPeriod().
 {cpu_period=GetCPUClockPeriod();}
Member Function Documentation
unsigned CycleTimer::cycles () inline
Definition at line 193 of file timer.h.
 {return(c2 - c1);}
unsigned CycleTimer::cycles () inline
Definition at line 193 of file timer.h.
 {return(c2 - c1);}
void CycleTimer::end () inline
Definition at line 191 of file timer.h.
References Timer::stop().
 {stop();}
void CycleTimer::end () inline
Definition at line 191 of file timer.h.
References Timer::stop().
 {stop();}
void CycleTimer::start () inline
Definition at line 189 of file timer.h.
 {get_cycle(c1);}
void CycleTimer::start () inline
Definition at line 189 of file timer.h.
Referenced by FunctionCycleTimer::FunctionCycleTimer().
 {get_cycle(c1);}
void CycleTimer::stop () inline
Definition at line 190 of file timer.h.
Referenced by FunctionCycleTimer::~FunctionCycleTimer().
 {get_cycle(c2);}
void CycleTimer::stop () inline
Definition at line 190 of file timer.h.
 {get_cycle(c2);}
double CycleTimer::time () inline
Definition at line 194 of file timer.h.
 {return((double)(c2-c1) * cpu_period * 1.0E0);}
double CycleTimer::time () inline
Definition at line 194 of file timer.h.
 {return((double)(c2-c1) * cpu_period * 1.0E0);}
double CycleTimer::timeMSec () inline
Definition at line 195 of file timer.h.
Referenced by FunctionCycleTimer::~FunctionCycleTimer().
 {return((double)(c2-c1) * cpu_period * 1.0E3);}
double CycleTimer::timeMSec () inline
Definition at line 195 of file timer.h.
 {return((double)(c2-c1) * cpu_period * 1.0E3);}
double CycleTimer::timeUSec () inline
Definition at line 196 of file timer.h.
 {return((double)(c2-c1) * cpu_period * 1.0E6);}
double CycleTimer::timeUSec () inline
Definition at line 196 of file timer.h.
 {return((double)(c2-c1) * cpu_period * 1.0E6);}
Field Documentation
cycle_t CycleTimer::c1 private
Definition at line 184 of file timer.h.
cycle_t CycleTimer::c2 private
Definition at line 184 of file timer.h.
static double CycleTimer::cpu_period static private
Definition at line 185 of file timer.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/timer.h