Documentation: Protobuf.GrSimCommands.grSim_Commands.Builder Class Reference
Protobuf.GrSimCommands.grSim_Commands.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
GrSimCommands.grSim_Commands getDefaultInstanceForType ()
GrSimCommands.grSim_Commands build ()
GrSimCommands.grSim_Commands buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (GrSimCommands.grSim_Commands other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasTimestamp ()
double getTimestamp ()
Builder setTimestamp (double value)
Builder clearTimestamp ()
boolean hasIsteamyellow ()
boolean getIsteamyellow ()
Builder setIsteamyellow (boolean value)
Builder clearIsteamyellow ()
java.util.List< GrSimCommands.grSim_Robot_Command > getRobotCommandsList ()
int getRobotCommandsCount ()
GrSimCommands.grSim_Robot_Command getRobotCommands (int index)
Builder setRobotCommands (int index, GrSimCommands.grSim_Robot_Command value)
Builder setRobotCommands (int index, GrSimCommands.grSim_Robot_Command.Builder builderForValue)
Builder addRobotCommands (GrSimCommands.grSim_Robot_Command value)
Builder addRobotCommands (int index, GrSimCommands.grSim_Robot_Command value)
Builder addRobotCommands (GrSimCommands.grSim_Robot_Command.Builder builderForValue)
Builder addRobotCommands (int index, GrSimCommands.grSim_Robot_Command.Builder builderForValue)
Builder addAllRobotCommands (java.lang.Iterable<?extends GrSimCommands.grSim_Robot_Command > values)
Builder clearRobotCommands ()
Builder removeRobotCommands (int index)
GrSimCommands.grSim_Robot_Command.Builder getRobotCommandsBuilder (int index)
GrSimCommands.grSim_Robot_CommandOrBuilder getRobotCommandsOrBuilder (int index)
java.util.List<?extends GrSimCommands.grSim_Robot_CommandOrBuilder > getRobotCommandsOrBuilderList ()
GrSimCommands.grSim_Robot_Command.Builder addRobotCommandsBuilder ()
GrSimCommands.grSim_Robot_Command.Builder addRobotCommandsBuilder (int index)
java.util.List< GrSimCommands.grSim_Robot_Command.Builder > getRobotCommandsBuilderList ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
GrSimCommands.grSim_Commands buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
void ensureRobotCommandsIsMutable ()
com.google.protobuf.RepeatedFieldBuilder< GrSimCommands.grSim_Robot_Command, GrSimCommands.grSim_Robot_Command.Builder, GrSimCommands.grSim_Robot_CommandOrBuilder > getRobotCommandsFieldBuilder ()
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
double timestamp_
boolean isteamyellow_
java.util.List< GrSimCommands.grSim_Robot_Command > robotCommands_
com.google.protobuf.RepeatedFieldBuilder< GrSimCommands.grSim_Robot_Command, GrSimCommands.grSim_Robot_Command.Builder, GrSimCommands.grSim_Robot_CommandOrBuilder > robotCommandsBuilder_
Detailed Description
Definition at line 1283 of file GrSimCommands.java.
Constructor & Destructor Documentation
Protobuf.GrSimCommands.grSim_Commands.Builder.Builder () inline private
Definition at line 1297 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Commands.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.GrSimCommands.grSim_Commands.Builder.Builder (BuilderParent parent) inline private
Definition at line 1301 of file GrSimCommands.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.addAllRobotCommands (java.lang.Iterable<?extends GrSimCommands.grSim_Robot_Command > values) inline
Definition at line 1646 of file GrSimCommands.java.
{
         if (robotCommandsBuilder_ == null) {
           ensureRobotCommandsIsMutable();
           super.addAll(values, robotCommands_);
           onChanged();
         } else {
           robotCommandsBuilder_.addAllMessages(values);
         }
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.addRobotCommands (GrSimCommands.grSim_Robot_Command value) inline
Definition at line 1597 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         if (robotCommandsBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureRobotCommandsIsMutable();
           robotCommands_.add(value);
           onChanged();
         } else {
           robotCommandsBuilder_.addMessage(value);
         }
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.addRobotCommands (int index, GrSimCommands.grSim_Robot_Command value) inline
Definition at line 1610 of file GrSimCommands.java.
{
         if (robotCommandsBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureRobotCommandsIsMutable();
           robotCommands_.add(index, value);
           onChanged();
         } else {
           robotCommandsBuilder_.addMessage(index, value);
         }
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.addRobotCommands (GrSimCommands.grSim_Robot_Command.Builder builderForValue) inline
Definition at line 1624 of file GrSimCommands.java.
{
         if (robotCommandsBuilder_ == null) {
           ensureRobotCommandsIsMutable();
           robotCommands_.add(builderForValue.build());
           onChanged();
         } else {
           robotCommandsBuilder_.addMessage(builderForValue.build());
         }
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.addRobotCommands (int index, GrSimCommands.grSim_Robot_Command.Builder builderForValue) inline
Definition at line 1635 of file GrSimCommands.java.
{
         if (robotCommandsBuilder_ == null) {
           ensureRobotCommandsIsMutable();
           robotCommands_.add(index, builderForValue.build());
           onChanged();
         } else {
           robotCommandsBuilder_.addMessage(index, builderForValue.build());
         }
         return this;
       }
GrSimCommands.grSim_Robot_Command.Builder Protobuf.GrSimCommands.grSim_Commands.Builder.addRobotCommandsBuilder () inline
Definition at line 1696 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.getDefaultInstance().
{
         return getRobotCommandsFieldBuilder().addBuilder(
             GrSimCommands.grSim_Robot_Command.getDefaultInstance());
       }
GrSimCommands.grSim_Robot_Command.Builder Protobuf.GrSimCommands.grSim_Commands.Builder.addRobotCommandsBuilder (int index) inline
Definition at line 1700 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.getDefaultInstance().
                      {
         return getRobotCommandsFieldBuilder().addBuilder(
             index, GrSimCommands.grSim_Robot_Command.getDefaultInstance());
       }
GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.Builder.build () inline
Definition at line 1342 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         GrSimCommands.grSim_Commands result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 1350 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Commands.parseDelimitedFrom().
{
         GrSimCommands.grSim_Commands result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.Builder.buildPartial () inline
Definition at line 1360 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Commands.timestamp_.
Referenced by Protobuf.GrSimPacket.grSim_Packet.Builder.mergeCommands().
{
         GrSimCommands.grSim_Commands result = new GrSimCommands.grSim_Commands(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         result.timestamp_ = timestamp_;
         if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
           to_bitField0_ |= 0x00000002;
         }
         result.isteamyellow_ = isteamyellow_;
         if (robotCommandsBuilder_ == null) {
           if (((bitField0_ & 0x00000004) == 0x00000004)) {
             robotCommands_ = java.util.Collections.unmodifiableList(robotCommands_);
             bitField0_ = (bitField0_ & ~0x00000004);
           }
           result.robotCommands_ = robotCommands_;
         } else {
           result.robotCommands_ = robotCommandsBuilder_.build();
         }
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.clear () inline
Definition at line 1314 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Commands.Builder.clear().
Referenced by Protobuf.GrSimCommands.grSim_Commands.Builder.clear().
{
         super.clear();
         timestamp_ = 0D;
         bitField0_ = (bitField0_ & ~0x00000001);
         isteamyellow_ = false;
         bitField0_ = (bitField0_ & ~0x00000002);
         if (robotCommandsBuilder_ == null) {
           robotCommands_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000004);
         } else {
           robotCommandsBuilder_.clear();
         }
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.clearIsteamyellow () inline
Definition at line 1531 of file GrSimCommands.java.
{
         bitField0_ = (bitField0_ & ~0x00000002);
         isteamyellow_ = false;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.clearRobotCommands () inline
Definition at line 1657 of file GrSimCommands.java.
{
         if (robotCommandsBuilder_ == null) {
           robotCommands_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000004);
           onChanged();
         } else {
           robotCommandsBuilder_.clear();
         }
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.clearTimestamp () inline
Definition at line 1510 of file GrSimCommands.java.
{
         bitField0_ = (bitField0_ & ~0x00000001);
         timestamp_ = 0D;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.clone () inline
Definition at line 1329 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Commands.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.GrSimCommands.grSim_Commands.Builder.create () inline static private
Definition at line 1310 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Commands.newBuilder().
{
         return new Builder();
       }
void Protobuf.GrSimCommands.grSim_Commands.Builder.ensureRobotCommandsIsMutable () inline private
Definition at line 1541 of file GrSimCommands.java.
{
         if (!((bitField0_ & 0x00000004) == 0x00000004)) {
           robotCommands_ = new java.util.ArrayList<GrSimCommands.grSim_Robot_Command>(robotCommands_);
           bitField0_ |= 0x00000004;
          }
       }
GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.Builder.getDefaultInstanceForType () inline
Definition at line 1338 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Commands.getDefaultInstance().
{
         return GrSimCommands.grSim_Commands.getDefaultInstance();
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimCommands.grSim_Commands.Builder.getDescriptor () inline static
Definition at line 1287 of file GrSimCommands.java.
References Protobuf.GrSimCommands.internal_static_grSim_Commands_descriptor.
{
         return GrSimCommands.internal_static_grSim_Commands_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimCommands.grSim_Commands.Builder.getDescriptorForType () inline
Definition at line 1334 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Commands.getDescriptor().
{
         return GrSimCommands.grSim_Commands.getDescriptor();
       }
boolean Protobuf.GrSimCommands.grSim_Commands.Builder.getIsteamyellow () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1522 of file GrSimCommands.java.
{
         return isteamyellow_;
       }
GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Commands.Builder.getRobotCommands (int index) inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1565 of file GrSimCommands.java.
{
         if (robotCommandsBuilder_ == null) {
           return robotCommands_.get(index);
         } else {
           return robotCommandsBuilder_.getMessage(index);
         }
       }
GrSimCommands.grSim_Robot_Command.Builder Protobuf.GrSimCommands.grSim_Commands.Builder.getRobotCommandsBuilder (int index) inline
Definition at line 1677 of file GrSimCommands.java.
                      {
         return getRobotCommandsFieldBuilder().getBuilder(index);
       }
java.util.List<GrSimCommands.grSim_Robot_Command.Builder> Protobuf.GrSimCommands.grSim_Commands.Builder.getRobotCommandsBuilderList () inline
Definition at line 1706 of file GrSimCommands.java.
{
         return getRobotCommandsFieldBuilder().getBuilderList();
       }
int Protobuf.GrSimCommands.grSim_Commands.Builder.getRobotCommandsCount () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1558 of file GrSimCommands.java.
{
         if (robotCommandsBuilder_ == null) {
           return robotCommands_.size();
         } else {
           return robotCommandsBuilder_.getCount();
         }
       }
com.google.protobuf.RepeatedFieldBuilder< GrSimCommands.grSim_Robot_Command, GrSimCommands.grSim_Robot_Command.Builder, GrSimCommands.grSim_Robot_CommandOrBuilder> Protobuf.GrSimCommands.grSim_Commands.Builder.getRobotCommandsFieldBuilder () inline private
Definition at line 1711 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Commands.initFields().
{
         if (robotCommandsBuilder_ == null) {
           robotCommandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
               GrSimCommands.grSim_Robot_Command, GrSimCommands.grSim_Robot_Command.Builder, GrSimCommands.grSim_Robot_CommandOrBuilder>(
                   robotCommands_,
                   ((bitField0_ & 0x00000004) == 0x00000004),
                   getParentForChildren(),
                   isClean());
           robotCommands_ = null;
         }
         return robotCommandsBuilder_;
       }
java.util.List<GrSimCommands.grSim_Robot_Command> Protobuf.GrSimCommands.grSim_Commands.Builder.getRobotCommandsList () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1551 of file GrSimCommands.java.
{
         if (robotCommandsBuilder_ == null) {
           return java.util.Collections.unmodifiableList(robotCommands_);
         } else {
           return robotCommandsBuilder_.getMessageList();
         }
       }
GrSimCommands.grSim_Robot_CommandOrBuilder Protobuf.GrSimCommands.grSim_Commands.Builder.getRobotCommandsOrBuilder (int index) inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1681 of file GrSimCommands.java.
                      {
         if (robotCommandsBuilder_ == null) {
           return robotCommands_.get(index);  } else {
           return robotCommandsBuilder_.getMessageOrBuilder(index);
         }
       }
java.util.List<? extends GrSimCommands.grSim_Robot_CommandOrBuilder> Protobuf.GrSimCommands.grSim_Commands.Builder.getRobotCommandsOrBuilderList () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1689 of file GrSimCommands.java.
{
         if (robotCommandsBuilder_ != null) {
           return robotCommandsBuilder_.getMessageOrBuilderList();
         } else {
           return java.util.Collections.unmodifiableList(robotCommands_);
         }
       }
double Protobuf.GrSimCommands.grSim_Commands.Builder.getTimestamp () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1501 of file GrSimCommands.java.
{
         return timestamp_;
       }
boolean Protobuf.GrSimCommands.grSim_Commands.Builder.hasIsteamyellow () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1519 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000002) == 0x00000002);
       }
boolean Protobuf.GrSimCommands.grSim_Commands.Builder.hasTimestamp () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1498 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.GrSimCommands.grSim_Commands.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 1292 of file GrSimCommands.java.
References Protobuf.GrSimCommands.internal_static_grSim_Commands_fieldAccessorTable.
{
         return GrSimCommands.internal_static_grSim_Commands_fieldAccessorTable;
       }
final boolean Protobuf.GrSimCommands.grSim_Commands.Builder.isInitialized () inline
Definition at line 1433 of file GrSimCommands.java.
References velocity.pid_.i.
{
         if (!hasTimestamp()) {
           return false;
         }
         if (!hasIsteamyellow()) {
           return false;
         }
         for (int i = 0; i < getRobotCommandsCount(); i++) {
           if (!getRobotCommands(i).isInitialized()) {
             return false;
           }
         }
         return true;
       }
void Protobuf.GrSimCommands.grSim_Commands.Builder.maybeForceBuilderInitialization () inline private
Definition at line 1305 of file GrSimCommands.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
           getRobotCommandsFieldBuilder();
         }
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 1386 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Commands.Builder.clone(), Protobuf.GrSimPacket.grSim_Packet.Builder.mergeCommands(), Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom(), and Protobuf.GrSimCommands.grSim_Commands.newBuilder().
{
         if (other instanceof GrSimCommands.grSim_Commands) {
           return mergeFrom((GrSimCommands.grSim_Commands)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.mergeFrom (GrSimCommands.grSim_Commands other) inline
Definition at line 1395 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Commands.getDefaultInstance(), and Protobuf.GrSimCommands.grSim_Commands.Builder.robotCommands_.
{
         if (other == GrSimCommands.grSim_Commands.getDefaultInstance()) return this;
         if (other.hasTimestamp()) {
           setTimestamp(other.getTimestamp());
         }
         if (other.hasIsteamyellow()) {
           setIsteamyellow(other.getIsteamyellow());
         }
         if (robotCommandsBuilder_ == null) {
           if (!other.robotCommands_.isEmpty()) {
             if (robotCommands_.isEmpty()) {
               robotCommands_ = other.robotCommands_;
               bitField0_ = (bitField0_ & ~0x00000004);
             } else {
               ensureRobotCommandsIsMutable();
               robotCommands_.addAll(other.robotCommands_);
             }
             onChanged();
           }
         } else {
           if (!other.robotCommands_.isEmpty()) {
             if (robotCommandsBuilder_.isEmpty()) {
               robotCommandsBuilder_.dispose();
               robotCommandsBuilder_ = null;
               robotCommands_ = other.robotCommands_;
               bitField0_ = (bitField0_ & ~0x00000004);
               robotCommandsBuilder_ =
                 com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                    getRobotCommandsFieldBuilder() : null;
             } else {
               robotCommandsBuilder_.addAllMessages(other.robotCommands_);
             }
           }
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 1451 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Commands.Builder.Builder(), and Protobuf.GrSimCommands.grSim_Robot_Command.newBuilder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 9: {
               bitField0_ |= 0x00000001;
               timestamp_ = input.readDouble();
               break;
             }
             case 16: {
               bitField0_ |= 0x00000002;
               isteamyellow_ = input.readBool();
               break;
             }
             case 26: {
               GrSimCommands.grSim_Robot_Command.Builder subBuilder = GrSimCommands.grSim_Robot_Command.newBuilder();
               input.readMessage(subBuilder, extensionRegistry);
               addRobotCommands(subBuilder.buildPartial());
               break;
             }
           }
         }
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.removeRobotCommands (int index) inline
Definition at line 1667 of file GrSimCommands.java.
{
         if (robotCommandsBuilder_ == null) {
           ensureRobotCommandsIsMutable();
           robotCommands_.remove(index);
           onChanged();
         } else {
           robotCommandsBuilder_.remove(index);
         }
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.setIsteamyellow (boolean value) inline
Definition at line 1525 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000002;
         isteamyellow_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.setRobotCommands (int index, GrSimCommands.grSim_Robot_Command value) inline
Definition at line 1572 of file GrSimCommands.java.
{
         if (robotCommandsBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureRobotCommandsIsMutable();
           robotCommands_.set(index, value);
           onChanged();
         } else {
           robotCommandsBuilder_.setMessage(index, value);
         }
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.setRobotCommands (int index, GrSimCommands.grSim_Robot_Command.Builder builderForValue) inline
Definition at line 1586 of file GrSimCommands.java.
{
         if (robotCommandsBuilder_ == null) {
           ensureRobotCommandsIsMutable();
           robotCommands_.set(index, builderForValue.build());
           onChanged();
         } else {
           robotCommandsBuilder_.setMessage(index, builderForValue.build());
         }
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Commands.Builder.setTimestamp (double value) inline
Definition at line 1504 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000001;
         timestamp_ = value;
         onChanged();
         return this;
       }
Field Documentation
int Protobuf.GrSimCommands.grSim_Commands.Builder.bitField0_ private
Definition at line 1494 of file GrSimCommands.java.
boolean Protobuf.GrSimCommands.grSim_Commands.Builder.isteamyellow_ private
Definition at line 1518 of file GrSimCommands.java.
java.util.List<GrSimCommands.grSim_Robot_Command> Protobuf.GrSimCommands.grSim_Commands.Builder.robotCommands_ private
Initial value:
=
        java.util.Collections.emptyList()
Definition at line 1539 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Commands.Builder.mergeFrom().
com.google.protobuf.RepeatedFieldBuilder< GrSimCommands.grSim_Robot_Command, GrSimCommands.grSim_Robot_Command.Builder, GrSimCommands.grSim_Robot_CommandOrBuilder> Protobuf.GrSimCommands.grSim_Commands.Builder.robotCommandsBuilder_ private
Definition at line 1549 of file GrSimCommands.java.
double Protobuf.GrSimCommands.grSim_Commands.Builder.timestamp_ private
Definition at line 1497 of file GrSimCommands.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimCommands.java