Documentation: Protobuf.GrSimReplacement.grSim_RobotReplacement Class Reference
Protobuf.GrSimReplacement.grSim_RobotReplacement Class Reference
Data Structures
class Builder
Public Member Functions
grSim_RobotReplacement getDefaultInstanceForType ()
boolean hasX ()
double getX ()
boolean hasY ()
double getY ()
boolean hasDir ()
double getDir ()
boolean hasId ()
int getId ()
boolean hasYellowteam ()
boolean getYellowteam ()
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static grSim_RobotReplacement getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static GrSimReplacement.grSim_RobotReplacement parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimReplacement.grSim_RobotReplacement parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimReplacement.grSim_RobotReplacement parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimReplacement.grSim_RobotReplacement parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimReplacement.grSim_RobotReplacement parseFrom (java.io.InputStream input) throws java.io.IOException
static GrSimReplacement.grSim_RobotReplacement parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static GrSimReplacement.grSim_RobotReplacement parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static GrSimReplacement.grSim_RobotReplacement parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static GrSimReplacement.grSim_RobotReplacement parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static GrSimReplacement.grSim_RobotReplacement parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (GrSimReplacement.grSim_RobotReplacement prototype)
Static Public Attributes
static final int X_FIELD_NUMBER = 1
static final int Y_FIELD_NUMBER = 2
static final int DIR_FIELD_NUMBER = 3
static final int ID_FIELD_NUMBER = 4
static final int YELLOWTEAM_FIELD_NUMBER = 5
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
grSim_RobotReplacement (Builder builder)
grSim_RobotReplacement (boolean noInit)
void initFields ()
Private Attributes
int bitField0_
double x_
double y_
double dir_
int id_
boolean yellowteam_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final grSim_RobotReplacement defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 34 of file GrSimReplacement.java.
Constructor & Destructor Documentation
Protobuf.GrSimReplacement.grSim_RobotReplacement.grSim_RobotReplacement (Builder builder) inline private
Definition at line 38 of file GrSimReplacement.java.
{
       super(builder);
     }
Protobuf.GrSimReplacement.grSim_RobotReplacement.grSim_RobotReplacement (boolean noInit) inline private
Definition at line 41 of file GrSimReplacement.java.
 {}
Member Function Documentation
static grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.getDefaultInstance () inline static
Definition at line 44 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.Builder.addRobotsBuilder(), Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.getDefaultInstanceForType(), and Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.mergeFrom().
{
       return defaultInstance;
     }
grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.getDefaultInstanceForType () inline
Definition at line 48 of file GrSimReplacement.java.
{
       return defaultInstance;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimReplacement.grSim_RobotReplacement.getDescriptor () inline static
Definition at line 53 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.internal_static_grSim_RobotReplacement_descriptor.
Referenced by Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.getDescriptorForType().
{
       return GrSimReplacement.internal_static_grSim_RobotReplacement_descriptor;
     }
double Protobuf.GrSimReplacement.grSim_RobotReplacement.getDir () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 89 of file GrSimReplacement.java.
{
       return dir_;
     }
int Protobuf.GrSimReplacement.grSim_RobotReplacement.getId () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 99 of file GrSimReplacement.java.
{
       return id_;
     }
int Protobuf.GrSimReplacement.grSim_RobotReplacement.getSerializedSize () inline
Definition at line 171 of file GrSimReplacement.java.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeDoubleSize(1, x_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         size += com.google.protobuf.CodedOutputStream
           .computeDoubleSize(2, y_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         size += com.google.protobuf.CodedOutputStream
           .computeDoubleSize(3, dir_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         size += com.google.protobuf.CodedOutputStream
           .computeUInt32Size(4, id_);
       }
       if (((bitField0_ & 0x00000010) == 0x00000010)) {
         size += com.google.protobuf.CodedOutputStream
           .computeBoolSize(5, yellowteam_);
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
double Protobuf.GrSimReplacement.grSim_RobotReplacement.getX () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 69 of file GrSimReplacement.java.
{
       return x_;
     }
double Protobuf.GrSimReplacement.grSim_RobotReplacement.getY () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 79 of file GrSimReplacement.java.
{
       return y_;
     }
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.getYellowteam () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 109 of file GrSimReplacement.java.
{
       return yellowteam_;
     }
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.hasDir () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 86 of file GrSimReplacement.java.
{
       return ((bitField0_ & 0x00000004) == 0x00000004);
     }
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.hasId () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 96 of file GrSimReplacement.java.
{
       return ((bitField0_ & 0x00000008) == 0x00000008);
     }
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.hasX () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 66 of file GrSimReplacement.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.hasY () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 76 of file GrSimReplacement.java.
{
       return ((bitField0_ & 0x00000002) == 0x00000002);
     }
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.hasYellowteam () inline
Implements Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.
Definition at line 106 of file GrSimReplacement.java.
{
       return ((bitField0_ & 0x00000010) == 0x00000010);
     }
void Protobuf.GrSimReplacement.grSim_RobotReplacement.initFields () inline private
Definition at line 113 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.clearYellowteam().
{
       x_ = 0D;
       y_ = 0D;
       dir_ = 0D;
       id_ = 0;
       yellowteam_ = false;
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.GrSimReplacement.grSim_RobotReplacement.internalGetFieldAccessorTable () inline protected
Definition at line 58 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.internal_static_grSim_RobotReplacement_fieldAccessorTable.
{
       return GrSimReplacement.internal_static_grSim_RobotReplacement_fieldAccessorTable;
     }
final boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.isInitialized () inline
Definition at line 121 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasDir(), Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasId(), Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasX(), Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasY(), and Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasYellowteam().
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (!hasX()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasY()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasDir()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasId()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasYellowteam()) {
         memoizedIsInitialized = 0;
         return false;
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.newBuilder () inline static
Definition at line 275 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.create().
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeFrom().
 { return Builder.create(); }
static Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.newBuilder (GrSimReplacement.grSim_RobotReplacement prototype) inline static
Definition at line 277 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.newBuilderForType () inline
Definition at line 276 of file GrSimReplacement.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 283 of file GrSimReplacement.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 242 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 251 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 208 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 213 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 220 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 224 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 231 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 235 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 262 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static GrSimReplacement.grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 267 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.GrSimReplacement.grSim_RobotReplacement.toBuilder () inline
Definition at line 280 of file GrSimReplacement.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.GrSimReplacement.grSim_RobotReplacement.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 203 of file GrSimReplacement.java.
{
       return super.writeReplace();
     }
void Protobuf.GrSimReplacement.grSim_RobotReplacement.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 149 of file GrSimReplacement.java.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeDouble(1, x_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         output.writeDouble(2, y_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         output.writeDouble(3, dir_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         output.writeUInt32(4, id_);
       }
       if (((bitField0_ & 0x00000010) == 0x00000010)) {
         output.writeBool(5, yellowteam_);
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
int Protobuf.GrSimReplacement.grSim_RobotReplacement.bitField0_ private
Definition at line 62 of file GrSimReplacement.java.
final grSim_RobotReplacement Protobuf.GrSimReplacement.grSim_RobotReplacement.defaultInstance static private
Definition at line 43 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_RobotReplacement.dir_ private
Definition at line 85 of file GrSimReplacement.java.
final int Protobuf.GrSimReplacement.grSim_RobotReplacement.DIR_FIELD_NUMBER = 3 static
Definition at line 84 of file GrSimReplacement.java.
int Protobuf.GrSimReplacement.grSim_RobotReplacement.id_ private
Definition at line 95 of file GrSimReplacement.java.
final int Protobuf.GrSimReplacement.grSim_RobotReplacement.ID_FIELD_NUMBER = 4 static
Definition at line 94 of file GrSimReplacement.java.
byte Protobuf.GrSimReplacement.grSim_RobotReplacement.memoizedIsInitialized = -1 private
Definition at line 120 of file GrSimReplacement.java.
int Protobuf.GrSimReplacement.grSim_RobotReplacement.memoizedSerializedSize = -1 private
Definition at line 170 of file GrSimReplacement.java.
final long Protobuf.GrSimReplacement.grSim_RobotReplacement.serialVersionUID = 0L static private
Definition at line 201 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_RobotReplacement.x_ private
Definition at line 65 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_RobotReplacement.Builder.buildPartial().
final int Protobuf.GrSimReplacement.grSim_RobotReplacement.X_FIELD_NUMBER = 1 static
Definition at line 64 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_RobotReplacement.y_ private
Definition at line 75 of file GrSimReplacement.java.
final int Protobuf.GrSimReplacement.grSim_RobotReplacement.Y_FIELD_NUMBER = 2 static
Definition at line 74 of file GrSimReplacement.java.
boolean Protobuf.GrSimReplacement.grSim_RobotReplacement.yellowteam_ private
Definition at line 105 of file GrSimReplacement.java.
final int Protobuf.GrSimReplacement.grSim_RobotReplacement.YELLOWTEAM_FIELD_NUMBER = 5 static
Definition at line 104 of file GrSimReplacement.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimReplacement.java