Documentation: CMVision::RegionLinkedList Class Reference
CMVision::RegionLinkedList Class Reference
#include <cmvision_region.h>
Public Member Functions
RegionLinkedList ()
Region * getInitialElement () const
int getNumRegions () const
void setFront (Region *r)
void setNum (int num)
void reset ()
void insertFront (Region *r)
Protected Attributes
Region * _first
int _num
Detailed Description
Definition at line 127 of file cmvision_region.h.
Constructor & Destructor Documentation
CMVision::RegionLinkedList::RegionLinkedList () inline
Definition at line 132 of file cmvision_region.h.
References role._GoToPoint::reset().
                      {
     reset();
   }
Member Function Documentation
Region* CMVision::RegionLinkedList::getInitialElement () const inline
Definition at line 135 of file cmvision_region.h.
Referenced by PluginDetectRobots::buildRegionTree(), PluginVisualize::DrawBlobs(), CMPattern::TeamDetector::findRobotsByModel(), CMPattern::TeamDetector::findRobotsByTeamMarkerOnly(), CMPattern::MultiPatternModel::loadSinglePatternImage(), and PluginDetectBalls::process().
{
     return _first;
   }
int CMVision::RegionLinkedList::getNumRegions () const inline
Definition at line 138 of file cmvision_region.h.
{
    return _num;
   };
void CMVision::RegionLinkedList::insertFront (Region * r) inline
Definition at line 151 of file cmvision_region.h.
References CMVision::Region::next.
Referenced by CMVision::RegionProcessing::separateRegions().
{
     r->next=_first;
     _first=r;
     _num++;
   }
void CMVision::RegionLinkedList::reset () inline
Definition at line 147 of file cmvision_region.h.
Referenced by PluginFindBlobs::process(), and CMVision::RegionProcessing::separateRegions().
                {
     _first=0;
     _num=0;
   }
void CMVision::RegionLinkedList::setFront (Region * r) inline
Definition at line 141 of file cmvision_region.h.
Referenced by CMVision::RegionProcessing::sortRegions().
{
     _first=r;
   }
void CMVision::RegionLinkedList::setNum (int num) inline
Definition at line 144 of file cmvision_region.h.
{
     _num=num;
   }
Field Documentation
Region* CMVision::RegionLinkedList::_first protected
Definition at line 129 of file cmvision_region.h.
int CMVision::RegionLinkedList::_num protected
Definition at line 130 of file cmvision_region.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/cmvision/cmvision_region.h