Documentation: Protobuf.GrSimCommands.grSim_Robot_Command Class Reference
Protobuf.GrSimCommands.grSim_Robot_Command Class Reference
Data Structures
class Builder
Public Member Functions
grSim_Robot_Command getDefaultInstanceForType ()
boolean hasId ()
int getId ()
boolean hasKickspeedx ()
float getKickspeedx ()
boolean hasKickspeedz ()
float getKickspeedz ()
boolean hasVeltangent ()
float getVeltangent ()
boolean hasVelnormal ()
float getVelnormal ()
boolean hasVelangular ()
float getVelangular ()
boolean hasSpinner ()
boolean getSpinner ()
boolean hasWheelsspeed ()
boolean getWheelsspeed ()
boolean hasWheel1 ()
float getWheel1 ()
boolean hasWheel2 ()
float getWheel2 ()
boolean hasWheel3 ()
float getWheel3 ()
boolean hasWheel4 ()
float getWheel4 ()
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static grSim_Robot_Command getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static GrSimCommands.grSim_Robot_Command parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimCommands.grSim_Robot_Command parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimCommands.grSim_Robot_Command parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimCommands.grSim_Robot_Command parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimCommands.grSim_Robot_Command parseFrom (java.io.InputStream input) throws java.io.IOException
static GrSimCommands.grSim_Robot_Command parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static GrSimCommands.grSim_Robot_Command parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static GrSimCommands.grSim_Robot_Command parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static GrSimCommands.grSim_Robot_Command parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static GrSimCommands.grSim_Robot_Command parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (GrSimCommands.grSim_Robot_Command prototype)
Static Public Attributes
static final int ID_FIELD_NUMBER = 1
static final int KICKSPEEDX_FIELD_NUMBER = 2
static final int KICKSPEEDZ_FIELD_NUMBER = 3
static final int VELTANGENT_FIELD_NUMBER = 4
static final int VELNORMAL_FIELD_NUMBER = 5
static final int VELANGULAR_FIELD_NUMBER = 6
static final int SPINNER_FIELD_NUMBER = 7
static final int WHEELSSPEED_FIELD_NUMBER = 8
static final int WHEEL1_FIELD_NUMBER = 9
static final int WHEEL2_FIELD_NUMBER = 10
static final int WHEEL3_FIELD_NUMBER = 11
static final int WHEEL4_FIELD_NUMBER = 12
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
grSim_Robot_Command (Builder builder)
grSim_Robot_Command (boolean noInit)
void initFields ()
Private Attributes
int bitField0_
int id_
float kickspeedx_
float kickspeedz_
float veltangent_
float velnormal_
float velangular_
boolean spinner_
boolean wheelsspeed_
float wheel1_
float wheel2_
float wheel3_
float wheel4_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final grSim_Robot_Command defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 61 of file GrSimCommands.java.
Constructor & Destructor Documentation
Protobuf.GrSimCommands.grSim_Robot_Command.grSim_Robot_Command (Builder builder) inline private
Definition at line 65 of file GrSimCommands.java.
{
       super(builder);
     }
Protobuf.GrSimCommands.grSim_Robot_Command.grSim_Robot_Command (boolean noInit) inline private
Definition at line 68 of file GrSimCommands.java.
 {}
Member Function Documentation
static grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.getDefaultInstance () inline static
Definition at line 71 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Commands.Builder.addRobotCommandsBuilder(), Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getDefaultInstanceForType(), and Protobuf.GrSimCommands.grSim_Robot_Command.Builder.mergeFrom().
{
       return defaultInstance;
     }
grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.getDefaultInstanceForType () inline
Definition at line 75 of file GrSimCommands.java.
{
       return defaultInstance;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimCommands.grSim_Robot_Command.getDescriptor () inline static
Definition at line 80 of file GrSimCommands.java.
References Protobuf.GrSimCommands.internal_static_grSim_Robot_Command_descriptor.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getDescriptorForType().
{
       return GrSimCommands.internal_static_grSim_Robot_Command_descriptor;
     }
int Protobuf.GrSimCommands.grSim_Robot_Command.getId () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 96 of file GrSimCommands.java.
{
       return id_;
     }
float Protobuf.GrSimCommands.grSim_Robot_Command.getKickspeedx () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 106 of file GrSimCommands.java.
{
       return kickspeedx_;
     }
float Protobuf.GrSimCommands.grSim_Robot_Command.getKickspeedz () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 116 of file GrSimCommands.java.
{
       return kickspeedz_;
     }
int Protobuf.GrSimCommands.grSim_Robot_Command.getSerializedSize () inline
Definition at line 308 of file GrSimCommands.java.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeUInt32Size(1, id_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(2, kickspeedx_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(3, kickspeedz_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(4, veltangent_);
       }
       if (((bitField0_ & 0x00000010) == 0x00000010)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(5, velnormal_);
       }
       if (((bitField0_ & 0x00000020) == 0x00000020)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(6, velangular_);
       }
       if (((bitField0_ & 0x00000040) == 0x00000040)) {
         size += com.google.protobuf.CodedOutputStream
           .computeBoolSize(7, spinner_);
       }
       if (((bitField0_ & 0x00000080) == 0x00000080)) {
         size += com.google.protobuf.CodedOutputStream
           .computeBoolSize(8, wheelsspeed_);
       }
       if (((bitField0_ & 0x00000100) == 0x00000100)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(9, wheel1_);
       }
       if (((bitField0_ & 0x00000200) == 0x00000200)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(10, wheel2_);
       }
       if (((bitField0_ & 0x00000400) == 0x00000400)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(11, wheel3_);
       }
       if (((bitField0_ & 0x00000800) == 0x00000800)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(12, wheel4_);
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.getSpinner () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 156 of file GrSimCommands.java.
{
       return spinner_;
     }
float Protobuf.GrSimCommands.grSim_Robot_Command.getVelangular () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 146 of file GrSimCommands.java.
{
       return velangular_;
     }
float Protobuf.GrSimCommands.grSim_Robot_Command.getVelnormal () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 136 of file GrSimCommands.java.
{
       return velnormal_;
     }
float Protobuf.GrSimCommands.grSim_Robot_Command.getVeltangent () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 126 of file GrSimCommands.java.
{
       return veltangent_;
     }
float Protobuf.GrSimCommands.grSim_Robot_Command.getWheel1 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 176 of file GrSimCommands.java.
{
       return wheel1_;
     }
float Protobuf.GrSimCommands.grSim_Robot_Command.getWheel2 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 186 of file GrSimCommands.java.
{
       return wheel2_;
     }
float Protobuf.GrSimCommands.grSim_Robot_Command.getWheel3 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 196 of file GrSimCommands.java.
{
       return wheel3_;
     }
float Protobuf.GrSimCommands.grSim_Robot_Command.getWheel4 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 206 of file GrSimCommands.java.
{
       return wheel4_;
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.getWheelsspeed () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 166 of file GrSimCommands.java.
{
       return wheelsspeed_;
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.hasId () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 93 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.hasKickspeedx () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 103 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000002) == 0x00000002);
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.hasKickspeedz () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 113 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000004) == 0x00000004);
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.hasSpinner () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 153 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000040) == 0x00000040);
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.hasVelangular () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 143 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000020) == 0x00000020);
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.hasVelnormal () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 133 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000010) == 0x00000010);
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.hasVeltangent () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 123 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000008) == 0x00000008);
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.hasWheel1 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 173 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000100) == 0x00000100);
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.hasWheel2 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 183 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000200) == 0x00000200);
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.hasWheel3 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 193 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000400) == 0x00000400);
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.hasWheel4 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 203 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000800) == 0x00000800);
     }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.hasWheelsspeed () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 163 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000080) == 0x00000080);
     }
void Protobuf.GrSimCommands.grSim_Robot_Command.initFields () inline private
Definition at line 210 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clearWheel4().
{
       id_ = 0;
       kickspeedx_ = 0F;
       kickspeedz_ = 0F;
       veltangent_ = 0F;
       velnormal_ = 0F;
       velangular_ = 0F;
       spinner_ = false;
       wheelsspeed_ = false;
       wheel1_ = 0F;
       wheel2_ = 0F;
       wheel3_ = 0F;
       wheel4_ = 0F;
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.GrSimCommands.grSim_Robot_Command.internalGetFieldAccessorTable () inline protected
Definition at line 85 of file GrSimCommands.java.
References Protobuf.GrSimCommands.internal_static_grSim_Robot_Command_fieldAccessorTable.
{
       return GrSimCommands.internal_static_grSim_Robot_Command_fieldAccessorTable;
     }
final boolean Protobuf.GrSimCommands.grSim_Robot_Command.isInitialized () inline
Definition at line 225 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasId(), Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasKickspeedx(), Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasKickspeedz(), Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasSpinner(), Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasVelangular(), Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasVelnormal(), Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasVeltangent(), and Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasWheelsspeed().
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (!hasId()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasKickspeedx()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasKickspeedz()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasVeltangent()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasVelnormal()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasVelangular()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasSpinner()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasWheelsspeed()) {
         memoizedIsInitialized = 0;
         return false;
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.GrSimCommands.grSim_Robot_Command.newBuilder () inline static
Definition at line 440 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.Builder.create().
Referenced by Protobuf.GrSimCommands.grSim_Commands.Builder.mergeFrom(), and Client.Conection.send().
 { return Builder.create(); }
static Builder Protobuf.GrSimCommands.grSim_Robot_Command.newBuilder (GrSimCommands.grSim_Robot_Command prototype) inline static
Definition at line 442 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.newBuilderForType () inline
Definition at line 441 of file GrSimCommands.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.GrSimCommands.grSim_Robot_Command.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 448 of file GrSimCommands.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 407 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 416 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 373 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 378 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 385 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 389 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 396 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 400 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 427 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 432 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.toBuilder () inline
Definition at line 445 of file GrSimCommands.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.GrSimCommands.grSim_Robot_Command.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 368 of file GrSimCommands.java.
{
       return super.writeReplace();
     }
void Protobuf.GrSimCommands.grSim_Robot_Command.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 265 of file GrSimCommands.java.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeUInt32(1, id_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         output.writeFloat(2, kickspeedx_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         output.writeFloat(3, kickspeedz_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         output.writeFloat(4, veltangent_);
       }
       if (((bitField0_ & 0x00000010) == 0x00000010)) {
         output.writeFloat(5, velnormal_);
       }
       if (((bitField0_ & 0x00000020) == 0x00000020)) {
         output.writeFloat(6, velangular_);
       }
       if (((bitField0_ & 0x00000040) == 0x00000040)) {
         output.writeBool(7, spinner_);
       }
       if (((bitField0_ & 0x00000080) == 0x00000080)) {
         output.writeBool(8, wheelsspeed_);
       }
       if (((bitField0_ & 0x00000100) == 0x00000100)) {
         output.writeFloat(9, wheel1_);
       }
       if (((bitField0_ & 0x00000200) == 0x00000200)) {
         output.writeFloat(10, wheel2_);
       }
       if (((bitField0_ & 0x00000400) == 0x00000400)) {
         output.writeFloat(11, wheel3_);
       }
       if (((bitField0_ & 0x00000800) == 0x00000800)) {
         output.writeFloat(12, wheel4_);
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
int Protobuf.GrSimCommands.grSim_Robot_Command.bitField0_ private
Definition at line 89 of file GrSimCommands.java.
final grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.defaultInstance static private
Definition at line 70 of file GrSimCommands.java.
int Protobuf.GrSimCommands.grSim_Robot_Command.id_ private
Definition at line 92 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.Builder.buildPartial().
final int Protobuf.GrSimCommands.grSim_Robot_Command.ID_FIELD_NUMBER = 1 static
Definition at line 91 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.kickspeedx_ private
Definition at line 102 of file GrSimCommands.java.
final int Protobuf.GrSimCommands.grSim_Robot_Command.KICKSPEEDX_FIELD_NUMBER = 2 static
Definition at line 101 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.kickspeedz_ private
Definition at line 112 of file GrSimCommands.java.
final int Protobuf.GrSimCommands.grSim_Robot_Command.KICKSPEEDZ_FIELD_NUMBER = 3 static
Definition at line 111 of file GrSimCommands.java.
byte Protobuf.GrSimCommands.grSim_Robot_Command.memoizedIsInitialized = -1 private
Definition at line 224 of file GrSimCommands.java.
int Protobuf.GrSimCommands.grSim_Robot_Command.memoizedSerializedSize = -1 private
Definition at line 307 of file GrSimCommands.java.
final long Protobuf.GrSimCommands.grSim_Robot_Command.serialVersionUID = 0L static private
Definition at line 366 of file GrSimCommands.java.
boolean Protobuf.GrSimCommands.grSim_Robot_Command.spinner_ private
Definition at line 152 of file GrSimCommands.java.
final int Protobuf.GrSimCommands.grSim_Robot_Command.SPINNER_FIELD_NUMBER = 7 static
Definition at line 151 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.velangular_ private
Definition at line 142 of file GrSimCommands.java.
final int Protobuf.GrSimCommands.grSim_Robot_Command.VELANGULAR_FIELD_NUMBER = 6 static
Definition at line 141 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.velnormal_ private
Definition at line 132 of file GrSimCommands.java.
final int Protobuf.GrSimCommands.grSim_Robot_Command.VELNORMAL_FIELD_NUMBER = 5 static
Definition at line 131 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.veltangent_ private
Definition at line 122 of file GrSimCommands.java.
final int Protobuf.GrSimCommands.grSim_Robot_Command.VELTANGENT_FIELD_NUMBER = 4 static
Definition at line 121 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.wheel1_ private
Definition at line 172 of file GrSimCommands.java.
final int Protobuf.GrSimCommands.grSim_Robot_Command.WHEEL1_FIELD_NUMBER = 9 static
Definition at line 171 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.wheel2_ private
Definition at line 182 of file GrSimCommands.java.
final int Protobuf.GrSimCommands.grSim_Robot_Command.WHEEL2_FIELD_NUMBER = 10 static
Definition at line 181 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.wheel3_ private
Definition at line 192 of file GrSimCommands.java.
final int Protobuf.GrSimCommands.grSim_Robot_Command.WHEEL3_FIELD_NUMBER = 11 static
Definition at line 191 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.wheel4_ private
Definition at line 202 of file GrSimCommands.java.
final int Protobuf.GrSimCommands.grSim_Robot_Command.WHEEL4_FIELD_NUMBER = 12 static
Definition at line 201 of file GrSimCommands.java.
boolean Protobuf.GrSimCommands.grSim_Robot_Command.wheelsspeed_ private
Definition at line 162 of file GrSimCommands.java.
final int Protobuf.GrSimCommands.grSim_Robot_Command.WHEELSSPEED_FIELD_NUMBER = 8 static
Definition at line 161 of file GrSimCommands.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimCommands.java