Documentation: CMVision::RegionProcessing Class Reference
CMVision::RegionProcessing Class Reference
#include <cmvision_region.h>
Public Member Functions
RegionProcessing ()
~RegionProcessing ()
Static Public Member Functions
static void encodeRuns (Image< raw8 > *tmap, CMVision::RunList *runlist)
static void connectComponents (CMVision::RunList *runlist)
static void extractRegions (CMVision::RegionList *reglist, CMVision::RunList *runlist)
static int separateRegions (CMVision::ColorRegionList *colorlist, CMVision::RegionList *reglist, int min_area)
static CMVision::Region * sortRegionListByArea (CMVision::Region *list, int passes)
static void sortRegions (CMVision::ColorRegionList *colors, int max_area)
Static Protected Member Functions
static int rangeSum (int x, int w)
static int rangeSumSq (int x, int w)
Detailed Description
Author
Author Name
Definition at line 270 of file cmvision_region.h.
Constructor & Destructor Documentation
CMVision::RegionProcessing::RegionProcessing ()
Definition at line 27 of file cmvision_region.cpp.
 {
 }
CMVision::RegionProcessing::~RegionProcessing ()
Definition at line 32 of file cmvision_region.cpp.
 {
 }
Member Function Documentation
void CMVision::RegionProcessing::connectComponents (CMVision::RunList * runlist) static
Definition at line 97 of file cmvision_region.cpp.
References CMVision::Run::color, CMVision::RunList::getRunArrayPointer(), CMVision::RunList::getUsedRuns(), velocity.pid_::i, CMVision::Run::parent, ColorGrey< num, fmt >::v, CMVision::Run::width, CMVision::Run::x, and role._GoToPoint::y.
Referenced by PluginFindBlobs::process(), and CMVision::ImageProcessor::processThresholded().
 {
   CMVision::Run * map=runlist->getRunArrayPointer();
   int num = runlist->getUsedRuns();
   int l1,l2;
   CMVision::Run r1,r2;
   int i,j,s;
   // l2 starts on first scan line, l1 starts on second
   l2 = 0;
   l1 = 1;
   while(map[l1].y == 0) l1++; // skip first line
   // Do rest in lock step
   r1 = map[l1];
   r2 = map[l2];
   s = l1;
   while(l1 < num){
     /*
     printf("%6d:(%3d,%3d,%3d) %6d:(%3d,%3d,%3d)\n",
        l1,r1.x,r1.y,r1.width,
        l2,r2.x,r2.y,r2.width);
     */
     if(r1.color==r2.color && r1.color.v!=0) {
       // case 1: r2.x <= r1.x < r2.x + r2.width
       // case 2: r1.x <= r2.x < r1.x + r1.width
       if((r2.x<=r1.x && r1.x<r2.x+r2.width) ||
         (r1.x<=r2.x && r2.x<r1.x+r1.width)){
         if(s != l1){
           // if we didn't have a parent already, just take this one
           map[l1].parent = r1.parent = r2.parent;
           s = l1;
         }else if(r1.parent != r2.parent){
           // otherwise union two parents if they are different
           // find terminal roots of each path up tree
           i = r1.parent;
           while(i != map[i].parent) i = map[i].parent;
           j = r2.parent;
           while(j != map[j].parent) j = map[j].parent;
           // union and compress paths; use smaller of two possible
           // representative indicies to preserve DAG property
           if(i < j){
             map[j].parent = i;
             map[l1].parent = map[l2].parent = r1.parent = r2.parent = i;
           }else{
             map[i].parent = j;
             map[l1].parent = map[l2].parent = r1.parent = r2.parent = j;
           }
         }
       }
     }
     // Move to next point where values may change
     i = (r2.x + r2.width) - (r1.x + r1.width);
     if(i >= 0) r1 = map[++l1];
     if(i <= 0) r2 = map[++l2];
   }
   // Now we need to compress all parent paths
   for(i=0; i<num; i++){
     j = map[i].parent;
     map[i].parent = map[j].parent;
   }
 }
void CMVision::RegionProcessing::encodeRuns (Image< raw8 > * tmap, CMVision::RunList * runlist) static
Definition at line 37 of file cmvision_region.cpp.
References CMVision::Run::color, Image< PIXEL >::getHeight(), CMVision::RunList::getMaxRuns(), Image< PIXEL >::getPixelData(), CMVision::RunList::getRunArrayPointer(), Image< PIXEL >::getWidth(), CMVision::Run::next, CMVision::Run::parent, CMVision::RunList::setUsedRuns(), CMVision::Run::width, role._GoToPoint::x, CMVision::Run::x, role._GoToPoint::y, and CMVision::Run::y.
Referenced by PluginRunlengthEncode::process(), and CMVision::ImageProcessor::processThresholded().
 {
   int max_runs = runlist->getMaxRuns();
   CMVision::Run * runs = runlist->getRunArrayPointer();
   raw8 * map = tmap->getPixelData();
   int width=tmap->getWidth();
   int height=tmap->getHeight();
   raw8 clear(0);
   raw8 m;
   raw8 *row;
   int x,y,j,l;
   CMVision::Run r;
   r.next = 0;
   j = 0;
   for(y=0; y<height; y++){
     row = &map[y * width];
     r.y = y;
     x = 0;
     while(x < width){
       m = row[x];
       r.x = x;
       l = x;
       //fix by Stefan: stop if x==row-width
       //(and don't access the row array in that case as it could cause a segfault)
       //Note that the left argument of the && operator is always evaluated first and as
       //such this expression should be safe.
       while(x != width && row[x] == m) x++;
       if(m != clear || x==width) {
         r.color = m;
         r.width = x - l;
         r.parent = j;
         runs[j++] = r;
         if(j >= max_runs){
           runlist->setUsedRuns(j);
           return;
         }
       }
     }
   }
   runlist->setUsedRuns(j);
 }
void CMVision::RegionProcessing::extractRegions (CMVision::RegionList * reglist, CMVision::RunList * runlist) static
Definition at line 178 of file cmvision_region.cpp.
References CMVision::Region::area, CMVision::Region::cen_x, CMVision::Region::cen_y, CMVision::Run::color, CMVision::Region::color, kalman_filter::color, CMVision::RegionList::getMaxRegions(), CMVision::RegionList::getRegionArrayPointer(), CMVision::RunList::getRunArrayPointer(), CMVision::RunList::getUsedRuns(), velocity.pid_::i, CMVision::Region::iterator_id, GVector::max(), GVector::min(), CMVision::Run::next, CMVision::Run::parent, rangeSum(), CMVision::Region::run_start, CMVision::RegionList::setUsedRegions(), CMVision::Run::width, CMVision::Run::x, CMVision::Region::x1, CMVision::Region::x2, CMVision::Run::y, CMVision::Region::y1, and CMVision::Region::y2.
Referenced by PluginFindBlobs::process(), and CMVision::ImageProcessor::processThresholded().
 {
   int b,i,n,a;
   CMVision::Run r;
   CMVision::Region * reg = reglist->getRegionArrayPointer();
   CMVision::Run * rmap = runlist->getRunArrayPointer();
   int max_reg=reglist->getMaxRegions();
   int num = runlist->getUsedRuns();
   n = 0;
   for(i=0; i<num; i++){
     if(rmap[i].color.v!=0){
       r = rmap[i];
       if(r.parent == i){
         // Add new region if this run is a root (i.e. self parented)
         rmap[i].parent = b = n;  // renumber to point to region id
         reg[b].color = r.color;
         reg[b].area = r.width;
         reg[b].x1 = r.x;
         reg[b].y1 = r.y;
         reg[b].x2 = r.x + r.width;
         reg[b].y2 = r.y;
         reg[b].cen_x = rangeSum(r.x,r.width);
         reg[b].cen_y = r.y * r.width;
         reg[b].run_start = i;
         reg[b].iterator_id = i; // temporarily use to store last run
         n++;
         if(n >= max_reg) {
           reglist->setUsedRegions(max_reg);
           return;
         }
       }else{
         // Otherwise update region stats incrementally
         b = rmap[r.parent].parent;
         rmap[i].parent = b; // update parent to identify region id
         reg[b].area += r.width;
         reg[b].x2 = max(r.x + r.width,reg[b].x2);
         reg[b].x1 = min((int)r.x,reg[b].x1);
         reg[b].y2 = r.y; // last set by lowest run
         reg[b].cen_x += rangeSum(r.x,r.width);
         reg[b].cen_y += r.y * r.width;
         // set previous run to point to this one as next
         rmap[reg[b].iterator_id].next = i;
         reg[b].iterator_id = i;
       }
     }
   }
   // calculate centroids from stored sums
   for(i=0; i<n; i++){
     a = reg[i].area;
     reg[i].cen_x = (float)reg[i].cen_x / a;
     reg[i].cen_y = (float)reg[i].cen_y / a;
     rmap[reg[i].iterator_id].next = 0; // -1;
     reg[i].iterator_id = 0;
     reg[i].x2--; // change to inclusive range
   }
   reglist->setUsedRegions(n);
   return;
 }
static int CMVision::RegionProcessing::rangeSum (int x, int w) inline static protected
Definition at line 274 of file cmvision_region.h.
Referenced by extractRegions().
   {
     return(w*(2*x + w-1) / 2);
   }
static int CMVision::RegionProcessing::rangeSumSq (int x, int w) inline static protected
Definition at line 284 of file cmvision_region.h.
References CMVision::Run::y.
   {
     int y = x + w;
     int rs = y*(y-1)*(2*y-1) - x*(x-1)*(2*x-1);
     return(rs / 6);
   }
int CMVision::RegionProcessing::separateRegions (CMVision::ColorRegionList * colorlist, CMVision::RegionList * reglist, int min_area) static
Definition at line 250 of file cmvision_region.cpp.
References CMVision::Region::area, CMVision::Region::color, kalman_filter::color, CMVision::ColorRegionList::getColorRegionArrayPointer(), CMVision::ColorRegionList::getNumColorRegions(), CMVision::RegionList::getRegionArrayPointer(), CMVision::RegionList::getUsedRegions(), velocity.pid_::i, CMVision::RegionLinkedList::insertFront(), CMVision::RegionLinkedList::reset(), and ColorGrey< num, fmt >::v.
Referenced by PluginFindBlobs::process(), and CMVision::ImageProcessor::processThresholded().
 {
   CMVision::Region * p;
   int i; // ,l;
   uint8_t c;
   int area,max_area;
   int num_regions=reglist->getUsedRegions();
   CMVision::Region * reg = reglist->getRegionArrayPointer();
   int num_colors=colorlist->getNumColorRegions();
   CMVision::RegionLinkedList * color=colorlist->getColorRegionArrayPointer();
   // clear out the region list head table
   for(i=0; i<num_colors; i++){
     color[i].reset();
   }
   // step over the table, adding successive
   // regions to the front of each list
   max_area = 0;
   for(i=0; i<num_regions; i++){
     p = &reg[i];
     c = p->color.v;
     area = p->area;
     if (c >= num_colors) {
       printf("Found a color of index %d...but colorlist is only allocated for a max index of %d\n",c,num_colors-1);
     } else {
       if(area >= min_area){
         if(area > max_area) max_area = area;
         color[c].insertFront(p);
       }
     }
   }
   return(max_area);
 }
CMVision::Region * CMVision::RegionProcessing::sortRegionListByArea (CMVision::Region * list, int passes) static
Definition at line 301 of file cmvision_region.cpp.
References CMVision::Region::area, CMV_RADIX, CMV_RBITS, CMV_RMASK, velocity.pid_::i, and CMVision::Region::next.
Referenced by sortRegions().
 {
   CMVision::Region *tbl[CMV_RADIX],*p,*pn;
   int slot,shift;
   int i,j;
   // Handle trivial cases
   if(!list || !list->next) return(list);
   // Initialize table
   for(j=0; j<CMV_RADIX; j++) tbl[j] = NULL;
   for(i=0; i<passes; i++){
     // split list into buckets
     shift = CMV_RBITS * i;
     p = list;
     while(p){
       pn = p->next;
       slot = ((p->area) >> shift) & CMV_RMASK;
       p->next = tbl[slot];
       tbl[slot] = p;
       p = pn;
     }
     // integrate back into partially ordered list
     list = NULL;
     for(j=0; j<CMV_RADIX; j++){
       p = tbl[j];
       tbl[j] = NULL; // clear out table for next pass
       while(p){
         pn = p->next;
         p->next = list;
         list = p;
         p = pn;
       }
     }
   }
   return(list);
 }
void CMVision::RegionProcessing::sortRegions (CMVision::ColorRegionList * colors, int max_area) static
Definition at line 344 of file cmvision_region.cpp.
References CMV_RBITS, kalman_filter::color, CMVision::ColorRegionList::getColorRegionArrayPointer(), CMVision::ColorRegionList::getNumColorRegions(), velocity.pid_::i, CMVision::RegionLinkedList::setFront(), sortRegionListByArea(), and role._GoToPoint::x.
Referenced by PluginFindBlobs::process(), and CMVision::ImageProcessor::processThresholded().
 {
   int i,p;
   // do minimal number of passes sufficient to touch all set bits
   p = 0;
   while(max_area != 0){
     max_area >>= CMV_RBITS;
     p++;
   }
   int num_colors=colors->getNumColorRegions();
   CMVision::RegionLinkedList * color = colors->getColorRegionArrayPointer();
   // sort each list
   for(i=0; i<num_colors; i++){
     color[i].setFront(sortRegionListByArea(color[i].getInitialElement(),p));
   }
 }
The documentation for this class was generated from the following files:
ssl-vision/src/shared/cmvision/cmvision_region.h
ssl-vision/src/shared/cmvision/cmvision_region.cpp