Documentation: SSL_FieldLineSegment Class Reference
SSL_FieldLineSegment Class Reference
#include <messages_robocup_ssl_geometry.pb.h>
Public Member Functions
SSL_FieldLineSegment ()
virtual ~SSL_FieldLineSegment ()
SSL_FieldLineSegment (const SSL_FieldLineSegment &from)
SSL_FieldLineSegment & operator= (const SSL_FieldLineSegment &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_FieldLineSegment *other)
SSL_FieldLineSegment * New () const PROTOBUF_FINAL
SSL_FieldLineSegment * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_FieldLineSegment &from)
void MergeFrom (const SSL_FieldLineSegment &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_name () const
void clear_name ()
const ::std::string & name () const
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
::std::string * mutable_name ()
::std::string * release_name ()
void set_allocated_name (::std::string *name)
bool has_p1 () const
void clear_p1 ()
const ::Vector2f & p1 () const
::Vector2f * release_p1 ()
::Vector2f * mutable_p1 ()
void set_allocated_p1 (::Vector2f *p1)
bool has_p2 () const
void clear_p2 ()
const ::Vector2f & p2 () const
::Vector2f * release_p2 ()
::Vector2f * mutable_p2 ()
void set_allocated_p2 (::Vector2f *p2)
bool has_thickness () const
void clear_thickness ()
float thickness () const
void set_thickness (float value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_FieldLineSegment & default_instance ()
static void InitAsDefaultInstance ()
static const SSL_FieldLineSegment * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kNameFieldNumber = 1
static const int kP1FieldNumber = 2
static const int kP2FieldNumber = 3
static const int kThicknessFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_FieldLineSegment *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_name ()
void clear_has_name ()
void set_has_p1 ()
void clear_has_p1 ()
void set_has_p2 ()
void clear_has_p2 ()
void set_has_thickness ()
void clear_has_thickness ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_FieldLineSegmentImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::internal::ArenaStringPtr name_
::Vector2f * p1_
::Vector2f * p2_
float thickness_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::TableStruct
void swap (SSL_FieldLineSegment &a, SSL_FieldLineSegment &b)
Detailed Description
Definition at line 210 of file messages_robocup_ssl_geometry.pb.h.
Constructor & Destructor Documentation
SSL_FieldLineSegment::SSL_FieldLineSegment ()
virtual SSL_FieldLineSegment::~SSL_FieldLineSegment () virtual
SSL_FieldLineSegment::SSL_FieldLineSegment (const SSL_FieldLineSegment & from)
Member Function Documentation
size_t SSL_FieldLineSegment::ByteSizeLong () const
void SSL_FieldLineSegment::Clear ()
void SSL_FieldLineSegment::clear_has_name () inline private
Definition at line 1163 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void SSL_FieldLineSegment::clear_has_p1 () inline private
Definition at line 1226 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] &= ~0x00000002u;
 }
void SSL_FieldLineSegment::clear_has_p2 () inline private
Definition at line 1280 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] &= ~0x00000004u;
 }
void SSL_FieldLineSegment::clear_has_thickness () inline private
Definition at line 1334 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] &= ~0x00000008u;
 }
void SSL_FieldLineSegment::clear_name () inline
Definition at line 1166 of file messages_robocup_ssl_geometry.pb.h.
{
   name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   clear_has_name();
 }
void SSL_FieldLineSegment::clear_p1 () inline
Definition at line 1229 of file messages_robocup_ssl_geometry.pb.h.
{
   if (p1_ != NULL) p1_->Clear();
   clear_has_p1();
 }
void SSL_FieldLineSegment::clear_p2 () inline
Definition at line 1283 of file messages_robocup_ssl_geometry.pb.h.
{
   if (p2_ != NULL) p2_->Clear();
   clear_has_p2();
 }
void SSL_FieldLineSegment::clear_thickness () inline
Definition at line 1337 of file messages_robocup_ssl_geometry.pb.h.
{
   thickness_ = 0;
   clear_has_thickness();
 }
void SSL_FieldLineSegment::CopyFrom (const ::google::protobuf::Message & from)
void SSL_FieldLineSegment::CopyFrom (const SSL_FieldLineSegment & from)
static const SSL_FieldLineSegment& SSL_FieldLineSegment::default_instance () static
static const ::google::protobuf::Descriptor* SSL_FieldLineSegment::descriptor () static
inline ::google::protobuf::Arena* SSL_FieldLineSegment::GetArenaNoVirtual () const inline private
Definition at line 285 of file messages_robocup_ssl_geometry.pb.h.
Referenced by operator=().
{
     return NULL;
   }
int SSL_FieldLineSegment::GetCachedSize () const inline
Definition at line 278 of file messages_robocup_ssl_geometry.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata SSL_FieldLineSegment::GetMetadata () const
bool SSL_FieldLineSegment::has_name () const inline
Definition at line 1157 of file messages_robocup_ssl_geometry.pb.h.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool SSL_FieldLineSegment::has_p1 () const inline
Definition at line 1220 of file messages_robocup_ssl_geometry.pb.h.
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool SSL_FieldLineSegment::has_p2 () const inline
Definition at line 1274 of file messages_robocup_ssl_geometry.pb.h.
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool SSL_FieldLineSegment::has_thickness () const inline
Definition at line 1328 of file messages_robocup_ssl_geometry.pb.h.
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
static void SSL_FieldLineSegment::InitAsDefaultInstance () static
static const SSL_FieldLineSegment* SSL_FieldLineSegment::internal_default_instance () inline static
Definition at line 247 of file messages_robocup_ssl_geometry.pb.h.
References _SSL_FieldLineSegment_default_instance_.
{
     return reinterpret_cast<const SSL_FieldLineSegment*>(
                &_SSL_FieldLineSegment_default_instance_);
   }
::google::protobuf::uint8* SSL_FieldLineSegment::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void SSL_FieldLineSegment::InternalSwap (SSL_FieldLineSegment * other) private
bool SSL_FieldLineSegment::IsInitialized () const
void* SSL_FieldLineSegment::MaybeArenaPtr () const inline private
Definition at line 288 of file messages_robocup_ssl_geometry.pb.h.
{
     return NULL;
   }
void SSL_FieldLineSegment::MergeFrom (const ::google::protobuf::Message & from)
void SSL_FieldLineSegment::MergeFrom (const SSL_FieldLineSegment & from)
bool SSL_FieldLineSegment::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
std::string * SSL_FieldLineSegment::mutable_name () inline
Definition at line 1199 of file messages_robocup_ssl_geometry.pb.h.
{
   set_has_name();
   // @@protoc_insertion_point(field_mutable:SSL_FieldLineSegment.name)
   return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
Vector2f * SSL_FieldLineSegment::mutable_p1 () inline
Definition at line 1246 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSLWorld::addFieldLine(), and RoboCupField::toProtoBuffer().
{
   set_has_p1();
   if (p1_ == NULL) {
     p1_ = new ::Vector2f;
   }
   // @@protoc_insertion_point(field_mutable:SSL_FieldLineSegment.p1)
   return p1_;
 }
Vector2f * SSL_FieldLineSegment::mutable_p2 () inline
Definition at line 1300 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSLWorld::addFieldLine(), and RoboCupField::toProtoBuffer().
{
   set_has_p2();
   if (p2_ == NULL) {
     p2_ = new ::Vector2f;
   }
   // @@protoc_insertion_point(field_mutable:SSL_FieldLineSegment.p2)
   return p2_;
 }
inline ::google::protobuf::UnknownFieldSet* SSL_FieldLineSegment::mutable_unknown_fields () inline
Definition at line 239 of file messages_robocup_ssl_geometry.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
const ::std::string & SSL_FieldLineSegment::name () const inline
Definition at line 1170 of file messages_robocup_ssl_geometry.pb.h.
Referenced by GLSoccerView::updateFieldGeometry().
{
   // @@protoc_insertion_point(field_get:SSL_FieldLineSegment.name)
   return name_.GetNoArena();
 }
SSL_FieldLineSegment* SSL_FieldLineSegment::New () const inline
Definition at line 261 of file messages_robocup_ssl_geometry.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_FieldLineSegment* SSL_FieldLineSegment::New (::google::protobuf::Arena * arena) const
SSL_FieldLineSegment& SSL_FieldLineSegment::operator= (const SSL_FieldLineSegment & from) inline
Definition at line 217 of file messages_robocup_ssl_geometry.pb.h.
References GetArenaNoVirtual().
{
     CopyFrom(from);
     return *this;
   }
const ::Vector2f & SSL_FieldLineSegment::p1 () const inline
Definition at line 1233 of file messages_robocup_ssl_geometry.pb.h.
References _Vector2f_default_instance_.
Referenced by GLSoccerView::updateFieldGeometry().
{
   const ::Vector2f* p = p1_;
   // @@protoc_insertion_point(field_get:SSL_FieldLineSegment.p1)
   return p != NULL ? *p : *reinterpret_cast<const ::Vector2f*>(
       &::_Vector2f_default_instance_);
 }
const ::Vector2f & SSL_FieldLineSegment::p2 () const inline
Definition at line 1287 of file messages_robocup_ssl_geometry.pb.h.
References _Vector2f_default_instance_.
Referenced by GLSoccerView::updateFieldGeometry().
{
   const ::Vector2f* p = p2_;
   // @@protoc_insertion_point(field_get:SSL_FieldLineSegment.p2)
   return p != NULL ? *p : *reinterpret_cast<const ::Vector2f*>(
       &::_Vector2f_default_instance_);
 }
std::string * SSL_FieldLineSegment::release_name () inline
Definition at line 1204 of file messages_robocup_ssl_geometry.pb.h.
{
   // @@protoc_insertion_point(field_release:SSL_FieldLineSegment.name)
   clear_has_name();
   return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
Vector2f * SSL_FieldLineSegment::release_p1 () inline
Definition at line 1239 of file messages_robocup_ssl_geometry.pb.h.
{
   // @@protoc_insertion_point(field_release:SSL_FieldLineSegment.p1)
   clear_has_p1();
   ::Vector2f* temp = p1_;
   p1_ = NULL;
   return temp;
 }
Vector2f * SSL_FieldLineSegment::release_p2 () inline
Definition at line 1293 of file messages_robocup_ssl_geometry.pb.h.
{
   // @@protoc_insertion_point(field_release:SSL_FieldLineSegment.p2)
   clear_has_p2();
   ::Vector2f* temp = p2_;
   p2_ = NULL;
   return temp;
 }
size_t SSL_FieldLineSegment::RequiredFieldsByteSizeFallback () const private
void SSL_FieldLineSegment::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void SSL_FieldLineSegment::set_allocated_name (::std::string * name) inline
Definition at line 1209 of file messages_robocup_ssl_geometry.pb.h.
{
   if (name != NULL) {
     set_has_name();
   } else {
     clear_has_name();
   }
   name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
   // @@protoc_insertion_point(field_set_allocated:SSL_FieldLineSegment.name)
 }
void SSL_FieldLineSegment::set_allocated_p1 (::Vector2f * p1) inline
Definition at line 1254 of file messages_robocup_ssl_geometry.pb.h.
{
   ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
   if (message_arena == NULL) {
     delete p1_;
   }
   if (p1) {
     ::google::protobuf::Arena* submessage_arena = NULL;
     if (message_arena != submessage_arena) {
       p1 = ::google::protobuf::internal::GetOwnedMessage(
           message_arena, p1, submessage_arena);
     }
     set_has_p1();
   } else {
     clear_has_p1();
   }
   p1_ = p1;
   // @@protoc_insertion_point(field_set_allocated:SSL_FieldLineSegment.p1)
 }
void SSL_FieldLineSegment::set_allocated_p2 (::Vector2f * p2) inline
Definition at line 1308 of file messages_robocup_ssl_geometry.pb.h.
{
   ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
   if (message_arena == NULL) {
     delete p2_;
   }
   if (p2) {
     ::google::protobuf::Arena* submessage_arena = NULL;
     if (message_arena != submessage_arena) {
       p2 = ::google::protobuf::internal::GetOwnedMessage(
           message_arena, p2, submessage_arena);
     }
     set_has_p2();
   } else {
     clear_has_p2();
   }
   p2_ = p2;
   // @@protoc_insertion_point(field_set_allocated:SSL_FieldLineSegment.p2)
 }
void SSL_FieldLineSegment::set_has_name () inline private
Definition at line 1160 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] |= 0x00000001u;
 }
void SSL_FieldLineSegment::set_has_p1 () inline private
Definition at line 1223 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] |= 0x00000002u;
 }
void SSL_FieldLineSegment::set_has_p2 () inline private
Definition at line 1277 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] |= 0x00000004u;
 }
void SSL_FieldLineSegment::set_has_thickness () inline private
Definition at line 1331 of file messages_robocup_ssl_geometry.pb.h.
{
   _has_bits_[0] |= 0x00000008u;
 }
void SSL_FieldLineSegment::set_name (const ::std::string & value) inline
Definition at line 1174 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSLWorld::addFieldLine(), and RoboCupField::toProtoBuffer().
{
   set_has_name();
   name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
   // @@protoc_insertion_point(field_set:SSL_FieldLineSegment.name)
 }
void SSL_FieldLineSegment::set_name (const char * value) inline
Definition at line 1187 of file messages_robocup_ssl_geometry.pb.h.
{
   GOOGLE_DCHECK(value != NULL);
   set_has_name();
   name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
   // @@protoc_insertion_point(field_set_char:SSL_FieldLineSegment.name)
 }
void SSL_FieldLineSegment::set_name (const char * value, size_t size) inline
Definition at line 1193 of file messages_robocup_ssl_geometry.pb.h.
{
   set_has_name();
   name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
       ::std::string(reinterpret_cast<const char*>(value), size));
   // @@protoc_insertion_point(field_set_pointer:SSL_FieldLineSegment.name)
 }
void SSL_FieldLineSegment::set_thickness (float value) inline
Definition at line 1345 of file messages_robocup_ssl_geometry.pb.h.
Referenced by SSLWorld::addFieldLine(), and RoboCupField::toProtoBuffer().
{
   set_has_thickness();
   thickness_ = value;
   // @@protoc_insertion_point(field_set:SSL_FieldLineSegment.thickness)
 }
void SSL_FieldLineSegment::SetCachedSize (int size) const private
void SSL_FieldLineSegment::SharedCtor () private
void SSL_FieldLineSegment::SharedDtor () private
void SSL_FieldLineSegment::Swap (SSL_FieldLineSegment * other)
float SSL_FieldLineSegment::thickness () const inline
Definition at line 1341 of file messages_robocup_ssl_geometry.pb.h.
Referenced by GLSoccerView::updateFieldGeometry().
{
   // @@protoc_insertion_point(field_get:SSL_FieldLineSegment.thickness)
   return thickness_;
 }
const ::google::protobuf::UnknownFieldSet& SSL_FieldLineSegment::unknown_fields () const inline
Definition at line 236 of file messages_robocup_ssl_geometry.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
SSL_FieldLineSegment::void::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_FieldLineSegmentImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::TableStruct friend
Definition at line 360 of file messages_robocup_ssl_geometry.pb.h.
void swap (SSL_FieldLineSegment & a, SSL_FieldLineSegment & b) friend
Definition at line 255 of file messages_robocup_ssl_geometry.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int SSL_FieldLineSegment::_cached_size_ mutable private
Definition at line 355 of file messages_robocup_ssl_geometry.pb.h.
::google::protobuf::internal::HasBits<1> SSL_FieldLineSegment::_has_bits_ private
Definition at line 354 of file messages_robocup_ssl_geometry.pb.h.
::google::protobuf::internal::InternalMetadataWithArena SSL_FieldLineSegment::_internal_metadata_ private
Definition at line 353 of file messages_robocup_ssl_geometry.pb.h.
PROTOBUF_CONSTEXPR int const SSL_FieldLineSegment::kIndexInFileMessages static
Initial value:
=
    1
Definition at line 251 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_FieldLineSegment::kNameFieldNumber = 1 static
Definition at line 302 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_FieldLineSegment::kP1FieldNumber = 2 static
Definition at line 317 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_FieldLineSegment::kP2FieldNumber = 3 static
Definition at line 326 of file messages_robocup_ssl_geometry.pb.h.
const int SSL_FieldLineSegment::kThicknessFieldNumber = 4 static
Definition at line 335 of file messages_robocup_ssl_geometry.pb.h.
::google::protobuf::internal::ArenaStringPtr SSL_FieldLineSegment::name_ private
Definition at line 356 of file messages_robocup_ssl_geometry.pb.h.
::Vector2f* SSL_FieldLineSegment::p1_ private
Definition at line 357 of file messages_robocup_ssl_geometry.pb.h.
::Vector2f* SSL_FieldLineSegment::p2_ private
Definition at line 358 of file messages_robocup_ssl_geometry.pb.h.
float SSL_FieldLineSegment::thickness_ private
Definition at line 359 of file messages_robocup_ssl_geometry.pb.h.
The documentation for this class was generated from the following file:
ssl-vision/build/messages_robocup_ssl_geometry.pb.h