Documentation: FieldFilter Class Reference
FieldFilter Class Reference
#include <field_filter.h>
Public Member Functions
FieldFilter ()
void update (const RoboCupField &field)
bool isInFieldOrPlayableBoundary (const vector2d &pos)
check whether a point is within the legal field or the boundary (but not the referee walking area)
bool isInFieldPlusThreshold (const vector2d &pos, double threshold)
check whether a point is within the legal field (excluding all boundary areas) plus some threshold
bool isInField (const vector2d &pos)
check whether a point is within the legal field (excluding all boundary areas)
bool isFarInGoal (const vector2d &pos)
Protected Attributes
double half_field_width
double half_field_length
double half_goal_width
double goal_depth
double boundary_width
Detailed Description
Definition at line 34 of file field_filter.h.
Constructor & Destructor Documentation
FieldFilter::FieldFilter () inline
Definition at line 43 of file field_filter.h.
   {
     half_field_width = 0.0;
     half_field_length = 0.0;
     half_goal_width = 0.0;
     goal_depth = 0.0;
     boundary_width = 0.0;
   }
Member Function Documentation
bool FieldFilter::isFarInGoal (const vector2d & pos) inline
checks whether a point is very far in the goal (more than half-way) this is mostly used for vision filtering
Definition at line 78 of file field_filter.h.
References GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
Referenced by PluginDetectBalls::process().
{
     return (fabs(pos.y) < half_goal_width &&
             fabs(pos.x) > half_field_length + (goal_depth/2));
   }
bool FieldFilter::isInField (const vector2d & pos) inline
check whether a point is within the legal field (excluding all boundary areas)
Definition at line 72 of file field_filter.h.
References GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
{
     return (fabs(pos.x) <= half_field_length && fabs(pos.y) <= half_field_width);
   }
bool FieldFilter::isInFieldOrPlayableBoundary (const vector2d & pos) inline
check whether a point is within the legal field or the boundary (but not the referee walking area)
Definition at line 61 of file field_filter.h.
References GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
Referenced by CMPattern::TeamDetector::findRobotsByModel(), and CMPattern::TeamDetector::findRobotsByTeamMarkerOnly().
{
     return (fabs(pos.x) <= (half_field_length+boundary_width) &&
             fabs(pos.y) <= (half_field_width+boundary_width));
   }
bool FieldFilter::isInFieldPlusThreshold (const vector2d & pos, double threshold) inline
check whether a point is within the legal field (excluding all boundary areas) plus some threshold
Definition at line 67 of file field_filter.h.
References GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
Referenced by PluginDetectBalls::process().
{
     return (fabs(pos.x) <= (half_field_length+threshold) &&  fabs(pos.y) <= (half_field_width+threshold));
   }
void FieldFilter::update (const RoboCupField & field) inline
Definition at line 52 of file field_filter.h.
References RoboCupField::boundary_width, RoboCupField::field_length, RoboCupField::field_width, VarTypes::VarDoubleVal::getDouble(), RoboCupField::goal_depth, and RoboCupField::goal_width.
Referenced by CMPattern::TeamDetector::init(), and PluginDetectBalls::process().
{
     half_field_width = 0.5 * field.field_width->getDouble();
     half_field_length = 0.5 * field.field_length->getDouble();
     half_goal_width = field.goal_width->getDouble();
     goal_depth = field.goal_depth->getDouble();
     boundary_width = field.boundary_width->getDouble();
   }
Field Documentation
double FieldFilter::boundary_width protected
Definition at line 41 of file field_filter.h.
double FieldFilter::goal_depth protected
Definition at line 40 of file field_filter.h.
double FieldFilter::half_field_length protected
Definition at line 38 of file field_filter.h.
double FieldFilter::half_field_width protected
Definition at line 37 of file field_filter.h.
double FieldFilter::half_goal_width protected
Definition at line 39 of file field_filter.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/field_filter.h