Documentation: Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log Class Reference
Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log Class Reference
Data Structures
class Builder
Public Member Functions
Refbox_Log getDefaultInstanceForType ()
java.util.List< MessagesRobocupSslRefboxLog.Log_Frame > getLogList ()
java.util.List<?extends MessagesRobocupSslRefboxLog.Log_FrameOrBuilder > getLogOrBuilderList ()
int getLogCount ()
MessagesRobocupSslRefboxLog.Log_Frame getLog (int index)
MessagesRobocupSslRefboxLog.Log_FrameOrBuilder getLogOrBuilder (int index)
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static Refbox_Log getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslRefboxLog.Refbox_Log parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslRefboxLog.Refbox_Log parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (MessagesRobocupSslRefboxLog.Refbox_Log prototype)
Static Public Attributes
static final int LOG_FIELD_NUMBER = 1
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
Refbox_Log (Builder builder)
Refbox_Log (boolean noInit)
void initFields ()
Private Attributes
java.util.List< MessagesRobocupSslRefboxLog.Log_Frame > log_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final Refbox_Log defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 566 of file MessagesRobocupSslRefboxLog.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Refbox_Log (Builder builder) inline private
Definition at line 570 of file MessagesRobocupSslRefboxLog.java.
{
       super(builder);
     }
Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Refbox_Log (boolean noInit) inline private
Definition at line 573 of file MessagesRobocupSslRefboxLog.java.
 {}
Member Function Documentation
static Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getDefaultInstance () inline static
Definition at line 576 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getDefaultInstanceForType(), and Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.mergeFrom().
{
       return defaultInstance;
     }
Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getDefaultInstanceForType () inline
Definition at line 580 of file MessagesRobocupSslRefboxLog.java.
{
       return defaultInstance;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getDescriptor () inline static
Definition at line 585 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_descriptor.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getDescriptorForType().
{
       return MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_descriptor;
     }
MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getLog (int index) inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Refbox_LogOrBuilder.
Definition at line 607 of file MessagesRobocupSslRefboxLog.java.
{
       return log_.get(index);
     }
int Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getLogCount () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Refbox_LogOrBuilder.
Definition at line 604 of file MessagesRobocupSslRefboxLog.java.
{
       return log_.size();
     }
java.util.List<MessagesRobocupSslRefboxLog.Log_Frame> Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getLogList () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Refbox_LogOrBuilder.
Definition at line 597 of file MessagesRobocupSslRefboxLog.java.
{
       return log_;
     }
MessagesRobocupSslRefboxLog.Log_FrameOrBuilder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getLogOrBuilder (int index) inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Refbox_LogOrBuilder.
Definition at line 610 of file MessagesRobocupSslRefboxLog.java.
                    {
       return log_.get(index);
     }
java.util.List<? extends MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getLogOrBuilderList () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Refbox_LogOrBuilder.
Definition at line 601 of file MessagesRobocupSslRefboxLog.java.
{
       return log_;
     }
int Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getSerializedSize () inline
Definition at line 643 of file MessagesRobocupSslRefboxLog.java.
References velocity.pid_.i.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       for (int i = 0; i < log_.size(); i++) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(1, log_.get(i));
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
void Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.initFields () inline private
Definition at line 615 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getLogFieldBuilder().
{
       log_ = java.util.Collections.emptyList();
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.internalGetFieldAccessorTable () inline protected
Definition at line 590 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_fieldAccessorTable.
{
       return MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_fieldAccessorTable;
     }
final boolean Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.isInitialized () inline
Definition at line 619 of file MessagesRobocupSslRefboxLog.java.
References velocity.pid_.i.
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       for (int i = 0; i < getLogCount(); i++) {
         if (!getLog(i).isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.newBuilder () inline static
Definition at line 731 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.create().
 { return Builder.create(); }
static Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.newBuilder (MessagesRobocupSslRefboxLog.Refbox_Log prototype) inline static
Definition at line 733 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.newBuilderForType () inline
Definition at line 732 of file MessagesRobocupSslRefboxLog.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 739 of file MessagesRobocupSslRefboxLog.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 698 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 707 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 664 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 669 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 676 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 680 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 687 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 691 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 718 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 723 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.toBuilder () inline
Definition at line 736 of file MessagesRobocupSslRefboxLog.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 659 of file MessagesRobocupSslRefboxLog.java.
{
       return super.writeReplace();
     }
void Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 633 of file MessagesRobocupSslRefboxLog.java.
References velocity.pid_.i.
{
       getSerializedSize();
       for (int i = 0; i < log_.size(); i++) {
         output.writeMessage(1, log_.get(i));
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
final Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.defaultInstance static private
Definition at line 575 of file MessagesRobocupSslRefboxLog.java.
java.util.List<MessagesRobocupSslRefboxLog.Log_Frame> Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.log_ private
Definition at line 596 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.buildPartial().
final int Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.LOG_FIELD_NUMBER = 1 static
Definition at line 595 of file MessagesRobocupSslRefboxLog.java.
byte Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.memoizedIsInitialized = -1 private
Definition at line 618 of file MessagesRobocupSslRefboxLog.java.
int Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.memoizedSerializedSize = -1 private
Definition at line 642 of file MessagesRobocupSslRefboxLog.java.
final long Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.serialVersionUID = 0L static private
Definition at line 657 of file MessagesRobocupSslRefboxLog.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslRefboxLog.java