Documentation: CaptureThread Class Reference
CaptureThread Class Reference
A thread for capturing and processing video data.
#include <capture_thread.h>
Public Slots
bool init ()
bool stop ()
bool reset ()
void refresh ()
void selectCaptureMethod ()
Public Member Functions
void setFrameBuffer (FrameBuffer *_rb)
FrameBuffer * getFrameBuffer () const
void setStack (VisionStack *_stack)
VisionStack * getStack () const
void kill ()
VarList * getSettings ()
void setAffinityManager (AffinityManager *_affinity)
CaptureThread (int cam_id)
~CaptureThread ()
virtual void run ()
Protected Attributes
QMutex stack_mutex
QMutex capture_mutex
VisionStack * stack
FrameCounter * counter
CaptureInterface * capture
CaptureInterface * captureDC1394
CaptureInterface * captureV4L
CaptureInterface * captureBlueFox2
CaptureInterface * captureFlycap
CaptureInterface * captureFiles
CaptureInterface * captureGenerator
AffinityManager * affinity
FrameBuffer * rb
bool _kill
int camId
VarList * settings
VarList * dc1394
VarList * v4l
VarList * bluefox2
VarList * flycap
VarList * generator
VarList * fromfile
VarList * control
VarTrigger * c_start
VarTrigger * c_stop
VarTrigger * c_reset
VarTrigger * c_refresh
VarBool * c_auto_refresh
VarStringEnum * captureModule
Timer timer
Detailed Description
A thread for capturing and processing video data.
Author
Stefan Zickler, (C) 2008
Definition at line 50 of file capture_thread.h.
Constructor & Destructor Documentation
CaptureThread::CaptureThread (int cam_id)
Definition at line 24 of file capture_thread.cpp.
References _kill, VarTypes::VarList::addChild(), VarTypes::VarType::addFlags(), VarTypes::VarStringEnum::addItem(), affinity, bluefox2, c_auto_refresh, c_refresh, c_reset, c_start, c_stop, camId, capture, captureBlueFox2, captureDC1394, captureFiles, captureFlycap, captureGenerator, captureModule, captureV4L, control, counter, dc1394, flycap, fromfile, generator, init(), rb, refresh(), reset(), selectCaptureMethod(), settings, stack, stop(), v4l, VarTypes::VARTYPE_FLAG_AUTO_EXPAND_TREE, VarTypes::VARTYPE_FLAG_NOLOAD_ENUM_CHILDREN, and VarTypes::VARTYPE_FLAG_READONLY.
 {
   camId=cam_id;
   affinity=0;
   settings=new VarList("Image Capture");
   settings->addChild( (VarType*) (control= new VarList("Capture Control")));
   control->addChild( (VarType*) (c_start  = new VarTrigger("start capture","Start")));
   control->addChild( (VarType*) (c_stop   = new VarTrigger("stop capture","Stop")));
   control->addChild( (VarType*) (c_reset  = new VarTrigger("reset bus","Reset")));
   control->addChild( (VarType*) (c_auto_refresh= new VarBool("auto refresh params",true)));
   control->addChild( (VarType*) (c_refresh= new VarTrigger("re-read params","Refresh")));
   control->addChild( (VarType*) (captureModule= new VarStringEnum("Capture Module","DC 1394")));
   captureModule->addFlags(VARTYPE_FLAG_NOLOAD_ENUM_CHILDREN);
   captureModule->addItem("DC 1394");
   captureModule->addItem("Video 4 Linux");
   captureModule->addItem("Read from files");
   captureModule->addItem("Generator");
   settings->addChild( (VarType*) (dc1394 = new VarList("DC1394")));
   settings->addChild( (VarType*) (v4l = new VarList("Video 4 Linux")));
   settings->addChild( (VarType*) (fromfile = new VarList("Read from files")));
   settings->addChild( (VarType*) (generator = new VarList("Generator")));
   settings->addFlags( VARTYPE_FLAG_AUTO_EXPAND_TREE );
   c_stop->addFlags( VARTYPE_FLAG_READONLY );
   c_refresh->addFlags( VARTYPE_FLAG_READONLY );
   connect(c_start,SIGNAL(wasEdited(VarType *)),this,SLOT(init()));
   connect(c_stop,SIGNAL(wasEdited(VarType *)),this,SLOT(stop()));
   connect(c_reset,SIGNAL(wasEdited(VarType *)),this,SLOT(reset()));
   connect(c_refresh,SIGNAL(wasEdited(VarType *)),this,SLOT(refresh()));
   connect(captureModule,SIGNAL(hasChanged(VarType *)),this,SLOT(selectCaptureMethod()));
   stack = 0;
   counter=new FrameCounter();
   capture=0;
   captureDC1394 = new CaptureDC1394v2(dc1394,camId);
   captureFiles = new CaptureFromFile(fromfile);
   captureGenerator = new CaptureGenerator(generator);
   captureV4L = new CaptureV4L(v4l,camId);
 #ifdef FLYCAP
   captureModule->addItem("Flycapture");
   settings->addChild( (VarType*) (flycap = new VarList("Flycapture")));
   captureFlycap = new CaptureFlycap(flycap, camId);
 #endif
 #ifdef MVIMPACT
   captureModule->addItem("BlueFox2");
   settings->addChild( (VarType*) (bluefox2 = new VarList("BlueFox2")));
   captureBlueFox2 = new CaptureBlueFox2(bluefox2,camId);
 #endif
   selectCaptureMethod();
   _kill =false;
   rb=0;
 }
CaptureThread::~CaptureThread ()
Definition at line 93 of file capture_thread.cpp.
References captureBlueFox2, captureDC1394, captureFiles, captureFlycap, captureGenerator, captureV4L, and counter.
 {
   delete captureDC1394;
   delete captureV4L;
   delete captureFiles;
   delete captureGenerator;
   delete counter;
 #ifdef FLYCAP
   delete captureFlycap;
 #endif
 #ifdef MVIMPACT
   delete captureBlueFox2;
 #endif
 }
Member Function Documentation
FrameBuffer * CaptureThread::getFrameBuffer () const
Definition at line 114 of file capture_thread.cpp.
References rb.
{
   return rb;
 }
VarList * CaptureThread::getSettings ()
Definition at line 89 of file capture_thread.cpp.
References settings.
{
   return settings;
 }
VisionStack * CaptureThread::getStack () const
Definition at line 118 of file capture_thread.cpp.
References stack.
{
   return stack;
 }
bool CaptureThread::init () slot
Definition at line 163 of file capture_thread.cpp.
References VarTypes::VarType::addFlags(), c_refresh, c_reset, c_start, c_stop, capture, capture_mutex, VarTypes::VarType::removeFlags(), CaptureInterface::startCapture(), and VarTypes::VARTYPE_FLAG_READONLY.
Referenced by CaptureThread(), and MainWindow::MainWindow().
{
   capture_mutex.lock();
   bool res = capture->startCapture();
   if (res==true) {
     c_start->addFlags( VARTYPE_FLAG_READONLY );
     c_reset->addFlags( VARTYPE_FLAG_READONLY );
     c_refresh->removeFlags( VARTYPE_FLAG_READONLY );
     c_stop->removeFlags( VARTYPE_FLAG_READONLY );
   }
   capture_mutex.unlock();
   return res;
 }
void CaptureThread::kill ()
Definition at line 156 of file capture_thread.cpp.
References _kill.
Referenced by MultiVisionStack::stop().
{
  _kill=true;
   while(isRunning()) {
     usleep(100);
   }
 }
void CaptureThread::refresh () slot
Definition at line 196 of file capture_thread.cpp.
References capture, capture_mutex, and CaptureInterface::readAllParameterValues().
Referenced by CaptureThread().
{
   capture_mutex.lock();
   capture->readAllParameterValues();
   capture_mutex.unlock();
 }
bool CaptureThread::reset () slot
Definition at line 189 of file capture_thread.cpp.
References capture, capture_mutex, and CaptureInterface::resetBus().
Referenced by CaptureThread().
{
   capture_mutex.lock();
   bool res = capture->resetBus();
   capture_mutex.unlock();
   return res;
 }
void CaptureThread::run () virtual
Definition at line 203 of file capture_thread.cpp.
References _kill, affinity, c_auto_refresh, FrameData::cam_id, camId, capture, capture_mutex, CaptureInterface::copyAndConvertFrame(), FrameCounter::count(), counter, AffinityManager::demandCore(), CaptureStats::fps_capture, FrameDataMap::get(), VarTypes::VarBoolVal::getBool(), FrameCounter::getFPS(), CaptureInterface::getFrame(), RawImage::getTime(), FrameCounter::getTotal(), FrameDataMap::insert(), CaptureInterface::isCapturing(), FrameData::map, FrameData::number, VisionStack::postProcess(), VisionStack::process(), rb, CaptureInterface::readAllParameterValues(), CaptureInterface::releaseFrame(), stack, stack_mutex, CaptureInterface::stopCapture(), FrameData::time, CaptureStats::total, VisionStack::updateTimingStatistics(), and FrameData::video.
{
     CaptureStats * stats;
     bool changed;
     if (affinity!=0) {
       affinity->demandCore(camId);
     }
     while(true) {
       if (rb!=0) {
         int idx=rb->curWrite();
         FrameData * d=rb->getPointer(idx);
         if ((stats=(CaptureStats *)d->map.get("capture_stats")) == 0) {
           stats=(CaptureStats *)d->map.insert("capture_stats",new CaptureStats());
         }
         capture_mutex.lock();
         if ((capture != 0) && (capture->isCapturing())) {
           RawImage pic_raw=capture->getFrame();
           d->time=pic_raw.getTime();
           bool bSuccess = capture->copyAndConvertFrame( pic_raw,d->video);
           capture_mutex.unlock();
           if (bSuccess) {           //only on a good frame read do we proceed
               counter->count();
               stats->total=d->number=counter->getTotal();
               d->cam_id=camId;
               stats->fps_capture=counter->getFPS(changed);
               stack_mutex.lock();
               if (stack!=0) {
                 stack->process(d);
                 stack->postProcess(d);
               }
               stack_mutex.unlock();
               rb->nextWrite(true);
               if (changed) {
                 if (c_auto_refresh->getBool()==true) {
                   capture_mutex.lock();
                   if ((capture != 0) && (capture->isCapturing())) capture->readAllParameterValues();
                   capture_mutex.unlock();
                 }
                 stack_mutex.lock();
                 stack->updateTimingStatistics();
                 stack_mutex.unlock();
               }
               capture_mutex.lock();
               if ((capture != 0) && (capture->isCapturing())) {
                 capture->releaseFrame();
               }
               capture_mutex.unlock();
           }
         } else {
           stats->total=d->number=counter->getTotal();
           stats->fps_capture=counter->getFPS(changed);
           //we are not capturing...chill this thread out...
           capture_mutex.unlock();
           usleep(5000);
         }
         if (_kill) {
           capture_mutex.lock();
           if(capture != 0) {
             capture->stopCapture();
             //make sure to read latest params from camera to be saved to file...
             if (capture->isCapturing()) capture->readAllParameterValues();
           }
           capture_mutex.unlock();
           return;
         }
       }
     }
 }
void CaptureThread::selectCaptureMethod () slot
Definition at line 122 of file capture_thread.cpp.
References capture, capture_mutex, captureBlueFox2, captureDC1394, captureFiles, captureFlycap, captureGenerator, captureModule, captureV4L, VarTypes::VarStringEnum::getString(), CaptureInterface::isCapturing(), and stop().
Referenced by CaptureThread().
{
   capture_mutex.lock();
   CaptureInterface * old_capture=capture;
   CaptureInterface * new_capture=0;
   if(captureModule->getString() == "Read from files") {
     new_capture = captureFiles;
   } else if(captureModule->getString() == "Generator") {
     new_capture = captureGenerator;
 #ifdef MVIMPACT
   } else if(captureModule->getString() == "BlueFox2") {
     new_capture = captureBlueFox2;
 #endif
   } else if(captureModule->getString() == "Video 4 Linux") {
     new_capture = captureV4L;
   } else if(captureModule->getString() == "DC 1394") {
     new_capture = captureDC1394;
 #ifdef FLYCAP
   } else if(captureModule->getString() == "Flycapture") {
     new_capture = captureFlycap;
 #endif
   }
   if (old_capture!=0 && new_capture!=old_capture && old_capture->isCapturing()) {
     capture_mutex.unlock();
     stop();
     capture_mutex.lock();
     capture=new_capture;
     capture_mutex.unlock();
     return;
   }
   capture=new_capture;
   capture_mutex.unlock();
 }
void CaptureThread::setAffinityManager (AffinityManager * _affinity)
Definition at line 79 of file capture_thread.cpp.
References affinity.
{
   affinity=_affinity;
 }
void CaptureThread::setFrameBuffer (FrameBuffer * _rb)
Definition at line 110 of file capture_thread.cpp.
References rb.
{
   rb=_rb;
 }
void CaptureThread::setStack (VisionStack * _stack)
Definition at line 83 of file capture_thread.cpp.
References stack, and stack_mutex.
{
   stack_mutex.lock();
   stack=_stack;
   stack_mutex.unlock();
 }
bool CaptureThread::stop () slot
Definition at line 176 of file capture_thread.cpp.
References VarTypes::VarType::addFlags(), c_refresh, c_reset, c_start, c_stop, capture, capture_mutex, VarTypes::VarType::removeFlags(), CaptureInterface::stopCapture(), and VarTypes::VARTYPE_FLAG_READONLY.
Referenced by CaptureThread(), and selectCaptureMethod().
{
   capture_mutex.lock();
   bool res = capture->stopCapture();
   if (res==true) {
     c_stop->addFlags( VARTYPE_FLAG_READONLY );
     c_refresh->addFlags( VARTYPE_FLAG_READONLY );
     c_start->removeFlags( VARTYPE_FLAG_READONLY );
     c_reset->removeFlags( VARTYPE_FLAG_READONLY );
   }
   capture_mutex.unlock();
   return res;
 }
Field Documentation
bool CaptureThread::_kill protected
Definition at line 67 of file capture_thread.h.
Referenced by CaptureThread(), kill(), and run().
AffinityManager* CaptureThread::affinity protected
Definition at line 65 of file capture_thread.h.
Referenced by CaptureThread(), run(), and setAffinityManager().
VarList* CaptureThread::bluefox2 protected
Definition at line 72 of file capture_thread.h.
Referenced by CaptureThread().
VarBool* CaptureThread::c_auto_refresh protected
Definition at line 81 of file capture_thread.h.
Referenced by CaptureThread(), and run().
VarTrigger* CaptureThread::c_refresh protected
Definition at line 80 of file capture_thread.h.
Referenced by CaptureThread(), init(), and stop().
VarTrigger* CaptureThread::c_reset protected
Definition at line 79 of file capture_thread.h.
Referenced by CaptureThread(), init(), and stop().
VarTrigger* CaptureThread::c_start protected
Definition at line 77 of file capture_thread.h.
Referenced by CaptureThread(), init(), and stop().
VarTrigger* CaptureThread::c_stop protected
Definition at line 78 of file capture_thread.h.
Referenced by CaptureThread(), init(), and stop().
int CaptureThread::camId protected
Definition at line 68 of file capture_thread.h.
Referenced by CaptureThread(), and run().
CaptureInterface* CaptureThread::capture protected
Definition at line 58 of file capture_thread.h.
Referenced by CaptureThread(), init(), refresh(), reset(), run(), selectCaptureMethod(), and stop().
QMutex CaptureThread::capture_mutex protected
Definition at line 55 of file capture_thread.h.
Referenced by init(), refresh(), reset(), run(), selectCaptureMethod(), and stop().
CaptureInterface* CaptureThread::captureBlueFox2 protected
Definition at line 61 of file capture_thread.h.
Referenced by CaptureThread(), selectCaptureMethod(), and ~CaptureThread().
CaptureInterface* CaptureThread::captureDC1394 protected
Definition at line 59 of file capture_thread.h.
Referenced by CaptureThread(), selectCaptureMethod(), and ~CaptureThread().
CaptureInterface* CaptureThread::captureFiles protected
Definition at line 63 of file capture_thread.h.
Referenced by CaptureThread(), selectCaptureMethod(), and ~CaptureThread().
CaptureInterface* CaptureThread::captureFlycap protected
Definition at line 62 of file capture_thread.h.
Referenced by CaptureThread(), selectCaptureMethod(), and ~CaptureThread().
CaptureInterface* CaptureThread::captureGenerator protected
Definition at line 64 of file capture_thread.h.
Referenced by CaptureThread(), selectCaptureMethod(), and ~CaptureThread().
VarStringEnum* CaptureThread::captureModule protected
Definition at line 82 of file capture_thread.h.
Referenced by CaptureThread(), and selectCaptureMethod().
CaptureInterface* CaptureThread::captureV4L protected
Definition at line 60 of file capture_thread.h.
Referenced by CaptureThread(), selectCaptureMethod(), and ~CaptureThread().
VarList* CaptureThread::control protected
Definition at line 76 of file capture_thread.h.
Referenced by CaptureThread().
FrameCounter* CaptureThread::counter protected
Definition at line 57 of file capture_thread.h.
Referenced by CaptureThread(), run(), and ~CaptureThread().
VarList* CaptureThread::dc1394 protected
Definition at line 70 of file capture_thread.h.
Referenced by CaptureThread().
VarList* CaptureThread::flycap protected
Definition at line 73 of file capture_thread.h.
Referenced by CaptureThread().
VarList* CaptureThread::fromfile protected
Definition at line 75 of file capture_thread.h.
Referenced by CaptureThread().
VarList* CaptureThread::generator protected
Definition at line 74 of file capture_thread.h.
Referenced by CaptureThread().
FrameBuffer* CaptureThread::rb protected
Definition at line 66 of file capture_thread.h.
Referenced by CaptureThread(), getFrameBuffer(), run(), and setFrameBuffer().
VarList* CaptureThread::settings protected
Definition at line 69 of file capture_thread.h.
Referenced by CaptureThread(), and getSettings().
VisionStack* CaptureThread::stack protected
Definition at line 56 of file capture_thread.h.
Referenced by CaptureThread(), getStack(), run(), and setStack().
QMutex CaptureThread::stack_mutex protected
Definition at line 54 of file capture_thread.h.
Referenced by run(), and setStack().
Timer CaptureThread::timer protected
Definition at line 83 of file capture_thread.h.
VarList* CaptureThread::v4l protected
Definition at line 71 of file capture_thread.h.
Referenced by CaptureThread().
The documentation for this class was generated from the following files:
ssl-vision/src/app/capture_thread.h
ssl-vision/src/app/capture_thread.cpp