Documentation: VarTypes::VarDouble Class Reference
VarTypes::VarDouble Class Reference
A Vartype for storing double precision floating points.
#include <VarDouble.h>
Public Member Functions
virtual double getMin () const
virtual double getMax () const
virtual bool hasMin () const
virtual bool hasMax () const
virtual void setMin (double minval)
virtual void setMax (double maxval)
virtual void unsetMin ()
virtual void unsetMax ()
virtual bool setDouble (double val)
set the value of this node to val.
VarDouble (string name="", double default_val=0, double min_val=(-DBL_MAX), double max_val=DBL_MAX)
virtual ~VarDouble ()
virtual void resetToDefault ()
virtual void setDefault (double val)
virtual QWidget * createEditor (const VarItemDelegate *delegate, QWidget *parent, const QStyleOptionViewItem &option)
virtual void setEditorData (const VarItemDelegate *delegate, QWidget *editor) const
virtual void setModelData (const VarItemDelegate *delegate, QWidget *editor)
Public Member Functions inherited from VarTypes::VarTypeTemplate< VarDoubleVal >
VarTypeTemplate (string name="")
Public Member Functions inherited from VarTypes::VarType
VarType (string name="")
virtual ~VarType ()
virtual vector< VarType * > getChildren () const
virtual void deleteAllChildren ()
virtual void setName (string name)
Set the string label of this node.
virtual string getName () const
Get the string label of this node.
virtual VarTypeFlag getFlags () const
virtual void setFlags (VarTypeFlag f)
virtual void addFlags (VarTypeFlag f)
virtual void removeFlags (VarTypeFlag f)
virtual bool areFlagsSet (VarTypeFlag f) const
VarType * findChild (string label) const
void writeXML (XMLNode &parent, bool blind_append=true)
Write the contents of this VarType node to an XMLNode.
void readXML (XMLNode &us)
Let this VarType node load the contents of an XMLNode.
virtual QSize sizeHint (const VarItemDelegate *delegate, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void paint (const VarItemDelegate *delegate, QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
Public Member Functions inherited from VarTypes::VarDoubleVal
VarDoubleVal (double default_val=0)
virtual VarVal * clone () const
virtual void printdebug () const
virtual VarTypeId getType () const
virtual string getString () const
virtual double getDouble () const
get the value of this data-type
virtual int getInt () const
virtual bool getBool () const
will return true if the value is 1.0, or false otherwise
virtual bool setString (const string &val)
virtual bool setInt (int val)
virtual bool setBool (bool val)
virtual bool hasValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Protected Member Functions
virtual void updateAttributes (XMLNode &us) const
virtual void readAttributes (XMLNode &us)
Protected Member Functions inherited from VarTypes::VarType
virtual void lock () const
virtual void unlock () const
virtual void changed ()
virtual void updateText (XMLNode &us) const
virtual void updateChildren (XMLNode &us) const
virtual void readText (XMLNode &us)
virtual void readChildren (XMLNode &us)
virtual void loadExternal ()
Protected Attributes
SafeVarVal< VarDoubleVal > _def
double _min
double _max
Protected Attributes inherited from VarTypes::VarType
QMutex * _mutex
VarTypeFlag _flags
string _name
Protected Attributes inherited from VarTypes::VarDoubleVal
double _val
Additional Inherited Members
Public Slots inherited from VarTypes::VarType
void mvcEditCompleted ()
A slot to receive signals from a model-view system that editing of this item was just completed.
Signals inherited from VarTypes::VarType
void hasChanged (VarType *)
void wasEdited (VarType *)
void XMLwasRead (VarType *)
This signal is triggered if data was written from an xml node.
void XMLwasWritten (VarType *)
This signal is triggered if data was written to an xml node.
Static Public Member Functions inherited from VarTypes::VarType
static void deleteAllVarChildren (XMLNode &node)
Clear an XMLNode's list of children.
static vector< VarType * > readChildrenHelper (XMLNode &parent, vector< VarType * > existing_children, bool only_update_existing, bool blind_append)
A helper function to read a list of children from XML and convert it to a vector of VarType nodes.
Static Protected Member Functions inherited from VarTypes::VarType
static string fixString (const char *cst)
static string intToString (int val)
static string doubleToString (double val)
static XMLNode findOrAppendChild (XMLNode &parent, string key, string val)
Detailed Description
A Vartype for storing double precision floating points.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 37 of file VarDouble.h.
Constructor & Destructor Documentation
VarTypes::VarDouble::VarDouble (string name = "", double default_val = 0, double min_val = (-DBL_MAX), double max_val = DBL_MAX) inline
Definition at line 108 of file VarDouble.h.
References VarTypes::VarType::changed(), setDefault(), setMax(), and setMin().
                                                                                                        : VarDoubleVal(default_val), VarTypeTemplate<VarDoubleVal>(name)
     {
       setMin(min_val);
       setMax(max_val);
       setDefault(default_val);
       changed();
     }
virtual VarTypes::VarDouble::~VarDouble () inline virtual
Definition at line 116 of file VarDouble.h.
 {}
Member Function Documentation
virtual QWidget* VarTypes::VarDouble::createEditor (const VarItemDelegate * delegate, QWidget * parent, const QStyleOptionViewItem & option) inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 169 of file VarDouble.h.
{
     //TODO: hookup editor changes on press-enter and on spin:
     (void)delegate;
     (void)parent;
     (void)option;
     QDoubleSpinBox * w = new QDoubleSpinBox(parent);
     //uncomment the following line for instant updates:
     //connect((const QObject *)w,SIGNAL(valueChanged ( double )),(const QObject *)delegate,SLOT(editorChangeEvent()));
     return w;
   }
virtual double VarTypes::VarDouble::getMax () const inline virtual
get the maximum accepted value if this data-type has a limited range
See also
setMax(...)
hasMax()
unsetMax()
Definition at line 55 of file VarDouble.h.
References _max, VarTypes::VarType::lock(), VarTypes::VarType::unlock(), and v.
Referenced by CameraCalibrationWidget::CameraCalibrationWidget(), setDouble(), setEditorData(), and updateAttributes().
 { lock(); double v=_max; unlock(); return v; }
virtual double VarTypes::VarDouble::getMin () const inline virtual
get the minimum accepted value if this data-type has a limited range
See also
setMin(...)
hasMin()
unsetMin()
Definition at line 49 of file VarDouble.h.
References _min, VarTypes::VarType::lock(), VarTypes::VarType::unlock(), and v.
Referenced by CameraCalibrationWidget::CameraCalibrationWidget(), setDouble(), setEditorData(), and updateAttributes().
 { lock(); double v=_min; unlock(); return v; }
virtual bool VarTypes::VarDouble::hasMax () const inline virtual
check whether this data type has a limited maximum value
See also
getMax(...)
setMax(...)
unsetMax()
Definition at line 67 of file VarDouble.h.
References VarTypes::VarType::lock(), VarTypes::VarType::unlock(), and v.
Referenced by setDouble(), and updateAttributes().
 { lock(); bool v= (_max != DBL_MAX); unlock(); return v; }
virtual bool VarTypes::VarDouble::hasMin () const inline virtual
check whether this data type has a limited minimum value
See also
getMin(...)
setMin(...)
unsetMin()
Definition at line 61 of file VarDouble.h.
References VarTypes::VarType::lock(), VarTypes::VarType::unlock(), and v.
Referenced by setDouble(), and updateAttributes().
 { lock(); bool v= (_min != (-DBL_MAX)); unlock(); return v; }
virtual void VarTypes::VarDouble::readAttributes (XMLNode & us) inline protected virtual
Reimplemented from VarTypes::VarType.
Definition at line 145 of file VarDouble.h.
References VarTypes::VarType::fixString(), VarTypes::XMLNode::getAttribute(), setMax(), setMin(), unsetMax(), and unsetMin().
     {
       string s = fixString(us.getAttribute("minval"));
       if (s=="") {
         unsetMin();
       } else {
         double num=0; sscanf(s.c_str(),"%lf",&num);
         setMin(num);
       }
       s = fixString(us.getAttribute("maxval"));
       if (s=="") {
         unsetMax();
       } else {
         double num=0; sscanf(s.c_str(),"%lf",&num);
         setMax(num);
       }
     }
virtual void VarTypes::VarDouble::resetToDefault () inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 118 of file VarDouble.h.
References setDouble().
Referenced by CameraParameters::reset().
     {
       setDouble(_def.getDouble());
     }
virtual void VarTypes::VarDouble::setDefault (double val) inline virtual
Definition at line 123 of file VarDouble.h.
References VarTypes::VarType::changed().
Referenced by VarDouble().
     {
       _def.setDouble(val);
       changed();
     }
virtual bool VarTypes::VarDouble::setDouble (double val) inline virtual
set the value of this node to val.
Reimplemented from VarTypes::VarDoubleVal.
Definition at line 95 of file VarDouble.h.
References _max, _min, getMax(), getMin(), hasMax(), hasMin(), and VarTypes::VarDoubleVal::setDouble().
Referenced by CameraParameters::calibrate(), CameraCalibrationWidget::cameraheight_slider_changed(), CameraCalibrationWidget::distortion_slider_changed(), CameraParameters::fromProtoBuffer(), CameraCalibrationWidget::line_search_slider_changed(), PluginCameraCalibration::mouseMoveEvent(), CaptureDC1394v2::readParameterValues(), resetToDefault(), and setModelData().
     {
       double tmp;
       if (hasMin() && val < getMin()) {
         tmp=_min;
       } else if (hasMax() &&  val > getMax()) {
         tmp=_max;
       } else {
         tmp=val;
       }
       return VarDoubleVal::setDouble(tmp);
     };
virtual void VarTypes::VarDouble::setEditorData (const VarItemDelegate * delegate, QWidget * editor) const inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 179 of file VarDouble.h.
References VarTypes::VarDoubleVal::getDouble(), getMax(), and getMin().
{
     (void)delegate;
     QDoubleSpinBox * spin=(QDoubleSpinBox *) editor;
     spin->setDecimals(10);
     spin->setRange(getMin(),getMax() );
     spin->setValue(getDouble());
   }
virtual void VarTypes::VarDouble::setMax (double maxval) inline virtual
limit the maximum value of this parameter to a pre-set value
See also
getMax(...)
hasMax()
unsetMax()
Definition at line 79 of file VarDouble.h.
References VarTypes::VarType::changed(), VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
Referenced by readAttributes(), CaptureDC1394v2::readParameterProperty(), and VarDouble().
 { lock(); _max=maxval; unlock(); changed(); }
virtual void VarTypes::VarDouble::setMin (double minval) inline virtual
limit the minumum value of this parameter to a pre-set value
See also
getMin(...)
hasMin()
unsetMin()
Definition at line 73 of file VarDouble.h.
References VarTypes::VarType::changed(), VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
Referenced by readAttributes(), CaptureDC1394v2::readParameterProperty(), and VarDouble().
 { lock(); _min=minval; unlock(); changed(); }
virtual void VarTypes::VarDouble::setModelData (const VarItemDelegate * delegate, QWidget * editor) inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 186 of file VarDouble.h.
References VarTypes::VarType::mvcEditCompleted(), and setDouble().
{
     (void)delegate;
     QDoubleSpinBox * spin=(QDoubleSpinBox *) editor;
     if (setDouble(spin->value())) mvcEditCompleted();
   }
virtual void VarTypes::VarDouble::unsetMax () inline virtual
unset any previous limit of maximum value of this parameter
See also
getMax(...)
setMax(...)
hasMax()
Definition at line 91 of file VarDouble.h.
References VarTypes::VarType::changed(), VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
Referenced by readAttributes().
 { lock(); _max=DBL_MAX; unlock(); changed(); }
virtual void VarTypes::VarDouble::unsetMin () inline virtual
unset any previous limit of minimum value of this parameter
See also
getMin(...)
setMin(...)
hasMin()
Definition at line 85 of file VarDouble.h.
References VarTypes::VarType::changed(), VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
Referenced by readAttributes().
 { lock(); _min=(-DBL_MAX); unlock(); changed(); }
virtual void VarTypes::VarDouble::updateAttributes (XMLNode & us) const inline protected virtual
Reimplemented from VarTypes::VarType.
Definition at line 131 of file VarDouble.h.
References VarTypes::VarType::doubleToString(), getMax(), getMin(), hasMax(), hasMin(), and VarTypes::XMLNode::updateAttribute().
     {
       if (hasMin()) {
         us.updateAttribute(doubleToString(getMin()).c_str(),"minval","minval");
       } else {
         us.updateAttribute("","minval","minval");
       }
       if (hasMax()) {
         us.updateAttribute(doubleToString(getMax()).c_str(),"maxval","maxval");
       } else {
         us.updateAttribute("","maxval","maxval");
       }
     }
Field Documentation
SafeVarVal<VarDoubleVal> VarTypes::VarDouble::_def protected
Definition at line 41 of file VarDouble.h.
double VarTypes::VarDouble::_max protected
Definition at line 43 of file VarDouble.h.
Referenced by getMax(), and setDouble().
double VarTypes::VarDouble::_min protected
Definition at line 42 of file VarDouble.h.
Referenced by getMin(), and setDouble().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/vartypes/primitives/VarDouble.h