Documentation: Timer Class Reference
Timer Class Reference
a basic timer class
#include <timer.h>
Public Member Functions
void start ()
void stop ()
void end ()
double time ()
double timeMSec ()
double timeUSec ()
double interval ()
double midtime ()
void start ()
void stop ()
void end ()
double time ()
double timeMSec ()
double timeUSec ()
double interval ()
double midtime ()
Private Attributes
timeval tv1
timeval tv2
Detailed Description
a basic timer class
Author
James R. Bruce, (C) 1999-2002
Definition at line 42 of file timer.h.
Member Function Documentation
void Timer::end () inline
Definition at line 47 of file timer.h.
References stop().
 {stop();}
void Timer::end () inline
Definition at line 47 of file timer.h.
References stop().
 {stop();}
double Timer::interval () inline
Definition at line 53 of file timer.h.
References t, time(), and tv2.
                    {
     double t;
     gettimeofday(&tv2,NULL);
     t = time();
     tv1 = tv2;
     return(t);
   }
double Timer::interval () inline
Definition at line 53 of file timer.h.
References t, time(), and tv2.
                    {
     double t;
     gettimeofday(&tv2,NULL);
     t = time();
     tv1 = tv2;
     return(t);
   }
double Timer::midtime () inline
Definition at line 60 of file timer.h.
References tv1, and tv2.
                    {
     timeval tmp;
     gettimeofday(&tmp,NULL);
     return((tmp.tv_sec - tv1.tv_sec) +
                         (tmp.tv_usec - tv1.tv_usec) * 1.0E-6);
   }
double Timer::midtime () inline
Definition at line 60 of file timer.h.
Referenced by FrameLimiter::init(), and FrameLimiter::waitForNextFrame().
                    {
     timeval tmp;
     gettimeofday(&tmp,NULL);
     return((tmp.tv_sec - tv1.tv_sec) +
                         (tmp.tv_usec - tv1.tv_usec) * 1.0E-6);
   }
void Timer::start () inline
Definition at line 45 of file timer.h.
 {gettimeofday(&tv1,NULL);}
void Timer::start () inline
Definition at line 45 of file timer.h.
Referenced by FunctionTimer::FunctionTimer(), and FrameLimiter::init().
 {gettimeofday(&tv1,NULL);}
void Timer::stop () inline
Definition at line 46 of file timer.h.
Referenced by end(), AccumulativeTimer::end(), CycleTimer::end(), and FunctionTimer::~FunctionTimer().
 {gettimeofday(&tv2,NULL);}
void Timer::stop () inline
Definition at line 46 of file timer.h.
 {gettimeofday(&tv2,NULL);}
double Timer::time () inline
Definition at line 48 of file timer.h.
Referenced by GetDate(), interval(), AccumulativeTimer::interval(), AccumulativeTimer::stop(), timeMSec(), AccumulativeTimer::timeMSec(), timeUSec(), and AccumulativeTimer::timeUSec().
                 {return((tv2.tv_sec - tv1.tv_sec) +
                         (tv2.tv_usec - tv1.tv_usec) * 1.0E-6);}
double Timer::time () inline
Definition at line 48 of file timer.h.
                 {return((tv2.tv_sec - tv1.tv_sec) +
                         (tv2.tv_usec - tv1.tv_usec) * 1.0E-6);}
double Timer::timeMSec () inline
Definition at line 50 of file timer.h.
References time().
 {return(time() * 1.0E3);}
double Timer::timeMSec () inline
Definition at line 50 of file timer.h.
References time().
Referenced by FunctionTimer::~FunctionTimer().
 {return(time() * 1.0E3);}
double Timer::timeUSec () inline
Definition at line 51 of file timer.h.
References time().
 {return(time() * 1.0E6);}
double Timer::timeUSec () inline
Definition at line 51 of file timer.h.
References time().
 {return(time() * 1.0E6);}
Field Documentation
timeval Timer::tv1 private
Definition at line 43 of file timer.h.
Referenced by midtime().
timeval Timer::tv2 private
Definition at line 43 of file timer.h.
Referenced by interval(), AccumulativeTimer::interval(), and midtime().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/timer.h