Documentation: CaptureBlueFox2 Class Reference
CaptureBlueFox2 Class Reference
A capture class for Matrix-Vision BlueFox2 cameras.
#include <capture_bluefox2.h>
Public Types
enum HDRMode {
HDR_MODE_OFF, HDR_MODE_FIXED0, HDR_MODE_FIXED1, HDR_MODE_FIXED2,
HDR_MODE_FIXED3, HDR_MODE_FIXED4, HDR_MODE_FIXED5
}
enum ColorTwistMode {
COLOR_TWIST_MODE_OFF, COLOR_TWIST_MODE_ADOBERGB_D50, COLOR_TWIST_MODE_SRGB_D50, COLOR_TWIST_MODE_WIDE_GAMUT_RGB_D50,
COLOR_TWIST_MODE_ADOBERGB_D65, COLOR_TWIST_MODE_SRGB_D65
}
Public Slots
void changed (VarType *group)
Public Member Functions
CaptureBlueFox2 (VarList *_settings=0, int default_camera_id=0, QObject *parent=0)
void mvc_connect (VarList *group)
~CaptureBlueFox2 ()
virtual bool startCapture ()
Initialize the interface and start capture.
virtual bool stopCapture ()
Stop Capture.
virtual bool isCapturing ()
virtual RawImage getFrame ()
virtual void releaseFrame ()
virtual bool resetBus ()
void readParameterValues (VarList *item)
void writeParameterValues (VarList *item)
virtual void readAllParameterValues ()
void writeAllParameterValues ()
virtual bool copyAndConvertFrame (const RawImage &src, RawImage &target)
virtual string getCaptureMethodName () const
Public Member Functions inherited from CaptureInterface
CaptureInterface (VarList *_settings=0)
virtual ~CaptureInterface ()
Static Public Member Functions
static HDRMode stringToHdrMode (const char *s)
static string hdrModeToString (HDRMode mode)
static ColorTwistMode stringToColorTwistMode (const char *s)
static string colorTwistModeToString (ColorTwistMode mode)
static TCameraPixelClock stringToPixelClock (const char *s)
static string pixelClockToString (TCameraPixelClock pxc)
Protected Attributes
QMutex mutex
bool is_capturing
VarInt * v_expose_us
VarBool * v_expose_overlapped
VarDouble * v_gain_db
VarStringEnum * v_hdr_mode
VarBool * v_mirror_top_down
VarBool * v_mirror_left_right
VarDouble * v_wb_red
VarDouble * v_wb_green
VarDouble * v_wb_blue
VarBool * v_sharpen
VarDouble * v_gamma
VarStringEnum * v_color_twist_mode
VarInt * v_aoi_width
VarInt * v_aoi_height
VarInt * v_aoi_left
VarInt * v_aoi_top
VarStringEnum * v_pixel_clock
VarInt * v_cam_bus
VarStringEnum * v_colorout
VarList * dcam_parameters
VarList * capture_settings
DeviceManager devMgr
Device * pDevice
FunctionInterface * pFI
CameraSettingsBlueFOX * pSettings
ImageProcessing * pImageProc
int lastRequestNr
unsigned int cam_id
ColorFormat capture_format
Additional Inherited Members
Data Fields inherited from CaptureInterface
VarList * settings
Detailed Description
A capture class for Matrix-Vision BlueFox2 cameras.
Author
Andre Ryll, (C) 2016
This class provides the ability to use and configure Matrix-Vision BlueFox2 cameras using the mvIMPACT driver.
Overall, it not only provides capture-abilities, but also full on-the-fly configuration abilities through the VarTypes system.
If you find your camera not working correctly, or discover a bug, please inform the author, as we are aiming for complete camera coverage.
Definition at line 64 of file capture_bluefox2.h.
Member Enumeration Documentation
enum CaptureBlueFox2::ColorTwistMode
Enumerator
COLOR_TWIST_MODE_OFF
COLOR_TWIST_MODE_ADOBERGB_D50
COLOR_TWIST_MODE_SRGB_D50
COLOR_TWIST_MODE_WIDE_GAMUT_RGB_D50
COLOR_TWIST_MODE_ADOBERGB_D65
COLOR_TWIST_MODE_SRGB_D65
Definition at line 127 of file capture_bluefox2.h.
   {
     COLOR_TWIST_MODE_OFF,
     COLOR_TWIST_MODE_ADOBERGB_D50,
     COLOR_TWIST_MODE_SRGB_D50,
     COLOR_TWIST_MODE_WIDE_GAMUT_RGB_D50,
     COLOR_TWIST_MODE_ADOBERGB_D65,
     COLOR_TWIST_MODE_SRGB_D65,
   };
enum CaptureBlueFox2::HDRMode
Enumerator
HDR_MODE_OFF
HDR_MODE_FIXED0
HDR_MODE_FIXED1
HDR_MODE_FIXED2
HDR_MODE_FIXED3
HDR_MODE_FIXED4
HDR_MODE_FIXED5
Definition at line 81 of file capture_bluefox2.h.
   {
     HDR_MODE_OFF,
     HDR_MODE_FIXED0,
     HDR_MODE_FIXED1,
     HDR_MODE_FIXED2,
     HDR_MODE_FIXED3,
     HDR_MODE_FIXED4,
     HDR_MODE_FIXED5,
   };
Constructor & Destructor Documentation
CaptureBlueFox2::CaptureBlueFox2 (VarList * _settings = 0, int default_camera_id = 0, QObject * parent = 0)
Definition at line 25 of file capture_bluefox2.cpp.
References VarTypes::VarList::addChild(), VarTypes::VarType::addFlags(), VarTypes::VarStringEnum::addItem(), cam_id, capture_settings, COLOR_RGB8, COLOR_TWIST_MODE_ADOBERGB_D50, COLOR_TWIST_MODE_ADOBERGB_D65, COLOR_TWIST_MODE_OFF, COLOR_TWIST_MODE_SRGB_D50, COLOR_TWIST_MODE_SRGB_D65, COLOR_TWIST_MODE_WIDE_GAMUT_RGB_D50, COLOR_YUV422_UYVY, Colors::colorFormatToString(), colorTwistModeToString(), dcam_parameters, HDR_MODE_FIXED0, HDR_MODE_FIXED1, HDR_MODE_FIXED2, HDR_MODE_FIXED3, HDR_MODE_FIXED4, HDR_MODE_FIXED5, HDR_MODE_OFF, hdrModeToString(), is_capturing, mutex, mvc_connect(), pixelClockToString(), CaptureInterface::settings, v_aoi_height, v_aoi_left, v_aoi_top, v_aoi_width, v_cam_bus, v_color_twist_mode, v_colorout, v_expose_overlapped, v_expose_us, v_gain_db, v_gamma, v_hdr_mode, v_mirror_left_right, v_mirror_top_down, v_pixel_clock, v_sharpen, v_wb_blue, v_wb_green, v_wb_red, and VarTypes::VARTYPE_FLAG_HIDE_CHILDREN.
                                                                                             : QObject(parent), CaptureInterface(_settings)
 #else
 CaptureBlueFox2::CaptureBlueFox2(VarList * _settings,int default_camera_id) : CaptureInterface(_settings)
 #endif
 {
   cam_id = default_camera_id;
   is_capturing = false;
   #ifndef VDATA_NO_QT
     mutex.lock();
   #endif
   settings->addChild(capture_settings = new VarList("Capture Settings"));
   settings->addChild(dcam_parameters  = new VarList("Camera Parameters"));
   //=======================CAPTURE SETTINGS==========================
   capture_settings->addChild(v_cam_bus          = new VarInt("cam idx",default_camera_id));
   capture_settings->addChild(v_colorout         = new VarStringEnum("color mode", Colors::colorFormatToString(COLOR_YUV422_UYVY)));
   v_colorout->addItem(Colors::colorFormatToString(COLOR_YUV422_UYVY));
   v_colorout->addItem(Colors::colorFormatToString(COLOR_RGB8));
   //=======================DCAM PARAMETERS===========================
   dcam_parameters->addFlags( VARTYPE_FLAG_HIDE_CHILDREN );
   v_expose_us = new VarInt("Expose [us]", 2000, 10, 100000);
   v_expose_overlapped = new VarBool("Expose Overlapped", true);
   v_gain_db = new VarDouble("Gain [dB]", 0.0, 0.0, 12.0);
   v_hdr_mode = new VarStringEnum("HDR Mode", hdrModeToString(HDR_MODE_OFF));
   v_hdr_mode->addItem(hdrModeToString(HDR_MODE_OFF));
   v_hdr_mode->addItem(hdrModeToString(HDR_MODE_FIXED0));
   v_hdr_mode->addItem(hdrModeToString(HDR_MODE_FIXED1));
   v_hdr_mode->addItem(hdrModeToString(HDR_MODE_FIXED2));
   v_hdr_mode->addItem(hdrModeToString(HDR_MODE_FIXED3));
   v_hdr_mode->addItem(hdrModeToString(HDR_MODE_FIXED4));
   v_hdr_mode->addItem(hdrModeToString(HDR_MODE_FIXED5));
   v_mirror_top_down = new VarBool("Mirror Top/Down");
   v_mirror_left_right = new VarBool("Mirror Left/Right");
   v_wb_red = new VarDouble("WB Red", 1.0, 0.1, 10.0);
   v_wb_green = new VarDouble("WB Green", 1.0, 0.1, 10.0);
   v_wb_blue = new VarDouble("WB Blue", 1.0, 0.1, 10.0);
   v_sharpen = new VarBool("Sharpen", true);
   v_gamma = new VarDouble("Gamma", 1.0, 0.01, 10.0);
   v_color_twist_mode = new VarStringEnum("Color Twist", colorTwistModeToString(COLOR_TWIST_MODE_SRGB_D50));
   v_color_twist_mode->addItem(colorTwistModeToString(COLOR_TWIST_MODE_OFF));
   v_color_twist_mode->addItem(colorTwistModeToString(COLOR_TWIST_MODE_ADOBERGB_D50));
   v_color_twist_mode->addItem(colorTwistModeToString(COLOR_TWIST_MODE_SRGB_D50));
   v_color_twist_mode->addItem(colorTwistModeToString(COLOR_TWIST_MODE_WIDE_GAMUT_RGB_D50));
   v_color_twist_mode->addItem(colorTwistModeToString(COLOR_TWIST_MODE_ADOBERGB_D65));
   v_color_twist_mode->addItem(colorTwistModeToString(COLOR_TWIST_MODE_SRGB_D65));
   v_aoi_width = new VarInt("AOI width", 752, 0, 752);
   v_aoi_height = new VarInt("AOI height", 480, 0, 480);
   v_aoi_left = new VarInt("AOI left", 0, 0, 752);
   v_aoi_top = new VarInt("AOI top", 0, 0, 480);
   v_pixel_clock = new VarStringEnum("Pixel Clock", pixelClockToString(cpc40000KHz));
   v_pixel_clock->addItem(pixelClockToString(cpc6000KHz));
   v_pixel_clock->addItem(pixelClockToString(cpc8000KHz));
   v_pixel_clock->addItem(pixelClockToString(cpc10000KHz));
   v_pixel_clock->addItem(pixelClockToString(cpc12000KHz));
   v_pixel_clock->addItem(pixelClockToString(cpc20000KHz));
   v_pixel_clock->addItem(pixelClockToString(cpc24000KHz));
   v_pixel_clock->addItem(pixelClockToString(cpc27000KHz));
   v_pixel_clock->addItem(pixelClockToString(cpc32000KHz));
   v_pixel_clock->addItem(pixelClockToString(cpc40000KHz));
   dcam_parameters->addChild(v_aoi_width);
   dcam_parameters->addChild(v_aoi_height);
   dcam_parameters->addChild(v_aoi_left);
   dcam_parameters->addChild(v_aoi_top);
   dcam_parameters->addChild(v_pixel_clock);
   dcam_parameters->addChild(v_expose_us);
   dcam_parameters->addChild(v_expose_overlapped);
   dcam_parameters->addChild(v_gain_db);
   dcam_parameters->addChild(v_hdr_mode);
   dcam_parameters->addChild(v_mirror_top_down);
   dcam_parameters->addChild(v_mirror_left_right);
   dcam_parameters->addChild(v_wb_red);
   dcam_parameters->addChild(v_wb_green);
   dcam_parameters->addChild(v_wb_blue);
   dcam_parameters->addChild(v_sharpen);
   dcam_parameters->addChild(v_gamma);
   dcam_parameters->addChild(v_color_twist_mode);
   #ifndef VDATA_NO_QT
     mvc_connect(dcam_parameters);
     mutex.unlock();
   #endif
 }
CaptureBlueFox2::~CaptureBlueFox2 ()
Definition at line 280 of file capture_bluefox2.cpp.
References capture_settings, dcam_parameters, and VarTypes::VarList::deleteAllChildren().
 {
   capture_settings->deleteAllChildren();
   dcam_parameters->deleteAllChildren();
 }
Member Function Documentation
void CaptureBlueFox2::changed (VarType * group) slot
Definition at line 129 of file capture_bluefox2.cpp.
References VarTypes::VarVal::getType(), readParameterValues(), VarTypes::VARTYPE_ID_LIST, and writeParameterValues().
Referenced by mvc_connect().
 {
   if (group->getType()==VARTYPE_ID_LIST)
   {
     writeParameterValues( (VarList *)group );
     readParameterValues( (VarList *)group );
   }
 }
static string CaptureBlueFox2::colorTwistModeToString (ColorTwistMode mode) inline static
Definition at line 156 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2().
   {
     switch(mode)
     {
       case COLOR_TWIST_MODE_ADOBERGB_D50: return "AdobeRGB_D50";
       case COLOR_TWIST_MODE_SRGB_D50: return "sRGB_D50";
       case COLOR_TWIST_MODE_WIDE_GAMUT_RGB_D50: return "WideGamutRGB_D50";
       case COLOR_TWIST_MODE_ADOBERGB_D65: return "AdobeRGB_D65";
       case COLOR_TWIST_MODE_SRGB_D65: return "sRGB_D65";
       default: return "Off";
     }
   }
bool CaptureBlueFox2::copyAndConvertFrame (const RawImage & src, RawImage & target) virtual
Reimplemented from CaptureInterface.
Definition at line 406 of file capture_bluefox2.cpp.
References RawImage::allocate(), COLOR_RGB8, RawImage::ensure_allocation(), RawImage::getColorFormat(), RawImage::getData(), RawImage::getHeight(), RawImage::getNumBytes(), RawImage::getTime(), RawImage::getWidth(), velocity.pid_::i, mutex, and RawImage::setTime().
 {
   #ifndef VDATA_NO_QT
     mutex.lock();
   #endif
   ColorFormat src_fmt = src.getColorFormat();
   if(target.getData() == 0)
   {
     //allocate target, if it does not exist yet
     target.allocate(src_fmt, src.getWidth(), src.getHeight());
   }
   else
   {
     target.ensure_allocation(src_fmt, src.getWidth(), src.getHeight());
   }
   target.setTime(src.getTime());
   if(src.getColorFormat() == COLOR_RGB8)
   {
     memcpy(target.getData(),src.getData(),src.getNumBytes());
   }
   else
   {
     for(int i = 0; i < src.getNumBytes(); i += 2)
     {
       target.getData()[i+1] = src.getData()[i];
       target.getData()[i] = src.getData()[i+1];
     }
   }
   #ifndef VDATA_NO_QT
     mutex.unlock();
   #endif
   return true;
 }
string CaptureBlueFox2::getCaptureMethodName () const virtual
Implements CaptureInterface.
Definition at line 518 of file capture_bluefox2.cpp.
 {
   return "BlueFox2";
 }
RawImage CaptureBlueFox2::getFrame () virtual
this gives a raw-image with a pointer directly to the video-buffer Note that this pointer is only guaranteed to point to a valid memory location until releaseFrame() is called.
Implements CaptureInterface.
Definition at line 445 of file capture_bluefox2.cpp.
References capture_format, VarTypes::VarStringEnum::getSelection(), lastRequestNr, mutex, pFI, RawImage::setColorFormat(), RawImage::setData(), RawImage::setHeight(), RawImage::setTime(), RawImage::setWidth(), Colors::stringToColorFormat(), and v_colorout.
 {
   #ifndef VDATA_NO_QT
     mutex.lock();
   #endif
   RawImage result;
   result.setColorFormat(capture_format);
   result.setWidth(0);
   result.setHeight(0);
   result.setTime(0.0);
   result.setData(0);
   // make sure the request queue is always filled
   while((static_cast<TDMR_ERROR>( pFI->imageRequestSingle() ) ) == DMR_NO_ERROR ) {};
   int requestNr = pFI->imageRequestWaitFor(-1);
   // check if the image has been captured without any problems.
   if(!pFI->isRequestNrValid(requestNr))
   {
       // If the error code is -2119(DEV_WAIT_FOR_REQUEST_FAILED), the documentation will provide
       // additional information under TDMR_ERROR in the interface reference
       fprintf(stderr, "imageRequestWaitFor failed (%d, %s)\n", requestNr, ImpactAcquireException::getErrorCodeAsString( requestNr ).c_str());
       #ifndef VDATA_NO_QT
     mutex.unlock();
       #endif
       return result;
   }
   const Request* pRequest = pFI->getRequest(requestNr);
   if(pRequest->isOK())
   {
     timeval tv;
     gettimeofday(&tv,NULL);
     result.setTime((double)tv.tv_sec + tv.tv_usec*(1.0E-6));
     result.setWidth(pRequest->imageWidth.read());
     result.setHeight(pRequest->imageHeight.read());
     ColorFormat out_color = Colors::stringToColorFormat(v_colorout->getSelection().c_str());
     result.setColorFormat(out_color);
     result.setData((unsigned char*)pRequest->imageData.read());
 //     fprintf(stderr, "Timestamp_us: %ld\n", pRequest->infoTimeStamp_us.read());
 //     fprintf(stderr, "BPP: %u\n", pRequest->imageBytesPerPixel.read());
 //     fprintf(stderr, "PixelFormat: %s\n", pRequest->imagePixelFormat.readS().c_str());
   }
   else
   {
     fprintf(stderr, "BlueFox2: request not OK\n");
   }
   lastRequestNr = requestNr;
   #ifndef VDATA_NO_QT
     mutex.unlock();
   #endif
   return result;
 }
static string CaptureBlueFox2::hdrModeToString (HDRMode mode) inline static
Definition at line 113 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2().
   {
     switch(mode)
     {
       case HDR_MODE_FIXED0: return "Fixed0";
       case HDR_MODE_FIXED1: return "Fixed1";
       case HDR_MODE_FIXED2: return "Fixed2";
       case HDR_MODE_FIXED3: return "Fixed3";
       case HDR_MODE_FIXED4: return "Fixed4";
       case HDR_MODE_FIXED5: return "Fixed5";
       default: return "Off";
     }
   }
virtual bool CaptureBlueFox2::isCapturing () inline virtual
Implements CaptureInterface.
Definition at line 264 of file capture_bluefox2.h.
References role._GoToPoint::target.
Referenced by stopCapture().
 { return is_capturing; };
void CaptureBlueFox2::mvc_connect (VarList * group)
Definition at line 119 of file capture_bluefox2.cpp.
References changed(), VarTypes::VarList::getChildren(), velocity.pid_::i, and v.
Referenced by CaptureBlueFox2().
 {
   vector<VarType *> v=group->getChildren();
   for (unsigned int i=0;i<v.size();i++)
   {
     connect(v[i],SIGNAL(wasEdited(VarType *)),group,SLOT(mvcEditCompleted()));
   }
   connect(group,SIGNAL(wasEdited(VarType *)),this,SLOT(changed(VarType *)));
 }
static string CaptureBlueFox2::pixelClockToString (TCameraPixelClock pxc) inline static
Definition at line 192 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2().
   {
     switch(pxc)
     {
       case cpc8000KHz: return "8MHz";
       case cpc10000KHz: return "10MHz";
       case cpc12000KHz: return "12MHz";
       case cpc20000KHz: return "20MHz";
       case cpc24000KHz: return "24MHz";
       case cpc27000KHz: return "27MHz";
       case cpc32000KHz: return "32MHz";
       case cpc40000KHz: return "40MHz";
       default: return "6MHz";
     }
   }
void CaptureBlueFox2::readAllParameterValues () virtual
Reimplemented from CaptureInterface.
Definition at line 139 of file capture_bluefox2.cpp.
References dcam_parameters, and readParameterValues().
Referenced by startCapture(), and stopCapture().
 {
   readParameterValues(dcam_parameters);
 }
void CaptureBlueFox2::readParameterValues (VarList * item)
Definition at line 149 of file capture_bluefox2.cpp.
References dcam_parameters, and mutex.
Referenced by changed(), and readAllParameterValues().
 {
   if(item != dcam_parameters)
     return;
   #ifndef VDATA_NO_QT
     mutex.lock();
   #endif
     // TODO: could do a read-out, but why?
 //   v_expose_us->setInt(pSettings->expose_us.read());
   #ifndef VDATA_NO_QT
     mutex.unlock();
   #endif
 }
void CaptureBlueFox2::releaseFrame () virtual
Implements CaptureInterface.
Definition at line 504 of file capture_bluefox2.cpp.
References lastRequestNr, mutex, and pFI.
 {
   #ifndef VDATA_NO_QT
     mutex.lock();
   #endif
   if(pFI->isRequestNrValid(lastRequestNr))
     pFI->imageRequestUnlock(lastRequestNr);
   #ifndef VDATA_NO_QT
     mutex.unlock();
   #endif
 }
bool CaptureBlueFox2::resetBus () virtual
Reimplemented from CaptureInterface.
Definition at line 286 of file capture_bluefox2.cpp.
References mutex.
 {
   #ifndef VDATA_NO_QT
     mutex.lock();
   #endif
   #ifndef VDATA_NO_QT
     mutex.unlock();
   #endif
   return true;
 }
bool CaptureBlueFox2::startCapture () virtual
Initialize the interface and start capture.
Implements CaptureInterface.
Definition at line 325 of file capture_bluefox2.cpp.
References cam_id, capture_settings, COLOR_RGB8, dcam_parameters, devMgr, VarTypes::VarList::getChildren(), VarTypes::VarInt::getInt(), VarTypes::VarStringEnum::getSelection(), velocity.pid_::i, is_capturing, mutex, pDevice, pFI, pImageProc, pSettings, readAllParameterValues(), VarTypes::VarType::removeFlags(), Colors::stringToColorFormat(), v_cam_bus, v_colorout, VarTypes::VARTYPE_FLAG_HIDE_CHILDREN, VarTypes::VARTYPE_FLAG_READONLY, and writeAllParameterValues().
 {
   #ifndef VDATA_NO_QT
     mutex.lock();
   #endif
   //grab current parameters:
   cam_id = v_cam_bus->getInt();
   const unsigned int devCnt = devMgr.deviceCount();
   fprintf(stderr, "BlueFox2: Number of cams: %u\n", devCnt);
   if(cam_id >= devCnt)
   {
     fprintf(stderr, "BlueFox2: Invalid cam_id: %u\n", cam_id);
     #ifndef VDATA_NO_QT
       mutex.unlock();
     #endif
     return false;
   }
   pDevice = devMgr[cam_id];
   try
   {
     pDevice->open();
   }
   catch(mvIMPACT::acquire::ImpactAcquireException& e)
   {
     // this e.g. might happen if the same device is already opened in another process...
     fprintf(stderr, "BlueFox2: An error occurred while opening the device(error code: %d, '%s')\n", e.getErrorCode(), e.getErrorString().c_str());
     #ifndef VDATA_NO_QT
       mutex.unlock();
     #endif
     return false;
   }
   fprintf(stderr, "BlueFox2: Opened: %s with serial ID %s\n", pDevice->family.read().c_str(), pDevice->serial.read().c_str());
   pFI = new FunctionInterface(pDevice);
   ImageDestination id( pDevice );
   id.restoreDefault();
   ColorFormat out_color = Colors::stringToColorFormat(v_colorout->getSelection().c_str());
   if(out_color == COLOR_RGB8)
   {
     id.pixelFormat.write(idpfBGR888Packed);
   }
   else
   {
     id.pixelFormat.write(idpfYUV422Packed);
   }
   pSettings = new CameraSettingsBlueFOX(pDevice);
   pSettings->restoreDefault();
   pImageProc = new ImageProcessing(pDevice);
   pImageProc->restoreDefault();
   is_capturing = true;
   vector<VarType *> tmp = capture_settings->getChildren();
   for (unsigned int i=0; i < tmp.size();i++) {
     tmp[i]->addFlags( VARTYPE_FLAG_READONLY );
   }
   dcam_parameters->removeFlags( VARTYPE_FLAG_HIDE_CHILDREN );
   #ifndef VDATA_NO_QT
     mutex.unlock();
   #endif
   printf("BlueFox2 Info: Restoring Previously Saved Camera Parameters\n");
   writeAllParameterValues();
   readAllParameterValues();
   return true;
 }
bool CaptureBlueFox2::stopCapture () virtual
Stop Capture.
Implements CaptureInterface.
Definition at line 299 of file capture_bluefox2.cpp.
References VarTypes::VarType::addFlags(), capture_settings, dcam_parameters, VarTypes::VarList::getChildren(), velocity.pid_::i, is_capturing, isCapturing(), pDevice, pFI, pImageProc, pSettings, readAllParameterValues(), VarTypes::VARTYPE_FLAG_HIDE_CHILDREN, and VarTypes::VARTYPE_FLAG_READONLY.
 {
   if (isCapturing())
   {
     readAllParameterValues();
     delete pFI;
     delete pSettings;
     delete pImageProc;
     pDevice->close();
     is_capturing = false;
   }
   vector<VarType *> tmp = capture_settings->getChildren();
   for (unsigned int i=0; i < tmp.size();i++)
   {
     tmp[i]->removeFlags( VARTYPE_FLAG_READONLY );
   }
   dcam_parameters->addFlags( VARTYPE_FLAG_HIDE_CHILDREN );
   return true;
 }
static ColorTwistMode CaptureBlueFox2::stringToColorTwistMode (const char * s) inline static
Definition at line 137 of file capture_bluefox2.h.
Referenced by writeParameterValues().
   {
       if (strcmp(s,"Off")==0) {
       return COLOR_TWIST_MODE_OFF;
     } else if (strcmp(s,"AdobeRGB_D50")==0) {
       return COLOR_TWIST_MODE_ADOBERGB_D50;
     } else if (strcmp(s,"sRGB_D50")==0) {
       return COLOR_TWIST_MODE_SRGB_D50;
     } else if (strcmp(s,"WideGamutRGB_D50")==0) {
       return COLOR_TWIST_MODE_WIDE_GAMUT_RGB_D50;
     } else if (strcmp(s,"AdobeRGB_D65")==0) {
       return COLOR_TWIST_MODE_ADOBERGB_D65;
     } else if (strcmp(s,"sRGB_D65")==0) {
       return COLOR_TWIST_MODE_SRGB_D65;
     } else {
       return COLOR_TWIST_MODE_OFF;
     }
   }
static HDRMode CaptureBlueFox2::stringToHdrMode (const char * s) inline static
Definition at line 92 of file capture_bluefox2.h.
Referenced by writeParameterValues().
   {
     if (strcmp(s,"Off")==0) {
       return HDR_MODE_OFF;
     } else if (strcmp(s,"Fixed0")==0) {
       return HDR_MODE_FIXED0;
     } else if (strcmp(s,"Fixed1")==0) {
       return HDR_MODE_FIXED1;
     } else if (strcmp(s,"Fixed2")==0) {
       return HDR_MODE_FIXED2;
     } else if (strcmp(s,"Fixed3")==0) {
       return HDR_MODE_FIXED3;
     } else if (strcmp(s,"Fixed4")==0) {
       return HDR_MODE_FIXED4;
     } else if (strcmp(s,"Fixed5")==0) {
       return HDR_MODE_FIXED5;
     } else {
       return HDR_MODE_OFF;
     }
   }
static TCameraPixelClock CaptureBlueFox2::stringToPixelClock (const char * s) inline static
Definition at line 169 of file capture_bluefox2.h.
Referenced by writeParameterValues().
   {
     if (strcmp(s,"8MHz")==0) {
       return cpc8000KHz;
     } else if (strcmp(s,"10MHz")==0) {
       return cpc10000KHz;
     } else if (strcmp(s,"12MHz")==0) {
       return cpc12000KHz;
     } else if (strcmp(s,"20MHz")==0) {
       return cpc20000KHz;
     } else if (strcmp(s,"24MHz")==0) {
       return cpc24000KHz;
     } else if (strcmp(s,"27MHz")==0) {
       return cpc27000KHz;
     } else if (strcmp(s,"32MHz")==0) {
       return cpc32000KHz;
     } else if (strcmp(s,"40MHz")==0) {
       return cpc40000KHz;
     } else {
       return cpc6000KHz;
     }
   }
void CaptureBlueFox2::writeAllParameterValues ()
Definition at line 144 of file capture_bluefox2.cpp.
References dcam_parameters, and writeParameterValues().
Referenced by startCapture().
 {
   writeParameterValues(dcam_parameters);
 }
void CaptureBlueFox2::writeParameterValues (VarList * item)
Definition at line 166 of file capture_bluefox2.cpp.
References COLOR_TWIST_MODE_ADOBERGB_D50, COLOR_TWIST_MODE_ADOBERGB_D65, COLOR_TWIST_MODE_OFF, COLOR_TWIST_MODE_SRGB_D50, COLOR_TWIST_MODE_WIDE_GAMUT_RGB_D50, dcam_parameters, VarTypes::VarBoolVal::getBool(), VarTypes::VarDoubleVal::getDouble(), VarTypes::VarInt::getInt(), VarTypes::VarStringEnum::getString(), HDR_MODE_FIXED0, HDR_MODE_FIXED1, HDR_MODE_FIXED2, HDR_MODE_FIXED3, HDR_MODE_FIXED4, HDR_MODE_OFF, mutex, pImageProc, pSettings, stringToColorTwistMode(), stringToHdrMode(), stringToPixelClock(), v_aoi_height, v_aoi_left, v_aoi_top, v_aoi_width, v_color_twist_mode, v_expose_overlapped, v_expose_us, v_gain_db, v_gamma, v_hdr_mode, v_mirror_left_right, v_mirror_top_down, v_pixel_clock, v_sharpen, v_wb_blue, v_wb_green, and v_wb_red.
Referenced by changed(), and writeAllParameterValues().
 {
   if(item != dcam_parameters)
     return;
   #ifndef VDATA_NO_QT
     mutex.lock();
   #endif
   pSettings->pixelClock_KHz.write(stringToPixelClock(v_pixel_clock->getString().c_str()));
   pSettings->expose_us.write(v_expose_us->getInt());
   if(v_expose_overlapped->getBool())
     pSettings->exposeMode.write(cemOverlapped);
   else
     pSettings->exposeMode.write(cemStandard);
   pSettings->gain_dB.write(v_gain_db->getDouble());
   pSettings->aoiStartX.write(v_aoi_left->getInt());
   pSettings->aoiStartY.write(v_aoi_top->getInt());
   pSettings->aoiWidth.write(v_aoi_width->getInt());
   pSettings->aoiHeight.write(v_aoi_height->getInt());
   HDRMode hdrMode = stringToHdrMode(v_hdr_mode->getString().c_str());
   if(hdrMode == HDR_MODE_OFF)
   {
     pSettings->getHDRControl().HDREnable.write(bFalse);
   }
   else
   {
     pSettings->getHDRControl().HDREnable.write(bTrue);
     TCameraHDRMode hdr;
     switch(hdrMode)
     {
       case HDR_MODE_FIXED0: hdr = cHDRmFixed0; break;
       case HDR_MODE_FIXED1: hdr = cHDRmFixed1; break;
       case HDR_MODE_FIXED2: hdr = cHDRmFixed2; break;
       case HDR_MODE_FIXED3: hdr = cHDRmFixed3; break;
       case HDR_MODE_FIXED4: hdr = cHDRmFixed4; break;
       default: hdr = cHDRmFixed5; break;
     }
     pSettings->getHDRControl().HDRMode.write(hdr);
   }
   int mm = mmOff;
   if(v_mirror_top_down->getBool())
     mm |= mmTopDown;
   if(v_mirror_left_right->getBool())
     mm |= mmLeftRight;
   pImageProc->mirrorOperationMode.write(momGlobal);
   pImageProc->mirrorModeGlobal.write((TMirrorMode)mm);
   pImageProc->whiteBalance.write(wbpUser1);
   WhiteBalanceSettings& wb = pImageProc->getWBUserSetting(0);
   wb.WBAoiMode.write(amFull);
   wb.totalGain.write(1.0);
   wb.redGain.write(v_wb_red->getDouble());
   wb.greenGain.write(v_wb_green->getDouble());
   wb.blueGain.write(v_wb_blue->getDouble());
   if(v_sharpen->getBool())
     pImageProc->filter.write(ipfSharpen);
   else
     pImageProc->filter.write(ipfOff);
   pImageProc->LUTEnable.write(bTrue);
   pImageProc->LUTMode.write(LUTmGamma);
   pImageProc->LUTImplementation.write(LUTiSoftware);
   pImageProc->LUTMappingSoftware.write(LUTm10To10);
   pImageProc->getLUTParameter(0).gamma.write(v_gamma->getDouble());
   pImageProc->getLUTParameter(1).gamma.write(v_gamma->getDouble());
   pImageProc->getLUTParameter(2).gamma.write(v_gamma->getDouble());
   pImageProc->getLUTParameter(3).gamma.write(v_gamma->getDouble());
   ColorTwistMode ctMode = stringToColorTwistMode(v_color_twist_mode->getString().c_str());
   if(ctMode == COLOR_TWIST_MODE_OFF)
   {
     pImageProc->colorTwistInputCorrectionMatrixEnable.write(bFalse);
     pImageProc->colorTwistEnable.write(bFalse);
     pImageProc->colorTwistOutputCorrectionMatrixEnable.write(bFalse);
   }
   else
   {
     pImageProc->colorTwistInputCorrectionMatrixEnable.write(bTrue);
     pImageProc->colorTwistInputCorrectionMatrixMode.write(cticmmDeviceSpecific);
     pImageProc->colorTwistEnable.write(bTrue);
     pImageProc->colorTwistOutputCorrectionMatrixEnable.write(bTrue);
     int ct;
     switch(ctMode)
     {
       case COLOR_TWIST_MODE_ADOBERGB_D50: ct = ctocmmXYZToAdobeRGB_D50; break;
       case COLOR_TWIST_MODE_SRGB_D50: ct = ctocmmXYZTosRGB_D50; break;
       case COLOR_TWIST_MODE_WIDE_GAMUT_RGB_D50: ct = ctocmmXYZToWideGamutRGB_D50; break;
       case COLOR_TWIST_MODE_ADOBERGB_D65: ct = ctocmmXYZToAdobeRGB_D65; break;
       default: ct = ctocmmXYZTosRGB_D65; break;
     }
     pImageProc->colorTwistOutputCorrectionMatrixMode.write((TColorTwistOutputCorrectionMatrixMode)ct);
   }
   #ifndef VDATA_NO_QT
     mutex.unlock();
   #endif
 }
Field Documentation
unsigned int CaptureBlueFox2::cam_id protected
Definition at line 246 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and startCapture().
ColorFormat CaptureBlueFox2::capture_format protected
Definition at line 247 of file capture_bluefox2.h.
Referenced by getFrame().
VarList* CaptureBlueFox2::capture_settings protected
Definition at line 236 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), startCapture(), stopCapture(), and ~CaptureBlueFox2().
VarList* CaptureBlueFox2::dcam_parameters protected
Definition at line 235 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), readAllParameterValues(), readParameterValues(), startCapture(), stopCapture(), writeAllParameterValues(), writeParameterValues(), and ~CaptureBlueFox2().
DeviceManager CaptureBlueFox2::devMgr protected
Definition at line 239 of file capture_bluefox2.h.
Referenced by startCapture().
bool CaptureBlueFox2::is_capturing protected
Definition at line 210 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), startCapture(), and stopCapture().
int CaptureBlueFox2::lastRequestNr protected
Definition at line 244 of file capture_bluefox2.h.
Referenced by getFrame(), and releaseFrame().
QMutex CaptureBlueFox2::mutex protected
Definition at line 76 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), copyAndConvertFrame(), getFrame(), readParameterValues(), releaseFrame(), resetBus(), startCapture(), and writeParameterValues().
Device* CaptureBlueFox2::pDevice protected
Definition at line 240 of file capture_bluefox2.h.
Referenced by startCapture(), and stopCapture().
FunctionInterface* CaptureBlueFox2::pFI protected
Definition at line 241 of file capture_bluefox2.h.
Referenced by getFrame(), releaseFrame(), startCapture(), and stopCapture().
ImageProcessing* CaptureBlueFox2::pImageProc protected
Definition at line 243 of file capture_bluefox2.h.
Referenced by startCapture(), stopCapture(), and writeParameterValues().
CameraSettingsBlueFOX* CaptureBlueFox2::pSettings protected
Definition at line 242 of file capture_bluefox2.h.
Referenced by startCapture(), stopCapture(), and writeParameterValues().
VarInt* CaptureBlueFox2::v_aoi_height protected
Definition at line 226 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarInt* CaptureBlueFox2::v_aoi_left protected
Definition at line 227 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarInt* CaptureBlueFox2::v_aoi_top protected
Definition at line 228 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarInt* CaptureBlueFox2::v_aoi_width protected
Definition at line 225 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarInt* CaptureBlueFox2::v_cam_bus protected
Definition at line 232 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and startCapture().
VarStringEnum* CaptureBlueFox2::v_color_twist_mode protected
Definition at line 224 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarStringEnum* CaptureBlueFox2::v_colorout protected
Definition at line 233 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), getFrame(), and startCapture().
VarBool* CaptureBlueFox2::v_expose_overlapped protected
Definition at line 214 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarInt* CaptureBlueFox2::v_expose_us protected
Definition at line 213 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarDouble* CaptureBlueFox2::v_gain_db protected
Definition at line 215 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarDouble* CaptureBlueFox2::v_gamma protected
Definition at line 223 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarStringEnum* CaptureBlueFox2::v_hdr_mode protected
Definition at line 216 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarBool* CaptureBlueFox2::v_mirror_left_right protected
Definition at line 218 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarBool* CaptureBlueFox2::v_mirror_top_down protected
Definition at line 217 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarStringEnum* CaptureBlueFox2::v_pixel_clock protected
Definition at line 229 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarBool* CaptureBlueFox2::v_sharpen protected
Definition at line 222 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarDouble* CaptureBlueFox2::v_wb_blue protected
Definition at line 221 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarDouble* CaptureBlueFox2::v_wb_green protected
Definition at line 220 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
VarDouble* CaptureBlueFox2::v_wb_red protected
Definition at line 219 of file capture_bluefox2.h.
Referenced by CaptureBlueFox2(), and writeParameterValues().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/capture/capture_bluefox2.h
ssl-vision/src/shared/capture/capture_bluefox2.cpp