Documentation: Protobuf.GrSimReplacement.grSim_BallReplacement Class Reference
Protobuf.GrSimReplacement.grSim_BallReplacement Class Reference
Data Structures
class Builder
Public Member Functions
grSim_BallReplacement getDefaultInstanceForType ()
boolean hasX ()
double getX ()
boolean hasY ()
double getY ()
boolean hasVx ()
double getVx ()
boolean hasVy ()
double getVy ()
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static grSim_BallReplacement getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static GrSimReplacement.grSim_BallReplacement parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimReplacement.grSim_BallReplacement parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimReplacement.grSim_BallReplacement parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimReplacement.grSim_BallReplacement parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimReplacement.grSim_BallReplacement parseFrom (java.io.InputStream input) throws java.io.IOException
static GrSimReplacement.grSim_BallReplacement parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static GrSimReplacement.grSim_BallReplacement parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static GrSimReplacement.grSim_BallReplacement parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static GrSimReplacement.grSim_BallReplacement parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static GrSimReplacement.grSim_BallReplacement parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (GrSimReplacement.grSim_BallReplacement prototype)
Static Public Attributes
static final int X_FIELD_NUMBER = 1
static final int Y_FIELD_NUMBER = 2
static final int VX_FIELD_NUMBER = 3
static final int VY_FIELD_NUMBER = 4
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
grSim_BallReplacement (Builder builder)
grSim_BallReplacement (boolean noInit)
void initFields ()
Private Attributes
int bitField0_
double x_
double y_
double vx_
double vy_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final grSim_BallReplacement defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 636 of file GrSimReplacement.java.
Constructor & Destructor Documentation
Protobuf.GrSimReplacement.grSim_BallReplacement.grSim_BallReplacement (Builder builder) inline private
Definition at line 640 of file GrSimReplacement.java.
{
       super(builder);
     }
Protobuf.GrSimReplacement.grSim_BallReplacement.grSim_BallReplacement (boolean noInit) inline private
Definition at line 643 of file GrSimReplacement.java.
 {}
Member Function Documentation
static grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.getDefaultInstance () inline static
Definition at line 646 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.Builder.clear(), Protobuf.GrSimReplacement.grSim_Replacement.Builder.clearBall(), Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.getDefaultInstanceForType(), Protobuf.GrSimReplacement.grSim_Replacement.initFields(), Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeBall(), and Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.mergeFrom().
{
       return defaultInstance;
     }
grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.getDefaultInstanceForType () inline
Definition at line 650 of file GrSimReplacement.java.
{
       return defaultInstance;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimReplacement.grSim_BallReplacement.getDescriptor () inline static
Definition at line 655 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.internal_static_grSim_BallReplacement_descriptor.
Referenced by Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.getDescriptorForType().
{
       return GrSimReplacement.internal_static_grSim_BallReplacement_descriptor;
     }
int Protobuf.GrSimReplacement.grSim_BallReplacement.getSerializedSize () inline
Definition at line 755 of file GrSimReplacement.java.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeDoubleSize(1, x_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         size += com.google.protobuf.CodedOutputStream
           .computeDoubleSize(2, y_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         size += com.google.protobuf.CodedOutputStream
           .computeDoubleSize(3, vx_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         size += com.google.protobuf.CodedOutputStream
           .computeDoubleSize(4, vy_);
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
double Protobuf.GrSimReplacement.grSim_BallReplacement.getVx () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 691 of file GrSimReplacement.java.
{
       return vx_;
     }
double Protobuf.GrSimReplacement.grSim_BallReplacement.getVy () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 701 of file GrSimReplacement.java.
{
       return vy_;
     }
double Protobuf.GrSimReplacement.grSim_BallReplacement.getX () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 671 of file GrSimReplacement.java.
{
       return x_;
     }
double Protobuf.GrSimReplacement.grSim_BallReplacement.getY () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 681 of file GrSimReplacement.java.
{
       return y_;
     }
boolean Protobuf.GrSimReplacement.grSim_BallReplacement.hasVx () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 688 of file GrSimReplacement.java.
{
       return ((bitField0_ & 0x00000004) == 0x00000004);
     }
boolean Protobuf.GrSimReplacement.grSim_BallReplacement.hasVy () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 698 of file GrSimReplacement.java.
{
       return ((bitField0_ & 0x00000008) == 0x00000008);
     }
boolean Protobuf.GrSimReplacement.grSim_BallReplacement.hasX () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 668 of file GrSimReplacement.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
boolean Protobuf.GrSimReplacement.grSim_BallReplacement.hasY () inline
Implements Protobuf.GrSimReplacement.grSim_BallReplacementOrBuilder.
Definition at line 678 of file GrSimReplacement.java.
{
       return ((bitField0_ & 0x00000002) == 0x00000002);
     }
void Protobuf.GrSimReplacement.grSim_BallReplacement.initFields () inline private
Definition at line 705 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.clearVy().
{
       x_ = 0D;
       y_ = 0D;
       vx_ = 0D;
       vy_ = 0D;
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.GrSimReplacement.grSim_BallReplacement.internalGetFieldAccessorTable () inline protected
Definition at line 660 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.internal_static_grSim_BallReplacement_fieldAccessorTable.
{
       return GrSimReplacement.internal_static_grSim_BallReplacement_fieldAccessorTable;
     }
final boolean Protobuf.GrSimReplacement.grSim_BallReplacement.isInitialized () inline
Definition at line 712 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasX(), and Protobuf.GrSimReplacement.grSim_RobotReplacementOrBuilder.hasY().
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (!hasX()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasY()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasVx()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasVy()) {
         memoizedIsInitialized = 0;
         return false;
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.GrSimReplacement.grSim_BallReplacement.newBuilder () inline static
Definition at line 855 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.create().
Referenced by Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeBall(), and Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeFrom().
 { return Builder.create(); }
static Builder Protobuf.GrSimReplacement.grSim_BallReplacement.newBuilder (GrSimReplacement.grSim_BallReplacement prototype) inline static
Definition at line 857 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.newBuilderForType () inline
Definition at line 856 of file GrSimReplacement.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.GrSimReplacement.grSim_BallReplacement.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 863 of file GrSimReplacement.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 822 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 831 of file GrSimReplacement.java.
References Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 788 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 793 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 800 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 804 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 811 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 815 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 842 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static GrSimReplacement.grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 847 of file GrSimReplacement.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.GrSimReplacement.grSim_BallReplacement.toBuilder () inline
Definition at line 860 of file GrSimReplacement.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.GrSimReplacement.grSim_BallReplacement.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 783 of file GrSimReplacement.java.
{
       return super.writeReplace();
     }
void Protobuf.GrSimReplacement.grSim_BallReplacement.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 736 of file GrSimReplacement.java.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeDouble(1, x_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         output.writeDouble(2, y_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         output.writeDouble(3, vx_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         output.writeDouble(4, vy_);
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
int Protobuf.GrSimReplacement.grSim_BallReplacement.bitField0_ private
Definition at line 664 of file GrSimReplacement.java.
final grSim_BallReplacement Protobuf.GrSimReplacement.grSim_BallReplacement.defaultInstance static private
Definition at line 645 of file GrSimReplacement.java.
byte Protobuf.GrSimReplacement.grSim_BallReplacement.memoizedIsInitialized = -1 private
Definition at line 711 of file GrSimReplacement.java.
int Protobuf.GrSimReplacement.grSim_BallReplacement.memoizedSerializedSize = -1 private
Definition at line 754 of file GrSimReplacement.java.
final long Protobuf.GrSimReplacement.grSim_BallReplacement.serialVersionUID = 0L static private
Definition at line 781 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_BallReplacement.vx_ private
Definition at line 687 of file GrSimReplacement.java.
final int Protobuf.GrSimReplacement.grSim_BallReplacement.VX_FIELD_NUMBER = 3 static
Definition at line 686 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_BallReplacement.vy_ private
Definition at line 697 of file GrSimReplacement.java.
final int Protobuf.GrSimReplacement.grSim_BallReplacement.VY_FIELD_NUMBER = 4 static
Definition at line 696 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_BallReplacement.x_ private
Definition at line 667 of file GrSimReplacement.java.
Referenced by Protobuf.GrSimReplacement.grSim_BallReplacement.Builder.buildPartial().
final int Protobuf.GrSimReplacement.grSim_BallReplacement.X_FIELD_NUMBER = 1 static
Definition at line 666 of file GrSimReplacement.java.
double Protobuf.GrSimReplacement.grSim_BallReplacement.y_ private
Definition at line 677 of file GrSimReplacement.java.
final int Protobuf.GrSimReplacement.grSim_BallReplacement.Y_FIELD_NUMBER = 2 static
Definition at line 676 of file GrSimReplacement.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimReplacement.java