Documentation: JogDial Class Reference
JogDial Class Reference
#include <jog_dial.h>
Signals
void valueChanged (float offset)
Public Member Functions
JogDial (QWidget *parent=0)
float offset ()
Protected Member Functions
void paintEvent (QPaintEvent *pe)
void mousePressEvent (QMouseEvent *me)
void mouseMoveEvent (QMouseEvent *me)
void mouseReleaseEvent (QMouseEvent *me)
Protected Attributes
QMutex mutex
Private Attributes
float _offset
float _spacing
float _viewSpan
int _x
Detailed Description
Definition at line 28 of file jog_dial.h.
Constructor & Destructor Documentation
JogDial::JogDial (QWidget * parent = 0)
Definition at line 28 of file jog_dial.cpp.
References _offset, _spacing, and _viewSpan.
                                 :
     QWidget(parent)
 {
     _offset = 0;
   QWidget::setMinimumSize(40,10);
     _spacing = 10.0f;
     _viewSpan = 180.0f;
 }
Member Function Documentation
void JogDial::mouseMoveEvent (QMouseEvent * me) protected
Definition at line 62 of file jog_dial.cpp.
References _offset, _viewSpan, _x, mutex, offset(), valueChanged(), and role._GoToPoint::x.
 {
   mutex.lock();
     int x = me->x();
     int diff = x - _x;
     _offset = diff * _viewSpan/width();
   mutex.unlock();
     update();
     valueChanged(offset());
 }
void JogDial::mousePressEvent (QMouseEvent * me) protected
Definition at line 55 of file jog_dial.cpp.
References _x, and mutex.
 {
  mutex.lock();
  _x = me->x();
  mutex.unlock();
 }
void JogDial::mouseReleaseEvent (QMouseEvent * me) protected
Definition at line 75 of file jog_dial.cpp.
References _offset, mutex, offset(), and valueChanged().
 {
   mutex.lock();
     _offset = 0;
   mutex.unlock();
     update();
     valueChanged(offset());
 }
float JogDial::offset () inline
returns the normalized offset
Definition at line 36 of file jog_dial.h.
References _offset, _viewSpan, mutex, and valueChanged().
Referenced by mouseMoveEvent(), mouseReleaseEvent(), and PluginDVR::process().
                    {
       float result=0.0;
       mutex.lock();
       result=_offset*2.0f/_viewSpan;
       mutex.unlock();
       return result;
     }
void JogDial::paintEvent (QPaintEvent * pe) protected
Definition at line 37 of file jog_dial.cpp.
References _offset, _spacing, _viewSpan, and mutex.
 {
     QPainter p(this);
     mutex.lock();
     const float s = _offset - _spacing * (int)(_offset/_spacing);
     for (float angle = s - _viewSpan/2.0; angle <= s + _viewSpan/2.0 ; angle += _spacing)
     {
         int pos = (int)(sin(angle * M_PI/180.0f) * width()/2.0 + width()/2.0);
         p.drawLine(pos, 0, pos, height());
     }
   mutex.unlock();
     p.drawLine(0, 0, width(), 0);
     p.drawLine(0, height()-1, width(), height()-1);
 }
void JogDial::valueChanged (float offset) signal
emitted when the offset changes, normalized
Definition at line 94 of file moc_jog_dial.cxx.
Referenced by mouseMoveEvent(), mouseReleaseEvent(), and offset().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 0, _a);
 }
Field Documentation
float JogDial::_offset private
angle offset from start (not normalized)
Definition at line 57 of file jog_dial.h.
Referenced by JogDial(), mouseMoveEvent(), mouseReleaseEvent(), offset(), and paintEvent().
float JogDial::_spacing private
degrees between dial marks
Definition at line 60 of file jog_dial.h.
Referenced by JogDial(), and paintEvent().
float JogDial::_viewSpan private
range of angles to see
Definition at line 63 of file jog_dial.h.
Referenced by JogDial(), mouseMoveEvent(), offset(), and paintEvent().
int JogDial::_x private
start x coordinate for mouse drag
Definition at line 66 of file jog_dial.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QMutex JogDial::mutex protected
Definition at line 49 of file jog_dial.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), offset(), and paintEvent().
The documentation for this class was generated from the following files:
ssl-vision/src/app/gui/jog_dial.h
ssl-vision/build/src/app/gui/moc_jog_dial.cxx
ssl-vision/src/app/gui/jog_dial.cpp