Documentation: grSim/src/sslworld.cpp File Reference
sslworld.cpp File Reference
#include "sslworld.h"
#include <QtGlobal>
#include <QtNetwork>
#include <QDebug>
#include "logger.h"
#include "grSim_Packet.pb.h"
#include "grSim_Commands.pb.h"
#include "grSim_Replacement.pb.h"
#include "messages_robocup_ssl_detection.pb.h"
#include "messages_robocup_ssl_geometry.pb.h"
#include "messages_robocup_ssl_refbox_log.pb.h"
#include "messages_robocup_ssl_wrapper.pb.h"
Macros
#define ROBOT_GRAY 0.4
#define WHEEL_COUNT 4
#define CONVUNIT(x) ((int)(1000*(x)))
#define PI 3.14159265358979323846
Functions
dReal randn_notrig (dReal mu=0.0, dReal sigma=1.0)
dReal randn_trig (dReal mu=0.0, dReal sigma=1.0)
dReal rand0_1 ()
dReal fric (dReal f)
int robotIndex (int robot, int team)
bool wheelCallBack (dGeomID o1, dGeomID o2, PSurface *s)
bool rayCallback (dGeomID o1, dGeomID o2, PSurface *s)
bool ballCallBack (dGeomID o1, dGeomID o2, PSurface *s)
QImage * createBlob (char yb, int i, QImage **res)
QImage * createNumber (int i, int r, int g, int b, int a)
dReal normalizeAngle (dReal a)
Variables
SSLWorld * _w
Macro Definition Documentation
#define CONVUNIT (x) ((int)(1000*(x)))
Definition at line 625 of file sslworld.cpp.
Referenced by SSLWorld::addFieldLinesArcs(), and SSLWorld::generatePacket().
#define PI 3.14159265358979323846
Definition at line 999 of file sslworld.cpp.
Referenced by randn_trig().
#define ROBOT_GRAY 0.4
Definition at line 37 of file sslworld.cpp.
Referenced by SSLWorld::SSLWorld(), and SSLWorld::step().
#define WHEEL_COUNT 4
Definition at line 38 of file sslworld.cpp.
Referenced by SSLWorld::SSLWorld().
Function Documentation
bool ballCallBack (dGeomID o1, dGeomID o2, PSurface * s)
Definition at line 120 of file sslworld.cpp.
References SSLWorld::ball, ConfigWidget::BallFriction(), SSLWorld::cfg, Robot::chassis, PSurface::fdir1, PObject::getBodyDirection(), SSLWorld::robots, PSurface::surface, PObject::tag, PSurface::usefdir1, role._GoToPoint::x, and role._GoToPoint::y.
Referenced by SSLWorld::SSLWorld().
 {
     if (_w->ball->tag!=-1) //spinner adjusting
     {
         dReal x,y,z;
         _w->robots[_w->ball->tag]->chassis->getBodyDirection(x,y,z);
         s->fdir1[0] = x;
         s->fdir1[1] = y;
         s->fdir1[2] = 0;
         s->fdir1[3] = 0;
         s->usefdir1 = true;
         s->surface.mode = dContactMu2 | dContactFDir1 | dContactSoftCFM;
         s->surface.mu = _w->cfg->BallFriction();
         s->surface.mu2 = 0.5;
         s->surface.soft_cfm = 0.002;
     }
     return true;
 }
QImage* createBlob (char yb, int i, QImage ** res)
Definition at line 306 of file sslworld.cpp.
Referenced by SSLWorld::glinit().
 {
     *res = new QImage(QString(":/%1%2").arg(yb).arg(i)+QString(".png"));
     return *res;
 }
QImage* createNumber (int i, int r, int g, int b, int a)
Definition at line 312 of file sslworld.cpp.
References SSLWorld::p.
Referenced by SSLWorld::glinit().
 {
     QImage* img = new QImage(32,32,QImage::Format_ARGB32);
     QPainter *p = new QPainter();
     QBrush br;
     p->begin(img);
     QColor black(0,0,0,0);
     for (int i=0;i<img->width();i++)
         for (int j=0;j<img->height();j++)
         {
             img->setPixel(i,j,black.rgba());
         }
     QColor txtcolor(r,g,b,a);
     QPen pen;
     pen.setStyle(Qt::SolidLine);
     pen.setWidth(3);
     pen.setBrush(txtcolor);
     pen.setCapStyle(Qt::RoundCap);
     pen.setJoinStyle(Qt::RoundJoin);
     p->setPen(pen);
     QFont f;
     f.setBold(true);
     f.setPointSize(26);
     p->setFont(f);
     p->drawText(img->width()/2-15,img->height()/2-15,30,30,Qt::AlignCenter,QString("%1").arg(i));
     p->end();
     delete p;
     return img;
 }
dReal fric (dReal f)
Definition at line 45 of file sslworld.cpp.
Referenced by MainWindow::changeBallGroundSurface(), SSLWorld::SSLWorld(), and wheelCallBack().
 {
     if (f==-1) return dInfinity;
     return f;
 }
dReal normalizeAngle (dReal a)
Definition at line 596 of file sslworld.cpp.
Referenced by role.pass_receive.PassReceive::check_failure(), and SSLWorld::generatePacket().
 {
     if (a>180) return -360+a;
     if (a<-180) return 360+a;
     return a;
 }
dReal rand0_1 ()
Definition at line 1032 of file sslworld.cpp.
Referenced by SSLWorld::generatePacket().
 {
     return (dReal) (rand()) / (dReal) (RAND_MAX);
 }
dReal randn_notrig (dReal mu = 0.0, dReal sigma = 1.0)
Definition at line 958 of file sslworld.cpp.
Referenced by SSLWorld::generatePacket().
{
     if (sigma==0) return mu;
     static bool deviateAvailable=false; //  flag
     static dReal storedDeviate;         //  deviate from previous calculation
     dReal polar, rsquared, var1, var2;
     //  If no deviate has been stored, the polar Box-Muller transformation is
     //  performed, producing two independent normally-distributed random
     //  deviates.  One is stored for the next round, and one is returned.
     if (!deviateAvailable) {
         //  choose pairs of uniformly distributed deviates, discarding those
         //  that don't fall within the unit circle
         do {
             var1=2.0*( dReal(rand())/dReal(RAND_MAX) ) - 1.0;
             var2=2.0*( dReal(rand())/dReal(RAND_MAX) ) - 1.0;
             rsquared=var1*var1+var2*var2;
         } while ( rsquared>=1.0 || rsquared == 0.0);
         //  calculate polar tranformation for each deviate
         polar=sqrt(-2.0*log(rsquared)/rsquared);
         //  store first deviate and set flag
         storedDeviate=var1*polar;
         deviateAvailable=true;
         //  return second deviate
         return var2*polar*sigma + mu;
     }
     //  If a deviate is available from a previous call to this function, it is
     //  returned, and the flag is set to false.
     else {
         deviateAvailable=false;
         return storedDeviate*sigma + mu;
     }
 }
dReal randn_trig (dReal mu = 0.0, dReal sigma = 1.0)
Definition at line 1001 of file sslworld.cpp.
References GVector::dist(), and PI.
{
     static bool deviateAvailable=false; //  flag
     static dReal storedDeviate;         //  deviate from previous calculation
     dReal dist, angle;
     //  If no deviate has been stored, the standard Box-Muller transformation is
     //  performed, producing two independent normally-distributed random
     //  deviates.  One is stored for the next round, and one is returned.
     if (!deviateAvailable) {
         //  choose a pair of uniformly distributed deviates, one for the
         //  distance and one for the angle, and perform transformations
         dist=sqrt( -2.0 * log(dReal(rand()) / dReal(RAND_MAX)) );
         angle=2.0 * PI * (dReal(rand()) / dReal(RAND_MAX));
         //  calculate and store first deviate and set flag
         storedDeviate=dist*cos(angle);
         deviateAvailable=true;
         //  calcaulate return second deviate
         return dist * sin(angle) * sigma + mu;
     }
     //  If a deviate is available from a previous call to this function, it is
     //  returned, and the flag is set to false.
     else {
         deviateAvailable=false;
         return storedDeviate*sigma + mu;
     }
 }
bool rayCallback (dGeomID o1, dGeomID o2, PSurface * s)
Definition at line 91 of file sslworld.cpp.
References SSLWorld::ball, Robot::chassis, PSurface::contactPos, SSLWorld::cursor_x, SSLWorld::cursor_y, SSLWorld::cursor_z, Robot::dummy, PObject::geom, SSLWorld::ground, velocity.pid_::i, SSLWorld::ray, ROBOT_COUNT, SSLWorld::robots, Robot::select_x, Robot::select_y, Robot::select_z, Robot::selected, SSLWorld::selected, and SSLWorld::updatedCursor.
Referenced by SSLWorld::SSLWorld().
 {
     if (!_w->updatedCursor) return false;
     dGeomID obj;
     if (o1==_w->ray->geom) obj = o2;
     else obj = o1;
     for (int i=0;i<ROBOT_COUNT * 2;i++)
     {
         if (_w->robots[i]->chassis->geom==obj || _w->robots[i]->dummy->geom==obj)
         {
             _w->robots[i]->selected = true;
             _w->robots[i]->select_x = s->contactPos[0];
             _w->robots[i]->select_y = s->contactPos[1];
             _w->robots[i]->select_z = s->contactPos[2];
         }
     }
     if (_w->ball->geom==obj)
     {
         _w->selected = -2;
     }
     if (obj==_w->ground->geom)
     {
         _w->cursor_x = s->contactPos[0];
         _w->cursor_y = s->contactPos[1];
         _w->cursor_z = s->contactPos[2];
     }
     return false;
 }
int robotIndex (int robot, int team)
Definition at line 51 of file sslworld.cpp.
References ROBOT_COUNT.
Referenced by MainWindow::changeCurrentRobot(), MainWindow::changeCurrentTeam(), MainWindow::customFPS(), GLWidget::keyPressEvent(), GLWidget::lockCameraToRobot(), GLWidget::moveCurrentRobot(), GLWidget::moveRobotHere(), GLWidget::paintGL(), SSLWorld::recvActions(), GLWidget::reform(), GLWidget::resetCurrentRobot(), GLWidget::resetRobot(), RobotsFomation::resetRobots(), MainWindow::setCurrentRobotPosition(), GLWidget::switchRobotOnOff(), GLWidget::unselectRobot(), MainWindow::update(), and MainWindow::updateRobotLabel().
 {
     if (robot >= ROBOT_COUNT) return -1;
     return robot + team*ROBOT_COUNT;
 }
bool wheelCallBack (dGeomID o1, dGeomID o2, PSurface * s)
Definition at line 57 of file sslworld.cpp.
References SSLWorld::cfg, PSurface::fdir1, fric(), PSurface::id1, PSurface::id2, ConfigWidget::robotSettings, PSurface::surface, PSurface::usefdir1, v, RobotSettings::WheelPerpendicularFriction, and RobotSettings::WheelTangentFriction.
Referenced by SSLWorld::SSLWorld().
 {
     //s->id2 is ground
     const dReal* r; //wheels rotation matrix
     //const dReal* p; //wheels rotation matrix
     if ((o1==s->id1) && (o2==s->id2)) {
         r=dBodyGetRotation(dGeomGetBody(o1));
         //p=dGeomGetPosition(o1);//never read
     } else if ((o1==s->id2) && (o2==s->id1)) {
         r=dBodyGetRotation(dGeomGetBody(o2));
         //p=dGeomGetPosition(o2);//never read
     } else {
         //XXX: in this case we dont have the rotation
         //     matrix, thus we must return
         return false;
     }
     s->surface.mode = dContactFDir1 | dContactMu2  | dContactApprox1 | dContactSoftCFM;
     s->surface.mu = fric(_w->cfg->robotSettings.WheelPerpendicularFriction);
     s->surface.mu2 = fric(_w->cfg->robotSettings.WheelTangentFriction);
     s->surface.soft_cfm = 0.002;
     dVector3 v={0,0,1,1};
     dVector3 axis;
     dMultiply0(axis,r,v,4,3,1);
     dReal l = sqrt(axis[0]*axis[0] + axis[1]*axis[1]);
     s->fdir1[0] = axis[0]/l;
     s->fdir1[1] = axis[1]/l;
     s->fdir1[2] = 0;
     s->fdir1[3] = 0;
     s->usefdir1 = true;
     return true;
 }
Variable Documentation
SSLWorld* _w
Definition at line 40 of file sslworld.cpp.