Documentation: ColorPicker Class Reference
ColorPicker Class Reference
A widget for picking and displaying a single color selection.
#include <colorpicker.h>
Public Member Functions
ColorPicker ()
virtual ~ColorPicker ()
void setColor (rgb color)
Data Fields
Swatch * swatch
QLabel * label
Detailed Description
A widget for picking and displaying a single color selection.
Author
Stefan Zickler, (C) 2008
Definition at line 63 of file colorpicker.h.
Constructor & Destructor Documentation
ColorPicker::ColorPicker ()
Definition at line 23 of file colorpicker.cpp.
References label, setColor(), and swatch.
{
   QHBoxLayout *hboxLayout;
   hboxLayout = new QHBoxLayout ( this );
   hboxLayout->setSpacing ( 4 );
   hboxLayout->setMargin ( 2 );
   swatch = new Swatch();
   label = new QLabel();
   hboxLayout->addWidget ( swatch );
   hboxLayout->addWidget ( label );
   label->setVisible ( true );
   swatch->setVisible ( true );
   setLayout ( hboxLayout );
   /*QFont font = label->font();
   font.setPointSize(7);
   label->setFont(font);*/
   setColor ( rgb ( 128,128,128 ) );
 }
ColorPicker::~ColorPicker () virtual
Definition at line 44 of file colorpicker.cpp.
{
 }
Member Function Documentation
void ColorPicker::setColor (rgb color)
Definition at line 47 of file colorpicker.cpp.
References ColorRGB< num, fmt >::b, ColorRGB< num, fmt >::g, label, ColorRGB< num, fmt >::r, Swatch::setColor(), and swatch.
Referenced by ColorPicker().
{
   swatch->setColor ( color );
   swatch->update();
   label->setText ( QString::number ( color.r ) + " " + QString::number ( color.g ) + " " + QString::number ( color.b ) );
   label->update();
 }
Field Documentation
QLabel* ColorPicker::label
Definition at line 66 of file colorpicker.h.
Referenced by ColorPicker(), and setColor().
Swatch* ColorPicker::swatch
Definition at line 65 of file colorpicker.h.
Referenced by ColorPicker(), and setColor().
The documentation for this class was generated from the following files:
ssl-vision/src/app/gui/colorpicker.h
ssl-vision/src/app/gui/colorpicker.cpp