Documentation: RoboCupField Class Reference
RoboCupField Class Reference
Definition of all variables for a symmetric, regulation-style RoboCup SSL field.
#include <field.h>
Signals
void calibrationChanged ()
Public Member Functions
VarList * getSettings () const
void toProtoBuffer (SSL_GeometryFieldSize &buffer) const
void fromProtoBuffer (const SSL_GeometryFieldSize &buffer)
void loadDefaultsRoboCup2012 ()
RoboCupField ()
~RoboCupField ()
Data Fields
QReadWriteLock field_markings_mutex
VarDouble * field_length
VarDouble * field_width
VarDouble * goal_width
VarDouble * goal_depth
VarDouble * boundary_width
VarInt * var_num_lines
VarInt * var_num_arcs
VarList * field_lines_list
VarList * field_arcs_list
vector< FieldLine * > field_lines
vector< FieldCircularArc * > field_arcs
Protected Slots
void ProcessNewFieldLines ()
void ProcessNewFieldArcs ()
void ResizeFieldLines ()
void ResizeFieldArcs ()
void InjectDefaults ()
void changed ()
void restoreRoboCup ()
Protected Attributes
VarList * settings
VarTrigger * restore
Detailed Description
Definition of all variables for a symmetric, regulation-style RoboCup SSL field.
Author
Stefan Zickler , (C) 2009
Definition at line 124 of file field.h.
Constructor & Destructor Documentation
RoboCupField::RoboCupField ()
Definition at line 275 of file field.cpp.
References FieldConstantsRoboCup2014::kNumFieldArcs, and FieldConstantsRoboCup2014::kNumFieldLines.
{
   settings = new VarList("Field Configuration");
   restore = new VarTrigger("Reset SSL 2014","Reset SSL 2014");
   field_length = new VarDouble(
       "Field Length", FieldConstantsRoboCup2014::kFieldLength);
   field_width = new VarDouble(
       "Field Width", FieldConstantsRoboCup2014::kFieldWidth);
   goal_width = new VarDouble(
       "Goal Width", FieldConstantsRoboCup2014::kGoalWidth);
   goal_depth = new VarDouble(
       "Goal Depth", FieldConstantsRoboCup2014::kGoalDepth);
   boundary_width = new VarDouble(
       "Boundary Width", FieldConstantsRoboCup2014::kBoundaryWidth);
   var_num_lines = new VarInt("Number of Line Segments", kNumFieldLines);
   var_num_arcs = new VarInt("Number of Arcs", kNumFieldArcs);
   field_lines_list = new VarList("Field Lines");
   field_arcs_list = new VarList("Field Arcs");
   settings->addChild(restore);
   settings->addChild(field_length);
   settings->addChild(field_width);
   settings->addChild(goal_width);
   settings->addChild(goal_depth);
   settings->addChild(boundary_width);
   settings->addChild(var_num_lines);
   settings->addChild(var_num_arcs);
   settings->addChild(field_lines_list);
   settings->addChild(field_arcs_list);
   connect(restore,SIGNAL(wasEdited(VarType*)),this,SLOT(restoreRoboCup()));
   connect(var_num_lines, SIGNAL(wasEdited(VarType*)),
           this, SLOT(ResizeFieldLines()));
   connect(var_num_arcs, SIGNAL(wasEdited(VarType*)),
           this, SLOT(ResizeFieldArcs()));
   connect(field_lines_list, SIGNAL(XMLwasRead(VarType*)),
           this, SLOT(ProcessNewFieldLines()));
   connect(field_arcs_list, SIGNAL(XMLwasRead(VarType*)),
           this, SLOT(ProcessNewFieldArcs()));
   connect(settings,SIGNAL(XMLwasRead(VarType*)),
           this, SLOT(InjectDefaults()));
   emit calibrationChanged();
 }
RoboCupField::~RoboCupField ()
Definition at line 320 of file field.cpp.
References velocity.pid_::i.
{
   delete field_length;
   delete field_width;
   delete goal_width;
   delete goal_depth;
   delete boundary_width;
   for (size_t i = 0; i < field_lines.size(); ++i) {
     delete field_lines[i];
   }
   for (size_t i = 0; i < field_arcs.size(); ++i) {
     delete field_arcs[i];
   }
   delete restore;
   delete settings;
 }
Member Function Documentation
void RoboCupField::calibrationChanged () signal
Definition at line 262 of file moc_field.cxx.
 {
     QMetaObject::activate(this, &staticMetaObject, 0, 0);
 }
void RoboCupField::changed () inline protected slot
Definition at line 165 of file field.h.
                  {
     calibrationChanged();
   }
void RoboCupField::fromProtoBuffer (const SSL_GeometryFieldSize & buffer)
VarList* RoboCupField::getSettings () const inline
Definition at line 130 of file field.h.
Referenced by MultiStackRoboCupSSL::MultiStackRoboCupSSL(), and PluginDetectBalls::PluginDetectBalls().
{
     return settings;
   }
void RoboCupField::InjectDefaults () protected slot
Definition at line 522 of file field.cpp.
{
   field_markings_mutex.lockForWrite();
   const size_t num_lines = static_cast<size_t>(var_num_lines->getInt());
   const size_t num_arcs = static_cast<size_t>(var_num_arcs->getInt());
   field_markings_mutex.unlock();
   if (num_lines == 0 && num_arcs == 0) {
     loadDefaultsRoboCup2012();
   }
 }
void RoboCupField::loadDefaultsRoboCup2012 ()
Definition at line 370 of file field.cpp.
References FieldCircularArc::FieldCircularArc(), velocity.pid_::i, FieldConstantsRoboCup2014::kFieldArcs, FieldConstantsRoboCup2014::kFieldLines, FieldConstantsRoboCup2014::kNumFieldArcs, and FieldConstantsRoboCup2014::kNumFieldLines.
{
   field_markings_mutex.lockForWrite();
   var_num_lines->setInt(kNumFieldLines);
   var_num_arcs->setInt(kNumFieldArcs);
   // Delete all old lines.
   vector<VarType*> old_lines = field_lines_list->getChildren();
   for (size_t i = 0; i < old_lines.size(); ++i) {
     field_lines_list->removeChild(old_lines[i]);
   }
   field_lines.clear();
   // Load default lines.
   for (size_t i = 0; i < kNumFieldLines; ++i) {
     field_lines.push_back(new FieldLine(kFieldLines[i]));
     field_lines_list->addChild(field_lines.back()->list);
   }
   // Delete all old arcs.
   vector<VarType*> old_arcs = field_arcs_list->getChildren();
   for (size_t i = 0; i < old_arcs.size(); ++i) {
     field_arcs_list->removeChild(old_arcs[i]);
   }
   field_arcs.clear();
   // Load default arcs.
   for (size_t i = 0; i < kNumFieldArcs; ++i) {
     field_arcs.push_back(new FieldCircularArc(kFieldArcs[i]));
     field_arcs_list->addChild(field_arcs.back()->list);
   }
   field_markings_mutex.unlock();
 }
void RoboCupField::ProcessNewFieldArcs () protected slot
Definition at line 403 of file field.cpp.
References FieldCircularArc::FromVarList(), and velocity.pid_::i.
{
   field_markings_mutex.lockForWrite();
   vector<VarType*> field_arc_entries = field_arcs_list->getChildren();
   for (size_t i = 0; i < field_arc_entries.size(); ++i) {
     VarList* field_arc_list_ptr =
         reinterpret_cast<VarList*>(field_arc_entries[i]);
     bool found = false;
     for (size_t j = 0; !found && j < field_arcs.size(); ++j) {
       found = (field_arcs[j]->list == field_arc_list_ptr);
     }
     if (!found) {
       // This item is not in field_arcs, try to cast and add it.
       FieldCircularArc* new_arc =
           FieldCircularArc::FromVarList(field_arc_list_ptr);
       if (new_arc != NULL) {
         // Cast succeeded, add it.
         field_arcs.push_back(new_arc);
       } else {
         // Cast failed, drop this entry.
         field_arcs_list->removeChild(field_arc_list_ptr);
       }
     }
   }
   if (static_cast<size_t>(field_arcs_list->getChildrenCount()) != field_arcs.size()) {
     fprintf(stderr, "Bug discovered, please report to the developers: "
             "field_arcs_list->getChildrenCount() != field_arcs.size(), @ "
             "%s:%d\n", __FILE__, __LINE__);
   }
   var_num_arcs->setInt(field_arcs.size());
   field_markings_mutex.unlock();
 }
void RoboCupField::ProcessNewFieldLines () protected slot
Definition at line 435 of file field.cpp.
References FieldLine::FromVarList(), and velocity.pid_::i.
{
   field_markings_mutex.lockForWrite();
   vector<VarType*> field_line_entries = field_lines_list->getChildren();
   for (size_t i = 0; i < field_line_entries.size(); ++i) {
     VarList* field_line_list_ptr =
         reinterpret_cast<VarList*>(field_line_entries[i]);
     bool found = false;
     for (size_t j = 0; !found && j < field_lines.size(); ++j) {
       found = (field_lines[j]->list == field_line_list_ptr);
     }
     if (!found) {
       // This item is not in field_lines, try to cast and add it.
       FieldLine* new_line = FieldLine::FromVarList(field_line_list_ptr);
       if (new_line != NULL) {
         // Cast succeeded, add it.
         field_lines.push_back(new_line);
       } else {
         // Cast failed, drop this entry.
         field_lines_list->removeChild(field_line_list_ptr);
       }
     }
   }
   if (static_cast<size_t>(field_lines_list->getChildrenCount()) != field_lines.size()) {
     fprintf(stderr, "Bug discovered, please report to the developers: "
             "field_lines_list->getChildrenCount() != field_lines.size(), @ "
             "%s:%d\n", __FILE__, __LINE__);
   }
   var_num_lines->setInt(field_lines.size());
   field_markings_mutex.unlock();
 }
void RoboCupField::ResizeFieldArcs () protected slot
Definition at line 494 of file field.cpp.
References FieldCircularArc::FieldCircularArc(), velocity.pid_::i, FieldCircularArc::list, FieldCircularArc::name, and StringPrintf().
{
   field_markings_mutex.lockForWrite();
   // Resize the field_arcs list.
   const size_t new_num_arcs = static_cast<size_t>(var_num_arcs->getInt());
   const size_t old_num_arcs = field_arcs.size();
   if (new_num_arcs < old_num_arcs) {
     // Remove the last few arc segments and their associated VarType objects.
     for (size_t i = new_num_arcs; i < old_num_arcs; ++i) {
       field_arcs_list->removeChild(field_arcs[i]->list);
       delete field_arcs[i];
     }
     field_arcs.resize(new_num_arcs);
   }
   if (new_num_arcs > old_num_arcs) {
     for (size_t i = old_num_arcs; i < new_num_arcs; ++i) {
       const string name = StringPrintf("Line %d", static_cast<int>(i));
       field_arcs.push_back(new FieldCircularArc(name));
       field_arcs_list->addChild(field_arcs[i]->list);
     }
   }
   if (static_cast<size_t>(field_arcs_list->getChildrenCount()) != field_arcs.size()) {
     fprintf(stderr, "Bug discovered, please report to the developers: "
             "field_arcs_list->getChildrenCount() != field_arcs.size(), @ "
             "%s:%d\n", __FILE__, __LINE__);
   }
   field_markings_mutex.unlock();
 }
void RoboCupField::ResizeFieldLines () protected slot
Definition at line 466 of file field.cpp.
References velocity.pid_::i, FieldCircularArc::list, FieldCircularArc::name, and StringPrintf().
{
   field_markings_mutex.lockForWrite();
   // Resize the field_lines list.
   const size_t new_num_lines = static_cast<size_t>(var_num_lines->getInt());
   const size_t old_num_lines = field_lines.size();
   if (new_num_lines < old_num_lines) {
     // Remove the last few line segments and their associated VarType objects.
     for (size_t i = new_num_lines; i < old_num_lines; ++i) {
       field_lines_list->removeChild(field_lines[i]->list);
       delete field_lines[i];
     }
     field_lines.resize(new_num_lines);
   }
   if (new_num_lines > old_num_lines) {
     for (size_t i = old_num_lines; i < new_num_lines; ++i) {
       const string name = StringPrintf("Line %d", static_cast<int>(i));
       field_lines.push_back(new FieldLine(name));
       field_lines_list->addChild(field_lines[i]->list);
     }
   }
   if (static_cast<size_t>(field_lines_list->getChildrenCount()) != field_lines.size()) {
     fprintf(stderr, "Bug discovered, please report to the developers: "
             "field_lines_list->getChildrenCount() != field_lines.size(), @ "
             "%s:%d\n", __FILE__, __LINE__);
   }
   field_markings_mutex.unlock();
 }
void RoboCupField::restoreRoboCup () inline protected slot
Definition at line 168 of file field.h.
{
     loadDefaultsRoboCup2012();
   }
void RoboCupField::toProtoBuffer (SSL_GeometryFieldSize & buffer) const
Definition at line 336 of file field.cpp.
References FieldCircularArc::a1, FieldCircularArc::a2, FieldCircularArc::center_x, FieldCircularArc::center_y, VarTypes::VarDoubleVal::getDouble(), VarTypes::VarStringVal::getString(), velocity.pid_::i, FieldLine::name, FieldCircularArc::name, FieldLine::p1_x, FieldLine::p1_y, FieldLine::p2_x, FieldLine::p2_y, FieldCircularArc::radius, FieldLine::thickness, and FieldCircularArc::thickness.
Referenced by PluginPublishGeometry::sendGeometry(), and PluginLegacyPublishGeometry::sendGeometry().
{
   field_markings_mutex.lockForRead();
   buffer.Clear();
   buffer.set_field_length(field_length->getDouble());
   buffer.set_field_width(field_width->getDouble());
   buffer.set_goal_width(goal_width->getDouble());
   buffer.set_goal_depth(goal_depth->getDouble());
   buffer.set_boundary_width(boundary_width->getDouble());
   for (size_t i = 0; i < field_lines.size(); ++i) {
     const FieldLine& line = *(field_lines[i]);
     SSL_FieldLineSegment proto_line;
     proto_line.set_name(line.name->getString());
     proto_line.mutable_p1()->set_x(line.p1_x->getDouble());
     proto_line.mutable_p1()->set_y(line.p1_y->getDouble());
     proto_line.mutable_p2()->set_x(line.p2_x->getDouble());
     proto_line.mutable_p2()->set_y(line.p2_y->getDouble());
     proto_line.set_thickness(line.thickness->getDouble());
     *(buffer.add_field_lines()) = proto_line;
   }
   for (size_t i = 0; i < field_arcs.size(); ++i) {
     const FieldCircularArc& arc = *(field_arcs[i]);
     SSL_FieldCicularArc proto_arc;
     proto_arc.set_name(arc.name->getString());
     proto_arc.mutable_center()->set_x(arc.center_x->getDouble());
     proto_arc.mutable_center()->set_y(arc.center_y->getDouble());
     proto_arc.set_radius(arc.radius->getDouble());
     proto_arc.set_a1(arc.a1->getDouble());
     proto_arc.set_a2(arc.a2->getDouble());
     proto_arc.set_thickness(arc.thickness->getDouble());
     *(buffer.add_field_arcs()) = proto_arc;
   }
   field_markings_mutex.unlock();
 }
Field Documentation
VarDouble* RoboCupField::boundary_width
Definition at line 144 of file field.h.
Referenced by FieldFilter::update().
vector<FieldCircularArc*> RoboCupField::field_arcs
Definition at line 150 of file field.h.
Referenced by PluginCameraCalibration::detectEdges(), PluginVisualize::DrawCalibrationResult(), PluginVisualize::DrawSearchCorridors(), and PluginLegacyPublishGeometry::GetFieldCircularArcRadius().
VarList* RoboCupField::field_arcs_list
Definition at line 148 of file field.h.
VarDouble* RoboCupField::field_length
Definition at line 140 of file field.h.
Referenced by PluginLegacySSLNetworkOutput::DoubleSizeToSingleSize(), and FieldFilter::update().
vector<FieldLine*> RoboCupField::field_lines
Definition at line 149 of file field.h.
Referenced by PluginCameraCalibration::detectEdges(), PluginLegacySSLNetworkOutput::DoubleSizeToSingleSize(), PluginVisualize::DrawCalibrationResult(), PluginVisualize::DrawSearchCorridors(), PluginLegacyPublishGeometry::GetFieldLineLength(), and PluginLegacyPublishGeometry::GetFieldLineThickness().
VarList* RoboCupField::field_lines_list
Definition at line 147 of file field.h.
QReadWriteLock RoboCupField::field_markings_mutex mutable
Definition at line 139 of file field.h.
Referenced by PluginCameraCalibration::detectEdges(), PluginVisualize::DrawCalibrationResult(), and PluginVisualize::DrawSearchCorridors().
VarDouble* RoboCupField::field_width
Definition at line 141 of file field.h.
Referenced by FieldFilter::update().
VarDouble* RoboCupField::goal_depth
Definition at line 143 of file field.h.
Referenced by FieldFilter::update().
VarDouble* RoboCupField::goal_width
Definition at line 142 of file field.h.
Referenced by FieldFilter::update().
VarTrigger* RoboCupField::restore protected
Definition at line 128 of file field.h.
VarList* RoboCupField::settings protected
Definition at line 127 of file field.h.
VarInt* RoboCupField::var_num_arcs
Definition at line 146 of file field.h.
VarInt* RoboCupField::var_num_lines
Definition at line 145 of file field.h.
The documentation for this class was generated from the following files:
ssl-vision/src/shared/util/field.h
ssl-vision/build/src/shared/util/moc_field.cxx
ssl-vision/src/shared/util/field.cpp