Documentation: RoboCupSSLClient Class Reference
RoboCupSSLClient Class Reference
#include <robocup_ssl_client.h>
Public Member Functions
RoboCupSSLClient (const quint16 &port=10002, const string &net_address="224.5.23.2", const string &net_interface="")
RoboCupSSLClient (const quint16 &port, const QHostAddress &, const QNetworkInterface &)
~RoboCupSSLClient ()
bool open ()
void close ()
bool receive (SSL_WrapperPacket &packet)
void changePort (quint16 port)
RoboCupSSLClient (int port=10006, string net_ref_address="224.5.23.2", string net_ref_interface="")
~RoboCupSSLClient ()
bool open (bool blocking=false)
void close ()
bool receive (SSL_WrapperPacket &packet)
RoboCupSSLClient (int port=10006, string net_ref_address="224.5.23.2", string net_ref_interface="")
~RoboCupSSLClient ()
bool open (bool blocking=false)
void close ()
bool receive (SSL_WrapperPacket &packet)
Protected Attributes
QUdpSocket * _socket
QMutex mutex
quint16 _port
QHostAddress * _net_address
QNetworkInterface * _net_interface
char * in_buffer
Net::UDP mc
int _port
string _net_address
string _net_interface
Static Protected Attributes
static const int MaxDataGramSize = 65536
Detailed Description
Author
Author Name
Definition at line 36 of file robocup_ssl_client.h.
Constructor & Destructor Documentation
RoboCupSSLClient::RoboCupSSLClient (const quint16 & port = 10002, const string & net_address = "224.5.23.2", const string & net_interface = "")
Definition at line 28 of file robocup_ssl_client.cpp.
                                                                                                                  :
     _socket(new QUdpSocket()),
     _port(port),
     _net_address(new QHostAddress(QString(net_address.c_str()))),
     _net_interface(new QNetworkInterface(QNetworkInterface::interfaceFromName(QString(net_interface.c_str()))))
 {
 }
RoboCupSSLClient::RoboCupSSLClient (const quint16 & port, const QHostAddress & addr, const QNetworkInterface & iface)
Definition at line 36 of file robocup_ssl_client.cpp.
                                                                                                                    :
     _socket(new QUdpSocket()),
     _port(port),
     _net_address(new QHostAddress(addr)),
     _net_interface(new QNetworkInterface(iface))
 {
 }
RoboCupSSLClient::~RoboCupSSLClient ()
Definition at line 44 of file robocup_ssl_client.cpp.
References _net_address, _net_interface, and _socket.
Referenced by RoboCupSSLClient().
 {
     delete _socket;
     delete _net_address;
     delete _net_interface;
 }
RoboCupSSLClient::RoboCupSSLClient (int port = 10006, string net_ref_address = "224.5.23.2", string net_ref_interface = "")
Definition at line 23 of file robocup_ssl_client.cpp.
References _net_address, _net_interface, _port, close(), Net::UDP::close(), in_buffer, mc, port(), and ~RoboCupSSLClient().
 {
   _port=port;
   _net_address=net_address;
   _net_interface=net_interface;
   in_buffer=new char[65536];
 }
RoboCupSSLClient::~RoboCupSSLClient ()
RoboCupSSLClient::RoboCupSSLClient (int port = 10006, string net_ref_address = "224.5.23.2", string net_ref_interface = "")
RoboCupSSLClient::~RoboCupSSLClient ()
Member Function Documentation
void RoboCupSSLClient::changePort (quint16 port) inline
Definition at line 52 of file robocup_ssl_client.h.
References _port, and port().
 {_port = port;}
void RoboCupSSLClient::close ()
void RoboCupSSLClient::close ()
Definition at line 51 of file robocup_ssl_client.cpp.
References _net_address, _net_interface, and _socket.
Referenced by open(), and RoboCupSSLClient().
 {
     if(_socket->state() == QUdpSocket::BoundState)
         _socket->leaveMulticastGroup(*_net_address, *_net_interface);
 }
void RoboCupSSLClient::close ()
bool RoboCupSSLClient::open (bool blocking = false)
Definition at line 43 of file robocup_ssl_client.cpp.
References _net_address, _net_interface, _port, Net::UDP::addMulticast(), close(), in_buffer, MaxDataGramSize, mc, Net::UDP::open(), receive(), Net::UDP::recv(), Net::Address::setAny(), and Net::Address::setHost().
{
   close();
   if(!mc.open(_port,true,true,blocking)) {
     fprintf(stderr,"Unable to open UDP network port: %d\n",_port);
     fflush(stderr);
     return(false);
   }
   Net::Address multiaddr,interface;
   multiaddr.setHost(_net_address.c_str(),_port);
   if(_net_interface.length() > 0){
     interface.setHost(_net_interface.c_str(),_port);
   }else{
     interface.setAny();
   }
   if(!mc.addMulticast(multiaddr,interface)) {
     fprintf(stderr,"Unable to setup UDP multicast\n");
     fflush(stderr);
     return(false);
   }
   return(true);
 }
bool RoboCupSSLClient::open ()
Definition at line 57 of file robocup_ssl_client.cpp.
References _net_address, _net_interface, _port, _socket, and close().
Referenced by main(), MyThread::run(), and ViewUpdateThread::run().
 {
     close();
     if(!_socket->bind(_port, QUdpSocket::ShareAddress | QUdpSocket::ReuseAddressHint)) {
         cerr << "Unable to bind UDP socket on port " << _port << ". "
              << _socket->errorString().toStdString() << '.' << endl;
         return false;
     }
     if(!_socket->joinMulticastGroup(*_net_address, *_net_interface)) {
         cerr << "Unable to join UDP multicast on "
              << _net_address->toString().toStdString() << ':' << _port << ". "
              << _socket->errorString().toStdString().c_str() << '.' << endl;
         return false;
     }
     return true;
 }
bool RoboCupSSLClient::open (bool blocking = false)
bool RoboCupSSLClient::receive (SSL_WrapperPacket & packet)
bool RoboCupSSLClient::receive (SSL_WrapperPacket & packet)
Definition at line 76 of file robocup_ssl_client.cpp.
References _socket, and mutex.
Referenced by ViewUpdateThread::execute(), main(), open(), and MyThread::run().
 {
     if(_socket->state() == QUdpSocket::BoundState && _socket->hasPendingDatagrams()) {
         QByteArray datagram;
         mutex.lock();
         datagram.resize(_socket->pendingDatagramSize());
         _socket->readDatagram(datagram.data(), datagram.size());
         mutex.unlock();
         //decode packet:
         return packet.ParseFromArray(datagram.data(), datagram.size());
     } else {
         return false;
     }
 }
bool RoboCupSSLClient::receive (SSL_WrapperPacket & packet)
Field Documentation
string RoboCupSSLClient::_net_address protected
Definition at line 40 of file robocup_ssl_client.h.
string RoboCupSSLClient::_net_address protected
Definition at line 58 of file robocup_ssl_client.h.
Referenced by close(), open(), RoboCupSSLClient(), and ~RoboCupSSLClient().
string RoboCupSSLClient::_net_interface protected
Definition at line 41 of file robocup_ssl_client.h.
string RoboCupSSLClient::_net_interface protected
Definition at line 59 of file robocup_ssl_client.h.
Referenced by close(), open(), RoboCupSSLClient(), and ~RoboCupSSLClient().
int RoboCupSSLClient::_port protected
Definition at line 39 of file robocup_ssl_client.h.
int RoboCupSSLClient::_port protected
Definition at line 57 of file robocup_ssl_client.h.
Referenced by open(), and RoboCupSSLClient().
QUdpSocket* RoboCupSSLClient::_socket protected
Definition at line 55 of file robocup_ssl_client.h.
Referenced by close(), open(), receive(), and ~RoboCupSSLClient().
char * RoboCupSSLClient::in_buffer protected
Definition at line 37 of file robocup_ssl_client.h.
Referenced by open(), and RoboCupSSLClient().
static const int RoboCupSSLClient::MaxDataGramSize = 65536 static protected
Definition at line 36 of file robocup_ssl_client.h.
Referenced by open().
Net::UDP RoboCupSSLClient::mc protected
Definition at line 38 of file robocup_ssl_client.h.
Referenced by open(), and RoboCupSSLClient().
QMutex RoboCupSSLClient::mutex protected
Definition at line 56 of file robocup_ssl_client.h.
Referenced by receive().
The documentation for this class was generated from the following files:
grSim/include/net/robocup_ssl_client.h
grSim/src/net/robocup_ssl_client.cpp