Documentation: Net::UDP Class Reference
Net::UDP Class Reference
#include <netraw.h>
Public Member Functions
UDP ()
~UDP ()
bool open (int port=0, bool share_port_for_multicasting=false, bool multicast_include_localhost=false, bool blocking=false)
bool addMulticast (const Address &multiaddr, const Address &interface)
void close ()
bool isOpen () const
bool send (const void *data, int length, const Address &dest)
int recv (void *data, int length, Address &src)
bool wait (int timeout_ms=-1) const
bool havePendingData () const
int getFd () const
UDP ()
~UDP ()
bool open (int port=0, bool share_port_for_multicasting=false, bool multicast_include_localhost=false, bool blocking=false)
bool addMulticast (const Address &multiaddr, const Address &interface)
void close ()
bool isOpen () const
bool send (const void *data, int length, const Address &dest)
int recv (void *data, int length, Address &src)
bool wait (int timeout_ms=-1) const
bool havePendingData () const
int getFd () const
Data Fields
unsigned sent_packets
unsigned sent_bytes
unsigned recv_packets
unsigned recv_bytes
Private Attributes
int fd
Detailed Description
Definition at line 54 of file netraw.h.
Constructor & Destructor Documentation
Net::UDP::UDP () inline
Definition at line 62 of file netraw.h.
 {fd=-1; close();}
Net::UDP::~UDP () inline
Definition at line 63 of file netraw.h.
References port().
 {close();}
Net::UDP::UDP () inline
Definition at line 62 of file netraw.h.
 {fd=-1; close();}
Net::UDP::~UDP () inline
Definition at line 63 of file netraw.h.
References port().
 {close();}
Member Function Documentation
bool Net::UDP::addMulticast (const Address & multiaddr, const Address & interface)
Definition at line 145 of file netraw.cpp.
References role.sGoalie::debug(), and Net::Address::getInAddr().
Referenced by RoboCupSSLClient::open(), and RoboCupSSLServer::open().
 {
   static const bool debug = false;
   struct ip_mreq imreq;
   imreq.imr_multiaddr.s_addr = multiaddr.getInAddr();
   imreq.imr_interface.s_addr = interface.getInAddr();
   if(debug){
     printf("0x%08X 0x%08X\n",
            (unsigned)interface.getInAddr(),
            (unsigned)INADDR_ANY);
   }
   int ret = setsockopt(fd, IPPROTO_IP, IP_ADD_MEMBERSHIP,
                        &imreq, sizeof(imreq));
   if(debug) printf("ret=%d\n",ret);
   if(ret != 0)
     return false;
   //set multicast output interface
   ret = setsockopt(fd, IPPROTO_IP, IP_MULTICAST_IF,
                    &imreq.imr_interface.s_addr, sizeof(imreq.imr_interface.s_addr));
   if(debug) printf("ret=%d\n",ret);
   return(ret == 0);
 }
bool Net::UDP::addMulticast (const Address & multiaddr, const Address & interface)
void Net::UDP::close ()
Definition at line 172 of file netraw.cpp.
Referenced by RoboCupSSLServer::close(), RoboCupSSLClient::RoboCupSSLClient(), and wait().
 {
   if(fd >= 0) ::close(fd);
   fd = -1;
   sent_packets = 0;
   sent_bytes   = 0;
   recv_packets = 0;
   recv_bytes   = 0;
 }
void Net::UDP::close ()
int Net::UDP::getFd () const inline
Definition at line 77 of file netraw.h.
     {return(fd);}
int Net::UDP::getFd () const inline
Definition at line 77 of file netraw.h.
     {return(fd);}
bool Net::UDP::havePendingData () const inline
Definition at line 74 of file netraw.h.
     {return(wait(0));}
bool Net::UDP::havePendingData () const inline
Definition at line 74 of file netraw.h.
     {return(wait(0));}
bool Net::UDP::isOpen () const inline
Definition at line 68 of file netraw.h.
     {return(fd >= 0);}
bool Net::UDP::isOpen () const inline
Definition at line 68 of file netraw.h.
     {return(fd >= 0);}
bool Net::UDP::open (int port = 0, bool share_port_for_multicasting = false, bool multicast_include_localhost = false, bool blocking = false)
bool Net::UDP::open (int port = 0, bool share_port_for_multicasting = false, bool multicast_include_localhost = false, bool blocking = false)
Definition at line 83 of file netraw.cpp.
Referenced by RoboCupSSLClient::open(), RoboCupSSLServer::open(), and wait().
 {
   const int TTL = 32;
   // open the socket
   if(fd >= 0) ::close(fd);
   fd = socket(PF_INET, SOCK_DGRAM, 0);
   // set socket as non-blocking
   int flags = fcntl(fd, F_GETFL, 0);
   if(flags < 0) flags = 0;
   fcntl(fd, F_SETFL, flags | (blocking ? 0 : O_NONBLOCK));
   if (share_port_for_multicasting) {
     int reuse=1;
     if(setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, (const char*)&reuse,sizeof(reuse))!=0) {
       fprintf(stderr,"ERROR WHEN SETTING SO_REUSEADDR ON UDP SOCKET\n");
       fflush(stderr);
     }
     /*if(setsockopt(fd, SOL_SOCKET, SO_REUSEPORT, 1)!=0) {
       fprintf(stderr,"ERROR WHEN SETTING SO_REUSEPORT ON UDP SOCKET\n");
       fflush(stderr);
     }*/
   }
   if (multicast_include_localhost) {
     int yes = 1;
     // allow packets to be received on this host
     if (setsockopt(fd, IPPROTO_IP, IP_MULTICAST_LOOP, (const char*)&yes, sizeof(yes))!=0) {
         fprintf(stderr,"ERROR WHEN SETTING IP_MULTICAST_LOOP ON UDP SOCKET\n");
         fflush(stderr);
     }
   }
     // sets the TTL value so routing of the packet is possible, if needed.
   int ret = setsockopt(fd, IPPROTO_IP, IP_MULTICAST_TTL, &TTL, sizeof(TTL));
   if(ret != 0)
   {
     printf("ERROR %d WHEN SETTING IP_MULTICAST_TTL\n", ret);
     return false;
   }
   // bind socket to port if nonzero
   if(port != 0){
     sockaddr_in sockname;
     sockname.sin_family = AF_INET;
     sockname.sin_addr.s_addr = htonl(INADDR_ANY);
     sockname.sin_port = htons(port);
     bind(fd,(struct sockaddr*)(&sockname),sizeof(sockname));
   }
   /*
   // allow port reuse (for when a program is quickly restarted)
   // (not sure we really need this)
   int one = 1;
   setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
   */
   return(true);
 }
int Net::UDP::recv (void * data, int length, Address & src)
Definition at line 195 of file netraw.cpp.
References Net::Address::addr, and Net::Address::addr_len.
Referenced by RoboCupSSLClient::open(), and wait().
 {
   src.addr_len = sizeof(src.addr);
   int len = recvfrom(fd,data,length,0,&src.addr,&src.addr_len);
   if(len > 0){
     recv_packets++;
     recv_bytes += len;
   }
   return(len);
 }
int Net::UDP::recv (void * data, int length, Address & src)
bool Net::UDP::send (const void * data, int length, const Address & dest)
bool Net::UDP::send (const void * data, int length, const Address & dest)
Definition at line 183 of file netraw.cpp.
References Net::Address::addr, and Net::Address::addr_len.
Referenced by RoboCupSSLServer::sendWrapperPacket(), and wait().
 {
   int len = sendto(fd,data,length,0,&dest.addr,dest.addr_len);
   if(len > 0){
     sent_packets++;
     sent_bytes += len;
   }
   return(len == length);
 }
bool Net::UDP::wait (int timeout_ms = -1) const
Definition at line 208 of file netraw.cpp.
References Net::Address::addr, close(), main(), open(), port(), Net::Address::print(), recv(), send(), Net::Address::setHost(), and wait().
Referenced by wait().
 {
   pollfd pfd;
   pfd.fd = fd;
   pfd.events = POLLIN;
   pfd.revents = 0;
   return(poll(&pfd,1,timeout_ms) == 1);
 }
bool Net::UDP::wait (int timeout_ms = -1) const
Field Documentation
int Net::UDP::fd private
Definition at line 55 of file netraw.h.
unsigned Net::UDP::recv_bytes
Definition at line 60 of file netraw.h.
unsigned Net::UDP::recv_packets
Definition at line 59 of file netraw.h.
unsigned Net::UDP::sent_bytes
Definition at line 58 of file netraw.h.
unsigned Net::UDP::sent_packets
Definition at line 57 of file netraw.h.
The documentation for this class was generated from the following files:
ssl-vision/src/shared/net/netraw.h
ssl-vision/src/shared/net/netraw.cpp