Documentation: GVector Namespace Reference
GVector Namespace Reference
Data Structures
class vector2d
class vector3d
Functions
template<class num >
num distance_to_line (const vector2d< num > x0, const vector2d< num > x1, const vector2d< num > p)
template<class num >
num offset_to_line (const vector2d< num > x0, const vector2d< num > x1, const vector2d< num > p)
template<class num >
num offset_along_line (const vector2d< num > x0, const vector2d< num > x1, const vector2d< num > p)
template<class num >
vector2d< num > segment_near_line (const vector2d< num > a0, const vector2d< num > a1, const vector2d< num > b0, const vector2d< num > b1)
template<class num >
vector2d< num > intersection (const vector2d< num > a1, const vector2d< num > a2, const vector2d< num > b1, const vector2d< num > b2)
template<class num >
num vertex_angle (const vector2d< num > a, const vector2d< num > b, const vector2d< num > c)
template<class num >
bool CalcCircle (vector2d< num > &cen, num &rad, const vector2d< num > p1, const vector2d< num > p2, const vector2d< num > p3)
template<class vector >
vector interpolate (const vector x0, const vector x1, double t)
template<class vector >
vector point_on_line (const vector x0, const vector x1, const vector p)
template<class vector >
vector point_on_segment (const vector x0, const vector x1, const vector p)
template<class vector >
double distance_to_segment (const vector x0, const vector x1, const vector p)
template<class vector >
double closest_point_time (const vector x1, const vector v1, const vector x2, const vector v2)
template<class vector >
double distance_seg_to_seg (vector s1a, vector s1b, vector s2a, vector s2b)
template<class vector >
double ray_plane_intersect (vector pOrigin, vector pNormal, vector rOrigin, vector rVector)
template<class vector , class real >
real ray_sphere_intersect (vector rO, vector rV, vector sO, real sR)
template<class vector , class real >
bool CircleTangentDir (vector cen, real rad, vector p, vector &left, vector &right)
template<class vector , class real >
bool CircleTangent (vector cen, real rad, vector p, vector &left, vector &right)
template<class vector , class real >
vector LineMidpointAngular (const vector &p0, const vector &p1, real &dist)
template<class num >
num dot (const vector3d< num > a, const vector3d< num > b)
template<class num >
num absdot (const vector3d< num > a, const vector3d< num > b)
template<class num >
vector3d< num > cross (const vector3d< num > a, const vector3d< num > b)
template<class num1 , class num2 >
vector3d< num2 > operator* (num1 f, const vector3d< num2 > &a)
template<class num >
vector3d< num > abs (vector3d< num > a)
template<class num >
vector3d< num > min (vector3d< num > a, vector3d< num > b)
template<class num >
vector3d< num > max (vector3d< num > a, vector3d< num > b)
template<class num >
vector3d< num > bound (vector3d< num > v, num low, num high)
template<class num >
double shortest_angle (const vector3d< num > a, const vector3d< num > b)
template<class num >
vector3d< num > shortest_axis (const vector3d< num > a, const vector3d< num > b)
template<class num >
num dist (const vector3d< num > a, const vector3d< num > b)
template<class num >
num distance (const vector3d< num > a, const vector3d< num > b)
template<class num >
num sqdist (const vector3d< num > a, const vector3d< num > b)
template<class num >
num sqdistance (const vector3d< num > a, const vector3d< num > b)
template<class num >
num distance_to_line (const vector3d< num > x0, const vector3d< num > x1, const vector3d< num > p)
template<class num >
num dot (const vector2d< num > a, const vector2d< num > b)
template<class num >
num cosine (const vector2d< num > a, const vector2d< num > b)
template<class num1 , class num2 >
vector2d< num2 > operator* (num1 f, const vector2d< num2 > &a)
template<class num >
vector2d< num > abs (vector2d< num > a)
template<class num >
vector2d< num > min (vector2d< num > a, vector2d< num > b)
template<class num >
vector2d< num > max (vector2d< num > a, vector2d< num > b)
template<class num >
vector2d< num > bound (vector2d< num > v, num low, num high)
template<class num >
num dist (const vector2d< num > a, const vector2d< num > b)
template<class num >
num distance (const vector2d< num > a, const vector2d< num > b)
template<class num >
num sqdist (const vector2d< num > a, const vector2d< num > b)
template<class num >
num sqdistance (const vector2d< num > a, const vector2d< num > b)
Function Documentation
template<class num > vector3d<num> GVector::abs (vector3d< num > a) inline
Definition at line 311 of file gvector.h.
References GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
Referenced by Sobel::centerOfLine(), check(), role.pass_receive.PassReceive::errors_below_thresholds(), role._GoToPoint::execute(), role._GoToPoint_::execute(), tactics._Goalie__.TGoalie::execute(), velocity.run_w::Get_Omega(), role.Pass_Receive.PassReceive::is_steady(), ViewUpdateThread::run(), and utils.math_functions::vicinity_theta().
 {
   a.x = ::fabs(a.x);
   a.y = ::fabs(a.y);
   a.z = ::fabs(a.z);
   return(a);
 }
template<class num > vector2d<num> GVector::abs (vector2d< num > a) inline
Definition at line 900 of file gvector.h.
References GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
 {
   a.x = ::fabs(a.x);
   a.y = ::fabs(a.y);
   return(a);
 }
template<class num > num GVector::absdot (const vector3d< num > a, const vector3d< num > b)
Definition at line 180 of file gvector.h.
References GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
 {
   return(fabs(a.x*b.x) + fabs(a.y*b.y) + fabs(a.z*b.z));
 }
template<class num > vector3d<num> GVector::bound (vector3d< num > v, num low, num high) inline
Definition at line 345 of file gvector.h.
References GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
Referenced by CMVision::Histogram::addBox(), bound(), GVector::vector2d< float >::heading(), PluginDetectBalls::process(), Conversions::rgb2yuv(), Conversions::yuv2rgb(), and GlobalV4Linstance::yuv2rgb().
 {
   v.x = ::bound(v.x,low,high);
   v.y = ::bound(v.y,low,high);
   v.z = ::bound(v.z,low,high);
   return(v);
 }
template<class num > vector2d<num> GVector::bound (vector2d< num > v, num low, num high) inline
Definition at line 931 of file gvector.h.
References bound(), GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
 {
   v.x = ::bound(v.x,low,high);
   v.y = ::bound(v.y,low,high);
   return(v);
 }
template<class num > bool GVector::CalcCircle (vector2d< num > & cen, num & rad, const vector2d< num > p1, const vector2d< num > p2, const vector2d< num > p3)
Definition at line 115 of file geomalgo.h.
References dist(), GVector::vector2d< num >::dot(), EPSILON, GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
 {
   vector2d<num> a,b;
   num da,db;
   // edge vectors
   a = (p2 - p1);
   b = (p3 - p2);
   // dot products of midpoint of each edge vector
   da = a.dot(p1 + p2) * 0.5;
   db = b.dot(p2 + p3) * 0.5;
   /*
   We want to find a point c on each line, so:
     [ a.x a.y ] [c.x] = [da]
     [ b.x b.y ] [c.y]   [db]
   We can invert the matrix to do that, and multiply it on the left of both
   side.  That yeilds a direct expression for center point c.
   */
   num det = a.x * b.y - a.y * b.x;
   if(fabs(det) < EPSILON) return(false);
   cen.x = ( b.y*da + -a.y*db) / det;
   cen.y = (-b.x*da +  a.x*db) / det;
   // use averaging to get a more numerically accurate radius
   // rad = sqrt((sqdist(cen,p1) + sqdist(cen,p2) + sqdist(cen,p3)) / 3.0);
   rad = dist(cen,p1);
   if(false){
     printf("%f %f, %f %f\n",
            a.dot(cen),da,
            b.dot(cen),db);
   }
   return(true);
 }
template<class vector , class real > bool GVector::CircleTangent (vector cen, real rad, vector p, vector & left, vector & right)
Definition at line 421 of file geomalgo.h.
References t.
 {
   vector delta,basis;
   vector tl,tr;
   double d2,l,t;
   // l,r,d form a right triangle where l*l + rad*rad = d*d = d2
   delta = cen - p;
   d2 = delta.sqlength();
   t = d2 - rad*rad;
   if(t < 0) return(false); // inside circle
   // set basis as sin/d,cos/d
   l = sqrt(t);
   basis.set(l/d2,rad/d2);
   // project to get left and right tangents
   // resulting vectors are normalized
   left  = basis.project_out(delta)*l;
   basis.y = -basis.y;
   right = basis.project_out(delta)*l;
   return(true);
 }
template<class vector , class real > bool GVector::CircleTangentDir (vector cen, real rad, vector p, vector & left, vector & right)
Definition at line 393 of file geomalgo.h.
References t.
 {
   vector delta,basis;
   vector tl,tr;
   double d2,l,t;
   // l,r,d form a right triangle where l*l + rad*rad = d*d = d2
   delta = cen - p;
   d2 = delta.sqlength();
   t = d2 - rad*rad;
   if(t < 0) return(false); // inside circle
   // set basis as sin/d,cos/d
   l = sqrt(t);
   basis.set(l/d2,rad/d2);
   // project to get left and right tangents
   // resulting vectors are normalized
   left = basis.project_out(delta);
   basis.y = -basis.y;
   right = basis.project_out(delta);
   return(true);
 }
template<class vector > double GVector::closest_point_time (const vector x1, const vector v1, const vector x2, const vector v2)
Definition at line 234 of file geomalgo.h.
References EPSILON, t, and v.
 {
   vector v  = v1 - v2;
   double sl = v.sqlength();
   double t;
   if(sl < EPSILON) return(0.0); // parallel tracks, any time is ok.
   t = -v.dot(x1 - x2) / sl;
   if(t < 0.0) return(0.0); // nearest time was in the past, now
                            // is closest point from now on.
   return(t);
 }
template<class num > num GVector::cosine (const vector2d< num > a, const vector2d< num > b)
Definition at line 724 of file gvector.h.
References GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
 {
   num l;
   l = sqrt(a.x*a.x + a.y*a.y) * sqrt(b.x*b.x + b.y*b.y);
   return((a.x*b.x + a.y*b.y) / l);
 }
template<class num > vector3d<num> GVector::cross (const vector3d< num > a, const vector3d< num > b)
Definition at line 199 of file gvector.h.
References GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
Referenced by shortestArc().
 {
   vector3d<num> r;
   // right handed
   r.x = a.y*b.z - a.z*b.y;
   r.y = a.z*b.x - a.x*b.z;
   r.z = a.x*b.y - a.y*b.x;
   return(r);
 }
template<class num > num GVector::dist (const vector3d< num > a, const vector3d< num > b)
Definition at line 462 of file gvector.h.
References GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
Referenced by role.GoToPoint.GoToPoint::at_new_point(), test_fsm::BS_callback(), CalcCircle(), Callback(), YUVLUT::computeLUTfromLabels(), distance(), distance_seg_to_seg(), distFn(), NKDTree< state_t, num_t, dim, scaled, get_next >::distFromQuery(), role._GoToPoint::execute(), role._GoToPoint_::execute(), role.Kick.Kick::execute_kick(), rrt::RRT< T >::findClosestNode(), CMPattern::TeamDetector::findRobotsByModel(), velocity.profiler.Velocity::GetExpectedPositionIndex(), velocity.profiler.Velocity::GetPathLength(), CameraParameters::radialDistortion(), randn_trig(), NKDTree< Region, float, 2, false, CMVision::RegionTreeGetNext >::setScale(), SSLWorld::step(), and rrt::RRT< T >::treeComplete().
 {
   num dx,dy,dz;
   dx = a.x - b.x;
   dy = a.y - b.y;
   dz = a.z - b.z;
   return(sqrt(dx*dx + dy*dy + dz*dz));
 }
template<class num > num GVector::dist (const vector2d< num > a, const vector2d< num > b)
Definition at line 940 of file gvector.h.
References GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
 {
   num dx,dy;
   dx = a.x - b.x;
   dy = a.y - b.y;
   return(sqrt(dx*dx + dy*dy));
 }
template<class num > num GVector::distance (const vector3d< num > a, const vector3d< num > b) inline
Definition at line 474 of file gvector.h.
References dist().
Referenced by distance_to_line(), distance_to_segment(), ForwardX(), GraphScene::makePath(), Zoom::panDown(), Zoom::panLeft(), Zoom::panRight(), Zoom::panUp(), GLCamera::setDistance(), and GLCamera::setState().
 {
   return(dist(a,b));
 }
template<class num > num GVector::distance (const vector2d< num > a, const vector2d< num > b) inline
Definition at line 951 of file gvector.h.
References dist().
 {
   return(dist(a,b));
 }
template<class vector > double GVector::distance_seg_to_seg (vector s1a, vector s1b, vector s2a, vector s2b)
Definition at line 261 of file geomalgo.h.
References dist(), distance_to_segment(), dot(), EPSILON, v, and V2COMP.
 {
   vector dp;
   vector u = s1b - s1a;
   vector v = s2b - s2a;
   vector w = s1a - s2a;
   float a = dot(u,u);        // always >= 0
   float b = dot(u,v);
   float c = dot(v,v);        // always >= 0
   float d = dot(u,w);
   float e = dot(v,w);
   float D = a*c - b*b;       // always >= 0
   float sc, sN, sD = D;      // sc = sN / sD, default sD = D >= 0
   float tc, tN, tD = D;      // tc = tN / tD, default tD = D >= 0
   if(true){
     printf("SegDist (%f,%f)-(%f,%f) to (%f,%f)-(%f,%f) a=%f b=%f\n",
            V2COMP(s1a),V2COMP(s1b),V2COMP(s2a),V2COMP(s2b),
            a,b);
   }
   if((a < EPSILON) || (b < EPSILON)){
     if((a < EPSILON) && (b < EPSILON)){
       return(dist(s1a,s2a));
     }else if(a < EPSILON){
       return(distance_to_segment(s2a,s2b,s1a));
     }else{
       return(distance_to_segment(s1a,s1b,s2a));
     }
   }
   // compute the line parameters of the two closest points
   if(D < EPSILON){ // the lines are almost parallel
     sN = 0.0; // force using point P0 on segment S1
     sD = 1.0; // to prevent possible division by 0.0 later
     tN = e;
     tD = c;
   }else{                // get the closest points on the infinite lines
     sN = (b*e - c*d);
     tN = (a*e - b*d);
     if(sN < 0){         // sc < 0 => the s=0 edge is visible
       sN = 0.0;
       tN = e;
       tD = c;
     }else if(sN > sD){  // sc > 1 => the s=1 edge is visible
       sN = sD;
       tN = e + b;
       tD = c;
     }
   }
   if(tN < 0){           // tc < 0 => the t=0 edge is visible
     tN = 0.0;
     // recompute sc for this edge
     if(-d < 0){
       sN = 0.0;
     }else if(-d > a){
       sN = sD;
     }else{
       sN = -d;
       sD = a;
     }
   }else if(tN > tD){      // tc > 1 => the t=1 edge is visible
     tN = tD;
     // recompute sc for this edge
     if((-d + b) < 0){
       sN = 0;
     }else if((-d + b) > a){
       sN = sD;
     }else{
       sN = (-d + b);
       sD = a;
     }
   }
   if(false){
     if(sD<1E-9 || tD<1E-9){
       printf("seg_seg_degen D=%f sD=%f tD=%f\n",D,sD,tD);
       printf("  SegDist (%f,%f)-(%f,%f) to (%f,%f)-(%f,%f)\n",
              V2COMP(s1a),V2COMP(s1b),V2COMP(s2a),V2COMP(s2b));
     }
   }
   // finally do the division to get sc and tc
   // sc = sN / sD;
   // tc = tN / tD;
   sc = (fabs(sN) < EPSILON)? 0.0 : sN / sD;
   tc = (fabs(tN) < EPSILON)? 0.0 : tN / tD;
   // get the difference of the two closest points
   dp = w + u*sc - v*tc; // = S1(sc) - S2(tc)
   return(dp.length()); // return the closest distance
 }
template<class num > num GVector::distance_to_line (const vector2d< num > x0, const vector2d< num > x1, const vector2d< num > p)
Definition at line 32 of file geomalgo.h.
 {
   // dot with unit length normal to line
   return(fabs((x1 - x0).norm().perpdot(p - x0)));
 }
template<class num > num GVector::distance_to_line (const vector3d< num > x0, const vector3d< num > x1, const vector3d< num > p)
Definition at line 500 of file gvector.h.
References distance(), t, GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
 {
   // FIXME: this is probably broken
   vector3d<num> x;
   num t;
   t = ((p.x - x0.x) + (p.y - x0.y) + (p.z - x0.z)) / (x1.x + x1.y + x1.z);
   x = x0 + (x1 - x0) * t;
   return(distance(x,p));
 }
template<class vector > double GVector::distance_to_segment (const vector x0, const vector x1, const vector p)
Definition at line 214 of file geomalgo.h.
References distance(), and dot().
Referenced by distance_seg_to_seg().
 {
   vector sx,sp,r;
   double f,l;
   sx = x1 - x0;
   sp = p  - x0;
   f = dot(sx,sp);
   if(f <= 0.0) return(distance(x0,p)); // also handles x0=x1 case
   l = sx.sqlength();
   if(f >= l) return(distance(x1,p));
   r = x0 + sx * (f / l);
   return(distance(r,p));
 }
template<class num > num GVector::dot (const vector3d< num > a, const vector3d< num > b)
Definition at line 174 of file gvector.h.
References GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
Referenced by distance_seg_to_seg(), distance_to_segment(), Robot::getDir(), point_on_line(), point_on_segment(), ray_plane_intersect(), ray_sphere_intersect(), segment_near_line(), and shortestArc().
 {
   return(a.x*b.x + a.y*b.y + a.z*b.z);
 }
template<class num > num GVector::dot (const vector2d< num > a, const vector2d< num > b)
Definition at line 718 of file gvector.h.
References GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
 {
   return(a.x*b.x + a.y*b.y);
 }
template<class vector > vector GVector::interpolate (const vector x0, const vector x1, double t)
Definition at line 163 of file geomalgo.h.
 {
   // t = bound(t, 0.0, 1.0);
   return(x0 + (x1-x0)*t);
 }
template<class num > vector2d<num> GVector::intersection (const vector2d< num > a1, const vector2d< num > a2, const vector2d< num > b1, const vector2d< num > b2)
Definition at line 91 of file geomalgo.h.
References GVector::vector2d< num >::angle(), role._GoToPoint_::rotate, GVector::vector2d< num >::rotate(), GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
 {
   vector2d<num> a = a2 - a1;
   vector2d<num> b1r = (b1 - a1).rotate(-a.angle());
   vector2d<num> b2r = (b2 - a1).rotate(-a.angle());
   vector2d<num> br = (b1r - b2r);
   return
     vector2d<num>(b2r.x - b2r.y * (br.x / br.y), 0.0).rotate(a.angle()) + a1;
 }
template<class vector , class real > vector GVector::LineMidpointAngular (const vector & p0, const vector & p1, real & dist)
Definition at line 453 of file geomalgo.h.
 {
   vector dir = (p0.norm() + p1.norm()).norm();
   vector pn = (p1 - p0).norm();
   dist = pn.perpdot(p0) / pn.perpdot(dir);
   return(dir);
 }
template<class num > vector3d<num> GVector::max (vector3d< num > a, vector3d< num > b) inline
Definition at line 333 of file gvector.h.
References v, GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
Referenced by BBox::BBox3D< vector, num >::add(), BBox::BBox2D< vector, num >::add(), Sobel::centerOfLine(), PluginLegacySSLNetworkOutput::DoubleSizeToSingleSize(), PluginVisualize::DrawSearchCorridors(), tactics._Goalie__.TGoalie::execute(), tactics.Goalie.Goalie::execute_protect(), CMVision::RegionProcessing::extractRegions(), GLText::getAscent(), GLText::getDescent(), CaptureGenerator::getFrame(), GLText::getHeight(), GLSoccerView::GLSoccerView(), GLText::initializeGlyph(), Range::Range< num, open_min, open_max >::inside(), CMPattern::MultiPatternModel::loadSinglePatternImage(), max(), max4(), BBox::BBox3D< vector, num >::merge(), BBox::BBox2D< vector, num >::merge(), GLCamera::mouseAction(), PluginDetectBalls::process(), GLSoccerView::resetView(), GLCamera::wheelEvent(), and GLLUTWidget::wheelEvent().
 {
   vector3d<num> v;
   v.x = ::max(a.x,b.x);
   v.y = ::max(a.y,b.y);
   v.z = ::max(a.z,b.z);
   return(v);
 }
template<class num > vector2d<num> GVector::max (vector2d< num > a, vector2d< num > b) inline
Definition at line 920 of file gvector.h.
References max(), v, GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
Referenced by shortest_angle().
 {
   vector2d<num> v;
   v.x = ::max(a.x,b.x);
   v.y = ::max(a.y,b.y);
   return(v);
 }
template<class num > vector3d<num> GVector::min (vector3d< num > a, vector3d< num > b) inline
Definition at line 321 of file gvector.h.
References v, GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
Referenced by BBox::BBox3D< vector, num >::add(), BBox::BBox2D< vector, num >::add(), utils.math_functions.Line::angle_with_line(), PluginLegacySSLNetworkOutput::DoubleSizeToSingleSize(), tactics._Goalie__.TGoalie::execute(), tactics.Goalie.Goalie::execute_protect(), CMVision::RegionProcessing::extractRegions(), CaptureGenerator::getFrame(), velocity.profiler.Velocity::getTime(), GLText::initializeGlyph(), Range::Range< num, open_min, open_max >::inside(), Planning::isStateValid(), BBox::BBox3D< vector, num >::merge(), BBox::BBox2D< vector, num >::merge(), min(), min4(), Planning::recordSolution(), velocity.profiler.Velocity::trapezoidalMotion(), GLCamera::wheelEvent(), GLLUTWidget::wheelEvent(), and Zoom::zoomToFit().
 {
   vector3d<num> v;
   v.x = ::min(a.x,b.x);
   v.y = ::min(a.y,b.y);
   v.z = ::min(a.z,b.z);
   return(v);
 }
template<class num > vector2d<num> GVector::min (vector2d< num > a, vector2d< num > b) inline
Definition at line 909 of file gvector.h.
References min(), v, GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
Referenced by shortest_angle().
 {
   vector2d<num> v;
   v.x = ::min(a.x,b.x);
   v.y = ::min(a.y,b.y);
   return(v);
 }
template<class num > num GVector::offset_along_line (const vector2d< num > x0, const vector2d< num > x1, const vector2d< num > p)
Definition at line 52 of file geomalgo.h.
References GVector::vector2d< num >::dot(), GVector::vector2d< num >::normalize(), and v.
 {
   vector2d<num> n,v;
   // get normal to line
   n = x1 - x0;
   n.normalize();
   v = p - x0;
   return(n.dot(v));
 }
template<class num > num GVector::offset_to_line (const vector2d< num > x0, const vector2d< num > x1, const vector2d< num > p)
Definition at line 40 of file geomalgo.h.
References GVector::vector2d< num >::dot(), and GVector::vector2d< num >::norm().
 {
   vector2d<num> n;
   // get normal to line
   n = (x1 - x0).perp().norm();
   return(n.dot(p - x0));
 }
template<class num1 , class num2 > vector3d<num2> GVector::operator* (num1 f, const vector3d< num2 > & a)
Definition at line 299 of file gvector.h.
References GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
 {
   vector3d<num2> r;
   r.x = f * a.x;
   r.y = f * a.y;
   r.z = f * a.z;
   return(r);
 }
template<class num1 , class num2 > vector2d<num2> GVector::operator* (num1 f, const vector2d< num2 > & a)
Definition at line 875 of file gvector.h.
References GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
 {
   vector2d<num2> r;
   r.x = f * a.x;
   r.y = f * a.y;
   return(r);
 }
template<class vector > vector GVector::point_on_line (const vector x0, const vector x1, const vector p)
Definition at line 170 of file geomalgo.h.
References dot(), and EPSILON.
 {
   vector sx,sp,r;
   double f,l;
   sx = x1 - x0;
   sp = p  - x0;
   f = dot(sx,sp);
   l = sx.sqlength();
   // if line is degenerate, any point will do
   if(l < EPSILON) return(p);
   // calculate point along line nearest to p
   r = x0 + sx * (f / l);
   return(r);
 }
template<class vector > vector GVector::point_on_segment (const vector x0, const vector x1, const vector p)
Definition at line 192 of file geomalgo.h.
References dot().
 {
   vector sx,sp,r;
   double f,l;
   sx = x1 - x0;
   sp = p  - x0;
   f = dot(sx,sp);
   if(f <= 0.0) return(x0); // also handles x0=x1 case
   l = sx.sqlength();
   if(f >= l) return(x1);
   r = x0 + sx * (f / l);
   return(r);
 }
template<class vector > double GVector::ray_plane_intersect (vector pOrigin, vector pNormal, vector rOrigin, vector rVector)
Definition at line 360 of file geomalgo.h.
References dot().
Referenced by CameraParameters::image2field().
 {
   return(dot(-pNormal,(rOrigin - pOrigin)) / (dot(pNormal,rVector)));
 //  return((dot(pNormal,pOrigin) - dot(pNormal,rOrigin)) /
 //         dot(pNormal,rVector));
 //  double numer = dot(pNormal,rOrigin) - dot(pNormal,pOrigin);
 //  double denom = dot(pNormal,rVector);
 //  return(-(numer / denom));
 }
template<class vector , class real > real GVector::ray_sphere_intersect (vector rO, vector rV, vector sO, real sR)
Definition at line 375 of file geomalgo.h.
References dot(), and v.
 {
   vector Q = sO - rO;
   real c = Q.length();
   real v = dot(Q,rV);
   real d = sR*sR - (c*c - v*v);
   // If there was no intersection, return -1
   if(d < 0.0) return(-1.0);
   // Return the distance to the [first] intersecting point
   return(v - sqrt(d));
 }
template<class num > vector2d<num> GVector::segment_near_line (const vector2d< num > a0, const vector2d< num > a1, const vector2d< num > b0, const vector2d< num > b1)
Definition at line 67 of file geomalgo.h.
References dot(), EPSILON, GVector::vector2d< num >::set(), t, v, GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
 {
   vector2d<num> v,n,p;
   double dn,t;
   v = a1-a0;
   n = (b1-b0).norm();
   n.set(-n.y,n.x);
   dn = dot(v,n);
   if(fabs(dn) < EPSILON) return(a0);
   t = -dot(a0-b0,n) / dn;
   // printf("t=%f dn=%f\n",t,dn);
   if(t < 0) t = 0;
   if(t > 1) t = 1;
   p = a0 + v*t;
   return(p);
 }
template<class num > double GVector::shortest_angle (const vector3d< num > a, const vector3d< num > b)
Definition at line 432 of file gvector.h.
References GVector::vector3d< num >::dot(), GVector::vector3d< num >::length(), max(), and min().
Referenced by GLCamera::lookAt(), and GLSmoothCamera::step().
{
   return(acos(std::max(-1.0,std::min(1.0,dot(a,b)/(a.length()*b.length())))));
 }
template<class num > vector3d<num> GVector::shortest_axis (const vector3d< num > a, const vector3d< num > b)
Definition at line 437 of file gvector.h.
References GVector::vector3d< num >::cross(), and GVector::vector3d< num >::norm().
{
   return(cross(a,b).norm());
 }
template<class num > num GVector::sqdist (const vector3d< num > a, const vector3d< num > b)
Definition at line 481 of file gvector.h.
References GVector::vector3d< num >::x, GVector::vector3d< num >::y, and GVector::vector3d< num >::z.
Referenced by CMPattern::TeamDetector::findRobotsByTeamMarkerOnly(), NKDTree< state_t, num_t, dim, scaled, get_next >::split(), and sqdistance().
 {
   num dx,dy,dz;
   dx = a.x - b.x;
   dy = a.y - b.y;
   dz = a.z - b.z;
   return(dx*dx + dy*dy + dz*dz);
 }
template<class num > num GVector::sqdist (const vector2d< num > a, const vector2d< num > b)
Definition at line 958 of file gvector.h.
References GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
 {
   num dx,dy;
   dx = a.x - b.x;
   dy = a.y - b.y;
   return(dx*dx + dy*dy);
 }
template<class num > num GVector::sqdistance (const vector3d< num > a, const vector3d< num > b) inline
Definition at line 493 of file gvector.h.
References sqdist().
 {
   return(sqdist(a,b));
 }
template<class num > num GVector::sqdistance (const vector2d< num > a, const vector2d< num > b) inline
Definition at line 969 of file gvector.h.
References sqdist().
 {
   return(sqdist(a,b));
 }
template<class num > num GVector::vertex_angle (const vector2d< num > a, const vector2d< num > b, const vector2d< num > c)
Definition at line 106 of file geomalgo.h.
References angle_mod().
 {
   return(angle_mod((a-b).angle() - (c-b).angle()));
 }