Documentation: GlobalCaptureDC1394instanceManager Class Reference
GlobalCaptureDC1394instanceManager Class Reference
A static instance manager to provide global singleton access to GlobalCaptureDC1394instance.
#include <capturedc1394v2.h>
Static Public Member Functions
static dc1394_t * obtainInstance ()
static bool removeInstance ()
Protected Member Functions
GlobalCaptureDC1394instanceManager ()
~GlobalCaptureDC1394instanceManager ()
GlobalCaptureDC1394instanceManager (const GlobalCaptureDC1394instanceManager &)
GlobalCaptureDC1394instanceManager & operator= (const GlobalCaptureDC1394instanceManager &)
Private Attributes
GlobalCaptureDC1394instance * instance
Static Private Attributes
static GlobalCaptureDC1394instanceManager * pinstance = 0
Detailed Description
A static instance manager to provide global singleton access to GlobalCaptureDC1394instance.
Author
Stefan Zickler, (C) 2008
Definition at line 124 of file capturedc1394v2.h.
Constructor & Destructor Documentation
GlobalCaptureDC1394instanceManager::GlobalCaptureDC1394instanceManager () protected
Definition at line 48 of file capturedc1394v2.cpp.
References instance.
Referenced by obtainInstance(), and removeInstance().
{
   instance=new GlobalCaptureDC1394instance();
 }
GlobalCaptureDC1394instanceManager::~GlobalCaptureDC1394instanceManager () protected
Definition at line 51 of file capturedc1394v2.cpp.
References instance.
{
   if (instance!=0) delete instance;
   instance=0;
 }
GlobalCaptureDC1394instanceManager::GlobalCaptureDC1394instanceManager (const GlobalCaptureDC1394instanceManager &) protected
Member Function Documentation
dc1394_t * GlobalCaptureDC1394instanceManager::obtainInstance () static
Definition at line 40 of file capturedc1394v2.cpp.
References GlobalCaptureDC1394instanceManager(), instance, GlobalCaptureDC1394instance::obtainInstance(), and pinstance.
Referenced by CaptureDC1394v2::CaptureDC1394v2().
{
   if (pinstance==0) pinstance=new GlobalCaptureDC1394instanceManager();
   return pinstance->instance->obtainInstance();
 }
GlobalCaptureDC1394instanceManager& GlobalCaptureDC1394instanceManager::operator= (const GlobalCaptureDC1394instanceManager &) protected
bool GlobalCaptureDC1394instanceManager::removeInstance () static
Definition at line 44 of file capturedc1394v2.cpp.
References GlobalCaptureDC1394instanceManager(), instance, pinstance, and GlobalCaptureDC1394instance::removeInstance().
Referenced by CaptureDC1394v2::~CaptureDC1394v2().
{
   if (pinstance==0) pinstance=new GlobalCaptureDC1394instanceManager();
   return pinstance->instance->removeInstance();
 }
Field Documentation
GlobalCaptureDC1394instance* GlobalCaptureDC1394instanceManager::instance private
Definition at line 136 of file capturedc1394v2.h.
Referenced by GlobalCaptureDC1394instanceManager(), obtainInstance(), removeInstance(), and ~GlobalCaptureDC1394instanceManager().
GlobalCaptureDC1394instanceManager * GlobalCaptureDC1394instanceManager::pinstance = 0 static private
Definition at line 135 of file capturedc1394v2.h.
Referenced by anonymous_namespace{capturedc1394v2.cpp}::compareCameraGUID(), obtainInstance(), and removeInstance().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/capture/capturedc1394v2.h
ssl-vision/src/shared/capture/capturedc1394v2.cpp