Documentation: VarTypes::VarStringEnum Class Reference
VarTypes::VarStringEnum Class Reference
This is the string enumeration VarType of the VarTypes system.
#include <VarStringEnum.h>
Public Member Functions
VarStringEnum (string _name="", string _default="")
virtual ~VarStringEnum ()
virtual string getString () const
virtual void resetToDefault ()
virtual void printdebug () const
unsigned int getCount () const
virtual bool setString (const string &val)
set the currently selected string
int getIndex () const
get the index of the currently selected string item
bool selectIndex (unsigned int i)
select an item by using its index
bool select (const string &val)
select a particular string
string getSelection () const
return the currently selected string
string getLabel (unsigned int index) const
get the string of item at a given index
void setSize (unsigned int size, const string default_label="")
trim or extend the list to a certain total number of items
void setLabel (unsigned int index, const string &label)
set the string of item at a given index
int addItem (const string &label)
add an item to the end of the enumeration
virtual VarTypeId getType () const
virtual vector< VarType * > getChildren () const
virtual QWidget * createEditor (const VarItemDelegate *delegate, QWidget *parent, const QStyleOptionViewItem &option)
virtual void setEditorData (const VarItemDelegate *delegate, QWidget *editor) const
virtual void setModelData (const VarItemDelegate *delegate, QWidget *editor)
Public Member Functions inherited from VarTypes::VarType
VarType (string name="")
virtual ~VarType ()
virtual void deleteAllChildren ()
virtual void setName (string name)
Set the string label of this node.
virtual string getName () const
Get the string label of this node.
virtual VarTypeFlag getFlags () const
virtual void setFlags (VarTypeFlag f)
virtual void addFlags (VarTypeFlag f)
virtual void removeFlags (VarTypeFlag f)
virtual bool areFlagsSet (VarTypeFlag f) const
VarType * findChild (string label) const
void writeXML (XMLNode &parent, bool blind_append=true)
Write the contents of this VarType node to an XMLNode.
void readXML (XMLNode &us)
Let this VarType node load the contents of an XMLNode.
virtual QSize sizeHint (const VarItemDelegate *delegate, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void paint (const VarItemDelegate *delegate, QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * clone () const
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
virtual bool hasValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Protected Member Functions
virtual void readChildren (XMLNode &us)
Protected Member Functions inherited from VarTypes::VarType
virtual void lock () const
virtual void unlock () const
virtual void changed ()
virtual void updateAttributes (XMLNode &us) const
virtual void updateText (XMLNode &us) const
virtual void updateChildren (XMLNode &us) const
virtual void readAttributes (XMLNode &us)
virtual void readText (XMLNode &us)
virtual void loadExternal ()
Protected Attributes
vector< VarType * > list
string selected
string default_string
Protected Attributes inherited from VarTypes::VarType
QMutex * _mutex
VarTypeFlag _flags
string _name
Additional Inherited Members
Public Slots inherited from VarTypes::VarType
void mvcEditCompleted ()
A slot to receive signals from a model-view system that editing of this item was just completed.
Signals inherited from VarTypes::VarType
void hasChanged (VarType *)
void wasEdited (VarType *)
void XMLwasRead (VarType *)
This signal is triggered if data was written from an xml node.
void XMLwasWritten (VarType *)
This signal is triggered if data was written to an xml node.
Static Public Member Functions inherited from VarTypes::VarType
static void deleteAllVarChildren (XMLNode &node)
Clear an XMLNode's list of children.
static vector< VarType * > readChildrenHelper (XMLNode &parent, vector< VarType * > existing_children, bool only_update_existing, bool blind_append)
A helper function to read a list of children from XML and convert it to a vector of VarType nodes.
Static Protected Member Functions inherited from VarTypes::VarType
static string fixString (const char *cst)
static string intToString (int val)
static string doubleToString (double val)
static XMLNode findOrAppendChild (XMLNode &parent, string key, string val)
Detailed Description
This is the string enumeration VarType of the VarTypes system.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
The VarStringEnum class allows to define an ordered set of strings from which the user can chose one. This effectively models a popup / listbox allowing a single-item selection.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 41 of file VarStringEnum.h.
Constructor & Destructor Documentation
VarTypes::VarStringEnum::VarStringEnum (string _name = "", string _default = "") inline
Definition at line 49 of file VarStringEnum.h.
                                                        : VarType(_name) {
       default_string=_default;
       selected=_default;
     }
virtual VarTypes::VarStringEnum::~VarStringEnum () inline virtual
Definition at line 54 of file VarStringEnum.h.
References velocity.pid_::i.
{
       int n = list.size();
       for (int i=n-1;i>=0;i--) {
         delete list[(unsigned int)i];
       }
     }
Member Function Documentation
int VarTypes::VarStringEnum::addItem (const string & label) inline
add an item to the end of the enumeration
Definition at line 171 of file VarStringEnum.h.
References VarTypes::VARTYPE_FLAG_HIDDEN.
Referenced by CaptureBlueFox2::CaptureBlueFox2(), CaptureDC1394v2::CaptureDC1394v2(), CaptureFlycap::CaptureFlycap(), CaptureFromFile::CaptureFromFile(), CaptureGenerator::CaptureGenerator(), CaptureThread::CaptureThread(), and CaptureV4L::CaptureV4L().
{
       lock();
       char tmp[64];
       sprintf(tmp,"%zu",list.size());
       list.push_back(new VarString(tmp ,label));
       list[list.size()-1]->addFlags(VARTYPE_FLAG_HIDDEN);
       unlock();
       changed();
       return (list.size()-1);
     }
virtual QWidget* VarTypes::VarStringEnum::createEditor (const VarItemDelegate * delegate, QWidget * parent, const QStyleOptionViewItem & option) inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 208 of file VarStringEnum.h.
{
       //TODO add connect...
       (void)delegate;
       (void)parent;
       (void)option;
       QComboBox * w = new QComboBox(parent);
       connect((const QObject *)w,SIGNAL(currentIndexChanged( int )),(const QObject *)delegate,SLOT(editorChangeEvent()));
       return w;
     }
virtual vector<VarType *> VarTypes::VarStringEnum::getChildren () const inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 184 of file VarStringEnum.h.
     {
       lock();
       vector<VarType *> l = list;
       unlock();
       return l;
     }
unsigned int VarTypes::VarStringEnum::getCount () const inline
Definition at line 65 of file VarStringEnum.h.
{
       lock();
       int n = list.size();
       unlock();
       return n;
     }
int VarTypes::VarStringEnum::getIndex () const inline
get the index of the currently selected string item
Definition at line 78 of file VarStringEnum.h.
References velocity.pid_::i.
Referenced by CMPattern::TeamSelector::getSelectedTeam(), and CMPattern::TeamSelector::update().
{
       lock();
       int res=-1;
       unsigned int n = list.size();
       for (unsigned int i=0;i<n;i++) {
         if (((VarString *)(list[i]))->getString().compare(selected)==0) {
           res= i;
           break;
         }
       }
       unlock();
       return res;
     }
string VarTypes::VarStringEnum::getLabel (unsigned int index) const inline
get the string of item at a given index
Definition at line 121 of file VarStringEnum.h.
{
     string result="";
     lock();
     if (index > (list.size() - 1)) {
       result="";
     } else {
       result=((VarString *)(list[index]))->getString();
     }
     unlock();
     return result;
     }
string VarTypes::VarStringEnum::getSelection () const inline
return the currently selected string
Definition at line 116 of file VarStringEnum.h.
Referenced by CaptureGenerator::copyAndConvertFrame(), CaptureFromFile::copyAndConvertFrame(), CaptureFlycap::copyAndConvertFrame(), CaptureV4L::copyAndConvertFrame(), CaptureDC1394v2::copyAndConvertFrame(), CaptureBlueFox2::getFrame(), and CaptureBlueFox2::startCapture().
{
       return selected;
     }
virtual string VarTypes::VarStringEnum::getString () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 61 of file VarStringEnum.h.
Referenced by CaptureThread::selectCaptureMethod(), CaptureV4L::startCapture(), CaptureDC1394v2::startCapture(), CaptureFlycap::writeParameterValues(), and CaptureBlueFox2::writeParameterValues().
 { return selected; }
virtual VarTypeId VarTypes::VarStringEnum::getType () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 182 of file VarStringEnum.h.
References VarTypes::VARTYPE_ID_STRINGENUM.
 { return VARTYPE_ID_STRINGENUM; } ;
virtual void VarTypes::VarStringEnum::printdebug () const inline virtual
Reimplemented from VarTypes::VarVal.
Definition at line 63 of file VarStringEnum.h.
 { printf("StringEnum named %s containing %zu element(s)\n",getName().c_str(), list.size()); }
virtual void VarTypes::VarStringEnum::readChildren (XMLNode & us) inline protected virtual
Reimplemented from VarTypes::VarType.
Definition at line 194 of file VarStringEnum.h.
References velocity.pid_::i, VarTypes::VARTYPE_FLAG_HIDDEN, and VarTypes::VARTYPE_FLAG_NOLOAD_ENUM_CHILDREN.
     {
       if (areFlagsSet(VARTYPE_FLAG_NOLOAD_ENUM_CHILDREN)==false) {
         list=readChildrenHelper(us, list, false, false);
         for (unsigned int i = 0; i < list.size();i++) {
           list[i]->addFlags(VARTYPE_FLAG_HIDDEN);
         }
       }
       changed();
     }
virtual void VarTypes::VarStringEnum::resetToDefault () inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 62 of file VarStringEnum.h.
 { list.clear(); selected=default_string; };
bool VarTypes::VarStringEnum::select (const string & val) inline
select a particular string
Definition at line 110 of file VarStringEnum.h.
{
       //TODO: add a flag so only selection of existing items is possible.
       lock(); if (val!=selected) {selected=val; unlock(); changed(); return true;} else { unlock(); return false;}
     }
bool VarTypes::VarStringEnum::selectIndex (unsigned int i) inline
select an item by using its index
Definition at line 93 of file VarStringEnum.h.
Referenced by CMPattern::TeamSelector::update().
{
       string result="";
       lock();
       if (i > (list.size() - 1)) {
         result=default_string;
       } else {
         result=((VarString *)(list[i]))->getString();
       }
       if (result!=selected) {
         selected=result;
         unlock(); changed(); return true;
       } else {
         unlock(); return false;
       }
     }
virtual void VarTypes::VarStringEnum::setEditorData (const VarItemDelegate * delegate, QWidget * editor) const inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 218 of file VarStringEnum.h.
References velocity.pid_::i.
{
       (void)delegate;
       QComboBox * combo =(QComboBox *)editor;
       int n = getCount();
       QString tmp;
       combo->clear();
       for (int i=0;i<n;i++) {
         tmp=QString::fromStdString(getLabel(i));
         combo->insertItem(combo->count(), tmp);
         if (tmp==QString::fromStdString(getString())) {
           combo->setCurrentIndex(i);
         }
       }
     }
void VarTypes::VarStringEnum::setLabel (unsigned int index, const string & label) inline
set the string of item at a given index
Definition at line 154 of file VarStringEnum.h.
Referenced by CMPattern::TeamSelector::update().
{
     string result="";
     lock();
     if (index < list.size()) {
       if (((VarString *)(list[index]))->getString().compare(selected)==0) {
         selected=label;
       }
       ((VarString *)(list[index]))->setString(label);
     }
     unlock();
     changed();
     return;
     }
virtual void VarTypes::VarStringEnum::setModelData (const VarItemDelegate * delegate, QWidget * editor) inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 233 of file VarStringEnum.h.
{
       (void)delegate;
       QComboBox * combo=(QComboBox *) editor;
       if (select(combo->currentText().toStdString())) mvcEditCompleted();
     };
void VarTypes::VarStringEnum::setSize (unsigned int size, const string default_label = "") inline
trim or extend the list to a certain total number of items
Definition at line 134 of file VarStringEnum.h.
References velocity.pid_::i, and VarTypes::VARTYPE_FLAG_HIDDEN.
Referenced by CMPattern::TeamSelector::update().
{
       lock();
       if (list.size() < size) {
         for (unsigned int i=list.size();i<size;i++) {
           char tmp[64];
           sprintf(tmp,"%zu",list.size());
           list.push_back(new VarString(tmp ,default_label));
           list[list.size()-1]->addFlags(VARTYPE_FLAG_HIDDEN);
         }
       } else if (list.size() > size) {
         for (unsigned int i=list.size();i>size;i--) {
           delete list[i-1];
           list.pop_back();
         }
       }
       unlock();
       changed();
     }
virtual bool VarTypes::VarStringEnum::setString (const string & val) inline virtual
set the currently selected string
Reimplemented from VarTypes::VarVal.
Definition at line 73 of file VarStringEnum.h.
{
       return select(val);
     }
Field Documentation
string VarTypes::VarStringEnum::default_string protected
Definition at line 47 of file VarStringEnum.h.
vector<VarType *> VarTypes::VarStringEnum::list protected
Definition at line 45 of file VarStringEnum.h.
string VarTypes::VarStringEnum::selected protected
Definition at line 46 of file VarStringEnum.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/vartypes/primitives/VarStringEnum.h