Documentation: grSim/CMakeLists.txt File Reference
grSim/CMakeLists.txt File Reference
Functions
cmake_minimum_required (VERSION 2.8) project(grSim) set(VERSION"1.0.0a2") set(MAINTAINER"Mani Monajjemi <mani.monajjemi@gmail.com>") string(TOLOWER $
CMAKE_PROJECT_NAME_LOWER set (CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake/modules) include($
cmake Utils cmake standard_config () standard_paths($
bin lib if (MSVC) add_definitions(-DHAVE_MSVC) endif() if(WIN32) add_definitions(-DHAVE_WINDOWS) endif() if(UNIX) add_definitions(-DHAVE_UNIX) if(APPLE) add_definitions(-DHAVE_MACOSX) else() add_definitions(-DHAVE_LINUX) endif() endif() set(CMAKE_CXX_FLAGS"$
Function Documentation
cmake_minimum_required (VERSION 2. 8)
Definition at line 1 of file CMakeLists.txt.
                 {CMAKE_PROJECT_NAME} CMAKE_PROJECT_NAME_LOWER)
bin lib if (MSVC)
Definition at line 20 of file CMakeLists.txt.
References app, GVector::dist(), execute_process(), bot_comm::file, list(), and main().
Referenced by test_GoToPoint::BS_callback(), triangle1::BS_callback(), triangle2::BS_callback(), triangle3::BS_callback(), test_Triangle::BS_callback(), GUI.ompl_gui::Callback_VelProfile(), test_Triangle::check_target(), GUI.ompl_gui::debug_path(), GUI.ompl_gui.MainWindow::display_bots(), GUI.ompl_gui.MainWindow::draw_path_one(), GUI.ompl_gui.MainWindow::end_all_process(), role._GoToPoint::execute(), role._GoToPoint_::execute(), velocity.run::Get_Vel(), and ssltest::gr_Commands_CB().
              : fix this, say we have FreeBSD, that's not linux
         add_definitions(-DHAVE_LINUX)
     endif()
 endif()
 # set explicitly the c++ standard to use
 set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++03")
CMAKE_PROJECT_NAME_LOWER set (CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake/ modules)
Definition at line 13 of file CMakeLists.txt.
                        {PROJECT_SOURCE_DIR}/cmake/modules)
 include(${PROJECT_SOURCE_DIR}/cmake/Utils.cmake)
cmake Utils cmake standard_config ()
Definition at line 15 of file CMakeLists.txt.
                 {PROJECT_SOURCE_DIR} bin lib)