Documentation: DVRStream Class Reference
DVRStream Class Reference
#include <plugin_dvr.h>
Public Member Functions
DVRStream ()
virtual ~DVRStream ()
int getLimit ()
void setLimit (int num_frames)
bool loadStream (QString file)
void newRecording (QString directory)
void saveStream (QString directory)
void clear ()
void appendFrame (FrameData *data, bool shift_stream_on_limit_exceed)
void seek (int frame)
int getFrameCount ()
void advance (int frames, bool wrap)
void advanceToMostRecent ()
int getCurrentFrameIndex ()
DVRFrame * getFrame (int i)
DVRFrame * getCurrentFrame ()
Protected Attributes
QList< DVRFrame * > frames
int limit
int current
Detailed Description
Definition at line 96 of file plugin_dvr.h.
Constructor & Destructor Documentation
DVRStream::DVRStream ()
Definition at line 566 of file plugin_dvr.cpp.
                      {
   limit=0;
   clear();
 }
DVRStream::~DVRStream () virtual
Definition at line 570 of file plugin_dvr.cpp.
                       {
  clear();
 }
Member Function Documentation
void DVRStream::advance (int frames, bool wrap)
Definition at line 573 of file plugin_dvr.cpp.
References max_idx(), and mod().
Referenced by PluginDVR::process().
{
   if (getFrameCount() == 0) return;
   int new_current=current+frames;
   int max_idx=getFrameCount()-1;
   if (new_current < 0) {
     if (wrap) {
       new_current=mod(new_current,getFrameCount());
     } else {
       new_current=0;
     }
   }
   if (new_current > max_idx) {
     if (wrap) {
       new_current=mod(new_current,getFrameCount());
     } else {
       new_current=max_idx;
     }
   }
   current=new_current;
 }
void DVRStream::advanceToMostRecent ()
Definition at line 594 of file plugin_dvr.cpp.
{
   current=getFrameCount()-1;
 }
void DVRStream::appendFrame (FrameData * data, bool shift_stream_on_limit_exceed)
Definition at line 532 of file plugin_dvr.cpp.
References DVRFrame::getFromFrameData().
Referenced by PluginDVR::process().
{
   if (limit!=0 && ((getFrameCount() + 1) > limit)) {
     if (shift_stream_on_limit_exceed) {
       DVRFrame * f = frames[0];
       delete f;
       frames.removeFirst();
       if (current > 0) current--;
     } else {
       return;
     }
   }
   DVRFrame * f = new DVRFrame();
   f->getFromFrameData(data);
   frames.append(f);
 }
void DVRStream::clear ()
Definition at line 524 of file plugin_dvr.cpp.
References velocity.pid_::i.
Referenced by PluginDVR::PluginDVR().
                       {
   for (int i = 0; i < frames.size(); i++) {
     delete frames[i];
   }
   frames.clear();
   current=0;
 }
DVRFrame * DVRStream::getCurrentFrame ()
Definition at line 600 of file plugin_dvr.cpp.
Referenced by PluginDVR::process().
{
   if (current >= frames.size()) return 0;
   return frames[current];
 }
int DVRStream::getCurrentFrameIndex ()
Definition at line 597 of file plugin_dvr.cpp.
Referenced by PluginDVR::process().
{
   return current;
 }
DVRFrame * DVRStream::getFrame (int i)
Definition at line 605 of file plugin_dvr.cpp.
References velocity.pid_::i.
{
   if (current >= frames.size()) return 0;
   if (i < 0) return 0;
   return frames[i];
 }
int DVRStream::getFrameCount ()
Definition at line 554 of file plugin_dvr.cpp.
Referenced by PluginDVR::process().
{
   return frames.size();
 }
int DVRStream::getLimit ()
Definition at line 562 of file plugin_dvr.cpp.
Referenced by PluginDVR::process().
{
   return limit;
 }
bool DVRStream::loadStream (QString file)
Definition at line 512 of file plugin_dvr.cpp.
{
   return false;
 }
void DVRStream::newRecording (QString directory)
Definition at line 516 of file plugin_dvr.cpp.
{
 }
void DVRStream::saveStream (QString directory)
Definition at line 520 of file plugin_dvr.cpp.
{
 }
void DVRStream::seek (int frame)
Definition at line 548 of file plugin_dvr.cpp.
References bot_comm::frame.
{
   if (frame >= getFrameCount()) frame=getFrameCount()-1;
   if (frame < 0) frame=0;
   current=frame;
 }
void DVRStream::setLimit (int num_frames)
Definition at line 558 of file plugin_dvr.cpp.
Referenced by PluginDVR::process().
{
   limit=num_frames;
 }
Field Documentation
int DVRStream::current protected
Definition at line 102 of file plugin_dvr.h.
QList<DVRFrame *> DVRStream::frames protected
Definition at line 100 of file plugin_dvr.h.
int DVRStream::limit protected
Definition at line 101 of file plugin_dvr.h.
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/plugin_dvr.h
ssl-vision/src/app/plugins/plugin_dvr.cpp