Documentation: Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder Class Reference
Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
MessagesRobocupSslRefboxLog.Refbox_Log getDefaultInstanceForType ()
MessagesRobocupSslRefboxLog.Refbox_Log build ()
MessagesRobocupSslRefboxLog.Refbox_Log buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (MessagesRobocupSslRefboxLog.Refbox_Log other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
java.util.List< MessagesRobocupSslRefboxLog.Log_Frame > getLogList ()
int getLogCount ()
MessagesRobocupSslRefboxLog.Log_Frame getLog (int index)
Builder setLog (int index, MessagesRobocupSslRefboxLog.Log_Frame value)
Builder setLog (int index, MessagesRobocupSslRefboxLog.Log_Frame.Builder builderForValue)
Builder addLog (MessagesRobocupSslRefboxLog.Log_Frame value)
Builder addLog (int index, MessagesRobocupSslRefboxLog.Log_Frame value)
Builder addLog (MessagesRobocupSslRefboxLog.Log_Frame.Builder builderForValue)
Builder addLog (int index, MessagesRobocupSslRefboxLog.Log_Frame.Builder builderForValue)
Builder addAllLog (java.lang.Iterable<?extends MessagesRobocupSslRefboxLog.Log_Frame > values)
Builder clearLog ()
Builder removeLog (int index)
MessagesRobocupSslRefboxLog.Log_Frame.Builder getLogBuilder (int index)
MessagesRobocupSslRefboxLog.Log_FrameOrBuilder getLogOrBuilder (int index)
java.util.List<?extends MessagesRobocupSslRefboxLog.Log_FrameOrBuilder > getLogOrBuilderList ()
MessagesRobocupSslRefboxLog.Log_Frame.Builder addLogBuilder ()
MessagesRobocupSslRefboxLog.Log_Frame.Builder addLogBuilder (int index)
java.util.List< MessagesRobocupSslRefboxLog.Log_Frame.Builder > getLogBuilderList ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
MessagesRobocupSslRefboxLog.Refbox_Log buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
void ensureLogIsMutable ()
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslRefboxLog.Log_Frame, MessagesRobocupSslRefboxLog.Log_Frame.Builder, MessagesRobocupSslRefboxLog.Log_FrameOrBuilder > getLogFieldBuilder ()
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
java.util.List< MessagesRobocupSslRefboxLog.Log_Frame > log_
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslRefboxLog.Log_Frame, MessagesRobocupSslRefboxLog.Log_Frame.Builder, MessagesRobocupSslRefboxLog.Log_FrameOrBuilder > logBuilder_
Detailed Description
Definition at line 744 of file MessagesRobocupSslRefboxLog.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.Builder () inline private
Definition at line 758 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.Builder (BuilderParent parent) inline private
Definition at line 762 of file MessagesRobocupSslRefboxLog.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.addAllLog (java.lang.Iterable<?extends MessagesRobocupSslRefboxLog.Log_Frame > values) inline
Definition at line 1027 of file MessagesRobocupSslRefboxLog.java.
{
         if (logBuilder_ == null) {
           ensureLogIsMutable();
           super.addAll(values, log_);
           onChanged();
         } else {
           logBuilder_.addAllMessages(values);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.addLog (MessagesRobocupSslRefboxLog.Log_Frame value) inline
Definition at line 978 of file MessagesRobocupSslRefboxLog.java.
{
         if (logBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureLogIsMutable();
           log_.add(value);
           onChanged();
         } else {
           logBuilder_.addMessage(value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.addLog (int index, MessagesRobocupSslRefboxLog.Log_Frame value) inline
Definition at line 991 of file MessagesRobocupSslRefboxLog.java.
{
         if (logBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureLogIsMutable();
           log_.add(index, value);
           onChanged();
         } else {
           logBuilder_.addMessage(index, value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.addLog (MessagesRobocupSslRefboxLog.Log_Frame.Builder builderForValue) inline
Definition at line 1005 of file MessagesRobocupSslRefboxLog.java.
{
         if (logBuilder_ == null) {
           ensureLogIsMutable();
           log_.add(builderForValue.build());
           onChanged();
         } else {
           logBuilder_.addMessage(builderForValue.build());
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.addLog (int index, MessagesRobocupSslRefboxLog.Log_Frame.Builder builderForValue) inline
Definition at line 1016 of file MessagesRobocupSslRefboxLog.java.
{
         if (logBuilder_ == null) {
           ensureLogIsMutable();
           log_.add(index, builderForValue.build());
           onChanged();
         } else {
           logBuilder_.addMessage(index, builderForValue.build());
         }
         return this;
       }
MessagesRobocupSslRefboxLog.Log_Frame.Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.addLogBuilder () inline
Definition at line 1077 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance().
{
         return getLogFieldBuilder().addBuilder(
             MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance());
       }
MessagesRobocupSslRefboxLog.Log_Frame.Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.addLogBuilder (int index) inline
Definition at line 1081 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance().
                      {
         return getLogFieldBuilder().addBuilder(
             index, MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance());
       }
MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.build () inline
Definition at line 799 of file MessagesRobocupSslRefboxLog.java.
{
         MessagesRobocupSslRefboxLog.Refbox_Log result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 807 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.parseDelimitedFrom().
{
         MessagesRobocupSslRefboxLog.Refbox_Log result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.buildPartial () inline
Definition at line 817 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.log_.
{
         MessagesRobocupSslRefboxLog.Refbox_Log result = new MessagesRobocupSslRefboxLog.Refbox_Log(this);
         int from_bitField0_ = bitField0_;
         if (logBuilder_ == null) {
           if (((bitField0_ & 0x00000001) == 0x00000001)) {
             log_ = java.util.Collections.unmodifiableList(log_);
             bitField0_ = (bitField0_ & ~0x00000001);
           }
           result.log_ = log_;
         } else {
           result.log_ = logBuilder_.build();
         }
         onBuilt();
         return result;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.clear () inline
Definition at line 775 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.clear().
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.clear().
{
         super.clear();
         if (logBuilder_ == null) {
           log_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000001);
         } else {
           logBuilder_.clear();
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.clearLog () inline
Definition at line 1038 of file MessagesRobocupSslRefboxLog.java.
{
         if (logBuilder_ == null) {
           log_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000001);
           onChanged();
         } else {
           logBuilder_.clear();
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.clone () inline
Definition at line 786 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.create () inline static private
Definition at line 771 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.newBuilder().
{
         return new Builder();
       }
void Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.ensureLogIsMutable () inline private
Definition at line 922 of file MessagesRobocupSslRefboxLog.java.
{
         if (!((bitField0_ & 0x00000001) == 0x00000001)) {
           log_ = new java.util.ArrayList<MessagesRobocupSslRefboxLog.Log_Frame>(log_);
           bitField0_ |= 0x00000001;
          }
       }
MessagesRobocupSslRefboxLog.Refbox_Log Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getDefaultInstanceForType () inline
Definition at line 795 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getDefaultInstance().
{
         return MessagesRobocupSslRefboxLog.Refbox_Log.getDefaultInstance();
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getDescriptor () inline static
Definition at line 748 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_descriptor.
{
         return MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getDescriptorForType () inline
Definition at line 791 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getDescriptor().
{
         return MessagesRobocupSslRefboxLog.Refbox_Log.getDescriptor();
       }
MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getLog (int index) inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Refbox_LogOrBuilder.
Definition at line 946 of file MessagesRobocupSslRefboxLog.java.
{
         if (logBuilder_ == null) {
           return log_.get(index);
         } else {
           return logBuilder_.getMessage(index);
         }
       }
MessagesRobocupSslRefboxLog.Log_Frame.Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getLogBuilder (int index) inline
Definition at line 1058 of file MessagesRobocupSslRefboxLog.java.
                      {
         return getLogFieldBuilder().getBuilder(index);
       }
java.util.List<MessagesRobocupSslRefboxLog.Log_Frame.Builder> Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getLogBuilderList () inline
Definition at line 1087 of file MessagesRobocupSslRefboxLog.java.
{
         return getLogFieldBuilder().getBuilderList();
       }
int Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getLogCount () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Refbox_LogOrBuilder.
Definition at line 939 of file MessagesRobocupSslRefboxLog.java.
{
         if (logBuilder_ == null) {
           return log_.size();
         } else {
           return logBuilder_.getCount();
         }
       }
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslRefboxLog.Log_Frame, MessagesRobocupSslRefboxLog.Log_Frame.Builder, MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getLogFieldBuilder () inline private
Definition at line 1092 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.initFields().
{
         if (logBuilder_ == null) {
           logBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
               MessagesRobocupSslRefboxLog.Log_Frame, MessagesRobocupSslRefboxLog.Log_Frame.Builder, MessagesRobocupSslRefboxLog.Log_FrameOrBuilder>(
                   log_,
                   ((bitField0_ & 0x00000001) == 0x00000001),
                   getParentForChildren(),
                   isClean());
           log_ = null;
         }
         return logBuilder_;
       }
java.util.List<MessagesRobocupSslRefboxLog.Log_Frame> Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getLogList () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Refbox_LogOrBuilder.
Definition at line 932 of file MessagesRobocupSslRefboxLog.java.
{
         if (logBuilder_ == null) {
           return java.util.Collections.unmodifiableList(log_);
         } else {
           return logBuilder_.getMessageList();
         }
       }
MessagesRobocupSslRefboxLog.Log_FrameOrBuilder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getLogOrBuilder (int index) inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Refbox_LogOrBuilder.
Definition at line 1062 of file MessagesRobocupSslRefboxLog.java.
                      {
         if (logBuilder_ == null) {
           return log_.get(index);  } else {
           return logBuilder_.getMessageOrBuilder(index);
         }
       }
java.util.List<? extends MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.getLogOrBuilderList () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Refbox_LogOrBuilder.
Definition at line 1070 of file MessagesRobocupSslRefboxLog.java.
{
         if (logBuilder_ != null) {
           return logBuilder_.getMessageOrBuilderList();
         } else {
           return java.util.Collections.unmodifiableList(log_);
         }
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 753 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_fieldAccessorTable.
{
         return MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_fieldAccessorTable;
       }
final boolean Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.isInitialized () inline
Definition at line 874 of file MessagesRobocupSslRefboxLog.java.
References velocity.pid_.i.
{
         for (int i = 0; i < getLogCount(); i++) {
           if (!getLog(i).isInitialized()) {
             return false;
           }
         }
         return true;
       }
void Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.maybeForceBuilderInitialization () inline private
Definition at line 766 of file MessagesRobocupSslRefboxLog.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
           getLogFieldBuilder();
         }
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 833 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.clone(), and Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.newBuilder().
{
         if (other instanceof MessagesRobocupSslRefboxLog.Refbox_Log) {
           return mergeFrom((MessagesRobocupSslRefboxLog.Refbox_Log)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.mergeFrom (MessagesRobocupSslRefboxLog.Refbox_Log other) inline
Definition at line 842 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getDefaultInstance(), and Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.log_.
{
         if (other == MessagesRobocupSslRefboxLog.Refbox_Log.getDefaultInstance()) return this;
         if (logBuilder_ == null) {
           if (!other.log_.isEmpty()) {
             if (log_.isEmpty()) {
               log_ = other.log_;
               bitField0_ = (bitField0_ & ~0x00000001);
             } else {
               ensureLogIsMutable();
               log_.addAll(other.log_);
             }
             onChanged();
           }
         } else {
           if (!other.log_.isEmpty()) {
             if (logBuilder_.isEmpty()) {
               logBuilder_.dispose();
               logBuilder_ = null;
               log_ = other.log_;
               bitField0_ = (bitField0_ & ~0x00000001);
               logBuilder_ =
                 com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                    getLogFieldBuilder() : null;
             } else {
               logBuilder_.addAllMessages(other.log_);
             }
           }
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 884 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.Builder(), and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.newBuilder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 10: {
               MessagesRobocupSslRefboxLog.Log_Frame.Builder subBuilder = MessagesRobocupSslRefboxLog.Log_Frame.newBuilder();
               input.readMessage(subBuilder, extensionRegistry);
               addLog(subBuilder.buildPartial());
               break;
             }
           }
         }
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.removeLog (int index) inline
Definition at line 1048 of file MessagesRobocupSslRefboxLog.java.
{
         if (logBuilder_ == null) {
           ensureLogIsMutable();
           log_.remove(index);
           onChanged();
         } else {
           logBuilder_.remove(index);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.setLog (int index, MessagesRobocupSslRefboxLog.Log_Frame value) inline
Definition at line 953 of file MessagesRobocupSslRefboxLog.java.
{
         if (logBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           ensureLogIsMutable();
           log_.set(index, value);
           onChanged();
         } else {
           logBuilder_.setMessage(index, value);
         }
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.setLog (int index, MessagesRobocupSslRefboxLog.Log_Frame.Builder builderForValue) inline
Definition at line 967 of file MessagesRobocupSslRefboxLog.java.
{
         if (logBuilder_ == null) {
           ensureLogIsMutable();
           log_.set(index, builderForValue.build());
           onChanged();
         } else {
           logBuilder_.setMessage(index, builderForValue.build());
         }
         return this;
       }
Field Documentation
int Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.bitField0_ private
Definition at line 917 of file MessagesRobocupSslRefboxLog.java.
java.util.List<MessagesRobocupSslRefboxLog.Log_Frame> Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.log_ private
Initial value:
=
        java.util.Collections.emptyList()
Definition at line 920 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.mergeFrom().
com.google.protobuf.RepeatedFieldBuilder< MessagesRobocupSslRefboxLog.Log_Frame, MessagesRobocupSslRefboxLog.Log_Frame.Builder, MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.logBuilder_ private
Definition at line 930 of file MessagesRobocupSslRefboxLog.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslRefboxLog.java