Documentation: VarTypes::VarNotifier Class Reference
VarTypes::VarNotifier Class Reference
A helper class which accumulates the occurence of VarType changes.
#include <VarNotifier.h>
Public Types
enum VarNotificationType { VarNotificationChanged, VarNotificationEdited }
Public Slots
void changeSlotOtherChange ()
Signals
void changeOccured (VarType *item)
Public Member Functions
VarNotifier ()
~VarNotifier ()
void addItem (VarType *item, VarNotificationType notification_type=VarNotificationChanged)
void addRecursive (VarType *item, VarNotificationType notification_type=VarNotificationChanged, bool include_root=true)
void removeItem (VarType *item)
void removeRecursive (VarType *item, bool include_root=true)
bool hasChangedNoReset ()
bool hasChanged ()
This will report true if any events have happened and reset the event counter.
void setChanged (bool value)
void clear ()
Data Fields
QHash< VarType *, VarNotificationType > senders
bool changed
QMutex mutex
Protected Slots
void changeSlot (VarType *item)
Protected Member Functions
void internalNonMutexedAddItem (VarType *item, VarNotificationType notification_type=VarNotificationChanged)
void internalNonMutexedRemoveItem (VarType *item)
Detailed Description
A helper class which accumulates the occurence of VarType changes.
Author
Stefan Zickler
Definition at line 34 of file VarNotifier.h.
Member Enumeration Documentation
enum VarTypes::VarNotifier::VarNotificationType
Enumerator
VarNotificationChanged
VarNotificationEdited
Definition at line 37 of file VarNotifier.h.
{
       VarNotificationChanged,
       VarNotificationEdited,
     };
Constructor & Destructor Documentation
VarTypes::VarNotifier::VarNotifier ()
Definition at line 25 of file VarNotifier.cpp.
References changed.
   {
     changed=false;
   }
VarTypes::VarNotifier::~VarNotifier ()
Definition at line 31 of file VarNotifier.cpp.
   {
   }
Member Function Documentation
void VarTypes::VarNotifier::addItem (VarType * item, VarNotificationType notification_type = VarNotificationChanged)
Definition at line 120 of file VarNotifier.cpp.
References internalNonMutexedAddItem(), and mutex.
{
     mutex.lock();
     internalNonMutexedAddItem(item, notification_type);
     mutex.unlock();
   }
void VarTypes::VarNotifier::addRecursive (VarType * item, VarNotificationType notification_type = VarNotificationChanged, bool include_root = true)
Definition at line 126 of file VarNotifier.cpp.
References VarTypes::VarType::getChildren(), velocity.pid_::i, internalNonMutexedAddItem(), and mutex.
Referenced by PluginDetectBalls::PluginDetectBalls(), PluginDetectRobots::PluginDetectRobots(), and CMPattern::Team::Team().
{
     mutex.lock();
     QQueue<VarType *> queue;
     if (item!=0) queue.enqueue(item);
     while(queue.isEmpty()==false) {
       VarType * d = queue.dequeue();
       if ((d!=item) || include_root) internalNonMutexedAddItem(d,notification_type);
       vector<VarType *> children = d->getChildren();
       int s=children.size();
       for (int i=0;i<s;i++) {
         if (children[i]!=0) queue.enqueue(children[i]);
       }
     }
     mutex.unlock();
   }
void VarTypes::VarNotifier::changeOccured (VarType * item) signal
Definition at line 102 of file moc_VarNotifier.cxx.
Referenced by changeSlot(), and changeSlotOtherChange().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 0, _a);
 }
void VarTypes::VarNotifier::changeSlot (VarType * item) protected slot
Definition at line 71 of file VarNotifier.cpp.
References changed, changeOccured(), and mutex.
Referenced by internalNonMutexedAddItem(), and internalNonMutexedRemoveItem().
{
     mutex.lock();
     changed=true;
     mutex.unlock();
     emit changeOccured(item);
   }
void VarTypes::VarNotifier::changeSlotOtherChange () slot
Definition at line 64 of file VarNotifier.cpp.
References changed, changeOccured(), and mutex.
Referenced by PluginDetectRobots::process().
{
     mutex.lock();
     changed=true;
     mutex.unlock();
     emit changeOccured(0);
   }
void VarTypes::VarNotifier::clear ()
Definition at line 35 of file VarNotifier.cpp.
References internalNonMutexedRemoveItem(), mutex, and senders.
{
     mutex.lock();
     QHash<VarType *, VarNotificationType>::const_iterator iter;
     for (iter = senders.constBegin();iter != senders.constEnd();iter++) {
       internalNonMutexedRemoveItem(iter.key());
     }
     senders.clear();
     mutex.unlock();
   }
bool VarTypes::VarNotifier::hasChanged ()
This will report true if any events have happened and reset the event counter.
Definition at line 45 of file VarNotifier.cpp.
References changed, and mutex.
Referenced by internalNonMutexedAddItem(), PluginDetectRobots::process(), and PluginDetectBalls::process().
{
     bool result=false;
     mutex.lock();
     if (changed) {
       result=true;
       changed=false;
     }
     mutex.unlock();
     return result;
   }
bool VarTypes::VarNotifier::hasChangedNoReset ()
This will report true if any events have happened, but it will not reset the event counter It is encouraged to use hasChanged() instead, if possible.
Definition at line 56 of file VarNotifier.cpp.
References changed, and mutex.
{
     bool result;
     mutex.lock();
     result=changed;
     mutex.unlock();
     return result;
   }
void VarTypes::VarNotifier::internalNonMutexedAddItem (VarType * item, VarNotificationType notification_type = VarNotificationChanged) protected
Definition at line 95 of file VarNotifier.cpp.
References changeSlot(), hasChanged(), senders, and VarNotificationChanged.
Referenced by addItem(), and addRecursive().
{
     if (item==0) return;
     QHash<VarType *, VarNotificationType>::iterator iter;
     iter = senders.find(item);
     if (iter != senders.constEnd()) {
       if (iter.value() == notification_type) {
         //this exact item already exists.
         return;
       } else {
         //item exists, but with wrong notification type:
         //fix it:
         disconnect(item, 0, this, SLOT(changeSlot(VarType *)));
         iter.value() = notification_type;
       }
     } else {
       iter=senders.insert(item,notification_type);
     }
     //connect it with correct notification type:
     if (notification_type==VarNotificationChanged) {
       connect(item, SIGNAL(hasChanged(VarType *)), this, SLOT(changeSlot(VarType *)));
     } else {
       connect(item, SIGNAL(wasEdited(VarType*)), this, SLOT(changeSlot(VarType *)));
     }
   }
void VarTypes::VarNotifier::internalNonMutexedRemoveItem (VarType * item) protected
Definition at line 85 of file VarNotifier.cpp.
References changeSlot(), and senders.
Referenced by clear(), removeItem(), and removeRecursive().
{
     if (item==0) return;
     QHash<VarType *, VarNotificationType>::iterator iter;
     iter = senders.find(item);
     if (iter != senders.constEnd()) {
       disconnect(item, 0, this, SLOT(changeSlot(VarType *)));
       senders.erase(iter);
     }
   }
void VarTypes::VarNotifier::removeItem (VarType * item)
Definition at line 142 of file VarNotifier.cpp.
References internalNonMutexedRemoveItem(), and mutex.
{
     mutex.lock();
     internalNonMutexedRemoveItem(item);
     mutex.unlock();
   }
void VarTypes::VarNotifier::removeRecursive (VarType * item, bool include_root = true)
Definition at line 148 of file VarNotifier.cpp.
References VarTypes::VarType::getChildren(), velocity.pid_::i, internalNonMutexedRemoveItem(), and mutex.
{
     mutex.lock();
     QQueue<VarType *> queue;
     if (item!=0) queue.enqueue(item);
     while(queue.isEmpty()==false) {
       VarType * d = queue.dequeue();
       if ((d!=item) || include_root) internalNonMutexedRemoveItem(item);
       vector<VarType *> children = d->getChildren();
       int s=children.size();
       for (int i=0;i<s;i++) {
         if (children[i]!=0) queue.enqueue(children[i]);
       }
     }
     mutex.unlock();
   }
void VarTypes::VarNotifier::setChanged (bool value)
Definition at line 78 of file VarNotifier.cpp.
References changed, and mutex.
{
     mutex.lock();
     changed=value;
     mutex.unlock();
   }
Field Documentation
bool VarTypes::VarNotifier::changed
Definition at line 46 of file VarNotifier.h.
Referenced by changeSlot(), changeSlotOtherChange(), hasChanged(), hasChangedNoReset(), setChanged(), and VarNotifier().
QMutex VarTypes::VarNotifier::mutex
Definition at line 47 of file VarNotifier.h.
Referenced by addItem(), addRecursive(), changeSlot(), changeSlotOtherChange(), clear(), hasChanged(), hasChangedNoReset(), removeItem(), removeRecursive(), and setChanged().
QHash<VarType *, VarNotificationType> VarTypes::VarNotifier::senders
Definition at line 45 of file VarNotifier.h.
Referenced by clear(), internalNonMutexedAddItem(), and internalNonMutexedRemoveItem().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/VarNotifier.h
ssl-vision/build/src/shared/vartypes/moc_VarNotifier.cxx
ssl-vision/src/shared/vartypes/VarNotifier.cpp