Documentation: Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder Interface Reference
Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder Interface Reference
Public Member Functions
boolean hasDetection ()
MessagesRobocupSslDetection.SSL_DetectionFrame getDetection ()
MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getDetectionOrBuilder ()
boolean hasGeometry ()
MessagesRobocupSslGeometry.SSL_GeometryData getGeometry ()
MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder getGeometryOrBuilder ()
Detailed Description
Definition at line 11 of file MessagesRobocupSslWrapper.java.
Member Function Documentation
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.getDetection ()
Implemented in Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder, and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.isInitialized(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.isInitialized(), and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom().
MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.getDetectionOrBuilder ()
Implemented in Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder, and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.
MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.getGeometry ()
Implemented in Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder, and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.isInitialized(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.isInitialized(), and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom().
MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.getGeometryOrBuilder ()
Implemented in Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder, and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.
boolean Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.hasDetection ()
Implemented in Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder, and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.isInitialized(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.isInitialized(), and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom().
boolean Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.hasGeometry ()
Implemented in Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder, and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.isInitialized(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.isInitialized(), and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom().
The documentation for this interface was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslWrapper.java