Documentation: belief_state/src/node_class.cpp File Reference
node_class.cpp File Reference
#include "ros/ros.h"
#include "../../ssl_common/include/ssl_common/config.h"
#include <krssg_ssl_msgs/BeliefState.h>
#include <krssg_ssl_msgs/SSL_DetectionFrame.h>
#include <krssg_ssl_msgs/SSL_DetectionRobot.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Point32.h>
#include "../../ssl_common/include/ssl_common/geometry.hpp"
#include <string.h>
#include <math.h>
#include <vector>
#include <queue>
#include <deque>
#include <fstream>
Data Structures
class BeliefState
Core class for extracting belief state information.
Functions
void print (Pose2D &p)
void print (vector< Pose2D > p)
void print (vector< bool > p)
bool isValidMsg (const krssg_ssl_msgs::SSL_DetectionFrame::ConstPtr &vmsg)
float distFn (krssg_ssl_msgs::SSL_DetectionRobot p, float x, float y)
void Callback (const krssg_ssl_msgs::SSL_DetectionFrame::ConstPtr &vmsg)
int main (int argc, char *argv[])
Variables
const int BALL_AT_CORNER_THRESH = 20
const int HALF_FIELD_MAXX = 3000
const int HALF_FIELD_MAXY = 2000
const float MAX_DRIBBLE_R = 3
const int DBOX_WIDTH = 600
const int DBOX_HEIGHT = 600
const int MAX_QUEUE_SZ = 5
short int isteamyellow = 0
ros::Publisher pub
Function Documentation
void Callback (const krssg_ssl_msgs::SSL_DetectionFrame::ConstPtr & vmsg)
Definition at line 419 of file node_class.cpp.
References test_fsm::BeliefState, and pub.
Referenced by main().
{
     static list<BeliefState> prev_msgQ;
     BeliefState bs(vmsg,prev_msgQ);
     bs.print();
     pub.publish(bs.getBeliefStateMsg());
 }
float distFn (krssg_ssl_msgs::SSL_DetectionRobot p, float x, float y)
Definition at line 136 of file node_class.cpp.
References role._GoToPoint::awayPos, awayVel, BALL_AT_CORNER_THRESH, ballPos, test_fsm::BeliefState, BeliefState::BeliefState(), DBOX_HEIGHT, DBOX_WIDTH, GVector::dist(), HALF_FIELD_MAXX, HALF_FIELD_MAXY, role._GoToPoint::homePos, homeVel, velocity.pid_::i, isteamyellow, isValidMsg(), MAX_DRIBBLE_R, MAX_QUEUE_SZ, role._GoToPoint::x, and role._GoToPoint::y.
{
     return sqrt((p.x - x)*(p.x - x) + (p.y - y)*(p.y - y));
 }
bool isValidMsg (const krssg_ssl_msgs::SSL_DetectionFrame::ConstPtr & vmsg)
Definition at line 95 of file node_class.cpp.
Referenced by distFn().
{
     if(vmsg->robots_yellow.size() == 0 && vmsg->robots_blue.size()==0)
         return false;
     if(vmsg->balls.size() == 0)
         return false;
     return true;
 }
int main (int argc, char * argv[])
Definition at line 427 of file node_class.cpp.
References test_fsm::BeliefState, Callback(), role._GoToPoint::init(), isteamyellow, pub, and vision_sub.
 {
     ros::init(argc,argv,"beliefstate_node");
     if(argc > 1){
         ::isteamyellow = atof(argv[1]);
     }
     ros::NodeHandle n;
     ros::Subscriber vision_sub = n.subscribe("/vision", 10000, Callback);
     ::pub = n.advertise<krssg_ssl_msgs::BeliefState>("/belief_state", 10000);
     ros::spin();
     return 0;
 }
void print (Pose2D & p)
Definition at line 34 of file node_class.cpp.
Referenced by velocity.error.Error::__init__(), test_fsm::BS_callback(), triangle1::BS_callback(), triangle2::BS_callback(), test_GoToPoint::BS_callback(), triangle3::BS_callback(), test_Triangle::check_target(), GUI.self_RRT::debug_path(), GUI.ompl_gui::debug_path(), GUI.ompl_gui.MainWindow::display_bots(), role._GoToPoint_::execute(), role.pass_receive.PassReceive::execute_aligned(), role.pass_receive.PassReceive::execute_aligning(), role.GoToPoint.GoToPoint::execute_drive(), tactics.CoPass.CoordinatedPass::execute_kicking(), tactics.CoPass.CoordinatedPass::execute_preparing(), role.pass_receive.PassReceive::execute_waiting(), kalman_filter::filter(), velocity.run::findPath(), test_role::function(), velocity.run::Get_Vel(), GUI.ompl_gui.MainWindow::goToBall(), bot_comm::gr_Commands_CB(), ssltest::gr_Commands_CB(), role._GoToPoint::init(), utils.functions.Circle::intersection_with_line(), role.pass_receive.PassReceive::is_ball_near(), tests.pid_tune::main(), GUI.ompl_gui.MainWindow::move_bot_1(), GUI.ompl_gui.MainWindow::move_bot_2(), GUI.ompl_gui.MainWindow::move_bot_3(), tactics.CoPass.CoordinatedPass::on_enter_kicking(), tactics.CoPass.CoordinatedPass::on_enter_preparing(), tactics.CoPass.CoordinatedPass::on_enter_receiving(), tactics.CoPass.CoordinatedPass::on_exit_kicking(), tactics.CoPass.CoordinatedPass::on_exit_receiving(), GUI.ompl_gui.MainWindow::path_listener(), velocity.pid_::pid(), velocity.pid::pid(), print(), BeliefState::print(), svg_filter::rectify(), velocity.profiler.Velocity::sendVelocity(), fsm.StateMachine::spin(), composite_behavior.CompositeBehavior::spin_cb(), StageCycleTimer< num >::stage(), velocity.profiler.Velocity::trapezoidalMotion(), GUI.ompl_gui.MainWindow::triangle_controller(), ssltest::vel_convert(), and bot_comm::vel_convert().
                      {
     cout<<"x: "<<p.x<<" y: "<<p.y<<endl;
 }
void print (vector< Pose2D > p)
Definition at line 38 of file node_class.cpp.
References velocity.pid_::i, and print().
{
     for(int i = 0; i < p.size(); i++)
     {
         cout<<"i: \t";
         print(p[i]);
     }
 }
void print (vector< bool > p)
Definition at line 46 of file node_class.cpp.
References velocity.pid_::i.
{
     for(int i=0;i<p.size();i++)
     {
         cout<<"i: \t"<<p[i]<<endl;
     }
 }
Variable Documentation
const int BALL_AT_CORNER_THRESH = 20
Definition at line 18 of file node_class.cpp.
Referenced by distFn().
const int DBOX_HEIGHT = 600
Definition at line 23 of file node_class.cpp.
Referenced by distFn().
const int DBOX_WIDTH = 600
Definition at line 22 of file node_class.cpp.
Referenced by distFn().
const int HALF_FIELD_MAXX = 3000
Definition at line 19 of file node_class.cpp.
Referenced by distFn().
const int HALF_FIELD_MAXY = 2000
Definition at line 20 of file node_class.cpp.
Referenced by distFn().
short int isteamyellow = 0
Definition at line 26 of file node_class.cpp.
Referenced by BeliefState::BeliefState(), distFn(), BeliefState::get_beliefstate_msg(), BeliefState::getBeliefStateMsg(), BeliefState::initialise(), main(), BeliefState::print(), and BeliefState::update_frame().
const float MAX_DRIBBLE_R = 3
Definition at line 21 of file node_class.cpp.
Referenced by distFn().
const int MAX_QUEUE_SZ = 5
Definition at line 24 of file node_class.cpp.
Referenced by distFn().
ros::Publisher pub
Definition at line 32 of file node_class.cpp.
Referenced by Callback(), and main().