Documentation: FrameDataMap Class Reference
FrameDataMap Class Reference
A general storage map, for plugins to store and read their data.
#include <framedata.h>
Public Member Functions
void * get (const string &label) const
void * insert (const string &label, void *item)
Detailed Description
A general storage map, for plugins to store and read their data.
Author
Stefan Zickler, (C) 2008
This class acts as a storage map of string and data-pointer pairs. This allows any plugin to make its results publicly available to the entire image stack pipeline for the current frame.
Definition at line 39 of file framedata.h.
Member Function Documentation
void* FrameDataMap::get (const string & label) const inline
Definition at line 42 of file framedata.h.
Referenced by GLWidget::displayLoopEvent(), PluginVisualize::DrawBlobs(), PluginVisualize::DrawThresholdedImage(), GLWidget::myGLdraw(), PluginColorThreshold::process(), PluginRunlengthEncode::process(), PluginFindBlobs::process(), PluginSSLNetworkOutput::process(), PluginLegacySSLNetworkOutput::process(), PluginDetectRobots::process(), PluginVisualize::process(), PluginDetectBalls::process(), CaptureThread::run(), and GLWidget::saveImage().
{
     map<string,void *>::const_iterator iter = map<string,void *>::find(label);
     if (iter==map<string,void *>::end()) return 0;
     return iter->second;
   }
void* FrameDataMap::insert (const string & label, void * item) inline
Definition at line 47 of file framedata.h.
Referenced by PluginColorThreshold::process(), PluginRunlengthEncode::process(), PluginFindBlobs::process(), PluginDetectRobots::process(), PluginVisualize::process(), PluginDetectBalls::process(), and CaptureThread::run().
{
     pair< map<string,void *>::iterator, bool > pair = map<string,void *>::insert ( make_pair(label,item) );
     if (pair.first==map<string,void *>::end()) return 0;
     return pair.first->second;
   }
The documentation for this class was generated from the following file:
ssl-vision/src/app/framedata.h