Documentation: Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData Class Reference
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData Class Reference
Data Structures
class Builder
Public Member Functions
SSL_GeometryData getDefaultInstanceForType ()
boolean hasField ()
MessagesRobocupSslGeometry.SSL_GeometryFieldSize getField ()
MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder getFieldOrBuilder ()
java.util.List< MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration > getCalibList ()
java.util.List<?extends MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder > getCalibOrBuilderList ()
int getCalibCount ()
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration getCalib (int index)
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder getCalibOrBuilder (int index)
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static SSL_GeometryData getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static MessagesRobocupSslGeometry.SSL_GeometryData parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslGeometry.SSL_GeometryData parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslGeometry.SSL_GeometryData parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslGeometry.SSL_GeometryData parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslGeometry.SSL_GeometryData parseFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryData parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryData parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryData parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryData parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryData parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (MessagesRobocupSslGeometry.SSL_GeometryData prototype)
Static Public Attributes
static final int FIELD_FIELD_NUMBER = 1
static final int CALIB_FIELD_NUMBER = 2
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
SSL_GeometryData (Builder builder)
SSL_GeometryData (boolean noInit)
void initFields ()
Private Attributes
int bitField0_
MessagesRobocupSslGeometry.SSL_GeometryFieldSize field_
java.util.List< MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration > calib_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final SSL_GeometryData defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 2452 of file MessagesRobocupSslGeometry.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.SSL_GeometryData (Builder builder) inline private
Definition at line 2456 of file MessagesRobocupSslGeometry.java.
{
       super(builder);
     }
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.SSL_GeometryData (boolean noInit) inline private
Definition at line 2459 of file MessagesRobocupSslGeometry.java.
 {}
Member Function Documentation
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getCalib (int index) inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2507 of file MessagesRobocupSslGeometry.java.
{
       return calib_.get(index);
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getCalibCount () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2504 of file MessagesRobocupSslGeometry.java.
{
       return calib_.size();
     }
java.util.List<MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration> Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getCalibList () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2497 of file MessagesRobocupSslGeometry.java.
{
       return calib_;
     }
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getCalibOrBuilder (int index) inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2510 of file MessagesRobocupSslGeometry.java.
                    {
       return calib_.get(index);
     }
java.util.List<? extends MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder> Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getCalibOrBuilderList () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2501 of file MessagesRobocupSslGeometry.java.
{
       return calib_;
     }
static SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance () inline static
Definition at line 2462 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.clear(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.clearGeometry(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getDefaultInstanceForType(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.initFields(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeFrom(), and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeGeometry().
{
       return defaultInstance;
     }
SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstanceForType () inline
Definition at line 2466 of file MessagesRobocupSslGeometry.java.
{
       return defaultInstance;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getDescriptor () inline static
Definition at line 2471 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.internal_static_SSL_GeometryData_descriptor.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getDescriptorForType().
{
       return MessagesRobocupSslGeometry.internal_static_SSL_GeometryData_descriptor;
     }
MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getField () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2487 of file MessagesRobocupSslGeometry.java.
{
       return field_;
     }
MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getFieldOrBuilder () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2490 of file MessagesRobocupSslGeometry.java.
{
       return field_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getSerializedSize () inline
Definition at line 2555 of file MessagesRobocupSslGeometry.java.
References velocity.pid_.i.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(1, field_);
       }
       for (int i = 0; i < calib_.size(); i++) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(2, calib_.get(i));
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.hasField () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder.
Definition at line 2484 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
void Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.initFields () inline private
Definition at line 2515 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance().
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.getCalibFieldBuilder().
{
       field_ = MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance();
       calib_ = java.util.Collections.emptyList();
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.internalGetFieldAccessorTable () inline protected
Definition at line 2476 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.internal_static_SSL_GeometryData_fieldAccessorTable.
{
       return MessagesRobocupSslGeometry.internal_static_SSL_GeometryData_fieldAccessorTable;
     }
final boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.isInitialized () inline
Definition at line 2520 of file MessagesRobocupSslGeometry.java.
References velocity.pid_.i.
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (!hasField()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!getField().isInitialized()) {
         memoizedIsInitialized = 0;
         return false;
       }
       for (int i = 0; i < getCalibCount(); i++) {
         if (!getCalib(i).isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.newBuilder () inline static
Definition at line 2647 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.create().
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom(), and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeGeometry().
 { return Builder.create(); }
static Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.newBuilder (MessagesRobocupSslGeometry.SSL_GeometryData prototype) inline static
Definition at line 2649 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.newBuilderForType () inline
Definition at line 2648 of file MessagesRobocupSslGeometry.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 2655 of file MessagesRobocupSslGeometry.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 2614 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 2623 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 2580 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 2585 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 2592 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 2596 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 2603 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 2607 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 2634 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 2639 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.toBuilder () inline
Definition at line 2652 of file MessagesRobocupSslGeometry.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 2575 of file MessagesRobocupSslGeometry.java.
{
       return super.writeReplace();
     }
void Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 2542 of file MessagesRobocupSslGeometry.java.
References velocity.pid_.i.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeMessage(1, field_);
       }
       for (int i = 0; i < calib_.size(); i++) {
         output.writeMessage(2, calib_.get(i));
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.bitField0_ private
Definition at line 2480 of file MessagesRobocupSslGeometry.java.
java.util.List<MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration> Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.calib_ private
Definition at line 2496 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.CALIB_FIELD_NUMBER = 2 static
Definition at line 2495 of file MessagesRobocupSslGeometry.java.
final SSL_GeometryData Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.defaultInstance static private
Definition at line 2461 of file MessagesRobocupSslGeometry.java.
MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.field_ private
Definition at line 2483 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.buildPartial().
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.FIELD_FIELD_NUMBER = 1 static
Definition at line 2482 of file MessagesRobocupSslGeometry.java.
byte Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.memoizedIsInitialized = -1 private
Definition at line 2519 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.memoizedSerializedSize = -1 private
Definition at line 2554 of file MessagesRobocupSslGeometry.java.
final long Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.serialVersionUID = 0L static private
Definition at line 2573 of file MessagesRobocupSslGeometry.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslGeometry.java