Documentation: Protobuf.GrSimPacket.grSim_Packet.Builder Class Reference
Protobuf.GrSimPacket.grSim_Packet.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
GrSimPacket.grSim_Packet getDefaultInstanceForType ()
GrSimPacket.grSim_Packet build ()
GrSimPacket.grSim_Packet buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (GrSimPacket.grSim_Packet other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasCommands ()
GrSimCommands.grSim_Commands getCommands ()
Builder setCommands (GrSimCommands.grSim_Commands value)
Builder setCommands (GrSimCommands.grSim_Commands.Builder builderForValue)
Builder mergeCommands (GrSimCommands.grSim_Commands value)
Builder clearCommands ()
GrSimCommands.grSim_Commands.Builder getCommandsBuilder ()
GrSimCommands.grSim_CommandsOrBuilder getCommandsOrBuilder ()
boolean hasReplacement ()
GrSimReplacement.grSim_Replacement getReplacement ()
Builder setReplacement (GrSimReplacement.grSim_Replacement value)
Builder setReplacement (GrSimReplacement.grSim_Replacement.Builder builderForValue)
Builder mergeReplacement (GrSimReplacement.grSim_Replacement value)
Builder clearReplacement ()
GrSimReplacement.grSim_Replacement.Builder getReplacementBuilder ()
GrSimReplacement.grSim_ReplacementOrBuilder getReplacementOrBuilder ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
GrSimPacket.grSim_Packet buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
com.google.protobuf.SingleFieldBuilder< GrSimCommands.grSim_Commands, GrSimCommands.grSim_Commands.Builder, GrSimCommands.grSim_CommandsOrBuilder > getCommandsFieldBuilder ()
com.google.protobuf.SingleFieldBuilder< GrSimReplacement.grSim_Replacement, GrSimReplacement.grSim_Replacement.Builder, GrSimReplacement.grSim_ReplacementOrBuilder > getReplacementFieldBuilder ()
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
GrSimCommands.grSim_Commands commands_ = GrSimCommands.grSim_Commands.getDefaultInstance()
com.google.protobuf.SingleFieldBuilder< GrSimCommands.grSim_Commands, GrSimCommands.grSim_Commands.Builder, GrSimCommands.grSim_CommandsOrBuilder > commandsBuilder_
GrSimReplacement.grSim_Replacement replacement_ = GrSimReplacement.grSim_Replacement.getDefaultInstance()
com.google.protobuf.SingleFieldBuilder< GrSimReplacement.grSim_Replacement, GrSimReplacement.grSim_Replacement.Builder, GrSimReplacement.grSim_ReplacementOrBuilder > replacementBuilder_
Detailed Description
Definition at line 221 of file GrSimPacket.java.
Constructor & Destructor Documentation
Protobuf.GrSimPacket.grSim_Packet.Builder.Builder () inline private
Definition at line 235 of file GrSimPacket.java.
Referenced by Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.GrSimPacket.grSim_Packet.Builder.Builder (BuilderParent parent) inline private
Definition at line 239 of file GrSimPacket.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.Builder.build () inline
Definition at line 283 of file GrSimPacket.java.
Referenced by Client.Conection.send(), Protobuf.GrSimPacket.grSim_Packet.Builder.setCommands(), and Protobuf.GrSimPacket.grSim_Packet.Builder.setReplacement().
{
         GrSimPacket.grSim_Packet result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 291 of file GrSimPacket.java.
Referenced by Protobuf.GrSimPacket.grSim_Packet.parseDelimitedFrom().
{
         GrSimPacket.grSim_Packet result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.Builder.buildPartial () inline
Definition at line 301 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.commands_.
{
         GrSimPacket.grSim_Packet result = new GrSimPacket.grSim_Packet(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         if (commandsBuilder_ == null) {
           result.commands_ = commands_;
         } else {
           result.commands_ = commandsBuilder_.build();
         }
         if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
           to_bitField0_ |= 0x00000002;
         }
         if (replacementBuilder_ == null) {
           result.replacement_ = replacement_;
         } else {
           result.replacement_ = replacementBuilder_.build();
         }
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.GrSimPacket.grSim_Packet.Builder.clear () inline
Definition at line 253 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.Builder.clear(), Protobuf.GrSimCommands.grSim_Commands.getDefaultInstance(), and Protobuf.GrSimReplacement.grSim_Replacement.getDefaultInstance().
Referenced by Protobuf.GrSimPacket.grSim_Packet.Builder.clear().
{
         super.clear();
         if (commandsBuilder_ == null) {
           commands_ = GrSimCommands.grSim_Commands.getDefaultInstance();
         } else {
           commandsBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000001);
         if (replacementBuilder_ == null) {
           replacement_ = GrSimReplacement.grSim_Replacement.getDefaultInstance();
         } else {
           replacementBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000002);
         return this;
       }
Builder Protobuf.GrSimPacket.grSim_Packet.Builder.clearCommands () inline
Definition at line 464 of file GrSimPacket.java.
References Protobuf.GrSimCommands.grSim_Commands.getDefaultInstance().
{
         if (commandsBuilder_ == null) {
           commands_ = GrSimCommands.grSim_Commands.getDefaultInstance();
           onChanged();
         } else {
           commandsBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000001);
         return this;
       }
Builder Protobuf.GrSimPacket.grSim_Packet.Builder.clearReplacement () inline
Definition at line 554 of file GrSimPacket.java.
References Protobuf.GrSimReplacement.grSim_Replacement.getDefaultInstance().
{
         if (replacementBuilder_ == null) {
           replacement_ = GrSimReplacement.grSim_Replacement.getDefaultInstance();
           onChanged();
         } else {
           replacementBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000002);
         return this;
       }
Builder Protobuf.GrSimPacket.grSim_Packet.Builder.clone () inline
Definition at line 270 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.GrSimPacket.grSim_Packet.Builder.create () inline static private
Definition at line 249 of file GrSimPacket.java.
Referenced by Protobuf.GrSimPacket.grSim_Packet.newBuilder().
{
         return new Builder();
       }
GrSimCommands.grSim_Commands Protobuf.GrSimPacket.grSim_Packet.Builder.getCommands () inline
Implements Protobuf.GrSimPacket.grSim_PacketOrBuilder.
Definition at line 417 of file GrSimPacket.java.
{
         if (commandsBuilder_ == null) {
           return commands_;
         } else {
           return commandsBuilder_.getMessage();
         }
       }
GrSimCommands.grSim_Commands.Builder Protobuf.GrSimPacket.grSim_Packet.Builder.getCommandsBuilder () inline
Definition at line 474 of file GrSimPacket.java.
{
         bitField0_ |= 0x00000001;
         onChanged();
         return getCommandsFieldBuilder().getBuilder();
       }
com.google.protobuf.SingleFieldBuilder< GrSimCommands.grSim_Commands, GrSimCommands.grSim_Commands.Builder, GrSimCommands.grSim_CommandsOrBuilder> Protobuf.GrSimPacket.grSim_Packet.Builder.getCommandsFieldBuilder () inline private
Definition at line 488 of file GrSimPacket.java.
{
         if (commandsBuilder_ == null) {
           commandsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
               GrSimCommands.grSim_Commands, GrSimCommands.grSim_Commands.Builder, GrSimCommands.grSim_CommandsOrBuilder>(
                   commands_,
                   getParentForChildren(),
                   isClean());
           commands_ = null;
         }
         return commandsBuilder_;
       }
GrSimCommands.grSim_CommandsOrBuilder Protobuf.GrSimPacket.grSim_Packet.Builder.getCommandsOrBuilder () inline
Implements Protobuf.GrSimPacket.grSim_PacketOrBuilder.
Definition at line 479 of file GrSimPacket.java.
{
         if (commandsBuilder_ != null) {
           return commandsBuilder_.getMessageOrBuilder();
         } else {
           return commands_;
         }
       }
GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.Builder.getDefaultInstanceForType () inline
Definition at line 279 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.getDefaultInstance().
{
         return GrSimPacket.grSim_Packet.getDefaultInstance();
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimPacket.grSim_Packet.Builder.getDescriptor () inline static
Definition at line 225 of file GrSimPacket.java.
References Protobuf.GrSimPacket.internal_static_grSim_Packet_descriptor.
{
         return GrSimPacket.internal_static_grSim_Packet_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimPacket.grSim_Packet.Builder.getDescriptorForType () inline
Definition at line 275 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.getDescriptor().
{
         return GrSimPacket.grSim_Packet.getDescriptor();
       }
GrSimReplacement.grSim_Replacement Protobuf.GrSimPacket.grSim_Packet.Builder.getReplacement () inline
Implements Protobuf.GrSimPacket.grSim_PacketOrBuilder.
Definition at line 507 of file GrSimPacket.java.
{
         if (replacementBuilder_ == null) {
           return replacement_;
         } else {
           return replacementBuilder_.getMessage();
         }
       }
GrSimReplacement.grSim_Replacement.Builder Protobuf.GrSimPacket.grSim_Packet.Builder.getReplacementBuilder () inline
Definition at line 564 of file GrSimPacket.java.
{
         bitField0_ |= 0x00000002;
         onChanged();
         return getReplacementFieldBuilder().getBuilder();
       }
com.google.protobuf.SingleFieldBuilder< GrSimReplacement.grSim_Replacement, GrSimReplacement.grSim_Replacement.Builder, GrSimReplacement.grSim_ReplacementOrBuilder> Protobuf.GrSimPacket.grSim_Packet.Builder.getReplacementFieldBuilder () inline private
Definition at line 578 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.initFields().
{
         if (replacementBuilder_ == null) {
           replacementBuilder_ = new com.google.protobuf.SingleFieldBuilder<
               GrSimReplacement.grSim_Replacement, GrSimReplacement.grSim_Replacement.Builder, GrSimReplacement.grSim_ReplacementOrBuilder>(
                   replacement_,
                   getParentForChildren(),
                   isClean());
           replacement_ = null;
         }
         return replacementBuilder_;
       }
GrSimReplacement.grSim_ReplacementOrBuilder Protobuf.GrSimPacket.grSim_Packet.Builder.getReplacementOrBuilder () inline
Implements Protobuf.GrSimPacket.grSim_PacketOrBuilder.
Definition at line 569 of file GrSimPacket.java.
{
         if (replacementBuilder_ != null) {
           return replacementBuilder_.getMessageOrBuilder();
         } else {
           return replacement_;
         }
       }
boolean Protobuf.GrSimPacket.grSim_Packet.Builder.hasCommands () inline
Implements Protobuf.GrSimPacket.grSim_PacketOrBuilder.
Definition at line 414 of file GrSimPacket.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
boolean Protobuf.GrSimPacket.grSim_Packet.Builder.hasReplacement () inline
Implements Protobuf.GrSimPacket.grSim_PacketOrBuilder.
Definition at line 504 of file GrSimPacket.java.
{
         return ((bitField0_ & 0x00000002) == 0x00000002);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.GrSimPacket.grSim_Packet.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 230 of file GrSimPacket.java.
References Protobuf.GrSimPacket.internal_static_grSim_Packet_fieldAccessorTable.
{
         return GrSimPacket.internal_static_grSim_Packet_fieldAccessorTable;
       }
final boolean Protobuf.GrSimPacket.grSim_Packet.Builder.isInitialized () inline
Definition at line 347 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_PacketOrBuilder.getCommands(), Protobuf.GrSimPacket.grSim_PacketOrBuilder.getReplacement(), Protobuf.GrSimPacket.grSim_PacketOrBuilder.hasCommands(), and Protobuf.GrSimPacket.grSim_PacketOrBuilder.hasReplacement().
{
         if (hasCommands()) {
           if (!getCommands().isInitialized()) {
             return false;
           }
         }
         if (hasReplacement()) {
           if (!getReplacement().isInitialized()) {
             return false;
           }
         }
         return true;
       }
void Protobuf.GrSimPacket.grSim_Packet.Builder.maybeForceBuilderInitialization () inline private
Definition at line 243 of file GrSimPacket.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
           getCommandsFieldBuilder();
           getReplacementFieldBuilder();
         }
       }
Builder Protobuf.GrSimPacket.grSim_Packet.Builder.mergeCommands (GrSimCommands.grSim_Commands value) inline
Definition at line 448 of file GrSimPacket.java.
References Protobuf.GrSimCommands.grSim_Commands.Builder.buildPartial(), Protobuf.GrSimCommands.grSim_Commands.getDefaultInstance(), Protobuf.GrSimCommands.grSim_Commands.Builder.mergeFrom(), and Protobuf.GrSimCommands.grSim_Commands.newBuilder().
{
         if (commandsBuilder_ == null) {
           if (((bitField0_ & 0x00000001) == 0x00000001) &&
               commands_ != GrSimCommands.grSim_Commands.getDefaultInstance()) {
             commands_ =
               GrSimCommands.grSim_Commands.newBuilder(commands_).mergeFrom(value).buildPartial();
           } else {
             commands_ = value;
           }
           onChanged();
         } else {
           commandsBuilder_.mergeFrom(value);
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 326 of file GrSimPacket.java.
Referenced by Protobuf.GrSimPacket.grSim_Packet.Builder.clone(), and Protobuf.GrSimPacket.grSim_Packet.newBuilder().
{
         if (other instanceof GrSimPacket.grSim_Packet) {
           return mergeFrom((GrSimPacket.grSim_Packet)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom (GrSimPacket.grSim_Packet other) inline
Definition at line 335 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.getDefaultInstance().
{
         if (other == GrSimPacket.grSim_Packet.getDefaultInstance()) return this;
         if (other.hasCommands()) {
           mergeCommands(other.getCommands());
         }
         if (other.hasReplacement()) {
           mergeReplacement(other.getReplacement());
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 363 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.Builder.Builder(), Protobuf.GrSimPacket.grSim_PacketOrBuilder.getCommands(), Protobuf.GrSimPacket.grSim_PacketOrBuilder.getReplacement(), Protobuf.GrSimPacket.grSim_PacketOrBuilder.hasCommands(), Protobuf.GrSimPacket.grSim_PacketOrBuilder.hasReplacement(), Protobuf.GrSimCommands.grSim_Commands.Builder.mergeFrom(), Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeFrom(), Protobuf.GrSimCommands.grSim_Commands.newBuilder(), and Protobuf.GrSimReplacement.grSim_Replacement.newBuilder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 10: {
               GrSimCommands.grSim_Commands.Builder subBuilder = GrSimCommands.grSim_Commands.newBuilder();
               if (hasCommands()) {
                 subBuilder.mergeFrom(getCommands());
               }
               input.readMessage(subBuilder, extensionRegistry);
               setCommands(subBuilder.buildPartial());
               break;
             }
             case 18: {
               GrSimReplacement.grSim_Replacement.Builder subBuilder = GrSimReplacement.grSim_Replacement.newBuilder();
               if (hasReplacement()) {
                 subBuilder.mergeFrom(getReplacement());
               }
               input.readMessage(subBuilder, extensionRegistry);
               setReplacement(subBuilder.buildPartial());
               break;
             }
           }
         }
       }
Builder Protobuf.GrSimPacket.grSim_Packet.Builder.mergeReplacement (GrSimReplacement.grSim_Replacement value) inline
Definition at line 538 of file GrSimPacket.java.
References Protobuf.GrSimReplacement.grSim_Replacement.Builder.buildPartial(), Protobuf.GrSimReplacement.grSim_Replacement.getDefaultInstance(), Protobuf.GrSimReplacement.grSim_Replacement.Builder.mergeFrom(), and Protobuf.GrSimReplacement.grSim_Replacement.newBuilder().
{
         if (replacementBuilder_ == null) {
           if (((bitField0_ & 0x00000002) == 0x00000002) &&
               replacement_ != GrSimReplacement.grSim_Replacement.getDefaultInstance()) {
             replacement_ =
               GrSimReplacement.grSim_Replacement.newBuilder(replacement_).mergeFrom(value).buildPartial();
           } else {
             replacement_ = value;
           }
           onChanged();
         } else {
           replacementBuilder_.mergeFrom(value);
         }
         bitField0_ |= 0x00000002;
         return this;
       }
Builder Protobuf.GrSimPacket.grSim_Packet.Builder.setCommands (GrSimCommands.grSim_Commands value) inline
Definition at line 424 of file GrSimPacket.java.
Referenced by Client.Conection.send().
{
         if (commandsBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           commands_ = value;
           onChanged();
         } else {
           commandsBuilder_.setMessage(value);
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.GrSimPacket.grSim_Packet.Builder.setCommands (GrSimCommands.grSim_Commands.Builder builderForValue) inline
Definition at line 437 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.Builder.build().
{
         if (commandsBuilder_ == null) {
           commands_ = builderForValue.build();
           onChanged();
         } else {
           commandsBuilder_.setMessage(builderForValue.build());
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.GrSimPacket.grSim_Packet.Builder.setReplacement (GrSimReplacement.grSim_Replacement value) inline
Definition at line 514 of file GrSimPacket.java.
{
         if (replacementBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           replacement_ = value;
           onChanged();
         } else {
           replacementBuilder_.setMessage(value);
         }
         bitField0_ |= 0x00000002;
         return this;
       }
Builder Protobuf.GrSimPacket.grSim_Packet.Builder.setReplacement (GrSimReplacement.grSim_Replacement.Builder builderForValue) inline
Definition at line 527 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.Builder.build().
{
         if (replacementBuilder_ == null) {
           replacement_ = builderForValue.build();
           onChanged();
         } else {
           replacementBuilder_.setMessage(builderForValue.build());
         }
         bitField0_ |= 0x00000002;
         return this;
       }
Field Documentation
int Protobuf.GrSimPacket.grSim_Packet.Builder.bitField0_ private
Definition at line 408 of file GrSimPacket.java.
GrSimCommands.grSim_Commands Protobuf.GrSimPacket.grSim_Packet.Builder.commands_ = GrSimCommands.grSim_Commands.getDefaultInstance() private
Definition at line 411 of file GrSimPacket.java.
com.google.protobuf.SingleFieldBuilder< GrSimCommands.grSim_Commands, GrSimCommands.grSim_Commands.Builder, GrSimCommands.grSim_CommandsOrBuilder> Protobuf.GrSimPacket.grSim_Packet.Builder.commandsBuilder_ private
Definition at line 413 of file GrSimPacket.java.
GrSimReplacement.grSim_Replacement Protobuf.GrSimPacket.grSim_Packet.Builder.replacement_ = GrSimReplacement.grSim_Replacement.getDefaultInstance() private
Definition at line 501 of file GrSimPacket.java.
com.google.protobuf.SingleFieldBuilder< GrSimReplacement.grSim_Replacement, GrSimReplacement.grSim_Replacement.Builder, GrSimReplacement.grSim_ReplacementOrBuilder> Protobuf.GrSimPacket.grSim_Packet.Builder.replacementBuilder_ private
Definition at line 503 of file GrSimPacket.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimPacket.java