Documentation: PluginLegacySSLNetworkOutput Class Reference
PluginLegacySSLNetworkOutput Class Reference
#include <plugin_legacysslnetworkoutput.h>
Public Member Functions
PluginLegacySSLNetworkOutput (FrameBuffer *_fb, RoboCupSSLServer *ds_udp_server_old, const CameraParameters &camera_params, const RoboCupField &field)
~PluginLegacySSLNetworkOutput ()
virtual ProcessResult process (FrameData *data, RenderOptions *options)
virtual string getName ()
bool DoubleSizeToSingleSize (const bool primary_field, const float x_in, const float y_in, const float a_in, float *x_out, float *y_out, float *a_out)
Public Member Functions inherited from VisionPlugin
VisionPlugin (FrameBuffer *_buffer)
virtual ~VisionPlugin ()
FrameBuffer * getFrameBuffer () const
this functions provides convenient access to the ring-buffer
void lock ()
void unlock ()
virtual bool isEnabled () const
virtual void setEnabled (bool enable)
virtual bool isVisualize () const
virtual void setVisualize (bool enable)
virtual bool isSharedAmongStacks () const
virtual void setSharedAmongStacks (bool enable)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual VarList * getSettings ()
virtual void postProcess (FrameData *data, RenderOptions *options)
virtual QWidget * getVisualizationWidget ()
virtual QWidget * getControlWidget ()
virtual void closeWidgets ()
virtual QList< QAction * > actions ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
void setTimeProcessing (double val)
void setTimePostProcessing (double val)
double getTimeProcessing ()
double getTimePostProcessing ()
Protected Attributes
const CameraParameters & _camera_params
const RoboCupField & _field
RoboCupSSLServer * _ds_udp_server_old
Protected Attributes inherited from VisionPlugin
QMutex mutex
bool enabled
bool visualize
bool shared
FrameBuffer * buffer
double time_proc
double time_post
Additional Inherited Members
Public Slots inherited from VisionPlugin
void slotKeyPressEvent (QKeyEvent *event)
Detailed Description
Definition at line 31 of file plugin_legacysslnetworkoutput.h.
Constructor & Destructor Documentation
PluginLegacySSLNetworkOutput::PluginLegacySSLNetworkOutput (FrameBuffer * _fb, RoboCupSSLServer * ds_udp_server_old, const CameraParameters & camera_params, const RoboCupField & field)
Definition at line 23 of file plugin_legacysslnetworkoutput.cpp.
                                :
     VisionPlugin(_fb),
     _camera_params(camera_params),
     _field(field),
     _ds_udp_server_old(ds_udp_server_old) {}
PluginLegacySSLNetworkOutput::~PluginLegacySSLNetworkOutput ()
Definition at line 33 of file plugin_legacysslnetworkoutput.cpp.
 {}
Member Function Documentation
bool PluginLegacySSLNetworkOutput::DoubleSizeToSingleSize (const bool primary_field, const float x_in, const float y_in, const float a_in, float * x_out, float * y_out, float * a_out)
Definition at line 35 of file plugin_legacysslnetworkoutput.cpp.
References _field, angle_mod(), RoboCupField::field_length, RoboCupField::field_lines, VarTypes::VarDoubleVal::getDouble(), GetFieldLine(), GVector::max(), GVector::min(), FieldLine::p1_x, FieldLine::p2_x, RAD, and FieldLine::thickness.
                   {
   const float half_field_length =
       primary_field ?
       -min(GetFieldLine("TopTouchLine", _field.field_lines)->
               p1_x->getDouble(),
            GetFieldLine("TopTouchLine", _field.field_lines)->
               p2_x->getDouble()) :
       max(GetFieldLine("TopTouchLine", _field.field_lines)->p1_x->getDouble(),
           GetFieldLine("TopTouchLine", _field.field_lines)->p2_x->getDouble());
   _field.field_length->getDouble();
   const float line_width =
       GetFieldLine("HalfwayLine", _field.field_lines)->thickness->getDouble();
   // Ignore robots not within the referee margin minus robot radius
   if (primary_field) {
     if (x_in > 425.0 - 90.0) return false;
     *y_out = -(x_in + 0.5 * half_field_length - 0.5 * line_width);
   } else {
     if (x_in < -425.0 + 90.0) return false;
     *y_out = -(x_in - 0.5 * half_field_length + 0.5 * line_width);
   }
   *x_out = y_in;
   *a_out = angle_mod(a_in - RAD(90.0));
   return true;
 }
string PluginLegacySSLNetworkOutput::getName () virtual
Reimplemented from VisionPlugin.
Definition at line 86 of file plugin_legacysslnetworkoutput.cpp.
{
   return "Legacy Network Output";
 }
ProcessResult PluginLegacySSLNetworkOutput::process (FrameData * data, RenderOptions * options) virtual
Reimplemented from VisionPlugin.
Definition at line 67 of file plugin_legacysslnetworkoutput.cpp.
References _ds_udp_server_old, FrameData::cam_id, FrameDataMap::get(), GetTimeSec(), FrameData::map, FrameData::number, ProcessingFailed, ProcessingOk, RoboCupSSLServer::sendLegacyMessage(), and FrameData::time.
{
   (void)options;
   if (data==0) return ProcessingFailed;
   SSL_DetectionFrame * detection_frame = 0;
   detection_frame=(SSL_DetectionFrame *)data->map.get("ssl_detection_frame");
   if (detection_frame != 0) {
     detection_frame->set_t_capture(data->time);
     detection_frame->set_frame_number(data->number);
     detection_frame->set_camera_id(data->cam_id);
     detection_frame->set_t_sent(GetTimeSec());
     // The double-sized field server uses the normal field coordinates.
     _ds_udp_server_old->sendLegacyMessage(*detection_frame);
   }
   return ProcessingOk;
 }
Field Documentation
const CameraParameters& PluginLegacySSLNetworkOutput::_camera_params protected
Definition at line 34 of file plugin_legacysslnetworkoutput.h.
RoboCupSSLServer* PluginLegacySSLNetworkOutput::_ds_udp_server_old protected
Definition at line 37 of file plugin_legacysslnetworkoutput.h.
Referenced by process().
const RoboCupField& PluginLegacySSLNetworkOutput::_field protected
Definition at line 35 of file plugin_legacysslnetworkoutput.h.
Referenced by DoubleSizeToSingleSize().
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/plugin_legacysslnetworkoutput.h
ssl-vision/src/app/plugins/plugin_legacysslnetworkoutput.cpp