Documentation: PluginLegacyPublishGeometry Class Reference
PluginLegacyPublishGeometry Class Reference
#include <plugin_legacypublishgeometry.h>
Public Member Functions
PluginLegacyPublishGeometry (FrameBuffer *fb, RoboCupSSLServer *ds_udp_server_old, const RoboCupField &field)
void addCameraParameters (CameraParameters *param)
virtual VarList * getSettings ()
virtual ~PluginLegacyPublishGeometry ()
virtual string getName ()
virtual ProcessResult process (FrameData *data, RenderOptions *options)
float GetFieldCircularArcRadius (const string &arc_name)
float GetFieldLineLength (const string &line_name)
float GetFieldLineThickness (const string &line_name)
Public Member Functions inherited from VisionPlugin
VisionPlugin (FrameBuffer *_buffer)
virtual ~VisionPlugin ()
FrameBuffer * getFrameBuffer () const
this functions provides convenient access to the ring-buffer
void lock ()
void unlock ()
virtual bool isEnabled () const
virtual void setEnabled (bool enable)
virtual bool isVisualize () const
virtual void setVisualize (bool enable)
virtual bool isSharedAmongStacks () const
virtual void setSharedAmongStacks (bool enable)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual void postProcess (FrameData *data, RenderOptions *options)
virtual QWidget * getVisualizationWidget ()
virtual QWidget * getControlWidget ()
virtual void closeWidgets ()
virtual QList< QAction * > actions ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
void setTimeProcessing (double val)
void setTimePostProcessing (double val)
double getTimeProcessing ()
double getTimePostProcessing ()
Protected Slots
void slotPublishTriggered ()
Protected Member Functions
void sendGeometry ()
Protected Attributes
RoboCupSSLServer * _ds_udp_server_old
const RoboCupField & _field
vector< CameraParameters * > params
VarList * _settings
VarTrigger * _pub
VarBool * _pub_auto_enable
VarDouble * _pub_auto_interval
VarList * _pub_auto
QMutex mutex
double last_t
Protected Attributes inherited from VisionPlugin
QMutex mutex
bool enabled
bool visualize
bool shared
FrameBuffer * buffer
double time_proc
double time_post
Additional Inherited Members
Public Slots inherited from VisionPlugin
void slotKeyPressEvent (QKeyEvent *event)
Detailed Description
Definition at line 38 of file plugin_legacypublishgeometry.h.
Constructor & Destructor Documentation
PluginLegacyPublishGeometry::PluginLegacyPublishGeometry (FrameBuffer * fb, RoboCupSSLServer * ds_udp_server_old, const RoboCupField & field)
Definition at line 47 of file plugin_legacypublishgeometry.cpp.
References _pub, _pub_auto, _pub_auto_enable, _pub_auto_interval, _settings, VarTypes::VarList::addChild(), last_t, VisionPlugin::setSharedAmongStacks(), and slotPublishTriggered().
                                :
     VisionPlugin(fb),
     _ds_udp_server_old(ds_udp_server_old),
     _field(field) {
   setSharedAmongStacks(true);
   _settings=new VarList("Publish Legacy Geometry");
   _settings->addChild(_pub=new VarTrigger("Publish","Publish!"));
   _settings->addChild(_pub_auto=new VarList("Auto Publish"));
   _pub_auto->addChild(_pub_auto_enable=new VarBool("Enable",true));
   _pub_auto->addChild(_pub_auto_interval=new VarDouble("Interval (seconds)",3.0));
   last_t=0;
   connect(_pub,SIGNAL(signalTriggered()),this,SLOT(slotPublishTriggered()));
 }
PluginLegacyPublishGeometry::~PluginLegacyPublishGeometry () virtual
Definition at line 70 of file plugin_legacypublishgeometry.cpp.
References _pub, and _settings.
{
   delete _settings;
   delete _pub;
 }
Member Function Documentation
void PluginLegacyPublishGeometry::addCameraParameters (CameraParameters * param)
Definition at line 64 of file plugin_legacypublishgeometry.cpp.
References VisionPlugin::lock(), params, and VisionPlugin::unlock().
Referenced by StackRoboCupSSL::StackRoboCupSSL().
{
   lock();
   params.push_back(param);
   unlock();
 }
float PluginLegacyPublishGeometry::GetFieldCircularArcRadius (const string & arc_name)
Definition at line 138 of file plugin_legacypublishgeometry.cpp.
References _field, RoboCupField::field_arcs, VarTypes::VarDoubleVal::getDouble(), GetFieldCircularArc(), FieldCircularArc::radius, and FieldCircularArc::thickness.
Referenced by sendGeometry().
{
   const FieldCircularArc* arc =
       GetFieldCircularArc(arc_name, _field.field_arcs);
   if (arc == NULL) return 0;
   return (arc->radius->getDouble() + 0.5 * arc->thickness->getDouble());
 }
float PluginLegacyPublishGeometry::GetFieldLineLength (const string & line_name)
Definition at line 124 of file plugin_legacypublishgeometry.cpp.
References _field, RoboCupField::field_lines, VarTypes::VarDoubleVal::getDouble(), GetFieldLine(), FieldLine::p1_x, FieldLine::p1_y, FieldLine::p2_x, FieldLine::p2_y, and sq().
Referenced by sendGeometry().
{
   const FieldLine* line = GetFieldLine(line_name, _field.field_lines);
   if (line == NULL) return 0;
   return (sqrt(sq(line->p1_x->getDouble() - line->p2_x->getDouble())
         + sq(line->p1_y->getDouble() - line->p2_y->getDouble())));
 }
float PluginLegacyPublishGeometry::GetFieldLineThickness (const string & line_name)
Definition at line 131 of file plugin_legacypublishgeometry.cpp.
References _field, RoboCupField::field_lines, VarTypes::VarDoubleVal::getDouble(), GetFieldLine(), and FieldLine::thickness.
{
   const FieldLine* line = GetFieldLine(line_name, _field.field_lines);
   if (line == NULL) return 0;
   return (line->thickness->getDouble());
 }
string PluginLegacyPublishGeometry::getName () virtual
Reimplemented from VisionPlugin.
Definition at line 79 of file plugin_legacypublishgeometry.cpp.
{
   return "Publish Geometry";
 }
VarList * PluginLegacyPublishGeometry::getSettings () virtual
Reimplemented from VisionPlugin.
Definition at line 75 of file plugin_legacypublishgeometry.cpp.
References _settings.
{
   return _settings;
 }
ProcessResult PluginLegacyPublishGeometry::process (FrameData * data, RenderOptions * options) virtual
Reimplemented from VisionPlugin.
Definition at line 152 of file plugin_legacypublishgeometry.cpp.
References _pub_auto_enable, _pub_auto_interval, VarTypes::VarBoolVal::getBool(), VarTypes::VarDoubleVal::getDouble(), last_t, ProcessingOk, sendGeometry(), t, and FrameData::time.
{
   (void)data;
   (void)options;
   //TODO: check client requests in server process
   //      if requested, call sendGeometry();
   if (_pub_auto_enable->getBool()==true) {
     double t = data->time - last_t;
     if (t > _pub_auto_interval->getDouble()) {
       sendGeometry();
       last_t=data->time;
     }
   }
   return ProcessingOk;
 }
void PluginLegacyPublishGeometry::sendGeometry () protected
Definition at line 83 of file plugin_legacypublishgeometry.cpp.
References _ds_udp_server_old, _field, GetFieldCircularArcRadius(), GetFieldLineLength(), velocity.pid_::i, params, RoboCupSSLServer::sendLegacyMessage(), and RoboCupField::toProtoBuffer().
Referenced by process(), and slotPublishTriggered().
{
   // NOTE: The field dimensions are derived from one half irrespective of
   // the exact field half / end in question.
   SSL_GeometryFieldSize field;
   _field.toProtoBuffer(field);
   // Geometry data for double-sized field in old format.
   RoboCup2014Legacy::Geometry::SSL_GeometryData ds_geodata_old;
   // Field data for double-sized field in old format.
   RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize ds_field_old;
   ds_field_old.set_field_length(field.field_length());
   ds_field_old.set_field_width(field.field_width());
   ds_field_old.set_goal_width(field.goal_width());
   ds_field_old.set_goal_depth(field.goal_depth());
   ds_field_old.set_boundary_width(field.boundary_width());
   ds_field_old.set_center_circle_radius(
       GetFieldCircularArcRadius("CenterCircle"));
   ds_field_old.set_defense_radius(
       GetFieldCircularArcRadius("LeftFieldLeftPenaltyArc"));
   ds_field_old.set_defense_stretch(GetFieldLineLength("LeftPenaltyStretch"));
   // The following fields no longer exist in ssl-vision, and are hard-coded
   // from the ssl-vision SVN trunk, r233.
   ds_field_old.set_line_width(10);
   ds_field_old.set_referee_width(425);
   ds_field_old.set_goal_wall_width(20);
   ds_field_old.set_free_kick_from_defense_dist(200);
   ds_field_old.set_penalty_spot_from_field_line_dist(750);
   ds_field_old.set_penalty_line_from_spot_dist(400);
   *ds_geodata_old.mutable_field() = ds_field_old;
   // Copy over the camera calibrations.
   for (unsigned int i = 0; i < params.size(); i++) {
     SSL_GeometryCameraCalibration* ds_calib_old = ds_geodata_old.add_calib();
     params[i]->toProtoBuffer(*ds_calib_old,i);
   }
   _ds_udp_server_old->sendLegacyMessage(ds_geodata_old);
 }
void PluginLegacyPublishGeometry::slotPublishTriggered () protected slot
Definition at line 146 of file plugin_legacypublishgeometry.cpp.
References VisionPlugin::lock(), sendGeometry(), and VisionPlugin::unlock().
Referenced by PluginLegacyPublishGeometry().
{
   lock();
   sendGeometry();
   unlock();
 }
Field Documentation
RoboCupSSLServer* PluginLegacyPublishGeometry::_ds_udp_server_old protected
Definition at line 43 of file plugin_legacypublishgeometry.h.
Referenced by sendGeometry().
const RoboCupField& PluginLegacyPublishGeometry::_field protected
Definition at line 44 of file plugin_legacypublishgeometry.h.
Referenced by GetFieldCircularArcRadius(), GetFieldLineLength(), GetFieldLineThickness(), and sendGeometry().
VarTrigger* PluginLegacyPublishGeometry::_pub protected
Definition at line 47 of file plugin_legacypublishgeometry.h.
Referenced by PluginLegacyPublishGeometry(), and ~PluginLegacyPublishGeometry().
VarList* PluginLegacyPublishGeometry::_pub_auto protected
Definition at line 50 of file plugin_legacypublishgeometry.h.
Referenced by PluginLegacyPublishGeometry().
VarBool* PluginLegacyPublishGeometry::_pub_auto_enable protected
Definition at line 48 of file plugin_legacypublishgeometry.h.
Referenced by PluginLegacyPublishGeometry(), and process().
VarDouble* PluginLegacyPublishGeometry::_pub_auto_interval protected
Definition at line 49 of file plugin_legacypublishgeometry.h.
Referenced by PluginLegacyPublishGeometry(), and process().
VarList* PluginLegacyPublishGeometry::_settings protected
Definition at line 46 of file plugin_legacypublishgeometry.h.
Referenced by getSettings(), PluginLegacyPublishGeometry(), and ~PluginLegacyPublishGeometry().
double PluginLegacyPublishGeometry::last_t protected
Definition at line 53 of file plugin_legacypublishgeometry.h.
Referenced by PluginLegacyPublishGeometry(), and process().
QMutex PluginLegacyPublishGeometry::mutex protected
Definition at line 51 of file plugin_legacypublishgeometry.h.
vector<CameraParameters *> PluginLegacyPublishGeometry::params protected
Definition at line 45 of file plugin_legacypublishgeometry.h.
Referenced by addCameraParameters(), and sendGeometry().
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/plugin_legacypublishgeometry.h
ssl-vision/src/app/plugins/plugin_legacypublishgeometry.cpp