Documentation: VarTypes::VarTreeModel Class Reference
VarTypes::VarTreeModel Class Reference
The 'item-model' inheriting QStandardItemModel for displaying VarTypes in the QT4 Item-Model.
#include <VarTreeModel.h>
Public Member Functions
void resetViewOptions ()
const VarTreeViewOptions * getViewOptions () const
VarTreeModel ()
virtual ~VarTreeModel ()
void updateHeader ()
void setRootItems (vector< VarType * > items)
void setRootItem (VarType *item)
virtual const QStandardItem * itemPrototype () const
QList< VarItem * > findItems (const QString &text, bool case_sensitive=false) const
QList< VarItem * > findItems (const VarType *item) const
Protected Attributes
VarTreeViewOptions opts
Detailed Description
The 'item-model' inheriting QStandardItemModel for displaying VarTypes in the QT4 Item-Model.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
This file is part of the QT4 Item-Model for VarTypes. It is used when you want to edit/visualize VarTypes using QT4's model/view system.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 41 of file VarTreeModel.h.
Constructor & Destructor Documentation
VarTypes::VarTreeModel::VarTreeModel ()
Definition at line 24 of file VarTreeModel.cpp.
References resetViewOptions(), and updateHeader().
                              : QStandardItemModel()
   {
     resetViewOptions();
     updateHeader();
   }
VarTypes::VarTreeModel::~VarTreeModel () virtual
Definition at line 30 of file VarTreeModel.cpp.
   {}
Member Function Documentation
QList< VarItem * > VarTypes::VarTreeModel::findItems (const QString & text, bool case_sensitive = false) const
Definition at line 64 of file VarTreeModel.cpp.
Referenced by VarTypes::VarTreeView::expandAndFocus(), and VarTypes::VarTreeView::search().
{
     QList<VarItem *> result;
     QList<QStandardItem *> tmp;
     tmp = QStandardItemModel::findItems(text,Qt::MatchRecursive|(case_sensitive ? (Qt::MatchContains|Qt::MatchCaseSensitive) : Qt::MatchContains),0);
     QList<QStandardItem *>::const_iterator iter = tmp.constBegin();
     QList<QStandardItem *>::const_iterator end = tmp.constEnd();
     while(iter != end) {
       result.append((VarItem *)(*iter));
       iter++;
     }
     return result;
   }
QList< VarItem * > VarTypes::VarTreeModel::findItems (const VarType * item) const
Definition at line 77 of file VarTreeModel.cpp.
References VarTypes::VarItem::searchTree().
{
     QList<VarItem *> result;
     if (item!=0) VarItem::searchTree(invisibleRootItem(), item, result);
     return result;
   }
const VarTreeViewOptions * VarTypes::VarTreeModel::getViewOptions () const
Definition at line 40 of file VarTreeModel.cpp.
References opts.
Referenced by setRootItems().
{
     return &opts;
   }
const QStandardItem * VarTypes::VarTreeModel::itemPrototype () const virtual
Definition at line 44 of file VarTreeModel.cpp.
{
     return 0;
   }
void VarTypes::VarTreeModel::resetViewOptions ()
Definition at line 33 of file VarTreeModel.cpp.
References VarTypes::GUI_COLUMN_FLAG_EDITABLE, VarTypes::GUI_COLUMN_FLAG_ICON, VarTypes::GUI_COLUMN_FLAG_RANGEBARS, VarTypes::GUI_COLUMN_FLAG_TEXT_LABEL, VarTypes::GUI_COLUMN_FLAG_TEXT_VALUE, VarTypes::GUI_COLUMN_FLAG_TREE_NODE, opts, VarTypes::VarTreeViewOptions::setColumns(), and v.
Referenced by VarTreeModel().
{
     vector<GuiColumnFlag> v;
     v.push_back(GUI_COLUMN_FLAG_TREE_NODE|GUI_COLUMN_FLAG_ICON|GUI_COLUMN_FLAG_TEXT_LABEL);
     v.push_back(GUI_COLUMN_FLAG_TEXT_VALUE|GUI_COLUMN_FLAG_EDITABLE|GUI_COLUMN_FLAG_RANGEBARS);
     opts.setColumns(v);
   }
void VarTypes::VarTreeModel::setRootItem (VarType * item)
Definition at line 87 of file VarTreeModel.cpp.
References setRootItems(), and v.
{
     vector<VarType *> v;
     v.push_back(item);
     setRootItems(v);
   }
void VarTypes::VarTreeModel::setRootItems (vector< VarType * > items)
Definition at line 83 of file VarTreeModel.cpp.
References getViewOptions(), and VarTypes::VarItem::updateTree().
Referenced by ConfigWidget::ConfigWidget(), MainWindow::MainWindow(), and setRootItem().
{
     VarItem::updateTree(invisibleRootItem(),items,getViewOptions(),true);
   }
void VarTypes::VarTreeModel::updateHeader ()
Definition at line 48 of file VarTreeModel.cpp.
References VarTypes::VarTreeViewOptions::getColumns(), VarTypes::GUI_COLUMN_FLAG_TEXT_LABEL, VarTypes::GUI_COLUMN_FLAG_TEXT_VALUE, velocity.pid_::i, opts, and v.
Referenced by VarTreeModel().
{
     vector<GuiColumnFlag> v=opts.getColumns();
     for (unsigned int i = 0;i<v.size();i++) {
       QStandardItem * head=new QStandardItem();
       if ((v[i] & (GUI_COLUMN_FLAG_TEXT_LABEL)) != 0) {
         head->setText("Variable");
       } else if ((v[i] & (GUI_COLUMN_FLAG_TEXT_VALUE)) != 0) {
         head->setText("Value");
       } else {
         head->setText("");
       }
       head->setTextAlignment(Qt::AlignLeft);
       setHorizontalHeaderItem(i,head);
     }
   }
Field Documentation
VarTreeViewOptions VarTypes::VarTreeModel::opts protected
Definition at line 46 of file VarTreeModel.h.
Referenced by getViewOptions(), resetViewOptions(), and updateHeader().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/gui/VarTreeModel.h
ssl-vision/src/shared/vartypes/gui/VarTreeModel.cpp