Documentation: MultiVisionStack Class Reference
MultiVisionStack Class Reference
Base-class of a multi-threaded / multi-camera vision stack.
#include <multivisionstack.h>
Public Member Functions
MultiVisionStack (string _name, RenderOptions *_opts)
virtual ~MultiVisionStack ()
VarList * getSettings ()
virtual string getName ()
virtual string getSettingsFileName ()
void start ()
void stop ()
Data Fields
string name
RenderOptions * opts
VarList * settings
vector< CaptureThread * > threads
Protected Member Functions
void createThreads (int number)
Detailed Description
Base-class of a multi-threaded / multi-camera vision stack.
Author
Stefan Zickler, (C) 2008
Definition at line 41 of file multivisionstack.h.
Constructor & Destructor Documentation
MultiVisionStack::MultiVisionStack (string _name, RenderOptions * _opts)
Definition at line 23 of file multivisionstack.cpp.
References name, opts, and settings.
{
   name=_name;
   opts=_opts;
   settings=new VarList("Global");
 }
MultiVisionStack::~MultiVisionStack () virtual
Definition at line 29 of file multivisionstack.cpp.
References velocity.pid_::i, settings, stop(), and threads.
{
   stop();
   for (size_t i = 0; i < threads.size(); i++) {
     delete threads.at(i);
   }
   delete settings;
 }
Member Function Documentation
void MultiVisionStack::createThreads (int number) protected
Definition at line 49 of file multivisionstack.cpp.
References velocity.pid_::i, and threads.
Referenced by MultiStackRoboCupSSL::MultiStackRoboCupSSL().
{
   for (int i=0;i<number;i++) {
     threads.push_back(new CaptureThread(i));
   }
 }
string MultiVisionStack::getName () virtual
Definition at line 37 of file multivisionstack.cpp.
References name.
Referenced by MainWindow::MainWindow().
{
   return name;
 }
VarList * MultiVisionStack::getSettings ()
Definition at line 41 of file multivisionstack.cpp.
References settings.
Referenced by MainWindow::MainWindow().
{
   return settings;
 }
string MultiVisionStack::getSettingsFileName () virtual
Reimplemented in MultiStackRoboCupSSL.
Definition at line 45 of file multivisionstack.cpp.
References name.
Referenced by MainWindow::MainWindow().
{
   return name;
 }
void MultiVisionStack::start ()
Definition at line 56 of file multivisionstack.cpp.
References velocity.pid_::i, t, and threads.
Referenced by MainWindow::MainWindow().
{
   unsigned int n=threads.size();
   CaptureThread * t;
   for (unsigned int i=0;i<n;i++) {
     t=threads[i];
     t->start(QThread::HighestPriority);
   }
 }
void MultiVisionStack::stop ()
Definition at line 65 of file multivisionstack.cpp.
References velocity.pid_::i, CaptureThread::kill(), t, and threads.
Referenced by MainWindow::closeEvent(), MultiStackRoboCupSSL::~MultiStackRoboCupSSL(), and ~MultiVisionStack().
{
   unsigned int n=threads.size();
   CaptureThread * t;
   for (unsigned int i=0;i<n;i++) {
     t=threads[i];
     t->kill();
   }
 }
Field Documentation
string MultiVisionStack::name
Definition at line 43 of file multivisionstack.h.
Referenced by getName(), getSettingsFileName(), and MultiVisionStack().
RenderOptions* MultiVisionStack::opts
Definition at line 44 of file multivisionstack.h.
Referenced by MultiVisionStack().
VarList* MultiVisionStack::settings
Definition at line 45 of file multivisionstack.h.
Referenced by getSettings(), MultiStackRoboCupSSL::MultiStackRoboCupSSL(), MultiVisionStack(), and ~MultiVisionStack().
vector<CaptureThread *> MultiVisionStack::threads
Definition at line 51 of file multivisionstack.h.
Referenced by createThreads(), MainWindow::MainWindow(), MultiStackRoboCupSSL::MultiStackRoboCupSSL(), start(), stop(), and ~MultiVisionStack().
The documentation for this class was generated from the following files:
ssl-vision/src/app/stacks/multivisionstack.h
ssl-vision/src/app/stacks/multivisionstack.cpp