Documentation: BBox::BBox2D< vector, num > Struct Template Reference
BBox::BBox2D< vector, num > Struct Template Reference
#include <bbox.h>
Public Member Functions
bool check (const BBox2D &b) const
bool inside (const vector &p) const
void zero ()
void set (const vector &_cen, const vector &_rad)
void set (const vector &_cen, num _rad)
void set (const vector &p0, const vector &p1, num _rad)
void expand (num amt)
void add (const BBox2D &b)
void add (vector cen, num rad)
void merge (const BBox2D &a, const BBox2D &b)
float area ()
Data Fields
vector cen
vector rad
Detailed Description
template<class vector, class num>
struct BBox::BBox2D< vector, num >
Definition at line 121 of file bbox.h.
Member Function Documentation
template<class vector , class num > void BBox::BBox2D< vector, num >::add (const BBox2D< vector, num > & b)
Definition at line 176 of file bbox.h.
References BBOX_TEM, BBox::BBox3D< vector, num >::cen, BBox::BBox2D< vector, num >::cen, GVector::max(), GVector::min(), BBox::BBox3D< vector, num >::rad, and BBox::BBox2D< vector, num >::rad.
 {
   vector p0 = min(cen-rad, b.cen-b.rad);
   vector p1 = max(cen+rad, b.cen+b.rad);
   cen = (p1 + p0)*0.5;
   rad = (p1 - p0)*0.5;
 }
template<class vector , class num > void BBox::BBox2D< vector, num >::add (vector cen, num rad)
Definition at line 186 of file bbox.h.
References BBOX_TEM, BBox::BBox3D< vector, num >::cen, GVector::max(), GVector::min(), and BBox::BBox3D< vector, num >::rad.
 {
   vector rv(radius,radius);
   vector p0 = min(cen-rad, center-rv);
   vector p1 = max(cen+rad, center+rv);
   cen = (p1 + p0)*0.5;
   rad = (p1 - p0)*0.5;
 }
template<class vector , class num > float BBox::BBox2D< vector, num >::area () inline
Definition at line 142 of file bbox.h.
References BBOX_TEM.
     {return(4*rad.x*rad.y);}
template<class vector , class num > bool BBox::BBox2D< vector, num >::check (const BBox2D< vector, num > & b) const
Definition at line 155 of file bbox.h.
References BBOX_TEM, BBox::BBox3D< vector, num >::cen, BBox::BBox2D< vector, num >::cen, BBox::BBox3D< vector, num >::rad, and BBox::BBox2D< vector, num >::rad.
 {
   return(fabs(b.cen.x - cen.x) > (b.rad.x + rad.x) ||
          fabs(b.cen.y - cen.y) > (b.rad.y + rad.y));
 }
template<class vector , class num > void BBox::BBox2D< vector, num >::expand (num amt)
Definition at line 169 of file bbox.h.
References BBOX_TEM, and BBox::BBox3D< vector, num >::rad.
 {
   rad.x += amt;
   rad.y += amt;
 }
template<class vector , class num > bool BBox::BBox2D< vector, num >::inside (const vector & p) const
Definition at line 162 of file bbox.h.
References BBOX_TEM, BBox::BBox3D< vector, num >::cen, and BBox::BBox3D< vector, num >::rad.
 {
   return(fabs(p.x - cen.x) < rad.x &&
          fabs(p.y - cen.y) < rad.y);
 }
template<class vector , class num > void BBox::BBox2D< vector, num >::merge (const BBox2D< vector, num > & a, const BBox2D< vector, num > & b)
Definition at line 197 of file bbox.h.
References BBox::BBox3D< vector, num >::cen, BBox::BBox2D< vector, num >::cen, GVector::max(), GVector::min(), BBox::BBox3D< vector, num >::rad, and BBox::BBox2D< vector, num >::rad.
 {
   vector p0 = min(a.cen-a.rad, b.cen-b.rad);
   vector p1 = max(a.cen+a.rad, b.cen+b.rad);
   cen = (p1 + p0)*0.5;
   rad = (p1 - p0)*0.5;
 }
template<class vector , class num > void BBox::BBox2D< vector, num >::set (const vector & _cen, const vector & _rad) inline
Definition at line 131 of file bbox.h.
     {cen=_cen; rad=_rad;}
template<class vector , class num > void BBox::BBox2D< vector, num >::set (const vector & _cen, num _rad) inline
Definition at line 133 of file bbox.h.
References BBox::BBox3D< vector, num >::add(), BBox::BBox3D< vector, num >::expand(), and BBox::BBox3D< vector, num >::merge().
     {cen=_cen; rad.set(_rad,_rad);}
template<class vector , class num > void BBox::BBox2D< vector, num >::set (const vector & p0, const vector & p1, num _rad)
Definition at line 147 of file bbox.h.
References BBOX_TEM, BBox::BBox3D< vector, num >::cen, and BBox::BBox3D< vector, num >::rad.
 {
   cen = (p0 + p1)*0.5;
   rad.set(fabs(p1.x - p0.x)*0.5 + _rad,
           fabs(p1.y - p0.y)*0.5 + _rad);
 }
template<class vector , class num > void BBox::BBox2D< vector, num >::zero () inline
Definition at line 129 of file bbox.h.
     {cen.zero(); rad.zero();}
Field Documentation
template<class vector , class num > vector BBox::BBox2D< vector, num >::cen
Definition at line 123 of file bbox.h.
Referenced by BBox::BBox2D< vector, num >::add(), BBox::BBox2D< vector, num >::check(), and BBox::BBox2D< vector, num >::merge().
template<class vector , class num > vector BBox::BBox2D< vector, num >::rad
Definition at line 124 of file bbox.h.
Referenced by BBox::BBox2D< vector, num >::add(), BBox::BBox2D< vector, num >::check(), and BBox::BBox2D< vector, num >::merge().
The documentation for this struct was generated from the following file:
ssl-vision/src/shared/util/bbox.h