Documentation: utils.functions Namespace Reference
utils.functions Namespace Reference
Data Structures
class Circle
class Line
Functions
def ball_in_our_dbox (state)
def point_in_a_triangle (point, triangle)
def line_ellipse_intersection (line, ellipse)
def normalize_angle (angle)
def magnitute (vector)
def line_circle_intersection (self, circle)
def direction (vector)
def getPointBehindTheBall (point, theta)
def deg_2_radian (theta)
def radian_2_deg (theta)
def dist (point1, point2)
def angle_diff (point1, point2)
def vicinity_points (point1, point2, thresh=10)
def vicinity_theta (theta1, theta2, thresh=0.1)
def angle_at_vextex (P1, P2, P3)
def area_of_triangle (p1, p2, p3)
def point_in_triangle (t, P)
def ball_in_front_of_bot (kub)
def kub_has_ball (state, kub_id)
def goalie_expected_y (state, kub_id)
Function Documentation
def utils.functions.angle_at_vextex (P1, P2, P3)
Definition at line 254 of file math_functions.py.
 def angle_at_vextex(P1, P2, P3):
     a = P2.dist(P3)
     b = P1.dist(P3)
     c = P1.dist(P2)
     value = (b**2 + c**2 - a**2) / (2 * b * c)
     theta = math.acos(value)
     return math.atan2(math.tan(theta), 1.0)
def utils.functions.angle_diff (point1, point2)
Definition at line 237 of file math_functions.py.
References utils.functions.getPointBehindTheBall().
 def angle_diff(point1, point2):
     return math.atan2(point2.y - point1.y, point2.x - point1.x)
def utils.functions.area_of_triangle (p1, p2, p3)
Definition at line 263 of file math_functions.py.
Referenced by utils.functions.point_in_triangle().
 def area_of_triangle(p1, p2, p3):
     return math.abs(p1.x * (p2.y - p3.y) + p2.x * (p3.y - p1.y) + p3.x * (p1.y - p2.y)) / 2.0
def utils.functions.ball_in_front_of_bot (kub)
Definition at line 278 of file math_functions.py.
References utils.functions.vicinity_points(), and utils.functions.vicinity_theta().
Referenced by role.GoToBall.GoToBall.ball_in_vicinity(), and role.GoToBall.GoToBall.target_present().
 def ball_in_front_of_bot(kub):
     theta1 = kub.get_pos().theta
     theta2 = math.atan2(kub.state.ballPos.y - kub.get_pos().y,
                         kub.state.ballPos.x - kub.get_pos().x)
     return vicinity_theta(theta1, theta2, thresh=0.25) and vicinity_points(kub.get_pos(), kub.state.ballPos,
                         thresh=BOT_RADIUS * 4)
def utils.functions.ball_in_our_dbox (state)
Definition at line 7 of file math_functions.py.
 def ball_in_our_dbox(state):
     ballPos = Vector2D(int(state.ballPos.x), int(state.ballPos.y))
     if ballPos.x > -HALF_FIELD_MAXX+DBOX_WIDTH :
         return False
     dbox_point1 = Vector2D(-HALF_FIELD_MAXX,DBOX_SMALLER_LENGTH/2)
     dbox_point2 = Vector2D(-HALF_FIELD_MAXX,-DBOX_SMALLER_LENGTH/2)
     if ballPos.dist(dbox_point1) < DBOX_RADIUS or ballPos.dist(dbox_point2) < DBOX_RADIUS :
         return True
     elif -DBOX_SMALLER_LENGTH/2 <= ballPos.y and ballPos.y <= DBOX_SMALLER_LENGTH/2 :
         return True
     else :
         return False
def utils.functions.deg_2_radian (theta)
Definition at line 225 of file math_functions.py.
 def deg_2_radian(theta):
     return theta * math.pi / 180.0
def utils.functions.direction (vector)
Definition at line 215 of file math_functions.py.
Referenced by kubs.kubs.kubs.get_vel().
 def direction(vector):
     return math.atan2(vector.y, vector.x)
def utils.functions.dist (point1, point2)
Definition at line 233 of file math_functions.py.
Referenced by utils.functions.vicinity_points().
 def dist(point1, point2):
     return math.sqrt((point1.x - point2.x)**2 + (point1.y - point2.y)**2)
def utils.functions.getPointBehindTheBall (point, theta)
Definition at line 219 of file math_functions.py.
Referenced by utils.functions.angle_diff(), role.GoToBall.GoToBall.execute_course_approach(), and role.GoToBall.GoToBall.execute_setup().
 def getPointBehindTheBall(point, theta):
     x = point.x - (3.5 * BOT_RADIUS) * (math.cos(theta))
     y = point.y - (3.5 * BOT_RADIUS) * (math.sin(theta))
     return Vector2D(int(x), int(y))
def utils.functions.goalie_expected_y (state, kub_id)
Definition at line 293 of file math_functions.py.
Referenced by tactics.Goalie.Goalie.execute_protect().
 def goalie_expected_y(state, kub_id):
     try:
         time = math.fabs((state.homePos[kub_id].x - state.ballPos.x) // state.ballVel.x)
     except: time = 0.0
     expected_y = time * state.ballVel.y + state.ballPos.y
     return expected_y
def utils.functions.kub_has_ball (state, kub_id)
Definition at line 286 of file math_functions.py.
References utils.functions.vicinity_points(), and utils.functions.vicinity_theta().
Referenced by kubs.kubs.kubs.has_ball().
 def kub_has_ball(state, kub_id):
     theta1 = state.homePos[kub_id].theta
     theta2 = math.atan2(state.ballPos.y - state.homePos[kub_id].y,
                         state.ballPos.x - state.homePos[kub_id].x)
     return vicinity_theta(theta1, theta2, thresh=0.25) and vicinity_points(state.homePos[kub_id],
                         state.ballPos, thresh=BOT_RADIUS * 1.5)
def utils.functions.line_circle_intersection (self, circle)
Definition at line 211 of file math_functions.py.
 def line_circle_intersection(self,circle):
   pass
def utils.functions.line_ellipse_intersection (line, ellipse)
Definition at line 194 of file math_functions.py.
 def line_ellipse_intersection(line, ellipse):
     pass
def utils.functions.magnitute (vector)
Definition at line 208 of file math_functions.py.
Referenced by kubs.kubs.kubs.get_vel().
 def magnitute(vector):
     return math.sqrt(vector.x * vector.x + vector.y * vector.y)
def utils.functions.normalize_angle (angle)
Definition at line 198 of file math_functions.py.
Referenced by role._GoToPoint_.execute(), test_role.function(), velocity.run_w.Get_Omega(), and GUI.ompl_gui.MainWindow.goToBallFsm().
 def normalize_angle(angle):
     if angle > math.pi:
         return angle - 2 * math.pi
     elif angle <= -math.pi:
         return angle + 2 * math.pi
     else:
         return angle
def utils.functions.point_in_a_triangle (point, triangle)
Definition at line 190 of file math_functions.py.
 def point_in_a_triangle(point, triangle):
     pass
def utils.functions.point_in_triangle (t, P)
Definition at line 267 of file math_functions.py.
References utils.functions.area_of_triangle().
 def point_in_triangle(t, P):
     P1, P2, P3 = t[0], t[1], t[2]
     a = area_of_triangle(P1, P2, P3)
     a1 = area_of_triangle(P, P2, P3)
     a2 = area_of_triangle(P1, P, P3)
     a3 = area_of_triangle(P1, P2, P)
     return a == a1 + a2 + a3
def utils.functions.radian_2_deg (theta)
Definition at line 229 of file math_functions.py.
 def radian_2_deg(theta):
     return theta * 180.0 / math.pi
def utils.functions.vicinity_points (point1, point2, thresh = 10)
Definition at line 246 of file math_functions.py.
References utils.functions.dist().
Referenced by role.GoToBall.GoToBall.at_ball_pos(), role.GoToBall.GoToBall.at_target_point(), utils.state_functions.ball_in_front_of_bot(), utils.functions.ball_in_front_of_bot(), role.GoToBall.GoToBall.execute_course_approach(), role.GoToPoint.GoToPoint.execute_drive(), role.GoToBall.GoToBall.execute_fine_approach(), utils.state_functions.kub_has_ball(), and utils.functions.kub_has_ball().
 def vicinity_points(point1, point2, thresh=10):
     return dist(point1, point2) < thresh
def utils.functions.vicinity_theta (theta1, theta2, thresh = 0.1)
Definition at line 250 of file math_functions.py.
References GVector.abs().
Referenced by utils.state_functions.ball_in_front_of_bot(), utils.functions.ball_in_front_of_bot(), utils.state_functions.kub_has_ball(), and utils.functions.kub_has_ball().
 def vicinity_theta(theta1, theta2, thresh=0.1):
     return abs(theta1 - theta2) < thresh