Documentation: CStatusWidget Class Reference
CStatusWidget Class Reference
#include <statuswidget.h>
Public Slots
void write (QString str, QColor color=QColor("black"))
void update ()
Public Member Functions
CStatusWidget (CStatusPrinter *_statusPrinter)
Data Fields
QTextEdit * statusText
QLabel * titleLbl
QTextDocument content
Private Attributes
CStatusPrinter * statusPrinter
QTime logTime
Detailed Description
Definition at line 57 of file statuswidget.h.
Constructor & Destructor Documentation
CStatusWidget::CStatusWidget (CStatusPrinter * _statusPrinter)
Definition at line 21 of file statuswidget.cpp.
References logTime, statusPrinter, statusText, and titleLbl.
 {
     statusPrinter = _statusPrinter;
     logTime.start();
     this->setAllowedAreas(Qt::BottomDockWidgetArea);
     this->setFeatures(QDockWidget::NoDockWidgetFeatures);
     statusText = new QTextEdit(this);
     statusText->setReadOnly(true);
     titleLbl = new QLabel(tr("Messages"));
     this->setWidget(statusText);
     this->setTitleBarWidget(titleLbl);
 }
Member Function Documentation
void CStatusWidget::update () slot
Definition at line 53 of file statuswidget.cpp.
References CStatusText::color, statusPrinter, CStatusText::text, CStatusPrinter::textBuffer, and write().
Referenced by MainWindow::update().
 {
     CStatusText text;
     while(!statusPrinter->textBuffer.isEmpty())
     {
         text = statusPrinter->textBuffer.dequeue();
         write(text.text, text.color);
     }
 }
void CStatusWidget::write (QString str, QColor color = QColor("black")) slot
Definition at line 39 of file statuswidget.cpp.
References statusText.
Referenced by update().
 {
     if( statusText->textCursor().blockNumber() > 2000 )
         statusText->clear();
     statusText->setTextColor(color);
     //statusText->append(QString::number(statusText->textCursor().blockNumber()) + " : " + str);
     //statusText->append(QString::number(logTime.elapsed()) + " : " + str);
     statusText->append(str);
     statusText->setTextColor(QColor("black"));
 }
Field Documentation
QTextDocument CStatusWidget::content
Definition at line 64 of file statuswidget.h.
QTime CStatusWidget::logTime private
Definition at line 72 of file statuswidget.h.
Referenced by CStatusWidget().
CStatusPrinter* CStatusWidget::statusPrinter private
Definition at line 71 of file statuswidget.h.
Referenced by CStatusWidget(), and update().
QTextEdit* CStatusWidget::statusText
Definition at line 62 of file statuswidget.h.
Referenced by CStatusWidget(), and write().
QLabel* CStatusWidget::titleLbl
Definition at line 63 of file statuswidget.h.
Referenced by CStatusWidget().
The documentation for this class was generated from the following files:
grSim/include/statuswidget.h
grSim/src/statuswidget.cpp