Documentation: Refbox_Log Class Reference
Refbox_Log Class Reference
#include <messages_robocup_ssl_refbox_log.pb.h>
Public Member Functions
Refbox_Log ()
virtual ~Refbox_Log ()
Refbox_Log (const Refbox_Log &from)
Refbox_Log & operator= (const Refbox_Log &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Refbox_Log *other)
Refbox_Log * New () const PROTOBUF_FINAL
Refbox_Log * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const Refbox_Log &from)
void MergeFrom (const Refbox_Log &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
int log_size () const
void clear_log ()
const ::Log_Frame & log (int index) const
::Log_Frame * mutable_log (int index)
::Log_Frame * add_log ()
::google::protobuf::RepeatedPtrField< ::Log_Frame > * mutable_log ()
const ::google::protobuf::RepeatedPtrField< ::Log_Frame > & log () const
Refbox_Log ()
virtual ~Refbox_Log ()
Refbox_Log (const Refbox_Log &from)
Refbox_Log & operator= (const Refbox_Log &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Refbox_Log *other)
Refbox_Log * New () const PROTOBUF_FINAL
Refbox_Log * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const Refbox_Log &from)
void MergeFrom (const Refbox_Log &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
int log_size () const
void clear_log ()
const ::Log_Frame & log (int index) const
::Log_Frame * mutable_log (int index)
::Log_Frame * add_log ()
::google::protobuf::RepeatedPtrField< ::Log_Frame > * mutable_log ()
const ::google::protobuf::RepeatedPtrField< ::Log_Frame > & log () const
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Refbox_Log & default_instance ()
static const Refbox_Log * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const Refbox_Log & default_instance ()
static void InitAsDefaultInstance ()
static const Refbox_Log * internal_default_instance ()
Static Public Attributes
static const int kLogFieldNumber = 1
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (Refbox_Log *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5frefbox_5flog_2eproto ()
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (Refbox_Log *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
friend void::protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::InitDefaultsRefbox_LogImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::RepeatedPtrField< ::Log_Frame > log_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::TableStruct
void protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl ()
void protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl ()
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5frefbox_5flog_2eproto ()
void swap (Refbox_Log &a, Refbox_Log &b)
Detailed Description
Definition at line 175 of file messages_robocup_ssl_refbox_log.pb.h.
Constructor & Destructor Documentation
Refbox_Log::Refbox_Log ()
virtual Refbox_Log::~Refbox_Log () virtual
Refbox_Log::Refbox_Log (const Refbox_Log & from)
Refbox_Log::Refbox_Log ()
virtual Refbox_Log::~Refbox_Log () virtual
Refbox_Log::Refbox_Log (const Refbox_Log & from)
Member Function Documentation
Log_Frame * Refbox_Log::add_log () inline
Definition at line 408 of file messages_robocup_ssl_refbox_log.pb.h.
{
   // @@protoc_insertion_point(field_add:Refbox_Log.log)
   return log_.Add();
 }
::Log_Frame* Refbox_Log::add_log ()
size_t Refbox_Log::ByteSizeLong () const
size_t Refbox_Log::ByteSizeLong () const
void Refbox_Log::Clear ()
void Refbox_Log::Clear ()
void Refbox_Log::clear_log () inline
Definition at line 397 of file messages_robocup_ssl_refbox_log.pb.h.
Referenced by ViewUpdateThread::end_play_record().
{
   log_.Clear();
 }
void Refbox_Log::clear_log ()
void Refbox_Log::CopyFrom (const ::google::protobuf::Message & from)
void Refbox_Log::CopyFrom (const Refbox_Log & from)
void Refbox_Log::CopyFrom (const ::google::protobuf::Message & from)
void Refbox_Log::CopyFrom (const Refbox_Log & from)
static const Refbox_Log& Refbox_Log::default_instance () static
static const Refbox_Log& Refbox_Log::default_instance () static
static const ::google::protobuf::Descriptor* Refbox_Log::descriptor () static
static const ::google::protobuf::Descriptor* Refbox_Log::descriptor () static
inline ::google::protobuf::Arena* Refbox_Log::GetArenaNoVirtual () const inline private
Definition at line 235 of file messages_robocup_ssl_refbox_log.pb.h.
{
     return NULL;
   }
inline ::google::protobuf::Arena* Refbox_Log::GetArenaNoVirtual () const inline private
Definition at line 272 of file messages_robocup_ssl_refbox_log.pb.h.
{
     return NULL;
   }
int Refbox_Log::GetCachedSize () const inline
Definition at line 228 of file messages_robocup_ssl_refbox_log.pb.h.
References Log_Frame::_cached_size_, Log_Frame::InternalSwap(), Log_Frame::SetCachedSize(), Log_Frame::SharedCtor(), and Log_Frame::SharedDtor().
 { return _cached_size_; }
int Refbox_Log::GetCachedSize () const inline
Definition at line 265 of file messages_robocup_ssl_refbox_log.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata Refbox_Log::GetMetadata () const
::google::protobuf::Metadata Refbox_Log::GetMetadata () const
static void Refbox_Log::InitAsDefaultInstance () static
static const Refbox_Log* Refbox_Log::internal_default_instance () inline static
Definition at line 198 of file messages_robocup_ssl_refbox_log.pb.h.
References _Refbox_Log_default_instance_, and Log_Frame::Swap().
{
     return reinterpret_cast<const Refbox_Log*>(
                &_Refbox_Log_default_instance_);
   }
static const Refbox_Log* Refbox_Log::internal_default_instance () inline static
Definition at line 234 of file messages_robocup_ssl_refbox_log.pb.h.
References _Refbox_Log_default_instance_.
{
     return reinterpret_cast<const Refbox_Log*>(
                &_Refbox_Log_default_instance_);
   }
::google::protobuf::uint8* Refbox_Log::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
::google::protobuf::uint8* Refbox_Log::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void Refbox_Log::InternalSwap (Refbox_Log * other) private
void Refbox_Log::InternalSwap (Refbox_Log * other) private
bool Refbox_Log::IsInitialized () const
Referenced by ViewUpdateThread::start_play_record().
bool Refbox_Log::IsInitialized () const
const ::Log_Frame & Refbox_Log::log (int index) const inline
Definition at line 400 of file messages_robocup_ssl_refbox_log.pb.h.
Referenced by ViewUpdateThread::start_play_record().
{
   // @@protoc_insertion_point(field_get:Refbox_Log.log)
   return log_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::Log_Frame > & Refbox_Log::log () const inline
Definition at line 418 of file messages_robocup_ssl_refbox_log.pb.h.
                       {
   // @@protoc_insertion_point(field_list:Refbox_Log.log)
   return log_;
 }
const ::Log_Frame& Refbox_Log::log (int index) const
const ::google::protobuf::RepeatedPtrField< ::Log_Frame >& Refbox_Log::log () const
int Refbox_Log::log_size () const inline
Definition at line 394 of file messages_robocup_ssl_refbox_log.pb.h.
Referenced by ViewUpdateThread::start_play_record().
{
   return log_.size();
 }
int Refbox_Log::log_size () const
void* Refbox_Log::MaybeArenaPtr () const inline private
Definition at line 238 of file messages_robocup_ssl_refbox_log.pb.h.
References Log_Frame::GetMetadata().
{
     return NULL;
   }
void* Refbox_Log::MaybeArenaPtr () const inline private
Definition at line 275 of file messages_robocup_ssl_refbox_log.pb.h.
{
     return NULL;
   }
void Refbox_Log::MergeFrom (const ::google::protobuf::Message & from)
void Refbox_Log::MergeFrom (const Refbox_Log & from)
void Refbox_Log::MergeFrom (const ::google::protobuf::Message & from)
void Refbox_Log::MergeFrom (const Refbox_Log & from)
bool Refbox_Log::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
bool Refbox_Log::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Log_Frame * Refbox_Log::mutable_log (int index) inline
Definition at line 404 of file messages_robocup_ssl_refbox_log.pb.h.
Referenced by ViewUpdateThread::execute(), and ViewUpdateThread::start_play_record().
{
   // @@protoc_insertion_point(field_mutable:Refbox_Log.log)
   return log_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::Log_Frame > * Refbox_Log::mutable_log () inline
Definition at line 413 of file messages_robocup_ssl_refbox_log.pb.h.
{
   // @@protoc_insertion_point(field_mutable_list:Refbox_Log.log)
   return &log_;
 }
::Log_Frame* Refbox_Log::mutable_log (int index)
::google::protobuf::RepeatedPtrField< ::Log_Frame >* Refbox_Log::mutable_log ()
inline ::google::protobuf::UnknownFieldSet* Refbox_Log::mutable_unknown_fields () inline
Definition at line 191 of file messages_robocup_ssl_refbox_log.pb.h.
References Log_Frame::_internal_metadata_, Log_Frame::default_instance(), and Log_Frame::descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
inline ::google::protobuf::UnknownFieldSet* Refbox_Log::mutable_unknown_fields () inline
Definition at line 226 of file messages_robocup_ssl_refbox_log.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
Refbox_Log* Refbox_Log::New () const inline
Definition at line 207 of file messages_robocup_ssl_refbox_log.pb.h.
References Log_Frame::ByteSizeLong(), Log_Frame::Clear(), Log_Frame::CopyFrom(), Log_Frame::InternalSerializeWithCachedSizesToArray(), Log_Frame::IsInitialized(), Log_Frame::MergeFrom(), Log_Frame::MergePartialFromCodedStream(), Log_Frame::New(), New(), Log_Frame::SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
Refbox_Log* Refbox_Log::New (::google::protobuf::Arena * arena) const
Refbox_Log* Refbox_Log::New () const inline
Definition at line 248 of file messages_robocup_ssl_refbox_log.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
Refbox_Log* Refbox_Log::New (::google::protobuf::Arena * arena) const
Refbox_Log& Refbox_Log::operator= (const Refbox_Log & from) inline
Definition at line 182 of file messages_robocup_ssl_refbox_log.pb.h.
References Log_Frame::CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
Refbox_Log& Refbox_Log::operator= (const Refbox_Log & from) inline
Definition at line 204 of file messages_robocup_ssl_refbox_log.pb.h.
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* Refbox_Log::protobuf_Offsets_messages_5frobocup_5fssl_5frefbox_5flog_2eproto () private
void Refbox_Log::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void Refbox_Log::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* Refbox_Log::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 224 of file messages_robocup_ssl_refbox_log.pb.h.
References Log_Frame::InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void Refbox_Log::SetCachedSize (int size) const private
void Refbox_Log::SetCachedSize (int size) const private
void Refbox_Log::SharedCtor () private
void Refbox_Log::SharedCtor () private
void Refbox_Log::SharedDtor () private
void Refbox_Log::SharedDtor () private
void Refbox_Log::Swap (Refbox_Log * other)
void Refbox_Log::Swap (Refbox_Log * other)
const ::google::protobuf::UnknownFieldSet& Refbox_Log::unknown_fields () const inline
Definition at line 187 of file messages_robocup_ssl_refbox_log.pb.h.
References Log_Frame::_internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
const ::google::protobuf::UnknownFieldSet& Refbox_Log::unknown_fields () const inline
Definition at line 223 of file messages_robocup_ssl_refbox_log.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
Refbox_Log::void::protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::InitDefaultsRefbox_LogImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::TableStruct friend
Definition at line 305 of file messages_robocup_ssl_refbox_log.pb.h.
void protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl () friend
void protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl () friend
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5frefbox_5flog_2eproto () friend
void swap (Refbox_Log & a, Refbox_Log & b) friend
Definition at line 242 of file messages_robocup_ssl_refbox_log.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int Refbox_Log::_cached_size_ mutable private
Definition at line 266 of file messages_robocup_ssl_refbox_log.pb.h.
google::protobuf::internal::HasBits< 1 > Refbox_Log::_has_bits_ private
Definition at line 265 of file messages_robocup_ssl_refbox_log.pb.h.
google::protobuf::internal::InternalMetadataWithArena Refbox_Log::_internal_metadata_ private
Definition at line 264 of file messages_robocup_ssl_refbox_log.pb.h.
PROTOBUF_CONSTEXPR int const Refbox_Log::kIndexInFileMessages static
Initial value:
=
    1
Definition at line 238 of file messages_robocup_ssl_refbox_log.pb.h.
static const int Refbox_Log::kLogFieldNumber = 1 static
Definition at line 252 of file messages_robocup_ssl_refbox_log.pb.h.
google::protobuf::RepeatedPtrField<::Log_Frame > Refbox_Log::log_ private
Definition at line 267 of file messages_robocup_ssl_refbox_log.pb.h.
The documentation for this class was generated from the following file:
grsim_comm/include/proto/messages_robocup_ssl_refbox_log.pb.h