Documentation: CMVisionThreshold Class Reference
CMVisionThreshold Class Reference
#include <cmvision_threshold.h>
Public Member Functions
CMVisionThreshold ()
~CMVisionThreshold ()
Static Public Member Functions
static bool thresholdImageYUV422_UYVY (Image< raw8 > *target, const RawImage *source, YUVLUT *lut)
static bool thresholdImageYUV444 (Image< raw8 > *target, const ImageInterface *source, YUVLUT *lut)
static bool thresholdImageRGB (Image< raw8 > *target, const ImageInterface *source, RGBLUT *lut)
static void colorizeImageFromThresholding (rgbImage &target, const Image< raw8 > &source, LUT3D *lut)
Detailed Description
Author
James Bruce (Original CMVision implementation and algorithms), Some code restructuring, and data structure changes: Stefan Zickler 2008
Definition at line 35 of file cmvision_threshold.h.
Constructor & Destructor Documentation
CMVisionThreshold::CMVisionThreshold ()
Definition at line 24 of file cmvision_threshold.cpp.
 {
 }
CMVisionThreshold::~CMVisionThreshold ()
Definition at line 29 of file cmvision_threshold.cpp.
 {
 }
Member Function Documentation
void CMVisionThreshold::colorizeImageFromThresholding (rgbImage & target, const Image< raw8 > & source, LUT3D * lut) static
Definition at line 34 of file cmvision_threshold.cpp.
References LUTChannel::draw_color, LUT3D::getChannel(), Image< PIXEL >::getHeight(), Image< PIXEL >::getNumPixels(), Image< PIXEL >::getPixelData(), Image< PIXEL >::getWidth(), and velocity.pid_::i.
{
   target.allocate(source.getWidth(),source.getHeight());
   int n = source.getNumPixels();
   rgb * vis_ptr = target.getPixelData();
   raw8 * seg_ptr = source.getPixelData();
   for (int i=0;i<n;i++) {
     vis_ptr[i]=lut->getChannel(seg_ptr[i].getIntensity()).draw_color;
   }
 }
bool CMVisionThreshold::thresholdImageRGB (Image< raw8 > * target, const ImageInterface * source, RGBLUT * lut) static
Definition at line 117 of file cmvision_threshold.cpp.
References ColorRGB< num, fmt >::b, COLOR_RGB8, Colors::colorFormatToString(), ColorRGB< num, fmt >::g, ImageInterface::getColorFormat(), ImageInterface::getData(), ImageInterface::getHeight(), Image< PIXEL >::getHeight(), ImageInterface::getNumPixels(), Image< PIXEL >::getNumPixels(), Image< PIXEL >::getPixelData(), LUT3D::getTable(), ImageInterface::getWidth(), Image< PIXEL >::getWidth(), velocity.pid_::i, ColorRGB< num, fmt >::r, LUT3D::X_SHIFT, LUT3D::Y_SHIFT, LUT3D::Z_AND_Y_BITS, LUT3D::Z_BITS, and LUT3D::Z_SHIFT.
Referenced by PluginColorThreshold::process().
{
   if (source->getColorFormat()!=COLOR_RGB8) {
     fprintf(stderr,"CMVision RGB thresholding assumes RGB8 as input, but found %s\n", Colors::colorFormatToString(source->getColorFormat()).c_str());
     return false;
   }
   register lut_mask_t * LUT = lut->getTable();
   int          source_size    = source->getNumPixels();
   rgb *        source_pointer = (rgb*)(source->getData());
   raw8 *      target_pointer = target->getPixelData();
   if (target->getNumPixels() != source->getNumPixels()) {
     fprintf(stderr, "CMVision RGB thresholding: source (num=%d  w=%d  h=%d) and target (num=%d w=%d h=%d) pixel counts do not match!\n", source->getNumPixels(),source->getWidth(),source->getHeight(), target->getNumPixels(),target->getWidth(),target->getHeight());
     return false;
   }
   int X_SHIFT=lut->X_SHIFT;
   int Y_SHIFT=lut->Y_SHIFT;
   int Z_SHIFT=lut->Z_SHIFT;
   int Z_AND_Y_BITS=lut->Z_AND_Y_BITS;
   int Z_BITS = lut->Z_BITS;
   for (int i=0;i<source_size;i++) {
     rgb p=source_pointer[i];
     target_pointer[i] =  LUT[(((p.r >> X_SHIFT) << Z_AND_Y_BITS) | ((p.g >> Y_SHIFT) << Z_BITS) | (p.b >> Z_SHIFT))];
   }
   return true;
 }
bool CMVisionThreshold::thresholdImageYUV422_UYVY (Image< raw8 > * target, const RawImage * source, YUVLUT * lut) static
Definition at line 45 of file cmvision_threshold.cpp.
References COLOR_YUV422_UYVY, Colors::colorFormatToString(), RawImage::getColorFormat(), RawImage::getData(), RawImage::getHeight(), Image< PIXEL >::getHeight(), RawImage::getNumPixels(), Image< PIXEL >::getNumPixels(), Image< PIXEL >::getPixelData(), LUT3D::getTable(), RawImage::getWidth(), Image< PIXEL >::getWidth(), velocity.pid_::i, LUT3D::lock(), ColorUYVY< num, fmt >::u, LUT3D::unlock(), ColorUYVY< num, fmt >::v, LUT3D::X_SHIFT, ColorUYVY< num, fmt >::y1, ColorUYVY< num, fmt >::y2, LUT3D::Y_SHIFT, LUT3D::Z_AND_Y_BITS, LUT3D::Z_BITS, and LUT3D::Z_SHIFT.
Referenced by PluginColorThreshold::process(), and CMVision::ImageProcessor::processYUV422_UYVY().
{
   if (source->getColorFormat()!=COLOR_YUV422_UYVY) {
     //TODO add YUV444 and maybe even 411 mode
     fprintf(stderr,"CMVision thresholdImageYUV422_UYVY assumes YUV422 as input, but found %s\n", Colors::colorFormatToString(source->getColorFormat()).c_str());
     return false;
   }
   register lut_mask_t * LUT = lut->getTable();
   register unsigned int          target_size    = target->getNumPixels();
   register uyvy *       source_pointer = (uyvy*)(source->getData());
   register raw8 *      target_pointer = target->getPixelData();
   if (target->getNumPixels() != source->getNumPixels()) {
     fprintf(stderr, "CMVision YUV422_UYVY thresholding: source (num=%d  w=%d  h=%d) and target (num=%d w=%d h=%d) pixel counts do not match!\n", source->getNumPixels(),source->getWidth(),source->getHeight(), target->getNumPixels(),target->getWidth(),target->getHeight());
     return false;
   }
   lut->lock();
   int X_SHIFT=lut->X_SHIFT;
   int Y_SHIFT=lut->Y_SHIFT;
   int Z_SHIFT=lut->Z_SHIFT;
   int Z_AND_Y_BITS=lut->Z_AND_Y_BITS;
   int Z_BITS = lut->Z_BITS;
   uyvy p;
   for (unsigned int i=0;i<target_size;i+=2) {
     p=source_pointer[(i >> 0x01)];
     register int B=((p.u >> Y_SHIFT) << Z_BITS);
     register int C=(p.v >> Z_SHIFT);
     target_pointer[i] =  LUT[(((p.y1 >> X_SHIFT) << Z_AND_Y_BITS) | B | C)];
     target_pointer[i+1] =  LUT[(((p.y2 >> X_SHIFT) << Z_AND_Y_BITS) | B | C)];
   }
   lut->unlock();
   //printf("time: %f\n",t.time());
   return true;
 }
bool CMVisionThreshold::thresholdImageYUV444 (Image< raw8 > * target, const ImageInterface * source, YUVLUT * lut) static
Definition at line 82 of file cmvision_threshold.cpp.
References COLOR_YUV444, Colors::colorFormatToString(), ImageInterface::getColorFormat(), ImageInterface::getData(), ImageInterface::getHeight(), Image< PIXEL >::getHeight(), ImageInterface::getNumPixels(), Image< PIXEL >::getNumPixels(), Image< PIXEL >::getPixelData(), LUT3D::getTable(), ImageInterface::getWidth(), Image< PIXEL >::getWidth(), velocity.pid_::i, LUT3D::lock(), ColorYUV< num, fmt >::u, LUT3D::unlock(), ColorYUV< num, fmt >::v, LUT3D::X_SHIFT, ColorYUV< num, fmt >::y, LUT3D::Y_SHIFT, LUT3D::Z_AND_Y_BITS, LUT3D::Z_BITS, and LUT3D::Z_SHIFT.
Referenced by PluginColorThreshold::process(), and CMVision::ImageProcessor::processYUV444().
{
   if (source->getColorFormat()!=COLOR_YUV444) {
     fprintf(stderr,"CMVision thresholdImageYUV444 assumes YUV444 as input, but found %s\n", Colors::colorFormatToString(source->getColorFormat()).c_str());
     return false;
   }
   register lut_mask_t * LUT = lut->getTable();
   register unsigned int          target_size    = target->getNumPixels();
   register yuv  *                source_pointer = (yuv*)(source->getData());
   register raw8 *                target_pointer = target->getPixelData();
   if (target->getNumPixels() != source->getNumPixels()) {
      fprintf(stderr, "CMVision YUV444 thresholding: source (num=%d  w=%d  h=%d) and target (num=%d w=%d h=%d) pixel counts do not match!\n", source->getNumPixels(),source->getWidth(),source->getHeight(), target->getNumPixels(),target->getWidth(),target->getHeight());
     return false;
   }
   lut->lock();
   int X_SHIFT=lut->X_SHIFT;
   int Y_SHIFT=lut->Y_SHIFT;
   int Z_SHIFT=lut->Z_SHIFT;
   int Z_AND_Y_BITS=lut->Z_AND_Y_BITS;
   int Z_BITS = lut->Z_BITS;
   yuv p;
   for (unsigned int i=0;i<target_size;i++) {
     p=source_pointer[i];
     target_pointer[i] =  LUT[(((p.y >> X_SHIFT) << Z_AND_Y_BITS) | ((p.u >> Y_SHIFT) << Z_BITS) | (p.v >> Z_SHIFT))];
   }
   lut->unlock();
   return true;
 }
The documentation for this class was generated from the following files:
ssl-vision/src/shared/cmvision/cmvision_threshold.h
ssl-vision/src/shared/cmvision/cmvision_threshold.cpp