Documentation: StackRoboCupSSL Class Reference
StackRoboCupSSL Class Reference
The single camera vision stack implementation used for the RoboCup SSL.
#include <stack_robocup_ssl.h>
Public Member Functions
StackRoboCupSSL (RenderOptions *_opts, FrameBuffer *_fb, int camera_id, RoboCupField *_global_field, PluginDetectBallsSettings *_global_ball_settings, PluginPublishGeometry *_global_plugin_publish_geometry, PluginLegacyPublishGeometry *_legacy_plugin_publish_geometry, CMPattern::TeamSelector *_global_team_selector_blue, CMPattern::TeamSelector *_global_team_selector_yellow, RoboCupSSLServer *ds_udp_server_new, RoboCupSSLServer *ds_udp_server_old, string cam_settings_filename)
virtual string getSettingsFileName ()
virtual ~StackRoboCupSSL ()
Public Member Functions inherited from VisionStack
VisionStack (string _name, RenderOptions *_opts)
virtual ~VisionStack ()
VarList * getSettings ()
virtual string getName ()
void process (FrameData *data)
void postProcess (FrameData *data)
void updateTimingStatistics ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
Protected Attributes
int _camera_id
YUVLUT * lut_yuv
string _cam_settings_filename
CameraParameters * camera_parameters
RoboCupField * global_field
PluginDetectBallsSettings * global_ball_settings
CMPattern::TeamSelector * global_team_selector_blue
CMPattern::TeamSelector * global_team_selector_yellow
RoboCupSSLServer * _ds_udp_server_new
RoboCupSSLServer * _ds_udp_server_old
Protected Attributes inherited from VisionStack
string name
RenderOptions * opts
VarList * settings
Additional Inherited Members
Data Fields inherited from VisionStack
vector< VisionPlugin * > stack
Detailed Description
The single camera vision stack implementation used for the RoboCup SSL.
Author
Stefan Zickler, (C) 2008 multiple of these stacks are run in parallel using the MultiStackRoboCupSSL
Definition at line 57 of file stack_robocup_ssl.h.
Constructor & Destructor Documentation
StackRoboCupSSL::StackRoboCupSSL (RenderOptions * _opts, FrameBuffer * _fb, int camera_id, RoboCupField * _global_field, PluginDetectBallsSettings * _global_ball_settings, PluginPublishGeometry * _global_plugin_publish_geometry, PluginLegacyPublishGeometry * _legacy_plugin_publish_geometry, CMPattern::TeamSelector * _global_team_selector_blue, CMPattern::TeamSelector * _global_team_selector_yellow, RoboCupSSLServer * ds_udp_server_new, RoboCupSSLServer * ds_udp_server_old, string cam_settings_filename)
Definition at line 23 of file stack_robocup_ssl.cpp.
References _camera_id, _ds_udp_server_new, _ds_udp_server_old, PluginPublishGeometry::addCameraParameters(), PluginLegacyPublishGeometry::addCameraParameters(), VarTypes::VarList::addChild(), LUT3D::addDerivedLUT(), camera_parameters, LUT3D::getSettings(), global_ball_settings, global_field, global_team_selector_blue, global_team_selector_yellow, LUT3D::loadRoboCupChannels(), lut_yuv, LUTChannelMode_Numeric, PluginVisualize::setThresholdingLUT(), VisionStack::settings, and VisionStack::stack.
                                   :
     VisionStack("RoboCup Image Processing",_opts),
     _camera_id(camera_id),
     _cam_settings_filename(cam_settings_filename),
     global_field(_global_field),
     global_ball_settings(_global_ball_settings),
     global_team_selector_blue(_global_team_selector_blue),
     global_team_selector_yellow(_global_team_selector_yellow),
     _ds_udp_server_new(ds_udp_server_new),
     _ds_udp_server_old(ds_udp_server_old) {
   (void)_fb;
   lut_yuv = new YUVLUT(4,6,6,cam_settings_filename + "-lut-yuv.xml");
   lut_yuv->loadRoboCupChannels(LUTChannelMode_Numeric);
   lut_yuv->addDerivedLUT(new RGBLUT(5,5,5,""));
   camera_parameters = new CameraParameters(_camera_id);
   _global_plugin_publish_geometry->addCameraParameters(camera_parameters);
   _legacy_plugin_publish_geometry->addCameraParameters(camera_parameters);
   stack.push_back(new PluginDVR(_fb));
   stack.push_back(new PluginColorCalibration(_fb,lut_yuv, LUTChannelMode_Numeric));
 #ifdef OPENCV
   stack.push_back(new PluginNeuralColorCalib(_fb,lut_yuv, LUTChannelMode_Numeric));
 #endif
   settings->addChild(lut_yuv->getSettings());
   stack.push_back(new PluginCameraCalibration(_fb,*camera_parameters, *global_field));
   stack.push_back(new PluginColorThreshold(_fb,lut_yuv));
   //initialize the runlength encoder...
   //we don't expect more than 50k runs per image
   stack.push_back(new PluginRunlengthEncode(_fb,50000));
   //initialize the blob finder
   //we don't expect more than 10k blobs per image
   stack.push_back(new PluginFindBlobs(_fb,lut_yuv, 10000));
   stack.push_back(new PluginDetectRobots(_fb,lut_yuv,*camera_parameters,*global_field,global_team_selector_blue,global_team_selector_yellow));
   stack.push_back(new PluginDetectBalls(_fb,lut_yuv,*camera_parameters,*global_field,global_ball_settings));
   stack.push_back(new PluginSSLNetworkOutput(
       _fb,
       _ds_udp_server_new,
       *camera_parameters,
       *global_field));
   stack.push_back(new PluginLegacySSLNetworkOutput(
       _fb,
       _ds_udp_server_old,
       *camera_parameters,
       *global_field));
   stack.push_back(_global_plugin_publish_geometry);
   stack.push_back(_legacy_plugin_publish_geometry);
   PluginVisualize * vis = new PluginVisualize(_fb,*camera_parameters,*global_field);
   vis->setThresholdingLUT(lut_yuv);
   stack.push_back(vis);
 }
StackRoboCupSSL::~StackRoboCupSSL () virtual
Definition at line 101 of file stack_robocup_ssl.cpp.
References camera_parameters, and lut_yuv.
{
   delete lut_yuv;
   delete camera_parameters;
 }
Member Function Documentation
string StackRoboCupSSL::getSettingsFileName () virtual
Reimplemented from VisionStack.
Definition at line 98 of file stack_robocup_ssl.cpp.
References _cam_settings_filename.
{
   return _cam_settings_filename;
 }
Field Documentation
string StackRoboCupSSL::_cam_settings_filename protected
Definition at line 61 of file stack_robocup_ssl.h.
Referenced by getSettingsFileName().
int StackRoboCupSSL::_camera_id protected
Definition at line 59 of file stack_robocup_ssl.h.
Referenced by StackRoboCupSSL().
RoboCupSSLServer* StackRoboCupSSL::_ds_udp_server_new protected
Definition at line 68 of file stack_robocup_ssl.h.
Referenced by StackRoboCupSSL().
RoboCupSSLServer* StackRoboCupSSL::_ds_udp_server_old protected
Definition at line 70 of file stack_robocup_ssl.h.
Referenced by StackRoboCupSSL().
CameraParameters* StackRoboCupSSL::camera_parameters protected
Definition at line 62 of file stack_robocup_ssl.h.
Referenced by StackRoboCupSSL(), and ~StackRoboCupSSL().
PluginDetectBallsSettings* StackRoboCupSSL::global_ball_settings protected
Definition at line 64 of file stack_robocup_ssl.h.
Referenced by StackRoboCupSSL().
RoboCupField* StackRoboCupSSL::global_field protected
Definition at line 63 of file stack_robocup_ssl.h.
Referenced by StackRoboCupSSL().
CMPattern::TeamSelector* StackRoboCupSSL::global_team_selector_blue protected
Definition at line 65 of file stack_robocup_ssl.h.
Referenced by StackRoboCupSSL().
CMPattern::TeamSelector* StackRoboCupSSL::global_team_selector_yellow protected
Definition at line 66 of file stack_robocup_ssl.h.
Referenced by StackRoboCupSSL().
YUVLUT* StackRoboCupSSL::lut_yuv protected
Definition at line 60 of file stack_robocup_ssl.h.
Referenced by StackRoboCupSSL(), and ~StackRoboCupSSL().
The documentation for this class was generated from the following files:
ssl-vision/src/app/stacks/stack_robocup_ssl.h
ssl-vision/src/app/stacks/stack_robocup_ssl.cpp