Documentation: ssl-vision/src/shared/util/vis_util.h File Reference
vis_util.h File Reference
Vision support functions.
#include <math.h>
Functions
double gaussian (double x)
double gaussian (double x, double var)
double GaussianVsUniform (double x, double var, double u)
double SSEVsUniform (double x2, double var, double u)
template<class item >
void add_bucket (item *bucket, int max, item &it)
template<class data >
void roll (data *arr, data *tmp, int num, int displacement)
Detailed Description
Vision support functions.
Author
James R. Bruce, (C) 1999-2002
Definition in file vis_util.h.
Function Documentation
template<class item > void add_bucket (item * bucket, int max, item & it)
Definition at line 50 of file vis_util.h.
References velocity.pid_::i.
 {
   int i;
   if(it.conf < bucket[max-1].conf) return;
   i = max-2;
   while(i>=0 && it.conf>bucket[i].conf){
     bucket[i+1] = bucket[i];
     i--;
   }
   bucket[i+1] = it;
 }
double gaussian (double x) inline
Definition at line 27 of file vis_util.h.
Referenced by GaussianVsUniform(), and PluginDetectBalls::process().
 {
   return(exp(-(x*x)/2));
 }
double gaussian (double x, double var) inline
Definition at line 32 of file vis_util.h.
 {
   return(exp(x*x / (-2*var)));
 }
double GaussianVsUniform (double x, double var, double u) inline
Definition at line 37 of file vis_util.h.
References gaussian().
Referenced by CMPattern::TeamDetector::findRobotsByTeamMarkerOnly().
 {
   double g = gaussian(x,var);
   return(g / (g + u));
 }
template<class data > void roll (data * arr, data * tmp, int num, int displacement)
Definition at line 65 of file vis_util.h.
References velocity.pid_::i.
Referenced by CMPattern::MultiPatternModel::findPattern(), GLCamera::setRoll(), and GLCamera::setState().
 {
   int i;
   // make sure it's positive
   displacement = ((displacement % num) + num) % num;
   // check if we have to do anything
   if(displacement % num == 0) return;
   // rotate using temp storage
   for(i=0; i<num; i++) tmp[i] = arr[i];
   for(i=0; i<num; i++) arr[(i + displacement) % num] = tmp[i];
 }
double SSEVsUniform (double x2, double var, double u) inline
Definition at line 43 of file vis_util.h.
Referenced by CMPattern::MultiPatternModel::findPattern().
 {
   double g = exp(x2 / (-2*var));
   return(g / (g + u));
 }