Documentation: Client.Interface Class Reference
Client.Interface Class Reference
Public Member Functions
Interface ()
Static Public Member Functions
static void main (String args[])
Private Member Functions
void initComponents ()
void jTextField1ActionPerformed (java.awt.event.ActionEvent evt)
void jTextField12ActionPerformed (java.awt.event.ActionEvent evt)
void jButton1ActionPerformed (java.awt.event.ActionEvent evt)
void jButton2ActionPerformed (java.awt.event.ActionEvent evt)
Private Attributes
Conection conection
javax.swing.JButton jButton1
javax.swing.JButton jButton2
javax.swing.JCheckBox jCheckBox1
javax.swing.JCheckBox jCheckBox2
javax.swing.JComboBox jComboBox1
javax.swing.JLabel jLabel1
javax.swing.JLabel jLabel10
javax.swing.JLabel jLabel11
javax.swing.JLabel jLabel12
javax.swing.JLabel jLabel2
javax.swing.JLabel jLabel3
javax.swing.JLabel jLabel4
javax.swing.JLabel jLabel5
javax.swing.JLabel jLabel6
javax.swing.JLabel jLabel7
javax.swing.JLabel jLabel8
javax.swing.JLabel jLabel9
javax.swing.JTextField jTextField1
javax.swing.JTextField jTextField10
javax.swing.JTextField jTextField11
javax.swing.JTextField jTextField12
javax.swing.JTextField jTextField2
javax.swing.JTextField jTextField3
javax.swing.JTextField jTextField4
javax.swing.JTextField jTextField5
javax.swing.JTextField jTextField6
javax.swing.JTextField jTextField7
javax.swing.JTextField jTextField8
javax.swing.JTextField jTextField9
Detailed Description
Definition at line 15 of file Interface.java.
Constructor & Destructor Documentation
Client.Interface.Interface () inline
Creates new form Interfaz
Definition at line 20 of file Interface.java.
References Client.Interface.initComponents().
Referenced by Client.Interface.main().
{
         conection=new Conection();
         initComponents();
     }
Member Function Documentation
void Client.Interface.initComponents () inline private
This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 32 of file Interface.java.
References Client.Interface.jButton1, Client.Interface.jButton1ActionPerformed(), Client.Interface.jButton2, Client.Interface.jButton2ActionPerformed(), Client.Interface.jCheckBox1, Client.Interface.jCheckBox2, Client.Interface.jComboBox1, Client.Interface.jLabel1, Client.Interface.jLabel10, Client.Interface.jLabel11, Client.Interface.jLabel12, Client.Interface.jLabel2, Client.Interface.jLabel3, Client.Interface.jLabel4, Client.Interface.jLabel5, Client.Interface.jLabel6, Client.Interface.jLabel7, Client.Interface.jLabel8, Client.Interface.jLabel9, Client.Interface.jTextField1, Client.Interface.jTextField10, Client.Interface.jTextField11, Client.Interface.jTextField12, Client.Interface.jTextField12ActionPerformed(), Client.Interface.jTextField1ActionPerformed(), Client.Interface.jTextField2, Client.Interface.jTextField3, Client.Interface.jTextField4, Client.Interface.jTextField5, Client.Interface.jTextField6, Client.Interface.jTextField7, Client.Interface.jTextField8, and Client.Interface.jTextField9.
Referenced by Client.Interface.Interface().
{
         jLabel1 = new javax.swing.JLabel();
         jLabel2 = new javax.swing.JLabel();
         jLabel3 = new javax.swing.JLabel();
         jLabel4 = new javax.swing.JLabel();
         jLabel5 = new javax.swing.JLabel();
         jCheckBox1 = new javax.swing.JCheckBox();
         jLabel6 = new javax.swing.JLabel();
         jCheckBox2 = new javax.swing.JCheckBox();
         jTextField1 = new javax.swing.JTextField();
         jTextField2 = new javax.swing.JTextField();
         jTextField3 = new javax.swing.JTextField();
         jTextField4 = new javax.swing.JTextField();
         jTextField5 = new javax.swing.JTextField();
         jTextField6 = new javax.swing.JTextField();
         jLabel7 = new javax.swing.JLabel();
         jComboBox1 = new javax.swing.JComboBox();
         jLabel8 = new javax.swing.JLabel();
         jLabel9 = new javax.swing.JLabel();
         jLabel10 = new javax.swing.JLabel();
         jLabel11 = new javax.swing.JLabel();
         jTextField7 = new javax.swing.JTextField();
         jTextField8 = new javax.swing.JTextField();
         jTextField9 = new javax.swing.JTextField();
         jTextField10 = new javax.swing.JTextField();
         jLabel12 = new javax.swing.JLabel();
         jTextField11 = new javax.swing.JTextField();
         jTextField12 = new javax.swing.JTextField();
         jButton1 = new javax.swing.JButton();
         jButton2 = new javax.swing.JButton();
         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
         jLabel1.setText("Simulator Address");
         jLabel2.setText("Id");
         jLabel3.setText("Velocity X (m/s)");
         jLabel4.setText("Velocity Y(m/s)");
         jLabel5.setText("Velocity Z(m/s)");
         jCheckBox1.setText("Send Velocity? (or wheels)");
         jLabel6.setText("Chip (m/s)");
         jCheckBox2.setText("Spin");
         jTextField1.setText("127.0.0.1");
         jTextField1.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jTextField1ActionPerformed(evt);
             }
         });
         jTextField2.setText("0");
         jTextField3.setText("0");
         jTextField4.setText("0");
         jTextField5.setText("0");
         jTextField6.setText("0");
         jLabel7.setText("Simulator Port");
         jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yellow", "Blue" }));
         jLabel8.setText("Wheel1 (m/s)");
         jLabel9.setText("Wheel2 (m/s)");
         jLabel10.setText("Wheel3 (m/s)");
         jLabel11.setText("Wheel4 (m/s)");
         jTextField7.setText("0");
         jTextField8.setText("0");
         jTextField9.setText("0");
         jTextField10.setText("0");
         jLabel12.setText("Kick (m/s)");
         jTextField11.setText("0");
         jTextField12.setText("20011");
         jTextField12.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jTextField12ActionPerformed(evt);
             }
         });
         jButton1.setText("Send");
         jButton1.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton1ActionPerformed(evt);
             }
         });
         jButton2.setText("Reset");
         jButton2.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton2ActionPerformed(evt);
             }
         });
         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
         getContentPane().setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addContainerGap()
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                             .addComponent(jCheckBox2)
                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                             .addComponent(jLabel5)
                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                             .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                             .addComponent(jLabel4)
                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                             .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                             .addComponent(jLabel3)
                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                             .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                             .addComponent(jLabel2)
                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                             .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                             .addComponent(jLabel1)
                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                             .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                             .addComponent(jLabel6)
                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                 .addGroup(layout.createSequentialGroup()
                                     .addComponent(jButton1)
                                     .addGap(73, 73, 73))
                                 .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                     .addGroup(layout.createSequentialGroup()
                         .addComponent(jCheckBox1)
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                         .addGap(43, 43, 43)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                             .addGroup(layout.createSequentialGroup()
                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                     .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                     .addComponent(jLabel8))
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                     .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                     .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                             .addGroup(layout.createSequentialGroup()
                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                     .addComponent(jLabel11)
                                     .addComponent(jLabel10)
                                     .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                 .addGap(18, 18, 18)
                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                     .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                     .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                     .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                             .addGroup(layout.createSequentialGroup()
                                 .addComponent(jLabel9)
                                 .addGap(18, 18, 18)
                                 .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                             .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                     .addGroup(layout.createSequentialGroup()
                         .addGap(51, 51, 51)
                         .addComponent(jButton2)))
                 .addContainerGap(78, Short.MAX_VALUE))
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addGap(20, 20, 20)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(jLabel7)
                         .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                         .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addGroup(layout.createSequentialGroup()
                                 .addGap(7, 7, 7)
                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                     .addComponent(jLabel2)
                                     .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                     .addComponent(jLabel3)
                                     .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                             .addGroup(layout.createSequentialGroup()
                                 .addGap(6, 6, 6)
                                 .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                     .addComponent(jLabel8)
                                     .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                         .addGap(18, 18, 18)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                 .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                 .addComponent(jLabel4))
                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                 .addComponent(jLabel9)
                                 .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                             .addComponent(jLabel10)
                             .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addGroup(layout.createSequentialGroup()
                         .addGap(144, 144, 144)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                             .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                             .addComponent(jLabel5))))
                 .addGap(18, 18, 18)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                             .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                             .addComponent(jLabel11))
                         .addGap(18, 18, 18)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                             .addComponent(jLabel12)
                             .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addGroup(layout.createSequentialGroup()
                         .addComponent(jCheckBox1)
                         .addGap(7, 7, 7)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                             .addComponent(jLabel6)
                             .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                         .addComponent(jCheckBox2)
                         .addGap(35, 35, 35)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                             .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                             .addComponent(jButton2))))
                 .addContainerGap(29, Short.MAX_VALUE))
         );
         pack();
     }// </editor-fold>//GEN-END:initComponents
void Client.Interface.jButton1ActionPerformed (java.awt.event.ActionEvent evt) inline private
Definition at line 302 of file Interface.java.
References Client.Interface.conection, Client.Interface.jCheckBox1, Client.Interface.jCheckBox2, Client.Interface.jComboBox1, Client.Interface.jTextField1, Client.Conection.send(), Client.Conection.setId(), Client.Conection.setIp(), Client.Conection.setKickspeedX(), Client.Conection.setKickspeedZ(), Client.Conection.setPort(), Client.Conection.setSpinner(), Client.Conection.setTeamYellow(), Client.Conection.setVelX(), Client.Conection.setVelY(), Client.Conection.setVelZ(), Client.Conection.setWheel1(), Client.Conection.setWheel2(), Client.Conection.setWheel3(), Client.Conection.setWheel4(), and Client.Conection.setWheelSpeed().
Referenced by Client.Interface.initComponents().
                                                                          {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
         conection.setIp(this.jTextField1.getText());
         conection.setPort(Integer.parseInt(this.jTextField12.getText()));
         conection.setId(Integer.parseInt(this.jTextField2.getText()));
         conection.setWheel1(Float.parseFloat(this.jTextField7.getText()));
         conection.setWheel2(Float.parseFloat(this.jTextField10.getText()));
         conection.setWheel3(Float.parseFloat(this.jTextField8.getText()));
         conection.setWheel4(Float.parseFloat(this.jTextField9.getText()));
         conection.setVelX(Float.parseFloat(this.jTextField3.getText()));
         conection.setVelY(Float.parseFloat(this.jTextField4.getText()));
         conection.setVelZ(Float.parseFloat(this.jTextField5.getText()));
         conection.setWheelSpeed(this.jCheckBox1.isSelected());
         conection.setKickspeedZ(Float.parseFloat(this.jTextField6.getText()));
         if(this.jComboBox1.getSelectedItem().equals("Yellow"))
             conection.setTeamYellow(true);
         else
             conection.setTeamYellow(false);
         conection.setKickspeedX(Float.parseFloat(this.jTextField11.getText()));
         conection.setSpinner(this.jCheckBox2.isSelected());
         conection.send();
     }//GEN-LAST:event_jButton1ActionPerformed
void Client.Interface.jButton2ActionPerformed (java.awt.event.ActionEvent evt) inline private
Definition at line 325 of file Interface.java.
References Client.Interface.conection, Client.Interface.jCheckBox2, Client.Interface.jComboBox1, Client.Interface.jTextField1, Client.Interface.jTextField10, Client.Interface.jTextField11, Client.Interface.jTextField12, Client.Interface.jTextField2, Client.Interface.jTextField3, Client.Interface.jTextField4, Client.Interface.jTextField5, Client.Interface.jTextField6, Client.Interface.jTextField7, Client.Interface.jTextField8, Client.Interface.jTextField9, Client.Conection.send(), Client.Conection.setId(), Client.Conection.setIp(), Client.Conection.setKickspeedX(), Client.Conection.setKickspeedZ(), Client.Conection.setPort(), Client.Conection.setSpinner(), Client.Conection.setTeamYellow(), Client.Conection.setVelX(), Client.Conection.setVelY(), Client.Conection.setVelZ(), Client.Conection.setWheel1(), Client.Conection.setWheel2(), Client.Conection.setWheel3(), Client.Conection.setWheel4(), and Client.Conection.setWheelSpeed().
Referenced by Client.Interface.initComponents().
                                                                          {//GEN-FIRST:event_jButton2ActionPerformed
         // TODO add your handling code here:
         conection.setIp("127.0.0.1");
         conection.setPort(20011);
         conection.setId(0);
         conection.setWheel1(0);
         conection.setWheel2(0);
         conection.setWheel3(0);
         conection.setWheel4(0);
         conection.setVelX(0);
         conection.setVelY(0);
         conection.setVelZ(0);
         conection.setWheelSpeed(false);
         conection.setKickspeedZ(0);
         if(this.jComboBox1.getSelectedItem().equals("Yellow"))
             conection.setTeamYellow(true);
         else
             conection.setTeamYellow(false);
         conection.setKickspeedX(0);
         conection.setSpinner(this.jCheckBox2.isSelected());
         conection.send();
         this.jTextField1.setText("127.0.0.1");
         this.jTextField10.setText("0");
         this.jTextField11.setText("0");
         this.jTextField12.setText("20011");
         this.jTextField2.setText("0");
         this.jTextField3.setText("0");
         this.jTextField4.setText("0");
         this.jTextField5.setText("0");
         this.jTextField6.setText("0");
         this.jTextField7.setText("0");
         this.jTextField8.setText("0");
         this.jTextField9.setText("0");
     }//GEN-LAST:event_jButton2ActionPerformed
void Client.Interface.jTextField12ActionPerformed (java.awt.event.ActionEvent evt) inline private
Definition at line 298 of file Interface.java.
Referenced by Client.Interface.initComponents().
                                                                              {//GEN-FIRST:event_jTextField12ActionPerformed
         // TODO add your handling code here:
     }//GEN-LAST:event_jTextField12ActionPerformed
void Client.Interface.jTextField1ActionPerformed (java.awt.event.ActionEvent evt) inline private
Definition at line 294 of file Interface.java.
Referenced by Client.Interface.initComponents().
                                                                             {//GEN-FIRST:event_jTextField1ActionPerformed
         // TODO add your handling code here:
     }//GEN-LAST:event_jTextField1ActionPerformed
static void Client.Interface.main (String args[]) inline static
Parameters
args the command line arguments
Definition at line 365 of file Interface.java.
References Client.Interface.Interface(), and role._GoToPoint_.run.
{
         java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                 new Interface().setVisible(true);
             }
         });
     }
Field Documentation
Conection Client.Interface.conection private
Definition at line 17 of file Interface.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JButton Client.Interface.jButton1 private
Definition at line 374 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JButton Client.Interface.jButton2 private
Definition at line 375 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JCheckBox Client.Interface.jCheckBox1 private
Definition at line 376 of file Interface.java.
Referenced by Client.Interface.initComponents(), and Client.Interface.jButton1ActionPerformed().
javax.swing.JCheckBox Client.Interface.jCheckBox2 private
Definition at line 377 of file Interface.java.
Referenced by Client.Interface.initComponents(), Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JComboBox Client.Interface.jComboBox1 private
Definition at line 378 of file Interface.java.
Referenced by Client.Interface.initComponents(), Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JLabel Client.Interface.jLabel1 private
Definition at line 379 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JLabel Client.Interface.jLabel10 private
Definition at line 380 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JLabel Client.Interface.jLabel11 private
Definition at line 381 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JLabel Client.Interface.jLabel12 private
Definition at line 382 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JLabel Client.Interface.jLabel2 private
Definition at line 383 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JLabel Client.Interface.jLabel3 private
Definition at line 384 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JLabel Client.Interface.jLabel4 private
Definition at line 385 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JLabel Client.Interface.jLabel5 private
Definition at line 386 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JLabel Client.Interface.jLabel6 private
Definition at line 387 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JLabel Client.Interface.jLabel7 private
Definition at line 388 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JLabel Client.Interface.jLabel8 private
Definition at line 389 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JLabel Client.Interface.jLabel9 private
Definition at line 390 of file Interface.java.
Referenced by Client.Interface.initComponents().
javax.swing.JTextField Client.Interface.jTextField1 private
Definition at line 391 of file Interface.java.
Referenced by Client.Interface.initComponents(), Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JTextField Client.Interface.jTextField10 private
Definition at line 392 of file Interface.java.
Referenced by Client.Interface.initComponents(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JTextField Client.Interface.jTextField11 private
Definition at line 393 of file Interface.java.
Referenced by Client.Interface.initComponents(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JTextField Client.Interface.jTextField12 private
Definition at line 394 of file Interface.java.
Referenced by Client.Interface.initComponents(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JTextField Client.Interface.jTextField2 private
Definition at line 395 of file Interface.java.
Referenced by Client.Interface.initComponents(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JTextField Client.Interface.jTextField3 private
Definition at line 396 of file Interface.java.
Referenced by Client.Interface.initComponents(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JTextField Client.Interface.jTextField4 private
Definition at line 397 of file Interface.java.
Referenced by Client.Interface.initComponents(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JTextField Client.Interface.jTextField5 private
Definition at line 398 of file Interface.java.
Referenced by Client.Interface.initComponents(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JTextField Client.Interface.jTextField6 private
Definition at line 399 of file Interface.java.
Referenced by Client.Interface.initComponents(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JTextField Client.Interface.jTextField7 private
Definition at line 400 of file Interface.java.
Referenced by Client.Interface.initComponents(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JTextField Client.Interface.jTextField8 private
Definition at line 401 of file Interface.java.
Referenced by Client.Interface.initComponents(), and Client.Interface.jButton2ActionPerformed().
javax.swing.JTextField Client.Interface.jTextField9 private
Definition at line 402 of file Interface.java.
Referenced by Client.Interface.initComponents(), and Client.Interface.jButton2ActionPerformed().
The documentation for this class was generated from the following file:
grSim/clients/java/src/Client/Interface.java