Documentation: grsim_comm/include/proto/sslDebug_Data.pb.cc File Reference
sslDebug_Data.pb.cc File Reference
#include "sslDebug_Data.pb.h"
#include <algorithm>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
Data Structures
class sslDebug_DataDefaultTypeInternal
class Debug_CircleDefaultTypeInternal
class Debug_LineDefaultTypeInternal
class Debug_AdjustBotDefaultTypeInternal
class Debug_AdjustBallDefaultTypeInternal
struct StaticDescriptorInitializer_sslDebug_5fData_2eproto
Namespaces
anonymous_namespace{sslDebug_Data.pb.cc}
Macros
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Functions
const ::google::protobuf::uint32 * protobuf_Offsets_sslDebug_5fData_2eproto () GOOGLE_ATTRIBUTE_COLD
void anonymous_namespace{sslDebug_Data.pb.cc}::protobuf_AssignDescriptors ()
void anonymous_namespace{sslDebug_Data.pb.cc}::protobuf_AssignDescriptorsOnce ()
void anonymous_namespace{sslDebug_Data.pb.cc}::protobuf_RegisterTypes (const ::std::string &) GOOGLE_ATTRIBUTE_COLD
void protobuf_ShutdownFile_sslDebug_5fData_2eproto ()
void protobuf_InitDefaults_sslDebug_5fData_2eproto_impl ()
void protobuf_InitDefaults_sslDebug_5fData_2eproto ()
void protobuf_AddDesc_sslDebug_5fData_2eproto_impl ()
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_sslDebug_5fData_2eproto_once_)
void protobuf_AddDesc_sslDebug_5fData_2eproto ()
Variables
sslDebug_DataDefaultTypeInternal _sslDebug_Data_default_instance_
Debug_CircleDefaultTypeInternal _Debug_Circle_default_instance_
Debug_LineDefaultTypeInternal _Debug_Line_default_instance_
Debug_AdjustBotDefaultTypeInternal _Debug_AdjustBot_default_instance_
Debug_AdjustBallDefaultTypeInternal _Debug_AdjustBall_default_instance_
::google::protobuf::Metadata anonymous_namespace{sslDebug_Data.pb.cc}::file_level_metadata [5]
static const ::google::protobuf::internal::MigrationSchema schemas []
static const ::google::protobuf::internal::DefaultInstanceData file_default_instances []
struct StaticDescriptorInitializer_sslDebug_5fData_2eproto static_descriptor_initializer_sslDebug_5fData_2eproto_
Macro Definition Documentation
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Referenced by sslDebug_Data::MergePartialFromCodedStream(), Debug_Circle::MergePartialFromCodedStream(), Debug_Line::MergePartialFromCodedStream(), Debug_AdjustBot::MergePartialFromCodedStream(), and Debug_AdjustBall::MergePartialFromCodedStream().
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
Definition at line 4 of file sslDebug_Data.pb.cc.
Function Documentation
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_sslDebug_5fData_2eproto_once_)
Referenced by protobuf_AddDesc_sslDebug_5fData_2eproto_impl(), anonymous_namespace{sslDebug_Data.pb.cc}::protobuf_AssignDescriptorsOnce(), and protobuf_InitDefaults_sslDebug_5fData_2eproto().
void protobuf_AddDesc_sslDebug_5fData_2eproto ()
Definition at line 210 of file sslDebug_Data.pb.cc.
References protobuf_AddDesc_sslDebug_5fData_2eproto_impl().
Referenced by protobuf_AddDesc_grSim_5fPacket_2eproto_impl(), anonymous_namespace{sslDebug_Data.pb.cc}::protobuf_AssignDescriptors(), and StaticDescriptorInitializer_sslDebug_5fData_2eproto::StaticDescriptorInitializer_sslDebug_5fData_2eproto().
{
   ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_sslDebug_5fData_2eproto_once_,
                  &protobuf_AddDesc_sslDebug_5fData_2eproto_impl);
 }
void protobuf_AddDesc_sslDebug_5fData_2eproto_impl ()
Definition at line 185 of file sslDebug_Data.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), protobuf_InitDefaults_sslDebug_5fData_2eproto(), anonymous_namespace{sslDebug_Data.pb.cc}::protobuf_RegisterTypes(), and protobuf_ShutdownFile_sslDebug_5fData_2eproto().
Referenced by protobuf_AddDesc_sslDebug_5fData_2eproto().
{
   protobuf_InitDefaults_sslDebug_5fData_2eproto();
   static const char descriptor[] = {
       "\n\023sslDebug_Data.proto\"\233\001\n\rsslDebug_Data\022"
       "\n\n\002id\030\001 \002(\t\022\035\n\006circle\030\002 \003(\0132\r.Debug_Circ"
       "le\022\031\n\004line\030\003 \003(\0132\013.Debug_Line\022 \n\006botpos\030"
       "\004 \003(\0132\020.Debug_AdjustBot\022\"\n\007ballpos\030\005 \003(\013"
       "2\021.Debug_AdjustBall\"C\n\014Debug_Circle\022\t\n\001x"
       "\030\001 \002(\005\022\t\n\001y\030\002 \002(\005\022\016\n\006radius\030\003 \002(\005\022\r\n\005col"
       "or\030\004 \002(\002\"K\n\nDebug_Line\022\n\n\002x1\030\001 \002(\005\022\n\n\002y1"
       "\030\002 \002(\005\022\n\n\002x2\030\003 \002(\005\022\n\n\002y2\030\004 \002(\005\022\r\n\005color\030"
       "\005 \002(\002\"r\n\017Debug_AdjustBot\022\n\n\002id\030\001 \002(\r\022\t\n\001"
       "x\030\002 \002(\005\022\t\n\001y\030\003 \002(\005\022\013\n\003dir\030\004 \002(\002\022\n\n\002vx\030\005 "
       "\002(\005\022\n\n\002vy\030\006 \002(\005\022\n\n\002vz\030\007 \002(\005\022\014\n\004team\030\010 \002("
       "\r\"L\n\020Debug_AdjustBall\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 "
       "\002(\005\022\n\n\002vx\030\003 \002(\005\022\n\n\002vy\030\004 \002(\005\022\n\n\002vz\030\005 \002(\r"
   };
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
       descriptor, 519);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "sslDebug_Data.proto", &protobuf_RegisterTypes);
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_sslDebug_5fData_2eproto);
 }
void protobuf_InitDefaults_sslDebug_5fData_2eproto ()
Definition at line 181 of file sslDebug_Data.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), and protobuf_InitDefaults_sslDebug_5fData_2eproto_impl().
Referenced by Debug_AdjustBall::Debug_AdjustBall(), Debug_AdjustBot::Debug_AdjustBot(), Debug_Circle::Debug_Circle(), Debug_Line::Debug_Line(), sslDebug_Data::default_instance(), Debug_Circle::default_instance(), Debug_Line::default_instance(), Debug_AdjustBot::default_instance(), Debug_AdjustBall::default_instance(), protobuf_AddDesc_sslDebug_5fData_2eproto_impl(), protobuf_InitDefaults_grSim_5fPacket_2eproto_impl(), and sslDebug_Data::sslDebug_Data().
{
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
   ::google::protobuf::GoogleOnceInit(&once, &protobuf_InitDefaults_sslDebug_5fData_2eproto_impl);
 }
void protobuf_InitDefaults_sslDebug_5fData_2eproto_impl ()
Definition at line 170 of file sslDebug_Data.pb.cc.
Referenced by protobuf_InitDefaults_sslDebug_5fData_2eproto().
{
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::internal::InitProtobufDefaults();
   _sslDebug_Data_default_instance_.DefaultConstruct();
   _Debug_Circle_default_instance_.DefaultConstruct();
   _Debug_Line_default_instance_.DefaultConstruct();
   _Debug_AdjustBot_default_instance_.DefaultConstruct();
   _Debug_AdjustBall_default_instance_.DefaultConstruct();
 }
const ::google::protobuf::uint32 * protobuf_Offsets_sslDebug_5fData_2eproto ()
Definition at line 38 of file sslDebug_Data.pb.cc.
Referenced by anonymous_namespace{sslDebug_Data.pb.cc}::protobuf_AssignDescriptors().
{
   static const ::google::protobuf::uint32 offsets[] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(sslDebug_Data, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(sslDebug_Data, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(sslDebug_Data, id_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(sslDebug_Data, circle_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(sslDebug_Data, line_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(sslDebug_Data, botpos_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(sslDebug_Data, ballpos_),
     0,
     1,
     2,
     3,
     4,
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_Circle, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_Circle, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_Circle, x_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_Circle, y_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_Circle, radius_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_Circle, color_),
     0,
     1,
     2,
     3,
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_Line, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_Line, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_Line, x1_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_Line, y1_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_Line, x2_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_Line, y2_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_Line, color_),
     0,
     1,
     2,
     3,
     4,
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBot, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBot, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBot, id_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBot, x_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBot, y_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBot, dir_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBot, vx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBot, vy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBot, vz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBot, team_),
     0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBall, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBall, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBall, x_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBall, y_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBall, vx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBall, vy_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Debug_AdjustBall, vz_),
     0,
     1,
     2,
     3,
     4,
   };
   return offsets;
 }
void protobuf_ShutdownFile_sslDebug_5fData_2eproto ()
Definition at line 157 of file sslDebug_Data.pb.cc.
References anonymous_namespace{sslDebug_Data.pb.cc}::file_level_metadata.
Referenced by protobuf_AddDesc_sslDebug_5fData_2eproto_impl().
{
   _sslDebug_Data_default_instance_.Shutdown();
   delete file_level_metadata[0].reflection;
   _Debug_Circle_default_instance_.Shutdown();
   delete file_level_metadata[1].reflection;
   _Debug_Line_default_instance_.Shutdown();
   delete file_level_metadata[2].reflection;
   _Debug_AdjustBot_default_instance_.Shutdown();
   delete file_level_metadata[3].reflection;
   _Debug_AdjustBall_default_instance_.Shutdown();
   delete file_level_metadata[4].reflection;
 }
Variable Documentation
Debug_AdjustBallDefaultTypeInternal _Debug_AdjustBall_default_instance_
Definition at line 28 of file sslDebug_Data.pb.cc.
Referenced by Debug_AdjustBall::internal_default_instance().
Debug_AdjustBotDefaultTypeInternal _Debug_AdjustBot_default_instance_
Definition at line 26 of file sslDebug_Data.pb.cc.
Referenced by Debug_AdjustBot::internal_default_instance().
Debug_CircleDefaultTypeInternal _Debug_Circle_default_instance_
Definition at line 22 of file sslDebug_Data.pb.cc.
Referenced by Debug_Circle::internal_default_instance().
Debug_LineDefaultTypeInternal _Debug_Line_default_instance_
Definition at line 24 of file sslDebug_Data.pb.cc.
Referenced by Debug_Line::internal_default_instance().
sslDebug_DataDefaultTypeInternal _sslDebug_Data_default_instance_
Definition at line 20 of file sslDebug_Data.pb.cc.
Referenced by sslDebug_Data::internal_default_instance().
const ::google::protobuf::internal::DefaultInstanceData file_default_instances[] static
Initial value:
= {
  {reinterpret_cast<const ::google::protobuf::Message*>(&_sslDebug_Data_default_instance_), NULL},
  {reinterpret_cast<const ::google::protobuf::Message*>(&_Debug_Circle_default_instance_), NULL},
  {reinterpret_cast<const ::google::protobuf::Message*>(&_Debug_Line_default_instance_), NULL},
  {reinterpret_cast<const ::google::protobuf::Message*>(&_Debug_AdjustBot_default_instance_), NULL},
  {reinterpret_cast<const ::google::protobuf::Message*>(&_Debug_AdjustBall_default_instance_), NULL},
}
Definition at line 126 of file sslDebug_Data.pb.cc.
Referenced by anonymous_namespace{sslDebug_Data.pb.cc}::protobuf_AssignDescriptors().
const ::google::protobuf::internal::MigrationSchema schemas[] static
Initial value:
= {
  { 0, 9, sizeof(sslDebug_Data)},
  { 14, 22, sizeof(Debug_Circle)},
  { 26, 35, sizeof(Debug_Line)},
  { 40, 52, sizeof(Debug_AdjustBot)},
  { 60, 69, sizeof(Debug_AdjustBall)},
}
Definition at line 118 of file sslDebug_Data.pb.cc.
Referenced by anonymous_namespace{sslDebug_Data.pb.cc}::protobuf_AssignDescriptors().
struct StaticDescriptorInitializer_sslDebug_5fData_2eproto static_descriptor_initializer_sslDebug_5fData_2eproto_
Referenced by StaticDescriptorInitializer_sslDebug_5fData_2eproto::StaticDescriptorInitializer_sslDebug_5fData_2eproto().