Documentation: Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket Class Reference
Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket Class Reference
Data Structures
class Builder
Public Member Functions
SSL_WrapperPacket getDefaultInstanceForType ()
boolean hasDetection ()
MessagesRobocupSslDetection.SSL_DetectionFrame getDetection ()
MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getDetectionOrBuilder ()
boolean hasGeometry ()
MessagesRobocupSslGeometry.SSL_GeometryData getGeometry ()
MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder getGeometryOrBuilder ()
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static SSL_WrapperPacket getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslWrapper.SSL_WrapperPacket parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslWrapper.SSL_WrapperPacket parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (MessagesRobocupSslWrapper.SSL_WrapperPacket prototype)
Static Public Attributes
static final int DETECTION_FIELD_NUMBER = 1
static final int GEOMETRY_FIELD_NUMBER = 2
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
SSL_WrapperPacket (Builder builder)
SSL_WrapperPacket (boolean noInit)
void initFields ()
Private Attributes
int bitField0_
MessagesRobocupSslDetection.SSL_DetectionFrame detection_
MessagesRobocupSslGeometry.SSL_GeometryData geometry_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final SSL_WrapperPacket defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 24 of file MessagesRobocupSslWrapper.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.SSL_WrapperPacket (Builder builder) inline private
Definition at line 28 of file MessagesRobocupSslWrapper.java.
{
       super(builder);
     }
Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.SSL_WrapperPacket (boolean noInit) inline private
Definition at line 31 of file MessagesRobocupSslWrapper.java.
 {}
Member Function Documentation
static SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.getDefaultInstance () inline static
Definition at line 34 of file MessagesRobocupSslWrapper.java.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getDefaultInstanceForType(), and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom().
{
       return defaultInstance;
     }
SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.getDefaultInstanceForType () inline
Definition at line 38 of file MessagesRobocupSslWrapper.java.
{
       return defaultInstance;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.getDescriptor () inline static
Definition at line 43 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_descriptor.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getDescriptorForType().
{
       return MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_descriptor;
     }
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.getDetection () inline
Implements Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.
Definition at line 59 of file MessagesRobocupSslWrapper.java.
{
       return detection_;
     }
MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.getDetectionOrBuilder () inline
Implements Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.
Definition at line 62 of file MessagesRobocupSslWrapper.java.
{
       return detection_;
     }
MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.getGeometry () inline
Implements Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.
Definition at line 72 of file MessagesRobocupSslWrapper.java.
{
       return geometry_;
     }
MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.getGeometryOrBuilder () inline
Implements Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.
Definition at line 75 of file MessagesRobocupSslWrapper.java.
{
       return geometry_;
     }
int Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.getSerializedSize () inline
Definition at line 117 of file MessagesRobocupSslWrapper.java.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(1, detection_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(2, geometry_);
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
boolean Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.hasDetection () inline
Implements Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.
Definition at line 56 of file MessagesRobocupSslWrapper.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
boolean Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.hasGeometry () inline
Implements Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.
Definition at line 69 of file MessagesRobocupSslWrapper.java.
{
       return ((bitField0_ & 0x00000002) == 0x00000002);
     }
void Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.initFields () inline private
Definition at line 79 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance().
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.getGeometryFieldBuilder().
{
       detection_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
       geometry_ = MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance();
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.internalGetFieldAccessorTable () inline protected
Definition at line 48 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_fieldAccessorTable.
{
       return MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_fieldAccessorTable;
     }
final boolean Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.isInitialized () inline
Definition at line 84 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.getDetection(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.getGeometry(), Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.hasDetection(), and Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder.hasGeometry().
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (hasDetection()) {
         if (!getDetection().isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       if (hasGeometry()) {
         if (!getGeometry().isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.newBuilder () inline static
Definition at line 209 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.create().
 { return Builder.create(); }
static Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.newBuilder (MessagesRobocupSslWrapper.SSL_WrapperPacket prototype) inline static
Definition at line 211 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.newBuilderForType () inline
Definition at line 210 of file MessagesRobocupSslWrapper.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 217 of file MessagesRobocupSslWrapper.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 176 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 185 of file MessagesRobocupSslWrapper.java.
References Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 142 of file MessagesRobocupSslWrapper.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 147 of file MessagesRobocupSslWrapper.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 154 of file MessagesRobocupSslWrapper.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 158 of file MessagesRobocupSslWrapper.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 165 of file MessagesRobocupSslWrapper.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 169 of file MessagesRobocupSslWrapper.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 196 of file MessagesRobocupSslWrapper.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslWrapper.SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 201 of file MessagesRobocupSslWrapper.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.toBuilder () inline
Definition at line 214 of file MessagesRobocupSslWrapper.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 137 of file MessagesRobocupSslWrapper.java.
{
       return super.writeReplace();
     }
void Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 104 of file MessagesRobocupSslWrapper.java.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeMessage(1, detection_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         output.writeMessage(2, geometry_);
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
int Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.bitField0_ private
Definition at line 52 of file MessagesRobocupSslWrapper.java.
final SSL_WrapperPacket Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.defaultInstance static private
Definition at line 33 of file MessagesRobocupSslWrapper.java.
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.detection_ private
Definition at line 55 of file MessagesRobocupSslWrapper.java.
Referenced by Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.buildPartial().
final int Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.DETECTION_FIELD_NUMBER = 1 static
Definition at line 54 of file MessagesRobocupSslWrapper.java.
MessagesRobocupSslGeometry.SSL_GeometryData Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.geometry_ private
Definition at line 68 of file MessagesRobocupSslWrapper.java.
final int Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.GEOMETRY_FIELD_NUMBER = 2 static
Definition at line 67 of file MessagesRobocupSslWrapper.java.
byte Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.memoizedIsInitialized = -1 private
Definition at line 83 of file MessagesRobocupSslWrapper.java.
int Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.memoizedSerializedSize = -1 private
Definition at line 116 of file MessagesRobocupSslWrapper.java.
final long Protobuf.MessagesRobocupSslWrapper.SSL_WrapperPacket.serialVersionUID = 0L static private
Definition at line 135 of file MessagesRobocupSslWrapper.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslWrapper.java