Documentation: PluginFindBlobs Class Reference
PluginFindBlobs Class Reference
#include <plugin_find_blobs.h>
Public Member Functions
PluginFindBlobs (FrameBuffer *_buffer, YUVLUT *_lut, int _max_regions)
~PluginFindBlobs ()
virtual ProcessResult process (FrameData *data, RenderOptions *options)
virtual VarList * getSettings ()
virtual string getName ()
Public Member Functions inherited from VisionPlugin
VisionPlugin (FrameBuffer *_buffer)
virtual ~VisionPlugin ()
FrameBuffer * getFrameBuffer () const
this functions provides convenient access to the ring-buffer
void lock ()
void unlock ()
virtual bool isEnabled () const
virtual void setEnabled (bool enable)
virtual bool isVisualize () const
virtual void setVisualize (bool enable)
virtual bool isSharedAmongStacks () const
virtual void setSharedAmongStacks (bool enable)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual void postProcess (FrameData *data, RenderOptions *options)
virtual QWidget * getVisualizationWidget ()
virtual QWidget * getControlWidget ()
virtual void closeWidgets ()
virtual QList< QAction * > actions ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
void setTimeProcessing (double val)
void setTimePostProcessing (double val)
double getTimeProcessing ()
double getTimePostProcessing ()
Protected Attributes
YUVLUT * lut
int max_regions
VarList * _settings
VarInt * _v_min_blob_area
VarBool * _v_enable
Protected Attributes inherited from VisionPlugin
QMutex mutex
bool enabled
bool visualize
bool shared
FrameBuffer * buffer
double time_proc
double time_post
Additional Inherited Members
Public Slots inherited from VisionPlugin
void slotKeyPressEvent (QKeyEvent *event)
Detailed Description
Author
Stefan Zickler
Definition at line 30 of file plugin_find_blobs.h.
Constructor & Destructor Documentation
PluginFindBlobs::PluginFindBlobs (FrameBuffer * _buffer, YUVLUT * _lut, int _max_regions)
Definition at line 23 of file plugin_find_blobs.cpp.
References _settings, _v_enable, _v_min_blob_area, VarTypes::VarList::addChild(), lut, and max_regions.
  : VisionPlugin(_buffer)
 {
   lut=_lut;
   max_regions=_max_regions;
   _settings=new VarList("Blob Finding");
   _settings->addChild(_v_min_blob_area=new VarInt("min_blob_area", 5));
   _settings->addChild(_v_enable=new VarBool("enable", true));
 }
PluginFindBlobs::~PluginFindBlobs ()
Definition at line 36 of file plugin_find_blobs.cpp.
 {
 }
Member Function Documentation
string PluginFindBlobs::getName () virtual
Reimplemented from VisionPlugin.
Definition at line 98 of file plugin_find_blobs.cpp.
{
   return "FindBlobs";
 }
VarList * PluginFindBlobs::getSettings () virtual
Reimplemented from VisionPlugin.
Definition at line 94 of file plugin_find_blobs.cpp.
References _settings.
{
   return _settings;
 }
ProcessResult PluginFindBlobs::process (FrameData * data, RenderOptions * options) virtual
Reimplemented from VisionPlugin.
Definition at line 42 of file plugin_find_blobs.cpp.
References _v_enable, _v_min_blob_area, kalman_filter::color, CMVision::RegionProcessing::connectComponents(), CMVision::RegionProcessing::extractRegions(), FrameDataMap::get(), VarTypes::VarBoolVal::getBool(), LUT3D::getChannelCount(), CMVision::ColorRegionList::getColorRegionArrayPointer(), VarTypes::VarInt::getInt(), CMVision::RegionList::getMaxRegions(), CMVision::ColorRegionList::getNumColorRegions(), CMVision::RegionList::getUsedRegions(), velocity.pid_::i, FrameDataMap::insert(), lut, FrameData::map, max_regions, ProcessingFailed, ProcessingOk, CMVision::RegionLinkedList::reset(), CMVision::RegionProcessing::separateRegions(), CMVision::RegionList::setUsedRegions(), and CMVision::RegionProcessing::sortRegions().
{
   (void)options;
   CMVision::RegionList * reglist;
   if ((reglist=(CMVision::RegionList *)data->map.get("cmv_reglist")) == 0) {
     reglist=(CMVision::RegionList *)data->map.insert("cmv_reglist",new CMVision::RegionList(max_regions));
   }
   CMVision::ColorRegionList * colorlist;
   if ((colorlist=(CMVision::ColorRegionList *)data->map.get("cmv_colorlist")) == 0) {
     colorlist=(CMVision::ColorRegionList *)data->map.insert("cmv_colorlist",new CMVision::ColorRegionList(lut->getChannelCount()));
   }
   CMVision::RunList * runlist;
   if ((runlist=(CMVision::RunList *)data->map.get("cmv_runlist")) == 0) {
     printf("Blob finder: no runlength-encoded input list was found!\n");
     return ProcessingFailed;
   }
   if (_v_enable->getBool()==true) {
     //Connect the components of the runlength map:
     CMVision::RegionProcessing::connectComponents(runlist);
     //Extract Regions from runlength map:
     CMVision::RegionProcessing::extractRegions(reglist, runlist);
     if (reglist->getUsedRegions() == reglist->getMaxRegions()) {
       printf("Warning: extract regions exceeded maximum number of %d regions\n",reglist->getMaxRegions());
     }
     //Separate Regions by colors:
     int max_area = CMVision::RegionProcessing::separateRegions(colorlist, reglist, _v_min_blob_area->getInt());
     //Sort Regions:
     CMVision::RegionProcessing::sortRegions(colorlist,max_area);
   } else {
     //detect nothing.
     reglist->setUsedRegions(0);
     int num_colors=colorlist->getNumColorRegions();
     CMVision::RegionLinkedList * color=colorlist->getColorRegionArrayPointer();
     // clear out the region list head table
     for(int i=0; i<num_colors; i++){
       color[i].reset();
     }
   }
   return ProcessingOk;
 }
Field Documentation
VarList* PluginFindBlobs::_settings protected
Definition at line 36 of file plugin_find_blobs.h.
Referenced by getSettings(), and PluginFindBlobs().
VarBool* PluginFindBlobs::_v_enable protected
Definition at line 38 of file plugin_find_blobs.h.
Referenced by PluginFindBlobs(), and process().
VarInt* PluginFindBlobs::_v_min_blob_area protected
Definition at line 37 of file plugin_find_blobs.h.
Referenced by PluginFindBlobs(), and process().
YUVLUT* PluginFindBlobs::lut protected
Definition at line 33 of file plugin_find_blobs.h.
Referenced by PluginFindBlobs(), and process().
int PluginFindBlobs::max_regions protected
Definition at line 34 of file plugin_find_blobs.h.
Referenced by PluginFindBlobs(), and process().
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/plugin_find_blobs.h
ssl-vision/src/app/plugins/plugin_find_blobs.cpp