Documentation: Protobuf.GrSimCommands.grSim_Commands Class Reference
Protobuf.GrSimCommands.grSim_Commands Class Reference
Data Structures
class Builder
Public Member Functions
grSim_Commands getDefaultInstanceForType ()
boolean hasTimestamp ()
double getTimestamp ()
boolean hasIsteamyellow ()
boolean getIsteamyellow ()
java.util.List< GrSimCommands.grSim_Robot_Command > getRobotCommandsList ()
java.util.List<?extends GrSimCommands.grSim_Robot_CommandOrBuilder > getRobotCommandsOrBuilderList ()
int getRobotCommandsCount ()
GrSimCommands.grSim_Robot_Command getRobotCommands (int index)
GrSimCommands.grSim_Robot_CommandOrBuilder getRobotCommandsOrBuilder (int index)
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static grSim_Commands getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static GrSimCommands.grSim_Commands parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimCommands.grSim_Commands parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimCommands.grSim_Commands parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimCommands.grSim_Commands parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimCommands.grSim_Commands parseFrom (java.io.InputStream input) throws java.io.IOException
static GrSimCommands.grSim_Commands parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static GrSimCommands.grSim_Commands parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static GrSimCommands.grSim_Commands parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static GrSimCommands.grSim_Commands parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static GrSimCommands.grSim_Commands parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (GrSimCommands.grSim_Commands prototype)
Static Public Attributes
static final int TIMESTAMP_FIELD_NUMBER = 1
static final int ISTEAMYELLOW_FIELD_NUMBER = 2
static final int ROBOT_COMMANDS_FIELD_NUMBER = 3
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
grSim_Commands (Builder builder)
grSim_Commands (boolean noInit)
void initFields ()
Private Attributes
int bitField0_
double timestamp_
boolean isteamyellow_
java.util.List< GrSimCommands.grSim_Robot_Command > robotCommands_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final grSim_Commands defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 1060 of file GrSimCommands.java.
Constructor & Destructor Documentation
Protobuf.GrSimCommands.grSim_Commands.grSim_Commands (Builder builder) inline private
Definition at line 1064 of file GrSimCommands.java.
{
       super(builder);
     }
Protobuf.GrSimCommands.grSim_Commands.grSim_Commands (boolean noInit) inline private
Definition at line 1067 of file GrSimCommands.java.
 {}
Member Function Documentation
static grSim_Commands Protobuf.GrSimCommands.grSim_Commands.getDefaultInstance () inline static
Definition at line 1070 of file GrSimCommands.java.
Referenced by Protobuf.GrSimPacket.grSim_Packet.Builder.clear(), Protobuf.GrSimPacket.grSim_Packet.Builder.clearCommands(), Protobuf.GrSimCommands.grSim_Commands.Builder.getDefaultInstanceForType(), Protobuf.GrSimPacket.grSim_Packet.initFields(), Protobuf.GrSimPacket.grSim_Packet.Builder.mergeCommands(), and Protobuf.GrSimCommands.grSim_Commands.Builder.mergeFrom().
{
       return defaultInstance;
     }
grSim_Commands Protobuf.GrSimCommands.grSim_Commands.getDefaultInstanceForType () inline
Definition at line 1074 of file GrSimCommands.java.
{
       return defaultInstance;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimCommands.grSim_Commands.getDescriptor () inline static
Definition at line 1079 of file GrSimCommands.java.
References Protobuf.GrSimCommands.internal_static_grSim_Commands_descriptor.
Referenced by Protobuf.GrSimCommands.grSim_Commands.Builder.getDescriptorForType().
{
       return GrSimCommands.internal_static_grSim_Commands_descriptor;
     }
boolean Protobuf.GrSimCommands.grSim_Commands.getIsteamyellow () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1105 of file GrSimCommands.java.
{
       return isteamyellow_;
     }
GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Commands.getRobotCommands (int index) inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1122 of file GrSimCommands.java.
{
       return robotCommands_.get(index);
     }
int Protobuf.GrSimCommands.grSim_Commands.getRobotCommandsCount () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1119 of file GrSimCommands.java.
{
       return robotCommands_.size();
     }
java.util.List<GrSimCommands.grSim_Robot_Command> Protobuf.GrSimCommands.grSim_Commands.getRobotCommandsList () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1112 of file GrSimCommands.java.
{
       return robotCommands_;
     }
GrSimCommands.grSim_Robot_CommandOrBuilder Protobuf.GrSimCommands.grSim_Commands.getRobotCommandsOrBuilder (int index) inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1125 of file GrSimCommands.java.
                    {
       return robotCommands_.get(index);
     }
java.util.List<? extends GrSimCommands.grSim_Robot_CommandOrBuilder> Protobuf.GrSimCommands.grSim_Commands.getRobotCommandsOrBuilderList () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1116 of file GrSimCommands.java.
{
       return robotCommands_;
     }
int Protobuf.GrSimCommands.grSim_Commands.getSerializedSize () inline
Definition at line 1174 of file GrSimCommands.java.
References velocity.pid_.i.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeDoubleSize(1, timestamp_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         size += com.google.protobuf.CodedOutputStream
           .computeBoolSize(2, isteamyellow_);
       }
       for (int i = 0; i < robotCommands_.size(); i++) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(3, robotCommands_.get(i));
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
double Protobuf.GrSimCommands.grSim_Commands.getTimestamp () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1095 of file GrSimCommands.java.
{
       return timestamp_;
     }
boolean Protobuf.GrSimCommands.grSim_Commands.hasIsteamyellow () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1102 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000002) == 0x00000002);
     }
boolean Protobuf.GrSimCommands.grSim_Commands.hasTimestamp () inline
Implements Protobuf.GrSimCommands.grSim_CommandsOrBuilder.
Definition at line 1092 of file GrSimCommands.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
void Protobuf.GrSimCommands.grSim_Commands.initFields () inline private
Definition at line 1130 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Commands.Builder.getRobotCommandsFieldBuilder().
{
       timestamp_ = 0D;
       isteamyellow_ = false;
       robotCommands_ = java.util.Collections.emptyList();
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.GrSimCommands.grSim_Commands.internalGetFieldAccessorTable () inline protected
Definition at line 1084 of file GrSimCommands.java.
References Protobuf.GrSimCommands.internal_static_grSim_Commands_fieldAccessorTable.
{
       return GrSimCommands.internal_static_grSim_Commands_fieldAccessorTable;
     }
final boolean Protobuf.GrSimCommands.grSim_Commands.isInitialized () inline
Definition at line 1136 of file GrSimCommands.java.
References velocity.pid_.i.
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (!hasTimestamp()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasIsteamyellow()) {
         memoizedIsInitialized = 0;
         return false;
       }
       for (int i = 0; i < getRobotCommandsCount(); i++) {
         if (!getRobotCommands(i).isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.GrSimCommands.grSim_Commands.newBuilder () inline static
Definition at line 1270 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Commands.Builder.create().
Referenced by Protobuf.GrSimPacket.grSim_Packet.Builder.mergeCommands(), Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom(), and Client.Conection.send().
 { return Builder.create(); }
static Builder Protobuf.GrSimCommands.grSim_Commands.newBuilder (GrSimCommands.grSim_Commands prototype) inline static
Definition at line 1272 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Commands.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.GrSimCommands.grSim_Commands.newBuilderForType () inline
Definition at line 1271 of file GrSimCommands.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.GrSimCommands.grSim_Commands.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 1278 of file GrSimCommands.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 1237 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Commands.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1246 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Commands.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1203 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1208 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1215 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1219 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 1226 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1230 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 1257 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static GrSimCommands.grSim_Commands Protobuf.GrSimCommands.grSim_Commands.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1262 of file GrSimCommands.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.GrSimCommands.grSim_Commands.toBuilder () inline
Definition at line 1275 of file GrSimCommands.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.GrSimCommands.grSim_Commands.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 1198 of file GrSimCommands.java.
{
       return super.writeReplace();
     }
void Protobuf.GrSimCommands.grSim_Commands.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 1158 of file GrSimCommands.java.
References velocity.pid_.i.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeDouble(1, timestamp_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         output.writeBool(2, isteamyellow_);
       }
       for (int i = 0; i < robotCommands_.size(); i++) {
         output.writeMessage(3, robotCommands_.get(i));
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
int Protobuf.GrSimCommands.grSim_Commands.bitField0_ private
Definition at line 1088 of file GrSimCommands.java.
final grSim_Commands Protobuf.GrSimCommands.grSim_Commands.defaultInstance static private
Definition at line 1069 of file GrSimCommands.java.
boolean Protobuf.GrSimCommands.grSim_Commands.isteamyellow_ private
Definition at line 1101 of file GrSimCommands.java.
final int Protobuf.GrSimCommands.grSim_Commands.ISTEAMYELLOW_FIELD_NUMBER = 2 static
Definition at line 1100 of file GrSimCommands.java.
byte Protobuf.GrSimCommands.grSim_Commands.memoizedIsInitialized = -1 private
Definition at line 1135 of file GrSimCommands.java.
int Protobuf.GrSimCommands.grSim_Commands.memoizedSerializedSize = -1 private
Definition at line 1173 of file GrSimCommands.java.
final int Protobuf.GrSimCommands.grSim_Commands.ROBOT_COMMANDS_FIELD_NUMBER = 3 static
Definition at line 1110 of file GrSimCommands.java.
java.util.List<GrSimCommands.grSim_Robot_Command> Protobuf.GrSimCommands.grSim_Commands.robotCommands_ private
Definition at line 1111 of file GrSimCommands.java.
final long Protobuf.GrSimCommands.grSim_Commands.serialVersionUID = 0L static private
Definition at line 1196 of file GrSimCommands.java.
double Protobuf.GrSimCommands.grSim_Commands.timestamp_ private
Definition at line 1091 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Commands.Builder.buildPartial().
final int Protobuf.GrSimCommands.grSim_Commands.TIMESTAMP_FIELD_NUMBER = 1 static
Definition at line 1090 of file GrSimCommands.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimCommands.java