Documentation: VarTypes::VarItemDelegate Class Reference
VarTypes::VarItemDelegate Class Reference
The 'item-delegate' inheriting QItemDelegate for displaying VarTypes in the QT4 Item-Model.
#include <VarItemDelegate.h>
Public Slots
void editorChangeEvent ()
Public Member Functions
VarItemDelegate (QObject *parent=0)
virtual ~VarItemDelegate ()
Protected Member Functions
virtual void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void drawBar (VarType *dt, QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const
void setEditorData (QWidget *editor, const QModelIndex &index) const
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const
void updateEditorGeometry (QWidget *editor, const QStyleOptionViewItem &option, const QModelIndex &index) const
Detailed Description
The 'item-delegate' inheriting QItemDelegate for displaying VarTypes in the QT4 Item-Model.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
This file is part of the QT4 Item-Model for VarTypes. It is used when you want to edit/visualize VarTypes using QT4's model/view system.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 49 of file VarItemDelegate.h.
Constructor & Destructor Documentation
VarTypes::VarItemDelegate::VarItemDelegate (QObject * parent = 0)
Definition at line 23 of file VarItemDelegate.cpp.
                                                   : QItemDelegate(parent)
   {
   }
VarTypes::VarItemDelegate::~VarItemDelegate () virtual
Definition at line 27 of file VarItemDelegate.cpp.
   {
   }
Member Function Documentation
QWidget * VarTypes::VarItemDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const protected
Definition at line 115 of file VarItemDelegate.cpp.
References VarTypes::VarType::createEditor(), velocity.pid::dt, and VarTypes::VarItem::getVarType().
{
     (void)option;
     if (index.isValid() && index.model()!=0) {
       VarItem * item=(VarItem*)(((VarTreeModel*)index.model())->itemFromIndex (index));
           if (item!=0) {
         VarType * dt=item->getVarType();
         if (dt!=0) {
           QWidget * w;
           w=dt->createEditor(this,parent,option);
           //if ((dt->getFlags() & VARTYPE_FLAG_PERSISTENT) != 0x00) w->setFocusPolicy(Qt::NoFocus);
           return w;
         }
       }
     }
     return 0;
   }
void VarTypes::VarItemDelegate::drawBar (VarType * dt, QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const protected virtual
Definition at line 60 of file VarItemDelegate.cpp.
References bot_comm::frame, VarTypes::VarVal::getMaxValue(), VarTypes::VarVal::getMinValue(), VarTypes::VarVal::getType(), VarTypes::VarVal::getValue(), VarTypes::VarVal::hasMaxValue(), VarTypes::VarVal::hasMinValue(), VarTypes::VarVal::hasValue(), and VarTypes::VARTYPE_ID_BOOL.
Referenced by paint().
{
     (void)index;
     //  QItemDelegate::drawBackground(painter,option,index);
     if (dt!=0) {
       if (dt->getType() != VARTYPE_ID_BOOL && dt->hasValue() && dt->hasMinValue() && dt->hasMaxValue()) {
         painter->save();
         QRectF rect=option.rect;
         double border_x=2.0;
         double width=rect.width()-(border_x*2.0);
         if (width < 0.0) width=0.0;
         rect.setX(rect.x()+border_x);
         rect.setWidth(width);
         double range=dt->getMaxValue() - dt->getMinValue();
         double value=dt->getValue()-dt->getMinValue();
         double pos=0.0;
         if (range!=0.0) pos=(value/range)*width;
         if (pos < 0.0) pos=0.0;
         if (pos > width) pos=width;
         QRectF bar=rect;
         double height=2;
         bar.setY(bar.y()+(bar.height() - (height + 1)));
         bar.setHeight(height);
         QRectF frame=bar;
         bar.setWidth(pos);
         QColor high_c;
         if (option.state & QStyle::State_Selected) {
           high_c=option.palette.color(QPalette::HighlightedText);
         } else {
           high_c=option.palette.color(QPalette::Highlight);
         }
         high_c.setAlpha(96);
         //painter->setPen(QPen(high_c,1));
         //painter->setBrush(Qt::NoBrush);
         painter->setPen(Qt::NoPen);
         painter->setBrush(QBrush(high_c));
         painter->drawRect(frame);
         high_c.setAlpha(192);
         QColor nocolor(255,255,255,0) ;
         painter->setPen(Qt::NoPen);
         painter->setBrush(QBrush(high_c));
         painter->drawRect(bar);
         painter->restore();
       }
     }
   }
void VarTypes::VarItemDelegate::editorChangeEvent () slot
Definition at line 31 of file VarItemDelegate.cpp.
{
     emit(commitData((QWidget *)sender()));
   }
void VarTypes::VarItemDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const protected virtual
Definition at line 35 of file VarItemDelegate.cpp.
References drawBar(), velocity.pid::dt, VarTypes::VarItem::getColFlags(), VarTypes::VarItem::getVarType(), VarTypes::GUI_COLUMN_FLAG_RANGEBARS, and VarTypes::VarType::paint().
{
     if (index.isValid() && index.model()!=0) {
       VarItem * item=(VarItem*)(((VarTreeModel*)index.model())->itemFromIndex (index));
       if (item!=0) {
         VarType * dt=item->getVarType();
         if (dt!=0) {
           /*if ((dt->getFlags() & VARTYPE_FLAG_PERSISTENT) != 0x00) {
             //there's a persistent editor on top!
             //don't draw anything!
             return;
           }*/
           dt->paint(this,painter,option,index);
           if ((item->getColFlags() & (GUI_COLUMN_FLAG_RANGEBARS)) != 0) {
             drawBar(dt,painter,option,index);
           }
           return;
         }
       }
     }
     QItemDelegate::paint(painter,option,index);
   }
void VarTypes::VarItemDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const protected
Definition at line 133 of file VarItemDelegate.cpp.
References velocity.pid::dt, VarTypes::VarType::getFlags(), VarTypes::VarItem::getVarType(), VarTypes::VarType::setEditorData(), and VarTypes::VARTYPE_FLAG_READONLY.
{
     if (editor==0) return;
     if (index.isValid() && index.model()!=0) {
       VarItem * item=(VarItem*)(((VarTreeModel*)index.model())->itemFromIndex (index));
       if (item!=0) {
         VarType * dt=item->getVarType();
         if (dt!=0) {
           //printf("Setting Editor for: %s\n",dt->getName().c_str());
           if (editor!=0 && ((dt->getFlags() & VARTYPE_FLAG_READONLY) != 0x00)) {
             editor->setEnabled(false);
           } else {
             editor->setEnabled(true);
           }
           dt->setEditorData(this,editor);
           //added on 3/27/09....return if we are done.
           return;
         }
       }
     }
     QItemDelegate::setEditorData(editor,index);
   }
void VarTypes::VarItemDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const protected
Definition at line 175 of file VarItemDelegate.cpp.
References velocity.pid::dt, VarTypes::VarItem::getVarType(), and VarTypes::VarType::setModelData().
{
     if (editor==0) return;
     if (index.isValid() && model!=0) {
       VarItem * item=(VarItem*)(((VarTreeModel*)model)->itemFromIndex (index));
       if (item!=0) {
         VarType * dt=item->getVarType();
         if (dt!=0) {
           dt->setModelData(this,editor);
           return;
         }
       }
     }
     QItemDelegate::setModelData(editor,model,index);
   }
QSize VarTypes::VarItemDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const protected virtual
Definition at line 155 of file VarItemDelegate.cpp.
References velocity.pid::dt, and VarTypes::VarType::sizeHint().
{
     if (index.isValid() && index.model()!=0) {
       if ((index.row() >= 0) && (index.column() >= 0)) {
         QStandardItem *parent = static_cast<QStandardItem*>(index.internalPointer());
         if (parent != 0) {
           QStandardItem *item = parent->child(index.row(), index.column());
           if (item!=0) {
             VarType * dt=((VarItem*)item)->getVarType();
             if (dt!=0) {
               return dt->sizeHint(this,option,index);
             }
           }
         }
       }
     }
     return QItemDelegate::sizeHint(option,index);
   }
void VarTypes::VarItemDelegate::updateEditorGeometry (QWidget * editor, const QStyleOptionViewItem & option, const QModelIndex & index) const protected
Definition at line 191 of file VarItemDelegate.cpp.
{
     QItemDelegate::updateEditorGeometry(editor,option,index);
   }
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/gui/VarItemDelegate.h
ssl-vision/src/shared/vartypes/gui/VarItemDelegate.cpp