Documentation: Debug_AdjustBall Class Reference
Debug_AdjustBall Class Reference
#include <sslDebug_Data.pb.h>
Public Member Functions
Debug_AdjustBall ()
virtual ~Debug_AdjustBall ()
Debug_AdjustBall (const Debug_AdjustBall &from)
Debug_AdjustBall & operator= (const Debug_AdjustBall &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Debug_AdjustBall *other)
Debug_AdjustBall * New () const PROTOBUF_FINAL
Debug_AdjustBall * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const Debug_AdjustBall &from)
void MergeFrom (const Debug_AdjustBall &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_x () const
void clear_x ()
::google::protobuf::int32 x () const
void set_x (::google::protobuf::int32 value)
bool has_y () const
void clear_y ()
::google::protobuf::int32 y () const
void set_y (::google::protobuf::int32 value)
bool has_vx () const
void clear_vx ()
::google::protobuf::int32 vx () const
void set_vx (::google::protobuf::int32 value)
bool has_vy () const
void clear_vy ()
::google::protobuf::int32 vy () const
void set_vy (::google::protobuf::int32 value)
bool has_vz () const
void clear_vz ()
::google::protobuf::uint32 vz () const
void set_vz (::google::protobuf::uint32 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Debug_AdjustBall & default_instance ()
static const Debug_AdjustBall * internal_default_instance ()
Static Public Attributes
static const int kXFieldNumber = 1
static const int kYFieldNumber = 2
static const int kVxFieldNumber = 3
static const int kVyFieldNumber = 4
static const int kVzFieldNumber = 5
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (Debug_AdjustBall *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_x ()
void clear_has_x ()
void set_has_y ()
void clear_has_y ()
void set_has_vx ()
void clear_has_vx ()
void set_has_vy ()
void clear_has_vy ()
void set_has_vz ()
void clear_has_vz ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_sslDebug_5fData_2eproto ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::int32 x_
::google::protobuf::int32 y_
::google::protobuf::int32 vx_
::google::protobuf::int32 vy_
::google::protobuf::uint32 vz_
Friends
void protobuf_InitDefaults_sslDebug_5fData_2eproto_impl ()
void protobuf_AddDesc_sslDebug_5fData_2eproto_impl ()
void protobuf_ShutdownFile_sslDebug_5fData_2eproto ()
Detailed Description
Definition at line 654 of file sslDebug_Data.pb.h.
Constructor & Destructor Documentation
Debug_AdjustBall::Debug_AdjustBall ()
virtual Debug_AdjustBall::~Debug_AdjustBall () virtual
Debug_AdjustBall::Debug_AdjustBall (const Debug_AdjustBall & from)
Member Function Documentation
size_t Debug_AdjustBall::ByteSizeLong () const
void Debug_AdjustBall::Clear ()
void Debug_AdjustBall::clear_has_vx () inline private
Definition at line 1462 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000004u;
 }
void Debug_AdjustBall::clear_has_vy () inline private
Definition at line 1486 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000008u;
 }
void Debug_AdjustBall::clear_has_vz () inline private
Definition at line 1510 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000010u;
 }
void Debug_AdjustBall::clear_has_x () inline private
Definition at line 1414 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void Debug_AdjustBall::clear_has_y () inline private
Definition at line 1438 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] &= ~0x00000002u;
 }
void Debug_AdjustBall::clear_vx () inline
Definition at line 1465 of file sslDebug_Data.pb.h.
{
   vx_ = 0;
   clear_has_vx();
 }
void Debug_AdjustBall::clear_vy () inline
Definition at line 1489 of file sslDebug_Data.pb.h.
{
   vy_ = 0;
   clear_has_vy();
 }
void Debug_AdjustBall::clear_vz () inline
Definition at line 1513 of file sslDebug_Data.pb.h.
{
   vz_ = 0u;
   clear_has_vz();
 }
void Debug_AdjustBall::clear_x () inline
Definition at line 1417 of file sslDebug_Data.pb.h.
{
   x_ = 0;
   clear_has_x();
 }
void Debug_AdjustBall::clear_y () inline
Definition at line 1441 of file sslDebug_Data.pb.h.
{
   y_ = 0;
   clear_has_y();
 }
void Debug_AdjustBall::CopyFrom (const ::google::protobuf::Message & from)
void Debug_AdjustBall::CopyFrom (const Debug_AdjustBall & from)
static const Debug_AdjustBall& Debug_AdjustBall::default_instance () static
static const ::google::protobuf::Descriptor* Debug_AdjustBall::descriptor () static
inline ::google::protobuf::Arena* Debug_AdjustBall::GetArenaNoVirtual () const inline private
Definition at line 714 of file sslDebug_Data.pb.h.
{
     return NULL;
   }
int Debug_AdjustBall::GetCachedSize () const inline
Definition at line 707 of file sslDebug_Data.pb.h.
References sslDebug_Data::_cached_size_, sslDebug_Data::InternalSwap(), sslDebug_Data::SetCachedSize(), sslDebug_Data::SharedCtor(), and sslDebug_Data::SharedDtor().
 { return _cached_size_; }
::google::protobuf::Metadata Debug_AdjustBall::GetMetadata () const
bool Debug_AdjustBall::has_vx () const inline
Definition at line 1456 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool Debug_AdjustBall::has_vy () const inline
Definition at line 1480 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool Debug_AdjustBall::has_vz () const inline
Definition at line 1504 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
bool Debug_AdjustBall::has_x () const inline
Definition at line 1408 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool Debug_AdjustBall::has_y () const inline
Definition at line 1432 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
static const Debug_AdjustBall* Debug_AdjustBall::internal_default_instance () inline static
Definition at line 677 of file sslDebug_Data.pb.h.
References _Debug_AdjustBall_default_instance_, and sslDebug_Data::Swap().
{
     return reinterpret_cast<const Debug_AdjustBall*>(
                &_Debug_AdjustBall_default_instance_);
   }
::google::protobuf::uint8* Debug_AdjustBall::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void Debug_AdjustBall::InternalSwap (Debug_AdjustBall * other) private
bool Debug_AdjustBall::IsInitialized () const
void* Debug_AdjustBall::MaybeArenaPtr () const inline private
Definition at line 717 of file sslDebug_Data.pb.h.
References sslDebug_Data::GetMetadata().
{
     return NULL;
   }
void Debug_AdjustBall::MergeFrom (const ::google::protobuf::Message & from)
void Debug_AdjustBall::MergeFrom (const Debug_AdjustBall & from)
bool Debug_AdjustBall::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
inline ::google::protobuf::UnknownFieldSet* Debug_AdjustBall::mutable_unknown_fields () inline
Definition at line 670 of file sslDebug_Data.pb.h.
References sslDebug_Data::_internal_metadata_, sslDebug_Data::default_instance(), and sslDebug_Data::descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
Debug_AdjustBall* Debug_AdjustBall::New () const inline
Definition at line 686 of file sslDebug_Data.pb.h.
References sslDebug_Data::ByteSizeLong(), sslDebug_Data::Clear(), sslDebug_Data::CopyFrom(), sslDebug_Data::InternalSerializeWithCachedSizesToArray(), sslDebug_Data::IsInitialized(), sslDebug_Data::MergeFrom(), sslDebug_Data::MergePartialFromCodedStream(), sslDebug_Data::New(), New(), sslDebug_Data::SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
Debug_AdjustBall* Debug_AdjustBall::New (::google::protobuf::Arena * arena) const
Debug_AdjustBall& Debug_AdjustBall::operator= (const Debug_AdjustBall & from) inline
Definition at line 661 of file sslDebug_Data.pb.h.
References sslDebug_Data::CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* Debug_AdjustBall::protobuf_Offsets_sslDebug_5fData_2eproto () private
size_t Debug_AdjustBall::RequiredFieldsByteSizeFallback () const private
void Debug_AdjustBall::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* Debug_AdjustBall::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 703 of file sslDebug_Data.pb.h.
References sslDebug_Data::InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void Debug_AdjustBall::set_has_vx () inline private
Definition at line 1459 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000004u;
 }
void Debug_AdjustBall::set_has_vy () inline private
Definition at line 1483 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000008u;
 }
void Debug_AdjustBall::set_has_vz () inline private
Definition at line 1507 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000010u;
 }
void Debug_AdjustBall::set_has_x () inline private
Definition at line 1411 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000001u;
 }
void Debug_AdjustBall::set_has_y () inline private
Definition at line 1435 of file sslDebug_Data.pb.h.
References sslDebug_Data::_has_bits_.
{
   _has_bits_[0] |= 0x00000002u;
 }
void Debug_AdjustBall::set_vx (::google::protobuf::int32 value) inline
Definition at line 1473 of file sslDebug_Data.pb.h.
{
   set_has_vx();
   vx_ = value;
   // @@protoc_insertion_point(field_set:Debug_AdjustBall.vx)
 }
void Debug_AdjustBall::set_vy (::google::protobuf::int32 value) inline
Definition at line 1497 of file sslDebug_Data.pb.h.
{
   set_has_vy();
   vy_ = value;
   // @@protoc_insertion_point(field_set:Debug_AdjustBall.vy)
 }
void Debug_AdjustBall::set_vz (::google::protobuf::uint32 value) inline
Definition at line 1521 of file sslDebug_Data.pb.h.
{
   set_has_vz();
   vz_ = value;
   // @@protoc_insertion_point(field_set:Debug_AdjustBall.vz)
 }
void Debug_AdjustBall::set_x (::google::protobuf::int32 value) inline
Definition at line 1425 of file sslDebug_Data.pb.h.
{
   set_has_x();
   x_ = value;
   // @@protoc_insertion_point(field_set:Debug_AdjustBall.x)
 }
void Debug_AdjustBall::set_y (::google::protobuf::int32 value) inline
Definition at line 1449 of file sslDebug_Data.pb.h.
{
   set_has_y();
   y_ = value;
   // @@protoc_insertion_point(field_set:Debug_AdjustBall.y)
 }
void Debug_AdjustBall::SetCachedSize (int size) const private
void Debug_AdjustBall::SharedCtor () private
void Debug_AdjustBall::SharedDtor () private
void Debug_AdjustBall::Swap (Debug_AdjustBall * other)
const ::google::protobuf::UnknownFieldSet& Debug_AdjustBall::unknown_fields () const inline
Definition at line 666 of file sslDebug_Data.pb.h.
References sslDebug_Data::_internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
google::protobuf::int32 Debug_AdjustBall::vx () const inline
Definition at line 1469 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_AdjustBall.vx)
   return vx_;
 }
google::protobuf::int32 Debug_AdjustBall::vy () const inline
Definition at line 1493 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_AdjustBall.vy)
   return vy_;
 }
google::protobuf::uint32 Debug_AdjustBall::vz () const inline
Definition at line 1517 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_AdjustBall.vz)
   return vz_;
 }
google::protobuf::int32 Debug_AdjustBall::x () const inline
Definition at line 1421 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_AdjustBall.x)
   return x_;
 }
google::protobuf::int32 Debug_AdjustBall::y () const inline
Definition at line 1445 of file sslDebug_Data.pb.h.
{
   // @@protoc_insertion_point(field_get:Debug_AdjustBall.y)
   return y_;
 }
Friends And Related Function Documentation
void protobuf_AddDesc_sslDebug_5fData_2eproto_impl () friend
void protobuf_InitDefaults_sslDebug_5fData_2eproto_impl () friend
void protobuf_ShutdownFile_sslDebug_5fData_2eproto () friend
Field Documentation
int Debug_AdjustBall::_cached_size_ mutable private
Definition at line 781 of file sslDebug_Data.pb.h.
::google::protobuf::internal::HasBits<1> Debug_AdjustBall::_has_bits_ private
Definition at line 780 of file sslDebug_Data.pb.h.
::google::protobuf::internal::InternalMetadataWithArena Debug_AdjustBall::_internal_metadata_ private
Definition at line 779 of file sslDebug_Data.pb.h.
const int Debug_AdjustBall::kVxFieldNumber = 3 static
Definition at line 745 of file sslDebug_Data.pb.h.
const int Debug_AdjustBall::kVyFieldNumber = 4 static
Definition at line 752 of file sslDebug_Data.pb.h.
const int Debug_AdjustBall::kVzFieldNumber = 5 static
Definition at line 759 of file sslDebug_Data.pb.h.
const int Debug_AdjustBall::kXFieldNumber = 1 static
Definition at line 731 of file sslDebug_Data.pb.h.
const int Debug_AdjustBall::kYFieldNumber = 2 static
Definition at line 738 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_AdjustBall::vx_ private
Definition at line 784 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_AdjustBall::vy_ private
Definition at line 785 of file sslDebug_Data.pb.h.
::google::protobuf::uint32 Debug_AdjustBall::vz_ private
Definition at line 786 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_AdjustBall::x_ private
Definition at line 782 of file sslDebug_Data.pb.h.
::google::protobuf::int32 Debug_AdjustBall::y_ private
Definition at line 783 of file sslDebug_Data.pb.h.
The documentation for this class was generated from the following file:
grsim_comm/include/proto/sslDebug_Data.pb.h