Documentation: Quaternion< num > Class Template Reference
Quaternion< num > Class Template Reference
A Quaternion class.
#include <quaternion.h>
Public Member Functions
Quaternion ()
Quaternion (const Quaternion< num > &q)
Quaternion (num qx, num qy, num qz, num qw)
~Quaternion ()
void operator= (const Quaternion< num > &q)
void operator*= (const Quaternion< num > &q)
void operator*= (const GVector::vector3d< num > &v)
bool operator== (const Quaternion< num > &rhs) const
bool operator!= (const Quaternion< num > &rhs) const
void norm ()
void blend (num d, const Quaternion< num > &q)
void clear ()
void conjugate ()
void invert ()
void set (num qx, num qy, num qz, num qw)
void setAxis (const GVector::vector3d< num > &v, num angle)
GVector::vector3d< num > getZvector ()
GVector::vector3d< num > rotateVectorByQuaternion (const GVector::vector3d< num > v) const
void getMatrix (num *m) const
void getAxisAngle (GVector::vector3d< num > &axis, num &angle)
num getAngle ()
void setEuler (num pitch, num yaw, num roll)
double getYaw ()
double getPitch ()
double getRoll ()
void getEuler (num &pitch, num &yaw, num &roll)
Data Fields
num x
num y
num z
num w
Detailed Description
template<class num>
class Quaternion< num >
A Quaternion class.
Author
Stefan Zickler, (C) 2007 Some parts of this class were ported from the Cal3D library which is released under GPL. Some other parts taken from public domain listed here: http://gpwiki.org/index.php/OpenGL:Tutorials:Using_Quaternions_to_represent_rotation and here: http://www.euclideanspace.com/maths/geometry/rotations/conversions/eulerToQuaternion/index.htm
Definition at line 44 of file quaternion.h.
Constructor & Destructor Documentation
template<class num> Quaternion< num >::Quaternion () inline
Definition at line 54 of file quaternion.h.
 : x(0.0f), y(0.0f), z(0.0f), w(1.0f){};
template<class num> Quaternion< num >::Quaternion (const Quaternion< num > & q) inline
Definition at line 55 of file quaternion.h.
 : x(q.x), y(q.y), z(q.z), w(q.w) {};
template<class num> Quaternion< num >::Quaternion (num qx, num qy, num qz, num qw) inline
Definition at line 56 of file quaternion.h.
 : x(qx), y(qy), z(qz), w(qw) {};
template<class num> Quaternion< num >::~Quaternion () inline
Definition at line 57 of file quaternion.h.
 {};
Member Function Documentation
template<class num> void Quaternion< num >::blend (num d, const Quaternion< num > & q) inline
Definition at line 126 of file quaternion.h.
Referenced by GLSmoothCamera::step().
   {
     num norm;
     norm = x * q.x + y * q.y + z * q.z + w * q.w;
     bool bFlip;
     bFlip = false;
     if(norm < 0.0f) {
       norm = -norm;
       bFlip = true;
     }
     num inv_d;
     if(1.0f - norm < 0.000001f) {
       inv_d = 1.0f - d;
     } else {
       num theta;
       theta = (num) acos(norm);
       num s;
       s = (num) (1.0f / sin(theta));
       inv_d = (num) sin((1.0f - d) * theta) * s;
       d = (num) sin(d * theta) * s;
     }
     if(bFlip) {
       d = -d;
     }
     x = inv_d * x + d * q.x;
     y = inv_d * y + d * q.y;
     z = inv_d * z + d * q.z;
     w = inv_d * w + d * q.w;
   }
template<class num> void Quaternion< num >::clear () inline
Definition at line 164 of file quaternion.h.
Referenced by GLObject::reset(), and GLCamera::reset().
   {
     x = 0.0f;
     y = 0.0f;
     z = 0.0f;
     w = 1.0f;
   }
template<class num> void Quaternion< num >::conjugate () inline
Definition at line 171 of file quaternion.h.
Referenced by Quaternion< double >::invert().
   {
     x = -x;
     y = -y;
     z = -z;
   }
template<class num> num Quaternion< num >::getAngle () inline
Definition at line 286 of file quaternion.h.
   {
     return acos(w) * 2.0f;
   }
template<class num> void Quaternion< num >::getAxisAngle (GVector::vector3d< num > & axis, num & angle) inline
Definition at line 277 of file quaternion.h.
   {
     num scale = sqrt(x * x + y * y + z * z);
     axis.x = x / scale;
     axis.y = y / scale;
     axis.z = z / scale;
     angle = acos(w) * 2.0f;
   }
template<class num> void Quaternion< num >::getEuler (num & pitch, num & yaw, num & roll) inline
Definition at line 338 of file quaternion.h.
Referenced by GLCamera::getEuler().
{
     pitch=getPitch();
     yaw=getYaw();
     roll=getRoll();
   }
template<class num> void Quaternion< num >::getMatrix (num * m) const inline
Definition at line 249 of file quaternion.h.
Referenced by GLObject::preRender(), and GLCamera::preRender().
   {
     num x2 = x * x;
     num y2 = y * y;
     num z2 = z * z;
     num xy = x * y;
     num xz = x * z;
     num yz = y * z;
     num wx = w * x;
     num wy = w * y;
     num wz = w * z;
     // This calculation would be a lot more complicated for non-unit length quaternions
     // Note: The constructor of Matrix4 expects the Matrix in column-major format like expected by
     //   OpenGL
     m[0]= 1.0f - 2.0f * (y2 + z2); m[1]= 2.0f * (xy - wz);        m[2]= 2.0f * (xz + wy);         m[3]=0.0f;
     m[4]= 2.0f * (xy + wz);        m[5]= 1.0f - 2.0f * (x2 + z2); m[6]= 2.0f * (yz - wx);         m[7]=0.0f;
     m[8]= 2.0f * (xz - wy);        m[9]= 2.0f * (yz + wx);        m[10]= 1.0f - 2.0f * (x2 + y2); m[11]=0.0f;
     m[12]=0.0f;                    m[13]=0.0f;                    m[14]= 0.0f;                    m[15]=1.0f;
      /*1.0f - 2.0f * (y2 + z2), 2.0f * (xy - wz), 2.0f * (xz + wy), 0.0f,
                     2.0f * (xy + wz), 1.0f - 2.0f * (x2 + z2), 2.0f * (yz - wx), 0.0f,
                     2.0f * (xz - wy), 2.0f * (yz + wx), 1.0f - 2.0f * (x2 + y2), 0.0f,
                     0.0f, 0.0f, 0.0f, 1.0f};*/
   }
template<class num> double Quaternion< num >::getPitch () inline
Definition at line 324 of file quaternion.h.
Referenced by Quaternion< double >::getEuler(), GLCamera::getPitch(), GLCamera::setRoll(), and GLCamera::setYaw().
                            { //bank
     if (fabs((x*y + z*w) - 0.5) <  0.000001f) { //it's north pole
         return 0.0;
     }
     if (fabs((x*y + z*w) + 0.5) <  0.000001f) { //it's south pole
       return 0.0;
     }
     return atan2(2*x*w-2*y*z , 1 - 2*(x*x) - 2*(z*z));
   }
template<class num> double Quaternion< num >::getRoll () inline
Definition at line 334 of file quaternion.h.
Referenced by Quaternion< double >::getEuler(), GLCamera::getRoll(), GLCamera::setPitch(), and GLCamera::setYaw().
                           { //attitude
       return asin(2*x*y + 2*z*w);
   }
template<class num> double Quaternion< num >::getYaw () inline
Definition at line 313 of file quaternion.h.
Referenced by Quaternion< double >::getEuler(), GLCamera::getYaw(), GLCamera::setPitch(), and GLCamera::setRoll().
                          { //heading
     if (fabs((x*y + z*w) - 0.5) <  0.000001f) { //it's north pole
         return 2 * atan2(x,w);
     }
     if (fabs((x*y + z*w) + 0.5) <  0.000001f) { //it's south pole
       return -2 * atan2(x,w);
     }
     return atan2(2* y*w-2*x*z , 1 - 2*(y*y) - 2*(z*z));
   }
template<class num> GVector::vector3d<num> Quaternion< num >::getZvector () inline
Definition at line 224 of file quaternion.h.
Referenced by GLSmoothCamera::step().
{
     GVector::vector3d<num> v;
     v.set(0.0,0.0,1.0);
     return(rotateVectorByQuaternion(v));
   }
template<class num> void Quaternion< num >::invert () inline
Definition at line 178 of file quaternion.h.
Referenced by GLCamera::freeLookAt(), CameraParameters::getWorldLocation(), and CameraParameters::toProtoBuffer().
   {
     conjugate();
     const num norm = (x*x) + (y*y) + (z*z) + (w*w);
     if (norm == 0.0f) return;
     const num inv_norm = 1 / norm;
     x *= inv_norm;
     y *= inv_norm;
     z *= inv_norm;
     w *= inv_norm;
   }
template<class num> void Quaternion< num >::norm () inline
Definition at line 111 of file quaternion.h.
Referenced by Quaternion< double >::blend(), CameraParameters::calibrate(), CameraParameters::field2image(), CameraParameters::image2field(), Quaternion< double >::invert(), and Quaternion< double >::setEuler().
   {
     // Don't normalize if we don't have to
     num mag2 = w * w + x * x + y * y + z * z;
     if (fabs(mag2 - 1.0f) > 0.000001f) {
             num mag = sqrt(mag2);
             if(mag!=0.0) {
             w /= mag;
             x /= mag;
             y /= mag;
             z /= mag;
             }
     }
   }
template<class num> bool Quaternion< num >::operator!= (const Quaternion< num > & rhs) const inline
Definition at line 106 of file quaternion.h.
   {
     return !operator==(rhs);
   }
template<class num> void Quaternion< num >::operator*= (const Quaternion< num > & q) inline
Definition at line 70 of file quaternion.h.
   {
     num qx, qy, qz, qw;
     qx = x;
     qy = y;
     qz = z;
     qw = w;
     x = qw * q.x + qx * q.w + qy * q.z - qz * q.y;
     y = qw * q.y - qx * q.z + qy * q.w + qz * q.x;
     z = qw * q.z + qx * q.y - qy * q.x + qz * q.w;
     w = qw * q.w - qx * q.x - qy * q.y - qz * q.z;
   }
template<class num> void Quaternion< num >::operator*= (const GVector::vector3d< num > & v) inline
Definition at line 84 of file quaternion.h.
   {
     num qx, qy, qz, qw;
     qx = x;
     qy = y;
     qz = z;
     qw = w;
     x = qw * v.x            + qy * v.z - qz * v.y;
     y = qw * v.y - qx * v.z            + qz * v.x;
     z = qw * v.z + qx * v.y - qy * v.x;
     w =          - qx * v.x - qy * v.y - qz * v.z;
   }
template<class num> void Quaternion< num >::operator= (const Quaternion< num > & q) inline
Definition at line 62 of file quaternion.h.
   {
     x = q.x;
     y = q.y;
     z = q.z;
     w = q.w;
   }
template<class num> bool Quaternion< num >::operator== (const Quaternion< num > & rhs) const inline
Definition at line 98 of file quaternion.h.
Referenced by Quaternion< double >::operator!=().
   {
     return x == rhs.x &&
            y == rhs.y &&
            z == rhs.z &&
            w == rhs.w;
   }
template<class num> GVector::vector3d<num> Quaternion< num >::rotateVectorByQuaternion (const GVector::vector3d< num > v) const inline
Definition at line 230 of file quaternion.h.
Referenced by CameraParameters::field2image(), GLCamera::getLensPosition(), CameraParameters::getWorldLocation(), Quaternion< double >::getZvector(), GLCamera::mouseAction(), and CameraParameters::toProtoBuffer().
{
     num x2 = x * x;
     num y2 = y * y;
     num z2 = z * z;
     num xy = x * y;
     num xz = x * z;
     num yz = y * z;
     num wx = w * x;
     num wy = w * y;
     num wz = w * z;
     GVector::vector3d<num> res;
     res.x= (1.0f - 2.0f * (y2 + z2)) * v.x +  (2.0f * (xy - wz))        * v.y +  (2.0f * (xz + wy))        * v.z;
     res.y= (2.0f * (xy + wz)) * v.x        +  (1.0f - 2.0f * (x2 + z2)) * v.y +  (2.0f * (yz - wx))        * v.z;
     res.z= (2.0f * (xz - wy)) * v.x        +  (2.0f * (yz + wx))        * v.y +  (1.0f - 2.0f * (x2 + y2)) * v.z;
     return res;
   }
template<class num> void Quaternion< num >::set (num qx, num qy, num qz, num qw) inline
Definition at line 192 of file quaternion.h.
Referenced by CameraParameters::getWorldLocation(), and CameraParameters::toProtoBuffer().
   {
     x = qx;
     y = qy;
     z = qz;
     w = qw;
   }
template<class num> void Quaternion< num >::setAxis (const GVector::vector3d< num > & v, num angle) inline
Definition at line 201 of file quaternion.h.
Referenced by CameraParameters::calibrate(), and CameraParameters::field2image().
   {
     if (angle != .0f) {
       num sinAngle;
       angle *= 0.5f;
       GVector::vector3d<num> vn(v);
       vn.normalize();
       sinAngle = sin(angle);
       x = (vn.x * sinAngle);
       y = (vn.y * sinAngle);
       z = (vn.z * sinAngle);
       w = cos(angle);
     }
     else {
       x = .0f;
       y = .0f;
       z = .0f;
       w = 1.f;
     }
   }
template<class num> void Quaternion< num >::setEuler (num pitch, num yaw, num roll) inline
Definition at line 291 of file quaternion.h.
Referenced by GLCamera::lookAt(), and GLCamera::setEuler().
   {
     // Basically we create 3 Quaternions, one for pitch, one for yaw, one for roll
     // and multiply those together.
     // the calculation below does the same, just shorter
     double c1 = cos(yaw/2);
     double s1 = sin(yaw/2);
     double c2 = cos(roll/2);
     double s2 = sin(roll/2);
     double c3 = cos(pitch/2);
     double s3 = sin(pitch/2);
     double c1c2 = c1*c2;
     double s1s2 = s1*s2;
     w =c1c2*c3 - s1s2*s3;
     x =c1c2*s3 + s1s2*c3;
     y =s1*c2*c3 + c1*s2*s3;
     z =c1*s2*c3 - s1*c2*s3;
     norm();
   }
Field Documentation
template<class num> num Quaternion< num >::w
Definition at line 50 of file quaternion.h.
Referenced by Quaternion< double >::blend(), operator*(), Quaternion< double >::operator*=(), Quaternion< double >::operator=(), and Quaternion< double >::operator==().
template<class num> num Quaternion< num >::x
Definition at line 47 of file quaternion.h.
Referenced by utils.geometry.Vector2D::__add__(), utils.geometry.Vector2D::__eq__(), utils.geometry.Vector2D::__mul__(), utils.geometry.Vector2D::__ne__(), utils.geometry.Vector2D::__sub__(), utils.geometry.Vector2D::__truediv__(), utils.geometry.Vector2D::angle(), Quaternion< double >::blend(), Quaternion< double >::conjugate(), utils.geometry.Vector2D::dist(), utils.geometry.Vector2D::distSq(), utils.geometry.Vector2D::dot(), Quaternion< double >::getMatrix(), Quaternion< double >::invert(), operator*(), Quaternion< double >::operator*=(), Quaternion< double >::operator=(), Quaternion< double >::operator==(), Quaternion< double >::rotateVectorByQuaternion(), and utils.geometry.Vector2D::valid().
template<class num> num Quaternion< num >::y
Definition at line 48 of file quaternion.h.
Referenced by utils.geometry.Vector2D::__add__(), utils.geometry.Vector2D::__eq__(), utils.geometry.Vector2D::__mul__(), utils.geometry.Vector2D::__ne__(), utils.geometry.Vector2D::__sub__(), utils.geometry.Vector2D::__truediv__(), utils.geometry.Vector2D::angle(), Quaternion< double >::blend(), Quaternion< double >::conjugate(), utils.geometry.Vector2D::dist(), utils.geometry.Vector2D::distSq(), utils.geometry.Vector2D::dot(), Quaternion< double >::getMatrix(), operator*(), Quaternion< double >::operator*=(), Quaternion< double >::operator=(), Quaternion< double >::operator==(), Quaternion< double >::rotateVectorByQuaternion(), and utils.geometry.Vector2D::valid().
template<class num> num Quaternion< num >::z
Definition at line 49 of file quaternion.h.
Referenced by Quaternion< double >::blend(), Quaternion< double >::conjugate(), Quaternion< double >::getMatrix(), Quaternion< double >::invert(), Quaternion< double >::norm(), operator*(), Quaternion< double >::operator*=(), Quaternion< double >::operator=(), Quaternion< double >::operator==(), and Quaternion< double >::rotateVectorByQuaternion().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/quaternion.h