Documentation: GlobalRandom Class Reference
GlobalRandom Class Reference
A singleton class to provide a single global instance of the Random class.
#include <global_random.h>
Static Public Member Functions
static Random * getInstance ()
Protected Member Functions
GlobalRandom ()
GlobalRandom (const GlobalRandom &)
GlobalRandom & operator= (const GlobalRandom &)
Private Attributes
Random * tool
Static Private Attributes
static GlobalRandom * pinstance = 0
Detailed Description
A singleton class to provide a single global instance of the Random class.
Author
Stefan Zickler, (C) 2008
Definition at line 31 of file global_random.h.
Constructor & Destructor Documentation
GlobalRandom::GlobalRandom () protected
Definition at line 35 of file global_random.cpp.
References Random::randomize(), and tool.
Referenced by getInstance().
 {
   tool = new Random();
   tool->randomize();
 }
GlobalRandom::GlobalRandom (const GlobalRandom &) protected
Member Function Documentation
Random * GlobalRandom::getInstance () static
Definition at line 26 of file global_random.cpp.
References GlobalRandom(), pinstance, and tool.
 {
   if (pinstance == 0)  // is it the first call?
   {
     pinstance = new GlobalRandom; // create sole instance
   }
   return pinstance->tool; // address of sole instance
 }
GlobalRandom& GlobalRandom::operator= (const GlobalRandom &) protected
Field Documentation
GlobalRandom * GlobalRandom::pinstance = 0 static private
Definition at line 40 of file global_random.h.
Referenced by getInstance().
Random* GlobalRandom::tool private
Definition at line 41 of file global_random.h.
Referenced by getInstance(), and GlobalRandom().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/util/global_random.h
ssl-vision/src/shared/util/global_random.cpp