Documentation: PluginRunlengthEncode Class Reference
PluginRunlengthEncode Class Reference
#include <plugin_runlength_encode.h>
Public Member Functions
PluginRunlengthEncode (FrameBuffer *_buffer, int max_runs)
~PluginRunlengthEncode ()
virtual ProcessResult process (FrameData *data, RenderOptions *options)
virtual VarList * getSettings ()
virtual string getName ()
Public Member Functions inherited from VisionPlugin
VisionPlugin (FrameBuffer *_buffer)
virtual ~VisionPlugin ()
FrameBuffer * getFrameBuffer () const
this functions provides convenient access to the ring-buffer
void lock ()
void unlock ()
virtual bool isEnabled () const
virtual void setEnabled (bool enable)
virtual bool isVisualize () const
virtual void setVisualize (bool enable)
virtual bool isSharedAmongStacks () const
virtual void setSharedAmongStacks (bool enable)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual void postProcess (FrameData *data, RenderOptions *options)
virtual QWidget * getVisualizationWidget ()
virtual QWidget * getControlWidget ()
virtual void closeWidgets ()
virtual QList< QAction * > actions ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
void setTimeProcessing (double val)
void setTimePostProcessing (double val)
double getTimeProcessing ()
double getTimePostProcessing ()
Protected Attributes
int _max_runs
Protected Attributes inherited from VisionPlugin
QMutex mutex
bool enabled
bool visualize
bool shared
FrameBuffer * buffer
double time_proc
double time_post
Additional Inherited Members
Public Slots inherited from VisionPlugin
void slotKeyPressEvent (QKeyEvent *event)
Detailed Description
Author
Stefan Zickler
Definition at line 31 of file plugin_runlength_encode.h.
Constructor & Destructor Documentation
PluginRunlengthEncode::PluginRunlengthEncode (FrameBuffer * _buffer, int max_runs)
Definition at line 23 of file plugin_runlength_encode.cpp.
References _max_runs.
  : VisionPlugin(_buffer)
 {
   _max_runs=max_runs;
 }
PluginRunlengthEncode::~PluginRunlengthEncode ()
Definition at line 30 of file plugin_runlength_encode.cpp.
 {
 }
Member Function Documentation
string PluginRunlengthEncode::getName () virtual
Reimplemented from VisionPlugin.
Definition at line 64 of file plugin_runlength_encode.cpp.
{
   return "RunlengthEncode";
 }
VarList * PluginRunlengthEncode::getSettings () virtual
Reimplemented from VisionPlugin.
Definition at line 60 of file plugin_runlength_encode.cpp.
{
   return 0;
 }
ProcessResult PluginRunlengthEncode::process (FrameData * data, RenderOptions * options) virtual
Reimplemented from VisionPlugin.
Definition at line 36 of file plugin_runlength_encode.cpp.
References _max_runs, CMVision::RegionProcessing::encodeRuns(), FrameDataMap::get(), CMVision::RunList::getMaxRuns(), CMVision::RunList::getUsedRuns(), FrameDataMap::insert(), FrameData::map, ProcessingFailed, and ProcessingOk.
{
   (void)options;
   CMVision::RunList * runlist;
   if ((runlist=(CMVision::RunList *)data->map.get("cmv_runlist")) == 0) {
     runlist=(CMVision::RunList *)data->map.insert("cmv_runlist",new CMVision::RunList(_max_runs));
   }
   Image<raw8> * img_thresholded = 0;
   if ((img_thresholded=(Image<raw8> *)data->map.get("cmv_threshold")) == 0) {
     printf("Runlength encoder: no thresholded input image found!\n");
     return ProcessingFailed;
   }
   //Runlength Encode the image:
   CMVision::RegionProcessing::encodeRuns(img_thresholded, runlist);
   if (runlist->getUsedRuns() == runlist->getMaxRuns()) {
     printf("Warning: runlength encoder exceeded current max run size of %d\n",runlist->getMaxRuns());
   }
   return ProcessingOk;
 }
Field Documentation
int PluginRunlengthEncode::_max_runs protected
Definition at line 34 of file plugin_runlength_encode.h.
Referenced by PluginRunlengthEncode(), and process().
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/plugin_runlength_encode.h
ssl-vision/src/app/plugins/plugin_runlength_encode.cpp