Documentation: VarTypes::VarExternal Class Reference
VarTypes::VarExternal Class Reference
A list of VarTypes to be stored in an separate XML file.
#include <VarExternal.h>
Public Member Functions
VarExternal (string _filename, VarList *vlist)
Construct a VarExternal list from an existing VarList.
VarExternal (string _filename="", string _name="")
Construct a new VarExternal list.
virtual ~VarExternal ()
virtual VarTypeId getType () const
Public Member Functions inherited from VarTypes::VarList
VarList (string _name="")
Creates an empty VarList.
virtual ~VarList ()
virtual string getString () const
this will always return the empty string ""
virtual void resetToDefault ()
this will clear the list
virtual void printdebug () const
prints the label and number of elements
int addChild (VarType *child)
adds a VarType item to the end of the list.
bool removeChild (VarType *child)
virtual int getChildrenCount () const
returns the number of children of this list
virtual void deleteAllChildren ()
virtual vector< VarType * > getChildren () const
returns a vector of all children in the order that they occur in internally
VarType * findChildOrReplace (VarType *other)
template<class VCLASS >
VCLASS * findChildOrReplace (VCLASS *other)
virtual QWidget * createEditor (const VarItemDelegate *delegate, QWidget *parent, const QStyleOptionViewItem &option)
Public Member Functions inherited from VarTypes::VarType
VarType (string name="")
virtual ~VarType ()
virtual void setName (string name)
Set the string label of this node.
virtual string getName () const
Get the string label of this node.
virtual VarTypeFlag getFlags () const
virtual void setFlags (VarTypeFlag f)
virtual void addFlags (VarTypeFlag f)
virtual void removeFlags (VarTypeFlag f)
virtual bool areFlagsSet (VarTypeFlag f) const
VarType * findChild (string label) const
void writeXML (XMLNode &parent, bool blind_append=true)
Write the contents of this VarType node to an XMLNode.
void readXML (XMLNode &us)
Let this VarType node load the contents of an XMLNode.
virtual void setEditorData (const VarItemDelegate *delegate, QWidget *editor) const
virtual void setModelData (const VarItemDelegate *delegate, QWidget *editor)
virtual QSize sizeHint (const VarItemDelegate *delegate, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void paint (const VarItemDelegate *delegate, QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * clone () const
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual bool setString (const string &val)
Set this node's data to some string representation.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
virtual bool hasValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Protected Member Functions
virtual void updateAttributes (XMLNode &us) const
virtual void readAttributes (XMLNode &us)
virtual void updateChildren (XMLNode &us) const
virtual void readChildren (XMLNode &us)
virtual void loadExternal ()
Protected Member Functions inherited from VarTypes::VarType
virtual void lock () const
virtual void unlock () const
virtual void changed ()
virtual void updateText (XMLNode &us) const
virtual void readText (XMLNode &us)
Protected Attributes
string filename
Protected Attributes inherited from VarTypes::VarList
vector< VarType * > list
Protected Attributes inherited from VarTypes::VarType
QMutex * _mutex
VarTypeFlag _flags
string _name
Additional Inherited Members
Public Slots inherited from VarTypes::VarType
void mvcEditCompleted ()
A slot to receive signals from a model-view system that editing of this item was just completed.
Signals inherited from VarTypes::VarList
void childAdded (VarType *child)
void childRemoved (VarType *child)
Signals inherited from VarTypes::VarType
void hasChanged (VarType *)
void wasEdited (VarType *)
void XMLwasRead (VarType *)
This signal is triggered if data was written from an xml node.
void XMLwasWritten (VarType *)
This signal is triggered if data was written to an xml node.
Static Public Member Functions inherited from VarTypes::VarType
static void deleteAllVarChildren (XMLNode &node)
Clear an XMLNode's list of children.
static vector< VarType * > readChildrenHelper (XMLNode &parent, vector< VarType * > existing_children, bool only_update_existing, bool blind_append)
A helper function to read a list of children from XML and convert it to a vector of VarType nodes.
Static Protected Member Functions inherited from VarTypes::VarType
static string fixString (const char *cst)
static string intToString (int val)
static string doubleToString (double val)
static XMLNode findOrAppendChild (XMLNode &parent, string key, string val)
Detailed Description
A list of VarTypes to be stored in an separate XML file.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
This is the external list VarType of the VarTypes system. It is similar to the VarList type (it inherits it), except that VarExternal allows saving/loading from an external xml-file, which is useful if you don't want to store the entire data-tree in the same XML file, but rather put a certain subtree into its own file.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 43 of file VarExternal.h.
Constructor & Destructor Documentation
VarTypes::VarExternal::VarExternal (string _filename, VarList * vlist)
Construct a VarExternal list from an existing VarList.
Definition at line 25 of file VarExternal.cpp.
References filename, VarTypes::VarList::getChildren(), VarTypes::VarList::list, VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
                                                           : VarList(vlist->getName())
 {
   list=vlist->getChildren();
   lock();
   filename=_filename;
   unlock();
 }
VarTypes::VarExternal::VarExternal (string _filename = "", string _name = "")
Construct a new VarExternal list.
Definition at line 33 of file VarExternal.cpp.
References filename, VarTypes::VarType::lock(), and VarTypes::VarType::unlock().
                                                        : VarList(_name)
 {
   lock();
   filename=_filename;
   unlock();
 }
VarTypes::VarExternal::~VarExternal () virtual
Definition at line 40 of file VarExternal.cpp.
 {
 }
Member Function Documentation
virtual VarTypeId VarTypes::VarExternal::getType () const inline virtual
Reimplemented from VarTypes::VarList.
Definition at line 57 of file VarExternal.h.
References VarTypes::VARTYPE_ID_EXTERNAL.
 { return VARTYPE_ID_EXTERNAL; } ;
void VarTypes::VarExternal::loadExternal () protected virtual
Reimplemented from VarTypes::VarType.
Definition at line 44 of file VarExternal.cpp.
References VarTypes::VarType::changed(), VarTypes::VarList::childAdded(), filename, velocity.pid_::i, VarTypes::VarList::list, VarTypes::VarType::lock(), VarTypes::XMLNode::openFileHelper(), VarTypes::VarType::readChildrenHelper(), and VarTypes::VarType::unlock().
Referenced by readChildren().
{
   lock();
   //load file to empty parent
   int before=list.size();
   XMLNode parent = XMLNode::openFileHelper(filename.c_str(),"VarXML");
   list=readChildrenHelper(parent, list, false, false);
   int after=list.size();
   if (after > before) {
     for (int i=before; i < after; i++) {
         emit(childAdded(list[i]));
     }
   }
   changed();
   unlock();
 }
virtual void VarTypes::VarExternal::readAttributes (XMLNode & us) inline protected virtual
Reimplemented from VarTypes::VarType.
Definition at line 68 of file VarExternal.h.
References VarTypes::XMLNode::getAttribute().
     {
       filename = fixString(us.getAttribute("filename"));
       VarList::readAttributes(us);
     }
void VarTypes::VarExternal::readChildren (XMLNode & us) protected virtual
Reimplemented from VarTypes::VarList.
Definition at line 60 of file VarExternal.cpp.
References loadExternal().
{
   (void)us;
   loadExternal();
 }
virtual void VarTypes::VarExternal::updateAttributes (XMLNode & us) const inline protected virtual
Reimplemented from VarTypes::VarType.
Definition at line 62 of file VarExternal.h.
References VarTypes::XMLNode::updateAttribute().
     {
       us.updateAttribute(filename.c_str(),"filename","filename");
       VarList::updateAttributes(us);
     }
virtual void VarTypes::VarExternal::updateChildren (XMLNode & us) const inline protected virtual
Reimplemented from VarTypes::VarType.
Definition at line 74 of file VarExternal.h.
References VarTypes::XMLNode::writeToFile().
     {
       (void)us;
       XMLNode parent = XMLNode::openFileHelper(filename.c_str(),"VarXML");
       //and update it...
       VarList::updateChildren(parent);
       //save file to empty parent
       parent.writeToFile(filename.c_str());
     }
Field Documentation
string VarTypes::VarExternal::filename protected
Definition at line 47 of file VarExternal.h.
Referenced by loadExternal(), and VarExternal().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/primitives/VarExternal.h
ssl-vision/src/shared/vartypes/primitives/VarExternal.cpp