Documentation: GLLUTWidget::UndoState Class Reference
GLLUTWidget::UndoState Class Reference
Public Member Functions
UndoState (LUT3D *lut)
~UndoState ()
void restore (LUT3D *lut)
Data Fields
lut_mask_t * table
Detailed Description
Definition at line 61 of file glLUTwidget.h.
Constructor & Destructor Documentation
GLLUTWidget::UndoState::UndoState (LUT3D * lut) inline
Definition at line 65 of file glLUTwidget.h.
References LUT3D::getPointerPreshrunk(), and LUT3D::LUT_SIZE.
{
         table=new lut_mask_t[lut->LUT_SIZE];
         memcpy(table,lut->getPointerPreshrunk(0,0,0),lut->LUT_SIZE);
       }
GLLUTWidget::UndoState::~UndoState () inline
Definition at line 70 of file glLUTwidget.h.
                    {
         delete[] table;
       };
Member Function Documentation
void GLLUTWidget::UndoState::restore (LUT3D * lut) inline
Definition at line 73 of file glLUTwidget.h.
References LUT3D::getPointerPreshrunk(), and LUT3D::LUT_SIZE.
Referenced by GLLUTWidget::editRedo(), and GLLUTWidget::editUndo().
{
         memcpy(lut->getPointerPreshrunk(0,0,0),table,lut->LUT_SIZE);
       }
Field Documentation
lut_mask_t* GLLUTWidget::UndoState::table
Definition at line 64 of file glLUTwidget.h.
The documentation for this class was generated from the following file:
ssl-vision/src/app/gui/glLUTwidget.h