Documentation: CMPattern::TeamDetectorSettings Class Reference
CMPattern::TeamDetectorSettings Class Reference
#include <cmpattern_teamdetector.h>
Signals
void teamInfoChanged ()
Public Member Functions
vector< Team * > getTeams () const
Team * getTeam (int idx) const
TeamDetectorSettings (string external_file="")
VarList * getSettings ()
Protected Slots
void slotTeamNodeAdded (VarType *node)
void slotAddPressed ()
Protected Attributes
VarList * settings
VarList * teams
VarTrigger * addTeam
vector< Team * > team_vector
Friends
class TeamDetector
class TeamSelector
Detailed Description
Definition at line 46 of file cmpattern_teamdetector.h.
Constructor & Destructor Documentation
CMPattern::TeamDetectorSettings::TeamDetectorSettings (string external_file = "")
Definition at line 26 of file cmpattern_teamdetector.cpp.
References VarTypes::VarList::addChild(), addTeam, settings, slotAddPressed(), slotTeamNodeAdded(), and teams.
{
  settings=new VarList("Team Config");
  if (external_file.length()==0) {
     settings->addChild(teams = new VarList("Teams"));; // a global variable, defining all teams
  } else {
     settings->addChild(teams = new VarExternal(external_file,"Teams"));; // a global variable, defining all teams
  }
  connect(teams,SIGNAL(childAdded(VarType *)),this,SLOT(slotTeamNodeAdded(VarType *)));
  settings->addChild(addTeam = new VarTrigger("Add", "Add Team..."));
  connect(addTeam,SIGNAL(signalTriggered()),this,SLOT(slotAddPressed()));
 }
Member Function Documentation
VarList* CMPattern::TeamDetectorSettings::getSettings () inline
Definition at line 64 of file cmpattern_teamdetector.h.
Referenced by MultiStackRoboCupSSL::MultiStackRoboCupSSL().
{
    return settings;
  }
Team * CMPattern::TeamDetectorSettings::getTeam (int idx) const
Definition at line 53 of file cmpattern_teamdetector.cpp.
References team_vector.
Referenced by CMPattern::TeamSelector::getSelectedTeam(), and CMPattern::TeamSelector::update().
{
   if (idx < 0 || idx >= (int)team_vector.size()) return 0;
   return (team_vector[idx]);
 }
vector< Team * > CMPattern::TeamDetectorSettings::getTeams () const
Definition at line 49 of file cmpattern_teamdetector.cpp.
References team_vector.
Referenced by CMPattern::TeamSelector::update().
{
   return team_vector;
 }
void CMPattern::TeamDetectorSettings::slotAddPressed () protected slot
Definition at line 45 of file cmpattern_teamdetector.cpp.
References VarTypes::VarList::addChild(), VarTypes::VarList::getChildrenCount(), and teams.
Referenced by TeamDetectorSettings().
{
   teams->addChild(new VarList("New Team " + QString::number(teams->getChildrenCount()).toStdString()));
 }
void CMPattern::TeamDetectorSettings::slotTeamNodeAdded (VarType * node) protected slot
Definition at line 39 of file cmpattern_teamdetector.cpp.
References team_vector, and teamInfoChanged().
Referenced by TeamDetectorSettings().
{
   team_vector.push_back(new Team((VarList *)node));
   connect(team_vector[team_vector.size()-1],SIGNAL(signalTeamNameChanged()),this,SIGNAL(teamInfoChanged()));
   emit(teamInfoChanged());
 }
void CMPattern::TeamDetectorSettings::teamInfoChanged () signal
Definition at line 103 of file moc_cmpattern_teamdetector.cxx.
Referenced by slotTeamNodeAdded().
 {
     QMetaObject::activate(this, &staticMetaObject, 0, 0);
 }
Friends And Related Function Documentation
friend class TeamDetector friend
Definition at line 48 of file cmpattern_teamdetector.h.
friend class TeamSelector friend
Definition at line 49 of file cmpattern_teamdetector.h.
Field Documentation
VarTrigger* CMPattern::TeamDetectorSettings::addTeam protected
Definition at line 53 of file cmpattern_teamdetector.h.
Referenced by TeamDetectorSettings().
VarList* CMPattern::TeamDetectorSettings::settings protected
Definition at line 51 of file cmpattern_teamdetector.h.
Referenced by TeamDetectorSettings().
vector<Team *> CMPattern::TeamDetectorSettings::team_vector protected
Definition at line 54 of file cmpattern_teamdetector.h.
Referenced by getTeam(), getTeams(), and slotTeamNodeAdded().
VarList* CMPattern::TeamDetectorSettings::teams protected
Definition at line 52 of file cmpattern_teamdetector.h.
Referenced by slotAddPressed(), and TeamDetectorSettings().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/cmpattern/cmpattern_teamdetector.h
ssl-vision/build/src/shared/cmpattern/moc_cmpattern_teamdetector.cxx
ssl-vision/src/shared/cmpattern/cmpattern_teamdetector.cpp