Documentation: Log_Frame Class Reference
Log_Frame Class Reference
#include <messages_robocup_ssl_refbox_log.pb.h>
Public Member Functions
Log_Frame ()
virtual ~Log_Frame ()
Log_Frame (const Log_Frame &from)
Log_Frame & operator= (const Log_Frame &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Log_Frame *other)
Log_Frame * New () const PROTOBUF_FINAL
Log_Frame * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const Log_Frame &from)
void MergeFrom (const Log_Frame &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_frame () const
void clear_frame ()
const ::SSL_DetectionFrame & frame () const
::SSL_DetectionFrame * mutable_frame ()
::SSL_DetectionFrame * release_frame ()
void set_allocated_frame (::SSL_DetectionFrame *frame)
bool has_refbox_cmd () const
void clear_refbox_cmd ()
const ::std::string & refbox_cmd () const
void set_refbox_cmd (const ::std::string &value)
void set_refbox_cmd (const char *value)
void set_refbox_cmd (const char *value, size_t size)
::std::string * mutable_refbox_cmd ()
::std::string * release_refbox_cmd ()
void set_allocated_refbox_cmd (::std::string *refbox_cmd)
Log_Frame ()
virtual ~Log_Frame ()
Log_Frame (const Log_Frame &from)
Log_Frame & operator= (const Log_Frame &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Log_Frame *other)
Log_Frame * New () const PROTOBUF_FINAL
Log_Frame * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const Log_Frame &from)
void MergeFrom (const Log_Frame &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_refbox_cmd () const
void clear_refbox_cmd ()
const ::std::string & refbox_cmd () const
void set_refbox_cmd (const ::std::string &value)
void set_refbox_cmd (const char *value)
void set_refbox_cmd (const char *value, size_t size)
::std::string * mutable_refbox_cmd ()
::std::string * release_refbox_cmd ()
void set_allocated_refbox_cmd (::std::string *refbox_cmd)
bool has_frame () const
void clear_frame ()
const ::SSL_DetectionFrame & frame () const
::SSL_DetectionFrame * release_frame ()
::SSL_DetectionFrame * mutable_frame ()
void set_allocated_frame (::SSL_DetectionFrame *frame)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Log_Frame & default_instance ()
static const Log_Frame * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const Log_Frame & default_instance ()
static void InitAsDefaultInstance ()
static const Log_Frame * internal_default_instance ()
Static Public Attributes
static const int kFrameFieldNumber = 1
static const int kRefboxCmdFieldNumber = 2
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (Log_Frame *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_frame ()
void clear_has_frame ()
void set_has_refbox_cmd ()
void clear_has_refbox_cmd ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5frefbox_5flog_2eproto ()
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (Log_Frame *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_frame ()
void clear_has_frame ()
void set_has_refbox_cmd ()
void clear_has_refbox_cmd ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::InitDefaultsLog_FrameImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::internal::ArenaStringPtr refbox_cmd_
::SSL_DetectionFrame * frame_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::TableStruct
void protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl ()
void protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl ()
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5frefbox_5flog_2eproto ()
void swap (Log_Frame &a, Log_Frame &b)
Detailed Description
Definition at line 54 of file messages_robocup_ssl_refbox_log.pb.h.
Constructor & Destructor Documentation
Log_Frame::Log_Frame ()
virtual Log_Frame::~Log_Frame () virtual
Log_Frame::Log_Frame (const Log_Frame & from)
Log_Frame::Log_Frame ()
virtual Log_Frame::~Log_Frame () virtual
Log_Frame::Log_Frame (const Log_Frame & from)
Member Function Documentation
size_t Log_Frame::ByteSizeLong () const
Referenced by New(), and Refbox_Log::New().
size_t Log_Frame::ByteSizeLong () const
void Log_Frame::Clear ()
Referenced by New(), and Refbox_Log::New().
void Log_Frame::Clear ()
void Log_Frame::clear_frame () inline
Definition at line 292 of file messages_robocup_ssl_refbox_log.pb.h.
References clear_has_frame(), and frame_.
Referenced by MaybeArenaPtr().
{
   if (frame_ != NULL) frame_->::SSL_DetectionFrame::Clear();
   clear_has_frame();
 }
void Log_Frame::clear_frame ()
void Log_Frame::clear_has_frame () inline private
Definition at line 289 of file messages_robocup_ssl_refbox_log.pb.h.
References _has_bits_.
Referenced by clear_frame(), release_frame(), and set_allocated_frame().
{
   _has_bits_[0] &= ~0x00000002u;
 }
void Log_Frame::clear_has_frame () private
void Log_Frame::clear_has_refbox_cmd () inline private
Definition at line 334 of file messages_robocup_ssl_refbox_log.pb.h.
References _has_bits_.
Referenced by clear_refbox_cmd(), release_refbox_cmd(), and set_allocated_refbox_cmd().
{
   _has_bits_[0] &= ~0x00000001u;
 }
void Log_Frame::clear_has_refbox_cmd () private
void Log_Frame::clear_refbox_cmd () inline
Definition at line 337 of file messages_robocup_ssl_refbox_log.pb.h.
References clear_has_refbox_cmd(), and refbox_cmd_.
{
   refbox_cmd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   clear_has_refbox_cmd();
 }
void Log_Frame::clear_refbox_cmd ()
void Log_Frame::CopyFrom (const ::google::protobuf::Message & from)
Referenced by New(), Refbox_Log::New(), operator=(), and Refbox_Log::operator=().
void Log_Frame::CopyFrom (const Log_Frame & from)
void Log_Frame::CopyFrom (const ::google::protobuf::Message & from)
void Log_Frame::CopyFrom (const Log_Frame & from)
static const Log_Frame& Log_Frame::default_instance () static
Referenced by mutable_unknown_fields(), and Refbox_Log::mutable_unknown_fields().
static const Log_Frame& Log_Frame::default_instance () static
static const ::google::protobuf::Descriptor* Log_Frame::descriptor () static
Referenced by mutable_unknown_fields(), and Refbox_Log::mutable_unknown_fields().
static const ::google::protobuf::Descriptor* Log_Frame::descriptor () static
const ::SSL_DetectionFrame & Log_Frame::frame () const inline
Definition at line 296 of file messages_robocup_ssl_refbox_log.pb.h.
References frame_, and SSL_DetectionFrame::internal_default_instance().
Referenced by set_allocated_frame().
{
   // @@protoc_insertion_point(field_get:Log_Frame.frame)
   return frame_ != NULL ? *frame_
                          : *::SSL_DetectionFrame::internal_default_instance();
 }
const ::SSL_DetectionFrame& Log_Frame::frame () const
inline ::google::protobuf::Arena* Log_Frame::GetArenaNoVirtual () const inline private
Definition at line 114 of file messages_robocup_ssl_refbox_log.pb.h.
Referenced by operator=().
{
     return NULL;
   }
inline ::google::protobuf::Arena* Log_Frame::GetArenaNoVirtual () const inline private
Definition at line 139 of file messages_robocup_ssl_refbox_log.pb.h.
{
     return NULL;
   }
int Log_Frame::GetCachedSize () const inline
Definition at line 107 of file messages_robocup_ssl_refbox_log.pb.h.
References _cached_size_, InternalSwap(), SetCachedSize(), SharedCtor(), and SharedDtor().
 { return _cached_size_; }
int Log_Frame::GetCachedSize () const inline
Definition at line 132 of file messages_robocup_ssl_refbox_log.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata Log_Frame::GetMetadata () const
Referenced by MaybeArenaPtr(), and Refbox_Log::MaybeArenaPtr().
::google::protobuf::Metadata Log_Frame::GetMetadata () const
bool Log_Frame::has_frame () const inline
Definition at line 283 of file messages_robocup_ssl_refbox_log.pb.h.
References _has_bits_.
Referenced by MaybeArenaPtr().
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool Log_Frame::has_frame () const
bool Log_Frame::has_refbox_cmd () const inline
Definition at line 328 of file messages_robocup_ssl_refbox_log.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool Log_Frame::has_refbox_cmd () const
static void Log_Frame::InitAsDefaultInstance () static
static const Log_Frame* Log_Frame::internal_default_instance () inline static
Definition at line 77 of file messages_robocup_ssl_refbox_log.pb.h.
References _Log_Frame_default_instance_, and Swap().
{
     return reinterpret_cast<const Log_Frame*>(
                &_Log_Frame_default_instance_);
   }
static const Log_Frame* Log_Frame::internal_default_instance () inline static
Definition at line 101 of file messages_robocup_ssl_refbox_log.pb.h.
References _Log_Frame_default_instance_.
{
     return reinterpret_cast<const Log_Frame*>(
                &_Log_Frame_default_instance_);
   }
::google::protobuf::uint8* Log_Frame::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
Referenced by New(), Refbox_Log::New(), SerializeWithCachedSizesToArray(), and Refbox_Log::SerializeWithCachedSizesToArray().
::google::protobuf::uint8* Log_Frame::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void Log_Frame::InternalSwap (Log_Frame * other) private
Referenced by GetCachedSize(), and Refbox_Log::GetCachedSize().
void Log_Frame::InternalSwap (Log_Frame * other) private
bool Log_Frame::IsInitialized () const
Referenced by New(), Refbox_Log::New(), and ViewUpdateThread::start_play_record().
bool Log_Frame::IsInitialized () const
void* Log_Frame::MaybeArenaPtr () const inline private
Definition at line 117 of file messages_robocup_ssl_refbox_log.pb.h.
References clear_frame(), GetMetadata(), and has_frame().
{
     return NULL;
   }
void* Log_Frame::MaybeArenaPtr () const inline private
Definition at line 142 of file messages_robocup_ssl_refbox_log.pb.h.
References bot_comm::frame.
{
     return NULL;
   }
void Log_Frame::MergeFrom (const ::google::protobuf::Message & from)
Referenced by New(), and Refbox_Log::New().
void Log_Frame::MergeFrom (const Log_Frame & from)
void Log_Frame::MergeFrom (const ::google::protobuf::Message & from)
void Log_Frame::MergeFrom (const Log_Frame & from)
bool Log_Frame::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Referenced by New(), and Refbox_Log::New().
bool Log_Frame::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
SSL_DetectionFrame * Log_Frame::mutable_frame () inline
Definition at line 301 of file messages_robocup_ssl_refbox_log.pb.h.
References frame_, and set_has_frame().
Referenced by ViewUpdateThread::execute().
{
   set_has_frame();
   if (frame_ == NULL) {
     frame_ = new ::SSL_DetectionFrame;
   }
   // @@protoc_insertion_point(field_mutable:Log_Frame.frame)
   return frame_;
 }
::SSL_DetectionFrame* Log_Frame::mutable_frame ()
std::string * Log_Frame::mutable_refbox_cmd () inline
Definition at line 369 of file messages_robocup_ssl_refbox_log.pb.h.
References refbox_cmd_, and set_has_refbox_cmd().
{
   set_has_refbox_cmd();
   // @@protoc_insertion_point(field_mutable:Log_Frame.refbox_cmd)
   return refbox_cmd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
::std::string* Log_Frame::mutable_refbox_cmd ()
inline ::google::protobuf::UnknownFieldSet* Log_Frame::mutable_unknown_fields () inline
Definition at line 70 of file messages_robocup_ssl_refbox_log.pb.h.
References _internal_metadata_, default_instance(), and descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
inline ::google::protobuf::UnknownFieldSet* Log_Frame::mutable_unknown_fields () inline
Definition at line 93 of file messages_robocup_ssl_refbox_log.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
Log_Frame* Log_Frame::New () const inline
Definition at line 86 of file messages_robocup_ssl_refbox_log.pb.h.
References ByteSizeLong(), Clear(), CopyFrom(), InternalSerializeWithCachedSizesToArray(), IsInitialized(), MergeFrom(), MergePartialFromCodedStream(), New(), SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New(), and Refbox_Log::New().
 { return New(NULL); }
Log_Frame* Log_Frame::New (::google::protobuf::Arena * arena) const
Log_Frame* Log_Frame::New () const inline
Definition at line 115 of file messages_robocup_ssl_refbox_log.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
Log_Frame* Log_Frame::New (::google::protobuf::Arena * arena) const
Log_Frame& Log_Frame::operator= (const Log_Frame & from) inline
Definition at line 61 of file messages_robocup_ssl_refbox_log.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
Log_Frame& Log_Frame::operator= (const Log_Frame & from) inline
Definition at line 71 of file messages_robocup_ssl_refbox_log.pb.h.
References GetArenaNoVirtual().
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* Log_Frame::protobuf_Offsets_messages_5frobocup_5fssl_5frefbox_5flog_2eproto () private
const ::std::string & Log_Frame::refbox_cmd () const inline
Definition at line 341 of file messages_robocup_ssl_refbox_log.pb.h.
References refbox_cmd_.
Referenced by ViewUpdateThread::start_play_record().
{
   // @@protoc_insertion_point(field_get:Log_Frame.refbox_cmd)
   return refbox_cmd_.GetNoArena();
 }
const ::std::string& Log_Frame::refbox_cmd () const
SSL_DetectionFrame * Log_Frame::release_frame () inline
Definition at line 309 of file messages_robocup_ssl_refbox_log.pb.h.
References clear_has_frame(), and frame_.
{
   // @@protoc_insertion_point(field_release:Log_Frame.frame)
   clear_has_frame();
   ::SSL_DetectionFrame* temp = frame_;
   frame_ = NULL;
   return temp;
 }
::SSL_DetectionFrame* Log_Frame::release_frame ()
std::string * Log_Frame::release_refbox_cmd () inline
Definition at line 374 of file messages_robocup_ssl_refbox_log.pb.h.
References clear_has_refbox_cmd(), and refbox_cmd_.
{
   // @@protoc_insertion_point(field_release:Log_Frame.refbox_cmd)
   clear_has_refbox_cmd();
   return refbox_cmd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
::std::string* Log_Frame::release_refbox_cmd ()
size_t Log_Frame::RequiredFieldsByteSizeFallback () const private
size_t Log_Frame::RequiredFieldsByteSizeFallback () const private
void Log_Frame::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Referenced by New(), and Refbox_Log::New().
void Log_Frame::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* Log_Frame::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 103 of file messages_robocup_ssl_refbox_log.pb.h.
References InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void Log_Frame::set_allocated_frame (::SSL_DetectionFrame * frame) inline
Definition at line 316 of file messages_robocup_ssl_refbox_log.pb.h.
References clear_has_frame(), frame(), frame_, and set_has_frame().
{
   delete frame_;
   frame_ = frame;
   if (frame) {
     set_has_frame();
   } else {
     clear_has_frame();
   }
   // @@protoc_insertion_point(field_set_allocated:Log_Frame.frame)
 }
void Log_Frame::set_allocated_frame (::SSL_DetectionFrame * frame)
void Log_Frame::set_allocated_refbox_cmd (::std::string * refbox_cmd) inline
Definition at line 379 of file messages_robocup_ssl_refbox_log.pb.h.
References clear_has_refbox_cmd(), refbox_cmd_, and set_has_refbox_cmd().
{
   if (refbox_cmd != NULL) {
     set_has_refbox_cmd();
   } else {
     clear_has_refbox_cmd();
   }
   refbox_cmd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), refbox_cmd);
   // @@protoc_insertion_point(field_set_allocated:Log_Frame.refbox_cmd)
 }
void Log_Frame::set_allocated_refbox_cmd (::std::string * refbox_cmd)
void Log_Frame::set_has_frame () inline private
Definition at line 286 of file messages_robocup_ssl_refbox_log.pb.h.
References _has_bits_.
Referenced by mutable_frame(), and set_allocated_frame().
{
   _has_bits_[0] |= 0x00000002u;
 }
void Log_Frame::set_has_frame () private
void Log_Frame::set_has_refbox_cmd () inline private
Definition at line 331 of file messages_robocup_ssl_refbox_log.pb.h.
References _has_bits_.
Referenced by mutable_refbox_cmd(), set_allocated_refbox_cmd(), and set_refbox_cmd().
{
   _has_bits_[0] |= 0x00000001u;
 }
void Log_Frame::set_has_refbox_cmd () private
void Log_Frame::set_refbox_cmd (const ::std::string & value) inline
Definition at line 345 of file messages_robocup_ssl_refbox_log.pb.h.
References refbox_cmd_, and set_has_refbox_cmd().
{
   set_has_refbox_cmd();
   refbox_cmd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
   // @@protoc_insertion_point(field_set:Log_Frame.refbox_cmd)
 }
void Log_Frame::set_refbox_cmd (const char * value) inline
Definition at line 358 of file messages_robocup_ssl_refbox_log.pb.h.
References refbox_cmd_, and set_has_refbox_cmd().
{
   set_has_refbox_cmd();
   refbox_cmd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
   // @@protoc_insertion_point(field_set_char:Log_Frame.refbox_cmd)
 }
void Log_Frame::set_refbox_cmd (const char * value, size_t size) inline
Definition at line 363 of file messages_robocup_ssl_refbox_log.pb.h.
References refbox_cmd_, and set_has_refbox_cmd().
{
   set_has_refbox_cmd();
   refbox_cmd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
       ::std::string(reinterpret_cast<const char*>(value), size));
   // @@protoc_insertion_point(field_set_pointer:Log_Frame.refbox_cmd)
 }
void Log_Frame::set_refbox_cmd (const ::std::string & value)
void Log_Frame::set_refbox_cmd (const char * value)
void Log_Frame::set_refbox_cmd (const char * value, size_t size)
void Log_Frame::SetCachedSize (int size) const private
Referenced by GetCachedSize(), and Refbox_Log::GetCachedSize().
void Log_Frame::SetCachedSize (int size) const private
void Log_Frame::SharedCtor () private
Referenced by GetCachedSize(), and Refbox_Log::GetCachedSize().
void Log_Frame::SharedCtor () private
void Log_Frame::SharedDtor () private
Referenced by GetCachedSize(), and Refbox_Log::GetCachedSize().
void Log_Frame::SharedDtor () private
void Log_Frame::Swap (Log_Frame * other)
Referenced by internal_default_instance(), and Refbox_Log::internal_default_instance().
void Log_Frame::Swap (Log_Frame * other)
const ::google::protobuf::UnknownFieldSet& Log_Frame::unknown_fields () const inline
Definition at line 66 of file messages_robocup_ssl_refbox_log.pb.h.
References _internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
const ::google::protobuf::UnknownFieldSet& Log_Frame::unknown_fields () const inline
Definition at line 90 of file messages_robocup_ssl_refbox_log.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
Log_Frame::void::protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::InitDefaultsLog_FrameImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::TableStruct friend
Definition at line 192 of file messages_robocup_ssl_refbox_log.pb.h.
void protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl () friend
void protobuf_InitDefaults_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_impl () friend
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5frefbox_5flog_2eproto () friend
void swap (Log_Frame & a, Log_Frame & b) friend
Definition at line 109 of file messages_robocup_ssl_refbox_log.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int Log_Frame::_cached_size_ mutable private
Definition at line 164 of file messages_robocup_ssl_refbox_log.pb.h.
Referenced by GetCachedSize(), and Refbox_Log::GetCachedSize().
google::protobuf::internal::HasBits< 1 > Log_Frame::_has_bits_ private
Definition at line 163 of file messages_robocup_ssl_refbox_log.pb.h.
Referenced by clear_has_frame(), clear_has_refbox_cmd(), has_frame(), has_refbox_cmd(), set_has_frame(), and set_has_refbox_cmd().
google::protobuf::internal::InternalMetadataWithArena Log_Frame::_internal_metadata_ private
Definition at line 162 of file messages_robocup_ssl_refbox_log.pb.h.
Referenced by mutable_unknown_fields(), Refbox_Log::mutable_unknown_fields(), unknown_fields(), and Refbox_Log::unknown_fields().
SSL_DetectionFrame * Log_Frame::frame_ private
Definition at line 166 of file messages_robocup_ssl_refbox_log.pb.h.
Referenced by clear_frame(), frame(), mutable_frame(), release_frame(), and set_allocated_frame().
static const int Log_Frame::kFrameFieldNumber = 1 static
Definition at line 131 of file messages_robocup_ssl_refbox_log.pb.h.
PROTOBUF_CONSTEXPR int const Log_Frame::kIndexInFileMessages static
Initial value:
=
    0
Definition at line 105 of file messages_robocup_ssl_refbox_log.pb.h.
static const int Log_Frame::kRefboxCmdFieldNumber = 2 static
Definition at line 140 of file messages_robocup_ssl_refbox_log.pb.h.
google::protobuf::internal::ArenaStringPtr Log_Frame::refbox_cmd_ private
Definition at line 165 of file messages_robocup_ssl_refbox_log.pb.h.
Referenced by clear_refbox_cmd(), mutable_refbox_cmd(), refbox_cmd(), release_refbox_cmd(), set_allocated_refbox_cmd(), and set_refbox_cmd().
The documentation for this class was generated from the following file:
grsim_comm/include/proto/messages_robocup_ssl_refbox_log.pb.h