Documentation: GLWidget Class Reference
GLWidget Class Reference
An OpenGL-based real-time video display widget.
#include <glwidget.h>
Public Slots
void moveRobot ()
void resetRobot ()
void selectRobot ()
void unselectRobot ()
void moveCurrentRobot ()
void resetCurrentRobot ()
void moveBall ()
void changeCameraMode ()
void yellowRobotsMenuTriggered (QAction *act)
void blueRobotsMenuTriggered (QAction *act)
void switchRobotOnOff ()
void moveRobotHere ()
void moveBallHere ()
void lockCameraToRobot ()
void lockCameraToBall ()
void flipImage ()
void callZoomNormal ()
void callZoomFit ()
void callHelp ()
void saveImage ()
Signals
void clicked ()
void selectedRobot ()
void closeSignal (bool)
void toggleFullScreen (bool)
void robotTurnedOnOff (int, bool)
void updateVideoStats (VideoStats)
void signalMouseAction (QMouseEvent *event, pixelloc loc)
void signalKeyPressEvent (QKeyEvent *event)
Public Member Functions
GLWidget (QWidget *parent, ConfigWidget *_cfg)
~GLWidget ()
dReal getFPS ()
void update3DCursor (int mouse_x, int mouse_y)
void putBall (dReal x, dReal y)
void reform (int team, const QString &act)
void step ()
virtual QSize sizeHint () const
virtual void setRingBufferBB (RingBuffer< FrameData > *rb)
void setVisionStack (VisionStack *_stack)
void setObjectName (const QString &s)
GLWidget (QWidget *parent=0, bool allow_qpainter_overlay=true)
virtual ~GLWidget ()
virtual void focusInEvent (QFocusEvent *event)
virtual void focusOutEvent (QFocusEvent *event)
void mainDraw ()
virtual void myQPainterOverlay (QPainter &painter, QTransform &trans)
virtual void myGLinit ()
virtual void myGLdraw ()
void setupViewPort (int width, int height)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual void redraw ()
Public Member Functions inherited from RealTimeDisplayWidget
RealTimeDisplayWidget (FrameBuffer *_rb=0)
virtual ~RealTimeDisplayWidget ()
FrameBuffer * getRingBuffer ()
void setRingBuffer (FrameBuffer *_rb)
Data Fields
ConfigWidget * cfg
SSLWorld * ssl
RobotsFomation * forms [6]
QMenu * robpopup
QMenu * ballpopup
QMenu * mainpopup
QMenu * blueRobotsMenu
QMenu * yellowRobotsMenu
QAction * moveRobotAct
QAction * selectRobotAct
QAction * resetRobotAct
QAction * moveBallAct
QAction * lockToBallAct
QAction * onOffRobotAct
QAction * lockToRobotAct
QAction * moveBallHereAct
QAction * moveRobotHereAct
QAction * changeCamModeAct
QMenu * cameraMenu
int Current_robot
int Current_team
int cammode
int lockedIndex
bool ctrl
bool alt
bool kickingball
bool altTrigger
bool chiping
double kickpower
double chipAngle
bool fullScreen
Zoom zoom
VideoStats stats
FrameCounter c_draw
FrameCounter c_loop
Protected Member Functions
void paintGL ()
void initializeGL ()
void mousePressEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void wheelEvent (QWheelEvent *event)
void keyPressEvent (QKeyEvent *event)
void keyReleaseEvent (QKeyEvent *event)
void closeEvent (QCloseEvent *event)
virtual void initializeGL ()
virtual void paintGL ()
virtual void resizeGL (int width, int height)
void wheelEvent (QWheelEvent *event)
void keyPressEvent (QKeyEvent *event)
void mouseAction (QMouseEvent *event, pixelloc loc)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void paintEvent (QPaintEvent *e)
Protected Attributes
bool ALLOW_QPAINTER
int vpW
int vpH
long long last_frame
VisionStack * stack
QPoint mouseStart
double mouseStartPanX
double mouseStartPanY
QAction * actionFlipV
QAction * actionFlipH
QAction * actionBB
QAction * actionOn
QWidgetAction * actionColorPicker
RingBuffer< FrameData > * rb_bb
Protected Attributes inherited from RealTimeDisplayWidget
VideoStats stats
FrameBuffer * rb
Private Attributes
int state
int moving_robot_id
int clicked_robot
int frames
bool first_time
QTime time
QTime rendertimer
dReal m_fps
QPoint lastPos
Friends
class GLWidgetGraphicsView
Detailed Description
An OpenGL-based real-time video display widget.
Author
Stefan Zickler, (C) 2008
Definition at line 31 of file glwidget.h.
Constructor & Destructor Documentation
GLWidget::GLWidget (QWidget * parent, ConfigWidget * _cfg)
Definition at line 30 of file glwidget.cpp.
References alt, altTrigger, ballpopup, blueRobotsMenu, blueRobotsMenuTriggered(), cameraMenu, cammode, cfg, changeCameraMode(), changeCamModeAct, chipAngle, chiping, ctrl, Current_robot, Current_team, first_time, forms, frames, fullScreen, kickingball, kickpower, lockCameraToBall(), lockCameraToRobot(), lockToBallAct, lockToRobotAct, mainpopup, moveBall(), moveBallAct, moveBallHere(), moveBallHereAct, moveRobot(), moveRobotAct, moveRobotHere(), moveRobotHereAct, onOffRobotAct, resetRobot(), resetRobotAct, robpopup, selectRobot(), selectRobotAct, ssl, state, switchRobotOnOff(), yellowRobotsMenu, and yellowRobotsMenuTriggered().
Referenced by setObjectName().
     : QGLWidget(parent)
 {
     frames = 0;
     state = 0;
     first_time = true;
     cfg = _cfg;
     forms[1] = new RobotsFomation(-1);  //outside yellow
     forms[2] = new RobotsFomation(1);  //inside type 1
     forms[3] = new RobotsFomation(2);  //inside type 2
     forms[4] = new RobotsFomation(3);  //inside type 1
     //forms[5] = new RobotsFomation(4);  //inside type 2
     ssl = new SSLWorld(this,cfg,forms[2],forms[2]);
     Current_robot = 0;
     Current_team = 0;
     cammode = 0;
     setMouseTracking(true);
     blueRobotsMenu = new QMenu("&Blue Robots");
     yellowRobotsMenu = new QMenu("&Yellow Robots");
     blueRobotsMenu->addAction(tr("Put all inside with formation 1"));
     blueRobotsMenu->addAction(tr("Put all inside with formation 2"));
     blueRobotsMenu->addAction(tr("Put all outside"));
     blueRobotsMenu->addAction(tr("Put all out of field"));
     blueRobotsMenu->addAction(tr("Turn all off"));
     blueRobotsMenu->addAction(tr("Turn all on"));
     yellowRobotsMenu->addAction(tr("Put all inside with formation 1"));
     yellowRobotsMenu->addAction(tr("Put all inside with formation 2"));
     yellowRobotsMenu->addAction(tr("Put all outside"));
     yellowRobotsMenu->addAction(tr("Put all out of field"));
     yellowRobotsMenu->addAction(tr("Turn all off"));
     yellowRobotsMenu->addAction(tr("Turn all on"));
     robpopup = new QMenu(this);
     moveRobotAct = new QAction(tr("&Locate robot"),this);
     selectRobotAct = new QAction(tr("&Select robot"),this);
     resetRobotAct = new QAction(tr("&Reset robot"),this);
     onOffRobotAct = new QAction(tr("Turn &off"),this);
     lockToRobotAct = new QAction(tr("Loc&k camera to this robot"),this);
     robpopup->addAction(moveRobotAct);
     robpopup->addAction(resetRobotAct);
     robpopup->addAction(onOffRobotAct);
     robpopup->addAction(lockToRobotAct);
     robpopup->addMenu(blueRobotsMenu);
     robpopup->addMenu(yellowRobotsMenu);
     moveBallAct = new QAction(tr("&Locate ball"),this);
     lockToBallAct = new QAction(tr("Loc&k camera to ball"),this);
     ballpopup = new QMenu(this);
     ballpopup->addAction(moveBallAct);
     ballpopup->addAction(lockToBallAct);
     moveRobotHereAct = new QAction(tr("Locate current &robot here"),this);
     moveBallHereAct = new QAction(tr("Locate &ball here"),this);
     mainpopup = new QMenu(this);
     mainpopup->addAction(moveBallHereAct);
     mainpopup->addAction(moveRobotHereAct);
     cameraMenu = new QMenu("&Camera");
     changeCamModeAct=new QAction(tr("Change &mode"),this);
     changeCamModeAct->setShortcut(QKeySequence("C"));
     cameraMenu->addAction(changeCamModeAct);
     cameraMenu->addAction(lockToRobotAct);
     cameraMenu->addAction(lockToBallAct);
     mainpopup->addMenu(cameraMenu);
     mainpopup->addMenu(blueRobotsMenu);
     mainpopup->addMenu(yellowRobotsMenu);
     connect(moveRobotAct, SIGNAL(triggered()), this, SLOT(moveRobot()));
     connect(selectRobotAct, SIGNAL(triggered()), this, SLOT(selectRobot()));
     connect(resetRobotAct, SIGNAL(triggered()), this, SLOT(resetRobot()));
     connect(moveBallAct, SIGNAL(triggered()), this, SLOT(moveBall()));
     connect(onOffRobotAct, SIGNAL(triggered()), this, SLOT(switchRobotOnOff()));
     connect(yellowRobotsMenu,SIGNAL(triggered(QAction*)),this,SLOT(yellowRobotsMenuTriggered(QAction*)));
     connect(blueRobotsMenu,SIGNAL(triggered(QAction*)),this,SLOT(blueRobotsMenuTriggered(QAction*)));
     connect(moveBallHereAct, SIGNAL(triggered()),this , SLOT(moveBallHere()));
     connect(moveRobotHereAct, SIGNAL(triggered()),this , SLOT(moveRobotHere()));
     connect(lockToRobotAct, SIGNAL(triggered()), this, SLOT(lockCameraToRobot()));
     connect(lockToBallAct, SIGNAL(triggered()), this, SLOT(lockCameraToBall()));
     connect(changeCamModeAct,SIGNAL(triggered()),this,SLOT(changeCameraMode()));
     setFocusPolicy(Qt::StrongFocus);
     fullScreen = false;
     ctrl = false;
     alt = false;
     kickingball = false;
     kickpower = 3.0;
     altTrigger = false;
     chipAngle = M_PI/4;
     chiping = false;
 }
GLWidget::~GLWidget ()
Definition at line 121 of file glwidget.cpp.
Referenced by GLWidget(), and setObjectName().
 {
 }
GLWidget::GLWidget (QWidget * parent = 0, bool allow_qpainter_overlay = true)
Definition at line 88 of file glwidget.cpp.
References actionFlipH, actionFlipV, actionOn, ALLOW_QPAINTER, callHelp(), callZoomFit(), callZoomNormal(), flipImage(), initializeGL(), myGLinit(), RealTimeDisplayWidget::rb, rb_bb, saveImage(), stack, and ~GLWidget().
                                                                   : QGLWidget ( allow_qpainter_overlay ? QGLFormat(QGL::SampleBuffers) : QGLFormat(), parent ) {
   ALLOW_QPAINTER=allow_qpainter_overlay;
   rb_bb=0;
   rb=0;
   stack=0;
   setAutoFillBackground(false);
   //not needed because we are remote triggering this:
   //startTimer(1);
   /*setMinimumSize ( 60,40 );
   colorPicker=new ColorPicker();
   actionColorPicker=new QWidgetAction ( this );
   actionColorPicker->setDefaultWidget ( ( QWidget * ) colorPicker );
   actionColorPicker->setVisible ( true );
   actionColorPicker->setToolTip ( "RGB Color Picker\n(Left click in image to use)" );
   addAction ( actionColorPicker );*/
   QAction * actionSave = new QAction ( this );
   actionSave->setObjectName ( "actionSave" );
   actionSave->setIcon ( QIcon ( ":/icons/document-save.png" ) );
   actionSave->setShortcut ( QKeySequence ( "Ctrl+s" ) );
   actionSave->setToolTip ( "Save Image... (Ctrl-s)" );
   actionSave->setShortcutContext ( Qt::WidgetShortcut );
   addAction ( actionSave );
   actionFlipV = new QAction ( this );
   actionFlipV->setObjectName ( "actionFlipV" );
   actionFlipV->setToolTip ( "Flip image vertically" );
   actionFlipV->setCheckable ( true );
   actionFlipV->setIcon ( QIcon ( ":/icons/delete_table_row.png" ) );
   addAction ( actionFlipV );
   actionFlipH = new QAction ( this );
   actionFlipH->setObjectName ( "actionFlipH" );
   actionFlipH->setToolTip ( "Flip image horizontally" );
   actionFlipH->setCheckable ( true );
   actionFlipH->setIcon ( QIcon ( ":/icons/delete_table_col.png" ) );
   addAction ( actionFlipH );
   QAction * actionHelp = new QAction ( this );
   actionHelp->setObjectName ( "actionHelp" );
   actionHelp->setIcon ( QIcon ( ":/icons/help-contents.png" ) );
   actionHelp->setShortcut ( QKeySequence ( "Ctrl+h" ) );
   actionHelp->setToolTip ( "Show keyboard shortcuts (Ctrl-h)" );
   actionHelp->setShortcutContext ( Qt::WidgetShortcut );
   addAction ( actionHelp );
   QAction * actionZoomFit = new QAction ( this );
   actionZoomFit->setObjectName ( "actionZoomFit" );
   actionZoomFit->setIcon ( QIcon ( ":/icons/zoom-best-fit.png" ) );
   actionZoomFit->setShortcut ( QKeySequence ( "Space" ) );
   actionZoomFit->setToolTip ( "Zoom to Fit (Space)" );
   actionZoomFit->setShortcutContext ( Qt::WidgetShortcut );
   addAction ( actionZoomFit );
   QAction * actionZoomNormal = new QAction ( this );
   actionZoomNormal->setObjectName ( "actionZoomNormal" );
   actionZoomNormal->setIcon ( QIcon ( ":/icons/zoom-original.png" ) );
   actionZoomNormal->setShortcut ( QKeySequence ( "Home" ) );
   actionZoomNormal->setShortcutContext ( Qt::WidgetShortcut );
   actionZoomNormal->setToolTip ( "Zoom to 100% (Home)" );
   addAction ( actionZoomNormal );
   actionOn = new QAction ( this );
   actionOn->setObjectName ( "actionOn" );
   actionOn->setCheckable ( true );
   actionOn->setChecked ( true );
   actionOn->setShortcut ( QKeySequence ( "Ctrl+p" ) );
   actionOn->setShortcutContext ( Qt::WidgetShortcut );
   actionOn->setToolTip ( "Turn display on/off (Ctrl-p)" );
   actionOn->setIcon ( QIcon ( ":/icons/application-exit.png" ) );
   addAction ( actionOn );
   connect ( actionSave, SIGNAL ( triggered() ), this, SLOT ( saveImage() ) );
   connect ( actionFlipV, SIGNAL ( triggered ( bool ) ), this, SLOT ( flipImage() ) );
   connect ( actionFlipH, SIGNAL ( triggered ( bool ) ), this, SLOT ( flipImage() ) );
   connect ( actionHelp, SIGNAL ( triggered() ), this, SLOT ( callHelp() ) );
   connect ( actionZoomFit, SIGNAL ( triggered() ), this, SLOT ( callZoomFit() ) );
   connect ( actionZoomNormal, SIGNAL ( triggered() ), this, SLOT ( callZoomNormal() ) );
   flipImage();
 }
virtual GLWidget::~GLWidget () virtual
Member Function Documentation
void GLWidget::blueRobotsMenuTriggered (QAction * act) slot
Definition at line 525 of file glwidget.cpp.
References reform().
Referenced by GLWidget().
 {
     reform(0,act->text());
 }
void GLWidget::callHelp () slot
Definition at line 327 of file glwidget.cpp.
References VisionStack::keyPressEvent(), keyPressEvent(), Zoom::panDown(), Zoom::panLeft(), Zoom::panRight(), Zoom::panUp(), redraw(), stack, zoom, Zoom::zoomIn(), and Zoom::zoomOut().
Referenced by GLWidget(), and redraw().
{
   QMessageBox::information ( this,"Keyboard and Mouse shortcuts",
                              "Left-Click: Pick RGB Color\nShift-Modifier: Erase pixel from LUT\nShift-Ctrl-Modifier: Add pixel to LUT\nArrow-Keys (or Right-Drag Mouse): Panning\nPage Up/Down (or Mousewheel): Zooming\nHome: Reset Zoom to 100%\nSpace: Reset Zoom to Best Fit\nCtrl-f: Toggle Fullscreen\nCtrl-w: Toggle Detach Window" );
 }
void GLWidget::callZoomFit () slot
Definition at line 321 of file glwidget.cpp.
References redraw(), Zoom::setPan(), zoom, and Zoom::zoomToFit().
Referenced by GLWidget(), and redraw().
{
   this->zoom.setPan ( 0.0,0.0 );
   this->zoom.zoomToFit();
   this->redraw(); //upgl
 }
void GLWidget::callZoomNormal () slot
Definition at line 315 of file glwidget.cpp.
References redraw(), Zoom::setPan(), Zoom::setZoom(), and zoom.
Referenced by GLWidget(), and redraw().
{
   this->zoom.setPan ( 0.0,0.0 );
   this->zoom.setZoom ( 1.0 );
   this->redraw(); //upgl
 }
void GLWidget::changeCameraMode () slot
Definition at line 413 of file glwidget.cpp.
References cammode, cfg, ConfigWidget::Field_Length(), ConfigWidget::Field_Margin(), ConfigWidget::Field_Width(), SSLWorld::g, CGraphics::getViewpoint(), CGraphics::setViewpoint(), and ssl.
Referenced by GLWidget().
 {
     static dReal xyz[3],hpr[3];
     if (cammode<0) cammode=0;
     else cammode ++;
     cammode %= 6;
     if (cammode==0)
         ssl->g->setViewpoint(0,-(cfg->Field_Width()+cfg->Field_Margin()*2.0f)/2.0f,3,90,-45,0);
     else if (cammode==1)
     {
         ssl->g->getViewpoint(xyz,hpr);
     }
     else if (cammode==2)
         ssl->g->setViewpoint(0,0,5,0,-90,0);
     else if (cammode==3)
         ssl->g->setViewpoint(0, (cfg->Field_Width()+cfg->Field_Margin()*2.0f)/2.0f,3,270,-45,0);
     else if (cammode==4)
         ssl->g->setViewpoint(-(cfg->Field_Length()+cfg->Field_Margin()*2.0f)/2.0f,0,3,0,-45,0);
     else if (cammode==5)
         ssl->g->setViewpoint((cfg->Field_Length()+cfg->Field_Margin()*2.0f)/2.0f,0,3,180,-45,0);
 }
void GLWidget::clicked () signal
Referenced by mouseReleaseEvent().
void GLWidget::closeEvent (QCloseEvent * event) protected
Definition at line 520 of file glwidget.cpp.
References closeSignal().
 {
     emit closeSignal(false);
 }
void GLWidget::closeSignal (bool) signal
Referenced by closeEvent().
virtual void GLWidget::displayLoopEvent (bool frame_changed, RenderOptions * opts) inline virtual
Reimplemented from RealTimeDisplayWidget.
Definition at line 137 of file glwidget.h.
References VideoStats::capture_stats, FrameCounter::count(), VideoStats::fps_draw, VideoStats::fps_loop, bot_comm::frame, FrameDataMap::get(), FrameCounter::getFPS(), FrameData::map, RealTimeDisplayWidget::rb, redraw(), and updateVideoStats().
   {
     (void)opts;
     bool changed=false;
     bool changed2=false;
     c_loop.count();
     if (frame_changed && rb!=0) {
       rb->lockRead();
       int cur=rb->curRead();
       last_frame=rb->getPointer(cur)->number;
       FrameData * frame = rb->getPointer(cur);
       CaptureStats * cstats = (CaptureStats *)frame->map.get("capture_stats");
       if (cstats != 0) {
         stats.capture_stats=(*cstats);
       }
       rb->unlockRead();
       redraw();
     }
     stats.fps_loop= c_loop.getFPS(changed);
     stats.fps_draw= c_draw.getFPS(changed2);
     if (changed || changed2)
       updateVideoStats(stats);
   }
void GLWidget::flipImage () slot
Definition at line 367 of file glwidget.cpp.
References actionFlipH, actionFlipV, redraw(), Zoom::setFlipX(), Zoom::setFlipY(), and zoom.
Referenced by GLWidget(), and redraw().
{
   this->zoom.setFlipX ( actionFlipH->isChecked() );
   this->zoom.setFlipY ( actionFlipV->isChecked() );
   this->redraw(); //upgl
 }
virtual void GLWidget::focusInEvent (QFocusEvent * event) inline virtual
Definition at line 110 of file glwidget.h.
   {
     (void)event;
     if (parentWidget()!=0) {
       parentWidget()->setBackgroundRole(QPalette::Highlight);
       parentWidget()->setForegroundRole(QPalette::HighlightedText);
       parentWidget()->update();
     }
   }
virtual void GLWidget::focusOutEvent (QFocusEvent * event) inline virtual
Definition at line 120 of file glwidget.h.
References mainDraw(), myGLdraw(), myGLinit(), myQPainterOverlay(), and setupViewPort().
   {
     (void)event;
     if (parentWidget()!=0) {
       parentWidget()->setBackgroundRole(QPalette::Window);
       parentWidget()->setForegroundRole(QPalette::WindowText);
       parentWidget()->update();
     }
   }
dReal GLWidget::getFPS ()
Definition at line 334 of file glwidget.cpp.
References m_fps.
Referenced by MainWindow::update().
 {
     return m_fps;
 }
virtual void GLWidget::initializeGL () protected virtual
void GLWidget::initializeGL () protected
Definition at line 340 of file glwidget.cpp.
References SSLWorld::glinit(), and ssl.
Referenced by GLWidget().
 {
     ssl->glinit();
 }
void GLWidget::keyPressEvent (QKeyEvent * event) protected
void GLWidget::keyPressEvent (QKeyEvent * event) protected
Definition at line 455 of file glwidget.cpp.
References alt, SSLWorld::ball, ConfigWidget::BallRadius(), PObject::body, cfg, chiping, ctrl, Current_robot, Current_team, fullScreen, Robot::incSpeed(), Robot::Kicker::kick(), Robot::kicker, kickingball, kickpower, logStatus(), Robot::resetSpeeds(), robotIndex(), SSLWorld::robots, ssl, toggleFullScreen(), and Robot::Kicker::toggleRoller().
Referenced by callHelp(), and GLWidgetGraphicsView::keyPressEvent().
 {
     if (event->key() == Qt::Key_Control) ctrl = true;
     if (event->key() == Qt::Key_Alt) alt = true;
     char cmd = event->key();
     if (fullScreen) {
         if (event->key()==Qt::Key_F2) emit toggleFullScreen(false);
     }
     const dReal S = 1.00;
     const dReal BallForce = 2.0;
     int R = robotIndex(Current_robot,Current_team);
     if (R < 0) return;
     bool flag=false;
     switch (cmd) {
     case 't': case 'T': ssl->robots[R]->incSpeed(0,-S);ssl->robots[R]->incSpeed(1,S);ssl->robots[R]->incSpeed(2,-S);ssl->robots[R]->incSpeed(3,S);break;
     case 'g': case 'G': ssl->robots[R]->incSpeed(0,S);ssl->robots[R]->incSpeed(1,-S);ssl->robots[R]->incSpeed(2,S);ssl->robots[R]->incSpeed(3,-S);break;
     case 'f': case 'F': ssl->robots[R]->incSpeed(0,S);ssl->robots[R]->incSpeed(1,S);ssl->robots[R]->incSpeed(2,S);ssl->robots[R]->incSpeed(3,S);break;
     case 'h': case 'H': ssl->robots[R]->incSpeed(0,-S);ssl->robots[R]->incSpeed(1,-S);ssl->robots[R]->incSpeed(2,-S);ssl->robots[R]->incSpeed(3,-S);break;
     case 'w': case 'W':dBodyAddForce(ssl->ball->body,0, BallForce,0);break;
     case 's': case 'S':dBodyAddForce(ssl->ball->body,0,-BallForce,0);break;
     case 'd': case 'D':dBodyAddForce(ssl->ball->body, BallForce,0,0);break;
     case 'a': case 'A':dBodyAddForce(ssl->ball->body,-BallForce,0,0);break;
     case 'k': case 'K': ssl->robots[R]->kicker->kick(8,0);break;
     case 'l': case 'L': ssl->robots[R]->kicker->kick(3,3);break;
     case 'j': case 'J': ssl->robots[R]->kicker->toggleRoller();break;
     case 'i': case 'I': dBodySetLinearVel(ssl->ball->body,2.0,0,0);dBodySetAngularVel(ssl->ball->body,0,2.0/cfg->BallRadius(),0);break;
     case ';':
         if (kickingball==false)
         {
             kickingball = true; logStatus(QString("Kick mode On"),QColor("blue"));
             chiping = false;
         }
         else
         {
             kickingball = false; logStatus(QString("Kick mode Off"),QColor("red"));
             chiping = false;
         }
         break;
     case '\'':
         if (chiping==false)
         {
             logStatus(QString("Chip mode On"),QColor("blue"));
             chiping = true;
             kickingball = false;
         }
         else
         {
             logStatus(QString("Chip mode Off"),QColor("red"));
             chiping = false;
             kickingball = false;
         }
         break;
     case ']': kickpower += 0.1; logStatus(QString("Kick power = %1").arg(kickpower),QColor("orange"));break;
     case '[': kickpower -= 0.1; logStatus(QString("Kick power = %1").arg(kickpower),QColor("cyan"));break;
     case ' ':
         ssl->robots[R]->resetSpeeds();
         break;
     case '`':
         dBodySetLinearVel(ssl->ball->body,0,0,0);
         dBodySetAngularVel(ssl->ball->body,0,0,0);
         break;
     }
 }
void GLWidget::keyReleaseEvent (QKeyEvent * event) protected
Definition at line 442 of file glwidget.cpp.
References alt, ctrl, moveCurrentRobot(), SSLWorld::show3DCursor, ssl, and unselectRobot().
 {
     if (event->key() == Qt::Key_Control) ctrl = false;
     if (event->key() == Qt::Key_Alt) {
         if (!ssl->show3DCursor)
             moveCurrentRobot();
         else {
             unselectRobot();
         }
         alt = false;
     }
 }
void GLWidget::lockCameraToBall () slot
Definition at line 580 of file glwidget.cpp.
References cammode.
Referenced by GLWidget().
 {
     cammode = -2;
 }
void GLWidget::lockCameraToRobot () slot
Definition at line 574 of file glwidget.cpp.
References cammode, Current_robot, Current_team, lockedIndex, and robotIndex().
Referenced by GLWidget().
 {
     cammode = -1;
     lockedIndex = robotIndex(Current_robot,Current_team);//clicked_robot;
 }
void GLWidget::mainDraw ()
new qpainter overlay stuff
Definition at line 210 of file glwidget.cpp.
References actionOn, ALLOW_QPAINTER, c_draw, FrameCounter::count(), Zoom::getQTransform(), myGLdraw(), myGLinit(), myQPainterOverlay(), setupViewPort(), and zoom.
Referenced by focusOutEvent(), mouseAction(), and paintEvent().
{
    if ( actionOn->isChecked() ==false ) return;
    if (ALLOW_QPAINTER) {
     makeCurrent();
     glMatrixMode(GL_MODELVIEW);
     glPushMatrix();
     myGLinit();
     setupViewPort(width(), height());
    }
    myGLdraw();
    if (ALLOW_QPAINTER) {
     QTransform trans=zoom.getQTransform(false);
     QPainter painter;
     painter.begin((QGLWidget*)this);
     painter.setRenderHint(QPainter::Antialiasing);
     myQPainterOverlay(painter,trans);
     painter.end();
     glMatrixMode ( GL_MODELVIEW );
     glPopMatrix();
   }
    c_draw.count();
 }
void GLWidget::mouseAction (QMouseEvent * event, pixelloc loc) protected
Definition at line 24 of file glwidget.cpp.
References Zoom::getFlipXval(), Zoom::getFlipYval(), Zoom::getPanX(), Zoom::getPanY(), Zoom::getZoom(), Zoom::invZoom(), mainDraw(), VisionStack::mouseMoveEvent(), mouseMoveEvent(), VisionStack::mousePressEvent(), mousePressEvent(), VisionStack::mouseReleaseEvent(), mouseReleaseEvent(), mouseStart, mouseStartPanX, mouseStartPanY, paintGL(), redraw(), Zoom::setPan(), stack, vpH, vpW, and zoom.
{
   (void)loc;
   if ( ( event->buttons() & Qt::RightButton ) !=0 ) {
     //Right mouse button...drag image
     QPoint offset=mouseStart-event->pos();
     zoom.setPan ( mouseStartPanX- ( ( double ) offset.x() / ( zoom.getZoom() * zoom.getFlipXval() * vpW ) ),
                   mouseStartPanY- ( ( double ) offset.y() / ( zoom.getZoom() * zoom.getFlipYval() * vpH ) ) );
   } /* else if ( ( event->buttons() & Qt::LeftButton ) !=0 ) {
     //Left mouse button...color-pick from image.
     if ( rb!=0 ) {
       rb->lockRead();
       int idx=rb->curRead();
       FrameData * frame = rb->getPointer ( idx );
       VisualizationFrame * vis_frame=(VisualizationFrame *)(frame->map.get("vis_frame"));
       if (vis_frame!=0 && vis_frame->valid==true) {
         rgbImage & img = vis_frame->data;
         if ( loc.x < img.getWidth() && loc.y < img.getHeight() && loc.x >=0 && loc.y >=0 ) {
           if ( img.getWidth() > 1 && img.getHeight() > 1 ) {
             colorPicker->setColor ( img.getPixel ( loc.x,loc.y ) );
             //img.setPixel(loc.x,loc.y,rgb(255,0,0));
           }
         }
       }
       rb->unlockRead();
     }
   }*/
   redraw();
 }
void GLWidget::mouseMoveEvent (QMouseEvent * event) protected
void GLWidget::mouseMoveEvent (QMouseEvent * event) protected
Definition at line 310 of file glwidget.cpp.
References CGraphics::cameraMotion(), ctrl, SSLWorld::g, CGraphics::isGraphicsEnabled(), lastPos, ssl, and update3DCursor().
Referenced by mouseAction(), and GLWidgetGraphicsView::mouseMoveEvent().
 {
     if (!ssl->g->isGraphicsEnabled()) return;
     int dx = -(event->x() - lastPos.x());
     int dy = -(event->y() - lastPos.y());
     if (event->buttons() & Qt::LeftButton) {
         if (ctrl)
             ssl->g->cameraMotion(4,dx,dy);
         else
             ssl->g->cameraMotion(1,dx,dy);
     }
     else if (event->buttons() & Qt::MidButton)
     {
         ssl->g->cameraMotion(2,dx,dy);
     }
     lastPos = event->pos();
     update3DCursor(event->x(),event->y());
 }
void GLWidget::mousePressEvent (QMouseEvent * event) protected
void GLWidget::mousePressEvent (QMouseEvent * event) protected
Definition at line 198 of file glwidget.cpp.
References SSLWorld::ball, ballpopup, ConfigWidget::BallRadius(), PObject::body, cfg, chipAngle, chiping, clicked_robot, SSLWorld::cursor_x, SSLWorld::cursor_y, SSLWorld::g, PObject::getBodyPosition(), CGraphics::isGraphicsEnabled(), kickingball, kickpower, lastPos, mainpopup, moving_robot_id, Robot::on, onOffRobotAct, SSLWorld::robots, robpopup, SSLWorld::selected, selectRobot(), PObject::setBodyPosition(), Robot::setXY(), SSLWorld::show3DCursor, ssl, state, role._GoToPoint::x, and role._GoToPoint::y.
Referenced by mouseAction(), and GLWidgetGraphicsView::mousePressEvent().
 {
     if (!ssl->g->isGraphicsEnabled()) return;
     lastPos = event->pos();
     if (event->buttons() & Qt::LeftButton)
     {
         if (state==1)
         {
             if (moving_robot_id!=-1)
             {
                 ssl->robots[moving_robot_id]->setXY(ssl->cursor_x,ssl->cursor_y);
                 state = 0;
                 ssl->show3DCursor = false;
             }
         }
         else if (state==2)
         {
             ssl->ball->setBodyPosition(ssl->cursor_x,ssl->cursor_y,cfg->BallRadius()*1.1*20.0);
             dBodySetAngularVel(ssl->ball->body,0,0,0);
             dBodySetLinearVel(ssl->ball->body,0,0,0);
             ssl->show3DCursor = false;
             state = 0;
         }
         else {
             if (ssl->selected>=0){
                 clicked_robot = ssl->selected;
                 selectRobot();
             }
             if (kickingball)
             {
                 dReal x,y,z;
                 ssl->ball->getBodyPosition(x,y,z);
                 x = ssl->cursor_x - x;
                 y = ssl->cursor_y - y;
                 dReal lxy = hypot(x,y);
                 x /= lxy;
                 y /= lxy;
                 x *= kickpower;
                 y *= kickpower;
                 dBodySetLinearVel(ssl->ball->body,x,y,0);
                 dBodySetAngularVel(ssl->ball->body,-y/cfg->BallRadius(),x/cfg->BallRadius(),0);
             }
             else if (chiping) {
                 dReal x,y,z;
                 ssl->ball->getBodyPosition(x,y,z);
                 x = ssl->cursor_x - x;
                 y = ssl->cursor_y - y;
                 dReal lxy = hypot(x,y);
                 x /= lxy;
                 y /= lxy;
                 x *= kickpower;
                 y *= kickpower;
                 z = kickpower*tan(chipAngle);
                 dBodySetLinearVel(ssl->ball->body,x,y,z);
                 dBodySetAngularVel(ssl->ball->body,-y/cfg->BallRadius(),x/cfg->BallRadius(),z);
             }
         }
     }
     if (event->buttons() & Qt::RightButton)
     {
         if (ssl->selected!=-1 && ssl->selected!=-2)
         {
             clicked_robot = ssl->selected;
             selectRobot();
             if (ssl->robots[ssl->selected]->on)
                 onOffRobotAct->setText("Turn &off");
             else onOffRobotAct->setText("Turn &on");
             robpopup->exec(event->globalPos());
         }
         else clicked_robot=-1;
         if (ssl->selected==-2)
             ballpopup->exec(event->globalPos());
         if (ssl->selected==-1)
             mainpopup->exec(event->globalPos());
     }
 }
void GLWidget::mouseReleaseEvent (QMouseEvent * event) protected
void GLWidget::mouseReleaseEvent (QMouseEvent * event) protected
Definition at line 329 of file glwidget.cpp.
References clicked().
Referenced by mouseAction(), and GLWidgetGraphicsView::mouseReleaseEvent().
 {
     emit clicked();
 }
void GLWidget::moveBall () slot
Definition at line 191 of file glwidget.cpp.
References ConfigWidget::BallRadius(), cfg, SSLWorld::cursor_radius, SSLWorld::show3DCursor, ssl, and state.
Referenced by GLWidget().
 {
     ssl->show3DCursor = true;
     ssl->cursor_radius = cfg->BallRadius();
     state = 2;
 }
void GLWidget::moveBallHere () slot
Definition at line 566 of file glwidget.cpp.
References SSLWorld::ball, ConfigWidget::BallRadius(), PObject::body, cfg, SSLWorld::cursor_x, SSLWorld::cursor_y, PObject::setBodyPosition(), and ssl.
Referenced by GLWidget().
 {
     ssl->ball->setBodyPosition(ssl->cursor_x,ssl->cursor_y,cfg->BallRadius()*2);
     dBodySetLinearVel(ssl->ball->body, 0.0, 0.0, 0.0);
     dBodySetAngularVel(ssl->ball->body, 0.0, 0.0, 0.0);
 }
void GLWidget::moveCurrentRobot () slot
Definition at line 183 of file glwidget.cpp.
References cfg, Current_robot, Current_team, SSLWorld::cursor_radius, moving_robot_id, robotIndex(), RobotSettings::RobotRadius, ConfigWidget::robotSettings, SSLWorld::show3DCursor, ssl, and state.
Referenced by keyReleaseEvent().
 {
     ssl->show3DCursor = true;
     ssl->cursor_radius = cfg->robotSettings.RobotRadius;
     state = 1;
     moving_robot_id = robotIndex(Current_robot,Current_team);
 }
void GLWidget::moveRobot () slot
Definition at line 125 of file glwidget.cpp.
References cfg, clicked_robot, SSLWorld::cursor_radius, moving_robot_id, RobotSettings::RobotRadius, ConfigWidget::robotSettings, SSLWorld::show3DCursor, ssl, and state.
Referenced by GLWidget().
 {
     ssl->show3DCursor = true;
     ssl->cursor_radius = cfg->robotSettings.RobotRadius;
     state = 1;
     moving_robot_id = clicked_robot;
 }
void GLWidget::moveRobotHere () slot
Definition at line 585 of file glwidget.cpp.
References Current_robot, Current_team, SSLWorld::cursor_x, SSLWorld::cursor_y, Robot::resetRobot(), robotIndex(), SSLWorld::robots, Robot::setXY(), and ssl.
Referenced by GLWidget().
 {
     ssl->robots[robotIndex(Current_robot,Current_team)]->setXY(ssl->cursor_x,ssl->cursor_y);
     ssl->robots[robotIndex(Current_robot,Current_team)]->resetRobot();
 }
void GLWidget::myGLdraw () virtual
Definition at line 239 of file glwidget.cpp.
References VisualizationFrame::data, bot_comm::frame, FrameDataMap::get(), Zoom::getFlipXval(), Zoom::getFlipYval(), Zoom::getZoom(), FrameData::map, RealTimeDisplayWidget::rb, Zoom::setup(), VisualizationFrame::valid, vpH, vpW, pixelloc::x, pixelloc::y, zoom, and Zoom::zoom().
Referenced by focusOutEvent(), and mainDraw().
{
   glPushAttrib ( GL_ALL_ATTRIB_BITS );
   glMatrixMode ( GL_PROJECTION );
   glLoadIdentity();
   glPushMatrix();
     glMatrixMode ( GL_MODELVIEW );
     glLoadIdentity();
     glPushMatrix();
       glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
       if ( rb!=0 ) {
         rb->lockRead();
         int idx=rb->curRead();
         FrameData * frame = rb->getPointer ( idx );
         VisualizationFrame * vis_frame=(VisualizationFrame *)(frame->map.get("vis_frame"));
         if (vis_frame!=0 && vis_frame->valid==true && vis_frame->data.getData() != 0 && vis_frame->data.getWidth() >= 1 && vis_frame->data.getHeight() >=1 ) {
           rgbImage & img = vis_frame->data;
           if ( img.getWidth() > 1 && img.getHeight() > 1 ) {
             glPushMatrix();
             zoom.setup ( img.getWidth(), img.getHeight(), vpW,vpH,true );
             pixelloc orig=zoom.zoom ( 0, 0 );
             glPushMatrix();
             glRasterPos2i ( 0,0 );
             glBitmap ( 0,0,0,0,orig.x,-orig.y,0 );
             glPixelZoom ( zoom.getZoom() * zoom.getFlipXval(),zoom.getZoom() * zoom.getFlipYval() * -1.0 );
             glDrawPixels ( img.getWidth(), img.getHeight(), GL_RGB, GL_UNSIGNED_BYTE, img.getData() );
             glPopMatrix();
             glPopMatrix();
           }
         }
         rb->unlockRead();
       }
       glMatrixMode ( GL_MODELVIEW );
     glPopMatrix();
   glMatrixMode ( GL_PROJECTION );
   glPopMatrix();
   glPopAttrib();
 }
void GLWidget::myGLinit () virtual
Definition at line 182 of file glwidget.cpp.
References ALLOW_QPAINTER.
Referenced by focusOutEvent(), GLWidget(), and mainDraw().
{
   qglClearColor ( QColor ( 64,64,128 ) );
   //qpainter stuff:
   if (ALLOW_QPAINTER) {
     glEnable ( GL_ALPHA_TEST );
     glEnable ( GL_BLEND );
     glBlendFunc ( GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA );
     glEnable ( GL_TEXTURE_2D );
     glEnable(GL_CULL_FACE);
   }
   glEnable(GL_MULTISAMPLE);
 }
void GLWidget::myQPainterOverlay (QPainter & painter, QTransform & trans) virtual
Definition at line 373 of file glwidget.cpp.
Referenced by focusOutEvent(), and mainDraw().
{
   (void)painter;
   (void)trans;
 }
void GLWidget::paintEvent (QPaintEvent * e) protected
Definition at line 199 of file glwidget.cpp.
References ALLOW_QPAINTER, and mainDraw().
{
   //QGLWidget::paintEvent(e);
   if (ALLOW_QPAINTER) {
     ( void ) e;
     mainDraw();
   } else {
     QGLWidget::paintEvent(e);
   }
 }
virtual void GLWidget::paintGL () protected virtual
void GLWidget::paintGL () protected
Definition at line 373 of file glwidget.cpp.
References SSLWorld::ball, cammode, Current_robot, Current_team, SSLWorld::g, PObject::getBodyPosition(), Robot::getDir(), Robot::getXY(), velocity.pid_::i, CGraphics::isGraphicsEnabled(), lockedIndex, CGraphics::lookAt(), Robot::on, ROBOT_COUNT, robotIndex(), SSLWorld::robots, CGraphics::setViewpoint(), ssl, step(), role._GoToPoint::x, and role._GoToPoint::y.
Referenced by mouseAction().
 {
     if (!ssl->g->isGraphicsEnabled()) return;
     if (cammode==1)
     {
         dReal x,y,z;
         int R = robotIndex(Current_robot,Current_team);
         ssl->robots[R]->getXY(x,y);z = 0.3;
         ssl->g->setViewpoint(x,y,z,ssl->robots[R]->getDir(),-25,0);
     }
     if (cammode==-1)
     {
         dReal x,y,z;
         ssl->robots[lockedIndex]->getXY(x,y);z = 0.1;
         ssl->g->lookAt(x,y,z);
     }
     if (cammode==-2)
     {
         dReal x,y,z;
         ssl->ball->getBodyPosition(x,y,z);
         ssl->g->lookAt(x,y,z);
     }
     step();
     QFont font;
     for (int i=0;i<ROBOT_COUNT*2;i++)
     {
         dReal xx,yy;
         ssl->robots[i]->getXY(xx,yy);
         if (i>=ROBOT_COUNT) qglColor(Qt::yellow);
         else qglColor(Qt::cyan);
         renderText(xx,yy,0.3,QString::number(i%ROBOT_COUNT),font);
         if (!ssl->robots[i]->on){
             qglColor(Qt::red);
             font.setBold(true);
             renderText(xx,yy,0.4,"Off",font);
         }
         font.setBold(false);
     }
 }
void GLWidget::putBall (dReal x, dReal y)
Definition at line 435 of file glwidget.cpp.
References SSLWorld::ball, PObject::body, PObject::setBodyPosition(), and ssl.
Referenced by MainWindow::ballMenuTriggered().
 {
     ssl->ball->setBodyPosition(x,y,0.3);
     dBodySetLinearVel(ssl->ball->body,0,0,0);
     dBodySetAngularVel(ssl->ball->body,0,0,0);
 }
virtual void GLWidget::redraw () inline virtual
Definition at line 165 of file glwidget.h.
References callHelp(), callZoomFit(), callZoomNormal(), flipImage(), saveImage(), signalKeyPressEvent(), signalMouseAction(), and updateVideoStats().
Referenced by callHelp(), callZoomFit(), callZoomNormal(), displayLoopEvent(), flipImage(), mouseAction(), and resizeGL().
   {
     if (ALLOW_QPAINTER) {
       repaint();
     } else {
       updateGL();
     }
   }
void GLWidget::reform (int team, const QString & act)
Definition at line 535 of file glwidget.cpp.
References forms, velocity.pid_::i, k, Robot::on, onOffRobotAct, RobotsFomation::resetRobots(), ROBOT_COUNT, robotIndex(), SSLWorld::robots, robotTurnedOnOff(), and ssl.
Referenced by blueRobotsMenuTriggered(), and yellowRobotsMenuTriggered().
 {
     if (act==tr("Put all inside with formation 1")) forms[2]->resetRobots(ssl->robots,team);
     if (act==tr("Put all inside with formation 2")) forms[3]->resetRobots(ssl->robots,team);
     if (act==tr("Put all outside")) forms[1]->resetRobots(ssl->robots,team);
     if (act==tr("Put all out of field")) forms[4]->resetRobots(ssl->robots,team);
     if(act==tr("Turn all off")) {
         for(int i=0; i<ROBOT_COUNT; i++) {
             int k = robotIndex(i, team);
             if(ssl->robots[k]->on==true) {
                 ssl->robots[k]->on = false;
                 onOffRobotAct->setText("Turn &on");
                 emit robotTurnedOnOff(k, false);
             }
         }
     }
     if(act==tr("Turn all on")) {
         for(int i=0; i<ROBOT_COUNT; i++) {
             int k = robotIndex(i, team);
             if(ssl->robots[k]->on==false) {
                 ssl->robots[k]->on = true;
                 onOffRobotAct->setText("Turn &off");
                 emit robotTurnedOnOff(k, true);
             }
         }
     }
 }
void GLWidget::resetCurrentRobot () slot
Definition at line 178 of file glwidget.cpp.
References Current_robot, Current_team, Robot::resetRobot(), robotIndex(), SSLWorld::robots, and ssl.
 {
     ssl->robots[robotIndex(Current_robot,Current_team)]->resetRobot();
 }
void GLWidget::resetRobot () slot
Definition at line 151 of file glwidget.cpp.
References Current_robot, Current_team, Robot::resetRobot(), robotIndex(), SSLWorld::robots, and ssl.
Referenced by GLWidget().
 {
     if (Current_robot!=-1)
     {
         ssl->robots[robotIndex(Current_robot, Current_team)]->resetRobot();
     }
 }
void GLWidget::resizeGL (int width, int height) protected virtual
Definition at line 295 of file glwidget.cpp.
References Zoom::invZoom(), redraw(), setupViewPort(), stack, VisionStack::wheelEvent(), wheelEvent(), zoom, Zoom::zoomIn(), and Zoom::zoomOut().
{
   setupViewPort(width,height);
 }
void GLWidget::robotTurnedOnOff (int , bool) signal
Referenced by reform(), and switchRobotOnOff().
void GLWidget::saveImage () slot
Definition at line 378 of file glwidget.cpp.
References VisualizationFrame::data, bot_comm::frame, FrameDataMap::get(), FrameData::map, RealTimeDisplayWidget::rb, and VisualizationFrame::valid.
Referenced by GLWidget(), and redraw().
{
   rgbImage temp;
   if ( rb!=0 ) {
     rb->lockRead();
     int idx=rb->curRead();
     FrameData * frame = rb->getPointer ( idx );
     VisualizationFrame * vis_frame=(VisualizationFrame *)(frame->map.get("vis_frame"));
     if (vis_frame !=0 && vis_frame->valid) {
       temp.copy ( vis_frame->data );
       rb->unlockRead();
     } else {
       rb->unlockRead();
       return;
     }
   }
   if ( temp.getWidth() > 1 && temp.getHeight() > 1 ) {
     QFileDialog dialog ( this,
                          "Export image to file...",
                          "",
                          "PNG (*.png)" );
     dialog.setConfirmOverwrite ( true );
     dialog.setDefaultSuffix ( "png" );
     dialog.setAcceptMode ( QFileDialog::AcceptSave );
     if ( dialog.exec() ) {
       if ( dialog.selectedFiles().size() > 0 ) {
         QString filename=dialog.selectedFiles().at ( 0 );
         if ( temp.save ( filename.toStdString() ) ) {
           QMessageBox::information ( this, "Success","PNG was saved successfully." );
         } else {
           QMessageBox::warning ( this, "Error","Unknown error while saving PNG." );
         }
       }
     }
   }
 }
void GLWidget::selectedRobot () signal
Referenced by selectRobot().
void GLWidget::selectRobot () slot
Definition at line 141 of file glwidget.cpp.
References clicked_robot, Current_robot, Current_team, ROBOT_COUNT, and selectedRobot().
Referenced by GLWidget(), and mousePressEvent().
 {
     if (clicked_robot!=-1)
     {
         Current_robot = clicked_robot%ROBOT_COUNT;
         Current_team = clicked_robot/ROBOT_COUNT;
         emit selectedRobot();
     }
 }
void GLWidget::setObjectName (const QString & s) inline
Definition at line 103 of file glwidget.h.
References GLWidget(), and ~GLWidget().
   {
     QGLWidget::setObjectName(s);
   }
virtual void GLWidget::setRingBufferBB (RingBuffer< FrameData > * rb) inline virtual
Definition at line 89 of file glwidget.h.
References RealTimeDisplayWidget::rb.
   {
     rb_bb=rb;
   }
void GLWidget::setupViewPort (int width, int height)
Definition at line 285 of file glwidget.cpp.
References vpH, and vpW.
Referenced by focusOutEvent(), mainDraw(), and resizeGL().
{
   glViewport ( 0, 0, width, height );
   glOrtho ( 0, width, 0, height, -1, 1 );
   //save new viewport dimensions:
   vpW=width;
   vpH=height;
   if ( vpW < 1 ) vpW=1;
   if ( vpH < 1 ) vpH=1;
 }
void GLWidget::setVisionStack (VisionStack * _stack) inline
Definition at line 99 of file glwidget.h.
Referenced by MainWindow::MainWindow().
   {
     stack=_stack;
   }
void GLWidget::signalKeyPressEvent (QKeyEvent * event) signal
Definition at line 130 of file moc_glwidget.cxx.
Referenced by redraw().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 2, _a);
 }
void GLWidget::signalMouseAction (QMouseEvent * event, pixelloc loc) signal
Definition at line 123 of file moc_glwidget.cxx.
Referenced by redraw().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)) };
     QMetaObject::activate(this, &staticMetaObject, 1, _a);
 }
virtual QSize GLWidget::sizeHint () const inline virtual
Definition at line 83 of file glwidget.h.
{
     QSize size;
     size.setHeight(580);
     size.setWidth(600);
     return size;
   }
void GLWidget::step ()
Definition at line 345 of file glwidget.cpp.
References SSLWorld::ball, PObject::body, cfg, ConfigWidget::DeltaTime(), ConfigWidget::DesiredFPS(), first_time, frames, m_fps, rendertimer, ssl, SSLWorld::step(), ConfigWidget::SyncWithGL(), and time.
Referenced by paintGL(), and MainWindow::update().
 {
     static double lastBallSpeed=-1;
     const dReal* ballV = dBodyGetLinearVel(ssl->ball->body);
     double ballSpeed = ballV[0]*ballV[0] + ballV[1]*ballV[1] + ballV[2]*ballV[2];
     ballSpeed  = sqrt(ballSpeed);
     lastBallSpeed = ballSpeed;
     rendertimer.restart();
     m_fps = frames /(time.elapsed()/1000.0);
     if (!(frames % ((int)(ceil(cfg->DesiredFPS()))))) {
         time.restart();
         frames = 0;
     }
     if (first_time) {ssl->step();first_time = false;}
     else {
         if (cfg->SyncWithGL())
         {
             dReal ddt=rendertimer.elapsed()/1000.0;
             if (ddt>0.05) ddt=0.05;
             ssl->step(ddt);
         }
         else {
             ssl->step(cfg->DeltaTime());
         }
     }
     frames ++;
 }
void GLWidget::switchRobotOnOff () slot
Definition at line 159 of file glwidget.cpp.
References Current_robot, Current_team, k, Robot::on, onOffRobotAct, robotIndex(), SSLWorld::robots, robotTurnedOnOff(), and ssl.
Referenced by GLWidget().
 {
     int k = robotIndex(Current_robot, Current_team);
     if (Current_robot!=-1)
     {
         if (ssl->robots[k]->on==true)
         {
             ssl->robots[k]->on = false;
             onOffRobotAct->setText("Turn &on");
             emit robotTurnedOnOff(k,false);
         }
         else {
             ssl->robots[k]->on = true;
             onOffRobotAct->setText("Turn &off");
             emit robotTurnedOnOff(k,true);
         }
     }
 }
void GLWidget::toggleFullScreen (bool) signal
Referenced by keyPressEvent().
void GLWidget::unselectRobot () slot
Definition at line 133 of file glwidget.cpp.
References cfg, Current_robot, Current_team, SSLWorld::cursor_radius, moving_robot_id, robotIndex(), RobotSettings::RobotRadius, ConfigWidget::robotSettings, SSLWorld::show3DCursor, ssl, and state.
Referenced by keyReleaseEvent().
 {
     ssl->show3DCursor = false;
     ssl->cursor_radius = cfg->robotSettings.RobotRadius;
     state = 0;
     moving_robot_id= robotIndex(Current_robot,Current_team);
 }
void GLWidget::update3DCursor (int mouse_x, int mouse_y)
Definition at line 284 of file glwidget.cpp.
References SSLWorld::g, CGraphics::getCameraForward(), CGraphics::getCameraRight(), CGraphics::getFrustum(), CGraphics::getViewpoint(), CGraphics::isGraphicsEnabled(), SSLWorld::ray, PRay::setPose(), ssl, SSLWorld::updatedCursor, role._GoToPoint::x, and role._GoToPoint::y.
Referenced by mouseMoveEvent(), and wheelEvent().
 {
     if (!ssl->g->isGraphicsEnabled()) return;
     ssl->updatedCursor = true;
     dVector3 xyz,hpr;
     dReal fx,fy,fz,rx,ry,rz,ux,uy,uz,px,py,pz;
     ssl->g->getViewpoint(xyz,hpr);
     ssl->g->getCameraForward(fx,fy,fz);
     ssl->g->getCameraRight(rx,ry,rz);
     ux = ry*fz - rz*fy;
     uy = rz*fx - rx*fz;
     uz = rx*fy - ry*fx;
     dReal w = width();
     dReal h = height();
     dReal xx,yy,z;
     dReal x = 1.0f - 2.0f*(dReal) mouse_x / w;
     dReal y = 1.0f - 2.0f*(dReal) mouse_y / h;
     ssl->g->getFrustum(xx,yy,z);
     x *= xx;
     y *= yy;
     px = -ux*y - rx*x - z*fx;
     py = -uy*y - ry*x - z*fy;
     pz = -uz*y - rz*x - z*fz;
     ssl->ray->setPose(xyz[0],xyz[1],xyz[2],px,py,pz);
 }
void GLWidget::updateVideoStats (VideoStats _t1) signal
Definition at line 116 of file moc_glwidget.cxx.
Referenced by displayLoopEvent(), and redraw().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 0, _a);
 }
void GLWidget::wheelEvent (QWheelEvent * event) protected
void GLWidget::wheelEvent (QWheelEvent * event) protected
Definition at line 277 of file glwidget.cpp.
References SSLWorld::g, CGraphics::isGraphicsEnabled(), ssl, update3DCursor(), and CGraphics::zoomCamera().
Referenced by resizeGL(), and GLWidgetGraphicsView::wheelEvent().
 {
     if (!ssl->g->isGraphicsEnabled()) return;
     ssl->g->zoomCamera(-event->delta()*0.002);
     update3DCursor(event->x(),event->y());
 }
void GLWidget::yellowRobotsMenuTriggered (QAction * act) slot
Definition at line 530 of file glwidget.cpp.
References reform().
Referenced by GLWidget().
 {
     reform(1,act->text());
 }
Friends And Related Function Documentation
friend class GLWidgetGraphicsView friend
Definition at line 105 of file glwidget.h.
Field Documentation
QAction* GLWidget::actionBB protected
Definition at line 65 of file glwidget.h.
QWidgetAction* GLWidget::actionColorPicker protected
Definition at line 67 of file glwidget.h.
QAction* GLWidget::actionFlipH protected
Definition at line 64 of file glwidget.h.
Referenced by flipImage(), and GLWidget().
QAction* GLWidget::actionFlipV protected
Definition at line 63 of file glwidget.h.
Referenced by flipImage(), and GLWidget().
QAction* GLWidget::actionOn protected
Definition at line 66 of file glwidget.h.
Referenced by GLWidget(), and mainDraw().
bool GLWidget::ALLOW_QPAINTER protected
Definition at line 55 of file glwidget.h.
Referenced by GLWidget(), mainDraw(), myGLinit(), and paintEvent().
bool GLWidget::alt
Definition at line 56 of file glwidget.h.
Referenced by GLWidget(), keyPressEvent(), and keyReleaseEvent().
bool GLWidget::altTrigger
Definition at line 56 of file glwidget.h.
Referenced by GLWidget().
QMenu * GLWidget::ballpopup
Definition at line 41 of file glwidget.h.
Referenced by GLWidget(), and mousePressEvent().
QMenu* GLWidget::blueRobotsMenu
Definition at line 42 of file glwidget.h.
Referenced by MainWindow::customFPS(), and GLWidget().
FrameCounter GLWidget::c_draw
Definition at line 96 of file glwidget.h.
Referenced by mainDraw().
FrameCounter GLWidget::c_loop
Definition at line 97 of file glwidget.h.
QMenu* GLWidget::cameraMenu
Definition at line 53 of file glwidget.h.
Referenced by MainWindow::customFPS(), and GLWidget().
int GLWidget::cammode
Definition at line 54 of file glwidget.h.
Referenced by changeCameraMode(), GLWidget(), lockCameraToBall(), lockCameraToRobot(), and paintGL().
ConfigWidget* GLWidget::cfg
Definition at line 38 of file glwidget.h.
Referenced by changeCameraMode(), GLWidget(), keyPressEvent(), mousePressEvent(), moveBall(), moveBallHere(), moveCurrentRobot(), moveRobot(), MainWindow::restartSimulator(), step(), and unselectRobot().
QAction* GLWidget::changeCamModeAct
Definition at line 52 of file glwidget.h.
Referenced by GLWidget().
double GLWidget::chipAngle
Definition at line 58 of file glwidget.h.
Referenced by GLWidget(), and mousePressEvent().
bool GLWidget::chiping
Definition at line 57 of file glwidget.h.
Referenced by GLWidget(), keyPressEvent(), and mousePressEvent().
int GLWidget::clicked_robot private
Definition at line 99 of file glwidget.h.
Referenced by mousePressEvent(), moveRobot(), and selectRobot().
bool GLWidget::ctrl
Definition at line 56 of file glwidget.h.
Referenced by GLWidget(), keyPressEvent(), keyReleaseEvent(), and mouseMoveEvent().
int GLWidget::Current_robot
Definition at line 54 of file glwidget.h.
Referenced by MainWindow::changeCurrentRobot(), MainWindow::changeCurrentTeam(), MainWindow::customFPS(), GLWidget(), keyPressEvent(), lockCameraToRobot(), moveCurrentRobot(), moveRobotHere(), paintGL(), resetCurrentRobot(), resetRobot(), selectRobot(), MainWindow::setCurrentRobotPosition(), switchRobotOnOff(), unselectRobot(), MainWindow::update(), and MainWindow::updateRobotLabel().
int GLWidget::Current_team
Definition at line 54 of file glwidget.h.
Referenced by MainWindow::changeCurrentRobot(), MainWindow::changeCurrentTeam(), MainWindow::customFPS(), GLWidget(), keyPressEvent(), lockCameraToRobot(), moveCurrentRobot(), moveRobotHere(), paintGL(), resetCurrentRobot(), resetRobot(), selectRobot(), MainWindow::setCurrentRobotPosition(), switchRobotOnOff(), unselectRobot(), MainWindow::update(), and MainWindow::updateRobotLabel().
bool GLWidget::first_time private
Definition at line 101 of file glwidget.h.
Referenced by GLWidget(), and step().
RobotsFomation* GLWidget::forms[6]
Definition at line 40 of file glwidget.h.
Referenced by GLWidget(), reform(), and MainWindow::restartSimulator().
int GLWidget::frames private
Definition at line 100 of file glwidget.h.
Referenced by GLWidget(), and step().
bool GLWidget::fullScreen
Definition at line 59 of file glwidget.h.
Referenced by GLWidget(), keyPressEvent(), and MainWindow::toggleFullScreen().
bool GLWidget::kickingball
Definition at line 56 of file glwidget.h.
Referenced by GLWidget(), keyPressEvent(), and mousePressEvent().
double GLWidget::kickpower
Definition at line 58 of file glwidget.h.
Referenced by GLWidget(), keyPressEvent(), and mousePressEvent().
long long GLWidget::last_frame protected
Definition at line 58 of file glwidget.h.
QPoint GLWidget::lastPos private
Definition at line 104 of file glwidget.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
int GLWidget::lockedIndex
Definition at line 55 of file glwidget.h.
Referenced by lockCameraToRobot(), and paintGL().
QAction* GLWidget::lockToBallAct
Definition at line 47 of file glwidget.h.
Referenced by GLWidget().
QAction* GLWidget::lockToRobotAct
Definition at line 49 of file glwidget.h.
Referenced by GLWidget().
dReal GLWidget::m_fps private
Definition at line 103 of file glwidget.h.
Referenced by getFPS(), and step().
QMenu * GLWidget::mainpopup
Definition at line 41 of file glwidget.h.
Referenced by GLWidget(), and mousePressEvent().
QPoint GLWidget::mouseStart protected
Definition at line 60 of file glwidget.h.
Referenced by mouseAction().
double GLWidget::mouseStartPanX protected
Definition at line 61 of file glwidget.h.
Referenced by mouseAction().
double GLWidget::mouseStartPanY protected
Definition at line 62 of file glwidget.h.
Referenced by mouseAction().
QAction* GLWidget::moveBallAct
Definition at line 46 of file glwidget.h.
Referenced by GLWidget().
QAction* GLWidget::moveBallHereAct
Definition at line 50 of file glwidget.h.
Referenced by GLWidget().
QAction* GLWidget::moveRobotAct
Definition at line 43 of file glwidget.h.
Referenced by GLWidget().
QAction* GLWidget::moveRobotHereAct
Definition at line 51 of file glwidget.h.
Referenced by GLWidget().
int GLWidget::moving_robot_id private
Definition at line 99 of file glwidget.h.
Referenced by mousePressEvent(), moveCurrentRobot(), moveRobot(), and unselectRobot().
QAction* GLWidget::onOffRobotAct
Definition at line 48 of file glwidget.h.
Referenced by GLWidget(), mousePressEvent(), reform(), and switchRobotOnOff().
RingBuffer<FrameData>* GLWidget::rb_bb protected
Definition at line 80 of file glwidget.h.
Referenced by GLWidget().
QTime GLWidget::rendertimer private
Definition at line 102 of file glwidget.h.
Referenced by step().
QAction* GLWidget::resetRobotAct
Definition at line 45 of file glwidget.h.
Referenced by GLWidget().
QMenu* GLWidget::robpopup
Definition at line 41 of file glwidget.h.
Referenced by GLWidget(), and mousePressEvent().
QAction* GLWidget::selectRobotAct
Definition at line 44 of file glwidget.h.
Referenced by GLWidget().
SSLWorld* GLWidget::ssl
Definition at line 39 of file glwidget.h.
Referenced by MainWindow::changeBallDamping(), MainWindow::changeBallGroundSurface(), MainWindow::changeBallMass(), changeCameraMode(), MainWindow::changeCurrentRobot(), MainWindow::changeCurrentTeam(), MainWindow::changeGravity(), MainWindow::customFPS(), GLWidget(), initializeGL(), keyPressEvent(), keyReleaseEvent(), mouseMoveEvent(), mousePressEvent(), moveBall(), moveBallHere(), moveCurrentRobot(), moveRobot(), moveRobotHere(), paintGL(), putBall(), MainWindow::recvActions(), reform(), resetCurrentRobot(), resetRobot(), MainWindow::restartSimulator(), MainWindow::setCurrentRobotPosition(), step(), switchRobotOnOff(), unselectRobot(), MainWindow::update(), update3DCursor(), MainWindow::updateRobotLabel(), and wheelEvent().
VisionStack* GLWidget::stack protected
Definition at line 59 of file glwidget.h.
Referenced by callHelp(), GLWidget(), mouseAction(), and resizeGL().
int GLWidget::state private
Definition at line 98 of file glwidget.h.
Referenced by fsm.StateMachine::corresponding_ancestor_state(), GLWidget(), kubs.kubs.kubs::has_ball(), fsm.StateMachine::is_in_state(), mousePressEvent(), moveBall(), moveCurrentRobot(), moveRobot(), fsm.StateMachine::spin(), fsm.StateMachine::transition(), unselectRobot(), and kubs.kubs.kubs::update_state().
VideoStats GLWidget::stats
Definition at line 95 of file glwidget.h.
QTime GLWidget::time private
Definition at line 102 of file glwidget.h.
Referenced by step().
int GLWidget::vpH protected
Definition at line 57 of file glwidget.h.
Referenced by mouseAction(), myGLdraw(), and setupViewPort().
int GLWidget::vpW protected
Definition at line 56 of file glwidget.h.
Referenced by mouseAction(), myGLdraw(), and setupViewPort().
QMenu * GLWidget::yellowRobotsMenu
Definition at line 42 of file glwidget.h.
Referenced by MainWindow::customFPS(), and GLWidget().
Zoom GLWidget::zoom
Definition at line 94 of file glwidget.h.
Referenced by callHelp(), callZoomFit(), callZoomNormal(), flipImage(), mainDraw(), mouseAction(), myGLdraw(), and resizeGL().
The documentation for this class was generated from the following files:
grSim/include/glwidget.h
grSim/src/glwidget.cpp
ssl-vision/build/src/app/gui/moc_glwidget.cxx