Documentation: VisionStack Class Reference
VisionStack Class Reference
Base-class of a single-threaded / single-camera vision stack.
#include <visionstack.h>
Public Member Functions
VisionStack (string _name, RenderOptions *_opts)
virtual ~VisionStack ()
VarList * getSettings ()
virtual string getName ()
virtual string getSettingsFileName ()
void process (FrameData *data)
void postProcess (FrameData *data)
void updateTimingStatistics ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
Data Fields
vector< VisionPlugin * > stack
Protected Attributes
string name
RenderOptions * opts
VarList * settings
Detailed Description
Base-class of a single-threaded / single-camera vision stack.
Author
Stefan Zickler, (C) 2008
Definition at line 34 of file visionstack.h.
Constructor & Destructor Documentation
VisionStack::VisionStack (string _name, RenderOptions * _opts)
Definition at line 23 of file visionstack.cpp.
References name, opts, and settings.
{
   name=_name;
   opts=_opts;
   //counter_proc=0.0;
   //counter_post_proc=0.0;
   settings=new VarList("Global");
 }
VisionStack::~VisionStack () virtual
Definition at line 31 of file visionstack.cpp.
References settings.
{
   delete settings;
 }
Member Function Documentation
string VisionStack::getName () virtual
Definition at line 35 of file visionstack.cpp.
References name.
{
   return name;
 }
VarList * VisionStack::getSettings ()
Definition at line 39 of file visionstack.cpp.
References settings.
Referenced by MainWindow::MainWindow().
{
   return settings;
 }
string VisionStack::getSettingsFileName () virtual
Reimplemented in StackRoboCupSSL.
Definition at line 43 of file visionstack.cpp.
References name.
{
   //this can be done dynamically based on camera-id's etc...
   return name;
 }
void VisionStack::keyPressEvent (QKeyEvent * event) virtual
Definition at line 94 of file visionstack.cpp.
References velocity.pid_::i, VisionPlugin::keyPressEvent(), VisionPlugin::lock(), stack, and VisionPlugin::unlock().
Referenced by GLWidget::callHelp().
{
   unsigned int n=stack.size();
   VisionPlugin * p;
   for (unsigned int i=0;i<n;i++) {
     p=stack[i];
     p->lock();
     p->keyPressEvent(event);
     p->unlock();
     if (event->isAccepted()) return;
   }
 }
void VisionStack::mouseMoveEvent (QMouseEvent * event, pixelloc loc) virtual
Definition at line 130 of file visionstack.cpp.
References velocity.pid_::i, VisionPlugin::lock(), VisionPlugin::mouseMoveEvent(), stack, and VisionPlugin::unlock().
Referenced by GLWidget::mouseAction().
{
   unsigned int n=stack.size();
   VisionPlugin * p;
   for (unsigned int i=0;i<n;i++) {
     p=stack[i];
     p->lock();
     p->mouseMoveEvent(event,loc);
     p->unlock();
     if (event->isAccepted()) return;
   }
 }
void VisionStack::mousePressEvent (QMouseEvent * event, pixelloc loc) virtual
Definition at line 106 of file visionstack.cpp.
References velocity.pid_::i, VisionPlugin::lock(), VisionPlugin::mousePressEvent(), stack, and VisionPlugin::unlock().
Referenced by GLWidget::mouseAction().
{
   unsigned int n=stack.size();
   VisionPlugin * p;
   for (unsigned int i=0;i<n;i++) {
     p=stack[i];
     p->lock();
     p->mousePressEvent(event, loc);
     p->unlock();
     if (event->isAccepted()) return;
   }
 }
void VisionStack::mouseReleaseEvent (QMouseEvent * event, pixelloc loc) virtual
Definition at line 118 of file visionstack.cpp.
References velocity.pid_::i, VisionPlugin::lock(), VisionPlugin::mouseReleaseEvent(), stack, and VisionPlugin::unlock().
Referenced by GLWidget::mouseAction().
{
   unsigned int n=stack.size();
   VisionPlugin * p;
   for (unsigned int i=0;i<n;i++) {
     p=stack[i];
     p->lock();
     p->mouseReleaseEvent(event,loc);
     p->unlock();
     if (event->isAccepted()) return;
   }
 }
void VisionStack::postProcess (FrameData * data)
Definition at line 73 of file visionstack.cpp.
References GetTimeSec(), velocity.pid_::i, VisionPlugin::lock(), opts, VisionPlugin::postProcess(), VisionPlugin::setTimePostProcessing(), stack, and VisionPlugin::unlock().
Referenced by CaptureThread::run().
{
   unsigned int n=stack.size();
   double a=0.0;
   double b=0.0;
   VisionPlugin * p;
   for (unsigned int i=0;i<n;i++) {
     p=stack[i];
     p->lock();
     a=GetTimeSec();
     p->postProcess(data,opts);
     b=GetTimeSec();
     p->setTimePostProcessing(b-a);
     p->unlock();
   }
   //counter_post_proc+=1.0;
 }
void VisionStack::process (FrameData * data)
Definition at line 48 of file visionstack.cpp.
References VisionPlugin::getName(), VisionPlugin::getTimeProcessing(), GetTimeSec(), velocity.pid_::i, VisionPlugin::lock(), opts, VisionPlugin::process(), VisionPlugin::setTimeProcessing(), stack, and VisionPlugin::unlock().
Referenced by CaptureThread::run().
{
   double a=0.0;
   double b=0.0;
   unsigned int n=stack.size();
   VisionPlugin * p;
   double total=0.0;
   bool show_timing = false;
   if (show_timing) printf("----------\n");
   for (unsigned int i=0;i<n;i++) {
     p=stack[i];
     p->lock();
     a=GetTimeSec();
     p->process(data,opts);
     b=GetTimeSec();
     p->setTimeProcessing(b-a);
     total+=(p->getTimeProcessing());
     if (show_timing) {
       printf("Plugin %s: %fms\n",p->getName().c_str(),  p->getTimeProcessing() * 1000.0);
     }
     p->unlock();
   }
   if (show_timing) printf("Total time: %fms\n",total * 1000.0);
   //counter_proc+=1.0;
 }
void VisionStack::updateTimingStatistics ()
Definition at line 90 of file visionstack.cpp.
Referenced by CaptureThread::run().
{
 }
void VisionStack::wheelEvent (QWheelEvent * event, pixelloc loc) virtual
Definition at line 142 of file visionstack.cpp.
References velocity.pid_::i, VisionPlugin::lock(), stack, VisionPlugin::unlock(), and VisionPlugin::wheelEvent().
Referenced by GLWidget::resizeGL().
{
   unsigned int n=stack.size();
   VisionPlugin * p;
   for (unsigned int i=0;i<n;i++) {
     p=stack[i];
     p->lock();
     p->wheelEvent(event,loc);
     p->unlock();
     if (event->isAccepted()) return;
   }
 }
Field Documentation
string VisionStack::name protected
Definition at line 36 of file visionstack.h.
Referenced by getName(), getSettingsFileName(), and VisionStack().
RenderOptions* VisionStack::opts protected
Definition at line 37 of file visionstack.h.
Referenced by postProcess(), process(), and VisionStack().
VarList* VisionStack::settings protected
Definition at line 38 of file visionstack.h.
Referenced by getSettings(), StackRoboCupSSL::StackRoboCupSSL(), VisionStack(), and ~VisionStack().
vector<VisionPlugin *> VisionStack::stack
Definition at line 44 of file visionstack.h.
Referenced by keyPressEvent(), MainWindow::MainWindow(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), postProcess(), process(), StackRoboCupSSL::StackRoboCupSSL(), and wheelEvent().
The documentation for this class was generated from the following files:
ssl-vision/src/app/stacks/visionstack.h
ssl-vision/src/app/stacks/visionstack.cpp