Documentation: vision_comm/src/class_node.cpp File Reference
class_node.cpp File Reference
#include "class_node.hpp"
#include <climits>
#include <string>
Functions
bool is_valid (const krssg_ssl_msgs::SSL_DetectionFrame::ConstPtr &vmsg)
void print (Pose2D &p)
void print (vector< Pose2D > p)
void print (vector< bool > p)
Variables
const int HALF_FIELD_MAXX = 3000
const int HALF_FIELD_MAXY = 2000
Function Documentation
bool is_valid (const krssg_ssl_msgs::SSL_DetectionFrame::ConstPtr & vmsg)
Definition at line 8 of file class_node.cpp.
References BeliefState::BeliefState().
{
    if(vmsg->robots_yellow.size() == 0 && vmsg->robots_blue.size() == 0)
       return false;
    if(vmsg->balls.size() == 0)
       return false;
    return true;
 }
void print (Pose2D & p)
Definition at line 176 of file class_node.cpp.
Referenced by BeliefState::print(), and print().
                       {
    cout<<"x: "<<p.x<<" y: "<<p.y<<endl;
 }
void print (vector< Pose2D > p)
Definition at line 180 of file class_node.cpp.
References velocity.pid_::i, and print().
{
    for(int i = 0; i < p.size(); i++) {
       cout<<"i: \t";
       print(p[i]);
    }
 }
void print (vector< bool > p)
Definition at line 187 of file class_node.cpp.
References velocity.pid_::i.
{
    for(int i=0;i<p.size();i++) {
       cout<<"i: \t"<<p[i]<<endl;
    }
 }
Variable Documentation
const int HALF_FIELD_MAXX = 3000
Definition at line 5 of file class_node.cpp.
Referenced by BeliefState::update_frame().
const int HALF_FIELD_MAXY = 2000
Definition at line 6 of file class_node.cpp.
Referenced by BeliefState::update_frame().