Documentation: ValueVis Class Reference
ValueVis Class Reference
#include <ValueVis.h>
Public Member Functions
ValueVis (VarType *_dt)
virtual ~ValueVis ()
void setupUi ()
void update (bool recurse=true)
Protected Attributes
VarType * dt
QVBoxLayout * layout
QLabel * label
QLabel * title
QList< ValueVis * > * children
Detailed Description
Definition at line 28 of file ValueVis.h.
Constructor & Destructor Documentation
ValueVis::ValueVis (VarType * _dt)
Definition at line 22 of file ValueVis.cpp.
References children, dt, setupUi(), and update().
Referenced by setupUi().
 {
   dt=_dt;
   children = new QList<ValueVis *>();
   setupUi();
   update();
 }
ValueVis::~ValueVis () virtual
Definition at line 56 of file ValueVis.cpp.
 {
 }
Member Function Documentation
void ValueVis::setupUi ()
Definition at line 30 of file ValueVis.cpp.
References children, dt, velocity.pid_::i, label, layout, title, v, and ValueVis().
Referenced by GUI.self_RRT.MainWindow::__init__(), GUI.ompl_gui.MainWindow::__init__(), and ValueVis().
{
   QVBoxLayout * layout = new QVBoxLayout();
   layout->setMargin(2);
   layout->setSpacing(2);
   title = new QLabel();
   layout->addWidget(title);
   setFrameStyle(QFrame::StyledPanel);
   layout->setSizeConstraint(QLayout::SetMinimumSize);
   setLayout(layout);
   if (dt!=0) {
     if (dt->getType() == DT_LIST) {
       vector<VarType *> v = dt->getChildren();
       for (unsigned int i=0;i<v.size();i++) {
         children->append(new ValueVis(v[i]));
         layout->addWidget(children->last());
       }
     } else {
       label = new QLabel();
       label->setAlignment(Qt::AlignRight);
       layout->addWidget(label);
     }
   }
 }
void ValueVis::update (bool recurse = true)
Definition at line 61 of file ValueVis.cpp.
References dt, label, and title.
Referenced by ValueVis().
{
   QFont font=title->font();
   font.setPointSize(8);
   title->setFont(font);
 //  this->setVisible(dt->areFlagsSet( VARTYPE_FLAG_HIDDEN));
   if (dt!=0) {
     title->setText(QString::fromStdString(dt->getName()));
     if (dt->getType() == DT_LIST) {
       if (recurse) {
         /*vector<VarType *> v = dt->getChildren();
         for (unsigned int i=0;i<v.size();i++) {
           layout->addWidget(new ValueVis(v[i]));
         }*/
         //for (int i=0;i<children.size();i++) {
         //  children[i]->update(recurse);
         //}
       }
     } else {
       font=label->font();
       font.setPointSize(9);
       font.setBold(true);
       label->setFont(font);
       label->setText(QString::fromStdString(dt->getString()));
     }
   } else {
     title->setText("no title");
   }
 }
Field Documentation
QList<ValueVis *>* ValueVis::children protected
Definition at line 35 of file ValueVis.h.
Referenced by setupUi(), and ValueVis().
VarType* ValueVis::dt protected
Definition at line 31 of file ValueVis.h.
Referenced by setupUi(), update(), and ValueVis().
QLabel* ValueVis::label protected
Definition at line 33 of file ValueVis.h.
Referenced by setupUi(), and update().
QVBoxLayout* ValueVis::layout protected
Definition at line 32 of file ValueVis.h.
Referenced by setupUi().
QLabel* ValueVis::title protected
Definition at line 34 of file ValueVis.h.
Referenced by setupUi(), and update().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/gui/experimental/ValueVis.h
ssl-vision/src/shared/vartypes/gui/experimental/ValueVis.cpp