Documentation: Protobuf.GrSimPacket.grSim_Packet Class Reference
Protobuf.GrSimPacket.grSim_Packet Class Reference
Data Structures
class Builder
Public Member Functions
grSim_Packet getDefaultInstanceForType ()
boolean hasCommands ()
GrSimCommands.grSim_Commands getCommands ()
GrSimCommands.grSim_CommandsOrBuilder getCommandsOrBuilder ()
boolean hasReplacement ()
GrSimReplacement.grSim_Replacement getReplacement ()
GrSimReplacement.grSim_ReplacementOrBuilder getReplacementOrBuilder ()
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static grSim_Packet getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static GrSimPacket.grSim_Packet parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimPacket.grSim_Packet parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimPacket.grSim_Packet parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimPacket.grSim_Packet parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static GrSimPacket.grSim_Packet parseFrom (java.io.InputStream input) throws java.io.IOException
static GrSimPacket.grSim_Packet parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static GrSimPacket.grSim_Packet parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static GrSimPacket.grSim_Packet parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static GrSimPacket.grSim_Packet parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static GrSimPacket.grSim_Packet parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (GrSimPacket.grSim_Packet prototype)
Static Public Attributes
static final int COMMANDS_FIELD_NUMBER = 1
static final int REPLACEMENT_FIELD_NUMBER = 2
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
grSim_Packet (Builder builder)
grSim_Packet (boolean noInit)
void initFields ()
Private Attributes
int bitField0_
GrSimCommands.grSim_Commands commands_
GrSimReplacement.grSim_Replacement replacement_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final grSim_Packet defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 23 of file GrSimPacket.java.
Constructor & Destructor Documentation
Protobuf.GrSimPacket.grSim_Packet.grSim_Packet (Builder builder) inline private
Definition at line 27 of file GrSimPacket.java.
{
       super(builder);
     }
Protobuf.GrSimPacket.grSim_Packet.grSim_Packet (boolean noInit) inline private
Definition at line 30 of file GrSimPacket.java.
 {}
Member Function Documentation
GrSimCommands.grSim_Commands Protobuf.GrSimPacket.grSim_Packet.getCommands () inline
Implements Protobuf.GrSimPacket.grSim_PacketOrBuilder.
Definition at line 58 of file GrSimPacket.java.
{
       return commands_;
     }
GrSimCommands.grSim_CommandsOrBuilder Protobuf.GrSimPacket.grSim_Packet.getCommandsOrBuilder () inline
Implements Protobuf.GrSimPacket.grSim_PacketOrBuilder.
Definition at line 61 of file GrSimPacket.java.
{
       return commands_;
     }
static grSim_Packet Protobuf.GrSimPacket.grSim_Packet.getDefaultInstance () inline static
Definition at line 33 of file GrSimPacket.java.
Referenced by Protobuf.GrSimPacket.grSim_Packet.Builder.getDefaultInstanceForType(), and Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom().
{
       return defaultInstance;
     }
grSim_Packet Protobuf.GrSimPacket.grSim_Packet.getDefaultInstanceForType () inline
Definition at line 37 of file GrSimPacket.java.
{
       return defaultInstance;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimPacket.grSim_Packet.getDescriptor () inline static
Definition at line 42 of file GrSimPacket.java.
References Protobuf.GrSimPacket.internal_static_grSim_Packet_descriptor.
Referenced by Protobuf.GrSimPacket.grSim_Packet.Builder.getDescriptorForType().
{
       return GrSimPacket.internal_static_grSim_Packet_descriptor;
     }
GrSimReplacement.grSim_Replacement Protobuf.GrSimPacket.grSim_Packet.getReplacement () inline
Implements Protobuf.GrSimPacket.grSim_PacketOrBuilder.
Definition at line 71 of file GrSimPacket.java.
{
       return replacement_;
     }
GrSimReplacement.grSim_ReplacementOrBuilder Protobuf.GrSimPacket.grSim_Packet.getReplacementOrBuilder () inline
Implements Protobuf.GrSimPacket.grSim_PacketOrBuilder.
Definition at line 74 of file GrSimPacket.java.
{
       return replacement_;
     }
int Protobuf.GrSimPacket.grSim_Packet.getSerializedSize () inline
Definition at line 116 of file GrSimPacket.java.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(1, commands_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(2, replacement_);
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
boolean Protobuf.GrSimPacket.grSim_Packet.hasCommands () inline
Implements Protobuf.GrSimPacket.grSim_PacketOrBuilder.
Definition at line 55 of file GrSimPacket.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
boolean Protobuf.GrSimPacket.grSim_Packet.hasReplacement () inline
Implements Protobuf.GrSimPacket.grSim_PacketOrBuilder.
Definition at line 68 of file GrSimPacket.java.
{
       return ((bitField0_ & 0x00000002) == 0x00000002);
     }
void Protobuf.GrSimPacket.grSim_Packet.initFields () inline private
Definition at line 78 of file GrSimPacket.java.
References Protobuf.GrSimCommands.grSim_Commands.getDefaultInstance(), and Protobuf.GrSimReplacement.grSim_Replacement.getDefaultInstance().
Referenced by Protobuf.GrSimPacket.grSim_Packet.Builder.getReplacementFieldBuilder().
{
       commands_ = GrSimCommands.grSim_Commands.getDefaultInstance();
       replacement_ = GrSimReplacement.grSim_Replacement.getDefaultInstance();
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.GrSimPacket.grSim_Packet.internalGetFieldAccessorTable () inline protected
Definition at line 47 of file GrSimPacket.java.
References Protobuf.GrSimPacket.internal_static_grSim_Packet_fieldAccessorTable.
{
       return GrSimPacket.internal_static_grSim_Packet_fieldAccessorTable;
     }
final boolean Protobuf.GrSimPacket.grSim_Packet.isInitialized () inline
Definition at line 83 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_PacketOrBuilder.getCommands(), Protobuf.GrSimPacket.grSim_PacketOrBuilder.getReplacement(), Protobuf.GrSimPacket.grSim_PacketOrBuilder.hasCommands(), and Protobuf.GrSimPacket.grSim_PacketOrBuilder.hasReplacement().
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (hasCommands()) {
         if (!getCommands().isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       if (hasReplacement()) {
         if (!getReplacement().isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.GrSimPacket.grSim_Packet.newBuilder () inline static
Definition at line 208 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.Builder.create().
Referenced by Client.Conection.send().
 { return Builder.create(); }
static Builder Protobuf.GrSimPacket.grSim_Packet.newBuilder (GrSimPacket.grSim_Packet prototype) inline static
Definition at line 210 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.GrSimPacket.grSim_Packet.newBuilderForType () inline
Definition at line 209 of file GrSimPacket.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.GrSimPacket.grSim_Packet.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 216 of file GrSimPacket.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 175 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 184 of file GrSimPacket.java.
References Protobuf.GrSimPacket.grSim_Packet.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 141 of file GrSimPacket.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 146 of file GrSimPacket.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 153 of file GrSimPacket.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 157 of file GrSimPacket.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 164 of file GrSimPacket.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 168 of file GrSimPacket.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 195 of file GrSimPacket.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static GrSimPacket.grSim_Packet Protobuf.GrSimPacket.grSim_Packet.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 200 of file GrSimPacket.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.GrSimPacket.grSim_Packet.toBuilder () inline
Definition at line 213 of file GrSimPacket.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.GrSimPacket.grSim_Packet.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 136 of file GrSimPacket.java.
{
       return super.writeReplace();
     }
void Protobuf.GrSimPacket.grSim_Packet.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 103 of file GrSimPacket.java.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeMessage(1, commands_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         output.writeMessage(2, replacement_);
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
int Protobuf.GrSimPacket.grSim_Packet.bitField0_ private
Definition at line 51 of file GrSimPacket.java.
GrSimCommands.grSim_Commands Protobuf.GrSimPacket.grSim_Packet.commands_ private
Definition at line 54 of file GrSimPacket.java.
Referenced by Protobuf.GrSimPacket.grSim_Packet.Builder.buildPartial().
final int Protobuf.GrSimPacket.grSim_Packet.COMMANDS_FIELD_NUMBER = 1 static
Definition at line 53 of file GrSimPacket.java.
final grSim_Packet Protobuf.GrSimPacket.grSim_Packet.defaultInstance static private
Definition at line 32 of file GrSimPacket.java.
byte Protobuf.GrSimPacket.grSim_Packet.memoizedIsInitialized = -1 private
Definition at line 82 of file GrSimPacket.java.
int Protobuf.GrSimPacket.grSim_Packet.memoizedSerializedSize = -1 private
Definition at line 115 of file GrSimPacket.java.
GrSimReplacement.grSim_Replacement Protobuf.GrSimPacket.grSim_Packet.replacement_ private
Definition at line 67 of file GrSimPacket.java.
final int Protobuf.GrSimPacket.grSim_Packet.REPLACEMENT_FIELD_NUMBER = 2 static
Definition at line 66 of file GrSimPacket.java.
final long Protobuf.GrSimPacket.grSim_Packet.serialVersionUID = 0L static private
Definition at line 134 of file GrSimPacket.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimPacket.java