Documentation: RoboCup2014Legacy::Geometry::SSL_GeometryData Class Reference
RoboCup2014Legacy::Geometry::SSL_GeometryData Class Reference
#include <messages_robocup_ssl_geometry_legacy.pb.h>
Public Member Functions
SSL_GeometryData ()
virtual ~SSL_GeometryData ()
SSL_GeometryData (const SSL_GeometryData &from)
SSL_GeometryData & operator= (const SSL_GeometryData &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_GeometryData *other)
SSL_GeometryData * New () const PROTOBUF_FINAL
SSL_GeometryData * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_GeometryData &from)
void MergeFrom (const SSL_GeometryData &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
int calib_size () const
void clear_calib ()
const ::SSL_GeometryCameraCalibration & calib (int index) const
::SSL_GeometryCameraCalibration * mutable_calib (int index)
::SSL_GeometryCameraCalibration * add_calib ()
::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration > * mutable_calib ()
const ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration > & calib () const
bool has_field () const
void clear_field ()
const ::RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize & field () const
::RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize * release_field ()
::RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize * mutable_field ()
void set_allocated_field (::RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize *field)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_GeometryData & default_instance ()
static void InitAsDefaultInstance ()
static const SSL_GeometryData * internal_default_instance ()
Static Public Attributes
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
static const int kCalibFieldNumber = 2
static const int kFieldFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_GeometryData *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_field ()
void clear_has_field ()
friend void::protobuf_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto::InitDefaultsSSL_GeometryDataImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration > calib_
::RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize * field_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto::TableStruct
void swap (SSL_GeometryData &a, SSL_GeometryData &b)
Detailed Description
Definition at line 313 of file messages_robocup_ssl_geometry_legacy.pb.h.
Constructor & Destructor Documentation
RoboCup2014Legacy::Geometry::SSL_GeometryData::SSL_GeometryData ()
virtual RoboCup2014Legacy::Geometry::SSL_GeometryData::~SSL_GeometryData () virtual
RoboCup2014Legacy::Geometry::SSL_GeometryData::SSL_GeometryData (const SSL_GeometryData & from)
Member Function Documentation
SSL_GeometryCameraCalibration * SSL_GeometryData::add_calib () inline
Definition at line 853 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   // @@protoc_insertion_point(field_add:RoboCup2014Legacy.Geometry.SSL_GeometryData.calib)
   return calib_.Add();
 }
size_t RoboCup2014Legacy::Geometry::SSL_GeometryData::ByteSizeLong () const
const ::SSL_GeometryCameraCalibration & SSL_GeometryData::calib (int index) const inline
Definition at line 845 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryData.calib)
   return calib_.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::SSL_GeometryCameraCalibration > & SSL_GeometryData::calib () const inline
Definition at line 863 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_list:RoboCup2014Legacy.Geometry.SSL_GeometryData.calib)
   return calib_;
 }
int SSL_GeometryData::calib_size () const inline
Definition at line 842 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return calib_.size();
 }
void RoboCup2014Legacy::Geometry::SSL_GeometryData::Clear ()
void RoboCup2014Legacy::Geometry::SSL_GeometryData::clear_calib ()
void SSL_GeometryData::clear_field () inline
Definition at line 797 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   if (field_ != NULL) field_->Clear();
   clear_has_field();
 }
void SSL_GeometryData::clear_has_field () inline private
Definition at line 794 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] &= ~0x00000001u;
 }
void RoboCup2014Legacy::Geometry::SSL_GeometryData::CopyFrom (const ::google::protobuf::Message & from)
Referenced by RoboCupSSLServer::sendLegacyMessage().
void RoboCup2014Legacy::Geometry::SSL_GeometryData::CopyFrom (const SSL_GeometryData & from)
static const SSL_GeometryData& RoboCup2014Legacy::Geometry::SSL_GeometryData::default_instance () static
static const ::google::protobuf::Descriptor* RoboCup2014Legacy::Geometry::SSL_GeometryData::descriptor () static
const ::RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize & SSL_GeometryData::field () const inline
Definition at line 801 of file messages_robocup_ssl_geometry_legacy.pb.h.
References RoboCup2014Legacy::Geometry::_SSL_GeometryFieldSize_default_instance_.
{
   const ::RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize* p = field_;
   // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Geometry.SSL_GeometryData.field)
   return p != NULL ? *p : *reinterpret_cast<const ::RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize*>(
       &::RoboCup2014Legacy::Geometry::_SSL_GeometryFieldSize_default_instance_);
 }
inline ::google::protobuf::Arena* RoboCup2014Legacy::Geometry::SSL_GeometryData::GetArenaNoVirtual () const inline private
Definition at line 388 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by operator=().
{
     return NULL;
   }
int RoboCup2014Legacy::Geometry::SSL_GeometryData::GetCachedSize () const inline
Definition at line 381 of file messages_robocup_ssl_geometry_legacy.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata RoboCup2014Legacy::Geometry::SSL_GeometryData::GetMetadata () const
bool SSL_GeometryData::has_field () const inline
Definition at line 788 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
static void RoboCup2014Legacy::Geometry::SSL_GeometryData::InitAsDefaultInstance () static
static const SSL_GeometryData* RoboCup2014Legacy::Geometry::SSL_GeometryData::internal_default_instance () inline static
Definition at line 350 of file messages_robocup_ssl_geometry_legacy.pb.h.
References RoboCup2014Legacy::Geometry::_SSL_GeometryData_default_instance_.
{
     return reinterpret_cast<const SSL_GeometryData*>(
                &_SSL_GeometryData_default_instance_);
   }
::google::protobuf::uint8* RoboCup2014Legacy::Geometry::SSL_GeometryData::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void RoboCup2014Legacy::Geometry::SSL_GeometryData::InternalSwap (SSL_GeometryData * other) private
bool RoboCup2014Legacy::Geometry::SSL_GeometryData::IsInitialized () const
void* RoboCup2014Legacy::Geometry::SSL_GeometryData::MaybeArenaPtr () const inline private
Definition at line 391 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
     return NULL;
   }
void RoboCup2014Legacy::Geometry::SSL_GeometryData::MergeFrom (const ::google::protobuf::Message & from)
void RoboCup2014Legacy::Geometry::SSL_GeometryData::MergeFrom (const SSL_GeometryData & from)
bool RoboCup2014Legacy::Geometry::SSL_GeometryData::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
SSL_GeometryCameraCalibration * SSL_GeometryData::mutable_calib (int index) inline
Definition at line 849 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_mutable:RoboCup2014Legacy.Geometry.SSL_GeometryData.calib)
   return calib_.Mutable(index);
 }
google::protobuf::RepeatedPtrField<::SSL_GeometryCameraCalibration > * SSL_GeometryData::mutable_calib () inline
Definition at line 858 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_mutable_list:RoboCup2014Legacy.Geometry.SSL_GeometryData.calib)
   return &calib_;
 }
RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize * SSL_GeometryData::mutable_field () inline
Definition at line 814 of file messages_robocup_ssl_geometry_legacy.pb.h.
Referenced by PluginLegacyPublishGeometry::sendGeometry().
{
   set_has_field();
   if (field_ == NULL) {
     field_ = new ::RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize;
   }
   // @@protoc_insertion_point(field_mutable:RoboCup2014Legacy.Geometry.SSL_GeometryData.field)
   return field_;
 }
inline ::google::protobuf::UnknownFieldSet* RoboCup2014Legacy::Geometry::SSL_GeometryData::mutable_unknown_fields () inline
Definition at line 342 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
SSL_GeometryData* RoboCup2014Legacy::Geometry::SSL_GeometryData::New () const inline
Definition at line 364 of file messages_robocup_ssl_geometry_legacy.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_GeometryData* RoboCup2014Legacy::Geometry::SSL_GeometryData::New (::google::protobuf::Arena * arena) const
SSL_GeometryData& RoboCup2014Legacy::Geometry::SSL_GeometryData::operator= (const SSL_GeometryData & from) inline
Definition at line 320 of file messages_robocup_ssl_geometry_legacy.pb.h.
References GetArenaNoVirtual().
{
     CopyFrom(from);
     return *this;
   }
RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize * SSL_GeometryData::release_field () inline
Definition at line 807 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   // @@protoc_insertion_point(field_release:RoboCup2014Legacy.Geometry.SSL_GeometryData.field)
   clear_has_field();
   ::RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize* temp = field_;
   field_ = NULL;
   return temp;
 }
void RoboCup2014Legacy::Geometry::SSL_GeometryData::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
void SSL_GeometryData::set_allocated_field (::RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize * field) inline
Definition at line 822 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
   if (message_arena == NULL) {
     delete field_;
   }
   if (field) {
     ::google::protobuf::Arena* submessage_arena = NULL;
     if (message_arena != submessage_arena) {
       field = ::google::protobuf::internal::GetOwnedMessage(
           message_arena, field, submessage_arena);
     }
     set_has_field();
   } else {
     clear_has_field();
   }
   field_ = field;
   // @@protoc_insertion_point(field_set_allocated:RoboCup2014Legacy.Geometry.SSL_GeometryData.field)
 }
void SSL_GeometryData::set_has_field () inline private
Definition at line 791 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
   _has_bits_[0] |= 0x00000001u;
 }
void RoboCup2014Legacy::Geometry::SSL_GeometryData::SetCachedSize (int size) const private
void RoboCup2014Legacy::Geometry::SSL_GeometryData::SharedCtor () private
void RoboCup2014Legacy::Geometry::SSL_GeometryData::SharedDtor () private
void RoboCup2014Legacy::Geometry::SSL_GeometryData::Swap (SSL_GeometryData * other)
const ::google::protobuf::UnknownFieldSet& RoboCup2014Legacy::Geometry::SSL_GeometryData::unknown_fields () const inline
Definition at line 339 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
RoboCup2014Legacy::Geometry::SSL_GeometryData::void::protobuf_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto::InitDefaultsSSL_GeometryDataImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto::TableStruct friend
Definition at line 433 of file messages_robocup_ssl_geometry_legacy.pb.h.
void swap (SSL_GeometryData & a, SSL_GeometryData & b) friend
Definition at line 358 of file messages_robocup_ssl_geometry_legacy.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int RoboCup2014Legacy::Geometry::SSL_GeometryData::_cached_size_ mutable private
Definition at line 430 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::internal::HasBits<1> RoboCup2014Legacy::Geometry::SSL_GeometryData::_has_bits_ private
Definition at line 429 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::internal::InternalMetadataWithArena RoboCup2014Legacy::Geometry::SSL_GeometryData::_internal_metadata_ private
Definition at line 428 of file messages_robocup_ssl_geometry_legacy.pb.h.
::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration > RoboCup2014Legacy::Geometry::SSL_GeometryData::calib_ private
Definition at line 431 of file messages_robocup_ssl_geometry_legacy.pb.h.
::RoboCup2014Legacy::Geometry::SSL_GeometryFieldSize* RoboCup2014Legacy::Geometry::SSL_GeometryData::field_ private
Definition at line 432 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryData::kCalibFieldNumber = 2 static
Definition at line 405 of file messages_robocup_ssl_geometry_legacy.pb.h.
const int RoboCup2014Legacy::Geometry::SSL_GeometryData::kFieldFieldNumber = 1 static
Definition at line 417 of file messages_robocup_ssl_geometry_legacy.pb.h.
PROTOBUF_CONSTEXPR int const RoboCup2014Legacy::Geometry::SSL_GeometryData::kIndexInFileMessages static
Initial value:
=
    1
Definition at line 354 of file messages_robocup_ssl_geometry_legacy.pb.h.
The documentation for this class was generated from the following file:
ssl-vision/build/messages_robocup_ssl_geometry_legacy.pb.h