Documentation: GlobalCaptureDC1394instance Class Reference
GlobalCaptureDC1394instance Class Reference
A singleton provider of a dc1394 lib context used for capturing with multiple threads.
#include <capturedc1394v2.h>
Public Member Functions
GlobalCaptureDC1394instance ()
~GlobalCaptureDC1394instance ()
dc1394_t * obtainInstance ()
bool removeInstance ()
Data Fields
QMutex mutex
Protected Attributes
char counter
dc1394_t * dc_instance
Private Member Functions
void lock ()
void unlock ()
Detailed Description
A singleton provider of a dc1394 lib context used for capturing with multiple threads.
Author
Stefan Zickler, (C) 2008
Definition at line 46 of file capturedc1394v2.h.
Constructor & Destructor Documentation
GlobalCaptureDC1394instance::GlobalCaptureDC1394instance () inline
Definition at line 49 of file capturedc1394v2.h.
References counter, dc_instance, and mutex.
{
     #ifndef VDATA_NO_QT
     #else
       pthread_mutex_init (&mutex);
     #endif
     counter=0;
     dc_instance=0;
   }
GlobalCaptureDC1394instance::~GlobalCaptureDC1394instance () inline
Definition at line 57 of file capturedc1394v2.h.
References mutex.
{
     #ifndef VDATA_NO_QT
     #else
       pthread_mutex_destroy (&mutex);
     #endif
   }
Member Function Documentation
void GlobalCaptureDC1394instance::lock () inline private
Definition at line 101 of file capturedc1394v2.h.
Referenced by obtainInstance(), and removeInstance().
               {
     #ifndef VDATA_NO_QT
       mutex.lock();
     #else
       pthread_mutex_lock();
     #endif
   }
dc1394_t* GlobalCaptureDC1394instance::obtainInstance () inline
Definition at line 72 of file capturedc1394v2.h.
References dc_instance, lock(), and unlock().
Referenced by GlobalCaptureDC1394instanceManager::obtainInstance().
{
     lock();
     if (counter == 0) {
       dc_instance=dc1394_new();
     }
     counter++;
     dc1394_t* inst=dc_instance;
     unlock();
     return inst;
   }
bool GlobalCaptureDC1394instance::removeInstance () inline
Definition at line 83 of file capturedc1394v2.h.
References lock(), and unlock().
Referenced by GlobalCaptureDC1394instanceManager::removeInstance().
{
     lock();
     counter--;
     bool was_last=false;
     if (counter == 0) {
       dc1394_free( dc_instance );
       was_last=true;
     }
     if (counter < 0) {
       fprintf(stderr,"WARNING: Attempting to remove more instances than have been created!\n");
       fflush(stderr);
       counter = 0;
     }
     unlock();
     return was_last;
   }
void GlobalCaptureDC1394instance::unlock () inline private
Definition at line 108 of file capturedc1394v2.h.
Referenced by obtainInstance(), and removeInstance().
                 {
     #ifndef VDATA_NO_QT
       mutex.unlock();
     #else
       pthread_mutex_unlock();
     #endif
   }
Field Documentation
char GlobalCaptureDC1394instance::counter protected
Definition at line 69 of file capturedc1394v2.h.
Referenced by GlobalCaptureDC1394instance().
dc1394_t* GlobalCaptureDC1394instance::dc_instance protected
Definition at line 70 of file capturedc1394v2.h.
Referenced by GlobalCaptureDC1394instance(), and obtainInstance().
QMutex GlobalCaptureDC1394instance::mutex
Definition at line 64 of file capturedc1394v2.h.
Referenced by GlobalCaptureDC1394instance(), and ~GlobalCaptureDC1394instance().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/capture/capturedc1394v2.h