Documentation: Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot Class Reference
Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot Class Reference
Data Structures
class Builder
Public Member Functions
SSL_DetectionRobot getDefaultInstanceForType ()
boolean hasConfidence ()
float getConfidence ()
boolean hasRobotId ()
int getRobotId ()
boolean hasX ()
float getX ()
boolean hasY ()
float getY ()
boolean hasOrientation ()
float getOrientation ()
boolean hasPixelX ()
float getPixelX ()
boolean hasPixelY ()
float getPixelY ()
boolean hasHeight ()
float getHeight ()
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static SSL_DetectionRobot getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static MessagesRobocupSslDetection.SSL_DetectionRobot parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslDetection.SSL_DetectionRobot parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslDetection.SSL_DetectionRobot parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslDetection.SSL_DetectionRobot parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslDetection.SSL_DetectionRobot parseFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionRobot parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionRobot parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionRobot parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionRobot parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionRobot parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (MessagesRobocupSslDetection.SSL_DetectionRobot prototype)
Static Public Attributes
static final int CONFIDENCE_FIELD_NUMBER = 1
static final int ROBOT_ID_FIELD_NUMBER = 2
static final int X_FIELD_NUMBER = 3
static final int Y_FIELD_NUMBER = 4
static final int ORIENTATION_FIELD_NUMBER = 5
static final int PIXEL_X_FIELD_NUMBER = 6
static final int PIXEL_Y_FIELD_NUMBER = 7
static final int HEIGHT_FIELD_NUMBER = 8
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
SSL_DetectionRobot (Builder builder)
SSL_DetectionRobot (boolean noInit)
void initFields ()
Private Attributes
int bitField0_
float confidence_
int robotId_
float x_
float y_
float orientation_
float pixelX_
float pixelY_
float height_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final SSL_DetectionRobot defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 766 of file MessagesRobocupSslDetection.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.SSL_DetectionRobot (Builder builder) inline private
Definition at line 770 of file MessagesRobocupSslDetection.java.
{
       super(builder);
     }
Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.SSL_DetectionRobot (boolean noInit) inline private
Definition at line 773 of file MessagesRobocupSslDetection.java.
 {}
Member Function Documentation
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getConfidence () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 801 of file MessagesRobocupSslDetection.java.
{
       return confidence_;
     }
static SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstance () inline static
Definition at line 776 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsBlueBuilder(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addRobotsYellowBuilder(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.getDefaultInstanceForType(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.mergeFrom().
{
       return defaultInstance;
     }
SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getDefaultInstanceForType () inline
Definition at line 780 of file MessagesRobocupSslDetection.java.
{
       return defaultInstance;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getDescriptor () inline static
Definition at line 785 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.internal_static_SSL_DetectionRobot_descriptor.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.getDescriptorForType().
{
       return MessagesRobocupSslDetection.internal_static_SSL_DetectionRobot_descriptor;
     }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getHeight () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 871 of file MessagesRobocupSslDetection.java.
{
       return height_;
     }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getOrientation () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 841 of file MessagesRobocupSslDetection.java.
{
       return orientation_;
     }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getPixelX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 851 of file MessagesRobocupSslDetection.java.
{
       return pixelX_;
     }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getPixelY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 861 of file MessagesRobocupSslDetection.java.
{
       return pixelY_;
     }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getRobotId () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 811 of file MessagesRobocupSslDetection.java.
{
       return robotId_;
     }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getSerializedSize () inline
Definition at line 945 of file MessagesRobocupSslDetection.java.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(1, confidence_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         size += com.google.protobuf.CodedOutputStream
           .computeUInt32Size(2, robotId_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(3, x_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(4, y_);
       }
       if (((bitField0_ & 0x00000010) == 0x00000010)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(5, orientation_);
       }
       if (((bitField0_ & 0x00000020) == 0x00000020)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(6, pixelX_);
       }
       if (((bitField0_ & 0x00000040) == 0x00000040)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(7, pixelY_);
       }
       if (((bitField0_ & 0x00000080) == 0x00000080)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(8, height_);
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 821 of file MessagesRobocupSslDetection.java.
{
       return x_;
     }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.getY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 831 of file MessagesRobocupSslDetection.java.
{
       return y_;
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.hasConfidence () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 798 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.hasHeight () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 868 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000080) == 0x00000080);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.hasOrientation () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 838 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000010) == 0x00000010);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.hasPixelX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 848 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000020) == 0x00000020);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.hasPixelY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 858 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000040) == 0x00000040);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.hasRobotId () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 808 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000002) == 0x00000002);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.hasX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 818 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000004) == 0x00000004);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.hasY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobotOrBuilder.
Definition at line 828 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000008) == 0x00000008);
     }
void Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.initFields () inline private
Definition at line 875 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.clearHeight().
{
       confidence_ = 0F;
       robotId_ = 0;
       x_ = 0F;
       y_ = 0F;
       orientation_ = 0F;
       pixelX_ = 0F;
       pixelY_ = 0F;
       height_ = 0F;
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.internalGetFieldAccessorTable () inline protected
Definition at line 790 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.internal_static_SSL_DetectionRobot_fieldAccessorTable.
{
       return MessagesRobocupSslDetection.internal_static_SSL_DetectionRobot_fieldAccessorTable;
     }
final boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.isInitialized () inline
Definition at line 886 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasConfidence(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasPixelX(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasPixelY(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasX(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasY().
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (!hasConfidence()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasX()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasY()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasPixelX()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasPixelY()) {
         memoizedIsInitialized = 0;
         return false;
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.newBuilder () inline static
Definition at line 1061 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.create().
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom().
 { return Builder.create(); }
static Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.newBuilder (MessagesRobocupSslDetection.SSL_DetectionRobot prototype) inline static
Definition at line 1063 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.newBuilderForType () inline
Definition at line 1062 of file MessagesRobocupSslDetection.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 1069 of file MessagesRobocupSslDetection.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 1028 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1037 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 994 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 999 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1006 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1010 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 1017 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1021 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 1048 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1053 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.toBuilder () inline
Definition at line 1066 of file MessagesRobocupSslDetection.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 989 of file MessagesRobocupSslDetection.java.
{
       return super.writeReplace();
     }
void Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 914 of file MessagesRobocupSslDetection.java.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeFloat(1, confidence_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         output.writeUInt32(2, robotId_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         output.writeFloat(3, x_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         output.writeFloat(4, y_);
       }
       if (((bitField0_ & 0x00000010) == 0x00000010)) {
         output.writeFloat(5, orientation_);
       }
       if (((bitField0_ & 0x00000020) == 0x00000020)) {
         output.writeFloat(6, pixelX_);
       }
       if (((bitField0_ & 0x00000040) == 0x00000040)) {
         output.writeFloat(7, pixelY_);
       }
       if (((bitField0_ & 0x00000080) == 0x00000080)) {
         output.writeFloat(8, height_);
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.bitField0_ private
Definition at line 794 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.confidence_ private
Definition at line 797 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.buildPartial().
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.CONFIDENCE_FIELD_NUMBER = 1 static
Definition at line 796 of file MessagesRobocupSslDetection.java.
final SSL_DetectionRobot Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.defaultInstance static private
Definition at line 775 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.height_ private
Definition at line 867 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.HEIGHT_FIELD_NUMBER = 8 static
Definition at line 866 of file MessagesRobocupSslDetection.java.
byte Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.memoizedIsInitialized = -1 private
Definition at line 885 of file MessagesRobocupSslDetection.java.
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.memoizedSerializedSize = -1 private
Definition at line 944 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.orientation_ private
Definition at line 837 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.ORIENTATION_FIELD_NUMBER = 5 static
Definition at line 836 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.PIXEL_X_FIELD_NUMBER = 6 static
Definition at line 846 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.PIXEL_Y_FIELD_NUMBER = 7 static
Definition at line 856 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.pixelX_ private
Definition at line 847 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.pixelY_ private
Definition at line 857 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.ROBOT_ID_FIELD_NUMBER = 2 static
Definition at line 806 of file MessagesRobocupSslDetection.java.
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.robotId_ private
Definition at line 807 of file MessagesRobocupSslDetection.java.
final long Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.serialVersionUID = 0L static private
Definition at line 987 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.x_ private
Definition at line 817 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.X_FIELD_NUMBER = 3 static
Definition at line 816 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.y_ private
Definition at line 827 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Y_FIELD_NUMBER = 4 static
Definition at line 826 of file MessagesRobocupSslDetection.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslDetection.java