Documentation: test_Triangle Namespace Reference
test_Triangle Namespace Reference
Functions
def distance_ (a, b)
def change_target ()
def check_target ()
def BS_callback (msg)
Variables
int BOT_1 = 0
int BOT_2 = 1
int BOT_3 = 2
target_1 = point_2d()
target_2 = point_2d()
target_3 = point_2d()
homePos = None
awayPos = None
int FIRST_CALL = 1
int THRESHOLD = 2
pub = rospy.Publisher('target_params', target_triangle)
anonymous
BeliefState
BS_callback
queue_size
Function Documentation
def test_Triangle.BS_callback (msg)
Definition at line 56 of file test_Triangle.py.
References BS_callback, check_target(), and triangle1.target_triangle.
 def BS_callback(msg):
     global homePos, awayPos, FIRST_CALL, target_1, target_2, target_3
     homePos = msg.homePos
     awayPos = msg.awayPos
     msgs = target_triangle()
     msgs.tx0 = target_1.x
     msgs.ty0 = target_1.y
     msgs.tx1 = target_2.x
     msgs.ty1 = target_2.y
     msgs.tx2 = target_3.x
     msgs.ty2 = target_3.y
     check_target()
     if(FIRST_CALL):
         target_1 = homePos[BOT_2]
         target_2 = homePos[BOT_3]
         target_3 = homePos[BOT_1]
         FIRST_CALL = 0
     pub.publish(msgs)
def test_Triangle.change_target ()
Definition at line 26 of file test_Triangle.py.
Referenced by check_target().
 def change_target():
     global target_1, target_2, target_3, homePos
     temp = point_2d()
     temp.x = target_1.x
     temp.y = target_1.y
     target_1.x = target_2.x
     target_1.y = target_2.y
     target_2.x = target_3.x
     target_2.y = target_3.y
     target_3.x = temp.x
     target_3.y = temp.y
def test_Triangle.check_target ()
Definition at line 41 of file test_Triangle.py.
References change_target(), distance_(), and print().
Referenced by BS_callback().
 def check_target():
     global target_1, target_2, target_3
     dist1 = distance_(target_1, homePos[BOT_1])
     dist2 = distance_(target_2, homePos[BOT_2])
     dist3 = distance_(target_3, homePos[BOT_3])
     flag1 = dist1<THRESHOLD
     flag2 = dist2<THRESHOLD
     flag3 = dist3<THRESHOLD
     print("flag1 = ",flag1," flag2 = ",flag2," flag3 = ",flag3)
     if(flag1 and flag2 and flag3):
         change_target()
def test_Triangle.distance_ (a, b)
Definition at line 21 of file test_Triangle.py.
Referenced by check_target().
 def distance_(a, b):
     dx = a.x-b.x
     dy = a.y-b.y
     return sqrt(dx*dx+dy*dy)
Variable Documentation
test_Triangle.anonymous
Definition at line 81 of file test_Triangle.py.
test_Triangle.awayPos = None
Definition at line 16 of file test_Triangle.py.
test_Triangle.BeliefState
Definition at line 82 of file test_Triangle.py.
int test_Triangle.BOT_1 = 0
Definition at line 8 of file test_Triangle.py.
int test_Triangle.BOT_2 = 1
Definition at line 9 of file test_Triangle.py.
int test_Triangle.BOT_3 = 2
Definition at line 10 of file test_Triangle.py.
test_Triangle.BS_callback
Definition at line 82 of file test_Triangle.py.
Referenced by BS_callback().
int test_Triangle.FIRST_CALL = 1
Definition at line 17 of file test_Triangle.py.
test_Triangle.homePos = None
Definition at line 15 of file test_Triangle.py.
test_Triangle.pub = rospy.Publisher('target_params', target_triangle)
Definition at line 19 of file test_Triangle.py.
test_Triangle.queue_size
Definition at line 82 of file test_Triangle.py.
test_Triangle.target_1 = point_2d()
Definition at line 12 of file test_Triangle.py.
test_Triangle.target_2 = point_2d()
Definition at line 13 of file test_Triangle.py.
test_Triangle.target_3 = point_2d()
Definition at line 14 of file test_Triangle.py.
int test_Triangle.THRESHOLD = 2
Definition at line 18 of file test_Triangle.py.