Documentation: Protobuf.GrSimPacket.grSim_PacketOrBuilder Interface Reference
Protobuf.GrSimPacket.grSim_PacketOrBuilder Interface Reference
Public Member Functions
boolean hasCommands ()
GrSimCommands.grSim_Commands getCommands ()
GrSimCommands.grSim_CommandsOrBuilder getCommandsOrBuilder ()
boolean hasReplacement ()
GrSimReplacement.grSim_Replacement getReplacement ()
GrSimReplacement.grSim_ReplacementOrBuilder getReplacementOrBuilder ()
Detailed Description
Definition at line 10 of file GrSimPacket.java.
Member Function Documentation
GrSimCommands.grSim_Commands Protobuf.GrSimPacket.grSim_PacketOrBuilder.getCommands ()
Implemented in Protobuf.GrSimPacket.grSim_Packet.Builder, and Protobuf.GrSimPacket.grSim_Packet.
Referenced by Protobuf.GrSimPacket.grSim_Packet.isInitialized(), Protobuf.GrSimPacket.grSim_Packet.Builder.isInitialized(), and Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom().
GrSimCommands.grSim_CommandsOrBuilder Protobuf.GrSimPacket.grSim_PacketOrBuilder.getCommandsOrBuilder ()
Implemented in Protobuf.GrSimPacket.grSim_Packet.Builder, and Protobuf.GrSimPacket.grSim_Packet.
GrSimReplacement.grSim_Replacement Protobuf.GrSimPacket.grSim_PacketOrBuilder.getReplacement ()
Implemented in Protobuf.GrSimPacket.grSim_Packet.Builder, and Protobuf.GrSimPacket.grSim_Packet.
Referenced by Protobuf.GrSimPacket.grSim_Packet.isInitialized(), Protobuf.GrSimPacket.grSim_Packet.Builder.isInitialized(), and Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom().
GrSimReplacement.grSim_ReplacementOrBuilder Protobuf.GrSimPacket.grSim_PacketOrBuilder.getReplacementOrBuilder ()
Implemented in Protobuf.GrSimPacket.grSim_Packet.Builder, and Protobuf.GrSimPacket.grSim_Packet.
boolean Protobuf.GrSimPacket.grSim_PacketOrBuilder.hasCommands ()
Implemented in Protobuf.GrSimPacket.grSim_Packet.Builder, and Protobuf.GrSimPacket.grSim_Packet.
Referenced by Protobuf.GrSimPacket.grSim_Packet.isInitialized(), Protobuf.GrSimPacket.grSim_Packet.Builder.isInitialized(), and Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom().
boolean Protobuf.GrSimPacket.grSim_PacketOrBuilder.hasReplacement ()
Implemented in Protobuf.GrSimPacket.grSim_Packet.Builder, and Protobuf.GrSimPacket.grSim_Packet.
Referenced by Protobuf.GrSimPacket.grSim_Packet.isInitialized(), Protobuf.GrSimPacket.grSim_Packet.Builder.isInitialized(), and Protobuf.GrSimPacket.grSim_Packet.Builder.mergeFrom().
The documentation for this interface was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimPacket.java