Documentation: ssl-vision/src/app/main.cpp File Reference
main.cpp File Reference
#include <QApplication>
#include <QCleanlooksStyle>
#include <QPlastiqueStyle>
#include <QString>
#include "mainwindow.h"
#include <signal.h>
#include <stdio.h>
#include <iostream>
#include <unistd.h>
#include "qgetopt.h"
Functions
void HandleStop (int i)
void printPathWarning ()
int main (int argc, char *argv[])
Variables
MainWindow * mainWinPtr = NULL
Function Documentation
void HandleStop (int i)
Definition at line 36 of file main.cpp.
References MainWindow::Quit().
Referenced by main().
{
   if (mainWinPtr != NULL) {
     printf("\nExiting.\n");
     fflush(stdout);
     mainWinPtr->Quit();
   }
 }
int main (int argc, char * argv[])
Definition at line 84 of file main.cpp.
References GetOpt::addShortOptSwitch(), GetOpt::addSwitch(), app, HandleStop(), MainWindow::init(), GetOpt::parse(), and printPathWarning().
 {
   signal(SIGINT,HandleStop);
   QApplication app(argc, argv);
   GetOpt opts(argc, argv);
   bool help=false;
   bool start=false;
   bool enforce_affinity=false;
   int ecode=0;
   opts.addSwitch("help",&help);
   opts.addShortOptSwitch( 'a',QString("Enforce Processor Affinity"),&enforce_affinity, false);
   opts.addShortOptSwitch( 's',QString("Start Capturing Immediately"),&start, false);
   if (!opts.parse()) {
     fprintf(stderr,"Invalid command line parameters!\n");
     help=true;
     ecode=1;
   }
   if (help) {
     printf("SSL-Vision command line options:\n");
     printf(" -s        Start capture immediately\n");
     printf(" -a        Set Processor Affinity\n");
     printf(" --help    Show this help\n");
     exit(ecode);
   }
   printPathWarning();
   MainWindow mainWin(start, enforce_affinity);
   mainWinPtr = &mainWin;
   //if desired, launch a particular style:
   // app.setStyle(new QPlastiqueStyle());
   // app.setStyle(new QCleanlooksStyle());
   mainWin.show();
   mainWin.init();
   int retval = app.exec();
   return retval;
 }
void printPathWarning ()
Definition at line 45 of file main.cpp.
Referenced by main().
{
   char cwd[PATH_MAX];
   char* result = getcwd(cwd, PATH_MAX);
   if (!result) {
     // We failed getting the cwd, abort
     return;
   }
   std::string currentWorkingDir = cwd;
   char binaryPathRaw[PATH_MAX];
   int count = readlink("/proc/self/exe", binaryPathRaw, PATH_MAX);
   if (count == -1) {
     // We failed getting the binary path, quit
     return;
   }
   std::string binaryPath = std::string(binaryPathRaw, count);
   // Get the offset to check
   unsigned int offset = currentWorkingDir.size();
   if (offset == 0 || offset >= binaryPath.size()){
     return;
   }
   if (binaryPath.substr(offset, string::npos) != "/bin/vision") {
     std::string warningMsg = "[WARNING] You are running vision from a non-standard directory.\n"
       "Please run ssl-vision from the root of the git repo unless you know what you are doing.\n"
       "(run with: ./bin/vision)\n";
     std::cout << std::endl << warningMsg << std::endl;
     // display a message box
     QMessageBox msgBox;
     msgBox.setText(QString::fromUtf8(warningMsg.c_str()));
     msgBox.exec();
   }
 }
Variable Documentation
MainWindow* mainWinPtr = NULL
Definition at line 33 of file main.cpp.