// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_game_controller_auto_ref.proto

package refproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AutoRefRegistration is the first message that a client must send to the controller to identify itself
type AutoRefRegistration struct {
	// identifier is a unique name of the client
	Identifier *string `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	// signature can optionally be specified to enable secure communication
	Signature            *Signature `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AutoRefRegistration) Reset()         { *m = AutoRefRegistration{} }
func (m *AutoRefRegistration) String() string { return proto.CompactTextString(m) }
func (*AutoRefRegistration) ProtoMessage()    {}
func (*AutoRefRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbb3ba3bab9727c, []int{0}
}

func (m *AutoRefRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoRefRegistration.Unmarshal(m, b)
}
func (m *AutoRefRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoRefRegistration.Marshal(b, m, deterministic)
}
func (m *AutoRefRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoRefRegistration.Merge(m, src)
}
func (m *AutoRefRegistration) XXX_Size() int {
	return xxx_messageInfo_AutoRefRegistration.Size(m)
}
func (m *AutoRefRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoRefRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_AutoRefRegistration proto.InternalMessageInfo

func (m *AutoRefRegistration) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

func (m *AutoRefRegistration) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// AutoRefToController is the wrapper message for all subsequent messages from the autoRef to the controller
type AutoRefToController struct {
	// signature can optionally be specified to enable secure communication
	Signature *Signature `protobuf:"bytes,1,opt,name=signature" json:"signature,omitempty"`
	// game_event is an optional event that the autoRef detected during the game
	GameEvent *GameEvent `protobuf:"bytes,2,opt,name=game_event,json=gameEvent" json:"game_event,omitempty"`
	// auto_ref_message is an optional message that describes the current state or situation of the game/autoRef
	// it is not and never was processed by the GC and is this marked deprecated
	AutoRefMessage       *AutoRefMessage `protobuf:"bytes,3,opt,name=auto_ref_message,json=autoRefMessage" json:"auto_ref_message,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AutoRefToController) Reset()         { *m = AutoRefToController{} }
func (m *AutoRefToController) String() string { return proto.CompactTextString(m) }
func (*AutoRefToController) ProtoMessage()    {}
func (*AutoRefToController) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbb3ba3bab9727c, []int{1}
}

func (m *AutoRefToController) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoRefToController.Unmarshal(m, b)
}
func (m *AutoRefToController) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoRefToController.Marshal(b, m, deterministic)
}
func (m *AutoRefToController) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoRefToController.Merge(m, src)
}
func (m *AutoRefToController) XXX_Size() int {
	return xxx_messageInfo_AutoRefToController.Size(m)
}
func (m *AutoRefToController) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoRefToController.DiscardUnknown(m)
}

var xxx_messageInfo_AutoRefToController proto.InternalMessageInfo

func (m *AutoRefToController) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *AutoRefToController) GetGameEvent() *GameEvent {
	if m != nil {
		return m.GameEvent
	}
	return nil
}

// Deprecated: Do not use.
func (m *AutoRefToController) GetAutoRefMessage() *AutoRefMessage {
	if m != nil {
		return m.AutoRefMessage
	}
	return nil
}

// ControllerToAutoRef is the wrapper message for all messages from controller to autoRef
type ControllerToAutoRef struct {
	// Types that are valid to be assigned to Msg:
	//	*ControllerToAutoRef_ControllerReply
	Msg                  isControllerToAutoRef_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ControllerToAutoRef) Reset()         { *m = ControllerToAutoRef{} }
func (m *ControllerToAutoRef) String() string { return proto.CompactTextString(m) }
func (*ControllerToAutoRef) ProtoMessage()    {}
func (*ControllerToAutoRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbb3ba3bab9727c, []int{2}
}

func (m *ControllerToAutoRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerToAutoRef.Unmarshal(m, b)
}
func (m *ControllerToAutoRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerToAutoRef.Marshal(b, m, deterministic)
}
func (m *ControllerToAutoRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerToAutoRef.Merge(m, src)
}
func (m *ControllerToAutoRef) XXX_Size() int {
	return xxx_messageInfo_ControllerToAutoRef.Size(m)
}
func (m *ControllerToAutoRef) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerToAutoRef.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerToAutoRef proto.InternalMessageInfo

type isControllerToAutoRef_Msg interface {
	isControllerToAutoRef_Msg()
}

type ControllerToAutoRef_ControllerReply struct {
	ControllerReply *ControllerReply `protobuf:"bytes,1,opt,name=controller_reply,json=controllerReply,oneof"`
}

func (*ControllerToAutoRef_ControllerReply) isControllerToAutoRef_Msg() {}

func (m *ControllerToAutoRef) GetMsg() isControllerToAutoRef_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *ControllerToAutoRef) GetControllerReply() *ControllerReply {
	if x, ok := m.GetMsg().(*ControllerToAutoRef_ControllerReply); ok {
		return x.ControllerReply
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ControllerToAutoRef) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ControllerToAutoRef_ControllerReply)(nil),
	}
}

// a message from autoRef, describing the current state or situation
type AutoRefMessage struct {
	// Types that are valid to be assigned to Message:
	//	*AutoRefMessage_Custom
	//	*AutoRefMessage_WaitForBots_
	Message              isAutoRefMessage_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AutoRefMessage) Reset()         { *m = AutoRefMessage{} }
func (m *AutoRefMessage) String() string { return proto.CompactTextString(m) }
func (*AutoRefMessage) ProtoMessage()    {}
func (*AutoRefMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbb3ba3bab9727c, []int{3}
}

func (m *AutoRefMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoRefMessage.Unmarshal(m, b)
}
func (m *AutoRefMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoRefMessage.Marshal(b, m, deterministic)
}
func (m *AutoRefMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoRefMessage.Merge(m, src)
}
func (m *AutoRefMessage) XXX_Size() int {
	return xxx_messageInfo_AutoRefMessage.Size(m)
}
func (m *AutoRefMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoRefMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AutoRefMessage proto.InternalMessageInfo

type isAutoRefMessage_Message interface {
	isAutoRefMessage_Message()
}

type AutoRefMessage_Custom struct {
	Custom string `protobuf:"bytes,1,opt,name=custom,oneof"`
}

type AutoRefMessage_WaitForBots_ struct {
	WaitForBots *AutoRefMessage_WaitForBots `protobuf:"bytes,2,opt,name=wait_for_bots,json=waitForBots,oneof"`
}

func (*AutoRefMessage_Custom) isAutoRefMessage_Message() {}

func (*AutoRefMessage_WaitForBots_) isAutoRefMessage_Message() {}

func (m *AutoRefMessage) GetMessage() isAutoRefMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *AutoRefMessage) GetCustom() string {
	if x, ok := m.GetMessage().(*AutoRefMessage_Custom); ok {
		return x.Custom
	}
	return ""
}

func (m *AutoRefMessage) GetWaitForBots() *AutoRefMessage_WaitForBots {
	if x, ok := m.GetMessage().(*AutoRefMessage_WaitForBots_); ok {
		return x.WaitForBots
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AutoRefMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AutoRefMessage_Custom)(nil),
		(*AutoRefMessage_WaitForBots_)(nil),
	}
}

// the bots that is waited for
type AutoRefMessage_WaitForBots struct {
	// the bots that are waited for
	Violators            []*AutoRefMessage_WaitForBots_Violator `protobuf:"bytes,1,rep,name=violators" json:"violators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *AutoRefMessage_WaitForBots) Reset()         { *m = AutoRefMessage_WaitForBots{} }
func (m *AutoRefMessage_WaitForBots) String() string { return proto.CompactTextString(m) }
func (*AutoRefMessage_WaitForBots) ProtoMessage()    {}
func (*AutoRefMessage_WaitForBots) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbb3ba3bab9727c, []int{3, 0}
}

func (m *AutoRefMessage_WaitForBots) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoRefMessage_WaitForBots.Unmarshal(m, b)
}
func (m *AutoRefMessage_WaitForBots) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoRefMessage_WaitForBots.Marshal(b, m, deterministic)
}
func (m *AutoRefMessage_WaitForBots) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoRefMessage_WaitForBots.Merge(m, src)
}
func (m *AutoRefMessage_WaitForBots) XXX_Size() int {
	return xxx_messageInfo_AutoRefMessage_WaitForBots.Size(m)
}
func (m *AutoRefMessage_WaitForBots) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoRefMessage_WaitForBots.DiscardUnknown(m)
}

var xxx_messageInfo_AutoRefMessage_WaitForBots proto.InternalMessageInfo

func (m *AutoRefMessage_WaitForBots) GetViolators() []*AutoRefMessage_WaitForBots_Violator {
	if m != nil {
		return m.Violators
	}
	return nil
}

type AutoRefMessage_WaitForBots_Violator struct {
	// the id of the violator
	BotId *BotId `protobuf:"bytes,1,req,name=bot_id,json=botId" json:"bot_id,omitempty"`
	// the distance to the next valid position
	Distance             *float32 `protobuf:"fixed32,2,req,name=distance" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoRefMessage_WaitForBots_Violator) Reset()         { *m = AutoRefMessage_WaitForBots_Violator{} }
func (m *AutoRefMessage_WaitForBots_Violator) String() string { return proto.CompactTextString(m) }
func (*AutoRefMessage_WaitForBots_Violator) ProtoMessage()    {}
func (*AutoRefMessage_WaitForBots_Violator) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbb3ba3bab9727c, []int{3, 0, 0}
}

func (m *AutoRefMessage_WaitForBots_Violator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoRefMessage_WaitForBots_Violator.Unmarshal(m, b)
}
func (m *AutoRefMessage_WaitForBots_Violator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoRefMessage_WaitForBots_Violator.Marshal(b, m, deterministic)
}
func (m *AutoRefMessage_WaitForBots_Violator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoRefMessage_WaitForBots_Violator.Merge(m, src)
}
func (m *AutoRefMessage_WaitForBots_Violator) XXX_Size() int {
	return xxx_messageInfo_AutoRefMessage_WaitForBots_Violator.Size(m)
}
func (m *AutoRefMessage_WaitForBots_Violator) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoRefMessage_WaitForBots_Violator.DiscardUnknown(m)
}

var xxx_messageInfo_AutoRefMessage_WaitForBots_Violator proto.InternalMessageInfo

func (m *AutoRefMessage_WaitForBots_Violator) GetBotId() *BotId {
	if m != nil {
		return m.BotId
	}
	return nil
}

func (m *AutoRefMessage_WaitForBots_Violator) GetDistance() float32 {
	if m != nil && m.Distance != nil {
		return *m.Distance
	}
	return 0
}

func init() {
	proto.RegisterType((*AutoRefRegistration)(nil), "AutoRefRegistration")
	proto.RegisterType((*AutoRefToController)(nil), "AutoRefToController")
	proto.RegisterType((*ControllerToAutoRef)(nil), "ControllerToAutoRef")
	proto.RegisterType((*AutoRefMessage)(nil), "AutoRefMessage")
	proto.RegisterType((*AutoRefMessage_WaitForBots)(nil), "AutoRefMessage.WaitForBots")
	proto.RegisterType((*AutoRefMessage_WaitForBots_Violator)(nil), "AutoRefMessage.WaitForBots.Violator")
}

func init() { proto.RegisterFile("ssl_game_controller_auto_ref.proto", fileDescriptor_2fbb3ba3bab9727c) }

var fileDescriptor_2fbb3ba3bab9727c = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xbf, 0x6e, 0xd4, 0x40,
	0x10, 0xc6, 0xcf, 0x3e, 0xe5, 0x88, 0xc7, 0x22, 0x89, 0x36, 0x8d, 0x39, 0x04, 0x3a, 0x59, 0x14,
	0xa6, 0xb1, 0xe0, 0x3a, 0x0a, 0x8a, 0x18, 0x05, 0x8e, 0x82, 0x66, 0x89, 0xa0, 0xa0, 0x58, 0xed,
	0xd9, 0x6b, 0x6b, 0x25, 0xdb, 0x13, 0xed, 0x8e, 0x13, 0xf1, 0x1c, 0x34, 0xbc, 0x02, 0x6f, 0x89,
	0x7c, 0x59, 0xdb, 0x67, 0x84, 0x52, 0xd9, 0xf3, 0x9b, 0x6f, 0xbe, 0xfd, 0xf6, 0x0f, 0xc4, 0xd6,
	0xd6, 0xa2, 0x92, 0x8d, 0x12, 0x39, 0xb6, 0x64, 0xb0, 0xae, 0x95, 0x11, 0xb2, 0x23, 0x14, 0x46,
	0x95, 0xe9, 0xad, 0x41, 0xc2, 0xf5, 0xe6, 0x7f, 0x9a, 0x1c, 0x9b, 0x06, 0x5b, 0xa7, 0x78, 0x36,
	0x2a, 0xd4, 0x9d, 0x6a, 0x49, 0x6c, 0xdf, 0xbc, 0x7d, 0xf7, 0xd0, 0x8a, 0x05, 0x5c, 0x5e, 0x75,
	0x84, 0x5c, 0x95, 0x5c, 0x55, 0xda, 0x92, 0x91, 0xa4, 0xb1, 0x65, 0x2f, 0x01, 0x74, 0xa1, 0x5a,
	0xd2, 0xa5, 0x56, 0x26, 0xf2, 0x36, 0x7e, 0x12, 0xf0, 0x23, 0xc2, 0x12, 0x08, 0xac, 0xae, 0x5a,
	0x49, 0x9d, 0x51, 0x91, 0xbf, 0xf1, 0x92, 0x70, 0x0b, 0xe9, 0xd7, 0x81, 0xf0, 0xa9, 0x19, 0xff,
	0xf1, 0xc6, 0x15, 0x6e, 0xf0, 0xc3, 0x18, 0x70, 0xee, 0xe0, 0x3d, 0xe2, 0xc0, 0x5e, 0x03, 0x4c,
	0xd9, 0xc7, 0xc5, 0x3e, 0xc9, 0x46, 0x5d, 0xf7, 0x84, 0x07, 0xd5, 0xf0, 0xcb, 0xde, 0xc3, 0xc5,
	0x70, 0x38, 0xa2, 0x51, 0xd6, 0xca, 0x4a, 0x45, 0xcb, 0xc3, 0xc0, 0x79, 0xea, 0x42, 0x7c, 0x79,
	0xc0, 0x99, 0x1f, 0x79, 0xfc, 0x4c, 0xce, 0x58, 0xfc, 0x03, 0x2e, 0xa7, 0x84, 0x37, 0xe8, 0x26,
	0x7a, 0xd7, 0xa3, 0x93, 0x35, 0xea, 0xb6, 0xfe, 0xe9, 0x12, 0x5f, 0xa4, 0x93, 0x9e, 0xf7, 0x7c,
	0xb7, 0xe0, 0xe7, 0xf9, 0x1c, 0x65, 0x27, 0xb0, 0x6c, 0x6c, 0x15, 0xff, 0xf2, 0xe1, 0x6c, 0x9e,
	0x81, 0x45, 0xb0, 0xca, 0x3b, 0x4b, 0xd8, 0x1c, 0xec, 0x82, 0xdd, 0x82, 0xbb, 0x9a, 0x5d, 0xc1,
	0xd3, 0x7b, 0xa9, 0x49, 0x94, 0x68, 0xc4, 0x1e, 0xc9, 0xba, 0x6d, 0x3f, 0xff, 0x67, 0x17, 0xe9,
	0x77, 0xa9, 0xe9, 0x23, 0x9a, 0x0c, 0xc9, 0xee, 0x16, 0x3c, 0xbc, 0x9f, 0xca, 0xf5, 0x6f, 0x0f,
	0xc2, 0xa3, 0x36, 0xcb, 0x20, 0xb8, 0xd3, 0x58, 0x4b, 0x42, 0x63, 0x23, 0x6f, 0xb3, 0x4c, 0xc2,
	0xed, 0xab, 0x47, 0xec, 0xd2, 0x6f, 0x4e, 0xcc, 0xa7, 0xb1, 0xf5, 0x35, 0x9c, 0x0e, 0x98, 0xbd,
	0x80, 0xd5, 0x1e, 0x49, 0xe8, 0xe2, 0xf0, 0x3c, 0xc2, 0xed, 0x2a, 0xcd, 0x90, 0x3e, 0x17, 0xfc,
	0x64, 0xdf, 0x7f, 0xd8, 0x1a, 0x4e, 0x0b, 0x6d, 0x49, 0xb6, 0x79, 0xff, 0x40, 0xfc, 0xc4, 0xe7,
	0x63, 0x9d, 0x05, 0xf0, 0xc4, 0xdd, 0xce, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x11, 0xc6,
	0xfa, 0xe1, 0x02, 0x00, 0x00,
}
