// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_referee.proto

package refproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// These are the "coarse" stages of the game.
type Referee_Stage int32

const (
	// The first half is about to start.
	// A kickoff is called within this stage.
	// This stage ends with the NORMAL_START.
	Referee_NORMAL_FIRST_HALF_PRE Referee_Stage = 0
	// The first half of the normal game, before half time.
	Referee_NORMAL_FIRST_HALF Referee_Stage = 1
	// Half time between first and second halves.
	Referee_NORMAL_HALF_TIME Referee_Stage = 2
	// The second half is about to start.
	// A kickoff is called within this stage.
	// This stage ends with the NORMAL_START.
	Referee_NORMAL_SECOND_HALF_PRE Referee_Stage = 3
	// The second half of the normal game, after half time.
	Referee_NORMAL_SECOND_HALF Referee_Stage = 4
	// The break before extra time.
	Referee_EXTRA_TIME_BREAK Referee_Stage = 5
	// The first half of extra time is about to start.
	// A kickoff is called within this stage.
	// This stage ends with the NORMAL_START.
	Referee_EXTRA_FIRST_HALF_PRE Referee_Stage = 6
	// The first half of extra time.
	Referee_EXTRA_FIRST_HALF Referee_Stage = 7
	// Half time between first and second extra halves.
	Referee_EXTRA_HALF_TIME Referee_Stage = 8
	// The second half of extra time is about to start.
	// A kickoff is called within this stage.
	// This stage ends with the NORMAL_START.
	Referee_EXTRA_SECOND_HALF_PRE Referee_Stage = 9
	// The second half of extra time.
	Referee_EXTRA_SECOND_HALF Referee_Stage = 10
	// The break before penalty shootout.
	Referee_PENALTY_SHOOTOUT_BREAK Referee_Stage = 11
	// The penalty shootout.
	Referee_PENALTY_SHOOTOUT Referee_Stage = 12
	// The game is over.
	Referee_POST_GAME Referee_Stage = 13
)

var Referee_Stage_name = map[int32]string{
	0:  "NORMAL_FIRST_HALF_PRE",
	1:  "NORMAL_FIRST_HALF",
	2:  "NORMAL_HALF_TIME",
	3:  "NORMAL_SECOND_HALF_PRE",
	4:  "NORMAL_SECOND_HALF",
	5:  "EXTRA_TIME_BREAK",
	6:  "EXTRA_FIRST_HALF_PRE",
	7:  "EXTRA_FIRST_HALF",
	8:  "EXTRA_HALF_TIME",
	9:  "EXTRA_SECOND_HALF_PRE",
	10: "EXTRA_SECOND_HALF",
	11: "PENALTY_SHOOTOUT_BREAK",
	12: "PENALTY_SHOOTOUT",
	13: "POST_GAME",
}

var Referee_Stage_value = map[string]int32{
	"NORMAL_FIRST_HALF_PRE":  0,
	"NORMAL_FIRST_HALF":      1,
	"NORMAL_HALF_TIME":       2,
	"NORMAL_SECOND_HALF_PRE": 3,
	"NORMAL_SECOND_HALF":     4,
	"EXTRA_TIME_BREAK":       5,
	"EXTRA_FIRST_HALF_PRE":   6,
	"EXTRA_FIRST_HALF":       7,
	"EXTRA_HALF_TIME":        8,
	"EXTRA_SECOND_HALF_PRE":  9,
	"EXTRA_SECOND_HALF":      10,
	"PENALTY_SHOOTOUT_BREAK": 11,
	"PENALTY_SHOOTOUT":       12,
	"POST_GAME":              13,
}

func (x Referee_Stage) Enum() *Referee_Stage {
	p := new(Referee_Stage)
	*p = x
	return p
}

func (x Referee_Stage) String() string {
	return proto.EnumName(Referee_Stage_name, int32(x))
}

func (x *Referee_Stage) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Referee_Stage_value, data, "Referee_Stage")
	if err != nil {
		return err
	}
	*x = Referee_Stage(value)
	return nil
}

func (Referee_Stage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f003bb08adc02ebb, []int{0, 0}
}

// These are the "fine" states of play on the field.
type Referee_Command int32

const (
	// All robots should completely stop moving.
	Referee_HALT Referee_Command = 0
	// Robots must keep 50 cm from the ball.
	Referee_STOP Referee_Command = 1
	// A prepared kickoff or penalty may now be taken.
	Referee_NORMAL_START Referee_Command = 2
	// The ball is dropped and free for either team.
	Referee_FORCE_START Referee_Command = 3
	// The yellow team may move into kickoff position.
	Referee_PREPARE_KICKOFF_YELLOW Referee_Command = 4
	// The blue team may move into kickoff position.
	Referee_PREPARE_KICKOFF_BLUE Referee_Command = 5
	// The yellow team may move into penalty position.
	Referee_PREPARE_PENALTY_YELLOW Referee_Command = 6
	// The blue team may move into penalty position.
	Referee_PREPARE_PENALTY_BLUE Referee_Command = 7
	// The yellow team may take a direct free kick.
	Referee_DIRECT_FREE_YELLOW Referee_Command = 8
	// The blue team may take a direct free kick.
	Referee_DIRECT_FREE_BLUE Referee_Command = 9
	// The yellow team may take an indirect free kick.
	Referee_INDIRECT_FREE_YELLOW Referee_Command = 10
	// The blue team may take an indirect free kick.
	Referee_INDIRECT_FREE_BLUE Referee_Command = 11
	// The yellow team is currently in a timeout.
	Referee_TIMEOUT_YELLOW Referee_Command = 12
	// The blue team is currently in a timeout.
	Referee_TIMEOUT_BLUE Referee_Command = 13
	// The yellow team just scored a goal.
	// For information only.
	// For rules compliance, teams must treat as STOP.
	// Deprecated: Use the score field from the team infos instead. That way, you can also detect revoked goals.
	Referee_GOAL_YELLOW Referee_Command = 14 // Deprecated: Do not use.
	// The blue team just scored a goal. See also GOAL_YELLOW.
	Referee_GOAL_BLUE Referee_Command = 15 // Deprecated: Do not use.
	// Equivalent to STOP, but the yellow team must pick up the ball and
	// drop it in the Designated Position.
	Referee_BALL_PLACEMENT_YELLOW Referee_Command = 16
	// Equivalent to STOP, but the blue team must pick up the ball and drop
	// it in the Designated Position.
	Referee_BALL_PLACEMENT_BLUE Referee_Command = 17
)

var Referee_Command_name = map[int32]string{
	0:  "HALT",
	1:  "STOP",
	2:  "NORMAL_START",
	3:  "FORCE_START",
	4:  "PREPARE_KICKOFF_YELLOW",
	5:  "PREPARE_KICKOFF_BLUE",
	6:  "PREPARE_PENALTY_YELLOW",
	7:  "PREPARE_PENALTY_BLUE",
	8:  "DIRECT_FREE_YELLOW",
	9:  "DIRECT_FREE_BLUE",
	10: "INDIRECT_FREE_YELLOW",
	11: "INDIRECT_FREE_BLUE",
	12: "TIMEOUT_YELLOW",
	13: "TIMEOUT_BLUE",
	14: "GOAL_YELLOW",
	15: "GOAL_BLUE",
	16: "BALL_PLACEMENT_YELLOW",
	17: "BALL_PLACEMENT_BLUE",
}

var Referee_Command_value = map[string]int32{
	"HALT":                   0,
	"STOP":                   1,
	"NORMAL_START":           2,
	"FORCE_START":            3,
	"PREPARE_KICKOFF_YELLOW": 4,
	"PREPARE_KICKOFF_BLUE":   5,
	"PREPARE_PENALTY_YELLOW": 6,
	"PREPARE_PENALTY_BLUE":   7,
	"DIRECT_FREE_YELLOW":     8,
	"DIRECT_FREE_BLUE":       9,
	"INDIRECT_FREE_YELLOW":   10,
	"INDIRECT_FREE_BLUE":     11,
	"TIMEOUT_YELLOW":         12,
	"TIMEOUT_BLUE":           13,
	"GOAL_YELLOW":            14,
	"GOAL_BLUE":              15,
	"BALL_PLACEMENT_YELLOW":  16,
	"BALL_PLACEMENT_BLUE":    17,
}

func (x Referee_Command) Enum() *Referee_Command {
	p := new(Referee_Command)
	*p = x
	return p
}

func (x Referee_Command) String() string {
	return proto.EnumName(Referee_Command_name, int32(x))
}

func (x *Referee_Command) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Referee_Command_value, data, "Referee_Command")
	if err != nil {
		return err
	}
	*x = Referee_Command(value)
	return nil
}

func (Referee_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f003bb08adc02ebb, []int{0, 1}
}

// Each UDP packet contains one of these messages.
type Referee struct {
	// The UNIX timestamp when the packet was sent, in microseconds.
	// Divide by 1,000,000 to get a time_t.
	PacketTimestamp *uint64        `protobuf:"varint,1,req,name=packet_timestamp,json=packetTimestamp" json:"packet_timestamp,omitempty"`
	Stage           *Referee_Stage `protobuf:"varint,2,req,name=stage,enum=Referee_Stage" json:"stage,omitempty"`
	// The number of microseconds left in the stage.
	// The following stages have this value; the rest do not:
	// NORMAL_FIRST_HALF
	// NORMAL_HALF_TIME
	// NORMAL_SECOND_HALF
	// EXTRA_TIME_BREAK
	// EXTRA_FIRST_HALF
	// EXTRA_HALF_TIME
	// EXTRA_SECOND_HALF
	// PENALTY_SHOOTOUT_BREAK
	//
	// If the stage runs over its specified time, this value
	// becomes negative.
	StageTimeLeft *int32           `protobuf:"zigzag32,3,opt,name=stage_time_left,json=stageTimeLeft" json:"stage_time_left,omitempty"`
	Command       *Referee_Command `protobuf:"varint,4,req,name=command,enum=Referee_Command" json:"command,omitempty"`
	// The number of commands issued since startup (mod 2^32).
	CommandCounter *uint32 `protobuf:"varint,5,req,name=command_counter,json=commandCounter" json:"command_counter,omitempty"`
	// The UNIX timestamp when the command was issued, in microseconds.
	// This value changes only when a new command is issued, not on each packet.
	CommandTimestamp *uint64 `protobuf:"varint,6,req,name=command_timestamp,json=commandTimestamp" json:"command_timestamp,omitempty"`
	// Information about the two teams.
	Yellow             *Referee_TeamInfo `protobuf:"bytes,7,req,name=yellow" json:"yellow,omitempty"`
	Blue               *Referee_TeamInfo `protobuf:"bytes,8,req,name=blue" json:"blue,omitempty"`
	DesignatedPosition *Referee_Point    `protobuf:"bytes,9,opt,name=designated_position,json=designatedPosition" json:"designated_position,omitempty"`
	// Information about the direction of play.
	// True, if the blue team will have it's goal on the positive x-axis of the ssl-vision coordinate system.
	// Obviously, the yellow team will play on the opposite half.
	BlueTeamOnPositiveHalf *bool `protobuf:"varint,10,opt,name=blue_team_on_positive_half,json=blueTeamOnPositiveHalf" json:"blue_team_on_positive_half,omitempty"`
	// The game event that caused the referee command.
	// deprecated in favor of game_events.
	GameEvent *Game_Event `protobuf:"bytes,11,opt,name=game_event,json=gameEvent" json:"game_event,omitempty"` // Deprecated: Do not use.
	// The command that will be issued after the current stoppage and ball placement to continue the game.
	NextCommand *Referee_Command `protobuf:"varint,12,opt,name=next_command,json=nextCommand,enum=Referee_Command" json:"next_command,omitempty"`
	// All game events that were detected since the last RUNNING state.
	// Will be cleared as soon as the game is continued.
	GameEvents []*GameEvent `protobuf:"bytes,13,rep,name=game_events,json=gameEvents" json:"game_events,omitempty"`
	// All non-finished proposed game events that may be processed next.
	ProposedGameEvents []*ProposedGameEvent `protobuf:"bytes,14,rep,name=proposed_game_events,json=proposedGameEvents" json:"proposed_game_events,omitempty"`
	// The time in microseconds that is remaining until the current action times out
	// The time will not be reset. It can get negative.
	// An autoRef would raise an appropriate event, if the time gets negative.
	// Possible actions where this time is relevant:
	//  * free kicks
	//  * kickoff, penalty kick, force start
	//  * ball placement
	CurrentActionTimeRemaining *int32   `protobuf:"varint,15,opt,name=current_action_time_remaining,json=currentActionTimeRemaining" json:"current_action_time_remaining,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *Referee) Reset()         { *m = Referee{} }
func (m *Referee) String() string { return proto.CompactTextString(m) }
func (*Referee) ProtoMessage()    {}
func (*Referee) Descriptor() ([]byte, []int) {
	return fileDescriptor_f003bb08adc02ebb, []int{0}
}

func (m *Referee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Referee.Unmarshal(m, b)
}
func (m *Referee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Referee.Marshal(b, m, deterministic)
}
func (m *Referee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Referee.Merge(m, src)
}
func (m *Referee) XXX_Size() int {
	return xxx_messageInfo_Referee.Size(m)
}
func (m *Referee) XXX_DiscardUnknown() {
	xxx_messageInfo_Referee.DiscardUnknown(m)
}

var xxx_messageInfo_Referee proto.InternalMessageInfo

func (m *Referee) GetPacketTimestamp() uint64 {
	if m != nil && m.PacketTimestamp != nil {
		return *m.PacketTimestamp
	}
	return 0
}

func (m *Referee) GetStage() Referee_Stage {
	if m != nil && m.Stage != nil {
		return *m.Stage
	}
	return Referee_NORMAL_FIRST_HALF_PRE
}

func (m *Referee) GetStageTimeLeft() int32 {
	if m != nil && m.StageTimeLeft != nil {
		return *m.StageTimeLeft
	}
	return 0
}

func (m *Referee) GetCommand() Referee_Command {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return Referee_HALT
}

func (m *Referee) GetCommandCounter() uint32 {
	if m != nil && m.CommandCounter != nil {
		return *m.CommandCounter
	}
	return 0
}

func (m *Referee) GetCommandTimestamp() uint64 {
	if m != nil && m.CommandTimestamp != nil {
		return *m.CommandTimestamp
	}
	return 0
}

func (m *Referee) GetYellow() *Referee_TeamInfo {
	if m != nil {
		return m.Yellow
	}
	return nil
}

func (m *Referee) GetBlue() *Referee_TeamInfo {
	if m != nil {
		return m.Blue
	}
	return nil
}

func (m *Referee) GetDesignatedPosition() *Referee_Point {
	if m != nil {
		return m.DesignatedPosition
	}
	return nil
}

func (m *Referee) GetBlueTeamOnPositiveHalf() bool {
	if m != nil && m.BlueTeamOnPositiveHalf != nil {
		return *m.BlueTeamOnPositiveHalf
	}
	return false
}

// Deprecated: Do not use.
func (m *Referee) GetGameEvent() *Game_Event {
	if m != nil {
		return m.GameEvent
	}
	return nil
}

func (m *Referee) GetNextCommand() Referee_Command {
	if m != nil && m.NextCommand != nil {
		return *m.NextCommand
	}
	return Referee_HALT
}

func (m *Referee) GetGameEvents() []*GameEvent {
	if m != nil {
		return m.GameEvents
	}
	return nil
}

func (m *Referee) GetProposedGameEvents() []*ProposedGameEvent {
	if m != nil {
		return m.ProposedGameEvents
	}
	return nil
}

func (m *Referee) GetCurrentActionTimeRemaining() int32 {
	if m != nil && m.CurrentActionTimeRemaining != nil {
		return *m.CurrentActionTimeRemaining
	}
	return 0
}

// Information about a single team.
type Referee_TeamInfo struct {
	// The team's name (empty string if operator has not typed anything).
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// The number of goals scored by the team during normal play and overtime.
	Score *uint32 `protobuf:"varint,2,req,name=score" json:"score,omitempty"`
	// The number of red cards issued to the team since the beginning of the game.
	RedCards *uint32 `protobuf:"varint,3,req,name=red_cards,json=redCards" json:"red_cards,omitempty"`
	// The amount of time (in microseconds) left on each yellow card issued to the team.
	// If no yellow cards are issued, this array has no elements.
	// Otherwise, times are ordered from smallest to largest.
	YellowCardTimes []uint32 `protobuf:"varint,4,rep,packed,name=yellow_card_times,json=yellowCardTimes" json:"yellow_card_times,omitempty"`
	// The total number of yellow cards ever issued to the team.
	YellowCards *uint32 `protobuf:"varint,5,req,name=yellow_cards,json=yellowCards" json:"yellow_cards,omitempty"`
	// The number of timeouts this team can still call.
	// If in a timeout right now, that timeout is excluded.
	Timeouts *uint32 `protobuf:"varint,6,req,name=timeouts" json:"timeouts,omitempty"`
	// The number of microseconds of timeout this team can use.
	TimeoutTime *uint32 `protobuf:"varint,7,req,name=timeout_time,json=timeoutTime" json:"timeout_time,omitempty"`
	// The pattern number of this team's goalkeeper.
	Goalkeeper *uint32 `protobuf:"varint,8,req,name=goalkeeper" json:"goalkeeper,omitempty"`
	// The total number of countable fouls that act towards yellow cards
	FoulCounter *uint32 `protobuf:"varint,9,opt,name=foul_counter,json=foulCounter" json:"foul_counter,omitempty"`
	// The number of consecutive ball placement failures of this team
	BallPlacementFailures *uint32 `protobuf:"varint,10,opt,name=ball_placement_failures,json=ballPlacementFailures" json:"ball_placement_failures,omitempty"`
	// Indicate if the team is able and allowed to place the ball
	CanPlaceBall *bool `protobuf:"varint,12,opt,name=can_place_ball,json=canPlaceBall" json:"can_place_ball,omitempty"`
	// The maximum number of bots allowed on the field based on division and cards
	MaxAllowedBots *uint32 `protobuf:"varint,13,opt,name=max_allowed_bots,json=maxAllowedBots" json:"max_allowed_bots,omitempty"`
	// The team has submitted an intent to substitute one or more robots at the next chance
	BotSubstitutionIntent *bool    `protobuf:"varint,14,opt,name=bot_substitution_intent,json=botSubstitutionIntent" json:"bot_substitution_intent,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Referee_TeamInfo) Reset()         { *m = Referee_TeamInfo{} }
func (m *Referee_TeamInfo) String() string { return proto.CompactTextString(m) }
func (*Referee_TeamInfo) ProtoMessage()    {}
func (*Referee_TeamInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f003bb08adc02ebb, []int{0, 0}
}

func (m *Referee_TeamInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Referee_TeamInfo.Unmarshal(m, b)
}
func (m *Referee_TeamInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Referee_TeamInfo.Marshal(b, m, deterministic)
}
func (m *Referee_TeamInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Referee_TeamInfo.Merge(m, src)
}
func (m *Referee_TeamInfo) XXX_Size() int {
	return xxx_messageInfo_Referee_TeamInfo.Size(m)
}
func (m *Referee_TeamInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Referee_TeamInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Referee_TeamInfo proto.InternalMessageInfo

func (m *Referee_TeamInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Referee_TeamInfo) GetScore() uint32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *Referee_TeamInfo) GetRedCards() uint32 {
	if m != nil && m.RedCards != nil {
		return *m.RedCards
	}
	return 0
}

func (m *Referee_TeamInfo) GetYellowCardTimes() []uint32 {
	if m != nil {
		return m.YellowCardTimes
	}
	return nil
}

func (m *Referee_TeamInfo) GetYellowCards() uint32 {
	if m != nil && m.YellowCards != nil {
		return *m.YellowCards
	}
	return 0
}

func (m *Referee_TeamInfo) GetTimeouts() uint32 {
	if m != nil && m.Timeouts != nil {
		return *m.Timeouts
	}
	return 0
}

func (m *Referee_TeamInfo) GetTimeoutTime() uint32 {
	if m != nil && m.TimeoutTime != nil {
		return *m.TimeoutTime
	}
	return 0
}

func (m *Referee_TeamInfo) GetGoalkeeper() uint32 {
	if m != nil && m.Goalkeeper != nil {
		return *m.Goalkeeper
	}
	return 0
}

func (m *Referee_TeamInfo) GetFoulCounter() uint32 {
	if m != nil && m.FoulCounter != nil {
		return *m.FoulCounter
	}
	return 0
}

func (m *Referee_TeamInfo) GetBallPlacementFailures() uint32 {
	if m != nil && m.BallPlacementFailures != nil {
		return *m.BallPlacementFailures
	}
	return 0
}

func (m *Referee_TeamInfo) GetCanPlaceBall() bool {
	if m != nil && m.CanPlaceBall != nil {
		return *m.CanPlaceBall
	}
	return false
}

func (m *Referee_TeamInfo) GetMaxAllowedBots() uint32 {
	if m != nil && m.MaxAllowedBots != nil {
		return *m.MaxAllowedBots
	}
	return 0
}

func (m *Referee_TeamInfo) GetBotSubstitutionIntent() bool {
	if m != nil && m.BotSubstitutionIntent != nil {
		return *m.BotSubstitutionIntent
	}
	return false
}

// The coordinates of the Designated Position. These are measured in
// millimetres and correspond to SSL-Vision coordinates. These fields are
// always either both present (in the case of a ball placement command) or
// both absent (in the case of any other command).
type Referee_Point struct {
	X                    *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Referee_Point) Reset()         { *m = Referee_Point{} }
func (m *Referee_Point) String() string { return proto.CompactTextString(m) }
func (*Referee_Point) ProtoMessage()    {}
func (*Referee_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_f003bb08adc02ebb, []int{0, 1}
}

func (m *Referee_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Referee_Point.Unmarshal(m, b)
}
func (m *Referee_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Referee_Point.Marshal(b, m, deterministic)
}
func (m *Referee_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Referee_Point.Merge(m, src)
}
func (m *Referee_Point) XXX_Size() int {
	return xxx_messageInfo_Referee_Point.Size(m)
}
func (m *Referee_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Referee_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Referee_Point proto.InternalMessageInfo

func (m *Referee_Point) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Referee_Point) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type ProposedGameEvent struct {
	// The UNIX timestamp when the game event proposal will time out, in microseconds.
	ValidUntil *uint64 `protobuf:"varint,1,req,name=valid_until,json=validUntil" json:"valid_until,omitempty"`
	// The identifier of the proposer.
	ProposerId *string `protobuf:"bytes,2,req,name=proposer_id,json=proposerId" json:"proposer_id,omitempty"`
	// The proposed game event.
	GameEvent            *GameEvent `protobuf:"bytes,3,req,name=game_event,json=gameEvent" json:"game_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProposedGameEvent) Reset()         { *m = ProposedGameEvent{} }
func (m *ProposedGameEvent) String() string { return proto.CompactTextString(m) }
func (*ProposedGameEvent) ProtoMessage()    {}
func (*ProposedGameEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f003bb08adc02ebb, []int{1}
}

func (m *ProposedGameEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposedGameEvent.Unmarshal(m, b)
}
func (m *ProposedGameEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposedGameEvent.Marshal(b, m, deterministic)
}
func (m *ProposedGameEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposedGameEvent.Merge(m, src)
}
func (m *ProposedGameEvent) XXX_Size() int {
	return xxx_messageInfo_ProposedGameEvent.Size(m)
}
func (m *ProposedGameEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposedGameEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ProposedGameEvent proto.InternalMessageInfo

func (m *ProposedGameEvent) GetValidUntil() uint64 {
	if m != nil && m.ValidUntil != nil {
		return *m.ValidUntil
	}
	return 0
}

func (m *ProposedGameEvent) GetProposerId() string {
	if m != nil && m.ProposerId != nil {
		return *m.ProposerId
	}
	return ""
}

func (m *ProposedGameEvent) GetGameEvent() *GameEvent {
	if m != nil {
		return m.GameEvent
	}
	return nil
}

func init() {
	proto.RegisterEnum("Referee_Stage", Referee_Stage_name, Referee_Stage_value)
	proto.RegisterEnum("Referee_Command", Referee_Command_name, Referee_Command_value)
	proto.RegisterType((*Referee)(nil), "Referee")
	proto.RegisterType((*Referee_TeamInfo)(nil), "Referee.TeamInfo")
	proto.RegisterType((*Referee_Point)(nil), "Referee.Point")
	proto.RegisterType((*ProposedGameEvent)(nil), "ProposedGameEvent")
}

func init() { proto.RegisterFile("ssl_referee.proto", fileDescriptor_f003bb08adc02ebb) }

var fileDescriptor_f003bb08adc02ebb = []byte{
	// 1122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0xae, 0x64, 0x3b, 0xb1, 0x8f, 0x2c, 0x5b, 0xde, 0x24, 0xad, 0x6a, 0x06, 0x30, 0xa1, 0x80,
	0x4b, 0x67, 0x3c, 0x10, 0x66, 0x98, 0x81, 0x1b, 0x46, 0x76, 0xe5, 0xc6, 0x53, 0x25, 0xf2, 0xac,
	0xd5, 0x81, 0x5e, 0xed, 0x6c, 0xec, 0x75, 0xd0, 0x54, 0x3f, 0x1e, 0x49, 0x2e, 0xe9, 0x1d, 0x4f,
	0xc0, 0xbb, 0xf1, 0x08, 0xdc, 0xf0, 0x1c, 0xcc, 0x1e, 0xad, 0x62, 0x27, 0x29, 0x77, 0xbb, 0xdf,
	0xf7, 0x9d, 0x6f, 0xcf, 0xd9, 0x73, 0xb4, 0x82, 0x5e, 0x9e, 0x47, 0x2c, 0x13, 0x6b, 0x91, 0x09,
	0x31, 0xda, 0x64, 0x69, 0x91, 0xf6, 0x8f, 0x25, 0x74, 0xcd, 0x63, 0xc1, 0xc4, 0x7b, 0x91, 0x14,
	0x0a, 0x7d, 0x7a, 0x17, 0x65, 0x67, 0xdf, 0x7d, 0xff, 0x53, 0x49, 0x9d, 0xfe, 0xd3, 0x85, 0x43,
	0x5a, 0x5a, 0x90, 0xe7, 0x60, 0x6d, 0xf8, 0xf2, 0x9d, 0x28, 0x58, 0x11, 0xc6, 0x22, 0x2f, 0x78,
	0xbc, 0xb1, 0xb5, 0x81, 0x3e, 0xac, 0xd3, 0x6e, 0x89, 0x07, 0x15, 0x4c, 0x9e, 0x41, 0x23, 0x2f,
	0xf8, 0xb5, 0xb0, 0xf5, 0x81, 0x3e, 0xec, 0x9c, 0x75, 0x46, 0xca, 0x63, 0xb4, 0x90, 0x28, 0x2d,
	0x49, 0xf2, 0x35, 0x74, 0x71, 0x81, 0x7e, 0x2c, 0x12, 0xeb, 0xc2, 0xae, 0x0d, 0xb4, 0x61, 0x8f,
	0x9a, 0x08, 0x4b, 0x3b, 0x4f, 0xac, 0x0b, 0xf2, 0x2d, 0x1c, 0x2e, 0xd3, 0x38, 0xe6, 0xc9, 0xca,
	0xae, 0xa3, 0x9f, 0x75, 0xeb, 0x37, 0x29, 0x71, 0x5a, 0x09, 0xc8, 0x37, 0xd0, 0x55, 0x4b, 0xb6,
	0x4c, 0xb7, 0x49, 0x21, 0x32, 0xbb, 0x31, 0xd0, 0x87, 0x26, 0xed, 0x28, 0x78, 0x52, 0xa2, 0xe4,
	0x05, 0xf4, 0x2a, 0xe1, 0xae, 0x9c, 0x03, 0x2c, 0xc7, 0x52, 0xc4, 0xae, 0x9e, 0xe7, 0x70, 0xf0,
	0x41, 0x44, 0x51, 0xfa, 0x87, 0x7d, 0x38, 0xd0, 0x87, 0xc6, 0x59, 0xef, 0x36, 0x81, 0x40, 0xf0,
	0x78, 0x96, 0xac, 0x53, 0xaa, 0x04, 0xe4, 0x2b, 0xa8, 0x5f, 0x45, 0x5b, 0x61, 0x37, 0xff, 0x4f,
	0x88, 0x34, 0xf9, 0x05, 0x8e, 0x56, 0x22, 0x0f, 0xaf, 0x13, 0x5e, 0x88, 0x15, 0xdb, 0xa4, 0x79,
	0x58, 0x84, 0x69, 0x62, 0xb7, 0x06, 0xda, 0xd0, 0xd8, 0xbb, 0xaf, 0x79, 0x1a, 0x26, 0x05, 0x25,
	0x3b, 0xe9, 0x5c, 0x29, 0xc9, 0xcf, 0xd0, 0x97, 0x46, 0xac, 0x10, 0x3c, 0x66, 0x69, 0xa2, 0x2c,
	0xde, 0x0b, 0xf6, 0x3b, 0x8f, 0xd6, 0x36, 0x0c, 0xb4, 0x61, 0x93, 0x3e, 0x96, 0x0a, 0x79, 0xb0,
	0x9f, 0xcc, 0x15, 0x7d, 0xce, 0xa3, 0x35, 0x19, 0x01, 0xec, 0xda, 0x6d, 0x1b, 0x78, 0xa6, 0x31,
	0x7a, 0x25, 0x21, 0x57, 0x42, 0x63, 0xdd, 0xd6, 0x68, 0x4b, 0x4a, 0x70, 0x4b, 0x7e, 0x80, 0x76,
	0x22, 0x6e, 0x0a, 0x56, 0x75, 0xa1, 0x3d, 0xd0, 0x3e, 0xda, 0x05, 0x43, 0xaa, 0xd4, 0x86, 0xbc,
	0x00, 0x63, 0x77, 0x48, 0x6e, 0x9b, 0x83, 0xda, 0xd0, 0x38, 0x03, 0x3c, 0x05, 0x5d, 0x29, 0xdc,
	0x1e, 0x90, 0x93, 0x97, 0x70, 0xbc, 0xc9, 0xd2, 0x4d, 0x9a, 0x8b, 0x15, 0xdb, 0x8f, 0xea, 0x60,
	0x14, 0x19, 0xcd, 0x15, 0xb9, 0x8b, 0x26, 0x9b, 0xfb, 0x50, 0x4e, 0x1c, 0xf8, 0x74, 0xb9, 0xcd,
	0x32, 0x39, 0xc3, 0x7c, 0x29, 0x6f, 0xa9, 0x9c, 0xac, 0x4c, 0xc4, 0x3c, 0x4c, 0xc2, 0xe4, 0xda,
	0xee, 0x0e, 0xb4, 0x61, 0x83, 0xf6, 0x95, 0xc8, 0x41, 0x8d, 0xec, 0x32, 0xad, 0x14, 0xfd, 0x7f,
	0x6b, 0xd0, 0xac, 0x5a, 0x45, 0x08, 0xd4, 0x13, 0x1e, 0x0b, 0x9c, 0xf2, 0x16, 0xc5, 0x35, 0x39,
	0x86, 0x46, 0xbe, 0x4c, 0xb3, 0x72, 0xb4, 0x4d, 0x5a, 0x6e, 0xc8, 0x27, 0xd0, 0xca, 0xc4, 0x8a,
	0x2d, 0x79, 0xb6, 0xca, 0xed, 0x1a, 0x32, 0xcd, 0x4c, 0xac, 0x26, 0x72, 0x4f, 0x46, 0xd0, 0x2b,
	0x87, 0x03, 0xf9, 0x72, 0xdc, 0xec, 0xfa, 0xa0, 0x36, 0x34, 0xc7, 0xba, 0xa5, 0xd1, 0x6e, 0x49,
	0x4a, 0x2d, 0x4e, 0x1c, 0xf9, 0x02, 0xda, 0x7b, 0xfa, 0x5c, 0x0d, 0xb0, 0xb1, 0x93, 0xe5, 0xa4,
	0x0f, 0x4d, 0x69, 0x93, 0x6e, 0x8b, 0x1c, 0x87, 0xd6, 0xa4, 0xb7, 0x7b, 0x19, 0xae, 0xd6, 0x78,
	0x14, 0x8e, 0xac, 0x49, 0x0d, 0x85, 0xc9, 0x23, 0xc8, 0x67, 0x00, 0xd7, 0x29, 0x8f, 0xde, 0x09,
	0xb1, 0x11, 0x19, 0x8e, 0xaa, 0x49, 0xf7, 0x10, 0x69, 0xb1, 0x4e, 0xb7, 0xd1, 0xed, 0x27, 0x24,
	0xc7, 0xd2, 0xa4, 0x86, 0xc4, 0xaa, 0xef, 0xe7, 0x47, 0x78, 0x72, 0xc5, 0xa3, 0x88, 0x6d, 0x22,
	0xbe, 0x14, 0xb1, 0xbc, 0xf2, 0x35, 0x0f, 0xa3, 0x6d, 0x26, 0x72, 0x1c, 0x3e, 0x93, 0x9e, 0x48,
	0x7a, 0x5e, 0xb1, 0x53, 0x45, 0x92, 0x67, 0xd0, 0x59, 0xf2, 0xa4, 0x0c, 0x63, 0x52, 0x82, 0xd3,
	0xd4, 0xa4, 0xed, 0x25, 0x4f, 0x50, 0x3d, 0xe6, 0x51, 0x44, 0x86, 0x60, 0xc5, 0xfc, 0x86, 0x71,
	0x59, 0xb1, 0x58, 0xb1, 0xab, 0x14, 0x27, 0x48, 0xda, 0x76, 0x62, 0x7e, 0xe3, 0x94, 0xf0, 0x38,
	0x2d, 0x72, 0xcc, 0x23, 0x2d, 0x58, 0xbe, 0xbd, 0xca, 0x8b, 0xb0, 0xd8, 0x62, 0xd7, 0xc3, 0xa4,
	0x90, 0x83, 0xdd, 0x41, 0xe3, 0x93, 0xab, 0xb4, 0x58, 0xec, 0xb1, 0x33, 0x24, 0xfb, 0x5f, 0x42,
	0x03, 0x3f, 0x2e, 0xd2, 0x06, 0xed, 0x06, 0x3b, 0xac, 0x53, 0xed, 0x46, 0xee, 0x3e, 0x60, 0x6b,
	0x75, 0xaa, 0x7d, 0x38, 0xfd, 0x5b, 0x87, 0x06, 0x3e, 0x59, 0xe4, 0x29, 0x9c, 0x5c, 0xfa, 0xf4,
	0xc2, 0xf1, 0xd8, 0x74, 0x46, 0x17, 0x01, 0x3b, 0x77, 0xbc, 0x29, 0x9b, 0x53, 0xd7, 0x7a, 0x44,
	0x4e, 0xa0, 0xf7, 0x80, 0xb2, 0x34, 0x72, 0x0c, 0x96, 0x82, 0x51, 0x1b, 0xcc, 0x2e, 0x5c, 0x4b,
	0x27, 0x7d, 0x78, 0xac, 0xd0, 0x85, 0x3b, 0xf1, 0x2f, 0x5f, 0xee, 0x8c, 0x6a, 0xe4, 0x31, 0x90,
	0x87, 0x9c, 0x55, 0x97, 0x4e, 0xee, 0x6f, 0x01, 0x75, 0xd0, 0x83, 0x8d, 0xa9, 0xeb, 0xbc, 0xb6,
	0x1a, 0xc4, 0x86, 0xe3, 0x12, 0xbd, 0x97, 0xd0, 0xc1, 0x4e, 0xbf, 0x97, 0xcf, 0x21, 0x39, 0x82,
	0x6e, 0x89, 0xee, 0xd2, 0x69, 0xca, 0xb2, 0x4a, 0xf0, 0x7e, 0x36, 0x2d, 0x59, 0xd6, 0x03, 0xca,
	0x02, 0x59, 0xc0, 0xdc, 0xbd, 0x74, 0xbc, 0xe0, 0x2d, 0x5b, 0x9c, 0xfb, 0x7e, 0xe0, 0xbf, 0x09,
	0x54, 0x4a, 0x86, 0x3c, 0xf8, 0x3e, 0x67, 0xb5, 0x89, 0x09, 0xad, 0xb9, 0xbf, 0x08, 0xd8, 0x2b,
	0xe7, 0xc2, 0xb5, 0xcc, 0xd3, 0xbf, 0x6a, 0x70, 0x58, 0xbd, 0x11, 0x4d, 0xa8, 0x9f, 0x3b, 0x5e,
	0x60, 0x3d, 0x92, 0xab, 0x45, 0xe0, 0xcf, 0x2d, 0x8d, 0x58, 0xd0, 0xae, 0x6e, 0x21, 0x70, 0x68,
	0x60, 0xe9, 0xa4, 0x0b, 0xc6, 0xd4, 0xa7, 0x13, 0x57, 0x01, 0x35, 0xcc, 0x81, 0xba, 0x73, 0x87,
	0xba, 0xec, 0xf5, 0x6c, 0xf2, 0xda, 0x9f, 0x4e, 0xd9, 0x5b, 0xd7, 0xf3, 0xfc, 0x5f, 0xad, 0xba,
	0xbc, 0x96, 0xfb, 0xdc, 0xd8, 0x7b, 0xe3, 0x5a, 0x8d, 0xfd, 0xa8, 0x2a, 0x4b, 0x15, 0x75, 0xb0,
	0x1f, 0x55, 0x71, 0x18, 0x75, 0x28, 0x9b, 0xf2, 0x72, 0x46, 0xdd, 0x49, 0xc0, 0xa6, 0xd4, 0x75,
	0xab, 0x88, 0xa6, 0xac, 0x75, 0x1f, 0x47, 0x75, 0x4b, 0xfa, 0xcc, 0x2e, 0x3f, 0xa2, 0x07, 0xe9,
	0x73, 0x97, 0xc1, 0x08, 0x83, 0x10, 0xe8, 0xc8, 0x5e, 0xc8, 0x6b, 0x54, 0xda, 0xb6, 0xbc, 0x82,
	0x0a, 0x43, 0x95, 0x49, 0x8e, 0xc0, 0x78, 0xe5, 0x3b, 0x5e, 0x25, 0xe9, 0xf4, 0xf5, 0xa6, 0x46,
	0x7a, 0xd0, 0x42, 0x10, 0x35, 0x5d, 0x84, 0x9e, 0xc2, 0xc9, 0xd8, 0xf1, 0x3c, 0x36, 0xf7, 0x9c,
	0x89, 0x7b, 0xe1, 0x5e, 0xde, 0x9a, 0x5a, 0xe4, 0x09, 0x1c, 0xdd, 0xa3, 0x30, 0xae, 0x77, 0xfa,
	0xa7, 0x06, 0xbd, 0x07, 0xef, 0x2b, 0xf9, 0x1c, 0x8c, 0xf7, 0x3c, 0x0a, 0x57, 0x6c, 0x9b, 0x14,
	0x61, 0xa4, 0x7e, 0xf4, 0x80, 0xd0, 0x1b, 0x89, 0x48, 0x81, 0x7a, 0x82, 0x33, 0x16, 0xae, 0xf0,
	0x9b, 0x69, 0x51, 0xa8, 0xa0, 0xd9, 0x8a, 0x3c, 0xbf, 0xf3, 0x97, 0xa9, 0xe1, 0xff, 0x70, 0xff,
	0xfd, 0xdf, 0xfd, 0x60, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x8b, 0xd5, 0x4d, 0xab, 0x08,
	0x00, 0x00,
}
