Documentation: RRT/src/main_connect.cpp File Reference
main_connect.cpp File Reference
#include <bits/stdc++.h>
#include "../include/RRTConnect_implementation.hpp"
Functions
bool check (Utils::Point< int > cur)
int main ()
Function Documentation
bool check (Utils::Point< int > cur)
Definition at line 7 of file main_connect.cpp.
References GVector::abs(), Utils::Point< T >::x, and Utils::Point< T >::y.
Referenced by main().
 {
     if(abs(cur.x)<2000 && abs(cur.y)<2000)
         return true;
     return false;
 }
int main ()
Definition at line 14 of file main_connect.cpp.
References check(), rrt::RRT< T >::getPointsOnPath(), velocity.pid_::i, path(), rrt::RRT< T >::plan(), rrt::RRT< T >::setBiasParameter(), rrt::RRT< T >::setCheckPointFunction(), rrt::RRT< T >::setEndPoints(), rrt::RRT< T >::setHalfDimensions(), rrt::RRT< T >::setMaxIterations(), rrt::RRT< T >::setOrigin(), rrt::RRT< T >::setStepLength(), Utils::Point< T >::x, role._GoToPoint::x, Utils::Point< T >::y, and role._GoToPoint::y.
 {
     srand(time(NULL));
     Utils::Point<int> start,finish,origin;
     start.x=-10;
     start.y=10;
     finish.x=1000;
     finish.y=730;
     origin.x=0;
     origin.y=0;
     RRT<int> test;
     test.setEndPoints(start,finish);
     test.setCheckPointFunction(*(check));
     test.setStepLength(200);
     test.setHalfDimensions(3000.0,2000.0);
     test.setBiasParameter(100);
     test.setOrigin(origin);
     test.setMaxIterations(10000);
     test.plan();
     cout<<"#################################################"<<endl;
     deque<Utils::Point<int> > path=test.getPointsOnPath();
     for(int i=0;i<path.size();i++)
         cout<<path[i].x<<","<<path[i].y<<endl;
 }