Documentation: grSim/include/sslworld.h File Reference
sslworld.h File Reference
#include <QGLWidget>
#include <QObject>
#include <QUdpSocket>
#include <QList>
#include "graphics.h"
#include "physics/pworld.h"
#include "physics/pball.h"
#include "physics/pground.h"
#include "physics/pfixedbox.h"
#include "physics/pray.h"
#include "net/robocup_ssl_server.h"
#include "robot.h"
#include "configwidget.h"
#include "config.h"
Data Structures
class SendingPacket
class SSLWorld
class RobotsFomation
Macros
#define WALL_COUNT 10
Functions
dReal fric (dReal f)
int robotIndex (int robot, int team)
Macro Definition Documentation
#define WALL_COUNT 10
Definition at line 43 of file sslworld.h.
Referenced by SSLWorld::SSLWorld().
Function Documentation
dReal fric (dReal f)
Definition at line 45 of file sslworld.cpp.
Referenced by MainWindow::changeBallGroundSurface(), SSLWorld::SSLWorld(), and wheelCallBack().
 {
     if (f==-1) return dInfinity;
     return f;
 }
int robotIndex (int robot, int team)
Definition at line 51 of file sslworld.cpp.
References ROBOT_COUNT.
Referenced by MainWindow::changeCurrentRobot(), MainWindow::changeCurrentTeam(), MainWindow::customFPS(), GLWidget::keyPressEvent(), GLWidget::lockCameraToRobot(), GLWidget::moveCurrentRobot(), GLWidget::moveRobotHere(), GLWidget::paintGL(), SSLWorld::recvActions(), GLWidget::reform(), GLWidget::resetCurrentRobot(), GLWidget::resetRobot(), RobotsFomation::resetRobots(), MainWindow::setCurrentRobotPosition(), GLWidget::switchRobotOnOff(), GLWidget::unselectRobot(), MainWindow::update(), and MainWindow::updateRobotLabel().
 {
     if (robot >= ROBOT_COUNT) return -1;
     return robot + team*ROBOT_COUNT;
 }