Documentation: CMVision::RegionFilter Class Reference
CMVision::RegionFilter Class Reference
#include <cmvision_region.h>
Public Member Functions
RegionFilter ()
void setArea (ClosedRangeInt &_area)
void setWidth (ClosedRangeInt &_width)
void setHeight (ClosedRangeInt &_height)
void setArea (int _min, int _max)
void setWidth (int _min, int _max)
void setHeight (int _min, int _max)
ClosedRangeInt getArea ()
ClosedRangeInt getWidth ()
ClosedRangeInt getHeight ()
bool check (const CMVision::Region &reg)
void init (const CMVision::Region *region_list)
const CMVision::Region * getNext ()
Protected Attributes
const CMVision::Region * reg
int w
int h
ClosedRangeInt area
ClosedRangeInt width
ClosedRangeInt height
Detailed Description
Definition at line 183 of file cmvision_region.h.
Constructor & Destructor Documentation
CMVision::RegionFilter::RegionFilter () inline
Definition at line 191 of file cmvision_region.h.
 {reg=0; w=0; h=0; area.set(0,1000000); width.set(0,1000); height.set(0,1000); }
Member Function Documentation
bool CMVision::RegionFilter::check (const CMVision::Region & reg) inline
Definition at line 222 of file cmvision_region.h.
References CMVision::Region::area, CMVision::Region::x1, CMVision::Region::x2, CMVision::Region::y1, and CMVision::Region::y2.
Referenced by CMPattern::TeamDetector::findRobotsByModel().
{
     int w = reg.x2 - reg.x1 + 1;
     int h = reg.y2 - reg.y1 + 1;
     return(area.inside(reg.area) && width.inside(w) && height.inside(h));
   }
ClosedRangeInt CMVision::RegionFilter::getArea () inline
Definition at line 213 of file cmvision_region.h.
{
     return area;
   }
ClosedRangeInt CMVision::RegionFilter::getHeight () inline
Definition at line 219 of file cmvision_region.h.
{
     return height;
   }
const CMVision::Region* CMVision::RegionFilter::getNext () inline
Definition at line 236 of file cmvision_region.h.
References CMVision::Region::area, CMVision::Region::height(), CMVision::Region::next, and CMVision::Region::width().
Referenced by CMPattern::TeamDetector::findRobotsByModel(), CMPattern::TeamDetector::findRobotsByTeamMarkerOnly(), and PluginDetectBalls::process().
   {
     // terminate when no regions, or no suitably large ones
     if(reg==0) return(0);
     // find the next region matching our ranges
     while(reg!=0) {
       w = reg->width();
       h = reg->height();
       if(reg->area < area.min) return(0);
       if(width.inside(w) && height.inside(h)){
         const CMVision::Region *match = reg;
         reg = reg->next;
         return(match);
       }
       reg = reg->next;
     }
     return(0);
   }
ClosedRangeInt CMVision::RegionFilter::getWidth () inline
Definition at line 216 of file cmvision_region.h.
References CMVision::Run::width.
{
     return width;
   }
void CMVision::RegionFilter::init (const CMVision::Region * region_list) inline
Definition at line 229 of file cmvision_region.h.
References CMVision::Region::area, and CMVision::Region::next.
Referenced by CMPattern::TeamDetector::findRobotsByModel(), CMPattern::TeamDetector::findRobotsByTeamMarkerOnly(), and PluginDetectBalls::process().
{
     reg = region_list;
     // skip too-large regions in sorted region list
     while(reg!=0 && reg->area>area.max) reg = reg->next;
   }
void CMVision::RegionFilter::setArea (ClosedRangeInt & _area) inline
Definition at line 192 of file cmvision_region.h.
Referenced by CMPattern::TeamDetector::init(), and PluginDetectBalls::process().
{
     area=_area;
   }
void CMVision::RegionFilter::setArea (int _min, int _max) inline
Definition at line 201 of file cmvision_region.h.
{
     area.min=_min;
     area.max=_max;
   }
void CMVision::RegionFilter::setHeight (ClosedRangeInt & _height) inline
Definition at line 198 of file cmvision_region.h.
Referenced by CMPattern::TeamDetector::init(), and PluginDetectBalls::process().
{
     height=_height;
   }
void CMVision::RegionFilter::setHeight (int _min, int _max) inline
Definition at line 209 of file cmvision_region.h.
{
     height.min=_min;
     height.max=_max;
   }
void CMVision::RegionFilter::setWidth (ClosedRangeInt & _width) inline
Definition at line 195 of file cmvision_region.h.
Referenced by CMPattern::TeamDetector::init(), and PluginDetectBalls::process().
{
     width=_width;
   }
void CMVision::RegionFilter::setWidth (int _min, int _max) inline
Definition at line 205 of file cmvision_region.h.
{
     width.min=_min;
     width.max=_max;
   }
Field Documentation
ClosedRangeInt CMVision::RegionFilter::area protected
Definition at line 187 of file cmvision_region.h.
int CMVision::RegionFilter::h protected
Definition at line 186 of file cmvision_region.h.
ClosedRangeInt CMVision::RegionFilter::height protected
Definition at line 189 of file cmvision_region.h.
const CMVision::Region* CMVision::RegionFilter::reg protected
Definition at line 185 of file cmvision_region.h.
int CMVision::RegionFilter::w protected
Definition at line 186 of file cmvision_region.h.
ClosedRangeInt CMVision::RegionFilter::width protected
Definition at line 188 of file cmvision_region.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/cmvision/cmvision_region.h