Documentation: CameraCalibrationWidget Class Reference
CameraCalibrationWidget Class Reference
#include <cameracalibwidget.h>
Public Slots
void is_clicked_initial ()
void is_clicked_full ()
void is_clicked_reset ()
void edges_is_clicked ()
void cameraheight_slider_changed (int val)
void distortion_slider_changed (int val)
void line_search_slider_changed (int val)
Public Member Functions
void focusInEvent (QFocusEvent *event)
CameraCalibrationWidget (CameraParameters &cp)
~CameraCalibrationWidget ()
bool getDetectEdges ()
void resetDetectEdges ()
void set_slider_from_vars ()
Data Fields
CameraParameters & camera_parameters
Protected Attributes
QSlider * lineSearchCorridorWidthSlider
QLabel * lineSearchCorridorWidthLabelRight
QSlider * cameraHeightSlider
QLabel * cameraHeightLabelRight
QSlider * distortionSlider
QLabel * distortionLabelRight
bool detectEdges
Detailed Description
Definition at line 34 of file cameracalibwidget.h.
Constructor & Destructor Documentation
CameraCalibrationWidget::CameraCalibrationWidget (CameraParameters & cp)
Definition at line 32 of file cameracalibwidget.cpp.
References CameraParameters::additional_calibration_information, camera_parameters, cameraheight_slider_changed(), cameraHeightLabelRight, cameraHeightSlider, CameraParameters::distortion, distortion_slider_changed(), distortionLabelRight, distortionSlider, edges_is_clicked(), VarTypes::VarDoubleVal::getDouble(), VarTypes::VarDouble::getMax(), VarTypes::VarDouble::getMin(), is_clicked_full(), is_clicked_initial(), is_clicked_reset(), CameraParameters::AdditionalCalibrationInformation::line_search_corridor_width, line_search_slider_changed(), lineSearchCorridorWidthLabelRight, lineSearchCorridorWidthSlider, and CameraParameters::tz.
                                                                       : camera_parameters(_cp), detectEdges(false)
 {
   // The calibration points and the fit button:
   QGroupBox* calibrationStepsBox = new QGroupBox(tr("Calibration Steps"));
   QPushButton* initialCalibrationButton = new QPushButton(tr("Do initial calibration"));
   connect(initialCalibrationButton, SIGNAL(clicked()), SLOT(is_clicked_initial()));
   QPushButton* fullCalibrationButton = new QPushButton(tr("Do full calibration"));
   connect(fullCalibrationButton, SIGNAL(clicked()), SLOT(is_clicked_full()));
   QPushButton* additionalPointsButton = new QPushButton(tr("Detect additional calibration points"));
   connect(additionalPointsButton, SIGNAL(clicked()), SLOT(edges_is_clicked()));
   QPushButton* resetButton = new QPushButton(tr("Reset"));
   connect(resetButton, SIGNAL(clicked()), SLOT(is_clicked_reset()));
   QGroupBox* calibrationParametersBox = new QGroupBox(tr("Calibration Parameters"));
   // The slider for the width of the line search corridor:
   QLabel* widthLabel = new QLabel("Line Search Corridor Width (in mm) ");
   lineSearchCorridorWidthSlider = new QSlider(Qt::Horizontal);
   lineSearchCorridorWidthSlider->setMinimum(50);
   lineSearchCorridorWidthSlider->setMaximum(800);
   lineSearchCorridorWidthSlider->setValue((int)(camera_parameters.additional_calibration_information->line_search_corridor_width->getDouble()));
   lineSearchCorridorWidthLabelRight = new QLabel();
   lineSearchCorridorWidthLabelRight->setNum(200);
   connect(lineSearchCorridorWidthSlider, SIGNAL(valueChanged(int)), this, SLOT(line_search_slider_changed(int)));
   QGroupBox* cameraParametersBox = new QGroupBox(tr("Initial Camera Parameters"));
   // The slider for height control:
   QLabel* heightLabel = new QLabel("Camera Height (in mm) ");
   cameraHeightSlider = new QSlider(Qt::Horizontal);
   cameraHeightSlider->setMinimum((int)camera_parameters.tz->getMin());
   cameraHeightSlider->setMaximum((int)camera_parameters.tz->getMax());
   cameraHeightSlider->setValue((int)camera_parameters.tz->getDouble());
   cameraHeightLabelRight = new QLabel();
   cameraHeightLabelRight->setNum((int)camera_parameters.tz->getDouble());
   connect(cameraHeightSlider, SIGNAL(valueChanged(int)), this, SLOT(cameraheight_slider_changed(int)));
   // Distortion slider
   QLabel* distortionLabel = new QLabel("Distortion ");
   distortionSlider = new QSlider(Qt::Horizontal);
   distortionSlider->setMinimum((int)(camera_parameters.distortion->getMin()*100));
   distortionSlider->setMaximum((int)(camera_parameters.distortion->getMax()*100));
   distortionSlider->setValue((int)(camera_parameters.distortion->getDouble()*100));
   distortionLabelRight = new QLabel();
   distortionLabelRight->setNum(1./100. * (double)(distortionSlider->value()));
   connect(distortionSlider, SIGNAL(valueChanged(int)), this, SLOT(distortion_slider_changed(int)));
   // Layout for calibration control:
   QVBoxLayout *vbox = new QVBoxLayout;
   vbox->addWidget(initialCalibrationButton);
   vbox->addWidget(additionalPointsButton);
   vbox->addWidget(fullCalibrationButton);
   vbox->addWidget(resetButton);
   vbox->addStretch(1);
   calibrationStepsBox->setLayout(vbox);
   // Layout for calibration parameters
   QGridLayout* gridCalibration = new QGridLayout;
   gridCalibration->addWidget(widthLabel,0,0);
   gridCalibration->addWidget(lineSearchCorridorWidthSlider,0,1);
   gridCalibration->addWidget(lineSearchCorridorWidthLabelRight,0,2);
   calibrationParametersBox->setLayout(gridCalibration);
   // Layout for camera parameters
   QGridLayout* gridCamera = new QGridLayout;
   gridCamera->addWidget(heightLabel,0,0);
   gridCamera->addWidget(cameraHeightSlider,0,1);
   gridCamera->addWidget(cameraHeightLabelRight,0,2);
   gridCamera->addWidget(distortionLabel,1,0);
   gridCamera->addWidget(distortionSlider,1,1);
   gridCamera->addWidget(distortionLabelRight,1,2);
   cameraParametersBox->setLayout(gridCamera);
   // Overall layout:
   QVBoxLayout *vbox2 = new QVBoxLayout;
   vbox2->addWidget(calibrationStepsBox);
   vbox2->addWidget(calibrationParametersBox);
   vbox2->addWidget(cameraParametersBox);
   this->setLayout(vbox2);
 }
CameraCalibrationWidget::~CameraCalibrationWidget ()
Definition at line 108 of file cameracalibwidget.cpp.
 {
   // Destroy GUI here
 }
Member Function Documentation
void CameraCalibrationWidget::cameraheight_slider_changed (int val) slot
Definition at line 149 of file cameracalibwidget.cpp.
References camera_parameters, cameraHeightLabelRight, VarTypes::VarDouble::setDouble(), and CameraParameters::tz.
Referenced by CameraCalibrationWidget().
 {
   cameraHeightLabelRight->setNum(val);
   camera_parameters.tz->setDouble(val);
 }
void CameraCalibrationWidget::distortion_slider_changed (int val) slot
Definition at line 155 of file cameracalibwidget.cpp.
References camera_parameters, CameraParameters::distortion, distortionLabelRight, and VarTypes::VarDouble::setDouble().
Referenced by CameraCalibrationWidget().
 {
   double doubleVal = 1/100. * (double) val;
   distortionLabelRight->setNum(doubleVal);
   camera_parameters.distortion->setDouble(doubleVal);
 }
void CameraCalibrationWidget::edges_is_clicked () slot
Definition at line 137 of file cameracalibwidget.cpp.
References detectEdges.
Referenced by CameraCalibrationWidget().
 {
   detectEdges = true;
 }
void CameraCalibrationWidget::focusInEvent (QFocusEvent * event)
Definition at line 113 of file cameracalibwidget.cpp.
{
   (void)event;
   //forward the focus to the actual widget that we contain
   // gllut->setFocus(Qt::OtherFocusReason); left as an example for later use
 }
bool CameraCalibrationWidget::getDetectEdges () inline
Definition at line 43 of file cameracalibwidget.h.
References detectEdges.
Referenced by PluginCameraCalibration::process().
 {return detectEdges;}
void CameraCalibrationWidget::is_clicked_full () slot
Definition at line 125 of file cameracalibwidget.cpp.
References camera_parameters, CameraParameters::do_calibration(), CameraParameters::FULL_ESTIMATION, and set_slider_from_vars().
Referenced by CameraCalibrationWidget().
 {
   camera_parameters.do_calibration(CameraParameters::FULL_ESTIMATION);
   set_slider_from_vars();
 }
void CameraCalibrationWidget::is_clicked_initial () slot
Definition at line 119 of file cameracalibwidget.cpp.
References camera_parameters, CameraParameters::do_calibration(), CameraParameters::FOUR_POINT_INITIAL, and set_slider_from_vars().
Referenced by CameraCalibrationWidget().
 {
   camera_parameters.do_calibration(CameraParameters::FOUR_POINT_INITIAL);
   set_slider_from_vars();
 }
void CameraCalibrationWidget::is_clicked_reset () slot
Definition at line 131 of file cameracalibwidget.cpp.
References camera_parameters, CameraParameters::reset(), and set_slider_from_vars().
Referenced by CameraCalibrationWidget().
 {
   camera_parameters.reset();
   set_slider_from_vars();
 }
void CameraCalibrationWidget::line_search_slider_changed (int val) slot
Definition at line 162 of file cameracalibwidget.cpp.
References CameraParameters::additional_calibration_information, camera_parameters, CameraParameters::AdditionalCalibrationInformation::line_search_corridor_width, lineSearchCorridorWidthLabelRight, and VarTypes::VarDouble::setDouble().
Referenced by CameraCalibrationWidget().
 {
   camera_parameters.additional_calibration_information->line_search_corridor_width->setDouble(val);
   lineSearchCorridorWidthLabelRight->setNum(val);
 }
void CameraCalibrationWidget::resetDetectEdges () inline
Definition at line 45 of file cameracalibwidget.h.
References detectEdges, and set_slider_from_vars().
Referenced by PluginCameraCalibration::process().
 {detectEdges = false;}
void CameraCalibrationWidget::set_slider_from_vars ()
Definition at line 142 of file cameracalibwidget.cpp.
References CameraParameters::additional_calibration_information, camera_parameters, cameraHeightSlider, CameraParameters::distortion, distortionSlider, VarTypes::VarDoubleVal::getDouble(), CameraParameters::AdditionalCalibrationInformation::line_search_corridor_width, lineSearchCorridorWidthSlider, and CameraParameters::tz.
Referenced by is_clicked_full(), is_clicked_initial(), is_clicked_reset(), PluginCameraCalibration::process(), and resetDetectEdges().
 {
   cameraHeightSlider->setValue((int)camera_parameters.tz->getDouble());
   distortionSlider->setValue((int)(camera_parameters.distortion->getDouble()*100));
   lineSearchCorridorWidthSlider->setValue((int)(camera_parameters.additional_calibration_information->line_search_corridor_width->getDouble()));
 }
Field Documentation
CameraParameters& CameraCalibrationWidget::camera_parameters
Definition at line 41 of file cameracalibwidget.h.
Referenced by CameraCalibrationWidget(), cameraheight_slider_changed(), distortion_slider_changed(), is_clicked_full(), is_clicked_initial(), is_clicked_reset(), line_search_slider_changed(), and set_slider_from_vars().
QLabel* CameraCalibrationWidget::cameraHeightLabelRight protected
Definition at line 53 of file cameracalibwidget.h.
Referenced by CameraCalibrationWidget(), and cameraheight_slider_changed().
QSlider* CameraCalibrationWidget::cameraHeightSlider protected
Definition at line 52 of file cameracalibwidget.h.
Referenced by CameraCalibrationWidget(), and set_slider_from_vars().
bool CameraCalibrationWidget::detectEdges protected
Definition at line 56 of file cameracalibwidget.h.
Referenced by edges_is_clicked(), getDetectEdges(), and resetDetectEdges().
QLabel* CameraCalibrationWidget::distortionLabelRight protected
Definition at line 55 of file cameracalibwidget.h.
Referenced by CameraCalibrationWidget(), and distortion_slider_changed().
QSlider* CameraCalibrationWidget::distortionSlider protected
Definition at line 54 of file cameracalibwidget.h.
Referenced by CameraCalibrationWidget(), and set_slider_from_vars().
QLabel* CameraCalibrationWidget::lineSearchCorridorWidthLabelRight protected
Definition at line 51 of file cameracalibwidget.h.
Referenced by CameraCalibrationWidget(), and line_search_slider_changed().
QSlider* CameraCalibrationWidget::lineSearchCorridorWidthSlider protected
Definition at line 50 of file cameracalibwidget.h.
Referenced by CameraCalibrationWidget(), and set_slider_from_vars().
The documentation for this class was generated from the following files:
ssl-vision/src/app/gui/cameracalibwidget.h
ssl-vision/src/app/gui/cameracalibwidget.cpp