Documentation: CaptureV4L Class Reference
CaptureV4L Class Reference
A v4l-based USB/Video For Linux Capture Class.
#include <capturev4l.h>
Public Slots
void changed (VarType *group)
Public Member Functions
CaptureV4L (VarList *_settings=0, int default_camera_id=0, QObject *parent=0)
void mvc_connect (VarList *group)
~CaptureV4L ()
virtual bool startCapture ()
Initialize the interface and start capture.
virtual bool stopCapture ()
Stop Capture.
virtual bool isCapturing ()
v4lfeature_t getV4LfeatureEnum (VarList *val, bool &valid)
This function converts a local variable pointer to enum.
v4lfeature_t getV4LfeatureEnum (VarList *val)
VarList * getVariablePointer (v4lfeature_t val)
This function converts a V4L feature into a local variable Pointer.
virtual RawImage getFrame ()
virtual void releaseFrame ()
virtual bool resetBus ()
void cleanup ()
void readParameterValues (VarList *item)
void writeParameterValues (VarList *item)
void readParameterProperty (VarList *item)
void readAllParameterProperties ()
bool copyFrame (const RawImage &src, RawImage &target)
virtual void readAllParameterValues ()
void writeAllParameterValues ()
virtual bool copyAndConvertFrame (const RawImage &src, RawImage &target)
virtual string getCaptureMethodName () const
Public Member Functions inherited from CaptureInterface
CaptureInterface (VarList *_settings=0)
virtual ~CaptureInterface ()
Protected Member Functions
bool convertFrame (const RawImage &src, RawImage &target, ColorFormat output_fmt, int y16bits=16)
Protected Attributes
QMutex mutex
bool is_capturing
VarStringEnum * v_colorout
VarList * P_BRIGHTNESS
VarList * P_CONTRAST
VarList * P_EXPOSURE
VarList * P_SHARPNESS
VarList * P_WHITE_BALANCE
VarList * P_HUE
VarList * P_SATURATION
VarList * P_GAMMA
VarList * P_GAIN
VarList * P_TEMPERATURE
VarList * P_FRAME_RATE
VarInt * v_cam_bus
VarInt * v_fps
VarInt * v_width
VarInt * v_height
VarInt * v_left
VarInt * v_top
VarStringEnum * v_colormode
VarStringEnum * v_format
VarInt * v_buffer_size
int cam_id
int width
int height
int top
int left
ColorFormat capture_format
int ring_buffer_size
int cam_list [4]
int cam_count
RawImage rawFrame
GlobalV4Linstance * camera_instance
VarList * dcam_parameters
VarList * capture_settings
VarList * conversion_settings
Additional Inherited Members
Data Fields inherited from CaptureInterface
VarList * settings
Detailed Description
A v4l-based USB/Video For Linux Capture Class.
Author
Eric Zavesky, (C) 2016
This class mirrors popular v4l implementations giving the most compatible options and based on the DC1394 base classes by Stefan.
Overall, it not only provides capture-abilities, but also full on-the-fly configuration abilities through the VarTypes system.
If you find your camera not working correctly, or discover a bug, please inform the author, but also consider contributing yourself, so that we can cover as many options as possible.
Definition at line 219 of file capturev4l.h.
Constructor & Destructor Documentation
CaptureV4L::CaptureV4L (VarList * _settings = 0, int default_camera_id = 0, QObject * parent = 0)
Definition at line 560 of file capturev4l.cpp.
References VarTypes::VarList::addChild(), VarTypes::VarType::addFlags(), VarTypes::VarStringEnum::addItem(), cam_count, cam_id, cam_list, camera_instance, capture_settings, COLOR_RGB8, Colors::colorFormatToString(), conversion_settings, dcam_parameters, GlobalV4LinstanceManager::enumerateInstances(), VarTypes::VarList::getChildren(), velocity.pid_::i, is_capturing, MAX_CAM_SCAN, mutex, mvc_connect(), mzero(), GlobalV4LinstanceManager::obtainInstance(), P_BRIGHTNESS, P_CONTRAST, P_EXPOSURE, P_FRAME_RATE, P_GAIN, P_GAMMA, P_HUE, P_SATURATION, P_SHARPNESS, P_TEMPERATURE, P_WHITE_BALANCE, CaptureInterface::settings, v, V4L_STREAMBUFS, v_buffer_size, v_cam_bus, v_colormode, v_colorout, v_fps, v_height, v_left, v_top, v_width, VarTypes::VARTYPE_FLAG_HIDDEN, VarTypes::VARTYPE_FLAG_HIDE_CHILDREN, VarTypes::VARTYPE_FLAG_READONLY, and VarTypes::VARTYPE_ID_LIST.
                                                                                   : QObject(parent), CaptureInterface(_settings)
 #else
 CaptureV4L::CaptureV4L(VarList * _settings,int default_camera_id) : CaptureInterface(_settings)
 #endif
 {
     mzero(cam_list, MAX_CAM_SCAN);
     cam_count = 0;
     cam_id=default_camera_id;
     is_capturing=false;
 #ifndef VDATA_NO_QT
     mutex.lock();
 #endif
     cam_count = GlobalV4LinstanceManager::enumerateInstances(cam_list, MAX_CAM_SCAN);
     if (cam_count==0) {
         fprintf(stderr,"CaptureV4L Error: can't find cameras");
     }
     if (cam_id > cam_list[cam_count-1]) {
         static bool bMaxWarningShown = false;
         if (!bMaxWarningShown) {
             fprintf(stderr,"CaptureV4L Error: no camera found with index %d. Max index is: %d\n",cam_id,cam_list[cam_count-1]);
             bMaxWarningShown = true;
         }
     }
     else {
         camera_instance = GlobalV4LinstanceManager::obtainInstance(cam_id);
         if (!camera_instance) {
             fprintf(stderr,"CaptureV4L: unable to obtain instance of camera id %d!\n", cam_id);
         }
     }
     settings->addChild(conversion_settings = new VarList("Conversion Settings"));
     settings->addChild(capture_settings = new VarList("Capture Settings"));
     settings->addChild(dcam_parameters  = new VarList("Camera Parameters"));
     //=======================CONVERSION SETTINGS=======================
     conversion_settings->addChild(v_colorout=new VarStringEnum("convert to mode",Colors::colorFormatToString(COLOR_RGB8)));
     v_colorout->addItem(Colors::colorFormatToString(COLOR_RGB8));
 //    v_colorout->addItem(Colors::colorFormatToString(COLOR_RGB16));
 //    v_colorout->addItem(Colors::colorFormatToString(COLOR_RAW8));
 //    v_colorout->addItem(Colors::colorFormatToString(COLOR_RAW16));
 //    v_colorout->addItem(Colors::colorFormatToString(COLOR_MONO8));
 //    v_colorout->addItem(Colors::colorFormatToString(COLOR_MONO16));
 //    v_colorout->addItem(Colors::colorFormatToString(COLOR_YUV411));
 //    v_colorout->addItem(Colors::colorFormatToString(COLOR_YUV422_UYVY));
 //    v_colorout->addItem(Colors::colorFormatToString(COLOR_YUV422_YUYV));
 //    v_colorout->addItem(Colors::colorFormatToString(COLOR_YUV444));
     dcam_parameters->addFlags( VARTYPE_FLAG_HIDE_CHILDREN );
     //=======================CAPTURE SETTINGS==========================
     capture_settings->addChild(v_cam_bus          = new VarInt("cam idx",default_camera_id));
     capture_settings->addChild(v_fps              = new VarInt("framerate",30));
     capture_settings->addChild(v_width            = new VarInt("width",640));
     capture_settings->addChild(v_height           = new VarInt("height",480));
     capture_settings->addChild(v_left            = new VarInt("left",0));
     capture_settings->addChild(v_top           = new VarInt("top",0));
     capture_settings->addChild(v_colormode        = new VarStringEnum("capture mode",Colors::colorFormatToString(COLOR_RGB8)));
     v_colormode->addItem(Colors::colorFormatToString(COLOR_RGB8));
 //    v_colormode->addItem(Colors::colorFormatToString(COLOR_RGB16));
 //    v_colormode->addItem(Colors::colorFormatToString(COLOR_RAW8));
 //    v_colormode->addItem(Colors::colorFormatToString(COLOR_RAW16));
 //    v_colormode->addItem(Colors::colorFormatToString(COLOR_MONO8));
 //    v_colormode->addItem(Colors::colorFormatToString(COLOR_MONO16));
 //    v_colormode->addItem(Colors::colorFormatToString(COLOR_YUV411));
 //    v_colormode->addItem(Colors::colorFormatToString(COLOR_YUV422_UYVY));
 //    v_colormode->addItem(Colors::colorFormatToString(COLOR_YUV422_YUYV));
 //    v_colormode->addItem(Colors::colorFormatToString(COLOR_YUV444));
 //    capture_settings->addChild(v_format           = new VarStringEnum("capture format",captureModeToString(CAPTURE_MODE_MIN)));
 //    for (int i = CAPTURE_MODE_MIN; i <= CAPTURE_MODE_MAX; i++) {
 //        v_format->addItem(captureModeToString((CaptureMode)i));
 //    }
     capture_settings->addChild(v_buffer_size      = new VarInt("ringbuffer size",V4L_STREAMBUFS));
     v_buffer_size->addFlags(VARTYPE_FLAG_READONLY);
     // we could do a better job of enumerating formats here...
     // http://www.linuxtv.org/downloads/v4l-dvb-apis/vidioc-enum-fmt.html
     // http://www.linuxtv.org/downloads/v4l-dvb-apis/vidioc-enum-framesizes.html#v4l2-frmsizeenum
     // v4l2_frmsizeenum
 //    printf("sensor supported frame size:\n");
 //    fsize.index = 0;
 //    while (ioctl(fd_v4l, VIDIOC_ENUM_FRAMESIZES, &fsize) >= 0) {
 //      printf(" %dx%d\n", fsize.discrete.width,
 //                 fsize.discrete.height);
 //      fsize.index++;
 //    }
     //=======================DCAM PARAMETERS===========================
     // http://linuxtv.org/downloads/legacy/video4linux/API/V4L2_API/spec/ch01s08.html
     dcam_parameters->addChild(P_BRIGHTNESS = new VarList("brightness"));
     P_BRIGHTNESS->addChild(new VarBool("enabled"));
     P_BRIGHTNESS->addChild(new VarBool("default"));
     P_BRIGHTNESS->addChild(new VarInt("value"));
 #ifndef VDATA_NO_QT
     mvc_connect(P_BRIGHTNESS);
 #endif
     dcam_parameters->addChild(P_SHARPNESS = new VarList("sharpness"));
     P_SHARPNESS->addChild(new VarBool("enabled"));
     P_SHARPNESS->addChild(new VarInt("defulat"));
     P_SHARPNESS->addChild(new VarInt("value"));
 #ifndef VDATA_NO_QT
     mvc_connect(P_SHARPNESS);
 #endif
     dcam_parameters->addChild(P_WHITE_BALANCE = new VarList("white balance"));
     P_WHITE_BALANCE->addChild(new VarBool("enabled"));
     P_WHITE_BALANCE->addChild(new VarBool("auto"));
 #ifndef VDATA_NO_QT
     mvc_connect(P_WHITE_BALANCE);
 #endif
     dcam_parameters->addChild(P_HUE = new VarList("hue"));
     P_HUE->addChild(new VarBool("enabled"));
     P_HUE->addChild(new VarBool("default"));
     P_HUE->addChild(new VarInt("value"));
 #ifndef VDATA_NO_QT
     mvc_connect(P_HUE);
 #endif
     dcam_parameters->addChild(P_SATURATION = new VarList("saturation"));
     P_SATURATION->addChild(new VarBool("enabled"));
     P_SATURATION->addChild(new VarBool("default"));
     P_SATURATION->addChild(new VarInt("value"));
 #ifndef VDATA_NO_QT
     mvc_connect(P_SATURATION);
 #endif
     dcam_parameters->addChild(P_GAMMA = new VarList("gamma"));
     P_GAMMA->addChild(new VarBool("enabled"));
     P_GAMMA->addChild(new VarBool("default"));
     P_GAMMA->addChild(new VarInt("value"));
 #ifndef VDATA_NO_QT
     mvc_connect(P_GAMMA);
 #endif
     dcam_parameters->addChild(P_EXPOSURE = new VarList("shutter/exposure"));
     P_EXPOSURE->addChild(new VarBool("enabled"));
     P_EXPOSURE->addChild(new VarBool("default"));
     P_EXPOSURE->addChild(new VarInt("value"));
 #ifndef VDATA_NO_QT
     mvc_connect(P_EXPOSURE);
 #endif
     dcam_parameters->addChild(P_CONTRAST = new VarList("contrast"));
     P_CONTRAST->addChild(new VarBool("enabled"));
     P_CONTRAST->addChild(new VarBool("default"));
     P_CONTRAST->addChild(new VarInt("value"));
 #ifndef VDATA_NO_QT
     mvc_connect(P_CONTRAST);
 #endif
     dcam_parameters->addChild(P_TEMPERATURE = new VarList("temperature"));
     P_TEMPERATURE->addChild(new VarBool("enabled"));
     P_TEMPERATURE->addChild(new VarBool("default"));
     P_TEMPERATURE->addChild(new VarInt("value"));
 #ifndef VDATA_NO_QT
     mvc_connect(P_TEMPERATURE);
 #endif
     dcam_parameters->addChild(P_GAIN = new VarList("gain"));
     P_GAIN->addChild(new VarBool("enabled"));
     P_GAIN->addChild(new VarBool("default"));
     P_GAIN->addChild(new VarInt("value"));
 #ifndef VDATA_NO_QT
     mvc_connect(P_GAIN);
 #endif
     dcam_parameters->addChild(P_FRAME_RATE = new VarList("frame rate"));
     P_FRAME_RATE->addChild(new VarBool("enabled"));
     P_FRAME_RATE->addChild(new VarBool("auto"));
     P_FRAME_RATE->addChild(new VarInt("value"));
 #ifndef VDATA_NO_QT
     mvc_connect(P_FRAME_RATE);
 #endif
     vector<VarType *> v=dcam_parameters->getChildren();
     for (unsigned int i=0;i<v.size();i++) {
         if (v[i]->getType()==VARTYPE_ID_LIST) {
             VarBool * temp;
             ((VarList *)v[i])->addChild(temp = new VarBool("was_read",false));
             temp->addFlags(VARTYPE_FLAG_HIDDEN);
         }
     }
 #ifndef VDATA_NO_QT
     mvc_connect(P_FRAME_RATE);
 #endif
 #ifndef VDATA_NO_QT
     mutex.unlock();
 #endif
 }
CaptureV4L::~CaptureV4L ()
Definition at line 981 of file capturev4l.cpp.
References camera_instance, RawImage::clear(), rawFrame, and GlobalV4LinstanceManager::removeInstance().
 {
     GlobalV4LinstanceManager::removeInstance(camera_instance);
     rawFrame.clear();           //release memory from local image
 }
Member Function Documentation
void CaptureV4L::changed (VarType * group) slot
Definition at line 767 of file capturev4l.cpp.
References VarTypes::VarVal::getType(), readParameterValues(), VarTypes::VARTYPE_ID_LIST, and writeParameterValues().
Referenced by mvc_connect().
{
     if (group->getType()==VARTYPE_ID_LIST) {
         writeParameterValues( (VarList *)group );
         readParameterValues( (VarList *)group );
     }
 }
void CaptureV4L::cleanup ()
Definition at line 1025 of file capturev4l.cpp.
References camera_instance, is_capturing, mutex, and GlobalV4Linstance::stopStreaming().
Referenced by startCapture(), and stopCapture().
 {
 #ifndef VDATA_NO_QT
     mutex.lock();
 #endif
     //TODO: cleanup/free any memory buffers.
     if (camera_instance && is_capturing)
         camera_instance->stopStreaming();
     is_capturing=false;
 #ifndef VDATA_NO_QT
     mutex.unlock();
 #endif
 }
bool CaptureV4L::convertFrame (const RawImage & src, RawImage & target, ColorFormat output_fmt, int y16bits = 16) protected
This function is used internally only The user should call copyAndConvertFrame with parameters setup through the VarTypes settings.
Definition at line 1406 of file capturev4l.cpp.
References RawImage::allocate(), COLOR_RGB8, COLOR_YUV422_UYVY, COLOR_YUV422_YUYV, Colors::colorFormatToString(), RawImage::ensure_allocation(), RawImage::getColorFormat(), RawImage::getData(), RawImage::getHeight(), RawImage::getNumBytes(), RawImage::getTime(), RawImage::getWidth(), height, mutex, Conversions::rgb2uyvy(), Conversions::rgb2yuyv(), RawImage::setTime(), and width.
Referenced by copyAndConvertFrame(), and copyFrame().
 {
 #ifndef VDATA_NO_QT
     mutex.lock();
 #endif
     ColorFormat src_fmt=src.getColorFormat();
     if (target.getData()==0) {
         //allocate target, if it does not exist yet
         target.allocate(output_fmt,src.getWidth(),src.getHeight());
     } else {
         target.ensure_allocation(output_fmt,src.getWidth(),src.getHeight());
         //target.setWidth(src.getWidth());
         //target.setHeight(src.getHeight());
         //target.setFormat(output_fmt);
     }
     target.setTime(src.getTime());
     if (output_fmt==src_fmt) {
         //just do a memcpy
         memcpy(target.getData(),src.getData(),src.getNumBytes());
     } else {
         //do some more fancy conversion
         /*if ((src_fmt==COLOR_MONO8 || src_fmt==COLOR_RAW8) && output_fmt==COLOR_RGB8) {
             Conversions::y2rgb (src.getData(), target.getData(), width, height);
         } else if ((src_fmt==COLOR_MONO16 || src_fmt==COLOR_RAW16)) {
             if (output_fmt==COLOR_RGB8) {
                 Conversions::y162rgb (src.getData(), target.getData(), width, height, y16bits);
             }
             else {
                 fprintf(stderr,"Cannot copy and convert frame...unknown conversion selected from: %s to %s\n",
                         Colors::colorFormatToString(src_fmt).c_str(),
                         Colors::colorFormatToString(output_fmt).c_str());
 #ifndef VDATA_NO_QT
                 mutex.unlock();
 #endif
                 return false;
             }
         } else */ if (src_fmt==COLOR_RGB8 && output_fmt==COLOR_YUV422_UYVY) {
             Conversions::rgb2uyvy (src.getData(), target.getData(), width, height);
         } else if (src_fmt==COLOR_RGB8 && output_fmt==COLOR_YUV422_YUYV) {
             Conversions::rgb2yuyv (src.getData(), target.getData(), width, height);
         } else {
             fprintf(stderr,"Cannot copy and convert frame...unknown conversion selected from: %s to %s\n",
                     Colors::colorFormatToString(src_fmt).c_str(),
                     Colors::colorFormatToString(output_fmt).c_str());
     #ifndef VDATA_NO_QT
             mutex.unlock();
     #endif
             return false;
         }
     }
 #ifndef VDATA_NO_QT
     mutex.unlock();
 #endif
     return true;
 }
bool CaptureV4L::copyAndConvertFrame (const RawImage & src, RawImage & target) virtual
Reimplemented from CaptureInterface.
Definition at line 1400 of file capturev4l.cpp.
References convertFrame(), VarTypes::VarStringEnum::getSelection(), Colors::stringToColorFormat(), and v_colorout.
 {
     return convertFrame(src, target, Colors::stringToColorFormat(v_colorout->getSelection().c_str()));
 }
bool CaptureV4L::copyFrame (const RawImage & src, RawImage & target)
will perform a pure memcpy of an image, independent of vartypes conversion settings
Definition at line 1395 of file capturev4l.cpp.
References convertFrame(), and RawImage::getColorFormat().
 {
     return convertFrame(src,target,src.getColorFormat());
 }
string CaptureV4L::getCaptureMethodName () const virtual
Implements CaptureInterface.
Definition at line 1506 of file capturev4l.cpp.
{
     return "V4L";
 }
RawImage CaptureV4L::getFrame () virtual
this gives a raw-image with a pointer directly to the video-buffer Note that this pointer is only guaranteed to point to a valid memory location until releaseFrame() is called.
Implements CaptureInterface.
Definition at line 1462 of file capturev4l.cpp.
References cam_id, camera_instance, capture_format, GlobalV4Linstance::captureFrame(), RawImage::ensure_allocation(), RawImage::getData(), height, is_capturing, mutex, rawFrame, width, and GlobalV4Linstance::writeRgbPPM().
 {
 #ifndef VDATA_NO_QT
     mutex.lock();
 #endif
     // capture a frame and write it
     rawFrame.ensure_allocation(capture_format, width, height);
     if (!camera_instance || !is_capturing || !camera_instance->captureFrame(&rawFrame)) {
         fprintf (stderr, "CaptureV4L Warning: Frame not ready, camera %d\n", cam_id);
 #ifndef VDATA_NO_QT
         mutex.unlock();
 #endif
         RawImage badImage;
         return badImage;
     }
 #ifndef NDEBUG
     //strictly for debugging
     const char *szOutput = NULL;
     if (szOutput) {
         GlobalV4Linstance::writeRgbPPM(reinterpret_cast<GlobalV4Linstance::rgb*>(rawFrame.getData()),
                                        width, height, szOutput);
     }
 #endif
     /*printf("B: %d w: %d h: %d bytes: %d pad: %d pos: %d %d depth: %d bpp %d coding: %d  behind %d id %d\n",frame->data_in_padding ? 1 : 0, frame->size[0],frame->size[1],frame->image_bytes,frame->padding_bytes, frame->position[0],frame->position[1],frame->data_depth,frame->packets_per_frame,frame->color_coding,frame->frames_behind,frame->id);*/
 #ifndef VDATA_NO_QT
     mutex.unlock();
 #endif
     return rawFrame;
 }
v4lfeature_t CaptureV4L::getV4LfeatureEnum (VarList * val, bool & valid)
This function converts a local variable pointer to enum.
This function converts a local dcam_parameters-manager variable ID to a v4l feature enum
Definition at line 1044 of file capturev4l.cpp.
References P_BRIGHTNESS, P_CONTRAST, P_EXPOSURE, P_FRAME_RATE, P_GAIN, P_GAMMA, P_HUE, P_SATURATION, P_SHARPNESS, P_TEMPERATURE, P_WHITE_BALANCE, and GlobalV4Linstance::V4L2_FEATURE_FRAME_RATE.
Referenced by readParameterProperty(), readParameterValues(), and writeParameterValues().
 {
     v4lfeature_t res=V4L2_CID_BASE;
     if (val== P_BRIGHTNESS) {
         res= V4L2_CID_BRIGHTNESS;
     } else if (val== P_EXPOSURE) {
         res= V4L2_CID_EXPOSURE;
     } else if (val== P_CONTRAST) {
         res= V4L2_CID_CONTRAST;
     } else if (val== P_SHARPNESS) {
         res= V4L2_CID_SHARPNESS;
     } else if (val== P_WHITE_BALANCE) {
         res= V4L2_CID_AUTO_WHITE_BALANCE;
     } else if (val== P_HUE) {
         res= V4L2_CID_HUE;
     } else if (val== P_SATURATION) {
         res= V4L2_CID_SATURATION;
     } else if (val== P_GAMMA) {
         res= V4L2_CID_GAMMA;
     } else if (val== P_GAIN) {
         res= V4L2_CID_GAIN;
     } else if (val== P_TEMPERATURE) {
         res= V4L2_CID_WHITE_BALANCE_TEMPERATURE;
     } else if (val== P_FRAME_RATE) {
         res= GlobalV4Linstance::V4L2_FEATURE_FRAME_RATE;
     } else {
         valid=false;
     }
     return res;
 }
v4lfeature_t CaptureV4L::getV4LfeatureEnum (VarList * val) inline
Definition at line 300 of file capturev4l.h.
References GlobalV4Linstance::releaseFrame(), and role._GoToPoint::target.
{
         bool b=true;
         return getV4LfeatureEnum(val,b);
     }
VarList * CaptureV4L::getVariablePointer (v4lfeature_t val)
This function converts a V4L feature into a local variable Pointer.
This function converts a v4l feature into a variable ID.
Definition at line 1077 of file capturev4l.cpp.
References P_BRIGHTNESS, P_CONTRAST, P_EXPOSURE, P_FRAME_RATE, P_GAIN, P_GAMMA, P_HUE, P_SATURATION, P_SHARPNESS, P_TEMPERATURE, P_WHITE_BALANCE, and GlobalV4Linstance::V4L2_FEATURE_FRAME_RATE.
 {
     VarList * res=0;
     switch (val) {
         case V4L2_CID_BRIGHTNESS: res=P_BRIGHTNESS; break;
         case V4L2_CID_CONTRAST: res=P_CONTRAST; break;
         case V4L2_CID_SATURATION: res=P_SATURATION; break;
         case V4L2_CID_SHARPNESS: res=P_SHARPNESS; break;
         case V4L2_CID_HUE: res=P_HUE; break;
         case V4L2_CID_AUTO_WHITE_BALANCE: res=P_WHITE_BALANCE; break;  //bool
         case V4L2_CID_GAMMA: res=P_GAMMA; break;
         case V4L2_CID_EXPOSURE: res=P_EXPOSURE; break;
         case V4L2_CID_GAIN: res=P_GAIN; break;
         case V4L2_CID_WHITE_BALANCE_TEMPERATURE: res=P_TEMPERATURE; break;
         case GlobalV4Linstance::V4L2_FEATURE_FRAME_RATE: res=P_FRAME_RATE; break;
         default: res=0; break;
     }
     return res;
 }
virtual bool CaptureV4L::isCapturing () inline virtual
Implements CaptureInterface.
Definition at line 296 of file capturev4l.h.
Referenced by stopCapture().
 { return is_capturing; };
void CaptureV4L::mvc_connect (VarList * group)
Definition at line 759 of file capturev4l.cpp.
References changed(), VarTypes::VarList::getChildren(), velocity.pid_::i, and v.
Referenced by CaptureV4L().
{
     vector<VarType *> v=group->getChildren();
     for (unsigned int i=0;i<v.size();i++) {
         connect(v[i],SIGNAL(wasEdited(VarType *)),group,SLOT(mvcEditCompleted()));
     }
     connect(group,SIGNAL(wasEdited(VarType *)),this,SLOT(changed(VarType *)));
 }
void CaptureV4L::readAllParameterProperties ()
Definition at line 785 of file capturev4l.cpp.
References dcam_parameters, VarTypes::VarList::getChildren(), velocity.pid_::i, readParameterProperty(), v, and VarTypes::VARTYPE_ID_LIST.
Referenced by startCapture().
 {
     vector<VarType *> v=dcam_parameters->getChildren();
     for (unsigned int i=0;i<v.size();i++) {
         if (v[i]->getType()==VARTYPE_ID_LIST) {
             readParameterProperty((VarList *)v[i]);
         }
     }
 }
void CaptureV4L::readAllParameterValues () virtual
Reimplemented from CaptureInterface.
Definition at line 776 of file capturev4l.cpp.
References dcam_parameters, VarTypes::VarList::getChildren(), velocity.pid_::i, readParameterValues(), v, and VarTypes::VARTYPE_ID_LIST.
Referenced by startCapture(), and stopCapture().
{
     vector<VarType *> v=dcam_parameters->getChildren();
     for (unsigned int i=0;i<v.size();i++) {
         if (v[i]->getType()==VARTYPE_ID_LIST) {
             readParameterValues((VarList *)v[i]);
         }
     }
 }
void CaptureV4L::readParameterProperty (VarList * item)
Definition at line 917 of file capturev4l.cpp.
References VarTypes::VarType::addFlags(), camera_instance, GlobalV4Linstance::checkControl(), role.sGoalie::debug(), VarTypes::VarList::getChildren(), GlobalV4Linstance::getControl(), VarTypes::VarType::getName(), getV4LfeatureEnum(), velocity.pid_::i, mutex, VarTypes::VarType::removeFlags(), VarTypes::VarBoolVal::setBool(), VarTypes::VarInt::setDefault(), VarTypes::VarInt::setMax(), VarTypes::VarInt::setMin(), GlobalV4Linstance::V4L2_FEATURE_PRIVATE, VarTypes::VARTYPE_FLAG_HIDE_CHILDREN, VarTypes::VARTYPE_FLAG_READONLY, VarTypes::VARTYPE_ID_BOOL, and VarTypes::VARTYPE_ID_INT.
Referenced by readAllParameterProperties().
{
     if (!camera_instance) return;
 #ifndef VDATA_NO_QT
     mutex.lock();
 #endif
     bool debug=false;
     bool valid=true;
     v4lfeature_t feature=getV4LfeatureEnum(item,valid);
     if (valid==false) {
         fprintf(stderr,"ERROR: INVALID PROPERTY ENCOUNTERED DURING READOUT: %s\n", item->getName().c_str());
 #ifndef VDATA_NO_QT
         mutex.unlock();
 #endif
         return;
     }
     VarInt * vint=0;
     VarBool * venabled=0;
     vector<VarType *> children=item->getChildren();
     for (unsigned int i=0;i<children.size();i++) {
         if (children[i]->getType()==VARTYPE_ID_BOOL && children[i]->getName()=="enabled") venabled=(VarBool *)children[i];
         if (children[i]->getType()==VARTYPE_ID_INT && children[i]->getName()=="value") vint=(VarInt *)children[i];
     }
     long lDefault = 0;
     if (feature > GlobalV4Linstance::V4L2_FEATURE_PRIVATE) {       //custom/private features
         printf("UNIMPLEMENTED FEATURE (readParameterProperty): %s\n",item->getName().c_str());
     }
     else {
         if (!camera_instance->getControl(feature, lDefault)) {
             if (debug) fprintf(stderr,"V4L PROP FEATURE IS *NOT* PRESENT: %s\n", item->getName().c_str());
             //feature doesn't exist
             item->addFlags(VARTYPE_FLAG_READONLY|VARTYPE_FLAG_HIDE_CHILDREN);
         }
         else {
             if (debug) fprintf(stderr,"V4L PROP FEATURE IS PRESENT: %s\n", item->getName().c_str());
             item->removeFlags(VARTYPE_FLAG_READONLY|VARTYPE_FLAG_HIDE_CHILDREN);
             //check for switchability:
             bool bReadOnly, bEnabled;
             long lMin, lMax;
             if (camera_instance->checkControl(feature, &bEnabled, &bReadOnly, &lDefault, &lMin, &lMax)) {
                 venabled->setBool(bEnabled);
                 if (bReadOnly)
                     venabled->removeFlags( VARTYPE_FLAG_READONLY);
                 else
                     venabled->addFlags( VARTYPE_FLAG_READONLY);
                 if (vint!=0) {
                     vint->setMin(lMin);
                     vint->setMax(lMax);
                     vint->setDefault(lDefault);
                 }
             }
             else {
                 venabled->setBool(false);
                 venabled->addFlags( VARTYPE_FLAG_READONLY);
             }
         }
     }
 #ifndef VDATA_NO_QT
     mutex.unlock();
 #endif
 }
void CaptureV4L::readParameterValues (VarList * item)
Definition at line 804 of file capturev4l.cpp.
References VarTypes::VarType::addFlags(), camera_instance, GlobalV4Linstance::checkControl(), VarTypes::VarBoolVal::getBool(), VarTypes::VarList::getChildren(), GlobalV4Linstance::getControl(), VarTypes::VarType::getName(), getV4LfeatureEnum(), velocity.pid_::i, mutex, VarTypes::VarType::removeFlags(), VarTypes::VarBoolVal::setBool(), VarTypes::VarInt::setInt(), GlobalV4Linstance::V4L2_FEATURE_PRIVATE, VarTypes::VARTYPE_FLAG_READONLY, VarTypes::VARTYPE_ID_BOOL, and VarTypes::VARTYPE_ID_INT.
Referenced by changed(), and readAllParameterValues().
{
     if (!camera_instance) return;
 #ifndef VDATA_NO_QT
     mutex.lock();
 #endif
     bool valid=true;
     v4lfeature_t feature=getV4LfeatureEnum(item,valid);
     if (valid==false) {
         printf("INVALID FEATURE: %s\n",item->getName().c_str());
 #ifndef VDATA_NO_QT
         mutex.unlock();
 #endif
         return;
     }
     VarInt * vint=0;
     VarBool * venabled=0;
     VarBool * vwasread=0;
     vector<VarType *> children=item->getChildren();
     for (unsigned int i=0;i<children.size();i++) {
         if (children[i]->getType()==VARTYPE_ID_BOOL && children[i]->getName()=="was_read") vwasread=(VarBool *)children[i];
         if (children[i]->getType()==VARTYPE_ID_BOOL && children[i]->getName()=="enabled") venabled=(VarBool *)children[i];
         if (children[i]->getType()==VARTYPE_ID_INT && children[i]->getName()=="value") vint=(VarInt *)children[i];
     }
     long lValue;
     if (vwasread!=0 && vwasread->getBool()==true) {             //only proceed if no failure in past
         if (feature > GlobalV4Linstance::V4L2_FEATURE_PRIVATE) {       //custom/private features
             printf("UNIMPLEMENTED FEATURE (readParameterValues): %s\n",item->getName().c_str());
         }
         else {
             if (!camera_instance->getControl(feature,lValue)) {
                 //feature doesn't exist
                 printf("NON-READ FEATURE (readParameterValues): %s\n",item->getName().c_str());
                 if (vwasread!=0) vwasread->setBool(false);
             } else {
                 //check for switchability:
                 if (vwasread!=0) vwasread->setBool(true);
                 if (camera_instance->checkControl(feature)) {
                     venabled->setBool(true);
                 } else {
                     venabled->setBool(false);
                 }
                 vint->setInt(lValue);
             }
             //update render flags:
             if (vint) {
                 if (venabled->getBool() ) {
                     vint->removeFlags( VARTYPE_FLAG_READONLY );
                 } else {
                     vint->addFlags( VARTYPE_FLAG_READONLY );
                 }
             }
         }
     }
 #ifndef VDATA_NO_QT
     mutex.unlock();
 #endif
 }
void CaptureV4L::releaseFrame () virtual
Implements CaptureInterface.
Definition at line 1495 of file capturev4l.cpp.
References mutex.
{
 #ifndef VDATA_NO_QT
     mutex.lock();
 #endif
     //frame management done at low-level now...
 #ifndef VDATA_NO_QT
     mutex.unlock();
 #endif
 }
bool CaptureV4L::resetBus () virtual
Reimplemented from CaptureInterface.
Definition at line 987 of file capturev4l.cpp.
References cam_count, cam_list, GlobalV4LinstanceManager::enumerateInstances(), MAX_CAM_SCAN, and mutex.
{
 #ifndef VDATA_NO_QT
     mutex.lock();
 #endif
     cam_count = GlobalV4LinstanceManager::enumerateInstances(cam_list, MAX_CAM_SCAN);
     if (cam_count==0) {
         fprintf(stderr,"CaptureV4L Error: can't find cameras");
 #ifndef VDATA_NO_QT
         mutex.unlock();
 #endif
         return false;
     }
 #ifndef VDATA_NO_QT
     mutex.unlock();
 #endif
     return true;
 }
bool CaptureV4L::startCapture () virtual
Initialize the interface and start capture.
Implements CaptureInterface.
Definition at line 1097 of file capturev4l.cpp.
References cam_count, cam_id, cam_list, camera_instance, capture_format, capture_settings, GlobalV4Linstance::captureWarm(), cleanup(), dcam_parameters, VarTypes::VarList::getChildren(), VarTypes::VarInt::getInt(), VarTypes::VarStringEnum::getString(), height, velocity.pid_::i, is_capturing, left, mutex, GlobalV4LinstanceManager::obtainInstance(), readAllParameterProperties(), readAllParameterValues(), VarTypes::VarType::removeFlags(), GlobalV4LinstanceManager::removeInstance(), ring_buffer_size, GlobalV4Linstance::startStreaming(), GlobalV4Linstance::stopStreaming(), Colors::stringToColorFormat(), top, v_buffer_size, v_cam_bus, v_colormode, v_fps, v_height, v_left, v_top, v_width, VarTypes::VARTYPE_FLAG_HIDE_CHILDREN, VarTypes::VARTYPE_FLAG_READONLY, width, and writeAllParameterValues().
 {
     if (!v_cam_bus) return false;
 #ifndef VDATA_NO_QT
     mutex.lock();
 #endif
     //disable any previous activity on that camera:
     if (is_capturing)
         camera_instance->stopStreaming();
     //dynamically fetch the camera ID and reconnect now
     int new_cam_id = v_cam_bus->getInt();
     if (cam_id != new_cam_id) {
         cam_id = new_cam_id;
         GlobalV4LinstanceManager::removeInstance(camera_instance);
         camera_instance = NULL;
         if (cam_id > cam_list[cam_count-1]) {
             static bool bMaxWarningShown = false;
             if (!bMaxWarningShown) {
                 fprintf(stderr,"CaptureV4L Error: no camera found with index %d. Max index is: %d\n",cam_id,cam_list[cam_count-1]);
                 bMaxWarningShown = true;
             }
         }
         else {
             camera_instance = GlobalV4LinstanceManager::obtainInstance(cam_id);
         }
     }
     if (!camera_instance) {
         fprintf(stderr,"CaptureV4L: unable to obtain instance of camera id %d in startCapture!\n", cam_id);
 #ifndef VDATA_NO_QT
         mutex.unlock();
 #endif
         return false;
     }
     //grab current parameters:
     width=v_width->getInt();
     height=v_height->getInt();
     left=v_left->getInt();
     top=v_top->getInt();
     capture_format=Colors::stringToColorFormat(v_colormode->getString().c_str());
     int fps=v_fps->getInt();
     //CaptureMode mode=stringToCaptureMode(v_format->getString().c_str());
     ring_buffer_size=v_buffer_size->getInt();
     //Check configuration parameters:
     if (fps > 60 ) {
         fprintf(stderr,"CaptureV4L Error: The library does not support framerates higher than 60 fps (does your camera?).");
 #ifndef VDATA_NO_QT
         mutex.unlock();
 #endif
         return false;
     }
     /* ---- TODO: adapt to do checking based on available USB mode?
     dc1394_video_set_transmission(camera,DC1394_OFF);
     dc1394video_modes_t supported_modes;
     bool know_modes=false;
     if (dc1394_video_get_supported_modes(camera,&supported_modes) == DC1394_SUCCESS) {
         know_modes=true;
     } else {
         fprintf(stderr,"CaptureV4L Warning: unable to query supported camera modes!\n");
     }
     bool native_unavailable = false;
     if (mode==CAPTURE_MODE_AUTO || mode==CAPTURE_MODE_NATIVE) {
         if (width==160 && height==120) {
             if (capture_format==COLOR_YUV444) {
                 dcformat=DC1394_VIDEO_MODE_160x120_YUV444;
             } else {
                 native_unavailable = true;
             }
         } else if (width==320 && height==240) {
             if (capture_format==COLOR_YUV422_UYVY) {
                 dcformat=DC1394_VIDEO_MODE_320x240_YUV422;
             } else {
                 native_unavailable = true;
             }
         } else if (width==640 && height==480) {
             if (capture_format==COLOR_YUV411) {
                 dcformat=DC1394_VIDEO_MODE_640x480_YUV411;
             } else if (capture_format==COLOR_YUV422_UYVY) {
                 dcformat=DC1394_VIDEO_MODE_640x480_YUV422;
             } else if (capture_format==COLOR_RGB8) {
                 dcformat=DC1394_VIDEO_MODE_640x480_RGB8;
             } else if (capture_format==COLOR_MONO8) {
                 dcformat=DC1394_VIDEO_MODE_640x480_MONO8;
             } else if (capture_format==COLOR_MONO16) {
                 dcformat=DC1394_VIDEO_MODE_640x480_MONO16;
             } else {
                 native_unavailable = true;
             }
         } else if (width==800 && height==600) {
             if (capture_format==COLOR_YUV422_UYVY) {
                 dcformat=DC1394_VIDEO_MODE_800x600_YUV422;
             } else if (capture_format==COLOR_RGB8) {
                 dcformat=DC1394_VIDEO_MODE_800x600_RGB8;
             } else if (capture_format==COLOR_MONO8) {
                 dcformat=DC1394_VIDEO_MODE_800x600_MONO8;
             } else if (capture_format==COLOR_MONO16) {
                 dcformat=DC1394_VIDEO_MODE_800x600_MONO16;
             } else {
                 native_unavailable = true;
             }
         } else if (width==1024 && height==768) {
             if (capture_format==COLOR_YUV422_UYVY) {
                 dcformat=DC1394_VIDEO_MODE_1024x768_YUV422;
             } else if (capture_format==COLOR_RGB8) {
                 dcformat=DC1394_VIDEO_MODE_1024x768_RGB8;
             } else if (capture_format==COLOR_MONO8) {
                 dcformat=DC1394_VIDEO_MODE_1024x768_MONO8;
             } else if (capture_format==COLOR_MONO16) {
                 dcformat=DC1394_VIDEO_MODE_1024x768_MONO16;
             } else {
                 native_unavailable = true;
             }
         } else if (width==1280 && height==960) {
             if (capture_format==COLOR_YUV422_UYVY) {
                 dcformat=DC1394_VIDEO_MODE_1280x960_YUV422;
             } else if (capture_format==COLOR_RGB8) {
                 dcformat=DC1394_VIDEO_MODE_1280x960_RGB8;
             } else if (capture_format==COLOR_MONO8) {
                 dcformat=DC1394_VIDEO_MODE_1280x960_MONO8;
             } else if (capture_format==COLOR_MONO16) {
                 dcformat=DC1394_VIDEO_MODE_1280x960_MONO16;
             } else {
                 native_unavailable = true;
             }
         } else if (width==1600 && height==1200) {
             if (capture_format==COLOR_YUV422_UYVY) {
                 dcformat=DC1394_VIDEO_MODE_1600x1200_YUV422;
             } else if (capture_format==COLOR_RGB8) {
                 dcformat=DC1394_VIDEO_MODE_1600x1200_RGB8;
             } else if (capture_format==COLOR_MONO8) {
                 dcformat=DC1394_VIDEO_MODE_1600x1200_MONO8;
             } else if (capture_format==COLOR_MONO16) {
                 dcformat=DC1394_VIDEO_MODE_1600x1200_MONO16;
             } else {
                 native_unavailable = true;
             }
         } else {
             native_unavailable = true;
         }
         if (native_unavailable==false && know_modes) {
             bool found_mode=false;
             for (unsigned int i=0;i<supported_modes.num;i++) {
                 if (supported_modes.modes[i]==dcformat) {
                     found_mode=true;
                     break;
                 }
             }
             if (found_mode==false) {
                 native_unavailable=true;
             }
         }
         if (native_unavailable==true) {
             if (mode==CAPTURE_MODE_AUTO) {
                 printf("CaptureV4L Info: Selected format/resolution not supported as FORMAT 0\n");
                 printf("CaptureV4L Info: Selecting lowest available Format 7 mode\n");
                 if (know_modes) {
                     bool found=false;
                     for (unsigned int i=0;i<supported_modes.num;i++) {
                         if (supported_modes.modes[i] >= DC1394_VIDEO_MODE_FORMAT7_MIN && supported_modes.modes[i]<=DC1394_VIDEO_MODE_FORMAT7_MAX) {
                             if (found==false || supported_modes.modes[i] < dcformat) {
                                 found=true;
                                 dcformat=supported_modes.modes[i];
                             }
                         }
                     }
                     if (found==false) {
                         fprintf(stderr,"CaptureV4L Error: No Format 7 modes available!");
                         fprintf(stderr,"CaptureV4L Error: Maybe try selecting a supported Format 0 resolution/framerate?");
 #ifndef VDATA_NO_QT
                         mutex.unlock();
 #endif
                         return false;
                     }
                 } else {
                     dcformat=DC1394_VIDEO_MODE_FORMAT7_0;
                 }
             } else {
                 fprintf(stderr,"CaptureV4L Error: Selected color format/resolution not natively supported!");
                 fprintf(stderr,"CaptureV4L Error: Maybe try switching to auto or a format7 mode.");
 #ifndef VDATA_NO_QT
                 mutex.unlock();
 #endif
                 return false;
             }
         }
     } else {
         if (mode==CAPTURE_MODE_FORMAT_7_MODE_0) dcformat = DC1394_VIDEO_MODE_FORMAT7_0;
         if (mode==CAPTURE_MODE_FORMAT_7_MODE_1) dcformat = DC1394_VIDEO_MODE_FORMAT7_1;
         if (mode==CAPTURE_MODE_FORMAT_7_MODE_2) dcformat = DC1394_VIDEO_MODE_FORMAT7_2;
         if (mode==CAPTURE_MODE_FORMAT_7_MODE_3) dcformat = DC1394_VIDEO_MODE_FORMAT7_3;
         if (mode==CAPTURE_MODE_FORMAT_7_MODE_4) dcformat = DC1394_VIDEO_MODE_FORMAT7_4;
         if (mode==CAPTURE_MODE_FORMAT_7_MODE_5) dcformat = DC1394_VIDEO_MODE_FORMAT7_5;
         if (mode==CAPTURE_MODE_FORMAT_7_MODE_6) dcformat = DC1394_VIDEO_MODE_FORMAT7_6;
         if (mode==CAPTURE_MODE_FORMAT_7_MODE_7) dcformat = DC1394_VIDEO_MODE_FORMAT7_7;
     }
     if (know_modes) {
         //check whether capture mode is supported:
         bool found=false;
         for (unsigned int i=0;i<supported_modes.num;i++) {
             if (supported_modes.modes[i]==dcformat) {
                 found=true;
                 break;
             }
         }
         if (found==false) {
             fprintf(stderr,"CaptureV4L Error: Selected mode (format/resolution/framerate) is not supported by camera!\n");
 #ifndef VDATA_NO_QT
             mutex.unlock();
 #endif
             cleanup();
             return false;
         } else {
         }
     }
     if (dc1394_video_set_mode(camera,dcformat) !=  DC1394_SUCCESS) {
         fprintf(stderr,"CaptureV4L Error: unable to set capture mode\n");
 #ifndef VDATA_NO_QT
         mutex.unlock();
 #endif
         cleanup();
         return false;
     }
     //verify mode:
     dc1394video_mode_t check_mode;
     if (dc1394_video_get_mode(camera,&check_mode) ==  DC1394_SUCCESS) {
         if (check_mode!=dcformat) {
             fprintf(stderr,"CaptureV4L Error: Unable to set selected mode\n");
 #ifndef VDATA_NO_QT
             mutex.unlock();
 #endif
             cleanup();
             return false;
         }
     }
      */
     //TODO: map cature_format to VFL format
     //  http://linuxtv.org/downloads/v4l-dvb-apis/yuv-formats.html
     if (!camera_instance->startStreaming(width, height)) {
         fprintf(stderr,"CaptureV4L Error: unable to setup capture. Maybe selected combination of Format/Resolution is not supported?\n");
 #ifndef VDATA_NO_QT
         mutex.unlock();
 #endif
         cleanup();
         return false;
     }
     vector<VarType *> l = capture_settings->getChildren();
     for (unsigned int i = 0; i < l.size(); i++) {
         l[i]->addFlags(VARTYPE_FLAG_READONLY);
     }
     vector<VarType *> tmp = capture_settings->getChildren();
     for (unsigned int i=0; i < tmp.size();i++) {
         tmp[i]->addFlags( VARTYPE_FLAG_READONLY );
     }
     dcam_parameters->removeFlags( VARTYPE_FLAG_HIDE_CHILDREN );
 #ifndef VDATA_NO_QT
     mutex.unlock();
 #endif
     readAllParameterProperties();
     printf("CaptureV4L Info: Restoring Previously Saved Camera Parameters\n");
     writeAllParameterValues();
     readAllParameterValues();
 #ifndef VDATA_NO_QT
     mutex.lock();
 #endif
     camera_instance->captureWarm();
     //now we can allow upstream/external to capture
     is_capturing=true;
 #ifndef VDATA_NO_QT
     mutex.unlock();
 #endif
     return true;
 }
bool CaptureV4L::stopCapture () virtual
Stop Capture.
Implements CaptureInterface.
Definition at line 1008 of file capturev4l.cpp.
References VarTypes::VarType::addFlags(), capture_settings, cleanup(), dcam_parameters, VarTypes::VarList::getChildren(), velocity.pid_::i, isCapturing(), readAllParameterValues(), VarTypes::VARTYPE_FLAG_HIDE_CHILDREN, and VarTypes::VARTYPE_FLAG_READONLY.
 {
     if (isCapturing()) {
         readAllParameterValues();
         vector<VarType *> tmp = capture_settings->getChildren();
         for (unsigned int i=0; i < tmp.size();i++) {
             tmp[i]->removeFlags( VARTYPE_FLAG_READONLY );
         }
         dcam_parameters->addFlags( VARTYPE_FLAG_HIDE_CHILDREN );
     }
     cleanup();
     return true;
 }
void CaptureV4L::writeAllParameterValues ()
Definition at line 795 of file capturev4l.cpp.
References dcam_parameters, VarTypes::VarList::getChildren(), velocity.pid_::i, v, VarTypes::VARTYPE_ID_LIST, and writeParameterValues().
Referenced by startCapture().
{
     vector<VarType *> v=dcam_parameters->getChildren();
     for (unsigned int i=0;i<v.size();i++) {
         if (v[i]->getType()==VARTYPE_ID_LIST) {
             writeParameterValues((VarList *)v[i]);
         }
     }
 }
void CaptureV4L::writeParameterValues (VarList * item)
Definition at line 867 of file capturev4l.cpp.
References camera_instance, VarTypes::VarBoolVal::getBool(), VarTypes::VarList::getChildren(), VarTypes::VarInt::getInt(), VarTypes::VarType::getName(), getV4LfeatureEnum(), velocity.pid_::i, mutex, VarTypes::VarInt::resetToDefault(), VarTypes::VarBoolVal::setBool(), GlobalV4Linstance::setControl(), GlobalV4Linstance::V4L2_FEATURE_PRIVATE, VarTypes::VARTYPE_ID_BOOL, and VarTypes::VARTYPE_ID_INT.
Referenced by changed(), and writeAllParameterValues().
{
 #ifndef VDATA_NO_QT
     mutex.lock();
 #endif
     bool valid=true;
     v4lfeature_t feature=getV4LfeatureEnum(item,valid);
     if (valid==false) {
 #ifndef VDATA_NO_QT
         mutex.unlock();
 #endif
         return;
     }
     VarInt * vint=0;
     VarBool * venabled=0;
     VarBool * vwasread=0;
     VarBool * vdefault=0;
     vector<VarType *> children=item->getChildren();
     for (unsigned int i=0;i<children.size();i++) {
         if (children[i]->getType()==VARTYPE_ID_BOOL && children[i]->getName()=="was_read") vwasread=(VarBool *)children[i];
         if (children[i]->getType()==VARTYPE_ID_BOOL && children[i]->getName()=="enabled") venabled=(VarBool *)children[i];
         if (children[i]->getType()==VARTYPE_ID_BOOL && children[i]->getName()=="default") vdefault=(VarBool *)children[i];
         if (children[i]->getType()==VARTYPE_ID_INT && children[i]->getName()=="value") vint=(VarInt *)children[i];
     }
     //new: only apply parameters which were previously read from the camera
     if (feature > GlobalV4Linstance::V4L2_FEATURE_PRIVATE) {       //custom/private features
         printf("UNIMPLEMENTED FEATURE (writeParameterValues): %s\n",item->getName().c_str());
     }
     else {
         if (vwasread!=0 && vwasread->getBool()==true) {
             printf("ATTEMPTING TO SET (writeParameterValues): %s\n",item->getName().c_str());
             if (vint!=0) {
                 if (vdefault && vdefault->getBool())
                     vint->resetToDefault();
                 long lValue = static_cast<long>(vint->getInt());
                 if (!camera_instance->setControl(feature,lValue)) {
                     //feature doesn't exist or broke after initial read
                     if (vwasread!=0) vwasread->setBool(false);
                     venabled->setBool(false);
                 }
             }
         }
     }
 #ifndef VDATA_NO_QT
     mutex.unlock();
 #endif
 }
Field Documentation
int CaptureV4L::cam_count protected
Definition at line 272 of file capturev4l.h.
Referenced by CaptureV4L(), resetBus(), and startCapture().
int CaptureV4L::cam_id protected
Definition at line 264 of file capturev4l.h.
Referenced by CaptureV4L(), getFrame(), and startCapture().
int CaptureV4L::cam_list[4] protected
Definition at line 271 of file capturev4l.h.
Referenced by CaptureV4L(), resetBus(), and startCapture().
GlobalV4Linstance* CaptureV4L::camera_instance protected
Definition at line 275 of file capturev4l.h.
Referenced by CaptureV4L(), cleanup(), getFrame(), readParameterProperty(), readParameterValues(), startCapture(), writeParameterValues(), and ~CaptureV4L().
ColorFormat CaptureV4L::capture_format protected
Definition at line 269 of file capturev4l.h.
Referenced by getFrame(), and startCapture().
VarList* CaptureV4L::capture_settings protected
Definition at line 278 of file capturev4l.h.
Referenced by CaptureV4L(), startCapture(), and stopCapture().
VarList* CaptureV4L::conversion_settings protected
Definition at line 279 of file capturev4l.h.
Referenced by CaptureV4L().
VarList* CaptureV4L::dcam_parameters protected
Definition at line 277 of file capturev4l.h.
Referenced by CaptureV4L(), readAllParameterProperties(), readAllParameterValues(), startCapture(), stopCapture(), and writeAllParameterValues().
int CaptureV4L::height protected
Definition at line 266 of file capturev4l.h.
Referenced by convertFrame(), getFrame(), and startCapture().
bool CaptureV4L::is_capturing protected
Definition at line 235 of file capturev4l.h.
Referenced by CaptureV4L(), cleanup(), getFrame(), and startCapture().
int CaptureV4L::left protected
Definition at line 268 of file capturev4l.h.
Referenced by startCapture().
QMutex CaptureV4L::mutex protected
Definition at line 229 of file capturev4l.h.
Referenced by CaptureV4L(), cleanup(), convertFrame(), getFrame(), readParameterProperty(), readParameterValues(), releaseFrame(), resetBus(), startCapture(), and writeParameterValues().
VarList* CaptureV4L::P_BRIGHTNESS protected
Definition at line 241 of file capturev4l.h.
Referenced by CaptureV4L(), getV4LfeatureEnum(), and getVariablePointer().
VarList* CaptureV4L::P_CONTRAST protected
Definition at line 242 of file capturev4l.h.
Referenced by CaptureV4L(), getV4LfeatureEnum(), and getVariablePointer().
VarList* CaptureV4L::P_EXPOSURE protected
Definition at line 243 of file capturev4l.h.
Referenced by CaptureV4L(), getV4LfeatureEnum(), and getVariablePointer().
VarList* CaptureV4L::P_FRAME_RATE protected
Definition at line 251 of file capturev4l.h.
Referenced by CaptureV4L(), getV4LfeatureEnum(), and getVariablePointer().
VarList* CaptureV4L::P_GAIN protected
Definition at line 249 of file capturev4l.h.
Referenced by CaptureV4L(), getV4LfeatureEnum(), and getVariablePointer().
VarList* CaptureV4L::P_GAMMA protected
Definition at line 248 of file capturev4l.h.
Referenced by CaptureV4L(), getV4LfeatureEnum(), and getVariablePointer().
VarList* CaptureV4L::P_HUE protected
Definition at line 246 of file capturev4l.h.
Referenced by CaptureV4L(), getV4LfeatureEnum(), and getVariablePointer().
VarList* CaptureV4L::P_SATURATION protected
Definition at line 247 of file capturev4l.h.
Referenced by CaptureV4L(), getV4LfeatureEnum(), and getVariablePointer().
VarList* CaptureV4L::P_SHARPNESS protected
Definition at line 244 of file capturev4l.h.
Referenced by CaptureV4L(), getV4LfeatureEnum(), and getVariablePointer().
VarList* CaptureV4L::P_TEMPERATURE protected
Definition at line 250 of file capturev4l.h.
Referenced by CaptureV4L(), getV4LfeatureEnum(), and getVariablePointer().
VarList* CaptureV4L::P_WHITE_BALANCE protected
Definition at line 245 of file capturev4l.h.
Referenced by CaptureV4L(), getV4LfeatureEnum(), and getVariablePointer().
RawImage CaptureV4L::rawFrame protected
Definition at line 273 of file capturev4l.h.
Referenced by getFrame(), and ~CaptureV4L().
int CaptureV4L::ring_buffer_size protected
Definition at line 270 of file capturev4l.h.
Referenced by startCapture().
int CaptureV4L::top protected
Definition at line 267 of file capturev4l.h.
Referenced by startCapture().
VarInt* CaptureV4L::v_buffer_size protected
Definition at line 262 of file capturev4l.h.
Referenced by CaptureV4L(), and startCapture().
VarInt* CaptureV4L::v_cam_bus protected
Definition at line 254 of file capturev4l.h.
Referenced by CaptureV4L(), and startCapture().
VarStringEnum* CaptureV4L::v_colormode protected
Definition at line 260 of file capturev4l.h.
Referenced by CaptureV4L(), and startCapture().
VarStringEnum* CaptureV4L::v_colorout protected
Definition at line 238 of file capturev4l.h.
Referenced by CaptureV4L(), and copyAndConvertFrame().
VarStringEnum* CaptureV4L::v_format protected
Definition at line 261 of file capturev4l.h.
VarInt* CaptureV4L::v_fps protected
Definition at line 255 of file capturev4l.h.
Referenced by CaptureV4L(), and startCapture().
VarInt* CaptureV4L::v_height protected
Definition at line 257 of file capturev4l.h.
Referenced by CaptureV4L(), and startCapture().
VarInt* CaptureV4L::v_left protected
Definition at line 258 of file capturev4l.h.
Referenced by CaptureV4L(), and startCapture().
VarInt* CaptureV4L::v_top protected
Definition at line 259 of file capturev4l.h.
Referenced by CaptureV4L(), and startCapture().
VarInt* CaptureV4L::v_width protected
Definition at line 256 of file capturev4l.h.
Referenced by CaptureV4L(), and startCapture().
int CaptureV4L::width protected
Definition at line 265 of file capturev4l.h.
Referenced by convertFrame(), getFrame(), and startCapture().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/capture/capturev4l.h
ssl-vision/src/shared/capture/capturev4l.cpp