Documentation: RealTimeDisplayWidget Class Reference
RealTimeDisplayWidget Class Reference
A base-class for all visualization-related display-widgets.
#include <realtimedisplaywidget.h>
Public Member Functions
RealTimeDisplayWidget (FrameBuffer *_rb=0)
virtual ~RealTimeDisplayWidget ()
FrameBuffer * getRingBuffer ()
void setRingBuffer (FrameBuffer *_rb)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
Protected Attributes
VideoStats stats
FrameBuffer * rb
Detailed Description
A base-class for all visualization-related display-widgets.
Author
Stefan Zickler, (C) 2008
Definition at line 34 of file realtimedisplaywidget.h.
Constructor & Destructor Documentation
RealTimeDisplayWidget::RealTimeDisplayWidget (FrameBuffer * _rb = 0)
Definition at line 24 of file realtimedisplaywidget.cpp.
References setRingBuffer().
{
   setRingBuffer(_rb);
 }
RealTimeDisplayWidget::~RealTimeDisplayWidget () virtual
Definition at line 28 of file realtimedisplaywidget.cpp.
{
 }
Member Function Documentation
void RealTimeDisplayWidget::displayLoopEvent (bool frame_changed, RenderOptions * opts) virtual
Reimplemented in GLWidget.
Definition at line 39 of file realtimedisplaywidget.cpp.
Referenced by MainWindow::timerEvent().
{
   (void) frame_changed;
   (void) opts;
 }
FrameBuffer * RealTimeDisplayWidget::getRingBuffer ()
Definition at line 31 of file realtimedisplaywidget.cpp.
References rb.
Referenced by MainWindow::timerEvent().
{
   return rb;
 }
void RealTimeDisplayWidget::setRingBuffer (FrameBuffer * _rb)
Definition at line 35 of file realtimedisplaywidget.cpp.
References rb.
Referenced by MainWindow::MainWindow(), and RealTimeDisplayWidget().
{
   rb = _rb;
 }
Field Documentation
FrameBuffer* RealTimeDisplayWidget::rb protected
Definition at line 37 of file realtimedisplaywidget.h.
Referenced by GLWidget::displayLoopEvent(), getRingBuffer(), GLLUTWidget::GLLUTWidget(), GLWidget::GLWidget(), GLWidget::myGLdraw(), GLWidget::saveImage(), setRingBuffer(), and GLWidget::setRingBufferBB().
VideoStats RealTimeDisplayWidget::stats protected
Definition at line 36 of file realtimedisplaywidget.h.
The documentation for this class was generated from the following files:
ssl-vision/src/app/gui/realtimedisplaywidget.h
ssl-vision/src/app/gui/realtimedisplaywidget.cpp