Documentation: GetOpt Class Reference
GetOpt Class Reference
A command line option parser.
#include <qgetopt.h>
Data Structures
struct Option
Public Member Functions
GetOpt ()
GetOpt (int offset)
GetOpt (int argc, char *argv[])
GetOpt (const QStringList &a)
QString appName () const
void addSwitch (const QString &lname, bool *b)
void addOptSwitch (const QString &lname, bool *b, bool def=false)
void addShortSwitch (char s, const QString &lname, bool *b)
void addShortOptSwitch (char s, const QString &lname, bool *b, bool def=false)
void addOption (char s, const QString &l, QString *v)
void addVarLengthOption (const QString &l, QStringList *v)
void addRepeatableOption (char s, QStringList *v)
void addRepeatableOption (const QString &l, QStringList *v)
void addOptionalOption (const QString &l, QString *v, const QString &def)
void addOptionalOption (char s, const QString &l, QString *v, const QString &def)
void addArgument (const QString &name, QString *v)
void addOptionalArgument (const QString &name, QString *v)
bool parse (bool untilFirstSwitchOnly)
bool parse ()
bool isSet (const QString &name) const
int currentArgument () const
Private Types
enum OptionType {
OUnknown, OEnd, OSwitch, OArg1,
OOpt, ORepeat, OVarLen, OOptSwitch,
OShortSwitch, OShortOptSwitch
}
typedef QLinkedList< Option >::const_iterator OptionConstIterator
Private Member Functions
void init (int argc, char *argv[], int offset=1)
void addOption (Option o)
void setSwitch (const Option &o)
Private Attributes
QLinkedList< Option > options
QMap< QString, int > setOptions
QStringList args
QString aname
int numReqArgs
int numOptArgs
Option reqArg
Option optArg
int currArg
Friends
struct Option
Detailed Description
A command line option parser.
This class helps to overcome the repetitive, tedious and error-prone task of parsing the command line options passed to your application by the user. Specify the acceptable syntax with a minimum of statements in a readable way, check it against the actual arguments passed and find the retrieved values in variables of your program. The name GetOpt is based on similar utilities build into the Unix shell and other languages.
A command line that a user might have entered is:
app -v --config=my.cnf -Wall input.dat
The typical usage has three stages:
Construct a parser specifying what arguments to parse
Set up the list of allowed and required options
Run the parser
For the first step there are three different constructors that either take arguments directly from main(), QApplication or a user specified list. Setting up the accepted syntax is done by a set of add functions like addSwitch(). The final step of running the parser is simply done by calling parse().
A short example implementing a –verbose switch:
int main(int argc, char **argv)
{
    GetOpt opts(argc, argv);
    bool verbose;
    opts.addSwitch("verbose", &verbose);
    if (!opts.parse())
        return 1;
    if (verbose)
        cout << "VERBOSE mode on" << endl;
    ...
For a better understanding of the function names we'll better define some terms used in the API and its documentation:
Argument An argument is a plain text token like e.g. a file name one typically passes to an editor when invoking it.
Switch A switch is an on/off kind of argument without the need of additional information. Example: –debug.
Option An option is a normally optional argument with a key-value syntax like –output=out.txt or -I/usr/include.
Short Option A short option is a one letter option with a preceding dash. Like -v.
Long Option A long option has a more verbose, multi-letter name like –debug.
Author
froglogic GbR conta.nosp@m.ct@f.nosp@m.roglo.nosp@m.gic..nosp@m.com
Definition at line 30 of file qgetopt.h.
Member Typedef Documentation
typedef QLinkedList<Option>::const_iterator GetOpt::OptionConstIterator private
Definition at line 92 of file qgetopt.h.
Member Enumeration Documentation
enum GetOpt::OptionType private
Enumerator
OUnknown
OEnd
OSwitch
OArg1
OOpt
ORepeat
OVarLen
OOptSwitch
OShortSwitch
OShortOptSwitch
Definition at line 67 of file qgetopt.h.
 { OUnknown, OEnd, OSwitch, OArg1, OOpt, ORepeat, OVarLen, OOptSwitch, OShortSwitch, OShortOptSwitch };
Constructor & Destructor Documentation
GetOpt::GetOpt ()
Constructs a command line parser from the arguments stored in a previously created QApplication instance.
Example usage:
QApplication a(argc, argv);
GetOpt opt;
This constructor is probably the most convenient one to use in a regular Qt application. Note that QApplication may already have removed Qt (or X11) specific arguments. Also see QApplication::argv() and QApplication::argc().
Definition at line 95 of file qgetopt.cpp.
References init().
 {
     if ( !qApp )
     qFatal( "GetOpt: requires a QApplication instance to be constructed first" );
     init( qApp->argc(), qApp->argv(), 1 );
 }
GetOpt::GetOpt (int offset)
Definition at line 106 of file qgetopt.cpp.
References init().
 {
     if ( !qApp )
     qFatal( "GetOpt: requires a QApplication instance to be constructed first" );
     init( qApp->argc(), qApp->argv(), offset );
 }
GetOpt::GetOpt (int argc, char * argv[])
Construct a command line parser from the array argv of string pointers with the size argc. Those parameters have the form typically found in the main() function. That means that you can simply pass on the arguments specified by the user of your application.
Example usage:
int main(int argc, char **argv) {
    GetOpt opt(argc, argv);
    ...
}
Definition at line 130 of file qgetopt.cpp.
References init().
 {
     init( argc, argv );
 }
GetOpt::GetOpt (const QStringList & a)
Construct a command line parser from the arguments specified in the list of arguments a. This constructor is convenient in those cases where you want to parse a command line assembled on-the-fly instead of relying on the argc and arg parameters passed to the main() function.
Definition at line 142 of file qgetopt.cpp.
References init().
     : args( a )
 {
     init( 0, 0 );
 }
Member Function Documentation
void GetOpt::addArgument (const QString & name, QString * v)
Registers a required command line argument name. If the argument is missing parse() will return false to indicate an error and *v will remain with its default QString::null value. Otherwise *v will be set to the value of the argument.
Example:
To accept simple arguments like
myeditor letter.txt
use a call like:
QString &file;
opt.addArgument("file", &file);
Note: the name parameter has a rather descriptive meaning for now. It might be used for generating a usage or error message in the future. Right now, the only current use is in relation with the isSet() function.
Definition at line 639 of file qgetopt.cpp.
References numReqArgs, OUnknown, reqArg, GetOpt::Option::stringValue, and v.
Referenced by appName().
 {
     Option opt( OUnknown, 0, name );
     opt.stringValue = v;
     reqArg = opt;
     ++numReqArgs;
     *v = QString::null;
 }
void GetOpt::addOption (char s, const QString & l, QString * v)
Registers an option with the short name s and long name l to the parser. If this option is found during parsing the value will be stored in the string pointed to by v. By default *v will be initialized to QString::null.
Definition at line 499 of file qgetopt.cpp.
References OArg1, GetOpt::Option::stringValue, and v.
Referenced by addOptionalOption(), addOptSwitch(), addRepeatableOption(), addShortOptSwitch(), addShortSwitch(), addSwitch(), addVarLengthOption(), and appName().
 {
     Option opt( OArg1, s, l );
     opt.stringValue = v;
     addOption( opt );
     *v = QString::null;
 }
void GetOpt::addOption (Option o) private
Definition at line 419 of file qgetopt.cpp.
References options.
 {
     // ### check for conflicts
     options.append( o );
 }
void GetOpt::addOptionalArgument (const QString & name, QString * v)
Registers an optional command line argument name. For a more detailed description see the addArgument() documentation.
Definition at line 653 of file qgetopt.cpp.
References numOptArgs, optArg, OUnknown, GetOpt::Option::stringValue, and v.
Referenced by appName().
 {
     Option opt( OUnknown, 0, name );
     opt.stringValue = v;
     optArg = opt;
     ++numOptArgs;
     *v = QString::null;
 }
void GetOpt::addOptionalOption (const QString & l, QString * v, const QString & def)
Adds a long option l that has an optional value parameter. If the value is not specified by the user it will be set to def.
Example:
GetOpt opt;
QString file;
opt.addOptionalOption("dump", &file, "<stdout>");
See also
addOption
Definition at line 593 of file qgetopt.cpp.
Referenced by appName().
 {
     addOptionalOption( 0, l, v, def );
 }
void GetOpt::addOptionalOption (char s, const QString & l, QString * v, const QString & def)
Adds a short option s that has an optional value parameter. If the value is not specified by the user it will be set to def.
Definition at line 603 of file qgetopt.cpp.
References addOption(), GetOpt::Option::def, OOpt, GetOpt::Option::stringValue, and v.
 {
     Option opt( OOpt, s, l );
     opt.stringValue = v;
     opt.def = def;
     addOption( opt );
     *v = def; //QString::null;
 }
void GetOpt::addOptSwitch (const QString & lname, bool * b, bool def = false)
Definition at line 451 of file qgetopt.cpp.
References addOption(), GetOpt::Option::boolValue, and OOptSwitch.
Referenced by appName().
 {
     Option opt( OOptSwitch, 0, lname );
     opt.boolValue = b;
     addOption( opt );
     // ### could do all inits at the beginning of parse()
     *b = def;
 }
void GetOpt::addRepeatableOption (char s, QStringList * v)
Registers an option with the short name s that can be specified repeatedly in the command line. The option values will be stored in the list pointed to by v. If no s option is found *v will remain at its default value of an empty QStringList instance.
Example:
To parse the -I options in a command line like
myapp -I/usr/include -I/usr/local/include
you can use code like this:
GetOpt opt;
QStringList includes;
opt.addRepeatableOption('I', &includes);
opt.parse();
Definition at line 557 of file qgetopt.cpp.
References addOption(), GetOpt::Option::listValue, ORepeat, and v.
Referenced by appName().
 {
     Option opt( ORepeat, s, QString::null );
     opt.listValue = v;
     addOption( opt );
     *v = QStringList();
 }
void GetOpt::addRepeatableOption (const QString & l, QStringList * v)
Registers an option with the long name l that can be specified repeatedly in the command line.
See also
addRepeatableOption(char, QStringList*)
Definition at line 571 of file qgetopt.cpp.
References addOption(), GetOpt::Option::listValue, ORepeat, and v.
 {
     Option opt( ORepeat, 0, l );
     opt.listValue = v;
     addOption( opt );
     *v = QStringList();
 }
void GetOpt::addShortOptSwitch (char s, const QString & lname, bool * b, bool def = false)
Definition at line 470 of file qgetopt.cpp.
References addOption(), GetOpt::Option::boolValue, and OShortOptSwitch.
Referenced by appName(), and main().
 {
     Option opt( OShortOptSwitch, s, lname );
     opt.boolValue = b;
     addOption( opt );
     // ### could do all inits at the beginning of parse()
     *b = def;
 }
void GetOpt::addShortSwitch (char s, const QString & lname, bool * b)
Definition at line 460 of file qgetopt.cpp.
References addOption(), GetOpt::Option::boolValue, and OShortSwitch.
Referenced by appName().
 {
     Option opt( OShortSwitch, s, lname );
     opt.boolValue = b;
     addOption( opt );
     // ### could do all inits at the beginning of parse()
     *b = false;
 }
void GetOpt::addSwitch (const QString & lname, bool * b)
Adds a switch with the long name lname. If the switch is found during parsing the bool *b will bet set to true. Otherwise the bool will be initialized to false.
Example:
GetOpt opt;
bool verbose;
opt.addSwitch("verbose", &verbose);
The boolean flag verbose will be set to true if –verbose has been specified in the command line; false otherwise.
Definition at line 441 of file qgetopt.cpp.
References addOption(), GetOpt::Option::boolValue, and OSwitch.
Referenced by appName(), and main().
 {
     Option opt( OSwitch, 0, lname );
     opt.boolValue = b;
     addOption( opt );
     // ### could do all inits at the beginning of parse()
     *b = false;
 }
void GetOpt::addVarLengthOption (const QString & l, QStringList * v)
Registers a long option l that can have a variable number of corresponding value parameters. As there currently is no way to tell the end of the value list the only sensible use of this option is at the end of the command line.
Example:
QStringList args;
opt.addVarLengthOption("exec", &args);
Above code will lead to "-f" and "test.txt" being stored in args upon
myapp --exec otherapp -f test.txt
Definition at line 527 of file qgetopt.cpp.
References addOption(), GetOpt::Option::listValue, OVarLen, and v.
Referenced by appName().
 {
     Option opt( OVarLen, 0, l );
     opt.listValue = v;
     addOption( opt );
     *v = QStringList();
 }
QString GetOpt::appName () const inline
Definition at line 37 of file qgetopt.h.
References addArgument(), addOption(), addOptionalArgument(), addOptionalOption(), addOptSwitch(), addRepeatableOption(), addShortOptSwitch(), addShortSwitch(), addSwitch(), addVarLengthOption(), aname, parse(), and v.
 { return aname; }
int GetOpt::currentArgument () const inline
Definition at line 64 of file qgetopt.h.
References currArg.
 { return currArg; }
void GetOpt::init (int argc, char * argv[], int offset = 1) private
Definition at line 151 of file qgetopt.cpp.
References aname, args, currArg, velocity.pid_::i, numOptArgs, and numReqArgs.
Referenced by GetOpt().
 {
     numReqArgs = numOptArgs = 0;
     currArg = 1; // appname is not part of the arguments
     if ( argc ) {
     // application name
     aname = QFileInfo( QString::fromUtf8( argv[0] ) ).fileName();
     // arguments
     for ( int i = offset; i < argc; ++i )
         args.append( QString::fromUtf8( argv[i] ) );
     }
 }
bool GetOpt::isSet (const QString & name) const
Returns true if the (long) option or switch name has been found in the command line; returns false otherwise. Leading hyphens are not part of the name.
As the set/not set decision can also be made depending on the value of the variable reference used in the respective add*() call there's generally little use for this function.
Definition at line 672 of file qgetopt.cpp.
References setOptions.
Referenced by parse().
 {
     return setOptions.find( name ) != setOptions.end();
 }
bool GetOpt::parse (bool untilFirstSwitchOnly)
Definition at line 180 of file qgetopt.cpp.
References args, currArg, GetOpt::Option::def, GetOpt::Option::listValue, GetOpt::Option::lname, numOptArgs, numReqArgs, OArg1, OEnd, OOpt, OOptSwitch, optArg, Option, options, ORepeat, OShortOptSwitch, OShortSwitch, OSwitch, OUnknown, OVarLen, reqArg, setOptions, setSwitch(), GetOpt::Option::sname, run_goalie::state, GetOpt::Option::stringValue, t, and GetOpt::Option::type.
Referenced by main().
 {
     //    qDebug( "parse(%s)", args.join( QString( "," ) ).ascii() );
     // push all arguments as we got them on a stack
     // more pushes might following when parsing condensed arguments
     // like --key=value.
     QStack<QString> stack;
     {
       QStringList::ConstIterator it = args.isEmpty() ? args.end() : --args.end();
       const QStringList::ConstIterator  end = args.end();
       while ( it != end )
       {
         stack.push( *it );
         if (it==args.begin())
           break;
         --it;
       }
     }
     const OptionConstIterator obegin = options.begin();
     const OptionConstIterator oend = options.end();
     enum { StartState, ExpectingState, OptionalState } state = StartState;
     Option currOpt;
     enum TokenType { LongOpt, ShortOpt, Arg, End } t, currType = End;
     bool extraLoop = true; // we'll do an extra round. fake an End argument
     while ( !stack.isEmpty() || extraLoop ) {
     QString a;
     QString origA;
     // identify argument type
     if ( !stack.isEmpty() ) {
         a = stack.pop();
         currArg++;
         origA = a;
         //      qDebug( "popped %s", a.ascii() );
         if ( a.startsWith( QString::fromLatin1( "--" ) ) ) {
         // recognized long option
         a = a.mid( 2 );
         if ( a.isEmpty() ) {
             qWarning( "'--' feature not supported, yet" );
             exit( 2 );
         }
         t = LongOpt;
         // split key=value style arguments
         int equal = a.indexOf( '=' );
         if ( equal >= 0 ) {
             stack.push( a.mid( equal + 1 ) );
             currArg--;
             a = a.left( equal );
         }
         } else if ( a.length() == 1 ) {
         t = Arg;
         } else if ( a[0] == '-' ) {
 #if 0 // compat mode for -long style options
         if ( a.length() == 2 ) {
             t = ShortOpt;
             a = a[1];
         } else {
             a = a.mid( 1 );
             t = LongOpt;
             // split key=value style arguments
             int equal = a.find( '=' );
             if ( equal >= 0 ) {
             stack.push( a.mid( equal + 1 ) );
             currArg--;
             a = a.left( equal );
             }
         }
 #else
         // short option
         t = ShortOpt;
         // followed by an argument ? push it for later processing.
         if ( a.length() > 2 ) {
             stack.push( a.mid( 2 ) );
             currArg--;
         }
         a = a[1];
 #endif
         } else {
         t = Arg;
         }
     } else {
         // faked closing argument
         t = End;
     }
     // look up among known list of options
     Option opt;
     if ( t != End ) {
         OptionConstIterator oit = obegin;
         while ( oit != oend ) {
         const Option &o = *oit;
         if ( ( t == LongOpt && a == o.lname ) || // ### check state
              ( t == ShortOpt && a[0].unicode() == o.sname ) ) {
             opt = o;
             break;
         }
         ++oit;
         }
         if ( t == LongOpt && opt.type == OUnknown ) {
         if ( currOpt.type != OVarLen ) {
             qWarning( "Unknown option --%s",a.toAscii().constData() );
             return false;
         } else {
             // VarLength options support arguments starting with '-'
             t = Arg;
         }
         } else if ( t == ShortOpt && opt.type == OUnknown ) {
         if ( currOpt.type != OVarLen ) {
             qWarning( "Unknown option -%c", a[0].unicode() );
             return false;
         } else {
             // VarLength options support arguments starting with '-'
             t = Arg;
         }
         }
     } else {
         opt = Option( OEnd );
     }
     // interpret result
     switch ( state ) {
     case StartState:
         if ( opt.type == OSwitch ) {
         setSwitch( opt );
         setOptions.insert( opt.lname, 1 );
         setOptions.insert( QString( QChar( opt.sname ) ), 1 );
         } else if ( opt.type == OOptSwitch ) {
         setSwitch( opt );
         setOptions.insert( opt.lname, 1 );
         setOptions.insert( QString( QChar( opt.sname ) ), 1 );
                 state = OptionalState;
         currOpt = opt;
         currType = t;
         } else if ( opt.type == OShortSwitch ) {
         setSwitch( opt );
         setOptions.insert( opt.lname, 1 );
         setOptions.insert( QString( QChar( opt.sname ) ), 1 );
         } else if ( opt.type == OShortOptSwitch ) {
         setSwitch( opt );
         setOptions.insert( opt.lname, 1 );
         setOptions.insert( QString( QChar( opt.sname ) ), 1 );
                 state = OptionalState;
         currOpt = opt;
         currType = t;
         } else if ( opt.type == OArg1 || opt.type == ORepeat ) {
         state = ExpectingState;
         currOpt = opt;
         currType = t;
         setOptions.insert( opt.lname, 1 );
         setOptions.insert( QString( QChar( opt.sname ) ), 1 );
         } else if ( opt.type == OOpt || opt.type == OVarLen ) {
         state = OptionalState;
         currOpt = opt;
         currType = t;
         setOptions.insert( opt.lname, 1 );
         setOptions.insert( QString( QChar( opt.sname ) ), 1 );
         } else if ( opt.type == OEnd ) {
         // we're done
         } else if ( opt.type == OUnknown && t == Arg ) {
         if ( numReqArgs > 0 ) {
             if ( reqArg.stringValue->isNull() ) { // ###
             *reqArg.stringValue = a;
             } else {
             qWarning( "Too many arguments" );
             return false;
             }
         } else if ( numOptArgs > 0 ) {
             if ( optArg.stringValue->isNull() ) { // ###
             *optArg.stringValue = a;
             } else {
             qWarning( "Too many arguments" );
             return false;
             }
         }
         } else {
         qFatal( "unhandled StartState case %d",  opt.type );
         }
         break;
     case ExpectingState:
         if ( t == Arg ) {
         if ( currOpt.type == OArg1 ) {
             *currOpt.stringValue = a;
             state = StartState;
         } else if ( currOpt.type == ORepeat ) {
             currOpt.listValue->append( a );
             state = StartState;
         } else {
             abort();
         }
         } else {
         QString n = currType == LongOpt ?
                 currOpt.lname : QString( QChar( currOpt.sname ) );
         qWarning( "Expected an argument after '%s' option", n.toAscii().constData() );
         return false;
         }
         break;
     case OptionalState:
         if ( t == Arg ) {
         if ( currOpt.type == OOpt ) {
             *currOpt.stringValue = a;
             state = StartState;
         } else if ( currOpt.type == OVarLen ) {
             currOpt.listValue->append( origA );
             // remain in this state
         } else {
             abort();
         }
         } else {
         // optional argument not specified
         if ( currOpt.type == OOpt )
             *currOpt.stringValue = currOpt.def;
         if ( t != End ) {
             // re-evaluate current argument
             stack.push( origA );
             currArg--;
         }
         state = StartState;
         }
         break;
     }
     if ( untilFirstSwitchOnly && (opt.type == OSwitch || opt.type== OShortSwitch || opt.type == OOptSwitch || opt.type == OShortOptSwitch) )
         return true;
     // are we in the extra loop ? if so, flag the final end
     if ( t == End )
         extraLoop = false;
     }
     if ( numReqArgs > 0 && reqArg.stringValue->isNull() ) {
     qWarning( "Lacking required argument" );
     return false;
     }
     return true;
 }
bool GetOpt::parse () inline
Parse the command line arguments specified in the constructor under the conditions set by the various add*() functions. On success, the given variable reference will be initialized with their respective values and true will be returned. Returns false otherwise.
In the future there'll be a way to retrieve an error message. In the current version the message will be printed to stderr.
Definition at line 60 of file qgetopt.h.
References isSet(), and parse().
Referenced by appName(), and parse().
 { return parse( false ); }
void GetOpt::setSwitch (const Option & o) private
Definition at line 487 of file qgetopt.cpp.
References GetOpt::Option::boolValue, OOptSwitch, OShortOptSwitch, OShortSwitch, OSwitch, and GetOpt::Option::type.
Referenced by parse().
 {
     assert( (o.type == OSwitch || o.type== OShortSwitch || o.type == OOptSwitch || o.type == OShortOptSwitch) );
     *o.boolValue = true;
 }
Friends And Related Function Documentation
friend struct Option friend
Definition at line 69 of file qgetopt.h.
Referenced by parse().
Field Documentation
QString GetOpt::aname private
Definition at line 100 of file qgetopt.h.
Referenced by appName(), and init().
QStringList GetOpt::args private
Definition at line 99 of file qgetopt.h.
Referenced by init(), and parse().
int GetOpt::currArg private
Definition at line 107 of file qgetopt.h.
Referenced by currentArgument(), init(), and parse().
int GetOpt::numOptArgs private
Definition at line 103 of file qgetopt.h.
Referenced by addOptionalArgument(), init(), and parse().
int GetOpt::numReqArgs private
Definition at line 102 of file qgetopt.h.
Referenced by addArgument(), init(), and parse().
Option GetOpt::optArg private
Definition at line 105 of file qgetopt.h.
Referenced by addOptionalArgument(), and parse().
QLinkedList<Option> GetOpt::options private
Definition at line 91 of file qgetopt.h.
Referenced by addOption(), and parse().
Option GetOpt::reqArg private
Definition at line 104 of file qgetopt.h.
Referenced by addArgument(), and parse().
QMap<QString, int> GetOpt::setOptions private
Definition at line 93 of file qgetopt.h.
Referenced by isSet(), and parse().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/util/qgetopt.h
ssl-vision/src/shared/util/qgetopt.cpp