Documentation: rrt::RRT< T > Class Template Reference
rrt::RRT< T > Class Template Reference
#include <RRT.hpp>
Public Member Functions
RRT ()
RRT (Utils::Point< T > start, Utils::Point< T > end)
virtual bool plan ()
virtual std::deque< Utils::Point< T > > getPointsOnPath ()
virtual void setEndPoints (Utils::Point< T > start, Utils::Point< T > end)
virtual void setCheckPointFunction (bool(*f)(Utils::Point< T >))
virtual void setStepLength (double value)
virtual void setOrigin (Utils::Point< T > origin)
virtual void setHalfDimensions (double x, double y)
virtual void setBiasParameter (unsigned int)
virtual void setMaxIterations (int)
Private Member Functions
bool checkPoint (Utils::Point< T > pt)
Utils::Point< T > generatePoint ()
Utils::Point< T > generateBiasedPoint (int)
void growTree (Utils::Point< T >)
std::pair< Utils::Point< T >, int > findClosestNode (Utils::Point< T >)
Utils::Point< T > getParent (Utils::Point< T >)
std::pair< Utils::Point< T >, Utils::Point< T > > treeComplete (int *)
void generatePath (Utils::Point< T > first, Utils::Point< T > last)
double dist (Utils::Point< T > a, Utils::Point< T > b)
Private Attributes
double halfDimensionX
double halfDimensionY
Utils::Point< T > origin
Utils::Point< T > startPoint
Utils::Point< T > endPoint
double stepLength
std::deque< Utils::Point< T > > pathPoints
int maxIterations
std::vector< std::pair< Utils::Point< T >, Utils::Point< T > > > tree
std::vector< std::pair< Utils::Point< T >, Utils::Point< T > > > tree1
std::vector< std::pair< Utils::Point< T >, Utils::Point< T > > > tree2
unsigned int biasParameter
bool(* userCheck)(Utils::Point< T >)
Detailed Description
template<class T>
class rrt::RRT< T >
Definition at line 11 of file RRT.hpp.
Constructor & Destructor Documentation
template<class T> rrt::RRT< T >::RRT () inline
Definition at line 29 of file RRT.hpp.
 {};
template<class T> rrt::RRT< T >::RRT (Utils::Point< T > start, Utils::Point< T > end) inline
Definition at line 30 of file RRT.hpp.
References rrt::RRT< T >::getPointsOnPath(), rrt::RRT< T >::plan(), rrt::RRT< T >::setBiasParameter(), rrt::RRT< T >::setCheckPointFunction(), rrt::RRT< T >::setEndPoints(), rrt::RRT< T >::setHalfDimensions(), rrt::RRT< T >::setMaxIterations(), rrt::RRT< T >::setOrigin(), rrt::RRT< T >::setStepLength(), role._GoToPoint::x, and role._GoToPoint::y.
         {
             //srand(time(NULL));
             startPoint=start;
             endPoint=end;
         }
Member Function Documentation
template<class T > bool rrt::RRT< T >::checkPoint (Utils::Point< T > pt) private
Definition at line 172 of file RRT_implementation.hpp.
     {
         return userCheck(next);
     }
template<class T > double rrt::RRT< T >::dist (Utils::Point< T > a, Utils::Point< T > b) private
Definition at line 228 of file RRT_implementation.hpp.
References Utils::Point< T >::x, and Utils::Point< T >::y.
     {
         return sqrt((a.x-b.x)*(a.x-b.x) + (a.y-b.y)*(a.y-b.y));
     }
template<class T > std::pair< Utils::Point< T >, int > rrt::RRT< T >::findClosestNode (Utils::Point< T > cur) private
Definition at line 114 of file RRT_implementation.hpp.
References GVector::dist(), and velocity.pid_::i.
     {
         double min_dist=INT_MAX;
         Utils::Point<T> closest;
         for(int i=0;i<tree.size();i++)
         {
             if(dist(tree[i].first,cur) < min_dist )
             {
                 min_dist=dist(tree[i].first,cur);
                 closest=tree[i].first;
             }
         }
         return std::make_pair(closest,1);
     }
template<class T > Utils::Point< T > rrt::RRT< T >::generateBiasedPoint (int which) private
Definition at line 159 of file RRT_implementation.hpp.
References bot_comm::theta, Utils::Point< T >::x, and Utils::Point< T >::y.
     {
         Utils::Point<T> closest=findClosestNode(endPoint).first;
         double theta = atan2(endPoint.y-closest.y,endPoint.x-closest.x);
         Utils::Point<T> next;
         next.x=closest.x+stepLength*cos(theta);
         next.y=closest.y+stepLength*sin(theta);
         //std::cout<<"Biased Point Generated = "<<next.x<<","<<next.y<<std::endl;
         return next;
     }
template<class T > void rrt::RRT< T >::generatePath (Utils::Point< T > first, Utils::Point< T > last) private
Definition at line 204 of file RRT_implementation.hpp.
     {
         Utils::Point<T> cur=last;
         pathPoints.push_back(cur);
         while(cur!=first || cur!=startPoint)
         {
             Utils::Point<T> parent= getParent(cur);
             //std::cout<<"current : "<<cur.x<<","<<cur.y<<"| parent : "<<parent.x<<","<<parent.y<<std::endl;
             pathPoints.push_back(parent);
             cur=parent;
         }
     }
template<class T > Utils::Point< T > rrt::RRT< T >::generatePoint () private
Definition at line 131 of file RRT_implementation.hpp.
References bot_comm::theta, Utils::Point< T >::x, and Utils::Point< T >::y.
     {
         Utils::Point<T> temp;
         int signX,signY;
         if(rand()%2==0)
             signX=-1;
         else
             signX=1;
         if(rand()%2==0)
             signY=-1;
         else
             signY=1;
         temp.x = origin.x + signX* ( rand() % (int)halfDimensionX );
         temp.y = origin.y + signY* ( rand() % (int)halfDimensionY );
         Utils::Point<T> closest=findClosestNode(temp).first;
         double theta = atan2(temp.y-closest.y,temp.x-closest.x);
         Utils::Point<T> next;
         next.x=closest.x+stepLength*cos(theta);
         next.y=closest.y+stepLength*sin(theta);
         //std::cout<<"Point Generated = "<<temp.x<<","<<temp.y<<std::endl;
         return next;
     }
template<class T > Utils::Point< T > rrt::RRT< T >::getParent (Utils::Point< T > cur) private
Definition at line 218 of file RRT_implementation.hpp.
References velocity.pid_::i.
     {
         for(int i=0;i<tree.size();i++)
         {
             if(tree[i].first==cur)
                 return tree[i].second;
         }
     }
template<class T > std::deque< Utils::Point< T > > rrt::RRT< T >::getPointsOnPath () virtual
Definition at line 28 of file RRT_implementation.hpp.
Referenced by main(), and rrt::RRT< T >::RRT().
     {
         return pathPoints;
     }
template<class T > void rrt::RRT< T >::growTree (Utils::Point< T > next) private
Definition at line 95 of file RRT_implementation.hpp.
     {
         //growing the tree by adding node
         //std::cout<<"finding parent in tree of size = "<<tree.size()<<std::endl;
         Utils::Point<T> parent;
         parent= findClosestNode(next).first;
         //std::cout<<"current : "<<next.x<<","<<next.y<<"| parent : "<<parent.x<<","<<parent.y<<std::endl;
         tree.push_back( std::pair< Utils::Point<T>, Utils::Point<T> > (next,parent));
         //std::cout<<"Tree grown"<<std::endl;
         //add pruning code to keep size of tree under control
     }
template<class T > bool rrt::RRT< T >::plan () virtual
Definition at line 46 of file RRT_implementation.hpp.
References check(), and role._GoToPoint::start_time.
Referenced by main(), and rrt::RRT< T >::RRT().
     {
         int count=0;
         int check=0;
         tree.push_back(std::pair< Utils::Point<T>, Utils::Point<T> > (startPoint,startPoint));
         while( check < maxIterations)
         {
             //std::cout<<"In Planning Loop"<<std::endl;
             Utils::Point<T> next;
             int arr[]={1};
             std::pair  <Utils::Point <T>,Utils::Point <T> >  mid = treeComplete(arr);
             if(mid.first!=mid.second)
             {
                 std::cout<<"Tree complete!!"<<std::endl;
                 int start_time=clock();
                 growTree(endPoint);
                 int end_time=clock();
                 std::cout<<"Time to generate path = "<<end_time-start_time<<std::endl;
                 generatePath(startPoint,endPoint);
                 return true;
             }
             else if(count%biasParameter==0)
             {
                 //std::cout<<"Adding Next Biased Point to tree!!"<<std::endl;
                 count=0;
                 do{
                     next= generateBiasedPoint(1);
                 }while(checkPoint(next)!=true);
                 //std::cout<<" : "<<next.x<<","<<next.y<<std::endl;
             }
             else
             {
                 //std::cout<<"Adding next point to tree!!"<<std::endl;
                 do{
                     next = generatePoint();
                 }while(checkPoint(next)!=true);
                 //std::cout<<" : "<<next.x<<","<<next.y<<std::endl;
             }
             //std::cout<<" Growing Tree next : "<<next.x<<","<<next.y<<std::endl;
             growTree(next);
             count++;
             check++;
             //std::cout<<"check= "<<check<<", count= "<<count<<std::endl;
         }
         std::cout<<"Path Not Found"<<std::endl;
         return false;
     }
template<class T > void rrt::RRT< T >::setBiasParameter (unsigned int param) virtual
Definition at line 198 of file RRT_implementation.hpp.
Referenced by main(), and rrt::RRT< T >::RRT().
     {
         biasParameter=param;
     }
template<class T > void rrt::RRT< T >::setCheckPointFunction (bool(*)(Utils::Point< T >) f) virtual
Definition at line 108 of file RRT_implementation.hpp.
Referenced by main(), and rrt::RRT< T >::RRT().
     {
         userCheck=f;
     }
template<class T > void rrt::RRT< T >::setEndPoints (Utils::Point< T > start, Utils::Point< T > end) virtual
Definition at line 8 of file RRT_implementation.hpp.
Referenced by main(), and rrt::RRT< T >::RRT().
     {
         startPoint=start;
         endPoint=end;
     }
template<class T > void rrt::RRT< T >::setHalfDimensions (double x, double y) virtual
Definition at line 15 of file RRT_implementation.hpp.
Referenced by main(), and rrt::RRT< T >::RRT().
     {
         halfDimensionX=a;
         halfDimensionY=b;
     }
template<class T > void rrt::RRT< T >::setMaxIterations (int value) virtual
Definition at line 40 of file RRT_implementation.hpp.
Referenced by main(), and rrt::RRT< T >::RRT().
     {
         maxIterations=value;
     }
template<class T > void rrt::RRT< T >::setOrigin (Utils::Point< T > origin) virtual
Definition at line 22 of file RRT_implementation.hpp.
Referenced by main(), and rrt::RRT< T >::RRT().
     {
         origin=pt;
     }
template<class T > void rrt::RRT< T >::setStepLength (double value) virtual
Definition at line 34 of file RRT_implementation.hpp.
Referenced by main(), and rrt::RRT< T >::RRT().
     {
         stepLength=value;
     }
template<class T> std::pair< Utils::Point< T >, Utils::Point< T > > rrt::RRT< T >::treeComplete (int *) private
Definition at line 178 of file RRT_implementation.hpp.
References GVector::dist(), and velocity.pid_::i.
     {
         //std::cout<<"Checking if tree is complete? "<<std::endl;
         //std::cout<<"tree size = "<<tree.size()<<std::endl;
         int min_dist=INT_MAX;
         for(int i=0;i<tree.size();i++)
         {
             double dis= dist(tree[i].first,endPoint);
             if(dis < min_dist)
                 min_dist=dis;
             if(dis < stepLength )
             {
                 return std::make_pair(tree[i].first,endPoint);
             }
         }
         //std::cout<<"Min Distance In this iteration = "<<min_dist<<std::endl;
         return std::make_pair(endPoint,endPoint);
     }
Field Documentation
template<class T> unsigned int rrt::RRT< T >::biasParameter private
Definition at line 25 of file RRT.hpp.
template<class T> Utils::Point<T> rrt::RRT< T >::endPoint private
Definition at line 18 of file RRT.hpp.
template<class T> double rrt::RRT< T >::halfDimensionX private
Definition at line 14 of file RRT.hpp.
template<class T> double rrt::RRT< T >::halfDimensionY private
Definition at line 15 of file RRT.hpp.
template<class T> int rrt::RRT< T >::maxIterations private
Definition at line 21 of file RRT.hpp.
template<class T> Utils::Point<T> rrt::RRT< T >::origin private
Definition at line 16 of file RRT.hpp.
template<class T> std::deque<Utils::Point<T> > rrt::RRT< T >::pathPoints private
Definition at line 20 of file RRT.hpp.
template<class T> Utils::Point<T> rrt::RRT< T >::startPoint private
Definition at line 17 of file RRT.hpp.
template<class T> double rrt::RRT< T >::stepLength private
Definition at line 19 of file RRT.hpp.
template<class T> std::vector< std::pair< Utils::Point<T>, Utils::Point<T> > > rrt::RRT< T >::tree private
Definition at line 22 of file RRT.hpp.
template<class T> std::vector< std::pair< Utils::Point<T>, Utils::Point<T> > > rrt::RRT< T >::tree1 private
Definition at line 23 of file RRT.hpp.
template<class T> std::vector< std::pair< Utils::Point<T>, Utils::Point<T> > > rrt::RRT< T >::tree2 private
Definition at line 24 of file RRT.hpp.
template<class T> bool(* rrt::RRT< T >::userCheck) (Utils::Point< T >) private
Definition at line 53 of file RRT.hpp.
The documentation for this class was generated from the following files:
RRT/include/RRT.hpp
RRT/include/RRT_implementation.hpp
RRT/include/RRTConnect_implementation.hpp