Documentation: protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto Namespace Reference
protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto Namespace Reference
Data Structures
struct TableStruct
Functions
void AddDescriptors ()
void InitDefaultsVector2fImpl ()
void InitDefaultsVector2f ()
void InitDefaultsSSL_FieldLineSegmentImpl ()
void InitDefaultsSSL_FieldLineSegment ()
void InitDefaultsSSL_FieldCicularArcImpl ()
void InitDefaultsSSL_FieldCicularArc ()
void InitDefaultsSSL_GeometryFieldSizeImpl ()
void InitDefaultsSSL_GeometryFieldSize ()
void InitDefaultsSSL_GeometryCameraCalibrationImpl ()
void InitDefaultsSSL_GeometryCameraCalibration ()
void InitDefaultsSSL_GeometryDataImpl ()
void InitDefaultsSSL_GeometryData ()
void InitDefaults ()
Function Documentation
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::AddDescriptors ()
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaults () inline
Definition at line 57 of file messages_robocup_ssl_geometry.pb.h.
References _SSL_FieldCicularArc_default_instance_, _SSL_FieldLineSegment_default_instance_, _SSL_GeometryCameraCalibration_default_instance_, _SSL_GeometryData_default_instance_, _SSL_GeometryFieldSize_default_instance_, _Vector2f_default_instance_, InitDefaultsSSL_FieldCicularArc(), InitDefaultsSSL_FieldLineSegment(), InitDefaultsSSL_GeometryCameraCalibration(), InitDefaultsSSL_GeometryData(), InitDefaultsSSL_GeometryFieldSize(), and InitDefaultsVector2f().
{
   InitDefaultsVector2f();
   InitDefaultsSSL_FieldLineSegment();
   InitDefaultsSSL_FieldCicularArc();
   InitDefaultsSSL_GeometryFieldSize();
   InitDefaultsSSL_GeometryCameraCalibration();
   InitDefaultsSSL_GeometryData();
 }
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_FieldCicularArc ()
Referenced by InitDefaults().
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_FieldCicularArcImpl ()
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_FieldLineSegment ()
Referenced by InitDefaults().
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_FieldLineSegmentImpl ()
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryCameraCalibration ()
Referenced by InitDefaults().
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryCameraCalibrationImpl ()
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryData ()
Referenced by InitDefaults().
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryDataImpl ()
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryFieldSize ()
Referenced by InitDefaults().
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsSSL_GeometryFieldSizeImpl ()
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsVector2f ()
Referenced by InitDefaults().
void protobuf_messages_5frobocup_5fssl_5fgeometry_2eproto::InitDefaultsVector2fImpl ()