Documentation: Sobel Class Reference
Sobel Class Reference
Collection of functions for edge detection.
#include <sobel.h>
Static Public Member Functions
static bool validImagePixel (const greyImage &img, const int x, const int y)
static int horizontalBrighter (const greyImage &img, int x, int y, int threshold)
static int horizontalDarker (const greyImage &img, int x, int y, int threshold)
static int verticalBrighter (const greyImage &img, int x, int y, int threshold)
static int verticalDarker (const greyImage &img, int x, int y, int threshold)
static int maximumHorizontalEdge (const greyImage &img, int y, int xStart, int xEnd, int threshold, int f(const greyImage &, int, int, int))
static int maximumVerticalEdge (const greyImage &img, int x, int yStart, int yEnd, int threshold, int f(const greyImage &, int, int, int))
static int centerOfHorizontalLine (const greyImage &img, int x, int yStart, int yEnd, int threshold)
static int centerOfVerticalLine (const greyImage &img, int y, int xStart, int xEnd, int threshold)
static void centerOfLine (const greyImage &img, int xStart, int xEnd, int yStart, int yEnd, GVector::vector2d< double > &p, bool &centerFound, int threshold)
Detailed Description
Collection of functions for edge detection.
Author
Tim Laue, (C) 2009
Definition at line 35 of file sobel.h.
Member Function Documentation
static int Sobel::centerOfHorizontalLine (const greyImage & img, int x, int yStart, int yEnd, int threshold) inline static
Definition at line 138 of file sobel.h.
References validImagePixel(), verticalBrighter(), verticalDarker(), and role._GoToPoint::y.
   {
     int maxDarkEdge(0);
     int maxBrightEdge(0);
     int maxDarkY(0);
     int maxBrightY(0);
     for(int y=yStart; y<=yEnd; ++y)
     {
       if (!validImagePixel(img, x, y)) continue;
       int currentDarkEdge = Sobel::verticalDarker(img, x, y, threshold);
       int currentBrightEdge = Sobel::verticalBrighter(img, x, y, threshold);
       if(currentDarkEdge > maxDarkEdge)
       {
         maxDarkEdge = currentDarkEdge;
         maxDarkY = y;
       }
       if(currentBrightEdge > maxBrightEdge)
       {
         maxBrightEdge = currentBrightEdge;
         maxBrightY = y;
       }
     }
     return (maxBrightY + maxDarkY) / 2;
   }
static void Sobel::centerOfLine (const greyImage & img, int xStart, int xEnd, int yStart, int yEnd, GVector::vector2d< double > & p, bool & centerFound, int threshold) inline static
Definition at line 192 of file sobel.h.
References GVector::abs(), horizontalBrighter(), horizontalDarker(), velocity.pid_::i, GVector::max(), validImagePixel(), verticalBrighter(), verticalDarker(), role._GoToPoint::x, and role._GoToPoint::y.
Referenced by PluginCameraCalibration::detectEdgesOnSingleArc(), and PluginCameraCalibration::detectEdgesOnSingleLine().
   {
     int maxDarkEdge(0);
     int maxBrightEdge(0);
     GVector::vector2d<double> maxDarkP(0.0,0.0);
     GVector::vector2d<double> maxBrightP(0.0,0.0);
     int numSteps = max(abs(xEnd-xStart),abs(yEnd-yStart));
     double xIncr = ((double) (xEnd-xStart))/((double) numSteps);
     double yIncr = ((double) (yEnd-yStart))/((double) numSteps);
     for(int i=0; i<=numSteps; i++)
     {
       int x = floor((double) xStart + ((double) i)*xIncr + 0.5);
       int y = floor((double) yStart + ((double) i)*yIncr + 0.5);
       if (!validImagePixel(img, x, y)) continue;
       int Dx = Sobel::horizontalDarker(img, x, y, threshold);
       int Dy = Sobel::verticalDarker(img, x, y, threshold);
       int Bx = Sobel::horizontalBrighter(img, x, y, threshold);
       int By = Sobel::verticalBrighter(img, x, y, threshold);
       int currentDarkEdge = (Dx*Dx+Dy*Dy);
       int currentBrightEdge = (Bx*Bx+By*By);
       if( currentDarkEdge > maxDarkEdge)
       {
         maxDarkEdge = currentDarkEdge;
         maxDarkP = GVector::vector2d<double>(x,y);
       }
       if(currentBrightEdge > maxBrightEdge)
       {
         maxBrightEdge = currentBrightEdge;
         maxBrightP = GVector::vector2d<double>(x,y);
       }
     }
     p = 0.5*(maxBrightP + maxDarkP);
     centerFound = (maxDarkEdge>0) && (maxBrightEdge>0);
   }
static int Sobel::centerOfVerticalLine (const greyImage & img, int y, int xStart, int xEnd, int threshold) inline static
Definition at line 165 of file sobel.h.
References horizontalBrighter(), horizontalDarker(), validImagePixel(), and role._GoToPoint::x.
   {
     int maxDarkEdge(0);
     int maxBrightEdge(0);
     int maxDarkX(0);
     int maxBrightX(0);
     for(int x=xStart; x<=xEnd; ++x)
     {
       if (!validImagePixel(img, x, y)) continue;
       int currentDarkEdge = Sobel::horizontalDarker(img, x, y, threshold);
       int currentBrightEdge = Sobel::horizontalBrighter(img, x, y, threshold);
       if(currentDarkEdge > maxDarkEdge)
       {
         maxDarkEdge = currentDarkEdge;
         maxDarkX = x;
       }
       if(currentBrightEdge > maxBrightEdge)
       {
         maxBrightEdge = currentBrightEdge;
         maxBrightX = x;
       }
     }
     return (maxBrightX + maxDarkX) / 2;
   }
static int Sobel::horizontalBrighter (const greyImage & img, int x, int y, int threshold) inline static
Definition at line 48 of file sobel.h.
Referenced by centerOfLine(), centerOfVerticalLine(), and PluginVisualize::DrawSobelImage().
   {
     int sobel = (-1*img.getPixel(x-1,y-1).v) +
                 (-2*img.getPixel(x-1,y).v) +
                 (-1*img.getPixel(x-1,y+1).v) +
                 ( 1*img.getPixel(x+1,y-1).v) +
                 ( 2*img.getPixel(x+1,y).v) +
                 ( 1*img.getPixel(x+1,y+1).v);
     return sobel > threshold ? sobel : 0;
   }
static int Sobel::horizontalDarker (const greyImage & img, int x, int y, int threshold) inline static
Definition at line 60 of file sobel.h.
Referenced by centerOfLine(), centerOfVerticalLine(), and PluginVisualize::DrawSobelImage().
   {
     int sobel = ( 1*img.getPixel(x-1,y-1).v) +
                 ( 2*img.getPixel(x-1,y).v) +
                 ( 1*img.getPixel(x-1,y+1).v) +
                 (-1*img.getPixel(x+1,y-1).v) +
                 (-2*img.getPixel(x+1,y).v) +
                 (-1*img.getPixel(x+1,y+1).v);
     return sobel > threshold ? sobel : 0;
   }
static int Sobel::maximumHorizontalEdge (const greyImage & img, int y, int xStart, int xEnd, int threshold, int fconst greyImage &, int, int, int) inline static
Definition at line 97 of file sobel.h.
References validImagePixel(), and role._GoToPoint::x.
   {
     int resX = -1;
     int maxEdge(0);
     for(int x=xStart; x<=xEnd; ++x)
     {
       if (!validImagePixel(img, x, y)) continue;
       int currentEdge = f(img,x,y,threshold);
       if(currentEdge > maxEdge)
       {
         maxEdge = currentEdge;
         resX = x;
       }
     }
     return resX;
   }
static int Sobel::maximumVerticalEdge (const greyImage & img, int x, int yStart, int yEnd, int threshold, int fconst greyImage &, int, int, int) inline static
Definition at line 117 of file sobel.h.
References validImagePixel(), and role._GoToPoint::y.
   {
     int resY = -1;
     int maxEdge(0);
     for(int y=yStart; y<=yEnd; ++y)
     {
       if (!validImagePixel(img, x, y)) continue;
       int currentEdge = f(img,x,y,threshold);
       if(currentEdge > maxEdge)
       {
         maxEdge = currentEdge;
         resY = y;
       }
     }
     return resY;
   }
static bool Sobel::validImagePixel (const greyImage & img, const int x, const int y) inline static
Definition at line 42 of file sobel.h.
Referenced by centerOfHorizontalLine(), centerOfLine(), centerOfVerticalLine(), maximumHorizontalEdge(), and maximumVerticalEdge().
{
     return (x > 0 && y > 0 &&
         x < img.getWidth() - 1 && y < img.getHeight() - 1);
   }
static int Sobel::verticalBrighter (const greyImage & img, int x, int y, int threshold) inline static
Definition at line 72 of file sobel.h.
Referenced by centerOfHorizontalLine(), centerOfLine(), and PluginVisualize::DrawSobelImage().
   {
     int sobel = (-1*img.getPixel(x-1,y-1).v) +
                 (-2*img.getPixel(x,y-1).v) +
                 (-1*img.getPixel(x-1,y-1).v) +
                 ( 1*img.getPixel(x-1,y+1).v) +
                 ( 2*img.getPixel(x,y+1).v) +
                 ( 1*img.getPixel(x+1,y+1).v);
     return sobel > threshold ? sobel : 0;
   }
static int Sobel::verticalDarker (const greyImage & img, int x, int y, int threshold) inline static
Definition at line 84 of file sobel.h.
Referenced by centerOfHorizontalLine(), centerOfLine(), and PluginVisualize::DrawSobelImage().
   {
     int sobel = ( 1*img.getPixel(x-1,y-1).v) +
                 ( 2*img.getPixel(x,y-1).v) +
                 ( 1*img.getPixel(x-1,y-1).v) +
                 (-1*img.getPixel(x-1,y+1).v) +
                 (-2*img.getPixel(x,y+1).v) +
                 (-1*img.getPixel(x+1,y+1).v);
     return sobel > threshold ? sobel : 0;
   }
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/sobel.h