Documentation: CMVision::RunList Class Reference
CMVision::RunList Class Reference
#include <cmvision_region.h>
Public Member Functions
RunList (int _max_runs)
void setUsedRuns (int runs)
int getUsedRuns ()
~RunList ()
Run * getRunArrayPointer ()
int getMaxRuns ()
Private Attributes
Run * runs
int max_runs
int used_runs
Detailed Description
Definition at line 44 of file cmvision_region.h.
Constructor & Destructor Documentation
CMVision::RunList::RunList (int _max_runs) inline
Definition at line 50 of file cmvision_region.h.
{
     runs=new Run[_max_runs];
     max_runs=_max_runs;
     used_runs=0;
   }
CMVision::RunList::~RunList () inline
Definition at line 61 of file cmvision_region.h.
              {
     delete[] runs;
   }
Member Function Documentation
int CMVision::RunList::getMaxRuns () inline
Definition at line 68 of file cmvision_region.h.
Referenced by CMVision::RegionProcessing::encodeRuns(), and PluginRunlengthEncode::process().
                    {
     return max_runs;
   }
Run* CMVision::RunList::getRunArrayPointer () inline
Definition at line 65 of file cmvision_region.h.
Referenced by CMVision::RegionProcessing::connectComponents(), CMVision::RegionProcessing::encodeRuns(), and CMVision::RegionProcessing::extractRegions().
{
     return runs;
   }
int CMVision::RunList::getUsedRuns () inline
Definition at line 58 of file cmvision_region.h.
Referenced by CMVision::RegionProcessing::connectComponents(), CMVision::RegionProcessing::extractRegions(), and PluginRunlengthEncode::process().
                     {
     return used_runs;
   }
void CMVision::RunList::setUsedRuns (int runs) inline
Definition at line 55 of file cmvision_region.h.
Referenced by CMVision::RegionProcessing::encodeRuns().
{
     used_runs=runs;
   }
Field Documentation
int CMVision::RunList::max_runs private
Definition at line 47 of file cmvision_region.h.
Run* CMVision::RunList::runs private
Definition at line 46 of file cmvision_region.h.
int CMVision::RunList::used_runs private
Definition at line 48 of file cmvision_region.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/cmvision/cmvision_region.h