Documentation: RoboCupSSLServer Class Reference
RoboCupSSLServer Class Reference
#include <robocup_ssl_server.h>
Public Member Functions
RoboCupSSLServer (QObject *parent=0, const quint16 &port=10002, const string &net_address="224.5.23.2", const string &net_interface="")
~RoboCupSSLServer ()
bool send (const SSL_WrapperPacket &packet)
bool send (const SSL_DetectionFrame &frame)
bool send (const SSL_GeometryData &geometry)
void change_port (const quint16 &port)
void change_address (const string &net_address)
void change_interface (const string &net_interface)
RoboCupSSLServer (int port, string net_ref_address, string net_ref_interface="")
~RoboCupSSLServer ()
bool open ()
void close ()
template<typename T >
bool sendWrapperPacket (const T &packet)
bool send (const SSL_DetectionFrame &frame)
bool send (const SSL_GeometryData &geometry)
bool sendLegacyMessage (const RoboCup2014Legacy::Geometry::SSL_GeometryData &geometry)
bool sendLegacyMessage (const SSL_DetectionFrame &frame)
Protected Attributes
QUdpSocket * _socket
QMutex mutex
quint16 _port
QHostAddress * _net_address
QNetworkInterface * _net_interface
Net::UDP mc
int _port
string _net_address
string _net_interface
Friends
class MultiStackRoboCupSSL
Detailed Description
Author
Stefan Zickler
Definition at line 36 of file robocup_ssl_server.h.
Constructor & Destructor Documentation
RoboCupSSLServer::RoboCupSSLServer (QObject * parent = 0, const quint16 & port = 10002, const string & net_address = "224.5.23.2", const string & net_interface = "")
Definition at line 29 of file robocup_ssl_server.cpp.
References _socket.
                                                                                                                                :
     _socket(new QUdpSocket(parent)),
     _port(port),
     _net_address(new QHostAddress(QString(net_address.c_str()))),
     _net_interface(new QNetworkInterface(QNetworkInterface::interfaceFromName(QString(net_interface.c_str()))))
 {
     _socket->setSocketOption(QAbstractSocket::MulticastTtlOption, 1);
 }
RoboCupSSLServer::~RoboCupSSLServer ()
Definition at line 38 of file robocup_ssl_server.cpp.
References _net_address, _net_interface, _socket, and mutex.
Referenced by RoboCupSSLServer().
 {
     mutex.lock();
     mutex.unlock();
     delete _socket;
     delete _net_address;
     delete _net_interface;
 }
RoboCupSSLServer::RoboCupSSLServer (int port, string net_ref_address, string net_ref_interface = "")
Definition at line 24 of file robocup_ssl_server.cpp.
References _net_address, _net_interface, _port, port(), and ~RoboCupSSLServer().
 {
   _port=port;
   _net_address=net_address;
   _net_interface=net_interface;
 }
RoboCupSSLServer::~RoboCupSSLServer ()
Member Function Documentation
void RoboCupSSLServer::change_address (const string & net_address)
Definition at line 52 of file robocup_ssl_server.cpp.
References _net_address.
Referenced by MainWindow::reconnectVisionSocket().
 {
     delete _net_address;
     _net_address = new QHostAddress(QString(net_address.c_str()));
 }
void RoboCupSSLServer::change_interface (const string & net_interface)
Definition at line 58 of file robocup_ssl_server.cpp.
References _net_interface.
 {
     delete _net_interface;
     _net_interface = new QNetworkInterface(QNetworkInterface::interfaceFromName(QString(net_interface.c_str())));
 }
void RoboCupSSLServer::change_port (const quint16 & port)
Definition at line 47 of file robocup_ssl_server.cpp.
References _port, and port().
Referenced by MainWindow::reconnectVisionSocket().
 {
     _port = port;
 }
void RoboCupSSLServer::close ()
Definition at line 39 of file robocup_ssl_server.cpp.
References Net::UDP::close(), and mc.
Referenced by open(), and MultiStackRoboCupSSL::UpdateServerSettings().
{
   mc.close();
 }
bool RoboCupSSLServer::open ()
Definition at line 43 of file robocup_ssl_server.cpp.
References _net_address, _net_interface, _port, Net::UDP::addMulticast(), close(), bot_comm::frame, GetTimeSec(), mc, mutex, Net::UDP::open(), send(), Net::Address::setAny(), and Net::Address::setHost().
Referenced by MultiStackRoboCupSSL::UpdateServerSettings().
{
   close();
   if(!mc.open(_port,true,true)) {
     fprintf(stderr,"Unable to open UDP network port: %d\n",_port);
     fflush(stderr);
     return(false);
   }
   Net::Address multiaddr,interface;
   multiaddr.setHost(_net_address.c_str(),_port);
   if(_net_interface.length() > 0){
     interface.setHost(_net_interface.c_str(),_port);
   }else{
     interface.setAny();
   }
   if(!mc.addMulticast(multiaddr,interface)) {
     fprintf(stderr,"Unable to setup UDP multicast\n");
     fflush(stderr);
     return(false);
   }
   return(true);
 }
bool RoboCupSSLServer::send (const SSL_WrapperPacket & packet)
Definition at line 64 of file robocup_ssl_server.cpp.
References _net_address, _port, _socket, logStatus(), and mutex.
Referenced by open(), PluginSSLNetworkOutput::process(), send(), PluginPublishGeometry::sendGeometry(), and SSLWorld::sendVisionBuffer().
 {
     QByteArray datagram;
     datagram.resize(packet.ByteSize());
     bool success = packet.SerializeToArray(datagram.data(), datagram.size());
     if(!success) {
         //TODO: print useful info
         logStatus(QString("Serializing packet to array failed."), QColor("red"));
         return false;
     }
     mutex.lock();
     quint64 bytes_sent = _socket->writeDatagram(datagram, *_net_address, _port);
     mutex.unlock();
     if (bytes_sent != datagram.size()) {
         logStatus(QString("Sending UDP datagram failed (maybe too large?). Size was: %1 byte(s).").arg(datagram.size()), QColor("red"));
         return false;
     }
     return true;
 }
bool RoboCupSSLServer::send (const SSL_DetectionFrame & frame)
Definition at line 87 of file robocup_ssl_server.cpp.
References send().
 {
     SSL_WrapperPacket pkt;
     SSL_DetectionFrame * nframe = pkt.mutable_detection();
     nframe->CopyFrom(frame);
     return send(pkt);
 }
bool RoboCupSSLServer::send (const SSL_GeometryData & geometry)
Definition at line 95 of file robocup_ssl_server.cpp.
References send().
 {
     SSL_WrapperPacket pkt;
     SSL_GeometryData * gdata = pkt.mutable_geometry();
     gdata->CopyFrom(geometry);
     return send(pkt);
 }
bool RoboCupSSLServer::send (const SSL_DetectionFrame & frame)
bool RoboCupSSLServer::send (const SSL_GeometryData & geometry)
bool RoboCupSSLServer::sendLegacyMessage (const RoboCup2014Legacy::Geometry::SSL_GeometryData & geometry)
Definition at line 99 of file robocup_ssl_server.cpp.
References mutex.
Referenced by PluginLegacySSLNetworkOutput::process(), and PluginLegacyPublishGeometry::sendGeometry().
{
   RoboCup2014Legacy::Wrapper::SSL_WrapperPacket pkt;
   RoboCup2014Legacy::Geometry::SSL_GeometryData * gdata = pkt.mutable_geometry();
   gdata->CopyFrom(geometry);
   mutex.lock();
   bool ret = sendWrapperPacket<RoboCup2014Legacy::Wrapper::SSL_WrapperPacket>(pkt);
   mutex.unlock();
   return ret;
 }
bool RoboCupSSLServer::sendLegacyMessage (const SSL_DetectionFrame & frame)
Definition at line 88 of file robocup_ssl_server.cpp.
References GetTimeSec(), and mutex.
{
   RoboCup2014Legacy::Wrapper::SSL_WrapperPacket pkt;
   SSL_DetectionFrame * nframe = pkt.mutable_detection();
   nframe->CopyFrom(frame);
   mutex.lock();
   nframe->set_t_sent(GetTimeSec());
   bool ret = sendWrapperPacket<RoboCup2014Legacy::Wrapper::SSL_WrapperPacket>(pkt);
   mutex.unlock();
   return ret;
 }
template<typename T > bool RoboCupSSLServer::sendWrapperPacket (const T & packet) inline
Definition at line 53 of file robocup_ssl_server.h.
References _port, bot_comm::frame, Net::UDP::send(), and Net::Address::setHost().
{
       string buffer;
       packet.SerializeToString(&buffer);
       Net::Address multiaddr;
       multiaddr.setHost(_net_address.c_str(),_port);
       bool result;
       result=mc.send(buffer.c_str(),buffer.length(),multiaddr);
       if (result==false) {
         perror("Sendto Error");
         fprintf(stderr,
                 "Sending UDP datagram to %s:%d failed (maybe too large?). "
                 "Size was: %zu byte(s)\n",
                 _net_address.c_str(),
                 _port,
                 buffer.length());
       }
       return(result);
     }
Friends And Related Function Documentation
MultiStackRoboCupSSL friend
Definition at line 38 of file robocup_ssl_server.h.
Field Documentation
string RoboCupSSLServer::_net_address protected
Definition at line 41 of file robocup_ssl_server.h.
QHostAddress* RoboCupSSLServer::_net_address protected
Definition at line 58 of file robocup_ssl_server.h.
Referenced by change_address(), open(), RoboCupSSLServer(), send(), MultiStackRoboCupSSL::UpdateServerSettings(), and ~RoboCupSSLServer().
string RoboCupSSLServer::_net_interface protected
Definition at line 42 of file robocup_ssl_server.h.
QNetworkInterface* RoboCupSSLServer::_net_interface protected
Definition at line 59 of file robocup_ssl_server.h.
Referenced by change_interface(), open(), RoboCupSSLServer(), MultiStackRoboCupSSL::UpdateServerSettings(), and ~RoboCupSSLServer().
int RoboCupSSLServer::_port protected
Definition at line 40 of file robocup_ssl_server.h.
quint16 RoboCupSSLServer::_port protected
Definition at line 57 of file robocup_ssl_server.h.
Referenced by change_port(), open(), RoboCupSSLServer(), send(), and MultiStackRoboCupSSL::UpdateServerSettings().
QUdpSocket* RoboCupSSLServer::_socket protected
Definition at line 55 of file robocup_ssl_server.h.
Referenced by RoboCupSSLServer(), send(), and ~RoboCupSSLServer().
Net::UDP RoboCupSSLServer::mc protected
Definition at line 38 of file robocup_ssl_server.h.
Referenced by close(), and open().
QMutex RoboCupSSLServer::mutex protected
Definition at line 56 of file robocup_ssl_server.h.
Referenced by open(), send(), sendLegacyMessage(), MultiStackRoboCupSSL::UpdateServerSettings(), and ~RoboCupSSLServer().
The documentation for this class was generated from the following files:
grSim/include/net/robocup_ssl_server.h
grSim/src/net/robocup_ssl_server.cpp