Documentation: grsim_comm/include/proto/grSim_Commands.pb.cc File Reference
grSim_Commands.pb.cc File Reference
#include "grSim_Commands.pb.h"
#include <algorithm>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
Data Structures
class grSim_Robot_CommandDefaultTypeInternal
class grSim_CommandsDefaultTypeInternal
struct StaticDescriptorInitializer_grSim_5fCommands_2eproto
Namespaces
anonymous_namespace{grSim_Commands.pb.cc}
Macros
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Functions
const ::google::protobuf::uint32 * protobuf_Offsets_grSim_5fCommands_2eproto () GOOGLE_ATTRIBUTE_COLD
void anonymous_namespace{grSim_Commands.pb.cc}::protobuf_AssignDescriptors ()
void anonymous_namespace{grSim_Commands.pb.cc}::protobuf_AssignDescriptorsOnce ()
void anonymous_namespace{grSim_Commands.pb.cc}::protobuf_RegisterTypes (const ::std::string &) GOOGLE_ATTRIBUTE_COLD
void protobuf_ShutdownFile_grSim_5fCommands_2eproto ()
void protobuf_InitDefaults_grSim_5fCommands_2eproto_impl ()
void protobuf_InitDefaults_grSim_5fCommands_2eproto ()
void protobuf_AddDesc_grSim_5fCommands_2eproto_impl ()
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_grSim_5fCommands_2eproto_once_)
void protobuf_AddDesc_grSim_5fCommands_2eproto ()
Variables
grSim_Robot_CommandDefaultTypeInternal _grSim_Robot_Command_default_instance_
grSim_CommandsDefaultTypeInternal _grSim_Commands_default_instance_
::google::protobuf::Metadata anonymous_namespace{grSim_Commands.pb.cc}::file_level_metadata [2]
static const ::google::protobuf::internal::MigrationSchema schemas []
static const ::google::protobuf::internal::DefaultInstanceData file_default_instances []
struct StaticDescriptorInitializer_grSim_5fCommands_2eproto static_descriptor_initializer_grSim_5fCommands_2eproto_
Macro Definition Documentation
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Referenced by grSim_Robot_Command::MergePartialFromCodedStream(), and grSim_Commands::MergePartialFromCodedStream().
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
Definition at line 4 of file grSim_Commands.pb.cc.
Function Documentation
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_grSim_5fCommands_2eproto_once_)
Referenced by protobuf_messages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto::AddDescriptors(), protobuf_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto::AddDescriptors(), protobuf_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto::InitDefaultsSSL_GeometryData(), protobuf_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto::InitDefaultsSSL_GeometryFieldSize(), protobuf_messages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto::InitDefaultsSSL_WrapperPacket(), protobuf_AddDesc_grSim_5fCommands_2eproto_impl(), protobuf_messages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto::protobuf_AssignDescriptorsOnce(), anonymous_namespace{grSim_Commands.pb.cc}::protobuf_AssignDescriptorsOnce(), protobuf_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto::protobuf_AssignDescriptorsOnce(), and protobuf_InitDefaults_grSim_5fCommands_2eproto().
void protobuf_AddDesc_grSim_5fCommands_2eproto ()
Definition at line 150 of file grSim_Commands.pb.cc.
References protobuf_AddDesc_grSim_5fCommands_2eproto_impl().
Referenced by protobuf_AddDesc_grSim_5fPacket_2eproto_impl(), anonymous_namespace{grSim_Commands.pb.cc}::protobuf_AssignDescriptors(), and StaticDescriptorInitializer_grSim_5fCommands_2eproto::StaticDescriptorInitializer_grSim_5fCommands_2eproto().
{
   ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_grSim_5fCommands_2eproto_once_,
                  &protobuf_AddDesc_grSim_5fCommands_2eproto_impl);
 }
void protobuf_AddDesc_grSim_5fCommands_2eproto_impl ()
Definition at line 128 of file grSim_Commands.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), protobuf_InitDefaults_grSim_5fCommands_2eproto(), anonymous_namespace{grSim_Commands.pb.cc}::protobuf_RegisterTypes(), and protobuf_ShutdownFile_grSim_5fCommands_2eproto().
Referenced by protobuf_AddDesc_grSim_5fCommands_2eproto().
{
   protobuf_InitDefaults_grSim_5fCommands_2eproto();
   static const char descriptor[] = {
       "\n\024grSim_Commands.proto\"\352\001\n\023grSim_Robot_C"
       "ommand\022\n\n\002id\030\001 \002(\r\022\022\n\nkickspeedx\030\002 \002(\002\022\022"
       "\n\nkickspeedz\030\003 \002(\002\022\022\n\nveltangent\030\004 \002(\002\022\021"
       "\n\tvelnormal\030\005 \002(\002\022\022\n\nvelangular\030\006 \002(\002\022\017\n"
       "\007spinner\030\007 \002(\010\022\023\n\013wheelsspeed\030\010 \002(\010\022\016\n\006w"
       "heel1\030\t \001(\002\022\016\n\006wheel2\030\n \001(\002\022\016\n\006wheel3\030\013 "
       "\001(\002\022\016\n\006wheel4\030\014 \001(\002\"g\n\016grSim_Commands\022\021\n"
       "\ttimestamp\030\001 \002(\001\022\024\n\014isteamyellow\030\002 \002(\010\022,"
       "\n\016robot_commands\030\003 \003(\0132\024.grSim_Robot_Com"
       "mand"
   };
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
       descriptor, 364);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "grSim_Commands.proto", &protobuf_RegisterTypes);
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_grSim_5fCommands_2eproto);
 }
void protobuf_InitDefaults_grSim_5fCommands_2eproto ()
Definition at line 124 of file grSim_Commands.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), and protobuf_InitDefaults_grSim_5fCommands_2eproto_impl().
Referenced by grSim_Robot_Command::default_instance(), grSim_Commands::default_instance(), grSim_Commands::grSim_Commands(), grSim_Robot_Command::grSim_Robot_Command(), protobuf_AddDesc_grSim_5fCommands_2eproto_impl(), and protobuf_InitDefaults_grSim_5fPacket_2eproto_impl().
{
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
   ::google::protobuf::GoogleOnceInit(&once, &protobuf_InitDefaults_grSim_5fCommands_2eproto_impl);
 }
void protobuf_InitDefaults_grSim_5fCommands_2eproto_impl ()
Definition at line 116 of file grSim_Commands.pb.cc.
Referenced by protobuf_InitDefaults_grSim_5fCommands_2eproto().
{
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::google::protobuf::internal::InitProtobufDefaults();
   _grSim_Robot_Command_default_instance_.DefaultConstruct();
   _grSim_Commands_default_instance_.DefaultConstruct();
 }
const ::google::protobuf::uint32 * protobuf_Offsets_grSim_5fCommands_2eproto ()
Definition at line 32 of file grSim_Commands.pb.cc.
Referenced by anonymous_namespace{grSim_Commands.pb.cc}::protobuf_AssignDescriptors().
{
   static const ::google::protobuf::uint32 offsets[] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, id_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, kickspeedx_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, kickspeedz_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, veltangent_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, velnormal_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, velangular_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, spinner_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, wheelsspeed_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, wheel1_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, wheel2_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, wheel3_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Robot_Command, wheel4_),
     0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Commands, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Commands, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Commands, timestamp_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Commands, isteamyellow_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(grSim_Commands, robot_commands_),
     0,
     1,
     2,
   };
   return offsets;
 }
void protobuf_ShutdownFile_grSim_5fCommands_2eproto ()
Definition at line 109 of file grSim_Commands.pb.cc.
References anonymous_namespace{grSim_Commands.pb.cc}::file_level_metadata.
Referenced by protobuf_AddDesc_grSim_5fCommands_2eproto_impl().
{
   _grSim_Robot_Command_default_instance_.Shutdown();
   delete file_level_metadata[0].reflection;
   _grSim_Commands_default_instance_.Shutdown();
   delete file_level_metadata[1].reflection;
 }
Variable Documentation
grSim_CommandsDefaultTypeInternal _grSim_Commands_default_instance_
Definition at line 22 of file grSim_Commands.pb.cc.
Referenced by grSim_Commands::internal_default_instance().
grSim_Robot_CommandDefaultTypeInternal _grSim_Robot_Command_default_instance_
Definition at line 20 of file grSim_Commands.pb.cc.
Referenced by grSim_Robot_Command::internal_default_instance().
const ::google::protobuf::internal::DefaultInstanceData file_default_instances[] static
Initial value:
= {
  {reinterpret_cast<const ::google::protobuf::Message*>(&_grSim_Robot_Command_default_instance_), NULL},
  {reinterpret_cast<const ::google::protobuf::Message*>(&_grSim_Commands_default_instance_), NULL},
}
Definition at line 81 of file grSim_Commands.pb.cc.
Referenced by anonymous_namespace{grSim_Commands.pb.cc}::protobuf_AssignDescriptors().
const ::google::protobuf::internal::MigrationSchema schemas[] static
Initial value:
= {
  { 0, 16, sizeof(grSim_Robot_Command)},
  { 28, 35, sizeof(grSim_Commands)},
}
Definition at line 76 of file grSim_Commands.pb.cc.
Referenced by protobuf_messages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto::protobuf_AssignDescriptors(), anonymous_namespace{grSim_Commands.pb.cc}::protobuf_AssignDescriptors(), and protobuf_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto::protobuf_AssignDescriptors().
struct StaticDescriptorInitializer_grSim_5fCommands_2eproto static_descriptor_initializer_grSim_5fCommands_2eproto_
Referenced by StaticDescriptorInitializer_grSim_5fCommands_2eproto::StaticDescriptorInitializer_grSim_5fCommands_2eproto().