Documentation: anonymous_namespace{sslDebug_Data.pb.cc} Namespace Reference
anonymous_namespace{sslDebug_Data.pb.cc} Namespace Reference
Functions
void protobuf_AssignDescriptors ()
void protobuf_AssignDescriptorsOnce ()
void protobuf_RegisterTypes (const ::std::string &) GOOGLE_ATTRIBUTE_COLD
Variables
::google::protobuf::Metadata file_level_metadata [5]
Function Documentation
void anonymous_namespace{sslDebug_Data.pb.cc}::protobuf_AssignDescriptors ()
Definition at line 136 of file sslDebug_Data.pb.cc.
References file_default_instances, file_level_metadata, protobuf_AddDesc_sslDebug_5fData_2eproto(), protobuf_Offsets_sslDebug_5fData_2eproto(), and schemas.
Referenced by protobuf_AssignDescriptorsOnce().
{
   protobuf_AddDesc_sslDebug_5fData_2eproto();
   ::google::protobuf::MessageFactory* factory = NULL;
   AssignDescriptors(
       "sslDebug_Data.proto", schemas, file_default_instances, protobuf_Offsets_sslDebug_5fData_2eproto(), factory,
       file_level_metadata, NULL, NULL);
 }
void anonymous_namespace{sslDebug_Data.pb.cc}::protobuf_AssignDescriptorsOnce ()
Definition at line 144 of file sslDebug_Data.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), protobuf_AssignDescriptors(), and protobuf_RegisterTypes().
Referenced by sslDebug_Data::descriptor(), Debug_Circle::descriptor(), Debug_Line::descriptor(), Debug_AdjustBot::descriptor(), Debug_AdjustBall::descriptor(), sslDebug_Data::GetMetadata(), Debug_Circle::GetMetadata(), Debug_Line::GetMetadata(), Debug_AdjustBot::GetMetadata(), Debug_AdjustBall::GetMetadata(), and protobuf_RegisterTypes().
{
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
   ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
 }
void anonymous_namespace{sslDebug_Data.pb.cc}::protobuf_RegisterTypes (const ::std::string &)
Definition at line 150 of file sslDebug_Data.pb.cc.
References file_level_metadata, and protobuf_AssignDescriptorsOnce().
Referenced by protobuf_AddDesc_sslDebug_5fData_2eproto_impl(), and protobuf_AssignDescriptorsOnce().
{
   protobuf_AssignDescriptorsOnce();
   ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
 }
Variable Documentation
::google::protobuf::Metadata anonymous_namespace{sslDebug_Data.pb.cc}::file_level_metadata[5]
Definition at line 32 of file sslDebug_Data.pb.cc.
Referenced by sslDebug_Data::descriptor(), Debug_Circle::descriptor(), Debug_Line::descriptor(), Debug_AdjustBot::descriptor(), Debug_AdjustBall::descriptor(), sslDebug_Data::GetMetadata(), Debug_Circle::GetMetadata(), Debug_Line::GetMetadata(), Debug_AdjustBot::GetMetadata(), Debug_AdjustBall::GetMetadata(), protobuf_AssignDescriptors(), protobuf_RegisterTypes(), and protobuf_ShutdownFile_sslDebug_5fData_2eproto().