Documentation: GUI.interfacePath.Ui_MainWindow Class Reference
GUI.interfacePath.Ui_MainWindow Class Reference
Public Member Functions
def setupUi (self, MainWindow)
def retranslateUi (self, MainWindow)
Data Fields
centralwidget
graphicsView
GoToBall
textBotId
bot_id
comboBox
GoToBallFsm
GoInTriangle
menubar
menuDIFFERENT_RRT
statusbar
actionRRT_CONNECT
actionRRTStar
actionRRT
Detailed Description
Definition at line 25 of file interfacePath.py.
Member Function Documentation
def GUI.interfacePath.Ui_MainWindow.retranslateUi (self, MainWindow)
Definition at line 85 of file interfacePath.py.
References GUI.interfacePath._translate().
     def retranslateUi(self, MainWindow):
         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
         self.GoToBall.setText(_translate("MainWindow", "GoToBall", None))
         self.bot_id.setText(_translate("MainWindow", "BotId", None))
         self.comboBox.setItemText(0, _translate("MainWindow", "PRM", None))
         self.comboBox.setItemText(1, _translate("MainWindow", "RRT", None))
         self.comboBox.setItemText(2, _translate("MainWindow", "RRTConnect", None))
         self.comboBox.setItemText(3, _translate("MainWindow", "RRTStar", None))
         self.comboBox.setItemText(4, _translate("MainWindow", "LBTRRT", None))
         self.comboBox.setItemText(5, _translate("MainWindow", "LazyRRT", None))
         self.comboBox.setItemText(6, _translate("MainWindow", "TRRT", None))
         self.comboBox.setItemText(7, _translate("MainWindow", "pRRT", None))
         self.comboBox.setItemText(8, _translate("MainWindow", "EST", None))
         self.GoToBallFsm.setText(_translate("MainWindow", "GoToBall(FSM)", None))
         self.GoInTriangle.setText(_translate("MainWindow", "GoInTriangle", None))
         self.menuDIFFERENT_RRT.setTitle(_translate("MainWindow", "DIFFERENT_RRT", None))
         self.actionRRT_CONNECT.setText(_translate("MainWindow", "RRT_CONNECT", None))
         self.actionRRTStar.setText(_translate("MainWindow", "RRT_STAR", None))
         self.actionRRT.setText(_translate("MainWindow", "RRT", None))
def GUI.interfacePath.Ui_MainWindow.setupUi (self, MainWindow)
Definition at line 26 of file interfacePath.py.
References GUI.interfacePath._fromUtf8.
Referenced by GUI.self_RRT.MainWindow.__init__(), and GUI.ompl_gui.MainWindow.__init__().
     def setupUi(self, MainWindow):
         MainWindow.setObjectName(_fromUtf8("MainWindow"))
         MainWindow.resize(1126, 653)
         self.centralwidget = QtGui.QWidget(MainWindow)
         self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
         self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
         self.graphicsView.setGeometry(QtCore.QRect(0, 0, 600, 400))
         self.graphicsView.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 0);\n"
 "background-color: rgb(0, 85, 0);"))
         self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
         self.GoToBall = QtGui.QPushButton(self.centralwidget)
         self.GoToBall.setGeometry(QtCore.QRect(920, 80, 99, 27))
         self.GoToBall.setObjectName(_fromUtf8("GoToBall"))
         self.textBotId = QtGui.QLineEdit(self.centralwidget)
         self.textBotId.setGeometry(QtCore.QRect(790, 80, 113, 27))
         self.textBotId.setObjectName(_fromUtf8("textBotId"))
         self.bot_id = QtGui.QLabel(self.centralwidget)
         self.bot_id.setGeometry(QtCore.QRect(740, 90, 41, 17))
         self.bot_id.setObjectName(_fromUtf8("bot_id"))
         self.comboBox = QtGui.QComboBox(self.centralwidget)
         self.comboBox.setGeometry(QtCore.QRect(740, 30, 161, 27))
         self.comboBox.setObjectName(_fromUtf8("comboBox"))
         self.comboBox.addItem(_fromUtf8(""))
         self.comboBox.addItem(_fromUtf8(""))
         self.comboBox.addItem(_fromUtf8(""))
         self.comboBox.addItem(_fromUtf8(""))
         self.comboBox.addItem(_fromUtf8(""))
         self.comboBox.addItem(_fromUtf8(""))
         self.comboBox.addItem(_fromUtf8(""))
         self.comboBox.addItem(_fromUtf8(""))
         self.comboBox.addItem(_fromUtf8(""))
         self.GoToBallFsm = QtGui.QPushButton(self.centralwidget)
         self.GoToBallFsm.setGeometry(QtCore.QRect(920, 110, 121, 27))
         self.GoToBallFsm.setObjectName(_fromUtf8("GoToBallFsm"))
         self.GoInTriangle = QtGui.QPushButton(self.centralwidget)
         self.GoInTriangle.setGeometry(QtCore.QRect(790, 160, 99, 27))
         self.GoInTriangle.setObjectName(_fromUtf8("GoInTriangle"))
         MainWindow.setCentralWidget(self.centralwidget)
         self.menubar = QtGui.QMenuBar(MainWindow)
         self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 25))
         self.menubar.setNativeMenuBar(False)
         self.menubar.setObjectName(_fromUtf8("menubar"))
         self.menuDIFFERENT_RRT = QtGui.QMenu(self.menubar)
         self.menuDIFFERENT_RRT.setObjectName(_fromUtf8("menuDIFFERENT_RRT"))
         MainWindow.setMenuBar(self.menubar)
         self.statusbar = QtGui.QStatusBar(MainWindow)
         self.statusbar.setObjectName(_fromUtf8("statusbar"))
         MainWindow.setStatusBar(self.statusbar)
         self.actionRRT_CONNECT = QtGui.QAction(MainWindow)
         self.actionRRT_CONNECT.setObjectName(_fromUtf8("actionRRT_CONNECT"))
         self.actionRRTStar = QtGui.QAction(MainWindow)
         self.actionRRTStar.setObjectName(_fromUtf8("actionRRTStar"))
         self.actionRRT = QtGui.QAction(MainWindow)
         self.actionRRT.setObjectName(_fromUtf8("actionRRT"))
         self.menubar.addAction(self.menuDIFFERENT_RRT.menuAction())
         self.retranslateUi(MainWindow)
         QtCore.QMetaObject.connectSlotsByName(MainWindow)
Field Documentation
GUI.interfacePath.Ui_MainWindow.actionRRT
Definition at line 78 of file interfacePath.py.
GUI.interfacePath.Ui_MainWindow.actionRRT_CONNECT
Definition at line 74 of file interfacePath.py.
GUI.interfacePath.Ui_MainWindow.actionRRTStar
Definition at line 76 of file interfacePath.py.
GUI.interfacePath.Ui_MainWindow.bot_id
Definition at line 42 of file interfacePath.py.
Referenced by tactics._Goalie__.TGoalie.execute(), and tactics._Goalie__.TGoalie.getState().
GUI.interfacePath.Ui_MainWindow.centralwidget
Definition at line 29 of file interfacePath.py.
GUI.interfacePath.Ui_MainWindow.comboBox
Definition at line 45 of file interfacePath.py.
GUI.interfacePath.Ui_MainWindow.GoInTriangle
Definition at line 60 of file interfacePath.py.
GUI.interfacePath.Ui_MainWindow.GoToBall
Definition at line 36 of file interfacePath.py.
GUI.interfacePath.Ui_MainWindow.GoToBallFsm
Definition at line 57 of file interfacePath.py.
GUI.interfacePath.Ui_MainWindow.graphicsView
Definition at line 31 of file interfacePath.py.
GUI.interfacePath.Ui_MainWindow.menubar
Definition at line 64 of file interfacePath.py.
GUI.interfacePath.Ui_MainWindow.menuDIFFERENT_RRT
Definition at line 68 of file interfacePath.py.
GUI.interfacePath.Ui_MainWindow.statusbar
Definition at line 71 of file interfacePath.py.
GUI.interfacePath.Ui_MainWindow.textBotId
Definition at line 39 of file interfacePath.py.
The documentation for this class was generated from the following file:
GUI/interfacePath.py