Documentation: RGB Namespace Reference
RGB Namespace Reference
Variables
static const rgb Black = rgb(0, 0, 0)
static const rgb Blue = rgb(0, 0,255)
static const rgb Green = rgb(0,255, 0)
static const rgb Red = rgb(255, 0, 0)
static const rgb White = rgb(255,255,255)
static const rgb Gray = rgb(128,128,128)
static const rgb Cyan = rgb(0,255,255)
static const rgb Pink = rgb(255, 0,255)
static const rgb Yellow = rgb(255,255, 0)
static const rgb Orange = rgb(255,128, 0)
static const rgb MidBlue = rgb(0, 0,192)
static const rgb MidGreen = rgb(0,192, 0)
static const rgb MidRed = rgb(192, 0, 0)
static const rgb DarkBlue = rgb(0, 0,128)
static const rgb DarkGreen = rgb(0,128, 0)
static const rgb DarkRed = rgb(128, 0, 0)
static const rgb Purple = rgb(128, 0,128)
static const rgb DarkGray = rgb(64, 64, 64)
Variable Documentation
const rgb RGB::Black = rgb(0, 0, 0) static
Definition at line 454 of file colors.h.
Referenced by CaptureGenerator::getFrame(), LUT3D::loadBlackWhite(), and LUT3D::loadRoboCupChannels().
const rgb RGB::Blue = rgb(0, 0,255) static
Definition at line 455 of file colors.h.
Referenced by CaptureGenerator::getFrame(), and LUT3D::loadRoboCupChannels().
const rgb RGB::Cyan = rgb(0,255,255) static
Definition at line 461 of file colors.h.
Referenced by CaptureGenerator::getFrame(), and LUT3D::loadRoboCupChannels().
const rgb RGB::DarkBlue = rgb(0, 0,128) static
Definition at line 470 of file colors.h.
const rgb RGB::DarkGray = rgb(64, 64, 64) static
Definition at line 474 of file colors.h.
const rgb RGB::DarkGreen = rgb(0,128, 0) static
Definition at line 471 of file colors.h.
Referenced by LUT3D::loadRoboCupChannels().
const rgb RGB::DarkRed = rgb(128, 0, 0) static
Definition at line 472 of file colors.h.
const rgb RGB::Gray = rgb(128,128,128) static
Definition at line 459 of file colors.h.
const rgb RGB::Green = rgb(0,255, 0) static
Definition at line 456 of file colors.h.
Referenced by CaptureGenerator::getFrame(), and LUT3D::loadRoboCupChannels().
const rgb RGB::MidBlue = rgb(0, 0,192) static
Definition at line 466 of file colors.h.
const rgb RGB::MidGreen = rgb(0,192, 0) static
Definition at line 467 of file colors.h.
const rgb RGB::MidRed = rgb(192, 0, 0) static
Definition at line 468 of file colors.h.
const rgb RGB::Orange = rgb(255,128, 0) static
Definition at line 464 of file colors.h.
Referenced by LUT3D::loadRoboCupChannels().
const rgb RGB::Pink = rgb(255, 0,255) static
Definition at line 462 of file colors.h.
Referenced by CaptureGenerator::getFrame(), and LUT3D::loadRoboCupChannels().
const rgb RGB::Purple = rgb(128, 0,128) static
Definition at line 473 of file colors.h.
const rgb RGB::Red = rgb(255, 0, 0) static
Definition at line 457 of file colors.h.
Referenced by PluginVisualize::DrawDetectedEdges(), and CaptureGenerator::getFrame().
const rgb RGB::White = rgb(255,255,255) static
Definition at line 458 of file colors.h.
Referenced by CaptureGenerator::getFrame(), LUT3D::loadBlackWhite(), and LUT3D::loadRoboCupChannels().
const rgb RGB::Yellow = rgb(255,255, 0) static
Definition at line 463 of file colors.h.
Referenced by CaptureGenerator::getFrame(), and LUT3D::loadRoboCupChannels().