Documentation: VarTypes::VarTreeView Class Reference
VarTypes::VarTreeView Class Reference
The 'view' using a QTreeView for displaying VarTypes in the QT4 Item-Model.
#include <VarTreeView.h>
Public Slots
void search (const QString &text)
void nextSearchResult ()
Public Member Functions
void setModel (VarTreeModel *tmodel)
VarTreeView (VarTreeModel *tmodel=0)
virtual ~VarTreeView ()
void fitColumns ()
void expandAndFocus (VarType *search)
Protected Slots
void newItemChecksRows (const QModelIndex &parent, int start, int end)
void checkDataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
Protected Attributes
QList< VarItem * > search_result
int result_idx
QLineEdit * search_edit
QTreeView * tw
VarItemDelegate * delegate
VarTreeModel * model
QVBoxLayout * l
Detailed Description
The 'view' using a QTreeView for displaying VarTypes in the QT4 Item-Model.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
This file is part of the QT4 Item-Model for VarTypes. It is used when you want to edit/visualize VarTypes using QT4's model/view system.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 44 of file VarTreeView.h.
Constructor & Destructor Documentation
VarTypes::VarTreeView::VarTreeView (VarTreeModel * tmodel = 0)
Definition at line 22 of file VarTreeView.cpp.
References delegate, l, model, nextSearchResult(), result_idx, search(), search_edit, setModel(), and tw.
{
     model=tmodel;
     tw=new QTreeView();
     delegate = new VarItemDelegate();
     tw->setItemDelegate(delegate);
     tw->setAlternatingRowColors(true);
     tw->setUniformRowHeights ( false );
     tw->setAnimated(false);
     tw->setWordWrap(true);
     tw->setEditTriggers(tw->editTriggers() | QAbstractItemView::CurrentChanged);
     if (tmodel!=0) setModel(tmodel);
     search_edit = new QLineEdit(this);
     l = new QVBoxLayout();
     setLayout(l);
     l->addWidget(tw);
     l->addWidget(search_edit);
     l->setMargin(1);
     l->setSpacing(1);
     result_idx=0;
     connect(search_edit,SIGNAL(textChanged(const QString)),this,SLOT(search(const QString)));
     connect(search_edit,SIGNAL(returnPressed()),this,SLOT(nextSearchResult()));
   }
VarTypes::VarTreeView::~VarTreeView () virtual
Definition at line 66 of file VarTreeView.cpp.
References delegate, l, and tw.
{
     delete delegate;
     delete tw;
     delete l;
   }
Member Function Documentation
void VarTypes::VarTreeView::checkDataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) protected slot
Definition at line 97 of file VarTreeView.cpp.
References velocity.pid::dt, VarTypes::VarType::getFlags(), VarTypes::VarItem::getVarType(), velocity.pid_::i, tw, and VarTypes::VARTYPE_FLAG_PERSISTENT.
Referenced by setModel().
{
     for (int i=topLeft.row();i<=bottomRight.row();i++) {
       if (topLeft.column()==1) {
         QModelIndex index=topLeft.sibling(i,1);
         if (index.isValid() && index.model()!=0) {
           VarItem * item=(VarItem*)(((VarTreeModel*)index.model())->itemFromIndex (index));
           if (item!=0) {
             VarType * dt=item->getVarType();
             if (dt!=0) {
               if ((dt->getFlags() & VARTYPE_FLAG_PERSISTENT) != 0x00) {
                 tw->openPersistentEditor(index);
               } /*else {
                 tw->closePersistentEditor(index);
               }*/
             }
           }
         }
       }
     }
   }
void VarTypes::VarTreeView::expandAndFocus (VarType * search)
Definition at line 142 of file VarTreeView.cpp.
References VarTypes::VarTreeModel::findItems(), model, and tw.
Referenced by ConfigWidget::ConfigWidget(), and MainWindow::MainWindow().
{
     if (model==0) return;
     QList<VarItem *> res=model->findItems(search);
     if (res.size() > 0) {
       tw->expand(res[0]->index());
       tw->scrollTo(res[0]->index());
       tw->setCurrentIndex(res[0]->index());
     }
   }
void VarTypes::VarTreeView::fitColumns ()
Definition at line 137 of file VarTreeView.cpp.
References tw.
Referenced by ConfigWidget::ConfigWidget(), MainWindow::MainWindow(), and setModel().
{
     tw->resizeColumnToContents(0);
     tw->resizeColumnToContents(1);
   }
void VarTypes::VarTreeView::newItemChecksRows (const QModelIndex & parent, int start, int end) protected slot
Definition at line 118 of file VarTreeView.cpp.
{
     (void)parent;
     (void)start;
     (void)end;
     /*
     printf("parent: %d  %d new row: %d to %d\n",parent.row(),parent.column(),start,end); fflush(stdout);
     if (parent.row() != -1 && parent.column() != -1) {
       //tw->openPersistentEditor(parent.child(start,0));
     }*/
   }
void VarTypes::VarTreeView::nextSearchResult () slot
Definition at line 57 of file VarTreeView.cpp.
References result_idx, search_result, and tw.
Referenced by VarTreeView().
{
     result_idx++;
     int n=search_result.size();
     if (result_idx > (n-1)) result_idx=0;
     if (n==0) return;
     tw->scrollTo(search_result[result_idx]->index());
     tw->setCurrentIndex(search_result[result_idx]->index());
   }
void VarTypes::VarTreeView::search (const QString & text) slot
Definition at line 47 of file VarTreeView.cpp.
References VarTypes::VarTreeModel::findItems(), model, result_idx, search_result, and tw.
Referenced by VarTreeView().
{
     if (model==0) return;
     search_result=model->findItems(text,false);
     result_idx=0;
     if (search_result.size() > 0) {
       tw->scrollTo(search_result[result_idx]->index());
       tw->setCurrentIndex(search_result[result_idx]->index());
     }
   }
void VarTypes::VarTreeView::setModel (VarTreeModel * tmodel)
Definition at line 72 of file VarTreeView.cpp.
References checkDataChanged(), fitColumns(), model, result_idx, search_result, and tw.
Referenced by ConfigWidget::ConfigWidget(), MainWindow::MainWindow(), and VarTreeView().
{
     if (model!=0) {
       //remove any old signals from the model to this view
       disconnect(model,0,this,0);
     }
     search_result.clear();
     result_idx=0;
     model=tmodel;
     tw->setModel(model);
     fitColumns();
     //open persistent editors for any items which to not have one yet:
     if (model!=0) {
       //connect the model to open persistent editors for new items:
       //connect(model,SIGNAL(rowsInserted(const QModelIndex &, int, int)),this,SLOT(newItemChecksRows(const QModelIndex &, int, int)));
       connect(model,SIGNAL(dataChanged(const QModelIndex &, const QModelIndex &)),this,SLOT(checkDataChanged(const QModelIndex &, const QModelIndex &)));
     }
   }
Field Documentation
VarItemDelegate* VarTypes::VarTreeView::delegate protected
Definition at line 52 of file VarTreeView.h.
Referenced by VarTreeView(), and ~VarTreeView().
QVBoxLayout* VarTypes::VarTreeView::l protected
Definition at line 54 of file VarTreeView.h.
Referenced by VarTreeView(), and ~VarTreeView().
VarTreeModel* VarTypes::VarTreeView::model protected
Definition at line 53 of file VarTreeView.h.
Referenced by expandAndFocus(), search(), setModel(), and VarTreeView().
int VarTypes::VarTreeView::result_idx protected
Definition at line 49 of file VarTreeView.h.
Referenced by nextSearchResult(), search(), setModel(), and VarTreeView().
QLineEdit* VarTypes::VarTreeView::search_edit protected
Definition at line 50 of file VarTreeView.h.
Referenced by VarTreeView().
QList<VarItem *> VarTypes::VarTreeView::search_result protected
Definition at line 48 of file VarTreeView.h.
Referenced by nextSearchResult(), search(), and setModel().
QTreeView* VarTypes::VarTreeView::tw protected
Definition at line 51 of file VarTreeView.h.
Referenced by checkDataChanged(), expandAndFocus(), fitColumns(), nextSearchResult(), search(), setModel(), VarTreeView(), and ~VarTreeView().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/gui/VarTreeView.h
ssl-vision/src/shared/vartypes/gui/VarTreeView.cpp