Documentation: VarTypes::VarString Class Reference
VarTypes::VarString Class Reference
This is the string VarType of the VarTypes system.
#include <VarString.h>
Public Member Functions
VarString (string name="", string default_val="")
virtual ~VarString ()
virtual void resetToDefault ()
virtual void setDefault (string val)
Public Member Functions inherited from VarTypes::VarTypeTemplate< VarStringVal >
VarTypeTemplate (string name="")
Public Member Functions inherited from VarTypes::VarType
VarType (string name="")
virtual ~VarType ()
virtual vector< VarType * > getChildren () const
virtual void deleteAllChildren ()
virtual void setName (string name)
Set the string label of this node.
virtual string getName () const
Get the string label of this node.
virtual VarTypeFlag getFlags () const
virtual void setFlags (VarTypeFlag f)
virtual void addFlags (VarTypeFlag f)
virtual void removeFlags (VarTypeFlag f)
virtual bool areFlagsSet (VarTypeFlag f) const
VarType * findChild (string label) const
void writeXML (XMLNode &parent, bool blind_append=true)
Write the contents of this VarType node to an XMLNode.
void readXML (XMLNode &us)
Let this VarType node load the contents of an XMLNode.
virtual QWidget * createEditor (const VarItemDelegate *delegate, QWidget *parent, const QStyleOptionViewItem &option)
virtual void setEditorData (const VarItemDelegate *delegate, QWidget *editor) const
virtual void setModelData (const VarItemDelegate *delegate, QWidget *editor)
virtual QSize sizeHint (const VarItemDelegate *delegate, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void paint (const VarItemDelegate *delegate, QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * deepClone () const
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Public Member Functions inherited from VarTypes::VarStringVal
VarStringVal (const string &default_val="")
virtual ~VarStringVal ()
virtual void printdebug () const
virtual VarTypeId getType () const
virtual string getString () const
virtual bool hasValue () const
virtual bool setString (const string &val)
virtual VarVal * clone () const
Protected Attributes
SafeVarVal< VarStringVal > _def
Protected Attributes inherited from VarTypes::VarType
QMutex * _mutex
VarTypeFlag _flags
string _name
Protected Attributes inherited from VarTypes::VarStringVal
string _val
Additional Inherited Members
Public Slots inherited from VarTypes::VarType
void mvcEditCompleted ()
A slot to receive signals from a model-view system that editing of this item was just completed.
Signals inherited from VarTypes::VarType
void hasChanged (VarType *)
void wasEdited (VarType *)
void XMLwasRead (VarType *)
This signal is triggered if data was written from an xml node.
void XMLwasWritten (VarType *)
This signal is triggered if data was written to an xml node.
Static Public Member Functions inherited from VarTypes::VarType
static void deleteAllVarChildren (XMLNode &node)
Clear an XMLNode's list of children.
static vector< VarType * > readChildrenHelper (XMLNode &parent, vector< VarType * > existing_children, bool only_update_existing, bool blind_append)
A helper function to read a list of children from XML and convert it to a vector of VarType nodes.
Protected Member Functions inherited from VarTypes::VarType
virtual void lock () const
virtual void unlock () const
virtual void changed ()
virtual void updateAttributes (XMLNode &us) const
virtual void updateText (XMLNode &us) const
virtual void updateChildren (XMLNode &us) const
virtual void readAttributes (XMLNode &us)
virtual void readText (XMLNode &us)
virtual void readChildren (XMLNode &us)
virtual void loadExternal ()
Static Protected Member Functions inherited from VarTypes::VarType
static string fixString (const char *cst)
static string intToString (int val)
static string doubleToString (double val)
static XMLNode findOrAppendChild (XMLNode &parent, string key, string val)
Detailed Description
This is the string VarType of the VarTypes system.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 35 of file VarString.h.
Constructor & Destructor Documentation
VarTypes::VarString::VarString (string name = "", string default_val = "") inline
Definition at line 41 of file VarString.h.
References VarTypes::VarType::changed().
                                                      : VarStringVal(default_val), VarTypeTemplate<VarStringVal>(name)
     {
       _def.setString(default_val);
       changed();
     }
virtual VarTypes::VarString::~VarString () inline virtual
Definition at line 47 of file VarString.h.
 {}
Member Function Documentation
virtual void VarTypes::VarString::resetToDefault () inline virtual
Reimplemented from VarTypes::VarType.
Definition at line 49 of file VarString.h.
References VarTypes::VarStringVal::setString().
     {
       setString(_def.getString());
     }
virtual void VarTypes::VarString::setDefault (string val) inline virtual
Definition at line 54 of file VarString.h.
References VarTypes::VarType::changed().
     {
       _def.setString(val);
       changed();
     }
Field Documentation
SafeVarVal<VarStringVal> VarTypes::VarString::_def protected
Definition at line 39 of file VarString.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/vartypes/primitives/VarString.h