Documentation: PluginDVR Class Reference
PluginDVR Class Reference
#include <plugin_dvr.h>
Public Member Functions
PluginDVR (FrameBuffer *fb)
virtual VarList * getSettings ()
virtual ~PluginDVR ()
virtual string getName ()
virtual QWidget * getControlWidget ()
virtual ProcessResult process (FrameData *data, RenderOptions *options)
Public Member Functions inherited from VisionPlugin
VisionPlugin (FrameBuffer *_buffer)
virtual ~VisionPlugin ()
FrameBuffer * getFrameBuffer () const
this functions provides convenient access to the ring-buffer
void lock ()
void unlock ()
virtual bool isEnabled () const
virtual void setEnabled (bool enable)
virtual bool isVisualize () const
virtual void setVisualize (bool enable)
virtual bool isSharedAmongStacks () const
virtual void setSharedAmongStacks (bool enable)
virtual void displayLoopEvent (bool frame_changed, RenderOptions *opts)
virtual void postProcess (FrameData *data, RenderOptions *options)
virtual QWidget * getVisualizationWidget ()
virtual void closeWidgets ()
virtual QList< QAction * > actions ()
virtual void keyPressEvent (QKeyEvent *event)
virtual void mousePressEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseReleaseEvent (QMouseEvent *event, pixelloc loc)
virtual void mouseMoveEvent (QMouseEvent *event, pixelloc loc)
virtual void wheelEvent (QWheelEvent *event, pixelloc loc)
void setTimeProcessing (double val)
void setTimePostProcessing (double val)
double getTimeProcessing ()
double getTimePostProcessing ()
Protected Types
enum DVRModeEnum { DVRModeOff, DVRModePause, DVRModeRecord }
enum SeekModeEnum { SeekModePause, SeekModePlay, SeekModeLive }
Protected Slots
void slotModeToggled ()
void slotPauseRefresh ()
void slotSeekModeToggled ()
void slotSeekFrameFirst ()
void slotSeekFrameForward ()
void slotSeekFrameBack ()
void slotSeekFrameLast ()
void slotMovieNew ()
void slotMovieLoad ()
void slotMovieSave ()
void jogValueChanged (float val)
Protected Attributes
DVRModeEnum mode
SeekModeEnum seek_mode
bool is_recording
VarList * _settings
VarInt * _max_frames
VarBool * _shift_on_exceed
PluginDVRWidget * w
double advance_last_t
bool trigger_pause_refresh
DVRFrame pause_frame
DVRStream stream
Protected Attributes inherited from VisionPlugin
QMutex mutex
bool enabled
bool visualize
bool shared
FrameBuffer * buffer
double time_proc
double time_post
Additional Inherited Members
Public Slots inherited from VisionPlugin
void slotKeyPressEvent (QKeyEvent *event)
Detailed Description
Author
Stefan Zickler
Definition at line 127 of file plugin_dvr.h.
Member Enumeration Documentation
enum PluginDVR::DVRModeEnum protected
Enumerator
DVRModeOff
DVRModePause
DVRModeRecord
Definition at line 145 of file plugin_dvr.h.
                    {
     DVRModeOff,
     DVRModePause,
     DVRModeRecord
   };
enum PluginDVR::SeekModeEnum protected
Enumerator
SeekModePause
SeekModePlay
SeekModeLive
Definition at line 150 of file plugin_dvr.h.
                     {
     SeekModePause,
     SeekModePlay,
     SeekModeLive,
   };
Constructor & Destructor Documentation
PluginDVR::PluginDVR (FrameBuffer * fb)
Definition at line 380 of file plugin_dvr.cpp.
References _max_frames, _settings, _shift_on_exceed, VarTypes::VarList::addChild(), advance_last_t, DVRStream::clear(), DVRModeOff, mode, seek_mode, SeekModeLive, VarTypes::VarInt::setMin(), slotModeToggled(), slotSeekModeToggled(), stream, trigger_pause_refresh, and w.
  : VisionPlugin(fb)
 {
   mode = DVRModeOff;
   advance_last_t=0;
   seek_mode = SeekModeLive;
   w=new PluginDVRWidget(this);
   trigger_pause_refresh=false;
   stream.clear();
  _settings = new VarList("DVR Settings");
   _max_frames = new VarInt("Max Frames",250);
   _max_frames->setMin(0);
   _shift_on_exceed = new VarBool("Shift Video On Exceeding",true);
   _settings->addChild(_max_frames);
   _settings->addChild(_shift_on_exceed);
   slotModeToggled();
   slotSeekModeToggled();
 }
PluginDVR::~PluginDVR () virtual
Definition at line 399 of file plugin_dvr.cpp.
References _settings, and w.
 {
   delete _settings;
   delete w;
 }
Member Function Documentation
QWidget * PluginDVR::getControlWidget () virtual
Reimplemented from VisionPlugin.
Definition at line 508 of file plugin_dvr.cpp.
References w.
{
   return w;
 }
string PluginDVR::getName () virtual
Reimplemented from VisionPlugin.
Definition at line 409 of file plugin_dvr.cpp.
{
   return "DVR";
 }
VarList * PluginDVR::getSettings () virtual
Reimplemented from VisionPlugin.
Definition at line 405 of file plugin_dvr.cpp.
References _settings.
{
   return _settings;
 }
void PluginDVR::jogValueChanged (float val) protected slot
Definition at line 290 of file plugin_dvr.cpp.
{
 }
ProcessResult PluginDVR::process (FrameData * data, RenderOptions * options) virtual
Reimplemented from VisionPlugin.
Definition at line 417 of file plugin_dvr.cpp.
References _max_frames, _shift_on_exceed, DVRStream::advance(), advance_last_t, DVRStream::appendFrame(), PluginDVRWidget::btn_rec_rec, PluginDVRWidget::btn_seek_pause, PluginDVRWidget::btn_seek_wrap, RawImage::deepCopyFromRawImage(), DVRModePause, DVRModeRecord, VarTypes::VarBoolVal::getBool(), DVRStream::getCurrentFrame(), DVRStream::getCurrentFrameIndex(), DVRStream::getFrameCount(), DVRFrame::getFromFrameData(), VarTypes::VarInt::getInt(), DVRStream::getLimit(), GetTimeSec(), is_recording, PluginDVRWidget::jog, PluginDVRWidget::label_info, mode, JogDial::offset(), pause_frame, ProcessingOk, seek_mode, SeekModeLive, SeekModePause, SeekModePlay, DVRStream::setLimit(), stream, t, trigger_pause_refresh, FrameData::video, DVRFrame::video, and w.
{
   (void)options;
   QString status;
   QString stream_info;
   stream_info = "";
   status = "";
   bool is_recording=w->btn_rec_rec->isChecked();
   //capture data:
   if (mode==DVRModePause) {
     if (trigger_pause_refresh) {
       pause_frame.getFromFrameData(data);
       trigger_pause_refresh=false;
     }
     status = "Pausing.";
   } else if (mode==DVRModeRecord) {
     if (is_recording) {
       stream.setLimit(_max_frames->getInt());
       stream.appendFrame(data,_shift_on_exceed->getBool());
       status = "Recording (Frame " + QString::number(stream.getFrameCount()) + ").";
       if (stream.getFrameCount() >= stream.getLimit()) {
         if (_shift_on_exceed->getBool()) {
           status = status + " Past Max Frame Limit! Now Shift-Recoding!";
         } else {
           status = status + " Past Max Frame Limit! Dropping Frames!";
         }
       }
     } else {
       status = "Recorded " + QString::number(stream.getFrameCount()) + " Frame(s)";
     }
   } else {
     status = "Live Pass-Through.";
   }
   if (mode==DVRModeRecord) {
     //move stream:
     double t=GetTimeSec();
     double advance_passed=t-advance_last_t;
     double advance_fps=(double)w->jog->offset() * 20.0;
     int frames_advance_int=0;
     if (advance_fps != 0.0) {
       double advance_period=1.0/advance_fps;
       float frames_behind=advance_passed/advance_period;
       if (fabs(frames_behind) > 1.0) {
         frames_advance_int=(int)frames_behind;
       }
     }
     if (frames_advance_int!=0) {
       w->btn_seek_pause->setChecked(true);
       seek_mode=SeekModePause;
     }
     if (seek_mode==SeekModePlay) {
       stream.advance(1,w->btn_seek_wrap->isChecked());
     } else if (seek_mode==SeekModePause) {
       if (frames_advance_int!=0) {
         stream.advance(frames_advance_int,w->btn_seek_wrap->isChecked());
         advance_last_t=t;
       }
     }
     if (stream.getFrameCount() <= 0 || seek_mode==SeekModeLive) {
       stream_info = "Showing Live-View.";
     } else {
       double percent = 100.0 * ((double)stream.getCurrentFrameIndex()+1) / ((double)(stream.getFrameCount()));
       if (seek_mode==SeekModePause) {
         stream_info = "Paused Playback at Frame " + QString::number(stream.getCurrentFrameIndex()+1) + "/" + QString::number(stream.getFrameCount()) + " (" + QString::number(percent,'f',2) + "%).";
       } else {
         stream_info = "Running Playback at Frame " + QString::number(stream.getCurrentFrameIndex()+1) + "/" + QString::number(stream.getFrameCount()) + " (" + QString::number(percent,'f',2) + "%).";
       }
     }
   }
   //output data:
   if (mode==DVRModePause) {
     data->video.deepCopyFromRawImage(pause_frame.video,false);
   } else if (mode==DVRModeRecord) {
     if (seek_mode!=SeekModeLive && stream.getFrameCount() > 0) {
       DVRFrame * f = stream.getCurrentFrame();
       if (f!=0) {
         data->video.deepCopyFromRawImage(f->video,false);
       }
     }
   }
   //update GUI:
   w->label_info->setText(status + "\n" + stream_info);
   return ProcessingOk;
 }
void PluginDVR::slotModeToggled () protected slot
Definition at line 235 of file plugin_dvr.cpp.
Referenced by PluginDVR().
{
   lock();
   w->btn_pause_refresh->setEnabled(w->btn_mode_pause->isChecked());
   DVRModeEnum old_mode = mode;
   if (w->btn_mode_pause->isChecked()) {
     mode=DVRModePause;
   } else if (w->btn_mode_record->isChecked()) {
     mode=DVRModeRecord;
   } else {
     mode=DVRModeOff;
   }
   w->box_dvr->setEnabled(mode==DVRModeRecord);
   if (mode==DVRModePause && mode!=old_mode) {
     trigger_pause_refresh=true;
   }
   //update mode:
   unlock();
 }
void PluginDVR::slotMovieLoad () protected slot
Definition at line 300 of file plugin_dvr.cpp.
References COLOR_RGB8, velocity.pid_::i, ImageIO::readRGB(), and FrameData::time.
{
   lock();
   // Do not use native dialog since some platforms like Windows XP and
   // Kubuntu 12.04 have very slow directory listing dialogs. The QT version is
   // pretty responsive.
   QString dirstr = QFileDialog::getExistingDirectory(
       0,"Select Directory to Load", "",
       QFileDialog::DontUseNativeDialog | QFileDialog::ShowDirsOnly);
   if (dirstr!="") {
     int fnum=0;
     stream.clear();
     QDir dir(dirstr);
     QFileInfoList list = dir.entryInfoList ( QDir::Files | QDir::Readable, QDir::Name );
     QProgressDialog * dlg = new QProgressDialog("Loading Movie from Files...","Cancel", 1,list.size());
     dlg->setWindowModality(Qt::WindowModal);
     for (int i = 0 ; i < list.size(); i ++) {
       dlg->setValue(i+1);
       QFileInfo info = list[i];
       if (info.suffix().compare("png",Qt::CaseInsensitive) == 0 ||
           info.suffix().compare("bmp",Qt::CaseInsensitive) == 0 ||
           info.suffix().compare("jpg",Qt::CaseInsensitive) == 0 ||
           info.suffix().compare("jpeg",Qt::CaseInsensitive) == 0) {
           int w,h;
           rgb * data = ImageIO::readRGB(w,h,info.filePath().toStdString().c_str());
           FrameData fdata;
           fdata.time = 0.0;
           fdata.number = fnum;
           fnum++;
           fdata.video.setColorFormat(COLOR_RGB8);
           fdata.video.setData((unsigned char*)data);
           fdata.video.setWidth(w);
           fdata.video.setHeight(h);
           stream.appendFrame(&fdata,false);
           delete[] data;
       }
       if (dlg->wasCanceled()) break;
     }
     delete dlg;
   }
   unlock();
 }
void PluginDVR::slotMovieNew () protected slot
Definition at line 294 of file plugin_dvr.cpp.
{
   lock();
   stream.clear();
   unlock();
 }
void PluginDVR::slotMovieSave () protected slot
Definition at line 343 of file plugin_dvr.cpp.
References COLOR_RGB8, COLOR_YUV422_UYVY, RawImage::getColorFormat(), RawImage::getData(), RawImage::getHeight(), RawImage::getNumBytes(), RawImage::getWidth(), velocity.pid_::i, Conversions::uyvy2rgb(), and DVRFrame::video.
{
   lock();
   QString dir = QFileDialog::getExistingDirectory(0,"Select Directory to Save");
   rgbImage output;
   QProgressDialog * dlg = new QProgressDialog("Saving Movie to PNG Files...","Cancel", 1,stream.getFrameCount());
   dlg->setWindowModality(Qt::WindowModal);
   if (dir!="") {
     for (int i = 0; i < stream.getFrameCount(); i++) {
       DVRFrame * f = stream.getFrame(i);
       dlg->setValue(i+1);
       if (f!=0) {
         ColorFormat fmt=f->video.getColorFormat();
         output.allocate(f->video.getWidth(),f->video.getHeight());
         if (fmt==COLOR_YUV422_UYVY) {
           Conversions::uyvy2rgb(f->video.getData(),output.getData(),f->video.getWidth(),f->video.getHeight());
         } else if (fmt==COLOR_RGB8) {
           memcpy(output.getData(),f->video.getData(),f->video.getNumBytes());
         } else {
           output.allocate(0,0);
         }
         if (output.getNumBytes() > 0) {
           //write file:
           QString num = QString::number(i);
           num = "00000" + num;
           num = num.right(5);
           QString filename = dir + "/" + num + ".png";
           output.save(filename.toStdString());
         }
       }
       if (dlg->wasCanceled()) break;
     }
   }
   delete dlg;
   unlock();
 }
void PluginDVR::slotPauseRefresh () protected slot
Definition at line 284 of file plugin_dvr.cpp.
{
   lock();
   trigger_pause_refresh=true;
   unlock();
 }
void PluginDVR::slotSeekFrameBack () protected slot
Definition at line 272 of file plugin_dvr.cpp.
{
   lock();
     stream.advance(-1,w->btn_seek_wrap->isChecked());
   unlock();
 }
void PluginDVR::slotSeekFrameFirst () protected slot
Definition at line 260 of file plugin_dvr.cpp.
{
   lock();
     stream.seek(0);
   unlock();
 }
void PluginDVR::slotSeekFrameForward () protected slot
Definition at line 266 of file plugin_dvr.cpp.
{
   lock();
     stream.advance(1,w->btn_seek_wrap->isChecked());
   unlock();
 }
void PluginDVR::slotSeekFrameLast () protected slot
Definition at line 278 of file plugin_dvr.cpp.
{
   lock();
     stream.seek(stream.getFrameCount()-1);
   unlock();
 }
void PluginDVR::slotSeekModeToggled () protected slot
Definition at line 223 of file plugin_dvr.cpp.
Referenced by PluginDVR().
{
   lock();
     if (w->btn_seek_pause->isChecked()) {
       seek_mode=SeekModePause;
     } else if (w->btn_seek_play->isChecked()) {
       seek_mode=SeekModePlay;
     } else {
       seek_mode=SeekModeLive;
     }
   unlock();
 }
Field Documentation
VarInt* PluginDVR::_max_frames protected
Definition at line 159 of file plugin_dvr.h.
Referenced by PluginDVR(), and process().
VarList* PluginDVR::_settings protected
Definition at line 158 of file plugin_dvr.h.
Referenced by getSettings(), PluginDVR(), and ~PluginDVR().
VarBool* PluginDVR::_shift_on_exceed protected
Definition at line 160 of file plugin_dvr.h.
Referenced by PluginDVR(), and process().
double PluginDVR::advance_last_t protected
Definition at line 163 of file plugin_dvr.h.
Referenced by PluginDVR(), and process().
bool PluginDVR::is_recording protected
Definition at line 157 of file plugin_dvr.h.
Referenced by process().
DVRModeEnum PluginDVR::mode protected
Definition at line 155 of file plugin_dvr.h.
Referenced by PluginDVR(), and process().
DVRFrame PluginDVR::pause_frame protected
Definition at line 166 of file plugin_dvr.h.
Referenced by process().
SeekModeEnum PluginDVR::seek_mode protected
Definition at line 156 of file plugin_dvr.h.
Referenced by PluginDVR(), and process().
DVRStream PluginDVR::stream protected
Definition at line 167 of file plugin_dvr.h.
Referenced by PluginDVR(), and process().
bool PluginDVR::trigger_pause_refresh protected
Definition at line 165 of file plugin_dvr.h.
Referenced by PluginDVR(), and process().
PluginDVRWidget* PluginDVR::w protected
Definition at line 161 of file plugin_dvr.h.
Referenced by getControlWidget(), PluginDVR(), process(), and ~PluginDVR().
The documentation for this class was generated from the following files:
ssl-vision/src/app/plugins/plugin_dvr.h
ssl-vision/src/app/plugins/plugin_dvr.cpp