Documentation: Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder Interface Reference
Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder Interface Reference
Public Member Functions
boolean hasConfidence ()
float getConfidence ()
boolean hasArea ()
int getArea ()
boolean hasX ()
float getX ()
boolean hasY ()
float getY ()
boolean hasZ ()
float getZ ()
boolean hasPixelX ()
float getPixelX ()
boolean hasPixelY ()
float getPixelY ()
Detailed Description
Definition at line 11 of file MessagesRobocupSslDetection.java.
Member Function Documentation
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.getArea ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.getConfidence ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.getPixelX ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.getPixelY ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.getX ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.getY ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.getZ ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasArea ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasConfidence ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.isInitialized(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.isInitialized(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.isInitialized(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasPixelX ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.isInitialized(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.isInitialized(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.isInitialized(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasPixelY ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.isInitialized(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.isInitialized(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.isInitialized(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasX ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.isInitialized(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.isInitialized(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.isInitialized(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasY ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.isInitialized(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.isInitialized(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.isInitialized(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionRobot.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasZ ()
Implemented in Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder, and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.
The documentation for this interface was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslDetection.java