Documentation: SSL_WrapperPacket Class Reference
SSL_WrapperPacket Class Reference
#include <messages_robocup_ssl_wrapper.pb.h>
Public Member Functions
SSL_WrapperPacket ()
virtual ~SSL_WrapperPacket ()
SSL_WrapperPacket (const SSL_WrapperPacket &from)
SSL_WrapperPacket & operator= (const SSL_WrapperPacket &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_WrapperPacket *other)
SSL_WrapperPacket * New () const PROTOBUF_FINAL
SSL_WrapperPacket * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_WrapperPacket &from)
void MergeFrom (const SSL_WrapperPacket &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_detection () const
void clear_detection ()
const ::SSL_DetectionFrame & detection () const
::SSL_DetectionFrame * mutable_detection ()
::SSL_DetectionFrame * release_detection ()
void set_allocated_detection (::SSL_DetectionFrame *detection)
bool has_geometry () const
void clear_geometry ()
const ::SSL_GeometryData & geometry () const
::SSL_GeometryData * mutable_geometry ()
::SSL_GeometryData * release_geometry ()
void set_allocated_geometry (::SSL_GeometryData *geometry)
SSL_WrapperPacket ()
virtual ~SSL_WrapperPacket ()
SSL_WrapperPacket (const SSL_WrapperPacket &from)
SSL_WrapperPacket & operator= (const SSL_WrapperPacket &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_WrapperPacket *other)
SSL_WrapperPacket * New () const PROTOBUF_FINAL
SSL_WrapperPacket * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_WrapperPacket &from)
void MergeFrom (const SSL_WrapperPacket &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_detection () const
void clear_detection ()
const ::SSL_DetectionFrame & detection () const
::SSL_DetectionFrame * release_detection ()
::SSL_DetectionFrame * mutable_detection ()
void set_allocated_detection (::SSL_DetectionFrame *detection)
bool has_geometry () const
void clear_geometry ()
const ::SSL_GeometryData & geometry () const
::SSL_GeometryData * release_geometry ()
::SSL_GeometryData * mutable_geometry ()
void set_allocated_geometry (::SSL_GeometryData *geometry)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_WrapperPacket & default_instance ()
static const SSL_WrapperPacket * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_WrapperPacket & default_instance ()
static void InitAsDefaultInstance ()
static const SSL_WrapperPacket * internal_default_instance ()
Static Public Attributes
static const int kDetectionFieldNumber = 1
static const int kGeometryFieldNumber = 2
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_WrapperPacket *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_detection ()
void clear_has_detection ()
void set_has_geometry ()
void clear_has_geometry ()
friendconst::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5fwrapper_2eproto ()
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_WrapperPacket *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_detection ()
void clear_has_detection ()
void set_has_geometry ()
void clear_has_geometry ()
friend void::protobuf_messages_5frobocup_5fssl_5fwrapper_2eproto::InitDefaultsSSL_WrapperPacketImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
::SSL_DetectionFrame * detection_
::SSL_GeometryData * geometry_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5fwrapper_2eproto::TableStruct
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto_impl ()
void protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_impl ()
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fwrapper_2eproto ()
void swap (SSL_WrapperPacket &a, SSL_WrapperPacket &b)
Detailed Description
Definition at line 61 of file messages_robocup_ssl_wrapper.pb.h.
Constructor & Destructor Documentation
SSL_WrapperPacket::SSL_WrapperPacket ()
virtual SSL_WrapperPacket::~SSL_WrapperPacket () virtual
SSL_WrapperPacket::SSL_WrapperPacket (const SSL_WrapperPacket & from)
SSL_WrapperPacket::SSL_WrapperPacket ()
virtual SSL_WrapperPacket::~SSL_WrapperPacket () virtual
SSL_WrapperPacket::SSL_WrapperPacket (const SSL_WrapperPacket & from)
Member Function Documentation
size_t SSL_WrapperPacket::ByteSizeLong () const
Referenced by New().
size_t SSL_WrapperPacket::ByteSizeLong () const
void SSL_WrapperPacket::Clear ()
Referenced by New().
void SSL_WrapperPacket::Clear ()
void SSL_WrapperPacket::clear_detection () inline
Definition at line 189 of file messages_robocup_ssl_wrapper.pb.h.
References clear_has_detection(), and detection_.
Referenced by MaybeArenaPtr().
{
   if (detection_ != NULL) detection_->::SSL_DetectionFrame::Clear();
   clear_has_detection();
 }
void SSL_WrapperPacket::clear_detection ()
void SSL_WrapperPacket::clear_geometry () inline
Definition at line 234 of file messages_robocup_ssl_wrapper.pb.h.
References clear_has_geometry(), and geometry_.
{
   if (geometry_ != NULL) geometry_->::SSL_GeometryData::Clear();
   clear_has_geometry();
 }
void SSL_WrapperPacket::clear_geometry ()
void SSL_WrapperPacket::clear_has_detection () inline private
Definition at line 186 of file messages_robocup_ssl_wrapper.pb.h.
References _has_bits_.
Referenced by clear_detection(), release_detection(), and set_allocated_detection().
{
   _has_bits_[0] &= ~0x00000001u;
 }
void SSL_WrapperPacket::clear_has_detection () private
void SSL_WrapperPacket::clear_has_geometry () inline private
Definition at line 231 of file messages_robocup_ssl_wrapper.pb.h.
References _has_bits_.
Referenced by clear_geometry(), release_geometry(), and set_allocated_geometry().
{
   _has_bits_[0] &= ~0x00000002u;
 }
void SSL_WrapperPacket::clear_has_geometry () private
void SSL_WrapperPacket::CopyFrom (const ::google::protobuf::Message & from)
Referenced by New(), and operator=().
void SSL_WrapperPacket::CopyFrom (const SSL_WrapperPacket & from)
void SSL_WrapperPacket::CopyFrom (const ::google::protobuf::Message & from)
void SSL_WrapperPacket::CopyFrom (const SSL_WrapperPacket & from)
static const SSL_WrapperPacket& SSL_WrapperPacket::default_instance () static
Referenced by mutable_unknown_fields().
static const SSL_WrapperPacket& SSL_WrapperPacket::default_instance () static
static const ::google::protobuf::Descriptor* SSL_WrapperPacket::descriptor () static
Referenced by mutable_unknown_fields().
static const ::google::protobuf::Descriptor* SSL_WrapperPacket::descriptor () static
const ::SSL_DetectionFrame & SSL_WrapperPacket::detection () const inline
Definition at line 193 of file messages_robocup_ssl_wrapper.pb.h.
References detection_, and SSL_DetectionFrame::internal_default_instance().
Referenced by ViewUpdateThread::execute(), main(), MyThread::run(), and set_allocated_detection().
{
   // @@protoc_insertion_point(field_get:SSL_WrapperPacket.detection)
   return detection_ != NULL ? *detection_
                          : *::SSL_DetectionFrame::internal_default_instance();
 }
const ::SSL_DetectionFrame& SSL_WrapperPacket::detection () const
const ::SSL_GeometryData & SSL_WrapperPacket::geometry () const inline
Definition at line 238 of file messages_robocup_ssl_wrapper.pb.h.
References geometry_, and SSL_GeometryData::internal_default_instance().
Referenced by ViewUpdateThread::execute(), main(), MyThread::run(), and set_allocated_geometry().
{
   // @@protoc_insertion_point(field_get:SSL_WrapperPacket.geometry)
   return geometry_ != NULL ? *geometry_
                          : *::SSL_GeometryData::internal_default_instance();
 }
const ::SSL_GeometryData& SSL_WrapperPacket::geometry () const
inline ::google::protobuf::Arena* SSL_WrapperPacket::GetArenaNoVirtual () const inline private
Definition at line 121 of file messages_robocup_ssl_wrapper.pb.h.
Referenced by operator=().
{
     return NULL;
   }
inline ::google::protobuf::Arena* SSL_WrapperPacket::GetArenaNoVirtual () const inline private
Definition at line 134 of file messages_robocup_ssl_wrapper.pb.h.
{
     return NULL;
   }
int SSL_WrapperPacket::GetCachedSize () const inline
Definition at line 114 of file messages_robocup_ssl_wrapper.pb.h.
References _cached_size_, InternalSwap(), SetCachedSize(), SharedCtor(), and SharedDtor().
 { return _cached_size_; }
int SSL_WrapperPacket::GetCachedSize () const inline
Definition at line 127 of file messages_robocup_ssl_wrapper.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata SSL_WrapperPacket::GetMetadata () const
Referenced by MaybeArenaPtr().
::google::protobuf::Metadata SSL_WrapperPacket::GetMetadata () const
bool SSL_WrapperPacket::has_detection () const inline
Definition at line 180 of file messages_robocup_ssl_wrapper.pb.h.
References _has_bits_.
Referenced by ViewUpdateThread::execute(), main(), MaybeArenaPtr(), and MyThread::run().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool SSL_WrapperPacket::has_detection () const
bool SSL_WrapperPacket::has_geometry () const inline
Definition at line 225 of file messages_robocup_ssl_wrapper.pb.h.
References _has_bits_.
Referenced by ViewUpdateThread::execute(), main(), and MyThread::run().
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool SSL_WrapperPacket::has_geometry () const
static void SSL_WrapperPacket::InitAsDefaultInstance () static
static const SSL_WrapperPacket* SSL_WrapperPacket::internal_default_instance () inline static
Definition at line 84 of file messages_robocup_ssl_wrapper.pb.h.
References _SSL_WrapperPacket_default_instance_, and Swap().
{
     return reinterpret_cast<const SSL_WrapperPacket*>(
                &_SSL_WrapperPacket_default_instance_);
   }
static const SSL_WrapperPacket* SSL_WrapperPacket::internal_default_instance () inline static
Definition at line 96 of file messages_robocup_ssl_wrapper.pb.h.
References _SSL_WrapperPacket_default_instance_.
{
     return reinterpret_cast<const SSL_WrapperPacket*>(
                &_SSL_WrapperPacket_default_instance_);
   }
::google::protobuf::uint8* SSL_WrapperPacket::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
Referenced by New(), and SerializeWithCachedSizesToArray().
::google::protobuf::uint8* SSL_WrapperPacket::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void SSL_WrapperPacket::InternalSwap (SSL_WrapperPacket * other) private
Referenced by GetCachedSize().
void SSL_WrapperPacket::InternalSwap (SSL_WrapperPacket * other) private
bool SSL_WrapperPacket::IsInitialized () const
Referenced by New().
bool SSL_WrapperPacket::IsInitialized () const
void* SSL_WrapperPacket::MaybeArenaPtr () const inline private
Definition at line 124 of file messages_robocup_ssl_wrapper.pb.h.
References clear_detection(), GetMetadata(), and has_detection().
{
     return NULL;
   }
void* SSL_WrapperPacket::MaybeArenaPtr () const inline private
Definition at line 137 of file messages_robocup_ssl_wrapper.pb.h.
{
     return NULL;
   }
void SSL_WrapperPacket::MergeFrom (const ::google::protobuf::Message & from)
Referenced by New().
void SSL_WrapperPacket::MergeFrom (const SSL_WrapperPacket & from)
void SSL_WrapperPacket::MergeFrom (const ::google::protobuf::Message & from)
void SSL_WrapperPacket::MergeFrom (const SSL_WrapperPacket & from)
bool SSL_WrapperPacket::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Referenced by New().
bool SSL_WrapperPacket::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
SSL_DetectionFrame * SSL_WrapperPacket::mutable_detection () inline
Definition at line 198 of file messages_robocup_ssl_wrapper.pb.h.
References detection_, and set_has_detection().
Referenced by SSLWorld::generatePacket(), RoboCupSSLServer::open(), and RoboCupSSLServer::send().
{
   set_has_detection();
   if (detection_ == NULL) {
     detection_ = new ::SSL_DetectionFrame;
   }
   // @@protoc_insertion_point(field_mutable:SSL_WrapperPacket.detection)
   return detection_;
 }
::SSL_DetectionFrame* SSL_WrapperPacket::mutable_detection ()
SSL_GeometryData * SSL_WrapperPacket::mutable_geometry () inline
Definition at line 243 of file messages_robocup_ssl_wrapper.pb.h.
References geometry_, and set_has_geometry().
Referenced by SSLWorld::generatePacket(), RoboCupSSLServer::open(), and RoboCupSSLServer::send().
{
   set_has_geometry();
   if (geometry_ == NULL) {
     geometry_ = new ::SSL_GeometryData;
   }
   // @@protoc_insertion_point(field_mutable:SSL_WrapperPacket.geometry)
   return geometry_;
 }
::SSL_GeometryData* SSL_WrapperPacket::mutable_geometry ()
inline ::google::protobuf::UnknownFieldSet* SSL_WrapperPacket::mutable_unknown_fields () inline
Definition at line 77 of file messages_robocup_ssl_wrapper.pb.h.
References _internal_metadata_, default_instance(), and descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
inline ::google::protobuf::UnknownFieldSet* SSL_WrapperPacket::mutable_unknown_fields () inline
Definition at line 88 of file messages_robocup_ssl_wrapper.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
SSL_WrapperPacket* SSL_WrapperPacket::New () const inline
Definition at line 93 of file messages_robocup_ssl_wrapper.pb.h.
References ByteSizeLong(), Clear(), CopyFrom(), InternalSerializeWithCachedSizesToArray(), IsInitialized(), MergeFrom(), MergePartialFromCodedStream(), New(), SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_WrapperPacket* SSL_WrapperPacket::New (::google::protobuf::Arena * arena) const
SSL_WrapperPacket* SSL_WrapperPacket::New () const inline
Definition at line 110 of file messages_robocup_ssl_wrapper.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_WrapperPacket* SSL_WrapperPacket::New (::google::protobuf::Arena * arena) const
SSL_WrapperPacket& SSL_WrapperPacket::operator= (const SSL_WrapperPacket & from) inline
Definition at line 66 of file messages_robocup_ssl_wrapper.pb.h.
References GetArenaNoVirtual().
{
     CopyFrom(from);
     return *this;
   }
SSL_WrapperPacket& SSL_WrapperPacket::operator= (const SSL_WrapperPacket & from) inline
Definition at line 68 of file messages_robocup_ssl_wrapper.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
friendconst ::google::protobuf::uint32* SSL_WrapperPacket::protobuf_Offsets_messages_5frobocup_5fssl_5fwrapper_2eproto () private
SSL_DetectionFrame * SSL_WrapperPacket::release_detection () inline
Definition at line 206 of file messages_robocup_ssl_wrapper.pb.h.
References clear_has_detection(), and detection_.
{
   // @@protoc_insertion_point(field_release:SSL_WrapperPacket.detection)
   clear_has_detection();
   ::SSL_DetectionFrame* temp = detection_;
   detection_ = NULL;
   return temp;
 }
::SSL_DetectionFrame* SSL_WrapperPacket::release_detection ()
SSL_GeometryData * SSL_WrapperPacket::release_geometry () inline
Definition at line 251 of file messages_robocup_ssl_wrapper.pb.h.
References clear_has_geometry(), and geometry_.
{
   // @@protoc_insertion_point(field_release:SSL_WrapperPacket.geometry)
   clear_has_geometry();
   ::SSL_GeometryData* temp = geometry_;
   geometry_ = NULL;
   return temp;
 }
::SSL_GeometryData* SSL_WrapperPacket::release_geometry ()
void SSL_WrapperPacket::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Referenced by New().
void SSL_WrapperPacket::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* SSL_WrapperPacket::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 110 of file messages_robocup_ssl_wrapper.pb.h.
References InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void SSL_WrapperPacket::set_allocated_detection (::SSL_DetectionFrame * detection) inline
Definition at line 213 of file messages_robocup_ssl_wrapper.pb.h.
References clear_has_detection(), detection(), detection_, and set_has_detection().
{
   delete detection_;
   detection_ = detection;
   if (detection) {
     set_has_detection();
   } else {
     clear_has_detection();
   }
   // @@protoc_insertion_point(field_set_allocated:SSL_WrapperPacket.detection)
 }
void SSL_WrapperPacket::set_allocated_detection (::SSL_DetectionFrame * detection)
void SSL_WrapperPacket::set_allocated_geometry (::SSL_GeometryData * geometry) inline
Definition at line 258 of file messages_robocup_ssl_wrapper.pb.h.
References clear_has_geometry(), geometry(), geometry_, and set_has_geometry().
{
   delete geometry_;
   geometry_ = geometry;
   if (geometry) {
     set_has_geometry();
   } else {
     clear_has_geometry();
   }
   // @@protoc_insertion_point(field_set_allocated:SSL_WrapperPacket.geometry)
 }
void SSL_WrapperPacket::set_allocated_geometry (::SSL_GeometryData * geometry)
void SSL_WrapperPacket::set_has_detection () inline private
Definition at line 183 of file messages_robocup_ssl_wrapper.pb.h.
References _has_bits_.
Referenced by mutable_detection(), and set_allocated_detection().
{
   _has_bits_[0] |= 0x00000001u;
 }
void SSL_WrapperPacket::set_has_detection () private
void SSL_WrapperPacket::set_has_geometry () inline private
Definition at line 228 of file messages_robocup_ssl_wrapper.pb.h.
References _has_bits_.
Referenced by mutable_geometry(), and set_allocated_geometry().
{
   _has_bits_[0] |= 0x00000002u;
 }
void SSL_WrapperPacket::set_has_geometry () private
void SSL_WrapperPacket::SetCachedSize (int size) const private
Referenced by GetCachedSize().
void SSL_WrapperPacket::SetCachedSize (int size) const private
void SSL_WrapperPacket::SharedCtor () private
Referenced by GetCachedSize().
void SSL_WrapperPacket::SharedCtor () private
void SSL_WrapperPacket::SharedDtor () private
Referenced by GetCachedSize().
void SSL_WrapperPacket::SharedDtor () private
void SSL_WrapperPacket::Swap (SSL_WrapperPacket * other)
Referenced by internal_default_instance().
void SSL_WrapperPacket::Swap (SSL_WrapperPacket * other)
const ::google::protobuf::UnknownFieldSet& SSL_WrapperPacket::unknown_fields () const inline
Definition at line 73 of file messages_robocup_ssl_wrapper.pb.h.
References _internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
const ::google::protobuf::UnknownFieldSet& SSL_WrapperPacket::unknown_fields () const inline
Definition at line 85 of file messages_robocup_ssl_wrapper.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
SSL_WrapperPacket::void::protobuf_messages_5frobocup_5fssl_5fwrapper_2eproto::InitDefaultsSSL_WrapperPacketImpl () private
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5fwrapper_2eproto::TableStruct friend
Definition at line 178 of file messages_robocup_ssl_wrapper.pb.h.
void protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_impl () friend
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto_impl () friend
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fwrapper_2eproto () friend
void swap (SSL_WrapperPacket & a, SSL_WrapperPacket & b) friend
Definition at line 104 of file messages_robocup_ssl_wrapper.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int SSL_WrapperPacket::_cached_size_ mutable private
Definition at line 162 of file messages_robocup_ssl_wrapper.pb.h.
Referenced by GetCachedSize().
google::protobuf::internal::HasBits< 1 > SSL_WrapperPacket::_has_bits_ private
Definition at line 161 of file messages_robocup_ssl_wrapper.pb.h.
Referenced by clear_has_detection(), clear_has_geometry(), has_detection(), has_geometry(), set_has_detection(), and set_has_geometry().
google::protobuf::internal::InternalMetadataWithArena SSL_WrapperPacket::_internal_metadata_ private
Definition at line 160 of file messages_robocup_ssl_wrapper.pb.h.
Referenced by mutable_unknown_fields(), and unknown_fields().
SSL_DetectionFrame * SSL_WrapperPacket::detection_ private
Definition at line 163 of file messages_robocup_ssl_wrapper.pb.h.
Referenced by clear_detection(), detection(), mutable_detection(), release_detection(), and set_allocated_detection().
SSL_GeometryData * SSL_WrapperPacket::geometry_ private
Definition at line 164 of file messages_robocup_ssl_wrapper.pb.h.
Referenced by clear_geometry(), geometry(), mutable_geometry(), release_geometry(), and set_allocated_geometry().
static const int SSL_WrapperPacket::kDetectionFieldNumber = 1 static
Definition at line 138 of file messages_robocup_ssl_wrapper.pb.h.
static const int SSL_WrapperPacket::kGeometryFieldNumber = 2 static
Definition at line 147 of file messages_robocup_ssl_wrapper.pb.h.
PROTOBUF_CONSTEXPR int const SSL_WrapperPacket::kIndexInFileMessages static
Initial value:
=
    0
Definition at line 100 of file messages_robocup_ssl_wrapper.pb.h.
The documentation for this class was generated from the following file:
grsim_comm/include/proto/messages_robocup_ssl_wrapper.pb.h