Documentation: anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc} Namespace Reference
anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc} Namespace Reference
Functions
void protobuf_AssignDescriptors ()
void protobuf_AssignDescriptorsOnce ()
void protobuf_RegisterTypes (const ::std::string &) GOOGLE_ATTRIBUTE_COLD
Variables
::google::protobuf::Metadata file_level_metadata [2]
Function Documentation
void anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}::protobuf_AssignDescriptors ()
Definition at line 64 of file messages_robocup_ssl_refbox_log.pb.cc.
References file_default_instances, protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::file_level_metadata, protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto(), protobuf_Offsets_messages_5frobocup_5fssl_5frefbox_5flog_2eproto(), and schemas.
{
   protobuf_AddDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto();
   ::google::protobuf::MessageFactory* factory = NULL;
   AssignDescriptors(
       "messages_robocup_ssl_refbox_log.proto", schemas, file_default_instances, protobuf_Offsets_messages_5frobocup_5fssl_5frefbox_5flog_2eproto(), factory,
       file_level_metadata, NULL, NULL);
 }
void anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}::protobuf_AssignDescriptorsOnce ()
Definition at line 72 of file messages_robocup_ssl_refbox_log.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::protobuf_AssignDescriptors(), and protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::protobuf_RegisterTypes().
{
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
   ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
 }
void anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}::protobuf_RegisterTypes (const ::std::string &)
Definition at line 78 of file messages_robocup_ssl_refbox_log.pb.cc.
References protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::file_level_metadata, and protobuf_messages_5frobocup_5fssl_5frefbox_5flog_2eproto::protobuf_AssignDescriptorsOnce().
{
   protobuf_AssignDescriptorsOnce();
   ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
 }
Variable Documentation
::google::protobuf::Metadata anonymous_namespace{messages_robocup_ssl_refbox_log.pb.cc}::file_level_metadata[2]
Definition at line 26 of file messages_robocup_ssl_refbox_log.pb.cc.