Documentation: FunctionCycleTimer Class Reference
FunctionCycleTimer Class Reference
#include <timer.h>
Public Member Functions
FunctionCycleTimer (const char *_fname)
~FunctionCycleTimer ()
FunctionCycleTimer (const char *_fname)
~FunctionCycleTimer ()
Private Attributes
const char * fname
CycleTimer timer
Detailed Description
Definition at line 240 of file timer.h.
Constructor & Destructor Documentation
FunctionCycleTimer::FunctionCycleTimer (const char * _fname) inline
Definition at line 244 of file timer.h.
References CycleTimer::start().
     {fname=_fname; timer.start();}
FunctionCycleTimer::~FunctionCycleTimer () inline
Definition at line 246 of file timer.h.
References CycleTimer::stop(), and CycleTimer::timeMSec().
     {timer.stop(); printf("%s: %0.3f\n",fname,timer.timeMSec());}
FunctionCycleTimer::FunctionCycleTimer (const char * _fname) inline
Definition at line 244 of file timer.h.
References CycleTimer::start().
     {fname=_fname; timer.start();}
FunctionCycleTimer::~FunctionCycleTimer () inline
Definition at line 246 of file timer.h.
References CycleTimer::stop(), and CycleTimer::timeMSec().
     {timer.stop(); printf("%s: %0.3f\n",fname,timer.timeMSec());}
Field Documentation
const char * FunctionCycleTimer::fname private
Definition at line 241 of file timer.h.
CycleTimer FunctionCycleTimer::timer private
Definition at line 242 of file timer.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/timer.h