Documentation: SoccerView Class Reference
SoccerView Class Reference
#include <GraphicsPrimitives.h>
Public Slots
void change_play_button (QString text)
Public Member Functions
SoccerView (QMutex *)
~SoccerView ()
void AddRobot (Robot *robot)
void UpdateRobots (SSL_DetectionFrame &detection)
int UpdateBalls (QVector< QPointF > &_balls, int cameraID)
void LoadFieldGeometry ()
void LoadFieldGeometry (SSL_GeometryFieldSize &fieldSize)
void updateView ()
void update (qreal x, qreal y, qreal width, qreal height)
void update (const QRectF &rect=QRectF())
void repaint (int x, int y, int w, int h)
void repaint (const QRect &rect)
void repaint (const QRegion &rgn)
void initView ()
Data Fields
QPushButton * playLogfile
Protected Member Functions
void wheelEvent (QWheelEvent *event)
void scaleView (qreal scaleFactor)
void timerEvent (QTimerEvent *)
Protected Attributes
QMutex * drawMutex
QMutex scrollMutex
float drawScale
bool scalingRequested
Private Member Functions
void ConstructField ()
Private Attributes
QVector< Robot * > blueRobots
QVector< Robot * > yellowRobots
QVector< Robot * > robots
QVector< QVector< QGraphicsEllipseItem * > > ballItems
QGraphicsScene * scene
QPainterPath * field
QGraphicsPathItem * fieldItem
QBrush * fieldBrush
QBrush * ballBrush
QPen * fieldPen
QPen * fieldLinePen
QPen * ballPen
QGLWidget * glWidget
bool shutdownSoccerView
Detailed Description
Definition at line 78 of file GraphicsPrimitives.h.
Constructor & Destructor Documentation
SoccerView::SoccerView (QMutex * _drawMutex)
Definition at line 147 of file GraphicsPrimitives.cpp.
 {
   drawMutex = _drawMutex;
   shutdownSoccerView = false;
   glWidget = new QGLWidget ( QGLFormat ( QGL::DoubleBuffer ) );
   setViewport ( glWidget );
   LoadFieldGeometry();
   scene = new QGraphicsScene ( this );
   setScene ( scene );
   this->setViewportUpdateMode ( QGraphicsView::NoViewportUpdate );
   scene->setBackgroundBrush ( QBrush ( QColor ( 0,0x91,0x19,255 ),Qt::SolidPattern ) );
   scene->setSceneRect ( -3700,-2700,7400,5400 );
   ConstructField();
   fieldBrush = new QBrush ( Qt::NoBrush );
   fieldLinePen = new QPen();
   fieldLinePen->setColor ( Qt::white );
   fieldLinePen->setWidth ( 10 );
   fieldLinePen->setJoinStyle ( Qt::MiterJoin );
   fieldItem = scene->addPath ( *field,*fieldLinePen,*fieldBrush );
   fieldItem->setZValue(0);
   drawScale = 0.15;
   //this->setRenderHint ( QPainter::Antialiasing, true );
   this->setRenderHint ( QPainter::HighQualityAntialiasing, true );
   this->setDragMode ( QGraphicsView::ScrollHandDrag );
   this->setGeometry ( 100,100,1036,756 );
   scalingRequested = true;
   //LogPlayer data
   playLogfile = new QPushButton(this);
   playLogfile->setObjectName(QString::fromUtf8("play_logfile_button"));
   playLogfile->setCheckable(false);
   playLogfile->setText("Play Logfile");
   playLogfile->setGeometry(10, 10, 150, 30);
   //Timer for casual redraw
   startTimer ( 1000 );
 }
SoccerView::~SoccerView ()
Definition at line 185 of file GraphicsPrimitives.cpp.
 {
   shutdownSoccerView = true;
 }
Member Function Documentation
void SoccerView::AddRobot (Robot * robot)
Definition at line 264 of file GraphicsPrimitives.cpp.
 {
   robots.append ( robot );
   scene->addItem ( robot );
 }
void SoccerView::change_play_button (QString text) inline slot
Definition at line 104 of file GraphicsPrimitives.h.
 {playLogfile->setText(text);}
void SoccerView::ConstructField () private
Definition at line 231 of file GraphicsPrimitives.cpp.
 {
   //scene->removeItem(fieldItem);
   field = new QPainterPath();
   printf("TODO(%s:%d) : Draw dynamic field markingsn\n", __FILE__, __LINE__);
   /*
   field->moveTo ( 0,-field_width/2 );
   field->lineTo ( 0,field_width/2 );
   field->addEllipse ( -center_circle_radius,-center_circle_radius,
                       2*center_circle_radius,2*center_circle_radius );
   */
 }
void SoccerView::initView ()
Definition at line 190 of file GraphicsPrimitives.cpp.
Referenced by CentralWindow::CentralWindow().
 {
   drawScale = pow ( 2.0, (-120) / 540.0 );
   scalingRequested = true;
 }
void SoccerView::LoadFieldGeometry ()
Definition at line 376 of file GraphicsPrimitives.cpp.
Referenced by ViewUpdateThread::execute().
 {
   printf("TODO(%s:%d) : Load list of field markings from "
          "FieldConstantsRoboCup2012\n", __FILE__, __LINE__);
 }
void SoccerView::LoadFieldGeometry (SSL_GeometryFieldSize & fieldSize)
Definition at line 382 of file GraphicsPrimitives.cpp.
 {
   printf("TODO(%s:%d) : Load dynamic list of field markings\n",
          __FILE__, __LINE__);
   scene->removeItem ( fieldItem );
   ConstructField();
   fieldItem = scene->addPath ( *field,*fieldLinePen,*fieldBrush );
 }
void SoccerView::repaint (int x, int y, int w, int h) inline
Definition at line 94 of file GraphicsPrimitives.h.
 {return;}
void SoccerView::repaint (const QRect & rect) inline
Definition at line 95 of file GraphicsPrimitives.h.
 {return;}
void SoccerView::repaint (const QRegion & rgn) inline
Definition at line 96 of file GraphicsPrimitives.h.
 {return;}
void SoccerView::scaleView (qreal scaleFactor) protected
Definition at line 245 of file GraphicsPrimitives.cpp.
 {
   qreal factor = matrix().scale ( scaleFactor, scaleFactor ).mapRect ( QRectF ( 0, 0, 1, 1 ) ).width();
   if ( factor > 0.07 && factor < 100.0 )
     drawScale = scaleFactor;
 }
void SoccerView::timerEvent (QTimerEvent * event) protected
Definition at line 219 of file GraphicsPrimitives.cpp.
 {
   if ( shutdownSoccerView )
   {
     killTimer ( event->timerId() );
     return;
   }
   drawMutex->lock();
   this->updateView();
   drawMutex->unlock();
 }
void SoccerView::update (qreal x, qreal y, qreal width, qreal height) inline
Definition at line 92 of file GraphicsPrimitives.h.
 { return;}
void SoccerView::update (const QRectF & rect = QRectF()) inline
Definition at line 93 of file GraphicsPrimitives.h.
 {return;}
int SoccerView::UpdateBalls (QVector< QPointF > & _balls, int cameraID)
Definition at line 343 of file GraphicsPrimitives.cpp.
References Robot::brush, velocity.pid_::i, Robot::pen, Robot::x, and Robot::y.
Referenced by ViewUpdateThread::execute().
 {
   QVector<QGraphicsEllipseItem*> tmp;
   while(cameraID+1>ballItems.size())
     ballItems.append(tmp);
   if ( ballItems[cameraID].size() < _balls.size() ){
     //need to allocate some space for the new balls
     QPen pen ( QColor ( 0xcd,0x59,0x00,0xff ) );
     pen.setWidth ( 4 );
     QBrush brush ( QColor ( 0xff,0x81,0x00,0xff ),Qt::SolidPattern );
     while(_balls.size()>ballItems[cameraID].size()){
       ballItems[cameraID].append ( scene->addEllipse ( 0,0,42,42,pen,brush ) );
       ballItems[cameraID][ballItems[cameraID].size()-1]->setZValue(2);
     }
   }
   else if ( ballItems[cameraID].size() >_balls.size() ){
     //need to delete some balls
     while(ballItems[cameraID].size()>_balls.size()){
       scene->removeItem ( ballItems[cameraID][0] );
       ballItems[cameraID].remove(0);
     }
   }
   for ( int i=0;i<_balls.size();i++ ){
     //Let's update the ball positions now
     ballItems[cameraID][i]->setPos ( _balls[i].x()-21,-_balls[i].y()-21 );
   }
   int balls = ballItems[cameraID].size();
   return balls;
 }
void SoccerView::UpdateRobots (SSL_DetectionFrame & detection)
Definition at line 270 of file GraphicsPrimitives.cpp.
References Robot::conf, velocity.pid_::i, Robot::key, NA, NAOrientation, Robot::orientation, Robot::robotLabel, teamBlue, teamYellow, Robot::x, and Robot::y.
Referenced by ViewUpdateThread::execute().
 {
   int robots_blue_n =  detection.robots_blue_size();
   int robots_yellow_n =  detection.robots_yellow_size();
   int i,j,yellowj=0,bluej=0;
   int team=teamBlue;
   SSL_DetectionRobot robot;
   for ( i = 0; i < robots_blue_n+robots_yellow_n; i++ )
   {
     if ( i<robots_blue_n )
     {
       robot = detection.robots_blue ( i );
       team = teamBlue;
       j=bluej;
     }
     else
     {
       robot = detection.robots_yellow ( i-robots_blue_n );
       team = teamYellow;
       j=yellowj;
     }
     double x,y,orientation,conf =robot.confidence();
     int id=NA;
     if ( robot.has_robot_id() )
       id = robot.robot_id();
     else
       id = NA;
     x = robot.x();
     y = robot.y();
     if ( robot.has_orientation() )
       orientation = robot.orientation() *180.0/M_PI;
     else
       orientation = NAOrientation;
     //seek to the next robot of the same camera and team colour
     while ( j<robots.size() && ( robots[j]->key!=detection.camera_id() || robots[j]->teamID!=team ) )
       j++;
     if ( j+1>robots.size() )
       AddRobot ( new Robot ( x,y,orientation,team,id,detection.camera_id(),conf ) );
     robots[j]->SetPose ( x,y,orientation,conf );
     QString label;
     if ( id!=NA )
       label.setNum ( id,16 );
     else
       label = "?";
     label = label.toUpper();
     if ( label!=robots[j]->robotLabel )
       robots[j]->robotLabel = label;
     j++;
     if ( i<robots_blue_n )
       bluej=j;
     else
       yellowj=j;
   }
   for ( j=bluej;j<robots.size();j++ )
   {
     if ( robots[j]->key==detection.camera_id() && robots[j]->teamID==teamBlue )
       robots[j]->conf=0.0;
   }
   for ( j=yellowj;j<robots.size();j++ )
   {
     if ( robots[j]->key==detection.camera_id() && robots[j]->teamID==teamYellow )
       robots[j]->conf=0.0;
   }
   return;
 }
void SoccerView::updateView ()
Definition at line 196 of file GraphicsPrimitives.cpp.
Referenced by CentralWindow::CentralWindow(), and ViewUpdateThread::run().
 {
   if ( shutdownSoccerView )
   {
     return;
   }
   if ( scalingRequested )
   {
     qreal factor = matrix().scale ( drawScale, drawScale ).mapRect ( QRectF ( 0, 0, 1, 1 ) ).width();
     if ( factor > 0.07 && factor < 100.0 )
       scale ( drawScale, drawScale );
     scalingRequested = false;
   }
   //causes segfaults, update-queue is evil
   //*** glibc detected *** PATH/ssl-vision-read-only/bin/graphicalClient: malloc(): memory corruption (fast): 0xb15682f2 ***
   //  Program received signal SIGSEGV, Segmentation fault.
   //  [Switching to Thread 0xb494ab90 (LWP 13615)]
   //  0xb766db63 in QRegion::operator+= () from /usr/lib/libQtGui.so.4
   this->viewport()->update();
 }
void SoccerView::wheelEvent (QWheelEvent * event) protected
Definition at line 252 of file GraphicsPrimitives.cpp.
 {
   scrollMutex.lock();
   drawScale = pow ( 2.0, event->delta() / 540.0 );
   scalingRequested = true;
   drawMutex->lock();
   this->updateView();
   drawMutex->unlock();
   event->ignore();
   scrollMutex.unlock();
 }
Field Documentation
QBrush * SoccerView::ballBrush private
Definition at line 129 of file GraphicsPrimitives.h.
QVector< QVector<QGraphicsEllipseItem*> > SoccerView::ballItems private
Definition at line 121 of file GraphicsPrimitives.h.
QPen * SoccerView::ballPen private
Definition at line 130 of file GraphicsPrimitives.h.
QVector<Robot*> SoccerView::blueRobots private
Definition at line 119 of file GraphicsPrimitives.h.
QMutex* SoccerView::drawMutex protected
Definition at line 112 of file GraphicsPrimitives.h.
float SoccerView::drawScale protected
Definition at line 114 of file GraphicsPrimitives.h.
QPainterPath* SoccerView::field private
Definition at line 125 of file GraphicsPrimitives.h.
QBrush* SoccerView::fieldBrush private
Definition at line 129 of file GraphicsPrimitives.h.
QGraphicsPathItem* SoccerView::fieldItem private
Definition at line 126 of file GraphicsPrimitives.h.
QPen * SoccerView::fieldLinePen private
Definition at line 130 of file GraphicsPrimitives.h.
QPen* SoccerView::fieldPen private
Definition at line 130 of file GraphicsPrimitives.h.
QGLWidget* SoccerView::glWidget private
Definition at line 131 of file GraphicsPrimitives.h.
QPushButton* SoccerView::playLogfile
Definition at line 101 of file GraphicsPrimitives.h.
Referenced by ViewUpdateThread::ViewUpdateThread().
QVector<Robot*> SoccerView::robots private
Definition at line 119 of file GraphicsPrimitives.h.
bool SoccerView::scalingRequested protected
Definition at line 115 of file GraphicsPrimitives.h.
QGraphicsScene* SoccerView::scene private
Definition at line 123 of file GraphicsPrimitives.h.
QMutex SoccerView::scrollMutex protected
Definition at line 113 of file GraphicsPrimitives.h.
bool SoccerView::shutdownSoccerView private
Definition at line 132 of file GraphicsPrimitives.h.
QVector<Robot*> SoccerView::yellowRobots private
Definition at line 119 of file GraphicsPrimitives.h.
The documentation for this class was generated from the following files:
ssl-vision/src/logClient/GraphicsPrimitives.h
ssl-vision/src/logClient/GraphicsPrimitives.cpp