Documentation: GLSmoothCamera Class Reference
GLSmoothCamera Class Reference
A smoothly animated OpenGL camera class.
#include <glcamera.h>
Public Member Functions
GLSmoothCamera (bool _prevent_overshoot=true, double k_acceleration=20.0, double k_damping=10.0)
virtual ~GLSmoothCamera ()
void step (const double dt)
Public Member Functions inherited from GLCamera
quat getQuaternion ()
GLCamera ()
~GLCamera ()
void reset ()
virtual void apply ()
virtual void setState (const GLCamera &cam)
GLCAM_PAN_MODE_ENUM getPanMode ()
void setPanMode (GLCAM_PAN_MODE_ENUM mode)
void setDistance (double distance, bool allow_negative=false)
double getDistance ()
vector3d getLensPosition ()
void freeLookAt (const vector3d &point)
void lookAt (const vector3d &point)
void setEuler (double pitch, double yaw, double roll)
void setRoll (double roll)
void setPitch (double pitch)
void setYaw (double yaw)
void getEuler (double &pitch, double &yaw, double &roll)
double getRoll ()
double getPitch ()
double getYaw ()
void wheelEvent (QWheelEvent *event)
void keyPressEvent (QKeyEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
Public Member Functions inherited from GLObject
GLObject ()
virtual ~GLObject ()
void reset ()
Data Fields
GLCamera target
Data Fields inherited from GLCamera
vector3d forward
Data Fields inherited from GLObject
vector3d scale
vector3d pos
quat rot
Private Attributes
vector3d v_forward
vector3d v_pos
double v_angle
bool prevent_overshoot
double k_acc
double k_damp
Additional Inherited Members
Public Types inherited from GLCamera
enum GLCAM_PAN_MODE_ENUM { GLCAM_PAN_POSITION_CENTRIC, GLCAM_PAN_FREE_FLY }
Protected Member Functions inherited from GLCamera
virtual void preRender ()
virtual void postRender ()
virtual void render ()
void mouseAction (QMouseEvent *event)
Protected Attributes inherited from GLCamera
GLCAM_PAN_MODE_ENUM pan_mode
QPoint mouseStart_rotate
QPoint mouseStart_pan
double p_start
double y_start
double r_start
double pan_start_x
double pan_start_y
vector3d pan_start_pos
Detailed Description
A smoothly animated OpenGL camera class.
Author
Stefan Zickler
Definition at line 119 of file glcamera.h.
Constructor & Destructor Documentation
GLSmoothCamera::GLSmoothCamera (bool _prevent_overshoot = true, double k_acceleration = 20.0, double k_damping = 10.0) inline
Definition at line 130 of file glcamera.h.
References GVector::vector3d< num >::set().
{
     k_acc=k_acceleration;
     k_damp=k_damping;
     v_forward.set(0.0,0.0,0.0);
     v_pos.set(0.0,0.0,0.0);
     v_angle = 0.0;
     prevent_overshoot=_prevent_overshoot;
   };
virtual GLSmoothCamera::~GLSmoothCamera () inline virtual
Definition at line 138 of file glcamera.h.
 {};
Member Function Documentation
void GLSmoothCamera::step (const double dt) inline
Definition at line 139 of file glcamera.h.
References Quaternion< num >::blend(), velocity.pid::dt, GLCamera::forward, Quaternion< num >::getZvector(), GVector::vector3d< num >::length(), GLObject::pos, GLObject::rot, and GVector::shortest_angle().
{
     //compute transition "delta" vectors:
     //this is the actual distance to the target
     vector3d d_forward = target.forward - forward;
     vector3d d_pos     = target.pos - pos;
     double   d_angle   = GVector::shortest_angle(rot.getZvector(),target.rot.getZvector());
     if (std::isnan(d_angle)) d_angle=0.0;
     //compute spring forces:
     vector3d f_forward = d_forward * k_acc - v_forward * k_damp;
     vector3d f_pos   =   d_pos * k_acc     - v_pos * k_damp;
     double   f_angle   = d_angle * k_acc   - v_angle * k_damp;
     //integrate:
     vector3d vnew_forward = v_forward + (f_forward * dt);
     vector3d vnew_pos     = v_pos     + (f_pos * dt);
     double   vnew_angle   = v_angle   + (f_angle * dt);
     //compute how far we will move (our 'applied' delta positions)
     vector3d delta_forward = (vnew_forward+v_forward) * 0.5 * dt;
     vector3d delta_pos     = (vnew_pos+v_pos) * 0.5 * dt;
     double   delta_angle   = (vnew_angle+v_angle) * 0.5 * dt;
     if (prevent_overshoot) {
       //hardcoded fix against overshooting: if applied deltas are bigger than target deltas, then shrink em
       //we will now never, ever overshoot...although it might be desirable if the target is moving
       if (delta_forward.length() > d_forward.length()) delta_forward=d_forward;
       if (delta_pos.length() > d_pos.length()) delta_pos=d_pos;
       if (delta_angle > d_angle) delta_angle=d_angle;
     }
     //add deltas to position.
     pos+=delta_pos;
     forward+=delta_forward;
     //perform angular blending:
     double blend_n=delta_angle / d_angle;
     if (blend_n==0.0 || d_angle==0.0 || delta_angle==0.0 || std::isnan(blend_n)) {
       //don't rotate!
     } else {
       rot.blend(blend_n,target.rot);
     }
     fflush(stdout);
     v_forward=vnew_forward;
     v_pos=vnew_pos;
     v_angle=vnew_angle;
   };
Field Documentation
double GLSmoothCamera::k_acc private
Definition at line 126 of file glcamera.h.
double GLSmoothCamera::k_damp private
Definition at line 127 of file glcamera.h.
bool GLSmoothCamera::prevent_overshoot private
Definition at line 125 of file glcamera.h.
GLCamera GLSmoothCamera::target
Definition at line 129 of file glcamera.h.
double GLSmoothCamera::v_angle private
Definition at line 124 of file glcamera.h.
vector3d GLSmoothCamera::v_forward private
Definition at line 122 of file glcamera.h.
vector3d GLSmoothCamera::v_pos private
Definition at line 123 of file glcamera.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/gl/glcamera.h