Documentation: ssl-vision/build/qrc_icons.cxx File Reference
qrc_icons.cxx File Reference
#include <QtCore/qglobal.h>
Functions
QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Q_CORE_EXPORT bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_icons ()
int QT_MANGLE_NAMESPACE() qCleanupResources_icons ()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Function Documentation
int QT_MANGLE_NAMESPACE() qCleanupResources_icons ()
Definition at line 685 of file qrc_icons.cxx.
References qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
 {
     QT_PREPEND_NAMESPACE(qUnregisterResourceData)
        (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
     return 1;
 }
QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_icons ()
Definition at line 676 of file qrc_icons.cxx.
References qRegisterResourceData(), qt_resource_data, qt_resource_name, and qt_resource_struct.
 {
     QT_PREPEND_NAMESPACE(qRegisterResourceData)
         (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
     return 1;
 }
QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool qRegisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qInitResources_icons().
Q_CORE_EXPORT bool qUnregisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qCleanupResources_icons().
Variable Documentation
const unsigned char qt_resource_data[] static
Definition at line 11 of file qrc_icons.cxx.
Referenced by qCleanupResources_icons(), and qInitResources_icons().
const unsigned char qt_resource_name[] static
Definition at line 613 of file qrc_icons.cxx.
Referenced by qCleanupResources_icons(), and qInitResources_icons().
const unsigned char qt_resource_struct[] static
Initial value:
= {
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x1,
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x2,
  0x0,0x0,0x0,0x10,0x0,0x2,0x0,0x0,0x0,0x4,0x0,0x0,0x0,0x3,
  0x0,0x0,0x0,0x70,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x19,0xe5,
  0x0,0x0,0x0,0x3c,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x8,0x6f,
  0x0,0x0,0x0,0x26,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,
  0x0,0x0,0x0,0x52,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x10,0x96,
}
Definition at line 647 of file qrc_icons.cxx.
Referenced by qCleanupResources_icons(), and qInitResources_icons().