Documentation: grsim_comm/include/proto/messages_robocup_ssl_wrapper.pb.cc File Reference
messages_robocup_ssl_wrapper.pb.cc File Reference
#include "messages_robocup_ssl_wrapper.pb.h"
#include <algorithm>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
Data Structures
class SSL_WrapperPacketDefaultTypeInternal
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5fwrapper_2eproto
Namespaces
anonymous_namespace{messages_robocup_ssl_wrapper.pb.cc}
Macros
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Functions
const ::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5fwrapper_2eproto () GOOGLE_ATTRIBUTE_COLD
void anonymous_namespace{messages_robocup_ssl_wrapper.pb.cc}::protobuf_AssignDescriptors ()
void anonymous_namespace{messages_robocup_ssl_wrapper.pb.cc}::protobuf_AssignDescriptorsOnce ()
void anonymous_namespace{messages_robocup_ssl_wrapper.pb.cc}::protobuf_RegisterTypes (const ::std::string &) GOOGLE_ATTRIBUTE_COLD
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fwrapper_2eproto ()
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto_impl ()
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto ()
void protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_impl ()
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_once_)
void protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto ()
Variables
SSL_WrapperPacketDefaultTypeInternal _SSL_WrapperPacket_default_instance_
::google::protobuf::Metadata anonymous_namespace{messages_robocup_ssl_wrapper.pb.cc}::file_level_metadata [1]
static const ::google::protobuf::internal::MigrationSchema schemas []
static const ::google::protobuf::internal::DefaultInstanceData file_default_instances []
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5fwrapper_2eproto static_descriptor_initializer_messages_5frobocup_5fssl_5fwrapper_2eproto_
Macro Definition Documentation
#define DO_ (EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
Referenced by SSL_WrapperPacket::MergePartialFromCodedStream().
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
Definition at line 4 of file messages_robocup_ssl_wrapper.pb.cc.
Function Documentation
GOOGLE_PROTOBUF_DECLARE_ONCE (protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_once_)
Referenced by protobuf_messages_5frobocup_5fssl_5fwrapper_2eproto::AddDescriptors(), protobuf_messages_5frobocup_5fssl_5fwrapper_2eproto::InitDefaultsSSL_WrapperPacket(), protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_impl(), anonymous_namespace{messages_robocup_ssl_wrapper.pb.cc}::protobuf_AssignDescriptorsOnce(), protobuf_messages_5frobocup_5fssl_5fwrapper_2eproto::protobuf_AssignDescriptorsOnce(), and protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto().
void protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto ()
Definition at line 117 of file messages_robocup_ssl_wrapper.pb.cc.
References protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_impl().
Referenced by anonymous_namespace{messages_robocup_ssl_wrapper.pb.cc}::protobuf_AssignDescriptors(), and StaticDescriptorInitializer_messages_5frobocup_5fssl_5fwrapper_2eproto::StaticDescriptorInitializer_messages_5frobocup_5fssl_5fwrapper_2eproto().
{
   ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_once_,
                  &protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_impl);
 }
void protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_impl ()
Definition at line 97 of file messages_robocup_ssl_wrapper.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto(), protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto(), protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto(), protobuf_messages_5frobocup_5fssl_5fwrapper_2eproto::protobuf_RegisterTypes(), and protobuf_ShutdownFile_messages_5frobocup_5fssl_5fwrapper_2eproto().
Referenced by protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto().
{
   protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto();
   static const char descriptor[] = {
       "\n\"messages_robocup_ssl_wrapper.proto\032$me"
       "ssages_robocup_ssl_detection.proto\032#mess"
       "ages_robocup_ssl_geometry.proto\"`\n\021SSL_W"
       "rapperPacket\022&\n\tdetection\030\001 \001(\0132\023.SSL_De"
       "tectionFrame\022#\n\010geometry\030\002 \001(\0132\021.SSL_Geo"
       "metryData"
   };
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
       descriptor, 209);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "messages_robocup_ssl_wrapper.proto", &protobuf_RegisterTypes);
   ::protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
   ::protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
   ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_messages_5frobocup_5fssl_5fwrapper_2eproto);
 }
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto ()
Definition at line 93 of file messages_robocup_ssl_wrapper.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), and protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto_impl().
Referenced by SSL_WrapperPacket::default_instance(), protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_impl(), and SSL_WrapperPacket::SSL_WrapperPacket().
{
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
   ::google::protobuf::GoogleOnceInit(&once, &protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto_impl);
 }
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto_impl ()
Definition at line 80 of file messages_robocup_ssl_wrapper.pb.cc.
References SSL_DetectionFrame::internal_default_instance(), SSL_GeometryData::internal_default_instance(), protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto(), and protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto().
Referenced by protobuf_InitDefaults_messages_5frobocup_5fssl_5fwrapper_2eproto().
{
   GOOGLE_PROTOBUF_VERIFY_VERSION;
   ::protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto();
   ::protobuf_InitDefaults_messages_5frobocup_5fssl_5fgeometry_2eproto();
   ::google::protobuf::internal::InitProtobufDefaults();
   _SSL_WrapperPacket_default_instance_.DefaultConstruct();
   _SSL_WrapperPacket_default_instance_.get_mutable()->detection_ = const_cast< ::SSL_DetectionFrame*>(
       ::SSL_DetectionFrame::internal_default_instance());
   _SSL_WrapperPacket_default_instance_.get_mutable()->geometry_ = const_cast< ::SSL_GeometryData*>(
       ::SSL_GeometryData::internal_default_instance());
 }
const ::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5fwrapper_2eproto ()
Definition at line 30 of file messages_robocup_ssl_wrapper.pb.cc.
Referenced by anonymous_namespace{messages_robocup_ssl_wrapper.pb.cc}::protobuf_AssignDescriptors().
{
   static const ::google::protobuf::uint32 offsets[] = {
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_WrapperPacket, _has_bits_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_WrapperPacket, _internal_metadata_),
     ~0u,  // no _extensions_
     ~0u,  // no _oneof_case_
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_WrapperPacket, detection_),
     GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_WrapperPacket, geometry_),
     0,
     1,
   };
   return offsets;
 }
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fwrapper_2eproto ()
Definition at line 75 of file messages_robocup_ssl_wrapper.pb.cc.
References protobuf_messages_5frobocup_5fssl_5fwrapper_2eproto::file_level_metadata.
Referenced by protobuf_AddDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_impl().
{
   _SSL_WrapperPacket_default_instance_.Shutdown();
   delete file_level_metadata[0].reflection;
 }
Variable Documentation
SSL_WrapperPacketDefaultTypeInternal _SSL_WrapperPacket_default_instance_
Definition at line 20 of file messages_robocup_ssl_wrapper.pb.cc.
Referenced by SSL_WrapperPacket::InitAsDefaultInstance(), protobuf_messages_5frobocup_5fssl_5fwrapper_2eproto::InitDefaultsSSL_WrapperPacketImpl(), and RoboCup2014Legacy::Wrapper::SSL_WrapperPacket::internal_default_instance().
const ::google::protobuf::internal::DefaultInstanceData file_default_instances[] static
Initial value:
= {
  {reinterpret_cast<const ::google::protobuf::Message*>(&_SSL_WrapperPacket_default_instance_), NULL},
}
Definition at line 48 of file messages_robocup_ssl_wrapper.pb.cc.
Referenced by anonymous_namespace{messages_robocup_ssl_wrapper.pb.cc}::protobuf_AssignDescriptors().
const ::google::protobuf::internal::MigrationSchema schemas[] static
Initial value:
= {
  { 0, 6, sizeof(SSL_WrapperPacket)},
}
Definition at line 44 of file messages_robocup_ssl_wrapper.pb.cc.
Referenced by anonymous_namespace{messages_robocup_ssl_wrapper.pb.cc}::protobuf_AssignDescriptors(), and protobuf_messages_5frobocup_5fssl_5fwrapper_2eproto::protobuf_AssignDescriptors().
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5fwrapper_2eproto static_descriptor_initializer_messages_5frobocup_5fssl_5fwrapper_2eproto_
Referenced by StaticDescriptorInitializer_messages_5frobocup_5fssl_5fwrapper_2eproto::StaticDescriptorInitializer_messages_5frobocup_5fssl_5fwrapper_2eproto().