Documentation: Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall Class Reference
Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall Class Reference
Data Structures
class Builder
Public Member Functions
SSL_DetectionBall getDefaultInstanceForType ()
boolean hasConfidence ()
float getConfidence ()
boolean hasArea ()
int getArea ()
boolean hasX ()
float getX ()
boolean hasY ()
float getY ()
boolean hasZ ()
float getZ ()
boolean hasPixelX ()
float getPixelX ()
boolean hasPixelY ()
float getPixelY ()
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static SSL_DetectionBall getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static MessagesRobocupSslDetection.SSL_DetectionBall parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslDetection.SSL_DetectionBall parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslDetection.SSL_DetectionBall parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslDetection.SSL_DetectionBall parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslDetection.SSL_DetectionBall parseFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionBall parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionBall parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionBall parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionBall parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static MessagesRobocupSslDetection.SSL_DetectionBall parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (MessagesRobocupSslDetection.SSL_DetectionBall prototype)
Static Public Attributes
static final int CONFIDENCE_FIELD_NUMBER = 1
static final int AREA_FIELD_NUMBER = 2
static final int X_FIELD_NUMBER = 3
static final int Y_FIELD_NUMBER = 4
static final int Z_FIELD_NUMBER = 5
static final int PIXEL_X_FIELD_NUMBER = 6
static final int PIXEL_Y_FIELD_NUMBER = 7
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
SSL_DetectionBall (Builder builder)
SSL_DetectionBall (boolean noInit)
void initFields ()
Private Attributes
int bitField0_
float confidence_
int area_
float x_
float y_
float z_
float pixelX_
float pixelY_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final SSL_DetectionBall defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 42 of file MessagesRobocupSslDetection.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.SSL_DetectionBall (Builder builder) inline private
Definition at line 46 of file MessagesRobocupSslDetection.java.
{
       super(builder);
     }
Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.SSL_DetectionBall (boolean noInit) inline private
Definition at line 49 of file MessagesRobocupSslDetection.java.
 {}
Member Function Documentation
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getArea () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 87 of file MessagesRobocupSslDetection.java.
{
       return area_;
     }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getConfidence () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 77 of file MessagesRobocupSslDetection.java.
{
       return confidence_;
     }
static SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getDefaultInstance () inline static
Definition at line 52 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.addBallsBuilder(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.getDefaultInstanceForType(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.mergeFrom().
{
       return defaultInstance;
     }
SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getDefaultInstanceForType () inline
Definition at line 56 of file MessagesRobocupSslDetection.java.
{
       return defaultInstance;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getDescriptor () inline static
Definition at line 61 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.internal_static_SSL_DetectionBall_descriptor.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.getDescriptorForType().
{
       return MessagesRobocupSslDetection.internal_static_SSL_DetectionBall_descriptor;
     }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getPixelX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 127 of file MessagesRobocupSslDetection.java.
{
       return pixelX_;
     }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getPixelY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 137 of file MessagesRobocupSslDetection.java.
{
       return pixelY_;
     }
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getSerializedSize () inline
Definition at line 207 of file MessagesRobocupSslDetection.java.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(1, confidence_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         size += com.google.protobuf.CodedOutputStream
           .computeUInt32Size(2, area_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(3, x_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(4, y_);
       }
       if (((bitField0_ & 0x00000010) == 0x00000010)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(5, z_);
       }
       if (((bitField0_ & 0x00000020) == 0x00000020)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(6, pixelX_);
       }
       if (((bitField0_ & 0x00000040) == 0x00000040)) {
         size += com.google.protobuf.CodedOutputStream
           .computeFloatSize(7, pixelY_);
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 97 of file MessagesRobocupSslDetection.java.
{
       return x_;
     }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 107 of file MessagesRobocupSslDetection.java.
{
       return y_;
     }
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.getZ () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 117 of file MessagesRobocupSslDetection.java.
{
       return z_;
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.hasArea () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 84 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000002) == 0x00000002);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.hasConfidence () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 74 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.hasPixelX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 124 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000020) == 0x00000020);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.hasPixelY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 134 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000040) == 0x00000040);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.hasX () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 94 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000004) == 0x00000004);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.hasY () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 104 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000008) == 0x00000008);
     }
boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.hasZ () inline
Implements Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.
Definition at line 114 of file MessagesRobocupSslDetection.java.
{
       return ((bitField0_ & 0x00000010) == 0x00000010);
     }
void Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.initFields () inline private
Definition at line 141 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.clearPixelY().
{
       confidence_ = 0F;
       area_ = 0;
       x_ = 0F;
       y_ = 0F;
       z_ = 0F;
       pixelX_ = 0F;
       pixelY_ = 0F;
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.internalGetFieldAccessorTable () inline protected
Definition at line 66 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.internal_static_SSL_DetectionBall_fieldAccessorTable.
{
       return MessagesRobocupSslDetection.internal_static_SSL_DetectionBall_fieldAccessorTable;
     }
final boolean Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.isInitialized () inline
Definition at line 151 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasConfidence(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasPixelX(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasPixelY(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasX(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionBallOrBuilder.hasY().
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (!hasConfidence()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasX()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasY()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasPixelX()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasPixelY()) {
         memoizedIsInitialized = 0;
         return false;
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.newBuilder () inline static
Definition at line 319 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.create().
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom().
 { return Builder.create(); }
static Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.newBuilder (MessagesRobocupSslDetection.SSL_DetectionBall prototype) inline static
Definition at line 321 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.newBuilderForType () inline
Definition at line 320 of file MessagesRobocupSslDetection.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 327 of file MessagesRobocupSslDetection.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 286 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 295 of file MessagesRobocupSslDetection.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 252 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 257 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 264 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 268 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 275 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 279 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 306 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslDetection.SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 311 of file MessagesRobocupSslDetection.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.toBuilder () inline
Definition at line 324 of file MessagesRobocupSslDetection.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 247 of file MessagesRobocupSslDetection.java.
{
       return super.writeReplace();
     }
void Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 179 of file MessagesRobocupSslDetection.java.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeFloat(1, confidence_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         output.writeUInt32(2, area_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         output.writeFloat(3, x_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         output.writeFloat(4, y_);
       }
       if (((bitField0_ & 0x00000010) == 0x00000010)) {
         output.writeFloat(5, z_);
       }
       if (((bitField0_ & 0x00000020) == 0x00000020)) {
         output.writeFloat(6, pixelX_);
       }
       if (((bitField0_ & 0x00000040) == 0x00000040)) {
         output.writeFloat(7, pixelY_);
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.area_ private
Definition at line 83 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.AREA_FIELD_NUMBER = 2 static
Definition at line 82 of file MessagesRobocupSslDetection.java.
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.bitField0_ private
Definition at line 70 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.confidence_ private
Definition at line 73 of file MessagesRobocupSslDetection.java.
Referenced by Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Builder.buildPartial().
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.CONFIDENCE_FIELD_NUMBER = 1 static
Definition at line 72 of file MessagesRobocupSslDetection.java.
final SSL_DetectionBall Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.defaultInstance static private
Definition at line 51 of file MessagesRobocupSslDetection.java.
byte Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.memoizedIsInitialized = -1 private
Definition at line 150 of file MessagesRobocupSslDetection.java.
int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.memoizedSerializedSize = -1 private
Definition at line 206 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.PIXEL_X_FIELD_NUMBER = 6 static
Definition at line 122 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.PIXEL_Y_FIELD_NUMBER = 7 static
Definition at line 132 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.pixelX_ private
Definition at line 123 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.pixelY_ private
Definition at line 133 of file MessagesRobocupSslDetection.java.
final long Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.serialVersionUID = 0L static private
Definition at line 245 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.x_ private
Definition at line 93 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.X_FIELD_NUMBER = 3 static
Definition at line 92 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.y_ private
Definition at line 103 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Y_FIELD_NUMBER = 4 static
Definition at line 102 of file MessagesRobocupSslDetection.java.
float Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.z_ private
Definition at line 113 of file MessagesRobocupSslDetection.java.
final int Protobuf.MessagesRobocupSslDetection.SSL_DetectionBall.Z_FIELD_NUMBER = 5 static
Definition at line 112 of file MessagesRobocupSslDetection.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslDetection.java