Documentation: Protobuf.MessagesRobocupSslRefboxLog.Log_Frame Class Reference
Protobuf.MessagesRobocupSslRefboxLog.Log_Frame Class Reference
Data Structures
class Builder
Public Member Functions
Log_Frame getDefaultInstanceForType ()
boolean hasFrame ()
MessagesRobocupSslDetection.SSL_DetectionFrame getFrame ()
MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getFrameOrBuilder ()
boolean hasRefboxCmd ()
String getRefboxCmd ()
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static Log_Frame getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static MessagesRobocupSslRefboxLog.Log_Frame parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslRefboxLog.Log_Frame parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslRefboxLog.Log_Frame parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslRefboxLog.Log_Frame parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslRefboxLog.Log_Frame parseFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslRefboxLog.Log_Frame parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslRefboxLog.Log_Frame parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslRefboxLog.Log_Frame parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslRefboxLog.Log_Frame parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static MessagesRobocupSslRefboxLog.Log_Frame parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (MessagesRobocupSslRefboxLog.Log_Frame prototype)
Static Public Attributes
static final int FRAME_FIELD_NUMBER = 1
static final int REFBOX_CMD_FIELD_NUMBER = 2
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
Log_Frame (Builder builder)
Log_Frame (boolean noInit)
com.google.protobuf.ByteString getRefboxCmdBytes ()
void initFields ()
Private Attributes
int bitField0_
MessagesRobocupSslDetection.SSL_DetectionFrame frame_
java.lang.Object refboxCmd_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final Log_Frame defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 23 of file MessagesRobocupSslRefboxLog.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Log_Frame (Builder builder) inline private
Definition at line 27 of file MessagesRobocupSslRefboxLog.java.
{
       super(builder);
     }
Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Log_Frame (boolean noInit) inline private
Definition at line 30 of file MessagesRobocupSslRefboxLog.java.
 {}
Member Function Documentation
static Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance () inline static
Definition at line 33 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.addLogBuilder(), Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.getDefaultInstanceForType(), and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrom().
{
       return defaultInstance;
     }
Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstanceForType () inline
Definition at line 37 of file MessagesRobocupSslRefboxLog.java.
{
       return defaultInstance;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getDescriptor () inline static
Definition at line 42 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.internal_static_Log_Frame_descriptor.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.getDescriptorForType().
{
       return MessagesRobocupSslRefboxLog.internal_static_Log_Frame_descriptor;
     }
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getFrame () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.
Definition at line 58 of file MessagesRobocupSslRefboxLog.java.
{
       return frame_;
     }
MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getFrameOrBuilder () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.
Definition at line 61 of file MessagesRobocupSslRefboxLog.java.
{
       return frame_;
     }
String Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getRefboxCmd () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.
Definition at line 71 of file MessagesRobocupSslRefboxLog.java.
{
       java.lang.Object ref = refboxCmd_;
       if (ref instanceof String) {
         return (String) ref;
       } else {
         com.google.protobuf.ByteString bs =
             (com.google.protobuf.ByteString) ref;
         String s = bs.toStringUtf8();
         if (com.google.protobuf.Internal.isValidUtf8(bs)) {
           refboxCmd_ = s;
         }
         return s;
       }
     }
com.google.protobuf.ByteString Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getRefboxCmdBytes () inline private
Definition at line 85 of file MessagesRobocupSslRefboxLog.java.
{
       java.lang.Object ref = refboxCmd_;
       if (ref instanceof String) {
         com.google.protobuf.ByteString b =
             com.google.protobuf.ByteString.copyFromUtf8((String) ref);
         refboxCmd_ = b;
         return b;
       } else {
         return (com.google.protobuf.ByteString) ref;
       }
     }
int Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getSerializedSize () inline
Definition at line 135 of file MessagesRobocupSslRefboxLog.java.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(1, frame_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         size += com.google.protobuf.CodedOutputStream
           .computeBytesSize(2, getRefboxCmdBytes());
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
boolean Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.hasFrame () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.
Definition at line 55 of file MessagesRobocupSslRefboxLog.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
boolean Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.hasRefboxCmd () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.
Definition at line 68 of file MessagesRobocupSslRefboxLog.java.
{
       return ((bitField0_ & 0x00000002) == 0x00000002);
     }
void Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.initFields () inline private
Definition at line 97 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance().
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.clearRefboxCmd().
{
       frame_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
       refboxCmd_ = "";
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.internalGetFieldAccessorTable () inline protected
Definition at line 47 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.internal_static_Log_Frame_fieldAccessorTable.
{
       return MessagesRobocupSslRefboxLog.internal_static_Log_Frame_fieldAccessorTable;
     }
final boolean Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.isInitialized () inline
Definition at line 102 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.getFrame(), Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.hasFrame(), and Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.hasRefboxCmd().
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (!hasFrame()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasRefboxCmd()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!getFrame().isInitialized()) {
         memoizedIsInitialized = 0;
         return false;
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.newBuilder () inline static
Definition at line 227 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.create().
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.mergeFrom().
 { return Builder.create(); }
static Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.newBuilder (MessagesRobocupSslRefboxLog.Log_Frame prototype) inline static
Definition at line 229 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.newBuilderForType () inline
Definition at line 228 of file MessagesRobocupSslRefboxLog.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 235 of file MessagesRobocupSslRefboxLog.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 194 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 203 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 160 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 165 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 172 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 176 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 183 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 187 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 214 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 219 of file MessagesRobocupSslRefboxLog.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.toBuilder () inline
Definition at line 232 of file MessagesRobocupSslRefboxLog.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 155 of file MessagesRobocupSslRefboxLog.java.
{
       return super.writeReplace();
     }
void Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 122 of file MessagesRobocupSslRefboxLog.java.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeMessage(1, frame_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         output.writeBytes(2, getRefboxCmdBytes());
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
int Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.bitField0_ private
Definition at line 51 of file MessagesRobocupSslRefboxLog.java.
final Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.defaultInstance static private
Definition at line 32 of file MessagesRobocupSslRefboxLog.java.
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.frame_ private
Definition at line 54 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.buildPartial().
final int Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.FRAME_FIELD_NUMBER = 1 static
Definition at line 53 of file MessagesRobocupSslRefboxLog.java.
byte Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.memoizedIsInitialized = -1 private
Definition at line 101 of file MessagesRobocupSslRefboxLog.java.
int Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.memoizedSerializedSize = -1 private
Definition at line 134 of file MessagesRobocupSslRefboxLog.java.
final int Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.REFBOX_CMD_FIELD_NUMBER = 2 static
Definition at line 66 of file MessagesRobocupSslRefboxLog.java.
java.lang.Object Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.refboxCmd_ private
Definition at line 67 of file MessagesRobocupSslRefboxLog.java.
final long Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.serialVersionUID = 0L static private
Definition at line 153 of file MessagesRobocupSslRefboxLog.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslRefboxLog.java