Documentation: Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder Interface Reference
Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder Interface Reference
Public Member Functions
boolean hasFrame ()
MessagesRobocupSslDetection.SSL_DetectionFrame getFrame ()
MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getFrameOrBuilder ()
boolean hasRefboxCmd ()
String getRefboxCmd ()
Detailed Description
Definition at line 11 of file MessagesRobocupSslRefboxLog.java.
Member Function Documentation
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.getFrame ()
Implemented in Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder, and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.isInitialized(), Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.isInitialized(), and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrom().
MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.getFrameOrBuilder ()
Implemented in Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder, and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.
String Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.getRefboxCmd ()
Implemented in Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder, and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.
boolean Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.hasFrame ()
Implemented in Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder, and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.isInitialized(), Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.isInitialized(), and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrom().
boolean Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.hasRefboxCmd ()
Implemented in Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder, and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.isInitialized(), and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.isInitialized().
The documentation for this interface was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslRefboxLog.java