Documentation: VarTypes::XMLNode Struct Reference
VarTypes::XMLNode Struct Reference
#include <xmlParser.h>
Data Structures
struct XMLNodeDataTag
Public Member Functions
const char * getName () const
const char * getText (int i=0) const
int nText () const
XMLNode getParentNode () const
XMLNode getChildNode (int i=0) const
XMLNode getChildNode (const char *name, int i) const
XMLNode getChildNode (const char *name, int *i=NULL) const
XMLNode getChildNodeWithAttribute (const char *tagName, const char *attributeName, const char *attributeValue=NULL, int *i=NULL) const
int nChildNode (const char *name) const
int nChildNode () const
XMLAttribute getAttribute (int i=0) const
const char * getAttributeName (int i=0) const
const char * getAttributeValue (int i=0) const
char isAttributeSet (const char *name) const
const char * getAttribute (const char *name, int i) const
const char * getAttribute (const char *name, int *i=NULL) const
int nAttribute () const
XMLClear getClear (int i=0) const
int nClear () const
char * createXMLString (int nFormat=1, int *pnSize=NULL) const
XMLError writeToFile (const char *filename, const char *encoding=NULL, char nFormat=1) const
XMLNodeContents enumContents (int i) const
int nElement () const
char isEmpty () const
char isDeclaration () const
~XMLNode ()
XMLNode (const XMLNode &A)
XMLNode & operator= (const XMLNode &A)
XMLNode ()
XMLNode addChild (const char *lpszName, char isDeclaration=0, int pos=-1)
XMLAttribute * addAttribute (const char *lpszName, const char *lpszValuev)
const char * addText (const char *lpszValue, int pos=-1)
XMLClear * addClear (const char *lpszValue, const char *lpszOpen=NULL, const char *lpszClose=NULL, int pos=-1)
XMLNode addChild (XMLNode nodeToAdd, int pos=-1)
const char * updateName (const char *lpszName)
XMLAttribute * updateAttribute (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
XMLAttribute * updateAttribute (const char *lpszNewValue, const char *lpszNewName=NULL, int i=0)
XMLAttribute * updateAttribute (const char *lpszNewValue, const char *lpszNewName, const char *lpszOldName)
const char * updateText (const char *lpszNewValue, int i=0)
const char * updateText (const char *lpszNewValue, const char *lpszOldValue)
XMLClear * updateClear (const char *lpszNewContent, int i=0)
XMLClear * updateClear (XMLClear *newP, XMLClear *oldP)
XMLClear * updateClear (const char *lpszNewValue, const char *lpszOldValue)
void deleteNodeContent (char force=0)
void deleteAttribute (const char *lpszName)
void deleteAttribute (int i=0)
void deleteAttribute (XMLAttribute *anAttribute)
void deleteText (int i=0)
void deleteText (const char *lpszValue)
void deleteClear (int i=0)
void deleteClear (XMLClear *p)
void deleteClear (const char *lpszValue)
XMLNode addChild_WOSD (const char *lpszName, char isDeclaration=0, int pos=-1)
XMLAttribute * addAttribute_WOSD (const char *lpszName, const char *lpszValue)
const char * addText_WOSD (const char *lpszValue, int pos=-1)
XMLClear * addClear_WOSD (const char *lpszValue, const char *lpszOpen=NULL, const char *lpszClose=NULL, int pos=-1)
const char * updateName_WOSD (const char *lpszName)
XMLAttribute * updateAttribute_WOSD (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
XMLAttribute * updateAttribute_WOSD (const char *lpszNewValue, const char *lpszNewName=NULL, int i=0)
XMLAttribute * updateAttribute_WOSD (const char *lpszNewValue, const char *lpszNewName, const char *lpszOldName)
const char * updateText_WOSD (const char *lpszNewValue, int i=0)
const char * updateText_WOSD (const char *lpszNewValue, const char *lpszOldValue)
XMLClear * updateClear_WOSD (const char *lpszNewContent, int i=0)
XMLClear * updateClear_WOSD (XMLClear *newP, XMLClear *oldP)
XMLClear * updateClear_WOSD (const char *lpszNewValue, const char *lpszOldValue)
int positionOfText (int i=0) const
int positionOfText (const char *lpszValue) const
int positionOfClear (int i=0) const
int positionOfClear (const char *lpszValue) const
int positionOfClear (XMLClear *a) const
int positionOfChildNode (int i=0) const
int positionOfChildNode (XMLNode x) const
int positionOfChildNode (const char *name, int i=0) const
Static Public Member Functions
static XMLNode createXMLTopNode (const char *lpszName, char isDeclaration=0)
static XMLNode parseString (const char *lpXMLString, const char *tag=NULL, XMLResults *pResults=NULL)
static XMLNode parseFile (const char *filename, const char *tag=NULL, XMLResults *pResults=NULL)
static XMLNode openFileHelper (const char *filename, const char *tag=NULL)
static const char * getError (XMLError error)
static const char * getVersion ()
static ALLXMLClearTag * getClearTagTable ()
static XMLNode createXMLTopNode_WOSD (const char *lpszName, char isDeclaration=0)
static void setGlobalOptions (char guessUnicodeChars=1, char strictUTF8Parsing=1, char dropWhiteSpace=1)
static char guessUTF8ParsingParameterValue (void *buffer, int bufLen, char useXMLEncodingAttribute=1)
Static Public Attributes
static XMLNode emptyXMLNode
static XMLClear emptyXMLClear ={ NULL, NULL, NULL}
static XMLAttribute emptyXMLAttribute ={ NULL, NULL}
Private Types
typedef struct VarTypes::XMLNode::XMLNodeDataTag XMLNodeData
Private Member Functions
XMLNode (struct XMLNodeDataTag *pParent, const char *lpszName, char isDeclaration)
XMLNode (struct XMLNodeDataTag *p)
char parseClearTag (void *px, ALLXMLClearTag *pa)
char maybeAddTxT (void *pa, const char *tokenPStr)
int ParseXMLElement (void *pXML)
void * addToOrder (int memInc, int *_pos, int nc, void *p, int size, XMLElementType xtype)
int indexText (const char *lpszValue) const
int indexClear (const char *lpszValue) const
XMLNode addChild_priv (int, const char *, char, int)
XMLAttribute * addAttribute_priv (int, const char *, const char *)
const char * addText_priv (int, const char *, int)
XMLClear * addClear_priv (int, const char *, const char *, const char *, int)
Static Private Member Functions
static int findPosition (XMLNodeData *d, int index, XMLElementType xtype)
static int CreateXMLStringR (XMLNodeData *pEntry, char *lpszMarker, int nFormat)
static int removeOrderElement (XMLNodeData *d, XMLElementType t, int index)
static void exactMemory (XMLNodeData *d)
static int detachFromParent (XMLNodeData *d)
Private Attributes
XMLNodeData * d
Detailed Description
Definition at line 177 of file xmlParser.h.
Member Typedef Documentation
typedef struct VarTypes::XMLNode::XMLNodeDataTag VarTypes::XMLNode::XMLNodeData private
Constructor & Destructor Documentation
VarTypes::XMLNode::XMLNode (struct XMLNodeDataTag * pParent, const char * lpszName, char isDeclaration) private
Definition at line 924 of file xmlParser.cpp.
References d, isDeclaration(), VarTypes::XMLNode::XMLNodeDataTag::isDeclaration, VarTypes::XMLNode::XMLNodeDataTag::lpszName, VarTypes::XMLNode::XMLNodeDataTag::nAttribute, VarTypes::XMLNode::XMLNodeDataTag::nChild, VarTypes::XMLNode::XMLNodeDataTag::nClear, VarTypes::XMLNode::XMLNodeDataTag::nText, VarTypes::XMLNode::XMLNodeDataTag::pAttribute, VarTypes::XMLNode::XMLNodeDataTag::pChild, VarTypes::XMLNode::XMLNodeDataTag::pClear, VarTypes::XMLNode::XMLNodeDataTag::pOrder, VarTypes::XMLNode::XMLNodeDataTag::pParent, VarTypes::XMLNode::XMLNodeDataTag::pText, VarTypes::XMLNode::XMLNodeDataTag::ref_count, and updateName_WOSD().
   {
       d=(XMLNodeData*)malloc(sizeof(XMLNodeData));
       d->ref_count=1;
       d->lpszName=NULL;
       d->nChild= 0;
       d->nText = 0;
       d->nClear = 0;
       d->nAttribute = 0;
       d->isDeclaration = isDeclaration;
       d->pParent = pParent;
       d->pChild= NULL;
       d->pText= NULL;
       d->pClear= NULL;
       d->pAttribute= NULL;
       d->pOrder= NULL;
       updateName_WOSD(lpszName);
   }
VarTypes::XMLNode::XMLNode (struct XMLNodeDataTag * p) private
Definition at line 923 of file xmlParser.cpp.
References d, and VarTypes::XMLNode::XMLNodeDataTag::ref_count.
 { d=p; (p->ref_count)++; }
VarTypes::XMLNode::~XMLNode ()
Definition at line 1978 of file xmlParser.cpp.
References deleteNodeContent().
 { deleteNodeContent(); }
VarTypes::XMLNode::XMLNode (const XMLNode & A)
Definition at line 2183 of file xmlParser.cpp.
References d, and VarTypes::XMLNode::XMLNodeDataTag::ref_count.
   {
       // shallow copy
       d=A.d;
       if (d) (d->ref_count)++ ;
   }
VarTypes::XMLNode::XMLNode () inline
Definition at line 276 of file xmlParser.h.
Referenced by addChild_priv(), createXMLTopNode(), createXMLTopNode_WOSD(), and getParentNode().
 : d(NULL){};
Member Function Documentation
XMLAttribute * VarTypes::XMLNode::addAttribute (const char * lpszName, const char * lpszValuev)
Definition at line 2366 of file xmlParser.cpp.
References addAttribute_priv(), and VarTypes::stringDup().
                 { return addAttribute_priv(0,stringDup(lpszName),stringDup(lpszValue)); }
XMLAttribute * VarTypes::XMLNode::addAttribute_priv (int memoryIncrease, const char * lpszName, const char * lpszValuev) private
Definition at line 1023 of file xmlParser.cpp.
References d, emptyXMLAttribute, VarTypes::XMLAttribute::lpszName, VarTypes::XMLAttribute::lpszValue, VarTypes::myRealloc(), VarTypes::XMLNode::XMLNodeDataTag::nAttribute, and VarTypes::XMLNode::XMLNodeDataTag::pAttribute.
Referenced by addAttribute(), addAttribute_WOSD(), and ParseXMLElement().
   {
       if (!lpszName) return &emptyXMLAttribute;
       int nc=d->nAttribute;
       d->pAttribute=(XMLAttribute*)myRealloc(d->pAttribute,(nc+1),memoryIncrease,sizeof(XMLAttribute));
       XMLAttribute *pAttr=d->pAttribute+nc;
       pAttr->lpszName = lpszName;
       pAttr->lpszValue = lpszValuev;
       d->nAttribute++;
       return pAttr;
   }
XMLAttribute * VarTypes::XMLNode::addAttribute_WOSD (const char * lpszName, const char * lpszValue)
Definition at line 2368 of file xmlParser.cpp.
References addAttribute_priv().
Referenced by updateAttribute_WOSD().
                 { return addAttribute_priv(0,lpszName,lpszValuev); }
XMLNode VarTypes::XMLNode::addChild (const char * lpszName, char isDeclaration = 0, int pos = -1)
Definition at line 2362 of file xmlParser.cpp.
References addChild_priv(), and VarTypes::stringDup().
Referenced by VarTypes::VarType::findOrAppendChild(), and VarTypes::VarType::writeXML().
                 { return addChild_priv(0,stringDup(lpszName),isDeclaration,pos); }
XMLNode VarTypes::XMLNode::addChild (XMLNode nodeToAdd, int pos = -1)
Definition at line 2018 of file xmlParser.cpp.
References addToOrder(), d, detachFromParent(), VarTypes::eNodeChild, VarTypes::XMLNode::XMLNodeDataTag::nChild, VarTypes::XMLNode::XMLNodeDataTag::pChild, VarTypes::XMLNode::XMLNodeDataTag::pParent, and VarTypes::XMLNode::XMLNodeDataTag::ref_count.
   {
       XMLNodeData *dc=childNode.d;
       if ((!dc)||(!d)) return childNode;
       if (dc->pParent) { if ((detachFromParent(dc)<=pos)&&(dc->pParent==d)) pos--; } else dc->ref_count++;
       dc->pParent=d;
   //     int nc=d->nChild;
   //     d->pChild=(XMLNode*)myRealloc(d->pChild,(nc+1),memoryIncrease,sizeof(XMLNode));
       d->pChild=(XMLNode*)addToOrder(0,&pos,d->nChild,d->pChild,sizeof(XMLNode),eNodeChild);
       d->pChild[pos].d=dc;
       d->nChild++;
       return childNode;
   }
XMLNode VarTypes::XMLNode::addChild_priv (int memoryIncrease, const char * lpszName, char isDeclaration, int pos) private
Definition at line 1012 of file xmlParser.cpp.
References addToOrder(), d, emptyXMLNode, VarTypes::eNodeChild, VarTypes::XMLNode::XMLNodeDataTag::nChild, VarTypes::XMLNode::XMLNodeDataTag::pChild, and XMLNode().
Referenced by addChild(), addChild_WOSD(), and ParseXMLElement().
   {
       if (!lpszName) return emptyXMLNode;
       d->pChild=(XMLNode*)addToOrder(memoryIncrease,&pos,d->nChild,d->pChild,sizeof(XMLNode),eNodeChild);
       d->pChild[pos].d=NULL;
       d->pChild[pos]=XMLNode(d,lpszName,isDeclaration);
       d->nChild++;
       return d->pChild[pos];
   }
XMLNode VarTypes::XMLNode::addChild_WOSD (const char * lpszName, char isDeclaration = 0, int pos = -1)
Definition at line 2364 of file xmlParser.cpp.
References addChild_priv().
                 { return addChild_priv(0,lpszName,isDeclaration,pos); }
XMLClear * VarTypes::XMLNode::addClear (const char * lpszValue, const char * lpszOpen = NULL, const char * lpszClose = NULL, int pos = -1)
Definition at line 2374 of file xmlParser.cpp.
References addClear_priv(), and VarTypes::stringDup().
                 { return addClear_priv(0,stringDup(lpszValue),lpszOpen,lpszClose,pos); }
XMLClear * VarTypes::XMLNode::addClear_priv (int memoryIncrease, const char * lpszValue, const char * lpszOpen, const char * lpszClose, int pos) private
Definition at line 1046 of file xmlParser.cpp.
References addToOrder(), d, emptyXMLClear, VarTypes::eNodeClear, getClearTagTable(), VarTypes::ALLXMLClearTag::lpszClose, VarTypes::XMLClear::lpszCloseTag, VarTypes::ALLXMLClearTag::lpszOpen, VarTypes::XMLClear::lpszOpenTag, VarTypes::XMLClear::lpszValue, VarTypes::XMLNode::XMLNodeDataTag::nClear, and VarTypes::XMLNode::XMLNodeDataTag::pClear.
Referenced by addClear(), addClear_WOSD(), and parseClearTag().
   {
       if (!lpszValue) return &emptyXMLClear;
       d->pClear=(XMLClear *)addToOrder(memoryIncrease,&pos,d->nClear,d->pClear,sizeof(XMLClear),eNodeClear);
       XMLClear *pNewClear=d->pClear+pos;
       pNewClear->lpszValue = lpszValue;
       if (!lpszOpen) lpszOpen=getClearTagTable()->lpszOpen;
       if (!lpszClose) lpszOpen=getClearTagTable()->lpszClose;
       pNewClear->lpszOpenTag = lpszOpen;
       pNewClear->lpszCloseTag = lpszClose;
       d->nClear++;
       return pNewClear;
   }
XMLClear * VarTypes::XMLNode::addClear_WOSD (const char * lpszValue, const char * lpszOpen = NULL, const char * lpszClose = NULL, int pos = -1)
Definition at line 2376 of file xmlParser.cpp.
References addClear_priv().
Referenced by updateClear_WOSD().
                 { return addClear_priv(0,lpszValue,lpszOpen,lpszClose,pos); }
const char * VarTypes::XMLNode::addText (const char * lpszValue, int pos = -1)
Definition at line 2370 of file xmlParser.cpp.
References addText_priv(), and VarTypes::stringDup().
                 { return addText_priv(0,stringDup(lpszValue),pos); }
const char * VarTypes::XMLNode::addText_priv (int memoryIncrease, const char * lpszValue, int pos) private
Definition at line 1036 of file xmlParser.cpp.
References addToOrder(), d, VarTypes::eNodeText, VarTypes::XMLNode::XMLNodeDataTag::nText, VarTypes::XMLNode::XMLNodeDataTag::pText, XMLCSTR, and XMLSTR.
Referenced by addText(), addText_WOSD(), and maybeAddTxT().
   {
       if (!lpszValue) return NULL;
       d->pText=(XMLCSTR*)addToOrder(memoryIncrease,&pos,d->nText,d->pText,sizeof(XMLSTR),eNodeText);
       d->pText[pos]=lpszValue;
       d->nText++;
       return lpszValue;
   }
const char * VarTypes::XMLNode::addText_WOSD (const char * lpszValue, int pos = -1)
Definition at line 2372 of file xmlParser.cpp.
References addText_priv().
Referenced by updateText_WOSD().
                 { return addText_priv(0,lpszValue,pos); }
void * VarTypes::XMLNode::addToOrder (int memInc, int * _pos, int nc, void * p, int size, XMLElementType xtype) private
Definition at line 985 of file xmlParser.cpp.
References d, velocity.pid_::i, VarTypes::myRealloc(), VarTypes::XMLNode::XMLNodeDataTag::nChild, VarTypes::XMLNode::XMLNodeDataTag::nClear, VarTypes::XMLNode::XMLNodeDataTag::nText, and VarTypes::XMLNode::XMLNodeDataTag::pOrder.
Referenced by addChild(), addChild_priv(), addClear_priv(), and addText_priv().
   {
       //  in: *_pos is the position inside d->pOrder ("-1" means "EndOf")
       // out: *_pos is the index inside p
       p=myRealloc(p,(nc+1),memoryIncrease,size);
       int n=d->nChild+d->nText+d->nClear;
       d->pOrder=(int*)myRealloc(d->pOrder,n+1,memoryIncrease*3,sizeof(int));
       int pos=*_pos,*o=d->pOrder;
       if ((pos<0)||(pos>=n)) { *_pos=nc; o[n]=(int)((nc<<2)+xtype); return p; }
       int i=pos;
       memmove(o+i+1, o+i, (n-i)*sizeof(int));
       while ((pos<n)&&((o[pos]&3)!=(int)xtype)) pos++;
       if (pos==n) { *_pos=nc; o[n]=(int)((nc<<2)+xtype); return p; }
       o[i]=o[pos];
       for (i=pos+1;i<=n;i++) if ((o[i]&3)==(int)xtype) o[i]+=4;
       *_pos=pos=o[pos]>>2;
       memmove(((char*)p)+(pos+1)*size,((char*)p)+pos*size,(nc-pos)*size);
       return p;
   }
char * VarTypes::XMLNode::createXMLString (int nFormat = 1, int * pnSize = NULL) const
Definition at line 1958 of file xmlParser.cpp.
References CreateXMLStringR(), d, VarTypes::dropWhiteSpace, XMLCHAR, and XMLSTR.
Referenced by writeToFile().
   {
       if (!d) { if (pnSize) *pnSize=0; return NULL; }
       XMLSTR lpszResult = NULL;
       int cbStr;
       // Recursively Calculate the size of the XML string
       if (!dropWhiteSpace) nFormat=0;
       nFormat = nFormat ? 0 : -1;
       cbStr = CreateXMLStringR(d, 0, nFormat);
       assert(cbStr);
       // Alllocate memory for the XML string + the NULL terminator and
       // create the recursively XML string.
       lpszResult=(XMLSTR)malloc((cbStr+1)*sizeof(XMLCHAR));
       CreateXMLStringR(d, lpszResult, nFormat);
       if (pnSize) *pnSize = cbStr;
       return lpszResult;
   }
int VarTypes::XMLNode::CreateXMLStringR (XMLNodeData * pEntry, char * lpszMarker, int nFormat) static private
Definition at line 1691 of file xmlParser.cpp.
References _T, VarTypes::_tcscpy(), VarTypes::charmemset(), d, VarTypes::eNodeChild, VarTypes::eNodeClear, VarTypes::eNodeText, velocity.pid_::i, INDENTCHAR, VarTypes::XMLNode::XMLNodeDataTag::isDeclaration, VarTypes::lengthXMLString(), LENSTR, VarTypes::XMLClear::lpszCloseTag, VarTypes::XMLAttribute::lpszName, VarTypes::XMLNode::XMLNodeDataTag::lpszName, VarTypes::XMLClear::lpszOpenTag, VarTypes::XMLClear::lpszValue, VarTypes::XMLAttribute::lpszValue, VarTypes::XMLNode::XMLNodeDataTag::nAttribute, VarTypes::XMLNode::XMLNodeDataTag::nChild, VarTypes::XMLNode::XMLNodeDataTag::nClear, VarTypes::XMLNode::XMLNodeDataTag::nText, VarTypes::XMLNode::XMLNodeDataTag::pAttribute, VarTypes::XMLNode::XMLNodeDataTag::pChild, VarTypes::XMLNode::XMLNodeDataTag::pClear, VarTypes::XMLNode::XMLNodeDataTag::pOrder, VarTypes::XMLNode::XMLNodeDataTag::pText, VarTypes::toXMLString(), XMLCHAR, and XMLCSTR.
Referenced by createXMLString().
   {
       int nResult = 0;
       int cb;
       int cbElement;
       int nChildFormat=-1;
       int nElementI=pEntry->nChild+pEntry->nText+pEntry->nClear;
       int i,j;
       assert(pEntry);
   #define LENSTR(lpsz) (lpsz ? _tcslen(lpsz) : 0)
       // If the element has no name then assume this is the head node.
       cbElement = (int)LENSTR(pEntry->lpszName);
       if (cbElement)
       {
           // "<elementname "
           cb = nFormat == -1 ? 0 : nFormat;
           if (lpszMarker)
           {
               if (cb) charmemset(lpszMarker, INDENTCHAR, sizeof(XMLCHAR)*cb);
               nResult = cb;
               lpszMarker[nResult++]=_T('<');
               if (pEntry->isDeclaration) lpszMarker[nResult++]=_T('?');
               _tcscpy(&lpszMarker[nResult], pEntry->lpszName);
               nResult+=cbElement;
               lpszMarker[nResult++]=_T(' ');
           } else
           {
               nResult+=cbElement+2+cb;
               if (pEntry->isDeclaration) nResult++;
           }
           // Enumerate attributes and add them to the string
           XMLAttribute *pAttr=pEntry->pAttribute;
           for (i=0; i<pEntry->nAttribute; i++)
           {
               // "Attrib
               cb = (int)LENSTR(pAttr->lpszName);
               if (cb)
               {
                   if (lpszMarker) _tcscpy(&lpszMarker[nResult], pAttr->lpszName);
                   nResult += cb;
                   // "Attrib=Value "
                   if (pAttr->lpszValue)
                   {
                       cb=(int)lengthXMLString(pAttr->lpszValue);
                       if (lpszMarker)
                       {
                           lpszMarker[nResult]=_T('=');
                           lpszMarker[nResult+1]=_T('"');
                           if (cb) toXMLString(&lpszMarker[nResult+2],pAttr->lpszValue);
                           lpszMarker[nResult+cb+2]=_T('"');
                       }
                       nResult+=cb+3;
                   }
                   if (lpszMarker) lpszMarker[nResult] = _T(' ');
                   nResult++;
               }
               pAttr++;
           }
           if (pEntry->isDeclaration)
           {
               if (lpszMarker)
               {
                   lpszMarker[nResult-1]=_T('?');
                   lpszMarker[nResult]=_T('>');
               }
               nResult++;
               if (nFormat!=-1)
               {
                   if (lpszMarker) lpszMarker[nResult]=_T('\n');
                   nResult++;
               }
           } else
               // If there are child nodes we need to terminate the start tag
               if (nElementI)
               {
                   if (lpszMarker) lpszMarker[nResult-1]=_T('>');
                   if (nFormat!=-1)
                   {
                       if (lpszMarker) lpszMarker[nResult]=_T('\n');
                       nResult++;
                   }
               } else nResult--;
       }
       // Calculate the child format for when we recurse.  This is used to
       // determine the number of spaces used for prefixes.
       if (nFormat!=-1)
       {
           if (cbElement&&(!pEntry->isDeclaration)) nChildFormat=nFormat+1;
           else nChildFormat=nFormat;
       }
       // Enumerate through remaining children
       for (i=0; i<nElementI; i++)
       {
           j=pEntry->pOrder[i];
           switch((XMLElementType)(j&3))
           {
           // Text nodes
           case eNodeText:
               {
                   // "Text"
                   XMLCSTR pChild=pEntry->pText[j>>2];
                   cb = (int)lengthXMLString(pChild);
                   if (cb)
                   {
                       if (nFormat!=-1)
                       {
                           if (lpszMarker)
{
                               charmemset(&lpszMarker[nResult],INDENTCHAR,sizeof(XMLCHAR)*(nFormat + 1));
                               toXMLString(&lpszMarker[nResult+nFormat+1],pChild);
                               lpszMarker[nResult+nFormat+1+cb]=_T('\n');
                           }
                           nResult+=cb+nFormat+2;
                       } else
                       {
                           if (lpszMarker) toXMLString(&lpszMarker[nResult], pChild);
                           nResult += cb;
                       }
                   }
                   break;
               }
           // Clear type nodes
           case eNodeClear:
               {
                   XMLClear *pChild=pEntry->pClear+(j>>2);
                   // "OpenTag"
                   cb = (int)LENSTR(pChild->lpszOpenTag);
                   if (cb)
                   {
                       if (nFormat!=-1)
                       {
                           if (lpszMarker)
{
                               charmemset(&lpszMarker[nResult], INDENTCHAR, sizeof(XMLCHAR)*(nFormat + 1));
                               _tcscpy(&lpszMarker[nResult+nFormat+1], pChild->lpszOpenTag);
                           }
                           nResult+=cb+nFormat+1;
                       }
                       else
                       {
                           if (lpszMarker)_tcscpy(&lpszMarker[nResult], pChild->lpszOpenTag);
                           nResult += cb;
                       }
                   }
                   // "OpenTag Value"
                   cb = (int)LENSTR(pChild->lpszValue);
                   if (cb)
                   {
                       if (lpszMarker) _tcscpy(&lpszMarker[nResult], pChild->lpszValue);
                       nResult += cb;
                   }
                   // "OpenTag Value CloseTag"
                   cb = (int)LENSTR(pChild->lpszCloseTag);
                   if (cb)
                   {
                       if (lpszMarker) _tcscpy(&lpszMarker[nResult], pChild->lpszCloseTag);
                       nResult += cb;
                   }
                   if (nFormat!=-1)
                   {
                       if (lpszMarker) lpszMarker[nResult] = _T('\n');
                       nResult++;
                   }
                   break;
               }
           // Element nodes
           case eNodeChild:
               {
                   // Recursively add child nodes
                   nResult += CreateXMLStringR(pEntry->pChild[j>>2].d, lpszMarker ? lpszMarker + nResult : 0, nChildFormat);
                   break;
               }
           default: break;
           }
       }
       if ((cbElement)&&(!pEntry->isDeclaration))
       {
           // If we have child entries we need to use long XML notation for
           // closing the element - "<elementname>blah blah blah</elementname>"
           if (nElementI)
           {
               // "</elementname>\0"
               if (lpszMarker)
               {
                   if (nFormat != -1)
                   {
                       if (nFormat)
                       {
                           charmemset(&lpszMarker[nResult], INDENTCHAR,sizeof(XMLCHAR)*nFormat);
                           nResult+=nFormat;
                       }
                   }
                   _tcscpy(&lpszMarker[nResult], _T("</"));
                   nResult += 2;
                   _tcscpy(&lpszMarker[nResult], pEntry->lpszName);
                   nResult += cbElement;
                   if (nFormat == -1)
                   {
                       _tcscpy(&lpszMarker[nResult], _T(">"));
                       nResult++;
                   } else
                   {
                       _tcscpy(&lpszMarker[nResult], _T(">\n"));
                       nResult+=2;
                   }
               } else
               {
                   if (nFormat != -1) nResult+=cbElement+4+nFormat;
                   else nResult+=cbElement+3;
               }
           } else
           {
               // If there are no children we can use shorthand XML notation -
               // "<elementname/>"
               // "/>\0"
               if (lpszMarker)
               {
                   if (nFormat == -1)
                   {
                       _tcscpy(&lpszMarker[nResult], _T("/>"));
                       nResult += 2;
                   }
                   else
                   {
                       _tcscpy(&lpszMarker[nResult], _T("/>\n"));
                       nResult += 3;
                   }
               }
               else
               {
                   nResult += nFormat == -1 ? 2 : 3;
               }
           }
       }
       return nResult;
   }
XMLNode VarTypes::XMLNode::createXMLTopNode (const char * lpszName, char isDeclaration = 0) static
Definition at line 948 of file xmlParser.cpp.
References VarTypes::stringDup(), and XMLNode().
Referenced by openFileHelper().
 { return XMLNode(NULL,stringDup(lpszName),isDeclaration); }
XMLNode VarTypes::XMLNode::createXMLTopNode_WOSD (const char * lpszName, char isDeclaration = 0) static
Definition at line 947 of file xmlParser.cpp.
References XMLNode().
 { return XMLNode(NULL,lpszName,isDeclaration); }
void VarTypes::XMLNode::deleteAttribute (const char * lpszName)
Definition at line 2043 of file xmlParser.cpp.
References getAttribute().
Referenced by deleteAttribute().
   {
       int j=0;
       getAttribute(lpszName,&j);
       if (j) deleteAttribute(j-1);
   }
void VarTypes::XMLNode::deleteAttribute (int i = 0)
Definition at line 2032 of file xmlParser.cpp.
References d, velocity.pid_::i, VarTypes::XMLAttribute::lpszName, VarTypes::XMLAttribute::lpszValue, VarTypes::XMLNode::XMLNodeDataTag::nAttribute, and VarTypes::XMLNode::XMLNodeDataTag::pAttribute.
   {
       if ((!d)||(i<0)||(i>=d->nAttribute)) return;
       d->nAttribute--;
       XMLAttribute *p=d->pAttribute+i;
       free((void*)p->lpszName);
       if (p->lpszValue) free((void*)p->lpszValue);
       if (d->nAttribute) memmove(p,p+1,(d->nAttribute-i)*sizeof(XMLAttribute)); else { free(p); d->pAttribute=NULL; }
   }
void VarTypes::XMLNode::deleteAttribute (XMLAttribute * anAttribute)
Definition at line 2042 of file xmlParser.cpp.
References deleteAttribute(), and VarTypes::XMLAttribute::lpszName.
 { if (a) deleteAttribute(a->lpszName); }
void VarTypes::XMLNode::deleteClear (int i = 0)
Definition at line 2122 of file xmlParser.cpp.
References d, VarTypes::eNodeClear, velocity.pid_::i, VarTypes::XMLClear::lpszValue, VarTypes::XMLNode::XMLNodeDataTag::nClear, VarTypes::XMLNode::XMLNodeDataTag::nText, VarTypes::XMLNode::XMLNodeDataTag::pClear, and removeOrderElement().
Referenced by deleteClear().
   {
       if ((!d)||(i<0)||(i>=d->nClear)) return;
       d->nClear--;
       XMLClear *p=d->pClear+i;
       free((void*)p->lpszValue);
       if (d->nClear) memmove(p,p+1,(d->nText-i)*sizeof(XMLClear)); else { free(p); d->pClear=NULL; }
       removeOrderElement(d,eNodeClear,i);
   }
void VarTypes::XMLNode::deleteClear (XMLClear * p)
Definition at line 2143 of file xmlParser.cpp.
References deleteClear(), and VarTypes::XMLClear::lpszValue.
 { if (a) deleteClear(a->lpszValue); }
void VarTypes::XMLNode::deleteClear (const char * lpszValue)
Definition at line 2142 of file xmlParser.cpp.
References deleteClear(), and indexClear().
 { deleteClear(indexClear(lpszValue)); }
void VarTypes::XMLNode::deleteNodeContent (char force = 0)
Definition at line 1991 of file xmlParser.cpp.
References d, deleteNodeContent(), detachFromParent(), velocity.pid_::i, VarTypes::XMLAttribute::lpszName, VarTypes::XMLNode::XMLNodeDataTag::lpszName, VarTypes::XMLClear::lpszValue, VarTypes::XMLAttribute::lpszValue, VarTypes::XMLNode::XMLNodeDataTag::nAttribute, VarTypes::XMLNode::XMLNodeDataTag::nChild, VarTypes::XMLNode::XMLNodeDataTag::nClear, VarTypes::XMLNode::XMLNodeDataTag::nText, VarTypes::XMLNode::XMLNodeDataTag::pAttribute, VarTypes::XMLNode::XMLNodeDataTag::pChild, VarTypes::XMLNode::XMLNodeDataTag::pClear, VarTypes::XMLNode::XMLNodeDataTag::pOrder, VarTypes::XMLNode::XMLNodeDataTag::pParent, VarTypes::XMLNode::XMLNodeDataTag::pText, and VarTypes::XMLNode::XMLNodeDataTag::ref_count.
Referenced by VarTypes::VarType::deleteAllVarChildren(), deleteNodeContent(), operator=(), and ~XMLNode().
   {
       if (!d) return;
       (d->ref_count) --;
       if ((d->ref_count==0)||force)
       {
           int i;
           if (d->pParent) detachFromParent(d);
           for(i=0; i<d->nChild; i++) { d->pChild[i].d->pParent=NULL; d->pChild[i].deleteNodeContent(force); }
           free(d->pChild);
           for(i=0; i<d->nText; i++) free((void*)d->pText[i]);
           free(d->pText);
           for(i=0; i<d->nClear; i++) free((void*)d->pClear[i].lpszValue);
           free(d->pClear);
           for(i=0; i<d->nAttribute; i++)
           {
               free((void*)d->pAttribute[i].lpszName);
               if (d->pAttribute[i].lpszValue) free((void*)d->pAttribute[i].lpszValue);
           }
           free(d->pAttribute);
           free(d->pOrder);
           free((void*)d->lpszName);
           free(d);
           d=NULL;
       }
   }
void VarTypes::XMLNode::deleteText (int i = 0)
Definition at line 2093 of file xmlParser.cpp.
References d, VarTypes::eNodeText, velocity.pid_::i, VarTypes::XMLNode::XMLNodeDataTag::nText, VarTypes::XMLNode::XMLNodeDataTag::pText, removeOrderElement(), and XMLCSTR.
Referenced by deleteText().
   {
       if ((!d)||(i<0)||(i>=d->nText)) return;
       d->nText--;
       XMLCSTR *p=d->pText+i;
       free((void*)*p);
       if (d->nText) memmove(p,p+1,(d->nText-i)*sizeof(XMLCSTR)); else { free(p); d->pText=NULL; }
       removeOrderElement(d,eNodeText,i);
   }
void VarTypes::XMLNode::deleteText (const char * lpszValue)
Definition at line 2103 of file xmlParser.cpp.
References deleteText(), and indexText().
 { deleteText(indexText(lpszValue)); }
int VarTypes::XMLNode::detachFromParent (XMLNodeData * d) static private
Definition at line 1980 of file xmlParser.cpp.
References VarTypes::eNodeChild, velocity.pid_::i, VarTypes::XMLNode::XMLNodeDataTag::pChild, VarTypes::XMLNode::XMLNodeDataTag::pParent, and removeOrderElement().
Referenced by addChild(), and deleteNodeContent().
   {
       XMLNode *pa=d->pParent->pChild;
       int i=0;
       while (((void*)(pa[i].d))!=((void*)d)) i++;
       d->pParent->nChild--;
       if (d->pParent->nChild) memmove(pa+i,pa+i+1,(d->pParent->nChild-i)*sizeof(XMLNode));
       else { free(pa); d->pParent->pChild=NULL; }
       return removeOrderElement(d->pParent,eNodeChild,i);
   }
XMLNodeContents VarTypes::XMLNode::enumContents (int i) const
Definition at line 2323 of file xmlParser.cpp.
References VarTypes::XMLNodeContents::attrib, VarTypes::XMLNodeContents::child, VarTypes::XMLNodeContents::clear, d, VarTypes::eNodeAttribute, VarTypes::eNodeChild, VarTypes::eNodeClear, VarTypes::eNodeNULL, VarTypes::eNodeText, velocity.pid_::i, nAttribute(), VarTypes::XMLNode::XMLNodeDataTag::nAttribute, VarTypes::XMLNode::XMLNodeDataTag::pAttribute, VarTypes::XMLNode::XMLNodeDataTag::pChild, VarTypes::XMLNode::XMLNodeDataTag::pClear, VarTypes::XMLNode::XMLNodeDataTag::pOrder, VarTypes::XMLNode::XMLNodeDataTag::pText, VarTypes::XMLNodeContents::text, and VarTypes::XMLNodeContents::type.
   {
       XMLNodeContents c;
       if (!d) { c.type=eNodeNULL; return c; }
       if (i<d->nAttribute)
       {
           c.type=eNodeAttribute;
           c.attrib=d->pAttribute[i];
           return c;
       }
       i-=d->nAttribute;
       c.type=(XMLElementType)(d->pOrder[i]&3);
       i=(d->pOrder[i])>>2;
       switch (c.type)
       {
       case eNodeChild:     c.child = d->pChild[i];      break;
       case eNodeText:      c.text  = d->pText[i];       break;
       case eNodeClear:     c.clear = d->pClear[i];      break;
       default: break;
       }
       return c;
   }
void VarTypes::XMLNode::exactMemory (XMLNodeData * d) static private
Definition at line 1104 of file xmlParser.cpp.
References VarTypes::XMLNode::XMLNodeDataTag::nAttribute, VarTypes::XMLNode::XMLNodeDataTag::nChild, VarTypes::XMLNode::XMLNodeDataTag::nClear, VarTypes::XMLNode::XMLNodeDataTag::nText, VarTypes::XMLNode::XMLNodeDataTag::pAttribute, VarTypes::XMLNode::XMLNodeDataTag::pChild, VarTypes::XMLNode::XMLNodeDataTag::pClear, VarTypes::XMLNode::XMLNodeDataTag::pOrder, VarTypes::XMLNode::XMLNodeDataTag::pText, XMLCSTR, and XMLSTR.
Referenced by ParseXMLElement().
   {
       if (d->pOrder)     d->pOrder=(int*)realloc(d->pOrder,(d->nChild+d->nText+d->nClear)*sizeof(int));
       if (d->pChild)     d->pChild=(XMLNode*)realloc(d->pChild,d->nChild*sizeof(XMLNode));
       if (d->pAttribute) d->pAttribute=(XMLAttribute*)realloc(d->pAttribute,d->nAttribute*sizeof(XMLAttribute));
       if (d->pText)      d->pText=(XMLCSTR*)realloc(d->pText,d->nText*sizeof(XMLSTR));
       if (d->pClear)     d->pClear=(XMLClear *)realloc(d->pClear,d->nClear*sizeof(XMLClear));
   }
int VarTypes::XMLNode::findPosition (XMLNodeData * d, int index, XMLElementType xtype) inline static private
Definition at line 964 of file xmlParser.cpp.
References velocity.pid_::i, and VarTypes::XMLNode::XMLNodeDataTag::pOrder.
Referenced by positionOfChildNode(), positionOfClear(), positionOfText(), and removeOrderElement().
   {
       if (index<0) return -1;
       int i=0,j=(int)((index<<2)+xtype),*o=d->pOrder; while (o[i]!=j) i++; return i;
   }
XMLAttribute VarTypes::XMLNode::getAttribute (int i = 0) const
Definition at line 2353 of file xmlParser.cpp.
References d, emptyXMLAttribute, velocity.pid_::i, VarTypes::XMLNode::XMLNodeDataTag::nAttribute, and VarTypes::XMLNode::XMLNodeDataTag::pAttribute.
Referenced by deleteAttribute(), VarTypes::VarType::findOrAppendChild(), getAttribute(), getChildNodeWithAttribute(), VarTypes::VarExternal::readAttributes(), VarTypes::VarDouble::readAttributes(), VarTypes::VarInt::readAttributes(), VarTypes::VarType::readChildrenHelper(), and updateAttribute_WOSD().
 { if ((!d)||(i>=d->nAttribute)) return emptyXMLAttribute; return d->pAttribute[i]; }
const char * VarTypes::XMLNode::getAttribute (const char * name, int i) const
Definition at line 2315 of file xmlParser.cpp.
References d, getAttribute(), and velocity.pid_::i.
   {
       if (!d) return NULL;
       int i=0;
       while (j-->0) getAttribute(name,&i);
       return getAttribute(name,&i);
   }
const char * VarTypes::XMLNode::getAttribute (const char * name, int * i = NULL) const
Definition at line 2281 of file xmlParser.cpp.
References VarTypes::_tcsicmp(), d, velocity.pid_::i, VarTypes::XMLAttribute::lpszName, VarTypes::XMLAttribute::lpszValue, VarTypes::XMLNode::XMLNodeDataTag::nAttribute, and VarTypes::XMLNode::XMLNodeDataTag::pAttribute.
   {
       if (!d) return NULL;
       int i=0,n=d->nAttribute;
       if (j) i=*j;
       XMLAttribute *pAttr=d->pAttribute+i;
       for (; i<n; i++)
       {
           if (_tcsicmp(pAttr->lpszName, lpszAttrib)==0)
           {
               if (j) *j=i+1;
               return pAttr->lpszValue;
           }
           pAttr++;
       }
       return NULL;
   }
const char * VarTypes::XMLNode::getAttributeName (int i = 0) const
Definition at line 2354 of file xmlParser.cpp.
References d, velocity.pid_::i, VarTypes::XMLAttribute::lpszName, VarTypes::XMLNode::XMLNodeDataTag::nAttribute, and VarTypes::XMLNode::XMLNodeDataTag::pAttribute.
 { if ((!d)||(i>=d->nAttribute)) return NULL;              return d->pAttribute[i].lpszName;  }
const char * VarTypes::XMLNode::getAttributeValue (int i = 0) const
Definition at line 2355 of file xmlParser.cpp.
References d, velocity.pid_::i, VarTypes::XMLAttribute::lpszValue, VarTypes::XMLNode::XMLNodeDataTag::nAttribute, and VarTypes::XMLNode::XMLNodeDataTag::pAttribute.
 { if ((!d)||(i>=d->nAttribute)) return NULL;              return d->pAttribute[i].lpszValue; }
XMLNode VarTypes::XMLNode::getChildNode (int i = 0) const
Definition at line 2357 of file xmlParser.cpp.
References d, emptyXMLNode, velocity.pid_::i, VarTypes::XMLNode::XMLNodeDataTag::nChild, and VarTypes::XMLNode::XMLNodeDataTag::pChild.
Referenced by VarTypes::VarType::deleteAllVarChildren(), VarTypes::VarType::findOrAppendChild(), getChildNode(), getChildNodeWithAttribute(), parseString(), positionOfChildNode(), and VarTypes::VarType::readChildrenHelper().
 { if ((!d)||(i>=d->nChild    )) return emptyXMLNode;      return d->pChild[i];     }
XMLNode VarTypes::XMLNode::getChildNode (const char * name, int i) const
Definition at line 2221 of file xmlParser.cpp.
References d, emptyXMLNode, getChildNode(), and velocity.pid_::i.
   {
       if (!d) return emptyXMLNode;
       int i=0;
       while (j-->0) getChildNode(name,&i);
       return getChildNode(name,&i);
   }
XMLNode VarTypes::XMLNode::getChildNode (const char * name, int * i = NULL) const
Definition at line 2203 of file xmlParser.cpp.
References VarTypes::_tcsicmp(), d, emptyXMLNode, velocity.pid_::i, VarTypes::XMLNode::XMLNodeDataTag::lpszName, VarTypes::XMLNode::XMLNodeDataTag::nChild, and VarTypes::XMLNode::XMLNodeDataTag::pChild.
   {
       if (!d) return emptyXMLNode;
       int i=0,n=d->nChild;
       if (j) i=*j;
       XMLNode *pc=d->pChild+i;
       for (; i<n; i++)
       {
           if (_tcsicmp(pc->d->lpszName, name)==0)
           {
               if (j) *j=i+1;
               return *pc;
           }
           pc++;
       }
       return emptyXMLNode;
   }
XMLNode VarTypes::XMLNode::getChildNodeWithAttribute (const char * tagName, const char * attributeName, const char * attributeValue = NULL, int * i = NULL) const
Definition at line 2252 of file xmlParser.cpp.
References VarTypes::_tcsicmp(), emptyXMLNode, getAttribute(), getChildNode(), velocity.pid_::i, isAttributeSet(), isEmpty(), k, t, role._GoToPoint::x, and XMLCSTR.
   {
       int i=0,j;
       if (k) i=*k;
       XMLNode x;
       XMLCSTR t;
       do
       {
           x=getChildNode(name,&i);
           if (!x.isEmpty())
           {
               if (attributeValue)
               {
                   j=0;
                   do
                   {
                       t=x.getAttribute(attributeName,&j);
                       if (t&&(_tcsicmp(attributeValue,t)==0)) { if (k) *k=i+1; return x; }
                   } while (t);
               } else
               {
                   if (x.isAttributeSet(attributeName)) { if (k) *k=i+1; return x; }
               }
           }
       } while (!x.isEmpty());
       return emptyXMLNode;
   }
XMLClear VarTypes::XMLNode::getClear (int i = 0) const
Definition at line 2352 of file xmlParser.cpp.
References d, emptyXMLClear, velocity.pid_::i, VarTypes::XMLNode::XMLNodeDataTag::nClear, and VarTypes::XMLNode::XMLNodeDataTag::pClear.
 { if ((!d)||(i>=d->nClear    )) return emptyXMLClear;     return d->pClear[i];     }
ALLXMLClearTag * VarTypes::XMLNode::getClearTagTable () static
Definition at line 116 of file xmlParser.cpp.
References VarTypes::XMLClearTags.
Referenced by addClear_priv().
 { return XMLClearTags; }
const char * VarTypes::XMLNode::getError (XMLError error) static
Definition at line 140 of file xmlParser.cpp.
References _T, VarTypes::eXMLErrorBase64DataSizeIsNotMultipleOf4, VarTypes::eXMLErrorBase64DecodeBufferTooSmall, VarTypes::eXMLErrorBase64DecodeIllegalCharacter, VarTypes::eXMLErrorBase64DecodeTruncatedData, VarTypes::eXMLErrorCannotOpenWriteFile, VarTypes::eXMLErrorCannotWriteFile, VarTypes::eXMLErrorCharConversionError, VarTypes::eXMLErrorEmpty, VarTypes::eXMLErrorFileNotFound, VarTypes::eXMLErrorFirstNotStartTag, VarTypes::eXMLErrorFirstTagNotFound, VarTypes::eXMLErrorInvalidTag, VarTypes::eXMLErrorMissingEndTag, VarTypes::eXMLErrorMissingEndTagName, VarTypes::eXMLErrorMissingTagName, VarTypes::eXMLErrorNoElements, VarTypes::eXMLErrorNoMatchingQuote, VarTypes::eXMLErrorNone, VarTypes::eXMLErrorUnexpectedToken, VarTypes::eXMLErrorUnknownCharacterEntity, VarTypes::eXMLErrorUnmatchedEndClearTag, and VarTypes::eXMLErrorUnmatchedEndTag.
Referenced by openFileHelper().
   {
       switch (xerror)
       {
       case eXMLErrorNone:                  return _T("No error");
       case eXMLErrorMissingEndTag:         return _T("Warning: Unmatched end tag");
       case eXMLErrorEmpty:                 return _T("Error: No XML data");
       case eXMLErrorFirstNotStartTag:      return _T("Error: First token not start tag");
       case eXMLErrorMissingTagName:        return _T("Error: Missing start tag name");
       case eXMLErrorMissingEndTagName:     return _T("Error: Missing end tag name");
       case eXMLErrorNoMatchingQuote:       return _T("Error: Unmatched quote");
       case eXMLErrorUnmatchedEndTag:       return _T("Error: Unmatched end tag");
       case eXMLErrorUnmatchedEndClearTag:  return _T("Error: Unmatched clear tag end");
       case eXMLErrorUnexpectedToken:       return _T("Error: Unexpected token found");
       case eXMLErrorInvalidTag:            return _T("Error: Invalid tag found");
       case eXMLErrorNoElements:            return _T("Error: No elements found");
       case eXMLErrorFileNotFound:          return _T("Error: File not found");
       case eXMLErrorFirstTagNotFound:      return _T("Error: First Tag not found");
       case eXMLErrorUnknownCharacterEntity:return _T("Error: Unknown character entity");
       case eXMLErrorCharConversionError:   return _T("Error: unable to convert between UNICODE and MultiByte chars");
       case eXMLErrorCannotOpenWriteFile:   return _T("Error: unable to open file for writing");
       case eXMLErrorCannotWriteFile:       return _T("Error: cannot write into file");
       case eXMLErrorBase64DataSizeIsNotMultipleOf4: return _T("Warning: Base64-string length is not a multiple of 4");
       case eXMLErrorBase64DecodeTruncatedData:      return _T("Warning: Base64-string is truncated");
       case eXMLErrorBase64DecodeIllegalCharacter:   return _T("Error: Base64-string contains an illegal character");
       case eXMLErrorBase64DecodeBufferTooSmall:     return _T("Error: Base64 decode output buffer is too small");
       };
       return _T("Unknown");
   }
const char * VarTypes::XMLNode::getName () const
Definition at line 2346 of file xmlParser.cpp.
References d, and VarTypes::XMLNode::XMLNodeDataTag::lpszName.
Referenced by parseString().
 { if (!d) return NULL; return d->lpszName;   }
XMLNode VarTypes::XMLNode::getParentNode () const
Definition at line 2358 of file xmlParser.cpp.
References d, emptyXMLNode, VarTypes::XMLNode::XMLNodeDataTag::pParent, and XMLNode().
 { if ((!d)||(!d->pParent     )) return emptyXMLNode;      return XMLNode(d->pParent); }
const char * VarTypes::XMLNode::getText (int i = 0) const
Definition at line 2356 of file xmlParser.cpp.
References d, velocity.pid_::i, VarTypes::XMLNode::XMLNodeDataTag::nText, and VarTypes::XMLNode::XMLNodeDataTag::pText.
Referenced by VarTypes::VarType::readText().
 { if ((!d)||(i>=d->nText     )) return NULL;              return d->pText[i];      }
const char * VarTypes::XMLNode::getVersion () static
Definition at line 96 of file xmlParser.cpp.
References _T.
 { return _T("v2.23"); }
char VarTypes::XMLNode::guessUTF8ParsingParameterValue (void * buffer, int bufLen, char useXMLEncodingAttribute = 1) static
Definition at line 2405 of file xmlParser.cpp.
References VarTypes::_strnicmp(), velocity.pid_::i, VarTypes::mmin(), VarTypes::myIsTextUnicode(), and XML_isSPACECHAR.
Referenced by openFileHelper().
   {
   #ifdef _XMLUNICODE
       return 0;
   #else
       if (l<25) return 0;
       if (myIsTextUnicode(buf,l)) return 0;
       unsigned char *b=(unsigned char*)buf;
       if ((b[0]==0xef)&&(b[1]==0xbb)&&(b[2]==0xbf)) return 1;
       // Match utf-8 model ?
       int i=0;
       while (i<l)
           switch (XML_utf8ByteTable[b[i]])
           {
           case 4: i++; if ((i<l)&&(b[i]& 0xC0)!=0x80) return 0; // 10bbbbbb ?
           case 3: i++; if ((i<l)&&(b[i]& 0xC0)!=0x80) return 0; // 10bbbbbb ?
           case 2: i++; if ((i<l)&&(b[i]& 0xC0)!=0x80) return 0; // 10bbbbbb ?
           case 1: i++; break;
           case 0: i=l;
           }
       if (!useXMLEncodingAttribute) return 1;
       // if encoding is specified and different from utf-8 than it's non-utf8
       // otherwise it's utf-8
       char bb[201];
       l=mmin(l,200);
       memcpy(bb,buf,l); // copy buf into bb to be able to do "bb[l]=0"
       bb[l]=0;
       b=(unsigned char*)strstr(bb,"encoding");
       if (!b) return 1;
       b+=8; while XML_isSPACECHAR(*b) b++; if (*b!='=') return 1;
       b++;  while XML_isSPACECHAR(*b) b++; if ((*b!='\'')&&(*b!='"')) return 1;
       b++;  while XML_isSPACECHAR(*b) b++; if ((_strnicmp((char*)b,"utf-8",5)==0)||
                                               (_strnicmp((char*)b,"utf8",4)==0)) return 1;
       return 0;
   #endif
   }
int VarTypes::XMLNode::indexClear (const char * lpszValue) const private
Definition at line 2132 of file xmlParser.cpp.
References d, velocity.pid_::i, VarTypes::XMLNode::XMLNodeDataTag::nClear, and VarTypes::XMLNode::XMLNodeDataTag::pClear.
Referenced by deleteClear(), positionOfClear(), and updateClear_WOSD().
   {
       if (!d) return -1;
       int i,l=d->nClear;
       if (!lpszValue) { if (l) return 0; return -1; }
       XMLClear *p=d->pClear;
       for (i=0; i<l; i++) if (lpszValue==p[i].lpszValue) return i;
       return -1;
   }
int VarTypes::XMLNode::indexText (const char * lpszValue) const private
Definition at line 2083 of file xmlParser.cpp.
References d, velocity.pid_::i, VarTypes::XMLNode::XMLNodeDataTag::nText, VarTypes::XMLNode::XMLNodeDataTag::pText, and XMLCSTR.
Referenced by deleteText(), positionOfText(), and updateText_WOSD().
   {
       if (!d) return -1;
       int i,l=d->nText;
       if (!lpszValue) { if (l) return 0; return -1; }
       XMLCSTR *p=d->pText;
       for (i=0; i<l; i++) if (lpszValue==p[i]) return i;
       return -1;
   }
char VarTypes::XMLNode::isAttributeSet (const char * name) const
Definition at line 2299 of file xmlParser.cpp.
References VarTypes::_tcsicmp(), d, FALSE, velocity.pid_::i, VarTypes::XMLAttribute::lpszName, VarTypes::XMLNode::XMLNodeDataTag::nAttribute, VarTypes::XMLNode::XMLNodeDataTag::pAttribute, and TRUE.
Referenced by getChildNodeWithAttribute().
   {
       if (!d) return FALSE;
       int i,n=d->nAttribute;
       XMLAttribute *pAttr=d->pAttribute;
       for (i=0; i<n; i++)
       {
           if (_tcsicmp(pAttr->lpszName, lpszAttrib)==0)
           {
               return TRUE;
           }
           pAttr++;
       }
       return FALSE;
   }
char VarTypes::XMLNode::isDeclaration () const
Definition at line 2359 of file xmlParser.cpp.
References d, and VarTypes::XMLNode::XMLNodeDataTag::isDeclaration.
Referenced by parseString(), writeToFile(), and XMLNode().
 { if (!d) return 0;             return d->isDeclaration; }
char VarTypes::XMLNode::isEmpty () const
Definition at line 2360 of file xmlParser.cpp.
References d.
Referenced by getChildNodeWithAttribute(), and ParseXMLElement().
 { return (d==NULL); }
char VarTypes::XMLNode::maybeAddTxT (void * pa, const char * tokenPStr) private
Definition at line 1113 of file xmlParser.cpp.
References addText_priv(), VarTypes::dropWhiteSpace, VarTypes::fromXMLString(), VarTypes::XML::lpszText, MEMORYINCREASE, XML_isSPACECHAR, and XMLCSTR.
Referenced by ParseXMLElement().
   {
       XML *pXML=(XML *)pa;
       XMLCSTR lpszText=pXML->lpszText;
       if (!lpszText) return 0;
       if (dropWhiteSpace) while (XML_isSPACECHAR(*lpszText)&&(lpszText!=tokenPStr)) lpszText++;
       int cbText = (int)(tokenPStr - lpszText);
       if (!cbText) { pXML->lpszText=NULL; return 0; }
       if (dropWhiteSpace) { cbText--; while ((cbText)&&XML_isSPACECHAR(lpszText[cbText])) cbText--; cbText++; }
       if (!cbText) { pXML->lpszText=NULL; return 0; }
       lpszText=fromXMLString(lpszText,cbText,pXML);
       if (!lpszText) return 1;
       addText_priv(MEMORYINCREASE,lpszText,-1);
       pXML->lpszText=NULL;
       return 0;
   }
int VarTypes::XMLNode::nAttribute () const
Definition at line 2349 of file xmlParser.cpp.
References d, and VarTypes::XMLNode::XMLNodeDataTag::nAttribute.
Referenced by enumContents().
 { if (!d) return 0;    return d->nAttribute; }
int VarTypes::XMLNode::nChildNode (const char * name) const
Definition at line 2190 of file xmlParser.cpp.
References VarTypes::_tcsicmp(), d, velocity.pid_::i, VarTypes::XMLNode::XMLNodeDataTag::lpszName, VarTypes::XMLNode::XMLNodeDataTag::nChild, and VarTypes::XMLNode::XMLNodeDataTag::pChild.
Referenced by VarTypes::VarType::deleteAllVarChildren(), VarTypes::VarType::findOrAppendChild(), parseString(), and VarTypes::VarType::readChildrenHelper().
   {
       if (!d) return 0;
       int i,j=0,n=d->nChild;
       XMLNode *pc=d->pChild;
       for (i=0; i<n; i++)
       {
           if (_tcsicmp(pc->d->lpszName, name)==0) j++;
           pc++;
       }
       return j;
   }
int VarTypes::XMLNode::nChildNode () const
Definition at line 2348 of file xmlParser.cpp.
References d, and VarTypes::XMLNode::XMLNodeDataTag::nChild.
 { if (!d) return 0;    return d->nChild;     }
int VarTypes::XMLNode::nClear () const
Definition at line 2350 of file xmlParser.cpp.
References d, and VarTypes::XMLNode::XMLNodeDataTag::nClear.
 { if (!d) return 0;    return d->nClear;     }
int VarTypes::XMLNode::nElement () const
Definition at line 2351 of file xmlParser.cpp.
References d, VarTypes::XMLNode::XMLNodeDataTag::nAttribute, VarTypes::XMLNode::XMLNodeDataTag::nChild, VarTypes::XMLNode::XMLNodeDataTag::nClear, and VarTypes::XMLNode::XMLNodeDataTag::nText.
Referenced by parseString().
 { if (!d) return 0;    return d->nAttribute+d->nChild+d->nText+d->nClear; }
int VarTypes::XMLNode::nText () const
Definition at line 2347 of file xmlParser.cpp.
References d, and VarTypes::XMLNode::XMLNodeDataTag::nText.
 { if (!d) return 0;    return d->nText;      }
XMLNode VarTypes::XMLNode::openFileHelper (const char * filename, const char * tag = NULL) static
Definition at line 340 of file xmlParser.cpp.
References _T, VarTypes::_tfopen(), createXMLTopNode(), VarTypes::dropWhiteSpace, VarTypes::XMLResults::error, VarTypes::eXMLErrorFirstTagNotFound, VarTypes::eXMLErrorNone, getError(), VarTypes::guessUnicodeChars, guessUTF8ParsingParameterValue(), VarTypes::XMLResults::nColumn, VarTypes::XMLResults::nLine, parseFile(), setGlobalOptions(), and XMLCSTR.
Referenced by VarTypes::VarExternal::loadExternal(), VarTypes::VarXML::read(), and VarTypes::VarXML::write().
   {
       // guess the value of the global parameter "strictUTF8Parsing"
       // (the guess is based on the first 200 bytes of the file).
       FILE *f=_tfopen(filename,_T("rb"));
       if (f)
       {
           char bb[205];
           int l=(int)fread(bb,1,200,f);
           setGlobalOptions(guessUnicodeChars,guessUTF8ParsingParameterValue(bb,l),dropWhiteSpace);
           fclose(f);
       }
       // parse the file
       XMLResults pResults;
       XMLNode xnode=XMLNode::parseFile(filename,tag,&pResults);
       // display error message (if any)
       if (pResults.error != eXMLErrorNone)
       {
           // create message
           char message[2000],*s1=(char*)"",*s3=(char*)""; XMLCSTR s2=_T("");
           if (pResults.error==eXMLErrorFirstTagNotFound) { s1=(char*)"First Tag should be '"; s2=tag; s3=(char*)"'.\n"; }
           sprintf(message,
   #ifdef _XMLUNICODE
               "XML Parsing error inside file '%S'.\n%S\nAt line %i, column %i.\n%s%S%s"
   #else
               "XML Parsing error inside file '%s'.\n%s\nAt line %i, column %i.\n%s%s%s"
   #endif
               ,filename,XMLNode::getError(pResults.error),pResults.nLine,pResults.nColumn,s1,s2,s3);
           // display message
   #if defined(WIN32) && !defined(UNDER_CE) && !defined(_XMLPARSER_NO_MESSAGEBOX_)
           MessageBoxA(NULL,message,"XML Parsing error",MB_OK|MB_ICONERROR|MB_TOPMOST);
   #else
           printf("%s",message);
   #endif
           xnode = XMLNode::createXMLTopNode(tag);
       }
       return xnode;
   }
XMLNode & VarTypes::XMLNode::operator= (const XMLNode & A)
Definition at line 2171 of file xmlParser.cpp.
References d, deleteNodeContent(), and VarTypes::XMLNode::XMLNodeDataTag::ref_count.
   {
       // shallow copy
       if (this != &A)
       {
           deleteNodeContent();
           d=A.d;
           if (d) (d->ref_count) ++ ;
       }
       return *this;
   }
char VarTypes::XMLNode::parseClearTag (void * px, ALLXMLClearTag * pa) private
Definition at line 1062 of file xmlParser.cpp.
References _T, VarTypes::_tcslen(), VarTypes::_tcsstr(), addClear_priv(), VarTypes::XML::error, VarTypes::eXMLErrorUnmatchedEndClearTag, VarTypes::ALLXMLClearTag::lpszClose, VarTypes::ALLXMLClearTag::lpszOpen, VarTypes::XML::lpXML, MEMORYINCREASE, VarTypes::XML::nIndex, VarTypes::stringDup(), and XMLCSTR.
Referenced by ParseXMLElement().
   {
       XML *pXML=(XML *)px;
       int cbTemp=0;
       XMLCSTR lpszTemp=NULL;
       XMLCSTR lpXML=&pXML->lpXML[pXML->nIndex];
       static XMLCSTR docTypeEnd=_T("]>");
       // Find the closing tag
       // Seems the <!DOCTYPE need a better treatment so lets handle it
       if (pClear->lpszOpen==XMLClearTags[1].lpszOpen)
       {
           XMLCSTR pCh=lpXML;
           while (*pCh)
           {
               if (*pCh==_T('<')) { pClear->lpszClose=docTypeEnd; lpszTemp=_tcsstr(lpXML,docTypeEnd); break; }
               else if (*pCh==_T('>')) { lpszTemp=pCh; break; }
   #ifdef _XMLUNICODE
               pCh++;
   #else
               pCh+=XML_ByteTable[(unsigned char)(*pCh)];
   #endif
           }
       } else lpszTemp=_tcsstr(lpXML, pClear->lpszClose);
       if (lpszTemp)
       {
           // Cache the size and increment the index
           cbTemp = (int)(lpszTemp - lpXML);
           pXML->nIndex += cbTemp+(int)_tcslen(pClear->lpszClose);
           // Add the clear node to the current element
           addClear_priv(MEMORYINCREASE,stringDup(lpXML,cbTemp), pClear->lpszOpen, pClear->lpszClose,-1);
           return 0;
       }
       // If we failed to find the end tag
       pXML->error = eXMLErrorUnmatchedEndClearTag;
       return 1;
   }
XMLNode VarTypes::XMLNode::parseFile (const char * filename, const char * tag = NULL, XMLResults * pResults = NULL) static
Definition at line 1633 of file xmlParser.cpp.
References _T, VarTypes::_tfopen(), buf, emptyXMLNode, VarTypes::XMLResults::error, VarTypes::eXMLErrorCharConversionError, VarTypes::eXMLErrorEmpty, VarTypes::eXMLErrorFileNotFound, VarTypes::guessUnicodeChars, VarTypes::myIsTextUnicode(), VarTypes::myWideCharToMultiByte(), VarTypes::XMLResults::nColumn, VarTypes::XMLResults::nLine, parseString(), role._GoToPoint::x, and XMLSTR.
Referenced by openFileHelper().
   {
       if (pResults) { pResults->nLine=0; pResults->nColumn=0; }
       FILE *f=_tfopen(filename,_T("rb"));
       if (f==NULL) { if (pResults) pResults->error=eXMLErrorFileNotFound; return emptyXMLNode; }
       fseek(f,0,SEEK_END);
       int l=ftell(f),headerSz=0;
       if (!l) { if (pResults) pResults->error=eXMLErrorEmpty; return emptyXMLNode; }
       fseek(f,0,SEEK_SET);
       unsigned char *buf=(unsigned char*)malloc(l+1);
       int tmp=fread(buf,l,1,f);
       (void)tmp;
       fclose(f);
       buf[l]=0;
   #ifdef _XMLUNICODE
       if (guessUnicodeChars)
       {
           if (!myIsTextUnicode(buf,l))
           {
               if ((buf[0]==0xef)&&(buf[1]==0xbb)&&(buf[2]==0xbf)) headerSz=3;
               XMLSTR b2=myMultiByteToWideChar((const char*)(buf+headerSz),l-headerSz);
               free(buf); buf=(unsigned char*)b2; headerSz=0;
           } else
           {
               if ((buf[0]==0xef)&&(buf[1]==0xff)) headerSz=2;
               if ((buf[0]==0xff)&&(buf[1]==0xfe)) headerSz=2;
           }
       }
   #else
       if (guessUnicodeChars)
       {
           if (myIsTextUnicode(buf,l))
           {
               l/=sizeof(wchar_t);
               if ((buf[0]==0xef)&&(buf[1]==0xff)) headerSz=2;
               if ((buf[0]==0xff)&&(buf[1]==0xfe)) headerSz=2;
               char *b2=myWideCharToMultiByte((const wchar_t*)(buf+headerSz),l-headerSz);
               free(buf); buf=(unsigned char*)b2; headerSz=0;
           } else
           {
               if ((buf[0]==0xef)&&(buf[1]==0xbb)&&(buf[2]==0xbf)) headerSz=3;
           }
       }
   #endif
       if (!buf) { if (pResults) pResults->error=eXMLErrorCharConversionError; return emptyXMLNode; }
       XMLNode x=parseString((XMLSTR)(buf+headerSz),tag,pResults);
       free(buf);
       return x;
   }
XMLNode VarTypes::XMLNode::parseString (const char * lpXMLString, const char * tag = NULL, XMLResults * pResults = NULL) static
Definition at line 1563 of file xmlParser.cpp.
References VarTypes::_tcsicmp(), VarTypes::_tcslen(), VarTypes::CountLinesAndColumns(), emptyXMLNode, VarTypes::XMLResults::error, VarTypes::XML::error, VarTypes::eXMLErrorFirstTagNotFound, VarTypes::eXMLErrorMissingEndTag, VarTypes::eXMLErrorNoElements, VarTypes::eXMLErrorNone, FALSE, getChildNode(), getName(), velocity.pid_::i, isDeclaration(), VarTypes::XML::lpXML, nChildNode(), VarTypes::XMLResults::nColumn, nElement(), VarTypes::XML::nIndex, VarTypes::XML::nIndexMissigEndTag, VarTypes::XMLResults::nLine, ParseXMLElement(), TRUE, and XMLCSTR.
Referenced by parseFile().
   {
       if (!lpszXML)
       {
           if (pResults)
           {
               pResults->error=eXMLErrorNoElements;
               pResults->nLine=0;
               pResults->nColumn=0;
           }
           return emptyXMLNode;
       }
       XMLNode xnode(NULL,NULL,FALSE);
       struct XML xml={ lpszXML, lpszXML, 0, 0, eXMLErrorNone, NULL, 0, NULL, 0, TRUE };
       // Create header element
       xnode.ParseXMLElement(&xml);
       enum XMLError error = xml.error;
       if ((xnode.nChildNode()==1)&&(xnode.nElement()==1)) xnode=xnode.getChildNode(); // skip the empty node
       // If no error occurred
       if ((error==eXMLErrorNone)||(error==eXMLErrorMissingEndTag))
       {
           XMLCSTR name=xnode.getName();
           if (tag&&_tcslen(tag)&&((!name)||(_tcsicmp(xnode.getName(),tag))))
           {
               XMLNode nodeTmp;
               int i=0;
               while (i<xnode.nChildNode())
               {
                   nodeTmp=xnode.getChildNode(i);
                   if (_tcsicmp(nodeTmp.getName(),tag)==0) break;
                   if (nodeTmp.isDeclaration()) { xnode=nodeTmp; i=0; } else i++;
               }
               if (i>=xnode.nChildNode())
               {
                   if (pResults)
                   {
                       pResults->error=eXMLErrorFirstTagNotFound;
                       pResults->nLine=0;
                       pResults->nColumn=0;
                   }
                   return emptyXMLNode;
               }
               xnode=nodeTmp;
           }
       } else
       {
           // Cleanup: this will destroy all the nodes
           xnode = emptyXMLNode;
       }
       // If we have been given somewhere to place results
       if (pResults)
       {
           pResults->error = error;
           // If we have an error
           if (error!=eXMLErrorNone)
           {
               if (error==eXMLErrorMissingEndTag) xml.nIndex=xml.nIndexMissigEndTag;
               // Find which line and column it starts on.
               CountLinesAndColumns(xml.lpXML, xml.nIndex, pResults);
           }
       }
       return xnode;
   }
int VarTypes::XMLNode::ParseXMLElement (void * pXML) private
Definition at line 1131 of file xmlParser.cpp.
References _T, addAttribute_priv(), addChild_priv(), VarTypes::XML::cbEndTag, VarTypes::XML::cbNewElement, d, VarTypes::eAttribEquals, VarTypes::eAttribName, VarTypes::eAttribValue, VarTypes::eInsideTag, emptyXMLNode, VarTypes::eOutsideTag, VarTypes::XML::error, VarTypes::eTokenClear, VarTypes::eTokenCloseTag, VarTypes::eTokenDeclaration, VarTypes::eTokenEquals, VarTypes::eTokenError, VarTypes::eTokenQuotedText, VarTypes::eTokenShortHandClose, VarTypes::eTokenTagEnd, VarTypes::eTokenTagStart, VarTypes::eTokenText, exactMemory(), VarTypes::eXMLErrorMissingEndTag, VarTypes::eXMLErrorMissingEndTagName, VarTypes::eXMLErrorMissingTagName, VarTypes::eXMLErrorUnexpectedToken, VarTypes::eXMLErrorUnmatchedEndTag, FALSE, VarTypes::fromXMLString(), VarTypes::GetNextToken(), VarTypes::XMLNode::XMLNodeDataTag::isDeclaration, isEmpty(), VarTypes::XML::lpEndTag, VarTypes::XML::lpNewElement, VarTypes::XMLNode::XMLNodeDataTag::lpszName, VarTypes::XML::lpszText, VarTypes::XML::lpXML, maybeAddTxT(), MEMORYINCREASE, VarTypes::myTagCompare(), VarTypes::XML::nFirst, VarTypes::XML::nIndex, VarTypes::XML::nIndexMissigEndTag, parseClearTag(), ParseXMLElement(), VarTypes::NextToken::pClr, VarTypes::XMLNode::XMLNodeDataTag::pParent, VarTypes::NextToken::pStr, VarTypes::stringDup(), TRUE, and XMLCSTR.
Referenced by parseString(), and ParseXMLElement().
   {
       XML *pXML=(XML *)pa;
       int cbToken;
       enum XMLTokenTypeTag type;
       NextToken token;
       XMLCSTR lpszTemp=NULL;
       int cbTemp=0;
       char nDeclaration;
       XMLNode pNew;
       enum Status status; // inside or outside a tag
       enum Attrib attrib = eAttribName;
       assert(pXML);
       // If this is the first call to the function
       if (pXML->nFirst)
       {
           // Assume we are outside of a tag definition
           pXML->nFirst = FALSE;
           status = eOutsideTag;
       } else
       {
           // If this is not the first call then we should only be called when inside a tag.
           status = eInsideTag;
       }
       // Iterate through the tokens in the document
       for(;;)
       {
           // Obtain the next token
           token = GetNextToken(pXML, &cbToken, &type);
           if (type != eTokenError)
           {
               // Check the current status
               switch(status)
               {
               // If we are outside of a tag definition
               case eOutsideTag:
                   // Check what type of token we obtained
                   switch(type)
                   {
                   // If we have found text or quoted text
                   case eTokenText:
                   case eTokenCloseTag:          /* '>'         */
                   case eTokenShortHandClose:    /* '/>'        */
                   case eTokenQuotedText:
                   case eTokenEquals:
                       break;
                   // If we found a start tag '<' and declarations '<?'
                   case eTokenTagStart:
                   case eTokenDeclaration:
                       // Cache whether this new element is a declaration or not
                       nDeclaration = (type == eTokenDeclaration);
                       // If we have node text then add this to the element
                       if (maybeAddTxT(pXML,token.pStr)) return FALSE;
                       // Find the name of the tag
                       token = GetNextToken(pXML, &cbToken, &type);
                       // Return an error if we couldn't obtain the next token or
                       // it wasnt text
                       if (type != eTokenText)
                       {
                           pXML->error = eXMLErrorMissingTagName;
                           return FALSE;
                       }
                       // If we found a new element which is the same as this
                       // element then we need to pass this back to the caller..
   #ifdef APPROXIMATE_PARSING
                       if (d->lpszName &&
                           myTagCompare(d->lpszName, token.pStr) == 0)
                       {
                           // Indicate to the caller that it needs to create a
                           // new element.
                           pXML->lpNewElement = token.pStr;
                           pXML->cbNewElement = cbToken;
                           return TRUE;
                       } else
   #endif
                       {
                           // If the name of the new element differs from the name of
                           // the current element we need to add the new element to
                           // the current one and recurse
                           pNew = addChild_priv(MEMORYINCREASE,stringDup(token.pStr,cbToken), nDeclaration,-1);
                           while (!pNew.isEmpty())
{
                               // Callself to process the new node.  If we return
                               // FALSE this means we dont have any more
                               // processing to do...
                               if (!pNew.ParseXMLElement(pXML)) return FALSE;
                               else
{
                                   // If the call to recurse this function
                                   // evented in a end tag specified in XML then
                                   // we need to unwind the calls to this
                                   // function until we find the appropriate node
                                   // (the element name and end tag name must
                                   // match)
                                   if (pXML->cbEndTag)
{
                                       // If we are back at the root node then we
                                       // have an unmatched end tag
                                       if (!d->lpszName)
{
                                           pXML->error=eXMLErrorUnmatchedEndTag;
                                           return FALSE;
                                       }
                                       // If the end tag matches the name of this
                                       // element then we only need to unwind
                                       // once more...
                                       if (myTagCompare(d->lpszName, pXML->lpEndTag)==0)
{
                                           pXML->cbEndTag = 0;
                                       }
                                       return TRUE;
                                   } else
                                       if (pXML->cbNewElement)
{
                                           // If the call indicated a new element is to
                                           // be created on THIS element.
                                           // If the name of this element matches the
                                           // name of the element we need to create
                                           // then we need to return to the caller
                                           // and let it process the element.
                                           if (myTagCompare(d->lpszName, pXML->lpNewElement)==0)
{
                                               return TRUE;
                                           }
                                           // Add the new element and recurse
                                           pNew = addChild_priv(MEMORYINCREASE,stringDup(pXML->lpNewElement,pXML->cbNewElement),0,-1);
                                           pXML->cbNewElement = 0;
                                       }
                                       else
{
                                           // If we didn't have a new element to create
                                           pNew = emptyXMLNode;
                                       }
                               }
                           }
                       }
                       break;
                   // If we found an end tag
                   case eTokenTagEnd:
                       // If we have node text then add this to the element
                       if (maybeAddTxT(pXML,token.pStr)) return FALSE;
                       // Find the name of the end tag
                       token = GetNextToken(pXML, &cbTemp, &type);
                       // The end tag should be text
                       if (type != eTokenText)
                       {
                           pXML->error = eXMLErrorMissingEndTagName;
                           return FALSE;
                       }
                       lpszTemp = token.pStr;
                       // After the end tag we should find a closing tag
                       token = GetNextToken(pXML, &cbToken, &type);
                       if (type != eTokenCloseTag)
                       {
                           pXML->error = eXMLErrorMissingEndTagName;
                           return FALSE;
                       }
                       pXML->lpszText=pXML->lpXML+pXML->nIndex;
                       // We need to return to the previous caller.  If the name
                       // of the tag cannot be found we need to keep returning to
                       // caller until we find a match
                       if (myTagCompare(d->lpszName, lpszTemp) != 0)
   #ifdef STRICT_PARSING
                       {
                           pXML->error=eXMLErrorUnmatchedEndTag;
                           pXML->nIndexMissigEndTag=pXML->nIndex;
                           return FALSE;
                       }
   #else
                       {
                           pXML->error=eXMLErrorMissingEndTag;
                           pXML->nIndexMissigEndTag=pXML->nIndex;
                           pXML->lpEndTag = lpszTemp;
                           pXML->cbEndTag = cbTemp;
                       }
   #endif
                       // Return to the caller
                       exactMemory(d);
                       return TRUE;
                   // If we found a clear (unformatted) token
                   case eTokenClear:
                       // If we have node text then add this to the element
                       if (maybeAddTxT(pXML,token.pStr)) return FALSE;
                       if (parseClearTag(pXML, token.pClr)) return FALSE;
                       pXML->lpszText=pXML->lpXML+pXML->nIndex;
                       break;
                   default:
                       break;
                   }
                   break;
               // If we are inside a tag definition we need to search for attributes
               case eInsideTag:
                   // Check what part of the attribute (name, equals, value) we
                   // are looking for.
                   switch(attrib)
                   {
                   // If we are looking for a new attribute
                   case eAttribName:
                       // Check what the current token type is
                       switch(type)
                       {
                       // If the current type is text...
                       // Eg.  'attribute'
                       case eTokenText:
                           // Cache the token then indicate that we are next to
                           // look for the equals
                           lpszTemp = token.pStr;
                           cbTemp = cbToken;
                           attrib = eAttribEquals;
                           break;
                       // If we found a closing tag...
                       // Eg.  '>'
                       case eTokenCloseTag:
                           // We are now outside the tag
                           status = eOutsideTag;
                           pXML->lpszText=pXML->lpXML+pXML->nIndex;
                           break;
                       // If we found a short hand '/>' closing tag then we can
                       // return to the caller
                       case eTokenShortHandClose:
                           exactMemory(d);
                           pXML->lpszText=pXML->lpXML+pXML->nIndex;
                           return TRUE;
                       // Errors...
                       case eTokenQuotedText:    /* '"SomeText"'   */
                       case eTokenTagStart:      /* '<'            */
                       case eTokenTagEnd:        /* '</'           */
                       case eTokenEquals:        /* '='            */
                       case eTokenDeclaration:   /* '<?'           */
                       case eTokenClear:
                           pXML->error = eXMLErrorUnexpectedToken;
                           return FALSE;
                       default: break;
                       }
                       break;
                   // If we are looking for an equals
                   case eAttribEquals:
                       // Check what the current token type is
                       switch(type)
                       {
                       // If the current type is text...
                       // Eg.  'Attribute AnotherAttribute'
                       case eTokenText:
                           // Add the unvalued attribute to the list
                           addAttribute_priv(MEMORYINCREASE,stringDup(lpszTemp,cbTemp), NULL);
                           // Cache the token then indicate.  We are next to
                           // look for the equals attribute
                           lpszTemp = token.pStr;
                           cbTemp = cbToken;
                           break;
                       // If we found a closing tag 'Attribute >' or a short hand
                       // closing tag 'Attribute />'
                       case eTokenShortHandClose:
                       case eTokenCloseTag:
                           // If we are a declaration element '<?' then we need
                           // to remove extra closing '?' if it exists
                           pXML->lpszText=pXML->lpXML+pXML->nIndex;
                           if (d->isDeclaration &&
                               (lpszTemp[cbTemp-1]) == _T('?'))
{
                               cbTemp--;
                           }
                           if (cbTemp)
{
                               // Add the unvalued attribute to the list
                               addAttribute_priv(MEMORYINCREASE,stringDup(lpszTemp,cbTemp), NULL);
                           }
                           // If this is the end of the tag then return to the caller
                           if (type == eTokenShortHandClose)
{
                               exactMemory(d);
                               return TRUE;
                           }
                           // We are now outside the tag
                           status = eOutsideTag;
                           break;
                       // If we found the equals token...
                       // Eg.  'Attribute ='
                       case eTokenEquals:
                           // Indicate that we next need to search for the value
                           // for the attribute
                           attrib = eAttribValue;
                           break;
                       // Errors...
                       case eTokenQuotedText:    /* 'Attribute "InvalidAttr"'*/
                       case eTokenTagStart:      /* 'Attribute <'            */
                       case eTokenTagEnd:        /* 'Attribute </'           */
                       case eTokenDeclaration:   /* 'Attribute <?'           */
                       case eTokenClear:
                           pXML->error = eXMLErrorUnexpectedToken;
                           return FALSE;
                       default: break;
                       }
                       break;
                   // If we are looking for an attribute value
                   case eAttribValue:
                       // Check what the current token type is
                       switch(type)
                       {
                       // If the current type is text or quoted text...
                       // Eg.  'Attribute = "Value"' or 'Attribute = Value' or
                       // 'Attribute = 'Value''.
                       case eTokenText:
                       case eTokenQuotedText:
                           // If we are a declaration element '<?' then we need
                           // to remove extra closing '?' if it exists
                           if (d->isDeclaration &&
                               (token.pStr[cbToken-1]) == _T('?'))
{
                               cbToken--;
                           }
                           if (cbTemp)
{
                               // Add the valued attribute to the list
                               if (type==eTokenQuotedText) { token.pStr++; cbToken-=2; }
                               XMLCSTR attrVal=token.pStr;
                               if (attrVal)
{
                                   attrVal=fromXMLString(attrVal,cbToken,pXML);
                                   if (!attrVal) return FALSE;
                               }
                               addAttribute_priv(MEMORYINCREASE,stringDup(lpszTemp,cbTemp),attrVal);
                           }
                           // Indicate we are searching for a new attribute
                           attrib = eAttribName;
                           break;
                       // Errors...
                       case eTokenTagStart:        /* 'Attr = <'          */
                       case eTokenTagEnd:          /* 'Attr = </'         */
                       case eTokenCloseTag:        /* 'Attr = >'          */
                       case eTokenShortHandClose:  /* "Attr = />"         */
                       case eTokenEquals:          /* 'Attr = ='          */
                       case eTokenDeclaration:     /* 'Attr = <?'         */
                       case eTokenClear:
                           pXML->error = eXMLErrorUnexpectedToken;
                           return FALSE;
                           break;
                       default: break;
                       }
                   }
               }
           }
           // If we failed to obtain the next token
           else
           {
               if ((!d->isDeclaration)&&(d->pParent))
               {
   #ifdef STRICT_PARSING
                   pXML->error=eXMLErrorUnmatchedEndTag;
   #else
                   pXML->error=eXMLErrorMissingEndTag;
   #endif
                   pXML->nIndexMissigEndTag=pXML->nIndex;
               }
               return FALSE;
           }
       }
   }
int VarTypes::XMLNode::positionOfChildNode (int i = 0) const
Definition at line 2231 of file xmlParser.cpp.
References d, VarTypes::eNodeChild, findPosition(), and VarTypes::XMLNode::XMLNodeDataTag::nChild.
Referenced by positionOfChildNode().
 { if (i>=d->nChild) i=d->nChild-1; return findPosition(d,i,eNodeChild); }
int VarTypes::XMLNode::positionOfChildNode (XMLNode x) const
Definition at line 2235 of file xmlParser.cpp.
References d, VarTypes::eNodeChild, findPosition(), velocity.pid_::i, VarTypes::XMLNode::XMLNodeDataTag::nChild, and VarTypes::XMLNode::XMLNodeDataTag::pChild.
   {
       if ((!d)||(!x.d)) return -1;
       XMLNodeData *dd=x.d;
       XMLNode *pc=d->pChild;
       int i=d->nChild;
       while (i--) if (pc[i].d==dd) return findPosition(d,i,eNodeChild);
       return -1;
   }
int VarTypes::XMLNode::positionOfChildNode (const char * name, int i = 0) const
Definition at line 2244 of file xmlParser.cpp.
References d, VarTypes::eNodeChild, findPosition(), getChildNode(), and positionOfChildNode().
   {
       if (!name) return positionOfChildNode(count);
       int j=0;
       do { getChildNode(name,&j); if (j<0) return -1; } while (count--);
       return findPosition(d,j-1,eNodeChild);
   }
int VarTypes::XMLNode::positionOfClear (int i = 0) const
Definition at line 2230 of file xmlParser.cpp.
References d, VarTypes::eNodeClear, findPosition(), and VarTypes::XMLNode::XMLNodeDataTag::nClear.
Referenced by positionOfClear().
 { if (i>=d->nClear) i=d->nClear-1; return findPosition(d,i,eNodeClear); }
int VarTypes::XMLNode::positionOfClear (const char * lpszValue) const
Definition at line 2233 of file xmlParser.cpp.
References indexClear(), and positionOfClear().
 { return positionOfClear(indexClear(lpszValue)); }
int VarTypes::XMLNode::positionOfClear (XMLClear * a) const
Definition at line 2234 of file xmlParser.cpp.
References VarTypes::XMLClear::lpszValue, and positionOfClear().
 { if (a) return positionOfClear(a->lpszValue); return positionOfClear(); }
int VarTypes::XMLNode::positionOfText (int i = 0) const
Definition at line 2229 of file xmlParser.cpp.
References d, VarTypes::eNodeText, findPosition(), and VarTypes::XMLNode::XMLNodeDataTag::nText.
Referenced by positionOfText().
 { if (i>=d->nText ) i=d->nText-1;  return findPosition(d,i,eNodeText ); }
int VarTypes::XMLNode::positionOfText (const char * lpszValue) const
Definition at line 2232 of file xmlParser.cpp.
References indexText(), and positionOfText().
 { return positionOfText (indexText (lpszValue)); }
int VarTypes::XMLNode::removeOrderElement (XMLNodeData * d, XMLElementType t, int index) static private
Definition at line 972 of file xmlParser.cpp.
References findPosition(), velocity.pid_::i, VarTypes::XMLNode::XMLNodeDataTag::nChild, VarTypes::XMLNode::XMLNodeDataTag::nClear, VarTypes::XMLNode::XMLNodeDataTag::nText, and VarTypes::XMLNode::XMLNodeDataTag::pOrder.
Referenced by deleteClear(), deleteText(), and detachFromParent().
   {
       int n=d->nChild+d->nText+d->nClear, *o=d->pOrder,i=findPosition(d,index,t);
       memmove(o+i, o+i+1, (n-i)*sizeof(int));
       for (;i<n;i++)
           if ((o[i]&3)==(int)t) o[i]-=4;
       // We should normally do:
       // d->pOrder=(int)realloc(d->pOrder,n*sizeof(int));
       // but we skip reallocation because it's too time consuming.
       // Anyway, at the end, it will be free'd completely at once.
       return i;
   }
void VarTypes::XMLNode::setGlobalOptions (char guessUnicodeChars = 1, char strictUTF8Parsing = 1, char dropWhiteSpace = 1) static
Definition at line 2397 of file xmlParser.cpp.
References VarTypes::dropWhiteSpace, VarTypes::guessUnicodeChars, VarTypes::XML_asciiByteTable, and VarTypes::XML_utf8ByteTable.
Referenced by openFileHelper().
   {
       guessUnicodeChars=_guessUnicodeChars; dropWhiteSpace=_dropWhiteSpace; strictUTF8Parsing=_strictUTF8Parsing;
   #ifndef _XMLUNICODE
       if (_strictUTF8Parsing) XML_ByteTable=XML_utf8ByteTable; else XML_ByteTable=XML_asciiByteTable;
   #endif
   }
XMLAttribute * VarTypes::XMLNode::updateAttribute (XMLAttribute * newAttribute, XMLAttribute * oldAttribute)
Definition at line 2380 of file xmlParser.cpp.
References VarTypes::XMLAttribute::lpszName, VarTypes::XMLAttribute::lpszValue, VarTypes::stringDup(), and updateAttribute_WOSD().
Referenced by VarTypes::VarExternal::updateAttributes(), VarTypes::VarDouble::updateAttributes(), VarTypes::VarInt::updateAttributes(), and VarTypes::VarType::writeXML().
                 { return updateAttribute_WOSD(stringDup(newAttribute->lpszValue),stringDup(newAttribute->lpszName),oldAttribute->lpszName); }
XMLAttribute * VarTypes::XMLNode::updateAttribute (const char * lpszNewValue, const char * lpszNewName = NULL, int i = 0)
Definition at line 2382 of file xmlParser.cpp.
References VarTypes::stringDup(), and updateAttribute_WOSD().
                 { return updateAttribute_WOSD(stringDup(lpszNewValue),stringDup(lpszNewName),i); }
XMLAttribute * VarTypes::XMLNode::updateAttribute (const char * lpszNewValue, const char * lpszNewName, const char * lpszOldName)
Definition at line 2384 of file xmlParser.cpp.
References VarTypes::stringDup(), and updateAttribute_WOSD().
                 { return updateAttribute_WOSD(stringDup(lpszNewValue),stringDup(lpszNewName),lpszOldName); }
XMLAttribute * VarTypes::XMLNode::updateAttribute_WOSD (XMLAttribute * newAttribute, XMLAttribute * oldAttribute)
Definition at line 2065 of file xmlParser.cpp.
References addAttribute_WOSD(), VarTypes::XMLAttribute::lpszName, and VarTypes::XMLAttribute::lpszValue.
Referenced by updateAttribute(), and updateAttribute_WOSD().
   {
       if (oldAttribute) return updateAttribute_WOSD(newAttribute->lpszValue,newAttribute->lpszName,oldAttribute->lpszName);
       return addAttribute_WOSD(newAttribute->lpszName,newAttribute->lpszValue);
   }
XMLAttribute * VarTypes::XMLNode::updateAttribute_WOSD (const char * lpszNewValue, const char * lpszNewName = NULL, int i = 0)
Definition at line 2050 of file xmlParser.cpp.
References addAttribute_WOSD(), d, velocity.pid_::i, VarTypes::XMLAttribute::lpszName, VarTypes::XMLAttribute::lpszValue, VarTypes::XMLNode::XMLNodeDataTag::nAttribute, and VarTypes::XMLNode::XMLNodeDataTag::pAttribute.
   {
       if (!d) return NULL;
       if (i>=d->nAttribute)
       {
           if (lpszNewName) return addAttribute_WOSD(lpszNewName,lpszNewValue);
           return NULL;
       }
       XMLAttribute *p=d->pAttribute+i;
       if (p->lpszValue&&p->lpszValue!=lpszNewValue) free((void*)p->lpszValue);
       p->lpszValue=lpszNewValue;
       if (lpszNewName&&p->lpszName!=lpszNewName) { free((void*)p->lpszName); p->lpszName=lpszNewName; };
       return p;
   }
XMLAttribute * VarTypes::XMLNode::updateAttribute_WOSD (const char * lpszNewValue, const char * lpszNewName, const char * lpszOldName)
Definition at line 2071 of file xmlParser.cpp.
References addAttribute_WOSD(), getAttribute(), VarTypes::stringDup(), and updateAttribute_WOSD().
   {
       int j=0;
       getAttribute(lpszOldName,&j);
       if (j) return updateAttribute_WOSD(lpszNewValue,lpszNewName,j-1);
       else
       {
           if (lpszNewName) return addAttribute_WOSD(lpszNewName,lpszNewValue);
           else             return addAttribute_WOSD(stringDup(lpszOldName),lpszNewValue);
       }
   }
XMLClear * VarTypes::XMLNode::updateClear (const char * lpszNewContent, int i = 0)
Definition at line 2390 of file xmlParser.cpp.
References VarTypes::stringDup(), and updateClear_WOSD().
                 { return updateClear_WOSD(stringDup(lpszNewContent),i); }
XMLClear * VarTypes::XMLNode::updateClear (XMLClear * newP, XMLClear * oldP)
Definition at line 2394 of file xmlParser.cpp.
References VarTypes::XMLClear::lpszValue, VarTypes::stringDup(), and updateClear_WOSD().
                 { return updateClear_WOSD(stringDup(newP->lpszValue),oldP->lpszValue); }
XMLClear * VarTypes::XMLNode::updateClear (const char * lpszNewValue, const char * lpszOldValue)
Definition at line 2392 of file xmlParser.cpp.
References VarTypes::stringDup(), and updateClear_WOSD().
                 { return updateClear_WOSD(stringDup(lpszNewValue),lpszOldValue); }
XMLClear * VarTypes::XMLNode::updateClear_WOSD (const char * lpszNewContent, int i = 0)
Definition at line 2145 of file xmlParser.cpp.
References addClear_WOSD(), d, velocity.pid_::i, VarTypes::XMLClear::lpszValue, VarTypes::XMLNode::XMLNodeDataTag::nClear, and VarTypes::XMLNode::XMLNodeDataTag::pClear.
Referenced by updateClear(), and updateClear_WOSD().
   {
       if (!d) return NULL;
       if (i>=d->nClear)
       {
           return addClear_WOSD(XMLClearTags[0].lpszOpen,lpszNewContent,XMLClearTags[0].lpszClose);
       }
       XMLClear *p=d->pClear+i;
       if (lpszNewContent!=p->lpszValue) { free((void*)p->lpszValue); p->lpszValue=lpszNewContent; }
       return p;
   }
XMLClear * VarTypes::XMLNode::updateClear_WOSD (XMLClear * newP, XMLClear * oldP)
Definition at line 2165 of file xmlParser.cpp.
References VarTypes::XMLClear::lpszValue, and updateClear_WOSD().
   {
       if (oldP) return updateClear_WOSD(newP->lpszValue,oldP->lpszValue);
       return NULL;
   }
XMLClear * VarTypes::XMLNode::updateClear_WOSD (const char * lpszNewValue, const char * lpszOldValue)
Definition at line 2157 of file xmlParser.cpp.
References addClear_WOSD(), d, velocity.pid_::i, indexClear(), and updateClear_WOSD().
   {
       if (!d) return NULL;
       int i=indexClear(lpszOldValue);
       if (i>=0) return updateClear_WOSD(lpszNewValue,i);
       return addClear_WOSD(lpszNewValue,XMLClearTags[0].lpszOpen,XMLClearTags[0].lpszClose);
   }
const char * VarTypes::XMLNode::updateName (const char * lpszName)
Definition at line 2378 of file xmlParser.cpp.
References VarTypes::stringDup(), and updateName_WOSD().
                 { return updateName_WOSD(stringDup(lpszName)); }
const char * VarTypes::XMLNode::updateName_WOSD (const char * lpszName)
Definition at line 915 of file xmlParser.cpp.
References d, and VarTypes::XMLNode::XMLNodeDataTag::lpszName.
Referenced by updateName(), and XMLNode().
   {
       if (d->lpszName&&(lpszName!=d->lpszName)) free((void*)d->lpszName);
       d->lpszName=lpszName;
       return lpszName;
   }
const char * VarTypes::XMLNode::updateText (const char * lpszNewValue, int i = 0)
Definition at line 2386 of file xmlParser.cpp.
References VarTypes::stringDup(), and updateText_WOSD().
Referenced by VarTypes::VarType::updateText().
                 { return updateText_WOSD(stringDup(lpszNewValue),i); }
const char * VarTypes::XMLNode::updateText (const char * lpszNewValue, const char * lpszOldValue)
Definition at line 2388 of file xmlParser.cpp.
References VarTypes::stringDup(), and updateText_WOSD().
                 { return updateText_WOSD(stringDup(lpszNewValue),lpszOldValue); }
const char * VarTypes::XMLNode::updateText_WOSD (const char * lpszNewValue, int i = 0)
Definition at line 2105 of file xmlParser.cpp.
References addText_WOSD(), d, velocity.pid_::i, VarTypes::XMLNode::XMLNodeDataTag::nText, VarTypes::XMLNode::XMLNodeDataTag::pText, and XMLCSTR.
Referenced by updateText(), and updateText_WOSD().
   {
       if (!d) return NULL;
       if (i>=d->nText) return addText_WOSD(lpszNewValue);
       XMLCSTR *p=d->pText+i;
       if (*p!=lpszNewValue) { free((void*)*p); *p=lpszNewValue; }
       return lpszNewValue;
   }
const char * VarTypes::XMLNode::updateText_WOSD (const char * lpszNewValue, const char * lpszOldValue)
Definition at line 2114 of file xmlParser.cpp.
References addText_WOSD(), d, velocity.pid_::i, indexText(), and updateText_WOSD().
   {
       if (!d) return NULL;
       int i=indexText(lpszOldValue);
       if (i>=0) return updateText_WOSD(lpszNewValue,i);
       return addText_WOSD(lpszNewValue);
   }
XMLError VarTypes::XMLNode::writeToFile (const char * filename, const char * encoding = NULL, char nFormat = 1) const
Definition at line 421 of file xmlParser.cpp.
References _T, VarTypes::_tfopen(), createXMLString(), VarTypes::eXMLErrorCannotOpenWriteFile, VarTypes::eXMLErrorCannotWriteFile, VarTypes::eXMLErrorNone, velocity.pid_::i, isDeclaration(), t, XMLCHAR, and XMLSTR.
Referenced by VarTypes::VarExternal::updateChildren(), and VarTypes::VarXML::write().
   {
       int i;
       XMLSTR t=createXMLString(nFormat,&i);
       FILE *f=_tfopen(filename,_T("wb"));
       if (!f) return eXMLErrorCannotOpenWriteFile;
   #ifdef _XMLUNICODE
       unsigned char h[2]={ 0xFF, 0xFE };
       if (!fwrite(h,2,1,f)) return eXMLErrorCannotWriteFile;
       if (!isDeclaration())
       {
           if (!fwrite(_T("<?xml version=\"1.0\" encoding=\"utf-16\"?>\n"),sizeof(wchar_t)*40,1,f))
               return eXMLErrorCannotWriteFile;
       }
   #else
       if (!isDeclaration())
       {
           if ((!encoding)||(XML_ByteTable==XML_utf8ByteTable))
           {
               // header so that windows recognize the file as UTF-8:
               unsigned char h[3]={0xEF,0xBB,0xBF};
               if (!fwrite(h,3,1,f)) return eXMLErrorCannotWriteFile;
               if (!fwrite("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n",39,1,f)) return eXMLErrorCannotWriteFile;
           }
           else
               if (fprintf(f,"<?xml version=\"1.0\" encoding=\"%s\"?>\n",encoding)<0) return eXMLErrorCannotWriteFile;
       } else
       {
           if (XML_ByteTable==XML_utf8ByteTable) // test if strictUTF8Parsing==1"
           {
               unsigned char h[3]={0xEF,0xBB,0xBF}; if (!fwrite(h,3,1,f)) return eXMLErrorCannotWriteFile;
           }
       }
   #endif
       if (!fwrite(t,sizeof(XMLCHAR)*i,1,f)) return eXMLErrorCannotWriteFile;
       if (fclose(f)!=0) return eXMLErrorCannotWriteFile;
       free(t);
       return eXMLErrorNone;
   }
Field Documentation
XMLNodeData* VarTypes::XMLNode::d private
Definition at line 426 of file xmlParser.h.
Referenced by addAttribute_priv(), addChild(), addChild_priv(), addClear_priv(), addText_priv(), addToOrder(), createXMLString(), CreateXMLStringR(), VarTypes::XMLParserBase64Tool::decode(), deleteAttribute(), deleteClear(), deleteNodeContent(), deleteText(), enumContents(), VarTypes::fromXMLString(), getAttribute(), getAttributeName(), getAttributeValue(), getChildNode(), getClear(), getName(), getParentNode(), getText(), indexClear(), indexText(), isAttributeSet(), isDeclaration(), isEmpty(), VarTypes::myIsTextUnicode(), VarTypes::myWideCharToMultiByte(), nAttribute(), nChildNode(), nClear(), nElement(), nText(), operator=(), ParseXMLElement(), positionOfChildNode(), positionOfClear(), positionOfText(), updateAttribute_WOSD(), updateClear_WOSD(), updateName_WOSD(), updateText_WOSD(), and XMLNode().
XMLAttribute VarTypes::XMLNode::emptyXMLAttribute ={ NULL, NULL} static
Definition at line 279 of file xmlParser.h.
Referenced by addAttribute_priv(), getAttribute(), and VarTypes::stringDup().
XMLClear VarTypes::XMLNode::emptyXMLClear ={ NULL, NULL, NULL} static
Definition at line 278 of file xmlParser.h.
Referenced by addClear_priv(), getClear(), and VarTypes::stringDup().
XMLNode VarTypes::XMLNode::emptyXMLNode static
Definition at line 276 of file xmlParser.h.
Referenced by addChild_priv(), getChildNode(), getChildNodeWithAttribute(), getParentNode(), parseFile(), parseString(), ParseXMLElement(), and VarTypes::stringDup().
The documentation for this struct was generated from the following files:
ssl-vision/src/shared/vartypes/xml/xmlParser.h
ssl-vision/src/shared/vartypes/xml/xmlParser.cpp