Documentation: Images Class Reference
Images Class Reference
A class with simple static image manipulation operations.
#include <image.h>
Static Public Member Functions
static void convert (const yuvImage &a, rgbImage &b)
static void convert (const rgbImage &a, yuvImage &b)
static void convert (const rgbImage &a, greyImage &b)
static void convert (const rgbImage &a, rgbaImage &b)
static void RGBAsetAlpha (const greyImage &a, rgbaImage &b)
static void RGBAsetRGB (const rgbImage &a, rgbaImage &b)
Detailed Description
A class with simple static image manipulation operations.
Definition at line 523 of file image.h.
Member Function Documentation
static void Images::convert (const yuvImage & a, rgbImage & b) inline static
Definition at line 526 of file image.h.
References velocity.pid_::i, and Conversions::yuv2rgb().
Referenced by PluginCameraCalibration::detectEdges(), PluginVisualize::DrawSobelImage(), and CMPattern::TeamDetector::init().
{
     if (a.getNumPixels()==b.getNumPixels()) {
       yuv * p1=a.getPixelData();
       rgb * p2=b.getPixelData();
       int n=a.getNumPixels();
       for (int i=0;i<n;i++) {
         *p2=Conversions::yuv2rgb(*p1);
         p1++;
         p2++;
       }
     } else {
       fprintf(stderr,"Cannot convert image of different sizes\n");
     }
   }
static void Images::convert (const rgbImage & a, yuvImage & b) inline static
Definition at line 540 of file image.h.
References velocity.pid_::i, and Conversions::rgb2yuv().
{
     if (a.getNumPixels()==b.getNumPixels()) {
       rgb * p1=a.getPixelData();
       yuv * p2=b.getPixelData();
       int n=a.getNumPixels();
       for (int i=0;i<n;i++) {
         *p2=Conversions::rgb2yuv(*p1);
         p1++;
         p2++;
       }
     } else {
       fprintf(stderr,"Cannot convert image of different sizes\n");
     }
   }
static void Images::convert (const rgbImage & a, greyImage & b) inline static
Definition at line 554 of file image.h.
References ColorRGB< num, fmt >::getIntensity(), velocity.pid_::i, and ColorGrey< num, fmt >::v.
{
     if (a.getNumPixels()==b.getNumPixels()) {
       rgb * p1=a.getPixelData();
       grey * p2=b.getPixelData();
       int n=a.getNumPixels();
       for (int i=0;i<n;i++) {
         p2->v=(p1->getIntensity());
         p1++;
         p2++;
       }
     } else {
       fprintf(stderr,"Cannot convert image of different sizes\n");
     }
   }
static void Images::convert (const rgbImage & a, rgbaImage & b) inline static
Definition at line 568 of file image.h.
References ColorRGB< num, fmt >::b, ColorRGB< num, fmt >::g, velocity.pid_::i, ColorRGB< num, fmt >::r, and ColorRGBA< num, fmt >::set().
{
     if (a.getNumPixels()==b.getNumPixels()) {
       rgb * p1=a.getPixelData();
       rgba * p2=b.getPixelData();
       int n=a.getNumPixels();
       for (int i=0;i<n;i++) {
         p2->set(p1->r,p1->g,p1->b);
         p1++;
         p2++;
       }
     } else {
       fprintf(stderr,"Cannot convert image of different sizes\n");
     }
   }
static void Images::RGBAsetAlpha (const greyImage & a, rgbaImage & b) inline static
Definition at line 583 of file image.h.
References ColorRGBA< num, fmt >::a, velocity.pid_::i, and ColorGrey< num, fmt >::v.
{
     if (a.getNumPixels()==b.getNumPixels()) {
       grey * p1=a.getPixelData();
       rgba * p2=b.getPixelData();
       int n=a.getNumPixels();
       for (int i=0;i<n;i++) {
         p2->a = p1->v;
         p1++;
         p2++;
       }
     } else {
       fprintf(stderr,"Cannot convert image of different sizes\n");
     }
   }
static void Images::RGBAsetRGB (const rgbImage & a, rgbaImage & b) inline static
Definition at line 598 of file image.h.
References ColorRGB< num, fmt >::b, ColorRGBA< num, fmt >::b, ColorRGB< num, fmt >::g, ColorRGBA< num, fmt >::g, velocity.pid_::i, ColorRGB< num, fmt >::r, and ColorRGBA< num, fmt >::r.
{
     if (a.getNumPixels()==b.getNumPixels()) {
       rgb * p1=a.getPixelData();
       rgba * p2=b.getPixelData();
       int n=a.getNumPixels();
       for (int i=0;i<n;i++) {
         p2->r = p1->r;
         p2->g = p1->g;
         p2->b = p1->b;
         p1++;
         p2++;
       }
     } else {
       fprintf(stderr,"Cannot convert image of different sizes\n");
     }
   }
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/image.h