Documentation: RGBLUT Class Reference
RGBLUT Class Reference
A 3D RGB LUT.
#include <lut3d.h>
Public Member Functions
RGBLUT (unsigned int r_bits=5, unsigned int g_bits=5, unsigned int b_bits=5, string filename="rgblut.xml")
virtual void deriveFromLUT (LUT3D *lut)
virtual ColorSpace getColorSpace () const
Public Member Functions inherited from LUT3D
LUT3D (unsigned int x_bits=7, unsigned int y_bits=7, unsigned int z_bits=7, string filename="3dlut.xml")
void lock ()
void unlock ()
VarList * getSettings ()
LUTChannel getChannel (unsigned int idx) const
void clearDerivedLUTs (bool unallocate_derived_memory=true)
int getDerivedLUTcount ()
LUT3D * getDerivedLUT (int idx)
void addDerivedLUT (LUT3D *lut)
LUT3D * getDerivedLUT (ColorSpace space)
void updateDerivedLUTs ()
int getChannelID (const string &label) const
void setChannel (unsigned int idx, LUTChannel c)
int getChannelCount () const
int getSizeX () const
int getSizeY () const
int getSizeZ () const
int getMaxX () const
int getMaxY () const
int getMaxZ () const
virtual ~LUT3D ()
void reset ()
lut_mask_t * getTable () const
lut_mask_t * getPointer (unsigned char x, unsigned char y, unsigned char z) const
lut_mask_t * getPointerPreshrunk (unsigned char x, unsigned char y, unsigned char z) const
unsigned char norm2lutX (unsigned char x) const
unsigned char norm2lutY (unsigned char y) const
unsigned char norm2lutZ (unsigned char z) const
unsigned char lut2normX (unsigned char x) const
unsigned char lut2normY (unsigned char y) const
unsigned char lut2normZ (unsigned char z) const
void set (unsigned char x, unsigned char y, unsigned char z, lut_mask_t mask)
void set_preshrunk (unsigned char x, unsigned char y, unsigned char z, lut_mask_t mask)
lut_mask_t get (const unsigned char x, const unsigned char y, const unsigned char z)
lut_mask_t get_preshrunk (const unsigned char x, const unsigned char y, const unsigned char z)
void copyChannels (const LUT3D &other)
void loadRoboCupChannels (LUTChannelMode mode)
void loadBlackWhite (LUTChannelMode mode)
void maskFillYZ (unsigned char slice_x, unsigned char origin_y, unsigned char origin_z, lut_mask_t new_color, LUTChannelMode mode, bool remove=false, bool check_exact=true, bool write_exclusive=false)
Additional Inherited Members
Data Fields inherited from LUT3D
unsigned int X_BITS
unsigned int Y_BITS
unsigned int Z_BITS
unsigned int X_SHIFT
unsigned int Y_SHIFT
unsigned int Z_SHIFT
unsigned int Y_SHIFT_PLUS_8
unsigned int Z_SHIFT_PLUS_16
unsigned int Z_AND_Y_BITS
unsigned int TOTAL_BITS
unsigned int LUT_SIZE
lut_mask_t * LUT
VarBlob * v_blob
VarList * v_settings
vector< LUTChannel > channels
vector< LUT3D * > derived_LUTs
QMutex mutex
Protected Slots inherited from LUT3D
void slotVBlobChange ()
Detailed Description
A 3D RGB LUT.
Author
Stefan Zickler
Definition at line 481 of file lut3d.h.
Constructor & Destructor Documentation
RGBLUT::RGBLUT (unsigned int r_bits = 5, unsigned int g_bits = 5, unsigned int b_bits = 5, string filename = "rgblut.xml") inline
Definition at line 483 of file lut3d.h.
 : LUT3D(r_bits, g_bits, b_bits,filename) {};
Member Function Documentation
virtual void RGBLUT::deriveFromLUT (LUT3D * lut) inline virtual
Reimplemented from LUT3D.
Definition at line 484 of file lut3d.h.
References CSPACE_YUV, LUT3D::get(), LUT3D::getColorSpace(), Conversions::rgb2yuv(), v, and role._GoToPoint::y.
{
     if (lut->getColorSpace()!=CSPACE_YUV) {
       fprintf(stderr,"Warning: deriveFromLUT input on RGBLUT does not seem to be in YUV color-space\n");
     } else {
       // OLD :
       /*int y,u,v;
       for (int r=0;r<=255;r++) {
         for (int g=0;g<=255;g++) {
           for (int b=0;b<=255;b++) {
             Conversions::rgb2yuv(r,g,b,y,u,v);
             set((unsigned char)r,(unsigned char)g,(unsigned char)b,lut->get((unsigned char)y,(unsigned char)u,(unsigned char)v));
           }
         }
       }*/
       //new, faster:
       int y,u,v;
       int rn=this->getSizeX();
       int gn=this->getSizeY();
       int bn=this->getSizeZ();
       for (int r=0;r!=rn;r++) {
         for (int g=0;g!=gn;g++) {
           for (int b=0;b!=bn;b++) {
             Conversions::rgb2yuv((int)lut2normX((unsigned char)r),(int)lut2normY((unsigned char)g),(int)lut2normZ((unsigned char)b),y,u,v);
             set_preshrunk(r,g,b,lut->get((unsigned char)y,(unsigned char)u,(unsigned char)v));
           }
         }
       }
     }
   }
virtual ColorSpace RGBLUT::getColorSpace () const inline virtual
Reimplemented from LUT3D.
Definition at line 516 of file lut3d.h.
References CSPACE_RGB.
{
     return CSPACE_RGB;
   }
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/lut3d.h