Documentation: CaptureInterface Class Reference
CaptureInterface Class Reference abstract
The interface to be used by all video capture methods.
#include <captureinterface.h>
Public Member Functions
CaptureInterface (VarList *_settings=0)
virtual ~CaptureInterface ()
virtual RawImage getFrame ()=0
virtual bool isCapturing ()=0
virtual void releaseFrame ()=0
This releases the pointer of a previous getFrame() call.
virtual bool startCapture ()=0
virtual bool stopCapture ()=0
This will make your method stop capturing data.
virtual bool resetBus ()
virtual void readAllParameterValues ()
virtual bool copyAndConvertFrame (const RawImage &src, RawImage &target)
virtual string getCaptureMethodName () const =0
Data Fields
VarList * settings
Detailed Description
The interface to be used by all video capture methods.
Author
Stefan Zickler, (C) 2008
The CaptureInterface is the base class that should be inherited for any particular capturing method implementation.
It relies on the VarTypes system (see
See also
VarTypes.h) for the management an introspection-abilities of settings.
Definition at line 43 of file captureinterface.h.
Constructor & Destructor Documentation
CaptureInterface::CaptureInterface (VarList * _settings = 0)
Definition at line 24 of file captureinterface.cpp.
References settings.
 {
   if (_settings!=0) {
     settings=_settings;
   } else {
     settings=new VarList("capture settings");
   }
 }
CaptureInterface::~CaptureInterface () virtual
Definition at line 34 of file captureinterface.cpp.
References settings.
 {
   delete settings;
 }
Member Function Documentation
bool CaptureInterface::copyAndConvertFrame (const RawImage & src, RawImage & target) virtual
This function will allow the copying of a captured frame to another RawImage data-structure. Overloading this function is recommended to provide more advanced functionality, such as converting the frame from one format to another. which format to convert to, should be a VarTypes option, added to the settings above. For an example implementation, please see how this function is overloaded in the CaptureDC1394v2 class.
In its current implementation in this base-interface, all this function will do is allocate the target image (if not already allocated, and then memcpy the data as-is.
Reimplemented in CaptureDC1394v2, CaptureV4L, CaptureBlueFox2, CaptureFlycap, CaptureFromFile, and CaptureGenerator.
Definition at line 48 of file captureinterface.cpp.
References RawImage::ensure_allocation(), RawImage::getColorFormat(), RawImage::getData(), RawImage::getHeight(), RawImage::getNumBytes(), RawImage::getTime(), RawImage::getWidth(), and RawImage::setTime().
Referenced by CaptureThread::run().
{
   target.ensure_allocation(target.getColorFormat(),src.getWidth(),src.getHeight());
   target.setTime(src.getTime());
   memcpy(target.getData(),src.getData(),src.getNumBytes());
   return true;
 }
virtual string CaptureInterface::getCaptureMethodName () const pure virtual
Return a string describing your capture method e.g. DC1394B, or GigEVision, or V4LCapture, or USBCam,...
Implemented in CaptureDC1394v2, CaptureV4L, CaptureBlueFox2, CaptureFlycap, CaptureFromFile, and CaptureGenerator.
virtual RawImage CaptureInterface::getFrame () pure virtual
This returns a raw-image with a pointer directly to the video-buffer Note, that this pointer is only guaranteed to point to a valid memory location until releaseFrame() is called.
Implemented in CaptureDC1394v2, CaptureV4L, CaptureBlueFox2, CaptureFlycap, CaptureFromFile, and CaptureGenerator.
Referenced by CaptureThread::run().
virtual bool CaptureInterface::isCapturing () pure virtual
This function should return true, if your method is currently actively capturing data.
Implemented in CaptureDC1394v2, CaptureV4L, CaptureBlueFox2, CaptureFlycap, CaptureFromFile, and CaptureGenerator.
Referenced by CaptureThread::run(), and CaptureThread::selectCaptureMethod().
void CaptureInterface::readAllParameterValues () virtual
If your capture device provides some kind of parameter readout that isn't automatically read-out at every frame, then this function should force a readout of such parameters.
Reimplemented in CaptureDC1394v2, CaptureV4L, CaptureBlueFox2, and CaptureFlycap.
Definition at line 44 of file captureinterface.cpp.
Referenced by CaptureThread::refresh(), and CaptureThread::run().
{
 }
virtual void CaptureInterface::releaseFrame () pure virtual
This releases the pointer of a previous getFrame() call.
Implemented in CaptureDC1394v2, CaptureV4L, CaptureBlueFox2, CaptureFlycap, CaptureFromFile, and CaptureGenerator.
Referenced by CaptureThread::run().
bool CaptureInterface::resetBus () virtual
If applicable, this will enforce a reinitialization / reset on your capturing hardware, in case something went wrong.
This is applicable, for example for DC1394 based systems where a firewire bus is able to 'freeze up' and can be reinitialized by a bus reset.
Reimplemented in CaptureDC1394v2, CaptureV4L, CaptureBlueFox2, and CaptureFlycap.
Definition at line 40 of file captureinterface.cpp.
Referenced by CaptureThread::reset().
{
   return true;
 }
virtual bool CaptureInterface::startCapture () pure virtual
This will make your method start capturing data Note, that upon construction, your class should NOT be starting to capture data automatically. Instead a call to startCapture() is required.
Implemented in CaptureDC1394v2, CaptureV4L, CaptureBlueFox2, CaptureFlycap, CaptureFromFile, and CaptureGenerator.
Referenced by CaptureThread::init().
virtual bool CaptureInterface::stopCapture () pure virtual
This will make your method stop capturing data.
Implemented in CaptureDC1394v2, CaptureV4L, CaptureBlueFox2, CaptureFlycap, CaptureFromFile, and CaptureGenerator.
Referenced by CaptureThread::run(), and CaptureThread::stop().
Field Documentation
VarList* CaptureInterface::settings
Any settings that your video capture method provides should be added as VarTypes-nodes in the VarList tree below: Please see VarTypes.h for more information on how to use VarTypes, or take a look at an existing capture method which implements this interface.
Definition at line 55 of file captureinterface.h.
Referenced by CaptureBlueFox2::CaptureBlueFox2(), CaptureDC1394v2::CaptureDC1394v2(), CaptureFlycap::CaptureFlycap(), CaptureFromFile::CaptureFromFile(), CaptureGenerator::CaptureGenerator(), CaptureInterface(), CaptureV4L::CaptureV4L(), and ~CaptureInterface().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/capture/captureinterface.h
ssl-vision/src/shared/capture/captureinterface.cpp