Documentation: HAL::Serial Class Reference
HAL::Serial Class Reference
#include <serial.h>
Public Member Functions
Serial ()
~Serial ()
bool Open (const std::string &device, int baud)
void Close (void)
int Read (void *buf, int size)
int Write (void *buf, int size)
int WriteByte (char b)
int ReadByte (void)
int ReadNBytesTimeout (int n, char *data, float ms, bool &ok)
int ReadByteTimeout (float ms, bool &ok)
void Clear ()
Data Fields
fd_set set
struct timeval timeout
Private Attributes
int fd
Detailed Description
Definition at line 33 of file serial.h.
Constructor & Destructor Documentation
HAL::Serial::Serial () inline
Definition at line 41 of file serial.h.
     {
 #ifdef WIN32
       hCom = INVALID_HANDLE_VALUE;
 #else
       fd = 0;
 #endif
     }
HAL::Serial::~Serial () inline
Definition at line 50 of file serial.h.
References Close(), and Open().
     {
 #ifdef WIN32
       if (hCom != INVALID_HANDLE_VALUE) Close();
 #else
       if (fd) close(fd);
 #endif
     }
Member Function Documentation
void HAL::Serial::Clear ()
Definition at line 420 of file serial.cpp.
References fd.
Referenced by Write().
   {
     #if WIN32
     #else
     tcflush(fd,TCIOFLUSH);
     #endif
   }
void HAL::Serial::Close (void)
Definition at line 265 of file serial.cpp.
References buf, fd, Read(), and Write().
Referenced by Open(), and ~Serial().
   {
 #ifdef WIN32
     if(!CloseHandle(hCom))
       fprintf(stderr, "ERROR: Can't close comm port.\n");
     hCom = INVALID_HANDLE_VALUE;
 #else
     if(fd)
     {
       ::close(fd);
       fd = 0;
     }
 #endif
   }
bool HAL::Serial::Open (const std::string & device, int baud)
Definition at line 114 of file serial.cpp.
References HAL::baud_flag_to_rate(), HAL::baud_rate_to_flag(), Close(), FALSE, and fd.
Referenced by main(), and ~Serial().
   {
 #ifdef WIN32
     DCB dcb;
     hCom = CreateFile( device.c_str(),
                        GENERIC_READ | GENERIC_WRITE,
                        0,    // exclusive access
                        NULL, // no security attributes
                        OPEN_EXISTING, 0, NULL);
     if (hCom == INVALID_HANDLE_VALUE)
     {
       err("ERROR: Can't open com port %s", device.c_str());
       return false;
     }
     if (!GetCommState(hCom, &dcb))
     {
       err("ERROR: Can't get CommState.\n");
       Close();
       return false;
     }
     switch (baud)
     {
       case 9600:
         dcb.BaudRate = CBR_9600;
         break;
       case 19200:
         dcb.BaudRate = CBR_19200;
         break;
       case 110:
         dcb.BaudRate = CBR_110;
         break;
       case 300:
         dcb.BaudRate = CBR_300;
         break;
       case 38400:
         dcb.BaudRate = CBR_38400;
         break;
       case 600:
         dcb.BaudRate = CBR_600;
         break;
       case 56000:
         dcb.BaudRate = CBR_56000;
         break;
       case 1200:
         dcb.BaudRate = CBR_1200;
         break;
       case 57600:
         dcb.BaudRate = CBR_57600;
         break;
       case 2400:
         dcb.BaudRate = CBR_2400;
         break;
       case 115200:
         dcb.BaudRate = CBR_115200;
         break;
       case 4800:
         dcb.BaudRate = CBR_4800;
         break;
       case 128000:
         dcb.BaudRate = CBR_128000;
         break;
       case 256000:
         dcb.BaudRate = CBR_256000;
         break;
       case 14400:
         dcb.BaudRate = CBR_14400;
         break;
       default:
         fprintf(stderr, "ERROR: Baut rate currently not supported.\n");
         Close();
         return false;
     }
     dcb.ByteSize = 8;
     dcb.fParity = FALSE;
     dcb.fDsrSensitivity = FALSE;
     dcb.fDtrControl = DTR_CONTROL_DISABLE;
     dcb.fOutxCtsFlow = FALSE;
     dcb.fOutxDsrFlow = FALSE;
     dcb.fOutX = FALSE;
     dcb.fInX = FALSE;
     dcb.fRtsControl = RTS_CONTROL_DISABLE;
     dcb.Parity = NOPARITY;
     dcb.StopBits = ONESTOPBIT;
     if(!SetCommState(hCom, &dcb))
     {
       fprintf(stderr, "ERROR: Can't set CommState.\n");
       Close();
       return false;
     }
     return true;
 #else
     struct termios tio;
     speed_t bf;
     int baud_in, baud_out;
     // open device
     fd = ::open(device.c_str(), O_RDWR | O_SYNC);
     perror("");
     if (fd < 0)
       return(false);
     /* set control attributes -
      * binary I/O, no flow control
      */
     tcgetattr(fd, &tio);
     cfmakeraw(&tio);
     tio.c_cflag &= ~(CRTSCTS | IXON | IXOFF);
     // set serial port speed
     bf = baud_rate_to_flag(baud);
     cfsetispeed(&tio, bf);
     cfsetospeed(&tio, bf);
     tcsetattr(fd, TCSANOW, &tio);
     // test what actually got set
     memset(&tio, 0, sizeof(tio));
     tcgetattr(fd, &tio);
     baud_in  = baud_flag_to_rate(cfgetispeed(&tio));
     baud_out = baud_flag_to_rate(cfgetospeed(&tio));
     return((baud_in == baud) && (baud_out == baud));
 #endif
   }
int HAL::Serial::Read (void * buf, int size) inline
Definition at line 67 of file serial.h.
Referenced by Close(), main(), ReadByte(), ReadByteTimeout(), and ReadNBytesTimeout().
     {return(::read(fd, buf, size));}
int HAL::Serial::ReadByte (void)
Definition at line 342 of file serial.cpp.
References fd, and Read().
Referenced by Write().
   {
 #ifdef WIN32
     char b;
     return Read(&b, 1);
     return b;
 #else
     char  data;
     int   ret_val;
     if ((ret_val = ::read(fd, &data, 1)) < 0)
       return (ret_val);
     return (data);
 #endif
   }
int HAL::Serial::ReadByteTimeout (float ms, bool & ok)
Definition at line 364 of file serial.cpp.
References fd, Read(), and timeout.
Referenced by Write().
   {
     ok = false;
 #ifdef WIN32
     char b;
     return Read(&b, 1);
     return b;
 #else
     int ret_val;
     char data;
     FD_ZERO(&set); /* clear the set */
     FD_SET(fd, &set); /* add our file descriptor to the set */
     timeout.tv_sec = 0;
     timeout.tv_usec = ms*1000;
     int rv = select(fd + 1, &set, NULL, NULL, &timeout);
     if(rv == -1)
       perror("select"); /* an error accured */
     else if(rv == 0){}
       //printf("><><><><><><>::::::::::><><><><><><><>timeout\n"); /* a timeout occured */
     else {
       ok = true;
       if ((ret_val = ::read(fd, &data, 1)) < 0)
         return (ret_val);
       return (data);
     }
     return data;
 #endif
   }
int HAL::Serial::ReadNBytesTimeout (int n, char * data, float ms, bool & ok)
Definition at line 393 of file serial.cpp.
References fd, Read(), and timeout.
Referenced by Write().
   {
     ok = false;
 #ifdef WIN32
     char b;
     return Read(&b, 1);
     return b;
 #else
     int ret_val;
     FD_ZERO(&set); /* clear the set */
     FD_SET(fd, &set); /* add our file descriptor to the set */
     timeout.tv_sec = 0;
     timeout.tv_usec = ms*1000;
     int rv = select(fd + 1, &set, NULL, NULL, &timeout);
     if(rv == -1)
       perror("select"); /* an error accured */
     else if(rv == 0){}
 //      printf("><><><><><><>::::::::::><><><><><><><>timeout\n"); /* a timeout occured */
     else {
       ok = true;
       ret_val = ::read(fd, data, n);
       return (ret_val);
     }
     return -1;
 #endif
   }
int HAL::Serial::Write (void * buf, int size) inline
Definition at line 73 of file serial.h.
References Clear(), ReadByte(), ReadByteTimeout(), ReadNBytesTimeout(), and WriteByte().
Referenced by CallBack(), Close(), main(), and WriteByte().
     {return(::write(fd, buf, size));}
int HAL::Serial::WriteByte (char b)
Definition at line 327 of file serial.cpp.
References fd, and Write().
Referenced by Write().
   {
 #ifdef WIN32
     return Write(&b, 1);
 #else
     return (::write(fd, &b, 1));
 #endif
   }
Field Documentation
int HAL::Serial::fd private
Definition at line 38 of file serial.h.
Referenced by Clear(), Close(), Open(), ReadByte(), ReadByteTimeout(), ReadNBytesTimeout(), and WriteByte().
fd_set HAL::Serial::set
Definition at line 84 of file serial.h.
struct timeval HAL::Serial::timeout
Definition at line 85 of file serial.h.
Referenced by ReadByteTimeout(), and ReadNBytesTimeout().
The documentation for this class was generated from the following files:
bot_comm/src/serial.h
bot_comm/src/serial.cpp