Documentation: composite_behavior.CompositeBehavior Class Reference
composite_behavior.CompositeBehavior Class Reference
A composite behavior is one that has 0+ named subbehaviors this class has methods for making it easy to work with and manage subbehaviors.
Public Member Functions
def __init__ (self)
def add_subbehavior (self, bhvr, name, required=True, priority=100)
Adds a subbehavior in composite behavior.
def remove_subbehavior (self, name)
def has_subbehavior_with_name (self, name)
def has_subbehaviors (self)
def subbehavior_with_name (self, name)
def subbehaviors_by_name (self)
def remove_all_subbehaviors (self)
def all_subbehaviors (self)
def all_subbehaviors_completed (self)
def spin_cb (self)
Override StateMachine.spin() so we can call spin() on subbehaviors.
def handle_subbehavior_exception (self, name, exception)
Override point for exception handling this is called whenever a subbehavior throws an exception during spin() subclasses of CompositeBehavior can override this to perform custom actions, such as removing the offending subbehavior the default implementation logs the exception and re-raises it.
def role_requirements (self)
returns a tree of role_requirements
def assign_roles (self, assignments)
assignments is a tree with the same structure as that returned by role_requirements() the only difference is that leaf nodes are (RoleRequirements, OurRobot) tuples instead of just RoleRequirements
def __str__ (self)
Public Member Functions inherited from behavior.Behavior
def __init__ (self)
def is_done_running (self)
Whether or not the Behavior is running Because we use hierarchial state machines, a behavior never be in the "running", but may be in a substate of it This is a convenience method to check whether or not the play is running.
def set_failed (self)
Set the behavior to failed if sub behaviors remains uncompleted.
def terminate (self)
Transitions the Behavior into a terminal state (either completed or cancelled)
def behavior_state (self)
returns a state in Behavior.State that represents what the behaviors is doing use this instead of the property if you want to avoid dealing with custom subclass substates
Public Member Functions inherited from fsm.StateMachine
def __init__ (self, start_state, end_state)
def start_state (self)
def restart (self)
def add_state (self, state, parent_state=None)
def spin (self)
def add_transition (self, from_state, to_state, condition, event_name)
def transition (self, new_state)
def is_in_state (self, state)
def state_is_substate (self, state, possible_parent)
def corresponding_ancestor_state (self, ancestors)
def ancestors_of_state (self, state)
def as_graphviz (self)
def write_diagram_png (self)
def state (self)
Private Attributes
_subbehavior_info
Detailed Description
A composite behavior is one that has 0+ named subbehaviors this class has methods for making it easy to work with and manage subbehaviors.
Definition at line 12 of file composite_behavior.py.
Constructor & Destructor Documentation
def composite_behavior.CompositeBehavior.__init__ (self)
Definition at line 13 of file composite_behavior.py.
     def __init__(self) :
         super(CompositeBehavior,self).__init__()
         self._subbehavior_info = {}  # type: Dict[str, Dict]
Member Function Documentation
def composite_behavior.CompositeBehavior.__str__ (self)
Definition at line 169 of file composite_behavior.py.
References composite_behavior.CompositeBehavior._subbehavior_info.
Referenced by composite_behavior.CompositeBehavior.assign_roles().
     def __str__(self) :
         desc = super().__str__()
         for name in self._subbehavior_info:
             bhvr = self._subbehavior_info[name]['behavior']
             # indent the subbehavior's description
             indent = '    '
             subdesc = str(bhvr)
             subdesc = "\n" + indent + re.sub(r'\n', '\n' + indent, subdesc)
             desc += subdesc
         return desc
def composite_behavior.CompositeBehavior.add_subbehavior (self, bhvr, name, required = True, priority = 100)
Adds a subbehavior in composite behavior.
Parameters
bhvr Behavior Instance
name Name of Subbehavior, to be used for identification
required TO BE IMPLEMENTED
priority TO BE IMPLEMENTED
Definition at line 34 of file composite_behavior.py.
References composite_behavior.CompositeBehavior._subbehavior_info, and composite_behavior.CompositeBehavior.remove_subbehavior().
Referenced by tactics.Triangle_Pass.CoordinatedPass.on_enter_preparing(), role.Pass_Receive.PassReceive.on_enter_receiving(), and tactics.Triangle_Pass.CoordinatedPass.on_enter_running().
                         priority=100):
         if name in self._subbehavior_info:
             raise AssertionError("There's already a subbehavior with name: '" +
                                  name + "'")
         if isinstance(priority, int):
             priority_func = (lambda: priority)
         else:
             priority_func = priority
         self._subbehavior_info[name] = {
             'required': required,
             'priority': priority_func,
             'behavior': bhvr
         }
def composite_behavior.CompositeBehavior.all_subbehaviors (self)
Definition at line 73 of file composite_behavior.py.
References composite_behavior.CompositeBehavior._subbehavior_info, and composite_behavior.CompositeBehavior.all_subbehaviors_completed().
Referenced by composite_behavior.CompositeBehavior.all_subbehaviors_completed(), and composite_behavior.CompositeBehavior.remove_all_subbehaviors().
     def all_subbehaviors(self) :
         return [
             self._subbehavior_info[name]['behavior']
             for name in self._subbehavior_info
         ]
def composite_behavior.CompositeBehavior.all_subbehaviors_completed (self)
Definition at line 79 of file composite_behavior.py.
References composite_behavior.CompositeBehavior.all_subbehaviors(), and composite_behavior.CompositeBehavior.spin_cb().
Referenced by composite_behavior.CompositeBehavior.all_subbehaviors().
     def all_subbehaviors_completed(self):
         return all(
             [bhvr.is_done_running() for bhvr in self.all_subbehaviors()])
def composite_behavior.CompositeBehavior.assign_roles (self, assignments)
assignments is a tree with the same structure as that returned by role_requirements() the only difference is that leaf nodes are (RoleRequirements, OurRobot) tuples instead of just RoleRequirements
Definition at line 165 of file composite_behavior.py.
References composite_behavior.CompositeBehavior.__str__(), and composite_behavior.CompositeBehavior.subbehavior_with_name().
Referenced by composite_behavior.CompositeBehavior.role_requirements().
     def assign_roles(self, assignments):
         for name, subtree in assignments.items():
             self.subbehavior_with_name(name).assign_roles(subtree)
def composite_behavior.CompositeBehavior.handle_subbehavior_exception (self, name, exception)
Override point for exception handling this is called whenever a subbehavior throws an exception during spin() subclasses of CompositeBehavior can override this to perform custom actions, such as removing the offending subbehavior the default implementation logs the exception and re-raises it.
Definition at line 141 of file composite_behavior.py.
References composite_behavior.CompositeBehavior.role_requirements().
Referenced by composite_behavior.CompositeBehavior.spin_cb().
     def handle_subbehavior_exception(self, name, exception):
         # We only call this inside the above except
         #pylint: disable=misplaced-bare-raise
         logging.error("Exception occurred when spinning subbehavior named '" +
                       name + "': " + str(exception))
         traceback.print_exc()
         raise
def composite_behavior.CompositeBehavior.has_subbehavior_with_name (self, name)
Definition at line 53 of file composite_behavior.py.
References composite_behavior.CompositeBehavior._subbehavior_info, and composite_behavior.CompositeBehavior.has_subbehaviors().
Referenced by tactics.Triangle_Pass.CoordinatedPass.execute_running(), tactics.Triangle_Pass.CoordinatedPass.get_robots(), and composite_behavior.CompositeBehavior.remove_subbehavior().
     def has_subbehavior_with_name(self, name):
         return name in self._subbehavior_info
def composite_behavior.CompositeBehavior.has_subbehaviors (self)
Definition at line 56 of file composite_behavior.py.
References composite_behavior.CompositeBehavior._subbehavior_info, and composite_behavior.CompositeBehavior.subbehavior_with_name().
Referenced by composite_behavior.CompositeBehavior.has_subbehavior_with_name().
     def has_subbehaviors(self) :
         return len(self._subbehavior_info) > 0
def composite_behavior.CompositeBehavior.remove_all_subbehaviors (self)
Definition at line 68 of file composite_behavior.py.
References composite_behavior.CompositeBehavior.all_subbehaviors(), and composite_behavior.CompositeBehavior.remove_subbehavior().
Referenced by composite_behavior.CompositeBehavior.subbehaviors_by_name().
     def remove_all_subbehaviors(self):
         subbehaviorNames = list(self._subbehavior_info.keys())
         for name in subbehaviorNames:
             self.remove_subbehavior(name)
def composite_behavior.CompositeBehavior.remove_subbehavior (self, name)
Definition at line 50 of file composite_behavior.py.
References composite_behavior.CompositeBehavior._subbehavior_info, and composite_behavior.CompositeBehavior.has_subbehavior_with_name().
Referenced by composite_behavior.CompositeBehavior.add_subbehavior(), tactics.Triangle_Pass.CoordinatedPass.on_enter_receiving(), role.Pass_Receive.PassReceive.on_exit_receiving(), tactics.CoPass.CoordinatedPass.on_exit_receiving(), tactics.sample_tactic.SampleTactic.on_exit_running(), tactics.Triangle_Pass.CoordinatedPass.on_exit_running(), and composite_behavior.CompositeBehavior.remove_all_subbehaviors().
     def remove_subbehavior(self, name):
         del self._subbehavior_info[name]
def composite_behavior.CompositeBehavior.role_requirements (self)
returns a tree of role_requirements
Definition at line 150 of file composite_behavior.py.
References composite_behavior.CompositeBehavior.assign_roles().
Referenced by composite_behavior.CompositeBehavior.handle_subbehavior_exception().
     def role_requirements(self):
         reqs = {}
         for name, info in self._subbehavior_info.items():
             r = info['behavior'].role_requirements()
             # r could be a RoleRequirements or a dict forming a subtree
             if isinstance(r, role_assignment.RoleRequirements):
                 r.required = info['required']
                 r.priority = info['priority']()
             # FIXME: should required and priority propogate if it's a tree?
             reqs[name] = r
         return reqs
def composite_behavior.CompositeBehavior.spin_cb (self)
Override StateMachine.spin() so we can call spin() on subbehaviors.
Spin Composite Behavior,execute all behaviors inside composite behavior
All behavior inside Composite behavior instance is executed using threading. If subbehavior inside Composite behavior is Composite subbehavior, then spin_cb() is used else spin().
See also
Behavior::spin()
Definition at line 94 of file composite_behavior.py.
References composite_behavior.CompositeBehavior._subbehavior_info, composite_behavior.CompositeBehavior.handle_subbehavior_exception(), print(), and fsm.StateMachine.spin().
Referenced by composite_behavior.CompositeBehavior.all_subbehaviors_completed().
     def spin_cb(self):
         self.spin()
         states = []
         def function_process(name):
             save_stdout = sys.stdout
             sys.stdout = open('./debug/'+ str(name) + '.txt','w')
             try:
                 print("here____")
                 print 'Starting behaviour: {} at {}'.format(name,time.time())
                 info = self._subbehavior_info[name]
                 bhvr = info['behavior']
                 print("Behavior",bhvr)
                 # multi-robot behaviors always get spun
                 # only spin single robot behaviors when they have a robot
                 should_spin = True
                 # try executing the subbehavior
                 # if it throws an exception, catch it and pass it to the exception handler, which subclasses can override
                 if should_spin:
                     try:
                         # print("Behavior name",bhvr)
                         if issubclass(bhvr.__class__, CompositeBehavior):
                             bhvr.spin_cb()
                         else:
                             bhvr.spin()
                     except:
                         exc = sys.exc_info()[0]
                         self.handle_subbehavior_exception(name, exc)
             finally:
                 sys.stdout = save_stdout
         print 'Starting {} at {}'.format(n_threads, time.time())
         n_threads = len(self._subbehavior_info.keys())
         pool = ThreadPool(n_threads)
         pool.map(function_process, list(self._subbehavior_info.keys()))
         pool.close()
         pool.join()
         print 'Completed at {}'.format(time.time())
def composite_behavior.CompositeBehavior.subbehavior_with_name (self, name)
Definition at line 59 of file composite_behavior.py.
References composite_behavior.CompositeBehavior._subbehavior_info, and composite_behavior.CompositeBehavior.subbehaviors_by_name().
Referenced by tactics.Triangle_Pass.CoordinatedPass.__init__(), composite_behavior.CompositeBehavior.assign_roles(), tactics.CoPass.CoordinatedPass.execute_kicking(), tactics.Triangle_Pass.CoordinatedPass.execute_preparing(), tactics.Triangle_Pass.CoordinatedPass.execute_running(), tactics.Triangle_Pass.CoordinatedPass.get_robots(), composite_behavior.CompositeBehavior.has_subbehaviors(), tactics.Triangle_Pass.CoordinatedPass.on_enter_kicking(), tactics.Triangle_Pass.CoordinatedPass.on_enter_receiving(), and tactics.CoPass.CoordinatedPass.on_enter_receiving().
     def subbehavior_with_name(self, name):
         return self._subbehavior_info[name]['behavior']
def composite_behavior.CompositeBehavior.subbehaviors_by_name (self)
Definition at line 62 of file composite_behavior.py.
References composite_behavior.CompositeBehavior._subbehavior_info, and composite_behavior.CompositeBehavior.remove_all_subbehaviors().
Referenced by composite_behavior.CompositeBehavior.subbehavior_with_name().
     def subbehaviors_by_name(self) :
         by_name = {}
         for name in self._subbehavior_info:
             by_name[name] = self._subbehavior_info[name]['behavior']
         return by_name
Field Documentation
composite_behavior.CompositeBehavior._subbehavior_info private
Definition at line 15 of file composite_behavior.py.
Referenced by composite_behavior.CompositeBehavior.__str__(), composite_behavior.CompositeBehavior.add_subbehavior(), composite_behavior.CompositeBehavior.all_subbehaviors(), composite_behavior.CompositeBehavior.has_subbehavior_with_name(), composite_behavior.CompositeBehavior.has_subbehaviors(), composite_behavior.CompositeBehavior.remove_subbehavior(), composite_behavior.CompositeBehavior.spin_cb(), composite_behavior.CompositeBehavior.subbehavior_with_name(), and composite_behavior.CompositeBehavior.subbehaviors_by_name().
The documentation for this class was generated from the following file:
composite_behavior.py