Documentation: MainWindow Class Reference
MainWindow Class Reference
The ssl-vision main window.
#include <mainwindow.h>
Public Slots
void reconnectUdp ()
void sendPacket ()
void sendBtnClicked ()
void resetBtnClicked ()
void disconnectUdp ()
void update ()
void updateRobotLabel ()
void showHideConfig (bool v)
void showHideSimulator (bool v)
void changeCurrentRobot ()
void changeCurrentTeam ()
void changeBallMass ()
void changeBallGroundSurface ()
void changeBallDamping ()
void changeGravity ()
void changeTimer ()
void restartSimulator ()
void ballMenuTriggered (QAction *act)
void toggleFullScreen (bool)
void setCurrentRobotPosition ()
void takeSnapshot ()
void takeSnapshotToClipboard ()
void customFPS (int fps)
void showAbout ()
void reconnectCommandSocket ()
void reconnectYellowStatusSocket ()
void reconnectBlueStatusSocket ()
void reconnectVisionSocket ()
void recvActions ()
void slotSaveSettings ()
Public Member Functions
MainWindow (QWidget *parent=0)
~MainWindow ()
MainWindow (QWidget *parent=0)
~MainWindow ()
MainWindow (bool start_capture, bool enforce_affinity)
virtual ~MainWindow ()
void init ()
void Quit ()
virtual void closeEvent (QCloseEvent *event)
virtual void timerEvent (QTimerEvent *e)
Data Fields
AffinityManager * affinity
VarList * root
VarTreeView * tree_view
QTabWidget * left_tab
QTabWidget * right_tab
QSplitter * splitter
QTabWidget * cam_tabs
VarList * settings
vector< VarType * > world
VarTreeModel * tmodel
vector< RealTimeDisplayWidget * > display_widgets
vector< QSplitter * > stack_widgets
RenderOptions * opts
VarTrigger * save_settings_trigger
MultiVisionStack * multi_stack
Private Member Functions
int getInterval ()
Private Attributes
bool sending
bool reseting
QUdpSocket udpsocket
QHostAddress _addr
quint16 _port
QLineEdit * edtIp
QLineEdit * edtPort
QLineEdit * edtId
QLineEdit * edtVx
QLineEdit * edtVy
QLineEdit * edtW
QLineEdit * edtV1
QLineEdit * edtV2
QLineEdit * edtV3
QLineEdit * edtV4
QLineEdit * edtKick
QLineEdit * edtChip
QLabel * lblIp
QLabel * lblPort
QLabel * lblId
QComboBox * cmbTeam
QLabel * lblVx
QLabel * lblVy
QLabel * lblW
QLabel * lblV1
QLabel * lblV2
QLabel * lblV3
QLabel * lblV4
QLabel * lblKick
QLabel * lblChip
QTextEdit * txtInfo
QCheckBox * chkVel
QCheckBox * chkSpin
QPushButton * btnSend
QPushButton * btnReset
QPushButton * btnConnect
QTimer * timer
QWorkspace * workspace
GLWidget * glwidget
ConfigWidget * configwidget
ConfigDockWidget * dockconfig
RobotWidget * robotwidget
CStatusPrinter * printer
CStatusWidget * statusWidget
QAction * showsimulator
QAction * showconfig
QAction * fullScreenAct
QLabel * fpslabel
QLabel * cursorlabel
QLabel * selectinglabel
QLabel * vanishlabel
QLabel * noiselabel
QString current_dir
QGraphicsScene * scene
GLWidgetGraphicsView * view
QSize lastSize
RoboCupSSLServer * visionServer
QUdpSocket * commandSocket
QUdpSocket * blueStatusSocket
QUdpSocket * yellowStatusSocket
Detailed Description
The ssl-vision main window.
Author
Stefan Zickler, (C) 2008
Definition at line 19 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0)
Definition at line 6 of file mainwindow.cpp.
References btnConnect, btnReset, btnSend, chkSpin, chkVel, cmbTeam, disconnectUdp(), edtChip, edtId, edtIp, edtKick, edtPort, edtV1, edtV2, edtV3, edtV4, edtVx, edtVy, edtW, lblChip, lblId, lblIp, lblKick, lblPort, lblV1, lblV2, lblV3, lblV4, lblVx, lblVy, lblW, reconnectUdp(), resetBtnClicked(), reseting, sendBtnClicked(), sending, sendPacket(), timer, and txtInfo.
Referenced by customFPS().
     : QDialog(parent),
     udpsocket(this)
 {
     QGridLayout* layout = new QGridLayout(this);
     edtIp = new QLineEdit("127.0.0.1", this);
     edtPort = new QLineEdit("20011", this);
     edtId = new QLineEdit("0", this);
     edtVx = new QLineEdit("0", this);
     edtVy = new QLineEdit("0", this);
     edtW  = new QLineEdit("0", this);
     edtV1 = new QLineEdit("0", this);
     edtV2 = new QLineEdit("0", this);
     edtV3 = new QLineEdit("0", this);
     edtV4 = new QLineEdit("0", this);
     edtChip = new QLineEdit("0", this);
     edtKick = new QLineEdit("0", this);
     this->setWindowTitle(QString("grSim Sample Client - v 1.0"));
     lblIp = new QLabel("Simulator Address", this);
     lblPort = new QLabel("Simulator Port", this);
     lblId = new QLabel("Id", this);
     lblVx = new QLabel("Velocity X (m/s)", this);
     lblVy = new QLabel("Velocity Y (m/s)", this);
     lblW  = new QLabel("Velocity W (rad/s)", this);
     lblV1 = new QLabel("Wheel1 (rad/s)", this);
     lblV2 = new QLabel("Wheel2 (rad/s)", this);
     lblV3 = new QLabel("Wheel3 (rad/s)", this);
     lblV4 = new QLabel("Wheel4 (rad/s)", this);
     cmbTeam = new QComboBox(this);
     cmbTeam->addItem("Yellow");
     cmbTeam->addItem("Blue");
     lblChip = new QLabel("Chip (m/s)", this);
     lblKick = new QLabel("Kick (m/s)", this);
     txtInfo = new QTextEdit(this);
     chkVel = new QCheckBox("Send Velocity? (or wheels)", this);
     chkSpin = new QCheckBox("Spin", this);
     btnSend = new QPushButton("Send", this);
     btnReset = new QPushButton("Reset", this);
     btnConnect = new QPushButton("Connect", this);
     txtInfo->setReadOnly(true);
     txtInfo->setHtml("This program is part of <b>grSim RoboCup SSL Simulator</b> package.<br />For more information please refer to <a href=\"http://eew.aut.ac.ir/~parsian/grsim/\">http://eew.aut.ac.ir/~parsian/grsim</a><br /><font color=\"gray\">This program is free software under the terms of GNU General Public License Version 3.</font>");
     txtInfo->setFixedHeight(70);
     layout->addWidget(lblIp, 1, 1, 1, 1);layout->addWidget(edtIp, 1, 2, 1, 1);
     layout->addWidget(lblPort, 1, 3, 1, 1);layout->addWidget(edtPort, 1, 4, 1, 1);
     layout->addWidget(lblId, 2, 1, 1, 1);layout->addWidget(edtId, 2, 2, 1, 1);layout->addWidget(cmbTeam, 2, 3, 1, 2);
     layout->addWidget(lblVx, 3, 1, 1, 1);layout->addWidget(edtVx, 3, 2, 1, 1);
     layout->addWidget(lblVy, 4, 1, 1, 1);layout->addWidget(edtVy, 4, 2, 1, 1);
     layout->addWidget(lblW, 5, 1, 1, 1);layout->addWidget(edtW, 5, 2, 1, 1);
     layout->addWidget(chkVel, 6, 1, 1, 1);layout->addWidget(edtKick, 6, 2, 1, 1);
     layout->addWidget(lblV1, 3, 3, 1, 1);layout->addWidget(edtV1, 3, 4, 1, 1);
     layout->addWidget(lblV2, 4, 3, 1, 1);layout->addWidget(edtV2, 4, 4, 1, 1);
     layout->addWidget(lblV3, 5, 3, 1, 1);layout->addWidget(edtV3, 5, 4, 1, 1);
     layout->addWidget(lblV4, 6, 3, 1, 1);layout->addWidget(edtV4, 6, 4, 1, 1);
     layout->addWidget(lblChip, 7, 1, 1, 1);layout->addWidget(edtChip, 7, 2, 1, 1);
     layout->addWidget(lblKick, 7, 3, 1, 1);layout->addWidget(edtKick, 7, 4, 1, 1);
     layout->addWidget(chkSpin, 8, 1, 1, 4);
     layout->addWidget(btnConnect, 9, 1, 1, 2);layout->addWidget(btnSend, 9, 3, 1, 1);layout->addWidget(btnReset, 9, 4, 1, 1);
     layout->addWidget(txtInfo, 10, 1, 1, 4);
     timer = new QTimer (this);
     timer->setInterval(20);
     connect(edtIp, SIGNAL(textChanged(QString)), this, SLOT(disconnectUdp()));
     connect(edtPort, SIGNAL(textChanged(QString)), this, SLOT(disconnectUdp()));
     connect(timer, SIGNAL(timeout()), this, SLOT(sendPacket()));
     connect(btnConnect, SIGNAL(clicked()), this, SLOT(reconnectUdp()));
     connect(btnSend, SIGNAL(clicked()), this, SLOT(sendBtnClicked()));
     connect(btnReset, SIGNAL(clicked()), this, SLOT(resetBtnClicked()));
     btnSend->setDisabled(true);
     chkVel->setChecked(true);
     sending = false;
     reseting = false;
 }
MainWindow::~MainWindow ()
Definition at line 80 of file mainwindow.cpp.
Referenced by closeEvent(), and customFPS().
 {
 }
MainWindow::MainWindow (QWidget * parent = 0)
MainWindow::~MainWindow ()
MainWindow::MainWindow (bool start_capture, bool enforce_affinity)
Definition at line 24 of file mainwindow.cpp.
References VarTypes::VarList::addChild(), affinity, cam_tabs, AffinityManager::demandCore(), display_widgets, VarTypes::VarTreeView::expandAndFocus(), VarTypes::VarTreeView::fitColumns(), VisionPlugin::getControlWidget(), MultiVisionStack::getName(), VisionPlugin::getName(), VisionStack::getSettings(), MultiVisionStack::getSettings(), VisionPlugin::getSettings(), MultiVisionStack::getSettingsFileName(), VisionPlugin::getVisualizationWidget(), velocity.pid_::i, CaptureThread::init(), VisionPlugin::isSharedAmongStacks(), left_tab, multi_stack, opts, right_tab, root, save_settings_trigger, VarTypes::VarTreeView::setModel(), RealTimeDisplayWidget::setRingBuffer(), VarTypes::VarTreeModel::setRootItems(), settings, GLWidget::setVisionStack(), slotSaveSettings(), splitter, VisionStack::stack, stack_widgets, MultiVisionStack::start(), MultiVisionStack::threads, tmodel, tree_view, and world.
 {
   affinity=0;
   if (enforce_affinity) affinity=new AffinityManager();
   //opt=new GetOpt();
   settings=0;
   setupUi((QMainWindow *)this);
   tree_view=new VarTreeView();
   tmodel=new VarTreeModel();
   splitter = new QSplitter(Qt::Horizontal,this);
   cam_tabs = new QTabWidget();
   root=new VarList("Vision System");
   save_settings_trigger = new VarTrigger("Save Settings", "Save Settings!");
   root->addChild(save_settings_trigger);
   opts=new RenderOptions();
   right_tab=0;
   QString stack_id="";
   //opt->addArgument("stack",&stack_id);
   //opt->parse();
   //load RoboCup SSL stack by default:
   multi_stack=new MultiStackRoboCupSSL(opts, 4);
   VarExternal * stackvar;
   root->addChild(stackvar= new VarExternal((multi_stack->getSettingsFileName() + ".xml").c_str(),multi_stack->getName()));
   stackvar->addChild(multi_stack->getSettings());
   //create tabs, GL visualizations and tool-panes for each capture thread in the multi-stack:
   for (unsigned int i=0;i<multi_stack->threads.size();i++) {
     QSplitter * splitter2 = new QSplitter(Qt::Vertical);
     VisionStack * s = multi_stack->threads[i]->getStack();
     if (affinity!=0) multi_stack->threads[i]->setAffinityManager(affinity);
     GLWidget * gl=new GLWidget(0,false);
     gl->setRingBuffer(multi_stack->threads[i]->getFrameBuffer());
     gl->setVisionStack(s);
     QString label = "Camera " + QString::number(i);
     VarList * threadvar = new VarList(label.toStdString());
     threadvar->addChild(s->getSettings());
     //iterate through plugin variables
     QSplitter * stack_widget = new QSplitter(Qt::Horizontal);
     stack_widgets.push_back(stack_widget);
     QSplitter * stack_vis_splitter = new QSplitter(Qt::Vertical);
     stack_widget->addWidget(stack_vis_splitter);
     QTabWidget * stack_control_tab = new QTabWidget();
     stack_control_tab->setTabPosition(QTabWidget::East);
     stack_widget->addWidget(stack_control_tab);
     VideoWidget * w=new VideoWidget(label,gl);
     display_widgets.push_back(gl);
     threadvar->addChild(multi_stack->threads[i]->getSettings());
     stack_vis_splitter->addWidget(w);
     //iterate through all plugins
     unsigned int n=s->stack.size();
     for (unsigned int j=0;j<n;j++) {
       VisionPlugin * p=s->stack[j];
       if (p->isSharedAmongStacks()) {
         if (i==0) {
           //this is a shared global plugin...
           //add it to global pane
           if (p->getSettings()!=0) stackvar->addChild(p->getSettings());
           QWidget * tmp_control = p->getControlWidget();
           if (tmp_control!=0) {
             if (right_tab==0) {
               right_tab=new QTabWidget();
               right_tab->setTabPosition(QTabWidget::East);
             }
             right_tab->addTab(tmp_control,QString::fromStdString(p->getName()));
           }
           QWidget * tmp_vis = p->getVisualizationWidget();
           if (tmp_vis!=0) splitter2->addWidget(tmp_vis);
         }
       } else {
         if (p->getSettings()!=0) threadvar->addChild(p->getSettings());
         //this is a local plugin relating only to a single thread
         //add it to the context.
         QWidget * tmp_control = p->getControlWidget();
         if (tmp_control!=0) stack_control_tab->addTab(tmp_control,QString::fromStdString(p->getName()));
         QWidget * tmp_vis = p->getVisualizationWidget();
         if (tmp_vis!=0) stack_vis_splitter->addWidget(tmp_vis);
       }
     }
     stackvar->addChild(threadvar);
     splitter2->addWidget(stack_widget);
     splitter2->addWidget(new QWidget());
     cam_tabs->addTab(splitter2, label);
   }
   if (affinity!=0) affinity->demandCore(multi_stack->threads.size());
   // Set position and size of main window:
   QSettings window_settings("RoboCup", "ssl-vision");
   window_settings.beginGroup("MainWindow");
   QPoint pos = window_settings.value("pos", QPoint(100, 100)).toPoint();
   QSize size = window_settings.value("size", QSize(800, 600)).toSize();
   window_settings.endGroup();
   resize(size);
   move(pos);
   //FINISHED STRUCTURAL TREE
   //NOW LOAD DATA:
   world.push_back(root);
   world=VarXML::read( world,"settings.xml");
   //update network output settings from xml file
   ((MultiStackRoboCupSSL*)multi_stack)->RefreshNetworkOutput();
   ((MultiStackRoboCupSSL*)multi_stack)->RefreshLegacyNetworkOutput();
   multi_stack->start();
   if (start_capture==true) {
     for (unsigned int i = 0; i < multi_stack->threads.size(); i++) {
       CaptureThread * ct = multi_stack->threads[i];
       ct->init();
     }
   }
   tree_view->setModel(tmodel);
   tmodel->setRootItems(world);
   tree_view->expandAndFocus(stackvar);
   tree_view->fitColumns();
   left_tab=new QTabWidget();
   left_tab->setTabPosition(QTabWidget::West);
   splitter->addWidget(left_tab);
   splitter->addWidget(cam_tabs);
   if (right_tab!=0) splitter->addWidget(right_tab);
   left_tab->addTab(tree_view,"Data-Tree");
   setCentralWidget(splitter); //was splitter
   startTimer(10);
   // connection must be queued as the data tree is locked
   // by a mutex when the signal is triggered
   connect(save_settings_trigger, SIGNAL(signalTriggered()),
           this, SLOT(slotSaveSettings()), Qt::QueuedConnection);
 }
virtual MainWindow::~MainWindow () virtual
Member Function Documentation
void MainWindow::ballMenuTriggered (QAction * act) slot
Definition at line 391 of file mainwindow.cpp.
References configwidget, ConfigWidget::Field_Length(), ConfigWidget::Field_Penalty_Point(), ConfigWidget::Field_Width(), glwidget, and GLWidget::putBall().
Referenced by customFPS().
 {
     dReal l = configwidget->Field_Length()/2.0;
     dReal w = configwidget->Field_Width()/2.0;
     dReal p = l - configwidget->Field_Penalty_Point();
     if (act->text()==tr("Put on Center")) glwidget->putBall(0,0);
     else if (act->text()==tr("Put on Corner 1")) glwidget->putBall(-l,-w);
     else if (act->text()==tr("Put on Corner 2")) glwidget->putBall(-l, w);
     else if (act->text()==tr("Put on Corner 3")) glwidget->putBall( l,-w);
     else if (act->text()==tr("Put on Corner 4")) glwidget->putBall( l, w);
     else if (act->text()==tr("Put on Penalty 1")) glwidget->putBall( p, 0);
     else if (act->text()==tr("Put on Penalty 2")) glwidget->putBall(-p, 0);
 }
void MainWindow::changeBallDamping () slot
Definition at line 370 of file mainwindow.cpp.
References SSLWorld::ball, ConfigWidget::BallAngularDamp(), ConfigWidget::BallLinearDamp(), PObject::body, configwidget, glwidget, and GLWidget::ssl.
Referenced by customFPS().
 {
     dBodySetLinearDampingThreshold(glwidget->ssl->ball->body,0.001);
     dBodySetLinearDamping(glwidget->ssl->ball->body,configwidget->BallLinearDamp());
     dBodySetAngularDampingThreshold(glwidget->ssl->ball->body,0.001);
     dBodySetAngularDamping(glwidget->ssl->ball->body,configwidget->BallAngularDamp());
 }
void MainWindow::changeBallGroundSurface () slot
Definition at line 359 of file mainwindow.cpp.
References SSLWorld::ball, ConfigWidget::BallBounce(), ConfigWidget::BallBounceVel(), ConfigWidget::BallFriction(), ConfigWidget::BallSlip(), configwidget, PWorld::findSurface(), fric(), glwidget, SSLWorld::ground, SSLWorld::p, GLWidget::ssl, and PSurface::surface.
Referenced by customFPS().
 {
     PSurface* ballwithwall = glwidget->ssl->p->findSurface(glwidget->ssl->ball,glwidget->ssl->ground);
     ballwithwall->surface.mode = dContactBounce | dContactApprox1 | dContactSlip1 | dContactSlip2;
     ballwithwall->surface.mu = fric(configwidget->BallFriction());
     ballwithwall->surface.bounce = configwidget->BallBounce();
     ballwithwall->surface.bounce_vel = configwidget->BallBounceVel();
     ballwithwall->surface.slip1 = configwidget->BallSlip();
     ballwithwall->surface.slip2 = configwidget->BallSlip();
 }
void MainWindow::changeBallMass () slot
Definition at line 353 of file mainwindow.cpp.
References SSLWorld::ball, ConfigWidget::BallMass(), configwidget, glwidget, PBall::setMass(), and GLWidget::ssl.
Referenced by customFPS().
 {
     glwidget->ssl->ball->setMass(configwidget->BallMass());
 }
void MainWindow::changeCurrentRobot () slot
Definition at line 268 of file mainwindow.cpp.
References RobotWidget::changeRobotOnOff(), GLWidget::Current_robot, GLWidget::Current_team, glwidget, RobotWidget::id, Robot::img, Robot::on, RobotWidget::robotCombo, robotIndex(), SSLWorld::robots, robotwidget, RobotWidget::setPicture(), and GLWidget::ssl.
Referenced by customFPS().
 {
     glwidget->Current_robot=robotwidget->robotCombo->currentIndex();
     robotwidget->setPicture(glwidget->ssl->robots[robotIndex(glwidget->Current_robot,glwidget->Current_team)]->img);
     robotwidget->id = robotIndex(glwidget->Current_robot, glwidget->Current_team);
     robotwidget->changeRobotOnOff(robotwidget->id, glwidget->ssl->robots[robotwidget->id]->on);
 }
void MainWindow::changeCurrentTeam () slot
Definition at line 276 of file mainwindow.cpp.
References RobotWidget::changeRobotOnOff(), GLWidget::Current_robot, GLWidget::Current_team, glwidget, RobotWidget::id, Robot::img, Robot::on, robotIndex(), SSLWorld::robots, robotwidget, RobotWidget::setPicture(), GLWidget::ssl, and RobotWidget::teamCombo.
Referenced by customFPS().
 {
     glwidget->Current_team=robotwidget->teamCombo->currentIndex();
     robotwidget->setPicture(glwidget->ssl->robots[robotIndex(glwidget->Current_robot,glwidget->Current_team)]->img);
     robotwidget->id = robotIndex(glwidget->Current_robot, glwidget->Current_team);
     robotwidget->changeRobotOnOff(robotwidget->id, glwidget->ssl->robots[robotwidget->id]->on);
 }
void MainWindow::changeGravity () slot
Definition at line 284 of file mainwindow.cpp.
References configwidget, glwidget, ConfigWidget::Gravity(), SSLWorld::p, GLWidget::ssl, and PWorld::world.
Referenced by customFPS().
 {
     dWorldSetGravity (glwidget->ssl->p->world,0,0,-configwidget->Gravity());
 }
void MainWindow::changeTimer () slot
Definition at line 289 of file mainwindow.cpp.
References getInterval(), and timer.
Referenced by customFPS().
 {
     timer->setInterval(getInterval());
 }
void MainWindow::closeEvent (QCloseEvent * event) virtual
Definition at line 211 of file mainwindow.cpp.
References affinity, multi_stack, MultiVisionStack::stop(), world, and ~MainWindow().
Referenced by Quit().
{
   (void)event;
   //Save window configuration before deleting:
   {
     QSettings window_settings("RoboCup", "ssl-vision");
     window_settings.beginGroup("MainWindow");
     window_settings.setValue("pos", pos());
     window_settings.setValue("size", size());
     window_settings.endGroup();
   }
 }
void MainWindow::customFPS (int fps) slot
Definition at line 48 of file mainwindow.cpp.
References ballMenuTriggered(), GLWidget::blueRobotsMenu, SSLWorld::blueStatusSocket, blueStatusSocket, GLWidget::cameraMenu, changeBallDamping(), changeBallGroundSurface(), changeBallMass(), changeCurrentRobot(), changeCurrentTeam(), changeGravity(), changeTimer(), SSLWorld::commandSocket, commandSocket, configwidget, current_dir, GLWidget::Current_robot, GLWidget::Current_team, cursorlabel, dockconfig, fpslabel, fullScreenAct, getInterval(), RobotWidget::getPoseWidget, glwidget, RobotWidget::id, Robot::img, initLogger(), k, RobotWidget::locateBtn, logStatus(), MainWindow(), noiselabel, GetPositionWidget::okBtn, RobotWidget::onOffBtn, printer, reconnectBlueStatusSocket(), reconnectCommandSocket(), reconnectVisionSocket(), reconnectYellowStatusSocket(), RobotWidget::resetBtn, restartSimulator(), RobotWidget::robotCombo, robotIndex(), SSLWorld::robots, robotwidget, scene, selectinglabel, setCurrentRobotPosition(), RobotWidget::setPicture(), showAbout(), showconfig, showHideConfig(), showHideSimulator(), showsimulator, GLWidget::ssl, statusWidget, takeSnapshot(), takeSnapshotToClipboard(), RobotWidget::teamCombo, timer, toggleFullScreen(), update(), updateRobotLabel(), ConfigWidget::v_BallAngularDamp, ConfigWidget::v_BallBounce, ConfigWidget::v_BallBounceVel, ConfigWidget::v_BallFriction, ConfigWidget::v_BallLinearDamp, ConfigWidget::v_BallMass, ConfigWidget::v_BallRadius, ConfigWidget::v_BallSlip, ConfigWidget::v_BlueStatusSendPort, ConfigWidget::v_BlueTeam, ConfigWidget::v_CommandListenPort, ConfigWidget::v_DesiredFPS, ConfigWidget::v_Field_Length, ConfigWidget::v_Field_Margin, ConfigWidget::v_Field_Penalty_Line, ConfigWidget::v_Field_Penalty_Point, ConfigWidget::v_Field_Penalty_Rad, ConfigWidget::v_Field_Rad, ConfigWidget::v_Field_Width, ConfigWidget::v_Gravity, ConfigWidget::v_VisionMulticastAddr, ConfigWidget::v_VisionMulticastPort, ConfigWidget::v_YellowStatusSendPort, ConfigWidget::v_YellowTeam, vanishlabel, SSLWorld::visionServer, visionServer, workspace, GLWidget::yellowRobotsMenu, SSLWorld::yellowStatusSocket, yellowStatusSocket, and ~MainWindow().
 {
     int k = ceil((1000.0f / fps));
     timer->setInterval(k);
     logStatus(QString("new FPS set by user: %1").arg(fps),"red");
 }
void MainWindow::disconnectUdp () slot
Definition at line 85 of file mainwindow.cpp.
References btnSend, sending, and udpsocket.
Referenced by MainWindow().
 {
     udpsocket.close();
     sending = false;
     btnSend->setText("Send");
     btnSend->setDisabled(true);
 }
int MainWindow::getInterval () private
Definition at line 43 of file mainwindow.cpp.
References configwidget, and ConfigWidget::DesiredFPS().
Referenced by changeTimer(), and customFPS().
 {
     return ceil((1000.0f / configwidget->DesiredFPS()));
 }
void MainWindow::init ()
Definition at line 207 of file mainwindow.cpp.
Referenced by main().
                       {
 }
void MainWindow::Quit () inline
Definition at line 74 of file mainwindow.h.
References closeEvent(), slotSaveSettings(), and timerEvent().
Referenced by HandleStop().
 { emit close(); }
void MainWindow::reconnectBlueStatusSocket () slot
Definition at line 474 of file mainwindow.cpp.
References ConfigWidget::BlueStatusSendPort(), blueStatusSocket, configwidget, and logStatus().
Referenced by customFPS().
 {
     if (blueStatusSocket!=NULL)
     {
         delete blueStatusSocket;
     }
     blueStatusSocket = new QUdpSocket(this);
     if (blueStatusSocket->bind(QHostAddress::Any,configwidget->BlueStatusSendPort()))
         logStatus(QString("Status send port binded for Blue Team on: %1").arg(configwidget->BlueStatusSendPort()),QColor("green"));
 }
void MainWindow::reconnectCommandSocket () slot
Definition at line 496 of file mainwindow.cpp.
References ConfigWidget::CommandListenPort(), commandSocket, configwidget, logStatus(), and recvActions().
Referenced by customFPS().
 {
     if (commandSocket!=NULL)
     {
         QObject::disconnect(commandSocket,SIGNAL(readyRead()),this,SLOT(recvActions()));
         delete commandSocket;
     }
     commandSocket = new QUdpSocket(this);
     if (commandSocket->bind(QHostAddress::Any,configwidget->CommandListenPort()))
         logStatus(QString("Command listen port binded on: %1").arg(configwidget->CommandListenPort()),QColor("green"));
     QObject::connect(commandSocket,SIGNAL(readyRead()),this,SLOT(recvActions()));
 }
void MainWindow::reconnectUdp () slot
Definition at line 124 of file mainwindow.cpp.
References _addr, _port, btnSend, edtIp, and edtPort.
Referenced by MainWindow().
 {
     _addr = edtIp->text();
     _port = edtPort->text().toUShort();
     btnSend->setDisabled(false);
 }
void MainWindow::reconnectVisionSocket () slot
Definition at line 509 of file mainwindow.cpp.
References RoboCupSSLServer::change_address(), RoboCupSSLServer::change_port(), configwidget, logStatus(), ConfigWidget::VisionMulticastAddr(), ConfigWidget::VisionMulticastPort(), and visionServer.
Referenced by customFPS().
 {
     if (visionServer == NULL) {
         visionServer = new RoboCupSSLServer(this);
     }
     visionServer->change_address(configwidget->VisionMulticastAddr());
     visionServer->change_port(configwidget->VisionMulticastPort());
     logStatus(QString("Vision server connected on: %1").arg(configwidget->VisionMulticastPort()),QColor("green"));
 }
void MainWindow::reconnectYellowStatusSocket () slot
Definition at line 485 of file mainwindow.cpp.
References configwidget, logStatus(), ConfigWidget::YellowStatusSendPort(), and yellowStatusSocket.
Referenced by customFPS().
 {
     if (yellowStatusSocket!=NULL)
     {
         delete yellowStatusSocket;
     }
     yellowStatusSocket = new QUdpSocket(this);
     if (yellowStatusSocket->bind(QHostAddress::Any,configwidget->YellowStatusSendPort()))
         logStatus(QString("Status send port binded for Yellow Team on: %1").arg(configwidget->YellowStatusSendPort()),QColor("green"));
 }
void MainWindow::recvActions () slot
Definition at line 519 of file mainwindow.cpp.
References glwidget, SSLWorld::recvActions(), and GLWidget::ssl.
Referenced by reconnectCommandSocket().
 {
     glwidget->ssl->recvActions();
 }
void MainWindow::resetBtnClicked () slot
Definition at line 107 of file mainwindow.cpp.
References chkSpin, chkVel, edtChip, edtKick, edtV1, edtV2, edtV3, edtV4, edtVx, edtVy, edtW, and reseting.
Referenced by MainWindow().
 {
     reseting = true;
     edtVx->setText("0");
     edtVy->setText("0");
     edtW->setText("0");
     edtV1->setText("0");
     edtV2->setText("0");
     edtV3->setText("0");
     edtV4->setText("0");
     edtChip->setText("0");
     edtKick->setText("0");
     chkVel->setChecked(true);
     chkSpin->setChecked(false);
 }
void MainWindow::restartSimulator () slot
Definition at line 378 of file mainwindow.cpp.
References SSLWorld::blueStatusSocket, blueStatusSocket, GLWidget::cfg, SSLWorld::commandSocket, commandSocket, GLWidget::forms, SSLWorld::glinit(), glwidget, GLWidget::ssl, SSLWorld::visionServer, visionServer, SSLWorld::yellowStatusSocket, and yellowStatusSocket.
Referenced by customFPS().
 {
     delete glwidget->ssl;
     glwidget->ssl = new SSLWorld(glwidget,glwidget->cfg,glwidget->forms[2],glwidget->forms[2]);
     glwidget->ssl->glinit();
     glwidget->ssl->visionServer = visionServer;
     glwidget->ssl->commandSocket = commandSocket;
     glwidget->ssl->blueStatusSocket = blueStatusSocket;
     glwidget->ssl->yellowStatusSocket = yellowStatusSocket;
 }
void MainWindow::sendBtnClicked () slot
Definition at line 93 of file mainwindow.cpp.
References btnSend, sending, and timer.
Referenced by MainWindow(), and sendPacket().
 {
     sending = !sending;
     if (!sending)
     {
         timer->stop();
         btnSend->setText("Send");
     }
     else {
         timer->start();
         btnSend->setText("Pause");
     }
 }
void MainWindow::sendPacket () slot
Definition at line 131 of file mainwindow.cpp.
References _addr, _port, chkSpin, chkVel, cmbTeam, edtChip, edtId, edtKick, edtV1, edtV2, edtV3, edtV4, edtVx, edtVy, edtW, reseting, sendBtnClicked(), and udpsocket.
Referenced by MainWindow().
 {
     if (reseting)
     {
         sendBtnClicked();
         reseting = false;
     }
     grSim_Packet packet;
     bool yellow = false;
     if (cmbTeam->currentText()=="Yellow") yellow = true;
     packet.mutable_commands()->set_isteamyellow(yellow);
     packet.mutable_commands()->set_timestamp(0.0);
     grSim_Robot_Command* command = packet.mutable_commands()->add_robot_commands();
     command->set_id(edtId->text().toInt());
     command->set_wheelsspeed(!chkVel->isChecked());
     command->set_wheel1(edtV1->text().toDouble());
     command->set_wheel2(edtV2->text().toDouble());
     command->set_wheel3(edtV3->text().toDouble());
     command->set_wheel4(edtV4->text().toDouble());
     command->set_veltangent(edtVx->text().toDouble());
     command->set_velnormal(edtVy->text().toDouble());
     command->set_velangular(edtW->text().toDouble());
     command->set_kickspeedx(edtKick->text().toDouble());
     command->set_kickspeedz(edtChip->text().toDouble());
     command->set_spinner(chkSpin->isChecked());
     QByteArray dgram;
     dgram.resize(packet.ByteSize());
     packet.SerializeToArray(dgram.data(), dgram.size());
     udpsocket.writeDatagram(dgram, _addr, _port);
 }
void MainWindow::setCurrentRobotPosition () slot
Definition at line 437 of file mainwindow.cpp.
References GetPositionWidget::a, GLWidget::Current_robot, GLWidget::Current_team, RobotWidget::getPoseWidget, glwidget, velocity.pid_::i, logStatus(), robotIndex(), SSLWorld::robots, robotwidget, Robot::setDir(), Robot::setXY(), GLWidget::ssl, role._GoToPoint::x, GetPositionWidget::x, role._GoToPoint::y, and GetPositionWidget::y.
Referenced by customFPS().
 {
     int i = robotIndex(glwidget->Current_robot,glwidget->Current_team);
     bool ok1=false,ok2=false,ok3=false;
     dReal x = robotwidget->getPoseWidget->x->text().toFloat(&ok1);
     dReal y = robotwidget->getPoseWidget->y->text().toFloat(&ok2);
     dReal a = robotwidget->getPoseWidget->a->text().toFloat(&ok3);
     if (!ok1) {logStatus("Invalid dReal for x",QColor("red"));return;}
     if (!ok2) {logStatus("Invalid dReal for y",QColor("red"));return;}
     if (!ok3) {logStatus("Invalid dReal for angle",QColor("red"));return;}
     glwidget->ssl->robots[i]->setXY(x,y);
     glwidget->ssl->robots[i]->setDir(a);
     robotwidget->getPoseWidget->close();
 }
void MainWindow::showAbout () slot
Definition at line 465 of file mainwindow.cpp.
Referenced by customFPS().
 {
     QString title = QString("grSim v0.9 - Build r1240");
     QString text = QString("grSim - RoboCup Small Size Soccer Robots Simulator\n\n(C) 2011 - Parsian Robotic Center\nhttp://eew.aut.ac.ir/~parsian/grsim\n\ngrSim is free software released under the terms of GNU GPL v3");
     QMessageBox::about(this, title, text);
 }
void MainWindow::showHideConfig (bool v) slot
Definition at line 256 of file mainwindow.cpp.
References dockconfig, and showconfig.
Referenced by customFPS().
 {
     if (v) {dockconfig->show();showconfig->setChecked(true);}
     else {dockconfig->hide();showconfig->setChecked(false);}
 }
void MainWindow::showHideSimulator (bool v) slot
Definition at line 262 of file mainwindow.cpp.
References glwidget, and showsimulator.
Referenced by customFPS().
 {
     if (v) {glwidget->show();showsimulator->setChecked(true);}
     else {glwidget->hide();showsimulator->setChecked(false);}
 }
void MainWindow::slotSaveSettings () slot
Definition at line 202 of file mainwindow.cpp.
References world.
Referenced by MainWindow(), and Quit().
 {
     VarXML::write(world,"settings.xml");
 }
void MainWindow::takeSnapshot () slot
Definition at line 452 of file mainwindow.cpp.
References current_dir, and glwidget.
Referenced by customFPS().
 {
     QPixmap p(glwidget->renderPixmap(glwidget->size().width(),glwidget->size().height(),false));
     p.save(QFileDialog::getSaveFileName(this, tr("Save Snapshot"), current_dir, tr("Images (*.png)")),"PNG",100);
 }
void MainWindow::takeSnapshotToClipboard () slot
Definition at line 458 of file mainwindow.cpp.
References glwidget.
Referenced by customFPS().
 {
     QPixmap p(glwidget->renderPixmap(glwidget->size().width(),glwidget->size().height(),false));
     QClipboard* b = QApplication::clipboard();
     b->setPixmap(p);
 }
void MainWindow::timerEvent (QTimerEvent * e) virtual
Definition at line 181 of file mainwindow.cpp.
References display_widgets, RealTimeDisplayWidget::displayLoopEvent(), RealTimeDisplayWidget::getRingBuffer(), velocity.pid_::i, and opts.
Referenced by Quit().
{
   (void)e;
   unsigned int n = display_widgets.size();
   RealTimeDisplayWidget * w;
   bool frame_changed;
   FrameBuffer * fb;
   for (unsigned int i=0;i<n;i++) {
     w = display_widgets[i];
     frame_changed=false;
     fb=w->getRingBuffer();
     if (fb!=0) {
       fb->lockRead();
       int cur=fb->curRead();
       if (fb->nextRead(false) != cur) frame_changed=true;
       fb->unlockRead();
     }
     w->displayLoopEvent(frame_changed,opts);
   }
 }
void MainWindow::toggleFullScreen (bool a) slot
Definition at line 405 of file mainwindow.cpp.
References GLWidget::fullScreen, fullScreenAct, glwidget, lastSize, scene, view, and workspace.
Referenced by customFPS().
 {
     if (a)
     {
         view = new GLWidgetGraphicsView(scene,glwidget);
         lastSize = glwidget->size();
         view->setViewport(glwidget);
         view->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
         view->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
         view->setViewportUpdateMode(QGraphicsView::FullViewportUpdate);
         view->setFrameStyle(0);
         view->showFullScreen();
         view->setFocus();
         glwidget->fullScreen = true;
         fullScreenAct->setChecked(true);
     }
     else {
         view->close();
 #ifdef QT5
         workspace->addSubWindow(glwidget, Qt::CustomizeWindowHint | Qt::WindowTitleHint | Qt::WindowSystemMenuHint | Qt::WindowMinimizeButtonHint | Qt::WindowMaximizeButtonHint);
 #else
         workspace->addWindow(glwidget, Qt::CustomizeWindowHint | Qt::WindowTitleHint | Qt::WindowSystemMenuHint | Qt::WindowMinimizeButtonHint | Qt::WindowMaximizeButtonHint);
 #endif
         glwidget->show();
         glwidget->resize(lastSize);
         glwidget->fullScreen = false;
         fullScreenAct->setChecked(false);
         glwidget->setFocusPolicy(Qt::StrongFocus);
         glwidget->setFocus();
     }
 }
void MainWindow::update () slot
Definition at line 302 of file mainwindow.cpp.
References RobotWidget::acclabel, PObject::body, Robot::chassis, configwidget, GLWidget::Current_robot, GLWidget::Current_team, SSLWorld::cursor_x, SSLWorld::cursor_y, SSLWorld::cursor_z, cursorlabel, ConfigWidget::DeltaTime(), dRealToStr(), fpslabel, SSLWorld::g, GLWidget::getFPS(), glwidget, CGraphics::isGraphicsEnabled(), ConfigWidget::noise(), noiselabel, ROBOT_COUNT, robotIndex(), SSLWorld::robots, robotwidget, SSLWorld::selected, selectinglabel, GLWidget::ssl, statusWidget, GLWidget::step(), CStatusWidget::update(), ConfigWidget::vanishing(), vanishlabel, and RobotWidget::vellabel.
Referenced by customFPS().
 {
     if (glwidget->ssl->g->isGraphicsEnabled()) glwidget->updateGL();
     else glwidget->step();
     int R = robotIndex(glwidget->Current_robot,glwidget->Current_team);
     const dReal* vv = dBodyGetLinearVel(glwidget->ssl->robots[R]->chassis->body);
     static dVector3 lvv;
     dVector3 aa;
     aa[0]=(vv[0]-lvv[0])/configwidget->DeltaTime();
     aa[1]=(vv[1]-lvv[1])/configwidget->DeltaTime();
     aa[2]=(vv[2]-lvv[2])/configwidget->DeltaTime();
     robotwidget->vellabel->setText(QString::number(sqrt(vv[0]*vv[0]+vv[1]*vv[1]+vv[2]*vv[2]),'f',3));
     robotwidget->acclabel->setText(QString::number(sqrt(aa[0]*aa[0]+aa[1]*aa[1]+aa[2]*aa[2]),'f',3));
     lvv[0]=vv[0];
     lvv[1]=vv[1];
     lvv[2]=vv[2];
     QString ss;
     fpslabel->setText(QString("Frame rate: %1 fps").arg(ss.sprintf("%06.2f",glwidget->getFPS())));
     if (glwidget->ssl->selected!=-1)
     {
         selectinglabel->setVisible(true);
         if (glwidget->ssl->selected==-2)
         {
             selectinglabel->setText("Ball");
         }
         else
         {
             int R = glwidget->ssl->selected%ROBOT_COUNT;
             int T = glwidget->ssl->selected/ROBOT_COUNT;
             if (T==0) selectinglabel->setText(QString("%1:Blue").arg(R));
             else selectinglabel->setText(QString("%1:Yellow").arg(R));
         }
     }
     else selectinglabel->setVisible(false);
     vanishlabel->setVisible(configwidget->vanishing());
     noiselabel->setVisible(configwidget->noise());
     cursorlabel->setText(QString("Cursor: [X=%1;Y=%2;Z=%3]").arg(dRealToStr(glwidget->ssl->cursor_x)).arg(dRealToStr(glwidget->ssl->cursor_y)).arg(dRealToStr(glwidget->ssl->cursor_z)));
     statusWidget->update();
 }
void MainWindow::updateRobotLabel () slot
Definition at line 344 of file mainwindow.cpp.
References RobotWidget::changeRobotOnOff(), GLWidget::Current_robot, GLWidget::Current_team, glwidget, RobotWidget::id, Robot::on, RobotWidget::robotCombo, robotIndex(), SSLWorld::robots, robotwidget, GLWidget::ssl, and RobotWidget::teamCombo.
Referenced by customFPS().
 {
     robotwidget->teamCombo->setCurrentIndex(glwidget->Current_team);
     robotwidget->robotCombo->setCurrentIndex(glwidget->Current_robot);
     robotwidget->id = robotIndex(glwidget->Current_robot,glwidget->Current_team);
     robotwidget->changeRobotOnOff(robotwidget->id,glwidget->ssl->robots[robotwidget->id]->on);
 }
Field Documentation
QHostAddress MainWindow::_addr private
Definition at line 35 of file mainwindow.h.
Referenced by reconnectUdp(), and sendPacket().
quint16 MainWindow::_port private
Definition at line 36 of file mainwindow.h.
Referenced by reconnectUdp(), and sendPacket().
AffinityManager* MainWindow::affinity
Definition at line 53 of file mainwindow.h.
Referenced by closeEvent(), and MainWindow().
QUdpSocket* MainWindow::blueStatusSocket private
Definition at line 100 of file mainwindow.h.
Referenced by customFPS(), reconnectBlueStatusSocket(), and restartSimulator().
QPushButton* MainWindow::btnConnect private
Definition at line 54 of file mainwindow.h.
Referenced by MainWindow().
QPushButton* MainWindow::btnReset private
Definition at line 53 of file mainwindow.h.
Referenced by MainWindow().
QPushButton* MainWindow::btnSend private
Definition at line 52 of file mainwindow.h.
Referenced by disconnectUdp(), MainWindow(), reconnectUdp(), and sendBtnClicked().
QTabWidget* MainWindow::cam_tabs
Definition at line 60 of file mainwindow.h.
Referenced by MainWindow().
QCheckBox * MainWindow::chkSpin private
Definition at line 51 of file mainwindow.h.
Referenced by MainWindow(), resetBtnClicked(), and sendPacket().
QCheckBox* MainWindow::chkVel private
Definition at line 51 of file mainwindow.h.
Referenced by MainWindow(), resetBtnClicked(), and sendPacket().
QComboBox* MainWindow::cmbTeam private
Definition at line 46 of file mainwindow.h.
Referenced by MainWindow(), and sendPacket().
QUdpSocket* MainWindow::commandSocket private
Definition at line 99 of file mainwindow.h.
Referenced by customFPS(), reconnectCommandSocket(), and restartSimulator().
ConfigWidget* MainWindow::configwidget private
Definition at line 83 of file mainwindow.h.
Referenced by ballMenuTriggered(), changeBallDamping(), changeBallGroundSurface(), changeBallMass(), changeGravity(), customFPS(), getInterval(), reconnectBlueStatusSocket(), reconnectCommandSocket(), reconnectVisionSocket(), reconnectYellowStatusSocket(), and update().
QString MainWindow::current_dir private
Definition at line 93 of file mainwindow.h.
Referenced by customFPS(), and takeSnapshot().
QLabel * MainWindow::cursorlabel private
Definition at line 92 of file mainwindow.h.
Referenced by customFPS(), and update().
vector<RealTimeDisplayWidget *> MainWindow::display_widgets
Definition at line 64 of file mainwindow.h.
Referenced by MainWindow(), and timerEvent().
ConfigDockWidget* MainWindow::dockconfig private
Definition at line 84 of file mainwindow.h.
Referenced by customFPS(), and showHideConfig().
QLineEdit * MainWindow::edtChip private
Definition at line 42 of file mainwindow.h.
Referenced by MainWindow(), resetBtnClicked(), and sendPacket().
QLineEdit* MainWindow::edtId private
Definition at line 39 of file mainwindow.h.
Referenced by MainWindow(), and sendPacket().
QLineEdit* MainWindow::edtIp private
Definition at line 37 of file mainwindow.h.
Referenced by MainWindow(), and reconnectUdp().
QLineEdit* MainWindow::edtKick private
Definition at line 42 of file mainwindow.h.
Referenced by MainWindow(), resetBtnClicked(), and sendPacket().
QLineEdit* MainWindow::edtPort private
Definition at line 38 of file mainwindow.h.
Referenced by MainWindow(), and reconnectUdp().
QLineEdit* MainWindow::edtV1 private
Definition at line 41 of file mainwindow.h.
Referenced by MainWindow(), resetBtnClicked(), and sendPacket().
QLineEdit * MainWindow::edtV2 private
Definition at line 41 of file mainwindow.h.
Referenced by MainWindow(), resetBtnClicked(), and sendPacket().
QLineEdit * MainWindow::edtV3 private
Definition at line 41 of file mainwindow.h.
Referenced by MainWindow(), resetBtnClicked(), and sendPacket().
QLineEdit * MainWindow::edtV4 private
Definition at line 41 of file mainwindow.h.
Referenced by MainWindow(), resetBtnClicked(), and sendPacket().
QLineEdit* MainWindow::edtVx private
Definition at line 40 of file mainwindow.h.
Referenced by MainWindow(), resetBtnClicked(), and sendPacket().
QLineEdit * MainWindow::edtVy private
Definition at line 40 of file mainwindow.h.
Referenced by MainWindow(), resetBtnClicked(), and sendPacket().
QLineEdit * MainWindow::edtW private
Definition at line 40 of file mainwindow.h.
Referenced by MainWindow(), resetBtnClicked(), and sendPacket().
QLabel* MainWindow::fpslabel private
Definition at line 92 of file mainwindow.h.
Referenced by customFPS(), and update().
QAction* MainWindow::fullScreenAct private
Definition at line 91 of file mainwindow.h.
Referenced by customFPS(), and toggleFullScreen().
GLWidget* MainWindow::glwidget private
Definition at line 82 of file mainwindow.h.
Referenced by ballMenuTriggered(), changeBallDamping(), changeBallGroundSurface(), changeBallMass(), changeCurrentRobot(), changeCurrentTeam(), changeGravity(), customFPS(), recvActions(), restartSimulator(), setCurrentRobotPosition(), showHideSimulator(), takeSnapshot(), takeSnapshotToClipboard(), toggleFullScreen(), update(), and updateRobotLabel().
QSize MainWindow::lastSize private
Definition at line 97 of file mainwindow.h.
Referenced by toggleFullScreen().
QLabel * MainWindow::lblChip private
Definition at line 49 of file mainwindow.h.
Referenced by MainWindow().
QLabel* MainWindow::lblId private
Definition at line 45 of file mainwindow.h.
Referenced by MainWindow().
QLabel* MainWindow::lblIp private
Definition at line 43 of file mainwindow.h.
Referenced by MainWindow().
QLabel* MainWindow::lblKick private
Definition at line 49 of file mainwindow.h.
Referenced by MainWindow().
QLabel* MainWindow::lblPort private
Definition at line 44 of file mainwindow.h.
Referenced by MainWindow().
QLabel* MainWindow::lblV1 private
Definition at line 48 of file mainwindow.h.
Referenced by MainWindow().
QLabel * MainWindow::lblV2 private
Definition at line 48 of file mainwindow.h.
Referenced by MainWindow().
QLabel * MainWindow::lblV3 private
Definition at line 48 of file mainwindow.h.
Referenced by MainWindow().
QLabel * MainWindow::lblV4 private
Definition at line 48 of file mainwindow.h.
Referenced by MainWindow().
QLabel* MainWindow::lblVx private
Definition at line 47 of file mainwindow.h.
Referenced by MainWindow().
QLabel * MainWindow::lblVy private
Definition at line 47 of file mainwindow.h.
Referenced by MainWindow().
QLabel * MainWindow::lblW private
Definition at line 47 of file mainwindow.h.
Referenced by MainWindow().
QTabWidget* MainWindow::left_tab
Definition at line 57 of file mainwindow.h.
Referenced by MainWindow().
MultiVisionStack* MainWindow::multi_stack
Definition at line 69 of file mainwindow.h.
Referenced by closeEvent(), and MainWindow().
QLabel * MainWindow::noiselabel private
Definition at line 92 of file mainwindow.h.
Referenced by customFPS(), and update().
RenderOptions* MainWindow::opts
Definition at line 66 of file mainwindow.h.
Referenced by MainWindow(), and timerEvent().
CStatusPrinter* MainWindow::printer private
Definition at line 87 of file mainwindow.h.
Referenced by customFPS().
bool MainWindow::reseting private
Definition at line 33 of file mainwindow.h.
Referenced by MainWindow(), resetBtnClicked(), and sendPacket().
QTabWidget* MainWindow::right_tab
Definition at line 58 of file mainwindow.h.
Referenced by MainWindow().
RobotWidget* MainWindow::robotwidget private
Definition at line 85 of file mainwindow.h.
Referenced by changeCurrentRobot(), changeCurrentTeam(), customFPS(), setCurrentRobotPosition(), update(), and updateRobotLabel().
VarList* MainWindow::root
Definition at line 55 of file mainwindow.h.
Referenced by MainWindow().
VarTrigger* MainWindow::save_settings_trigger
Definition at line 67 of file mainwindow.h.
Referenced by MainWindow().
QGraphicsScene* MainWindow::scene private
Definition at line 95 of file mainwindow.h.
Referenced by customFPS(), GUI.ompl_gui.MainWindow::display_bots(), and toggleFullScreen().
QLabel * MainWindow::selectinglabel private
Definition at line 92 of file mainwindow.h.
Referenced by customFPS(), and update().
bool MainWindow::sending private
Definition at line 33 of file mainwindow.h.
Referenced by disconnectUdp(), MainWindow(), and sendBtnClicked().
VarList* MainWindow::settings
Definition at line 61 of file mainwindow.h.
Referenced by MainWindow().
QAction * MainWindow::showconfig private
Definition at line 90 of file mainwindow.h.
Referenced by customFPS(), and showHideConfig().
QAction* MainWindow::showsimulator private
Definition at line 90 of file mainwindow.h.
Referenced by customFPS(), and showHideSimulator().
QSplitter* MainWindow::splitter
Definition at line 59 of file mainwindow.h.
Referenced by MainWindow().
vector<QSplitter *> MainWindow::stack_widgets
Definition at line 65 of file mainwindow.h.
Referenced by MainWindow().
CStatusWidget* MainWindow::statusWidget private
Definition at line 88 of file mainwindow.h.
Referenced by customFPS(), and update().
QTimer * MainWindow::timer private
Definition at line 55 of file mainwindow.h.
Referenced by changeTimer(), customFPS(), MainWindow(), and sendBtnClicked().
VarTreeModel* MainWindow::tmodel
Definition at line 63 of file mainwindow.h.
Referenced by MainWindow().
VarTreeView* MainWindow::tree_view
Definition at line 56 of file mainwindow.h.
Referenced by MainWindow().
QTextEdit* MainWindow::txtInfo private
Definition at line 50 of file mainwindow.h.
Referenced by MainWindow().
QUdpSocket MainWindow::udpsocket private
Definition at line 34 of file mainwindow.h.
Referenced by disconnectUdp(), and sendPacket().
QLabel * MainWindow::vanishlabel private
Definition at line 92 of file mainwindow.h.
Referenced by customFPS(), and update().
GLWidgetGraphicsView* MainWindow::view private
Definition at line 96 of file mainwindow.h.
Referenced by toggleFullScreen().
RoboCupSSLServer* MainWindow::visionServer private
Definition at line 98 of file mainwindow.h.
Referenced by customFPS(), reconnectVisionSocket(), and restartSimulator().
QWorkspace* MainWindow::workspace private
Definition at line 78 of file mainwindow.h.
Referenced by customFPS(), and toggleFullScreen().
vector<VarType * > MainWindow::world
Definition at line 62 of file mainwindow.h.
Referenced by closeEvent(), MainWindow(), and slotSaveSettings().
QUdpSocket * MainWindow::yellowStatusSocket private
Definition at line 100 of file mainwindow.h.
Referenced by customFPS(), reconnectYellowStatusSocket(), and restartSimulator().
The documentation for this class was generated from the following files:
grSim/clients/qt/mainwindow.h
grSim/clients/qt/mainwindow.cpp