Documentation: VarTypes::VarType Class Reference
VarTypes::VarType Class Reference
The base class of the VarTypes system.
#include <VarType.h>
Public Slots
void mvcEditCompleted ()
A slot to receive signals from a model-view system that editing of this item was just completed.
Signals
void hasChanged (VarType *)
void wasEdited (VarType *)
void XMLwasRead (VarType *)
This signal is triggered if data was written from an xml node.
void XMLwasWritten (VarType *)
This signal is triggered if data was written to an xml node.
Public Member Functions
VarType (string name="")
virtual ~VarType ()
virtual vector< VarType * > getChildren () const
virtual void deleteAllChildren ()
virtual void setName (string name)
Set the string label of this node.
virtual string getName () const
Get the string label of this node.
virtual void resetToDefault ()
Reset the values of this node to default.
virtual VarTypeFlag getFlags () const
virtual void setFlags (VarTypeFlag f)
virtual void addFlags (VarTypeFlag f)
virtual void removeFlags (VarTypeFlag f)
virtual bool areFlagsSet (VarTypeFlag f) const
VarType * findChild (string label) const
void writeXML (XMLNode &parent, bool blind_append=true)
Write the contents of this VarType node to an XMLNode.
void readXML (XMLNode &us)
Let this VarType node load the contents of an XMLNode.
virtual QWidget * createEditor (const VarItemDelegate *delegate, QWidget *parent, const QStyleOptionViewItem &option)
virtual void setEditorData (const VarItemDelegate *delegate, QWidget *editor) const
virtual void setModelData (const VarItemDelegate *delegate, QWidget *editor)
virtual QSize sizeHint (const VarItemDelegate *delegate, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void paint (const VarItemDelegate *delegate, QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Public Member Functions inherited from VarTypes::VarVal
VarVal ()
virtual ~VarVal ()
virtual VarVal * clone () const
virtual VarVal * deepClone () const
virtual VarTypeId getType () const
Get the type of this VarType node.
virtual string getTypeName () const
Get the string label of the type of this VarType node.
virtual void printdebug () const
virtual string getString () const
Get a human-readable string representation of this node's data.
virtual bool setString (const string &val)
Set this node's data to some string representation.
virtual void getBinarySerialString (string &val) const
string getBinarySerialString () const
virtual void setBinarySerialString (const string &val)
virtual void getSerialString (string &val) const
string getSerialString () const
virtual void setSerialString (const string &val)
virtual bool hasValue () const
virtual bool hasMaxValue () const
virtual bool hasMinValue () const
virtual double getMinValue () const
virtual double getMaxValue () const
virtual double getValue () const
Static Public Member Functions
static void deleteAllVarChildren (XMLNode &node)
Clear an XMLNode's list of children.
static vector< VarType * > readChildrenHelper (XMLNode &parent, vector< VarType * > existing_children, bool only_update_existing, bool blind_append)
A helper function to read a list of children from XML and convert it to a vector of VarType nodes.
Protected Member Functions
virtual void lock () const
virtual void unlock () const
virtual void changed ()
virtual void updateAttributes (XMLNode &us) const
virtual void updateText (XMLNode &us) const
virtual void updateChildren (XMLNode &us) const
virtual void readAttributes (XMLNode &us)
virtual void readText (XMLNode &us)
virtual void readChildren (XMLNode &us)
virtual void loadExternal ()
Static Protected Member Functions
static string fixString (const char *cst)
static string intToString (int val)
static string doubleToString (double val)
static XMLNode findOrAppendChild (XMLNode &parent, string key, string val)
Protected Attributes
QMutex * _mutex
VarTypeFlag _flags
string _name
Detailed Description
The base class of the VarTypes system.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
This is is the base-class of the VarType system. All other VarTypes must publicly inherit this class.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 97 of file VarType.h.
Constructor & Destructor Documentation
VarType::VarType (string name = "")
The constructor of a VarType type. If inheriting this class, you should forward the name argument to this constructor.
Parameters
name The string label of this VarType node
Definition at line 26 of file VarType.cpp.
References _flags, _mutex, _name, changed(), lock(), unlock(), and VarTypes::VARTYPE_FLAG_NONE.
   {
     #ifndef VDATA_NO_THREAD_SAFETY
     _mutex=new QMutex();
     #endif
     lock();
     _name=name;
     _flags=VARTYPE_FLAG_NONE;
     unlock();
     changed();
   }
VarType::~VarType () virtual
Definition at line 39 of file VarType.cpp.
References _mutex.
   {
     #ifndef VDATA_NO_THREAD_SAFETY
     delete _mutex;
     #endif
   }
Member Function Documentation
void VarType::addFlags (VarTypeFlag f) virtual
Add (bitwise-or) some renderflags f to the currently set renderflags.
See also
VarTypeFlag
Definition at line 62 of file VarType.cpp.
References _flags, changed(), lock(), and unlock().
Referenced by CameraParameters::CameraParameters(), CaptureBlueFox2::CaptureBlueFox2(), CaptureDC1394v2::CaptureDC1394v2(), CaptureThread::CaptureThread(), CaptureV4L::CaptureV4L(), CaptureThread::init(), CaptureV4L::readParameterProperty(), CaptureDC1394v2::readParameterProperty(), CaptureV4L::readParameterValues(), CaptureDC1394v2::readParameterValues(), CaptureThread::stop(), CaptureBlueFox2::stopCapture(), CaptureV4L::stopCapture(), CaptureDC1394v2::stopCapture(), CMPattern::Team::Team(), and CMPattern::TeamSelector::TeamSelector().
{
     lock();
     VarTypeFlag old=_flags;
     _flags |= f;
     if (_flags != old) {
       unlock();
       changed();
     } else {
       unlock();
     }
   }
bool VarType::areFlagsSet (VarTypeFlag f) const virtual
Check whether all the flags specified in f are currently set.
See also
VarTypeFlag
Definition at line 86 of file VarType.cpp.
References _flags, lock(), and unlock().
Referenced by VarTypes::VarItem::changeUpdate(), readXML(), VarTypes::VarItem::update(), VarTypes::VarItem::updateTree(), and writeXML().
{
     lock();
     bool answer=(_flags & f) == f;
     unlock();
     return (answer);
   }
virtual void VarTypes::VarType::changed () inline protected virtual
Reimplemented from VarTypes::VarVal.
Reimplemented in VarTypes::VarProtoBuffer< CLASS_VARVAL_TYPE, TPL_vartype_id >.
Definition at line 133 of file VarType.h.
References VARTYPE_MACRO_CHANGED.
Referenced by addFlags(), VarTypes::VarBlob::allocate(), VarTypes::VarBlob::clearData(), VarTypes::VarExternal::loadExternal(), removeFlags(), resetToDefault(), VarTypes::VarBlob::setBinarySerialString(), VarTypes::VarBlob::setDataPointer(), VarTypes::VarString::setDefault(), VarTypes::VarBool::setDefault(), VarTypes::VarInt::setDefault(), VarTypes::VarDouble::setDefault(), setFlags(), VarTypes::VarTrigger::setLabel(), VarTypes::VarDouble::setMax(), VarTypes::VarInt::setMax(), VarTypes::VarDouble::setMin(), VarTypes::VarInt::setMin(), setName(), VarTypes::VarQWidget::setQWidget(), VarTypes::VarBlob::setSerialString(), VarTypes::VarTrigger::trigger(), VarTypes::VarDouble::unsetMax(), VarTypes::VarInt::unsetMax(), VarTypes::VarDouble::unsetMin(), VarTypes::VarInt::unsetMin(), VarTypes::VarBlob::VarBlob(), VarTypes::VarBool::VarBool(), VarTypes::VarDouble::VarDouble(), VarTypes::VarInt::VarInt(), VarTypes::VarQWidget::VarQWidget(), VarTypes::VarString::VarString(), VarTypes::VarTrigger::VarTrigger(), and VarType().
{
       VARTYPE_MACRO_CHANGED;
     }
QWidget * VarType::createEditor (const VarItemDelegate * delegate, QWidget * parent, const QStyleOptionViewItem & option) virtual
Reimplemented in VarTypes::VarStringEnum, VarTypes::VarSelection, VarTypes::VarInt, VarTypes::VarList, VarTypes::VarDouble, VarTypes::VarBlob, VarTypes::VarTrigger, VarTypes::VarQWidget, and VarTypes::VarBool.
Definition at line 339 of file VarType.cpp.
Referenced by VarTypes::VarItemDelegate::createEditor().
{
     (void)delegate;
     (void)option;
     return new QLineEdit(parent);
   }
virtual void VarTypes::VarType::deleteAllChildren () inline virtual
removes all children, by actually deleting them in memory note that this is recursive. use it to un-allocate entire hierarchies from memory
Reimplemented in VarTypes::VarList.
Definition at line 163 of file VarType.h.
{
     }
void VarType::deleteAllVarChildren (XMLNode & node) static
Clear an XMLNode's list of children.
Definition at line 186 of file VarType.cpp.
References VarTypes::XMLNode::deleteNodeContent(), VarTypes::XMLNode::getChildNode(), velocity.pid_::i, VarTypes::XMLNode::nChildNode(), and t.
Referenced by updateChildren(), and VarTypes::VarXML::write().
   {
     int n=node.nChildNode("Var");
     int i=0;
     for (i=0; i<n; i++) {
       //fixed 08/06/2007: always delete first node in list, instead of using iterator
       XMLNode t=node.getChildNode("Var",0);
       t.deleteNodeContent(1);
     }
   }
string VarType::doubleToString (double val) static protected
Definition at line 138 of file VarType.cpp.
Referenced by VarTypes::VarDouble::updateAttributes().
   {
     char result[255];
     result[0]=0;
     sprintf(result,"%lf",val);
     return result;
   }
VarType * VarType::findChild (string label) const
Finds a child based on its label Returns 0 if not found
Definition at line 323 of file VarType.cpp.
References getChildren(), getName(), and velocity.pid_::i.
{
     vector<VarType *> children = getChildren();
     unsigned int s = children.size();
     for (unsigned int i=0;i<s;i++) {
       if (children[i]->getName().compare(label)==0) return (children[i]);
     }
     return 0;
   }
XMLNode VarType::findOrAppendChild (XMLNode & parent, string key, string val) static protected
Definition at line 147 of file VarType.cpp.
References VarTypes::XMLNode::addChild(), fixString(), VarTypes::XMLNode::getAttribute(), VarTypes::XMLNode::getChildNode(), velocity.pid_::i, VarTypes::XMLNode::nChildNode(), and t.
Referenced by writeXML().
   {
     //access ourselves:
     int n=parent.nChildNode("Var");
     int i,myIterator=0;
     //iterate through them and check if we already exist
     for (i=0; i<n; i++) {
       XMLNode t=parent.getChildNode("Var",&myIterator);
       if (fixString(t.getAttribute(key.c_str()))==val) {
         return t;
       }
     }
     return(parent.addChild("Var"));
   }
string VarType::fixString (const char * cst) static protected
Definition at line 121 of file VarType.cpp.
Referenced by findOrAppendChild(), VarTypes::VarDouble::readAttributes(), VarTypes::VarInt::readAttributes(), readChildrenHelper(), and readText().
   {
     if (cst==0) {
       return "";
     } else {
       return cst;
     }
   }
vector< VarType * > VarType::getChildren () const virtual
Return a list of children nodes of this VarType type. This can be an empty vector if the node does not have any children.
Reimplemented in VarTypes::VarStringEnum, VarTypes::VarSelection, and VarTypes::VarList.
Definition at line 93 of file VarType.cpp.
References v.
Referenced by VarTypes::VarNotifier::addRecursive(), findChild(), readChildrenHelper(), VarTypes::VarNotifier::removeRecursive(), and updateChildren().
   {
     vector<VarType *> v;
     return v;
   }
VarTypeFlag VarType::getFlags () const virtual
Return the current render option bitflags
See also
VarTypeFlag
Definition at line 46 of file VarType.cpp.
References _flags.
Referenced by VarTypes::VarTreeView::checkDataChanged(), VarTypes::VarItemDelegate::setEditorData(), and VarTypes::VarItem::update().
{
     return _flags;
   }
string VarType::getName () const virtual
Get the string label of this node.
Definition at line 111 of file VarType.cpp.
References _name.
Referenced by CaptureFlycap::changed(), findChild(), VarTypes::VarList::findChildOrReplace(), FieldLine::FromVarList(), FieldCircularArc::FromVarList(), readChildrenHelper(), CaptureV4L::readParameterProperty(), CaptureDC1394v2::readParameterProperty(), CaptureV4L::readParameterValues(), CaptureDC1394v2::readParameterValues(), CMPattern::Team::Team(), VarTypes::VarItem::update(), CaptureFlycap::writeParameterValues(), CaptureV4L::writeParameterValues(), CaptureDC1394v2::writeParameterValues(), and writeXML().
   {
     return _name;
   }
void VarType::hasChanged (VarType * _t1) signal
This signal is triggered when any data or flag of this VarType has changed. This includes changes that were done programmatically, as well through a GUI. It also includes changes to render-flags or other meta-data.
Definition at line 108 of file moc_VarType.cxx.
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 0, _a);
 }
string VarType::intToString (int val) static protected
Definition at line 130 of file VarType.cpp.
Referenced by VarTypes::VarInt::updateAttributes().
   {
     char result[255];
     result[0]=0;
     sprintf(result,"%d",val);
     return result;
   }
void VarType::loadExternal () protected virtual
Reimplemented in VarTypes::VarExternal.
Definition at line 244 of file VarType.cpp.
Referenced by readChildrenHelper().
{
   }
virtual void VarTypes::VarType::lock () const inline protected virtual
Reimplemented from VarTypes::VarVal.
Definition at line 127 of file VarType.h.
References VARTYPE_MACRO_LOCK.
Referenced by addFlags(), areFlagsSet(), VarTypes::VarTrigger::getAndResetCounter(), VarTypes::VarTrigger::getCounter(), VarTypes::VarInt::getInt(), VarTypes::VarTrigger::getLabel(), VarTypes::VarDouble::getMax(), VarTypes::VarInt::getMax(), VarTypes::VarDouble::getMin(), VarTypes::VarInt::getMin(), VarTypes::VarDouble::hasMax(), VarTypes::VarInt::hasMax(), VarTypes::VarDouble::hasMin(), VarTypes::VarInt::hasMin(), VarTypes::VarExternal::loadExternal(), removeFlags(), VarTypes::VarTrigger::resetCounter(), setFlags(), VarTypes::VarTrigger::setLabel(), VarTypes::VarDouble::setMax(), VarTypes::VarInt::setMax(), VarTypes::VarDouble::setMin(), VarTypes::VarInt::setMin(), setName(), VarTypes::VarTrigger::trigger(), VarTypes::VarDouble::unsetMax(), VarTypes::VarInt::unsetMax(), VarTypes::VarDouble::unsetMin(), VarTypes::VarInt::unsetMin(), VarTypes::VarBool::VarBool(), VarTypes::VarExternal::VarExternal(), and VarType().
{
       VARTYPE_MACRO_LOCK;
     }
void VarTypes::VarType::mvcEditCompleted () inline slot
A slot to receive signals from a model-view system that editing of this item was just completed.
Definition at line 122 of file VarType.h.
Referenced by VarTypes::VarBool::setModelData(), VarTypes::VarDouble::setModelData(), VarTypes::VarInt::setModelData(), and setModelData().
{
       wasEdited(this);
     }
void VarType::paint (const VarItemDelegate * delegate, QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Definition at line 334 of file VarType.cpp.
Referenced by VarTypes::VarItemDelegate::paint().
{
     //let the QT default delegate do the painting:
     delegate->QItemDelegate::paint(painter,option,index);
   }
void VarType::readAttributes (XMLNode & us) protected virtual
Reimplemented in VarTypes::VarInt, VarTypes::VarDouble, and VarTypes::VarExternal.
Definition at line 219 of file VarType.cpp.
Referenced by readXML().
   {
     (void)us;
   }
void VarType::readChildren (XMLNode & us) protected virtual
Reimplemented in VarTypes::VarStringEnum, VarTypes::VarSelection, VarTypes::VarList, and VarTypes::VarExternal.
Definition at line 229 of file VarType.cpp.
Referenced by readXML().
   {
     (void)us;
   }
vector< VarType * > VarType::readChildrenHelper (XMLNode & parent, vector< VarType * > existing_children, bool only_update_existing, bool blind_append) static
A helper function to read a list of children from XML and convert it to a vector of VarType nodes.
Definition at line 248 of file VarType.cpp.
References fixString(), VarTypes::XMLNode::getAttribute(), VarTypes::XMLNode::getChildNode(), getChildren(), VarTypes::VarTypesInstance::getFactory(), getName(), VarTypes::VarVal::getType(), velocity.pid_::i, loadExternal(), VarTypes::XMLNode::nChildNode(), VarTypes::VarTypesFactory::newVarType(), readXML(), setName(), VarTypes::VarTypesFactory::stringToType(), t, and VarTypes::VARTYPE_ID_UNDEFINED.
Referenced by VarTypes::VarExternal::loadExternal(), and VarTypes::VarXML::read().
   {
     //this again does non-destructive integration
     //As a result we update any predefined structures and
     //append any types that don't exist yet.
     vector<VarType *> result=existing_children;
     int n=parent.nChildNode("Var");
     int i,myIterator=0;
     //iterate through them and check if we already exist
     set<VarType *> unmatched_children;
     for (unsigned int j=0;j<existing_children.size();j++) {
       unmatched_children.insert(existing_children[j]);
     }
     for (i=0; i<n; i++) {
       XMLNode t=parent.getChildNode("Var",&myIterator);
       string sname=fixString(t.getAttribute("name"));
       string stype=fixString(t.getAttribute("type"));
       VarTypeId type=VarTypesInstance::getFactory()->stringToType(stype);
       if (type!=VARTYPE_ID_UNDEFINED) {
         bool found=false;
         if (sname!="" && blind_append==false) {
           //try to find existing child with this name
           for (unsigned int j=0;j<existing_children.size();j++) {
             if (existing_children[j]->getName()==sname) {
               if (existing_children[j]->getType()==type) {
                 existing_children[j]->readXML(t);
               } else {
                 fprintf(stderr,"Type mismatch between XML and Data-Tree. Object name: %s. XML type was: %s. Internal type was: %s\n",sname.c_str(),stype.c_str(),existing_children[j]->getTypeName().c_str());
               }
               unmatched_children.erase(existing_children[j]);
               found=true;
               break;
               //ok matching name was found...update this node
             }
           }
         }
         if (found==false) {
           //printf("unable to find: %s in existing\n",sname.c_str());
           //the item did not already exist in the children...
           if (only_update_existing==false) {
             //create new node and append it:
             VarType * td= VarTypesInstance::getFactory()->newVarType(type);
             td->setName(sname);
             td->readXML(t);
             result.push_back(td);
           }
         }
       } else {
         fprintf(stderr,"Found var with no or unknown type in XML... type: %s\n",stype.c_str());
       }
     }
     //---fix for recursing tree that's not defined in xml yet:
     queue<VarType *> _queue;
     for (set<VarType *>::iterator iter = unmatched_children.begin(); iter!=unmatched_children.end(); iter++) {
       if (*iter!=0) _queue.push(*iter);
     }
     //recurse all unmatched children to make sure we load all externals:
     while(_queue.empty()==false) {
       VarType * d = _queue.front();
       _queue.pop();
       d->loadExternal();
       vector<VarType *> children = d->getChildren();
       int s=children.size();
       for (int i=0;i<s;i++) {
         if (children[i]!=0) _queue.push(children[i]);
       }
     }
     //---end of fix
     return result;
   }
void VarType::readText (XMLNode & us) protected virtual
Definition at line 224 of file VarType.cpp.
References fixString(), VarTypes::XMLNode::getText(), and VarTypes::VarVal::setSerialString().
Referenced by readXML().
   {
     setSerialString(fixString(us.getText()));
   }
void VarType::readXML (XMLNode & us)
Let this VarType node load the contents of an XMLNode.
Definition at line 234 of file VarType.cpp.
References areFlagsSet(), readAttributes(), readChildren(), readText(), VarTypes::VARTYPE_FLAG_NOLOAD, VarTypes::VARTYPE_FLAG_NOLOAD_ATTRIBUTES, and XMLwasRead().
Referenced by readChildrenHelper().
   {
     if (areFlagsSet(VARTYPE_FLAG_NOLOAD)) return;
     //printf("readXML: %s\n",this->getName().c_str());
     if (areFlagsSet(VARTYPE_FLAG_NOLOAD_ATTRIBUTES)==false) readAttributes(us);
     readText(us);
     readChildren(us);
     emit(XMLwasRead(this));
   }
void VarType::removeFlags (VarTypeFlag f) virtual
Remove some renderflags f from the currently set renderflags.
See also
VarTypeFlag
Definition at line 74 of file VarType.cpp.
References _flags, changed(), lock(), and unlock().
Referenced by CaptureThread::init(), CaptureV4L::readParameterProperty(), CaptureDC1394v2::readParameterProperty(), CaptureV4L::readParameterValues(), CaptureDC1394v2::readParameterValues(), CaptureBlueFox2::startCapture(), CaptureV4L::startCapture(), CaptureDC1394v2::startCapture(), and CaptureThread::stop().
{
     lock();
     VarTypeFlag old=_flags;
     _flags = _flags & (~f);
     if (_flags != old) {
       unlock();
       changed();
     } else {
       unlock();
     }
   }
void VarType::resetToDefault () virtual
Reset the values of this node to default.
Reimplemented in VarTypes::VarInt, VarTypes::VarDouble, VarTypes::VarTrigger, VarTypes::VarQWidget, VarTypes::VarList, VarTypes::VarStringEnum, VarTypes::VarBool, and VarTypes::VarString.
Definition at line 116 of file VarType.cpp.
References changed().
   {
     changed();
   }
void VarType::setEditorData (const VarItemDelegate * delegate, QWidget * editor) const virtual
Reimplemented in VarTypes::VarStringEnum, VarTypes::VarSelection, VarTypes::VarInt, VarTypes::VarDouble, VarTypes::VarTrigger, VarTypes::VarQWidget, and VarTypes::VarBool.
Definition at line 345 of file VarType.cpp.
References VarTypes::VarVal::getString().
Referenced by VarTypes::VarItemDelegate::setEditorData().
{
     (void)delegate;
     QLineEdit * ledit=(QLineEdit *) editor;
     ledit->setText(QString::fromStdString(getString()));
   }
void VarType::setFlags (VarTypeFlag f) virtual
Set the current render option bitflags
See also
VarTypeFlag
Definition at line 50 of file VarType.cpp.
References _flags, changed(), lock(), and unlock().
{
     lock();
     VarTypeFlag old=_flags;
     _flags=f;
     if (_flags != old) {
       unlock();
       changed();
     } else {
       unlock();
     }
   }
void VarType::setModelData (const VarItemDelegate * delegate, QWidget * editor) virtual
Reimplemented in VarTypes::VarStringEnum, VarTypes::VarSelection, VarTypes::VarInt, VarTypes::VarDouble, VarTypes::VarTrigger, VarTypes::VarQWidget, and VarTypes::VarBool.
Definition at line 351 of file VarType.cpp.
References mvcEditCompleted(), and VarTypes::VarVal::setString().
Referenced by VarTypes::VarItemDelegate::setModelData().
{
     (void)delegate;
     QLineEdit * ledit=(QLineEdit *) editor;
     if (setString(ledit->text().toStdString())) mvcEditCompleted();
   }
void VarType::setName (string name) virtual
Set the string label of this node.
Definition at line 99 of file VarType.cpp.
References _name, changed(), lock(), and unlock().
Referenced by readChildrenHelper(), FieldLine::Rename(), FieldCircularArc::Rename(), and CMPattern::Team::slotTeamNameChanged().
   {
     lock();
     if (name!=_name) {
       _name=name;
       unlock();
       changed();
     } else {
       unlock();
     }
   }
QSize VarType::sizeHint (const VarItemDelegate * delegate, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Reimplemented in VarTypes::VarSelection.
Definition at line 357 of file VarType.cpp.
Referenced by VarTypes::VarItemDelegate::sizeHint().
{
     return (delegate->QItemDelegate::sizeHint(option, index));
   }
virtual void VarTypes::VarType::unlock () const inline protected virtual
Reimplemented from VarTypes::VarVal.
Definition at line 130 of file VarType.h.
References VARTYPE_MACRO_UNLOCK.
Referenced by addFlags(), areFlagsSet(), VarTypes::VarTrigger::getAndResetCounter(), VarTypes::VarTrigger::getCounter(), VarTypes::VarInt::getInt(), VarTypes::VarTrigger::getLabel(), VarTypes::VarDouble::getMax(), VarTypes::VarInt::getMax(), VarTypes::VarDouble::getMin(), VarTypes::VarInt::getMin(), VarTypes::VarDouble::hasMax(), VarTypes::VarInt::hasMax(), VarTypes::VarDouble::hasMin(), VarTypes::VarInt::hasMin(), VarTypes::VarExternal::loadExternal(), removeFlags(), VarTypes::VarTrigger::resetCounter(), setFlags(), VarTypes::VarTrigger::setLabel(), VarTypes::VarDouble::setMax(), VarTypes::VarInt::setMax(), VarTypes::VarDouble::setMin(), VarTypes::VarInt::setMin(), setName(), VarTypes::VarTrigger::trigger(), VarTypes::VarDouble::unsetMax(), VarTypes::VarInt::unsetMax(), VarTypes::VarDouble::unsetMin(), VarTypes::VarInt::unsetMin(), VarTypes::VarBool::VarBool(), VarTypes::VarExternal::VarExternal(), and VarType().
{
       VARTYPE_MACRO_UNLOCK;
     }
void VarType::updateAttributes (XMLNode & us) const protected virtual
TODO: implement this function. It might be useful for some purposes. VarType * merge(VarType * structure, VarType * data);
Reimplemented in VarTypes::VarInt, VarTypes::VarDouble, and VarTypes::VarExternal.
Definition at line 163 of file VarType.cpp.
Referenced by writeXML().
   {
     (void)us;
   }
void VarType::updateChildren (XMLNode & us) const protected virtual
Reimplemented in VarTypes::VarExternal.
Definition at line 175 of file VarType.cpp.
References deleteAllVarChildren(), getChildren(), velocity.pid_::i, and v.
Referenced by writeXML().
   {
     //wipe out all children of type var...
     deleteAllVarChildren(us);
     vector<VarType *> v = getChildren();
     for (unsigned int i=0;i<v.size();i++) {
       //printf("writing: %d/%d (%s)\n",i,v.size(),v[i]->getName().c_str());
       v[i]->writeXML(us,true);
     }
   }
void VarType::updateText (XMLNode & us) const protected virtual
Definition at line 168 of file VarType.cpp.
References VarTypes::VarVal::getSerialString(), and VarTypes::XMLNode::updateText().
Referenced by writeXML().
   {
     string tmp;
     getSerialString(tmp);
     us.updateText(tmp.c_str());
   }
void VarType::wasEdited (VarType * _t1) signal
This signal is triggered when data of this VarType has been edited by a user through an MVC viewer. Unlike /c hasChanged(), this signal is not necessarily triggered if this data was internally changed. So, if you would like to catch all events, you should use /c hasChanged() instead.
Definition at line 115 of file moc_VarType.cxx.
Referenced by VarTypes::VarTrigger::trigger().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 1, _a);
 }
void VarType::writeXML (XMLNode & parent, bool blind_append = true)
Write the contents of this VarType node to an XMLNode.
Definition at line 197 of file VarType.cpp.
References VarTypes::XMLNode::addChild(), areFlagsSet(), findOrAppendChild(), getName(), VarTypes::VarVal::getTypeName(), VarTypes::XMLNode::updateAttribute(), updateAttributes(), updateChildren(), updateText(), VarTypes::VARTYPE_FLAG_NOSAVE, and XMLwasWritten().
   {
     if (areFlagsSet(VARTYPE_FLAG_NOSAVE)) return;
     XMLNode us;
     if (blind_append) {
       //do a simple append to the XML parent
       us = parent.addChild("Var");
     } else {
       //do a name-based find and update, or append if it does not exist.
       us = findOrAppendChild(parent,"name",getName());
     }
     us.updateAttribute(getName().c_str(),"name","name");
     us.updateAttribute(getTypeName().c_str(),"type","type");
     updateAttributes(us);
     updateText(us);
     updateChildren(us);
     emit(XMLwasWritten(this));
   }
void VarType::XMLwasRead (VarType * _t1) signal
This signal is triggered if data was written from an xml node.
Definition at line 122 of file moc_VarType.cxx.
Referenced by readXML().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 2, _a);
 }
void VarType::XMLwasWritten (VarType * _t1) signal
This signal is triggered if data was written to an xml node.
Definition at line 129 of file moc_VarType.cxx.
Referenced by writeXML().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 3, _a);
 }
Field Documentation
VarTypeFlag VarTypes::VarType::_flags protected
Definition at line 140 of file VarType.h.
Referenced by addFlags(), areFlagsSet(), getFlags(), removeFlags(), setFlags(), VarTypes::VarBool::VarBool(), VarTypes::VarQWidget::VarQWidget(), VarTypes::VarTrigger::VarTrigger(), and VarType().
QMutex* VarTypes::VarType::_mutex protected
Definition at line 138 of file VarType.h.
Referenced by VarType(), and ~VarType().
string VarTypes::VarType::_name protected
Definition at line 141 of file VarType.h.
Referenced by getName(), setName(), and VarType().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/primitives/VarType.h
ssl-vision/build/src/shared/vartypes/primitives/moc_VarType.cxx
ssl-vision/src/shared/vartypes/primitives/VarType.cpp