Documentation: SSLWorld Class Reference
SSLWorld Class Reference
#include <sslworld.h>
Public Slots
void recvActions ()
Signals
void fpsChanged (int newFPS)
Public Member Functions
SSLWorld (QGLWidget *parent, ConfigWidget *_cfg, RobotsFomation *form1, RobotsFomation *form2)
virtual ~SSLWorld ()
void glinit ()
void step (dReal dt=-1)
SSL_WrapperPacket * generatePacket (int cam_id=0)
void addFieldLinesArcs (SSL_GeometryFieldSize *field)
Vector2f * allocVector (float x, float y)
void addFieldLine (SSL_GeometryFieldSize *field, const std::string &name, float p1_x, float p1_y, float p2_x, float p2_y, float thickness)
void addFieldArc (SSL_GeometryFieldSize *field, const string &name, float c_x, float c_y, float radius, float a1, float a2, float thickness)
void sendVisionBuffer ()
bool visibleInCam (int id, double x, double y)
Data Fields
dReal customDT
bool isGLEnabled
ConfigWidget * cfg
CGraphics * g
PWorld * p
PBall * ball
PGround * ground
PRay * ray
PFixedBox * walls [10]
int selected
bool show3DCursor
dReal cursor_x
dReal cursor_y
dReal cursor_z
dReal cursor_radius
RoboCupSSLServer * visionServer
QUdpSocket * commandSocket
QUdpSocket * blueStatusSocket
QUdpSocket * yellowStatusSocket
bool updatedCursor
Robot * robots [12 *2]
QTime * timer
int sendGeomCount
Private Attributes
QGLWidget * m_parent
int framenum
dReal last_dt
QList< SendingPacket * > sendQueue
char packet [200]
char * in_buffer
Detailed Description
Definition at line 53 of file sslworld.h.
Constructor & Destructor Documentation
SSLWorld::SSLWorld (QGLWidget * parent, ConfigWidget * _cfg, RobotsFomation * form1, RobotsFomation * form2)
Definition at line 139 of file sslworld.cpp.
References PWorld::addObject(), ball, ConfigWidget::BallBounce(), ConfigWidget::BallBounceVel(), ballCallBack(), ConfigWidget::BallMass(), ConfigWidget::BallRadius(), ConfigWidget::blueSettings, PSurface::callback, cfg, Robot::chassis, PWorld::createSurface(), customDT, ConfigWidget::Field_Defense_Rad(), ConfigWidget::Field_Defense_Stretch(), ConfigWidget::Field_Length(), ConfigWidget::Field_Line_Width(), ConfigWidget::Field_Margin(), ConfigWidget::Field_Penalty_Line(), ConfigWidget::Field_Penalty_Point(), ConfigWidget::Field_Penalty_Rad(), ConfigWidget::Field_Rad(), ConfigWidget::Field_Referee_Margin(), ConfigWidget::Field_Width(), framenum, fric(), g, ConfigWidget::Goal_Depth(), ConfigWidget::Goal_Height(), ConfigWidget::Goal_Thickness(), ConfigWidget::Goal_Width(), ground, velocity.pid_::i, in_buffer, PWorld::initAllObjects(), isGLEnabled, k, RobotSettings::Kicker_Friction, last_dt, m_parent, p, ray, rayCallback(), ROBOT_COUNT, ROBOT_GRAY, ROBOT_START_Z, robots, ConfigWidget::robotSettings, sendGeomCount, CGraphics::setSphereQuality(), CGraphics::setViewpoint(), show3DCursor, PSurface::surface, timer, updatedCursor, PSurface::usefdir1, WALL_COUNT, ConfigWidget::Wall_Thickness(), walls, WHEEL_COUNT, wheelCallBack(), RobotsFomation::x, RobotsFomation::y, and ConfigWidget::yellowSettings.
     : QObject(parent)
 {
     isGLEnabled = true;
     customDT = -1;
     _w = this;
     cfg = _cfg;
     m_parent = parent;
     show3DCursor = false;
     updatedCursor = false;
     framenum = 0;
     last_dt = -1;
     g = new CGraphics(parent);
     g->setSphereQuality(1);
     g->setViewpoint(0,-(cfg->Field_Width()+cfg->Field_Margin()*2.0f)/2.0f,3,90,-45,0);
     p = new PWorld(0.05,9.81f,g);
     ball = new PBall (0,0,0.5,cfg->BallRadius(),cfg->BallMass(), 1,0.7,0);
     ground = new PGround(cfg->Field_Rad(),cfg->Field_Length(),cfg->Field_Width(),cfg->Field_Penalty_Rad(),cfg->Field_Penalty_Line(),cfg->Field_Penalty_Point(),cfg->Field_Line_Width(),cfg->Field_Defense_Stretch(),cfg->Field_Defense_Rad(),0);
     ray = new PRay(50);
     // Bounding walls
     const double thick = cfg->Wall_Thickness();
     const double increment = cfg->Field_Margin() + cfg->Field_Referee_Margin() + thick / 2;
     const double pos_x = cfg->Field_Length() / 2.0 + increment;
     const double pos_y = cfg->Field_Width() / 2.0 + increment;
     const double pos_z = 0.0;
     const double siz_x = 2.0 * pos_x;
     const double siz_y = 2.0 * pos_y;
     const double siz_z = 0.4;
     const double tone = 1.0;
     walls[0] = new PFixedBox(thick/2, pos_y, pos_z,
                              siz_x, thick, siz_z,
                              tone, tone, tone);
     walls[1] = new PFixedBox(-thick/2, -pos_y, pos_z,
                              siz_x, thick, siz_z,
                              tone, tone, tone);
     walls[2] = new PFixedBox(pos_x, -thick/2, pos_z,
                              thick, siz_y, siz_z,
                              tone, tone, tone);
     walls[3] = new PFixedBox(-pos_x, thick/2, pos_z,
                              thick, siz_y, siz_z,
                              tone, tone, tone);
     // Goal walls
     const double gthick = cfg->Goal_Thickness();
     const double gpos_x = (cfg->Field_Length() + gthick) / 2.0 + cfg->Goal_Depth();
     const double gpos_y = (cfg->Goal_Width() + gthick) / 2.0;
     const double gpos_z = cfg->Goal_Height() / 2.0;
     const double gsiz_x = cfg->Goal_Depth() + gthick;
     const double gsiz_y = cfg->Goal_Width();
     const double gsiz_z = cfg->Goal_Height();
     const double gpos2_x = (cfg->Field_Length() + gsiz_x) / 2.0;
     walls[4] = new PFixedBox(gpos_x, 0.0, gpos_z,
                              gthick, gsiz_y, gsiz_z,
                              tone, tone, tone);
     walls[5] = new PFixedBox(gpos2_x, -gpos_y, gpos_z,
                              gsiz_x, gthick, gsiz_z,
                              tone, tone, tone);
     walls[6] = new PFixedBox(gpos2_x, gpos_y, gpos_z,
                              gsiz_x, gthick, gsiz_z,
                              tone, tone, tone);
     walls[7] = new PFixedBox(-gpos_x, 0.0, gpos_z,
                              gthick, gsiz_y, gsiz_z,
                              tone, tone, tone);
     walls[8] = new PFixedBox(-gpos2_x, -gpos_y, gpos_z,
                              gsiz_x, gthick, gsiz_z,
                              tone, tone, tone);
     walls[9] = new PFixedBox(-gpos2_x, gpos_y, gpos_z,
                              gsiz_x, gthick, gsiz_z,
                              tone, tone, tone);
     p->addObject(ground);
     p->addObject(ball);
     p->addObject(ray);
     for (int i=0;i<10;i++)
         p->addObject(walls[i]);
     const int wheeltexid = 4 * ROBOT_COUNT + 12 + 1 ; //37 for 6 robots
     cfg->robotSettings = cfg->blueSettings;
     for (int k=0;k<ROBOT_COUNT;k++)
         robots[k] = new Robot(p,ball,cfg,-form1->x[k],form1->y[k],ROBOT_START_Z(cfg),ROBOT_GRAY,ROBOT_GRAY,ROBOT_GRAY,k+1,wheeltexid,1);
     cfg->robotSettings = cfg->yellowSettings;
     for (int k=0;k<ROBOT_COUNT;k++)
         robots[k+ROBOT_COUNT] = new Robot(p,ball,cfg,form2->x[k],form2->y[k],ROBOT_START_Z(cfg),ROBOT_GRAY,ROBOT_GRAY,ROBOT_GRAY,k+ROBOT_COUNT+1,wheeltexid,-1);//XXX
     p->initAllObjects();
     //Surfaces
     p->createSurface(ray,ground)->callback = rayCallback;
     p->createSurface(ray,ball)->callback = rayCallback;
     for (int k=0;k<ROBOT_COUNT * 2;k++)
     {
         p->createSurface(ray,robots[k]->chassis)->callback = rayCallback;
         p->createSurface(ray,robots[k]->dummy)->callback = rayCallback;
     }
     PSurface ballwithwall;
     ballwithwall.surface.mode = dContactBounce | dContactApprox1;// | dContactSlip1;
     ballwithwall.surface.mu = 1;//fric(cfg->ballfriction());
     ballwithwall.surface.bounce = cfg->BallBounce();
     ballwithwall.surface.bounce_vel = cfg->BallBounceVel();
     ballwithwall.surface.slip1 = 0;//cfg->ballslip();
     PSurface wheelswithground;
     PSurface* ball_ground = p->createSurface(ball,ground);
     ball_ground->surface = ballwithwall.surface;
     ball_ground->callback = ballCallBack;
     PSurface ballwithkicker;
     ballwithkicker.surface.mode = dContactApprox1;
     ballwithkicker.surface.mu = fric(cfg->robotSettings.Kicker_Friction);
     ballwithkicker.surface.slip1 = 5;
     for (int i = 0; i < WALL_COUNT; i++)
         p->createSurface(ball, walls[i])->surface = ballwithwall.surface;
     for (int k = 0; k < 2 * ROBOT_COUNT; k++)
     {
         p->createSurface(robots[k]->chassis,ground);
         for (int j = 0; j < WALL_COUNT; j++)
             p->createSurface(robots[k]->chassis,walls[j]);
         p->createSurface(robots[k]->dummy,ball);
         //p->createSurface(robots[k]->chassis,ball);
         p->createSurface(robots[k]->kicker->box,ball)->surface = ballwithkicker.surface;
         for (int j = 0; j < WHEEL_COUNT; j++)
         {
             p->createSurface(robots[k]->wheels[j]->cyl,ball);
             PSurface* w_g = p->createSurface(robots[k]->wheels[j]->cyl,ground);
             w_g->surface=wheelswithground.surface;
             w_g->usefdir1=true;
             w_g->callback=wheelCallBack;
         }
         for (int j = k + 1; j < 2 * ROBOT_COUNT; j++)
         {
             if (k != j)
             {
                 p->createSurface(robots[k]->dummy,robots[j]->dummy); //seams ode doesn't understand cylinder-cylinder contacts, so I used spheres
                 p->createSurface(robots[k]->chassis,robots[j]->kicker->box);
             }
         }
     }
     sendGeomCount = 0;
     timer = new QTime();
     timer->start();
     in_buffer = new char [65536];
 }
SSLWorld::~SSLWorld () virtual
Definition at line 300 of file sslworld.cpp.
References g, and p.
 {
     delete g;
     delete p;
 }
Member Function Documentation
void SSLWorld::addFieldArc (SSL_GeometryFieldSize * field, const string & name, float c_x, float c_y, float radius, float a1, float a2, float thickness)
Definition at line 780 of file sslworld.cpp.
Referenced by addFieldLinesArcs().
{
     SSL_FieldCicularArc *arc = field->add_field_arcs();
     arc->set_name(name.c_str());
     arc->mutable_center()->set_x(c_x);
     arc->mutable_center()->set_y(c_y);
     arc->set_radius(radius);
     arc->set_a1(a1);
     arc->set_a2(a2);
     arc->set_thickness(thickness);
 }
void SSLWorld::addFieldLine (SSL_GeometryFieldSize * field, const std::string & name, float p1_x, float p1_y, float p2_x, float p2_y, float thickness)
Definition at line 770 of file sslworld.cpp.
Referenced by addFieldLinesArcs().
{
     SSL_FieldLineSegment *line = field->add_field_lines();
     line->set_name(name.c_str());
     line->mutable_p1()->set_x(p1_x);
     line->mutable_p1()->set_y(p1_y);
     line->mutable_p2()->set_x(p2_x);
     line->mutable_p2()->set_y(p2_y);
     line->set_thickness(thickness);
 }
void SSLWorld::addFieldLinesArcs (SSL_GeometryFieldSize * field)
Definition at line 721 of file sslworld.cpp.
References addFieldArc(), addFieldLine(), cfg, CONVUNIT, ConfigWidget::Field_Defense_Rad(), ConfigWidget::Field_Defense_Stretch(), ConfigWidget::Field_Length(), ConfigWidget::Field_Line_Width(), ConfigWidget::Field_Rad(), ConfigWidget::Field_Referee_Margin(), ConfigWidget::Field_Width(), ConfigWidget::Goal_Depth(), and ConfigWidget::Goal_Width().
Referenced by generatePacket().
{
     const double kFieldLength = CONVUNIT(cfg->Field_Length());
     const double kFieldWidth = CONVUNIT(cfg->Field_Width());
     const double kGoalWidth = CONVUNIT(cfg->Goal_Width());
     const double kGoalDepth = CONVUNIT(cfg->Goal_Depth());
     const double kBoundaryWidth = CONVUNIT(cfg->Field_Referee_Margin());
     const double kCenterRadius = CONVUNIT(cfg->Field_Rad());
     const double kDefenseRadius = CONVUNIT(cfg->Field_Defense_Rad());
     const double kDefenseStretch = CONVUNIT(cfg->Field_Defense_Stretch());
     const double kLineThickness = CONVUNIT(cfg->Field_Line_Width());
     const double kXMax = (kFieldLength-2*kLineThickness)/2;
     const double kXMin = -kXMax;
     const double kYMax = (kFieldWidth-kLineThickness)/2;
     const double kYMin = -kYMax;
     // Field lines
     addFieldLine(field, "TopTouchLine", kXMin-kLineThickness/2, kYMax, kXMax+kLineThickness/2, kYMax, kLineThickness);
     addFieldLine(field, "BottomTouchLine", kXMin-kLineThickness/2, kYMin, kXMax+kLineThickness/2, kYMin, kLineThickness);
     addFieldLine(field, "LeftGoalLine", kXMin, kYMin, kXMin, kYMax, kLineThickness);
     addFieldLine(field, "RightGoalLine", kXMax, kYMin, kXMax, kYMax, kLineThickness);
     addFieldLine(field, "HalfwayLine", 0, kYMin, 0, kYMax, kLineThickness);
     addFieldLine(field, "CenterLine", kXMin, 0, kXMax, 0, kLineThickness);
     addFieldLine(field, "LeftPenaltyStretch", kXMin+kDefenseRadius-kLineThickness/2, -kDefenseStretch/2, kXMin+kDefenseRadius-kLineThickness/2, kDefenseStretch/2, kLineThickness);
     addFieldLine(field, "RightPenaltyStretch", kXMax-kDefenseRadius+kLineThickness/2, -kDefenseStretch/2, kXMax-kDefenseRadius+kLineThickness/2, kDefenseStretch/2, kLineThickness);
     addFieldLine(field, "RightGoalTopLine", kXMax, kGoalWidth/2, kXMax+kGoalDepth, kGoalWidth/2, kLineThickness);
     addFieldLine(field, "RightGoalBottomLine", kXMax, -kGoalWidth/2, kXMax+kGoalDepth, -kGoalWidth/2, kLineThickness);
     addFieldLine(field, "RightGoalDepthLine", kXMax+kGoalDepth-kLineThickness/2, -kGoalWidth/2, kXMax+kGoalDepth-kLineThickness/2, kGoalWidth/2, kLineThickness);
     addFieldLine(field, "LeftGoalTopLine", -kXMax, kGoalWidth/2, -kXMax-kGoalDepth, kGoalWidth/2, kLineThickness);
     addFieldLine(field, "LeftGoalBottomLine", -kXMax, -kGoalWidth/2, -kXMax-kGoalDepth, -kGoalWidth/2, kLineThickness);
     addFieldLine(field, "LeftGoalDepthLine", -kXMax-kGoalDepth+kLineThickness/2, -kGoalWidth/2, -kXMax-kGoalDepth+kLineThickness/2, kGoalWidth/2, kLineThickness);
     // Field arcs
     addFieldArc(field, "LeftFieldLeftPenaltyArc",   kXMin, kDefenseStretch/2,  kDefenseRadius-kLineThickness/2, 0,        M_PI/2,   kLineThickness);
     addFieldArc(field, "LeftFieldRightPenaltyArc",  kXMin, -kDefenseStretch/2, kDefenseRadius-kLineThickness/2, 1.5*M_PI, 2*M_PI,   kLineThickness);
     addFieldArc(field, "RightFieldLeftPenaltyArc",  kXMax, -kDefenseStretch/2, kDefenseRadius-kLineThickness/2, M_PI,     1.5*M_PI, kLineThickness);
     addFieldArc(field, "RightFieldRightPenaltyArc", kXMax, kDefenseStretch/2,  kDefenseRadius-kLineThickness/2, M_PI/2,   M_PI,     kLineThickness);
     addFieldArc(field, "CenterCircle",              0,     0,                  kCenterRadius-kLineThickness/2,  0,        2*M_PI,   kLineThickness);
 }
Vector2f * SSLWorld::allocVector (float x, float y)
Definition at line 763 of file sslworld.cpp.
{
     Vector2f *vec = new Vector2f();
     vec->set_x(x);
     vec->set_y(y);
     return vec;
 }
void SSLWorld::fpsChanged (int newFPS) signal
SSL_WrapperPacket * SSLWorld::generatePacket (int cam_id = 0)
Definition at line 626 of file sslworld.cpp.
References addFieldLinesArcs(), ball, ConfigWidget::ball_vanishing(), ConfigWidget::blue_team_vanishing(), cfg, CONVUNIT, ConfigWidget::Field_Length(), ConfigWidget::Field_Margin(), ConfigWidget::Field_Width(), framenum, PObject::getBodyPosition(), Robot::getDir(), Robot::getXY(), ConfigWidget::Goal_Depth(), ConfigWidget::Goal_Width(), velocity.pid_::i, ConfigWidget::noise(), ConfigWidget::noiseDeviation_angle(), ConfigWidget::noiseDeviation_x(), ConfigWidget::noiseDeviation_y(), normalizeAngle(), packet, rand0_1(), randn_notrig(), ROBOT_COUNT, robots, sendGeomCount, ConfigWidget::sendGeometryEvery(), timer, ConfigWidget::vanishing(), visibleInCam(), role._GoToPoint::x, role._GoToPoint::y, and ConfigWidget::yellow_team_vanishing().
Referenced by sendVisionBuffer().
 {
     SSL_WrapperPacket* packet = new SSL_WrapperPacket;
     dReal x,y,z,dir;
     ball->getBodyPosition(x,y,z);
     packet->mutable_detection()->set_camera_id(cam_id);
     packet->mutable_detection()->set_frame_number(framenum);
     dReal t_elapsed = timer->elapsed()/1000.0;
     packet->mutable_detection()->set_t_capture(t_elapsed);
     packet->mutable_detection()->set_t_sent(t_elapsed);
     dReal dev_x = cfg->noiseDeviation_x();
     dReal dev_y = cfg->noiseDeviation_y();
     dReal dev_a = cfg->noiseDeviation_angle();
     if (sendGeomCount++ % cfg->sendGeometryEvery() == 0)
     {
         SSL_GeometryData* geom = packet->mutable_geometry();
         SSL_GeometryFieldSize* field = geom->mutable_field();
         // Old protocol
 //        field->set_line_width(CONVUNIT(cfg->Field_Line_Width()));
 //        field->set_referee_width(CONVUNIT(cfg->Field_Referee_Margin()));
 //        field->set_goal_wall_width(CONVUNIT(cfg->Goal_Thickness()));
 //        field->set_center_circle_radius(CONVUNIT(cfg->Field_Rad()));
 //        field->set_defense_radius(CONVUNIT(cfg->Field_Defense_Rad()));
 //        field->set_defense_stretch(CONVUNIT(cfg->Field_Defense_Stretch()));
 //        field->set_free_kick_from_defense_dist(CONVUNIT(cfg->Field_Free_Kick()));
         //TODO: verify if these fields are correct:
 //        field->set_penalty_line_from_spot_dist(CONVUNIT(cfg->Field_Penalty_Line()));
 //        field->set_penalty_spot_from_field_line_dist(CONVUNIT(cfg->Field_Penalty_Point()));
         // Current protocol (2015+)
         // Field general info
         field->set_field_length(CONVUNIT(cfg->Field_Length()));
         field->set_field_width(CONVUNIT(cfg->Field_Width()));
         field->set_boundary_width(CONVUNIT(cfg->Field_Margin()));
         field->set_goal_width(CONVUNIT(cfg->Goal_Width()));
         field->set_goal_depth(CONVUNIT(cfg->Goal_Depth()));
         // Field lines and arcs
         addFieldLinesArcs(field);
     }
     if (cfg->noise()==false) {dev_x = 0;dev_y = 0;dev_a = 0;}
     if ((cfg->vanishing()==false) || (rand0_1() > cfg->ball_vanishing()))
     {
         if (visibleInCam(cam_id, x, y)) {
             SSL_DetectionBall* vball = packet->mutable_detection()->add_balls();
             vball->set_x(randn_notrig(x*1000.0f,dev_x));
             vball->set_y(randn_notrig(y*1000.0f,dev_y));
             vball->set_z(z*1000.0f);
             vball->set_pixel_x(x*1000.0f);
             vball->set_pixel_y(y*1000.0f);
             vball->set_confidence(0.9 + rand0_1()*0.1);
         }
     }
     for(int i = 0; i < ROBOT_COUNT; i++){
         if ((cfg->vanishing()==false) || (rand0_1() > cfg->blue_team_vanishing()))
         {
             if (!robots[i]->on) continue;
             robots[i]->getXY(x,y);
             dir = robots[i]->getDir();
             if (visibleInCam(cam_id, x, y)) {
                 SSL_DetectionRobot* rob = packet->mutable_detection()->add_robots_blue();
                 rob->set_robot_id(i);
                 rob->set_pixel_x(x*1000.0f);
                 rob->set_pixel_y(y*1000.0f);
                 rob->set_confidence(1);
                 rob->set_x(randn_notrig(x*1000.0f,dev_x));
                 rob->set_y(randn_notrig(y*1000.0f,dev_y));
                 rob->set_orientation(normalizeAngle(randn_notrig(dir,dev_a))*M_PI/180.0f);
             }
         }
     }
     for(int i = ROBOT_COUNT; i < ROBOT_COUNT*2; i++){
         if ((cfg->vanishing()==false) || (rand0_1() > cfg->yellow_team_vanishing()))
         {
             if (!robots[i]->on) continue;
             robots[i]->getXY(x,y);
             dir = robots[i]->getDir();
             if (visibleInCam(cam_id, x, y)) {
                 SSL_DetectionRobot* rob = packet->mutable_detection()->add_robots_yellow();
                 rob->set_robot_id(i-ROBOT_COUNT);
                 rob->set_pixel_x(x*1000.0f);
                 rob->set_pixel_y(y*1000.0f);
                 rob->set_confidence(1);
                 rob->set_x(randn_notrig(x*1000.0f,dev_x));
                 rob->set_y(randn_notrig(y*1000.0f,dev_y));
                 rob->set_orientation(normalizeAngle(randn_notrig(dir,dev_a))*M_PI/180.0f);
             }
         }
     }
     return packet;
 }
void SSLWorld::glinit ()
Definition at line 343 of file sslworld.cpp.
References createBlob(), createNumber(), g, PWorld::glinit(), velocity.pid_::i, CGraphics::loadTexture(), p, ROBOT_COUNT, and robots.
Referenced by GLWidget::initializeGL(), and MainWindow::restartSimulator().
 {
     g->loadTexture(new QImage(":/grass.png"));
     // Loading Robot textures for each robot
     for (int i = 0; i < ROBOT_COUNT; i++)
         g->loadTexture(createBlob('b', i, &robots[i]->img));
     for (int i = 0; i < ROBOT_COUNT; i++)
         g->loadTexture(createBlob('y', i, &robots[ROBOT_COUNT + i]->img));
     // Creating number textures
     for (int i=0; i<ROBOT_COUNT;i++)
         g->loadTexture(createNumber(i,15,193,225,255));
     for (int i=0; i<ROBOT_COUNT;i++)
         g->loadTexture(createNumber(i,0xff,0xff,0,255));
     // Loading sky textures
     // XXX: for some reason they are loaded twice otherwise the wheel texture is wrong
     for (int i=0; i<6; i++) {
         g->loadTexture(new QImage(QString(":/sky/neg_%1").arg(i%3==0?'x':i%3==1?'y':'z')+QString(".png")));
         g->loadTexture(new QImage(QString(":/sky/pos_%1").arg(i%3==0?'x':i%3==1?'y':'z')+QString(".png")));
     }
     // The wheel texture
     g->loadTexture(new QImage(":/wheel.png"));
     // Init at last
     p->glinit();
 }
void SSLWorld::recvActions () slot
Definition at line 480 of file sslworld.cpp.
References ball, ConfigWidget::BallRadius(), ConfigWidget::BlueStatusSendPort(), blueStatusSocket, PObject::body, cfg, commandSocket, velocity.pid_::i, in_buffer, k, Robot::Kicker::kick(), Robot::kicker, Robot::on, packet, port(), Robot::resetRobot(), ROBOT_COUNT, robotIndex(), robots, PObject::setBodyPosition(), Robot::setDir(), Robot::Kicker::setRoller(), Robot::setSpeed(), Robot::setXY(), role._GoToPoint::x, role._GoToPoint::y, ConfigWidget::YellowStatusSendPort(), and yellowStatusSocket.
Referenced by MainWindow::recvActions().
 {
     QHostAddress sender;
     quint16 port;
     grSim_Packet packet;
     while (commandSocket->hasPendingDatagrams())
     {
         int size = commandSocket->readDatagram(in_buffer, 65536, &sender, &port);
         if (size > 0)
         {
             packet.ParseFromArray(in_buffer, size);
             int team=0;
             if (packet.has_commands())
             {
                 if (packet.commands().has_isteamyellow())
                 {
                     if (packet.commands().isteamyellow()) team=1;
                 }
                 for (int i=0;i<packet.commands().robot_commands_size();i++)
                 {
                     if (!packet.commands().robot_commands(i).has_id()) continue;
                     int k = packet.commands().robot_commands(i).id();
                     int id = robotIndex(k, team);
                     if ((id < 0) || (id >= ROBOT_COUNT*2)) continue;
                     bool wheels = false;
                     if (packet.commands().robot_commands(i).has_wheelsspeed())
                     {
                         if (packet.commands().robot_commands(i).wheelsspeed()==true)
{
                             if (packet.commands().robot_commands(i).has_wheel1()) robots[id]->setSpeed(0, packet.commands().robot_commands(i).wheel1());
                             if (packet.commands().robot_commands(i).has_wheel2()) robots[id]->setSpeed(1, packet.commands().robot_commands(i).wheel2());
                             if (packet.commands().robot_commands(i).has_wheel3()) robots[id]->setSpeed(2, packet.commands().robot_commands(i).wheel3());
                             if (packet.commands().robot_commands(i).has_wheel4()) robots[id]->setSpeed(3, packet.commands().robot_commands(i).wheel4());
                             wheels = true;
                         }
                     }
                     if (!wheels)
                     {
                         dReal vx = 0;if (packet.commands().robot_commands(i).has_veltangent()) vx = packet.commands().robot_commands(i).veltangent();
                         dReal vy = 0;if (packet.commands().robot_commands(i).has_velnormal())  vy = packet.commands().robot_commands(i).velnormal();
                         dReal vw = 0;if (packet.commands().robot_commands(i).has_velangular()) vw = packet.commands().robot_commands(i).velangular();
                         robots[id]->setSpeed(vx, vy, vw);
                     }
                     dReal kickx = 0 , kickz = 0;
                     bool kick = false;
                     if (packet.commands().robot_commands(i).has_kickspeedx())
                     {
                         kick = true;
                         kickx = packet.commands().robot_commands(i).kickspeedx();
                     }
                     if (packet.commands().robot_commands(i).has_kickspeedz())
                     {
                         kick = true;
                         kickz = packet.commands().robot_commands(i).kickspeedz();
                     }
                     if (kick && ((kickx>0.0001) || (kickz>0.0001)))
                         robots[id]->kicker->kick(kickx,kickz);
                     int rolling = 0;
                     if (packet.commands().robot_commands(i).has_spinner())
                     {
                         if (packet.commands().robot_commands(i).spinner()) rolling = 1;
                     }
                     robots[id]->kicker->setRoller(rolling);
                     char status = 0;
                     status = k;
                     if (robots[id]->kicker->isTouchingBall()) status = status | 8;
                     if (robots[id]->on) status = status | 240;
                     if (team == 0)
                         blueStatusSocket->writeDatagram(&status,1,sender,cfg->BlueStatusSendPort());
                     else
                         yellowStatusSocket->writeDatagram(&status,1,sender,cfg->YellowStatusSendPort());
                 }
             }
             if (packet.has_replacement())
             {
                 for (int i=0;i<packet.replacement().robots_size();i++)
                 {
                     int team = 0;
                     if (packet.replacement().robots(i).has_yellowteam())
                     {
                         if (packet.replacement().robots(i).yellowteam())
                             team = 1;
                     }
                     if (!packet.replacement().robots(i).has_id()) continue;
                     int k = packet.replacement().robots(i).id();
                     dReal x = 0, y = 0, dir = 0;
                     bool turnon = true;
                     if (packet.replacement().robots(i).has_x()) x = packet.replacement().robots(i).x();
                     if (packet.replacement().robots(i).has_y()) y = packet.replacement().robots(i).y();
                     if (packet.replacement().robots(i).has_dir()) dir = packet.replacement().robots(i).dir();
                     if (packet.replacement().robots(i).has_turnon()) turnon = packet.replacement().robots(i).turnon();
                     int id = robotIndex(k, team);
                     if ((id < 0) || (id >= ROBOT_COUNT*2)) continue;
                     robots[id]->setXY(x,y);
                     robots[id]->resetRobot();
                     robots[id]->setDir(dir);
                     robots[id]->on = turnon;
                 }
                 if (packet.replacement().has_ball())
                 {
                     dReal x = 0, y = 0, vx = 0, vy = 0;
                     if (packet.replacement().ball().has_x())  x  = packet.replacement().ball().x();
                     if (packet.replacement().ball().has_y())  y  = packet.replacement().ball().y();
                     if (packet.replacement().ball().has_vx()) vx = packet.replacement().ball().vx();
                     if (packet.replacement().ball().has_vy()) vy = packet.replacement().ball().vy();
                     ball->setBodyPosition(x,y,cfg->BallRadius()*1.2);
                     dBodySetLinearVel(ball->body,vx,vy,0);
                     dBodySetAngularVel(ball->body,0,0,0);
                 }
             }
         }
     }
 }
void SSLWorld::sendVisionBuffer ()
Definition at line 797 of file sslworld.cpp.
References cfg, generatePacket(), packet, RoboCupSSLServer::send(), ConfigWidget::sendDelay(), sendQueue, t, timer, and visionServer.
Referenced by step().
 {
     int t = timer->elapsed();
     sendQueue.push_back(new SendingPacket(generatePacket(0),t));
     sendQueue.push_back(new SendingPacket(generatePacket(1),t+1));
     sendQueue.push_back(new SendingPacket(generatePacket(2),t+2));
     sendQueue.push_back(new SendingPacket(generatePacket(3),t+3));
     while (t - sendQueue.front()->t>=cfg->sendDelay())
     {
         SSL_WrapperPacket *packet = sendQueue.front()->packet;
         delete sendQueue.front();
         sendQueue.pop_front();
         visionServer->send(*packet);
         delete packet;
         if (sendQueue.isEmpty()) break;
     }
 }
void SSLWorld::step (dReal dt = -1)
Definition at line 375 of file sslworld.cpp.
References ball, ConfigWidget::BallFriction(), ConfigWidget::BallMass(), ConfigWidget::BallRadius(), PObject::body, cfg, Robot::chassis, cursor_radius, cursor_x, cursor_y, customDT, CGraphics::disableGraphics(), GVector::dist(), PWorld::draw(), CGraphics::drawCircle(), CGraphics::drawSkybox(), velocity.pid::dt, CGraphics::enableGraphics(), CGraphics::finalizeScene(), framenum, g, PObject::getBodyPosition(), CGraphics::getViewpoint(), ConfigWidget::Gravity(), CGraphics::initScene(), isGLEnabled, CGraphics::isGraphicsEnabled(), k, last_dt, m_parent, p, ROBOT_COUNT, ROBOT_GRAY, robots, Robot::select_x, Robot::select_y, Robot::select_z, Robot::selected, selected, sendVisionBuffer(), PObject::setColor(), CGraphics::setColor(), show3DCursor, PWorld::step(), Robot::step(), and PObject::tag.
Referenced by GLWidget::step().
 {
     if (!isGLEnabled) g->disableGraphics();
     else g->enableGraphics();
     if (customDT > 0)
         dt = customDT;
     g->initScene(m_parent->width(),m_parent->height(),0,0.7,1);//true,0.7,0.7,0.7,0.8);
     for (int kk=0;kk<5;kk++)
     {
         const dReal* ballvel = dBodyGetLinearVel(ball->body);
         dReal ballspeed = ballvel[0]*ballvel[0] + ballvel[1]*ballvel[1] + ballvel[2]*ballvel[2];
         ballspeed = sqrt(ballspeed);
         dReal ballfx=0,ballfy=0,ballfz=0;
         dReal balltx=0,ballty=0,balltz=0;
         if (ballspeed<0.01)
         {
             ;//const dReal* ballAngVel = dBodyGetAngularVel(ball->body);
             //TODO: what was supposed to be here?
         }
         else {
             dReal fk = cfg->BallFriction()*cfg->BallMass()*cfg->Gravity();
             ballfx = -fk*ballvel[0] / ballspeed;
             ballfy = -fk*ballvel[1] / ballspeed;
             ballfz = -fk*ballvel[2] / ballspeed;
             balltx = -ballfy*cfg->BallRadius();
             ballty = ballfx*cfg->BallRadius();
             balltz = 0;
             dBodyAddTorque(ball->body,balltx,ballty,balltz);
         }
         dBodyAddForce(ball->body,ballfx,ballfy,ballfz);
         if (dt==0) dt=last_dt;
         else last_dt = dt;
         selected = -1;
         p->step(dt*0.2);
     }
     int best_k=-1;
     dReal best_dist = 1e8;
     dReal xyz[3],hpr[3];
     if (selected==-2) {
         best_k=-2;
         dReal bx,by,bz;
         ball->getBodyPosition(bx,by,bz);
         g->getViewpoint(xyz,hpr);
         best_dist  =(bx-xyz[0])*(bx-xyz[0])
                 +(by-xyz[1])*(by-xyz[1])
                 +(bz-xyz[2])*(bz-xyz[2]);
     }
     for (int k=0;k<ROBOT_COUNT * 2;k++)
     {
         if (robots[k]->selected)
         {
             g->getViewpoint(xyz,hpr);
             dReal dist= (robots[k]->select_x-xyz[0])*(robots[k]->select_x-xyz[0])
                     +(robots[k]->select_y-xyz[1])*(robots[k]->select_y-xyz[1])
                     +(robots[k]->select_z-xyz[2])*(robots[k]->select_z-xyz[2]);
             if (dist<best_dist) {
                 best_dist = dist;
                 best_k = k;
             }
         }
         robots[k]->chassis->setColor(ROBOT_GRAY,ROBOT_GRAY,ROBOT_GRAY);
     }
     if (best_k>=0) robots[best_k]->chassis->setColor(ROBOT_GRAY*2,ROBOT_GRAY*1.5,ROBOT_GRAY*1.5);
     selected = best_k;
     ball->tag = -1;
     for (int k=0;k<ROBOT_COUNT * 2;k++)
     {
         robots[k]->step();
         robots[k]->selected = false;
     }
     p->draw();
     //g->drawSkybox(31,32,33,34,35,36);
     g->drawSkybox(4 * ROBOT_COUNT + 6 + 1, //31 for 6 robot
                   4 * ROBOT_COUNT + 6 + 2, //32 for 6 robot
                   4 * ROBOT_COUNT + 6 + 3, //33 for 6 robot
                   4 * ROBOT_COUNT + 6 + 4, //34 for 6 robot
                   4 * ROBOT_COUNT + 6 + 5, //31 for 6 robot
                   4 * ROBOT_COUNT + 6 + 6);//36 for 6 robot
     dMatrix3 R;
     if (g->isGraphicsEnabled())
         if (show3DCursor)
         {
             dRFromAxisAndAngle(R,0,0,1,0);
             g->setColor(1,0.9,0.2,0.5);
             glEnable(GL_BLEND);
             glBlendFunc(GL_SRC_ALPHA,GL_ONE_MINUS_SRC_ALPHA);
             g->drawCircle(cursor_x,cursor_y,0.001,cursor_radius);
             glDisable(GL_BLEND);
         }
     //for (int k=0;k<10;k++) robots[k]->drawLabel();
     g->finalizeScene();
     sendVisionBuffer();
     framenum ++;
 }
bool SSLWorld::visibleInCam (int id, double x, double y)
Definition at line 603 of file sslworld.cpp.
Referenced by generatePacket().
 {
     id %= 4;
     if (id==0)
     {
         if (x>-0.2 && y>-0.2) return true;
     }
     if (id==1)
     {
         if (x>-0.2 && y<0.2) return true;
     }
     if (id==2)
     {
         if (x<0.2 && y<0.2) return true;
     }
     if (id==3)
     {
         if (x<0.2 && y>-0.2) return true;
     }
     return false;
 }
Field Documentation
PBall* SSLWorld::ball
Definition at line 80 of file sslworld.h.
Referenced by ballCallBack(), MainWindow::changeBallDamping(), MainWindow::changeBallGroundSurface(), MainWindow::changeBallMass(), generatePacket(), GLWidget::keyPressEvent(), GLWidget::mousePressEvent(), GLWidget::moveBallHere(), GLWidget::paintGL(), GLWidget::putBall(), rayCallback(), recvActions(), SSLWorld(), GLWidget::step(), and step().
QUdpSocket* SSLWorld::blueStatusSocket
Definition at line 90 of file sslworld.h.
Referenced by MainWindow::customFPS(), recvActions(), and MainWindow::restartSimulator().
ConfigWidget* SSLWorld::cfg
Definition at line 77 of file sslworld.h.
Referenced by addFieldLinesArcs(), ballCallBack(), generatePacket(), recvActions(), sendVisionBuffer(), SSLWorld(), step(), and wheelCallBack().
QUdpSocket* SSLWorld::commandSocket
Definition at line 89 of file sslworld.h.
Referenced by MainWindow::customFPS(), recvActions(), and MainWindow::restartSimulator().
dReal SSLWorld::cursor_radius
Definition at line 87 of file sslworld.h.
Referenced by GLWidget::moveBall(), GLWidget::moveCurrentRobot(), GLWidget::moveRobot(), step(), and GLWidget::unselectRobot().
dReal SSLWorld::cursor_x
Definition at line 86 of file sslworld.h.
Referenced by GLWidget::mousePressEvent(), GLWidget::moveBallHere(), GLWidget::moveRobotHere(), rayCallback(), step(), and MainWindow::update().
dReal SSLWorld::cursor_y
Definition at line 86 of file sslworld.h.
Referenced by GLWidget::mousePressEvent(), GLWidget::moveBallHere(), GLWidget::moveRobotHere(), rayCallback(), step(), and MainWindow::update().
dReal SSLWorld::cursor_z
Definition at line 86 of file sslworld.h.
Referenced by rayCallback(), and MainWindow::update().
dReal SSLWorld::customDT
Definition at line 64 of file sslworld.h.
Referenced by SSLWorld(), and step().
int SSLWorld::framenum private
Definition at line 58 of file sslworld.h.
Referenced by generatePacket(), SSLWorld(), and step().
CGraphics* SSLWorld::g
Definition at line 78 of file sslworld.h.
Referenced by GLWidget::changeCameraMode(), glinit(), GLWidget::mouseMoveEvent(), GLWidget::mousePressEvent(), GLWidget::paintGL(), SSLWorld(), step(), MainWindow::update(), GLWidget::update3DCursor(), GLWidget::wheelEvent(), and ~SSLWorld().
PGround* SSLWorld::ground
Definition at line 81 of file sslworld.h.
Referenced by MainWindow::changeBallGroundSurface(), rayCallback(), and SSLWorld().
char* SSLWorld::in_buffer private
Definition at line 62 of file sslworld.h.
Referenced by recvActions(), and SSLWorld().
bool SSLWorld::isGLEnabled
Definition at line 65 of file sslworld.h.
Referenced by SSLWorld(), and step().
dReal SSLWorld::last_dt private
Definition at line 59 of file sslworld.h.
Referenced by SSLWorld(), and step().
QGLWidget* SSLWorld::m_parent private
Definition at line 57 of file sslworld.h.
Referenced by SSLWorld(), and step().
PWorld* SSLWorld::p
Definition at line 79 of file sslworld.h.
Referenced by MainWindow::changeBallGroundSurface(), MainWindow::changeGravity(), createNumber(), glinit(), SSLWorld(), step(), and ~SSLWorld().
char SSLWorld::packet[200] private
Definition at line 61 of file sslworld.h.
Referenced by generatePacket(), recvActions(), SendingPacket::SendingPacket(), and sendVisionBuffer().
PRay* SSLWorld::ray
Definition at line 82 of file sslworld.h.
Referenced by rayCallback(), SSLWorld(), and GLWidget::update3DCursor().
Robot* SSLWorld::robots[12 *2]
Definition at line 92 of file sslworld.h.
Referenced by ballCallBack(), MainWindow::changeCurrentRobot(), MainWindow::changeCurrentTeam(), MainWindow::customFPS(), generatePacket(), glinit(), GLWidget::keyPressEvent(), GLWidget::mousePressEvent(), GLWidget::moveRobotHere(), GLWidget::paintGL(), rayCallback(), recvActions(), GLWidget::reform(), GLWidget::resetCurrentRobot(), GLWidget::resetRobot(), MainWindow::setCurrentRobotPosition(), SSLWorld(), step(), GLWidget::switchRobotOnOff(), MainWindow::update(), and MainWindow::updateRobotLabel().
int SSLWorld::selected
Definition at line 84 of file sslworld.h.
Referenced by GLWidget::mousePressEvent(), rayCallback(), step(), and MainWindow::update().
int SSLWorld::sendGeomCount
Definition at line 94 of file sslworld.h.
Referenced by generatePacket(), and SSLWorld().
QList<SendingPacket*> SSLWorld::sendQueue private
Definition at line 60 of file sslworld.h.
Referenced by sendVisionBuffer().
bool SSLWorld::show3DCursor
Definition at line 85 of file sslworld.h.
Referenced by GLWidget::keyReleaseEvent(), GLWidget::mousePressEvent(), GLWidget::moveBall(), GLWidget::moveCurrentRobot(), GLWidget::moveRobot(), SSLWorld(), step(), and GLWidget::unselectRobot().
QTime* SSLWorld::timer
Definition at line 93 of file sslworld.h.
Referenced by generatePacket(), sendVisionBuffer(), and SSLWorld().
bool SSLWorld::updatedCursor
Definition at line 91 of file sslworld.h.
Referenced by rayCallback(), SSLWorld(), and GLWidget::update3DCursor().
RoboCupSSLServer* SSLWorld::visionServer
Definition at line 88 of file sslworld.h.
Referenced by MainWindow::customFPS(), MainWindow::restartSimulator(), and sendVisionBuffer().
PFixedBox* SSLWorld::walls[10]
Definition at line 83 of file sslworld.h.
Referenced by SSLWorld().
QUdpSocket * SSLWorld::yellowStatusSocket
Definition at line 90 of file sslworld.h.
Referenced by MainWindow::customFPS(), recvActions(), and MainWindow::restartSimulator().
The documentation for this class was generated from the following files:
grSim/include/sslworld.h
grSim/src/sslworld.cpp