Documentation: Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder Interface Reference
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder Interface Reference
Public Member Functions
boolean hasLineWidth ()
int getLineWidth ()
boolean hasFieldLength ()
int getFieldLength ()
boolean hasFieldWidth ()
int getFieldWidth ()
boolean hasBoundaryWidth ()
int getBoundaryWidth ()
boolean hasRefereeWidth ()
int getRefereeWidth ()
boolean hasGoalWidth ()
int getGoalWidth ()
boolean hasGoalDepth ()
int getGoalDepth ()
boolean hasGoalWallWidth ()
int getGoalWallWidth ()
boolean hasCenterCircleRadius ()
int getCenterCircleRadius ()
boolean hasDefenseRadius ()
int getDefenseRadius ()
boolean hasDefenseStretch ()
int getDefenseStretch ()
boolean hasFreeKickFromDefenseDist ()
int getFreeKickFromDefenseDist ()
boolean hasPenaltySpotFromFieldLineDist ()
int getPenaltySpotFromFieldLineDist ()
boolean hasPenaltyLineFromSpotDist ()
int getPenaltyLineFromSpotDist ()
Detailed Description
Definition at line 11 of file MessagesRobocupSslGeometry.java.
Member Function Documentation
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getBoundaryWidth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getCenterCircleRadius ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getDefenseRadius ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getDefenseStretch ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getFieldLength ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getFieldWidth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getFreeKickFromDefenseDist ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getGoalDepth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getGoalWallWidth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getGoalWidth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getLineWidth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getPenaltyLineFromSpotDist ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getPenaltySpotFromFieldLineDist ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.getRefereeWidth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasBoundaryWidth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasCenterCircleRadius ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasDefenseRadius ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasDefenseStretch ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasFieldLength ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasFieldWidth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasFreeKickFromDefenseDist ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasGoalDepth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasGoalWallWidth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasGoalWidth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasLineWidth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasPenaltyLineFromSpotDist ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasPenaltySpotFromFieldLineDist ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasRefereeWidth ()
Implemented in Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder, and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.isInitialized().
The documentation for this interface was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslGeometry.java