Documentation: anonymous_namespace{grSim_Commands.pb.cc} Namespace Reference
anonymous_namespace{grSim_Commands.pb.cc} Namespace Reference
Functions
void protobuf_AssignDescriptors ()
void protobuf_AssignDescriptorsOnce ()
void protobuf_RegisterTypes (const ::std::string &) GOOGLE_ATTRIBUTE_COLD
Variables
::google::protobuf::Metadata file_level_metadata [2]
Function Documentation
void anonymous_namespace{grSim_Commands.pb.cc}::protobuf_AssignDescriptors ()
Definition at line 88 of file grSim_Commands.pb.cc.
References file_default_instances, file_level_metadata, protobuf_AddDesc_grSim_5fCommands_2eproto(), protobuf_Offsets_grSim_5fCommands_2eproto(), and schemas.
Referenced by protobuf_AssignDescriptorsOnce().
{
   protobuf_AddDesc_grSim_5fCommands_2eproto();
   ::google::protobuf::MessageFactory* factory = NULL;
   AssignDescriptors(
       "grSim_Commands.proto", schemas, file_default_instances, protobuf_Offsets_grSim_5fCommands_2eproto(), factory,
       file_level_metadata, NULL, NULL);
 }
void anonymous_namespace{grSim_Commands.pb.cc}::protobuf_AssignDescriptorsOnce ()
Definition at line 96 of file grSim_Commands.pb.cc.
References GOOGLE_PROTOBUF_DECLARE_ONCE(), protobuf_AssignDescriptors(), and protobuf_RegisterTypes().
Referenced by grSim_Robot_Command::descriptor(), grSim_Commands::descriptor(), grSim_Robot_Command::GetMetadata(), grSim_Commands::GetMetadata(), and protobuf_RegisterTypes().
{
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
   ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
 }
void anonymous_namespace{grSim_Commands.pb.cc}::protobuf_RegisterTypes (const ::std::string &)
Definition at line 102 of file grSim_Commands.pb.cc.
References file_level_metadata, and protobuf_AssignDescriptorsOnce().
Referenced by protobuf_AddDesc_grSim_5fCommands_2eproto_impl(), and protobuf_AssignDescriptorsOnce().
{
   protobuf_AssignDescriptorsOnce();
   ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
 }
Variable Documentation
::google::protobuf::Metadata anonymous_namespace{grSim_Commands.pb.cc}::file_level_metadata[2]
Definition at line 26 of file grSim_Commands.pb.cc.
Referenced by grSim_Robot_Command::descriptor(), grSim_Commands::descriptor(), grSim_Robot_Command::GetMetadata(), grSim_Commands::GetMetadata(), protobuf_AssignDescriptors(), protobuf_RegisterTypes(), and protobuf_ShutdownFile_grSim_5fCommands_2eproto().