Documentation: YUVLUT Class Reference
YUVLUT Class Reference
A 3D YUV LUT.
#include <lut3d.h>
Public Member Functions
YUVLUT (unsigned int y_bits=4, unsigned int u_bits=5, unsigned int v_bits=5, string filename="yuvlut.xml")
virtual void deriveFromLUT (LUT3D *lut)
virtual void computeLUTfromLabels (int max_dist=0)
This will clear the LUT and create a new LUT-dataset modeling a NN-lookup based solely on color labels.
virtual ColorSpace getColorSpace () const
Public Member Functions inherited from LUT3D
LUT3D (unsigned int x_bits=7, unsigned int y_bits=7, unsigned int z_bits=7, string filename="3dlut.xml")
void lock ()
void unlock ()
VarList * getSettings ()
LUTChannel getChannel (unsigned int idx) const
void clearDerivedLUTs (bool unallocate_derived_memory=true)
int getDerivedLUTcount ()
LUT3D * getDerivedLUT (int idx)
void addDerivedLUT (LUT3D *lut)
LUT3D * getDerivedLUT (ColorSpace space)
void updateDerivedLUTs ()
int getChannelID (const string &label) const
void setChannel (unsigned int idx, LUTChannel c)
int getChannelCount () const
int getSizeX () const
int getSizeY () const
int getSizeZ () const
int getMaxX () const
int getMaxY () const
int getMaxZ () const
virtual ~LUT3D ()
void reset ()
lut_mask_t * getTable () const
lut_mask_t * getPointer (unsigned char x, unsigned char y, unsigned char z) const
lut_mask_t * getPointerPreshrunk (unsigned char x, unsigned char y, unsigned char z) const
unsigned char norm2lutX (unsigned char x) const
unsigned char norm2lutY (unsigned char y) const
unsigned char norm2lutZ (unsigned char z) const
unsigned char lut2normX (unsigned char x) const
unsigned char lut2normY (unsigned char y) const
unsigned char lut2normZ (unsigned char z) const
void set (unsigned char x, unsigned char y, unsigned char z, lut_mask_t mask)
void set_preshrunk (unsigned char x, unsigned char y, unsigned char z, lut_mask_t mask)
lut_mask_t get (const unsigned char x, const unsigned char y, const unsigned char z)
lut_mask_t get_preshrunk (const unsigned char x, const unsigned char y, const unsigned char z)
void copyChannels (const LUT3D &other)
void loadRoboCupChannels (LUTChannelMode mode)
void loadBlackWhite (LUTChannelMode mode)
void maskFillYZ (unsigned char slice_x, unsigned char origin_y, unsigned char origin_z, lut_mask_t new_color, LUTChannelMode mode, bool remove=false, bool check_exact=true, bool write_exclusive=false)
Additional Inherited Members
Data Fields inherited from LUT3D
unsigned int X_BITS
unsigned int Y_BITS
unsigned int Z_BITS
unsigned int X_SHIFT
unsigned int Y_SHIFT
unsigned int Z_SHIFT
unsigned int Y_SHIFT_PLUS_8
unsigned int Z_SHIFT_PLUS_16
unsigned int Z_AND_Y_BITS
unsigned int TOTAL_BITS
unsigned int LUT_SIZE
lut_mask_t * LUT
VarBlob * v_blob
VarList * v_settings
vector< LUTChannel > channels
vector< LUT3D * > derived_LUTs
QMutex mutex
Protected Slots inherited from LUT3D
void slotVBlobChange ()
Detailed Description
A 3D YUV LUT.
Author
Stefan Zickler
Definition at line 527 of file lut3d.h.
Constructor & Destructor Documentation
YUVLUT::YUVLUT (unsigned int y_bits = 4, unsigned int u_bits = 5, unsigned int v_bits = 5, string filename = "yuvlut.xml") inline
Definition at line 529 of file lut3d.h.
 : LUT3D(y_bits, u_bits, v_bits,filename) {};
Member Function Documentation
virtual void YUVLUT::computeLUTfromLabels (int max_dist = 0) inline virtual
This will clear the LUT and create a new LUT-dataset modeling a NN-lookup based solely on color labels.
Definition at line 560 of file lut3d.h.
References GVector::dist(), velocity.pid_::i, Conversions::rgb2yuv(), sq(), ColorYUV< num, fmt >::u, v, ColorYUV< num, fmt >::v, role._GoToPoint::y, and ColorYUV< num, fmt >::y.
Referenced by CMPattern::TeamDetector::init().
{
     this->lock();
     long max_dist_sq=max_dist * max_dist;
     int cn=channels.size();
     long best_dist=0;
     int best_idx=0;
     yuv l;
     for (int y=0;y<=getMaxX();y++) {
       for (int u=0;u<=getMaxY();u++) {
         for (int v=0;v<=getMaxZ();v++) {
           best_idx=0;
           best_dist=0;
           for (int i = 1; i <cn; i++) {
               l = Conversions::rgb2yuv(channels[i].draw_color);
               long dist=(sq( lut2normX(y)-l.y)+sq(lut2normY(u)-l.u)+sq(lut2normZ(v)-l.v));
               if (i==1 || (dist < best_dist)) {
                 best_dist=dist;
                 best_idx=i;
               }
               if (max_dist_sq!=0 && best_dist > max_dist_sq) {
                 best_idx=0;
               }
           }
             //Conversions::yuv2rgb(y,u,v,r,g,b);
           set_preshrunk((unsigned char)y,(unsigned char)u,(unsigned char)v,best_idx);
         }
       }
     }
     this->unlock();
   }
virtual void YUVLUT::deriveFromLUT (LUT3D * lut) inline virtual
Reimplemented from LUT3D.
Definition at line 531 of file lut3d.h.
References CSPACE_RGB, LUT3D::get(), LUT3D::getColorSpace(), v, role._GoToPoint::y, and Conversions::yuv2rgb().
{
     if (lut->getColorSpace()!=CSPACE_RGB) {
       fprintf(stderr,"Warning: deriveFromLUT input on YUVLUT does not seem to be in RGB color-space\n");
     } else {
       /*int r,g,b;
       for (int y=0;y<=255;y++) {
         for (int u=0;u<=255;u++) {
           for (int v=0;v<=255;v++) {
             Conversions::yuv2rgb(y,u,v,r,g,b);
             set((unsigned char)y,(unsigned char)u,(unsigned char)v,lut->get((unsigned char)r,(unsigned char)g,(unsigned char)b));
           }
         }
       }*/
       int r,g,b;
       int yn=this->getSizeX();
       int un=this->getSizeY();
       int vn=this->getSizeZ();
       for (int y=0;y!=yn;y++) {
         for (int u=0;u!=un;u++) {
           for (int v=0;v!=vn;v++) {
             Conversions::yuv2rgb((int)lut2normX((unsigned char)y),(int)lut2normY((unsigned char)u),(int)lut2normZ((unsigned char)v),r,g,b);
             set_preshrunk((unsigned char)y,(unsigned char)u,(unsigned char)v,lut->get((unsigned char)r,(unsigned char)g,(unsigned char)b));
           }
         }
       }
     }
   }
virtual ColorSpace YUVLUT::getColorSpace () const inline virtual
Reimplemented from LUT3D.
Definition at line 590 of file lut3d.h.
References CSPACE_YUV.
{
     return CSPACE_YUV;
   }
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/lut3d.h