Documentation: RawImage Class Reference
RawImage Class Reference
A class providing description and storage of raw image data.
#include <rawimage.h>
Public Member Functions
RawImage ()
~RawImage ()
int getWidth () const
int getHeight () const
ColorFormat getColorFormat () const
double getTime () const
unsigned char * getData () const
int getNumBytes () const
int getNumColorBlocks () const
int getNumPixels () const
void setColorFormat (ColorFormat f)
void setWidth (int w)
void setHeight (int h)
void setTime (double t)
void setData (unsigned char *d)
void allocate (ColorFormat fmt, int w, int h)
void ensure_allocation (ColorFormat fmt, int w, int h)
void deepCopyFromRawImage (const RawImage &img, bool copyMetaData)
void clear ()
Public Member Functions inherited from ImageInterface
virtual ~ImageInterface ()
Static Public Member Functions
static int computeImageSize (ColorFormat fmt, int pixelCount)
Protected Attributes
unsigned char * data
pointer to capture buffer
int width
width of the image in pixels
int height
height of the image in pixels
ColorFormat format
encoding format of the image
double time
capture timestamp of the image
Detailed Description
A class providing description and storage of raw image data.
Author
Stefan Zickler, (C) 2008
The RawImage class stores a pointer and basic meta-data (width, height, color-format, timestamp).
This class is mostly used for storing captured data. For an image class providing higher level processing functions, look at Image and its template instantiations rgbImage, rgbaImage, greyImage etc.
Definition at line 39 of file rawimage.h.
Constructor & Destructor Documentation
RawImage::RawImage ()
Definition at line 24 of file rawimage.cpp.
References COLOR_UNDEFINED, data, format, height, time, and width.
 {
   data=0;
   width=0;
   height=0;
   format=COLOR_UNDEFINED;
   time=0.0;
 }
RawImage::~RawImage ()
Definition at line 34 of file rawimage.cpp.
 {
 }
Member Function Documentation
void RawImage::allocate (ColorFormat fmt, int w, int h)
Definition at line 112 of file rawimage.cpp.
References computeImageSize(), data, format, height, and width.
Referenced by clear(), CaptureFlycap::convertFrame(), CaptureV4L::convertFrame(), CaptureDC1394v2::convertFrame(), CaptureGenerator::copyAndConvertFrame(), CaptureFromFile::copyAndConvertFrame(), CaptureBlueFox2::copyAndConvertFrame(), ensure_allocation(), and CaptureGenerator::getFrame().
 {
   if(w >= 0 && h >= 0) {
     if (data!=0) {
       delete[] data;
     }
     if (w==0 && h==0) {
       data=0;
     } else {
       data=new unsigned char[computeImageSize(fmt,w*h)];
     }
     width=w;
     height=h;
     format=fmt;
   }
 }
void RawImage::clear ()
Definition at line 145 of file rawimage.cpp.
References allocate(), and getColorFormat().
Referenced by CaptureV4L::~CaptureV4L().
 {
   allocate(getColorFormat(),0,0);
 };
int RawImage::computeImageSize (ColorFormat fmt, int pixelCount) static
Definition at line 150 of file rawimage.cpp.
References COLOR_MONO16, COLOR_MONO8, COLOR_RGB8, COLOR_RGBA8, COLOR_YUV411, COLOR_YUV422_UYVY, and COLOR_YUV444.
Referenced by allocate(), and getNumBytes().
 {
   switch (fmt) {
     case COLOR_RGB8: return pixelCount*3;
     case COLOR_RGBA8: return pixelCount*4;
     case COLOR_YUV444: return pixelCount*3;
     case COLOR_YUV422_UYVY: return pixelCount*2;
     case COLOR_YUV411: return pixelCount*3/2;
     case COLOR_MONO8: return pixelCount;
     case COLOR_MONO16: return pixelCount*2;
     default:
     return 0;
   }
 }
void RawImage::deepCopyFromRawImage (const RawImage & img, bool copyMetaData)
Definition at line 136 of file rawimage.cpp.
References ensure_allocation(), getColorFormat(), getData(), getHeight(), getNumBytes(), getWidth(), and time.
Referenced by PluginDVR::process().
 {
   ensure_allocation(img.getColorFormat(),img.getWidth(),img.getHeight());
   memcpy(getData(),img.getData(),img.getNumBytes());
   if (copyMetaData) {
     time=img.time;
   }
 }
void RawImage::ensure_allocation (ColorFormat fmt, int w, int h)
Definition at line 129 of file rawimage.cpp.
References allocate(), data, format, height, and width.
Referenced by CaptureFlycap::convertFrame(), CaptureV4L::convertFrame(), CaptureDC1394v2::convertFrame(), CaptureGenerator::copyAndConvertFrame(), CaptureFromFile::copyAndConvertFrame(), CaptureInterface::copyAndConvertFrame(), CaptureBlueFox2::copyAndConvertFrame(), deepCopyFromRawImage(), and CaptureV4L::getFrame().
 {
   if(data == 0 || format != fmt || width != w || height!=h) {
     allocate(fmt,w,h);
   }
 }
ColorFormat RawImage::getColorFormat () const virtual
Implements ImageInterface.
Definition at line 49 of file rawimage.cpp.
References format.
Referenced by clear(), CaptureFlycap::convertFrame(), CaptureV4L::convertFrame(), CaptureDC1394v2::convertFrame(), CaptureGenerator::copyAndConvertFrame(), CaptureFromFile::copyAndConvertFrame(), CaptureInterface::copyAndConvertFrame(), CaptureBlueFox2::copyAndConvertFrame(), CaptureFlycap::copyFrame(), CaptureV4L::copyFrame(), CaptureDC1394v2::copyFrame(), Image< rgb >::copyToRawImage(), deepCopyFromRawImage(), PluginCameraCalibration::detectEdges(), PluginVisualize::DrawCameraImage(), Image< rgb >::fromRawImage(), getNumColorBlocks(), PluginColorCalibration::mouseEvent(), PluginNeuralColorCalib::mouseEvent(), PluginColorThreshold::process(), GLLUTWidget::sampleImage(), PluginDVR::slotMovieSave(), and CMVisionThreshold::thresholdImageYUV422_UYVY().
 {
   return format;
 }
unsigned char * RawImage::getData () const virtual
Implements ImageInterface.
Definition at line 59 of file rawimage.cpp.
References data.
Referenced by GlobalV4Linstance::captureFrame(), CaptureFlycap::convertFrame(), CaptureV4L::convertFrame(), CaptureDC1394v2::convertFrame(), CaptureGenerator::copyAndConvertFrame(), CaptureFromFile::copyAndConvertFrame(), CaptureInterface::copyAndConvertFrame(), CaptureBlueFox2::copyAndConvertFrame(), Image< rgb >::copyToRawImage(), deepCopyFromRawImage(), PluginCameraCalibration::detectEdges(), PluginVisualize::DrawCameraImage(), Image< rgb >::fromRawImage(), CaptureV4L::getFrame(), PluginColorCalibration::mouseEvent(), PluginNeuralColorCalib::mouseEvent(), GLLUTWidget::sampleImage(), PluginDVR::slotMovieSave(), and CMVisionThreshold::thresholdImageYUV422_UYVY().
 {
   return data;
 }
int RawImage::getHeight () const virtual
Implements ImageInterface.
Definition at line 44 of file rawimage.cpp.
References height.
Referenced by GlobalV4Linstance::captureFrame(), CaptureFlycap::convertFrame(), CaptureV4L::convertFrame(), CaptureDC1394v2::convertFrame(), CaptureGenerator::copyAndConvertFrame(), CaptureFromFile::copyAndConvertFrame(), CaptureInterface::copyAndConvertFrame(), CaptureBlueFox2::copyAndConvertFrame(), deepCopyFromRawImage(), PluginCameraCalibration::detectEdges(), PluginVisualize::DrawCameraImage(), PluginVisualize::DrawSobelImage(), Image< rgb >::fromRawImage(), CaptureGenerator::getFrame(), PluginColorCalibration::mouseEvent(), PluginNeuralColorCalib::mouseEvent(), PluginColorThreshold::process(), PluginCameraCalibration::process(), PluginVisualize::process(), CMVision::ImageProcessor::processYUV422_UYVY(), GLLUTWidget::sampleImage(), PluginDVR::slotMovieSave(), and CMVisionThreshold::thresholdImageYUV422_UYVY().
 {
   return height;
 }
int RawImage::getNumBytes () const virtual
Implements ImageInterface.
Definition at line 69 of file rawimage.cpp.
References computeImageSize(), format, and getNumPixels().
Referenced by CaptureFlycap::convertFrame(), CaptureV4L::convertFrame(), CaptureDC1394v2::convertFrame(), CaptureGenerator::copyAndConvertFrame(), CaptureFromFile::copyAndConvertFrame(), CaptureInterface::copyAndConvertFrame(), CaptureBlueFox2::copyAndConvertFrame(), Image< rgb >::copyToRawImage(), deepCopyFromRawImage(), PluginVisualize::DrawCameraImage(), and PluginDVR::slotMovieSave().
 {
   return computeImageSize(format,getNumPixels());
 }
int RawImage::getNumColorBlocks () const
Definition at line 74 of file rawimage.cpp.
References COLOR_YUV411, COLOR_YUV422_UYVY, getColorFormat(), height, and width.
{
   int pixelCount=width*height;
   switch (getColorFormat()) {
     case COLOR_YUV422_UYVY:
     return pixelCount/2;
     case COLOR_YUV411:
     return pixelCount/4;
     default:
     return pixelCount;
   }
 }
int RawImage::getNumPixels () const virtual
Implements ImageInterface.
Definition at line 64 of file rawimage.cpp.
References height, and width.
Referenced by getNumBytes(), GLLUTWidget::sampleImage(), and CMVisionThreshold::thresholdImageYUV422_UYVY().
 {
   return width*height;
 }
double RawImage::getTime () const
Definition at line 54 of file rawimage.cpp.
References time.
Referenced by CaptureFlycap::convertFrame(), CaptureV4L::convertFrame(), CaptureDC1394v2::convertFrame(), CaptureGenerator::copyAndConvertFrame(), CaptureFromFile::copyAndConvertFrame(), CaptureInterface::copyAndConvertFrame(), CaptureBlueFox2::copyAndConvertFrame(), and CaptureThread::run().
 {
   return time;
 }
int RawImage::getWidth () const virtual
Implements ImageInterface.
Definition at line 39 of file rawimage.cpp.
References width.
Referenced by GlobalV4Linstance::captureFrame(), CaptureFlycap::convertFrame(), CaptureV4L::convertFrame(), CaptureDC1394v2::convertFrame(), CaptureGenerator::copyAndConvertFrame(), CaptureFromFile::copyAndConvertFrame(), CaptureInterface::copyAndConvertFrame(), CaptureBlueFox2::copyAndConvertFrame(), deepCopyFromRawImage(), PluginCameraCalibration::detectEdges(), PluginVisualize::DrawCameraImage(), PluginVisualize::DrawSobelImage(), Image< rgb >::fromRawImage(), CaptureGenerator::getFrame(), PluginColorCalibration::mouseEvent(), PluginNeuralColorCalib::mouseEvent(), PluginColorThreshold::process(), PluginCameraCalibration::process(), PluginVisualize::process(), CMVision::ImageProcessor::processYUV422_UYVY(), GLLUTWidget::sampleImage(), PluginDVR::slotMovieSave(), and CMVisionThreshold::thresholdImageYUV422_UYVY().
 {
   return width;
 }
void RawImage::setColorFormat (ColorFormat f)
Definition at line 86 of file rawimage.cpp.
References format.
Referenced by CaptureGenerator::getFrame(), CaptureFromFile::getFrame(), CaptureFlycap::getFrame(), CaptureBlueFox2::getFrame(), and CaptureDC1394v2::getFrame().
 {
   format=f;
 }
void RawImage::setData (unsigned char * d)
Definition at line 106 of file rawimage.cpp.
References data.
Referenced by CaptureFromFile::getFrame(), CaptureFlycap::getFrame(), CaptureBlueFox2::getFrame(), and CaptureDC1394v2::getFrame().
 {
   if (data!=0) delete[] data;
   data=d;
 }
void RawImage::setHeight (int h)
Definition at line 96 of file rawimage.cpp.
References height.
Referenced by Image< rgb >::copyToRawImage(), CaptureFromFile::getFrame(), CaptureFlycap::getFrame(), CaptureBlueFox2::getFrame(), and CaptureDC1394v2::getFrame().
 {
   height=h;
 }
void RawImage::setTime (double t)
Definition at line 101 of file rawimage.cpp.
References t, and time.
Referenced by GlobalV4Linstance::captureFrame(), CaptureFlycap::convertFrame(), CaptureV4L::convertFrame(), CaptureDC1394v2::convertFrame(), CaptureGenerator::copyAndConvertFrame(), CaptureFromFile::copyAndConvertFrame(), CaptureInterface::copyAndConvertFrame(), CaptureBlueFox2::copyAndConvertFrame(), CaptureGenerator::getFrame(), CaptureFromFile::getFrame(), CaptureFlycap::getFrame(), CaptureBlueFox2::getFrame(), and CaptureDC1394v2::getFrame().
 {
   time=t;
 }
void RawImage::setWidth (int w)
Definition at line 91 of file rawimage.cpp.
References width.
Referenced by Image< rgb >::copyToRawImage(), CaptureFromFile::getFrame(), CaptureFlycap::getFrame(), CaptureBlueFox2::getFrame(), and CaptureDC1394v2::getFrame().
 {
   width=w;
 }
Field Documentation
unsigned char* RawImage::data protected
pointer to capture buffer
Definition at line 43 of file rawimage.h.
Referenced by allocate(), ensure_allocation(), getData(), RawImage(), and setData().
ColorFormat RawImage::format protected
encoding format of the image
Definition at line 52 of file rawimage.h.
Referenced by allocate(), ensure_allocation(), getColorFormat(), getNumBytes(), RawImage(), and setColorFormat().
int RawImage::height protected
height of the image in pixels
Definition at line 49 of file rawimage.h.
Referenced by allocate(), ensure_allocation(), getHeight(), getNumColorBlocks(), getNumPixels(), RawImage(), and setHeight().
double RawImage::time protected
capture timestamp of the image
Definition at line 55 of file rawimage.h.
Referenced by deepCopyFromRawImage(), getTime(), RawImage(), and setTime().
int RawImage::width protected
width of the image in pixels
Definition at line 46 of file rawimage.h.
Referenced by allocate(), ensure_allocation(), getNumColorBlocks(), getNumPixels(), getWidth(), RawImage(), and setWidth().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/util/rawimage.h
ssl-vision/src/shared/util/rawimage.cpp