Documentation: Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize Class Reference
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize Class Reference
Data Structures
class Builder
Public Member Functions
SSL_GeometryFieldSize getDefaultInstanceForType ()
boolean hasLineWidth ()
int getLineWidth ()
boolean hasFieldLength ()
int getFieldLength ()
boolean hasFieldWidth ()
int getFieldWidth ()
boolean hasBoundaryWidth ()
int getBoundaryWidth ()
boolean hasRefereeWidth ()
int getRefereeWidth ()
boolean hasGoalWidth ()
int getGoalWidth ()
boolean hasGoalDepth ()
int getGoalDepth ()
boolean hasGoalWallWidth ()
int getGoalWallWidth ()
boolean hasCenterCircleRadius ()
int getCenterCircleRadius ()
boolean hasDefenseRadius ()
int getDefenseRadius ()
boolean hasDefenseStretch ()
int getDefenseStretch ()
boolean hasFreeKickFromDefenseDist ()
int getFreeKickFromDefenseDist ()
boolean hasPenaltySpotFromFieldLineDist ()
int getPenaltySpotFromFieldLineDist ()
boolean hasPenaltyLineFromSpotDist ()
int getPenaltyLineFromSpotDist ()
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static SSL_GeometryFieldSize getDefaultInstance ()
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize parseFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (MessagesRobocupSslGeometry.SSL_GeometryFieldSize prototype)
Static Public Attributes
static final int LINE_WIDTH_FIELD_NUMBER = 1
static final int FIELD_LENGTH_FIELD_NUMBER = 2
static final int FIELD_WIDTH_FIELD_NUMBER = 3
static final int BOUNDARY_WIDTH_FIELD_NUMBER = 4
static final int REFEREE_WIDTH_FIELD_NUMBER = 5
static final int GOAL_WIDTH_FIELD_NUMBER = 6
static final int GOAL_DEPTH_FIELD_NUMBER = 7
static final int GOAL_WALL_WIDTH_FIELD_NUMBER = 8
static final int CENTER_CIRCLE_RADIUS_FIELD_NUMBER = 9
static final int DEFENSE_RADIUS_FIELD_NUMBER = 10
static final int DEFENSE_STRETCH_FIELD_NUMBER = 11
static final int FREE_KICK_FROM_DEFENSE_DIST_FIELD_NUMBER = 12
static final int PENALTY_SPOT_FROM_FIELD_LINE_DIST_FIELD_NUMBER = 13
static final int PENALTY_LINE_FROM_SPOT_DIST_FIELD_NUMBER = 14
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
.lang.Override Builder newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent)
Private Member Functions
SSL_GeometryFieldSize (Builder builder)
SSL_GeometryFieldSize (boolean noInit)
void initFields ()
Private Attributes
int bitField0_
int lineWidth_
int fieldLength_
int fieldWidth_
int boundaryWidth_
int refereeWidth_
int goalWidth_
int goalDepth_
int goalWallWidth_
int centerCircleRadius_
int defenseRadius_
int defenseStretch_
int freeKickFromDefenseDist_
int penaltySpotFromFieldLineDist_
int penaltyLineFromSpotDist_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final SSL_GeometryFieldSize defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Definition at line 70 of file MessagesRobocupSslGeometry.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.SSL_GeometryFieldSize (Builder builder) inline private
Definition at line 74 of file MessagesRobocupSslGeometry.java.
{
       super(builder);
     }
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.SSL_GeometryFieldSize (boolean noInit) inline private
Definition at line 77 of file MessagesRobocupSslGeometry.java.
 {}
Member Function Documentation
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getBoundaryWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 135 of file MessagesRobocupSslGeometry.java.
{
       return boundaryWidth_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getCenterCircleRadius () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 185 of file MessagesRobocupSslGeometry.java.
{
       return centerCircleRadius_;
     }
static SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstance () inline static
Definition at line 80 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.clear(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.clearField(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getDefaultInstanceForType(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.initFields(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeField(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.mergeFrom().
{
       return defaultInstance;
     }
SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefaultInstanceForType () inline
Definition at line 84 of file MessagesRobocupSslGeometry.java.
{
       return defaultInstance;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefenseRadius () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 195 of file MessagesRobocupSslGeometry.java.
{
       return defenseRadius_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDefenseStretch () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 205 of file MessagesRobocupSslGeometry.java.
{
       return defenseStretch_;
     }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getDescriptor () inline static
Definition at line 89 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.internal_static_SSL_GeometryFieldSize_descriptor.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.getDescriptorForType().
{
       return MessagesRobocupSslGeometry.internal_static_SSL_GeometryFieldSize_descriptor;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getFieldLength () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 115 of file MessagesRobocupSslGeometry.java.
{
       return fieldLength_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getFieldWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 125 of file MessagesRobocupSslGeometry.java.
{
       return fieldWidth_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getFreeKickFromDefenseDist () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 215 of file MessagesRobocupSslGeometry.java.
{
       return freeKickFromDefenseDist_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getGoalDepth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 165 of file MessagesRobocupSslGeometry.java.
{
       return goalDepth_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getGoalWallWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 175 of file MessagesRobocupSslGeometry.java.
{
       return goalWallWidth_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getGoalWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 155 of file MessagesRobocupSslGeometry.java.
{
       return goalWidth_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getLineWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 105 of file MessagesRobocupSslGeometry.java.
{
       return lineWidth_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getPenaltyLineFromSpotDist () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 235 of file MessagesRobocupSslGeometry.java.
{
       return penaltyLineFromSpotDist_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getPenaltySpotFromFieldLineDist () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 225 of file MessagesRobocupSslGeometry.java.
{
       return penaltySpotFromFieldLineDist_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getRefereeWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 145 of file MessagesRobocupSslGeometry.java.
{
       return refereeWidth_;
     }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.getSerializedSize () inline
Definition at line 369 of file MessagesRobocupSslGeometry.java.
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(1, lineWidth_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(2, fieldLength_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(3, fieldWidth_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(4, boundaryWidth_);
       }
       if (((bitField0_ & 0x00000010) == 0x00000010)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(5, refereeWidth_);
       }
       if (((bitField0_ & 0x00000020) == 0x00000020)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(6, goalWidth_);
       }
       if (((bitField0_ & 0x00000040) == 0x00000040)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(7, goalDepth_);
       }
       if (((bitField0_ & 0x00000080) == 0x00000080)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(8, goalWallWidth_);
       }
       if (((bitField0_ & 0x00000100) == 0x00000100)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(9, centerCircleRadius_);
       }
       if (((bitField0_ & 0x00000200) == 0x00000200)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(10, defenseRadius_);
       }
       if (((bitField0_ & 0x00000400) == 0x00000400)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(11, defenseStretch_);
       }
       if (((bitField0_ & 0x00000800) == 0x00000800)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(12, freeKickFromDefenseDist_);
       }
       if (((bitField0_ & 0x00001000) == 0x00001000)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(13, penaltySpotFromFieldLineDist_);
       }
       if (((bitField0_ & 0x00002000) == 0x00002000)) {
         size += com.google.protobuf.CodedOutputStream
           .computeInt32Size(14, penaltyLineFromSpotDist_);
       }
       size += getUnknownFields().getSerializedSize();
       memoizedSerializedSize = size;
       return size;
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasBoundaryWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 132 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000008) == 0x00000008);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasCenterCircleRadius () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 182 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000100) == 0x00000100);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasDefenseRadius () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 192 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000200) == 0x00000200);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasDefenseStretch () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 202 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000400) == 0x00000400);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasFieldLength () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 112 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000002) == 0x00000002);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasFieldWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 122 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000004) == 0x00000004);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasFreeKickFromDefenseDist () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 212 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000800) == 0x00000800);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasGoalDepth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 162 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000040) == 0x00000040);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasGoalWallWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 172 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000080) == 0x00000080);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasGoalWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 152 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000020) == 0x00000020);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasLineWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 102 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasPenaltyLineFromSpotDist () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 232 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00002000) == 0x00002000);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasPenaltySpotFromFieldLineDist () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 222 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00001000) == 0x00001000);
     }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.hasRefereeWidth () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.
Definition at line 142 of file MessagesRobocupSslGeometry.java.
{
       return ((bitField0_ & 0x00000010) == 0x00000010);
     }
void Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.initFields () inline private
Definition at line 239 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.clearPenaltyLineFromSpotDist().
{
       lineWidth_ = 0;
       fieldLength_ = 0;
       fieldWidth_ = 0;
       boundaryWidth_ = 0;
       refereeWidth_ = 0;
       goalWidth_ = 0;
       goalDepth_ = 0;
       goalWallWidth_ = 0;
       centerCircleRadius_ = 0;
       defenseRadius_ = 0;
       defenseStretch_ = 0;
       freeKickFromDefenseDist_ = 0;
       penaltySpotFromFieldLineDist_ = 0;
       penaltyLineFromSpotDist_ = 0;
     }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.internalGetFieldAccessorTable () inline protected
Definition at line 94 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.internal_static_SSL_GeometryFieldSize_fieldAccessorTable.
{
       return MessagesRobocupSslGeometry.internal_static_SSL_GeometryFieldSize_fieldAccessorTable;
     }
final boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.isInitialized () inline
Definition at line 256 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasBoundaryWidth(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasCenterCircleRadius(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasDefenseRadius(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasDefenseStretch(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasFieldLength(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasFieldWidth(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasFreeKickFromDefenseDist(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasGoalDepth(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasGoalWallWidth(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasGoalWidth(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasLineWidth(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasPenaltyLineFromSpotDist(), Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasPenaltySpotFromFieldLineDist(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSizeOrBuilder.hasRefereeWidth().
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized != -1) return isInitialized == 1;
       if (!hasLineWidth()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasFieldLength()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasFieldWidth()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasBoundaryWidth()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasRefereeWidth()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasGoalWidth()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasGoalDepth()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasGoalWallWidth()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasCenterCircleRadius()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasDefenseRadius()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasDefenseStretch()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasFreeKickFromDefenseDist()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasPenaltySpotFromFieldLineDist()) {
         memoizedIsInitialized = 0;
         return false;
       }
       if (!hasPenaltyLineFromSpotDist()) {
         memoizedIsInitialized = 0;
         return false;
       }
       memoizedIsInitialized = 1;
       return true;
     }
static Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.newBuilder () inline static
Definition at line 509 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.create().
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeField(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryData.Builder.mergeFrom().
 { return Builder.create(); }
static Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.newBuilder (MessagesRobocupSslGeometry.SSL_GeometryFieldSize prototype) inline static
Definition at line 511 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.newBuilderForType () inline
Definition at line 510 of file MessagesRobocupSslGeometry.java.
 { return newBuilder(); }
.lang.Override Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.newBuilderForType (com.google.protobuf.GeneratedMessage.BuilderParent parent) inline protected
Definition at line 517 of file MessagesRobocupSslGeometry.java.
{
       Builder builder = new Builder(parent);
       return builder;
     }
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 476 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 485 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.buildParsed().
{
       Builder builder = newBuilder();
       if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
         return builder.buildParsed();
       } else {
         return null;
       }
     }
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 442 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 447 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 454 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(data).buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 458 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(data, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 465 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 469 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 496 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(input).buildParsed();
     }
static MessagesRobocupSslGeometry.SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 501 of file MessagesRobocupSslGeometry.java.
{
       return newBuilder().mergeFrom(input, extensionRegistry)
                .buildParsed();
     }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.toBuilder () inline
Definition at line 514 of file MessagesRobocupSslGeometry.java.
 { return newBuilder(this); }
.lang.Override java.lang.Object Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.writeReplace () throws java.io.ObjectStreamException inline protected
Definition at line 437 of file MessagesRobocupSslGeometry.java.
{
       return super.writeReplace();
     }
void Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException inline
Definition at line 320 of file MessagesRobocupSslGeometry.java.
{
       getSerializedSize();
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeInt32(1, lineWidth_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         output.writeInt32(2, fieldLength_);
       }
       if (((bitField0_ & 0x00000004) == 0x00000004)) {
         output.writeInt32(3, fieldWidth_);
       }
       if (((bitField0_ & 0x00000008) == 0x00000008)) {
         output.writeInt32(4, boundaryWidth_);
       }
       if (((bitField0_ & 0x00000010) == 0x00000010)) {
         output.writeInt32(5, refereeWidth_);
       }
       if (((bitField0_ & 0x00000020) == 0x00000020)) {
         output.writeInt32(6, goalWidth_);
       }
       if (((bitField0_ & 0x00000040) == 0x00000040)) {
         output.writeInt32(7, goalDepth_);
       }
       if (((bitField0_ & 0x00000080) == 0x00000080)) {
         output.writeInt32(8, goalWallWidth_);
       }
       if (((bitField0_ & 0x00000100) == 0x00000100)) {
         output.writeInt32(9, centerCircleRadius_);
       }
       if (((bitField0_ & 0x00000200) == 0x00000200)) {
         output.writeInt32(10, defenseRadius_);
       }
       if (((bitField0_ & 0x00000400) == 0x00000400)) {
         output.writeInt32(11, defenseStretch_);
       }
       if (((bitField0_ & 0x00000800) == 0x00000800)) {
         output.writeInt32(12, freeKickFromDefenseDist_);
       }
       if (((bitField0_ & 0x00001000) == 0x00001000)) {
         output.writeInt32(13, penaltySpotFromFieldLineDist_);
       }
       if (((bitField0_ & 0x00002000) == 0x00002000)) {
         output.writeInt32(14, penaltyLineFromSpotDist_);
       }
       getUnknownFields().writeTo(output);
     }
Field Documentation
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.bitField0_ private
Definition at line 98 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.BOUNDARY_WIDTH_FIELD_NUMBER = 4 static
Definition at line 130 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.boundaryWidth_ private
Definition at line 131 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.CENTER_CIRCLE_RADIUS_FIELD_NUMBER = 9 static
Definition at line 180 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.centerCircleRadius_ private
Definition at line 181 of file MessagesRobocupSslGeometry.java.
final SSL_GeometryFieldSize Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.defaultInstance static private
Definition at line 79 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.DEFENSE_RADIUS_FIELD_NUMBER = 10 static
Definition at line 190 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.DEFENSE_STRETCH_FIELD_NUMBER = 11 static
Definition at line 200 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.defenseRadius_ private
Definition at line 191 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.defenseStretch_ private
Definition at line 201 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.FIELD_LENGTH_FIELD_NUMBER = 2 static
Definition at line 110 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.FIELD_WIDTH_FIELD_NUMBER = 3 static
Definition at line 120 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.fieldLength_ private
Definition at line 111 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.fieldWidth_ private
Definition at line 121 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.FREE_KICK_FROM_DEFENSE_DIST_FIELD_NUMBER = 12 static
Definition at line 210 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.freeKickFromDefenseDist_ private
Definition at line 211 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.GOAL_DEPTH_FIELD_NUMBER = 7 static
Definition at line 160 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.GOAL_WALL_WIDTH_FIELD_NUMBER = 8 static
Definition at line 170 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.GOAL_WIDTH_FIELD_NUMBER = 6 static
Definition at line 150 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.goalDepth_ private
Definition at line 161 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.goalWallWidth_ private
Definition at line 171 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.goalWidth_ private
Definition at line 151 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.LINE_WIDTH_FIELD_NUMBER = 1 static
Definition at line 100 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.lineWidth_ private
Definition at line 101 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.Builder.buildPartial().
byte Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.memoizedIsInitialized = -1 private
Definition at line 255 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.memoizedSerializedSize = -1 private
Definition at line 368 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.PENALTY_LINE_FROM_SPOT_DIST_FIELD_NUMBER = 14 static
Definition at line 230 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.PENALTY_SPOT_FROM_FIELD_LINE_DIST_FIELD_NUMBER = 13 static
Definition at line 220 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.penaltyLineFromSpotDist_ private
Definition at line 231 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.penaltySpotFromFieldLineDist_ private
Definition at line 221 of file MessagesRobocupSslGeometry.java.
final int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.REFEREE_WIDTH_FIELD_NUMBER = 5 static
Definition at line 140 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.refereeWidth_ private
Definition at line 141 of file MessagesRobocupSslGeometry.java.
final long Protobuf.MessagesRobocupSslGeometry.SSL_GeometryFieldSize.serialVersionUID = 0L static private
Definition at line 435 of file MessagesRobocupSslGeometry.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslGeometry.java