Documentation: Vec Namespace Reference
Vec Namespace Reference
Data Structures
class NVector
Functions
template<class num , const int dim>
num sqdist (const NVector< num, dim > &a, const NVector< num, dim > &b)
template<class num , const int dim>
num dist (const NVector< num, dim > &a, const NVector< num, dim > &b)
template<class num , const int dim>
num dot (const NVector< num, dim > &a, const NVector< num, dim > &b)
Function Documentation
template<class num , const int dim> num Vec::dist (const NVector< num, dim > & a, const NVector< num, dim > & b)
Definition at line 307 of file nvector.h.
References sqdist().
 {
   return(sqrt(sqdist(a,b)));
 }
template<class num , const int dim> num Vec::dot (const NVector< num, dim > & a, const NVector< num, dim > & b)
Definition at line 313 of file nvector.h.
References velocity.pid_::i, and Vec::NVector< num, dim >::v.
 {
   num sum = 0;
   switch(dim){
     case 4: sum += a.v[3] * b.v[3];
     case 3: sum += a.v[2] * b.v[2];
     case 2: sum += a.v[1] * b.v[1];
     case 1: sum += a.v[0] * b.v[0];
       break;
     default:
       for(int i=0; i<dim; i++){
         sum += a.v[i] * b.v[i];
       }
   }
   return(sum);
 }
template<class num , const int dim> num Vec::sqdist (const NVector< num, dim > & a, const NVector< num, dim > & b)
Definition at line 289 of file nvector.h.
References velocity.pid_::i, and sq().
Referenced by dist().
 {
   num sum = 0;
   switch(dim){
     case 4: sum += sq(a.v[3] - b.v[3]);
     case 3: sum += sq(a.v[2] - b.v[2]);
     case 2: sum += sq(a.v[1] - b.v[1]);
     case 1: sum += sq(a.v[0] - b.v[0]);
       break;
     default:
       for(int i=0; i<dim; i++){
         sum += sq(a.v[i] - b.v[i]);
       }
   }
   return(sum);
 }