Documentation: BeliefState Class Reference
BeliefState Class Reference
Core class for extracting belief state information.
#include <class_node.hpp>
Public Member Functions
BeliefState ()
BeliefState (const krssg_ssl_msgs::SSL_DetectionFrame::ConstPtr &, list< BeliefState > &)
BeliefState (const BeliefState &)
void copy (const BeliefState &)
void initialise ()
void print ()
krssg_ssl_msgs::BeliefState getBeliefStateMsg ()
BeliefState ()
Default Constructer.
BeliefState (bool isteamyellow)
Default Constructer.
BeliefState (const BeliefState &msg)
Copy constructer.
void update_frame (const krssg_ssl_msgs::SSL_DetectionFrame *vmsg)
Copy Constructer for frame data.
void copy (const BeliefState &)
Copy bf to current instance.
void initialise ()
{ function_description }
void print (string str)
Print one instance of the belief state data.
krssg_ssl_msgs::BeliefState get_beliefstate_msg ()
Gets the beliefstate message of the current instance.
Private Attributes
ros::Time time
bool isteamyellow
int frame_number
double t_capture
double t_sent
Pose2D ballPos
vector< Pose2D > awayPos
vector< Pose2D > homePos
Pose2D ballVel
vector< Pose2D > awayVel
vector< Pose2D > homeVel
bool ballDetected
vector< bool > awayDetected
vector< bool > homeDetected
short int our_bot_closest_to_ball
short int opp_bot_closest_to_ball
short int our_goalie
short int opp_goalie
short int opp_bot_marking_our_attacker
bool ball_at_corners
bool ball_in_our_half
bool ball_in_our_possession
BeliefState * prev_msg
ros::Time stamp
Detailed Description
Core class for extracting belief state information.
Parameters
Definition at line 53 of file node_class.cpp.
Constructor & Destructor Documentation
BeliefState::BeliefState ()
Referenced by BeliefState(), distFn(), and is_valid().
BeliefState::BeliefState (const krssg_ssl_msgs::SSL_DetectionFrame::ConstPtr & , list< BeliefState > &)
BeliefState::BeliefState (const BeliefState &)
BeliefState::BeliefState ()
Default Constructer.
Definition at line 103 of file node_class.cpp.
{
     this->initialise();
 }
BeliefState::BeliefState (bool isteamyellow)
Default Constructer.
Parameters
[in] isteamyellow True if our team is yellow
Definition at line 19 of file class_node.cpp.
References test_fsm::BeliefState, BeliefState(), and isteamyellow.
{
    this->prev_msg = NULL;
    this->isteamyellow = isteamyellow;
    this->initialise();
 }
BeliefState::BeliefState (const BeliefState & msg)
Copy constructer.
Parameters
[in] msg Instance of belief state
Definition at line 107 of file node_class.cpp.
References role._GoToPoint::awayPos, awayVel, ballPos, test_fsm::BeliefState, copy(), role._GoToPoint::homePos, homeVel, and isteamyellow.
{
     this->copy(msg);
 }
Member Function Documentation
void BeliefState::copy (const BeliefState &)
Copy bf to current instance.
Parameters
[in] bf Instance of belief state
void BeliefState::copy (const BeliefState &)
Referenced by BeliefState(), and update_frame().
krssg_ssl_msgs::BeliefState BeliefState::get_beliefstate_msg ()
Gets the beliefstate message of the current instance.
Returns
The beliefstate message.
Definition at line 29 of file class_node.cpp.
References role._GoToPoint::awayPos, awayVel, ballPos, test_fsm::BeliefState, role._GoToPoint::homePos, homeVel, velocity.pid_::i, and isteamyellow.
{
    krssg_ssl_msgs::BeliefState msg;
    msg.stamp = this->stamp;
    msg.isteamyellow = this->isteamyellow;
    msg.frame_number = this->frame_number;
    msg.t_capture = this->t_capture;
    msg.t_sent = this->t_sent;
    msg.ballPos.x = this->ballPos.x;
    msg.ballPos.y = this->ballPos.y;
    msg.awayPos = this->awayPos;
    msg.homePos = this->homePos;
    msg.ballVel.x = this->ballVel.x;
    msg.ballVel.y = this->ballVel.y;
    msg.awayVel = this->awayVel;
    msg.homeVel = this->homeVel;
    msg.ballDetected = this->ballDetected;
    for(int i=0;i<msg.homeDetected.size();i++)
       msg.homeDetected[i] = this->homeDetected[i];
    for(int i=0;i<msg.awayDetected.size();i++)
       msg.awayDetected[i] = this->awayDetected[i];
    return msg;
 }
krssg_ssl_msgs::BeliefState BeliefState::getBeliefStateMsg ()
Definition at line 388 of file node_class.cpp.
References role._GoToPoint::awayPos, awayVel, ballPos, test_fsm::BeliefState, role._GoToPoint::homePos, homeVel, velocity.pid_::i, and isteamyellow.
{
     krssg_ssl_msgs::BeliefState msg;
     msg.isteamyellow = this->isteamyellow;
     msg.frame_number = this->frame_number;
     msg.t_capture = this->t_capture;
     msg.t_sent = this->t_sent;
     msg.ballPos.x = this->ballPos.x;
     msg.ballPos.y = this->ballPos.y;
     msg.awayPos = this->awayPos;
     msg.homePos = this->homePos;
     msg.ballVel.x = this->ballVel.x;
     msg.ballVel.y = this->ballVel.y;
     msg.awayVel = this->awayVel;
     msg.homeVel = this->homeVel;
     msg.ballDetected = this->ballDetected;
     for(int i=0;i<this->homeDetected.size();i++)
         msg.homeDetected.push_back(this->homeDetected[i]);
     for(int i=0;i<this->awayDetected.size();i++)
         msg.awayDetected.push_back(this->awayDetected[i]);
     msg.our_bot_closest_to_ball = this->our_bot_closest_to_ball;
     msg.opp_bot_closest_to_ball = this->opp_bot_closest_to_ball;
     msg.our_goalie = this->our_goalie;
     msg.opp_goalie = this->opp_goalie;
     msg.opp_bot_marking_our_attacker = this->opp_bot_marking_our_attacker;
     msg.ball_at_corners = this->ball_at_corners;
     msg.ball_in_our_half = this->ball_in_our_half;
     msg.ball_in_our_possession = this->ball_in_our_possession;
     return msg;
 }
void BeliefState::initialise ()
{ function_description }
Definition at line 331 of file node_class.cpp.
References role._GoToPoint::awayPos, awayVel, ballPos, role._GoToPoint::homePos, homeVel, and isteamyellow.
{
     this->time = ros::Time::now();
     this->isteamyellow = ::isteamyellow;
     this->frame_number = 0;
     this->t_capture = 0.0;
     this->t_sent = 0.0;
     this->ballPos = Pose2D();
     this->awayPos = vector<Pose2D>(6,Pose2D());
     this->homePos = vector<Pose2D>(6,Pose2D());
     this->ballVel = Pose2D();
     this->awayVel = vector<Pose2D>(6,Pose2D());
     this->homeVel = vector<Pose2D>(6,Pose2D());
     this->ballDetected = false;
     this->homeDetected = vector<bool>(6,0);
     this->awayDetected = vector<bool>(6,0);
     this->our_bot_closest_to_ball = this->opp_bot_closest_to_ball =
     this->our_goalie = this->opp_goalie = this->opp_bot_marking_our_attacker = 0;
     this->ball_at_corners = this->ball_in_our_possession = this->ball_in_our_half = false;
 }
void BeliefState::initialise ()
Referenced by update_frame().
void BeliefState::print ()
Definition at line 357 of file node_class.cpp.
References role._GoToPoint::awayPos, awayVel, ballPos, role._GoToPoint::homePos, homeVel, isteamyellow, and print().
{
     system("clear");
     cout<<"time: "<<this->time<<endl;
     cout<<"isteamyellow: "<<isteamyellow<<endl;
     cout<<"frame_number: "<<frame_number<<endl;
     cout<<"t_capture: "<<t_capture<<" t_sent: "<<t_sent<<endl;
     cout<<"ballPos:"<<endl;
     ::print(ballPos);
     cout<<"awayPos:"<<endl;
     ::print(awayPos);
     cout<<"homePos:"<<endl;
     ::print(homePos);
     cout<<"ballVel:"<<endl;
     ::print(ballVel);
     cout<<"awayVel:"<<endl;
     ::print(awayVel);
     cout<<"homeVel:"<<endl;
     ::print(homeVel);
     cout<<"ballDetected: "<<ballDetected;
     cout<<"homeDetected:"<<endl;
     ::print(homeDetected);
     cout<<"awayDetected:"<<endl;
     ::print(awayDetected);
     cout<<"our_bot_closest_to_ball: "<<our_bot_closest_to_ball<<
     " opp_bot_closest_to_ball: "<<opp_bot_closest_to_ball<<
     " \n our_goalie: "<<our_goalie<<" opp_goalie: "<<opp_goalie<<
     " opp_bot_marking_our_attacker: "<<opp_bot_marking_our_attacker<<
     "\n ball_at_corners: "<<ball_at_corners<<" ball_in_our_half: "<<ball_in_our_half<<
     "\n ball_in_our_possession: "<<ball_in_our_possession<<endl;
 }
void BeliefState::print (string str)
Print one instance of the belief state data.
Definition at line 193 of file class_node.cpp.
References role._GoToPoint::awayPos, awayVel, ballPos, role._GoToPoint::homePos, homeVel, isteamyellow, and print().
{
    system("clear");
    cout<<"Data recieved from : " << str << endl
        <<"Time: "<<this->stamp<<endl
        <<"isteamyellow: "<<this->isteamyellow<<endl
        <<"frame_number: "<<frame_number<<endl
        <<"t_capture: "<<t_capture<<endl
        <<"t_sent: "<<t_sent<<endl
        <<"ballPos:"<<endl;
    ::print(ballPos);
    cout<<"awayPos:"<<endl;
    ::print(awayPos);
    cout<<"homePos:"<<endl;
    ::print(homePos);
    cout<<"ballVel:"<<endl;
    ::print(ballVel);
    cout<<"awayVel:"<<endl;
    ::print(awayVel);
    cout<<"homeVel:"<<endl;
    ::print(homeVel);
 }
void BeliefState::update_frame (const krssg_ssl_msgs::SSL_DetectionFrame * vmsg)
Copy Constructer for frame data.
Parameters
[in] vmsg packet of frame data
Definition at line 57 of file class_node.cpp.
References role._GoToPoint::awayPos, awayVel, ballPos, test_fsm::BeliefState, copy(), HALF_FIELD_MAXX, HALF_FIELD_MAXY, role._GoToPoint::homePos, homeVel, velocity.pid_::i, initialise(), isteamyellow, and role._GoToPoint_::prev_state.
{
    BeliefState prev_state;
    if(this->prev_msg == NULL) {
       this->initialise();
    } else {
       prev_state = *this->prev_msg;
       this->stamp = ros::Time::now();
       this->frame_number = vmsg->frame_number;
       this->t_capture = vmsg->t_capture;
       this->t_sent = vmsg->t_sent;
       this->isteamyellow = isteamyellow;
       vector<krssg_ssl_msgs::SSL_DetectionRobot> homePos, awayPos;
       if(isteamyellow) {
          homePos = vmsg->robots_yellow;
          awayPos = vmsg->robots_blue;
       } else {
          homePos = vmsg->robots_blue;
          awayPos = vmsg->robots_yellow;
       }
       if(vmsg->balls.size()) {
          this->ballDetected = 1;
          this->ballPos.x = vmsg->balls[0].x;
          this->ballPos.y = vmsg->balls[0].y;
       } else {
          this->ballDetected = 0;
       }
       for(int i=0;i<homePos.size();i++) {
          int bot_id = homePos[i].robot_id;
          this->homeDetected[bot_id] = 1;
          this->homePos[bot_id].x = homePos[i].x;
          this->homePos[bot_id].y = homePos[i].y;
          this->homePos[bot_id].theta = homePos[i].orientation;
       }
       for(int i=0;i<awayPos.size();i++){
          int bot_id = awayPos[i].robot_id;
          this->awayDetected[bot_id] = 1;
          this->awayPos[bot_id].x = awayPos[i].x;
          this->awayPos[bot_id].y = awayPos[i].y;
          this->awayPos[bot_id].theta = awayPos[i].orientation;
       }
    }
    if(this->prev_msg == NULL) {
       prev_msg = this;
       return;
    }
    assert(prev_state.homePos.size() == 6);
    assert(prev_state.awayPos.size() == 6);
    this->ballVel.x = (this->ballPos.x - prev_state.ballPos.x)/(this->stamp - prev_state.stamp).toSec();
    this->ballVel.y = (this->ballPos.y - prev_state.ballPos.y)/(this->stamp - prev_state.stamp).toSec();
    for(int i=0;i<this->homePos.size();i++) {
       this->homeVel[i].x = (this->homePos[i].x - prev_state.homePos[i].x)/(this->stamp - prev_state.stamp).toSec();
       this->homeVel[i].y = (this->homePos[i].y - prev_state.homePos[i].y)/(this->stamp - prev_state.stamp).toSec();
    }
    for(int i=0;i<this->awayPos.size();i++) {
       this->awayVel[i].x = (this->awayPos[i].x - prev_state.awayPos[i].x)/(this->stamp - prev_state.stamp).toSec();
       this->awayVel[i].y = (this->awayPos[i].y - prev_state.awayPos[i].y)/(this->stamp - prev_state.stamp).toSec();
    }
 }
Field Documentation
vector< bool > BeliefState::awayDetected private
Definition at line 73 of file node_class.cpp.
vector< Pose2D > BeliefState::awayPos private
Definition at line 65 of file node_class.cpp.
vector< Pose2D > BeliefState::awayVel private
Definition at line 69 of file node_class.cpp.
bool BeliefState::ball_at_corners private
Definition at line 82 of file node_class.cpp.
bool BeliefState::ball_in_our_half private
Definition at line 82 of file node_class.cpp.
bool BeliefState::ball_in_our_possession private
Definition at line 82 of file node_class.cpp.
bool BeliefState::ballDetected private
Definition at line 72 of file node_class.cpp.
Pose2D BeliefState::ballPos private
Definition at line 64 of file node_class.cpp.
Pose2D BeliefState::ballVel private
Definition at line 68 of file node_class.cpp.
int BeliefState::frame_number private
Definition at line 60 of file node_class.cpp.
vector< bool > BeliefState::homeDetected private
Definition at line 73 of file node_class.cpp.
vector< Pose2D > BeliefState::homePos private
Definition at line 65 of file node_class.cpp.
vector< Pose2D > BeliefState::homeVel private
Definition at line 69 of file node_class.cpp.
bool BeliefState::isteamyellow private
Definition at line 59 of file node_class.cpp.
Referenced by kubs.kubs.kubs::execute().
short int BeliefState::opp_bot_closest_to_ball private
Definition at line 76 of file node_class.cpp.
short int BeliefState::opp_bot_marking_our_attacker private
Definition at line 76 of file node_class.cpp.
short int BeliefState::opp_goalie private
Definition at line 76 of file node_class.cpp.
short int BeliefState::our_bot_closest_to_ball private
Definition at line 76 of file node_class.cpp.
short int BeliefState::our_goalie private
Definition at line 76 of file node_class.cpp.
BeliefState* BeliefState::prev_msg private
Definition at line 26 of file class_node.hpp.
ros::Time BeliefState::stamp private
Definition at line 29 of file class_node.hpp.
double BeliefState::t_capture private
Definition at line 61 of file node_class.cpp.
double BeliefState::t_sent private
Definition at line 61 of file node_class.cpp.
ros::Time BeliefState::time private
Definition at line 56 of file node_class.cpp.
The documentation for this class was generated from the following files:
belief_state/src/node_class.cpp
vision_comm/include/class_node.hpp
vision_comm/src/class_node.cpp