Documentation: Client.Conection Class Reference
Client.Conection Class Reference
Public Member Functions
void setTime (float timeStamp)
void setWheel1 (float wheel1)
void setWheel2 (float wheel2)
void setWheel3 (float wheel3)
void setWheel4 (float wheel4)
void setKickspeedX (float kickspeedx)
void setKickspeedZ (float kickspeedz)
void setVelX (float velx)
void setVelY (float vely)
void setVelZ (float velz)
void setId (int id)
void setSpinner (boolean spinner)
void setWheelSpeed (boolean wheelSpeed)
void setTeamYellow (boolean teamYellow)
void setIp (String ip)
void setPort (int port)
void send ()
Detailed Description
Definition at line 9 of file Conection.java.
Member Function Documentation
void Client.Conection.send () inline
Definition at line 103 of file Conection.java.
References Protobuf.GrSimCommands.grSim_Commands.Builder.addRobotCommands(), Protobuf.GrSimPacket.grSim_Packet.Builder.build(), Protobuf.GrSimCommands.grSim_Robot_Command.Builder.build(), Protobuf.GrSimCommands.grSim_Commands.Builder.build(), Protobuf.GrSimPacket.grSim_Packet.newBuilder(), Protobuf.GrSimCommands.grSim_Robot_Command.newBuilder(), Protobuf.GrSimCommands.grSim_Commands.newBuilder(), Protobuf.GrSimPacket.grSim_Packet.Builder.setCommands(), Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setId(), Protobuf.GrSimCommands.grSim_Commands.Builder.setIsteamyellow(), Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setKickspeedx(), Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setKickspeedz(), Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setSpinner(), Protobuf.GrSimCommands.grSim_Commands.Builder.setTimestamp(), Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setVelangular(), Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setVelnormal(), Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setVeltangent(), Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setWheel1(), Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setWheel2(), Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setWheel3(), Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setWheel4(), and Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setWheelsspeed().
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
                   {
     GrSimCommands.grSim_Robot_Command command = GrSimCommands.grSim_Robot_Command.newBuilder().setId(this.id).setWheel2(this.wheel2).setWheel1(this.wheel1).setWheel3(this.wheel3).setWheel4(this.wheel4).setKickspeedx(this.kickspeedx).setKickspeedz(this.kickspeedz).setVeltangent(this.velx).setVelnormal(this.vely).setVelangular(this.velz).setSpinner(this.spinner).setWheelsspeed(this.wheelSpeed).build();
     GrSimCommands.grSim_Commands command2 = GrSimCommands.grSim_Commands.newBuilder().setTimestamp(this.timeStamp).setIsteamyellow(this.teamYellow).addRobotCommands(command).build();
     GrSimPacket.grSim_Packet packet = GrSimPacket.grSim_Packet.newBuilder().setCommands(command2).build();
     String buffer = packet.toString();
     buffer2=packet.toByteArray();
     try{
         ds = new DatagramSocket();
         DatagramPacket dp = new DatagramPacket(buffer2, buffer2.length, InetAddress.getByName("127.0.0.1"),20011);
         ds.send(dp);
         System.out.println(buffer);
     }catch(Exception e){
         System.out.println(e);
     }
 }
void Client.Conection.setId (int id) inline
Definition at line 79 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.id=id;
 }
void Client.Conection.setIp (String ip) inline
Definition at line 95 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.ip=ip;
 }
void Client.Conection.setKickspeedX (float kickspeedx) inline
Definition at line 59 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.kickspeedx=kickspeedx;
 }
void Client.Conection.setKickspeedZ (float kickspeedz) inline
Definition at line 63 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.kickspeedz=kickspeedz;
 }
void Client.Conection.setPort (int port) inline
Definition at line 99 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.port=port;
 }
void Client.Conection.setSpinner (boolean spinner) inline
Definition at line 83 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.spinner=spinner;
 }
void Client.Conection.setTeamYellow (boolean teamYellow) inline
Definition at line 91 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.teamYellow=teamYellow;
 }
void Client.Conection.setTime (float timeStamp) inline
Definition at line 39 of file Conection.java.
{
     this.timeStamp=timeStamp;
 }
void Client.Conection.setVelX (float velx) inline
Definition at line 67 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.velx=velx;
 }
void Client.Conection.setVelY (float vely) inline
Definition at line 71 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.vely=vely;
 }
void Client.Conection.setVelZ (float velz) inline
Definition at line 75 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.velz=velz;
 }
void Client.Conection.setWheel1 (float wheel1) inline
Definition at line 43 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.wheel1=wheel1;
 }
void Client.Conection.setWheel2 (float wheel2) inline
Definition at line 47 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.wheel2=wheel2;
 }
void Client.Conection.setWheel3 (float wheel3) inline
Definition at line 51 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.wheel3=wheel3;
 }
void Client.Conection.setWheel4 (float wheel4) inline
Definition at line 55 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.wheel4=wheel4;
 }
void Client.Conection.setWheelSpeed (boolean wheelSpeed) inline
Definition at line 87 of file Conection.java.
Referenced by Client.Interface.jButton1ActionPerformed(), and Client.Interface.jButton2ActionPerformed().
{
     this.wheelSpeed=wheelSpeed;
 }
The documentation for this class was generated from the following file:
grSim/clients/java/src/Client/Conection.java