Documentation: VarTypes::VarTreeViewOptions Class Reference
VarTypes::VarTreeViewOptions Class Reference
An internal set of rendering parameters used by the VarTypes view-model.
#include <VarTreeViewOptions.h>
Public Member Functions
void setColumns (vector< GuiColumnFlag > v)
vector< GuiColumnFlag > getColumns () const
VarTreeViewOptions ()
virtual ~VarTreeViewOptions ()
Protected Attributes
vector< GuiColumnFlag > cols
Detailed Description
An internal set of rendering parameters used by the VarTypes view-model.
Author
Stefan Zickler, (C) 2008
See also
VarTypes.h
This file is part of the QT4 Item-Model for VarTypes. It is used when you want to edit/visualize VarTypes using QT4's model/view system.
If you don't know what VarTypes are, please see VarTypes.h
Definition at line 49 of file VarTreeViewOptions.h.
Constructor & Destructor Documentation
VarTypes::VarTreeViewOptions::VarTreeViewOptions ()
Definition at line 24 of file VarTreeViewOptions.cpp.
{
   }
VarTypes::VarTreeViewOptions::~VarTreeViewOptions () virtual
Definition at line 28 of file VarTreeViewOptions.cpp.
{
   }
Member Function Documentation
vector< GuiColumnFlag > VarTypes::VarTreeViewOptions::getColumns () const
Definition at line 35 of file VarTreeViewOptions.cpp.
References cols.
Referenced by VarTypes::VarTreeModel::updateHeader(), and VarTypes::VarItem::updateTree().
{
     return cols;
   }
void VarTypes::VarTreeViewOptions::setColumns (vector< GuiColumnFlag > v)
Definition at line 31 of file VarTreeViewOptions.cpp.
References cols, and v.
Referenced by VarTypes::VarTreeModel::resetViewOptions().
{
     cols=v;
   }
Field Documentation
vector<GuiColumnFlag> VarTypes::VarTreeViewOptions::cols protected
Definition at line 52 of file VarTreeViewOptions.h.
Referenced by getColumns(), and setColumns().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/vartypes/gui/VarTreeViewOptions.h
ssl-vision/src/shared/vartypes/gui/VarTreeViewOptions.cpp