Documentation: ssl-vision/src/shared/capture/capture_flycap.cpp File Reference
capture_flycap.cpp File Reference
C++ Interface: CaptureGigE.
#include "capture_flycap.h"
#include "capturedc1394v2.h"
#include "FlyCapture2.h"
#include "conversions.h"
#include "colors.h"
#include "VarTypes.h"
#include <iostream>
#include <sstream>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/poll.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
Functions
ColorFormat pixelFormatToColorFormat (PixelFormat pixel_format)
PixelFormat colorFormatToPixelFormat (ColorFormat color_format)
Mode videoModeFromString (string modestring)
Detailed Description
C++ Interface: CaptureGigE.
Author
Spencer Lane, (C) 2016
Definition in file capture_flycap.cpp.
Function Documentation
PixelFormat colorFormatToPixelFormat (ColorFormat color_format)
Definition at line 73 of file capture_flycap.cpp.
References COLOR_MONO16, COLOR_MONO8, COLOR_RAW16, COLOR_RAW8, COLOR_RGB16, COLOR_RGB8, COLOR_UNDEFINED, COLOR_YUV411, COLOR_YUV422_UYVY, and COLOR_YUV444.
Referenced by CaptureFlycap::writeParameterValues().
 {
    PixelFormat format;
    //fprintf(stderr, "Pixel Format: %i\n",(int)pixel_format);
    switch(color_format) {
      case COLOR_MONO8: format = PIXEL_FORMAT_MONO8; break;
      case COLOR_YUV411: format = PIXEL_FORMAT_411YUV8; break;//< YUV 4:1:1.
      case COLOR_YUV444: format = PIXEL_FORMAT_444YUV8; break;//< YUV 4:4:4.
      case COLOR_RGB8: format = PIXEL_FORMAT_RGB8; break;//< R = G = B = 8 bits.
      case COLOR_MONO16: format = PIXEL_FORMAT_MONO16; break;//< 16 bits of mono information.
      case COLOR_RGB16: format = PIXEL_FORMAT_RGB16; break;//< R = G = B = 16 bits.
      case COLOR_RAW8: format = PIXEL_FORMAT_RAW8; break;//< 8 bit raw data output of sensor.
      case COLOR_RAW16: format = PIXEL_FORMAT_RAW16; break;//< 16 bit raw data output of sensor.
      case COLOR_YUV422_UYVY: format = PIXEL_FORMAT_422YUV8; break;
      case COLOR_UNDEFINED: format = UNSPECIFIED_PIXEL_FORMAT; break; //< Unspecified pixel format.
      default: format = UNSPECIFIED_PIXEL_FORMAT; break;
    }
   return format;
 }
ColorFormat pixelFormatToColorFormat (PixelFormat pixel_format)
Definition at line 51 of file capture_flycap.cpp.
References COLOR_MONO16, COLOR_MONO8, COLOR_RAW16, COLOR_RAW8, COLOR_RGB16, COLOR_RGB8, COLOR_UNDEFINED, COLOR_YUV411, COLOR_YUV422_UYVY, and COLOR_YUV444.
Referenced by CaptureFlycap::getFrame().
 {
    ColorFormat format;
    //fprintf(stderr, "Pixel Format: %i\n",(int)pixel_format);
    switch(pixel_format) {
      case PIXEL_FORMAT_MONO8: format = COLOR_MONO8; break;
      case PIXEL_FORMAT_411YUV8: format = COLOR_YUV411; break;//< YUV 4:1:1.
      case PIXEL_FORMAT_444YUV8: format = COLOR_YUV444; break;//< YUV 4:4:4.
      case PIXEL_FORMAT_RGB8: format = COLOR_RGB8; break;//< R = G = B = 8 bits.
      case PIXEL_FORMAT_MONO16: format = COLOR_MONO16; break;//< 16 bits of mono information.
      case PIXEL_FORMAT_RGB16: format = COLOR_RGB16; break;//< R = G = B = 16 bits.
      case PIXEL_FORMAT_RAW8: format = COLOR_RAW8; break;//< 8 bit raw data output of sensor.
      case PIXEL_FORMAT_RAW16: format = COLOR_RAW16; break;//< 16 bit raw data output of sensor.
      case PIXEL_FORMAT_422YUV8: format = COLOR_YUV422_UYVY; break;
      case UNSPECIFIED_PIXEL_FORMAT: format = COLOR_UNDEFINED; break; //< Unspecified pixel format.
      default: format = COLOR_UNDEFINED; break;
    }
    //fprintf(stderr,"Color format: %i\n",(int)format);
    return format;
 }
Mode videoModeFromString (string modestring)
Definition at line 93 of file capture_flycap.cpp.
Referenced by CaptureFlycap::writeParameterValues().
 {
   Mode mode;
   if (modestring == "4") {
     mode = FlyCapture2::MODE_4;
   } else if (modestring == "7") {
     mode = FlyCapture2::MODE_7;
   } else {
     mode = FlyCapture2::MODE_4;
   }
   return mode;
 }