Documentation: ssl-vision/build/qrc_icons_gui.cxx File Reference
qrc_icons_gui.cxx File Reference
#include <QtCore/qglobal.h>
Functions
QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Q_CORE_EXPORT bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_icons_gui ()
int QT_MANGLE_NAMESPACE() qCleanupResources_icons_gui ()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Function Documentation
int QT_MANGLE_NAMESPACE() qCleanupResources_icons_gui ()
Definition at line 11559 of file qrc_icons_gui.cxx.
References qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
 {
     QT_PREPEND_NAMESPACE(qUnregisterResourceData)
        (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
     return 1;
 }
QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_icons_gui ()
Definition at line 11550 of file qrc_icons_gui.cxx.
References qRegisterResourceData(), qt_resource_data, qt_resource_name, and qt_resource_struct.
 {
     QT_PREPEND_NAMESPACE(qRegisterResourceData)
         (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
     return 1;
 }
QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool qRegisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qInitResources_icons_gui().
Q_CORE_EXPORT bool qUnregisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qCleanupResources_icons_gui().
Variable Documentation
const unsigned char qt_resource_data[] static
Definition at line 11 of file qrc_icons_gui.cxx.
Referenced by qCleanupResources_icons_gui(), and qInitResources_icons_gui().
const unsigned char qt_resource_name[] static
Definition at line 10856 of file qrc_icons_gui.cxx.
Referenced by qCleanupResources_icons_gui(), and qInitResources_icons_gui().
const unsigned char qt_resource_struct[] static
Definition at line 11349 of file qrc_icons_gui.cxx.
Referenced by qCleanupResources_icons_gui(), and qInitResources_icons_gui().