Documentation: StageCycleTimer< num > Class Template Reference
StageCycleTimer< num > Class Template Reference
#include <timer.h>
Public Member Functions
void start ()
void stage ()
void print (FILE *out=stdout)
int cycles (int stage)
void start ()
void stage ()
void print (FILE *out=stdout)
int cycles (int stage)
Private Attributes
cycle_t c [num+1]
unsigned n
Detailed Description
template<int num>
class StageCycleTimer< num >
Definition at line 200 of file timer.h.
Member Function Documentation
template<int num> int StageCycleTimer< num >::cycles (int stage) inline
Definition at line 209 of file timer.h.
     {return((int)(c[stage+1] - c[stage]));}
template<int num> int StageCycleTimer< num >::cycles (int stage) inline
Definition at line 209 of file timer.h.
References velocity.pid_::i, and StageCycleTimer< num >::print().
     {return((int)(c[stage+1] - c[stage]));}
template<int num> void StageCycleTimer< num >::print (FILE * out = stdout)
Definition at line 214 of file timer.h.
References velocity.pid_::i.
Referenced by StageCycleTimer< num >::cycles().
 {
   if(num){
     cycle_t tot = c[n] - c[0];
     for(unsigned i=0; i<n; i++){
       cycle_t dc = c[i+1] - c[i];
       fprintf(out,"  %d: %5.2f%% %d\n",i,100.0*dc/tot,dc);
     }
   }
 }
template<int num> void StageCycleTimer< num >::print (FILE * out = stdout)
template<int num> void StageCycleTimer< num >::stage () inline
Definition at line 206 of file timer.h.
References print().
     {if(n<num){n++; get_cycle(c[n]);}}
template<int num> void StageCycleTimer< num >::stage () inline
Definition at line 206 of file timer.h.
References print().
     {if(n<num){n++; get_cycle(c[n]);}}
template<int num> void StageCycleTimer< num >::start () inline
Definition at line 204 of file timer.h.
     {n=0; get_cycle(c[n]);}
template<int num> void StageCycleTimer< num >::start () inline
Definition at line 204 of file timer.h.
     {n=0; get_cycle(c[n]);}
Field Documentation
template<int num> cycle_t StageCycleTimer< num >::c private
Definition at line 201 of file timer.h.
template<int num> unsigned StageCycleTimer< num >::n private
Definition at line 202 of file timer.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/timer.h