Documentation: AccumulativeTimer Class Reference
AccumulativeTimer Class Reference
a basic timer class
#include <timer.h>
Public Member Functions
AccumulativeTimer ()
void clear ()
void start ()
void stop ()
double getTotal ()
void end ()
double time ()
double timeMSec ()
double timeUSec ()
double interval ()
double midtime ()
AccumulativeTimer ()
void clear ()
void start ()
void stop ()
double getTotal ()
void end ()
double time ()
double timeMSec ()
double timeUSec ()
double interval ()
double midtime ()
Private Attributes
timeval tv1
timeval tv2
double total
Detailed Description
a basic timer class
Author
James R. Bruce, (C) 1999-2002
Definition at line 74 of file timer.h.
Constructor & Destructor Documentation
AccumulativeTimer::AccumulativeTimer () inline
Definition at line 78 of file timer.h.
                       {
     clear();
   }
AccumulativeTimer::AccumulativeTimer () inline
Definition at line 78 of file timer.h.
                       {
     clear();
   }
Member Function Documentation
void AccumulativeTimer::clear () inline
Definition at line 81 of file timer.h.
                {
     total=0.0;
   }
void AccumulativeTimer::clear () inline
Definition at line 81 of file timer.h.
                {
     total=0.0;
   }
void AccumulativeTimer::end () inline
Definition at line 92 of file timer.h.
References Timer::stop().
 {stop();}
void AccumulativeTimer::end () inline
Definition at line 92 of file timer.h.
References Timer::stop().
 {stop();}
double AccumulativeTimer::getTotal () inline
Definition at line 89 of file timer.h.
                     {
     return total;
   }
double AccumulativeTimer::getTotal () inline
Definition at line 89 of file timer.h.
                     {
     return total;
   }
double AccumulativeTimer::interval () inline
Definition at line 98 of file timer.h.
References t, Timer::time(), and Timer::tv2.
                    {
     double t;
     gettimeofday(&tv2,NULL);
     t = time();
     tv1 = tv2;
     return(t);
   }
double AccumulativeTimer::interval () inline
Definition at line 98 of file timer.h.
References t, Timer::time(), and Timer::tv2.
                    {
     double t;
     gettimeofday(&tv2,NULL);
     t = time();
     tv1 = tv2;
     return(t);
   }
double AccumulativeTimer::midtime () inline
Definition at line 105 of file timer.h.
                    {
     timeval tmp;
     gettimeofday(&tmp,NULL);
     return((tmp.tv_sec - tv1.tv_sec) +
                         (tmp.tv_usec - tv1.tv_usec) * 1.0E-6);
   }
double AccumulativeTimer::midtime () inline
Definition at line 105 of file timer.h.
                    {
     timeval tmp;
     gettimeofday(&tmp,NULL);
     return((tmp.tv_sec - tv1.tv_sec) +
                         (tmp.tv_usec - tv1.tv_usec) * 1.0E-6);
   }
void AccumulativeTimer::start () inline
Definition at line 84 of file timer.h.
 {gettimeofday(&tv1,NULL);}
void AccumulativeTimer::start () inline
Definition at line 84 of file timer.h.
 {gettimeofday(&tv1,NULL);}
void AccumulativeTimer::stop () inline
Definition at line 85 of file timer.h.
References Timer::time().
                 {
     gettimeofday(&tv2,NULL);
     total+=time();
   }
void AccumulativeTimer::stop () inline
Definition at line 85 of file timer.h.
References Timer::time().
                 {
     gettimeofday(&tv2,NULL);
     total+=time();
   }
double AccumulativeTimer::time () inline
Definition at line 93 of file timer.h.
                 {return((tv2.tv_sec - tv1.tv_sec) +
                         (tv2.tv_usec - tv1.tv_usec) * 1.0E-6);}
double AccumulativeTimer::time () inline
Definition at line 93 of file timer.h.
                 {return((tv2.tv_sec - tv1.tv_sec) +
                         (tv2.tv_usec - tv1.tv_usec) * 1.0E-6);}
double AccumulativeTimer::timeMSec () inline
Definition at line 95 of file timer.h.
References Timer::time().
 {return(time() * 1.0E3);}
double AccumulativeTimer::timeMSec () inline
Definition at line 95 of file timer.h.
References Timer::time().
 {return(time() * 1.0E3);}
double AccumulativeTimer::timeUSec () inline
Definition at line 96 of file timer.h.
References Timer::time().
 {return(time() * 1.0E6);}
double AccumulativeTimer::timeUSec () inline
Definition at line 96 of file timer.h.
References Timer::time().
 {return(time() * 1.0E6);}
Field Documentation
double AccumulativeTimer::total private
Definition at line 76 of file timer.h.
timeval AccumulativeTimer::tv1 private
Definition at line 75 of file timer.h.
timeval AccumulativeTimer::tv2 private
Definition at line 75 of file timer.h.
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/timer.h