Documentation: GLSoccerView Class Reference
GLSoccerView Class Reference
#include <soccerview.h>
Data Structures
struct FieldDimensions
struct Robot
Public Types
enum TeamTypes { teamUnknown = 0, teamBlue, teamYellow }
Public Slots
void resetView ()
Signals
void postRedraw ()
Public Member Functions
GLSoccerView (QWidget *parent=0)
void updateDetection (const SSL_DetectionFrame &detection)
void updateFieldGeometry (const SSL_GeometryFieldSize &fieldSize)
Protected Member Functions
void paintEvent (QPaintEvent *event)
void wheelEvent (QWheelEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void keyPressEvent (QKeyEvent *event)
void resizeEvent (QResizeEvent *event)
void initializeGL ()
void resizeGL (int width, int height)
QSize sizeHint () const
Private Slots
void redraw ()
Private Member Functions
void drawFieldLines (FieldDimensions &dimensions)
void drawRobots ()
void drawBalls ()
void drawQuad (vector2d loc1, vector2d loc2, double z=0.0)
void drawQuad (double x1, double y1, double x2, double y2, double z=0.0)
void drawArc (vector2d loc, double r1, double r2, double theta1, double theta2, double z=0.0, double dTheta=-1)
void drawArc (double x, double y, double r1, double r2, double theta1, double theta2, double z=0.0, double dTheta=-1)
void recomputeProjection ()
void drawRobot (vector2d loc, double theta, double conf, int robotID, int team, bool hasAngle)
void drawRobot (int team, bool hasAngle, bool useDisplayLists)
int UpdateBalls (QVector< QPointF > &_balls, int cameraID)
void drawBall (vector2d loc)
void vectorTextTest ()
Private Attributes
QVector< QVector< Robot > > robots
QVector< QVector< vector2d > > balls
QMutex graphicsMutex
GLText glText
GLuint blueRobotShape
GLuint yellowRobotShape
GLuint greyRobotShape
GLuint blueCircleRobotShape
GLuint yellowCircleRobotShape
GLuint greyCircleRobotShape
double viewScale
double viewXOffset
Ratio of world space to screen space coordinates.
double viewYOffset
bool leftButton
bool midButton
bool rightButton
int mouseStartX
int mouseStartY
double tLastRedraw
FieldDimensions fieldDim
Static Private Attributes
static const double minZValue = -10
static const double maxZValue = 10
static const double FieldZ = 1.0
static const double RobotZ = 2.0
static const double BallZ = 3.0
static const int PreferedWidth = 1024
static const int PreferedHeight = 768
static const double MinRedrawInterval = 0.016
static const int unknownRobotID = -1
Minimum time between graphics updates (limits the fps)
Detailed Description
Definition at line 47 of file soccerview.h.
Member Enumeration Documentation
enum GLSoccerView::TeamTypes
Enumerator
teamUnknown
teamBlue
teamYellow
Definition at line 70 of file soccerview.h.
               {
     teamUnknown = 0,
     teamBlue,
     teamYellow
   }TeamTypes;
Constructor & Destructor Documentation
GLSoccerView::GLSoccerView (QWidget * parent = 0)
Definition at line 54 of file soccerview.cpp.
References blueCircleRobotShape, blueRobotShape, GLSoccerView::FieldDimensions::boundary_width, GLSoccerView::FieldDimensions::field_length, GLSoccerView::FieldDimensions::field_width, fieldDim, glText, greyCircleRobotShape, greyRobotShape, GVector::max(), postRedraw(), redraw(), sizeHint(), tLastRedraw, viewScale, viewXOffset, viewYOffset, yellowCircleRobotShape, and yellowRobotShape.
                                           :
     QGLWidget(QGLFormat(
         QGL::DoubleBuffer | QGL::DepthBuffer | QGL::SampleBuffers),parent) {
   viewScale =
       (fieldDim.field_length + fieldDim.boundary_width) / sizeHint().width();
   viewScale = max(viewScale,
                   (fieldDim.field_width + fieldDim.boundary_width) /
                       sizeHint().height());
   viewXOffset = viewYOffset = 0.0;
   setAutoFillBackground(false); //Do not let painter auto fill the widget's background: we'll do it manually through openGl
   connect(this, SIGNAL(postRedraw()), this, SLOT(redraw()));
   blueRobotShape = GL_INVALID_VALUE;
   yellowRobotShape = GL_INVALID_VALUE;
   greyRobotShape = GL_INVALID_VALUE;
   blueCircleRobotShape = GL_INVALID_VALUE;
   yellowCircleRobotShape = GL_INVALID_VALUE;
   greyCircleRobotShape = GL_INVALID_VALUE;
   QFont RobotIDFont = this->font();
   RobotIDFont.setWeight(QFont::Bold);
   RobotIDFont.setPointSize(80);
   glText = GLText(RobotIDFont);
   tLastRedraw = 0;
 }
Member Function Documentation
void GLSoccerView::drawArc (vector2d loc, double r1, double r2, double theta1, double theta2, double z = 0.0, double dTheta = -1) private
Definition at line 306 of file soccerview.cpp.
References bot_comm::theta, GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
Referenced by drawBall(), drawFieldLines(), and drawRobot().
 {
   static const double tesselation = 1.0;
   if(dTheta<0){
     dTheta = tesselation/r2;
   }
   glBegin(GL_QUAD_STRIP);
   for(double theta=theta1; theta<theta2; theta+=dTheta){
     double c1 = cos(theta), s1 = sin(theta);
     glVertex3d(r2*c1+loc.x,r2*s1+loc.y,z);
     glVertex3d(r1*c1+loc.x,r1*s1+loc.y,z);
   }
   double c1 = cos(theta2), s1 = sin(theta2);
   glVertex3d(r2*c1+loc.x,r2*s1+loc.y,z);
   glVertex3d(r1*c1+loc.x,r1*s1+loc.y,z);
   glEnd();
 }
void GLSoccerView::drawArc (double x, double y, double r1, double r2, double theta1, double theta2, double z = 0.0, double dTheta = -1) inline private
Definition at line 120 of file soccerview.h.
References drawArc(), and bot_comm::theta.
Referenced by drawArc().
 {drawArc(vector2d(x,y),r1,r2,theta1,theta2,z,dTheta);}
void GLSoccerView::drawBall (vector2d loc) private
Definition at line 474 of file soccerview.cpp.
References BallZ, and drawArc().
Referenced by drawBalls().
 {
   glColor3d(1.0,0.5059,0.0);
   drawArc(loc,0,16,-M_PI,M_PI,BallZ);
   glColor3d(0.8706,0.3490,0.0);
   drawArc(loc,15,21,-M_PI,M_PI,BallZ);
 }
void GLSoccerView::drawBalls () private
Definition at line 483 of file soccerview.cpp.
References balls, drawBall(), and velocity.pid_::i.
Referenced by paintEvent().
 {
   for(int i=0; i<balls.size(); i++){
     for(int j=0; j<balls[i].size(); j++){
       drawBall(balls[i][j]);
     }
   }
 }
void GLSoccerView::drawFieldLines (FieldDimensions & dimensions) private
Definition at line 448 of file soccerview.cpp.
References FieldCircularArc::a1, FieldCircularArc::a2, GLSoccerView::FieldDimensions::arcs, FieldCircularArc::center_x, FieldCircularArc::center_y, drawArc(), drawQuad(), FIELD_LINES_COLOR, fieldDim, FieldZ, VarTypes::VarDoubleVal::getDouble(), velocity.pid_::i, GLSoccerView::FieldDimensions::lines, FieldLine::p1_x, FieldLine::p1_y, FieldLine::p2_x, FieldLine::p2_y, GVector::vector2d< num >::perp(), radius, FieldCircularArc::radius, FieldLine::thickness, and FieldCircularArc::thickness.
Referenced by paintEvent().
 {
   glColor4f(FIELD_LINES_COLOR);
   for (size_t i = 0; i < fieldDim.lines.size(); ++i) {
     const FieldLine& line = *fieldDim.lines[i];
     const double half_thickness = 0.5 * line.thickness->getDouble();
     const vector2d p1(line.p1_x->getDouble(), line.p1_y->getDouble());
     const vector2d p2(line.p2_x->getDouble(), line.p2_y->getDouble());
     const vector2d perp = (p2 - p1).norm().perp();
     const vector2d corner1 = p1 - half_thickness * perp;
     const vector2d corner2 = p2 + half_thickness * perp;
     drawQuad(corner1, corner2, FieldZ);
   }
   for (size_t i = 0; i < fieldDim.arcs.size(); ++i) {
     const FieldCircularArc& arc = *fieldDim.arcs[i];
     const double half_thickness = 0.5 * arc.thickness->getDouble();
     const double radius = arc.radius->getDouble();
     const vector2d center(arc.center_x->getDouble(), arc.center_y->getDouble());
     const double a1 = arc.a1->getDouble();
     const double a2 = arc.a2->getDouble();
     drawArc(center, radius - half_thickness, radius + half_thickness, a1, a2,
             FieldZ);
   }
 }
void GLSoccerView::drawQuad (vector2d loc1, vector2d loc2, double z = 0.0) private
Definition at line 296 of file soccerview.cpp.
References GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
Referenced by drawFieldLines(), and drawRobot().
 {
   glBegin(GL_QUADS);
   glVertex3d(loc1.x,loc1.y,z);
   glVertex3d(loc2.x,loc1.y,z);
   glVertex3d(loc2.x,loc2.y,z);
   glVertex3d(loc1.x,loc2.y,z);
   glEnd();
 }
void GLSoccerView::drawQuad (double x1, double y1, double x2, double y2, double z = 0.0) inline private
Definition at line 118 of file soccerview.h.
References drawQuad().
Referenced by drawQuad().
 {drawQuad(vector2d(x1,y1),vector2d(x2,y2),z);}
void GLSoccerView::drawRobot (vector2d loc, double theta, double conf, int robotID, int team, bool hasAngle) private
Definition at line 397 of file soccerview.cpp.
References buf, GLText::CenterAligned, drawQuad(), GLText::drawString(), glText, GLText::MiddleAligned, RobotZ, teamBlue, teamYellow, unknownRobotID, GVector::vector2d< num >::x, and GVector::vector2d< num >::y.
Referenced by drawRobots(), and initializeGL().
 {
   glPushMatrix();
   glLoadIdentity();
   glTranslated(loc.x,loc.y,0);
   switch ( team ){
     case teamBlue:{
       glColor3d(0.2549, 0.4941, 1.0);
       break;
     }
     case teamYellow:{
       glColor3d(1.0, 0.9529, 0.2431);
       break;
     }
     default:{
       glColor3d(0.5882,0.5882,0.5882);
       break;
     }
   }
   drawQuad(-90,130,-90.0+180.0*conf,160,RobotZ);
   glColor3d(0.0,0.0,0.0);
   char buf[1024];
   if(robotID!=unknownRobotID)
     snprintf(buf,1023,"%X",robotID);
   else
     snprintf(buf,1023,"?");
   glText.drawString(loc,0,100,buf,GLText::CenterAligned,GLText::MiddleAligned);
   switch ( team ){
     case teamBlue:{
       glColor3d(0.0706, 0.2314, 0.6275);
       break;
     }
     case teamYellow:{
       glColor3d(0.8, 0.6157, 0.0);
       break;
     }
     default:{
       glColor3d(0.2745,0.2745,0.2745);
       break;
     }
   }
   drawQuad(-96,124,96.0,130,RobotZ+0.01);
   drawQuad(-96,124,-90.0,166,RobotZ+0.01);
   drawQuad(-96,160,96.0,166,RobotZ+0.01);
   drawQuad(90,124,96.0,166,RobotZ+0.01);
   glRotated(theta,0,0,1.0);
   drawRobot(team, hasAngle, true);
   glPopMatrix();
 }
void GLSoccerView::drawRobot (int team, bool hasAngle, bool useDisplayLists) private
Definition at line 324 of file soccerview.cpp.
References blueCircleRobotShape, blueRobotShape, drawArc(), drawQuad(), greyCircleRobotShape, greyRobotShape, RAD, RobotZ, teamBlue, teamYellow, yellowCircleRobotShape, and yellowRobotShape.
 {
   if(useDisplayLists){
     switch ( team ){
       case teamBlue:{
         if(hasAngle)
           glCallList(blueRobotShape);
         else
           glCallList(blueCircleRobotShape);
         break;
       }
       case teamYellow:{
         if(hasAngle)
           glCallList(yellowRobotShape);
         else
           glCallList(yellowCircleRobotShape);
         break;
       }
       default:{
         if(hasAngle)
           glCallList(greyRobotShape);
         else
           glCallList(greyCircleRobotShape);
         break;
       }
     }
     return;
   }
   switch ( team ){
     case teamBlue:{
       glColor3d(0.2549, 0.4941, 1.0);
       break;
     }
     case teamYellow:{
       glColor3d(1.0, 0.9529, 0.2431);
       break;
     }
     default:{
       glColor3d(0.5882,0.5882,0.5882);
       break;
     }
   }
   double theta1 = hasAngle?RAD(40):0.0;
   double theta2 = 2.0*M_PI - theta1;
   drawArc(0,0,0,90,theta1, theta2, RobotZ);
   if(hasAngle){
     glBegin(GL_TRIANGLES);
     glVertex3d(0,0,RobotZ);
     glVertex3d(90.0*cos(theta1),90.0*sin(theta1),RobotZ);
     glVertex3d(90.0*cos(theta2),90.0*sin(theta2),RobotZ);
     glEnd();
   }
   switch ( team ){
     case teamBlue:{
       glColor3d(0.0706, 0.2314, 0.6275);
       break;
     }
     case teamYellow:{
       glColor3d(0.8, 0.6157, 0.0);
       break;
     }
     default:{
       glColor3d(0.2745,0.2745,0.2745);
       break;
     }
   }
   drawArc(0,0,80,90,theta1, theta2, RobotZ+0.01);
   if(hasAngle)
     drawQuad(90.0*cos(theta1)-10,90.0*sin(theta1), 90.0*cos(theta2),90.0*sin(theta2),RobotZ+0.01);
 }
void GLSoccerView::drawRobots () private
Definition at line 492 of file soccerview.cpp.
References GLSoccerView::Robot::angle, GLSoccerView::Robot::conf, drawRobot(), GLSoccerView::Robot::hasAngle, velocity.pid_::i, GLSoccerView::Robot::id, GLSoccerView::Robot::loc, robots, and GLSoccerView::Robot::team.
Referenced by paintEvent().
 {
   for(int i=0; i<robots.size(); i++){
     for(int j=0; j<robots[i].size(); j++){
       Robot r = robots[i][j];
       drawRobot(r.loc,r.angle,r.conf,r.id,r.team,r.hasAngle);
     }
   }
 }
void GLSoccerView::initializeGL () protected
Definition at line 193 of file soccerview.cpp.
References blueCircleRobotShape, blueRobotShape, drawRobot(), greyCircleRobotShape, greyRobotShape, teamBlue, teamUnknown, teamYellow, yellowCircleRobotShape, and yellowRobotShape.
 {
   blueRobotShape = glGenLists(1);
   if(blueRobotShape==GL_INVALID_VALUE){
     printf("Unable to create display list!\n");
     exit(1);
   }
   glNewList(blueRobotShape, GL_COMPILE);
   drawRobot(teamBlue,true,false);
   glEndList();
   yellowRobotShape = glGenLists(1);
   if(yellowRobotShape==GL_INVALID_VALUE){
     printf("Unable to create display list!\n");
     exit(1);
   }
   glNewList(yellowRobotShape, GL_COMPILE);
   drawRobot(teamYellow,true,false);
   glEndList();
   greyRobotShape = glGenLists(1);
   if(greyRobotShape==GL_INVALID_VALUE){
     printf("Unable to create display list!\n");
     exit(1);
   }
   glNewList(greyRobotShape, GL_COMPILE);
   drawRobot(teamUnknown,true,false);
   glEndList();
   blueCircleRobotShape = glGenLists(1);
   if(blueRobotShape==GL_INVALID_VALUE){
     printf("Unable to create display list!\n");
     exit(1);
   }
   glNewList(blueCircleRobotShape, GL_COMPILE);
   drawRobot(teamBlue,false,false);
   glEndList();
   yellowCircleRobotShape = glGenLists(1);
   if(yellowRobotShape==GL_INVALID_VALUE){
     printf("Unable to create display list!\n");
     exit(1);
   }
   glNewList(yellowCircleRobotShape, GL_COMPILE);
   drawRobot(teamYellow,false,false);
   glEndList();
   greyCircleRobotShape = glGenLists(1);
   if(greyRobotShape==GL_INVALID_VALUE){
     printf("Unable to create display list!\n");
     exit(1);
   }
   glNewList(greyCircleRobotShape, GL_COMPILE);
   drawRobot(teamUnknown,false,false);
   glEndList();
 }
void GLSoccerView::keyPressEvent (QKeyEvent * event) protected
Definition at line 151 of file soccerview.cpp.
References role.sGoalie::debug(), and resetView().
 {
   static const bool debug = false;
   if(debug) printf("KeyPress: 0x%08X\n",event->key());
   if(event->key() == Qt::Key_Space)
     resetView();
   if(event->key() == Qt::Key_Escape)
     close();
 }
void GLSoccerView::mouseMoveEvent (QMouseEvent * event) protected
Definition at line 113 of file soccerview.cpp.
References role.sGoalie::debug(), leftButton, midButton, mouseStartX, mouseStartY, postRedraw(), recomputeProjection(), rightButton, viewScale, viewXOffset, and viewYOffset.
 {
   static const bool debug = false;
   bool leftButton = event->buttons().testFlag(Qt::LeftButton);
   bool midButton = event->buttons().testFlag(Qt::MidButton);
   bool rightButton = event->buttons().testFlag(Qt::RightButton);
   if(debug) printf("MouseMove Event, Left:%d Mid:%d Right:%d\n", leftButton?1:0, midButton?1:0, rightButton?1:0);
   if(leftButton){
     //Pan
     viewXOffset -= viewScale*double(event->x() - mouseStartX);
     viewYOffset += viewScale*double(event->y() - mouseStartY);
     mouseStartX = event->x();
     mouseStartY = event->y();
     recomputeProjection();
     postRedraw();
   }else if(midButton){
     //Zoom
     double zoomRatio = double(event->y() - mouseStartY)/500.0;
     viewScale = viewScale*(1.0+zoomRatio);
     recomputeProjection();
     mouseStartX = event->x();
     mouseStartY = event->y();
     postRedraw();
   }
 }
void GLSoccerView::mousePressEvent (QMouseEvent * event) protected
Definition at line 90 of file soccerview.cpp.
References leftButton, midButton, mouseStartX, mouseStartY, postRedraw(), and rightButton.
 {
   leftButton = event->buttons().testFlag(Qt::LeftButton);
   midButton = event->buttons().testFlag(Qt::MidButton);
   rightButton = event->buttons().testFlag(Qt::RightButton);
   if(leftButton)
     setCursor(Qt::ClosedHandCursor);
   if(midButton)
     setCursor(Qt::SizeVerCursor);
   if(leftButton || midButton){
     // Start Pan / Zoom
     mouseStartX = event->x();
     mouseStartY = event->y();
     postRedraw();
   }
 }
void GLSoccerView::mouseReleaseEvent (QMouseEvent * event) protected
Definition at line 108 of file soccerview.cpp.
 {
   setCursor(Qt::ArrowCursor);
 }
void GLSoccerView::paintEvent (QPaintEvent * event) protected
Definition at line 272 of file soccerview.cpp.
References drawBalls(), drawFieldLines(), drawRobots(), FIELD_COLOR, fieldDim, and graphicsMutex.
 {
   graphicsMutex.lock();
   makeCurrent();
   glClearColor(FIELD_COLOR);
   glShadeModel(GL_SMOOTH);
   glDisable(GL_LIGHTING);
   glDisable(GL_CULL_FACE);
   glEnable(GL_DEPTH_TEST);
   glEnable(GL_MULTISAMPLE);
   glClear (GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
   glMatrixMode(GL_MODELVIEW);
   glPushMatrix();
   glLoadIdentity();
   drawFieldLines(fieldDim);
   drawRobots();
   drawBalls();
   //vectorTextTest();
   glPopMatrix();
   swapBuffers();
   graphicsMutex.unlock();
 }
void GLSoccerView::postRedraw () signal
Definition at line 102 of file moc_soccerview.cxx.
Referenced by GLSoccerView(), mouseMoveEvent(), mousePressEvent(), resetView(), updateDetection(), and wheelEvent().
 {
     QMetaObject::activate(this, &staticMetaObject, 0, 0);
 }
void GLSoccerView::recomputeProjection () private
Definition at line 179 of file soccerview.cpp.
References maxZValue, minZValue, viewScale, viewXOffset, and viewYOffset.
Referenced by mouseMoveEvent(), resetView(), resizeGL(), and wheelEvent().
 {
   glMatrixMode(GL_PROJECTION);
   glLoadIdentity();
   glOrtho(-0.5*viewScale*width()+viewXOffset, 0.5*viewScale*width()+viewXOffset, -0.5*viewScale*height()+viewYOffset, 0.5*viewScale*height()+viewYOffset, minZValue, maxZValue);
   glMatrixMode(GL_MODELVIEW);
 }
void GLSoccerView::redraw () private slot
Definition at line 79 of file soccerview.cpp.
References GetTimeSec(), graphicsMutex, MinRedrawInterval, and tLastRedraw.
Referenced by GLSoccerView(), and resizeEvent().
 {
   if(GetTimeSec()-tLastRedraw<MinRedrawInterval)
     return;
   graphicsMutex.lock();
   update();
   graphicsMutex.unlock();
   tLastRedraw = GetTimeSec();
 }
void GLSoccerView::resetView () slot
Definition at line 161 of file soccerview.cpp.
References GLSoccerView::FieldDimensions::boundary_width, GLSoccerView::FieldDimensions::field_length, GLSoccerView::FieldDimensions::field_width, fieldDim, GVector::max(), postRedraw(), recomputeProjection(), viewScale, viewXOffset, and viewYOffset.
Referenced by keyPressEvent().
 {
   viewScale =
       (fieldDim.field_length + fieldDim.boundary_width) / width();
   viewScale = max(viewScale,
                   (fieldDim.field_width + fieldDim.boundary_width) / height());
   viewXOffset = viewYOffset = 0.0;
   recomputeProjection();
   postRedraw();
 }
void GLSoccerView::resizeEvent (QResizeEvent * event) protected
Definition at line 173 of file soccerview.cpp.
References redraw().
 {
   QGLWidget::resizeEvent(event);
   redraw();
 }
void GLSoccerView::resizeGL (int width, int height) protected
Definition at line 187 of file soccerview.cpp.
References recomputeProjection().
 {
   glViewport(0, 0, width, height);
   recomputeProjection();
 }
QSize GLSoccerView::sizeHint () const inline protected
Definition at line 138 of file soccerview.h.
Referenced by GLSoccerView().
 {return QSize(PreferedWidth,PreferedHeight);}
int GLSoccerView::UpdateBalls (QVector< QPointF > & _balls, int cameraID) private
void GLSoccerView::updateDetection (const SSL_DetectionFrame & detection)
Definition at line 502 of file soccerview.cpp.
References GLSoccerView::Robot::angle, balls, GLSoccerView::Robot::cameraID, GLSoccerView::Robot::conf, DEG, graphicsMutex, GLSoccerView::Robot::hasAngle, velocity.pid_::i, GLSoccerView::Robot::id, GLSoccerView::Robot::loc, postRedraw(), robots, GVector::vector2d< num >::set(), GLSoccerView::Robot::team, teamBlue, teamYellow, and unknownRobotID.
Referenced by MyThread::run().
 {
   int numBlueRobots =  detection.robots_blue_size();
   int numYellowRobots =  detection.robots_yellow_size();
   int numBalls = detection.balls_size();
   SSL_DetectionRobot sslRobot;
   Robot robot;
   SSL_DetectionBall sslBall;
   vector2d ball;
   int cam = detection.camera_id();
   graphicsMutex.lock();
   if(cam+1>robots.size()){
     robots.resize(cam+1);
   }
   if(cam+1>balls.size()){
     balls.resize(cam+1);
   }
   robots[cam].clear();
   balls[cam].clear();
   for(int i=0; i<numBlueRobots; i++){
     sslRobot = detection.robots_blue(i);
     robot.loc.set(sslRobot.x(), sslRobot.y());
     if(sslRobot.has_robot_id())
       robot.id = sslRobot.robot_id();
     else
       robot.id = unknownRobotID;
     robot.hasAngle = sslRobot.has_orientation();
     if(robot.hasAngle)
       robot.angle = DEG(sslRobot.orientation());
     robot.team = teamBlue;
     robot.cameraID = detection.camera_id();
     robot.conf = sslRobot.confidence();
     robots[cam].append(robot);
   }
   for(int i=0; i<numYellowRobots; i++){
     sslRobot = detection.robots_yellow(i);
     robot.loc.set(sslRobot.x(), sslRobot.y());
     if(sslRobot.has_robot_id())
       robot.id = sslRobot.robot_id();
     else
       robot.id = unknownRobotID;
     robot.hasAngle = sslRobot.has_orientation();
     if(robot.hasAngle)
       robot.angle = DEG(sslRobot.orientation());
     robot.team = teamYellow;
     robot.cameraID = detection.camera_id();
     robot.conf = sslRobot.confidence();
     robots[cam].append(robot);
   }
   for(int i=0; i<numBalls; i++){
     sslBall = detection.balls(i);
     ball.set(sslBall.x(), sslBall.y());
     balls[cam].append(ball);
   }
   graphicsMutex.unlock();
   postRedraw();
 }
void GLSoccerView::updateFieldGeometry (const SSL_GeometryFieldSize & fieldSize)
Definition at line 564 of file soccerview.cpp.
References GLSoccerView::FieldDimensions::arcs, fieldDim, graphicsMutex, velocity.pid_::i, and GLSoccerView::FieldDimensions::lines.
Referenced by MyThread::run().
{
   graphicsMutex.lock();
   for (size_t i = 0; i < fieldDim.lines.size(); ++i) {
     delete fieldDim.lines[i];
   }
   fieldDim.lines.clear();
   for (int i = 0; i < fieldSize.field_lines_size(); ++i) {
     const SSL_FieldLineSegment& line = fieldSize.field_lines(i);
     fieldDim.lines.push_back(new FieldLine(
         line.name(), line.p1().x(), line.p1().y(),
         line.p2().x(), line.p2().y(), line.thickness()));
   }
   for (size_t i = 0; i < fieldDim.arcs.size(); ++i) {
     delete fieldDim.arcs[i];
   }
   fieldDim.arcs.clear();
   for (int i = 0; i < fieldSize.field_arcs_size(); ++i) {
     const SSL_FieldCicularArc& arc = fieldSize.field_arcs(i);
     fieldDim.arcs.push_back(new FieldCircularArc(
         arc.name(), arc.center().x(), arc.center().y(),  arc.radius(),
         arc.a1(), arc.a2(), arc.thickness()));
   }
   graphicsMutex.unlock();
 }
void GLSoccerView::vectorTextTest () private
Definition at line 251 of file soccerview.cpp.
References GLText::BottomAligned, GLText::CenterAligned, GLSoccerView::FieldDimensions::field_length, GLSoccerView::FieldDimensions::field_width, fieldDim, GLText::LeftAligned, GLText::MedianAligned, GLText::MiddleAligned, GLText::RightAligned, TextTest, and GLText::TopAligned.
 {
   #define TextTest(loc,angle,size,str,halign,valign) \
   {glText.drawString((loc),angle,size,str,halign,valign); \
   vector2d l1,l2; \
   l1.heading(M_PI/180.0*angle); \
   l1 = loc+l1*size*(glText.getWidth(str)); \
   l2.heading(M_PI/180.0*angle); \
   l2 = loc-l2*size*(glText.getWidth(str)); \
   glBegin(GL_LINES); \
   glVertex3d(l1.x,l1.y,9); \
   glVertex3d(l2.x,l2.y,9); \
   glEnd();}
   glColor3d(1,1,1);
   TextTest(vector2d(1,1)*353.6,45,500,"123agdo0",GLText::LeftAligned,GLText::MedianAligned)
   TextTest(vector2d(fieldDim.field_length*0.5,0),0,500,"123agdo0",GLText::RightAligned,GLText::BottomAligned)
   TextTest(vector2d(0,-fieldDim.field_width*0.5),0,500,"123agdo0",GLText::CenterAligned,GLText::TopAligned)
   TextTest(vector2d(-fieldDim.field_length*0.5,0),0,500,"1\ub023agdo0",GLText::CenterAligned,GLText::MiddleAligned)
 }
void GLSoccerView::wheelEvent (QWheelEvent * event) protected
Definition at line 141 of file soccerview.cpp.
References role.sGoalie::debug(), postRedraw(), recomputeProjection(), and viewScale.
 {
   static const bool debug = false;
   double zoomRatio = -double(event->delta())/1000.0;
   viewScale = viewScale*(1.0+zoomRatio);
   recomputeProjection();
   if(debug) printf("Zoom: %5.3f\n",viewScale);
   postRedraw();
 }
Field Documentation
QVector<QVector<vector2d> > GLSoccerView::balls private
Definition at line 88 of file soccerview.h.
Referenced by drawBalls(), and updateDetection().
const double GLSoccerView::BallZ = 3.0 static private
Definition at line 81 of file soccerview.h.
Referenced by drawBall().
GLuint GLSoccerView::blueCircleRobotShape private
Definition at line 95 of file soccerview.h.
Referenced by drawRobot(), GLSoccerView(), and initializeGL().
GLuint GLSoccerView::blueRobotShape private
Definition at line 92 of file soccerview.h.
Referenced by drawRobot(), GLSoccerView(), and initializeGL().
FieldDimensions GLSoccerView::fieldDim private
Definition at line 111 of file soccerview.h.
Referenced by drawFieldLines(), GLSoccerView(), paintEvent(), resetView(), updateFieldGeometry(), and vectorTextTest().
const double GLSoccerView::FieldZ = 1.0 static private
Definition at line 79 of file soccerview.h.
Referenced by drawFieldLines().
GLText GLSoccerView::glText private
Definition at line 90 of file soccerview.h.
Referenced by drawRobot(), and GLSoccerView().
QMutex GLSoccerView::graphicsMutex private
Definition at line 89 of file soccerview.h.
Referenced by paintEvent(), redraw(), updateDetection(), and updateFieldGeometry().
GLuint GLSoccerView::greyCircleRobotShape private
Definition at line 97 of file soccerview.h.
Referenced by drawRobot(), GLSoccerView(), and initializeGL().
GLuint GLSoccerView::greyRobotShape private
Definition at line 94 of file soccerview.h.
Referenced by drawRobot(), GLSoccerView(), and initializeGL().
bool GLSoccerView::leftButton private
Definition at line 103 of file soccerview.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
const double GLSoccerView::maxZValue = 10 static private
Definition at line 78 of file soccerview.h.
Referenced by recomputeProjection().
bool GLSoccerView::midButton private
Definition at line 104 of file soccerview.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
const double GLSoccerView::MinRedrawInterval = 0.016 static private
Definition at line 84 of file soccerview.h.
Referenced by redraw().
const double GLSoccerView::minZValue = -10 static private
Definition at line 77 of file soccerview.h.
Referenced by recomputeProjection().
int GLSoccerView::mouseStartX private
Definition at line 106 of file soccerview.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
int GLSoccerView::mouseStartY private
Definition at line 107 of file soccerview.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
const int GLSoccerView::PreferedHeight = 768 static private
Definition at line 83 of file soccerview.h.
const int GLSoccerView::PreferedWidth = 1024 static private
Definition at line 82 of file soccerview.h.
bool GLSoccerView::rightButton private
Definition at line 105 of file soccerview.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QVector<QVector<Robot> > GLSoccerView::robots private
Definition at line 87 of file soccerview.h.
Referenced by drawRobots(), and updateDetection().
const double GLSoccerView::RobotZ = 2.0 static private
Definition at line 80 of file soccerview.h.
Referenced by drawRobot().
double GLSoccerView::tLastRedraw private
Definition at line 109 of file soccerview.h.
Referenced by GLSoccerView(), and redraw().
const int GLSoccerView::unknownRobotID = -1 static private
Minimum time between graphics updates (limits the fps)
Definition at line 85 of file soccerview.h.
Referenced by drawRobot(), and updateDetection().
double GLSoccerView::viewScale private
Definition at line 99 of file soccerview.h.
Referenced by GLSoccerView(), mouseMoveEvent(), recomputeProjection(), resetView(), and wheelEvent().
double GLSoccerView::viewXOffset private
Ratio of world space to screen space coordinates.
Definition at line 100 of file soccerview.h.
Referenced by GLSoccerView(), mouseMoveEvent(), recomputeProjection(), and resetView().
double GLSoccerView::viewYOffset private
Definition at line 101 of file soccerview.h.
Referenced by GLSoccerView(), mouseMoveEvent(), recomputeProjection(), and resetView().
GLuint GLSoccerView::yellowCircleRobotShape private
Definition at line 96 of file soccerview.h.
Referenced by drawRobot(), GLSoccerView(), and initializeGL().
GLuint GLSoccerView::yellowRobotShape private
Definition at line 93 of file soccerview.h.
Referenced by drawRobot(), GLSoccerView(), and initializeGL().
The documentation for this class was generated from the following files:
ssl-vision/src/graphicalClient/soccerview.h
ssl-vision/build/src/graphicalClient/moc_soccerview.cxx
ssl-vision/src/graphicalClient/soccerview.cpp