Documentation: Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder Class Reference
Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
MessagesRobocupSslRefboxLog.Log_Frame getDefaultInstanceForType ()
MessagesRobocupSslRefboxLog.Log_Frame build ()
MessagesRobocupSslRefboxLog.Log_Frame buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (MessagesRobocupSslRefboxLog.Log_Frame other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasFrame ()
MessagesRobocupSslDetection.SSL_DetectionFrame getFrame ()
Builder setFrame (MessagesRobocupSslDetection.SSL_DetectionFrame value)
Builder setFrame (MessagesRobocupSslDetection.SSL_DetectionFrame.Builder builderForValue)
Builder mergeFrame (MessagesRobocupSslDetection.SSL_DetectionFrame value)
Builder clearFrame ()
MessagesRobocupSslDetection.SSL_DetectionFrame.Builder getFrameBuilder ()
MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getFrameOrBuilder ()
boolean hasRefboxCmd ()
String getRefboxCmd ()
Builder setRefboxCmd (String value)
Builder clearRefboxCmd ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
MessagesRobocupSslRefboxLog.Log_Frame buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionFrame, MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder > getFrameFieldBuilder ()
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
MessagesRobocupSslDetection.SSL_DetectionFrame frame_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance()
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionFrame, MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder > frameBuilder_
java.lang.Object refboxCmd_ = ""
Detailed Description
Definition at line 240 of file MessagesRobocupSslRefboxLog.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.Builder () inline private
Definition at line 254 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.Builder (BuilderParent parent) inline private
Definition at line 258 of file MessagesRobocupSslRefboxLog.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.build () inline
Definition at line 297 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.setFrame().
{
         MessagesRobocupSslRefboxLog.Log_Frame result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 305 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.parseDelimitedFrom().
{
         MessagesRobocupSslRefboxLog.Log_Frame result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.buildPartial () inline
Definition at line 315 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.frame_.
{
         MessagesRobocupSslRefboxLog.Log_Frame result = new MessagesRobocupSslRefboxLog.Log_Frame(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         if (frameBuilder_ == null) {
           result.frame_ = frame_;
         } else {
           result.frame_ = frameBuilder_.build();
         }
         if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
           to_bitField0_ |= 0x00000002;
         }
         result.refboxCmd_ = refboxCmd_;
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.clear () inline
Definition at line 271 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.clear(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance().
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.clear().
{
         super.clear();
         if (frameBuilder_ == null) {
           frame_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
         } else {
           frameBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000001);
         refboxCmd_ = "";
         bitField0_ = (bitField0_ & ~0x00000002);
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.clearFrame () inline
Definition at line 470 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance().
{
         if (frameBuilder_ == null) {
           frame_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
           onChanged();
         } else {
           frameBuilder_.clear();
         }
         bitField0_ = (bitField0_ & ~0x00000001);
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.clearRefboxCmd () inline
Definition at line 530 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.getRefboxCmd(), and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.initFields().
{
         bitField0_ = (bitField0_ & ~0x00000002);
         refboxCmd_ = getDefaultInstance().getRefboxCmd();
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.clone () inline
Definition at line 284 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.create () inline static private
Definition at line 267 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.newBuilder().
{
         return new Builder();
       }
MessagesRobocupSslRefboxLog.Log_Frame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.getDefaultInstanceForType () inline
Definition at line 293 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance().
{
         return MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance();
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.getDescriptor () inline static
Definition at line 244 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.internal_static_Log_Frame_descriptor.
{
         return MessagesRobocupSslRefboxLog.internal_static_Log_Frame_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.getDescriptorForType () inline
Definition at line 289 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getDescriptor().
{
         return MessagesRobocupSslRefboxLog.Log_Frame.getDescriptor();
       }
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.getFrame () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.
Definition at line 423 of file MessagesRobocupSslRefboxLog.java.
{
         if (frameBuilder_ == null) {
           return frame_;
         } else {
           return frameBuilder_.getMessage();
         }
       }
MessagesRobocupSslDetection.SSL_DetectionFrame.Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.getFrameBuilder () inline
Definition at line 480 of file MessagesRobocupSslRefboxLog.java.
{
         bitField0_ |= 0x00000001;
         onChanged();
         return getFrameFieldBuilder().getBuilder();
       }
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionFrame, MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder> Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.getFrameFieldBuilder () inline private
Definition at line 494 of file MessagesRobocupSslRefboxLog.java.
{
         if (frameBuilder_ == null) {
           frameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
               MessagesRobocupSslDetection.SSL_DetectionFrame, MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder>(
                   frame_,
                   getParentForChildren(),
                   isClean());
           frame_ = null;
         }
         return frameBuilder_;
       }
MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.getFrameOrBuilder () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.
Definition at line 485 of file MessagesRobocupSslRefboxLog.java.
{
         if (frameBuilder_ != null) {
           return frameBuilder_.getMessageOrBuilder();
         } else {
           return frame_;
         }
       }
String Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.getRefboxCmd () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.
Definition at line 511 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.clearRefboxCmd().
{
         java.lang.Object ref = refboxCmd_;
         if (!(ref instanceof String)) {
           String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
           refboxCmd_ = s;
           return s;
         } else {
           return (String) ref;
         }
       }
boolean Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.hasFrame () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.
Definition at line 420 of file MessagesRobocupSslRefboxLog.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
boolean Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.hasRefboxCmd () inline
Implements Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.
Definition at line 508 of file MessagesRobocupSslRefboxLog.java.
{
         return ((bitField0_ & 0x00000002) == 0x00000002);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 249 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.internal_static_Log_Frame_fieldAccessorTable.
{
         return MessagesRobocupSslRefboxLog.internal_static_Log_Frame_fieldAccessorTable;
       }
final boolean Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.isInitialized () inline
Definition at line 357 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.getFrame(), Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.hasFrame(), and Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.hasRefboxCmd().
{
         if (!hasFrame()) {
           return false;
         }
         if (!hasRefboxCmd()) {
           return false;
         }
         if (!getFrame().isInitialized()) {
           return false;
         }
         return true;
       }
void Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.maybeForceBuilderInitialization () inline private
Definition at line 262 of file MessagesRobocupSslRefboxLog.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
           getFrameFieldBuilder();
         }
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrame (MessagesRobocupSslDetection.SSL_DetectionFrame value) inline
Definition at line 454 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.buildPartial(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder().
{
         if (frameBuilder_ == null) {
           if (((bitField0_ & 0x00000001) == 0x00000001) &&
               frame_ != MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance()) {
             frame_ =
               MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder(frame_).mergeFrom(value).buildPartial();
           } else {
             frame_ = value;
           }
           onChanged();
         } else {
           frameBuilder_.mergeFrom(value);
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 336 of file MessagesRobocupSslRefboxLog.java.
Referenced by Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.clone(), and Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.newBuilder().
{
         if (other instanceof MessagesRobocupSslRefboxLog.Log_Frame) {
           return mergeFrom((MessagesRobocupSslRefboxLog.Log_Frame)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrom (MessagesRobocupSslRefboxLog.Log_Frame other) inline
Definition at line 345 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance().
{
         if (other == MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance()) return this;
         if (other.hasFrame()) {
           mergeFrame(other.getFrame());
         }
         if (other.hasRefboxCmd()) {
           setRefboxCmd(other.getRefboxCmd());
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 373 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.Builder(), Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.getFrame(), Protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder.hasFrame(), Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder.mergeFrom(), and Protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 10: {
               MessagesRobocupSslDetection.SSL_DetectionFrame.Builder subBuilder = MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder();
               if (hasFrame()) {
                 subBuilder.mergeFrom(getFrame());
               }
               input.readMessage(subBuilder, extensionRegistry);
               setFrame(subBuilder.buildPartial());
               break;
             }
             case 18: {
               bitField0_ |= 0x00000002;
               refboxCmd_ = input.readBytes();
               break;
             }
           }
         }
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.setFrame (MessagesRobocupSslDetection.SSL_DetectionFrame value) inline
Definition at line 430 of file MessagesRobocupSslRefboxLog.java.
{
         if (frameBuilder_ == null) {
           if (value == null) {
             throw new NullPointerException();
           }
           frame_ = value;
           onChanged();
         } else {
           frameBuilder_.setMessage(value);
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.setFrame (MessagesRobocupSslDetection.SSL_DetectionFrame.Builder builderForValue) inline
Definition at line 443 of file MessagesRobocupSslRefboxLog.java.
References Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.build().
{
         if (frameBuilder_ == null) {
           frame_ = builderForValue.build();
           onChanged();
         } else {
           frameBuilder_.setMessage(builderForValue.build());
         }
         bitField0_ |= 0x00000001;
         return this;
       }
Builder Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.setRefboxCmd (String value) inline
Definition at line 521 of file MessagesRobocupSslRefboxLog.java.
{
         if (value == null) {
     throw new NullPointerException();
   }
   bitField0_ |= 0x00000002;
         refboxCmd_ = value;
         onChanged();
         return this;
       }
Field Documentation
int Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.bitField0_ private
Definition at line 414 of file MessagesRobocupSslRefboxLog.java.
MessagesRobocupSslDetection.SSL_DetectionFrame Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.frame_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance() private
Definition at line 417 of file MessagesRobocupSslRefboxLog.java.
com.google.protobuf.SingleFieldBuilder< MessagesRobocupSslDetection.SSL_DetectionFrame, MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder> Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.frameBuilder_ private
Definition at line 419 of file MessagesRobocupSslRefboxLog.java.
java.lang.Object Protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.refboxCmd_ = "" private
Definition at line 507 of file MessagesRobocupSslRefboxLog.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslRefboxLog.java