Documentation: Robot::Kicker Class Reference
Robot::Kicker Class Reference
#include <robot.h>
Public Member Functions
Kicker (Robot *robot)
void step ()
void kick (dReal kickspeedx, dReal kickspeedz)
void setRoller (int roller)
int getRoller ()
void toggleRoller ()
bool isTouchingBall ()
Data Fields
dJointID joint
PBox * box
Robot * rob
Private Attributes
bool kicking
int rolling
int kickstate
dReal m_kickspeed
dReal m_kicktime
Detailed Description
Definition at line 63 of file robot.h.
Constructor & Destructor Documentation
Robot::Kicker::Kicker (Robot * robot)
Definition at line 65 of file robot.cpp.
References PWorld::addObject(), PObject::body, RobotSettings::BottomHeight, Robot::cfg, Robot::chassis, Robot::Wheel::joint, RobotSettings::KickerHeight, RobotSettings::KickerMass, RobotSettings::KickerThickness, RobotSettings::KickerWidth, RobotSettings::KickerZ, Robot::m_x, Robot::m_y, Robot::m_z, Robot::Wheel::rob, RobotSettings::RobotCenterFromKicker, RobotSettings::RobotHeight, ConfigWidget::robotSettings, PObject::setBodyPosition(), Robot::space, Robot::w, RobotSettings::WheelRadius, PWorld::world, Robot::x, and Robot::y.
 {
     rob = robot;
     dReal x = rob->m_x;
     dReal y = rob->m_y;
     dReal z = rob->m_z;
     dReal centerx = x+(rob->cfg->robotSettings.RobotCenterFromKicker+rob->cfg->robotSettings.KickerThickness);
     dReal centery = y;
     dReal centerz = z-(rob->cfg->robotSettings.RobotHeight)*0.5f+rob->cfg->robotSettings.WheelRadius-rob->cfg->robotSettings.BottomHeight+rob->cfg->robotSettings.KickerZ;
     box = new PBox(centerx,centery,centerz,rob->cfg->robotSettings.KickerThickness,rob->cfg->robotSettings.KickerWidth,rob->cfg->robotSettings.KickerHeight,rob->cfg->robotSettings.KickerMass,0.9,0.9,0.9);
     box->setBodyPosition(centerx-x,centery-y,centerz-z,true);
     box->space = rob->space;
     rob->w->addObject(box);
     joint = dJointCreateHinge (rob->w->world,0);
     dJointAttach (joint,rob->chassis->body,box->body);
     const dReal *aa = dBodyGetPosition (box->body);
     dJointSetHingeAnchor (joint,aa[0],aa[1],aa[2]);
     dJointSetHingeAxis (joint,0,-1,0);
     dJointSetHingeParam (joint,dParamVel,0);
     dJointSetHingeParam (joint,dParamLoStop,0);
     dJointSetHingeParam (joint,dParamHiStop,0);
     rolling = 0;
     kicking = false;
 }
Member Function Documentation
int Robot::Kicker::getRoller ()
Definition at line 153 of file robot.cpp.
 {
     return rolling;
 }
bool Robot::Kicker::isTouchingBall ()
Definition at line 132 of file robot.cpp.
References ConfigWidget::BallRadius(), Robot::cfg, Robot::chassis, Robot::getBall(), PObject::getBodyDirection(), PObject::getBodyPosition(), RobotSettings::KickerHeight, RobotSettings::KickerThickness, RobotSettings::KickerWidth, Robot::Wheel::rob, and ConfigWidget::robotSettings.
 {
     dReal vx,vy,vz;
     dReal bx,by,bz;
     dReal kx,ky,kz;
     rob->chassis->getBodyDirection(vx,vy,vz);
     rob->getBall()->getBodyPosition(bx,by,bz);
     box->getBodyPosition(kx,ky,kz);
     kx += vx*rob->cfg->robotSettings.KickerThickness*0.5f;
     ky += vy*rob->cfg->robotSettings.KickerThickness*0.5f;
     dReal xx = fabs((kx-bx)*vx + (ky-by)*vy);
     dReal yy = fabs(-(kx-bx)*vy + (ky-by)*vx);
     dReal zz = fabs(kz-bz);
     return ((xx<rob->cfg->robotSettings.KickerThickness*2.0f+rob->cfg->BallRadius()) && (yy<rob->cfg->robotSettings.KickerWidth*0.5f) && (zz<rob->cfg->robotSettings.KickerHeight*0.5f));
 }
void Robot::Kicker::kick (dReal kickspeedx, dReal kickspeedz)
Definition at line 165 of file robot.cpp.
References PObject::body, Robot::cfg, Robot::chassis, Robot::getBall(), PObject::getBodyDirection(), RobotSettings::KickerDampFactor, Robot::Wheel::rob, and ConfigWidget::robotSettings.
Referenced by GLWidget::keyPressEvent(), and SSLWorld::recvActions().
 {
     dReal dx,dy,dz;
     dReal vx,vy,vz;
     rob->chassis->getBodyDirection(dx,dy,dz);dz = 0;
     dReal zf = kickspeedz;
     if (isTouchingBall())
     {
         dReal dlen = dx*dx+dy*dy+dz*dz;
         dlen = sqrt(dlen);
         vx = dx*kickspeedx/dlen;
         vy = dy*kickspeedx/dlen;
         vz = zf;
         const dReal* vball = dBodyGetLinearVel(rob->getBall()->body);
         dReal vn = -(vball[0]*dx + vball[1]*dy)*rob->cfg->robotSettings.KickerDampFactor;
         dReal vt = -(vball[0]*dy - vball[1]*dx);
         vx += vn * dx - vt * dy;
         vy += vn * dy + vt * dx;
         dBodySetLinearVel(rob->getBall()->body,vx,vy,vz);
     }
     kicking = true;
     kickstate = 10;
 }
void Robot::Kicker::setRoller (int roller)
Definition at line 148 of file robot.cpp.
Referenced by SSLWorld::recvActions(), and Robot::step().
 {
     rolling = roller;
 }
void Robot::Kicker::step ()
Definition at line 95 of file robot.cpp.
References PObject::body, Robot::cfg, Robot::chassis, Robot::getBall(), PObject::getBodyDirection(), PObject::getBodyPosition(), Robot::getID(), RobotSettings::KickerWidth, Robot::Wheel::rob, ConfigWidget::robotSettings, RobotSettings::RollerPerpendicularTorqueFactor, RobotSettings::RollerTorqueFactor, and PObject::tag.
Referenced by Robot::step().
 {
     if (kicking)
     {
         box->setColor(1,0.3,0);
         kickstate--;
         if (kickstate<=0) kicking = false;
     }
     else if (rolling!=0)
     {
         box->setColor(1,0.7,0);
         if (isTouchingBall())
         {
             dReal fx,fy,fz;
             rob->chassis->getBodyDirection(fx,fy,fz);
             fz = sqrt(fx*fx + fy*fy);
             fx/=fz;fy/=fz;
             if (rolling==-1) {fx=-fx;fy=-fy;}
             rob->getBall()->tag = rob->getID();
             dReal vx,vy,vz;
             dReal bx,by,bz;
             dReal kx,ky,kz;
             rob->chassis->getBodyDirection(vx,vy,vz);
             rob->getBall()->getBodyPosition(bx,by,bz);
             box->getBodyPosition(kx,ky,kz);
             dReal yy = -((-(kx-bx)*vy + (ky-by)*vx)) / rob->cfg->robotSettings.KickerWidth;
             //dReal dir = 1;
             //if (yy>0) dir = -1.0f;//never read
             dBodySetAngularVel(rob->getBall()->body,fy*rob->cfg->robotSettings.RollerTorqueFactor*1400,-fx*rob->cfg->robotSettings.RollerTorqueFactor*1400,0);
             //dBodyAddTorque(rob->getBall()->body,fy*rob->cfg->ROLLERTORQUEFACTOR(),-fx*rob->cfg->ROLLERTORQUEFACTOR(),0);
             dBodyAddTorque(rob->getBall()->body,yy*fx*rob->cfg->robotSettings.RollerPerpendicularTorqueFactor,yy*fy*rob->cfg->robotSettings.RollerPerpendicularTorqueFactor,0);
         }
     }
     else box->setColor(0.9,0.9,0.9);
 }
void Robot::Kicker::toggleRoller ()
Definition at line 158 of file robot.cpp.
Referenced by GLWidget::keyPressEvent().
 {
     if (rolling==0)
         rolling = 1;
     else rolling = 0;
 }
Field Documentation
PBox* Robot::Kicker::box
Definition at line 79 of file robot.h.
Referenced by Robot::resetRobot(), Robot::setDir(), and Robot::setXY().
dJointID Robot::Kicker::joint
Definition at line 78 of file robot.h.
bool Robot::Kicker::kicking private
Definition at line 66 of file robot.h.
int Robot::Kicker::kickstate private
Definition at line 68 of file robot.h.
dReal Robot::Kicker::m_kickspeed private
Definition at line 69 of file robot.h.
dReal Robot::Kicker::m_kicktime private
Definition at line 69 of file robot.h.
Robot* Robot::Kicker::rob
Definition at line 80 of file robot.h.
int Robot::Kicker::rolling private
Definition at line 67 of file robot.h.
The documentation for this class was generated from the following files:
grSim/include/robot.h
grSim/src/robot.cpp