Documentation: Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder Class Reference
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration getDefaultInstanceForType ()
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration build ()
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasCameraId ()
int getCameraId ()
Builder setCameraId (int value)
Builder clearCameraId ()
boolean hasFocalLength ()
float getFocalLength ()
Builder setFocalLength (float value)
Builder clearFocalLength ()
boolean hasPrincipalPointX ()
float getPrincipalPointX ()
Builder setPrincipalPointX (float value)
Builder clearPrincipalPointX ()
boolean hasPrincipalPointY ()
float getPrincipalPointY ()
Builder setPrincipalPointY (float value)
Builder clearPrincipalPointY ()
boolean hasDistortion ()
float getDistortion ()
Builder setDistortion (float value)
Builder clearDistortion ()
boolean hasQ0 ()
float getQ0 ()
Builder setQ0 (float value)
Builder clearQ0 ()
boolean hasQ1 ()
float getQ1 ()
Builder setQ1 (float value)
Builder clearQ1 ()
boolean hasQ2 ()
float getQ2 ()
Builder setQ2 (float value)
Builder clearQ2 ()
boolean hasQ3 ()
float getQ3 ()
Builder setQ3 (float value)
Builder clearQ3 ()
boolean hasTx ()
float getTx ()
Builder setTx (float value)
Builder clearTx ()
boolean hasTy ()
float getTy ()
Builder setTy (float value)
Builder clearTy ()
boolean hasTz ()
float getTz ()
Builder setTz (float value)
Builder clearTz ()
boolean hasDerivedCameraWorldTx ()
float getDerivedCameraWorldTx ()
Builder setDerivedCameraWorldTx (float value)
Builder clearDerivedCameraWorldTx ()
boolean hasDerivedCameraWorldTy ()
float getDerivedCameraWorldTy ()
Builder setDerivedCameraWorldTy (float value)
Builder clearDerivedCameraWorldTy ()
boolean hasDerivedCameraWorldTz ()
float getDerivedCameraWorldTz ()
Builder setDerivedCameraWorldTz (float value)
Builder clearDerivedCameraWorldTz ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
int cameraId_
float focalLength_
float principalPointX_
float principalPointY_
float distortion_
float q0_
float q1_
float q2_
float q3_
float tx_
float ty_
float tz_
float derivedCameraWorldTx_
float derivedCameraWorldTy_
float derivedCameraWorldTz_
Detailed Description
Definition at line 1727 of file MessagesRobocupSslGeometry.java.
Constructor & Destructor Documentation
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.Builder () inline private
Definition at line 1741 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.Builder (BuilderParent parent) inline private
Definition at line 1745 of file MessagesRobocupSslGeometry.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.build () inline
Definition at line 1805 of file MessagesRobocupSslGeometry.java.
{
         MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 1813 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.parseDelimitedFrom().
{
         MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.buildPartial () inline
Definition at line 1823 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.cameraId_.
{
         MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration result = new MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         result.cameraId_ = cameraId_;
         if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
           to_bitField0_ |= 0x00000002;
         }
         result.focalLength_ = focalLength_;
         if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
           to_bitField0_ |= 0x00000004;
         }
         result.principalPointX_ = principalPointX_;
         if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
           to_bitField0_ |= 0x00000008;
         }
         result.principalPointY_ = principalPointY_;
         if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
           to_bitField0_ |= 0x00000010;
         }
         result.distortion_ = distortion_;
         if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
           to_bitField0_ |= 0x00000020;
         }
         result.q0_ = q0_;
         if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
           to_bitField0_ |= 0x00000040;
         }
         result.q1_ = q1_;
         if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
           to_bitField0_ |= 0x00000080;
         }
         result.q2_ = q2_;
         if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
           to_bitField0_ |= 0x00000100;
         }
         result.q3_ = q3_;
         if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
           to_bitField0_ |= 0x00000200;
         }
         result.tx_ = tx_;
         if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
           to_bitField0_ |= 0x00000400;
         }
         result.ty_ = ty_;
         if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
           to_bitField0_ |= 0x00000800;
         }
         result.tz_ = tz_;
         if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
           to_bitField0_ |= 0x00001000;
         }
         result.derivedCameraWorldTx_ = derivedCameraWorldTx_;
         if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
           to_bitField0_ |= 0x00002000;
         }
         result.derivedCameraWorldTy_ = derivedCameraWorldTy_;
         if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
           to_bitField0_ |= 0x00004000;
         }
         result.derivedCameraWorldTz_ = derivedCameraWorldTz_;
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clear () inline
Definition at line 1757 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clear().
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clear().
{
         super.clear();
         cameraId_ = 0;
         bitField0_ = (bitField0_ & ~0x00000001);
         focalLength_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000002);
         principalPointX_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000004);
         principalPointY_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000008);
         distortion_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000010);
         q0_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000020);
         q1_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000040);
         q2_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000080);
         q3_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000100);
         tx_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000200);
         ty_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000400);
         tz_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000800);
         derivedCameraWorldTx_ = 0F;
         bitField0_ = (bitField0_ & ~0x00001000);
         derivedCameraWorldTy_ = 0F;
         bitField0_ = (bitField0_ & ~0x00002000);
         derivedCameraWorldTz_ = 0F;
         bitField0_ = (bitField0_ & ~0x00004000);
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearCameraId () inline
Definition at line 2122 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000001);
         cameraId_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearDerivedCameraWorldTx () inline
Definition at line 2374 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00001000);
         derivedCameraWorldTx_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearDerivedCameraWorldTy () inline
Definition at line 2395 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00002000);
         derivedCameraWorldTy_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearDerivedCameraWorldTz () inline
Definition at line 2416 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.initFields().
{
         bitField0_ = (bitField0_ & ~0x00004000);
         derivedCameraWorldTz_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearDistortion () inline
Definition at line 2206 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000010);
         distortion_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearFocalLength () inline
Definition at line 2143 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000002);
         focalLength_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearPrincipalPointX () inline
Definition at line 2164 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000004);
         principalPointX_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearPrincipalPointY () inline
Definition at line 2185 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000008);
         principalPointY_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearQ0 () inline
Definition at line 2227 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000020);
         q0_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearQ1 () inline
Definition at line 2248 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000040);
         q1_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearQ2 () inline
Definition at line 2269 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000080);
         q2_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearQ3 () inline
Definition at line 2290 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000100);
         q3_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearTx () inline
Definition at line 2311 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000200);
         tx_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearTy () inline
Definition at line 2332 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000400);
         ty_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clearTz () inline
Definition at line 2353 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ = (bitField0_ & ~0x00000800);
         tz_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clone () inline
Definition at line 1792 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.create () inline static private
Definition at line 1753 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.newBuilder().
{
         return new Builder();
       }
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getCameraId () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2113 of file MessagesRobocupSslGeometry.java.
{
         return cameraId_;
       }
MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getDefaultInstanceForType () inline
Definition at line 1801 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDefaultInstance().
{
         return MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDefaultInstance();
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getDerivedCameraWorldTx () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2365 of file MessagesRobocupSslGeometry.java.
{
         return derivedCameraWorldTx_;
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getDerivedCameraWorldTy () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2386 of file MessagesRobocupSslGeometry.java.
{
         return derivedCameraWorldTy_;
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getDerivedCameraWorldTz () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2407 of file MessagesRobocupSslGeometry.java.
{
         return derivedCameraWorldTz_;
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getDescriptor () inline static
Definition at line 1731 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.internal_static_SSL_GeometryCameraCalibration_descriptor.
{
         return MessagesRobocupSslGeometry.internal_static_SSL_GeometryCameraCalibration_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getDescriptorForType () inline
Definition at line 1797 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDescriptor().
{
         return MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDescriptor();
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getDistortion () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2197 of file MessagesRobocupSslGeometry.java.
{
         return distortion_;
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getFocalLength () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2134 of file MessagesRobocupSslGeometry.java.
{
         return focalLength_;
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getPrincipalPointX () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2155 of file MessagesRobocupSslGeometry.java.
{
         return principalPointX_;
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getPrincipalPointY () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2176 of file MessagesRobocupSslGeometry.java.
{
         return principalPointY_;
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getQ0 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2218 of file MessagesRobocupSslGeometry.java.
{
         return q0_;
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getQ1 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2239 of file MessagesRobocupSslGeometry.java.
{
         return q1_;
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getQ2 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2260 of file MessagesRobocupSslGeometry.java.
{
         return q2_;
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getQ3 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2281 of file MessagesRobocupSslGeometry.java.
{
         return q3_;
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getTx () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2302 of file MessagesRobocupSslGeometry.java.
{
         return tx_;
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getTy () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2323 of file MessagesRobocupSslGeometry.java.
{
         return ty_;
       }
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.getTz () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2344 of file MessagesRobocupSslGeometry.java.
{
         return tz_;
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasCameraId () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2110 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasDerivedCameraWorldTx () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2362 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00001000) == 0x00001000);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasDerivedCameraWorldTy () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2383 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00002000) == 0x00002000);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasDerivedCameraWorldTz () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2404 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00004000) == 0x00004000);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasDistortion () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2194 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000010) == 0x00000010);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasFocalLength () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2131 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000002) == 0x00000002);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasPrincipalPointX () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2152 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000004) == 0x00000004);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasPrincipalPointY () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2173 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000008) == 0x00000008);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasQ0 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2215 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000020) == 0x00000020);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasQ1 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2236 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000040) == 0x00000040);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasQ2 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2257 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000080) == 0x00000080);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasQ3 () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2278 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000100) == 0x00000100);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasTx () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2299 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000200) == 0x00000200);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasTy () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2320 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000400) == 0x00000400);
       }
boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.hasTz () inline
Implements Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibrationOrBuilder.
Definition at line 2341 of file MessagesRobocupSslGeometry.java.
{
         return ((bitField0_ & 0x00000800) == 0x00000800);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 1736 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.internal_static_SSL_GeometryCameraCalibration_fieldAccessorTable.
{
         return MessagesRobocupSslGeometry.internal_static_SSL_GeometryCameraCalibration_fieldAccessorTable;
       }
final boolean Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.isInitialized () inline
Definition at line 1952 of file MessagesRobocupSslGeometry.java.
{
         if (!hasCameraId()) {
           return false;
         }
         if (!hasFocalLength()) {
           return false;
         }
         if (!hasPrincipalPointX()) {
           return false;
         }
         if (!hasPrincipalPointY()) {
           return false;
         }
         if (!hasDistortion()) {
           return false;
         }
         if (!hasQ0()) {
           return false;
         }
         if (!hasQ1()) {
           return false;
         }
         if (!hasQ2()) {
           return false;
         }
         if (!hasQ3()) {
           return false;
         }
         if (!hasTx()) {
           return false;
         }
         if (!hasTy()) {
           return false;
         }
         if (!hasTz()) {
           return false;
         }
         return true;
       }
void Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.maybeForceBuilderInitialization () inline private
Definition at line 1749 of file MessagesRobocupSslGeometry.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
         }
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 1892 of file MessagesRobocupSslGeometry.java.
Referenced by Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.clone(), and Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.newBuilder().
{
         if (other instanceof MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration) {
           return mergeFrom((MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.mergeFrom (MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration other) inline
Definition at line 1901 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDefaultInstance().
{
         if (other == MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.getDefaultInstance()) return this;
         if (other.hasCameraId()) {
           setCameraId(other.getCameraId());
         }
         if (other.hasFocalLength()) {
           setFocalLength(other.getFocalLength());
         }
         if (other.hasPrincipalPointX()) {
           setPrincipalPointX(other.getPrincipalPointX());
         }
         if (other.hasPrincipalPointY()) {
           setPrincipalPointY(other.getPrincipalPointY());
         }
         if (other.hasDistortion()) {
           setDistortion(other.getDistortion());
         }
         if (other.hasQ0()) {
           setQ0(other.getQ0());
         }
         if (other.hasQ1()) {
           setQ1(other.getQ1());
         }
         if (other.hasQ2()) {
           setQ2(other.getQ2());
         }
         if (other.hasQ3()) {
           setQ3(other.getQ3());
         }
         if (other.hasTx()) {
           setTx(other.getTx());
         }
         if (other.hasTy()) {
           setTy(other.getTy());
         }
         if (other.hasTz()) {
           setTz(other.getTz());
         }
         if (other.hasDerivedCameraWorldTx()) {
           setDerivedCameraWorldTx(other.getDerivedCameraWorldTx());
         }
         if (other.hasDerivedCameraWorldTy()) {
           setDerivedCameraWorldTy(other.getDerivedCameraWorldTy());
         }
         if (other.hasDerivedCameraWorldTz()) {
           setDerivedCameraWorldTz(other.getDerivedCameraWorldTz());
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 2004 of file MessagesRobocupSslGeometry.java.
References Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.Builder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 8: {
               bitField0_ |= 0x00000001;
               cameraId_ = input.readUInt32();
               break;
             }
             case 21: {
               bitField0_ |= 0x00000002;
               focalLength_ = input.readFloat();
               break;
             }
             case 29: {
               bitField0_ |= 0x00000004;
               principalPointX_ = input.readFloat();
               break;
             }
             case 37: {
               bitField0_ |= 0x00000008;
               principalPointY_ = input.readFloat();
               break;
             }
             case 45: {
               bitField0_ |= 0x00000010;
               distortion_ = input.readFloat();
               break;
             }
             case 53: {
               bitField0_ |= 0x00000020;
               q0_ = input.readFloat();
               break;
             }
             case 61: {
               bitField0_ |= 0x00000040;
               q1_ = input.readFloat();
               break;
             }
             case 69: {
               bitField0_ |= 0x00000080;
               q2_ = input.readFloat();
               break;
             }
             case 77: {
               bitField0_ |= 0x00000100;
               q3_ = input.readFloat();
               break;
             }
             case 85: {
               bitField0_ |= 0x00000200;
               tx_ = input.readFloat();
               break;
             }
             case 93: {
               bitField0_ |= 0x00000400;
               ty_ = input.readFloat();
               break;
             }
             case 101: {
               bitField0_ |= 0x00000800;
               tz_ = input.readFloat();
               break;
             }
             case 109: {
               bitField0_ |= 0x00001000;
               derivedCameraWorldTx_ = input.readFloat();
               break;
             }
             case 117: {
               bitField0_ |= 0x00002000;
               derivedCameraWorldTy_ = input.readFloat();
               break;
             }
             case 125: {
               bitField0_ |= 0x00004000;
               derivedCameraWorldTz_ = input.readFloat();
               break;
             }
           }
         }
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setCameraId (int value) inline
Definition at line 2116 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000001;
         cameraId_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setDerivedCameraWorldTx (float value) inline
Definition at line 2368 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00001000;
         derivedCameraWorldTx_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setDerivedCameraWorldTy (float value) inline
Definition at line 2389 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00002000;
         derivedCameraWorldTy_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setDerivedCameraWorldTz (float value) inline
Definition at line 2410 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00004000;
         derivedCameraWorldTz_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setDistortion (float value) inline
Definition at line 2200 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000010;
         distortion_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setFocalLength (float value) inline
Definition at line 2137 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000002;
         focalLength_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setPrincipalPointX (float value) inline
Definition at line 2158 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000004;
         principalPointX_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setPrincipalPointY (float value) inline
Definition at line 2179 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000008;
         principalPointY_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setQ0 (float value) inline
Definition at line 2221 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000020;
         q0_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setQ1 (float value) inline
Definition at line 2242 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000040;
         q1_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setQ2 (float value) inline
Definition at line 2263 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000080;
         q2_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setQ3 (float value) inline
Definition at line 2284 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000100;
         q3_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setTx (float value) inline
Definition at line 2305 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000200;
         tx_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setTy (float value) inline
Definition at line 2326 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000400;
         ty_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.setTz (float value) inline
Definition at line 2347 of file MessagesRobocupSslGeometry.java.
{
         bitField0_ |= 0x00000800;
         tz_ = value;
         onChanged();
         return this;
       }
Field Documentation
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.bitField0_ private
Definition at line 2106 of file MessagesRobocupSslGeometry.java.
int Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.cameraId_ private
Definition at line 2109 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.derivedCameraWorldTx_ private
Definition at line 2361 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.derivedCameraWorldTy_ private
Definition at line 2382 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.derivedCameraWorldTz_ private
Definition at line 2403 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.distortion_ private
Definition at line 2193 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.focalLength_ private
Definition at line 2130 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.principalPointX_ private
Definition at line 2151 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.principalPointY_ private
Definition at line 2172 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.q0_ private
Definition at line 2214 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.q1_ private
Definition at line 2235 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.q2_ private
Definition at line 2256 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.q3_ private
Definition at line 2277 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.tx_ private
Definition at line 2298 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.ty_ private
Definition at line 2319 of file MessagesRobocupSslGeometry.java.
float Protobuf.MessagesRobocupSslGeometry.SSL_GeometryCameraCalibration.Builder.tz_ private
Definition at line 2340 of file MessagesRobocupSslGeometry.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/MessagesRobocupSslGeometry.java