// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grSim_Packet.proto

#ifndef PROTOBUF_grSim_5fPacket_2eproto__INCLUDED
#define PROTOBUF_grSim_5fPacket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "grSim_Commands.pb.h"
#include "grSim_Replacement.pb.h"
#include "sslDebug_Data.pb.h"
// @@protoc_insertion_point(includes)
class Debug_AdjustBall;
class Debug_AdjustBallDefaultTypeInternal;
extern Debug_AdjustBallDefaultTypeInternal _Debug_AdjustBall_default_instance_;
class Debug_AdjustBot;
class Debug_AdjustBotDefaultTypeInternal;
extern Debug_AdjustBotDefaultTypeInternal _Debug_AdjustBot_default_instance_;
class Debug_Circle;
class Debug_CircleDefaultTypeInternal;
extern Debug_CircleDefaultTypeInternal _Debug_Circle_default_instance_;
class Debug_Line;
class Debug_LineDefaultTypeInternal;
extern Debug_LineDefaultTypeInternal _Debug_Line_default_instance_;
class grSim_BallReplacement;
class grSim_BallReplacementDefaultTypeInternal;
extern grSim_BallReplacementDefaultTypeInternal _grSim_BallReplacement_default_instance_;
class grSim_Commands;
class grSim_CommandsDefaultTypeInternal;
extern grSim_CommandsDefaultTypeInternal _grSim_Commands_default_instance_;
class grSim_Packet;
class grSim_PacketDefaultTypeInternal;
extern grSim_PacketDefaultTypeInternal _grSim_Packet_default_instance_;
class grSim_Replacement;
class grSim_ReplacementDefaultTypeInternal;
extern grSim_ReplacementDefaultTypeInternal _grSim_Replacement_default_instance_;
class grSim_RobotReplacement;
class grSim_RobotReplacementDefaultTypeInternal;
extern grSim_RobotReplacementDefaultTypeInternal _grSim_RobotReplacement_default_instance_;
class grSim_Robot_Command;
class grSim_Robot_CommandDefaultTypeInternal;
extern grSim_Robot_CommandDefaultTypeInternal _grSim_Robot_Command_default_instance_;
class sslDebug_Data;
class sslDebug_DataDefaultTypeInternal;
extern sslDebug_DataDefaultTypeInternal _sslDebug_Data_default_instance_;

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_grSim_5fPacket_2eproto();
void protobuf_InitDefaults_grSim_5fPacket_2eproto();

// ===================================================================

class grSim_Packet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:grSim_Packet) */ {
 public:
  grSim_Packet();
  virtual ~grSim_Packet();

  grSim_Packet(const grSim_Packet& from);

  inline grSim_Packet& operator=(const grSim_Packet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const grSim_Packet& default_instance();

  static inline const grSim_Packet* internal_default_instance() {
    return reinterpret_cast<const grSim_Packet*>(
               &_grSim_Packet_default_instance_);
  }

  void Swap(grSim_Packet* other);

  // implements Message ----------------------------------------------

  inline grSim_Packet* New() const PROTOBUF_FINAL { return New(NULL); }

  grSim_Packet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const grSim_Packet& from);
  void MergeFrom(const grSim_Packet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(grSim_Packet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .grSim_Commands commands = 1;
  bool has_commands() const;
  void clear_commands();
  static const int kCommandsFieldNumber = 1;
  const ::grSim_Commands& commands() const;
  ::grSim_Commands* mutable_commands();
  ::grSim_Commands* release_commands();
  void set_allocated_commands(::grSim_Commands* commands);

  // optional .grSim_Replacement replacement = 2;
  bool has_replacement() const;
  void clear_replacement();
  static const int kReplacementFieldNumber = 2;
  const ::grSim_Replacement& replacement() const;
  ::grSim_Replacement* mutable_replacement();
  ::grSim_Replacement* release_replacement();
  void set_allocated_replacement(::grSim_Replacement* replacement);

  // optional .sslDebug_Data debuginfo = 3;
  bool has_debuginfo() const;
  void clear_debuginfo();
  static const int kDebuginfoFieldNumber = 3;
  const ::sslDebug_Data& debuginfo() const;
  ::sslDebug_Data* mutable_debuginfo();
  ::sslDebug_Data* release_debuginfo();
  void set_allocated_debuginfo(::sslDebug_Data* debuginfo);

  // @@protoc_insertion_point(class_scope:grSim_Packet)
 private:
  void set_has_commands();
  void clear_has_commands();
  void set_has_replacement();
  void clear_has_replacement();
  void set_has_debuginfo();
  void clear_has_debuginfo();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::grSim_Commands* commands_;
  ::grSim_Replacement* replacement_;
  ::sslDebug_Data* debuginfo_;
  friend void  protobuf_InitDefaults_grSim_5fPacket_2eproto_impl();
  friend void  protobuf_AddDesc_grSim_5fPacket_2eproto_impl();
  friend const ::google::protobuf::uint32* protobuf_Offsets_grSim_5fPacket_2eproto();
  friend void protobuf_ShutdownFile_grSim_5fPacket_2eproto();

};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// grSim_Packet

// optional .grSim_Commands commands = 1;
inline bool grSim_Packet::has_commands() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void grSim_Packet::set_has_commands() {
  _has_bits_[0] |= 0x00000001u;
}
inline void grSim_Packet::clear_has_commands() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void grSim_Packet::clear_commands() {
  if (commands_ != NULL) commands_->::grSim_Commands::Clear();
  clear_has_commands();
}
inline const ::grSim_Commands& grSim_Packet::commands() const {
  // @@protoc_insertion_point(field_get:grSim_Packet.commands)
  return commands_ != NULL ? *commands_
                         : *::grSim_Commands::internal_default_instance();
}
inline ::grSim_Commands* grSim_Packet::mutable_commands() {
  set_has_commands();
  if (commands_ == NULL) {
    commands_ = new ::grSim_Commands;
  }
  // @@protoc_insertion_point(field_mutable:grSim_Packet.commands)
  return commands_;
}
inline ::grSim_Commands* grSim_Packet::release_commands() {
  // @@protoc_insertion_point(field_release:grSim_Packet.commands)
  clear_has_commands();
  ::grSim_Commands* temp = commands_;
  commands_ = NULL;
  return temp;
}
inline void grSim_Packet::set_allocated_commands(::grSim_Commands* commands) {
  delete commands_;
  commands_ = commands;
  if (commands) {
    set_has_commands();
  } else {
    clear_has_commands();
  }
  // @@protoc_insertion_point(field_set_allocated:grSim_Packet.commands)
}

// optional .grSim_Replacement replacement = 2;
inline bool grSim_Packet::has_replacement() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void grSim_Packet::set_has_replacement() {
  _has_bits_[0] |= 0x00000002u;
}
inline void grSim_Packet::clear_has_replacement() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void grSim_Packet::clear_replacement() {
  if (replacement_ != NULL) replacement_->::grSim_Replacement::Clear();
  clear_has_replacement();
}
inline const ::grSim_Replacement& grSim_Packet::replacement() const {
  // @@protoc_insertion_point(field_get:grSim_Packet.replacement)
  return replacement_ != NULL ? *replacement_
                         : *::grSim_Replacement::internal_default_instance();
}
inline ::grSim_Replacement* grSim_Packet::mutable_replacement() {
  set_has_replacement();
  if (replacement_ == NULL) {
    replacement_ = new ::grSim_Replacement;
  }
  // @@protoc_insertion_point(field_mutable:grSim_Packet.replacement)
  return replacement_;
}
inline ::grSim_Replacement* grSim_Packet::release_replacement() {
  // @@protoc_insertion_point(field_release:grSim_Packet.replacement)
  clear_has_replacement();
  ::grSim_Replacement* temp = replacement_;
  replacement_ = NULL;
  return temp;
}
inline void grSim_Packet::set_allocated_replacement(::grSim_Replacement* replacement) {
  delete replacement_;
  replacement_ = replacement;
  if (replacement) {
    set_has_replacement();
  } else {
    clear_has_replacement();
  }
  // @@protoc_insertion_point(field_set_allocated:grSim_Packet.replacement)
}

// optional .sslDebug_Data debuginfo = 3;
inline bool grSim_Packet::has_debuginfo() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void grSim_Packet::set_has_debuginfo() {
  _has_bits_[0] |= 0x00000004u;
}
inline void grSim_Packet::clear_has_debuginfo() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void grSim_Packet::clear_debuginfo() {
  if (debuginfo_ != NULL) debuginfo_->::sslDebug_Data::Clear();
  clear_has_debuginfo();
}
inline const ::sslDebug_Data& grSim_Packet::debuginfo() const {
  // @@protoc_insertion_point(field_get:grSim_Packet.debuginfo)
  return debuginfo_ != NULL ? *debuginfo_
                         : *::sslDebug_Data::internal_default_instance();
}
inline ::sslDebug_Data* grSim_Packet::mutable_debuginfo() {
  set_has_debuginfo();
  if (debuginfo_ == NULL) {
    debuginfo_ = new ::sslDebug_Data;
  }
  // @@protoc_insertion_point(field_mutable:grSim_Packet.debuginfo)
  return debuginfo_;
}
inline ::sslDebug_Data* grSim_Packet::release_debuginfo() {
  // @@protoc_insertion_point(field_release:grSim_Packet.debuginfo)
  clear_has_debuginfo();
  ::sslDebug_Data* temp = debuginfo_;
  debuginfo_ = NULL;
  return temp;
}
inline void grSim_Packet::set_allocated_debuginfo(::sslDebug_Data* debuginfo) {
  delete debuginfo_;
  debuginfo_ = debuginfo;
  if (debuginfo) {
    set_has_debuginfo();
  } else {
    clear_has_debuginfo();
  }
  // @@protoc_insertion_point(field_set_allocated:grSim_Packet.debuginfo)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_grSim_5fPacket_2eproto__INCLUDED
