Documentation: CaptureFlycap Class Reference
CaptureFlycap Class Reference
#include <capture_flycap.h>
Public Slots
void changed (VarType *group)
Public Member Functions
CaptureFlycap (VarList *_settings=0, int default_camera_id=0, QObject *parent=0)
void mvc_connect (VarList *group)
~CaptureFlycap ()
virtual bool startCapture ()
Initialize the interface and start capture.
virtual bool stopCapture ()
Stop Capture.
virtual bool isCapturing ()
virtual RawImage getFrame ()
virtual void releaseFrame ()
virtual bool resetBus ()
void cleanup ()
void readParameterValues (VarList *item)
void writeParameterValues (VarList *item)
bool copyFrame (const RawImage &src, RawImage &target)
virtual void readAllParameterValues ()
void writeAllParameterValues ()
virtual bool copyAndConvertFrame (const RawImage &src, RawImage &target)
virtual string getCaptureMethodName () const
Public Member Functions inherited from CaptureInterface
CaptureInterface (VarList *_settings=0)
virtual ~CaptureInterface ()
Static Public Member Functions
static dc1394color_filter_t stringToColorFilter (const char *s)
static string colorFilterToString (dc1394color_filter_t f)
static dc1394bayer_method_t stringToBayerMethod (const char *s)
static string bayerMethodToString (dc1394bayer_method_t f)
Protected Member Functions
bool convertFrame (const RawImage &src, RawImage &target, ColorFormat output_fmt, bool debayer=true, dc1394color_filter_t bayer_format=DC1394_COLOR_FILTER_RGGB, dc1394bayer_method_t bayer_method=DC1394_BAYER_METHOD_HQLINEAR, int y16bits=16)
Protected Attributes
QMutex mutex
ApplicationData cbData
const char * dev_name
unsigned char * currentFrame
bool is_capturing
bool settings_changed
string prev_mode_string
bool is_connected
VarStringEnum * v_colorout
VarStringEnum * v_debayer_pattern
VarStringEnum * v_debayer_method
VarInt * v_debayer_y16
VarBool * v_debayer
VarList * P_WHITE_BALANCE
VarInt * v_cam_bus
VarInt * v_width
VarInt * v_height
VarInt * v_xoffset
VarInt * v_yoffset
VarStringEnum * v_videomode
VarStringEnum * v_colormode
int previous_id
unsigned int cam_id
ColorFormat capture_format
VarList * camera_parameters
VarList * capture_settings
VarList * conversion_settings
FlyCapture2::GigECamera * camera
FlyCapture2::PGRGuid guid
FlyCapture2::Image * stored_image
Static Protected Attributes
static std::vector< unsigned int > active_cam_ids
static QMutex cam_id_mutex
Additional Inherited Members
Data Fields inherited from CaptureInterface
VarList * settings
Detailed Description
Definition at line 59 of file capture_flycap.h.
Constructor & Destructor Documentation
CaptureFlycap::CaptureFlycap (VarList * _settings = 0, int default_camera_id = 0, QObject * parent = 0)
Definition at line 121 of file capture_flycap.cpp.
References VarTypes::VarList::addChild(), VarTypes::VarStringEnum::addItem(), bayerMethodToString(), cam_id, camera, camera_parameters, capture_settings, COLOR_MONO16, COLOR_MONO8, COLOR_RAW16, COLOR_RGB16, COLOR_RGB8, COLOR_YUV422_UYVY, COLOR_YUV444, colorFilterToString(), Colors::colorFormatToString(), conversion_settings, currentFrame, VarTypes::VarInt::getInt(), velocity.pid_::i, is_capturing, is_connected, mutex, mvc_connect(), P_WHITE_BALANCE, previous_id, CaptureInterface::settings, settings_changed, stored_image, v_cam_bus, v_colormode, v_colorout, v_debayer, v_debayer_method, v_debayer_pattern, v_debayer_y16, v_height, v_videomode, v_width, v_xoffset, and v_yoffset.
                                                                                         : QObject(parent),CaptureInterface(_settings)
 {
     mutex.lock();
     settings->addChild(conversion_settings = new VarList("Conversion Settings"));
     settings->addChild(capture_settings = new VarList("Capture Settings"));
     settings->addChild(camera_parameters  = new VarList("Camera Parameters"));
     //=======================CONVERSION SETTINGS=======================
     conversion_settings->addChild(v_colorout=new VarStringEnum(
       "convert to mode",Colors::colorFormatToString(COLOR_YUV422_UYVY)));
     v_colorout->addItem(Colors::colorFormatToString(COLOR_RGB8));
     v_colorout->addItem(Colors::colorFormatToString(COLOR_YUV422_UYVY));
     conversion_settings->addChild(v_debayer=new VarBool("de-bayer",false));
     conversion_settings->addChild(v_debayer_pattern=new VarStringEnum("de-bayer pattern",colorFilterToString(DC1394_COLOR_FILTER_MIN)));
     for (int i = DC1394_COLOR_FILTER_MIN; i <= DC1394_COLOR_FILTER_MAX; i++) {
       v_debayer_pattern->addItem(colorFilterToString((dc1394color_filter_t)i));
     }
     conversion_settings->addChild(v_debayer_method=new VarStringEnum("de-bayer method",bayerMethodToString(DC1394_BAYER_METHOD_MIN)));
     for (int i = DC1394_BAYER_METHOD_MIN; i <= DC1394_BAYER_METHOD_MAX; i++) {
       v_debayer_method->addItem(bayerMethodToString((dc1394bayer_method_t)i));
     }
     conversion_settings->addChild(v_debayer_y16=new VarInt("de-bayer y16 bits",16));
     //dcam_parameters->addFlags( VARTYPE_FLAG_HIDE_CHILDREN );
     //=======================CAPTURE SETTINGS==========================
     //TODO: set default camera id
     capture_settings->addChild(v_cam_bus          = new VarInt("Cam Index",-1));
     capture_settings->addChild(v_width            = new VarInt("Width",960));
     capture_settings->addChild(v_height           = new VarInt("Height",600));
     capture_settings->addChild(v_xoffset          = new VarInt("X Offset",0));
     capture_settings->addChild(v_yoffset          = new VarInt("Y Offset",0));
     capture_settings->addChild(v_colormode        = new VarStringEnum("Color Mode",Colors::colorFormatToString(COLOR_YUV422_UYVY)));
     v_colormode->addItem(Colors::colorFormatToString(COLOR_MONO8));
     v_colormode->addItem(Colors::colorFormatToString(COLOR_YUV422_UYVY));
     v_colormode->addItem(Colors::colorFormatToString(COLOR_YUV444));
     v_colormode->addItem(Colors::colorFormatToString(COLOR_RGB8));
     v_colormode->addItem(Colors::colorFormatToString(COLOR_MONO16));
     v_colormode->addItem(Colors::colorFormatToString(COLOR_RGB16));
     v_colormode->addItem(Colors::colorFormatToString(COLOR_RGB8));
     v_colormode->addItem(Colors::colorFormatToString(COLOR_RAW16));
     //v_buffer_size->addFlags(VARTYPE_FLAG_READONLY);
     //camera_parameters->addFlags( VARTYPE_FLAG_HIDE_CHILDREN );
     camera_parameters->addChild(v_videomode = new VarStringEnum("Mode","4"));
     v_videomode->addItem("4");
     v_videomode->addItem("7");
     camera_parameters->addChild(new VarDouble("Brightness", 2.93));
     camera_parameters->addChild(new VarDouble("Shutter", 0.6635));
     camera_parameters->addChild(new VarDouble("Gain", 17.998));
     camera_parameters->addChild(new VarDouble("Gamma", 1.250));
     camera_parameters->addChild(new VarDouble("Frame Rate", 60.250));
     camera_parameters->addChild(P_WHITE_BALANCE = new VarList("White Balance"));
     P_WHITE_BALANCE->addChild(new VarBool("Enabled",true));
     P_WHITE_BALANCE->addChild(new VarInt("Red Value",637));
     P_WHITE_BALANCE->addChild(new VarInt("Blue Value",1023));
     mvc_connect(capture_settings);
     mvc_connect(camera_parameters);
     mvc_connect(P_WHITE_BALANCE);
     is_capturing = false;
     is_connected = false;
     currentFrame = NULL;
     camera = NULL;
     stored_image = NULL;
     settings_changed = true;
     previous_id = v_cam_bus->getInt();
     if (previous_id >= 0) {
       cam_id = (unsigned int)v_cam_bus->getInt();
     } else {
       cam_id = 0;
     }
     mutex.unlock();
 }
CaptureFlycap::~CaptureFlycap ()
Definition at line 348 of file capture_flycap.cpp.
{
 }
Member Function Documentation
static string CaptureFlycap::bayerMethodToString (dc1394bayer_method_t f) inline static
Definition at line 117 of file capture_flycap.h.
Referenced by CaptureFlycap().
{
   if (f==DC1394_BAYER_METHOD_NEAREST) {
     return "nearest";
   } else if (f==DC1394_BAYER_METHOD_SIMPLE) {
     return "simple";
   } else if (f==DC1394_BAYER_METHOD_BILINEAR) {
     return "bilinear";
   } else if (f==DC1394_BAYER_METHOD_HQLINEAR) {
     return "hqlinear";
   } else if (f==DC1394_BAYER_METHOD_DOWNSAMPLE) {
     return "downsample";
   } else if (f==DC1394_BAYER_METHOD_EDGESENSE) {
     return "edgesense";
   } else if (f==DC1394_BAYER_METHOD_VNG) {
     return "vng";
   } else if (f==DC1394_BAYER_METHOD_AHD) {
     return "ahd";
   } else {
     return "nearest";
   }
 }
void CaptureFlycap::changed (VarType * group) slot
Definition at line 210 of file capture_flycap.cpp.
References VarTypes::VarType::getName(), VarTypes::VarVal::getType(), readParameterValues(), settings_changed, VarTypes::VARTYPE_ID_LIST, and writeParameterValues().
Referenced by mvc_connect().
{
     if (group->getType()==VARTYPE_ID_LIST) {
       if (group->getName() == "Camera Settings")
         settings_changed = true;
       writeParameterValues( (VarList *)group );
       readParameterValues( (VarList *)group );
     }
 }
void CaptureFlycap::cleanup ()
static string CaptureFlycap::colorFilterToString (dc1394color_filter_t f) inline static
Definition at line 81 of file capture_flycap.h.
Referenced by CaptureFlycap().
{
   if (f==DC1394_COLOR_FILTER_RGGB) {
     return "rggb";
   } else if (f==DC1394_COLOR_FILTER_GBRG) {
     return "gbrg";
   } else if (f==DC1394_COLOR_FILTER_GRBG) {
     return "grbg";
   } else if (f==DC1394_COLOR_FILTER_BGGR) {
     return "bggr";
   } else {
     return "rggb";
   }
 }
bool CaptureFlycap::convertFrame (const RawImage & src, RawImage & target, ColorFormat output_fmt, bool debayer = true, dc1394color_filter_t bayer_format = DC1394_COLOR_FILTER_RGGB, dc1394bayer_method_t bayer_method = DC1394_BAYER_METHOD_HQLINEAR, int y16bits = 16) protected
This function is used internally only The user should call copyAndConvertFrame with parameters setup through the VarTypes settings.
Definition at line 523 of file capture_flycap.cpp.
References RawImage::allocate(), COLOR_MONO16, COLOR_MONO8, COLOR_RAW16, COLOR_RAW8, COLOR_RGB16, COLOR_RGB8, COLOR_YUV411, COLOR_YUV422_UYVY, COLOR_YUV422_YUYV, COLOR_YUV444, Colors::colorFormatToString(), RawImage::ensure_allocation(), RawImage::getColorFormat(), RawImage::getData(), RawImage::getHeight(), VarTypes::VarInt::getInt(), RawImage::getNumBytes(), RawImage::getTime(), RawImage::getWidth(), mutex, RawImage::setTime(), v_height, and v_width.
Referenced by copyAndConvertFrame(), and copyFrame().
{
   mutex.lock();
   int width = v_width->getInt();
   int height = v_height->getInt();
   ColorFormat src_fmt=src.getColorFormat();
   if (target.getData()==0) {
     //allocate target, if it does not exist yet
     target.allocate(output_fmt,src.getWidth(),src.getHeight());
   } else {
     target.ensure_allocation(output_fmt,src.getWidth(),src.getHeight());
   }
   target.setTime(src.getTime());
   if (output_fmt==src_fmt) {
     //just do a memcpy
     memcpy(target.getData(),src.getData(),src.getNumBytes());
   } else {
     //do some more fancy conversion
     if ((src_fmt==COLOR_MONO8 || src_fmt==COLOR_RAW8) && output_fmt==COLOR_RGB8) {
       //check whether to debayer or simply average to a grey rgb image
       if (debayer) {
         //de-bayer
         if ( dc1394_bayer_decoding_8bit( src.getData(), target.getData(), src.getWidth(), src.getHeight(), bayer_format, bayer_method) != DC1394_SUCCESS ) {
           #ifndef VDATA_NO_QT
             mutex.unlock();
           #endif
           return false;
         }
       } else {
         dc1394_convert_to_RGB8(src.getData(),target.getData(), width, height, 0,
                        DC1394_COLOR_CODING_MONO8, 8);
         //Conversions::y2rgb (src.getData(), target.getData(), src.getNumPixels());
       }
     } else if ((src_fmt==COLOR_MONO16 || src_fmt==COLOR_RAW16)) {
       //check whether to debayer or simply average to a grey rgb image
       if (debayer && output_fmt==COLOR_RGB16) {
         //de-bayer
         if ( dc1394_bayer_decoding_16bit( (uint16_t *)src.getData(), (uint16_t *)target.getData(), src.getWidth(), src.getHeight(), bayer_format, bayer_method, y16bits) != DC1394_SUCCESS ) {
           fprintf(stderr,"Error in 16bit Bayer Conversion");
           #ifndef VDATA_NO_QT
             mutex.unlock();
           #endif
           return false;
         }
       } else if (debayer==false && output_fmt==COLOR_RGB8) {
        dc1394_convert_to_RGB8(src.getData(),target.getData(), width, height, 0,
                        ((src_fmt==COLOR_MONO16) ? DC1394_COLOR_CODING_MONO16 : DC1394_COLOR_CODING_RAW16), y16bits);
         //Conversions::y162rgb (src.getData(), target.getData(), src.getNumPixels(), y16bits);
       } else {
       fprintf(stderr,"Cannot copy and convert frame...unknown conversion selected from: %s to %s\n",Colors::colorFormatToString(src_fmt).c_str(),Colors::colorFormatToString(output_fmt).c_str());
       mutex.unlock();
       return false;
       }
     } else if (src_fmt==COLOR_YUV411 && output_fmt==COLOR_RGB8) {
       dc1394_convert_to_RGB8(src.getData(),target.getData(), width, height, 0,
                        DC1394_COLOR_CODING_YUV411, 8);
       //Conversions::uyyvyy2rgb (src.getData(), target.getData(), src.getNumPixels());
     } else if (src_fmt==COLOR_YUV422_UYVY && output_fmt==COLOR_RGB8) {
         dc1394_convert_to_RGB8(src.getData(),target.getData(), width, height, DC1394_BYTE_ORDER_UYVY,
                        DC1394_COLOR_CODING_YUV422, 8);
     } else if (src_fmt==COLOR_YUV422_YUYV && output_fmt==COLOR_RGB8) {
         dc1394_convert_to_RGB8(src.getData(),target.getData(), width, height, DC1394_BYTE_ORDER_YUYV,
                        DC1394_COLOR_CODING_YUV422, 8);
     } else if (src_fmt==COLOR_YUV444 && output_fmt==COLOR_RGB8) {
       dc1394_convert_to_RGB8(src.getData(),target.getData(), width, height, 0,
                        DC1394_COLOR_CODING_YUV444, 8);
     } else {
       fprintf(stderr,"Cannot copy and convert frame...unknown conversion selected from: %s to %s\n",Colors::colorFormatToString(src_fmt).c_str(),Colors::colorFormatToString(output_fmt).c_str());
       mutex.unlock();
       return false;
     }
   }
   mutex.unlock();
   return true;
 }
bool CaptureFlycap::copyAndConvertFrame (const RawImage & src, RawImage & target) virtual
Reimplemented from CaptureInterface.
Definition at line 513 of file capture_flycap.cpp.
References convertFrame(), VarTypes::VarBoolVal::getBool(), VarTypes::VarInt::getInt(), VarTypes::VarStringEnum::getSelection(), stringToBayerMethod(), stringToColorFilter(), Colors::stringToColorFormat(), v_colorout, v_debayer, v_debayer_method, v_debayer_pattern, and v_debayer_y16.
{
   return convertFrame(src,target,
                       Colors::stringToColorFormat(v_colorout->getSelection().c_str()),
                       v_debayer->getBool(),
                       stringToColorFilter(v_debayer_pattern->getSelection().c_str()),
                       stringToBayerMethod(v_debayer_method->getSelection().c_str()),
                       v_debayer_y16->getInt());
 }
bool CaptureFlycap::copyFrame (const RawImage & src, RawImage & target)
will perform a pure memcpy of an image, independent of vartypes conversion settings
Definition at line 509 of file capture_flycap.cpp.
References convertFrame(), and RawImage::getColorFormat().
{
     return convertFrame(src,target,src.getColorFormat());
 }
string CaptureFlycap::getCaptureMethodName () const virtual
Implements CaptureInterface.
Definition at line 647 of file capture_flycap.cpp.
{
     return "Flycap";
 }
RawImage CaptureFlycap::getFrame () virtual
this gives a raw-image with a pointer directly to the video-buffer Note that this pointer is only guaranteed to point to a valid memory location until releaseFrame() is called.
Implements CaptureInterface.
Definition at line 609 of file capture_flycap.cpp.
References camera, capture_format, mutex, pixelFormatToColorFormat(), RawImage::setColorFormat(), RawImage::setData(), RawImage::setHeight(), RawImage::setTime(), RawImage::setWidth(), and stored_image.
{
   mutex.lock();
   Error error;
   Image image;
   RawImage result;
   result.setColorFormat(capture_format);
   result.setWidth(0);
   result.setHeight(0);
   result.setTime(0.0);
   result.setData(0);
   error = camera->RetrieveBuffer(&image);
   if (error != PGRERROR_OK) {
     error.PrintErrorTrace();
     mutex.unlock();
     return result;
   }
   stored_image = new Image;
   stored_image->DeepCopy(&image);
   result.setData(stored_image->GetData());
   struct timeval tv;
   gettimeofday(&tv,NULL);
   result.setTime((double)tv.tv_sec + tv.tv_usec*(1.0E-6));
   result.setHeight(stored_image->GetRows());
   result.setWidth(stored_image->GetCols());
   result.setColorFormat(pixelFormatToColorFormat(stored_image->GetPixelFormat()));
   mutex.unlock();
   return result;
 }
virtual bool CaptureFlycap::isCapturing () inline virtual
Implements CaptureInterface.
Definition at line 196 of file capture_flycap.h.
References role._GoToPoint::target.
Referenced by stopCapture().
 { return is_capturing; };
void CaptureFlycap::mvc_connect (VarList * group)
Definition at line 202 of file capture_flycap.cpp.
References changed(), VarTypes::VarList::getChildren(), velocity.pid_::i, and v.
Referenced by CaptureFlycap().
{
     vector<VarType *> v=group->getChildren();
     for (unsigned int i=0;i<v.size();i++) {
         connect(v[i],SIGNAL(wasEdited(VarType *)),group,SLOT(mvcEditCompleted()));
     }
     connect(group,SIGNAL(wasEdited(VarType *)),this,SLOT(changed(VarType *)));
 }
void CaptureFlycap::readAllParameterValues () virtual
Reimplemented from CaptureInterface.
Definition at line 219 of file capture_flycap.cpp.
References camera_parameters, VarTypes::VarList::getChildren(), velocity.pid_::i, readParameterValues(), v, and VarTypes::VARTYPE_ID_LIST.
{
     vector<VarType *> v=camera_parameters->getChildren();
     for (unsigned int i=0;i<v.size();i++) {
         if (v[i]->getType()==VARTYPE_ID_LIST) {
           readParameterValues((VarList *)v[i]);
         }
     }
 }
void CaptureFlycap::readParameterValues (VarList * item)
Definition at line 237 of file capture_flycap.cpp.
References mutex.
Referenced by changed(), and readAllParameterValues().
{
   mutex.lock();
   mutex.unlock();
 }
void CaptureFlycap::releaseFrame () virtual
Implements CaptureInterface.
Definition at line 641 of file capture_flycap.cpp.
References mutex, and stored_image.
{
   mutex.lock();
   delete stored_image;
   mutex.unlock();
 }
bool CaptureFlycap::resetBus () virtual
Reimplemented from CaptureInterface.
Definition at line 351 of file capture_flycap.cpp.
References guid, and mutex.
{
   mutex.lock();
   BusManager busMgr;
   busMgr.FireBusReset(&guid);
   mutex.unlock();
   return true;
 }
bool CaptureFlycap::startCapture () virtual
Initialize the interface and start capture.
Implements CaptureInterface.
Definition at line 387 of file capture_flycap.cpp.
References active_cam_ids, cam_id, cam_id_mutex, camera, VarTypes::VarInt::getInt(), guid, velocity.pid_::i, is_capturing, is_connected, mutex, v_cam_bus, and writeAllParameterValues().
{
   mutex.lock();
   cam_id_mutex.lock();
   BusManager busMgr;
   Error error;
   unsigned int numCameras;
   int current_id = v_cam_bus->getInt();
   if (current_id >= 0) {
     cam_id = (unsigned int)current_id;
   } else {
     fprintf(stderr, "Flycapture: Invalid cam_id: %d\n", current_id);
     mutex.unlock();
     cam_id_mutex.unlock();
     return false;
   }
   error = busMgr.GetNumOfCameras(&numCameras);
   if (error != PGRERROR_OK)
   {
     error.PrintErrorTrace();
     mutex.unlock();
     cam_id_mutex.unlock();
     return false;
   }
   if(cam_id >= numCameras)
   {
     fprintf(stderr, "Flycapture: Invalid cam_id: %u\n", cam_id);
     mutex.unlock();
     cam_id_mutex.unlock();
     return false;
   }
   bool id_active = false;
   for (size_t i = 0; i < active_cam_ids.size(); i++) {
     if (active_cam_ids[i] == cam_id) {
       id_active = true;
       break;
     }
   }
   if (id_active) {
     fprintf(stderr, "Flycapture: cam_id %u is already in use \n", cam_id);
     mutex.unlock();
     cam_id_mutex.unlock();
     return false;
   }
   camera = new GigECamera();
   error = busMgr.GetCameraFromIndex(v_cam_bus->getInt(), &guid);
   if (error != PGRERROR_OK) {
     error.PrintErrorTrace();
     delete camera;
     mutex.unlock();
     cam_id_mutex.unlock();
     return false;
   }
   error = camera->Connect(&guid);
   if (error != PGRERROR_OK) {
     error.PrintErrorTrace();
     delete camera;
     mutex.unlock();
     cam_id_mutex.unlock();
     return false;
   }
   fprintf(stderr,"Connected");
   is_connected = true;
   CameraInfo camInfo;
   error = camera->GetCameraInfo(&camInfo);
   if (error != PGRERROR_OK) {
     error.PrintErrorTrace();
     delete camera;
     mutex.unlock();
     cam_id_mutex.unlock();
     return false;
   }
   fprintf(stderr," to %s, Serial Number: %u\n",
           camInfo.modelName,
           camInfo.serialNumber);
   Property auto_exposure;
   auto_exposure.onOff = false;
   auto_exposure.onePush = false;
   auto_exposure.type = FlyCapture2::AUTO_EXPOSURE;
   error = camera->SetProperty(&auto_exposure);
   if (error != PGRERROR_OK) {
     mutex.unlock();
     cam_id_mutex.unlock();
     delete camera;
     error.PrintErrorTrace();
     return false;
   }
   writeAllParameterValues();
   error = camera->StartCapture();
   if (error != PGRERROR_OK) {
     error.PrintErrorTrace();
     delete camera;
     mutex.unlock();
     cam_id_mutex.unlock();
     return false;
   }
   is_capturing = true;
   active_cam_ids.push_back(cam_id);
   mutex.unlock();
   cam_id_mutex.unlock();
   return true;
 }
bool CaptureFlycap::stopCapture () virtual
Stop Capture.
Implements CaptureInterface.
Definition at line 361 of file capture_flycap.cpp.
References active_cam_ids, cam_id, cam_id_mutex, camera, is_capturing, is_connected, and isCapturing().
{
   cam_id_mutex.lock();
   if (!isCapturing()) {
     cam_id_mutex.unlock();
     return true;
   }
   for (std::vector<unsigned int>::iterator it = active_cam_ids.begin();
        it != active_cam_ids.end();
        ++it) {
     if (*it == cam_id) {
       active_cam_ids.erase(it);
       break;
     }
   }
   is_capturing = false;
   camera->StopCapture();
   camera->Disconnect();
   is_connected = false;
   delete camera;
   cam_id_mutex.unlock();
   return true;
 }
static dc1394bayer_method_t CaptureFlycap::stringToBayerMethod (const char * s) inline static
Definition at line 95 of file capture_flycap.h.
Referenced by copyAndConvertFrame().
{
   if (strcmp(s,"nearest")==0) {
     return DC1394_BAYER_METHOD_NEAREST;
   } else if (strcmp(s,"simple")==0) {
     return DC1394_BAYER_METHOD_SIMPLE;
   } else if (strcmp(s,"bilinear")==0) {
     return DC1394_BAYER_METHOD_BILINEAR;
   } else if (strcmp(s,"hqlinear")==0) {
     return DC1394_BAYER_METHOD_HQLINEAR;
   } else if (strcmp(s,"downsample")==0) {
     return DC1394_BAYER_METHOD_DOWNSAMPLE;
   } else if (strcmp(s,"edgesense")==0) {
     return DC1394_BAYER_METHOD_EDGESENSE;
   } else if (strcmp(s,"vng")==0) {
     return DC1394_BAYER_METHOD_VNG;
   } else if (strcmp(s,"ahd")==0) {
     return DC1394_BAYER_METHOD_AHD;
   } else {
     return DC1394_BAYER_METHOD_MIN;
   }
 }
static dc1394color_filter_t CaptureFlycap::stringToColorFilter (const char * s) inline static
Definition at line 67 of file capture_flycap.h.
Referenced by copyAndConvertFrame().
{
     if (strcmp(s,"rggb")==0) {
       return DC1394_COLOR_FILTER_RGGB;
     } else if (strcmp(s,"gbrg")==0) {
       return DC1394_COLOR_FILTER_GBRG;
     } else if (strcmp(s,"grbg")==0) {
       return DC1394_COLOR_FILTER_GRBG;
     } else if (strcmp(s,"bggr")==0) {
       return DC1394_COLOR_FILTER_BGGR;
     } else {
       return DC1394_COLOR_FILTER_MIN;
     }
 }
void CaptureFlycap::writeAllParameterValues ()
Definition at line 228 of file capture_flycap.cpp.
References camera_parameters, VarTypes::VarList::getChildren(), velocity.pid_::i, v, VarTypes::VARTYPE_ID_LIST, and writeParameterValues().
Referenced by startCapture().
{
     vector<VarType *> v=camera_parameters->getChildren();
     for (unsigned int i=0;i<v.size();i++) {
         if (v[i]->getType()==VARTYPE_ID_LIST) {
           writeParameterValues((VarList *)v[i]);
         }
     }
 }
void CaptureFlycap::writeParameterValues (VarList * item)
Definition at line 243 of file capture_flycap.cpp.
References camera, colorFormatToPixelFormat(), VarTypes::VarBoolVal::getBool(), VarTypes::VarList::getChildren(), VarTypes::VarDoubleVal::getDouble(), VarTypes::VarInt::getInt(), VarTypes::VarType::getName(), VarTypes::VarStringEnum::getString(), velocity.pid_::i, is_capturing, is_connected, mutex, settings_changed, Colors::stringToColorFormat(), v_colormode, v_height, v_videomode, v_width, v_xoffset, v_yoffset, and videoModeFromString().
Referenced by changed(), and writeAllParameterValues().
{
   if (!is_connected) {
     mutex.lock();
   }
   Error error;
   string item_name = item->getName();
   if (item_name == "Camera Parameters") {
     vector<VarType *> children = item->getChildren();
     for (unsigned int i=0;i<children.size();i++) {
       bool is_property=false;
       Property prop;
       string param_name = children[i]->getName();
       if (param_name == "Video Mode") {
         if (is_connected && !is_capturing) {
           Mode mode = videoModeFromString(v_videomode->getString());
           error = camera->SetGigEImagingMode(mode);
           if (error != PGRERROR_OK) {
             error.PrintErrorTrace();
             mutex.unlock();
             return;
           }
         }
       } else if (param_name == "Brightness") {
         is_property = true;
         prop.type = FlyCapture2::BRIGHTNESS;
       } else if (param_name == "Shutter") {
         is_property = true;
         prop.type = FlyCapture2::SHUTTER;
       }
       else if (param_name == "Gain") {
         is_property = true;
         prop.type = FlyCapture2::GAIN;
       }
       else if (param_name == "Gamma") {
         is_property = true;
         prop.type = FlyCapture2::GAMMA;
       }
       else if (param_name == "Frame Rate") {
         is_property = true;
         prop.type = FlyCapture2::FRAME_RATE;
       }
       else if (param_name == "White Balance") {
         is_property = true;
         prop.type = FlyCapture2::WHITE_BALANCE;
       }
       if (is_property) {
         prop.onePush = false;
         prop.onOff = true;
         prop.autoManualMode = false;
         prop.absControl = true;
         if (is_connected) {
           if (param_name == "White Balance")  {
             vector<VarType *> grandchildren = children[i]->getChildren();
             VarBool* vOnOff = (VarBool*)grandchildren[0];
             VarInt* vRed = (VarInt*)grandchildren[1];
             VarInt* vBlue = (VarInt*)grandchildren[2];
             prop.onOff = vOnOff->getBool();
             prop.valueA = vRed->getInt();
             prop.valueB = vBlue->getInt();
           }
           else {
             VarDouble* current_double = (VarDouble *)children[i];
             double absvalue = current_double->getDouble();
             prop.absValue = (float)absvalue;
           }
           error = camera->SetProperty(&prop);
           if (error != PGRERROR_OK) {
             mutex.unlock();
             error.PrintErrorTrace();
             return;
           }
         }
       }
     }
   }
   if (settings_changed) {
     if (is_connected) {
       GigEImageSettings imageSettings;
       imageSettings.offsetX = v_xoffset->getInt();
       imageSettings.offsetY = v_yoffset->getInt();
       imageSettings.height = v_height->getInt();
       imageSettings.width = v_width->getInt();
       imageSettings.pixelFormat = colorFormatToPixelFormat(Colors::stringToColorFormat(v_colormode->getString().c_str()));
       error = camera->SetGigEImageSettings(&imageSettings);
       if (error != PGRERROR_OK) {
         error.PrintErrorTrace();
         mutex.unlock();
         return;
       }
       settings_changed = false;
     }
   }
   if(!is_connected){
     mutex.unlock();
   }
 }
Field Documentation
std::vector< unsigned int > CaptureFlycap::active_cam_ids static protected
Definition at line 182 of file capture_flycap.h.
Referenced by startCapture(), and stopCapture().
unsigned int CaptureFlycap::cam_id protected
Definition at line 171 of file capture_flycap.h.
Referenced by CaptureFlycap(), startCapture(), and stopCapture().
QMutex CaptureFlycap::cam_id_mutex static protected
Definition at line 183 of file capture_flycap.h.
Referenced by startCapture(), and stopCapture().
FlyCapture2::GigECamera* CaptureFlycap::camera protected
Definition at line 178 of file capture_flycap.h.
Referenced by CaptureFlycap(), getFrame(), startCapture(), stopCapture(), and writeParameterValues().
VarList* CaptureFlycap::camera_parameters protected
Definition at line 173 of file capture_flycap.h.
Referenced by CaptureFlycap(), readAllParameterValues(), and writeAllParameterValues().
ColorFormat CaptureFlycap::capture_format protected
Definition at line 172 of file capture_flycap.h.
Referenced by getFrame().
VarList* CaptureFlycap::capture_settings protected
Definition at line 174 of file capture_flycap.h.
Referenced by CaptureFlycap().
ApplicationData CaptureFlycap::cbData protected
Definition at line 141 of file capture_flycap.h.
VarList* CaptureFlycap::conversion_settings protected
Definition at line 175 of file capture_flycap.h.
Referenced by CaptureFlycap().
unsigned char* CaptureFlycap::currentFrame protected
Definition at line 144 of file capture_flycap.h.
Referenced by CaptureFlycap().
const char* CaptureFlycap::dev_name protected
Definition at line 142 of file capture_flycap.h.
FlyCapture2::PGRGuid CaptureFlycap::guid protected
Definition at line 179 of file capture_flycap.h.
Referenced by resetBus(), and startCapture().
bool CaptureFlycap::is_capturing protected
Definition at line 146 of file capture_flycap.h.
Referenced by CaptureFlycap(), startCapture(), stopCapture(), and writeParameterValues().
bool CaptureFlycap::is_connected protected
Definition at line 149 of file capture_flycap.h.
Referenced by CaptureFlycap(), startCapture(), stopCapture(), and writeParameterValues().
QMutex CaptureFlycap::mutex protected
Definition at line 64 of file capture_flycap.h.
Referenced by CaptureFlycap(), convertFrame(), getFrame(), readParameterValues(), releaseFrame(), resetBus(), startCapture(), and writeParameterValues().
VarList* CaptureFlycap::P_WHITE_BALANCE protected
Definition at line 159 of file capture_flycap.h.
Referenced by CaptureFlycap().
string CaptureFlycap::prev_mode_string protected
Definition at line 148 of file capture_flycap.h.
int CaptureFlycap::previous_id protected
Definition at line 170 of file capture_flycap.h.
Referenced by CaptureFlycap().
bool CaptureFlycap::settings_changed protected
Definition at line 147 of file capture_flycap.h.
Referenced by CaptureFlycap(), changed(), and writeParameterValues().
FlyCapture2::Image* CaptureFlycap::stored_image protected
Definition at line 180 of file capture_flycap.h.
Referenced by CaptureFlycap(), getFrame(), and releaseFrame().
VarInt* CaptureFlycap::v_cam_bus protected
Definition at line 162 of file capture_flycap.h.
Referenced by CaptureFlycap(), and startCapture().
VarStringEnum* CaptureFlycap::v_colormode protected
Definition at line 168 of file capture_flycap.h.
Referenced by CaptureFlycap(), and writeParameterValues().
VarStringEnum* CaptureFlycap::v_colorout protected
Definition at line 152 of file capture_flycap.h.
Referenced by CaptureFlycap(), and copyAndConvertFrame().
VarBool* CaptureFlycap::v_debayer protected
Definition at line 156 of file capture_flycap.h.
Referenced by CaptureFlycap(), and copyAndConvertFrame().
VarStringEnum* CaptureFlycap::v_debayer_method protected
Definition at line 154 of file capture_flycap.h.
Referenced by CaptureFlycap(), and copyAndConvertFrame().
VarStringEnum* CaptureFlycap::v_debayer_pattern protected
Definition at line 153 of file capture_flycap.h.
Referenced by CaptureFlycap(), and copyAndConvertFrame().
VarInt* CaptureFlycap::v_debayer_y16 protected
Definition at line 155 of file capture_flycap.h.
Referenced by CaptureFlycap(), and copyAndConvertFrame().
VarInt* CaptureFlycap::v_height protected
Definition at line 164 of file capture_flycap.h.
Referenced by CaptureFlycap(), convertFrame(), and writeParameterValues().
VarStringEnum* CaptureFlycap::v_videomode protected
Definition at line 167 of file capture_flycap.h.
Referenced by CaptureFlycap(), and writeParameterValues().
VarInt* CaptureFlycap::v_width protected
Definition at line 163 of file capture_flycap.h.
Referenced by CaptureFlycap(), convertFrame(), and writeParameterValues().
VarInt* CaptureFlycap::v_xoffset protected
Definition at line 165 of file capture_flycap.h.
Referenced by CaptureFlycap(), and writeParameterValues().
VarInt* CaptureFlycap::v_yoffset protected
Definition at line 166 of file capture_flycap.h.
Referenced by CaptureFlycap(), and writeParameterValues().
The documentation for this class was generated from the following files:
ssl-vision/src/shared/capture/capture_flycap.h
ssl-vision/src/shared/capture/capture_flycap.cpp