Documentation: BitFlags< num > Class Template Reference
BitFlags< num > Class Template Reference
#include <bitflags.h>
Public Member Functions
bool isRaised (num const &val) const
bool isDropped (num const &val) const
bool areAnyRaised (num const &val) const
bool areAnyDropped (num const &val) const
void set (num const &val)
num get () const
bool isClear ()
void clear ()
void drop (num const &val)
void raise (num const &val)
BitFlags ()
BitFlags (const num &p)
void operator= (const BitFlags< num > &p)
bool operator== (const BitFlags< num > &p) const
bool operator!= (const BitFlags< num > &p) const
BitFlags< num > operator& (const BitFlags< num > &p) const
BitFlags< num > operator| (const BitFlags< num > &p) const
BitFlags< num > operator^ (const BitFlags< num > &p) const
BitFlags< num > & operator&= (const BitFlags< num > &p) const
BitFlags< num > & operator|= (const BitFlags< num > &p) const
BitFlags< num > & operator^= (const BitFlags< num > &p) const
BitFlags< num > operator~ () const
void operator= (const num &p)
bool operator== (const num &p) const
bool operator!= (const num &p) const
num operator& (const num &p) const
num operator| (const num &p) const
num operator^ (const num &p) const
num & operator&= (const num &p) const
num & operator|= (const num &p) const
num & operator^= (const num &p) const
Protected Attributes
num data
Detailed Description
template<class num = uint32_t>
class BitFlags< num >
Definition at line 28 of file bitflags.h.
Constructor & Destructor Documentation
template<class num = uint32_t> BitFlags< num >::BitFlags () inline
Definition at line 75 of file bitflags.h.
References BitFlags< num >::clear().
   {
     clear();
   }
template<class num = uint32_t> BitFlags< num >::BitFlags (const num & p) inline
Definition at line 80 of file bitflags.h.
   {
     data=p;
   }
Member Function Documentation
template<class num = uint32_t> bool BitFlags< num >::areAnyDropped (num const & val) const inline
Definition at line 46 of file bitflags.h.
   {
     return ((data & val) != val);
   }
template<class num = uint32_t> bool BitFlags< num >::areAnyRaised (num const & val) const inline
Definition at line 42 of file bitflags.h.
   {
     return ((data & val) != 0x00);
   };
template<class num = uint32_t> void BitFlags< num >::clear () inline
Definition at line 62 of file bitflags.h.
Referenced by BitFlags< num >::BitFlags().
   {
     data=0x00;
   };
template<class num = uint32_t> void BitFlags< num >::drop (num const & val) inline
Definition at line 66 of file bitflags.h.
   {
     data&=(~val);
   };
template<class num = uint32_t> num BitFlags< num >::get () const inline
Definition at line 54 of file bitflags.h.
References BitFlags< num >::data.
Referenced by BitFlags< num >::operator&(), BitFlags< num >::operator=(), BitFlags< num >::operator==(), BitFlags< num >::operator^(), BitFlags< num >::operator|(), and BitFlags< num >::operator~().
     {
       return data;
     }
template<class num = uint32_t> bool BitFlags< num >::isClear () inline
Definition at line 58 of file bitflags.h.
   {
     return (data==0x00);
   }
template<class num = uint32_t> bool BitFlags< num >::isDropped (num const & val) const inline
Definition at line 38 of file bitflags.h.
   {
     return ((data & val) == 0x00);
   };
template<class num = uint32_t> bool BitFlags< num >::isRaised (num const & val) const inline
Definition at line 34 of file bitflags.h.
   {
     return ((data & val) == val);
   };
template<class num = uint32_t> bool BitFlags< num >::operator!= (const BitFlags< num > & p) const inline
Definition at line 93 of file bitflags.h.
References BitFlags< num >::operator==().
   {
     return !operator==(p);
   }
template<class num = uint32_t> bool BitFlags< num >::operator!= (const num & p) const inline
Definition at line 138 of file bitflags.h.
References BitFlags< num >::operator==().
   {
     return !operator==(p);
   }
template<class num = uint32_t> BitFlags<num> BitFlags< num >::operator& (const BitFlags< num > & p) const inline
Definition at line 97 of file bitflags.h.
References BitFlags< num >::get().
   {
     return data&p.get();
   }
template<class num = uint32_t> num BitFlags< num >::operator& (const num & p) const inline
Definition at line 142 of file bitflags.h.
   {
     return data&p;
   }
template<class num = uint32_t> BitFlags<num>& BitFlags< num >::operator&= (const BitFlags< num > & p) const inline
Definition at line 109 of file bitflags.h.
   {
     data&=p;
     return (*this);
   }
template<class num = uint32_t> num& BitFlags< num >::operator&= (const num & p) const inline
Definition at line 154 of file bitflags.h.
   {
     data&=p;
     return (*this);
   }
template<class num = uint32_t> void BitFlags< num >::operator= (const BitFlags< num > & p) inline
Definition at line 85 of file bitflags.h.
References BitFlags< num >::get().
   {
     data=p.get();
   }
template<class num = uint32_t> void BitFlags< num >::operator= (const num & p) inline
Definition at line 130 of file bitflags.h.
   {
     data=p;
   }
template<class num = uint32_t> bool BitFlags< num >::operator== (const BitFlags< num > & p) const inline
Definition at line 89 of file bitflags.h.
References BitFlags< num >::get().
Referenced by BitFlags< num >::operator!=().
   {
     return data==p.get();
   }
template<class num = uint32_t> bool BitFlags< num >::operator== (const num & p) const inline
Definition at line 134 of file bitflags.h.
   {
     return data==p;
   }
template<class num = uint32_t> BitFlags<num> BitFlags< num >::operator^ (const BitFlags< num > & p) const inline
Definition at line 105 of file bitflags.h.
References BitFlags< num >::get().
   {
     return data^p.get();
   }
template<class num = uint32_t> num BitFlags< num >::operator^ (const num & p) const inline
Definition at line 150 of file bitflags.h.
   {
     return data^p;
   }
template<class num = uint32_t> BitFlags<num>& BitFlags< num >::operator^= (const BitFlags< num > & p) const inline
Definition at line 119 of file bitflags.h.
   {
     data^=p;
     return (*this);
   }
template<class num = uint32_t> num& BitFlags< num >::operator^= (const num & p) const inline
Definition at line 164 of file bitflags.h.
   {
     data^=p;
     return (*this);
   }
template<class num = uint32_t> BitFlags<num> BitFlags< num >::operator| (const BitFlags< num > & p) const inline
Definition at line 101 of file bitflags.h.
References BitFlags< num >::get().
   {
     return data|p.get();
   }
template<class num = uint32_t> num BitFlags< num >::operator| (const num & p) const inline
Definition at line 146 of file bitflags.h.
   {
     return data|p.get();
   }
template<class num = uint32_t> BitFlags<num>& BitFlags< num >::operator|= (const BitFlags< num > & p) const inline
Definition at line 114 of file bitflags.h.
   {
     data|=p;
     return (*this);
   }
template<class num = uint32_t> num& BitFlags< num >::operator|= (const num & p) const inline
Definition at line 159 of file bitflags.h.
   {
     data|=p;
     return (*this);
   }
template<class num = uint32_t> BitFlags<num> BitFlags< num >::operator~ () const inline
Definition at line 124 of file bitflags.h.
References BitFlags< num >::data, and BitFlags< num >::get().
   {
     BitFlags<num> res;
     res.data=~get();
     return res;
   }
template<class num = uint32_t> void BitFlags< num >::raise (num const & val) inline
Definition at line 70 of file bitflags.h.
   {
     data|=val;
   };
template<class num = uint32_t> void BitFlags< num >::set (num const & val) inline
Definition at line 50 of file bitflags.h.
   {
     data=val;
   };
Field Documentation
template<class num = uint32_t> num BitFlags< num >::data protected
Definition at line 31 of file bitflags.h.
Referenced by BitFlags< num >::get(), and BitFlags< num >::operator~().
The documentation for this class was generated from the following file:
ssl-vision/src/shared/util/bitflags.h