Documentation: tactics.sample_tactic.SampleTactic Class Reference
tactics.sample_tactic.SampleTactic Class Reference
Data Structures
class State
Public Member Functions
def __init__ (self)
Init method for SampleTactic.
def add_kub (self, kub)
def on_enter_running (self)
def execute_running (self)
def on_exit_running (self)
def on_enter_preparing (self)
def execute_preparing (self)
def on_exit_preparing (self)
Public Member Functions inherited from composite_behavior.CompositeBehavior
def __init__ (self)
def add_subbehavior (self, bhvr, name, required=True, priority=100)
Adds a subbehavior in composite behavior.
def remove_subbehavior (self, name)
def has_subbehavior_with_name (self, name)
def has_subbehaviors (self)
def subbehavior_with_name (self, name)
def subbehaviors_by_name (self)
def remove_all_subbehaviors (self)
def all_subbehaviors (self)
def all_subbehaviors_completed (self)
def spin_cb (self)
Override StateMachine.spin() so we can call spin() on subbehaviors.
def handle_subbehavior_exception (self, name, exception)
Override point for exception handling this is called whenever a subbehavior throws an exception during spin() subclasses of CompositeBehavior can override this to perform custom actions, such as removing the offending subbehavior the default implementation logs the exception and re-raises it.
def role_requirements (self)
returns a tree of role_requirements
def assign_roles (self, assignments)
assignments is a tree with the same structure as that returned by role_requirements() the only difference is that leaf nodes are (RoleRequirements, OurRobot) tuples instead of just RoleRequirements
def __str__ (self)
Public Member Functions inherited from behavior.Behavior
def __init__ (self)
def is_done_running (self)
Whether or not the Behavior is running Because we use hierarchial state machines, a behavior never be in the "running", but may be in a substate of it This is a convenience method to check whether or not the play is running.
def set_failed (self)
Set the behavior to failed if sub behaviors remains uncompleted.
def terminate (self)
Transitions the Behavior into a terminal state (either completed or cancelled)
def behavior_state (self)
returns a state in Behavior.State that represents what the behaviors is doing use this instead of the property if you want to avoid dealing with custom subclass substates
Public Member Functions inherited from fsm.StateMachine
def __init__ (self, start_state, end_state)
def start_state (self)
def restart (self)
def add_state (self, state, parent_state=None)
def spin (self)
def add_transition (self, from_state, to_state, condition, event_name)
def transition (self, new_state)
def is_in_state (self, state)
def state_is_substate (self, state, possible_parent)
def corresponding_ancestor_state (self, ancestors)
def ancestors_of_state (self, state)
def as_graphviz (self)
def write_diagram_png (self)
def state (self)
Data Fields
kub
fetch
Detailed Description
Definition at line 16 of file sample_tactic.py.
Constructor & Destructor Documentation
def tactics.sample_tactic.SampleTactic.__init__ (self)
Init method for SampleTactic.
Parameters
skillreceiver an instance of a class that will handle the receiving robot. See pass_receive and angle_receive for examples. Using this, you can change what the receiving robot does (rather than just receiving the ball, it can pass or shoot it). Subclasses of pass_receive are preferred, but check the usage of this variable to be sure.
receive_point The point that will be kicked too. (Target point)
skillkicker A tuple of this form (kicking_class instance, ready_lambda). If none, it will use (pivot_kick lambda x: x == pivot_kick.State.aimed).
receiver_required Whether the receiver subbehavior should be required or not
kicker_required Whether the kicker subbehavior should be required or not The lambda equation is called (passed with the state of your class instance) to see if your class is ready. Simple implementations will just compare it to your ready state.
Definition at line 32 of file sample_tactic.py.
References fsm.StateMachine.add_state(), and fsm.StateMachine.add_transition().
     def __init__(self):
         super(SampleTactic,self).__init__()
         self.add_state(SampleTactic.State.preparing,
                        behavior.Behavior.State.running)
         self.add_state(SampleTactic.State.running,
                        behavior.Behavior.State.running)
         self.add_transition(behavior.Behavior.State.start,
                             SampleTactic.State.preparing, lambda: True,
                             'immediately')
         self.add_transition(
             SampleTactic.State.preparing, SampleTactic.State.running,
             lambda: True,
             'ready')
         # self.add_transition(
         #     SampleTactic.State.running, behavior.Behavior.State.completed,
         #     lambda: self.done_running(),
         #     'done!')
Member Function Documentation
def tactics.sample_tactic.SampleTactic.add_kub (self, kub)
Definition at line 60 of file sample_tactic.py.
     def add_kub(self,kub):
         self.kub = kub
def tactics.sample_tactic.SampleTactic.execute_preparing (self)
Definition at line 102 of file sample_tactic.py.
     def execute_preparing(self):
         pass
def tactics.sample_tactic.SampleTactic.execute_running (self)
Definition at line 66 of file sample_tactic.py.
     def execute_running(self):
         pass
def tactics.sample_tactic.SampleTactic.on_enter_preparing (self)
Definition at line 75 of file sample_tactic.py.
     def on_enter_preparing(self):
         # self.kub.state = shared.get('state')
         print (self.kub.get_pos().x,self.kub.get_pos().y)
         self.fetch = GoToBall.GoToBall()
         self.fetch.add_kub(self.kub)
         goal = Vector2D(HALF_FIELD_MAXX,0)
         ballPos = Vector2D()
         angle = normalize_angle()
         self.fetch.add_theta(theta=normalize_angle(pi+atan2(self.kub.state.ballPos.y,self.kub.state.ballPos.y-3000)))
         self.add_subbehavior(self.fetch,'fetch')
         # self.kub.state = shared.get('state')
         print (self.kub.get_pos().x,self.kub.get_pos().y)
         self.fetch = GoToBall.GoToBall()
         self.fetch.add_kub(self.kub)
         self.fetch.add_theta(theta=normalize_angle(pi+atan2(self.kub.state.ballPos.y,self.kub.state.ballPos.y-3000)))
         self.add_subbehavior(self.fetch,'move')
         print (self.kub.get_pos().x,self.kub.get_pos().y)
         # self.move = GoToPoint.GoToPoint()
         # self.move.add_kub(self.kub)
         # self.move.add_point(point=Vector2D(3000,0),orient=normalize_angle(pi))
         # self.add_subbehavior(self.move,'move')
         pass
def tactics.sample_tactic.SampleTactic.on_enter_running (self)
Definition at line 63 of file sample_tactic.py.
     def on_enter_running(self):
         pass
def tactics.sample_tactic.SampleTactic.on_exit_preparing (self)
Definition at line 105 of file sample_tactic.py.
     def on_exit_preparing(self):
         pass
def tactics.sample_tactic.SampleTactic.on_exit_running (self)
Definition at line 69 of file sample_tactic.py.
References composite_behavior.CompositeBehavior.remove_subbehavior().
     def on_exit_running(self):
         self.remove_subbehavior('fetch')
         self.remove_subbehavior('move')
         pass
Field Documentation
tactics.sample_tactic.SampleTactic.fetch
Definition at line 78 of file sample_tactic.py.
tactics.sample_tactic.SampleTactic.kub
Definition at line 61 of file sample_tactic.py.
The documentation for this class was generated from the following file:
tactics/sample_tactic.py