Documentation: CMVision::ImageProcessor Class Reference
CMVision::ImageProcessor Class Reference
#include <cmvision_region.h>
Public Member Functions
ImageProcessor (YUVLUT *_lut, int _max_regions=10000, int _max_runs=50000)
~ImageProcessor ()
void processYUV422_UYVY (const RawImage *image, int min_blob_area)
void processYUV444 (const ImageInterface *image, int min_blob_area)
void processThresholded (Image< raw8 > *_img_thresholded, int min_blob_area)
ColorRegionList * getColorRegionList ()
Protected Attributes
YUVLUT * lut
int max_regions
int max_runs
CMVision::RegionList * reglist
CMVision::ColorRegionList * colorlist
CMVision::RunList * runlist
Image< raw8 > * img_thresholded
Detailed Description
Definition at line 311 of file cmvision_region.h.
Constructor & Destructor Documentation
CMVision::ImageProcessor::ImageProcessor (YUVLUT * _lut, int _max_regions = 10000, int _max_runs = 50000)
Definition at line 390 of file cmvision_region.cpp.
{
   lut=_lut;
   max_regions=_max_regions;
   max_runs=_max_runs;
   img_thresholded = new Image<raw8>();
   runlist = new CMVision::RunList(max_runs);
   reglist = new CMVision::RegionList(max_regions);
   colorlist = new CMVision::ColorRegionList(lut->getChannelCount());
 }
CMVision::ImageProcessor::~ImageProcessor ()
Definition at line 400 of file cmvision_region.cpp.
{
   delete reglist;
   delete colorlist;
   delete runlist;
   delete img_thresholded;
 }
Member Function Documentation
ColorRegionList * CMVision::ImageProcessor::getColorRegionList ()
Definition at line 444 of file cmvision_region.cpp.
Referenced by CMPattern::MultiPatternModel::loadSinglePatternImage().
{
   return colorlist;
 }
void CMVision::ImageProcessor::processThresholded (Image< raw8 > * _img_thresholded, int min_blob_area)
Definition at line 423 of file cmvision_region.cpp.
References CMVision::RegionProcessing::connectComponents(), CMVision::RegionProcessing::encodeRuns(), CMVision::RegionProcessing::extractRegions(), CMVision::RegionProcessing::separateRegions(), and CMVision::RegionProcessing::sortRegions().
{
   CMVision::RegionProcessing::encodeRuns(_img_thresholded, runlist);
   if (runlist->getUsedRuns() == runlist->getMaxRuns()) {
     printf("Warning: runlength encoder exceeded current max run size of %d\n",runlist->getMaxRuns());
   }
   //Connect the components of the runlength map:
   CMVision::RegionProcessing::connectComponents(runlist);
   //Extract Regions from runlength map:
   CMVision::RegionProcessing::extractRegions(reglist, runlist);
   if (reglist->getUsedRegions() == reglist->getMaxRegions()) {
     printf("Warning: extract regions exceeded maximum number of %d regions\n",reglist->getMaxRegions());
   }
   //Separate Regions by colors:
   int max_area = CMVision::RegionProcessing::separateRegions(colorlist, reglist, min_blob_area);
   CMVision::RegionProcessing::sortRegions(colorlist,max_area);
 }
void CMVision::ImageProcessor::processYUV422_UYVY (const RawImage * image, int min_blob_area)
Definition at line 407 of file cmvision_region.cpp.
References RawImage::getHeight(), RawImage::getWidth(), and CMVisionThreshold::thresholdImageYUV422_UYVY().
{
   img_thresholded->allocate(image->getWidth(),image->getHeight());
   CMVisionThreshold::thresholdImageYUV422_UYVY(img_thresholded,image,lut);
   processThresholded(img_thresholded,min_blob_area);
 }
void CMVision::ImageProcessor::processYUV444 (const ImageInterface * image, int min_blob_area)
Definition at line 413 of file cmvision_region.cpp.
References ImageInterface::getHeight(), ImageInterface::getWidth(), and CMVisionThreshold::thresholdImageYUV444().
Referenced by CMPattern::MultiPatternModel::loadSinglePatternImage().
{
   img_thresholded->allocate(image->getWidth(),image->getHeight());
   CMVisionThreshold::thresholdImageYUV444(img_thresholded,image,lut);
   /*DEBUG OUTPUT: rgbImage out;
   CMVisionThreshold::colorizeImageFromThresholding(out, *img_thresholded,  lut);
   out.save("output.jpg");
   //exit(0);*/
   processThresholded(img_thresholded,min_blob_area);
 }
Field Documentation
CMVision::ColorRegionList* CMVision::ImageProcessor::colorlist protected
Definition at line 317 of file cmvision_region.h.
Image<raw8>* CMVision::ImageProcessor::img_thresholded protected
Definition at line 319 of file cmvision_region.h.
YUVLUT* CMVision::ImageProcessor::lut protected
Definition at line 313 of file cmvision_region.h.
int CMVision::ImageProcessor::max_regions protected
Definition at line 314 of file cmvision_region.h.
int CMVision::ImageProcessor::max_runs protected
Definition at line 315 of file cmvision_region.h.
CMVision::RegionList* CMVision::ImageProcessor::reglist protected
Definition at line 316 of file cmvision_region.h.
CMVision::RunList* CMVision::ImageProcessor::runlist protected
Definition at line 318 of file cmvision_region.h.
The documentation for this class was generated from the following files:
ssl-vision/src/shared/cmvision/cmvision_region.h
ssl-vision/src/shared/cmvision/cmvision_region.cpp