Documentation: SSL_DetectionBall Class Reference
SSL_DetectionBall Class Reference
#include <messages_robocup_ssl_detection.pb.h>
Public Member Functions
SSL_DetectionBall ()
virtual ~SSL_DetectionBall ()
SSL_DetectionBall (const SSL_DetectionBall &from)
SSL_DetectionBall & operator= (const SSL_DetectionBall &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_DetectionBall *other)
SSL_DetectionBall * New () const PROTOBUF_FINAL
SSL_DetectionBall * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_DetectionBall &from)
void MergeFrom (const SSL_DetectionBall &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_confidence () const
void clear_confidence ()
float confidence () const
void set_confidence (float value)
bool has_area () const
void clear_area ()
::google::protobuf::uint32 area () const
void set_area (::google::protobuf::uint32 value)
bool has_x () const
void clear_x ()
float x () const
void set_x (float value)
bool has_y () const
void clear_y ()
float y () const
void set_y (float value)
bool has_z () const
void clear_z ()
float z () const
void set_z (float value)
bool has_pixel_x () const
void clear_pixel_x ()
float pixel_x () const
void set_pixel_x (float value)
bool has_pixel_y () const
void clear_pixel_y ()
float pixel_y () const
void set_pixel_y (float value)
SSL_DetectionBall ()
virtual ~SSL_DetectionBall ()
SSL_DetectionBall (const SSL_DetectionBall &from)
SSL_DetectionBall & operator= (const SSL_DetectionBall &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (SSL_DetectionBall *other)
SSL_DetectionBall * New () const PROTOBUF_FINAL
SSL_DetectionBall * New (::google::protobuf::Arena *arena) const PROTOBUF_FINAL
void CopyFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void MergeFrom (const ::google::protobuf::Message &from) PROTOBUF_FINAL
void CopyFrom (const SSL_DetectionBall &from)
void MergeFrom (const SSL_DetectionBall &from)
void Clear () PROTOBUF_FINAL
bool IsInitialized () const PROTOBUF_FINAL
size_t ByteSizeLong () const PROTOBUF_FINAL
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) PROTOBUF_FINAL
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const PROTOBUF_FINAL
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const PROTOBUF_FINAL
int GetCachedSize () const PROTOBUF_FINAL
::google::protobuf::Metadata GetMetadata () const PROTOBUF_FINAL
bool has_confidence () const
void clear_confidence ()
float confidence () const
void set_confidence (float value)
bool has_area () const
void clear_area ()
::google::protobuf::uint32 area () const
void set_area (::google::protobuf::uint32 value)
bool has_x () const
void clear_x ()
float x () const
void set_x (float value)
bool has_y () const
void clear_y ()
float y () const
void set_y (float value)
bool has_z () const
void clear_z ()
float z () const
void set_z (float value)
bool has_pixel_x () const
void clear_pixel_x ()
float pixel_x () const
void set_pixel_x (float value)
bool has_pixel_y () const
void clear_pixel_y ()
float pixel_y () const
void set_pixel_y (float value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_DetectionBall & default_instance ()
static const SSL_DetectionBall * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const SSL_DetectionBall & default_instance ()
static void InitAsDefaultInstance ()
static const SSL_DetectionBall * internal_default_instance ()
Static Public Attributes
static const int kConfidenceFieldNumber = 1
static const int kAreaFieldNumber = 2
static const int kXFieldNumber = 3
static const int kYFieldNumber = 4
static const int kZFieldNumber = 5
static const int kPixelXFieldNumber = 6
static const int kPixelYFieldNumber = 7
static PROTOBUF_CONSTEXPR int const kIndexInFileMessages
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_DetectionBall *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_confidence ()
void clear_has_confidence ()
void set_has_area ()
void clear_has_area ()
void set_has_x ()
void clear_has_x ()
void set_has_y ()
void clear_has_y ()
void set_has_z ()
void clear_has_z ()
void set_has_pixel_x ()
void clear_has_pixel_x ()
void set_has_pixel_y ()
void clear_has_pixel_y ()
size_t RequiredFieldsByteSizeFallback () const
friendconst::google::protobuf::uint32 * protobuf_Offsets_messages_5frobocup_5fssl_5fdetection_2eproto ()
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const PROTOBUF_FINAL
void InternalSwap (SSL_DetectionBall *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_confidence ()
void clear_has_confidence ()
void set_has_area ()
void clear_has_area ()
void set_has_x ()
void clear_has_x ()
void set_has_y ()
void clear_has_y ()
void set_has_z ()
void clear_has_z ()
void set_has_pixel_x ()
void clear_has_pixel_x ()
void set_has_pixel_y ()
void clear_has_pixel_y ()
size_t RequiredFieldsByteSizeFallback () const
friend void::protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::InitDefaultsSSL_DetectionBallImpl ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
int _cached_size_
float confidence_
::google::protobuf::uint32 area_
float x_
float y_
float z_
float pixel_x_
float pixel_y_
Friends
struct ::protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::TableStruct
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto_impl ()
void protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_impl ()
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fdetection_2eproto ()
void swap (SSL_DetectionBall &a, SSL_DetectionBall &b)
Detailed Description
Definition at line 47 of file messages_robocup_ssl_detection.pb.h.
Constructor & Destructor Documentation
SSL_DetectionBall::SSL_DetectionBall ()
virtual SSL_DetectionBall::~SSL_DetectionBall () virtual
SSL_DetectionBall::SSL_DetectionBall (const SSL_DetectionBall & from)
SSL_DetectionBall::SSL_DetectionBall ()
virtual SSL_DetectionBall::~SSL_DetectionBall () virtual
SSL_DetectionBall::SSL_DetectionBall (const SSL_DetectionBall & from)
Member Function Documentation
google::protobuf::uint32 SSL_DetectionBall::area () const inline
Definition at line 593 of file messages_robocup_ssl_detection.pb.h.
References area_.
Referenced by main().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionBall.area)
   return area_;
 }
::google::protobuf::uint32 SSL_DetectionBall::area () const
size_t SSL_DetectionBall::ByteSizeLong () const
Referenced by New(), SSL_DetectionRobot::New(), and SSL_DetectionFrame::New().
size_t SSL_DetectionBall::ByteSizeLong () const
void SSL_DetectionBall::Clear ()
Referenced by New(), SSL_DetectionRobot::New(), and SSL_DetectionFrame::New().
void SSL_DetectionBall::Clear ()
void SSL_DetectionBall::clear_area () inline
Definition at line 589 of file messages_robocup_ssl_detection.pb.h.
References area_, and clear_has_area().
{
   area_ = 0u;
   clear_has_area();
 }
void SSL_DetectionBall::clear_area ()
void SSL_DetectionBall::clear_confidence () inline
Definition at line 565 of file messages_robocup_ssl_detection.pb.h.
References clear_has_confidence(), and confidence_.
Referenced by MaybeArenaPtr(), and SSL_DetectionRobot::MaybeArenaPtr().
{
   confidence_ = 0;
   clear_has_confidence();
 }
void SSL_DetectionBall::clear_confidence ()
void SSL_DetectionBall::clear_has_area () inline private
Definition at line 586 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by clear_area().
{
   _has_bits_[0] &= ~0x00000002u;
 }
void SSL_DetectionBall::clear_has_area () private
void SSL_DetectionBall::clear_has_confidence () inline private
Definition at line 562 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by clear_confidence(), and SSL_DetectionRobot::clear_confidence().
{
   _has_bits_[0] &= ~0x00000001u;
 }
void SSL_DetectionBall::clear_has_confidence () private
void SSL_DetectionBall::clear_has_pixel_x () inline private
Definition at line 682 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by clear_pixel_x(), and SSL_DetectionRobot::clear_pixel_x().
{
   _has_bits_[0] &= ~0x00000020u;
 }
void SSL_DetectionBall::clear_has_pixel_x () private
void SSL_DetectionBall::clear_has_pixel_y () inline private
Definition at line 706 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by clear_pixel_y(), and SSL_DetectionRobot::clear_pixel_y().
{
   _has_bits_[0] &= ~0x00000040u;
 }
void SSL_DetectionBall::clear_has_pixel_y () private
void SSL_DetectionBall::clear_has_x () inline private
Definition at line 610 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by clear_x(), and SSL_DetectionRobot::clear_x().
{
   _has_bits_[0] &= ~0x00000004u;
 }
void SSL_DetectionBall::clear_has_x () private
void SSL_DetectionBall::clear_has_y () inline private
Definition at line 634 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by clear_y(), and SSL_DetectionRobot::clear_y().
{
   _has_bits_[0] &= ~0x00000008u;
 }
void SSL_DetectionBall::clear_has_y () private
void SSL_DetectionBall::clear_has_z () inline private
Definition at line 658 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by clear_z().
{
   _has_bits_[0] &= ~0x00000010u;
 }
void SSL_DetectionBall::clear_has_z () private
void SSL_DetectionBall::clear_pixel_x () inline
Definition at line 685 of file messages_robocup_ssl_detection.pb.h.
References clear_has_pixel_x(), and pixel_x_.
{
   pixel_x_ = 0;
   clear_has_pixel_x();
 }
void SSL_DetectionBall::clear_pixel_x ()
void SSL_DetectionBall::clear_pixel_y () inline
Definition at line 709 of file messages_robocup_ssl_detection.pb.h.
References clear_has_pixel_y(), and pixel_y_.
{
   pixel_y_ = 0;
   clear_has_pixel_y();
 }
void SSL_DetectionBall::clear_pixel_y ()
void SSL_DetectionBall::clear_x () inline
Definition at line 613 of file messages_robocup_ssl_detection.pb.h.
References clear_has_x(), and x_.
{
   x_ = 0;
   clear_has_x();
 }
void SSL_DetectionBall::clear_x ()
void SSL_DetectionBall::clear_y () inline
Definition at line 637 of file messages_robocup_ssl_detection.pb.h.
References clear_has_y(), and y_.
{
   y_ = 0;
   clear_has_y();
 }
void SSL_DetectionBall::clear_y ()
void SSL_DetectionBall::clear_z () inline
Definition at line 661 of file messages_robocup_ssl_detection.pb.h.
References clear_has_z(), and z_.
{
   z_ = 0;
   clear_has_z();
 }
void SSL_DetectionBall::clear_z ()
float SSL_DetectionBall::confidence () const inline
Definition at line 569 of file messages_robocup_ssl_detection.pb.h.
References confidence_.
Referenced by ViewUpdateThread::execute(), and main().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionBall.confidence)
   return confidence_;
 }
float SSL_DetectionBall::confidence () const
void SSL_DetectionBall::CopyFrom (const ::google::protobuf::Message & from)
Referenced by New(), SSL_DetectionRobot::New(), SSL_DetectionFrame::New(), operator=(), SSL_DetectionRobot::operator=(), and SSL_DetectionFrame::operator=().
void SSL_DetectionBall::CopyFrom (const SSL_DetectionBall & from)
void SSL_DetectionBall::CopyFrom (const ::google::protobuf::Message & from)
void SSL_DetectionBall::CopyFrom (const SSL_DetectionBall & from)
static const SSL_DetectionBall& SSL_DetectionBall::default_instance () static
Referenced by mutable_unknown_fields(), SSL_DetectionRobot::mutable_unknown_fields(), and SSL_DetectionFrame::mutable_unknown_fields().
static const SSL_DetectionBall& SSL_DetectionBall::default_instance () static
static const ::google::protobuf::Descriptor* SSL_DetectionBall::descriptor () static
Referenced by mutable_unknown_fields(), SSL_DetectionRobot::mutable_unknown_fields(), and SSL_DetectionFrame::mutable_unknown_fields().
static const ::google::protobuf::Descriptor* SSL_DetectionBall::descriptor () static
inline ::google::protobuf::Arena* SSL_DetectionBall::GetArenaNoVirtual () const inline private
Definition at line 107 of file messages_robocup_ssl_detection.pb.h.
Referenced by operator=().
{
     return NULL;
   }
inline ::google::protobuf::Arena* SSL_DetectionBall::GetArenaNoVirtual () const inline private
Definition at line 144 of file messages_robocup_ssl_detection.pb.h.
{
     return NULL;
   }
int SSL_DetectionBall::GetCachedSize () const inline
Definition at line 100 of file messages_robocup_ssl_detection.pb.h.
References _cached_size_, InternalSwap(), SetCachedSize(), SharedCtor(), and SharedDtor().
 { return _cached_size_; }
int SSL_DetectionBall::GetCachedSize () const inline
Definition at line 137 of file messages_robocup_ssl_detection.pb.h.
 { return _cached_size_; }
::google::protobuf::Metadata SSL_DetectionBall::GetMetadata () const
Referenced by MaybeArenaPtr(), SSL_DetectionRobot::MaybeArenaPtr(), and SSL_DetectionFrame::MaybeArenaPtr().
::google::protobuf::Metadata SSL_DetectionBall::GetMetadata () const
bool SSL_DetectionBall::has_area () const inline
Definition at line 580 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00000002u) != 0;
 }
bool SSL_DetectionBall::has_area () const
bool SSL_DetectionBall::has_confidence () const inline
Definition at line 556 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by MaybeArenaPtr(), and SSL_DetectionRobot::MaybeArenaPtr().
{
   return (_has_bits_[0] & 0x00000001u) != 0;
 }
bool SSL_DetectionBall::has_confidence () const
bool SSL_DetectionBall::has_pixel_x () const inline
Definition at line 676 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00000020u) != 0;
 }
bool SSL_DetectionBall::has_pixel_x () const
bool SSL_DetectionBall::has_pixel_y () const inline
Definition at line 700 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00000040u) != 0;
 }
bool SSL_DetectionBall::has_pixel_y () const
bool SSL_DetectionBall::has_x () const inline
Definition at line 604 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00000004u) != 0;
 }
bool SSL_DetectionBall::has_x () const
bool SSL_DetectionBall::has_y () const inline
Definition at line 628 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
{
   return (_has_bits_[0] & 0x00000008u) != 0;
 }
bool SSL_DetectionBall::has_y () const
bool SSL_DetectionBall::has_z () const inline
Definition at line 652 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by main().
{
   return (_has_bits_[0] & 0x00000010u) != 0;
 }
bool SSL_DetectionBall::has_z () const
static void SSL_DetectionBall::InitAsDefaultInstance () static
static const SSL_DetectionBall* SSL_DetectionBall::internal_default_instance () inline static
Definition at line 70 of file messages_robocup_ssl_detection.pb.h.
References _SSL_DetectionBall_default_instance_, and Swap().
{
     return reinterpret_cast<const SSL_DetectionBall*>(
                &_SSL_DetectionBall_default_instance_);
   }
static const SSL_DetectionBall* SSL_DetectionBall::internal_default_instance () inline static
Definition at line 106 of file messages_robocup_ssl_detection.pb.h.
References _SSL_DetectionBall_default_instance_.
{
     return reinterpret_cast<const SSL_DetectionBall*>(
                &_SSL_DetectionBall_default_instance_);
   }
::google::protobuf::uint8* SSL_DetectionBall::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
Referenced by New(), SSL_DetectionRobot::New(), SSL_DetectionFrame::New(), SerializeWithCachedSizesToArray(), SSL_DetectionRobot::SerializeWithCachedSizesToArray(), and SSL_DetectionFrame::SerializeWithCachedSizesToArray().
::google::protobuf::uint8* SSL_DetectionBall::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const
void SSL_DetectionBall::InternalSwap (SSL_DetectionBall * other) private
Referenced by GetCachedSize(), SSL_DetectionRobot::GetCachedSize(), and SSL_DetectionFrame::GetCachedSize().
void SSL_DetectionBall::InternalSwap (SSL_DetectionBall * other) private
bool SSL_DetectionBall::IsInitialized () const
Referenced by New(), SSL_DetectionRobot::New(), and SSL_DetectionFrame::New().
bool SSL_DetectionBall::IsInitialized () const
void* SSL_DetectionBall::MaybeArenaPtr () const inline private
Definition at line 110 of file messages_robocup_ssl_detection.pb.h.
References clear_confidence(), GetMetadata(), and has_confidence().
{
     return NULL;
   }
void* SSL_DetectionBall::MaybeArenaPtr () const inline private
Definition at line 147 of file messages_robocup_ssl_detection.pb.h.
References role._GoToPoint::x, and role._GoToPoint::y.
{
     return NULL;
   }
void SSL_DetectionBall::MergeFrom (const ::google::protobuf::Message & from)
Referenced by New(), SSL_DetectionRobot::New(), and SSL_DetectionFrame::New().
void SSL_DetectionBall::MergeFrom (const SSL_DetectionBall & from)
void SSL_DetectionBall::MergeFrom (const ::google::protobuf::Message & from)
void SSL_DetectionBall::MergeFrom (const SSL_DetectionBall & from)
bool SSL_DetectionBall::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Referenced by New(), SSL_DetectionRobot::New(), and SSL_DetectionFrame::New().
bool SSL_DetectionBall::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
inline ::google::protobuf::UnknownFieldSet* SSL_DetectionBall::mutable_unknown_fields () inline
Definition at line 63 of file messages_robocup_ssl_detection.pb.h.
References _internal_metadata_, default_instance(), and descriptor().
{
     return _internal_metadata_.mutable_unknown_fields();
   }
inline ::google::protobuf::UnknownFieldSet* SSL_DetectionBall::mutable_unknown_fields () inline
Definition at line 98 of file messages_robocup_ssl_detection.pb.h.
{
     return _internal_metadata_.mutable_unknown_fields();
   }
SSL_DetectionBall* SSL_DetectionBall::New () const inline
Definition at line 79 of file messages_robocup_ssl_detection.pb.h.
References ByteSizeLong(), Clear(), CopyFrom(), InternalSerializeWithCachedSizesToArray(), IsInitialized(), MergeFrom(), MergePartialFromCodedStream(), New(), SerializeWithCachedSizes(), and role._GoToPoint::target.
Referenced by New(), SSL_DetectionRobot::New(), and SSL_DetectionFrame::New().
 { return New(NULL); }
SSL_DetectionBall* SSL_DetectionBall::New (::google::protobuf::Arena * arena) const
SSL_DetectionBall* SSL_DetectionBall::New () const inline
Definition at line 120 of file messages_robocup_ssl_detection.pb.h.
References New(), and role._GoToPoint::target.
Referenced by New().
 { return New(NULL); }
SSL_DetectionBall* SSL_DetectionBall::New (::google::protobuf::Arena * arena) const
SSL_DetectionBall& SSL_DetectionBall::operator= (const SSL_DetectionBall & from) inline
Definition at line 54 of file messages_robocup_ssl_detection.pb.h.
References CopyFrom().
{
     CopyFrom(from);
     return *this;
   }
SSL_DetectionBall& SSL_DetectionBall::operator= (const SSL_DetectionBall & from) inline
Definition at line 76 of file messages_robocup_ssl_detection.pb.h.
References GetArenaNoVirtual().
{
     CopyFrom(from);
     return *this;
   }
float SSL_DetectionBall::pixel_x () const inline
Definition at line 689 of file messages_robocup_ssl_detection.pb.h.
References pixel_x_.
Referenced by main().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionBall.pixel_x)
   return pixel_x_;
 }
float SSL_DetectionBall::pixel_x () const
float SSL_DetectionBall::pixel_y () const inline
Definition at line 713 of file messages_robocup_ssl_detection.pb.h.
References pixel_y_.
Referenced by main().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionBall.pixel_y)
   return pixel_y_;
 }
float SSL_DetectionBall::pixel_y () const
friendconst ::google::protobuf::uint32* SSL_DetectionBall::protobuf_Offsets_messages_5frobocup_5fssl_5fdetection_2eproto () private
size_t SSL_DetectionBall::RequiredFieldsByteSizeFallback () const private
size_t SSL_DetectionBall::RequiredFieldsByteSizeFallback () const private
void SSL_DetectionBall::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Referenced by New(), SSL_DetectionRobot::New(), and SSL_DetectionFrame::New().
void SSL_DetectionBall::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
::google::protobuf::uint8* SSL_DetectionBall::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const inline
Definition at line 96 of file messages_robocup_ssl_detection.pb.h.
References InternalSerializeWithCachedSizesToArray().
{
     return InternalSerializeWithCachedSizesToArray(false, output);
   }
void SSL_DetectionBall::set_area (::google::protobuf::uint32 value) inline
Definition at line 597 of file messages_robocup_ssl_detection.pb.h.
References area_, and set_has_area().
Referenced by PluginDetectBalls::process().
{
   set_has_area();
   area_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionBall.area)
 }
void SSL_DetectionBall::set_area (::google::protobuf::uint32 value)
void SSL_DetectionBall::set_confidence (float value) inline
Definition at line 573 of file messages_robocup_ssl_detection.pb.h.
References confidence_, and set_has_confidence().
Referenced by SSLWorld::generatePacket(), and PluginDetectBalls::process().
{
   set_has_confidence();
   confidence_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionBall.confidence)
 }
void SSL_DetectionBall::set_confidence (float value)
void SSL_DetectionBall::set_has_area () inline private
Definition at line 583 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by set_area().
{
   _has_bits_[0] |= 0x00000002u;
 }
void SSL_DetectionBall::set_has_area () private
void SSL_DetectionBall::set_has_confidence () inline private
Definition at line 559 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by set_confidence(), and SSL_DetectionRobot::set_confidence().
{
   _has_bits_[0] |= 0x00000001u;
 }
void SSL_DetectionBall::set_has_confidence () private
void SSL_DetectionBall::set_has_pixel_x () inline private
Definition at line 679 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by set_pixel_x(), and SSL_DetectionRobot::set_pixel_x().
{
   _has_bits_[0] |= 0x00000020u;
 }
void SSL_DetectionBall::set_has_pixel_x () private
void SSL_DetectionBall::set_has_pixel_y () inline private
Definition at line 703 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by set_pixel_y(), and SSL_DetectionRobot::set_pixel_y().
{
   _has_bits_[0] |= 0x00000040u;
 }
void SSL_DetectionBall::set_has_pixel_y () private
void SSL_DetectionBall::set_has_x () inline private
Definition at line 607 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by set_x(), and SSL_DetectionRobot::set_x().
{
   _has_bits_[0] |= 0x00000004u;
 }
void SSL_DetectionBall::set_has_x () private
void SSL_DetectionBall::set_has_y () inline private
Definition at line 631 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by set_y(), and SSL_DetectionRobot::set_y().
{
   _has_bits_[0] |= 0x00000008u;
 }
void SSL_DetectionBall::set_has_y () private
void SSL_DetectionBall::set_has_z () inline private
Definition at line 655 of file messages_robocup_ssl_detection.pb.h.
References _has_bits_.
Referenced by set_z().
{
   _has_bits_[0] |= 0x00000010u;
 }
void SSL_DetectionBall::set_has_z () private
void SSL_DetectionBall::set_pixel_x (float value) inline
Definition at line 693 of file messages_robocup_ssl_detection.pb.h.
References pixel_x_, and set_has_pixel_x().
Referenced by SSLWorld::generatePacket(), and PluginDetectBalls::process().
{
   set_has_pixel_x();
   pixel_x_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionBall.pixel_x)
 }
void SSL_DetectionBall::set_pixel_x (float value)
void SSL_DetectionBall::set_pixel_y (float value) inline
Definition at line 717 of file messages_robocup_ssl_detection.pb.h.
References pixel_y_, and set_has_pixel_y().
Referenced by SSLWorld::generatePacket(), and PluginDetectBalls::process().
{
   set_has_pixel_y();
   pixel_y_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionBall.pixel_y)
 }
void SSL_DetectionBall::set_pixel_y (float value)
void SSL_DetectionBall::set_x (float value) inline
Definition at line 621 of file messages_robocup_ssl_detection.pb.h.
References set_has_x(), and x_.
Referenced by SSLWorld::generatePacket(), and PluginDetectBalls::process().
{
   set_has_x();
   x_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionBall.x)
 }
void SSL_DetectionBall::set_x (float value)
void SSL_DetectionBall::set_y (float value) inline
Definition at line 645 of file messages_robocup_ssl_detection.pb.h.
References set_has_y(), and y_.
Referenced by SSLWorld::generatePacket(), and PluginDetectBalls::process().
{
   set_has_y();
   y_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionBall.y)
 }
void SSL_DetectionBall::set_y (float value)
void SSL_DetectionBall::set_z (float value) inline
Definition at line 669 of file messages_robocup_ssl_detection.pb.h.
References set_has_z(), and z_.
Referenced by SSLWorld::generatePacket().
{
   set_has_z();
   z_ = value;
   // @@protoc_insertion_point(field_set:SSL_DetectionBall.z)
 }
void SSL_DetectionBall::set_z (float value)
void SSL_DetectionBall::SetCachedSize (int size) const private
Referenced by GetCachedSize(), SSL_DetectionRobot::GetCachedSize(), and SSL_DetectionFrame::GetCachedSize().
void SSL_DetectionBall::SetCachedSize (int size) const private
void SSL_DetectionBall::SharedCtor () private
Referenced by GetCachedSize(), SSL_DetectionRobot::GetCachedSize(), and SSL_DetectionFrame::GetCachedSize().
void SSL_DetectionBall::SharedCtor () private
void SSL_DetectionBall::SharedDtor () private
Referenced by GetCachedSize(), SSL_DetectionRobot::GetCachedSize(), and SSL_DetectionFrame::GetCachedSize().
void SSL_DetectionBall::SharedDtor () private
void SSL_DetectionBall::Swap (SSL_DetectionBall * other)
Referenced by internal_default_instance(), SSL_DetectionRobot::internal_default_instance(), and SSL_DetectionFrame::internal_default_instance().
void SSL_DetectionBall::Swap (SSL_DetectionBall * other)
const ::google::protobuf::UnknownFieldSet& SSL_DetectionBall::unknown_fields () const inline
Definition at line 59 of file messages_robocup_ssl_detection.pb.h.
References _internal_metadata_.
{
     return _internal_metadata_.unknown_fields();
   }
const ::google::protobuf::UnknownFieldSet& SSL_DetectionBall::unknown_fields () const inline
Definition at line 95 of file messages_robocup_ssl_detection.pb.h.
{
     return _internal_metadata_.unknown_fields();
   }
SSL_DetectionBall::void::protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::InitDefaultsSSL_DetectionBallImpl () private
float SSL_DetectionBall::x () const inline
Definition at line 617 of file messages_robocup_ssl_detection.pb.h.
References x_.
Referenced by ViewUpdateThread::execute(), main(), and GLSoccerView::updateDetection().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionBall.x)
   return x_;
 }
float SSL_DetectionBall::x () const
float SSL_DetectionBall::y () const inline
Definition at line 641 of file messages_robocup_ssl_detection.pb.h.
References y_.
Referenced by ViewUpdateThread::execute(), main(), and GLSoccerView::updateDetection().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionBall.y)
   return y_;
 }
float SSL_DetectionBall::y () const
float SSL_DetectionBall::z () const inline
Definition at line 665 of file messages_robocup_ssl_detection.pb.h.
References z_.
Referenced by main().
{
   // @@protoc_insertion_point(field_get:SSL_DetectionBall.z)
   return z_;
 }
float SSL_DetectionBall::z () const
Friends And Related Function Documentation
friend struct ::protobuf_messages_5frobocup_5fssl_5fdetection_2eproto::TableStruct friend
Definition at line 237 of file messages_robocup_ssl_detection.pb.h.
void protobuf_AddDesc_messages_5frobocup_5fssl_5fdetection_2eproto_impl () friend
void protobuf_InitDefaults_messages_5frobocup_5fssl_5fdetection_2eproto_impl () friend
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fdetection_2eproto () friend
void swap (SSL_DetectionBall & a, SSL_DetectionBall & b) friend
Definition at line 114 of file messages_robocup_ssl_detection.pb.h.
{
     a.Swap(&b);
   }
Field Documentation
int SSL_DetectionBall::_cached_size_ mutable private
Definition at line 192 of file messages_robocup_ssl_detection.pb.h.
Referenced by GetCachedSize(), SSL_DetectionRobot::GetCachedSize(), and SSL_DetectionFrame::GetCachedSize().
google::protobuf::internal::HasBits< 1 > SSL_DetectionBall::_has_bits_ private
Definition at line 191 of file messages_robocup_ssl_detection.pb.h.
Referenced by clear_has_area(), SSL_DetectionFrame::clear_has_camera_id(), clear_has_confidence(), SSL_DetectionRobot::clear_has_confidence(), SSL_DetectionFrame::clear_has_frame_number(), SSL_DetectionRobot::clear_has_height(), SSL_DetectionRobot::clear_has_orientation(), clear_has_pixel_x(), SSL_DetectionRobot::clear_has_pixel_x(), clear_has_pixel_y(), SSL_DetectionRobot::clear_has_pixel_y(), SSL_DetectionRobot::clear_has_robot_id(), SSL_DetectionFrame::clear_has_t_capture(), SSL_DetectionFrame::clear_has_t_sent(), clear_has_x(), SSL_DetectionRobot::clear_has_x(), clear_has_y(), SSL_DetectionRobot::clear_has_y(), clear_has_z(), has_area(), SSL_DetectionFrame::has_camera_id(), has_confidence(), SSL_DetectionRobot::has_confidence(), SSL_DetectionFrame::has_frame_number(), SSL_DetectionRobot::has_height(), SSL_DetectionRobot::has_orientation(), has_pixel_x(), SSL_DetectionRobot::has_pixel_x(), has_pixel_y(), SSL_DetectionRobot::has_pixel_y(), SSL_DetectionRobot::has_robot_id(), SSL_DetectionFrame::has_t_capture(), SSL_DetectionFrame::has_t_sent(), has_x(), SSL_DetectionRobot::has_x(), has_y(), SSL_DetectionRobot::has_y(), has_z(), set_has_area(), SSL_DetectionFrame::set_has_camera_id(), set_has_confidence(), SSL_DetectionRobot::set_has_confidence(), SSL_DetectionFrame::set_has_frame_number(), SSL_DetectionRobot::set_has_height(), SSL_DetectionRobot::set_has_orientation(), set_has_pixel_x(), SSL_DetectionRobot::set_has_pixel_x(), set_has_pixel_y(), SSL_DetectionRobot::set_has_pixel_y(), SSL_DetectionRobot::set_has_robot_id(), SSL_DetectionFrame::set_has_t_capture(), SSL_DetectionFrame::set_has_t_sent(), set_has_x(), SSL_DetectionRobot::set_has_x(), set_has_y(), SSL_DetectionRobot::set_has_y(), and set_has_z().
google::protobuf::internal::InternalMetadataWithArena SSL_DetectionBall::_internal_metadata_ private
Definition at line 190 of file messages_robocup_ssl_detection.pb.h.
Referenced by mutable_unknown_fields(), SSL_DetectionRobot::mutable_unknown_fields(), SSL_DetectionFrame::mutable_unknown_fields(), unknown_fields(), SSL_DetectionRobot::unknown_fields(), and SSL_DetectionFrame::unknown_fields().
google::protobuf::uint32 SSL_DetectionBall::area_ private
Definition at line 194 of file messages_robocup_ssl_detection.pb.h.
Referenced by area(), clear_area(), and set_area().
float SSL_DetectionBall::confidence_ private
Definition at line 193 of file messages_robocup_ssl_detection.pb.h.
Referenced by clear_confidence(), SSL_DetectionRobot::clear_confidence(), confidence(), SSL_DetectionRobot::confidence(), set_confidence(), and SSL_DetectionRobot::set_confidence().
static const int SSL_DetectionBall::kAreaFieldNumber = 2 static
Definition at line 131 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionBall::kConfidenceFieldNumber = 1 static
Definition at line 124 of file messages_robocup_ssl_detection.pb.h.
PROTOBUF_CONSTEXPR int const SSL_DetectionBall::kIndexInFileMessages static
Initial value:
=
    0
Definition at line 110 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionBall::kPixelXFieldNumber = 6 static
Definition at line 159 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionBall::kPixelYFieldNumber = 7 static
Definition at line 166 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionBall::kXFieldNumber = 3 static
Definition at line 138 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionBall::kYFieldNumber = 4 static
Definition at line 145 of file messages_robocup_ssl_detection.pb.h.
static const int SSL_DetectionBall::kZFieldNumber = 5 static
Definition at line 152 of file messages_robocup_ssl_detection.pb.h.
float SSL_DetectionBall::pixel_x_ private
Definition at line 198 of file messages_robocup_ssl_detection.pb.h.
Referenced by clear_pixel_x(), SSL_DetectionRobot::clear_pixel_x(), pixel_x(), SSL_DetectionRobot::pixel_x(), set_pixel_x(), and SSL_DetectionRobot::set_pixel_x().
float SSL_DetectionBall::pixel_y_ private
Definition at line 199 of file messages_robocup_ssl_detection.pb.h.
Referenced by clear_pixel_y(), SSL_DetectionRobot::clear_pixel_y(), pixel_y(), SSL_DetectionRobot::pixel_y(), set_pixel_y(), and SSL_DetectionRobot::set_pixel_y().
float SSL_DetectionBall::x_ private
Definition at line 195 of file messages_robocup_ssl_detection.pb.h.
Referenced by clear_x(), SSL_DetectionRobot::clear_x(), set_x(), SSL_DetectionRobot::set_x(), x(), and SSL_DetectionRobot::x().
float SSL_DetectionBall::y_ private
Definition at line 196 of file messages_robocup_ssl_detection.pb.h.
Referenced by clear_y(), SSL_DetectionRobot::clear_y(), set_y(), SSL_DetectionRobot::set_y(), y(), and SSL_DetectionRobot::y().
float SSL_DetectionBall::z_ private
Definition at line 197 of file messages_robocup_ssl_detection.pb.h.
Referenced by clear_z(), set_z(), and z().
The documentation for this class was generated from the following file:
grsim_comm/include/proto/messages_robocup_ssl_detection.pb.h