Documentation: LogControl Class Reference
LogControl Class Reference
#include <LogControl.h>
Public Slots
void log_forward ()
void log_backward ()
void log_play ()
void log_pause ()
void log_faster ()
void log_slower ()
void log_frame_forward ()
void log_frame_back ()
void goto_frame (int)
Signals
void update_speed (QString)
Public Member Functions
LogControl ()
~LogControl ()
void reset (int)
int get_current_frame ()
int get_next_frame ()
int get_prop_next_frame ()
double get_play_speed ()
Private Member Functions
void update_play_speed ()
Private Attributes
int current_frame
int next_frame
int log_length
double play_speed
double play_speed_save
Detailed Description
Definition at line 28 of file LogControl.h.
Constructor & Destructor Documentation
LogControl::LogControl ()
Definition at line 26 of file LogControl.cpp.
References reset().
 {
     reset(0);
 }
LogControl::~LogControl ()
Definition at line 31 of file LogControl.cpp.
 {
     ;
 }
Member Function Documentation
int LogControl::get_current_frame ()
Definition at line 46 of file LogControl.cpp.
References current_frame, and log_length.
Referenced by ViewUpdateThread::execute().
 {
     if(current_frame >= log_length)
         return 0;
     return current_frame;
 }
int LogControl::get_next_frame ()
Definition at line 55 of file LogControl.cpp.
References current_frame, log_length, next_frame, and play_speed.
Referenced by ViewUpdateThread::execute().
 {
     if(play_speed == 0.)
         return current_frame;
     current_frame = next_frame;
     if(play_speed < 0.)
         next_frame--;
     else
         next_frame++;
     if(current_frame >= log_length || current_frame < 0)
         return -1;
     return current_frame;
 }
double LogControl::get_play_speed ()
Definition at line 86 of file LogControl.cpp.
References play_speed.
Referenced by ViewUpdateThread::execute().
 {
     return play_speed;
 }
int LogControl::get_prop_next_frame ()
Definition at line 72 of file LogControl.cpp.
References current_frame, log_length, and play_speed.
Referenced by ViewUpdateThread::execute().
 {
     int prop_next_frame = current_frame;
     if(play_speed < 0.)
         prop_next_frame--;
     else if(play_speed > 0.)
         prop_next_frame++;
     if(prop_next_frame < 0 || prop_next_frame >= log_length)
         return -1;
     return prop_next_frame;
 }
void LogControl::goto_frame (int f) slot
Definition at line 142 of file LogControl.cpp.
References current_frame, and next_frame.
 {
     current_frame = f;
     next_frame = f+1;
 }
void LogControl::log_backward () slot
Definition at line 98 of file LogControl.cpp.
References play_speed, and update_play_speed().
 {
     play_speed = -5.;
     update_play_speed();
 }
void LogControl::log_faster () slot
Definition at line 120 of file LogControl.cpp.
References play_speed, and update_play_speed().
 {
     play_speed *= 2.;
     update_play_speed();
 }
void LogControl::log_forward () slot
Definition at line 92 of file LogControl.cpp.
References play_speed, and update_play_speed().
 {
     play_speed = 5.;
     update_play_speed();
 }
void LogControl::log_frame_back () slot
Definition at line 132 of file LogControl.cpp.
References current_frame.
 {
     current_frame--;
 }
void LogControl::log_frame_forward () slot
Definition at line 137 of file LogControl.cpp.
References current_frame.
 {
     current_frame++;
 }
void LogControl::log_pause () slot
Definition at line 113 of file LogControl.cpp.
References play_speed, play_speed_save, and update_play_speed().
 {
     play_speed_save = play_speed;
     play_speed = 0.;
     update_play_speed();
 }
void LogControl::log_play () slot
Definition at line 104 of file LogControl.cpp.
References play_speed, play_speed_save, and update_play_speed().
 {
     if(play_speed != 0.)
         play_speed = play_speed_save;
     else
         play_speed = 1.;
     update_play_speed();
 }
void LogControl::log_slower () slot
Definition at line 126 of file LogControl.cpp.
References play_speed, and update_play_speed().
 {
     play_speed /= 2.;
     update_play_speed();
 }
void LogControl::reset (int size)
Definition at line 36 of file LogControl.cpp.
References current_frame, log_length, next_frame, play_speed, play_speed_save, and update_play_speed().
Referenced by ViewUpdateThread::end_play_record(), LogControl(), and ViewUpdateThread::start_play_record().
 {
     current_frame = 0;
     next_frame = 0;
     log_length = size;
     play_speed = 1.;
     play_speed_save = 1.;
     update_play_speed();
 }
void LogControl::update_play_speed () private
Definition at line 148 of file LogControl.cpp.
References play_speed, and update_speed().
Referenced by log_backward(), log_faster(), log_forward(), log_pause(), log_play(), log_slower(), and reset().
 {
     double speed_tmp = floor(play_speed * 100.0 + 0.5) / 100.0;
     std::ostringstream o;
     o << speed_tmp;
     QString speed = QString::number(play_speed, 'g', 4);
     speed.append("x");
     emit update_speed(speed);
 }
void LogControl::update_speed (QString _t1) signal
Definition at line 118 of file moc_LogControl.cxx.
Referenced by update_play_speed().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 0, _a);
 }
Field Documentation
int LogControl::current_frame private
Definition at line 57 of file LogControl.h.
Referenced by get_current_frame(), get_next_frame(), get_prop_next_frame(), goto_frame(), log_frame_back(), log_frame_forward(), and reset().
int LogControl::log_length private
Definition at line 59 of file LogControl.h.
Referenced by get_current_frame(), get_next_frame(), get_prop_next_frame(), and reset().
int LogControl::next_frame private
Definition at line 58 of file LogControl.h.
Referenced by get_next_frame(), goto_frame(), and reset().
double LogControl::play_speed private
Definition at line 60 of file LogControl.h.
Referenced by get_next_frame(), get_play_speed(), get_prop_next_frame(), log_backward(), log_faster(), log_forward(), log_pause(), log_play(), log_slower(), reset(), and update_play_speed().
double LogControl::play_speed_save private
Definition at line 61 of file LogControl.h.
Referenced by log_pause(), log_play(), and reset().
The documentation for this class was generated from the following files:
ssl-vision/src/logClient/LogControl.h
ssl-vision/build/src/logClient/moc_LogControl.cxx
ssl-vision/src/logClient/LogControl.cpp