Documentation: Protobuf.GrSimCommands.grSim_Robot_Command.Builder Class Reference
Protobuf.GrSimCommands.grSim_Robot_Command.Builder Class Reference
Public Member Functions
Builder clear ()
Builder clone ()
com.google.protobuf.Descriptors.Descriptor getDescriptorForType ()
GrSimCommands.grSim_Robot_Command getDefaultInstanceForType ()
GrSimCommands.grSim_Robot_Command build ()
GrSimCommands.grSim_Robot_Command buildPartial ()
Builder mergeFrom (com.google.protobuf.Message other)
Builder mergeFrom (GrSimCommands.grSim_Robot_Command other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasId ()
int getId ()
Builder setId (int value)
Builder clearId ()
boolean hasKickspeedx ()
float getKickspeedx ()
Builder setKickspeedx (float value)
Builder clearKickspeedx ()
boolean hasKickspeedz ()
float getKickspeedz ()
Builder setKickspeedz (float value)
Builder clearKickspeedz ()
boolean hasVeltangent ()
float getVeltangent ()
Builder setVeltangent (float value)
Builder clearVeltangent ()
boolean hasVelnormal ()
float getVelnormal ()
Builder setVelnormal (float value)
Builder clearVelnormal ()
boolean hasVelangular ()
float getVelangular ()
Builder setVelangular (float value)
Builder clearVelangular ()
boolean hasSpinner ()
boolean getSpinner ()
Builder setSpinner (boolean value)
Builder clearSpinner ()
boolean hasWheelsspeed ()
boolean getWheelsspeed ()
Builder setWheelsspeed (boolean value)
Builder clearWheelsspeed ()
boolean hasWheel1 ()
float getWheel1 ()
Builder setWheel1 (float value)
Builder clearWheel1 ()
boolean hasWheel2 ()
float getWheel2 ()
Builder setWheel2 (float value)
Builder clearWheel2 ()
boolean hasWheel3 ()
float getWheel3 ()
Builder setWheel3 (float value)
Builder clearWheel3 ()
boolean hasWheel4 ()
float getWheel4 ()
Builder setWheel4 (float value)
Builder clearWheel4 ()
Static Public Member Functions
static final com.google.protobuf.Descriptors.Descriptor getDescriptor ()
Protected Member Functions
com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable ()
Private Member Functions
Builder ()
Builder (BuilderParent parent)
void maybeForceBuilderInitialization ()
GrSimCommands.grSim_Robot_Command buildParsed () throws com.google.protobuf.InvalidProtocolBufferException
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
int id_
float kickspeedx_
float kickspeedz_
float veltangent_
float velnormal_
float velangular_
boolean spinner_
boolean wheelsspeed_
float wheel1_
float wheel2_
float wheel3_
float wheel4_
Detailed Description
Definition at line 453 of file GrSimCommands.java.
Constructor & Destructor Documentation
Protobuf.GrSimCommands.grSim_Robot_Command.Builder.Builder () inline private
Definition at line 467 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.Builder.mergeFrom().
{
         maybeForceBuilderInitialization();
       }
Protobuf.GrSimCommands.grSim_Robot_Command.Builder.Builder (BuilderParent parent) inline private
Definition at line 471 of file GrSimCommands.java.
{
         super(parent);
         maybeForceBuilderInitialization();
       }
Member Function Documentation
GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.Builder.build () inline
Definition at line 525 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         GrSimCommands.grSim_Robot_Command result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.Builder.buildParsed () throws com.google.protobuf.InvalidProtocolBufferException inline private
Definition at line 533 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.parseDelimitedFrom().
{
         GrSimCommands.grSim_Robot_Command result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(
             result).asInvalidProtocolBufferException();
         }
         return result;
       }
GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.Builder.buildPartial () inline
Definition at line 543 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.id_.
{
         GrSimCommands.grSim_Robot_Command result = new GrSimCommands.grSim_Robot_Command(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
           to_bitField0_ |= 0x00000001;
         }
         result.id_ = id_;
         if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
           to_bitField0_ |= 0x00000002;
         }
         result.kickspeedx_ = kickspeedx_;
         if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
           to_bitField0_ |= 0x00000004;
         }
         result.kickspeedz_ = kickspeedz_;
         if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
           to_bitField0_ |= 0x00000008;
         }
         result.veltangent_ = veltangent_;
         if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
           to_bitField0_ |= 0x00000010;
         }
         result.velnormal_ = velnormal_;
         if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
           to_bitField0_ |= 0x00000020;
         }
         result.velangular_ = velangular_;
         if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
           to_bitField0_ |= 0x00000040;
         }
         result.spinner_ = spinner_;
         if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
           to_bitField0_ |= 0x00000080;
         }
         result.wheelsspeed_ = wheelsspeed_;
         if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
           to_bitField0_ |= 0x00000100;
         }
         result.wheel1_ = wheel1_;
         if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
           to_bitField0_ |= 0x00000200;
         }
         result.wheel2_ = wheel2_;
         if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
           to_bitField0_ |= 0x00000400;
         }
         result.wheel3_ = wheel3_;
         if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
           to_bitField0_ |= 0x00000800;
         }
         result.wheel4_ = wheel4_;
         result.bitField0_ = to_bitField0_;
         onBuilt();
         return result;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clear () inline
Definition at line 483 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clear().
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clear().
{
         super.clear();
         id_ = 0;
         bitField0_ = (bitField0_ & ~0x00000001);
         kickspeedx_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000002);
         kickspeedz_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000004);
         veltangent_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000008);
         velnormal_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000010);
         velangular_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000020);
         spinner_ = false;
         bitField0_ = (bitField0_ & ~0x00000040);
         wheelsspeed_ = false;
         bitField0_ = (bitField0_ & ~0x00000080);
         wheel1_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000100);
         wheel2_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000200);
         wheel3_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000400);
         wheel4_ = 0F;
         bitField0_ = (bitField0_ & ~0x00000800);
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clearId () inline
Definition at line 790 of file GrSimCommands.java.
{
         bitField0_ = (bitField0_ & ~0x00000001);
         id_ = 0;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clearKickspeedx () inline
Definition at line 811 of file GrSimCommands.java.
{
         bitField0_ = (bitField0_ & ~0x00000002);
         kickspeedx_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clearKickspeedz () inline
Definition at line 832 of file GrSimCommands.java.
{
         bitField0_ = (bitField0_ & ~0x00000004);
         kickspeedz_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clearSpinner () inline
Definition at line 916 of file GrSimCommands.java.
{
         bitField0_ = (bitField0_ & ~0x00000040);
         spinner_ = false;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clearVelangular () inline
Definition at line 895 of file GrSimCommands.java.
{
         bitField0_ = (bitField0_ & ~0x00000020);
         velangular_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clearVelnormal () inline
Definition at line 874 of file GrSimCommands.java.
{
         bitField0_ = (bitField0_ & ~0x00000010);
         velnormal_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clearVeltangent () inline
Definition at line 853 of file GrSimCommands.java.
{
         bitField0_ = (bitField0_ & ~0x00000008);
         veltangent_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clearWheel1 () inline
Definition at line 958 of file GrSimCommands.java.
{
         bitField0_ = (bitField0_ & ~0x00000100);
         wheel1_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clearWheel2 () inline
Definition at line 979 of file GrSimCommands.java.
{
         bitField0_ = (bitField0_ & ~0x00000200);
         wheel2_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clearWheel3 () inline
Definition at line 1000 of file GrSimCommands.java.
{
         bitField0_ = (bitField0_ & ~0x00000400);
         wheel3_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clearWheel4 () inline
Definition at line 1021 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.initFields().
{
         bitField0_ = (bitField0_ & ~0x00000800);
         wheel4_ = 0F;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clearWheelsspeed () inline
Definition at line 937 of file GrSimCommands.java.
{
         bitField0_ = (bitField0_ & ~0x00000080);
         wheelsspeed_ = false;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clone () inline
Definition at line 512 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
static Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.create () inline static private
Definition at line 479 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.newBuilder().
{
         return new Builder();
       }
GrSimCommands.grSim_Robot_Command Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getDefaultInstanceForType () inline
Definition at line 521 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.getDefaultInstance().
{
         return GrSimCommands.grSim_Robot_Command.getDefaultInstance();
       }
static final com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getDescriptor () inline static
Definition at line 457 of file GrSimCommands.java.
References Protobuf.GrSimCommands.internal_static_grSim_Robot_Command_descriptor.
{
         return GrSimCommands.internal_static_grSim_Robot_Command_descriptor;
       }
com.google.protobuf.Descriptors.Descriptor Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getDescriptorForType () inline
Definition at line 517 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.getDescriptor().
{
         return GrSimCommands.grSim_Robot_Command.getDescriptor();
       }
int Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getId () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 781 of file GrSimCommands.java.
{
         return id_;
       }
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getKickspeedx () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 802 of file GrSimCommands.java.
{
         return kickspeedx_;
       }
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getKickspeedz () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 823 of file GrSimCommands.java.
{
         return kickspeedz_;
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getSpinner () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 907 of file GrSimCommands.java.
{
         return spinner_;
       }
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getVelangular () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 886 of file GrSimCommands.java.
{
         return velangular_;
       }
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getVelnormal () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 865 of file GrSimCommands.java.
{
         return velnormal_;
       }
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getVeltangent () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 844 of file GrSimCommands.java.
{
         return veltangent_;
       }
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getWheel1 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 949 of file GrSimCommands.java.
{
         return wheel1_;
       }
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getWheel2 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 970 of file GrSimCommands.java.
{
         return wheel2_;
       }
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getWheel3 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 991 of file GrSimCommands.java.
{
         return wheel3_;
       }
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getWheel4 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 1012 of file GrSimCommands.java.
{
         return wheel4_;
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.getWheelsspeed () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 928 of file GrSimCommands.java.
{
         return wheelsspeed_;
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.hasId () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 778 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.hasKickspeedx () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 799 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000002) == 0x00000002);
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.hasKickspeedz () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 820 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000004) == 0x00000004);
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.hasSpinner () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 904 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000040) == 0x00000040);
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.hasVelangular () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 883 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000020) == 0x00000020);
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.hasVelnormal () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 862 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000010) == 0x00000010);
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.hasVeltangent () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 841 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000008) == 0x00000008);
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.hasWheel1 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 946 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000100) == 0x00000100);
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.hasWheel2 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 967 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000200) == 0x00000200);
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.hasWheel3 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 988 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000400) == 0x00000400);
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.hasWheel4 () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 1009 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000800) == 0x00000800);
       }
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.hasWheelsspeed () inline
Implements Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.
Definition at line 925 of file GrSimCommands.java.
{
         return ((bitField0_ & 0x00000080) == 0x00000080);
       }
com.google.protobuf.GeneratedMessage.FieldAccessorTable Protobuf.GrSimCommands.grSim_Robot_Command.Builder.internalGetFieldAccessorTable () inline protected
Definition at line 462 of file GrSimCommands.java.
References Protobuf.GrSimCommands.internal_static_grSim_Robot_Command_fieldAccessorTable.
{
         return GrSimCommands.internal_static_grSim_Robot_Command_fieldAccessorTable;
       }
final boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.isInitialized () inline
Definition at line 651 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasId(), Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasKickspeedx(), Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasKickspeedz(), Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasSpinner(), Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasVelangular(), Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasVelnormal(), Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasVeltangent(), and Protobuf.GrSimCommands.grSim_Robot_CommandOrBuilder.hasWheelsspeed().
{
         if (!hasId()) {
           return false;
         }
         if (!hasKickspeedx()) {
           return false;
         }
         if (!hasKickspeedz()) {
           return false;
         }
         if (!hasVeltangent()) {
           return false;
         }
         if (!hasVelnormal()) {
           return false;
         }
         if (!hasVelangular()) {
           return false;
         }
         if (!hasSpinner()) {
           return false;
         }
         if (!hasWheelsspeed()) {
           return false;
         }
         return true;
       }
void Protobuf.GrSimCommands.grSim_Robot_Command.Builder.maybeForceBuilderInitialization () inline private
Definition at line 475 of file GrSimCommands.java.
{
         if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
         }
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.mergeFrom (com.google.protobuf.Message other) inline
Definition at line 600 of file GrSimCommands.java.
Referenced by Protobuf.GrSimCommands.grSim_Robot_Command.Builder.clone(), and Protobuf.GrSimCommands.grSim_Robot_Command.newBuilder().
{
         if (other instanceof GrSimCommands.grSim_Robot_Command) {
           return mergeFrom((GrSimCommands.grSim_Robot_Command)other);
         } else {
           super.mergeFrom(other);
           return this;
         }
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.mergeFrom (GrSimCommands.grSim_Robot_Command other) inline
Definition at line 609 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.getDefaultInstance().
{
         if (other == GrSimCommands.grSim_Robot_Command.getDefaultInstance()) return this;
         if (other.hasId()) {
           setId(other.getId());
         }
         if (other.hasKickspeedx()) {
           setKickspeedx(other.getKickspeedx());
         }
         if (other.hasKickspeedz()) {
           setKickspeedz(other.getKickspeedz());
         }
         if (other.hasVeltangent()) {
           setVeltangent(other.getVeltangent());
         }
         if (other.hasVelnormal()) {
           setVelnormal(other.getVelnormal());
         }
         if (other.hasVelangular()) {
           setVelangular(other.getVelangular());
         }
         if (other.hasSpinner()) {
           setSpinner(other.getSpinner());
         }
         if (other.hasWheelsspeed()) {
           setWheelsspeed(other.getWheelsspeed());
         }
         if (other.hasWheel1()) {
           setWheel1(other.getWheel1());
         }
         if (other.hasWheel2()) {
           setWheel2(other.getWheel2());
         }
         if (other.hasWheel3()) {
           setWheel3(other.getWheel3());
         }
         if (other.hasWheel4()) {
           setWheel4(other.getWheel4());
         }
         this.mergeUnknownFields(other.getUnknownFields());
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline
Definition at line 687 of file GrSimCommands.java.
References Protobuf.GrSimCommands.grSim_Robot_Command.Builder.Builder().
{
         com.google.protobuf.UnknownFieldSet.Builder unknownFields =
           com.google.protobuf.UnknownFieldSet.newBuilder(
             this.getUnknownFields());
         while (true) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               this.setUnknownFields(unknownFields.build());
               onChanged();
               return this;
             default: {
               if (!parseUnknownField(input, unknownFields,
                                      extensionRegistry, tag)) {
                 this.setUnknownFields(unknownFields.build());
                 onChanged();
                 return this;
               }
               break;
             }
             case 8: {
               bitField0_ |= 0x00000001;
               id_ = input.readUInt32();
               break;
             }
             case 21: {
               bitField0_ |= 0x00000002;
               kickspeedx_ = input.readFloat();
               break;
             }
             case 29: {
               bitField0_ |= 0x00000004;
               kickspeedz_ = input.readFloat();
               break;
             }
             case 37: {
               bitField0_ |= 0x00000008;
               veltangent_ = input.readFloat();
               break;
             }
             case 45: {
               bitField0_ |= 0x00000010;
               velnormal_ = input.readFloat();
               break;
             }
             case 53: {
               bitField0_ |= 0x00000020;
               velangular_ = input.readFloat();
               break;
             }
             case 56: {
               bitField0_ |= 0x00000040;
               spinner_ = input.readBool();
               break;
             }
             case 64: {
               bitField0_ |= 0x00000080;
               wheelsspeed_ = input.readBool();
               break;
             }
             case 77: {
               bitField0_ |= 0x00000100;
               wheel1_ = input.readFloat();
               break;
             }
             case 85: {
               bitField0_ |= 0x00000200;
               wheel2_ = input.readFloat();
               break;
             }
             case 93: {
               bitField0_ |= 0x00000400;
               wheel3_ = input.readFloat();
               break;
             }
             case 101: {
               bitField0_ |= 0x00000800;
               wheel4_ = input.readFloat();
               break;
             }
           }
         }
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setId (int value) inline
Definition at line 784 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000001;
         id_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setKickspeedx (float value) inline
Definition at line 805 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000002;
         kickspeedx_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setKickspeedz (float value) inline
Definition at line 826 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000004;
         kickspeedz_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setSpinner (boolean value) inline
Definition at line 910 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000040;
         spinner_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setVelangular (float value) inline
Definition at line 889 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000020;
         velangular_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setVelnormal (float value) inline
Definition at line 868 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000010;
         velnormal_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setVeltangent (float value) inline
Definition at line 847 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000008;
         veltangent_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setWheel1 (float value) inline
Definition at line 952 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000100;
         wheel1_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setWheel2 (float value) inline
Definition at line 973 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000200;
         wheel2_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setWheel3 (float value) inline
Definition at line 994 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000400;
         wheel3_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setWheel4 (float value) inline
Definition at line 1015 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000800;
         wheel4_ = value;
         onChanged();
         return this;
       }
Builder Protobuf.GrSimCommands.grSim_Robot_Command.Builder.setWheelsspeed (boolean value) inline
Definition at line 931 of file GrSimCommands.java.
Referenced by Client.Conection.send().
{
         bitField0_ |= 0x00000080;
         wheelsspeed_ = value;
         onChanged();
         return this;
       }
Field Documentation
int Protobuf.GrSimCommands.grSim_Robot_Command.Builder.bitField0_ private
Definition at line 774 of file GrSimCommands.java.
int Protobuf.GrSimCommands.grSim_Robot_Command.Builder.id_ private
Definition at line 777 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.kickspeedx_ private
Definition at line 798 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.kickspeedz_ private
Definition at line 819 of file GrSimCommands.java.
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.spinner_ private
Definition at line 903 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.velangular_ private
Definition at line 882 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.velnormal_ private
Definition at line 861 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.veltangent_ private
Definition at line 840 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.wheel1_ private
Definition at line 945 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.wheel2_ private
Definition at line 966 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.wheel3_ private
Definition at line 987 of file GrSimCommands.java.
float Protobuf.GrSimCommands.grSim_Robot_Command.Builder.wheel4_ private
Definition at line 1008 of file GrSimCommands.java.
boolean Protobuf.GrSimCommands.grSim_Robot_Command.Builder.wheelsspeed_ private
Definition at line 924 of file GrSimCommands.java.
The documentation for this class was generated from the following file:
grSim/clients/java/src/Protobuf/GrSimCommands.java