Documentation: GUI.InterfacePath_ompl.Ui_MainWindow Class Reference
GUI.InterfacePath_ompl.Ui_MainWindow Class Reference
Public Member Functions
def setupUi (self, MainWindow)
def retranslateUi (self, MainWindow)
Data Fields
centralwidget
graphicsView
stepSizeText
stepSize
maxIterationsText
biasParamText
maxIterations
biasParam
sendData
refresh
startPoint
endPoint
startPointText
endPointText
updatePath
menubar
menuDIFFERENT_RRT
statusbar
actionRRT_CONNECT
actionRRT_X
Detailed Description
Definition at line 26 of file InterfacePath_ompl.py.
Member Function Documentation
def GUI.InterfacePath_ompl.Ui_MainWindow.retranslateUi (self, MainWindow)
Definition at line 102 of file InterfacePath_ompl.py.
References GUI.InterfacePath_ompl._translate().
     def retranslateUi(self, MainWindow):
         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
         self.stepSize.setText(_translate("MainWindow", "StepSize", None))
         self.maxIterations.setText(_translate("MainWindow", "Planner No", None))
         self.biasParam.setText(_translate("MainWindow", "BiasParam", None))
         self.sendData.setText(_translate("MainWindow", "sendData", None))
         self.refresh.setText(_translate("MainWindow", "refresh", None))
         self.startPoint.setText(_translate("MainWindow", "choosen start point", None))
         self.endPoint.setText(_translate("MainWindow", "choosen end point", None))
         self.updatePath.setText(_translate("MainWindow", "updatePath", None))
         self.menuDIFFERENT_RRT.setTitle(_translate("MainWindow", "DIFFERENT_RRT", None))
         self.actionRRT_CONNECT.setText(_translate("MainWindow", "RRT_CONNECT", None))
         self.actionRRT_X.setText(_translate("MainWindow", "RRT_X", None))
def GUI.InterfacePath_ompl.Ui_MainWindow.setupUi (self, MainWindow)
Definition at line 27 of file InterfacePath_ompl.py.
References GUI.InterfacePath_ompl._fromUtf8.
Referenced by GUI.self_RRT.MainWindow.__init__(), and GUI.ompl_gui.MainWindow.__init__().
     def setupUi(self, MainWindow):
         MainWindow.setObjectName(_fromUtf8("MainWindow"))
         MainWindow.resize(1140, 670)
         self.centralwidget = QtGui.QWidget(MainWindow)
         self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
         self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
         self.graphicsView.setGeometry(QtCore.QRect(0, 0, 650, 410))
         self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
         self.stepSizeText = QtGui.QLineEdit(self.centralwidget)
         self.stepSizeText.setGeometry(QtCore.QRect(990, 40, 91, 27))
         self.stepSizeText.setObjectName(_fromUtf8("stepSizeText"))
         self.stepSize = QtGui.QLabel(self.centralwidget)
         self.stepSize.setGeometry(QtCore.QRect(810, 50, 66, 17))
         self.stepSize.setObjectName(_fromUtf8("stepSize"))
         self.maxIterationsText = QtGui.QLineEdit(self.centralwidget)
         self.maxIterationsText.setGeometry(QtCore.QRect(900, 80, 81, 27))
         self.maxIterationsText.setObjectName(_fromUtf8("maxIterationsText"))
         self.biasParamText = QtGui.QLineEdit(self.centralwidget)
         self.biasParamText.setGeometry(QtCore.QRect(890, 130, 81, 27))
         self.biasParamText.setObjectName(_fromUtf8("biasParamText"))
         self.maxIterations = QtGui.QLabel(self.centralwidget)
         self.maxIterations.setGeometry(QtCore.QRect(790, 90, 91, 20))
         self.maxIterations.setObjectName(_fromUtf8("maxIterations"))
         self.biasParam = QtGui.QLabel(self.centralwidget)
         self.biasParam.setGeometry(QtCore.QRect(800, 130, 71, 20))
         self.biasParam.setObjectName(_fromUtf8("biasParam"))
         self.sendData = QtGui.QPushButton(self.centralwidget)
         self.sendData.setGeometry(QtCore.QRect(880, 210, 98, 27))
         self.sendData.setObjectName(_fromUtf8("sendData"))
         self.refresh = QtGui.QPushButton(self.centralwidget)
         self.refresh.setGeometry(QtCore.QRect(680, 420, 98, 27))
         self.refresh.setObjectName(_fromUtf8("refresh"))
         self.startPoint = QtGui.QPushButton(self.centralwidget)
         self.startPoint.setGeometry(QtCore.QRect(70, 480, 181, 27))
         self.startPoint.setObjectName(_fromUtf8("startPoint"))
         self.endPoint = QtGui.QPushButton(self.centralwidget)
         self.endPoint.setGeometry(QtCore.QRect(280, 480, 211, 27))
         self.endPoint.setObjectName(_fromUtf8("endPoint"))
         self.startPointText = QtGui.QLineEdit(self.centralwidget)
         self.startPointText.setGeometry(QtCore.QRect(90, 520, 113, 27))
         self.startPointText.setObjectName(_fromUtf8("startPointText"))
         self.endPointText = QtGui.QLineEdit(self.centralwidget)
         self.endPointText.setGeometry(QtCore.QRect(320, 520, 113, 27))
         self.endPointText.setObjectName(_fromUtf8("endPointText"))
         self.updatePath = QtGui.QPushButton(self.centralwidget)
         self.updatePath.setGeometry(QtCore.QRect(680, 310, 98, 27))
         self.updatePath.setObjectName(_fromUtf8("updatePath"))
         MainWindow.setCentralWidget(self.centralwidget)
         self.menubar = QtGui.QMenuBar(MainWindow)
         self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 25))
         self.menubar.setNativeMenuBar(False)
         self.menubar.setObjectName(_fromUtf8("menubar"))
         self.menuDIFFERENT_RRT = QtGui.QMenu(self.menubar)
         self.menuDIFFERENT_RRT.setObjectName(_fromUtf8("menuDIFFERENT_RRT"))
         MainWindow.setMenuBar(self.menubar)
         self.statusbar = QtGui.QStatusBar(MainWindow)
         self.statusbar.setObjectName(_fromUtf8("statusbar"))
         MainWindow.setStatusBar(self.statusbar)
         self.actionRRT_CONNECT = QtGui.QAction(MainWindow)
         self.actionRRT_CONNECT.setObjectName(_fromUtf8("actionRRT_CONNECT"))
         self.actionRRT_X = QtGui.QAction(MainWindow)
         self.actionRRT_X.setObjectName(_fromUtf8("actionRRT_X"))
         self.menuDIFFERENT_RRT.addAction(self.actionRRT_CONNECT)
         self.menuDIFFERENT_RRT.addAction(self.actionRRT_X)
         self.menubar.addAction(self.menuDIFFERENT_RRT.menuAction())
         self.retranslateUi(MainWindow)
         QtCore.QObject.connect(self.actionRRT_CONNECT, QtCore.SIGNAL(_fromUtf8("triggered()")), self.biasParam.show)
         QtCore.QObject.connect(self.actionRRT_CONNECT, QtCore.SIGNAL(_fromUtf8("triggered()")), self.biasParamText.show)
         QtCore.QObject.connect(self.actionRRT_CONNECT, QtCore.SIGNAL(_fromUtf8("triggered()")), self.maxIterations.show)
         QtCore.QObject.connect(self.actionRRT_CONNECT, QtCore.SIGNAL(_fromUtf8("triggered()")), self.maxIterationsText.show)
         QtCore.QObject.connect(self.actionRRT_CONNECT, QtCore.SIGNAL(_fromUtf8("triggered()")), self.stepSize.show)
         QtCore.QObject.connect(self.actionRRT_CONNECT, QtCore.SIGNAL(_fromUtf8("triggered()")), self.stepSizeText.show)
         QtCore.QMetaObject.connectSlotsByName(MainWindow)
Field Documentation
GUI.InterfacePath_ompl.Ui_MainWindow.actionRRT_CONNECT
Definition at line 85 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.actionRRT_X
Definition at line 87 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.biasParam
Definition at line 50 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.biasParamText
Definition at line 44 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.centralwidget
Definition at line 30 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.endPoint
Definition at line 62 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.endPointText
Definition at line 68 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.graphicsView
Definition at line 32 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.maxIterations
Definition at line 47 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.maxIterationsText
Definition at line 41 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.menubar
Definition at line 75 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.menuDIFFERENT_RRT
Definition at line 79 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.refresh
Definition at line 56 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.sendData
Definition at line 53 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.startPoint
Definition at line 59 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.startPointText
Definition at line 65 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.statusbar
Definition at line 82 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.stepSize
Definition at line 38 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.stepSizeText
Definition at line 35 of file InterfacePath_ompl.py.
GUI.InterfacePath_ompl.Ui_MainWindow.updatePath
Definition at line 71 of file InterfacePath_ompl.py.
The documentation for this class was generated from the following file:
GUI/InterfacePath_ompl.py